{
  "abstract": [
    {
      "text": "Creates a padding layer with the zero padding sizes you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithZeroPadding:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCPaddingLayer(cm)layerWithZeroPadding:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "layerWithZeroPadding:"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "layerWithZeroPadding:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "layerWithZeroPadding:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "layerWithZeroPadding:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSNumber *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "padding"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array that contains the zero padding sizes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "padding"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A zero padding layer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer": {
      "abstract": [
        {
          "text": "A layer that pads a tensor with the padding sizes you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPaddingLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddinglayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithConstantPadding:constantValue:": {
      "abstract": [
        {
          "text": "Creates a padding layer with the constant padding sizes and constant valu you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layerWithConstantPadding:constantValue:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithConstantPadding:constantValue:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithConstantPadding:constantValue:"
        }
      ],
      "role": "symbol",
      "title": "layerWithConstantPadding:constantValue:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddinglayer/layerwithconstantpadding:constantvalue:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithReflectionPadding:": {
      "abstract": [
        {
          "text": "Creates a padding layer with the reflection padding sizes you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layerWithReflectionPadding:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithReflectionPadding:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithReflectionPadding:"
        }
      ],
      "role": "symbol",
      "title": "layerWithReflectionPadding:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddinglayer/layerwithreflectionpadding:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithSymmetricPadding:": {
      "abstract": [
        {
          "text": "Creates a padding layer with the symmetric padding sizes you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layerWithSymmetricPadding:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithSymmetricPadding:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithSymmetricPadding:"
        }
      ],
      "role": "symbol",
      "title": "layerWithSymmetricPadding:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddinglayer/layerwithsymmetricpadding:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithZeroPadding:": {
      "abstract": [
        {
          "text": "Creates a padding layer with the zero padding sizes you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layerWithZeroPadding:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithZeroPadding:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithZeroPadding:"
        }
      ],
      "role": "symbol",
      "title": "layerWithZeroPadding:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddinglayer/layerwithzeropadding:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Padding-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithReflectionPadding:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithSymmetricPadding:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer/layerWithConstantPadding:constantValue:"
      ],
      "title": "Creating Padding Layers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingLayer/title",
          "value": "MLCPaddingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcpaddinglayer/layerwithzeropadding:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
