{
  "abstract": [
    {
      "text": "The table will use the system default layout size: small, medium or large.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTableViewRowSizeStyle@NSTableViewRowSizeStyleDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTableViewRowSizeStyleDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTableView.RowSizeStyle.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableCellView": {
      "abstract": [
        {
          "text": "A reusable container view shown for a particular cell in a table view that uses rows for content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableCellView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableCellView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableCellView"
        }
      ],
      "role": "symbol",
      "title": "NSTableCellView",
      "type": "topic",
      "url": "/documentation/appkit/nstablecellview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableCellView/rowSizeStyle": {
      "abstract": [
        {
          "text": "Returns the row size style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowSizeStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewRowSizeStyle",
          "text": "RowSizeStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableCellView/rowSizeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowSizeStyle"
        }
      ],
      "role": "symbol",
      "title": "rowSizeStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstablecellview/rowsizestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView": {
      "abstract": [
        {
          "text": "A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "role": "symbol",
      "title": "NSTableView",
      "type": "topic",
      "url": "/documentation/appkit/nstableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum": {
      "abstract": [
        {
          "text": "The row size style constants define the size of the rows in the table view. They are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/effectiveRowSizeStyle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowSizeStyle-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties. You can also query the row size in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableCellView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class’ property ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableCellView/rowSizeStyle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RowSizeStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RowSizeStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.RowSizeStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowsizestyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/custom": {
      "abstract": [
        {
          "text": "The table will use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowHeight",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or invoke the delegate method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", if implemented. The cell layout is not changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/custom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewRowSizeStyleCustom"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.RowSizeStyle.custom",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowsizestyle-swift.enum/custom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/default": {
      "abstract": [
        {
          "text": "The table will use the system default layout size: small, medium or large.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewRowSizeStyleDefault"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.RowSizeStyle.default",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowsizestyle-swift.enum/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/large": {
      "abstract": [
        {
          "text": "The table will use a row height specified for a large table. It is required that the size be fully tested and supported if ",
          "type": "text"
        },
        {
          "code": "NSTableViewRowSizeStyleCustom",
          "type": "codeVoice"
        },
        {
          "text": " is not used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "large"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/large",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewRowSizeStyleLarge"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.RowSizeStyle.large",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowsizestyle-swift.enum/large"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/medium": {
      "abstract": [
        {
          "text": "The table will use a row height specified for a medium table. It is required that the size be fully tested and supported if ",
          "type": "text"
        },
        {
          "code": "NSTableViewRowSizeStyleCustom",
          "type": "codeVoice"
        },
        {
          "text": " is not used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewRowSizeStyleMedium"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.RowSizeStyle.medium",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowsizestyle-swift.enum/medium"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/small": {
      "abstract": [
        {
          "text": "The table will use a row height specified for a small table. It is required that the size be fully tested and supported if ",
          "type": "text"
        },
        {
          "code": "NSTableViewRowSizeStyleCustom",
          "type": "codeVoice"
        },
        {
          "text": " is not used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "small"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/small",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewRowSizeStyleSmall"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.RowSizeStyle.small",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowsizestyle-swift.enum/small"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/effectiveRowSizeStyle": {
      "abstract": [
        {
          "text": "The effective row size style for the table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveRowSizeStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewRowSizeStyle",
          "text": "RowSizeStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/effectiveRowSizeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectiveRowSizeStyle"
        }
      ],
      "role": "symbol",
      "title": "effectiveRowSizeStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/effectiverowsizestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowHeight": {
      "abstract": [
        {
          "text": "The height of each row in the table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowHeight"
        }
      ],
      "role": "symbol",
      "title": "rowHeight",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowheight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowSizeStyle-swift.property": {
      "abstract": [
        {
          "text": "The row size style (small, medium, large, or custom) used by the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowSizeStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewRowSizeStyle",
          "text": "RowSizeStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/rowSizeStyle-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowSizeStyle"
        }
      ],
      "role": "symbol",
      "title": "rowSizeStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/rowsizestyle-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the height of the specified row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "heightOfRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:heightOfRow:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:heightOfRow:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewdelegate/tableview(_:heightofrow:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/custom",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/small",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/medium",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/large"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTableViewRowSizeStyleDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowSizeStyleDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/custom",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/small",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/medium",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/RowSizeStyle-swift.enum/large"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTableViewRowSizeStyleDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView/title",
          "value": "NSTableCellView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableCellView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableCellView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1default/title",
          "value": "NSTableViewRowSizeStyleDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowSizeStyleDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1medium/title",
          "value": "NSTableViewRowSizeStyleMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowSizeStyleMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1effectiveRowSizeStyle/title",
          "value": "effectiveRowSizeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1effectiveRowSizeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "effectiveRowSizeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView~1rowSizeStyle/title",
          "value": "rowSizeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView~1rowSizeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowSizeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title",
          "value": "NSTableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:heightOfRow:)/title",
          "value": "tableView:heightOfRow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:heightOfRow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:heightOfRow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1large/title",
          "value": "NSTableViewRowSizeStyleLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1large/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowSizeStyleLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1custom/title",
          "value": "NSTableViewRowSizeStyleCustom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1custom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowSizeStyleCustom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1small/title",
          "value": "NSTableViewRowSizeStyleSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum~1small/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowSizeStyleSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1rowSizeStyle-swift.property/title",
          "value": "rowSizeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1rowSizeStyle-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowSizeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum/title",
          "value": "NSTableViewRowSizeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowSizeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1RowSizeStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowSizeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1rowHeight/title",
          "value": "rowHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1rowHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowHeight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstableview/rowsizestyle-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstableview/rowsizestyle-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
