{
  "abstract": [
    {
      "text": "The name of the scene class you want UIKit to instantiate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/UISceneClassName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UIApplicationSceneManifest.UISceneConfigurations.CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication.UISceneClassName",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISceneClassName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UISceneClassName"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Class Name",
        "name": "UISceneClassName",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [],
          "name": "CPTemplateApplicationScene"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "CarPlay doesn’t support custom classes. Omit this key or specify ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CarPlay/CPTemplateApplicationInstrumentClusterScene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for scenes meant for a CarPlay Instrument Cluster.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest": {
      "abstract": [
        {
          "text": "The information about the app’s scene-based life-cycle support.",
          "type": "text"
        }
      ],
      "ideTitle": "Application Scene Manifest",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
      "kind": "symbol",
      "name": "UIApplicationSceneManifest",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationSceneManifest"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationSceneManifest",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations": {
      "abstract": [
        {
          "text": "The default configuration details the system uses to create new scenes.",
          "type": "text"
        }
      ],
      "ideTitle": "Scene Configuration",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations",
      "kind": "symbol",
      "name": "UISceneConfigurations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneConfigurations"
        }
      ],
      "role": "symbol",
      "title": "UISceneConfigurations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication": {
      "abstract": [
        {
          "text": "Configurations for scenes you use to display navigation content on a CarPlay Instrument Cluster.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication",
      "kind": "symbol",
      "name": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cptemplateapplicationinstrumentclusterscenesessionroleapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/UISceneClassName": {
      "abstract": [
        {
          "text": "The name of the scene class you want UIKit to instantiate.",
          "type": "text"
        }
      ],
      "ideTitle": "Class Name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/UISceneClassName",
      "kind": "symbol",
      "name": "UISceneClassName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneClassName"
        }
      ],
      "role": "symbol",
      "title": "UISceneClassName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cptemplateapplicationinstrumentclusterscenesessionroleapplication/uisceneclassname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/UISceneDelegateClassName": {
      "abstract": [
        {
          "text": "The name of the app-specific class you want UIKit to instantiate and use as the scene delegate object.",
          "type": "text"
        }
      ],
      "ideTitle": "Delegate Class Name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/UISceneDelegateClassName",
      "kind": "symbol",
      "name": "UISceneDelegateClassName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneDelegateClassName"
        }
      ],
      "role": "symbol",
      "title": "UISceneDelegateClassName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cptemplateapplicationinstrumentclusterscenesessionroleapplication/uiscenedelegateclassname"
    },
    "doc://com.apple.documentation/documentation/CarPlay/CPTemplateApplicationInstrumentClusterScene": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationInstrumentClusterScene"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CarPlay/CPTemplateApplicationInstrumentClusterScene",
      "kind": "symbol",
      "role": "symbol",
      "title": "CPTemplateApplicationInstrumentClusterScene",
      "type": "topic",
      "url": "/documentation/CarPlay/CPTemplateApplicationInstrumentClusterScene"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scene-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/UISceneDelegateClassName"
      ],
      "title": "Scene objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISceneClassName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneClassName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scene-objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UISceneConfigurations/CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/UISceneDelegateClassName"
              ],
              "title": "Scene objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication~1UISceneDelegateClassName/title",
          "value": "UISceneDelegateClassName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication~1UISceneDelegateClassName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneDelegateClassName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication~1UISceneClassName/title",
          "value": "UISceneClassName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication~1UISceneClassName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneClassName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/title",
          "value": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations~1CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationInstrumentClusterSceneSessionRoleApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/title",
          "value": "UIApplicationSceneManifest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationSceneManifest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CarPlay~1CPTemplateApplicationInstrumentClusterScene/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationInstrumentClusterScene"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIScene",
              "text": "UIScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations/title",
          "value": "UISceneConfigurations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationSceneManifest~1UISceneConfigurations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneConfigurations"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cptemplateapplicationinstrumentclusterscenesessionroleapplication/uisceneclassname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationscenemanifest/uisceneconfigurations/cptemplateapplicationinstrumentclusterscenesessionroleapplication/uisceneclassname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
