{
  "abstract": [
    {
      "text": "The displayed sticker object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messages/documentation/Messages",
        "doc://com.apple.messages/documentation/Messages/MSStickerView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages/MSStickerView/sticker"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MSStickerView(py)sticker",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sticker"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MSSticker",
        "text": "MSSticker"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sticker"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "sticker"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sticker"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSSticker",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MSSticker",
              "text": "MSSticker"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set this property to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " to remove the current sticker.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you are using Auto Layout, setting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerView/sticker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property changes the view’s intrinsic content size. A view with a ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": "-valued ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerView/sticker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property does not have an intrinsic content size (the intrinsic content size is set to ",
              "type": "text"
            },
            {
              "code": "{UIViewNoIntrinsicMetric, UIViewNoIntrinsicMetric}",
              "type": "codeVoice"
            },
            {
              "text": "). Otherwise, the view’s intrinsic content size is set equal to the size of the sticker’s image file (in points).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you are not using Auto Layout, setting the sticker property does not change the view’s size. Call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/sizeToFit()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to adjust the size of the view to match the sticker.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UIView/sizeToFit()": {
      "abstract": [
        {
          "text": "Resizes and moves the receiver view so it just encloses its subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeToFit"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/sizeToFit()",
      "kind": "symbol",
      "role": "symbol",
      "title": "sizeToFit()",
      "type": "topic",
      "url": "/documentation/UIKit/UIView/sizeToFit()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSSticker": {
      "abstract": [
        {
          "text": "A sticker that can be sent as a new message or attached to an existing balloon in the Messages app’s  transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSSticker"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSSticker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSSticker"
        }
      ],
      "role": "symbol",
      "title": "MSSticker",
      "type": "topic",
      "url": "/documentation/messages/mssticker"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickerView": {
      "abstract": [
        {
          "text": "A view for displaying a sticker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSStickerView"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSStickerView"
        }
      ],
      "role": "symbol",
      "title": "MSStickerView",
      "type": "topic",
      "url": "/documentation/messages/msstickerview"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickerView/init(frame:sticker:)": {
      "abstract": [
        {
          "text": "Initializes a new sticker view with the provided sticker and frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sticker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSSticker",
          "text": "MSSticker"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerView/init(frame:sticker:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:sticker:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:sticker:)",
      "type": "topic",
      "url": "/documentation/messages/msstickerview/init(frame:sticker:)"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickerView/sticker": {
      "abstract": [
        {
          "text": "The displayed sticker object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sticker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSSticker",
          "text": "MSSticker"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerView/sticker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sticker"
        }
      ],
      "role": "symbol",
      "title": "sticker",
      "type": "topic",
      "url": "/documentation/messages/msstickerview/sticker"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Sticker-Views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSStickerView/init(frame:sticker:)"
      ],
      "title": "Working with Sticker Views"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sticker"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messages/documentation/Messages",
                "doc://com.apple.messages/documentation/Messages/MSStickerView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Sticker-Views",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSStickerView/init(frame:sticker:)"
              ],
              "title": "Working with Sticker Views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.messages/documentation/Messages/MSSticker",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MSSticker",
                    "text": "MSSticker"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "sticker"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView~1init(frame:sticker:)/title",
          "value": "initWithFrame:sticker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView~1init(frame:sticker:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:sticker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSticker/title",
          "value": "MSSticker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSticker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSticker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1sizeToFit()/title",
          "value": "sizeToFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1sizeToFit()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "sizeToFit"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView~1sticker/title",
          "value": "sticker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView~1sticker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView/title",
          "value": "MSStickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages/msstickerview/sticker"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages/msstickerview/sticker"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
