{
  "abstract": [
    {
      "text": "Learn the expected use cases for Network Extension packet tunnel providers, and",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "about use cases that are not supported.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.technotes/documentation/Technotes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.technotes/documentation/Technotes/tn3120-expected-use-cases-for-network-extension-packet-tunnel-providers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "TN3120: Expected use cases for Network Extension packet tunnel providers"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEPacketTunnelProvider",
              "isActive": true,
              "overridingTitle": "NEPacketTunnelProvider",
              "overridingTitleInlineContent": [
                {
                  "text": "NEPacketTunnelProvider",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " is very powerful and useful on Apple platforms.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "It has many valid use cases such as providing users access to secure resources",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and securing network traffic on an insecure network. While this API is very",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "powerful, there are certain use cases that do not line up with its intended",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "purpose. This technote briefly explains the recommended use cases for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "packet tunnel providers, along with common scenarios that are unsupported.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Recommended-use-cases-for-packet-tunnel-providers",
          "level": 2,
          "text": "Recommended use cases for packet tunnel providers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Recommended use cases for a packet tunnel provider include:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Do use a packet tunnel provider to access secure resources on an",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "isolated network. For example, use ",
                      "type": "text"
                    },
                    {
                      "code": "NEPacketTunnelProvider",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to implement an iOS",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "or macOS VPN client that tunnels network traffic through a VPN connection into a",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "private enterprise network. This can be done by tunneling specific destination IP",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "and DNS traffic to the isolated network.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Do use a packet tunnel provider to secure network access while on an insecure",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "network.  For example, use ",
                      "type": "text"
                    },
                    {
                      "code": "NEPacketTunnelProvider",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to implement an iOS or macOS VPN",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "client that tunnels network traffic through a public VPN service that provides",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "access to the wider internet.  Common techniques used to achieve this functionality",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "include creating a full tunnel VPN that routes all traffic to the remote",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "VPN server that then forwards the traffic to its final destination.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Unsupported-uses-of-packet-tunnel-providers",
          "level": 2,
          "text": "Unsupported uses of packet tunnel providers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While there are many reasons to use a packet tunnel provider, there are also many",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "unsupported uses of this API. If you find yourself implementing any one",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of the code paths below, consider using one of the suggested alternatives:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Do not use a packet tunnel provider to implement a network content filter. Packets that",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "are read from ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEPacketTunnelFlow",
                      "isActive": true,
                      "overridingTitle": "NEPacketTunnelFlow",
                      "overridingTitleInlineContent": [
                        {
                          "text": "NEPacketTunnelFlow",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " are meant to be sent over a tunnel connection",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to a remote server for injection into a remote network. They are not meant to be",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "dropped or re-injected back into the system. Doing so is a content filter action,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "as supported by one of the Network Extension",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/content-filter-providers",
                      "isActive": true,
                      "overridingTitle": "Content Filter",
                      "overridingTitleInlineContent": [
                        {
                          "text": "Content Filter",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " APIs.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "On iOS, implement a connection-based content filter using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEFilterDataProvider",
                      "isActive": true,
                      "overridingTitle": "NEFilterDataProvider",
                      "overridingTitleInlineContent": [
                        {
                          "text": "NEFilterDataProvider",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " and",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEFilterControlProvider",
                      "isActive": true,
                      "overridingTitle": "NEFilterControlProvider",
                      "overridingTitleInlineContent": [
                        {
                          "text": "NEFilterControlProvider",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": ". On macOS, implement a connection-based content filter",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "with ",
                      "type": "text"
                    },
                    {
                      "code": "NEFilterDataProvider",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or a packet-based content filter with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEFilterPacketProvider",
                      "isActive": true,
                      "overridingTitle": "NEFilterPacketProvider",
                      "overridingTitleInlineContent": [
                        {
                          "text": "NEFilterPacketProvider",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "On macOS, using both providers at the same time is supported.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "text": "There are two ways to deploy a content filter on iOS. In a managed environment,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "use MDM to deploy a content filter to supervised devices. In an unmanaged environment,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "deploy your content filter as part of a Screen Time app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Do not use a packet tunnel provider to intercept all DNS traffic on the system.",
                      "type": "text"
                    },
                    {
                      "text": "\n",
                      "type": "text"
                    },
                    {
                      "text": "For small sets of DNS traffic inside your isolated network, this is reasonable.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "However, trying to intercept all DNS traffic on the system can result in endless",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "edge cases and problems during development and deployment. As an alternative",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEDNSProxyProvider",
                      "isActive": true,
                      "overridingTitle": "NEDNSProxyProvider",
                      "overridingTitleInlineContent": [
                        {
                          "text": "NEDNSProxyProvider",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " or the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/dns-settings",
                      "isActive": true,
                      "overridingTitle": "DNS Settings",
                      "overridingTitleInlineContent": [
                        {
                          "text": "DNS Settings",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " APIs.  These APIs were built for handling all DNS traffic on the system.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Do not use a packet tunnel provider to selectively claim traffic for the packet tunnel",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "and proxy all other traffic elsewhere. Traffic that is claimed by a ",
                      "type": "text"
                    },
                    {
                      "code": "NEPacketTunnelProvider",
                      "type": "codeVoice"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "is meant to be sent through the tunnel connection and not be routed through another",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "interface via a proxy.  The recommended alternative is to implement a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NETransparentProxyProvider",
                      "isActive": true,
                      "overridingTitle": "NETransparentProxyProvider",
                      "overridingTitleInlineContent": [
                        {
                          "text": "NETransparentProxyProvider",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " on",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "macOS.  On iOS, consider either claiming the network traffic that is needed",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "for your tunnel with ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/networkextension/netunnelprovidermanager#2110139",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", or claiming traffic by destination IP with",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEIPv4Settings/includedRoutes",
                      "isActive": true,
                      "overridingTitle": "includedRoutes",
                      "overridingTitleInlineContent": [
                        {
                          "text": "includedRoutes",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Do not use a packet tunnel provider to host a network listener or proxy server.",
                      "type": "text"
                    },
                    {
                      "text": "\n",
                      "type": "text"
                    },
                    {
                      "text": "There is no reasonable alternative here other than using one of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/app-proxy-provider",
                      "isActive": true,
                      "overridingTitle": "App Proxy Provider",
                      "overridingTitleInlineContent": [
                        {
                          "text": "App Proxy Provider",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "APIs.  This path is simply not a recommended use case for a packet tunnel provider",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "or any other Network Extension.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Avoiding the unsupported scenarios will save your project many edges cases and bugs during",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the development and deployment process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Revision-History",
          "level": 2,
          "text": "Revision History",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "2022-05-24",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Made minor editorial changes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "2022-03-29",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Added additional links to APIs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "2022-03-22",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " First published.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/NetworkExtension/NEDNSProxyProvider": {
      "abstract": [
        {
          "text": "The principal class for a DNS proxy provider app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEDNSProxyProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEDNSProxyProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEDNSProxyProvider",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEDNSProxyProvider"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEFilterControlProvider": {
      "abstract": [
        {
          "text": "The principal class for a filter control provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterControlProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEFilterControlProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEFilterControlProvider",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEFilterControlProvider"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEFilterDataProvider": {
      "abstract": [
        {
          "text": "The principal class for a filter data provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterDataProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEFilterDataProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEFilterDataProvider",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEFilterDataProvider"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEFilterPacketProvider": {
      "abstract": [
        {
          "text": "A filter provider that evaluates network packets and decides whether to block, allow, or delay the packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterPacketProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEFilterPacketProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEFilterPacketProvider",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEFilterPacketProvider"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEIPv4Settings/includedRoutes": {
      "abstract": [
        {
          "text": "The IPv4 network traffic that the system routes to the TUN interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includedRoutes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEIPv4Route",
          "text": "NEIPv4Route"
        },
        {
          "kind": "text",
          "text": "]? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEIPv4Settings/includedRoutes",
      "kind": "symbol",
      "role": "symbol",
      "title": "includedRoutes",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEIPv4Settings/includedRoutes"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEPacketTunnelFlow": {
      "abstract": [
        {
          "text": "An object you use to read and write packets to and from the tunnel’s virtual interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEPacketTunnelFlow"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEPacketTunnelFlow",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEPacketTunnelFlow",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEPacketTunnelFlow"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEPacketTunnelProvider": {
      "abstract": [
        {
          "text": "The principal class for a packet tunnel provider app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEPacketTunnelProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEPacketTunnelProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEPacketTunnelProvider",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEPacketTunnelProvider"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NETransparentProxyProvider": {
      "abstract": [
        {
          "text": "An object that implements the client side of a custom transparent network proxy solution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NETransparentProxyProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NETransparentProxyProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NETransparentProxyProvider",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NETransparentProxyProvider"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/app-proxy-provider": {
      "abstract": [
        {
          "text": "Implement a VPN client for a flow-oriented, custom VPN protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/app-proxy-provider",
      "kind": "article",
      "role": "article",
      "title": "App proxy provider",
      "type": "topic",
      "url": "/documentation/NetworkExtension/app-proxy-provider"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/content-filter-providers": {
      "abstract": [
        {
          "text": "Create an on-device network content filter.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/content-filter-providers",
      "kind": "article",
      "role": "article",
      "title": "Content filter providers",
      "type": "topic",
      "url": "/documentation/NetworkExtension/content-filter-providers"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/dns-settings": {
      "abstract": [
        {
          "text": "Create and manage a system-wide DNS configuration that uses built-in encrypted DNS protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/dns-settings",
      "kind": "article",
      "role": "article",
      "title": "DNS settings",
      "type": "topic",
      "url": "/documentation/NetworkExtension/dns-settings"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.technotes/documentation/Technotes": {
      "abstract": [
        {
          "text": "Learn about specific development topics through these in-depth technical articles.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes",
      "kind": "article",
      "role": "collection",
      "title": "Technotes",
      "type": "topic",
      "url": "/documentation/technotes"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview": {
      "abstract": [
        {
          "text": "Explore the various Wi-Fi APIs available on iOS and their expected use cases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview",
      "kind": "article",
      "role": "article",
      "title": "TN3111: iOS Wi-Fi API overview",
      "type": "topic",
      "url": "/documentation/technotes/tn3111-ios-wifi-api-overview"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations": {
      "abstract": [
        {
          "text": "Learn techniques to help debug any coordinate space issue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations",
      "kind": "article",
      "role": "article",
      "title": "TN3124: Debugging coordinate space issues",
      "type": "topic",
      "url": "/documentation/technotes/tn3124-debugging-coordinate-transformations"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store": {
      "abstract": [
        {
          "text": "Learn how to configure your App Clip to prevent it from being unavailable in the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store",
      "kind": "article",
      "role": "article",
      "title": "TN3168: Making your App Clip available in the App Store",
      "type": "topic",
      "url": "/documentation/technotes/tn3168-making-your-app-clip-available-app-store"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration": {
      "abstract": [
        {
          "text": "Diagnose errors due to invalid Apple Pay merchant identifier configurations by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "identifying the underlying causes of common errors and explore their",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration",
      "kind": "article",
      "role": "article",
      "title": "TN3173: Troubleshooting issues with your Apple Pay merchant identifier configuration",
      "type": "topic",
      "url": "/documentation/technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website": {
      "abstract": [
        {
          "text": "Diagnose errors received while presenting the Apple Pay payment sheet on",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your website by identifying the underlying causes of common errors and explore",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "their potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website",
      "kind": "article",
      "role": "article",
      "title": "TN3174: Diagnosing issues with the Apple Pay payment sheet on your website",
      "type": "topic",
      "url": "/documentation/technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website": {
      "abstract": [
        {
          "text": "Diagnose common errors received while displaying the Apple Pay button on your",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "website by identifying the underlying causes, and explore potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website",
      "kind": "article",
      "role": "article",
      "title": "TN3175: Diagnosing issues with displaying the Apple Pay button on your website",
      "type": "topic",
      "url": "/documentation/technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues": {
      "abstract": [
        {
          "text": "Diagnose errors that occur when processing Apple Pay payments,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "identify common causes, and explore potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues",
      "kind": "article",
      "role": "article",
      "title": "TN3176: Troubleshooting Apple Pay payment processing issues",
      "type": "topic",
      "url": "/documentation/technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files": {
      "abstract": [
        {
          "text": "Learn how alternate groups collect audio tracks, and how to choose which audio track to use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files",
      "kind": "article",
      "role": "article",
      "title": "TN3177: Understanding alternate audio track groups in movie files",
      "type": "topic",
      "url": "/documentation/technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems": {
      "abstract": [
        {
          "text": "Ensure that every Mach-O image has a UUID, and that every distinct Mach-O image has its own unique UUID.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems",
      "kind": "article",
      "role": "article",
      "title": "TN3178: Checking for and resolving build UUID problems",
      "type": "topic",
      "url": "/documentation/technotes/tn3178-checking-for-and-resolving-build-uuid-problems"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy": {
      "abstract": [
        {
          "text": "Learn how local network privacy affects your software.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy",
      "kind": "article",
      "role": "article",
      "title": "TN3179: Understanding local network privacy",
      "type": "topic",
      "url": "/documentation/technotes/tn3179-understanding-local-network-privacy"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1": {
      "abstract": [
        {
          "text": "Migrate from version 2 to version 1 of App Store Server Notifications using the Modify an App endpoint.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1",
      "kind": "article",
      "role": "article",
      "title": "TN3180: Reverting to App Store Server Notifications V1",
      "type": "topic",
      "url": "/documentation/technotes/tn3180-reverting-app-store-server-notifications-v1"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest": {
      "abstract": [
        {
          "text": "Identify common configurations that cause unsuccessful privacy manifest validation with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3181: Debugging an invalid privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3181-debugging-invalid-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the tracking domains you use in your app or third-party SDK in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3182: Adding privacy tracking keys to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the APIs that can potentially fingerprint devices in your app or third-party SDK in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3183: Adding required reason API entries to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the data your app or third-party SDK collects in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3184: Adding data collection details to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest"
    },
    "https://developer.apple.com/documentation/networkextension/netunnelprovidermanager#2110139": {
      "identifier": "https://developer.apple.com/documentation/networkextension/netunnelprovidermanager#2110139",
      "title": "Per-App VPN",
      "titleInlineContent": [
        {
          "text": "Per-App VPN",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/networkextension/netunnelprovidermanager#2110139"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Latest",
      "generated": true,
      "identifiers": [
        "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1",
        "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy",
        "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems",
        "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files",
        "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview",
        "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues",
        "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website",
        "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website",
        "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration",
        "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store",
        "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations"
      ],
      "title": "Latest"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEDNSProxyProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEDNSProxyProvider"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEProvider",
              "text": "NEProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEPacketTunnelFlow/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEPacketTunnelFlow"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEFilterPacketProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEFilterPacketProvider"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEFilterProvider",
              "text": "NEFilterProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEFilterDataProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEFilterDataProvider"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEFilterProvider",
              "text": "NEFilterProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEFilterControlProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEFilterControlProvider"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEFilterProvider",
              "text": "NEFilterProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEIPv4Settings~1includedRoutes/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NEIPv4Route *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "includedRoutes"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NETransparentProxyProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NETransparentProxyProvider"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEAppProxyProvider",
              "text": "NEAppProxyProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEPacketTunnelProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEPacketTunnelProvider"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NETunnelProvider",
              "text": "NETunnelProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
