{
  "abstract": [
    {
      "text": "Understand dataless files and how to minimize the performance impact as the system materializes them.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.technotes/documentation/Technotes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.technotes/documentation/Technotes/tn3150-getting-ready-for-data-less-files"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "TN3150: Getting ready for dataless files"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In a modern file system, a file’s content may not be available locally on the device. A file that contains only metadata is known as a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "dataless",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " file. The file’s content typically resides on a remote server and is available to people or apps, transparently, when they access the file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, a person can create a dataless file in iCloud Drive on iOS by selecting a file in the Files app and choosing the Remove Download menu item. That action removes the file’s contents from the local device and frees the used storage space. Later, when a person taps the same file, or an app accesses it, the system redownloads the file’s content and makes it available again — a process known as materialization. File providers typically support dataless files. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/FileProvider/synchronizing-the-file-provider-extension",
              "isActive": true,
              "overridingTitle": "Synchronizing the File Provider Extension",
              "overridingTitleInlineContent": [
                {
                  "text": "Synchronizing the File Provider Extension",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Materializing a dataless file can take time if the file is large or there are poor network conditions. In such a scenario, the app may become unresponsive. If an app’s main queue remains unresponsive for a long time, the system may terminate the app and trigger a watchdog crash. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/addressing-watchdog-terminations",
              "isActive": true,
              "overridingTitle": "Addressing watchdog terminations",
              "overridingTitleInlineContent": [
                {
                  "text": "Addressing watchdog terminations",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " for details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Understand-the-impact-of-file-materialization",
          "level": 2,
          "text": "Understand the impact of file materialization",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Dataless files reduce the amount of storage space a file typically consumes, but accessing a dataless file causes the system to materialize the file. This can take a long time, creating a poor user experience in apps that aren’t ready for it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This typically affects apps that store files in their own ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1411653-url",
              "isActive": true,
              "overridingTitle": "ubiquity containers",
              "overridingTitleInlineContent": [
                {
                  "text": "ubiquity containers",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " or access files from network file providers like iCloud Drive. Common symptoms are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Slower frame rates and jitters when someone scrolls a user interface that loads data from one or more files",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Spins or hangs when performing file system operations",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Time-out errors (",
                      "type": "text"
                    },
                    {
                      "code": "ETIMEDOUT",
                      "type": "codeVoice"
                    },
                    {
                      "text": ") when invoking file system APIs",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A watchdog termination where the crash report includes reference to the materialization process",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Examples of actions that may result in one or more of these symptoms are enumerating a directory’s contents and checking whether a file exists using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1415645-fileexists",
              "isActive": true,
              "overridingTitle": "fileExists(atPath:)",
              "overridingTitleInlineContent": [
                {
                  "text": "fileExists(atPath:)",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you app encounters one of these symptoms, use Instruments to profile your app and identify the contributing API calls. For example, the following trace shows an app using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1414584-contentsofdirectory",
              "isActive": true,
              "overridingTitle": "contentsOfDirectory(atPath:)",
              "overridingTitleInlineContent": [
                {
                  "text": "contentsOfDirectory(atPath:)",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " to retrieve all paths in a directory, and the ",
              "type": "text"
            },
            {
              "code": "apfs_materialize_dataless_file_ext",
              "type": "codeVoice"
            },
            {
              "text": " symbol in the last frame corresponds to the materialization process:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            " 1000 -[NSFileManager contentsOfDirectoryAtPath:error:] + 36 (Foundation + 416570) [0x7ff81ca4fb3a]",
            " 1000 _NSDirectoryContentsFromCFURLEnumeratorError + 466 (Foundation + 417600) [0x7ff81ca4ff40]",
            " 1000 _URLEnumeratorGetNextURL + 176 (CoreServicesInternal + 51302) [0x7ff81e465866]",
            " 1000 _GetDirectoryURLs(_CFURLEnumerator*) + 1223 (CoreServicesInternal + 57378) [0x7ff81e467022]",
            " 1000 DirEnumRead + 432 (CoreServicesInternal + 58064) [0x7ff81e4672d0]",
            " 1000 getattrlistbulk + 10 (libsystem_kernel.dylib + 17338) [0x7ff81baed3ba]",
            " *1000 hndl_unix_scall64 + 22 (kernel + 57910) [0xffffff800021e236]",
            " *1000 unix_syscall64 + 507 (kernel + 7833867) [0xffffff800098890b]",
            " *1000 getattrlistbulk + 1570 (kernel + 3070210) [0xffffff80004fd902]",
            " *1000 apfs_vnop_getattrlistbulk + 272 (apfs + 394110) [0xffffff800356837e]",
            " *1000 apfs_materialize_dataless_file_ext + 160 (apfs + 738928) [0xffffff80035bc670]"
          ],
          "syntax": null,
          "type": "codeListing"
        },
        {
          "anchor": "Prepare-your-app-for-dataless-file-access",
          "level": 2,
          "text": "Prepare your app for dataless file access",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system, or a person using the device, can make dataless files whenever they determine it’s appropriate, and your app needs to be ready to handle them. Specifically, avoid unnecessarily materializing dataless files and, when your app requires access to a file’s contents, perform that work asynchronously off the main thread. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/file_system/improving_performance_and_stability_when_accessing_the_file_system",
              "isActive": true,
              "overridingTitle": "Improving performance and stability when accessing the file system",
              "overridingTitleInlineContent": [
                {
                  "text": "Improving performance and stability when accessing the file system",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDocument",
              "isActive": true,
              "overridingTitle": "UIDocument",
              "overridingTitleInlineContent": [
                {
                  "text": "UIDocument",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSDocument",
              "isActive": true,
              "overridingTitle": "NSDocument",
              "overridingTitleInlineContent": [
                {
                  "text": "NSDocument",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " automatically access the file system in a coordinated and asynchronous manner. If your app uses those classes to read and write files (and document packages), it will automatically do the right thing with dataless files. (The system still materializes the intermediate folders, if they themselves are dataless.)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app or framework uses low-level POSIX APIs to access the file system and you’re unable to migrate to the preferred methods, consider the following two options:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check if a file is dataless and then only access it in a safe context. To do the check, call ",
                      "type": "text"
                    },
                    {
                      "code": "stat",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "getattrlist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and examine if ",
                      "type": "text"
                    },
                    {
                      "code": "SF_DATALESS",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is present in ",
                      "type": "text"
                    },
                    {
                      "code": "stat.st_flags",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". Be aware that ",
                      "type": "text"
                    },
                    {
                      "code": "stat",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "getattrlist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " both trigger the materialization of any intermediate folders in the file’s path, if they themselves are dataless.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "code": [
            "struct stat fileStat;",
            "if (stat(yourFilePath, &fileStat) == 0) {",
            "    if ((fileStat.st_flags & SF_DATALESS) > 0) {",
            "        // The file is dataless.",
            "    } else {",
            "        // The file isn't dataless.",
            "        // SF_DATALESS is a feature of APFS;",
            "        // don't assume IO is local here because network IO can happen on NFS.",
            "    }",
            "}"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Opt-out of dataless file materialization on a per-thread (or per-process) basis. Call ",
                      "type": "text"
                    },
                    {
                      "code": "setiopolicy_np",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with ",
                      "type": "text"
                    },
                    {
                      "code": "IOPOL_MATERIALIZE_DATALESS_FILES_OFF",
                      "type": "codeVoice"
                    },
                    {
                      "text": " as the ",
                      "type": "text"
                    },
                    {
                      "code": "iotype",
                      "type": "codeVoice"
                    },
                    {
                      "text": " parameter, and ",
                      "type": "text"
                    },
                    {
                      "code": "IOPOL_SCOPE_THREAD",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "IOPOL_SCOPE_PROCESS",
                      "type": "codeVoice"
                    },
                    {
                      "text": " as the ",
                      "type": "text"
                    },
                    {
                      "code": "scope",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". If you choose this option, handle any EDEADLK errors that arise when accessing dataless files.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "code": [
            "int iopolicy = getiopolicy_np(IOPOL_TYPE_VFS_MATERIALIZE_DATALESS_FILES, IOPOL_SCOPE_THREAD);",
            "if (iopolicy >= 0) {",
            "    if (setiopolicy_np(IOPOL_TYPE_VFS_MATERIALIZE_DATALESS_FILES, IOPOL_SCOPE_THREAD, IOPOL_MATERIALIZE_DATALESS_FILES_OFF) == 0) {",
            "        // Do your work here.",
            "        // Detect the EDEADLK error and handle the I/O failure when accessing dataless files.",
            "    }",
            "    // Restore the iopolicy.",
            "    setiopolicy_np(IOPOL_TYPE_VFS_MATERIALIZE_DATALESS_FILES, IOPOL_SCOPE_THREAD, iopolicy);",
            "}"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about the functions and constants in the above code, see their man pages. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/reading-unix-manual-pages",
              "isActive": true,
              "overridingTitle": "Reading UNIX Manual Pages",
              "overridingTitleInlineContent": [
                {
                  "text": "Reading UNIX Manual Pages",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " covers how to read man pages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Revision-History",
          "level": 2,
          "text": "Revision History",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "2023-05-09",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " First published.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/AppKit/NSDocument"
    },
    "doc://com.apple.documentation/documentation/FileProvider/synchronizing-the-file-provider-extension": {
      "abstract": [
        {
          "text": "Keep the local and remote copies of your File Provider extension’s content in sync.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/FileProvider/synchronizing-the-file-provider-extension",
      "kind": "article",
      "role": "article",
      "title": "Synchronizing the File Provider Extension",
      "type": "topic",
      "url": "/documentation/FileProvider/synchronizing-the-file-provider-extension"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIDocument": {
      "abstract": [
        {
          "text": "An abstract base class for managing discrete portions of your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDocument",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDocument",
      "type": "topic",
      "url": "/documentation/UIKit/UIDocument"
    },
    "doc://com.apple.documentation/documentation/Xcode/addressing-watchdog-terminations": {
      "abstract": [
        {
          "text": "Identify the signature of an unresponsive app terminated by the watchdog, and address the issue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/addressing-watchdog-terminations",
      "kind": "article",
      "role": "article",
      "title": "Addressing watchdog terminations",
      "type": "topic",
      "url": "/documentation/Xcode/addressing-watchdog-terminations"
    },
    "doc://com.apple.documentation/documentation/foundation/file_system/improving_performance_and_stability_when_accessing_the_file_system": {
      "abstract": [
        {
          "text": "Prevent data loss and app crashes by interacting with the file system in a coordinated, asynchronous manner and by avoiding unnecessary disk I/O.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/file_system/improving_performance_and_stability_when_accessing_the_file_system",
      "kind": "article",
      "role": "article",
      "title": "Improving performance and stability when accessing the file system",
      "type": "topic",
      "url": "/documentation/foundation/file_system/improving_performance_and_stability_when_accessing_the_file_system"
    },
    "doc://com.apple.documentation/documentation/foundation/filemanager/1411653-url": {
      "abstract": [
        {
          "text": "Returns the URL for the iCloud container associated with the specified identifier and establishes access to that container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "forUbiquityContainerIdentifier"
        },
        {
          "kind": "text",
          "text": ": String?) -> URL?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1411653-url",
      "kind": "symbol",
      "role": "symbol",
      "title": "url(forUbiquityContainerIdentifier:)",
      "type": "topic",
      "url": "/documentation/foundation/filemanager/1411653-url"
    },
    "doc://com.apple.documentation/documentation/foundation/filemanager/1414584-contentsofdirectory": {
      "abstract": [
        {
          "text": "Performs a shallow search of the specified directory and returns the paths of any contained items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "contentsOfDirectory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "atPath"
        },
        {
          "kind": "text",
          "text": ": String) -> [String]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1414584-contentsofdirectory",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentsOfDirectory(atPath:)",
      "type": "topic",
      "url": "/documentation/foundation/filemanager/1414584-contentsofdirectory"
    },
    "doc://com.apple.documentation/documentation/foundation/filemanager/1415645-fileexists": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a file or directory exists at a specified path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "fileExists"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "atPath"
        },
        {
          "kind": "text",
          "text": ": String) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1415645-fileexists",
      "kind": "symbol",
      "role": "symbol",
      "title": "fileExists(atPath:)",
      "type": "topic",
      "url": "/documentation/foundation/filemanager/1415645-fileexists"
    },
    "doc://com.apple.documentation/documentation/os/reading-unix-manual-pages": {
      "abstract": [
        {
          "text": "Use the Terminal app to read the documentation for low-level UNIX tools and APIs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/reading-unix-manual-pages",
      "kind": "article",
      "role": "article",
      "title": "Reading UNIX Manual Pages",
      "type": "topic",
      "url": "/documentation/os/reading-unix-manual-pages"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.technotes/documentation/Technotes": {
      "abstract": [
        {
          "text": "Learn about specific development topics through these in-depth technical articles.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes",
      "kind": "article",
      "role": "collection",
      "title": "Technotes",
      "type": "topic",
      "url": "/documentation/technotes"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview": {
      "abstract": [
        {
          "text": "Explore the various Wi-Fi APIs available on iOS and their expected use cases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview",
      "kind": "article",
      "role": "article",
      "title": "TN3111: iOS Wi-Fi API overview",
      "type": "topic",
      "url": "/documentation/technotes/tn3111-ios-wifi-api-overview"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations": {
      "abstract": [
        {
          "text": "Learn techniques to help debug any coordinate space issue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations",
      "kind": "article",
      "role": "article",
      "title": "TN3124: Debugging coordinate space issues",
      "type": "topic",
      "url": "/documentation/technotes/tn3124-debugging-coordinate-transformations"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store": {
      "abstract": [
        {
          "text": "Learn how to configure your App Clip to prevent it from being unavailable in the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store",
      "kind": "article",
      "role": "article",
      "title": "TN3168: Making your App Clip available in the App Store",
      "type": "topic",
      "url": "/documentation/technotes/tn3168-making-your-app-clip-available-app-store"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration": {
      "abstract": [
        {
          "text": "Diagnose errors due to invalid Apple Pay merchant identifier configurations by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "identifying the underlying causes of common errors and explore their",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration",
      "kind": "article",
      "role": "article",
      "title": "TN3173: Troubleshooting issues with your Apple Pay merchant identifier configuration",
      "type": "topic",
      "url": "/documentation/technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website": {
      "abstract": [
        {
          "text": "Diagnose errors received while presenting the Apple Pay payment sheet on",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your website by identifying the underlying causes of common errors and explore",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "their potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website",
      "kind": "article",
      "role": "article",
      "title": "TN3174: Diagnosing issues with the Apple Pay payment sheet on your website",
      "type": "topic",
      "url": "/documentation/technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website": {
      "abstract": [
        {
          "text": "Diagnose common errors received while displaying the Apple Pay button on your",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "website by identifying the underlying causes, and explore potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website",
      "kind": "article",
      "role": "article",
      "title": "TN3175: Diagnosing issues with displaying the Apple Pay button on your website",
      "type": "topic",
      "url": "/documentation/technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues": {
      "abstract": [
        {
          "text": "Diagnose errors that occur when processing Apple Pay payments,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "identify common causes, and explore potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues",
      "kind": "article",
      "role": "article",
      "title": "TN3176: Troubleshooting Apple Pay payment processing issues",
      "type": "topic",
      "url": "/documentation/technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files": {
      "abstract": [
        {
          "text": "Learn how alternate groups collect audio tracks, and how to choose which audio track to use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files",
      "kind": "article",
      "role": "article",
      "title": "TN3177: Understanding alternate audio track groups in movie files",
      "type": "topic",
      "url": "/documentation/technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems": {
      "abstract": [
        {
          "text": "Ensure that every Mach-O image has a UUID, and that every distinct Mach-O image has its own unique UUID.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems",
      "kind": "article",
      "role": "article",
      "title": "TN3178: Checking for and resolving build UUID problems",
      "type": "topic",
      "url": "/documentation/technotes/tn3178-checking-for-and-resolving-build-uuid-problems"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy": {
      "abstract": [
        {
          "text": "Learn how local network privacy affects your software.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy",
      "kind": "article",
      "role": "article",
      "title": "TN3179: Understanding local network privacy",
      "type": "topic",
      "url": "/documentation/technotes/tn3179-understanding-local-network-privacy"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1": {
      "abstract": [
        {
          "text": "Migrate from version 2 to version 1 of App Store Server Notifications using the Modify an App endpoint.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1",
      "kind": "article",
      "role": "article",
      "title": "TN3180: Reverting to App Store Server Notifications V1",
      "type": "topic",
      "url": "/documentation/technotes/tn3180-reverting-app-store-server-notifications-v1"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest": {
      "abstract": [
        {
          "text": "Identify common configurations that cause unsuccessful privacy manifest validation with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3181: Debugging an invalid privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3181-debugging-invalid-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the tracking domains you use in your app or third-party SDK in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3182: Adding privacy tracking keys to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the APIs that can potentially fingerprint devices in your app or third-party SDK in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3183: Adding required reason API entries to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the data your app or third-party SDK collects in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3184: Adding data collection details to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Latest",
      "generated": true,
      "identifiers": [
        "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1",
        "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy",
        "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems",
        "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files",
        "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview",
        "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues",
        "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website",
        "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website",
        "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration",
        "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store",
        "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations"
      ],
      "title": "Latest"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDocument"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1filemanager~11414584-contentsofdirectory/title",
          "value": "contentsOfDirectoryAtPath:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIDocument/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIDocument"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1filemanager~11415645-fileexists/title",
          "value": "fileExistsAtPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1filemanager~11411653-url/title",
          "value": "URLForUbiquityContainerIdentifier:"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
