{
  "abstract": [
    {
      "text": "Learn how to choose the best output pixel format for your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.technotes/documentation/Technotes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.technotes/documentation/Technotes/tn3121-selecting-a-pixel-format-for-an-avcapturevideodataoutput"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "TN3121: Selecting a pixel format for an AVCaptureVideoDataOutput"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "AVCaptureVideoDataOutput is capable of outputting pixel buffers to your app in many different pixel formats.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This Technote will explore the usability and perfomance characteristics of these formats, enabling you to make an informed decision about the best format to use in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Avoid-defaulting-to-BGRA",
          "level": 2,
          "text": "Avoid defaulting to ‘BGRA’",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A common mistake is to ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "default",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " to selecting ‘BGRA’ as the output format.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This format is not a native capture format, which means that AVCapture has to perform a conversion to deliver this format.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Additionally, this format requires significantly more memory than many of the native capture formats.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Consider a common scenario where the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/activeFormat",
              "isActive": true,
              "overridingTitle": "activeFormat",
              "overridingTitleInlineContent": [
                {
                  "text": "activeFormat",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice",
              "isActive": true,
              "overridingTitle": "AVCaptureDevice",
              "overridingTitleInlineContent": [
                {
                  "text": "AVCaptureDevice",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " is configured to capture in ‘420v’:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In this scenario, if you request that the video data output deliver pixel buffers in ‘BGRA’, then AVCapture has to convert every captured ‘420v’ pixel buffer to ‘BGRA’.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "AVCapture performs these conversions efficiently, but they are not free.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Also, ‘BGRA’ pixel buffers require approximately 2.6x more memory than their ‘420v’ equivalent pixel buffers!",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This dramatic increase in memory bandwidth usage has serious implications for the efficiency, thermals, and battery consumption of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Instead of paying the costs of pixel format conversion and high memory bandwidth by default, follow the guidance provided in “Choosing the output pixel format” to select an appropriate pixel format for your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Discovering-available-output-pixel-formats",
          "level": 2,
          "text": "Discovering available output pixel formats",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Not all devices support the full range of output pixel formats.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To see the available formats at run time, iterate through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureVideoDataOutput",
              "isActive": true,
              "overridingTitle": "AVCaptureVideoDataOutput",
              "overridingTitleInlineContent": [
                {
                  "text": "AVCaptureVideoDataOutput",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": "’s array of ",
              "type": "text"
            },
            {
              "text": "availableVideoPixelFormatTypes",
              "type": "text"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The availableVideoPixelFormatTypes array is dynamic, and depends on the activeFormat of the capture device that the AVCaptureVideoDataOutput is connected to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "As an example, iPhone 13 Pro supports the following output pixel formats:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Pixel Format Constant",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "FourCharCode",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Bits Per Channel",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘420v’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "8",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘&8v0’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "8",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossy_420YpCbCr8BiPlanarVideoRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘-8v0’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "8",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_420YpCbCr8BiPlanarFullRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘420f’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "8",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘&8f0’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "8",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossy_420YpCbCr8BiPlanarFullRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘-8f0’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "8",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_32BGRA",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘BGRA’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "8",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossless_32BGRA",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘&BGA’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "8",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossy_32BGRA",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘-BGA’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "8",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘x420’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "10",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘&xv0’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "10",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossy_420YpCbCr10PackedBiPlanarVideoRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘-xv0’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "10",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_422YpCbCr10BiPlanarVideoRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘x422’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "10",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘&xv2’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "10",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "kCVPixelFormatType_Lossy_422YpCbCr10PackedBiPlanarVideoRange",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "‘-xv2’",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "10",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "anchor": "Choosing-the-output-pixel-format",
          "level": 2,
          "text": "Choosing the output pixel format",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ideal output pixel format for your app will depend on how your app utilizes the pixel buffers that it receives from the video data output, as well the requirements that you have for your app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "There is no exact formula that can be applied to identify this format, but here are a few questions to consider:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Can your app work with bi-planar YpCbCr pixel buffers, or does it ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "require",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " BGRA pixel buffers?",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Can your app work with compressed pixel buffers, or does it ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "require",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " uncompressed pixel buffers?",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Does your app want to deliver 10-bit high dynamic range content?",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Consider the following example scenarios, which are intended to help guide you in selecting the output pixel format for your app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Scenario 1: An app takes the output pixel buffers and feeds them to a machine learning model that requires uncompressed BGRA pixel buffers as input. This app is a good candidate for the ‘BGRA’ output pixel format. By specifying this format, this app benefits from efficient conversion from a native capture format to the ‘BGRA’ that is required by the machine learning model.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Scenario 2: An app takes the output pixel buffers and feeds them to an AVAssetWriter, configured to write with the hevc codec. This app is a good candidate for a bi-planar YpCbCr format, which the asset writer can accept as input. By specifying this format, this app benefits from the efficiency and performance advantages of bi-planar YpCbCr data compared to BGRA data, and if the device this app is running on supports compressed pixel buffer formats, this app can use a compressed variation of the bi-planar format to reduce memory bandwidth even further.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Scenario 3: An app takes the output pixel buffers and feeds them to a custom Metal kernel to filter that operates on BGRA data. The developer of this app should consider modifying their kernel implementation to operate on bi-planar YCbCr data. Then, the app could request bi-planar YCbCr pixel buffers, greatly reducing its memory bandwidth usage. Since this app’s filter is implemented for the GPU, it can also utilize a compressed variation of its chosen output pixel format on supported devices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Choosing-between-lossy-and-lossless",
          "level": 2,
          "text": "Choosing between lossy and lossless",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In a scenario where your app can utilize a compressed pixel format, always request the lossy variation as the output pixel format if it is available, which will provide additional memory footprint savings.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "There is no difference in image quality between the lossy, lossless, and uncompressed pixel buffers that you receive from AVCapture.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This is because AVCapture internally uses lossy formats on devices that support them.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "These lossy formats are implemented such that, for most images, the compression is lossless, while the few remaining images are visually lossless.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Revision-History",
          "level": 2,
          "text": "Revision History",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "2022-03-29",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " First published.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/activeFormat": {
      "abstract": [
        {
          "text": "The capture format in use by the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDeviceFormat",
          "text": "Format"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/activeFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "activeFormat",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice/activeFormat"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureVideoDataOutput": {
      "abstract": [
        {
          "text": "A capture output that records video and provides access to video frames for processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureVideoDataOutput"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureVideoDataOutput",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureVideoDataOutput",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureVideoDataOutput"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.technotes/documentation/Technotes": {
      "abstract": [
        {
          "text": "Learn about specific development topics through these in-depth technical articles.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes",
      "kind": "article",
      "role": "collection",
      "title": "Technotes",
      "type": "topic",
      "url": "/documentation/technotes"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview": {
      "abstract": [
        {
          "text": "Explore the various Wi-Fi APIs available on iOS and their expected use cases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview",
      "kind": "article",
      "role": "article",
      "title": "TN3111: iOS Wi-Fi API overview",
      "type": "topic",
      "url": "/documentation/technotes/tn3111-ios-wifi-api-overview"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations": {
      "abstract": [
        {
          "text": "Learn techniques to help debug any coordinate space issue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations",
      "kind": "article",
      "role": "article",
      "title": "TN3124: Debugging coordinate space issues",
      "type": "topic",
      "url": "/documentation/technotes/tn3124-debugging-coordinate-transformations"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store": {
      "abstract": [
        {
          "text": "Learn how to configure your App Clip to prevent it from being unavailable in the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store",
      "kind": "article",
      "role": "article",
      "title": "TN3168: Making your App Clip available in the App Store",
      "type": "topic",
      "url": "/documentation/technotes/tn3168-making-your-app-clip-available-app-store"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration": {
      "abstract": [
        {
          "text": "Diagnose errors due to invalid Apple Pay merchant identifier configurations by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "identifying the underlying causes of common errors and explore their",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration",
      "kind": "article",
      "role": "article",
      "title": "TN3173: Troubleshooting issues with your Apple Pay merchant identifier configuration",
      "type": "topic",
      "url": "/documentation/technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website": {
      "abstract": [
        {
          "text": "Diagnose errors received while presenting the Apple Pay payment sheet on",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your website by identifying the underlying causes of common errors and explore",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "their potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website",
      "kind": "article",
      "role": "article",
      "title": "TN3174: Diagnosing issues with the Apple Pay payment sheet on your website",
      "type": "topic",
      "url": "/documentation/technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website": {
      "abstract": [
        {
          "text": "Diagnose common errors received while displaying the Apple Pay button on your",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "website by identifying the underlying causes, and explore potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website",
      "kind": "article",
      "role": "article",
      "title": "TN3175: Diagnosing issues with displaying the Apple Pay button on your website",
      "type": "topic",
      "url": "/documentation/technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues": {
      "abstract": [
        {
          "text": "Diagnose errors that occur when processing Apple Pay payments,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "identify common causes, and explore potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues",
      "kind": "article",
      "role": "article",
      "title": "TN3176: Troubleshooting Apple Pay payment processing issues",
      "type": "topic",
      "url": "/documentation/technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files": {
      "abstract": [
        {
          "text": "Learn how alternate groups collect audio tracks, and how to choose which audio track to use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files",
      "kind": "article",
      "role": "article",
      "title": "TN3177: Understanding alternate audio track groups in movie files",
      "type": "topic",
      "url": "/documentation/technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems": {
      "abstract": [
        {
          "text": "Ensure that every Mach-O image has a UUID, and that every distinct Mach-O image has its own unique UUID.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems",
      "kind": "article",
      "role": "article",
      "title": "TN3178: Checking for and resolving build UUID problems",
      "type": "topic",
      "url": "/documentation/technotes/tn3178-checking-for-and-resolving-build-uuid-problems"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy": {
      "abstract": [
        {
          "text": "Learn how local network privacy affects your software.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy",
      "kind": "article",
      "role": "article",
      "title": "TN3179: Understanding local network privacy",
      "type": "topic",
      "url": "/documentation/technotes/tn3179-understanding-local-network-privacy"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1": {
      "abstract": [
        {
          "text": "Migrate from version 2 to version 1 of App Store Server Notifications using the Modify an App endpoint.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1",
      "kind": "article",
      "role": "article",
      "title": "TN3180: Reverting to App Store Server Notifications V1",
      "type": "topic",
      "url": "/documentation/technotes/tn3180-reverting-app-store-server-notifications-v1"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest": {
      "abstract": [
        {
          "text": "Identify common configurations that cause unsuccessful privacy manifest validation with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3181: Debugging an invalid privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3181-debugging-invalid-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the tracking domains you use in your app or third-party SDK in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3182: Adding privacy tracking keys to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the APIs that can potentially fingerprint devices in your app or third-party SDK in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3183: Adding required reason API entries to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the data your app or third-party SDK collects in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3184: Adding data collection details to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Latest",
      "generated": true,
      "identifiers": [
        "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1",
        "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy",
        "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems",
        "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files",
        "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview",
        "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues",
        "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website",
        "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website",
        "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration",
        "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store",
        "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations"
      ],
      "title": "Latest"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureVideoDataOutput/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureVideoDataOutput"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureOutput",
              "text": "AVCaptureOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1activeFormat/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "retain"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureDeviceFormat",
              "text": "AVCaptureDeviceFormat"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "activeFormat"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
