{
  "abstract": [
    {
      "text": "Use an anonymous XPC listener to simplify your XPC testing and debugging.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.technotes/documentation/Technotes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.technotes/documentation/Technotes/tn3113-testing-xpc-code-with-an-anonymous-listener"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "TN3113: Testing and debugging XPC code with an anonymous listener"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Testing and debugging XPC code is tricky because there are two processes involved.  Imagine you have an app with an embedded XPC service.  To debug this you have to run two instances of the debugger, one connected to the app and another to the service, and then switch between them.  This works, but it’s quite inconvenient.  Fortunately there is a better way, a technique that allows you to test and debug all your XPC code in a single process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This technique does not help with all XPC testing and debugging scenarios.  For example, if you’re developing a ",
                  "type": "text"
                },
                {
                  "code": "launchd",
                  "type": "codeVoice"
                },
                {
                  "text": " daemon that performs privileged operations on behalf of your app, you can’t use this technique to debug your privileged code because it’s not running in a privileged process.  However, even in situations like that, this technique is useful when debugging your XPC-specific code.  For example, you might use it to create a unit test for your ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nssecurecoding",
                  "isActive": true,
                  "overridingTitle": "NSSecureCoding",
                  "overridingTitleInlineContent": [
                    {
                      "code": "NSSecureCoding",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "reference"
                },
                {
                  "text": " implementation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "This technique involves two key concepts:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Put your XPC listener and XPC client code in the same test program.  The specifics of this program are up to you: It might be a simple test app that you create specifically for this purpose, or it might be an Xcode unit test bundle, or it might be some other kind of program.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use an anonymous XPC listener to connect your XPC listener and client code.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Imagine you’re building an app with an embedded XPC service.  You have a ",
              "type": "text"
            },
            {
              "code": "MyListener",
              "type": "codeVoice"
            },
            {
              "text": " class that manages your XPC listener within the XPC service, and a ",
              "type": "text"
            },
            {
              "code": "MyConnection",
              "type": "codeVoice"
            },
            {
              "text": " class that manages the connection on the app side of things.  Add both of those classes, and all their support code, to your test program.  Then change ",
              "type": "text"
            },
            {
              "code": "MyListener",
              "type": "codeVoice"
            },
            {
              "text": " to accept an ",
              "type": "text"
            },
            {
              "code": "NSXPCListener",
              "type": "codeVoice"
            },
            {
              "text": " instance.  For example, your ",
              "type": "text"
            },
            {
              "code": "MyListener",
              "type": "codeVoice"
            },
            {
              "text": " class might look like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class MyListener {",
            "",
            "    init() {",
            "        self.listener = NSXPCListener.service()",
            "    }",
            "",
            "    let listener: NSXPCListener",
            "    ",
            "    … more code …",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "While this example uses the Foundation ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/xpc",
                  "isActive": true,
                  "overridingTitle": "XPC",
                  "overridingTitleInlineContent": [
                    {
                      "text": "XPC",
                      "type": "text"
                    }
                  ],
                  "type": "reference"
                },
                {
                  "text": " API, the same technique works for the low-level C ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/XPC",
                  "isActive": true,
                  "overridingTitle": "XPC",
                  "overridingTitleInlineContent": [
                    {
                      "text": "XPC",
                      "type": "text"
                    }
                  ],
                  "type": "reference"
                },
                {
                  "text": " API.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Change its initialiser to look like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "init(listener: NSXPCListener = .service()) {",
            "    self.listener = listener",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This uses the XPC service’s listener by default, but allows you to override that by passing in a value to the ",
              "type": "text"
            },
            {
              "code": "listener",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Now, in your test program, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsxpclistener/1412648-anonymouslistener",
              "isActive": true,
              "overridingTitle": "anonymous()",
              "overridingTitleInlineContent": [
                {
                  "code": "anonymous()",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " to create a anonymous listener and pass that to your listener abstraction:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let myListener = MyListener(listener: .anonymous())"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "On the client side, your ",
              "type": "text"
            },
            {
              "code": "MyConnection",
              "type": "codeVoice"
            },
            {
              "text": " class might look like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class MyConnection {",
            "",
            "    init() {",
            "        self.connection = NSXPCConnection(serviceName: \"com.example.MyService\")",
            "    }",
            "",
            "    let connection: NSXPCConnection",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Change the initialiser to look like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "init(connection: NSXPCConnection = .init(serviceName: \"com.example.MyService\")) {",
            "    self.connection = connection",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This sets up a connection to the XPC service’s listener by default, but allows you to override that by passing in a value to the ",
              "type": "text"
            },
            {
              "code": "connection",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, in your test program, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsxpcconnection/1416298-init",
              "isActive": true,
              "overridingTitle": "init(listenerEndpoint:)",
              "overridingTitleInlineContent": [
                {
                  "code": "init(listenerEndpoint:)",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " to create a connection to your anonymous listener:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let connection = NSXPCConnection(listenerEndpoint: myListener.listener.endpoint)",
            "let myConnection = MyConnection(connection: connection)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You now have an XPC connection between your client code and your listener, with all the code running in the same test program.  This makes it much easier to debug your XPC code.  And the same technique is perfect for unit tests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Revision-History",
          "level": 2,
          "text": "Revision History",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "2022-04-12",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Added syntax highlighting to the code listings (r. 89366505).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "2022-02-08",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Republished as TN3113.  Expanded the introduction to clarify the overall concept.  Made other minor editorial changes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "2021-11-09",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " First published as ”Testing and Debugging XPC Code With an Anonymous Listener” on Apple Developer Forums.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/XPC": {
      "abstract": [
        {
          "text": "Access a low-level interprocess communication mechanism.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC",
      "kind": "symbol",
      "role": "collection",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/XPC"
    },
    "doc://com.apple.documentation/documentation/foundation/nssecurecoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nssecurecoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.apple.documentation/documentation/foundation/nsxpcconnection/1416298-init": {
      "abstract": [
        {
          "text": "Initializes an  object to connect to an  object in another process, identified by an  object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "listenerEndpoint"
        },
        {
          "kind": "text",
          "text": ": NSXPCListenerEndpoint)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsxpcconnection/1416298-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(listenerEndpoint:)",
      "type": "topic",
      "url": "/documentation/foundation/nsxpcconnection/1416298-init"
    },
    "doc://com.apple.documentation/documentation/foundation/nsxpclistener/1412648-anonymouslistener": {
      "abstract": [
        {
          "text": "Returns a new anonymous listener connection.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsxpclistener/1412648-anonymouslistener",
      "kind": "symbol",
      "role": "symbol",
      "title": "anonymousListener",
      "type": "topic",
      "url": "/documentation/foundation/nsxpclistener/1412648-anonymouslistener"
    },
    "doc://com.apple.documentation/documentation/foundation/xpc": {
      "abstract": [
        {
          "text": "Manage secure interprocess communication. ",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/xpc",
      "kind": "article",
      "role": "article",
      "title": "XPC",
      "type": "topic",
      "url": "/documentation/foundation/xpc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.technotes/documentation/Technotes": {
      "abstract": [
        {
          "text": "Learn about specific development topics through these in-depth technical articles.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes",
      "kind": "article",
      "role": "collection",
      "title": "Technotes",
      "type": "topic",
      "url": "/documentation/technotes"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview": {
      "abstract": [
        {
          "text": "Explore the various Wi-Fi APIs available on iOS and their expected use cases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview",
      "kind": "article",
      "role": "article",
      "title": "TN3111: iOS Wi-Fi API overview",
      "type": "topic",
      "url": "/documentation/technotes/tn3111-ios-wifi-api-overview"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations": {
      "abstract": [
        {
          "text": "Learn techniques to help debug any coordinate space issue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations",
      "kind": "article",
      "role": "article",
      "title": "TN3124: Debugging coordinate space issues",
      "type": "topic",
      "url": "/documentation/technotes/tn3124-debugging-coordinate-transformations"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store": {
      "abstract": [
        {
          "text": "Learn how to configure your App Clip to prevent it from being unavailable in the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store",
      "kind": "article",
      "role": "article",
      "title": "TN3168: Making your App Clip available in the App Store",
      "type": "topic",
      "url": "/documentation/technotes/tn3168-making-your-app-clip-available-app-store"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration": {
      "abstract": [
        {
          "text": "Diagnose errors due to invalid Apple Pay merchant identifier configurations by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "identifying the underlying causes of common errors and explore their",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration",
      "kind": "article",
      "role": "article",
      "title": "TN3173: Troubleshooting issues with your Apple Pay merchant identifier configuration",
      "type": "topic",
      "url": "/documentation/technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website": {
      "abstract": [
        {
          "text": "Diagnose errors received while presenting the Apple Pay payment sheet on",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your website by identifying the underlying causes of common errors and explore",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "their potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website",
      "kind": "article",
      "role": "article",
      "title": "TN3174: Diagnosing issues with the Apple Pay payment sheet on your website",
      "type": "topic",
      "url": "/documentation/technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website": {
      "abstract": [
        {
          "text": "Diagnose common errors received while displaying the Apple Pay button on your",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "website by identifying the underlying causes, and explore potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website",
      "kind": "article",
      "role": "article",
      "title": "TN3175: Diagnosing issues with displaying the Apple Pay button on your website",
      "type": "topic",
      "url": "/documentation/technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues": {
      "abstract": [
        {
          "text": "Diagnose errors that occur when processing Apple Pay payments,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "identify common causes, and explore potential solutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues",
      "kind": "article",
      "role": "article",
      "title": "TN3176: Troubleshooting Apple Pay payment processing issues",
      "type": "topic",
      "url": "/documentation/technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files": {
      "abstract": [
        {
          "text": "Learn how alternate groups collect audio tracks, and how to choose which audio track to use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files",
      "kind": "article",
      "role": "article",
      "title": "TN3177: Understanding alternate audio track groups in movie files",
      "type": "topic",
      "url": "/documentation/technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems": {
      "abstract": [
        {
          "text": "Ensure that every Mach-O image has a UUID, and that every distinct Mach-O image has its own unique UUID.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems",
      "kind": "article",
      "role": "article",
      "title": "TN3178: Checking for and resolving build UUID problems",
      "type": "topic",
      "url": "/documentation/technotes/tn3178-checking-for-and-resolving-build-uuid-problems"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy": {
      "abstract": [
        {
          "text": "Learn how local network privacy affects your software.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy",
      "kind": "article",
      "role": "article",
      "title": "TN3179: Understanding local network privacy",
      "type": "topic",
      "url": "/documentation/technotes/tn3179-understanding-local-network-privacy"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1": {
      "abstract": [
        {
          "text": "Migrate from version 2 to version 1 of App Store Server Notifications using the Modify an App endpoint.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1",
      "kind": "article",
      "role": "article",
      "title": "TN3180: Reverting to App Store Server Notifications V1",
      "type": "topic",
      "url": "/documentation/technotes/tn3180-reverting-app-store-server-notifications-v1"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest": {
      "abstract": [
        {
          "text": "Identify common configurations that cause unsuccessful privacy manifest validation with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3181: Debugging an invalid privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3181-debugging-invalid-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the tracking domains you use in your app or third-party SDK in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3182: Adding privacy tracking keys to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the APIs that can potentially fingerprint devices in your app or third-party SDK in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3183: Adding required reason API entries to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest"
    },
    "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest": {
      "abstract": [
        {
          "text": "Declare the data your app or third-party SDK collects in a privacy manifest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest",
      "kind": "article",
      "role": "article",
      "title": "TN3184: Adding data collection details to your privacy manifest",
      "type": "topic",
      "url": "/documentation/technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Latest",
      "generated": true,
      "identifiers": [
        "doc://com.apple.technotes/documentation/Technotes/tn3182-adding-privacy-tracking-keys-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3183-adding-required-reason-api-entries-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3184-adding-data-collection-details-to-your-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3181-debugging-invalid-privacy-manifest",
        "doc://com.apple.technotes/documentation/Technotes/tn3180-reverting-app-store-server-notifications-v1",
        "doc://com.apple.technotes/documentation/Technotes/tn3179-understanding-local-network-privacy",
        "doc://com.apple.technotes/documentation/Technotes/tn3178-checking-for-and-resolving-build-uuid-problems",
        "doc://com.apple.technotes/documentation/Technotes/tn3177-understanding-alternate-audio-track-groups-in-movie-files",
        "doc://com.apple.technotes/documentation/Technotes/tn3111-ios-wifi-api-overview",
        "doc://com.apple.technotes/documentation/Technotes/tn3176-troubleshooting-apple-pay-payment-processing-issues",
        "doc://com.apple.technotes/documentation/Technotes/tn3175-diagnosing-issues-with-displaying-the-apple-pay-button-on-your-website",
        "doc://com.apple.technotes/documentation/Technotes/tn3174-diagnosing-issues-with-the-apple-pay-payment-sheet-on-your-website",
        "doc://com.apple.technotes/documentation/Technotes/tn3173-troubleshooting-issues-with-your-apple-pay-merchant-id-configuration",
        "doc://com.apple.technotes/documentation/Technotes/tn3168-making-your-app-clip-available-app-store",
        "doc://com.apple.technotes/documentation/Technotes/tn3124-debugging-coordinate-transformations"
      ],
      "title": "Latest"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsxpclistener~11412648-anonymouslistener/title",
          "value": "anonymous()"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsxpclistener~11412648-anonymouslistener/fragments",
          "value": [
            {
              "kind": "text",
              "text": "class func "
            },
            {
              "kind": "identifier",
              "text": "anonymous"
            },
            {
              "kind": "text",
              "text": "() -> NSXPCListener"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsxpcconnection~11416298-init/title",
          "value": "initWithListenerEndpoint:"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
