{
  "abstract": [
    {
      "text": "The network address of the acceptor, in the form specified by ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_address"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@gss_channel_bindings_struct@FI@acceptor_address",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "acceptor_address"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_buffer_desc",
        "text": "gss_buffer_desc"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "acceptor_address"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "acceptor_address"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "acceptor_address"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_desc",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_buffer_desc",
              "text": "gss_buffer_desc"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the specified address family has more than one format, the address itself should contain enough information to distinguish among them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_desc": {
      "abstract": [
        {
          "text": "The buffer descriptor that you use to exchange octet streams with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_desc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_desc"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_desc",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_desc"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_desc_struct": {
      "abstract": [
        {
          "text": "The structure for a buffer descriptor that you use to exchange octet streams with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_desc_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_desc_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_desc_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_desc_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_desc_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct": {
      "abstract": [
        {
          "text": "The structure defining a channel bindings descriptor that specifies the communications channel used to carry a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_channel_bindings_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_address": {
      "abstract": [
        {
          "text": "The network address of the acceptor, in the form specified by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceptor_address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_desc",
          "text": "gss_buffer_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptor_address"
        }
      ],
      "role": "symbol",
      "title": "acceptor_address",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/acceptor_address"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype": {
      "abstract": [
        {
          "text": "The type of address contained in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_address",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceptor_addrtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptor_addrtype"
        }
      ],
      "role": "symbol",
      "title": "acceptor_addrtype",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/acceptor_addrtype"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/application_data": {
      "abstract": [
        {
          "text": "Application specific data for use in communicating a channel binding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application_data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_desc",
          "text": "gss_buffer_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/application_data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application_data"
        }
      ],
      "role": "symbol",
      "title": "application_data",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/application_data"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address": {
      "abstract": [
        {
          "text": "The network address of the acceptor, in the form specified by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initiator_address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_desc",
          "text": "gss_buffer_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initiator_address"
        }
      ],
      "role": "symbol",
      "title": "initiator_address",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/initiator_address"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype": {
      "abstract": [
        {
          "text": "The type of address contained in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initiator_addrtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initiator_addrtype"
        }
      ],
      "role": "symbol",
      "title": "initiator_addrtype",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/initiator_addrtype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/application_data"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "acceptor_address"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptor_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS",
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype",
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address",
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype",
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/application_data"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_desc_struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@gss_buffer_desc_struct",
                    "text": "gss_buffer_desc"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "acceptor_address"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1acceptor_address/title",
          "value": "acceptor_address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1acceptor_address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptor_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct/title",
          "value": "gss_channel_bindings_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1initiator_addrtype/title",
          "value": "initiator_addrtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1initiator_addrtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initiator_addrtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1initiator_address/title",
          "value": "initiator_address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1initiator_address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initiator_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1acceptor_addrtype/title",
          "value": "acceptor_addrtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1acceptor_addrtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptor_addrtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc_struct/title",
          "value": "gss_buffer_desc_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc/title",
          "value": "gss_buffer_desc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1application_data/title",
          "value": "application_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1application_data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "application_data"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_channel_bindings_struct/acceptor_address"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_channel_bindings_struct/acceptor_address"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
