{
  "abstract": [
    {
      "text": "The size of the document file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/fileSize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreSpotlight",
    "externalID": "c:objc(cs)CSSearchableItemAttributeSet(py)fileSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fileSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "fileSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "fileSize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fileSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet": {
      "abstract": [
        {
          "text": "The detailed metadata for a searchable item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableItemAttributeSet",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/audiences": {
      "abstract": [
        {
          "text": "A class of entity for which the item is intended or useful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audiences"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/audiences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audiences"
        }
      ],
      "role": "symbol",
      "title": "audiences",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/audiences"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/contentDescription": {
      "abstract": [
        {
          "text": "A description of the item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/contentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentDescription"
        }
      ],
      "role": "symbol",
      "title": "contentDescription",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/contentdescription"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/creator": {
      "abstract": [
        {
          "text": "The name of the app that created the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/creator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creator"
        }
      ],
      "role": "symbol",
      "title": "creator",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/creator"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/encodingApplications": {
      "abstract": [
        {
          "text": "The name of the apps that converted the original content into a PDF stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodingApplications"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/encodingApplications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encodingApplications"
        }
      ],
      "role": "symbol",
      "title": "encodingApplications",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/encodingapplications"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/fileSize": {
      "abstract": [
        {
          "text": "The size of the document file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/fileSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileSize"
        }
      ],
      "role": "symbol",
      "title": "fileSize",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/filesize"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/fontNames": {
      "abstract": [
        {
          "text": "An array of font names the document uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/fontNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontNames"
        }
      ],
      "role": "symbol",
      "title": "fontNames",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/fontnames"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/identifier": {
      "abstract": [
        {
          "text": "A formal identifier that references the document the item represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/identifier"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/kind": {
      "abstract": [
        {
          "text": "A description of the kind of document the item represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/kind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kind"
        }
      ],
      "role": "symbol",
      "title": "kind",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/kind"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageCount": {
      "abstract": [
        {
          "text": "The number of pages in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageCount"
        }
      ],
      "role": "symbol",
      "title": "pageCount",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/pagecount"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageHeight": {
      "abstract": [
        {
          "text": "The height of the document page, in points (72 points per inch).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageHeight"
        }
      ],
      "role": "symbol",
      "title": "pageHeight",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/pageheight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageWidth": {
      "abstract": [
        {
          "text": "The width of the document page, in points (72 points per inch).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageWidth"
        }
      ],
      "role": "symbol",
      "title": "pageWidth",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/pagewidth"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/securityMethod": {
      "abstract": [
        {
          "text": "The security method (a type of encryption) that protects the document file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securityMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/securityMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "securityMethod"
        }
      ],
      "role": "symbol",
      "title": "securityMethod",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/securitymethod"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/subject": {
      "abstract": [
        {
          "text": "The subject of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/subject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subject"
        }
      ],
      "role": "symbol",
      "title": "subject",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/subject"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/theme": {
      "abstract": [
        {
          "text": "The theme of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "theme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/theme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "theme"
        }
      ],
      "role": "symbol",
      "title": "theme",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/theme"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Describing-documents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/audiences",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/contentDescription",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/creator",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/encodingApplications",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/fontNames",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/identifier",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/kind",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageCount",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageHeight",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageWidth",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/securityMethod",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/subject",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/theme"
      ],
      "title": "Describing documents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "fileSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fileSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Describing-documents",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/audiences",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/contentDescription",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/creator",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/encodingApplications",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/fontNames",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/identifier",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/kind",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageCount",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageHeight",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/pageWidth",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/securityMethod",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/subject",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/theme"
              ],
              "title": "Describing documents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSNumber",
                    "text": "NSNumber"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "fileSize"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1subject/title",
          "value": "subject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1subject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1kind/title",
          "value": "kind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1kind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/title",
          "value": "CSSearchableItemAttributeSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1pageCount/title",
          "value": "pageCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1pageCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1pageWidth/title",
          "value": "pageWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1pageWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1securityMethod/title",
          "value": "securityMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1securityMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "securityMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1contentDescription/title",
          "value": "contentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1contentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1audiences/title",
          "value": "audiences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1audiences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audiences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1fileSize/title",
          "value": "fileSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1fileSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fileSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1fontNames/title",
          "value": "fontNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1fontNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fontNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1encodingApplications/title",
          "value": "encodingApplications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1encodingApplications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encodingApplications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1pageHeight/title",
          "value": "pageHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1pageHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1creator/title",
          "value": "creator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1creator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "creator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1theme/title",
          "value": "theme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1theme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "theme"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/cssearchableitemattributeset/filesize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corespotlight/cssearchableitemattributeset/filesize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
