{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the mail or messages content represents a prioritized item.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/isPriority"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreSpotlight",
    "externalID": "c:objc(cs)CSSearchableItemAttributeSet(py)isPriority",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isPriority"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "isPriority"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "isPriority"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isPriority"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the value of this property is ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ", Apple Intelligence identified this email or message content as needing priority classification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet": {
      "abstract": [
        {
          "text": "The detailed metadata for a searchable item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableItemAttributeSet",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/isPriority": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the mail or messages content represents a prioritized item.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPriority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/isPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isPriority"
        }
      ],
      "role": "symbol",
      "title": "isPriority",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/ispriority"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/textContentSummary": {
      "abstract": [
        {
          "text": "A string that presents the Apple Intelligence summarization of this item.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textContentSummary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/textContentSummary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textContentSummary"
        }
      ],
      "role": "symbol",
      "title": "textContentSummary",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/textcontentsummary"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/transcribedTextContent": {
      "abstract": [
        {
          "text": "A string that represents the text the system transcribed.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transcribedTextContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/transcribedTextContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transcribedTextContent"
        }
      ],
      "role": "symbol",
      "title": "transcribedTextContent",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset/transcribedtextcontent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Describing-Apple-Intelligence-prioritization-and-summarization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/textContentSummary",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/transcribedTextContent"
      ],
      "title": "Describing Apple Intelligence prioritization and summarization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "isPriority"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Describing-Apple-Intelligence-prioritization-and-summarization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/textContentSummary",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet/transcribedTextContent"
              ],
              "title": "Describing Apple Intelligence prioritization and summarization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSNumber",
                    "text": "NSNumber"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "isPriority"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/title",
          "value": "CSSearchableItemAttributeSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1isPriority/title",
          "value": "isPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1isPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1textContentSummary/title",
          "value": "textContentSummary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1textContentSummary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textContentSummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1transcribedTextContent/title",
          "value": "transcribedTextContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet~1transcribedTextContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transcribedTextContent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/cssearchableitemattributeset/ispriority"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corespotlight/cssearchableitemattributeset/ispriority"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
