{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling422"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@IOSurfaceSubsampling@kIOSurfaceSubsampling422",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "subsampling422"
      }
    ],
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kIOSurfaceSubsampling422"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "IOSurfaceSubsampling.subsampling422"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "subsampling422"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceSubsampling"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceSubsampling"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceSubsampling",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacesubsampling"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling411": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subsampling411"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling411",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceSubsampling411"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceSubsampling.subsampling411",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacesubsampling/subsampling411"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling420": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subsampling420"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling420",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceSubsampling420"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceSubsampling.subsampling420",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacesubsampling/subsampling420"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling422": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subsampling422"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling422",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceSubsampling422"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceSubsampling.subsampling422",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacesubsampling/subsampling422"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsamplingNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subsamplingNone"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsamplingNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceSubsamplingNone"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceSubsampling.subsamplingNone",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacesubsampling/subsamplingnone"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsamplingUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subsamplingUnknown"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsamplingUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceSubsamplingUnknown"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceSubsampling.subsamplingUnknown",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacesubsampling/subsamplingunknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling411",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling420",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsamplingNone",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsamplingUnknown"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kIOSurfaceSubsampling422"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceSubsampling422"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iosurface/documentation/IOSurface",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling411",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsampling420",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsamplingNone",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling/subsamplingUnknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kIOSurfaceSubsampling422"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsampling422/title",
          "value": "kIOSurfaceSubsampling422"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsampling422/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceSubsampling422"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsampling411/title",
          "value": "kIOSurfaceSubsampling411"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsampling411/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceSubsampling411"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsamplingNone/title",
          "value": "kIOSurfaceSubsamplingNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsamplingNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceSubsamplingNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsampling420/title",
          "value": "kIOSurfaceSubsampling420"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsampling420/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceSubsampling420"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling/title",
          "value": "IOSurfaceSubsampling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceSubsampling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceSubsampling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsamplingUnknown/title",
          "value": "kIOSurfaceSubsamplingUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling~1subsamplingUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceSubsamplingUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurfacesubsampling/subsampling422"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/iosurfacesubsampling/subsampling422"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
