{
  "abstract": [
    {
      "text": "The trait that indicates a voice is a novelty voice.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits/isNoveltyVoice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVSpeechSynthesisVoiceTraits@AVSpeechSynthesisVoiceTraitIsNoveltyVoice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isNoveltyVoice"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVSpeechSynthesisVoice",
        "text": "AVSpeechSynthesisVoice"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVSpeechSynthesisVoiceTraits",
        "text": "Traits"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVSpeechSynthesisVoiceTraitIsNoveltyVoice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "isNoveltyVoice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isNoveltyVoice"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVSpeechSynthesisVoice",
              "text": "AVSpeechSynthesisVoice"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVSpeechSynthesisVoiceTraits",
              "text": "Traits"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An example of a novelty voice is a character’s voice in a game.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice": {
      "abstract": [
        {
          "text": "A distinct voice for use in speech synthesis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoice"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoice"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisVoice",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits": {
      "abstract": [
        {
          "text": "Traits that describe a voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Traits"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Traits"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisVoice.Traits",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/traits"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits/isNoveltyVoice": {
      "abstract": [
        {
          "text": "The trait that indicates a voice is a novelty voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNoveltyVoice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesisVoice",
          "text": "AVSpeechSynthesisVoice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVSpeechSynthesisVoiceTraits",
          "text": "Traits"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits/isNoveltyVoice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceTraitIsNoveltyVoice"
        }
      ],
      "role": "symbol",
      "title": "isNoveltyVoice",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/traits/isnoveltyvoice"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits/isPersonalVoice": {
      "abstract": [
        {
          "text": "The trait that indicates a voice is a personal voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPersonalVoice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesisVoice",
          "text": "AVSpeechSynthesisVoice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVSpeechSynthesisVoiceTraits",
          "text": "Traits"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits/isPersonalVoice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceTraitIsPersonalVoice"
        }
      ],
      "role": "symbol",
      "title": "isPersonalVoice",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/traits/ispersonalvoice"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceTraits/AVSpeechSynthesisVoiceTraitNone": {
      "abstract": [
        {
          "text": "The trait that indicates a voice is a regular voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceTraitNone"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceTraits/AVSpeechSynthesisVoiceTraitNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVSpeechSynthesisVoiceTraitNone",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoicetraits/avspeechsynthesisvoicetraitnone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-voice-trait",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits/isPersonalVoice"
      ],
      "title": "Inspecting a voice trait"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVSpeechSynthesisVoiceTraitIsNoveltyVoice"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceTraitIsNoveltyVoice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-voice-trait",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceTraits/AVSpeechSynthesisVoiceTraitNone",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits/isPersonalVoice"
              ],
              "title": "Inspecting a voice trait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVSpeechSynthesisVoiceTraitIsNoveltyVoice"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits~1isPersonalVoice/title",
          "value": "AVSpeechSynthesisVoiceTraitIsPersonalVoice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits~1isPersonalVoice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceTraitIsPersonalVoice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits/title",
          "value": "AVSpeechSynthesisVoiceTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice/title",
          "value": "AVSpeechSynthesisVoice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits~1isNoveltyVoice/title",
          "value": "AVSpeechSynthesisVoiceTraitIsNoveltyVoice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits~1isNoveltyVoice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceTraitIsNoveltyVoice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesisvoice/traits/isnoveltyvoice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesisvoice/traits/isnoveltyvoice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
