{
  "abstract": [
    {
      "text": "An error code that indicates network conditions changed such that the VPN connection needed to terminate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/unrecoverableNetworkChange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEVPNConnectionError@NEVPNConnectionErrorUnrecoverableNetworkChange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unrecoverableNetworkChange"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNConnectionErrorUnrecoverableNetworkChange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEVPNConnectionError.unrecoverableNetworkChange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unrecoverableNetworkChange"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError": {
      "abstract": [
        {
          "text": "Error codes specific to VPN connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNConnectionError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionError"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/authenticationFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the VPN server rejected the user credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/authenticationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorAuthenticationFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.authenticationFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/authenticationfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the configuration is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorConfigurationFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.configurationFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/configurationfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationNotFound": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the system couldn’t find a configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationNotFound"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorConfigurationNotFound"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.configurationNotFound",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/configurationnotfound"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/negotiationFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the negotiation failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "negotiationFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/negotiationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorNegotiationFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.negotiationFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/negotiationfailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/noNetworkAvailable": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN connection failed because the system isn’t connected to a network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noNetworkAvailable"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/noNetworkAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorNoNetworkAvailable"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.noNetworkAvailable",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/nonetworkavailable"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/overslept": {
      "abstract": [
        {
          "text": "An error code that indicates the system slept for an extended period of time, causing the VPN connection to terminate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overslept"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/overslept",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorOverslept"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.overslept",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/overslept"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/unrecoverableNetworkChange": {
      "abstract": [
        {
          "text": "An error code that indicates network conditions changed such that the VPN connection needed to terminate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrecoverableNetworkChange"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/unrecoverableNetworkChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNConnectionErrorUnrecoverableNetworkChange"
        }
      ],
      "role": "symbol",
      "title": "NEVPNConnectionError.unrecoverableNetworkChange",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnconnectionerror/unrecoverablenetworkchange"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/overslept",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/noNetworkAvailable",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/authenticationFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationNotFound",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/negotiationFailed"
      ],
      "title": "General error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNConnectionErrorUnrecoverableNetworkChange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorUnrecoverableNetworkChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/overslept",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/noNetworkAvailable",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/authenticationFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/configurationNotFound",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNConnectionError/negotiationFailed"
              ],
              "title": "General error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEVPNConnectionErrorUnrecoverableNetworkChange"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1authenticationFailed/title",
          "value": "NEVPNConnectionErrorAuthenticationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1authenticationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorAuthenticationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1unrecoverableNetworkChange/title",
          "value": "NEVPNConnectionErrorUnrecoverableNetworkChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1unrecoverableNetworkChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorUnrecoverableNetworkChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1negotiationFailed/title",
          "value": "NEVPNConnectionErrorNegotiationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1negotiationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorNegotiationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError/title",
          "value": "NEVPNConnectionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1configurationFailed/title",
          "value": "NEVPNConnectionErrorConfigurationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1configurationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorConfigurationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1noNetworkAvailable/title",
          "value": "NEVPNConnectionErrorNoNetworkAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1noNetworkAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorNoNetworkAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1overslept/title",
          "value": "NEVPNConnectionErrorOverslept"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1overslept/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorOverslept"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1configurationNotFound/title",
          "value": "NEVPNConnectionErrorConfigurationNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNConnectionError~1configurationNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNConnectionErrorConfigurationNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnconnectionerror/unrecoverablenetworkchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnconnectionerror/unrecoverablenetworkchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
