{
  "abstract": [
    {
      "text": "Returns a list of registered user accounts for your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/userAccounts(options:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "VideoSubscriberAccount",
    "externalID": "s:So20VSUserAccountManagerC015VideoSubscriberB0E12userAccounts7optionsSayAC0aB0VGSo0aB12QueryOptionsV_tYaKF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "userAccounts"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VSUserAccountManager",
        "text": "VSUserAccountManager"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@VSUserAccountQueryOptions",
        "text": "QueryOptions"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "async"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "throws"
      },
      {
        "kind": "text",
        "text": " -> ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V",
        "text": "VSUserAccount"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "Video Subscriber Account"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "userAccounts(options:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "userAccounts"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VSUserAccountManager",
              "text": "VSUserAccountManager"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/QueryOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VSUserAccountQueryOptions",
              "text": "QueryOptions"
            },
            {
              "kind": "text",
              "text": " = []) "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> ["
            },
            {
              "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V",
              "text": "VSUserAccount"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of options you specify to customize the user account query.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A list of registered user accounts for your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, this fetches and returns the list of registered user accounts on the current device. Provide the query option ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/QueryOptions/allDevices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to fetch the list of registered user accounts on all the devices the user has in their iCloud account.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount": {
      "abstract": [
        {
          "text": "Support TV provider and Apple TV app functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Subscriber Account",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct": {
      "abstract": [
        {
          "text": "An object that represents a user’s account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSUserAccount"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSUserAccount"
        }
      ],
      "role": "symbol",
      "title": "VSUserAccount",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager": {
      "abstract": [
        {
          "text": "The object that coordinates your app’s user account actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSUserAccountManager"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSUserAccountManager"
        }
      ],
      "role": "symbol",
      "title": "VSUserAccountManager",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccountmanager"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/QueryOptions": {
      "abstract": [
        {
          "text": "Constants that represent options you use to fetch a list of user accounts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QueryOptions"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/QueryOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QueryOptions"
        }
      ],
      "role": "symbol",
      "title": "VSUserAccountManager.QueryOptions",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccountmanager/queryoptions"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/QueryOptions/allDevices": {
      "abstract": [
        {
          "text": "A constant that indicates fetching user accounts from all the user’s iCloud devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allDevices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VSUserAccountManager",
          "text": "VSUserAccountManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSUserAccountQueryOptions",
          "text": "QueryOptions"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/QueryOptions/allDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSUserAccountQueryAllDevices"
        }
      ],
      "role": "symbol",
      "title": "allDevices",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccountmanager/queryoptions/alldevices"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/userAccounts(options:)": {
      "abstract": [
        {
          "text": "Returns a list of registered user accounts for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userAccounts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VSUserAccountManager",
          "text": "VSUserAccountManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSUserAccountQueryOptions",
          "text": "QueryOptions"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V",
          "text": "VSUserAccount"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/userAccounts(options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "userAccounts(options:)",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccountmanager/useraccounts(options:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-user-accounts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/QueryOptions"
      ],
      "title": "Getting user accounts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager~1QueryOptions~1allDevices/title",
          "value": "VSUserAccountQueryAllDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager~1QueryOptions~1allDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSUserAccountQueryAllDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager/title",
          "value": "VSUserAccountManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSUserAccountManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSUserAccountManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager~1QueryOptions/title",
          "value": "VSUserAccountQueryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager~1QueryOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSUserAccountQueryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager~1QueryOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSUserAccountQueryOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videosubscriberaccount/vsuseraccountmanager/useraccounts(options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
