{
  "abstract": [
    {
      "text": "Sets the title of the default/select button in the device selector panel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setPrompt(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOBluetoothDeviceSelectorController(im)setPrompt:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setPrompt"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setPrompt:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setPrompt(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setPrompt"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "prompt"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "String that appears in the default/select button in the device selector panel.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "prompt"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The prompt text should be localized for best user experience.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "NOTE: This method is only available in macOS 10.2.4 (Bluetooth v1.1) or later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController": {
      "abstract": [
        {
          "text": "A NSWindowController subclass to display a window to initiate pairing to other bluetooth devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorController"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSelectorController",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUID(_:)": {
      "abstract": [
        {
          "text": "Adds a UUID to the list of UUIDs that are used to validate the user’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAllowedUUID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothSDPUUID",
          "text": "IOBluetoothSDPUUID"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUID(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAllowedUUID:"
        }
      ],
      "role": "symbol",
      "title": "addAllowedUUID(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/addalloweduuid(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUIDArray(_:)": {
      "abstract": [
        {
          "text": "Adds an array of UUIDs to the list of UUIDs that are used to validate the user’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAllowedUUIDArray"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUIDArray(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAllowedUUIDArray:"
        }
      ],
      "role": "symbol",
      "title": "addAllowedUUIDArray(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/addalloweduuidarray(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/beginSheetModal(for:modalDelegate:didEnd:contextInfo:)": {
      "abstract": [
        {
          "text": "Runs the device selector panel as a sheet on the target window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSheetModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "modalDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/beginSheetModal(for:modalDelegate:didEnd:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "beginSheetModal(for:modalDelegate:didEnd:contextInfo:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/beginsheetmodal(for:modaldelegate:didend:contextinfo:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/clearAllowedUUIDs()": {
      "abstract": [
        {
          "text": "Resets the controller back to the default state where it will accept any device the user selects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearAllowedUUIDs"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/clearAllowedUUIDs()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearAllowedUUIDs"
        }
      ],
      "role": "symbol",
      "title": "clearAllowedUUIDs()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/clearalloweduuids()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getCancel()": {
      "abstract": [
        {
          "text": "Returns the title of the default/cancel button in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getCancel"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getCancel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getCancel"
        }
      ],
      "role": "symbol",
      "title": "getCancel()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getcancel()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getDescriptionText()": {
      "abstract": [
        {
          "text": "Returns the description text that appears in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getDescriptionText"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getDescriptionText()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getDescriptionText"
        }
      ],
      "role": "symbol",
      "title": "getDescriptionText()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getdescriptiontext()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getHeader()": {
      "abstract": [
        {
          "text": "Returns the header text that appears in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getHeader"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getHeader()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getHeader"
        }
      ],
      "role": "symbol",
      "title": "getHeader()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getheader()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getOptions()": {
      "abstract": [
        {
          "text": "Returns the option bits that control the panel’s behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getOptions"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothServiceBrowserControllerOptions",
          "text": "IOBluetoothServiceBrowserControllerOptions"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getOptions()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getOptions"
        }
      ],
      "role": "symbol",
      "title": "getOptions()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getoptions()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getPrompt()": {
      "abstract": [
        {
          "text": "Returns the title of the default/select button in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getPrompt"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getPrompt()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getPrompt"
        }
      ],
      "role": "symbol",
      "title": "getPrompt()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getprompt()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getResults()": {
      "abstract": [
        {
          "text": "Returns the result of the user’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getResults"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getResults()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getResults"
        }
      ],
      "role": "symbol",
      "title": "getResults()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getresults()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getSearchAttributes()": {
      "abstract": [
        {
          "text": "Returns the search attributes that control the panel’s search/inquiry behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getSearchAttributes"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOBluetoothDeviceSearchAttributes",
          "text": "IOBluetoothDeviceSearchAttributes"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getSearchAttributes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getSearchAttributes"
        }
      ],
      "role": "symbol",
      "title": "getSearchAttributes()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getsearchattributes()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getTitle()": {
      "abstract": [
        {
          "text": "Returns the title of the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getTitle"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getTitle()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getTitle"
        }
      ],
      "role": "symbol",
      "title": "getTitle()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/gettitle()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/runModal()": {
      "abstract": [
        {
          "text": "Runs the device selector panel in a modal session to allow the user to select a Bluetooth device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/runModal()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModal"
        }
      ],
      "role": "symbol",
      "title": "runModal()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/runmodal()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setCancel(_:)": {
      "abstract": [
        {
          "text": "Sets the title of the default/cancel button in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setCancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCancel:"
        }
      ],
      "role": "symbol",
      "title": "setCancel(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setcancel(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setDescriptionText(_:)": {
      "abstract": [
        {
          "text": "Sets the description text that appears in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDescriptionText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setDescriptionText(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDescriptionText:"
        }
      ],
      "role": "symbol",
      "title": "setDescriptionText(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setdescriptiontext(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setPrompt(_:)": {
      "abstract": [
        {
          "text": "Sets the title of the default/select button in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPrompt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setPrompt(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPrompt:"
        }
      ],
      "role": "symbol",
      "title": "setPrompt(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setprompt(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUID(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUIDArray(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/beginSheetModal(for:modalDelegate:didEnd:contextInfo:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/clearAllowedUUIDs()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getCancel()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getDescriptionText()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getHeader()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getOptions()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getPrompt()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getResults()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getSearchAttributes()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getTitle()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/runModal()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setCancel(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setDescriptionText(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setPrompt:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPrompt:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUID(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUIDArray(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/beginSheetModal(for:modalDelegate:didEnd:contextInfo:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/clearAllowedUUIDs()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getCancel()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getDescriptionText()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getHeader()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getOptions()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getPrompt()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getResults()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getSearchAttributes()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getTitle()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/runModal()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setCancel(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setDescriptionText(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setPrompt:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "prompt"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "String that appears in the default/select button in the device selector panel.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "prompt"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getSearchAttributes()/title",
          "value": "getSearchAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getSearchAttributes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getSearchAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getDescriptionText()/title",
          "value": "getDescriptionText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getDescriptionText()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getDescriptionText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1addAllowedUUIDArray(_:)/title",
          "value": "addAllowedUUIDArray:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1addAllowedUUIDArray(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAllowedUUIDArray:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController/title",
          "value": "IOBluetoothDeviceSelectorController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1clearAllowedUUIDs()/title",
          "value": "clearAllowedUUIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1clearAllowedUUIDs()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearAllowedUUIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setCancel(_:)/title",
          "value": "setCancel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setCancel(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setCancel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getTitle()/title",
          "value": "getTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getTitle()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getResults()/title",
          "value": "getResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getResults()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getCancel()/title",
          "value": "getCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getCancel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1addAllowedUUID(_:)/title",
          "value": "addAllowedUUID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1addAllowedUUID(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAllowedUUID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1beginSheetModal(for:modalDelegate:didEnd:contextInfo:)/title",
          "value": "beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1beginSheetModal(for:modalDelegate:didEnd:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1runModal()/title",
          "value": "runModal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1runModal()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getPrompt()/title",
          "value": "getPrompt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getPrompt()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getPrompt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setPrompt(_:)/title",
          "value": "setPrompt:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setPrompt(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPrompt:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getOptions()/title",
          "value": "getOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getOptions()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setDescriptionText(_:)/title",
          "value": "setDescriptionText:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setDescriptionText(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDescriptionText:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getHeader()/title",
          "value": "getHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getHeader()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getHeader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setprompt(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setprompt(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
