{
  "abstract": [
    {
      "text": "A link (an ",
      "type": "text"
    },
    {
      "code": "href",
      "type": "codeVoice"
    },
    {
      "text": ") was clicked.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WebNavigationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/linkClicked"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WebNavigationType@WebNavigationTypeLinkClicked",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "linkClicked"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WebNavigationTypeLinkClicked"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WebNavigationType.linkClicked"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "linkClicked"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebActionNavigationTypeKey": {
      "abstract": [
        {
          "text": "The navigation type of the action. Can be any of the values defined in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " below.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebActionNavigationTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebActionNavigationTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebActionNavigationTypeKey"
        }
      ],
      "role": "symbol",
      "title": "WebActionNavigationTypeKey",
      "type": "topic",
      "url": "/documentation/webkit/webactionnavigationtypekey"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebNavigationType": {
      "abstract": [
        {
          "text": "Possible values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebActionNavigationTypeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key that appears in an action dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebNavigationType"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebNavigationType"
        }
      ],
      "role": "symbol",
      "title": "WebNavigationType",
      "type": "topic",
      "url": "/documentation/webkit/webnavigationtype"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/backForward": {
      "abstract": [
        {
          "text": "The user clicked back or forward button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backForward"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/backForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebNavigationTypeBackForward"
        }
      ],
      "role": "symbol",
      "title": "WebNavigationType.backForward",
      "type": "topic",
      "url": "/documentation/webkit/webnavigationtype/backforward"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/formResubmitted": {
      "abstract": [
        {
          "text": "A form was resubmitted (through a back, forward or reload action).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formResubmitted"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/formResubmitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebNavigationTypeFormResubmitted"
        }
      ],
      "role": "symbol",
      "title": "WebNavigationType.formResubmitted",
      "type": "topic",
      "url": "/documentation/webkit/webnavigationtype/formresubmitted"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/formSubmitted": {
      "abstract": [
        {
          "text": "A form was submitted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formSubmitted"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/formSubmitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebNavigationTypeFormSubmitted"
        }
      ],
      "role": "symbol",
      "title": "WebNavigationType.formSubmitted",
      "type": "topic",
      "url": "/documentation/webkit/webnavigationtype/formsubmitted"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/linkClicked": {
      "abstract": [
        {
          "text": "A link (an ",
          "type": "text"
        },
        {
          "code": "href",
          "type": "codeVoice"
        },
        {
          "text": ") was clicked.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkClicked"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/linkClicked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebNavigationTypeLinkClicked"
        }
      ],
      "role": "symbol",
      "title": "WebNavigationType.linkClicked",
      "type": "topic",
      "url": "/documentation/webkit/webnavigationtype/linkclicked"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/other": {
      "abstract": [
        {
          "text": "Navigation is taking place for some other reason.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebNavigationTypeOther"
        }
      ],
      "role": "symbol",
      "title": "WebNavigationType.other",
      "type": "topic",
      "url": "/documentation/webkit/webnavigationtype/other"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/reload": {
      "abstract": [
        {
          "text": "The user hit the reload button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reload"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/reload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebNavigationTypeReload"
        }
      ],
      "role": "symbol",
      "title": "WebNavigationType.reload",
      "type": "topic",
      "url": "/documentation/webkit/webnavigationtype/reload"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/formSubmitted",
        "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/backForward",
        "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/reload",
        "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/formResubmitted",
        "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/other"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WebNavigationTypeLinkClicked"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationTypeLinkClicked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WebNavigationType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/formSubmitted",
                "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/backForward",
                "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/reload",
                "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/formResubmitted",
                "doc://com.apple.webkit/documentation/WebKit/WebNavigationType/other"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WebNavigationTypeLinkClicked"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1formSubmitted/title",
          "value": "WebNavigationTypeFormSubmitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1formSubmitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationTypeFormSubmitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1formResubmitted/title",
          "value": "WebNavigationTypeFormResubmitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1formResubmitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationTypeFormResubmitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1backForward/title",
          "value": "WebNavigationTypeBackForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1backForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationTypeBackForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionNavigationTypeKey/title",
          "value": "WebActionNavigationTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebActionNavigationTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebActionNavigationTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1linkClicked/title",
          "value": "WebNavigationTypeLinkClicked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1linkClicked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationTypeLinkClicked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1reload/title",
          "value": "WebNavigationTypeReload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1reload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationTypeReload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType/title",
          "value": "WebNavigationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1other/title",
          "value": "WebNavigationTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebNavigationType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebNavigationTypeOther"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webnavigationtype/linkclicked"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/webnavigationtype/linkclicked"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
