{
  "abstract": [
    {
      "text": "A transparent black color ",
      "type": "text"
    },
    {
      "code": "(0,0,0,0)",
      "type": "codeVoice"
    },
    {
      "text": " for texture values outside the border.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/transparentBlack"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLSamplerBorderColor@MTLSamplerBorderColorTransparentBlack",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "transparentBlack"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLSamplerBorderColorTransparentBlack"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLSamplerBorderColor.transparentBlack"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "transparentBlack"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor": {
      "abstract": [
        {
          "text": "Out-of-range texture coordinates return the value specified by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clampToBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressModeClampToBorderColor"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode.clampToBorderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode/clamptobordercolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor": {
      "abstract": [
        {
          "text": "Values that determine the border color for clamped texture values when the sampler address mode is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColor"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerBorderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueBlack": {
      "abstract": [
        {
          "text": "An opaque black color ",
          "type": "text"
        },
        {
          "code": "(0,0,0,1)",
          "type": "codeVoice"
        },
        {
          "text": " for texture values outside the border",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opaqueBlack"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueBlack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColorOpaqueBlack"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerBorderColor.opaqueBlack",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor/opaqueblack"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueWhite": {
      "abstract": [
        {
          "text": "An opaque white color ",
          "type": "text"
        },
        {
          "code": "(1,1,1,1)",
          "type": "codeVoice"
        },
        {
          "text": " for texture values outside the border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opaqueWhite"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueWhite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColorOpaqueWhite"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerBorderColor.opaqueWhite",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor/opaquewhite"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/transparentBlack": {
      "abstract": [
        {
          "text": "A transparent black color ",
          "type": "text"
        },
        {
          "code": "(0,0,0,0)",
          "type": "codeVoice"
        },
        {
          "text": " for texture values outside the border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transparentBlack"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/transparentBlack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColorTransparentBlack"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerBorderColor.transparentBlack",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor/transparentblack"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Border-Color-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueBlack",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueWhite"
      ],
      "title": "Specifying Border Color Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLSamplerBorderColorTransparentBlack"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColorTransparentBlack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Border-Color-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueBlack",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueWhite"
              ],
              "title": "Specifying Border Color Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLSamplerBorderColorTransparentBlack"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToBorderColor/title",
          "value": "MTLSamplerAddressModeClampToBorderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToBorderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeClampToBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor/title",
          "value": "MTLSamplerBorderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1opaqueBlack/title",
          "value": "MTLSamplerBorderColorOpaqueBlack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1opaqueBlack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColorOpaqueBlack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1transparentBlack/title",
          "value": "MTLSamplerBorderColorTransparentBlack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1transparentBlack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColorTransparentBlack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1opaqueWhite/title",
          "value": "MTLSamplerBorderColorOpaqueWhite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1opaqueWhite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColorOpaqueWhite"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlsamplerbordercolor/transparentblack"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlsamplerbordercolor/transparentblack"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
