{
  "abstract": [
    {
      "text": "Socket values you specify to configure Rosetta’s caching capabilities.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Virtualization",
    "externalID": "s:So28VZLinuxRosettaDirectoryShareC14VirtualizationE14CachingOptionsO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CachingOptions"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CachingOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VZLinuxRosettaDirectoryShare.CachingOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CachingOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare": {
      "abstract": [
        {
          "text": "The Linux directory share for Rosetta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZLinuxRosettaDirectoryShare"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZLinuxRosettaDirectoryShare"
        }
      ],
      "role": "symbol",
      "title": "VZLinuxRosettaDirectoryShare",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum": {
      "abstract": [
        {
          "text": "Socket values you specify to configure Rosetta’s caching capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CachingOptions"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CachingOptions"
        }
      ],
      "role": "symbol",
      "title": "VZLinuxRosettaDirectoryShare.CachingOptions",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/abstractSocket(_:)": {
      "abstract": [
        {
          "text": "The value that describes an abstract socket with a name you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "abstractSocket"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/abstractSocket(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VZLinuxRosettaDirectoryShare.CachingOptions.abstractSocket(_:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum/abstractsocket(_:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/defaultUnixSocket": {
      "abstract": [
        {
          "text": "The options to use for a default UNIX domain socket.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultUnixSocket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZLinuxRosettaDirectoryShare",
          "text": "VZLinuxRosettaDirectoryShare"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So28VZLinuxRosettaDirectoryShareC14VirtualizationE14CachingOptionsO",
          "text": "CachingOptions"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/defaultUnixSocket",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultUnixSocket",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum/defaultunixsocket"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/maximumNameLength": {
      "abstract": [
        {
          "text": "The maximum length of the name of an abstract socket.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumNameLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/maximumNameLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "maximumNameLength",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum/maximumnamelength"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/maximumPathLength": {
      "abstract": [
        {
          "text": "The maximum length of the path to a UNIX domain socket.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumPathLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/maximumPathLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "maximumPathLength",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum/maximumpathlength"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/unixSocket(_:)": {
      "abstract": [
        {
          "text": "The value that describes an UNIX domain socket at a path that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unixSocket"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/unixSocket(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VZLinuxRosettaDirectoryShare.CachingOptions.unixSocket(_:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum/unixsocket(_:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/cachingOptions-swift.property": {
      "abstract": [
        {
          "text": "The value that enables translation caching and configures the socket communication type for Rosetta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cachingOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZLinuxRosettaDirectoryShare",
          "text": "VZLinuxRosettaDirectoryShare"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So28VZLinuxRosettaDirectoryShareC14VirtualizationE14CachingOptionsO",
          "text": "CachingOptions"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/cachingOptions-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "cachingOptions",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.property"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/setCachingOptions(_:)": {
      "abstract": [
        {
          "text": "Sets the Rosetta caching options using the options you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCachingOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZLinuxRosettaDirectoryShare",
          "text": "VZLinuxRosettaDirectoryShare"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So28VZLinuxRosettaDirectoryShareC14VirtualizationE14CachingOptionsO",
          "text": "CachingOptions"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/setCachingOptions(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setCachingOptions(_:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/setcachingoptions(_:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta": {
      "abstract": [
        {
          "text": "Run x86_64 Linux binaries under ARM Linux on Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta",
      "kind": "article",
      "role": "article",
      "title": "Running Intel Binaries in Linux VMs with Rosetta",
      "type": "topic",
      "url": "/documentation/virtualization/running-intel-binaries-in-linux-vms-with-rosetta"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-ahead-of-time-AOT-caching-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/cachingOptions-swift.property",
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/setCachingOptions(_:)"
      ],
      "title": "Setting the ahead of time (AOT) caching options"
    }
  ],
  "topicSections": [
    {
      "anchor": "Socket-types",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/abstractSocket(_:)",
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/unixSocket(_:)"
      ],
      "title": "Socket types"
    },
    {
      "anchor": "Type-properties",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/defaultUnixSocket",
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/maximumNameLength",
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/maximumPathLength"
      ],
      "title": "Type properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaDirectoryShare/title",
          "value": "VZLinuxRosettaDirectoryShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaDirectoryShare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxRosettaDirectoryShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaDirectoryShare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxRosettaDirectoryShare"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
