{
  "abstract": [
    {
      "text": "Resolves the requested lock status (locked or unlocked).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling/resolveLocked(for:with:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INSetCarLockStatusIntentHandling(im)resolveLockedForSetCarLockStatus:withCompletion:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resolveLocked"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INSetCarLockStatusIntent",
        "text": "INSetCarLockStatusIntent"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
        "text": "INBooleanResolutionResult"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "resolveLockedForSetCarLockStatus:withCompletion:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "resolveLocked(for:with:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resolveLocked"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INSetCarLockStatusIntent",
              "text": "INSetCarLockStatusIntent"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INBooleanResolutionResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
              "text": "INBooleanResolutionResult"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resolveLocked"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INSetCarLockStatusIntent",
              "text": "INSetCarLockStatusIntent"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INBooleanResolutionResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
              "text": "INBooleanResolutionResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The intent object containing details about the user’s request. Use this object to get the initial information, if any, provided by the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "intent"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block to execute with the resolution. You must execute this block at some point during your implementation of this method. This block has no return value and takes the following parameter:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The object containing the details of your proposed resolution. For successful resolutions, create a resolution object with the requested lock status (locked or unlocked).",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "resolutionResult",
                        "type": "text"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completion"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this method to verify the requested lock status. This status is a Boolean value: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " indicates that the car should be locked, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " indicates it should be unlocked.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBooleanResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a Boolean value associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBooleanResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBooleanResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBooleanResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INBooleanResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inbooleanresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntent": {
      "abstract": [
        {
          "text": "A request to lock or unlock the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetCarLockStatusIntent",
      "type": "topic",
      "url": "/documentation/intents/insetcarlockstatusintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for requesting to lock or unlock a car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetCarLockStatusIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetcarlockstatusintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling/resolveCarName(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the name of the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveCarName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetCarLockStatusIntent",
          "text": "INSetCarLockStatusIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpeakableStringResolutionResult",
          "text": "INSpeakableStringResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling/resolveCarName(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveCarNameForSetCarLockStatus:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveCarName(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetcarlockstatusintenthandling/resolvecarname(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling/resolveLocked(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested lock status (locked or unlocked).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveLocked"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetCarLockStatusIntent",
          "text": "INSetCarLockStatusIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
          "text": "INBooleanResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling/resolveLocked(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveLockedForSetCarLockStatus:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveLocked(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetcarlockstatusintenthandling/resolvelocked(for:with:)"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Resolving-the-Intent-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling/resolveCarName(for:with:)"
      ],
      "title": "Resolving the Intent Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "resolveLockedForSetCarLockStatus:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveLockedForSetCarLockStatus:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Resolving-the-Intent-Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling/resolveCarName(for:with:)"
              ],
              "title": "Resolving the Intent Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "resolveLockedForSetCarLockStatus:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INSetCarLockStatusIntent",
                    "text": "INSetCarLockStatusIntent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "intent"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withCompletion:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INBooleanResolutionResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
                    "text": "INBooleanResolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "resolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The intent object containing details about the user’s request. Use this object to get the initial information, if any, provided by the user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "intent"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The block to execute with the resolution. You must execute this block at some point during your implementation of this method. This block has no return value and takes the following parameter:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The object containing the details of your proposed resolution. For successful resolutions, create a resolution object with the requested lock status (locked or unlocked).",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "resolutionResult",
                              "type": "text"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntent/title",
          "value": "INSetCarLockStatusIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling~1resolveLocked(for:with:)/title",
          "value": "resolveLockedForSetCarLockStatus:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling~1resolveLocked(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveLockedForSetCarLockStatus:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling/title",
          "value": "INSetCarLockStatusIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBooleanResolutionResult/title",
          "value": "INBooleanResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBooleanResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBooleanResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBooleanResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBooleanResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling~1resolveCarName(for:with:)/title",
          "value": "resolveCarNameForSetCarLockStatus:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling~1resolveCarName(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveCarNameForSetCarLockStatus:withCompletion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insetcarlockstatusintenthandling/resolvelocked(for:with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insetcarlockstatusintenthandling/resolvelocked(for:with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
