{
  "abstract": [
    {
      "text": "A required argument was not provided.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/badArgument"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CFNetServicesError@kCFNetServicesErrorBadArgument",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "badArgument"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFNetServicesErrorBadArgument"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CFNetServicesError.badArgument"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "badArgument"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError": {
      "abstract": [
        {
          "text": "Error codes that may be returned by CFNetServices functions or passed to CFNetServices callback functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServicesError"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServicesError"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/badArgument": {
      "abstract": [
        {
          "text": "A required argument was not provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badArgument"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/badArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetServicesErrorBadArgument"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError.badArgument",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror/badargument"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/cancel": {
      "abstract": [
        {
          "text": "The search or service was canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/cancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetServicesErrorCancel"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError.cancel",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror/cancel"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/collision": {
      "abstract": [
        {
          "text": "An attempt was made to use a name that is already in use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collision"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/collision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetServicesErrorCollision"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError.collision",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror/collision"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/inProgress": {
      "abstract": [
        {
          "text": "A search is already in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetServicesErrorInProgress"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError.inProgress",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror/inprogress"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/invalid": {
      "abstract": [
        {
          "text": "Invalid data was passed to a CFNetServices function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetServicesErrorInvalid"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError.invalid",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror/invalid"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/notFound": {
      "abstract": [
        {
          "text": "Not used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFound"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/notFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetServicesErrorNotFound"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError.notFound",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror/notfound"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/timeout": {
      "abstract": [
        {
          "text": "Resolution failed because the timeout was reached.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeout"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/timeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetServicesErrorTimeout"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError.timeout",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror/timeout"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/unknown": {
      "abstract": [
        {
          "text": "An unknown CFNetService error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetServicesErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError.unknown",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/unknown",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/collision",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/notFound",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/inProgress",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/cancel",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/invalid",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/timeout"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFNetServicesErrorBadArgument"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServicesErrorBadArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/unknown",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/collision",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/notFound",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/inProgress",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/cancel",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/invalid",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError/timeout"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCFNetServicesErrorBadArgument"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError/title",
          "value": "CFNetServicesError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServicesError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServicesError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1collision/title",
          "value": "kCFNetServicesErrorCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1collision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServicesErrorCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1invalid/title",
          "value": "kCFNetServicesErrorInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServicesErrorInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1cancel/title",
          "value": "kCFNetServicesErrorCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1cancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServicesErrorCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1unknown/title",
          "value": "kCFNetServicesErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServicesErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1notFound/title",
          "value": "kCFNetServicesErrorNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1notFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServicesErrorNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1timeout/title",
          "value": "kCFNetServicesErrorTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1timeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServicesErrorTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1inProgress/title",
          "value": "kCFNetServicesErrorInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServicesErrorInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1badArgument/title",
          "value": "kCFNetServicesErrorBadArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError~1badArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetServicesErrorBadArgument"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetserviceserror/badargument"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetserviceserror/badargument"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
