{
  "abstract": [
    {
      "text": "An option indicating the system should display a button for in-app notification settings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/providesAppNotificationSettings"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UNAuthorizationOptions@UNAuthorizationOptionProvidesAppNotificationSettings",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "providesAppNotificationSettings"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UNAuthorizationOptions",
        "text": "UNAuthorizationOptions"
      }
    ],
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UNAuthorizationOptionProvidesAppNotificationSettings"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "providesAppNotificationSettings"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "providesAppNotificationSettings"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UNAuthorizationOptions",
              "text": "UNAuthorizationOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions": {
      "abstract": [
        {
          "text": "Options that determine the authorized features of local and remote notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptions"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptions"
        }
      ],
      "role": "symbol",
      "title": "UNAuthorizationOptions",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationoptions"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/alert": {
      "abstract": [
        {
          "text": "The ability to display alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/alert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptionAlert"
        }
      ],
      "role": "symbol",
      "title": "alert",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationoptions/alert"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/badge": {
      "abstract": [
        {
          "text": "The ability to update the app’s badge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/badge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptionBadge"
        }
      ],
      "role": "symbol",
      "title": "badge",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationoptions/badge"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/carPlay": {
      "abstract": [
        {
          "text": "The ability to display notifications in a CarPlay environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/carPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptionCarPlay"
        }
      ],
      "role": "symbol",
      "title": "carPlay",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationoptions/carplay"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/criticalAlert": {
      "abstract": [
        {
          "text": "The ability to play sounds for critical alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "criticalAlert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/criticalAlert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptionCriticalAlert"
        }
      ],
      "role": "symbol",
      "title": "criticalAlert",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationoptions/criticalalert"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/providesAppNotificationSettings": {
      "abstract": [
        {
          "text": "An option indicating the system should display a button for in-app notification settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providesAppNotificationSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/providesAppNotificationSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptionProvidesAppNotificationSettings"
        }
      ],
      "role": "symbol",
      "title": "providesAppNotificationSettings",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationoptions/providesappnotificationsettings"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/provisional": {
      "abstract": [
        {
          "text": "The ability to post noninterrupting notifications provisionally to the Notification Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provisional"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/provisional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptionProvisional"
        }
      ],
      "role": "symbol",
      "title": "provisional",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationoptions/provisional"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/sound": {
      "abstract": [
        {
          "text": "The ability to play sounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/sound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptionSound"
        }
      ],
      "role": "symbol",
      "title": "sound",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationoptions/sound"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/badge",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/sound",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/alert",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/carPlay",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/criticalAlert",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/provisional"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UNAuthorizationOptionProvidesAppNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptionProvidesAppNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.usernotifications/documentation/UserNotifications",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/badge",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/sound",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/alert",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/carPlay",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/criticalAlert",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/provisional"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UNAuthorizationOptionProvidesAppNotificationSettings"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1criticalAlert/title",
          "value": "UNAuthorizationOptionCriticalAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1criticalAlert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptionCriticalAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1alert/title",
          "value": "UNAuthorizationOptionAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1alert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptionAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions/title",
          "value": "UNAuthorizationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1carPlay/title",
          "value": "UNAuthorizationOptionCarPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1carPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptionCarPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1providesAppNotificationSettings/title",
          "value": "UNAuthorizationOptionProvidesAppNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1providesAppNotificationSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptionProvidesAppNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1badge/title",
          "value": "UNAuthorizationOptionBadge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1badge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptionBadge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1sound/title",
          "value": "UNAuthorizationOptionSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1sound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptionSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1provisional/title",
          "value": "UNAuthorizationOptionProvisional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1provisional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptionProvisional"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/unauthorizationoptions/providesappnotificationsettings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/unauthorizationoptions/providesappnotificationsettings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
