{
  "abstract": [
    {
      "text": "Use the latest API to support In-App Purchases in new or existing apps, or the original API to support In-App Purchases in earlier operating systems.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/choosing-a-storekit-api-for-in-app-purchases"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Choosing a StoreKit API for In-App Purchases"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The StoreKit framework provides two APIs to implement a store in your app and offer in-app purchases:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is a Swift-based API that provides App Store-signed transactions in JSON Web Signature (JWS) format, available starting in iOS 15, macOS 12, tvOS 15, watchOS 8, and visionOS 1.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " provides transaction information using App Store receipts, available starting in iOS 3, macOS 10.7, tvOS 9, watchOS 6.2, and visionOS 1.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " is deprecated.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "If your app has a minimum required operating system that the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " API supports, use this API to take advantage of Swift concurrency and simplified in-app purchase workflows. Use this API for visionOS apps that use multiple scenes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to maintain and update app versions that have a minimum required operating system of the following versions: macOS 11 or earlier, iOS 14 or earlier, iPadOS 14 or earlier, tvOS 14 or earlier, or watchOS 7 or earlier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An app can use both the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " API and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the app runs in iOS 15, macOS 12, tvOS 15, watchOS 8, and visionOS 1 or later. However, only the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " API supports multi-scene apps for visionOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Both APIs provide access to your data in the App Store, such as your configured in-app purchases and transaction information for your customers. In-app purchases that users make using either API are fully available to both APIs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Use-the-In-App-Purchase-API-to-access-new-features",
          "level": 3,
          "text": "Use the In-App Purchase API to access new features",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following features are available only with the Swift-based ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " APIs:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/storekit-views",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", which provide the UI to build a store in your app",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Refund request sheets, such as ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/beginRefundRequest(for:in:)-65tph",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", that enable customers to request refunds",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Information about a subscription’s renewal status, such as auto-renew preferences. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionInfo/Status-swift.struct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Information about available promotional offers and a subscriber’s eligibility for an introductory offer. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionInfo",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Deferring or suppressing Billing Issue messages that the system displays. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Presenting the App Store sheet for managing subscriptions. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/AppStore/showManageSubscriptions(in:subscriptionGroupID:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Transaction information in JSON Web Signature (JWS) format. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Use-the-Original-API-to-support-certain-features",
          "level": 3,
          "text": "Use the Original API to support certain features",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You might need to use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the following features, if your app supports them:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Promoting in-app purchases in apps that run in iOS 11 through 16.3. For more informaton, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/promoting-in-app-purchases",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". For information about this feature in iOS 16.4, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-promoted-in-app-purchases-in-your-app",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The Volume Purchase Program (VPP). For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/DeviceManagement",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/DeviceManagement": {
      "abstract": [
        {
          "text": "Manage your organization’s devices remotely.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/DeviceManagement",
      "kind": "symbol",
      "role": "collection",
      "title": "Device Management",
      "type": "topic",
      "url": "/documentation/DeviceManagement"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/AppStore/showManageSubscriptions(in:subscriptionGroupID:)": {
      "abstract": [
        {
          "text": "Presents the App Store sheet for managing subscriptions for a subscription group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showManageSubscriptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscriptionGroupID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/AppStore/showManageSubscriptions(in:subscriptionGroupID:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "showManageSubscriptions(in:subscriptionGroupID:)",
      "type": "topic",
      "url": "/documentation/storekit/appstore/showmanagesubscriptions(in:subscriptiongroupid:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Message": {
      "abstract": [
        {
          "text": "An instance for receiving and displaying App Store messages in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Message"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Message"
        }
      ],
      "role": "symbol",
      "title": "Message",
      "type": "topic",
      "url": "/documentation/storekit/message"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionInfo": {
      "abstract": [
        {
          "text": "Information about an auto-renewable subscription, such as its status, period, subscription group, and subscription offer details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SubscriptionInfo"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SubscriptionInfo"
        }
      ],
      "role": "symbol",
      "title": "Product.SubscriptionInfo",
      "type": "topic",
      "url": "/documentation/storekit/product/subscriptioninfo"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionInfo/Status-swift.struct": {
      "abstract": [
        {
          "text": "The renewal status information for an auto-renewable subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionInfo/Status-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "role": "symbol",
      "title": "Product.SubscriptionInfo.Status",
      "type": "topic",
      "url": "/documentation/storekit/product/subscriptioninfo/status-swift.struct"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction": {
      "abstract": [
        {
          "text": "Information that represents the customer’s purchase of a product in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Transaction"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Transaction"
        }
      ],
      "role": "symbol",
      "title": "Transaction",
      "type": "topic",
      "url": "/documentation/storekit/transaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction/beginRefundRequest(for:in:)-65tph": {
      "abstract": [
        {
          "text": "Presents the refund request sheet for the specified transaction in a window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginRefundRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV19RefundRequestStatusO",
          "text": "RefundRequestStatus"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/beginRefundRequest(for:in:)-65tph",
      "kind": "symbol",
      "role": "symbol",
      "title": "beginRefundRequest(for:in:)",
      "type": "topic",
      "url": "/documentation/storekit/transaction/beginrefundrequest(for:in:)-65tph"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase": {
      "abstract": [
        {
          "text": "Offer additional content and services in your app using the Original In-App Purchase API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original API for In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/original-api-for-in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/promoting-in-app-purchases": {
      "abstract": [
        {
          "text": "Show promoted In-App Purchases on your product page and handle purchases that customers initiate on the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/promoting-in-app-purchases",
      "kind": "article",
      "role": "article",
      "title": "Promoting In-App Purchases",
      "type": "topic",
      "url": "/documentation/storekit/promoting-in-app-purchases"
    },
    "doc://com.apple.storekit/documentation/StoreKit/storekit-views": {
      "abstract": [
        {
          "text": "Display a customizable In-App Purchase store using StoreKit views for SwiftUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/storekit-views",
      "kind": "article",
      "role": "collectionGroup",
      "title": "StoreKit views",
      "type": "topic",
      "url": "/documentation/storekit/storekit-views"
    },
    "doc://com.apple.storekit/documentation/StoreKit/supporting-promoted-in-app-purchases-in-your-app": {
      "abstract": [
        {
          "text": "Display promoted In-App Purchases on your product page and handle purchases that users initiate on the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-promoted-in-app-purchases-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting promoted In-App Purchases in your app",
      "type": "topic",
      "url": "/documentation/storekit/supporting-promoted-in-app-purchases-in-your-app"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase"
              ],
              "title": "Deprecated"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/choosing-a-storekit-api-for-in-app-purchases"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/choosing-a-storekit-api-for-in-app-purchases"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
