{
  "abstract": [
    {
      "text": "Recreate the byte array for version 3 postbacks that win and don’t win attribution.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution",
        "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork",
        "doc://com.apple.storekit/documentation/StoreKit/verifying-an-install-validation-postback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/combining-parameters-for-skadnetwork-3-postbacks"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Combining parameters for SKAdNetwork 3 postbacks"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Check your postback’s version, and use the version-specific instructions to combine the parameters to validate the postback. The order of the parameters depends on the version of the postback you receive.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To verify the signature, combine the postback parameter values in this order for a version 3 postback:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "version",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "ad-network-id",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "campaign-id",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "app-id",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "transaction-id",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "redownload",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (Use the strings ",
                      "type": "text"
                    },
                    {
                      "code": "“true”",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "“false”",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to represent the Boolean value of the redownload parameter.)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "source-app-id",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "fidelity-type",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "did-win",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Include ",
              "type": "text"
            },
            {
              "code": "source-app-id",
              "type": "codeVoice"
            },
            {
              "text": " only if you receive it in the postback. Note that the signature doesn’t include a conversion value, even if it’s present in the postback. Postbacks that win the attribution have a ",
              "type": "text"
            },
            {
              "code": "did-win",
              "type": "codeVoice"
            },
            {
              "text": " value of ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ". Postbacks that don’t win the attribution have a ",
              "type": "text"
            },
            {
              "code": "did-win",
              "type": "codeVoice"
            },
            {
              "text": " value of ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ", and don’t include ",
              "type": "text"
            },
            {
              "code": "source-app-id",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example of the UTF-8 string includes ",
              "type": "text"
            },
            {
              "code": "source-app-id:",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "version + '\\u2063' + ad-network-id + '\\u2063' + campaign-id + '\\u2063' + app-id + '\\u2063' + transaction-id + '\\u2063' + redownload + '\\u2063' + source-app-id + '\\u2063' + fidelity-type + '\\u2063' + did-win",
            " "
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The following example of the UTF-8 string doesn’t include ",
              "type": "text"
            },
            {
              "code": "source-app-id:",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "version + '\\u2063' + ad-network-id + '\\u2063' + campaign-id + '\\u2063' + app-id + '\\u2063' + transaction-id + '\\u2063' + redownload + '\\u2063' + fidelity-type + '\\u2063' + did-win",
            ""
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "anchor": "Receive-the-winning-postback-with-attribution",
          "level": 3,
          "text": "Receive the winning postback with attribution",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following JSON example shows a version 3 install-validation postback the device sends to an ad network that wins the attribution. This example contains all possible parameters and a valid signature:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{ ",
            "  \"version\": \"3.0\", ",
            "  \"ad-network-id\": \"example123.skadnetwork\", ",
            "  \"campaign-id\": 42, ",
            "  \"transaction-id\": \"6aafb7a5-0170-41b5-bbe4-fe71dedf1e28\", ",
            "  \"app-id\": 525463029, ",
            "  \"attribution-signature\": \"MEYCIQD5eq3AUlamORiGovqFiHWI4RZT/PrM3VEiXUrsC+M51wIhAPMANZA9c07raZJ64gVaXhB9+9yZj/X6DcNxONdccQij\", ",
            "  \"redownload\": true, ",
            "  \"source-app-id\": 1234567891, ",
            "  \"fidelity-type\": 1, ",
            "  \"conversion-value\": 20,",
            "  \"did-win\": true",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "anchor": "Receive-a-nonwinning-postback-without-attribution",
          "level": 3,
          "text": "Receive a nonwinning postback, without attribution",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 14.6 and later, ad networks that sign ads with version 3 may receive a postback for their qualifying ad impression that don’t win the attribution. Such postbacks have a ",
              "type": "text"
            },
            {
              "code": "did-win",
              "type": "codeVoice"
            },
            {
              "text": " value of ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ", and don’t include ",
              "type": "text"
            },
            {
              "code": "source-app-id",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "conversion-value",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example shows a version 3 postback for an ad that doesn’t win the attribution. This example contains all the parameters the system includes in a nonwinning postback:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{ ",
            "  \"version\": \"3.0\",",
            "  \"ad-network-id\": \"example123.skadnetwork\",",
            "  \"campaign-id\": 42,",
            "  \"transaction-id\": \"f9ac267a-a889-44ce-b5f7-0166d11461f0\",",
            "  \"app-id\": 525463029,",
            "  \"attribution-signature\": \"MEUCIQDDetUtkyc/MiQvVJ5I6HIO1E7l598572Wljot2Onzd4wIgVJLzVcyAV+TXksGNoa0DTMXEPgNPeHCmD4fw1ABXX0g=\",",
            "  \"redownload\": true,",
            "  \"fidelity-type\": 1,",
            "  \"did-win\": false",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Up to five ad networks may receive a nonwinning postback. A single ad network can receive at most one postback per advertised app, per conversion. For example, if the device registers three qualifying ad impressions from your ad network, you receive only one postback.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your ad network wins the attribution, you only receive the winning postback, even if the device registers other qualifying impressions for your ad.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about ad impressions qualifying for attribution, and receiving winning or nonwinning postbacks, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/receiving-ad-attributions-and-postbacks",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork": {
      "abstract": [
        {
          "text": "A class that validates advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdNetwork"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdNetwork"
        }
      ],
      "role": "symbol",
      "title": "SKAdNetwork",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution": {
      "abstract": [
        {
          "text": "Validate advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ad network attribution",
      "type": "topic",
      "url": "/documentation/storekit/ad-network-attribution"
    },
    "doc://com.apple.storekit/documentation/StoreKit/combining-parameters-for-previous-skadnetwork-postback-versions": {
      "abstract": [
        {
          "text": "Recreate the byte array for versions 2.2 or earlier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/combining-parameters-for-previous-skadnetwork-postback-versions",
      "kind": "article",
      "role": "article",
      "title": "Combining parameters for previous SKAdNetwork postback versions",
      "type": "topic",
      "url": "/documentation/storekit/combining-parameters-for-previous-skadnetwork-postback-versions"
    },
    "doc://com.apple.storekit/documentation/StoreKit/receiving-ad-attributions-and-postbacks": {
      "abstract": [
        {
          "text": "Learn about timeframes and priorities for ad impressions that result in ad attributions, and how additional impressions qualify for postbacks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/receiving-ad-attributions-and-postbacks",
      "kind": "article",
      "role": "article",
      "title": "Receiving ad attributions and postbacks",
      "type": "topic",
      "url": "/documentation/storekit/receiving-ad-attributions-and-postbacks"
    },
    "doc://com.apple.storekit/documentation/StoreKit/verifying-an-install-validation-postback": {
      "abstract": [
        {
          "text": "Ensure the validity of a postback you receive after an ad conversion by verifying its cryptographic signature.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/verifying-an-install-validation-postback",
      "kind": "article",
      "role": "article",
      "title": "Verifying an install-validation postback",
      "type": "topic",
      "url": "/documentation/storekit/verifying-an-install-validation-postback"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "SKAdNetworks-3-and-earlier-postbacks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/combining-parameters-for-previous-skadnetwork-postback-versions"
      ],
      "title": "SKAdNetworks 3 and earlier postbacks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "SKAdNetworks-3-and-earlier-postbacks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/combining-parameters-for-previous-skadnetwork-postback-versions"
              ],
              "title": "SKAdNetworks 3 and earlier postbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork/title",
          "value": "SKAdNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetwork"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/combining-parameters-for-skadnetwork-3-postbacks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/combining-parameters-for-skadnetwork-3-postbacks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
