{
  "abstract": [
    {
      "text": "Enable qualifying apps to link to an external website for account creation or management.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/external-link-account"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "External link account"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you develop a qualifying app, you can complete a request for an entitlement that allows you to link to an external website for account creation or management. For more information about whether your app qualifies and how to request an entitlement, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/support/reader-apps/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your account has the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement, implement the following to link to an external website for account creation and management:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property list key.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " type’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount/canOpen",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount/open()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In a compatible iPad or iPhone app running in visionOS, on a Mac with Apple silicon, or on a Mac app built with Mac Catalyst, the External Link Account APIs throw an error or return ",
                  "type": "text"
                },
                {
                  "code": "false",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can link to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.storekit.external-link.account",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount": {
      "abstract": [
        {
          "text": "A dictionary that contains localized URLs to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKExternalLinkAccount",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount": {
      "abstract": [
        {
          "text": "Enables qualifying apps to link to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExternalLinkAccount"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExternalLinkAccount"
        }
      ],
      "role": "symbol",
      "title": "ExternalLinkAccount",
      "type": "topic",
      "url": "/documentation/storekit/externallinkaccount"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount/canOpen": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can open the external link account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canOpen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount/canOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "canOpen",
      "type": "topic",
      "url": "/documentation/storekit/externallinkaccount/canopen"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount/open()": {
      "abstract": [
        {
          "text": "Presents a continuation sheet that enables people to choose whether to open your app’s link to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount/open()",
      "kind": "symbol",
      "role": "symbol",
      "title": "open()",
      "type": "topic",
      "url": "/documentation/storekit/externallinkaccount/open()"
    },
    "https://developer.apple.com/support/reader-apps/": {
      "identifier": "https://developer.apple.com/support/reader-apps/",
      "title": "Distributing “reader” apps with a link to your website",
      "titleInlineContent": [
        {
          "text": "Distributing “reader” apps with a link to your website",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/reader-apps/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "External-accounts",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
        "doc://com.apple.storekit/documentation/StoreKit/ExternalLinkAccount"
      ],
      "title": "External accounts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "External-accounts",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount"
              ],
              "title": "External accounts"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/external-link-account"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/external-link-account"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
