{
  "abstract": [
    {
      "text": "Enable qualifying apps to offer external purchases.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/external-purchase"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "External Purchase"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you develop a qualifying app, you may complete a request for one or two optional entitlements that allow you to offer external purchases. For more information about whether your app qualifies and requesting an entitlement, see:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/go/?id=storekit-external-purchase-eu",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/support/storekit-external-entitlement/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/contact/request/storekit-external-entitlement-ru/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/support/storekit-external-entitlement-kr/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/support/storekit-external-entitlement-us/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Offer-external-purchases-using-alternative-payment-service-providers",
          "level": 3,
          "text": "Offer external purchases using alternative payment service providers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your account receives the StoreKit External Purchase entitlement, implement the following to offer external purchases within your app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the entitlement for your app. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property list key.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " type’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase/canPresent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to determine whether external purchase is available.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase/presentNoticeSheet()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method and use the external purchase token you receive from the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase/NoticeResult/continuedWithExternalPurchaseToken(token:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " result to record transactions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "From your server, report the external purchase tokens and the transactions associated with the tokens by using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ExternalPurchaseServerAPI",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Offer-external-purchases-with-custom-links",
          "level": 3,
          "text": "Offer external purchases with custom links",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your account receives the StoreKit External Purchase Link entitlement, implement the following to offer custom links for external purchases:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the entitlement for your app. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property list key. Include the country code for each permitted region where your app offers external purchase custom links.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/isEligible",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " type to determine whether external purchase is available.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "At launch, call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/token(for:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function to request the external purchase tokens, using the token types ",
                      "type": "text"
                    },
                    {
                      "code": "ACQUISITION",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "SERVICES",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". Associate these tokens with a customer account on your server.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/showNotice(type:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function after a deliberate customer interaction, such as tapping a button, and before linking out to external purchases.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "From your server, report the external purchase tokens and the transactions associated with the tokens by using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ExternalPurchaseServerAPI",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Offer-external-purchase-link-outs",
          "level": 3,
          "text": "Offer external purchase link outs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your account receives the StoreKit External Purchase Link entitlement, implement the following to offer external purchase links:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the entitlement for your app. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property list key. Provide one or more external purchase links for each permitted country code.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " type’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/eligibleURLs",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " array to determine whether one or more external purchase links are available, then select one of those eligible URLs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/open(url:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method with the URL you select. StoreKit appends the external purchase token to your website’s URL. Use this token to record purchases.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "From your server, report the external purchase tokens and the transactions associated with the tokens by using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ExternalPurchaseServerAPI",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Offer-a-single-external-purchase-link-out-for-each-country-code",
          "level": 3,
          "text": "Offer a single external purchase link out for each country code",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property list key if your app has a minimum OS version prior to iOS 17.5, macOS 14.5, watchOS 10.5, or tvOS 17.5, or visionOS 1.2 and receives the StoreKit External Purchase Link entitlement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Implement the following to offer an external purchase link when your app runs on these prior operating systems:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the entitlement for your app. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property list key.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " type’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/canOpen",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to determine whether external purchase link is available.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/open()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method. StoreKit appends the external purchase token to your website’s URL. Use this token to record purchases.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "From your server, report the external purchase tokens and the transactions associated with the tokens by using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ExternalPurchaseServerAPI",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Your app may configure both the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property list keys.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Record-and-report-external-purchase-tokens-and-associated-transactions",
          "level": 3,
          "text": "Record and report external purchase tokens and associated transactions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An external purchase token is a unique string that your app or website receives when your app’s customer chooses to view your external purchase offerings. Record all tokens in your system and report them and their associated transactions using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ExternalPurchaseServerAPI",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more information about tokens, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/receiving-and-decoding-external-purchase-tokens",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Check-API-availability",
          "level": 3,
          "text": "Check API availability",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The External Purchase APIs, including ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provide ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "external purchase tokens",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " that you use to report transactions to Apple. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " are available starting in iOS 17.4, iPadOS 17.4, macOS 14.4, Mac Catalyst 17.4, tvOS 17.4, visionOS 1.1, and watchOS 10.4. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is available starting in iOS 18.1, iPadOS 18.1, Mac Catalyst 18.1, and macOS 15.1.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For apps that run on iOS 15.4 through 17.3 and iPadOS 15.4 through 17.3, the External Purchase APIs have the following behavior:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " APIs throw errors or return ",
                      "type": "text"
                    },
                    {
                      "code": "false",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for compatible iPad or iPhone apps running in visionOS, on a Mac with Apple silicon, or on a Mac app built with Mac Catalyst.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The APIs don’t provide external purchase tokens.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The APIs are available in iOS and iPadOS only.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can offer external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.storekit.external-purchase",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can include a link that directs people to a website to make an external purchase.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.storekit.external-purchase-link",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchase": {
      "abstract": [
        {
          "text": "A string array of country codes that indicates your app supports external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKExternalPurchase",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SKExternalPurchase"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions": {
      "abstract": [
        {
          "text": "An array of country code strings that indicate the regions where your app supports custom links for external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKExternalPurchaseCustomLinkRegions",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink": {
      "abstract": [
        {
          "text": "A dictionary that contains URLs to websites where people using your app can make external purchases for supported regions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKExternalPurchaseLink",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink": {
      "abstract": [
        {
          "text": "A dictionary that contains an array of URLs to websites where people using your app can make external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKExternalPurchaseMultiLink",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink"
    },
    "doc://com.apple.documentation/documentation/ExternalPurchaseServerAPI": {
      "abstract": [
        {
          "text": "Send and manage reports you send to Apple for tokens you receive when your app provides external purchases for digital goods and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ExternalPurchaseServerAPI",
      "kind": "symbol",
      "role": "collection",
      "title": "External Purchase Server API",
      "type": "topic",
      "url": "/documentation/ExternalPurchaseServerAPI"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase": {
      "abstract": [
        {
          "text": "Enables qualifying apps to offer external purchases within the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExternalPurchase"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExternalPurchase"
        }
      ],
      "role": "symbol",
      "title": "ExternalPurchase",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase/NoticeResult/continuedWithExternalPurchaseToken(token:)": {
      "abstract": [
        {
          "text": "Describes when people chose to continue to view external purchases, and provides the external purchase token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuedWithExternalPurchaseToken"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase/NoticeResult/continuedWithExternalPurchaseToken(token:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExternalPurchase.NoticeResult.continuedWithExternalPurchaseToken(token:)",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchase/noticeresult/continuedwithexternalpurchasetoken(token:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase/canPresent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can successfully present the notice sheet to inform people about external purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase/canPresent",
      "kind": "symbol",
      "role": "symbol",
      "title": "canPresent",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchase/canpresent"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase/presentNoticeSheet()": {
      "abstract": [
        {
          "text": "Presents a notice sheet from Apple that informs people before showing external purchases and determines whether your app can present external purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentNoticeSheet"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit16ExternalPurchaseO",
          "text": "ExternalPurchase"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit16ExternalPurchaseO12NoticeResultO",
          "text": "NoticeResult"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase/presentNoticeSheet()",
      "kind": "symbol",
      "role": "symbol",
      "title": "presentNoticeSheet()",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchase/presentnoticesheet()"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink": {
      "abstract": [
        {
          "text": "Enables qualifying apps to offer custom links for external purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExternalPurchaseCustomLink"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExternalPurchaseCustomLink"
        }
      ],
      "role": "symbol",
      "title": "ExternalPurchaseCustomLink",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchasecustomlink"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/Token": {
      "abstract": [
        {
          "text": "An external purchase token for use with custom links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Token"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/Token",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Token"
        }
      ],
      "role": "symbol",
      "title": "ExternalPurchaseCustomLink.Token",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchasecustomlink/token"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/isEligible": {
      "abstract": [
        {
          "text": "A Boolean value that indicates at runtime whether the app can use this API to offer custom links for external purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEligible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/isEligible",
      "kind": "symbol",
      "role": "symbol",
      "title": "isEligible",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchasecustomlink/iseligible"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/showNotice(type:)": {
      "abstract": [
        {
          "text": "Displays the system disclosure notice sheet and asks the customer whether to continue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showNotice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit26ExternalPurchaseCustomLinkO",
          "text": "ExternalPurchaseCustomLink"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit26ExternalPurchaseCustomLinkO10NoticeTypeO",
          "text": "NoticeType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit26ExternalPurchaseCustomLinkO",
          "text": "ExternalPurchaseCustomLink"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit26ExternalPurchaseCustomLinkO12NoticeResultO",
          "text": "NoticeResult"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/showNotice(type:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "showNotice(type:)",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchasecustomlink/shownotice(type:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/token(for:)": {
      "abstract": [
        {
          "text": "Requests an external purchase token of the specified type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "token"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit26ExternalPurchaseCustomLinkO",
          "text": "ExternalPurchaseCustomLink"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit26ExternalPurchaseCustomLinkO5TokenV",
          "text": "Token"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/token(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "token(for:)",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchasecustomlink/token(for:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink": {
      "abstract": [
        {
          "text": "Enables qualifying apps to offer external purchase links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExternalPurchaseLink"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExternalPurchaseLink"
        }
      ],
      "role": "symbol",
      "title": "ExternalPurchaseLink",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchaselink"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/canOpen": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can successfully open the configured external purchase link in the current App Store storefront.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canOpen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/canOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "canOpen",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchaselink/canopen"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/eligibleURLs": {
      "abstract": [
        {
          "text": "An array of external purchase links for the current storefront that the app configured and from which it chooses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eligibleURLs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/eligibleURLs",
      "kind": "symbol",
      "role": "symbol",
      "title": "eligibleURLs",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchaselink/eligibleurls"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/open()": {
      "abstract": [
        {
          "text": "Presents a continuation sheet that enables people to choose whether your app shows its link for external purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/open()",
      "kind": "symbol",
      "role": "symbol",
      "title": "open()",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchaselink/open()"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/open(url:)": {
      "abstract": [
        {
          "text": "Presents a continuation sheet that enables people to choose whether your app shows the indicated URL link for external purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink/open(url:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "open(url:)",
      "type": "topic",
      "url": "/documentation/storekit/externalpurchaselink/open(url:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/receiving-and-decoding-external-purchase-tokens": {
      "abstract": [
        {
          "text": "Receive tokens for external purchases that you use to report transactions to Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/receiving-and-decoding-external-purchase-tokens",
      "kind": "article",
      "role": "article",
      "title": "Receiving and decoding external purchase tokens",
      "type": "topic",
      "url": "/documentation/storekit/receiving-and-decoding-external-purchase-tokens"
    },
    "https://developer.apple.com/contact/request/storekit-external-entitlement-ru/": {
      "identifier": "https://developer.apple.com/contact/request/storekit-external-entitlement-ru/",
      "title": "Distributing apps in Russia that provide an external purchase link",
      "titleInlineContent": [
        {
          "text": "Distributing apps in Russia that provide an external purchase link",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/contact/request/storekit-external-entitlement-ru/"
    },
    "https://developer.apple.com/go/?id=storekit-external-purchase-eu": {
      "identifier": "https://developer.apple.com/go/?id=storekit-external-purchase-eu",
      "title": "Using alternative payment options on the App Store in the European Union",
      "titleInlineContent": [
        {
          "text": "Using alternative payment options on the App Store in the European Union",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/go/?id=storekit-external-purchase-eu"
    },
    "https://developer.apple.com/support/music-streaming-services-entitlement-eea/": {
      "identifier": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/",
      "title": "Distributing music streaming apps in the EEA that provide an external purchase link",
      "titleInlineContent": [
        {
          "text": "Distributing music streaming apps in the EEA that provide an external purchase link",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/"
    },
    "https://developer.apple.com/support/storekit-external-entitlement-kr/": {
      "identifier": "https://developer.apple.com/support/storekit-external-entitlement-kr/",
      "title": "Distributing apps using a third-party payment provider in South Korea",
      "titleInlineContent": [
        {
          "text": "Distributing apps using a third-party payment provider in South Korea",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/storekit-external-entitlement-kr/"
    },
    "https://developer.apple.com/support/storekit-external-entitlement-us/": {
      "identifier": "https://developer.apple.com/support/storekit-external-entitlement-us/",
      "title": "Distributing apps in the U.S. that provide an external purchase link",
      "titleInlineContent": [
        {
          "text": "Distributing apps in the U.S. that provide an external purchase link",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/storekit-external-entitlement-us/"
    },
    "https://developer.apple.com/support/storekit-external-entitlement/": {
      "identifier": "https://developer.apple.com/support/storekit-external-entitlement/",
      "title": "Distributing dating apps in the Netherlands",
      "titleInlineContent": [
        {
          "text": "Distributing dating apps in the Netherlands",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/storekit-external-entitlement/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Offering-external-purchases",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchase",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchase"
      ],
      "title": "Offering external purchases"
    },
    {
      "anchor": "Offering-external-purchases-with-custom-links",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink",
        "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseCustomLink/Token",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions"
      ],
      "title": "Offering external purchases with custom links"
    },
    {
      "anchor": "Offering-external-purchase-links",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/ExternalPurchaseLink",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink"
      ],
      "title": "Offering external purchase links"
    },
    {
      "anchor": "Managing-external-purchase-tokens",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/receiving-and-decoding-external-purchase-tokens"
      ],
      "title": "Managing external purchase tokens"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Offering-external-purchases",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchase"
              ],
              "title": "Offering external purchases"
            },
            {
              "anchor": "Offering-external-purchases-with-custom-links",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions"
              ],
              "title": "Offering external purchases with custom links"
            },
            {
              "anchor": "Offering-external-purchase-links",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink"
              ],
              "title": "Offering external purchase links"
            },
            {
              "anchor": "Managing-external-purchase-tokens",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/receiving-and-decoding-external-purchase-tokens"
              ],
              "title": "Managing external purchase tokens"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/external-purchase"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/external-purchase"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
