{
  "abstract": [
    {
      "text": "Create signed JSON Web Signature (JWS) strings on your server to authorize your API requests in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/generating-jws-to-sign-app-store-requests"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Generating JWS to sign App Store requests"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "JWS is an open standard (",
              "type": "text"
            },
            {
              "identifier": "https://datatracker.ietf.org/doc/html/rfc7515",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") that defines a way to securely transmit information. You create the JWS header and payload using information specific to the App Store feature. You sign the JWS on your server using a private API key that you download from App Store Connect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following App Store features require a JWS Compact Serialization to authorize calls in StoreKit:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Advanced Commerce API in-app requests",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Promotional offer signatures",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Introductory offer eligibility",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The data you sign when generating the JWS is a JSON Web Token (JWT). The JWT contains name-value pairs called ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "claims",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", including claims specific to the feature you’re using. Your server returns the JWS Compact Serialization to your app. Your app uses the JWS in the relevant StoreKit API call.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The App Store Server Library provides a signing utility that creates JWS specific for each of these uses. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/simplifying-your-implementation-by-using-the-app-store-server-library",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To get started, you need your key ID and issuer ID from App Store Connect. Then, to generate a signed JWS, you perform these steps on your server:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create the JWS header.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create the JWS payload. The payload includes the base payload claims, and may also require feature-specific claims.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Sign the JWS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Get-your-key-ID-and-issuer-ID-from-App-Store-Connect",
          "level": 3,
          "text": "Get your key ID and issuer ID from App Store Connect",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "First you need your key ID for the JWS header and your issuer ID for the JWS payload. Sign in to ",
              "type": "text"
            },
            {
              "identifier": "https://appstoreconnect.apple.com/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to get these values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To get the key ID:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select Users and Access, then select the Keys tab.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Hover the cursor next to a key ID to display the Copy Key ID link. The key IDs appear in a column under the Active heading.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Copy Key ID.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If you have more than one API key, copy the key ID of the private key that you use to sign the JWS. For information about creating keys, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/creating-api-keys-to-authorize-api-requests",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To get the issuer ID:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select Users and Access, then select the Keys tab.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To copy the issuer ID that appears near the top of the page, click Copy next to the ID.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Create-the-JWS-header",
          "level": 3,
          "text": "Create the JWS header",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The App Store features all use the same JWS header.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create a JWS to communicate with the App Store, use the following fields and values in the header:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Header field",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Value",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "alg",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - Encryption Algorithm",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "ES256",
                      "type": "codeVoice"
                    },
                    {
                      "text": "  ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " You need to sign JWS with ES256 encryption.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "kid",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - Key ID",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Your private key ID from App Store Connect (example: ",
                      "type": "text"
                    },
                    {
                      "code": "2X9R4HXF34",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "typ",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - Token Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "JWT",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s an example of a JWS header:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "  \"alg\": \"ES256\",",
            "  \"kid\": \"2X9R4HXF34\",",
            "  \"typ\": \"JWT\"",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "anchor": "Create-the-JWS-payload",
          "level": 3,
          "text": "Create the JWS payload",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The JWS payload contains base claims specific to the App Store, such as an issuer ID and issuance time.  It also includes custom claims that are specific to App Store features.  The following table shows the base claims. The next sections shows the feature-specific claims that you also include in the JWS payload.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Include the following base claims in the JWS payload:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Payload field",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Value",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "iss",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - Issuer",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Your issuer ID from the Keys page in App Store Connect (example: “",
                      "type": "text"
                    },
                    {
                      "code": "57246542-96fe-1a63-e053-0824d011072a\"",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "iat",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - Issued At",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The UNIX time, in seconds, that you issue the token, which the App Store server uses to calculate an expiration time (example: ",
                      "type": "text"
                    },
                    {
                      "code": "1623085200",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "aud",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - Audience",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "A value that depends on the feature you’re using (see the table below)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "bid",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - Bundle ID",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Your app’s bundle ID (example: ",
                      "type": "text"
                    },
                    {
                      "code": "“com.example.testbundleid”)",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "nonce",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - Nonce",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "A one-time-use UUID that identifies this request (example: “",
                      "type": "text"
                    },
                    {
                      "code": "368f3888-dcd8-11ef-b3c8-325096b39f47\"",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Choose the ",
              "type": "text"
            },
            {
              "code": "aud",
              "type": "codeVoice"
            },
            {
              "text": " value to match the feature you’re using:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Feature",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "code": "aud",
                          "type": "codeVoice"
                        },
                        {
                          "text": " value",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Advanced Commerce API in-app request",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "“",
                      "type": "text"
                    },
                    {
                      "code": "advanced-commerce-api\"",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Promotional offer signature",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "“",
                      "type": "text"
                    },
                    {
                      "code": "promotional-offer\"",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Introductory offer eligibility",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "“",
                      "type": "text"
                    },
                    {
                      "code": "introductory-offer-eligibility\"",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s an example of the base payload, without any feature-specific fields:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "  \"iss\": \"57246542-96fe-1a63e053-0824d011072a\",",
            "  \"iat\": 1741043663,",
            "  \"aud\": \"promotional-offer\",",
            "  \"bid\": \"com.example.testbundleid\",",
            "  \"nonce\": \"6584bedf-2ed0-4c01-93ed-c0c64a1670cc\"",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Be sure to include feature-specific custom claims in the JWS payload as well.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Include-custom-claims-for-Advanced-Commerce-API-in-app-requests",
          "level": 3,
          "text": "Include custom claims for Advanced Commerce API in-app requests",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For custom claims for Advanced Commerce in-app requests, use the following values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Payload field",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Value",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "request",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Base64-encoded request data",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on generating the base64-encoded request data, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/sending-advanced-commerce-api-requests-from-your-app#Create-the-base64-encoded-request-data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s an example of a payload for an Advanced Commerce API in-app request:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "  \"iss\": \"57246542-96fe-1a63e053-0824d011072a\",",
            "  \"iat\": 1741043663,",
            "  \"aud\": \"advanced-commerce-api\",",
            "  \"bid\": \"com.example.testbundleid\",",
            "  \"nonce\": \"df2b8374-95a1-425b-a6a5-77a4d7648333\",",
            "  \"request\": \"<base64-encoded request data>\"",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about making Advanced Commerce API requests in StoreKit, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/sending-advanced-commerce-api-requests-from-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Include-custom-claims-for-promotional-offer-signatures",
          "level": 3,
          "text": "Include custom claims for promotional offer signatures",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For promotional offer signature custom claims, use the following values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Payload field",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Value",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "productId",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The unique identifier of the product (for more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/id",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "offerIdentifier",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The promotional offer identifier that you set up in App Store Connect",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "transactionId",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The unique identifier of any transaction that belongs to the customer. You can use the customer’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/AppTransaction/appTransactionID",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", even for customers who haven’t made any In-App Purchases in your app. This field is optional, but recommended.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s an example of a payload for a promotional offer signature:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{ ",
            "    \"iss\": \"57246542-96fe-1a63e053-0824d011072a\",",
            "    \"iat\": 1741043663,",
            "    \"aud\": \"promotional-offer\",",
            "    \"bid\": \"com.example.testbundleid\",",
            "    \"nonce\": \"368f3088-dcd5-11ef-b3c8-325096b39f46\",",
            "    \"productId\": \"com.example.product\",",
            "    \"offerIdentifier\": \"com.example.product.offer\",",
            "    \"transactionId\": \"1000011859217\"",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "anchor": "Include-custom-claims-for-introductory-offer-eligibility",
          "level": 3,
          "text": "Include custom claims for introductory offer eligibility",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For introductory offer eligibility custom claims, use the following values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Payload field",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Value",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "productId",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The unique identifier of the product (for more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/id",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "allowIntroductoryOffer",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "A Boolean value, ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "false",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", that determines whether the customer is eligible for an introductory offer",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "transactionId",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The unique identifier of any transaction that belongs to the customer. You can use the customer’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/AppTransaction/appTransactionID",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", even for customers who haven’t made any In-App Purchases in your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s an example of a payload for introductory offer eligibility:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "  \"iss\": \"57246542-96fe-1a63e053-0824d011072a\",",
            "  \"iat\": 1741043663,",
            "  \"aud\": \"introductory-offer-eligibility\",",
            "  \"bid\": \"com.example.testbundleid\",",
            "  \"nonce\": \"cfb43594-4f92-4fe2-8b06-d947a848adaa\",",
            "  \"productId\": \"com.example.product\",",
            "  \"allowIntroductoryOffer\": false,",
            "  \"transactionId\": \"1000011859217\"",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about providing the introductory offer eligibility signed value in a purchase option, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/PurchaseOption",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Sign-the-JWS",
          "level": 3,
          "text": "Sign the JWS",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On your server, use the private key associated with the key ID you specified in the header to generate the signature using ES256 encryption.  The process of signing combines the JWS Header and JWS Payload into a single signed string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are a variety of open source libraries available online for creating and signing JWT tokens; see ",
              "type": "text"
            },
            {
              "identifier": "https://jwt.io/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.  Consider using the App Store Server Library to create the JWS. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/simplifying-your-implementation-by-using-the-app-store-server-library",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After signing, you should have a string in JWS compact serialization format.  Send that string to your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Always use a secure connection when sending data, including the signature, between your app and server. For more information on ensuring your data’s security, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Security/preventing-insecure-network-connections",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppStoreServerAPI/creating-api-keys-to-authorize-api-requests": {
      "abstract": [
        {
          "text": "Create API keys you use to sign JSON Web Tokens and authorize API requests.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/creating-api-keys-to-authorize-api-requests",
      "kind": "article",
      "role": "article",
      "title": "Creating API keys to authorize API requests",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI/creating-api-keys-to-authorize-api-requests"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerAPI/simplifying-your-implementation-by-using-the-app-store-server-library": {
      "abstract": [
        {
          "text": "Use Apple’s open source library to create JSON Web Tokens (JWT) to authorize your calls, verify transactions, extract transaction identifiers from receipts, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/simplifying-your-implementation-by-using-the-app-store-server-library",
      "kind": "article",
      "role": "article",
      "title": "Simplifying your implementation by using the App Store Server Library",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI/simplifying-your-implementation-by-using-the-app-store-server-library"
    },
    "doc://com.apple.documentation/documentation/Security/preventing-insecure-network-connections": {
      "abstract": [
        {
          "text": "Enforce secure network links in your app by relying on App Transport Security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/preventing-insecure-network-connections",
      "kind": "article",
      "role": "article",
      "title": "Preventing Insecure Network Connections",
      "type": "topic",
      "url": "/documentation/Security/preventing-insecure-network-connections"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/AdvancedCommerceProduct": {
      "abstract": [
        {
          "text": "A product configured as a generic SKU in App Store Connect for use with the Advanced Commerce API.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AdvancedCommerceProduct"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/AdvancedCommerceProduct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AdvancedCommerceProduct"
        }
      ],
      "role": "symbol",
      "title": "AdvancedCommerceProduct",
      "type": "topic",
      "url": "/documentation/storekit/advancedcommerceproduct"
    },
    "doc://com.apple.storekit/documentation/StoreKit/AppTransaction/appTransactionID": {
      "abstract": [
        {
          "text": "The unique identifier of the app download transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appTransactionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/AppTransaction/appTransactionID",
      "kind": "symbol",
      "role": "symbol",
      "title": "appTransactionID",
      "type": "topic",
      "url": "/documentation/storekit/apptransaction/apptransactionid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Product/PurchaseOption": {
      "abstract": [
        {
          "text": "Optional settings for a product purchase that add account information, purchase details, and offers, or that specify behaviors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PurchaseOption"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/PurchaseOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PurchaseOption"
        }
      ],
      "role": "symbol",
      "title": "Product.PurchaseOption",
      "type": "topic",
      "url": "/documentation/storekit/product/purchaseoption"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Product/id": {
      "abstract": [
        {
          "text": "The unique product identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/id",
      "kind": "symbol",
      "role": "symbol",
      "title": "id",
      "type": "topic",
      "url": "/documentation/storekit/product/id"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/sending-advanced-commerce-api-requests-from-your-app": {
      "abstract": [
        {
          "text": "Send Advanced Commerce API requests from your app that you authorize with a JSON Web Signature (JWS) you generate on your server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/sending-advanced-commerce-api-requests-from-your-app",
      "kind": "article",
      "role": "article",
      "title": "Sending Advanced Commerce API requests from your app",
      "type": "topic",
      "url": "/documentation/storekit/sending-advanced-commerce-api-requests-from-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/sending-advanced-commerce-api-requests-from-your-app#Create-the-base64-encoded-request-data": {
      "abstract": [],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/sending-advanced-commerce-api-requests-from-your-app#Create-the-base64-encoded-request-data",
      "kind": "section",
      "title": "Create the base64-encoded request data",
      "type": "topic",
      "url": "/documentation/storekit/sending-advanced-commerce-api-requests-from-your-app#Create-the-base64-encoded-request-data"
    },
    "https://appstoreconnect.apple.com/": {
      "identifier": "https://appstoreconnect.apple.com/",
      "title": "App Store Connect",
      "titleInlineContent": [
        {
          "text": "App Store Connect",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://appstoreconnect.apple.com/"
    },
    "https://datatracker.ietf.org/doc/html/rfc7515": {
      "identifier": "https://datatracker.ietf.org/doc/html/rfc7515",
      "title": "RFC 7515",
      "titleInlineContent": [
        {
          "text": "RFC 7515",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://datatracker.ietf.org/doc/html/rfc7515"
    },
    "https://jwt.io/": {
      "identifier": "https://jwt.io/",
      "title": "JWT.io",
      "titleInlineContent": [
        {
          "text": "JWT.io",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://jwt.io/"
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Advanced-Commerce-API-interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/AdvancedCommerceProduct",
        "doc://com.apple.storekit/documentation/StoreKit/sending-advanced-commerce-api-requests-from-your-app"
      ],
      "title": "Advanced Commerce API interactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Advanced-Commerce-API-interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/sending-advanced-commerce-api-requests-from-your-app"
              ],
              "title": "Advanced Commerce API interactions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/generating-jws-to-sign-app-store-requests"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/generating-jws-to-sign-app-store-requests"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
