{
  "abstract": [
    {
      "text": "Offer introductory pricing for auto-renewable subscriptions to eligible users.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/subscriptions-and-offers"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/implementing-introductory-offers-in-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Implementing introductory offers in your app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps with auto-renewable subscriptions can offer a discounted introductory price, including a free trial, to eligible users. You can make introductory offers to customers who haven’t previously received an introductory offer for the given product, or for any products in the same subscription group.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Start by setting up introductory offers in App Store Connect. Then, in your app, determine if the user is eligible to receive an introductory offer. When the app queries the App Store for a list of available products, display the introductory pricing if the user is eligible to receive them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-Up-Introductory-Offers",
          "level": 3,
          "text": "Set Up Introductory Offers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you can display introductory offers in your app, you must first configure the offers in App Store Connect. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/app-store-connect/#/deve1d49254f",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Choose from one of three types of introductory offers, which differ in their mode of payment. All subscriptions renew at the regular price when the introductory period is over. The offer types are “pay as you go”, “pay up front”, and “free trial”.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Pay-As-You-Go",
          "level": 4,
          "text": "Pay As You Go",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum/payAsYouGo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value represents the pay as you go offer type. In this introductory offer, new subscribers pay an introductory price each billing period for a specific duration (for example, $1.99 per month for 3 months).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3149470",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Pay-Up-Front",
          "level": 4,
          "text": "Pay Up Front",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum/payUpFront",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value represents the pay up front offer type. In this introductory offer, new subscribers pay a one-time introductory price for a specific duration (for example, $1.99 for 2 months).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3149471",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Free-Trial",
          "level": 4,
          "text": "Free Trial",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum/freeTrial",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value represents a free trial offer type. In this introductory offer, new subscribers access content for free for a specified duration. Subscriptions begin immediately, but subscribers won’t be billed until the free trial period is over.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174516",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Determine-Eligibility",
          "level": 3,
          "text": "Determine Eligibility",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To determine if a user is eligible for an introductory offer, check their receipt:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Validate the receipt as described in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/validating-receipts-with-the-app-store",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the receipt, check the values of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/is_trial_period",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/is_in_intro_offer_period",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for all in-app purchase transactions. If either of these fields are ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for a given subscription, the user is not eligible for an introductory offer on that subscription product or any other products within the same subscription group. Use ",
                      "type": "text"
                    },
                    {
                      "code": "subscription_group_identifier",
                      "type": "codeVoice"
                    },
                    {
                      "text": " in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/responsebody/pending_renewal_info",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " array to determine the subscription group to which the subscription belongs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, you check the user’s eligibility from your server. Determine eligibility early—for example, on the first launch of the app, if possible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2942147",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Based on the receipt, you will find that new and returning customers are eligible for introductory offers, including free trials:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "New subscribers are always eligible.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Lapsed subscribers who renew are eligible if they haven’t previously used an introductory offer for the given product (or any product within the same subscription group).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Existing subscribers are not eligible for an introductory offer for any product within the same subscription group. For example, customers are not eligible if they are upgrading, downgrading, or crossgrading their subscription from another product, regardless of whether they consumed an introductory offer in the past.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Display-the-Introductory-Offer",
          "level": 3,
          "text": "Display the Introductory Offer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Once you determine the user is eligible for an introductory offer, query the App Store for available products, and present the offer to the user:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Retrieve localized information from the App Store about a specified list of subscription products using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductsRequest",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class. Products that have an available discount defined in App Store Connect always include an ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the properties in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object to display the discounted price for the subscription. Based on the type of the introductory offer (represented by ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "), display a UI that describes the offer accordingly.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/in-app-purchase/overview/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/appstorereceipts/is_in_intro_offer_period": {
      "abstract": [
        {
          "text": "An indicator of whether an auto-renewable subscription is in the introductory price period.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "type "
        },
        {
          "kind": "identifier",
          "text": "is_in_intro_offer_period"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/is_in_intro_offer_period",
      "kind": "symbol",
      "role": "symbol",
      "title": "is_in_intro_offer_period",
      "type": "topic",
      "url": "/documentation/appstorereceipts/is_in_intro_offer_period"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/is_trial_period": {
      "abstract": [
        {
          "text": "An indicator of whether an auto-renewable subscription is in the free trial period.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "type "
        },
        {
          "kind": "identifier",
          "text": "is_trial_period"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/is_trial_period",
      "kind": "symbol",
      "role": "symbol",
      "title": "is_trial_period",
      "type": "topic",
      "url": "/documentation/appstorereceipts/is_trial_period"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/responsebody/pending_renewal_info": {
      "abstract": [
        {
          "text": "An array of elements that refers to open or failed auto-renewable subscription renewals.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "responseBody.Pending_renewal_info"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/responsebody/pending_renewal_info",
      "kind": "article",
      "role": "symbol",
      "title": "responseBody.Pending_renewal_info",
      "type": "topic",
      "url": "/documentation/appstorereceipts/responsebody/pending_renewal_info"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice": {
      "abstract": [
        {
          "text": "The object containing introductory price information for the product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "introductoryPrice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductDiscount",
          "text": "SKProductDiscount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "introductoryPrice"
        }
      ],
      "role": "symbol",
      "title": "introductoryPrice",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/introductoryprice"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount": {
      "abstract": [
        {
          "text": "The details of an introductory offer or a promotional offer for an auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum": {
      "abstract": [
        {
          "text": "Values representing the payment modes for a product discount.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PaymentMode"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PaymentMode"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount.PaymentMode",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/paymentmode-swift.enum"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum/freeTrial": {
      "abstract": [
        {
          "text": "A constant that indicates that the payment mode is a free trial.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freeTrial"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum/freeTrial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductDiscountPaymentModeFreeTrial"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount.PaymentMode.freeTrial",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/paymentmode-swift.enum/freetrial"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum/payAsYouGo": {
      "abstract": [
        {
          "text": "A constant that indicates a product discount that applies over a single billing period or multiple billing periods.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payAsYouGo"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum/payAsYouGo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductDiscountPaymentModePayAsYouGo"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount.PaymentMode.payAsYouGo",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/paymentmode-swift.enum/payasyougo"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum/payUpFront": {
      "abstract": [
        {
          "text": "A constant that indicates that the system applies the product discount up front.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payUpFront"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum/payUpFront",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductDiscountPaymentModePayUpFront"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount.PaymentMode.payUpFront",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/paymentmode-swift.enum/payupfront"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductsRequest": {
      "abstract": [
        {
          "text": "An object that can retrieve localized information from the App Store about a specified list of products.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductsRequest"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductsRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductsRequest"
        }
      ],
      "role": "symbol",
      "title": "SKProductsRequest",
      "type": "topic",
      "url": "/documentation/storekit/skproductsrequest"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase": {
      "abstract": [
        {
          "text": "Offer additional content and services in your app using the Original In-App Purchase API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original API for In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/original-api-for-in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/subscriptions-and-offers": {
      "abstract": [
        {
          "text": "Offer customers additional time-based content and services through purchases they make within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/subscriptions-and-offers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Subscriptions and offers",
      "type": "topic",
      "url": "/documentation/storekit/subscriptions-and-offers"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-introductory-offers": {
      "abstract": [
        {
          "text": "Test your introductory pricing in a variety of user scenarios.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-introductory-offers",
      "kind": "article",
      "role": "article",
      "title": "Testing introductory offers",
      "type": "topic",
      "url": "/documentation/storekit/testing-introductory-offers"
    },
    "doc://com.apple.storekit/documentation/StoreKit/validating-receipts-with-the-app-store": {
      "abstract": [
        {
          "text": "Verify transactions with the App Store on a secure server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/validating-receipts-with-the-app-store",
      "kind": "article",
      "role": "article",
      "title": "Validating receipts with the App Store",
      "type": "topic",
      "url": "/documentation/storekit/validating-receipts-with-the-app-store"
    },
    "https://developer.apple.com/design/human-interface-guidelines/in-app-purchase/overview/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/in-app-purchase/overview/",
      "title": "Human Interface Guidelines > In-App Purchase",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > In-App Purchase",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/in-app-purchase/overview/"
    },
    "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Introduction.html#//apple_ref/doc/uid/TP40010573": {
      "identifier": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Introduction.html#//apple_ref/doc/uid/TP40010573",
      "title": "Receipt Validation Programming Guide",
      "titleInlineContent": [
        {
          "text": "Receipt Validation Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Introduction.html#//apple_ref/doc/uid/TP40010573"
    },
    "https://help.apple.com/app-store-connect/#/deve1d49254f": {
      "identifier": "https://help.apple.com/app-store-connect/#/deve1d49254f",
      "title": "Set an introductory offer for an auto-renewable subscription",
      "titleInlineContent": [
        {
          "text": "Set an introductory offer for an auto-renewable subscription",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/app-store-connect/#/deve1d49254f"
    },
    "media-2942147": {
      "alt": "Diagram showing that introductory offers are available to new subscribers, and to lapsed subscribers who receive an introductory offer for the first time.",
      "identifier": "media-2942147",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3700fb494140a08886656f52e6c8f493/media-2942147@2x.png"
        }
      ]
    },
    "media-3149470": {
      "alt": "Pay as you go timeline",
      "identifier": "media-3149470",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cdf7424c589eb68fe7962e3c551ebba1/media-3149470@2x.png"
        }
      ]
    },
    "media-3149471": {
      "alt": "Pay up front timeline",
      "identifier": "media-3149471",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d4efc45f4203f1875f488fa0f304656f/media-3149471@2x.png"
        }
      ]
    },
    "media-3174516": {
      "alt": "Free trial timeline",
      "identifier": "media-3174516",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/987bbe3dd419145066746cc36e06f45c/media-3174516@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Introduction.html#//apple_ref/doc/uid/TP40010573"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Introductory-offers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/testing-introductory-offers",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount"
      ],
      "title": "Introductory offers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Introduction.html#//apple_ref/doc/uid/TP40010573"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Introductory-offers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/testing-introductory-offers",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount"
              ],
              "title": "Introductory offers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1introductoryPrice/title",
          "value": "introductoryPrice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1introductoryPrice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "introductoryPrice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum/title",
          "value": "SKProductDiscountPaymentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscountPaymentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscountPaymentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum~1payUpFront/title",
          "value": "SKProductDiscountPaymentModePayUpFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum~1payUpFront/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscountPaymentModePayUpFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductsRequest/title",
          "value": "SKProductsRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductsRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductsRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductsRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductsRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum~1freeTrial/title",
          "value": "SKProductDiscountPaymentModeFreeTrial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum~1freeTrial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscountPaymentModeFreeTrial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/title",
          "value": "SKProductDiscount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum~1payAsYouGo/title",
          "value": "SKProductDiscountPaymentModePayAsYouGo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum~1payAsYouGo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscountPaymentModePayAsYouGo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/implementing-introductory-offers-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/implementing-introductory-offers-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
