{
  "abstract": [
    {
      "text": "Support a single auto-renewable subscription across multiple apps.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/subscriptions-and-offers"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/offering-a-subscription-across-multiple-apps"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Offering a Subscription Across Multiple Apps"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can offer customers auto-renewable subscription services that are accessible through multiple apps across one or more operating systems.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To offer this functionality, your server must grant access to the subscription content across all apps, despite the user having purchased the subscription within a specific app. You can use a unified account management database along with server-side receipt validation to validate a user’s purchase and handle in-app transactions. By entitling subscription access from your server, you can provide users the ability to access your subscription across multiple apps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-the-Subscription-for-Each-App",
          "level": 3,
          "text": "Create the Subscription for Each App",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To get started, use App Store Connect to create a separate and equivalent ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/app-store-connect/#/dev06f89ce98",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for each app that offers the multi-app subscription so that users can subscribe from any app. For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/in-app-purchase/overview/introduction/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Use an ",
                  "type": "text"
                },
                {
                  "identifier": "https://help.apple.com/app-store-connect/#/dev96d99635a",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to group apps that share auto-renewable subscriptions on the same platform in a single App Store product page. An app bundle enables customers to view and download apps in a single purchase.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The following image illustrates the steps for implementing a multi-app subscription:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174488",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Authenticate-the-User",
          "level": 3,
          "text": "Authenticate the User",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When providing auto-renewable subscription access across multiple apps, you must authenticate the user in a way that correlates across apps. Authenticating users using a login allows you to determine if the user has access to the content. To provide a consistent user experience, ensure that the login process is similar across your apps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To provide an easy and secure login, take advantage of ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/sign-in-with-apple/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Sign in with Apple allows you to identify a user across your apps, while maintaining user privacy and protecting your app against fraud. You can store and retrieve user account data across your apps and the user’s devices, and use that data to unlock access appropriately.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Check-Billing-Status",
          "level": 3,
          "text": "Check Billing Status",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After authenticating the user, determine whether to grant access to the content based on their transaction history in the receipt.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Check if the user has purchased any subscription products before showing a subscription offer in the app. If there’s a subscription purchase from any app, verify if the subscription is active by looking at the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW28",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the receipt.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Present users who don’t have an active subscription with the subscription for purchase. Consider all potential billing scenarios within your account database when determining eligibility and granting access to a user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If the user has purchased the subscription from an app, you must propagate the purchase across all the apps that provide the subscription service. Failing to persist the purchase to the other apps opens the possibility of a user paying multiple times for the same service.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Validate-Subscription-Status",
          "level": 3,
          "text": "Validate Subscription Status",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A user’s subscription status can change any time. Validate the receipt and check the latest ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW28",
              "isActive": true,
              "overridingTitle": "subscription expiration date",
              "overridingTitleInlineContent": [
                {
                  "text": "subscription expiration date",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " to maintain the billing status for each user and reflect any changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/enabling-app-store-server-notifications",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " keeps your server aware of changes made to a customer’s subscription status. Update your records to keep users’ subscription status and content current. The billing status must be accurate in your account database to provide the expected user experience across all apps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-Access-to-Purchased-Content",
          "level": 3,
          "text": "Enable Access to Purchased Content",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After determining that the user should have access, you can enable access in each app based on the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW28",
              "isActive": true,
              "overridingTitle": "subscription expiration date",
              "overridingTitleInlineContent": [
                {
                  "text": "subscription expiration date",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ". The user can access the subscription within any app that offers the same service. Repeat the previous steps as necessary across each app or user’s session to unlock the subscription.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/enabling-app-store-server-notifications": {
      "abstract": [
        {
          "text": "Configure your server and provide an HTTPS URL to receive notifications about in-app purchase events and unreported external purchase tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/enabling-app-store-server-notifications",
      "kind": "article",
      "role": "article",
      "title": "Enabling App Store Server Notifications",
      "type": "topic",
      "url": "/documentation/storekit/enabling-app-store-server-notifications"
    },
    "doc://com.apple.storekit/documentation/StoreKit/handling-subscriptions-billing": {
      "abstract": [
        {
          "text": "Build logic around the date and time constraints of subscription products, while planning for all scenarios where you control access to content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/handling-subscriptions-billing",
      "kind": "article",
      "role": "article",
      "title": "Handling Subscriptions Billing",
      "type": "topic",
      "url": "/documentation/storekit/handling-subscriptions-billing"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase": {
      "abstract": [
        {
          "text": "Offer additional content and services in your app using the Original In-App Purchase API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original API for In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/original-api-for-in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/reducing-involuntary-subscriber-churn": {
      "abstract": [
        {
          "text": "Prevent unintentional loss of subscribers due to billing issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/reducing-involuntary-subscriber-churn",
      "kind": "article",
      "role": "article",
      "title": "Reducing Involuntary Subscriber Churn",
      "type": "topic",
      "url": "/documentation/storekit/reducing-involuntary-subscriber-churn"
    },
    "doc://com.apple.storekit/documentation/StoreKit/subscriptions-and-offers": {
      "abstract": [
        {
          "text": "Offer customers additional time-based content and services through purchases they make within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/subscriptions-and-offers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Subscriptions and offers",
      "type": "topic",
      "url": "/documentation/storekit/subscriptions-and-offers"
    },
    "https://developer.apple.com/design/human-interface-guidelines/in-app-purchase/overview/introduction/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/in-app-purchase/overview/introduction/",
      "title": "Human Interface Guidelines > In-App Purchase",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > In-App Purchase",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/in-app-purchase/overview/introduction/"
    },
    "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW28": {
      "identifier": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW28",
      "title": "subscription expiration date",
      "titleInlineContent": [
        {
          "text": "subscription expiration date",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW28"
    },
    "https://developer.apple.com/sign-in-with-apple/": {
      "identifier": "https://developer.apple.com/sign-in-with-apple/",
      "title": "Sign in with Apple",
      "titleInlineContent": [
        {
          "text": "Sign in with Apple",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/sign-in-with-apple/"
    },
    "https://help.apple.com/app-store-connect/#/dev06f89ce98": {
      "identifier": "https://help.apple.com/app-store-connect/#/dev06f89ce98",
      "title": "auto-renewable subscription",
      "titleInlineContent": [
        {
          "text": "auto-renewable subscription",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/app-store-connect/#/dev06f89ce98"
    },
    "https://help.apple.com/app-store-connect/#/dev96d99635a": {
      "identifier": "https://help.apple.com/app-store-connect/#/dev96d99635a",
      "title": "app bundle",
      "titleInlineContent": [
        {
          "text": "app bundle",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/app-store-connect/#/dev96d99635a"
    },
    "media-3174488": {
      "alt": "A diagram of a subscription shared across multiple apps showing the flow of implementation between apps, developer account database, and the App Store.",
      "identifier": "media-3174488",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c8625dbac1c5c2caacdd8f3fd0f5f76d/media-3174488@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7e37c9a4e77559b1e44e2d24b4bd50bc/media-3174488~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/handling-subscriptions-billing",
        "doc://com.apple.storekit/documentation/StoreKit/enabling-app-store-server-notifications",
        "doc://com.apple.storekit/documentation/StoreKit/reducing-involuntary-subscriber-churn"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/handling-subscriptions-billing",
                "doc://com.apple.storekit/documentation/StoreKit/enabling-app-store-server-notifications",
                "doc://com.apple.storekit/documentation/StoreKit/reducing-involuntary-subscriber-churn"
              ],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/offering-a-subscription-across-multiple-apps"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/offering-a-subscription-across-multiple-apps"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
