{
  "abstract": [
    {
      "text": "Register a transaction queue observer to get and handle transaction updates from the App Store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/processing-a-transaction"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Processing a transaction"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implementing an in-app purchase flow consists of three stages. In the first stage, your app retrieves product information. Then your app requests payment when the user selects a product in your app’s store. Finally, your app delivers the product.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The App Store calls the transaction queue observer after it processes the payment request. Your app then records information about the purchase for future launches, downloads the purchased content, and marks the transaction as finished.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3314631",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Monitor-transactions-in-the-queue",
          "level": 3,
          "text": "Monitor transactions in the queue",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The transaction queue plays a central role in letting your app communicate with the App Store through the StoreKit framework. You add work to the queue that the App Store needs to act on, such as a payment request for processing. When the transaction’s state changes, such as when a payment request succeeds, StoreKit calls the app’s transaction queue observer. You decide which class acts as the observer. In very small apps, you might handle all the StoreKit logic in the app delegate, including observing the transaction queue. In most apps, however, you create a separate class that handles this observer logic, along with the rest of your app’s store logic. The observer needs to conform to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By adding an observer, your app doesn’t need to constantly poll the status of its active transactions. Your app uses the transaction queue for payment requests, to download Apple-hosted content, and to determine when subscriptions renew.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It’s important to register a transaction queue observer as soon as your app launches, as the code shows below. For more guidance, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/setting-up-the-transaction-observer-for-the-payment-queue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {",
                    "    /* ... */",
                    "    SKPaymentQueue.default().add(observer)",
                    "    return true",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (BOOL)application:(UIApplication *)application",
                    " didFinishLaunchingWithOptions:(NSDictionary *)launchOptions",
                    "{",
                    "    /* ... */",
                    "",
                    "    [[SKPaymentQueue defaultQueue] addTransactionObserver:observer];",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Make sure that the observer is ready to handle a transaction at any time, not only after you add a transaction to the queue. For example, if a user buys something in your app just before entering a tunnel, your app may not be able to deliver the purchased content if there isn’t a network connection. The next time your app launches, StoreKit calls your transaction queue observer again so your app can handle the transaction and deliver the purchased content. Similarly, if your app fails to mark a transaction as finished, StoreKit calls the observer every time your app launches until the transaction finishes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:updatedTransactions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on your transaction queue observer. StoreKit calls this method when the status of a transaction changes, such as when a payment request has been processed. The transaction status tells you what action your app needs to perform, as described in the table below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Status",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Action to take in your app",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchasing",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Update your UI to reflect the in-progress status, and wait for StoreKit to call the method again.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/deferred",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Update your UI to reflect the deferred status, and wait for StoreKit to call the method again.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/failed",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Use the value of the ",
                      "type": "text"
                    },
                    {
                      "code": "error",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property to present a message to the user. For a list of error constants, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchased",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Provide the purchased functionality, typically by unlocking features or delivering content.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/restored",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Restore the previously purchased functionality.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Transactions in the queue can change state in any order. Your app needs to be ready to work on any active transaction at any time. Act on every transaction according to its transaction state, as in this example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func paymentQueue(_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction]) {",
                    "     for transaction in transactions {",
                    "     switch transaction.transactionState {",
                    "          // Call the appropriate custom method for the transaction state.",
                    "     case .purchasing: showTransactionAsInProgress(transaction, deferred: false)",
                    "     case .deferred: showTransactionAsInProgress(transaction, deferred: true)",
                    "     case .failed: failedTransaction(transaction)",
                    "          case .purchased: completeTransaction(transaction)",
                    "     case .restored: restoreTransaction(transaction)",
                    "          // For debugging purposes.",
                    "     @unknown default: print(\"Unexpected transaction state \\(transaction.transactionState)\")",
                    "    }",
                    "     }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)paymentQueue:(SKPaymentQueue *)queue",
                    " updatedTransactions:(NSArray *)transactions",
                    "{",
                    "    for (SKPaymentTransaction *transaction in transactions) {",
                    "        switch (transaction.transactionState) {",
                    "            // Call the appropriate custom method for the transaction state.",
                    "            case SKPaymentTransactionStatePurchasing:",
                    "                [self showTransactionAsInProgress:transaction deferred:NO];",
                    "                break;",
                    "            case SKPaymentTransactionStateDeferred:",
                    "                [self showTransactionAsInProgress:transaction deferred:YES];",
                    "                break;",
                    "            case SKPaymentTransactionStateFailed:",
                    "                [self failedTransaction:transaction];",
                    "                break;",
                    "            case SKPaymentTransactionStatePurchased:",
                    "                [self completeTransaction:transaction];",
                    "                break;",
                    "            case SKPaymentTransactionStateRestored:",
                    "                [self restoreTransaction:transaction];",
                    "                break;",
                    "            default:",
                    "                // For debugging",
                    "                NSLog(@\"Unexpected transaction state %@\", @(transaction.transactionState));",
                    "                break;",
                    "        }",
                    "    }",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Update-the-apps-UI-to-reflect-transaction-changes",
          "level": 3,
          "text": "Update the app’s UI to reflect transaction changes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To keep your user interface up to date while waiting, the transaction queue observer can implement optional methods from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "StoreKit calls the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:removedTransactions:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method when it removes transactions from the queue. In your implementation of this method, remove the corresponding items from your app’s UI.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "StoreKit calls the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueueRestoreCompletedTransactionsFinished(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:restoreCompletedTransactionsFailedWithError:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " methods when it finishes restoring transactions, depending on whether there is an error. In your implementation of these methods, update your app’s UI to reflect the success or failure.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For successfully processed transactions, validate the receipt associated with the transaction to verify the items the user purchased, and unlock content accordingly. For more information on validating receipts serverside, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/validating-receipts-with-the-app-store",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain": {
      "abstract": [
        {
          "text": "The error domain name for StoreKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SKErrorDomain",
      "type": "topic",
      "url": "/documentation/storekit/skerrordomain"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKMutablePayment": {
      "abstract": [
        {
          "text": "A mutable request to the App Store to process payment for additional functionality that your app offers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKMutablePayment"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKMutablePayment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKMutablePayment"
        }
      ],
      "role": "symbol",
      "title": "SKMutablePayment",
      "type": "topic",
      "url": "/documentation/storekit/skmutablepayment"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPayment": {
      "abstract": [
        {
          "text": "A request to the App Store to process payment for additional functionality that your app offers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPayment"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPayment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPayment"
        }
      ],
      "role": "symbol",
      "title": "SKPayment",
      "type": "topic",
      "url": "/documentation/storekit/skpayment"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransaction": {
      "abstract": [
        {
          "text": "An object in the payment queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPaymentTransaction"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransaction"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransaction",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver": {
      "abstract": [
        {
          "text": "A set of methods that process transactions, unlock purchased functionality, and continue promoted In-App Purchases.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionObserver"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionObserver"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionObserver",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionobserver"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:removedTransactions:)": {
      "abstract": [
        {
          "text": "Tells an observer that one or more transactions have been removed from the queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPaymentQueue",
          "text": "SKPaymentQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "removedTransactions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPaymentTransaction",
          "text": "SKPaymentTransaction"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:removedTransactions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentQueue:removedTransactions:"
        }
      ],
      "role": "symbol",
      "title": "paymentQueue(_:removedTransactions:)",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionobserver/paymentqueue(_:removedtransactions:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:restoreCompletedTransactionsFailedWithError:)": {
      "abstract": [
        {
          "text": "Tells the observer that an error occurred while restoring transactions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPaymentQueue",
          "text": "SKPaymentQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "restoreCompletedTransactionsFailedWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:restoreCompletedTransactionsFailedWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentQueue:restoreCompletedTransactionsFailedWithError:"
        }
      ],
      "role": "symbol",
      "title": "paymentQueue(_:restoreCompletedTransactionsFailedWithError:)",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionobserver/paymentqueue(_:restorecompletedtransactionsfailedwitherror:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:updatedTransactions:)": {
      "abstract": [
        {
          "text": "Tells an observer that one or more transactions have been updated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPaymentQueue",
          "text": "SKPaymentQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "updatedTransactions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPaymentTransaction",
          "text": "SKPaymentTransaction"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:updatedTransactions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentQueue:updatedTransactions:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "paymentQueue(_:updatedTransactions:)",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionobserver/paymentqueue(_:updatedtransactions:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueueRestoreCompletedTransactionsFinished(_:)": {
      "abstract": [
        {
          "text": "Tells the observer that the payment queue has finished sending restored transactions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentQueueRestoreCompletedTransactionsFinished"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPaymentQueue",
          "text": "SKPaymentQueue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueueRestoreCompletedTransactionsFinished(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentQueueRestoreCompletedTransactionsFinished:"
        }
      ],
      "role": "symbol",
      "title": "paymentQueueRestoreCompletedTransactionsFinished(_:)",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionobserver/paymentqueuerestorecompletedtransactionsfinished(_:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/deferred": {
      "abstract": [
        {
          "text": "A transaction that is in the queue, but its final status is pending external action such as Ask to Buy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferred"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/deferred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStateDeferred"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.deferred",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/deferred"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/failed": {
      "abstract": [
        {
          "text": "A failed transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStateFailed"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.failed",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/failed"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchased": {
      "abstract": [
        {
          "text": "A successfully processed transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purchased"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStatePurchased"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.purchased",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/purchased"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchasing": {
      "abstract": [
        {
          "text": "A transaction that is being processed by the App Store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purchasing"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchasing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStatePurchasing"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.purchasing",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/purchasing"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/restored": {
      "abstract": [
        {
          "text": "A transaction that restores content previously purchased by the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restored"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/restored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStateRestored"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.restored",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/restored"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase": {
      "abstract": [
        {
          "text": "Offer additional content and services in your app using the Original In-App Purchase API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original API for In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/original-api-for-in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/requesting-a-payment-from-the-app-store": {
      "abstract": [
        {
          "text": "Submit a payment request to the App Store when a customer selects a product to buy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/requesting-a-payment-from-the-app-store",
      "kind": "article",
      "role": "article",
      "title": "Requesting a payment from the App Store",
      "type": "topic",
      "url": "/documentation/storekit/requesting-a-payment-from-the-app-store"
    },
    "doc://com.apple.storekit/documentation/StoreKit/setting-up-the-transaction-observer-for-the-payment-queue": {
      "abstract": [
        {
          "text": "Enable your app to receive and handle transactions by adding an observer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/setting-up-the-transaction-observer-for-the-payment-queue",
      "kind": "article",
      "role": "article",
      "title": "Setting up the transaction observer for the payment queue",
      "type": "topic",
      "url": "/documentation/storekit/setting-up-the-transaction-observer-for-the-payment-queue"
    },
    "doc://com.apple.storekit/documentation/StoreKit/validating-receipts-with-the-app-store": {
      "abstract": [
        {
          "text": "Verify transactions with the App Store on a secure server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/validating-receipts-with-the-app-store",
      "kind": "article",
      "role": "article",
      "title": "Validating receipts with the App Store",
      "type": "topic",
      "url": "/documentation/storekit/validating-receipts-with-the-app-store"
    },
    "media-3314631": {
      "alt": "A flowchart depicting the three stages of the in-app purchase process between your app and the App Store. First, your app makes a request for a product, the App Store provides that product information, and your app displays it. Next, the user selects a product, your app makes a payment request, and the App Store processes the payment. Finally, the App Store calls your app’s transaction queue observer, and your app delivers the purchased product. The third stage, delivering products, is highlighted.",
      "identifier": "media-3314631",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5b88efb67bd1deaf5cc7b0e2c373d310/media-3314631@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6178a53dc876893b248d37f27528cc35/media-3314631~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Purchases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/requesting-a-payment-from-the-app-store",
        "doc://com.apple.storekit/documentation/StoreKit/SKPayment",
        "doc://com.apple.storekit/documentation/StoreKit/SKMutablePayment",
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransaction"
      ],
      "title": "Purchases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Purchases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/requesting-a-payment-from-the-app-store",
                "doc://com.apple.storekit/documentation/StoreKit/SKPayment",
                "doc://com.apple.storekit/documentation/StoreKit/SKMutablePayment",
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransaction"
              ],
              "title": "Purchases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueue(_:updatedTransactions:)/title",
          "value": "paymentQueue:updatedTransactions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueue(_:updatedTransactions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentQueue:updatedTransactions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1deferred/title",
          "value": "SKPaymentTransactionStateDeferred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1deferred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStateDeferred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueue(_:removedTransactions:)/title",
          "value": "paymentQueue:removedTransactions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueue(_:removedTransactions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentQueue:removedTransactions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKErrorDomain/title",
          "value": "SKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1restored/title",
          "value": "SKPaymentTransactionStateRestored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1restored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStateRestored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver/title",
          "value": "SKPaymentTransactionObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransaction/title",
          "value": "SKPaymentTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransaction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPayment/title",
          "value": "SKPayment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPayment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPayment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPayment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPayment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueue(_:restoreCompletedTransactionsFailedWithError:)/title",
          "value": "paymentQueue:restoreCompletedTransactionsFailedWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueue(_:restoreCompletedTransactionsFailedWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentQueue:restoreCompletedTransactionsFailedWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKMutablePayment/title",
          "value": "SKMutablePayment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKMutablePayment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKMutablePayment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKMutablePayment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKMutablePayment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchased/title",
          "value": "SKPaymentTransactionStatePurchased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStatePurchased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchasing/title",
          "value": "SKPaymentTransactionStatePurchasing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchasing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStatePurchasing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1failed/title",
          "value": "SKPaymentTransactionStateFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStateFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueueRestoreCompletedTransactionsFinished(_:)/title",
          "value": "paymentQueueRestoreCompletedTransactionsFinished:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueueRestoreCompletedTransactionsFinished(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentQueueRestoreCompletedTransactionsFinished:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/processing-a-transaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/processing-a-transaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
