{
  "abstract": [
    {
      "text": "Keys for identifying products and the tokens for affiliates and campaigns.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/product-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Product Dictionary Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These dictionary keys are used in the parameter for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(withParameters:completionBlock:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterITunesItemIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key represents the product to display, and is always required. Other keys provide optional affiliate or promoted product information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Learn more about the Affiliate Program at ",
              "type": "text"
            },
            {
              "identifier": "https://apple.com/itunes/affiliates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterAdvertisingPartnerToken": {
      "abstract": [
        {
          "text": "The key representing the advertising partner you wish to use for any purchase made through the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterAdvertisingPartnerToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterAdvertisingPartnerToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterAdvertisingPartnerToken"
        }
      ],
      "role": "symbol",
      "title": "SKStoreProductParameterAdvertisingPartnerToken",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductparameteradvertisingpartnertoken"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterAffiliateToken": {
      "abstract": [
        {
          "text": "The key representing the affiliate identifier you wish to use for any purchase made through the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterAffiliateToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterAffiliateToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterAffiliateToken"
        }
      ],
      "role": "symbol",
      "title": "SKStoreProductParameterAffiliateToken",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductparameteraffiliatetoken"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterCampaignToken": {
      "abstract": [
        {
          "text": "The key representing an App Analytics campaign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterCampaignToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterCampaignToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterCampaignToken"
        }
      ],
      "role": "symbol",
      "title": "SKStoreProductParameterCampaignToken",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductparametercampaigntoken"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterCustomProductPageIdentifier": {
      "abstract": [
        {
          "text": "The key that represents the custom product page identifier you want the store to display when you present the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterCustomProductPageIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterCustomProductPageIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterCustomProductPageIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKStoreProductParameterCustomProductPageIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductparametercustomproductpageidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterITunesItemIdentifier": {
      "abstract": [
        {
          "text": "The key representing the iTunes identifier for the item you want the store to display when the view controller is presented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterITunesItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterITunesItemIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterITunesItemIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKStoreProductParameterITunesItemIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductparameteritunesitemidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterProductIdentifier": {
      "abstract": [
        {
          "text": "The key representing the product identifier for the promoted product you want the store to display at the top of the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterProductIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterProductIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterProductIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKStoreProductParameterProductIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductparameterproductidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterProviderToken": {
      "abstract": [
        {
          "text": "The key representing the provider token for the developer that created the app specified by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterITunesItemIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterProviderToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterProviderToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreProductParameterProviderToken"
        }
      ],
      "role": "symbol",
      "title": "SKStoreProductParameterProviderToken",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductparameterprovidertoken"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController": {
      "abstract": [
        {
          "text": "A view controller that provides a page where customers can purchase media from the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreProductViewController"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreProductViewController"
        }
      ],
      "role": "symbol",
      "title": "SKStoreProductViewController",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductviewcontroller"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(parameters:impression:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "impression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16AdAttributionKit13AppImpressionV",
          "text": "AppImpression"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(parameters:impression:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadProduct(parameters:impression:)",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductviewcontroller/loadproduct(parameters:impression:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(parameters:impression:reengagementURL:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "impression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16AdAttributionKit13AppImpressionV",
          "text": "AppImpression"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reengagementURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(parameters:impression:reengagementURL:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadProduct(parameters:impression:reengagementURL:)",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductviewcontroller/loadproduct(parameters:impression:reengagementurl:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(withParameters:completionBlock:)": {
      "abstract": [
        {
          "text": "Loads a new product screen to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionBlock"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(withParameters:completionBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadProductWithParameters:completionBlock:"
        }
      ],
      "role": "symbol",
      "title": "loadProduct(withParameters:completionBlock:)",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductviewcontroller/loadproduct(withparameters:completionblock:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(withParameters:impression:completionBlock:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadProduct"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "impression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKAdImpression",
          "text": "SKAdImpression"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionBlock"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(withParameters:impression:completionBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadProductWithParameters:impression:completionBlock:"
        }
      ],
      "role": "symbol",
      "title": "loadProduct(withParameters:impression:completionBlock:)",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductviewcontroller/loadproduct(withparameters:impression:completionblock:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/offering-media-for-sale-in-your-app": {
      "abstract": [
        {
          "text": "Allow users to purchase media in the App Store from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/offering-media-for-sale-in-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Offering media for sale in your app",
      "type": "topic",
      "url": "/documentation/storekit/offering-media-for-sale-in-your-app"
    },
    "https://apple.com/itunes/affiliates": {
      "identifier": "https://apple.com/itunes/affiliates",
      "title": "https://apple.com/itunes/affiliates",
      "titleInlineContent": [
        {
          "text": "https://apple.com/itunes/affiliates",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://apple.com/itunes/affiliates"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Loading-a-new-product-screen",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/offering-media-for-sale-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(withParameters:completionBlock:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(withParameters:impression:completionBlock:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(parameters:impression:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(parameters:impression:reengagementURL:)"
      ],
      "title": "Loading a new product screen"
    }
  ],
  "topicSections": [
    {
      "anchor": "Required-Key",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterITunesItemIdentifier"
      ],
      "title": "Required Key"
    },
    {
      "anchor": "Affiliate-and-Analytics-Keys",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterProductIdentifier",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterAdvertisingPartnerToken",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterAffiliateToken",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterCampaignToken",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterProviderToken",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterCustomProductPageIdentifier"
      ],
      "title": "Affiliate and Analytics Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Required-Key",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterITunesItemIdentifier"
              ],
              "title": "Required Key"
            },
            {
              "anchor": "Affiliate-and-Analytics-Keys",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterProductIdentifier",
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterAdvertisingPartnerToken",
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterAffiliateToken",
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterCampaignToken",
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterProviderToken",
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductParameterCustomProductPageIdentifier"
              ],
              "title": "Affiliate and Analytics Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Loading-a-new-product-screen",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/offering-media-for-sale-in-your-app",
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(withParameters:completionBlock:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController/loadProduct(withParameters:impression:completionBlock:)"
              ],
              "title": "Loading a new product screen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController/title",
          "value": "SKStoreProductViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterProviderToken/title",
          "value": "SKStoreProductParameterProviderToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterProviderToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductParameterProviderToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterCustomProductPageIdentifier/title",
          "value": "SKStoreProductParameterCustomProductPageIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterCustomProductPageIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductParameterCustomProductPageIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterProductIdentifier/title",
          "value": "SKStoreProductParameterProductIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterProductIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductParameterProductIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterAffiliateToken/title",
          "value": "SKStoreProductParameterAffiliateToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterAffiliateToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductParameterAffiliateToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterCampaignToken/title",
          "value": "SKStoreProductParameterCampaignToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterCampaignToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductParameterCampaignToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController~1loadProduct(withParameters:completionBlock:)/title",
          "value": "loadProductWithParameters:completionBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController~1loadProduct(withParameters:completionBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadProductWithParameters:completionBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController~1loadProduct(withParameters:impression:completionBlock:)/title",
          "value": "loadProductWithParameters:impression:completionBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController~1loadProduct(withParameters:impression:completionBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadProductWithParameters:impression:completionBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterAdvertisingPartnerToken/title",
          "value": "SKStoreProductParameterAdvertisingPartnerToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterAdvertisingPartnerToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductParameterAdvertisingPartnerToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterITunesItemIdentifier/title",
          "value": "SKStoreProductParameterITunesItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductParameterITunesItemIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductParameterITunesItemIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/product-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/product-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
