{
  "abstract": [
    {
      "text": "A version of SKAdNetwork available in iOS 11.3 and later.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution",
        "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork",
        "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-1-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "SKAdNetwork 1 release notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You’re eligible to receive a version 1.0 postback when any of these conditions are met:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The source app uses iOS 13.7 SDK or earlier.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The advertised app is App Store-signed and running on a device with iOS 14 or earlier.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The original install-validation postback doesn’t include a version number. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/combining-parameters-for-previous-skadnetwork-postback-versions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When verifying an install-validation postback for version 1.0, use the following Apple P-192 public key:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "MEkwEwYHKoZIzj0CAQYIKoZIzj0DAQEDMgAEMyHD625uvsmGq4C43cQ9BnfN2xslVT5V1nOmAMP6qaRRUll3PB1JYmgSm+62sosG"
          ],
          "syntax": null,
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/verifying-an-install-validation-postback",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "New-features",
          "level": 3,
          "text": "New features",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This is the original version of SKAdNetwork.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork": {
      "abstract": [
        {
          "text": "A class that validates advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdNetwork"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdNetwork"
        }
      ],
      "role": "symbol",
      "title": "SKAdNetwork",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution": {
      "abstract": [
        {
          "text": "Validate advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ad network attribution",
      "type": "topic",
      "url": "/documentation/storekit/ad-network-attribution"
    },
    "doc://com.apple.storekit/documentation/StoreKit/combining-parameters-for-previous-skadnetwork-postback-versions": {
      "abstract": [
        {
          "text": "Recreate the byte array for versions 2.2 or earlier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/combining-parameters-for-previous-skadnetwork-postback-versions",
      "kind": "article",
      "role": "article",
      "title": "Combining parameters for previous SKAdNetwork postback versions",
      "type": "topic",
      "url": "/documentation/storekit/combining-parameters-for-previous-skadnetwork-postback-versions"
    },
    "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-1-release-notes": {
      "abstract": [
        {
          "text": "A version of SKAdNetwork available in iOS 14 and later.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "SKAdNetwork 2.1 release notes",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork-2-1-release-notes"
    },
    "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-2-release-notes": {
      "abstract": [
        {
          "text": "A version of SKAdNetwork available in iOS 14.5 and later.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "SKAdNetwork 2.2 release notes",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork-2-2-release-notes"
    },
    "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-release-notes": {
      "abstract": [
        {
          "text": "A version of SKAdNetwork available in iOS 14 and later.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "SKAdNetwork 2 release notes",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork-2-release-notes"
    },
    "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-3-release-notes": {
      "abstract": [
        {
          "text": "A version of SKAdNetwork available in iOS 14.6 and later.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "SKAdNetwork 3 release notes",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork-3-release-notes"
    },
    "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-4-release-notes": {
      "abstract": [
        {
          "text": "A version of SKAdNetwork available in iOS 16.1 and later.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-4-release-notes",
      "kind": "article",
      "role": "article",
      "title": "SKAdNetwork 4 release notes",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork-4-release-notes"
    },
    "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-release-notes": {
      "abstract": [
        {
          "text": "Learn about the features in each SKAdNetwork version.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-release-notes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SKAdNetwork release notes",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork-release-notes"
    },
    "doc://com.apple.storekit/documentation/StoreKit/verifying-an-install-validation-postback": {
      "abstract": [
        {
          "text": "Ensure the validity of a postback you receive after an ad conversion by verifying its cryptographic signature.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/verifying-an-install-validation-postback",
      "kind": "article",
      "role": "article",
      "title": "Verifying an install-validation postback",
      "type": "topic",
      "url": "/documentation/storekit/verifying-an-install-validation-postback"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "SKAdNetwork-versions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-4-release-notes",
        "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-3-release-notes",
        "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-2-release-notes",
        "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-1-release-notes",
        "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-release-notes"
      ],
      "title": "SKAdNetwork versions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "SKAdNetwork-versions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-4-release-notes",
                "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-3-release-notes",
                "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-2-release-notes",
                "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-1-release-notes",
                "doc://com.apple.storekit/documentation/StoreKit/skadnetwork-2-release-notes"
              ],
              "title": "SKAdNetwork versions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork/title",
          "value": "SKAdNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetwork"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skadnetwork-1-release-notes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skadnetwork-1-release-notes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
