{
  "abstract": [
    {
      "text": "An object that determines the current capabilities of a person’s Music library.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/SwiftUI",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/MusicKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKCloudServiceController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKCloudServiceController"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKCloudServiceController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.3",
        "message": "Use MusicKit",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.3",
        "message": "Use MusicKit",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "message": "Use MusicKit",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "Use MusicKit",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.3",
        "message": "Use MusicKit",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "7.0",
        "message": "Use MusicKit",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SKCloudServiceController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKCloudServiceController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities",
        "doc://com.apple.storekit/documentation/StoreKit/requesting-access-to-apple-music-library",
        "doc://com.apple.storekit/documentation/StoreKit/offering-apple-music-subscription-in-your-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to determine the current capabilities of a customer’s Music library, like whether the device allows playback of Apple Music catalog tracks and the addition of tracks to the library.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/MusicKit": {
      "abstract": [
        {
          "text": "Integrate your app with Apple Music.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MusicKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MusicKit",
      "type": "topic",
      "url": "/documentation/MusicKit"
    },
    "doc://com.apple.documentation/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/SwiftUI"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1620626-skcloudservicecapabilitiesdidcha": {
      "abstract": [
        {
          "text": "A notification name for indicating a change in the capabilities associated with the Music library on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapabilitiesDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1620626-skcloudservicecapabilitiesdidcha",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKCloudServiceCapabilitiesDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1620626-skcloudservicecapabilitiesdidcha"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1620636-skstorefrontidentifierdidchange": {
      "abstract": [
        {
          "text": "A notification name for indicating a change in the storefront identifier associated with the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "SKStorefrontIdentifierDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1620636-skstorefrontidentifierdidchange",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKStorefrontIdentifierDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1620636-skstorefrontidentifierdidchange"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/2909077-skstorefrontcountrycodedidchange": {
      "abstract": [
        {
          "text": "A notification name for indicating a change in the storefront country or region code associated with the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "SKStorefrontCountryCodeDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/2909077-skstorefrontcountrycodedidchange",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKStorefrontCountryCodeDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/2909077-skstorefrontcountrycodedidchange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus": {
      "abstract": [
        {
          "text": "Constants that indicate the type of authorization the customer has for accessing the Music library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/storekit/skcloudserviceauthorizationstatus"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapabilitiesDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification name for indicating a change in the capabilities associated with the Music library on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapabilitiesDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapabilitiesDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKCloudServiceCapabilitiesDidChangeNotification",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecapabilitiesdidchangenotification"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability": {
      "abstract": [
        {
          "text": "Constants that specify the current capabilities of the customer’s Music library on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapability"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapability"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceCapability",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecapability"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController": {
      "abstract": [
        {
          "text": "An object that determines the current capabilities of a person’s Music library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceController"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceController"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceController",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecontroller"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/authorizationStatus()": {
      "abstract": [
        {
          "text": "Returns the type of authorization the customer has for accessing the Music library on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKCloudServiceAuthorizationStatus",
          "text": "SKCloudServiceAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/authorizationStatus()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus()",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecontroller/authorizationstatus()"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestAuthorization(_:)": {
      "abstract": [
        {
          "text": "Asks the customer for permission to access the Music library on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAuthorization"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKCloudServiceAuthorizationStatus",
          "text": "SKCloudServiceAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestAuthorization(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAuthorization:"
        }
      ],
      "role": "symbol",
      "title": "requestAuthorization(_:)",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecontroller/requestauthorization(_:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestCapabilities(completionHandler:)": {
      "abstract": [
        {
          "text": "Gets the current capabilities associated with the Music library on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestCapabilities"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKCloudServiceCapability",
          "text": "SKCloudServiceCapability"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestCapabilities(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestCapabilitiesWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestCapabilities(completionHandler:)",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecontroller/requestcapabilities(completionhandler:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestPersonalizationToken(forClientToken:withCompletionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestPersonalizationToken"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forClientToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestPersonalizationToken(forClientToken:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestPersonalizationTokenForClientToken:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestPersonalizationToken(forClientToken:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecontroller/requestpersonalizationtoken(forclienttoken:withcompletionhandler:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestStorefrontCountryCode(completionHandler:)": {
      "abstract": [
        {
          "text": "Gets the country code for the storefront associated with a customer’s iTunes account.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestStorefrontCountryCode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestStorefrontCountryCode(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestStorefrontCountryCodeWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestStorefrontCountryCode(completionHandler:)",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecontroller/requeststorefrontcountrycode(completionhandler:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestStorefrontIdentifier(completionHandler:)": {
      "abstract": [
        {
          "text": "Gets the device’s storefront identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestStorefrontIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestStorefrontIdentifier(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestStorefrontIdentifierWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestStorefrontIdentifier(completionHandler:)",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecontroller/requeststorefrontidentifier(completionhandler:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestUserToken(forDeveloperToken:completionHandler:)": {
      "abstract": [
        {
          "text": "Returns a user token that you use to access personalized Apple Music content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestUserToken"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDeveloperToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestUserToken(forDeveloperToken:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestUserTokenForDeveloperToken:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestUserToken(forDeveloperToken:completionHandler:)",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecontroller/requestusertoken(fordevelopertoken:completionhandler:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupViewController": {
      "abstract": [
        {
          "text": "A view controller that helps people perform setup for a cloud service, like an Apple Music subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupViewController"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupViewController"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceSetupViewController",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicesetupviewcontroller"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStorefrontCountryCodeDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification name for indicating a change in the storefront country or region code associated with the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SKStorefrontCountryCodeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStorefrontCountryCodeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKStorefrontCountryCodeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/storekit/skstorefrontcountrycodedidchangenotification"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStorefrontIdentifierDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification name for indicating a change in the storefront identifier associated with the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SKStorefrontIdentifierDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStorefrontIdentifierDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKStorefrontIdentifierDidChangeNotification",
      "type": "topic",
      "url": "/documentation/storekit/skstorefrontidentifierdidchangenotification"
    },
    "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities": {
      "abstract": [
        {
          "text": "Determine which Apple Music capabilities are available on a customer’s device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities",
      "kind": "article",
      "role": "article",
      "title": "Determining a person’s Apple Music capabilities",
      "type": "topic",
      "url": "/documentation/storekit/determining-a-person-s-apple-music-capabilities"
    },
    "doc://com.apple.storekit/documentation/StoreKit/offering-apple-music-subscription-in-your-app": {
      "abstract": [
        {
          "text": "Allow eligible customers to subscribe to Apple Music.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/offering-apple-music-subscription-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Offering Apple Music Subscription in Your App",
      "type": "topic",
      "url": "/documentation/storekit/offering-apple-music-subscription-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/requesting-access-to-apple-music-library": {
      "abstract": [
        {
          "text": "Prompt the customer to authorize access to Apple Music library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/requesting-access-to-apple-music-library",
      "kind": "article",
      "role": "article",
      "title": "Requesting Access to Apple Music Library",
      "type": "topic",
      "url": "/documentation/storekit/requesting-access-to-apple-music-library"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupViewController"
      ],
      "title": "Deprecated"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-authorization-to-access-the-Music-library",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/requesting-access-to-apple-music-library",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/authorizationStatus()",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestAuthorization(_:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus"
      ],
      "title": "Getting authorization to access the Music library"
    },
    {
      "anchor": "Determining-capabilities",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestUserToken(forDeveloperToken:completionHandler:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestStorefrontCountryCode(completionHandler:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestCapabilities(completionHandler:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestStorefrontIdentifier(completionHandler:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestPersonalizationToken(forClientToken:withCompletionHandler:)"
      ],
      "title": "Determining capabilities"
    },
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1620636-skstorefrontidentifierdidchange",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1620626-skcloudservicecapabilitiesdidcha",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/2909077-skstorefrontcountrycodedidchange"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.3",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKCloudServiceController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-authorization-to-access-the-Music-library",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/requesting-access-to-apple-music-library",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/authorizationStatus()",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestAuthorization(_:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus"
              ],
              "title": "Getting authorization to access the Music library"
            },
            {
              "anchor": "Determining-capabilities",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestUserToken(forDeveloperToken:completionHandler:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestStorefrontCountryCode(completionHandler:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestCapabilities(completionHandler:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestStorefrontIdentifier(completionHandler:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController/requestPersonalizationToken(forClientToken:withCompletionHandler:)"
              ],
              "title": "Determining capabilities"
            },
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1620636-skstorefrontidentifierdidchange",
                "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1620626-skcloudservicecapabilitiesdidcha",
                "doc://com.apple.documentation/documentation/foundation/nsnotification/name/2909077-skstorefrontcountrycodedidchange",
                "doc://com.apple.storekit/documentation/StoreKit/SKStorefrontIdentifierDidChangeNotification",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapabilitiesDidChangeNotification",
                "doc://com.apple.storekit/documentation/StoreKit/SKStorefrontCountryCodeDidChangeNotification"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupViewController"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKCloudServiceController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/SwiftUI",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and  ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/MusicKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestStorefrontIdentifier(completionHandler:)/title",
          "value": "requestStorefrontIdentifierWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestStorefrontIdentifier(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestStorefrontIdentifierWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestUserToken(forDeveloperToken:completionHandler:)/title",
          "value": "requestUserTokenForDeveloperToken:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestUserToken(forDeveloperToken:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestUserTokenForDeveloperToken:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestAuthorization(_:)/title",
          "value": "requestAuthorization:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestAuthorization(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorization:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController/title",
          "value": "SKCloudServiceController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupViewController/title",
          "value": "SKCloudServiceSetupViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestStorefrontCountryCode(completionHandler:)/title",
          "value": "requestStorefrontCountryCodeWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestStorefrontCountryCode(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestStorefrontCountryCodeWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus/title",
          "value": "SKCloudServiceAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability/title",
          "value": "SKCloudServiceCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestCapabilities(completionHandler:)/title",
          "value": "requestCapabilitiesWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestCapabilities(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestCapabilitiesWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1authorizationStatus()/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1authorizationStatus()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestPersonalizationToken(forClientToken:withCompletionHandler:)/title",
          "value": "requestPersonalizationTokenForClientToken:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController~1requestPersonalizationToken(forClientToken:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestPersonalizationTokenForClientToken:withCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skcloudservicecontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skcloudservicecontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
