{
  "abstract": [
    {
      "text": "StoreKit error descriptions, codes, and domains.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11SKErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKError"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SKError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError": {
      "abstract": [
        {
          "text": "StoreKit error descriptions, codes, and domains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKError"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKError"
        }
      ],
      "role": "symbol",
      "title": "SKError",
      "type": "topic",
      "url": "/documentation/storekit/skerror"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code": {
      "abstract": [
        {
          "text": "Error codes for StoreKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/clientInvalid": {
      "abstract": [
        {
          "text": "Error code indicating that the client is not allowed to perform the attempted action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/clientInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientInvalid",
      "type": "topic",
      "url": "/documentation/storekit/skerror/clientinvalid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceNetworkConnectionFailed": {
      "abstract": [
        {
          "text": "Error code indicating that the device could not connect to the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServiceNetworkConnectionFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceNetworkConnectionFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudServiceNetworkConnectionFailed",
      "type": "topic",
      "url": "/documentation/storekit/skerror/cloudservicenetworkconnectionfailed"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServicePermissionDenied": {
      "abstract": [
        {
          "text": "Error code indicating that the user has not allowed access to Cloud service information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServicePermissionDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServicePermissionDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudServicePermissionDenied",
      "type": "topic",
      "url": "/documentation/storekit/skerror/cloudservicepermissiondenied"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceRevoked": {
      "abstract": [
        {
          "text": "Error code indicating that the user has revoked permission to use this cloud service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServiceRevoked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceRevoked",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudServiceRevoked",
      "type": "topic",
      "url": "/documentation/storekit/skerror/cloudservicerevoked"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/storekit/skerror/errordomain"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/ineligibleForOffer": {
      "abstract": [
        {
          "text": "An error code that indicates the user is ineligible for the subscription offer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ineligibleForOffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/ineligibleForOffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "ineligibleForOffer",
      "type": "topic",
      "url": "/documentation/storekit/skerror/ineligibleforoffer"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferIdentifier": {
      "abstract": [
        {
          "text": "Error code indicating that the offer identifier cannot be found or is not active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOfferIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidOfferIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skerror/invalidofferidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferPrice": {
      "abstract": [
        {
          "text": "Error code indicating that the price you specified in App Store Connect is no longer valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOfferPrice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferPrice",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidOfferPrice",
      "type": "topic",
      "url": "/documentation/storekit/skerror/invalidofferprice"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidSignature": {
      "abstract": [
        {
          "text": "Error code indicating that the signature in a payment discount is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidSignature",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSignature",
      "type": "topic",
      "url": "/documentation/storekit/skerror/invalidsignature"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/missingOfferParams": {
      "abstract": [
        {
          "text": "Error code indicating that parameters are missing in a payment discount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingOfferParams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/missingOfferParams",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingOfferParams",
      "type": "topic",
      "url": "/documentation/storekit/skerror/missingofferparams"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayCancelled": {
      "abstract": [
        {
          "text": "An error code that indicates the cancellation of an overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlayCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "overlayCancelled",
      "type": "topic",
      "url": "/documentation/storekit/skerror/overlaycancelled"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayInvalidConfiguration": {
      "abstract": [
        {
          "text": "An error code that indicates the overlay’s configuration is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlayInvalidConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayInvalidConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "overlayInvalidConfiguration",
      "type": "topic",
      "url": "/documentation/storekit/skerror/overlayinvalidconfiguration"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayPresentedInBackgroundScene": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlayPresentedInBackgroundScene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayPresentedInBackgroundScene",
      "kind": "symbol",
      "role": "symbol",
      "title": "overlayPresentedInBackgroundScene",
      "type": "topic",
      "url": "/documentation/storekit/skerror/overlaypresentedinbackgroundscene"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayTimeout": {
      "abstract": [
        {
          "text": "An error code that indicates the timing out of an overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlayTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayTimeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "overlayTimeout",
      "type": "topic",
      "url": "/documentation/storekit/skerror/overlaytimeout"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentCancelled": {
      "abstract": [
        {
          "text": "Error code indicating that the user canceled a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "paymentCancelled",
      "type": "topic",
      "url": "/documentation/storekit/skerror/paymentcancelled"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentInvalid": {
      "abstract": [
        {
          "text": "Error code indicating that one of the payment parameters was not recognized by the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "paymentInvalid",
      "type": "topic",
      "url": "/documentation/storekit/skerror/paymentinvalid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentNotAllowed": {
      "abstract": [
        {
          "text": "Error code indicating that the user is not allowed to authorize payments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentNotAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "paymentNotAllowed",
      "type": "topic",
      "url": "/documentation/storekit/skerror/paymentnotallowed"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/privacyAcknowledgementRequired": {
      "abstract": [
        {
          "text": "Error code indicating that the user has not yet acknowledged Apple’s privacy policy for Apple Music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "privacyAcknowledgementRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/privacyAcknowledgementRequired",
      "kind": "symbol",
      "role": "symbol",
      "title": "privacyAcknowledgementRequired",
      "type": "topic",
      "url": "/documentation/storekit/skerror/privacyacknowledgementrequired"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/storeProductNotAvailable": {
      "abstract": [
        {
          "text": "Error code indicating that the requested product is not available in the store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeProductNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/storeProductNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "storeProductNotAvailable",
      "type": "topic",
      "url": "/documentation/storekit/skerror/storeproductnotavailable"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/unauthorizedRequestData": {
      "abstract": [
        {
          "text": "Error code indicating that the app is attempting to use a property for which it does not have the required entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unauthorizedRequestData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/unauthorizedRequestData",
      "kind": "symbol",
      "role": "symbol",
      "title": "unauthorizedRequestData",
      "type": "topic",
      "url": "/documentation/storekit/skerror/unauthorizedrequestdata"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/unknown": {
      "abstract": [
        {
          "text": "Error code indicating that an unknown or unexpected error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/storekit/skerror/unknown"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/unsupportedPlatform": {
      "abstract": [
        {
          "text": "An error code that indicates the current platform doesn’t support overlays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedPlatform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/unsupportedPlatform",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedPlatform",
      "type": "topic",
      "url": "/documentation/storekit/skerror/unsupportedplatform"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain": {
      "abstract": [
        {
          "text": "The error domain name for StoreKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SKErrorDomain",
      "type": "topic",
      "url": "/documentation/storekit/skerrordomain"
    },
    "doc://com.apple.storekit/documentation/StoreKit/handling-errors": {
      "abstract": [
        {
          "text": "Determine the underlying cause of errors that result from StoreKit requests.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/handling-errors",
      "kind": "article",
      "role": "article",
      "title": "Handling errors",
      "type": "topic",
      "url": "/documentation/storekit/handling-errors"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/handling-errors",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code",
        "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/unknown",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/clientInvalid",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentCancelled",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentInvalid",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentNotAllowed",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/storeProductNotAvailable",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServicePermissionDenied",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceNetworkConnectionFailed",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceRevoked",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/privacyAcknowledgementRequired",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/unauthorizedRequestData",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferIdentifier",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferPrice",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidSignature",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/missingOfferParams",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/ineligibleForOffer",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayCancelled",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayInvalidConfiguration",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayPresentedInBackgroundScene",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/overlayTimeout",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/unsupportedPlatform"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Error-domain",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain"
      ],
      "title": "Error domain"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code/title",
          "value": "SKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKErrorDomain/title",
          "value": "SKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
