{
  "abstract": [
    {
      "text": "Methods for responding to the overlay’s appearance, dismissal, or failure to load.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SKOverlayDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKOverlayDelegate"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKOverlayDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "SKOverlayDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKOverlayDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/TransitionContext": {
      "abstract": [
        {
          "text": "A context object you can use to animate UI changes while the platform presents or dismisses an overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TransitionContext"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/TransitionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TransitionContext"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay.TransitionContext",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/transitioncontext"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/delegate": {
      "abstract": [
        {
          "text": "The overlay’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SKOverlayDelegate",
          "text": "SKOverlayDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/delegate"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate": {
      "abstract": [
        {
          "text": "Methods for responding to the overlay’s appearance, dismissal, or failure to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKOverlayDelegate"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKOverlayDelegate"
        }
      ],
      "role": "symbol",
      "title": "SKOverlayDelegate",
      "type": "topic",
      "url": "/documentation/storekit/skoverlaydelegate"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFailToLoad(_:error:)": {
      "abstract": [
        {
          "text": "Indicates that an overlay failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeOverlayDidFailToLoad"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFailToLoad(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeOverlay:didFailToLoadWithError:"
        }
      ],
      "role": "symbol",
      "title": "storeOverlayDidFailToLoad(_:error:)",
      "type": "topic",
      "url": "/documentation/storekit/skoverlaydelegate/storeoverlaydidfailtoload(_:error:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFinishDismissal(_:transitionContext:)": {
      "abstract": [
        {
          "text": "Indicates that platform finished dismissing an overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeOverlayDidFinishDismissal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transitionContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlayTransitionContext",
          "text": "TransitionContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFinishDismissal(_:transitionContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeOverlay:didFinishDismissal:"
        }
      ],
      "role": "symbol",
      "title": "storeOverlayDidFinishDismissal(_:transitionContext:)",
      "type": "topic",
      "url": "/documentation/storekit/skoverlaydelegate/storeoverlaydidfinishdismissal(_:transitioncontext:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFinishPresentation(_:transitionContext:)": {
      "abstract": [
        {
          "text": "Indicates that the platform finished presenting an overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeOverlayDidFinishPresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transitionContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlayTransitionContext",
          "text": "TransitionContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFinishPresentation(_:transitionContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeOverlay:didFinishPresentation:"
        }
      ],
      "role": "symbol",
      "title": "storeOverlayDidFinishPresentation(_:transitionContext:)",
      "type": "topic",
      "url": "/documentation/storekit/skoverlaydelegate/storeoverlaydidfinishpresentation(_:transitioncontext:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayWillStartDismissal(_:transitionContext:)": {
      "abstract": [
        {
          "text": "Indicates that the platform dismisses an overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeOverlayWillStartDismissal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transitionContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlayTransitionContext",
          "text": "TransitionContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayWillStartDismissal(_:transitionContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeOverlay:willStartDismissal:"
        }
      ],
      "role": "symbol",
      "title": "storeOverlayWillStartDismissal(_:transitionContext:)",
      "type": "topic",
      "url": "/documentation/storekit/skoverlaydelegate/storeoverlaywillstartdismissal(_:transitioncontext:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayWillStartPresentation(_:transitionContext:)": {
      "abstract": [
        {
          "text": "Indicates that the platform presents an overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeOverlayWillStartPresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transitionContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlayTransitionContext",
          "text": "TransitionContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayWillStartPresentation(_:transitionContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeOverlay:willStartPresentation:"
        }
      ],
      "role": "symbol",
      "title": "storeOverlayWillStartPresentation(_:transitionContext:)",
      "type": "topic",
      "url": "/documentation/storekit/skoverlaydelegate/storeoverlaywillstartpresentation(_:transitioncontext:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-a-delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/delegate"
      ],
      "title": "Setting a delegate"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-the-Overlays-Appearance-and-Disappearance",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayWillStartPresentation(_:transitionContext:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFinishPresentation(_:transitionContext:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayWillStartDismissal(_:transitionContext:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFinishDismissal(_:transitionContext:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/TransitionContext"
      ],
      "title": "Responding to the Overlay’s Appearance and Disappearance"
    },
    {
      "anchor": "Responding-to-Failures",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFailToLoad(_:error:)"
      ],
      "title": "Responding to Failures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKOverlayDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-the-Overlays-Appearance-and-Disappearance",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayWillStartPresentation(_:transitionContext:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFinishPresentation(_:transitionContext:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayWillStartDismissal(_:transitionContext:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFinishDismissal(_:transitionContext:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/TransitionContext"
              ],
              "title": "Responding to the Overlay’s Appearance and Disappearance"
            },
            {
              "anchor": "Responding-to-Failures",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlayDelegate/storeOverlayDidFailToLoad(_:error:)"
              ],
              "title": "Responding to Failures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-a-delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/delegate"
              ],
              "title": "Setting a delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKOverlayDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayDidFailToLoad(_:error:)/title",
          "value": "storeOverlay:didFailToLoadWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayDidFailToLoad(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "storeOverlay:didFailToLoadWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayDidFinishDismissal(_:transitionContext:)/title",
          "value": "storeOverlay:didFinishDismissal:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayDidFinishDismissal(_:transitionContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "storeOverlay:didFinishDismissal:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1TransitionContext/title",
          "value": "SKOverlayTransitionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1TransitionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayTransitionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1TransitionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayTransitionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayWillStartPresentation(_:transitionContext:)/title",
          "value": "storeOverlay:willStartPresentation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayWillStartPresentation(_:transitionContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "storeOverlay:willStartPresentation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayDidFinishPresentation(_:transitionContext:)/title",
          "value": "storeOverlay:didFinishPresentation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayDidFinishPresentation(_:transitionContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "storeOverlay:didFinishPresentation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate/title",
          "value": "SKOverlayDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayWillStartDismissal(_:transitionContext:)/title",
          "value": "storeOverlay:willStartDismissal:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlayDelegate~1storeOverlayWillStartDismissal(_:transitionContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "storeOverlay:willStartDismissal:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skoverlaydelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skoverlaydelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
