{
  "abstract": [
    {
      "text": "Information about a registered product in App Store Connect.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use Product",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKProduct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKProduct",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKProduct"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKProduct"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "3.0",
        "message": "Use Product",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "3.0",
        "message": "Use Product",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Use Product",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.7",
        "message": "Use Product",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "message": "Use Product",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use Product",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "6.2",
        "message": "Use Product",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SKProduct"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKProduct"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/supporting-family-sharing-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/fetching-product-information-from-the-app-store",
        "doc://com.apple.storekit/documentation/StoreKit/requesting-a-payment-from-the-app-store"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects are returned as part of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductsResponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct": {
      "abstract": [
        {
          "text": "Information about a registered product in App Store Connect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProduct"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProduct"
        }
      ],
      "role": "symbol",
      "title": "SKProduct",
      "type": "topic",
      "url": "/documentation/storekit/skproduct"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit": {
      "abstract": [
        {
          "text": "Values representing the duration of an interval, from a day up to a year.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PeriodUnit"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PeriodUnit"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/contentLengths": {
      "abstract": [
        {
          "text": "The total size of the content, in bytes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentLengths"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/contentLengths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentLengths"
        }
      ],
      "role": "symbol",
      "title": "contentLengths",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/contentlengths"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/contentVersion": {
      "abstract": [
        {
          "text": "A string that identifies the version of the content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/contentVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentVersion"
        }
      ],
      "role": "symbol",
      "title": "contentVersion",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/contentversion"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/discounts": {
      "abstract": [
        {
          "text": "An array of subscription offers available for the auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discounts"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductDiscount",
          "text": "SKProductDiscount"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/discounts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discounts"
        }
      ],
      "role": "symbol",
      "title": "discounts",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/discounts"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadContentLengths": {
      "abstract": [
        {
          "text": "The lengths of the downloadable files available for this product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadContentLengths"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadContentLengths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downloadContentLengths"
        }
      ],
      "role": "symbol",
      "title": "downloadContentLengths",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/downloadcontentlengths"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadContentVersion": {
      "abstract": [
        {
          "text": "A string that identifies which version of the content is available for download.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadContentVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadContentVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downloadContentVersion"
        }
      ],
      "role": "symbol",
      "title": "downloadContentVersion",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/downloadcontentversion"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the App Store has downloadable content for this product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downloadable"
        }
      ],
      "role": "symbol",
      "title": "downloadable",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/downloadable"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice": {
      "abstract": [
        {
          "text": "The object containing introductory price information for the product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "introductoryPrice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductDiscount",
          "text": "SKProductDiscount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "introductoryPrice"
        }
      ],
      "role": "symbol",
      "title": "introductoryPrice",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/introductoryprice"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/isDownloadable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the App Store has downloadable content for this product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDownloadable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/isDownloadable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isDownloadable"
        }
      ],
      "role": "symbol",
      "title": "isDownloadable",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/isdownloadable"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/isFamilyShareable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the product is available for Family Sharing in App Store Connect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFamilyShareable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/isFamilyShareable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isFamilyShareable"
        }
      ],
      "role": "symbol",
      "title": "isFamilyShareable",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/isfamilyshareable"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/localizedDescription": {
      "abstract": [
        {
          "text": "A description of the product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/localizedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedDescription"
        }
      ],
      "role": "symbol",
      "title": "localizedDescription",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/localizeddescription"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/localizedTitle": {
      "abstract": [
        {
          "text": "The name of the product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/localizedTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedTitle"
        }
      ],
      "role": "symbol",
      "title": "localizedTitle",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/localizedtitle"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/price": {
      "abstract": [
        {
          "text": "The cost of the product in the local currency.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "price"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
          "text": "NSDecimalNumber"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/price",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "price"
        }
      ],
      "role": "symbol",
      "title": "price",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/price"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/priceLocale": {
      "abstract": [
        {
          "text": "The locale used to format the price of the product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "priceLocale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/priceLocale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "priceLocale"
        }
      ],
      "role": "symbol",
      "title": "priceLocale",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/pricelocale"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/productIdentifier": {
      "abstract": [
        {
          "text": "The string that identifies the product to the Apple App Store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/productIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "productIdentifier"
        }
      ],
      "role": "symbol",
      "title": "productIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/productidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/subscriptionGroupIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the subscription group to which the subscription belongs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionGroupIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/subscriptionGroupIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriptionGroupIdentifier"
        }
      ],
      "role": "symbol",
      "title": "subscriptionGroupIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/subscriptiongroupidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/subscriptionPeriod": {
      "abstract": [
        {
          "text": "The period details for products that are subscriptions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionPeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductSubscriptionPeriod",
          "text": "SKProductSubscriptionPeriod"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/subscriptionPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriptionPeriod"
        }
      ],
      "role": "symbol",
      "title": "subscriptionPeriod",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/subscriptionperiod"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount": {
      "abstract": [
        {
          "text": "The details of an introductory offer or a promotional offer for an auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductSubscriptionPeriod": {
      "abstract": [
        {
          "text": "An object containing the subscription period duration information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductSubscriptionPeriod"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductSubscriptionPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductSubscriptionPeriod"
        }
      ],
      "role": "symbol",
      "title": "SKProductSubscriptionPeriod",
      "type": "topic",
      "url": "/documentation/storekit/skproductsubscriptionperiod"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductsRequest": {
      "abstract": [
        {
          "text": "An object that can retrieve localized information from the App Store about a specified list of products.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductsRequest"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductsRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductsRequest"
        }
      ],
      "role": "symbol",
      "title": "SKProductsRequest",
      "type": "topic",
      "url": "/documentation/storekit/skproductsrequest"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductsResponse": {
      "abstract": [
        {
          "text": "An App Store response to a request for information about a list of products.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductsResponse"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductsResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductsResponse"
        }
      ],
      "role": "symbol",
      "title": "SKProductsResponse",
      "type": "topic",
      "url": "/documentation/storekit/skproductsresponse"
    },
    "doc://com.apple.storekit/documentation/StoreKit/fetching-product-information-from-the-app-store": {
      "abstract": [
        {
          "text": "Retrieve up-to-date information about the products for sale in your app to display to your customers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/fetching-product-information-from-the-app-store",
      "kind": "article",
      "role": "article",
      "title": "Fetching product information from the App Store",
      "type": "topic",
      "url": "/documentation/storekit/fetching-product-information-from-the-app-store"
    },
    "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app": {
      "abstract": [
        {
          "text": "Offer discounted pricing for auto-renewable subscription products to eligible subscribers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Implementing promotional offers in your app",
      "type": "topic",
      "url": "/documentation/storekit/implementing-promotional-offers-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/loading-in-app-product-identifiers": {
      "abstract": [
        {
          "text": "Load the unique identifiers for your in-app products to retrieve product information from the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/loading-in-app-product-identifiers",
      "kind": "article",
      "role": "article",
      "title": "Loading in-app product identifiers",
      "type": "topic",
      "url": "/documentation/storekit/loading-in-app-product-identifiers"
    },
    "doc://com.apple.storekit/documentation/StoreKit/requesting-a-payment-from-the-app-store": {
      "abstract": [
        {
          "text": "Submit a payment request to the App Store when a customer selects a product to buy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/requesting-a-payment-from-the-app-store",
      "kind": "article",
      "role": "article",
      "title": "Requesting a payment from the App Store",
      "type": "topic",
      "url": "/documentation/storekit/requesting-a-payment-from-the-app-store"
    },
    "doc://com.apple.storekit/documentation/StoreKit/supporting-family-sharing-in-your-app": {
      "abstract": [
        {
          "text": "Provide service to share subscriptions and non-consumable products to family members.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-family-sharing-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting Family Sharing in your app",
      "type": "topic",
      "url": "/documentation/storekit/supporting-family-sharing-in-your-app"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Product-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/loading-in-app-product-identifiers",
        "doc://com.apple.storekit/documentation/StoreKit/fetching-product-information-from-the-app-store",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductsRequest",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductsResponse"
      ],
      "title": "Product information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Product-Identifier",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/productIdentifier"
      ],
      "title": "Getting the Product Identifier"
    },
    {
      "anchor": "Getting-Product-Attributes",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/localizedDescription",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/localizedTitle",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/contentVersion",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/isFamilyShareable",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/contentLengths"
      ],
      "title": "Getting Product Attributes"
    },
    {
      "anchor": "Getting-Pricing-Information",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/price",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/priceLocale",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/discounts",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount"
      ],
      "title": "Getting Pricing Information"
    },
    {
      "anchor": "Getting-Subscription-Information",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/subscriptionGroupIdentifier",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/subscriptionPeriod",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductSubscriptionPeriod",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit"
      ],
      "title": "Getting Subscription Information"
    },
    {
      "anchor": "Getting-Downloadable-Content-Information",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/isDownloadable",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadContentLengths",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadContentVersion",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadable"
      ],
      "title": "Getting Downloadable Content Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKProduct"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Product-Identifier",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/productIdentifier"
              ],
              "title": "Getting the Product Identifier"
            },
            {
              "anchor": "Getting-Product-Attributes",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/localizedDescription",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/localizedTitle",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/contentVersion",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/isFamilyShareable",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/contentLengths"
              ],
              "title": "Getting Product Attributes"
            },
            {
              "anchor": "Getting-Pricing-Information",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/price",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/priceLocale",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/discounts",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount"
              ],
              "title": "Getting Pricing Information"
            },
            {
              "anchor": "Getting-Subscription-Information",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/subscriptionGroupIdentifier",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/subscriptionPeriod",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductSubscriptionPeriod",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit"
              ],
              "title": "Getting Subscription Information"
            },
            {
              "anchor": "Getting-Downloadable-Content-Information",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/isDownloadable",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadContentLengths",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadContentVersion",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/downloadable"
              ],
              "title": "Getting Downloadable Content Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Product-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/loading-in-app-product-identifiers",
                "doc://com.apple.storekit/documentation/StoreKit/fetching-product-information-from-the-app-store",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductsRequest",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductsResponse"
              ],
              "title": "Product information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKProduct"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use Product",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1isFamilyShareable/title",
          "value": "isFamilyShareable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1isFamilyShareable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isFamilyShareable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1downloadContentLengths/title",
          "value": "downloadContentLengths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1downloadContentLengths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "downloadContentLengths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1isDownloadable/title",
          "value": "isDownloadable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1isDownloadable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isDownloadable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1productIdentifier/title",
          "value": "productIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1productIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "productIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1contentVersion/title",
          "value": "contentVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1contentVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct/title",
          "value": "SKProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1localizedDescription/title",
          "value": "localizedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1localizedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1subscriptionGroupIdentifier/title",
          "value": "subscriptionGroupIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1subscriptionGroupIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriptionGroupIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1downloadContentVersion/title",
          "value": "downloadContentVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1downloadContentVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "downloadContentVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductSubscriptionPeriod/title",
          "value": "SKProductSubscriptionPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductSubscriptionPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductSubscriptionPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductSubscriptionPeriod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductSubscriptionPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductsResponse/title",
          "value": "SKProductsResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductsResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductsResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductsResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductsResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1discounts/title",
          "value": "discounts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1discounts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "discounts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1introductoryPrice/title",
          "value": "introductoryPrice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1introductoryPrice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "introductoryPrice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1localizedTitle/title",
          "value": "localizedTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1localizedTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1price/title",
          "value": "price"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1price/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "price"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1downloadable/title",
          "value": "downloadable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1downloadable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "downloadable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductsRequest/title",
          "value": "SKProductsRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductsRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductsRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductsRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductsRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1contentLengths/title",
          "value": "contentLengths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1contentLengths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentLengths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit/title",
          "value": "SKProductPeriodUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1subscriptionPeriod/title",
          "value": "subscriptionPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1subscriptionPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriptionPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1priceLocale/title",
          "value": "priceLocale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1priceLocale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "priceLocale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/title",
          "value": "SKProductDiscount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skproduct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skproduct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
