{
  "abstract": [
    {
      "text": "The details of an introductory offer or a promotional offer for an auto-renewable subscription.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use Product.SubscriptionOffer",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKProductDiscount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKProductDiscount"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKProductDiscount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.2",
        "message": "Use Product.SubscriptionOffer",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.2",
        "message": "Use Product.SubscriptionOffer",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Use Product.SubscriptionOffer",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.13.2",
        "message": "Use Product.SubscriptionOffer",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.2",
        "message": "Use Product.SubscriptionOffer",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use Product.SubscriptionOffer",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "6.2",
        "message": "Use Product.SubscriptionOffer",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SKProductDiscount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You set up introductory and promotional offers in App Store Connect. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " contains the offer information as retrieved from the App Store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about setting up offers, see ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/app-store-connect/#/deve1d49254f",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/app-store-connect/#/dev16dfca448",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/discounts": {
      "abstract": [
        {
          "text": "An array of subscription offers available for the auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discounts"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductDiscount",
          "text": "SKProductDiscount"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/discounts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discounts"
        }
      ],
      "role": "symbol",
      "title": "discounts",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/discounts"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice": {
      "abstract": [
        {
          "text": "The object containing introductory price information for the product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "introductoryPrice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductDiscount",
          "text": "SKProductDiscount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "introductoryPrice"
        }
      ],
      "role": "symbol",
      "title": "introductoryPrice",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/introductoryprice"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/price": {
      "abstract": [
        {
          "text": "The cost of the product in the local currency.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "price"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
          "text": "NSDecimalNumber"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/price",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "price"
        }
      ],
      "role": "symbol",
      "title": "price",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/price"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/priceLocale": {
      "abstract": [
        {
          "text": "The locale used to format the price of the product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "priceLocale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/priceLocale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "priceLocale"
        }
      ],
      "role": "symbol",
      "title": "priceLocale",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/pricelocale"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount": {
      "abstract": [
        {
          "text": "The details of an introductory offer or a promotional offer for an auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum": {
      "abstract": [
        {
          "text": "Values representing the payment modes for a product discount.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PaymentMode"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PaymentMode"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount.PaymentMode",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/paymentmode-swift.enum"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/Type-swift.enum": {
      "abstract": [
        {
          "text": "Values representing the types of discount offers an app can present.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Type"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/Type-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Type"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount.Type",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/type-swift.enum"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/identifier": {
      "abstract": [
        {
          "text": "A string used to uniquely identify a discount offer for a product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/identifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/numberOfPeriods": {
      "abstract": [
        {
          "text": "An integer that indicates the number of periods the product discount is available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfPeriods"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/numberOfPeriods",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfPeriods"
        }
      ],
      "role": "symbol",
      "title": "numberOfPeriods",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/numberofperiods"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/paymentMode-swift.property": {
      "abstract": [
        {
          "text": "The payment mode for this product discount.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductDiscount",
          "text": "SKProductDiscount"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKProductDiscountPaymentMode",
          "text": "PaymentMode"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/paymentMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentMode"
        }
      ],
      "role": "symbol",
      "title": "paymentMode",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/paymentmode-swift.property"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/price": {
      "abstract": [
        {
          "text": "The discount price of the product in the local currency.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "price"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
          "text": "NSDecimalNumber"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/price",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "price"
        }
      ],
      "role": "symbol",
      "title": "price",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/price"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/priceLocale": {
      "abstract": [
        {
          "text": "The locale used to format the discount price of the product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "priceLocale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/priceLocale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "priceLocale"
        }
      ],
      "role": "symbol",
      "title": "priceLocale",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/pricelocale"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/subscriptionPeriod": {
      "abstract": [
        {
          "text": "An object that defines the period for the product discount.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionPeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductSubscriptionPeriod",
          "text": "SKProductSubscriptionPeriod"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/subscriptionPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriptionPeriod"
        }
      ],
      "role": "symbol",
      "title": "subscriptionPeriod",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/subscriptionperiod"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/type-swift.property": {
      "abstract": [
        {
          "text": "The type of discount offer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductDiscount",
          "text": "SKProductDiscount"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKProductDiscountType",
          "text": "Type"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/type-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/type-swift.property"
    },
    "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app": {
      "abstract": [
        {
          "text": "Offer discounted pricing for auto-renewable subscription products to eligible subscribers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Implementing promotional offers in your app",
      "type": "topic",
      "url": "/documentation/storekit/implementing-promotional-offers-in-your-app"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://help.apple.com/app-store-connect/#/dev16dfca448": {
      "identifier": "https://help.apple.com/app-store-connect/#/dev16dfca448",
      "title": "Set up promotional offers for auto-renewable subscriptions",
      "titleInlineContent": [
        {
          "text": "Set up promotional offers for auto-renewable subscriptions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/app-store-connect/#/dev16dfca448"
    },
    "https://help.apple.com/app-store-connect/#/deve1d49254f": {
      "identifier": "https://help.apple.com/app-store-connect/#/deve1d49254f",
      "title": "Set an introductory offer for an auto-renewable subscription",
      "titleInlineContent": [
        {
          "text": "Set an introductory offer for an auto-renewable subscription",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/app-store-connect/#/deve1d49254f"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Pricing-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/price",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/priceLocale",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/discounts"
      ],
      "title": "Getting Pricing Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Identifying-the-Discount",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/identifier",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/type-swift.property",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/Type-swift.enum"
      ],
      "title": "Identifying the Discount"
    },
    {
      "anchor": "Getting-Price-and-Payment-Mode",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/price",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/priceLocale",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/paymentMode-swift.property",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum"
      ],
      "title": "Getting Price and Payment Mode"
    },
    {
      "anchor": "Getting-the-Discount-Duration",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/numberOfPeriods",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/subscriptionPeriod"
      ],
      "title": "Getting the Discount Duration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.13.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKProductDiscount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Identifying-the-Discount",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/identifier",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/type-swift.property",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/Type-swift.enum"
              ],
              "title": "Identifying the Discount"
            },
            {
              "anchor": "Getting-Price-and-Payment-Mode",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/price",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/priceLocale",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/paymentMode-swift.property",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/PaymentMode-swift.enum"
              ],
              "title": "Getting Price and Payment Mode"
            },
            {
              "anchor": "Getting-the-Discount-Duration",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/numberOfPeriods",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/subscriptionPeriod"
              ],
              "title": "Getting the Discount Duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Pricing-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/price",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/priceLocale",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/introductoryPrice",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/discounts"
              ],
              "title": "Getting Pricing Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKProductDiscount"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use Product.SubscriptionOffer",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum/title",
          "value": "SKProductDiscountPaymentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscountPaymentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1PaymentMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscountPaymentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1numberOfPeriods/title",
          "value": "numberOfPeriods"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1numberOfPeriods/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfPeriods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1introductoryPrice/title",
          "value": "introductoryPrice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1introductoryPrice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "introductoryPrice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1price/title",
          "value": "price"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1price/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "price"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/title",
          "value": "SKProductDiscount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1Type-swift.enum/title",
          "value": "SKProductDiscountType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1Type-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1Type-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1paymentMode-swift.property/title",
          "value": "paymentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1paymentMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paymentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1discounts/title",
          "value": "discounts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1discounts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "discounts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1priceLocale/title",
          "value": "priceLocale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1priceLocale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "priceLocale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1type-swift.property/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1type-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1price/title",
          "value": "price"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1price/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "price"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1subscriptionPeriod/title",
          "value": "subscriptionPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1subscriptionPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriptionPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1priceLocale/title",
          "value": "priceLocale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1priceLocale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "priceLocale"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skproductdiscount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skproductdiscount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
