{
  "abstract": [
    {
      "text": "Terminates an app if the license to use the app has expired.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKTerminateForInvalidReceipt()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SKTerminateForInvalidReceipt",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKTerminateForInvalidReceipt"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKTerminateForInvalidReceipt"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SKTerminateForInvalidReceipt()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKTerminateForInvalidReceipt"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransaction": {
      "abstract": [
        {
          "text": "An object in the payment queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPaymentTransaction"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransaction"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransaction",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKReceiptRefreshRequest": {
      "abstract": [
        {
          "text": "A request to the App Store to get the app receipt, which represents the customer’s transactions with your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKReceiptRefreshRequest"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKReceiptRefreshRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKReceiptRefreshRequest"
        }
      ],
      "role": "symbol",
      "title": "SKReceiptRefreshRequest",
      "type": "topic",
      "url": "/documentation/storekit/skreceiptrefreshrequest"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKRequest": {
      "abstract": [
        {
          "text": "An abstract class that represents a request to the App Store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKRequest"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRequest"
        }
      ],
      "role": "symbol",
      "title": "SKRequest",
      "type": "topic",
      "url": "/documentation/storekit/skrequest"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKTerminateForInvalidReceipt()": {
      "abstract": [
        {
          "text": "Terminates an app if the license to use the app has expired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTerminateForInvalidReceipt"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKTerminateForInvalidReceipt()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTerminateForInvalidReceipt"
        }
      ],
      "role": "symbol",
      "title": "SKTerminateForInvalidReceipt()",
      "type": "topic",
      "url": "/documentation/storekit/skterminateforinvalidreceipt()"
    },
    "doc://com.apple.storekit/documentation/StoreKit/restoring-purchased-products": {
      "abstract": [
        {
          "text": "Give customers functionality that restores their purchases in your app to maintain access to purchased content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/restoring-purchased-products",
      "kind": "article",
      "role": "article",
      "title": "Restoring purchased products",
      "type": "topic",
      "url": "/documentation/storekit/restoring-purchased-products"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-access-to-previously-purchased-products",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/restoring-purchased-products",
        "doc://com.apple.storekit/documentation/StoreKit/SKReceiptRefreshRequest",
        "doc://com.apple.storekit/documentation/StoreKit/SKRequest",
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransaction"
      ],
      "title": "Providing access to previously purchased products"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKTerminateForInvalidReceipt"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTerminateForInvalidReceipt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-access-to-previously-purchased-products",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/restoring-purchased-products",
                "doc://com.apple.storekit/documentation/StoreKit/SKReceiptRefreshRequest",
                "doc://com.apple.storekit/documentation/StoreKit/SKRequest",
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransaction"
              ],
              "title": "Providing access to previously purchased products"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKTerminateForInvalidReceipt"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKTerminateForInvalidReceipt()/title",
          "value": "SKTerminateForInvalidReceipt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKTerminateForInvalidReceipt()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTerminateForInvalidReceipt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKReceiptRefreshRequest/title",
          "value": "SKReceiptRefreshRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKReceiptRefreshRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKReceiptRefreshRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKReceiptRefreshRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKReceiptRefreshRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKRequest/title",
          "value": "SKRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransaction/title",
          "value": "SKPaymentTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransaction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransaction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skterminateforinvalidreceipt()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skterminateforinvalidreceipt()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
