{
  "abstract": [
    {
      "text": "Offer customers additional time-based content and services through purchases they make within your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/subscriptions-and-offers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Subscriptions and offers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount": {
      "abstract": [
        {
          "text": "The signed discount to apply to a payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPaymentDiscount"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentDiscount"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentDiscount",
      "type": "topic",
      "url": "/documentation/storekit/skpaymentdiscount"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount": {
      "abstract": [
        {
          "text": "The details of an introductory offer or a promotional offer for an auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount"
    },
    "doc://com.apple.storekit/documentation/StoreKit/determining-service-entitlement-on-the-server": {
      "abstract": [
        {
          "text": "Identify a customer’s entitlement to your service, offers, and messaging by analyzing a validated receipt and the state of their subscription.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/determining-service-entitlement-on-the-server",
      "kind": "article",
      "role": "sampleCode",
      "title": "Determining service entitlement on the server",
      "type": "topic",
      "url": "/documentation/storekit/determining-service-entitlement-on-the-server"
    },
    "doc://com.apple.storekit/documentation/StoreKit/enabling-app-store-server-notifications": {
      "abstract": [
        {
          "text": "Configure your server and provide an HTTPS URL to receive notifications about in-app purchase events and unreported external purchase tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/enabling-app-store-server-notifications",
      "kind": "article",
      "role": "article",
      "title": "Enabling App Store Server Notifications",
      "type": "topic",
      "url": "/documentation/storekit/enabling-app-store-server-notifications"
    },
    "doc://com.apple.storekit/documentation/StoreKit/generating-a-promotional-offer-signature-on-the-server": {
      "abstract": [
        {
          "text": "Generate a signature using your private key and lightweight cryptography libraries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/generating-a-promotional-offer-signature-on-the-server",
      "kind": "article",
      "role": "sampleCode",
      "title": "Generating a Promotional Offer Signature on the Server",
      "type": "topic",
      "url": "/documentation/storekit/generating-a-promotional-offer-signature-on-the-server"
    },
    "doc://com.apple.storekit/documentation/StoreKit/generating-a-signature-for-promotional-offers": {
      "abstract": [
        {
          "text": "Create a signature to validate a promotional offer using your private key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/generating-a-signature-for-promotional-offers",
      "kind": "article",
      "role": "article",
      "title": "Generating a signature for promotional offers",
      "type": "topic",
      "url": "/documentation/storekit/generating-a-signature-for-promotional-offers"
    },
    "doc://com.apple.storekit/documentation/StoreKit/handling-subscriptions-billing": {
      "abstract": [
        {
          "text": "Build logic around the date and time constraints of subscription products, while planning for all scenarios where you control access to content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/handling-subscriptions-billing",
      "kind": "article",
      "role": "article",
      "title": "Handling Subscriptions Billing",
      "type": "topic",
      "url": "/documentation/storekit/handling-subscriptions-billing"
    },
    "doc://com.apple.storekit/documentation/StoreKit/implementing-introductory-offers-in-your-app": {
      "abstract": [
        {
          "text": "Offer introductory pricing for auto-renewable subscriptions to eligible users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/implementing-introductory-offers-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Implementing introductory offers in your app",
      "type": "topic",
      "url": "/documentation/storekit/implementing-introductory-offers-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/implementing-offer-codes-in-your-app": {
      "abstract": [
        {
          "text": "Provide subscription service for customers who redeem offer codes through the App Store or within an app that uses receipts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/implementing-offer-codes-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Implementing offer codes in your app",
      "type": "topic",
      "url": "/documentation/storekit/implementing-offer-codes-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app": {
      "abstract": [
        {
          "text": "Offer discounted pricing for auto-renewable subscription products to eligible subscribers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Implementing promotional offers in your app",
      "type": "topic",
      "url": "/documentation/storekit/implementing-promotional-offers-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/offering-a-subscription-across-multiple-apps": {
      "abstract": [
        {
          "text": "Support a single auto-renewable subscription across multiple apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/offering-a-subscription-across-multiple-apps",
      "kind": "article",
      "role": "article",
      "title": "Offering a Subscription Across Multiple Apps",
      "type": "topic",
      "url": "/documentation/storekit/offering-a-subscription-across-multiple-apps"
    },
    "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase": {
      "abstract": [
        {
          "text": "Offer additional content and services in your app using the Original In-App Purchase API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original API for In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/original-api-for-in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/reducing-involuntary-subscriber-churn": {
      "abstract": [
        {
          "text": "Prevent unintentional loss of subscribers due to billing issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/reducing-involuntary-subscriber-churn",
      "kind": "article",
      "role": "article",
      "title": "Reducing Involuntary Subscriber Churn",
      "type": "topic",
      "url": "/documentation/storekit/reducing-involuntary-subscriber-churn"
    },
    "doc://com.apple.storekit/documentation/StoreKit/setting-up-promotional-offers": {
      "abstract": [
        {
          "text": "Generate a key and configure offers for auto-renewable subscriptions in App Store Connect.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/setting-up-promotional-offers",
      "kind": "article",
      "role": "article",
      "title": "Setting up promotional offers",
      "type": "topic",
      "url": "/documentation/storekit/setting-up-promotional-offers"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-introductory-offers": {
      "abstract": [
        {
          "text": "Test your introductory pricing in a variety of user scenarios.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-introductory-offers",
      "kind": "article",
      "role": "article",
      "title": "Testing introductory offers",
      "type": "topic",
      "url": "/documentation/storekit/testing-introductory-offers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/handling-subscriptions-billing",
        "doc://com.apple.storekit/documentation/StoreKit/enabling-app-store-server-notifications",
        "doc://com.apple.storekit/documentation/StoreKit/offering-a-subscription-across-multiple-apps",
        "doc://com.apple.storekit/documentation/StoreKit/reducing-involuntary-subscriber-churn"
      ],
      "title": "Essentials"
    },
    {
      "abstract": [
        {
          "text": "Provide discount pricing for new customers to encourage them to subscribe.",
          "type": "text"
        }
      ],
      "anchor": "Introductory-offers",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/implementing-introductory-offers-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/testing-introductory-offers",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount"
      ],
      "title": "Introductory offers"
    },
    {
      "abstract": [
        {
          "text": "Provide discount pricing for existing or previously subscribed customers to encourage them to renew.",
          "type": "text"
        }
      ],
      "anchor": "Promotional-offers",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/setting-up-promotional-offers",
        "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/generating-a-signature-for-promotional-offers",
        "doc://com.apple.storekit/documentation/StoreKit/generating-a-promotional-offer-signature-on-the-server",
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount"
      ],
      "title": "Promotional offers"
    },
    {
      "abstract": [
        {
          "text": "Provide offer codes to customers to acquire, retain, and win back subscribers.",
          "type": "text"
        }
      ],
      "anchor": "Subscription-offer-codes",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/implementing-offer-codes-in-your-app"
      ],
      "title": "Subscription offer codes"
    },
    {
      "anchor": "Subscription-service-entitlement",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/determining-service-entitlement-on-the-server"
      ],
      "title": "Subscription service entitlement"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/handling-subscriptions-billing",
                "doc://com.apple.storekit/documentation/StoreKit/enabling-app-store-server-notifications",
                "doc://com.apple.storekit/documentation/StoreKit/offering-a-subscription-across-multiple-apps",
                "doc://com.apple.storekit/documentation/StoreKit/reducing-involuntary-subscriber-churn"
              ],
              "title": "Essentials"
            },
            {
              "abstract": [
                {
                  "text": "Provide discount pricing for new customers to encourage them to subscribe.",
                  "type": "text"
                }
              ],
              "anchor": "Introductory-offers",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/implementing-introductory-offers-in-your-app",
                "doc://com.apple.storekit/documentation/StoreKit/testing-introductory-offers",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount"
              ],
              "title": "Introductory offers"
            },
            {
              "abstract": [
                {
                  "text": "Provide discount pricing for existing or previously subscribed customers to encourage them to renew.",
                  "type": "text"
                }
              ],
              "anchor": "Promotional-offers",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/setting-up-promotional-offers",
                "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app",
                "doc://com.apple.storekit/documentation/StoreKit/generating-a-signature-for-promotional-offers",
                "doc://com.apple.storekit/documentation/StoreKit/generating-a-promotional-offer-signature-on-the-server",
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount"
              ],
              "title": "Promotional offers"
            },
            {
              "abstract": [
                {
                  "text": "Provide offer codes to customers to acquire, retain, and win back subscribers.",
                  "type": "text"
                }
              ],
              "anchor": "Subscription-offer-codes",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/implementing-offer-codes-in-your-app"
              ],
              "title": "Subscription offer codes"
            },
            {
              "anchor": "Subscription-service-entitlement",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/determining-service-entitlement-on-the-server"
              ],
              "title": "Subscription service entitlement"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/title",
          "value": "SKProductDiscount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount/title",
          "value": "SKPaymentDiscount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentDiscount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/subscriptions-and-offers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/subscriptions-and-offers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
