{
  "abstract": [
    {
      "text": "Re-engage previous subscribers with a free or discounted offer for an auto-renewable subscription, for a specific duration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/supporting-win-back-offers-in-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Supporting win-back offers in your app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A win-back offer is a free or discounted offer for an auto-renewable subscription for eligible customers whose subscription is ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "churned",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". A churned subscription is one that has an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/expirationDate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the past, and a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/willAutoRenew",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value of ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ". You set up win-back offers in App Store Connect, including the criteria that determines whether a customer is eligible. You can base eligibility on the duration of the customer’s paid subscription, the time since the subscription expired, and the time that must pass between redeemed offers. You also set the discount type, and specify the regions or countries in which the offer is available.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Session 10110: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc24/10110",
                  "isActive": true,
                  "type": "reference"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Related sessions from WWDC24",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "You can merchandise win-back offers in multiple ways. App Store Connect provides a direct link that you can share through your own channels, such as email. Customers can also discover and redeem win-back offers in the App Store, in their Apple account in the Subscription settings, and in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Within your app, you can merchandise win-back offers with the win-back offer sheet, using StoreKit views, or by using other StoreKit APIs to fully customize your own merchandising.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your app needs to handle win-back offers that customers redeem outside the app. By default, your app receives a completed purchase transaction when someone redeems the offer outside of the app. This workflow results when the Streamlined Purchasing option in App Store Connect is on, its default state. You can choose to turn off Streamlined Purchasing to enable the customer to complete the purchase within your app. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-win-back-offers-in-your-app#Handle-win-back-offers-redeemed-outside-of-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-win-back-offers-in-App-Store-Connect",
          "level": 3,
          "text": "Configure win-back offers in App Store Connect",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set up win-back offers in App Store Connect by following the instructions in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/app-store-connect/manage-subscriptions/set-up-win-back-offers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". As you set up a win-back offer, consider the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You create the win-back offer identifier. This alphanumeric string appears in transaction information and subscription renewal information.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "After you confirm the win-back offer details, App Store Connect creates a numeric win-back offer Apple ID for the offer, and a direct link. The direct link uses the offer’s Apple ID, and has the format ",
                      "type": "text"
                    },
                    {
                      "code": "https://apps.apple.com/win-back/<win-back offer Apple ID>",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add an approved subscription image in App Store Connect. The App Store requires the image if you choose to promote the win-back offer on the App Store. The win-back offer sheet and the direct link also use the image, if it’s available. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/help/app-store-connect/manage-in-app-purchases/view-and-edit-in-app-purchase-information#add-or-remove-an-image",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Store the win-back offer identifier and its corresponding direct link on your server, for easy access later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "anchor": "Configure-Streamlined-Purchasing-in-App-Store-Connect",
          "level": 3,
          "text": "Configure Streamlined Purchasing in App Store Connect",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you set up your win-back offer, you can also set the Streamlined Purchasing option in App Store Connect. This setting applies to all win-back offers and contingent pricing in your app. It affects how your app handles a win-back offer redemption, as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "With Streamlined Purchasing on (default), the customer completes the win-back offer purchase outside of your app. Your app receives a completed purchase transaction in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " sequence if it’s running, and in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/all",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/currentEntitlements",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " sequences otherwise. Your app is responsible for unlocking the purchased product, as usual.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "With Streamlined Purchasing turned off, your app has the opportunity to perform processing related to the win-back offer before it enables the customer to complete the purchase. The workflow starts when the customer initiates the purchase outside of your app. The system prompts them to install the app if it isn’t already installed. Your app receives a_ _purchase intent in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/intents",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " sequence, instead of a transaction, and must use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " API to complete the purchase.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If customers redeem a win-back offer through the manage subscriptions page in their Apple account, the redemption always behaves as if Streamline Purchasing is on, and your app receives a completed purchase transaction.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Before you can turn off the Streamlined Purchasing option in App Store Connect, your lastest approved app binary must use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " API.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on configuring this setting in App Store Connect, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/app-store-connect/manage-subscriptions/manage-streamlined-purchasing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Merchandise-win-back-offers-in-your-app",
          "level": 3,
          "text": "Merchandise win-back offers in your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "StoreKit provides several ways to merchandise win-back offers to eligible customers in your app. By default, StoreKit displays a win-back offer sheet when it receives a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message/Reason-swift.struct/winBackOffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " message from the App Store. You can also merchandise the win-back offer using StoreKit views, or other StoreKit APIs to fully customize the experience.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information on implementing each of these options, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/merchandising-win-back-offers-in-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Merchandise-win-back-offers-outside-your-app-using-the-direct-link",
          "level": 3,
          "text": "Merchandise win-back offers outside your app using the direct link",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you create a win-back offer, App Store Connect provides a direct link. Use the direct link to merchandise the win-back offer through your own channels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before you send a direct link to a customer, check whether the customer is eligible to redeem the offer by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/GET-v1-subscriptions-_transactionId_",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint from your server. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/JWSRenewalInfoDecodedPayload",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " from the response contains the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/eligibleWinBackOfferIds",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array, which lists the eligible offers. Send the direct link to eligible customers only.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/eligibleWinBackOfferIds",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array has multiple entries, the customer is eligible for more than one offer. The App Store sets the order of the win-back offer IDs with the best offer first. The order takes into account the available offers you configure in App Store Connect for the customer’s most recent subscription in the subscription group.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Handle-offers-redeemed-through-the-win-back-offer-sheet",
          "level": 3,
          "text": "Handle offers redeemed through the win-back offer sheet",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When customers redeem a win-back offer using the win-back offer sheet, StoreKit treats this transaction the same as a purchase that occurs outside of the app. Specifically, the app receives the transaction in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sequence of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Be sure your app creates a task to iterate through ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " as soon as it launches. For more information and sample code, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Handle-win-back-offers-redeemed-outside-of-your-app",
          "level": 3,
          "text": "Handle win-back offers redeemed outside of your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Customers can discover and redeem win-back offers outside of your app in several ways: through the direct link that you merchandise, in the App Store, and when they manage their subscriptions in their Apple account. How your app handles the redemption depends on the whether the Streamlined Purchasing setting is on or off in App Store Connect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If Streamlined Purchasing is on (the default setting), customers complete the win-back offer purchase outside of your app. Your app receives the completed purchase transaction the next time they open the app. Treat this transaction the same as any purchase that completes outside of your app, and unlock the purchased content. Specifically:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To get the transactions that occurred in the past, including while your app wasn’t running, iterate the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/all",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/currentEntitlements",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " sequences on ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " when the app launches.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To observe transactions that occur outside of the app while the app is running, iterate ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " on ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Create a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Swift/Task",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to iterate through the transactions from the listener as soon as your app launches. For more information and sample code, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The transaction entitles the customer to the auto-renewable subscription. Your app unlocks the purchased content and finishes the transaction with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/finish()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you turn off Streamlined Purchasing in App Store Connect, your app receives a purchase intent instead of a completed transaction. When a customer initiates a redemption outside your app, with Streamlined Purchasing off, the flow is as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system opens your app if it isn’t already running. StoreKit doesn’t display the win-back offer sheet when a purchase intent is in progress.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "StoreKit sends the win-back offer information to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/intents",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " asynchronous sequence of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your app has the opportunity to perform any actions related to the purchase before it prompts the customer to complete the purchase. For example, your app might ask the customer to log in.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your app calls the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/purchase(options:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method on the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/product",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to enable the customer to complete the purchase. Be sure to add the win-back offer to the purchase options.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following example checks the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/offer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to detect whether the purchase intent is for a win-back offer, and adds the offer to the purchase options:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Prepare the purchase options.",
            "var purchaseOptions: Set<Product.PurchaseOption> = []",
            "",
            "// Add the win-back offer to the purchase.",
            "if let offer = purchaseIntent.offer, offer.type == .winBack {",
            "    purchaseOptions.insert(.winBackOffer(offer))",
            "}",
            "",
            "// Present the purchase.",
            "let result = try await purchaseIntent.product.purchase(options: purchaseOptions)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, follow the same workflow your app uses for any successful purchase, such as unlocking the purchased content and finishing the transaction with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/finish()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If your app uses the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " API but doesn’t explicitly add support for win-back offers using ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/offer",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", StoreKit adds the win-back offer to the purchase options on devices running iOS 18 and later and visionOS 2 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Identify-subscriptions-purchased-with-a-win-back-offer",
          "level": 3,
          "text": "Identify subscriptions purchased with a win-back offer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When customers successfully redeem subscription offers, including win-back offers, the transaction information contains the offer details. Find those details in the app and on your server, as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In your app, check the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property, ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/offer-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". An offer type value of ",
                      "type": "text"
                    },
                    {
                      "code": "winback",
                      "type": "codeVoice"
                    },
                    {
                      "text": " indicates the customer redeemed a win-back offer.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On your server, check the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/JWSTransactionDecodedPayload",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " that you receive in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerNotifications/App-Store-Server-Notifications-V2",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " notifications or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " responses. The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/offerIdentifier",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " represents the offer that’s applied to the transaction. An ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/offerType",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " of ",
                      "type": "text"
                    },
                    {
                      "code": "4",
                      "type": "codeVoice"
                    },
                    {
                      "text": " indicates a win-back offer.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Testing-win-back-offers",
          "level": 3,
          "text": "Testing win-back offers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can test win-back offers early in your development using StoreKit Testing in Xcode, and in the sandbox environment. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-xcode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppStoreServerAPI": {
      "abstract": [
        {
          "text": "Manage your customers’ App Store transactions from your server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI",
      "kind": "symbol",
      "role": "collection",
      "title": "App Store Server API",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerAPI/GET-v1-subscriptions-_transactionId_": {
      "abstract": [
        {
          "text": "Get the statuses for all of a customer’s auto-renewable subscriptions in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/GET-v1-subscriptions-_transactionId_",
      "kind": "symbol",
      "role": "symbol",
      "title": "Get All Subscription Statuses",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI/GET-v1-subscriptions-_transactionId_"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerAPI/JWSRenewalInfoDecodedPayload": {
      "abstract": [
        {
          "text": "A decoded payload containing subscription renewal information for an auto-renewable subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "JWSRenewalInfoDecodedPayload"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/JWSRenewalInfoDecodedPayload",
      "kind": "symbol",
      "role": "symbol",
      "title": "JWSRenewalInfoDecodedPayload",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI/JWSRenewalInfoDecodedPayload"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerAPI/JWSTransactionDecodedPayload": {
      "abstract": [
        {
          "text": "A decoded payload that contains transaction information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "JWSTransactionDecodedPayload"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/JWSTransactionDecodedPayload",
      "kind": "symbol",
      "role": "symbol",
      "title": "JWSTransactionDecodedPayload",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI/JWSTransactionDecodedPayload"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerAPI/eligibleWinBackOfferIds": {
      "abstract": [
        {
          "text": "An array of win-back offer identifiers that a customer is eligible to redeem, which sorts the identifiers with the best offers first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "data:app_store_server_api:offerIdentifier",
          "text": "offerIdentifier"
        },
        {
          "kind": "text",
          "text": "] "
        },
        {
          "kind": "identifier",
          "text": "eligibleWinBackOfferIds"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/eligibleWinBackOfferIds",
      "kind": "symbol",
      "role": "symbol",
      "title": "eligibleWinBackOfferIds",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI/eligibleWinBackOfferIds"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerAPI/offerIdentifier": {
      "abstract": [
        {
          "text": "The string identifier of a subscription offer that you create in App Store Connect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "string "
        },
        {
          "kind": "identifier",
          "text": "offerIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/offerIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "offerIdentifier",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI/offerIdentifier"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerAPI/offerType": {
      "abstract": [
        {
          "text": "The type of subscription offer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "int32 "
        },
        {
          "kind": "identifier",
          "text": "offerType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI/offerType",
      "kind": "symbol",
      "role": "symbol",
      "title": "offerType",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI/offerType"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerNotifications/App-Store-Server-Notifications-V2": {
      "abstract": [
        {
          "text": "Specify your secure server’s URL in App Store Connect to receive version 2 notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerNotifications/App-Store-Server-Notifications-V2",
      "kind": "symbol",
      "role": "symbol",
      "title": "App Store Server Notifications V2",
      "type": "topic",
      "url": "/documentation/AppStoreServerNotifications/App-Store-Server-Notifications-V2"
    },
    "doc://com.apple.documentation/documentation/Swift/Task": {
      "abstract": [
        {
          "text": "A unit of asynchronous work.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Task"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Success"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Success"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Task",
      "kind": "symbol",
      "role": "symbol",
      "title": "Task",
      "type": "topic",
      "url": "/documentation/Swift/Task"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Message/Reason-swift.struct/winBackOffer": {
      "abstract": [
        {
          "text": "A message the App Store sends when the customer is eligible for a win-back offer that you configure in App Store Connect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "winBackOffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7MessageV",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7MessageV6ReasonV",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message/Reason-swift.struct/winBackOffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "winBackOffer",
      "type": "topic",
      "url": "/documentation/storekit/message/reason-swift.struct/winbackoffer"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/willAutoRenew": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the subscription automatically renews in the next period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willAutoRenew"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/willAutoRenew",
      "kind": "symbol",
      "role": "symbol",
      "title": "willAutoRenew",
      "type": "topic",
      "url": "/documentation/storekit/product/subscriptioninfo/renewalinfo/willautorenew"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionOffer": {
      "abstract": [
        {
          "text": "Information about a subscription offer that you configure in App Store Connect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SubscriptionOffer"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionOffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SubscriptionOffer"
        }
      ],
      "role": "symbol",
      "title": "Product.SubscriptionOffer",
      "type": "topic",
      "url": "/documentation/storekit/product/subscriptionoffer"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionOffer/OfferType": {
      "abstract": [
        {
          "text": "The types of offers for auto-renewable subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OfferType"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionOffer/OfferType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OfferType"
        }
      ],
      "role": "symbol",
      "title": "Product.SubscriptionOffer.OfferType",
      "type": "topic",
      "url": "/documentation/storekit/product/subscriptionoffer/offertype"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Product/purchase(options:)": {
      "abstract": [
        {
          "text": "Initiates a purchase for the product with the App Store and displays the confirmation sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purchase"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV14PurchaseOptionV",
          "text": "PurchaseOption"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV14PurchaseResultO",
          "text": "PurchaseResult"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Product/purchase(options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "purchase(options:)",
      "type": "topic",
      "url": "/documentation/storekit/product/purchase(options:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent": {
      "abstract": [
        {
          "text": "An instance that emits purchase intents, which indicate that the customer initiated a purchase outside of your app, for your app to complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PurchaseIntent"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PurchaseIntent"
        }
      ],
      "role": "symbol",
      "title": "PurchaseIntent",
      "type": "topic",
      "url": "/documentation/storekit/purchaseintent"
    },
    "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/intents": {
      "abstract": [
        {
          "text": "The asynchronous sequence that emits a purchase intent when customers initiate a purchase outside of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit14PurchaseIntentV",
          "text": "PurchaseIntent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit14PurchaseIntentV0C7IntentsV",
          "text": "PurchaseIntents"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/intents",
      "kind": "symbol",
      "role": "symbol",
      "title": "intents",
      "type": "topic",
      "url": "/documentation/storekit/purchaseintent/intents"
    },
    "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/offer": {
      "abstract": [
        {
          "text": "The subscription offer that the customer redeems outside of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV17SubscriptionOfferV",
          "text": "SubscriptionOffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/offer",
      "kind": "symbol",
      "role": "symbol",
      "title": "offer",
      "type": "topic",
      "url": "/documentation/storekit/purchaseintent/offer"
    },
    "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/product": {
      "abstract": [
        {
          "text": "The product information of the In-App Purchase the customer selects to purchase outside of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "product"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PurchaseIntent/product",
      "kind": "symbol",
      "role": "symbol",
      "title": "product",
      "type": "topic",
      "url": "/documentation/storekit/purchaseintent/product"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction": {
      "abstract": [
        {
          "text": "Information that represents the customer’s purchase of a product in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Transaction"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Transaction"
        }
      ],
      "role": "symbol",
      "title": "Transaction",
      "type": "topic",
      "url": "/documentation/storekit/transaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction/all": {
      "abstract": [
        {
          "text": "A sequence that emits all the customer’s transactions for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV12TransactionsV",
          "text": "Transactions"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/all",
      "kind": "symbol",
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/storekit/transaction/all"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction/currentEntitlements": {
      "abstract": [
        {
          "text": "A sequence of the latest transactions that entitle a customer to In-App Purchases and subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentEntitlements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV12TransactionsV",
          "text": "Transactions"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/currentEntitlements",
      "kind": "symbol",
      "role": "symbol",
      "title": "currentEntitlements",
      "type": "topic",
      "url": "/documentation/storekit/transaction/currententitlements"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction/expirationDate": {
      "abstract": [
        {
          "text": "The date the subscription expires or renews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/expirationDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "expirationDate",
      "type": "topic",
      "url": "/documentation/storekit/transaction/expirationdate"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction/finish()": {
      "abstract": [
        {
          "text": "Indicates to the App Store that the app delivered the purchased content or enabled the service to finish the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finish"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/finish()",
      "kind": "symbol",
      "role": "symbol",
      "title": "finish()",
      "type": "topic",
      "url": "/documentation/storekit/transaction/finish()"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction/offer-swift.property": {
      "abstract": [
        {
          "text": "The subscription offer that applies to the transaction, including its offer type, payment mode, and ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV5OfferV",
          "text": "Offer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/offer-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "offer",
      "type": "topic",
      "url": "/documentation/storekit/transaction/offer-swift.property"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates": {
      "abstract": [
        {
          "text": "The asynchronous sequence that emits a transaction when the system creates or updates transactions that occur outside the app or on other devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV12TransactionsV",
          "text": "Transactions"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
      "kind": "symbol",
      "role": "symbol",
      "title": "updates",
      "type": "topic",
      "url": "/documentation/storekit/transaction/updates"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/merchandising-win-back-offers-in-your-app": {
      "abstract": [
        {
          "text": "Present win-back offers to eligible customers in your app with the win-back offer sheet or by implementing custom merchandising.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/merchandising-win-back-offers-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Merchandising win-back offers in your app",
      "type": "topic",
      "url": "/documentation/storekit/merchandising-win-back-offers-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/supporting-subscription-offer-codes-in-your-app": {
      "abstract": [
        {
          "text": "Provide subscription service for customers who redeem offer codes through the App Store or within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-subscription-offer-codes-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting subscription offer codes in your app",
      "type": "topic",
      "url": "/documentation/storekit/supporting-subscription-offer-codes-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/supporting-win-back-offers-in-your-app#Handle-win-back-offers-redeemed-outside-of-your-app": {
      "abstract": [],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-win-back-offers-in-your-app#Handle-win-back-offers-redeemed-outside-of-your-app",
      "kind": "section",
      "title": "Handle win-back offers redeemed outside of your app",
      "type": "topic",
      "url": "/documentation/storekit/supporting-win-back-offers-in-your-app#Handle-win-back-offers-redeemed-outside-of-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment": {
      "abstract": [
        {
          "text": "Verify that your app receives and handles win-back offer transactions, including those made outside your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment",
      "kind": "article",
      "role": "article",
      "title": "Testing win-back offers in the sandbox environment",
      "type": "topic",
      "url": "/documentation/storekit/testing-win-back-offers-in-the-sandbox-environment"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-xcode": {
      "abstract": [
        {
          "text": "Validate your app’s handling of win-back offers that you configure for the testing environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-xcode",
      "kind": "article",
      "role": "article",
      "title": "Testing win-back offers in Xcode",
      "type": "topic",
      "url": "/documentation/storekit/testing-win-back-offers-in-xcode"
    },
    "https://developer.apple.com/help/app-store-connect/manage-in-app-purchases/view-and-edit-in-app-purchase-information#add-or-remove-an-image": {
      "identifier": "https://developer.apple.com/help/app-store-connect/manage-in-app-purchases/view-and-edit-in-app-purchase-information#add-or-remove-an-image",
      "title": "Add or remove an image",
      "titleInlineContent": [
        {
          "text": "Add or remove an image",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/app-store-connect/manage-in-app-purchases/view-and-edit-in-app-purchase-information#add-or-remove-an-image"
    },
    "https://developer.apple.com/help/app-store-connect/manage-subscriptions/manage-streamlined-purchasing": {
      "identifier": "https://developer.apple.com/help/app-store-connect/manage-subscriptions/manage-streamlined-purchasing",
      "title": "Manage Streamlined Purchasing",
      "titleInlineContent": [
        {
          "text": "Manage Streamlined Purchasing",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/app-store-connect/manage-subscriptions/manage-streamlined-purchasing"
    },
    "https://developer.apple.com/help/app-store-connect/manage-subscriptions/set-up-win-back-offers": {
      "identifier": "https://developer.apple.com/help/app-store-connect/manage-subscriptions/set-up-win-back-offers",
      "title": "Set up win-back offers",
      "titleInlineContent": [
        {
          "text": "Set up win-back offers",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/app-store-connect/manage-subscriptions/set-up-win-back-offers"
    },
    "https://developer.apple.com/wwdc24/10110": {
      "identifier": "https://developer.apple.com/wwdc24/10110",
      "title": "Implement App Store Offers",
      "titleInlineContent": [
        {
          "text": "Implement App Store Offers",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc24/10110"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Subscription-offers-and-offer-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/merchandising-win-back-offers-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/supporting-subscription-offer-codes-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionOffer",
        "doc://com.apple.storekit/documentation/StoreKit/Product/SubscriptionOffer/OfferType"
      ],
      "title": "Subscription offers and offer codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Subscription-offers-and-offer-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/merchandising-win-back-offers-in-your-app",
                "doc://com.apple.storekit/documentation/StoreKit/supporting-subscription-offer-codes-in-your-app"
              ],
              "title": "Subscription offers and offer codes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/supporting-win-back-offers-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/supporting-win-back-offers-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
