{
  "abstract": [
    {
      "text": "Verify that your app receives and handles win-back offer transactions, including those made outside your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Testing win-back offers in the sandbox environment"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you set up win-back offers for auto-renewable subscriptions in App Store Connect, you can begin testing them in the sandbox environment. You can merchandise win-back offers in multiple ways, enabling customers to discover and redeem them in the App Store, in their Apple Account in Subscription settings, in your own marketing channels, and in your app. Within your app, you can merchandise win-back offers by using the win-back offer sheet, StoreKit views, or other StoreKit APIs for full customization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the sandbox testing environment to simulate redeeming win-back offers in these ways:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Customers can redeem win-back offers in the App Store, through a direct link, or in the Subscription settings in their Apple Account. You can simulate redeeming win-back offers outside the app by using the Test Transactions feature in the sandbox Account Settings in iOS. The system applies the win-back offer if the test account is eligible for it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Outside the app",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "To simulate redeeming a win-back offer in your app, turn on the Display Win-back Offer Sheet toggle in Account Settings in iOS. The system displays a win-back offer sheet, using the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " API’s ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message/Reason-swift.struct/winBackOffer",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " reason, when you launch the app. The test account needs to be eligible for the offer in the sandbox environment. This option is only available to apps running in iOS 18 and iPadOS 18 and later.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "In the app, using the win-back offer sheet",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Follow the steps to make the test account eligible for the offer in the sandbox environment. Exercise your app’s implementation that uses StoreKit views or your custom code using StoreKit APIs. StoreKit views automatically chooses an offer to display.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "In the app, using StoreKit views or your custom code",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Handle the resulting transactions in your app. StoreKit delivers them through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " asynchronous sequence in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "In TestFlight testing, you can only test win-back offers if you implement them using StoreKit views or other StoreKit APIs. The win-back offer sheet and redemption through the App Store aren’t available for testing in TestFlight.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Other types of offers and transactions can also occur outside your app. For testing information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-purchases-made-outside-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can also test win-back offers in Xcode, which doesn’t rely on App Store Connect configurations. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-xcode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-up-win-back-offer-testing-in-App-Store-Connect-and-Account-Settings",
          "level": 3,
          "text": "Set up win-back offer testing in App Store Connect and Account Settings",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you begin testing in the sandbox environment, use App Store Connect to configure at least one auto-renewable subscription, and at least one win-back offer. Make a note of the product ID of the auto-renewable subscription and the corresponding win-back offer IDs to use in your tests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Changes that you make to product metadata in App Store Connect can take up to one hour to appear in the sandbox environment.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "On the iOS device, set up the testing environment by opening Account Settings, as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open Settings and select Developer.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the Sandbox Apple Account. If you’re not yet signed in, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox#Sign-in-to-the-App-Store-with-your-Sandbox-Apple-Account",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to sign in. A popover appears.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select Manage on the popover. The Account Settings page appears.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check that the Allow Purchases & Renewals toggle remains on. If it’s off, all purchases fail, which represents a different test case. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-failing-subscription-renewals-and-in-app-purchases",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Turn on or off the Win-Back Offer Sheet toggle.  Turn it on to enable the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " API to display the win-back offer sheet when you launch the app.  Turn it off to prevent the sheet from appearing, even if the customer is eligible for the offer. This toggle only affects sandbox testing.  In either case, StoreKit delivers the new transaction to your app through the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " asynchronous sequence in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Prepare-eligibility-conditions",
          "level": 3,
          "text": "Prepare eligibility conditions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In the sandbox environment, test accounts are automatically eligible for win-back offers when they have an expired subscription. The account needs to have owned the subscription; having access through Family Sharing doesn’t qualify the account for a win-back offer. Also, the account can’t have any active subscriptions from the same subscription group.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To make your Sandbox Apple Account eligible for a win-back offer, follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Cancel any subscriptions that are from the same subscription group as the win-back offer’s subscription.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the test account has an active subscription through Family Sharing in the same subscription group, it’s ineligible for a win-back offer in that subscription group. To make the account eligible, leave the family group, or stop sharing the subscription with the family.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Wait for the subscription to expire. By default, a monthly subscription expires in 5 minutes in the sandbox. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/help/app-store-connect/test-in-app-purchases/manage-sandbox-apple-account-settings/",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Subscribe to the auto-renewable subscription that has the win-back offer you’re testing.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Cancel the subscription and wait for it to expire.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Close the app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The Sandbox Apple Account is now eligible for the win-back offer in the sandbox environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Repeat these steps to repeat a test.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-redeeming-a-win-back-offer-outside-the-app",
          "level": 3,
          "text": "Test redeeming a win-back offer outside the app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To simulate a win-back offer redemption outside your app, follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Complete the steps in the preceding sections: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Set-up-win-back-offer-testing-in-App-Store-Connect-and-Account-Settings",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Prepare-eligibility-conditions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Close your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On the Account Settings page (Settings > Developer > Sandbox Apple Account > Manage), select Test Transactions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enter the auto-renewable subscription’s product ID and the bundle ID in the applicable text boxes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enter the win-back offer ID in the Win-Back ID text box. The win-back offer ID needs to be a valid offer for the product, that you configure in App Store Connect.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system presents the App Store [Sandbox] payment sheet for the sandbox environment. Confirm the purchase.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Launch your app. StoreKit provides the transaction in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " asynchronous sequence.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check that your app receives and processes the win-back offer transaction.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The sandbox environment doesn’t process actual payments. Instead, it returns transactions as if the system successfully processes them.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Test-redeeming-an-offer-in-your-app-using-the-win-back-offer-sheet",
          "level": 3,
          "text": "Test redeeming an offer in your app using the win-back offer sheet",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To simulate a win-back offer redemption in your app, follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Complete the steps in the preceding sections: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Set-up-win-back-offer-testing-in-App-Store-Connect-and-Account-Settings",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Prepare-eligibility-conditions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Close the app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On the Account Settings page (Settings > Developer > Sandbox Apple Account > Manage), turn on the Display Win-back Offer Sheet toggle.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Launch your app. The system presents the win-back offer sheet.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Accept the offer. The system presents the App Store [Sandbox] payment sheet for the sandbox environment. Confirm the purchase.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check that your app receives and processes the win-back offer transaction.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Test-redeeming-an-offer-in-your-app-through-StoreKit-views-or-your-customized-code",
          "level": 3,
          "text": "Test redeeming an offer in your app through StoreKit views or your customized code",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you merchandise the win-back offer using StoreKit views or other StoreKit APIs to fully customize the experience, you can test your implementation in the sandbox environment. Follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Complete the steps in the preceding sections to ensure the test account is eligible for one or more win-back offers: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Set-up-win-back-offer-testing-in-App-Store-Connect-and-Account-Settings",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Prepare-eligibility-conditions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Close the app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Optionally, on the Account Settings page (Settings > Developer > Sandbox Apple Account > Manage), turn off the Display Win-back Offer Sheet toggle to prevent the win-back offer sheet from appearing.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Launch your app. Open your app’s store and exercise the offer API.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "StoreKit views automatically chooses an offer to display. If there are multiple offers, your app indicates a preference using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/preferredSubscriptionOffer(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " API.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about customizing your in-app experience, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/merchandising-win-back-offers-in-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-win-back-offers-in-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Restart-or-conclude-a-test",
          "level": 3,
          "text": "Restart or conclude a test",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To repeat a test and redeem the same win-back offer, cancel the subscription and wait for it to expire. The test account in the sandbox environment is eligible for the same win-back offer after the subscription expires.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/SwiftUI/View/preferredSubscriptionOffer(_:)": {
      "abstract": [
        {
          "text": "Selects a subscription offer to apply to a purchase that a customer makes from a subscription store view, a store view, or a product view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredSubscriptionOffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "offer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV16SubscriptionInfoV",
          "text": "SubscriptionInfo"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV17SubscriptionOfferV",
          "text": "SubscriptionOffer"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV17SubscriptionOfferV",
          "text": "SubscriptionOffer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/preferredSubscriptionOffer(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredSubscriptionOffer(_:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/preferredSubscriptionOffer(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Message": {
      "abstract": [
        {
          "text": "An instance for receiving and displaying App Store messages in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Message"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Message"
        }
      ],
      "role": "symbol",
      "title": "Message",
      "type": "topic",
      "url": "/documentation/storekit/message"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Message/Reason-swift.struct/winBackOffer": {
      "abstract": [
        {
          "text": "A message the App Store sends when the customer is eligible for a win-back offer that you configure in App Store Connect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "winBackOffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7MessageV",
          "text": "Message"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7MessageV6ReasonV",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message/Reason-swift.struct/winBackOffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "winBackOffer",
      "type": "topic",
      "url": "/documentation/storekit/message/reason-swift.struct/winbackoffer"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction": {
      "abstract": [
        {
          "text": "Information that represents the customer’s purchase of a product in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Transaction"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Transaction"
        }
      ],
      "role": "symbol",
      "title": "Transaction",
      "type": "topic",
      "url": "/documentation/storekit/transaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates": {
      "abstract": [
        {
          "text": "The asynchronous sequence that emits a transaction when the system creates or updates transactions that occur outside the app or on other devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV12TransactionsV",
          "text": "Transactions"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Transaction/updates",
      "kind": "symbol",
      "role": "symbol",
      "title": "updates",
      "type": "topic",
      "url": "/documentation/storekit/transaction/updates"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/merchandising-win-back-offers-in-your-app": {
      "abstract": [
        {
          "text": "Present win-back offers to eligible customers in your app with the win-back offer sheet or by implementing custom merchandising.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/merchandising-win-back-offers-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Merchandising win-back offers in your app",
      "type": "topic",
      "url": "/documentation/storekit/merchandising-win-back-offers-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase": {
      "abstract": [
        {
          "text": "Offer additional content and services in your app using the Original In-App Purchase API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original API for In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/original-api-for-in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/supporting-win-back-offers-in-your-app": {
      "abstract": [
        {
          "text": "Re-engage previous subscribers with a free or discounted offer for an auto-renewable subscription, for a specific duration.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-win-back-offers-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting win-back offers in your app",
      "type": "topic",
      "url": "/documentation/storekit/supporting-win-back-offers-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-a-payment-request": {
      "abstract": [
        {
          "text": "Verify that requests for payment function properly in the sandbox environment by inspecting the calls to the payment transaction observer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-a-payment-request",
      "kind": "article",
      "role": "article",
      "title": "Testing a payment request",
      "type": "topic",
      "url": "/documentation/storekit/testing-a-payment-request"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-an-interrupted-purchase": {
      "abstract": [
        {
          "text": "Verify that your app handles an interrupted purchase by inspecting and invoking payment transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-an-interrupted-purchase",
      "kind": "article",
      "role": "article",
      "title": "Testing an interrupted purchase",
      "type": "topic",
      "url": "/documentation/storekit/testing-an-interrupted-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-failing-subscription-renewals-and-in-app-purchases": {
      "abstract": [
        {
          "text": "Verify that your app handles failed subscription renewals that are in the billing retry or billing grace period states, as well as failed In-App Purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-failing-subscription-renewals-and-in-app-purchases",
      "kind": "article",
      "role": "article",
      "title": "Testing failing subscription renewals and In-App Purchases",
      "type": "topic",
      "url": "/documentation/storekit/testing-failing-subscription-renewals-and-in-app-purchases"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox": {
      "abstract": [
        {
          "text": "Test your implementation of In-App Purchases using real product information and server-to-server transactions in the sandbox environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox",
      "kind": "article",
      "role": "article",
      "title": "Testing In-App Purchases with sandbox",
      "type": "topic",
      "url": "/documentation/storekit/testing-in-app-purchases-with-sandbox"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox#Sign-in-to-the-App-Store-with-your-Sandbox-Apple-Account": {
      "abstract": [],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox#Sign-in-to-the-App-Store-with-your-Sandbox-Apple-Account",
      "kind": "section",
      "title": "Sign in to the App Store with your Sandbox Apple Account",
      "type": "topic",
      "url": "/documentation/storekit/testing-in-app-purchases-with-sandbox#Sign-in-to-the-App-Store-with-your-Sandbox-Apple-Account"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-purchases-made-outside-your-app": {
      "abstract": [
        {
          "text": "Verify that your app receives and handles transactions that occur outside your app, such as subscription purchases, renewals, and offer and promo code redemptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-purchases-made-outside-your-app",
      "kind": "article",
      "role": "article",
      "title": "Testing purchases made outside your app",
      "type": "topic",
      "url": "/documentation/storekit/testing-purchases-made-outside-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Prepare-eligibility-conditions": {
      "abstract": [],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Prepare-eligibility-conditions",
      "kind": "section",
      "title": "Prepare eligibility conditions",
      "type": "topic",
      "url": "/documentation/storekit/testing-win-back-offers-in-the-sandbox-environment#Prepare-eligibility-conditions"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Set-up-win-back-offer-testing-in-App-Store-Connect-and-Account-Settings": {
      "abstract": [],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-the-sandbox-environment#Set-up-win-back-offer-testing-in-App-Store-Connect-and-Account-Settings",
      "kind": "section",
      "title": "Set up win-back offer testing in App Store Connect and Account Settings",
      "type": "topic",
      "url": "/documentation/storekit/testing-win-back-offers-in-the-sandbox-environment#Set-up-win-back-offer-testing-in-App-Store-Connect-and-Account-Settings"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-xcode": {
      "abstract": [
        {
          "text": "Validate your app’s handling of win-back offers that you configure for the testing environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-win-back-offers-in-xcode",
      "kind": "article",
      "role": "article",
      "title": "Testing win-back offers in Xcode",
      "type": "topic",
      "url": "/documentation/storekit/testing-win-back-offers-in-xcode"
    },
    "https://developer.apple.com/help/app-store-connect/test-in-app-purchases/manage-sandbox-apple-account-settings/": {
      "identifier": "https://developer.apple.com/help/app-store-connect/test-in-app-purchases/manage-sandbox-apple-account-settings/",
      "title": "Manage Sandbox Apple Account settings ",
      "titleInlineContent": [
        {
          "text": "Manage Sandbox Apple Account settings ",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/app-store-connect/test-in-app-purchases/manage-sandbox-apple-account-settings/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Payment-transactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/testing-purchases-made-outside-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/testing-an-interrupted-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/testing-failing-subscription-renewals-and-in-app-purchases",
        "doc://com.apple.storekit/documentation/StoreKit/testing-a-payment-request"
      ],
      "title": "Payment transactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Payment-transactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/testing-purchases-made-outside-your-app",
                "doc://com.apple.storekit/documentation/StoreKit/testing-an-interrupted-purchase",
                "doc://com.apple.storekit/documentation/StoreKit/testing-failing-subscription-renewals-and-in-app-purchases",
                "doc://com.apple.storekit/documentation/StoreKit/testing-a-payment-request"
              ],
              "title": "Payment transactions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/testing-win-back-offers-in-the-sandbox-environment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/testing-win-back-offers-in-the-sandbox-environment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
