{
  "abstract": [
    {
      "text": "Reduce the time-window for ad attributions and inspect postbacks using a proxy during testing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution",
        "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/testing-ad-attributions-with-a-downloaded-profile"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Testing ad attributions with a downloaded profile"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can reduce the time window for receiving ad attribution postbacks by installing an SKAdNetwork testing profile on your test device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To download the latest profile, see the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AdAttributionKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " article on ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AdAttributionKit/testing-ad-attributions-with-a-downloaded-profile",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". This profile is compatible with both AdAttributionKit and SKAdNetwork.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "For information about installing profiles, see ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/en-us/HT209435",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can install this profile on devices running iOS or iPadOS 14 or later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "With this profile, the installed app has five minutes to update the conversion value after initially registering. The device sends the postback within another five minutes after the rolling five-minute timer for conversion updates expires. Using this profile reduces the conversion value update and postback window from 24–48 hours to 5–10 minutes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This testing profile expires two weeks after you install it on the device. To continue testing, download the latest profile and reinstall it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Log-in-with-an-Apple-ID-to-test-ad-attributions",
          "level": 3,
          "text": "Log in with an Apple ID to test ad attributions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To test ad attributions, you must log in to the device with a production Apple ID. SKAdNetwork doesn’t support Sandbox Apple IDs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Inspect-postbacks-using-an-HTTP-proxy",
          "level": 3,
          "text": "Inspect postbacks using an HTTP proxy",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On devices running iOS 14.7 and later with this profile installed, the system can send SKAdNetwork postbacks through an HTTP proxy that you configure. By using an HTTP proxy, you can monitor the HTTP traffic between your device and the network, including SKAdNetwork postbacks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To configure the HTTP proxy, do the following on a testing device:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Go to Settings > Wi-Fi and select the Wi-Fi network you’re connected to.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Under the HTTP Proxy heading, select Configure Proxy.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select Manual to configure the Server, Port, and Authentication settings for your proxy, or select Automatic to provide a URL for your proxy.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Tap Save.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "With the profile installed, the SKAdNetwork postbacks that the device sends now go through the proxy you configured.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AdAttributionKit": {
      "abstract": [
        {
          "text": "Present, process, and register postbacks for in-app ads in the App Store and alternative app marketplaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdAttributionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AdAttributionKit",
      "type": "topic",
      "url": "/documentation/AdAttributionKit"
    },
    "doc://com.apple.documentation/documentation/AdAttributionKit/testing-ad-attributions-with-a-downloaded-profile": {
      "abstract": [
        {
          "text": "Reduce the time-window for ad attributions and inspect postbacks using a proxy during testing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdAttributionKit/testing-ad-attributions-with-a-downloaded-profile",
      "kind": "article",
      "role": "article",
      "title": "Testing ad attributions with a downloaded profile",
      "type": "topic",
      "url": "/documentation/AdAttributionKit/testing-ad-attributions-with-a-downloaded-profile"
    },
    "doc://com.apple.documentation/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork": {
      "abstract": [
        {
          "text": "Validate your ad impressions and test your postbacks by creating unit tests using the StoreKit Test framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork",
      "kind": "article",
      "role": "sampleCode",
      "title": "Testing and validating ad impression signatures and postbacks for SKAdNetwork",
      "type": "topic",
      "url": "/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork": {
      "abstract": [
        {
          "text": "A class that validates advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdNetwork"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKAdNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdNetwork"
        }
      ],
      "role": "symbol",
      "title": "SKAdNetwork",
      "type": "topic",
      "url": "/documentation/storekit/skadnetwork"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution": {
      "abstract": [
        {
          "text": "Validate advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ad network attribution",
      "type": "topic",
      "url": "/documentation/storekit/ad-network-attribution"
    },
    "https://support.apple.com/en-us/HT209435": {
      "identifier": "https://support.apple.com/en-us/HT209435",
      "title": "Install a configuration profile on your iPhone or iPad",
      "titleInlineContent": [
        {
          "text": "Install a configuration profile on your iPhone or iPad",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/en-us/HT209435"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Testing-ad-attributions-and-postbacks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork"
      ],
      "title": "Testing ad attributions and postbacks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Testing-ad-attributions-and-postbacks",
              "generated": true,
              "identifiers": [],
              "title": "Testing ad attributions and postbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork/title",
          "value": "SKAdNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKAdNetwork/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetwork"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/testing-ad-attributions-with-a-downloaded-profile"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/testing-ad-attributions-with-a-downloaded-profile"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
