{
  "abstract": [
    {
      "text": "Confirm that your app can make a successful transaction in the sandbox environment by inspecting the transaction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/testing-a-successful-transaction"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Testing a successful transaction"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set a breakpoint in your implementation of the transaction queue observer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:updatedTransactions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Then sign in to the App Store with a Sandbox Apple ID, and make a purchase in your app. Inspect the transaction to verify that its status is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchased",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Set a breakpoint at the point in your code where your app stores the purchase, and confirm that your code saves the data in response to a successful purchase. Inspect the user default or iCloud key-value store, to verify that your code correctly records the information. For more information on saving data in response to a successful purchase, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/persisting-a-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:updatedTransactions:)": {
      "abstract": [
        {
          "text": "Tells an observer that one or more transactions have been updated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPaymentQueue",
          "text": "SKPaymentQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "updatedTransactions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPaymentTransaction",
          "text": "SKPaymentTransaction"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionObserver/paymentQueue(_:updatedTransactions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentQueue:updatedTransactions:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "paymentQueue(_:updatedTransactions:)",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionobserver/paymentqueue(_:updatedtransactions:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchased": {
      "abstract": [
        {
          "text": "A successfully processed transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purchased"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStatePurchased"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.purchased",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/purchased"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase": {
      "abstract": [
        {
          "text": "Offer additional content and services in your app using the Original In-App Purchase API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original API for In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/original-api-for-in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/persisting-a-purchase": {
      "abstract": [
        {
          "text": "Keep a persistent record of a purchase to continue making the product available as needed.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/persisting-a-purchase",
      "kind": "article",
      "role": "article",
      "title": "Persisting a purchase",
      "type": "topic",
      "url": "/documentation/storekit/persisting-a-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-complete-transactions": {
      "abstract": [
        {
          "text": "Verify that your app completes transactions properly by confirming that any downloadable purchases are present on your test device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-complete-transactions",
      "kind": "article",
      "role": "article",
      "title": "Testing complete transactions",
      "type": "topic",
      "url": "/documentation/storekit/testing-complete-transactions"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox": {
      "abstract": [
        {
          "text": "Test your implementation of In-App Purchases using real product information and server-to-server transactions in the sandbox environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox",
      "kind": "article",
      "role": "article",
      "title": "Testing In-App Purchases with sandbox",
      "type": "topic",
      "url": "/documentation/storekit/testing-in-app-purchases-with-sandbox"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-transaction-observer-code": {
      "abstract": [
        {
          "text": "Verify that your app activates its payment transaction observer by using breakpoints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-transaction-observer-code",
      "kind": "article",
      "role": "article",
      "title": "Testing transaction observer code",
      "type": "topic",
      "url": "/documentation/storekit/testing-transaction-observer-code"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transaction-observer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/testing-transaction-observer-code",
        "doc://com.apple.storekit/documentation/StoreKit/testing-complete-transactions"
      ],
      "title": "Transaction observer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transaction-observer",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/testing-transaction-observer-code",
                "doc://com.apple.storekit/documentation/StoreKit/testing-complete-transactions"
              ],
              "title": "Transaction observer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueue(_:updatedTransactions:)/title",
          "value": "paymentQueue:updatedTransactions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionObserver~1paymentQueue(_:updatedTransactions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentQueue:updatedTransactions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchased/title",
          "value": "SKPaymentTransactionStatePurchased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStatePurchased"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/testing-a-successful-transaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/testing-a-successful-transaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
