{
  "abstract": [
    {
      "text": "Verify that your app receives subscription updates when a user cancels a subscription by verifying the receipt or receiving a notification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/testing-disabling-auto-renew"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Testing disabling auto-renew"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Customers can manage their active subscriptions, as well as their expired subscriptions for up to a year after expiry, in the Subscriptions page on iOS, tvOS, iPadOS, and macOS. In this test scenario, the customer cancels a subscription, which disables auto-renew.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To set up for this test, purchase an auto-renewable subscription for the Sandbox Apple Account.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Begin-testing",
          "level": 3,
          "text": "Begin testing",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To test disabling auto-renew:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On the test iOS device, open Settings > Developer.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the Sandbox Account section, tap your highlighted Sandbox Apple Account, and tap Manage.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the sandbox Subscriptions page, select the subscription product that you want to cancel.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Tap the Cancel Subscription button.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Verify the change in the subscription status using either of these two methods:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you’ve configured App Store Connect settings to receive App Store server notifications, your server receives the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerNotifications/notification_type",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "DID_CHANGE_RENEWAL_STATUS",
                      "type": "codeVoice"
                    },
                    {
                      "text": " each time the subscription’s auto-renew status changes. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerNotifications/enabling-app-store-server-notifications",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Verify the receipt by calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/verifyreceipt",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with the latest receipt. Check that the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/auto_renew_status",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/responsebody/pending_renewal_info",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object changes to ",
                      "type": "text"
                    },
                    {
                      "code": "0",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". The ",
                      "type": "text"
                    },
                    {
                      "code": "auto_renew_status_change_date_ms",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property of ",
                      "type": "text"
                    },
                    {
                      "code": "responseBody",
                      "type": "codeVoice"
                    },
                    {
                      "text": " contains the timestamp of the change.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Test-reenabling-the-subscription-renewal",
          "level": 3,
          "text": "Test reenabling the subscription renewal",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After disabling auto-renew, reenable the subscription on the same Manage Subscriptions page by tapping the subscription and confirming payment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Verify the change in the subscription status using either of these two methods:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you’ve configured App Store Connect settings to receive App Store server notifications, your server receives the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerNotifications/notification_type",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "DID_CHANGE_RENEWAL_STATUS",
                      "type": "codeVoice"
                    },
                    {
                      "text": " each time the subscription’s auto-renew status changes. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerNotifications/enabling-app-store-server-notifications",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Verify the receipt by calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/verifyreceipt",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with the latest receipt. Check that the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/auto_renew_status",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/responsebody/pending_renewal_info",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object changes to ",
                      "type": "text"
                    },
                    {
                      "code": "1",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". The ",
                      "type": "text"
                    },
                    {
                      "code": "auto_renew_status_change_date_ms",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property of ",
                      "type": "text"
                    },
                    {
                      "code": "responseBody",
                      "type": "codeVoice"
                    },
                    {
                      "text": " contains the timestamp of the change.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppStoreServerNotifications/enabling-app-store-server-notifications": {
      "abstract": [
        {
          "text": "Configure your server and provide an HTTPS URL to receive notifications about in-app purchase events and unreported external purchase tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerNotifications/enabling-app-store-server-notifications",
      "kind": "article",
      "role": "article",
      "title": "Enabling App Store Server Notifications",
      "type": "topic",
      "url": "/documentation/AppStoreServerNotifications/enabling-app-store-server-notifications"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerNotifications/notification_type": {
      "abstract": [
        {
          "text": "The type that describes the in-app purchase event for which the App Store sends the version 1 notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "string "
        },
        {
          "kind": "identifier",
          "text": "notification_type"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerNotifications/notification_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "notification_type",
      "type": "topic",
      "url": "/documentation/AppStoreServerNotifications/notification_type"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/auto_renew_status": {
      "abstract": [
        {
          "text": "The renewal status for the auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "type "
        },
        {
          "kind": "identifier",
          "text": "auto_renew_status"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/auto_renew_status",
      "kind": "symbol",
      "role": "symbol",
      "title": "auto_renew_status",
      "type": "topic",
      "url": "/documentation/appstorereceipts/auto_renew_status"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/responsebody/pending_renewal_info": {
      "abstract": [
        {
          "text": "An array of elements that refers to open or failed auto-renewable subscription renewals.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "responseBody.Pending_renewal_info"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/responsebody/pending_renewal_info",
      "kind": "article",
      "role": "symbol",
      "title": "responseBody.Pending_renewal_info",
      "type": "topic",
      "url": "/documentation/appstorereceipts/responsebody/pending_renewal_info"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/verifyreceipt": {
      "abstract": [
        {
          "text": "Send a receipt to the App Store for verification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/verifyreceipt",
      "kind": "article",
      "role": "symbol",
      "title": "verifyReceipt",
      "type": "topic",
      "url": "/documentation/appstorereceipts/verifyreceipt"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase": {
      "abstract": [
        {
          "text": "Offer additional content and services in your app using the Original In-App Purchase API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/original-api-for-in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Original API for In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/original-api-for-in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-an-auto-renewable-subscription": {
      "abstract": [
        {
          "text": "Verify that your app handles a subscription lapse properly using the accelerated time rates within the sandbox environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-an-auto-renewable-subscription",
      "kind": "article",
      "role": "article",
      "title": "Testing an auto-renewable subscription",
      "type": "topic",
      "url": "/documentation/storekit/testing-an-auto-renewable-subscription"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox": {
      "abstract": [
        {
          "text": "Test your implementation of In-App Purchases using real product information and server-to-server transactions in the sandbox environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-with-sandbox",
      "kind": "article",
      "role": "article",
      "title": "Testing In-App Purchases with sandbox",
      "type": "topic",
      "url": "/documentation/storekit/testing-in-app-purchases-with-sandbox"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-resubscribing-from-the-subscriptions-page": {
      "abstract": [
        {
          "text": "Verify that your app can reactivate an expired subscription by receiving a transaction callback or inspecting an updated receipt.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-resubscribing-from-the-subscriptions-page",
      "kind": "article",
      "role": "article",
      "title": "Testing resubscribing from the subscriptions page",
      "type": "topic",
      "url": "/documentation/storekit/testing-resubscribing-from-the-subscriptions-page"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Subscriptions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/testing-an-auto-renewable-subscription",
        "doc://com.apple.storekit/documentation/StoreKit/testing-resubscribing-from-the-subscriptions-page"
      ],
      "title": "Subscriptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Subscriptions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/testing-an-auto-renewable-subscription",
                "doc://com.apple.storekit/documentation/StoreKit/testing-resubscribing-from-the-subscriptions-page"
              ],
              "title": "Subscriptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/testing-disabling-auto-renew"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/testing-disabling-auto-renew"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
