{"topicSections":[{"title":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/noColumnResizing","doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/autoColumnResizing","doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/userColumnResizing"],"anchor":"Constants"},{"title":"Initializers","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/init(rawValue:)"],"anchor":"Initializers"}],"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColumnResizingType"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"These constants are used by the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property"},{"text":" methods.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Types of browser column resizing."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/DropOperation","doc://com.apple.appkit/documentation/AppKit/application-kit-versions-for-nsbrowser-functionality"],"anchor":"Constants","generated":true,"title":"Constants"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"variants":[{"paths":["/documentation/appkit/nsbrowser/columnresizingtype-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsbrowser/columnresizingtype-swift.enum"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"enum","modules":[{"name":"AppKit"}],"title":"NSBrowser.ColumnResizingType","roleHeading":"Enumeration","externalID":"c:@E@NSBrowserColumnResizingType","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"extendedModule":"AppKit","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColumnResizingType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColumnResizingType"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/noColumnResizing":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noColumnResizing"}],"url":"/documentation/appkit/nsbrowser/columnresizingtype-swift.enum/nocolumnresizing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/noColumnResizing","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSBrowserNoColumnResizing"}],"type":"topic","abstract":[],"title":"NSBrowser.ColumnResizingType.noColumnResizing"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum":{"title":"NSBrowser.ColumnResizingType","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum","url":"/documentation/appkit/nsbrowser/columnresizingtype-swift.enum","navigatorTitle":[{"kind":"identifier","text":"ColumnResizingType"}],"abstract":[{"type":"text","text":"Types of browser column resizing."}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColumnResizingType"}]},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","title":"BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","type":"topic","abstract":[{"text":"","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property":{"type":"topic","abstract":[{"type":"text","text":"A constant indicating the browser’s column resizing type."}],"title":"columnResizingType","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"columnResizingType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBrowser","text":"NSBrowser","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSBrowserColumnResizingType","text":"ColumnResizingType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"columnResizingType","kind":"identifier"}],"url":"/documentation/appkit/nsbrowser/columnresizingtype-swift.property","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/userColumnResizing":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/userColumnResizing","title":"NSBrowser.ColumnResizingType.userColumnResizing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userColumnResizing"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSBrowserUserColumnResizing"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nsbrowser/columnresizingtype-swift.enum/usercolumnresizing"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/DropOperation":{"type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/DropOperation","url":"/documentation/appkit/nsbrowser/dropoperation","title":"NSBrowser.DropOperation","abstract":[{"text":"The type used to specify the drop type of a drag-and-drop operation. See ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowserDelegate/browser(_:validateDrop:proposedRow:column:dropOperation:)","type":"reference","isActive":true},{"text":" for more information.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DropOperation","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DropOperation","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa"},{"text":">","kind":"text"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SY","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSBrowser","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser","navigatorTitle":[{"text":"NSBrowser","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface that displays a hierarchically organized list of data items that can be navigated and selected."}],"type":"topic","title":"NSBrowser","url":"/documentation/appkit/nsbrowser"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/init(rawValue:)":{"type":"topic","kind":"symbol","role":"symbol","title":"init(rawValue:)","url":"/documentation/appkit/nsbrowser/columnresizingtype-swift.enum/init(rawvalue:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/init(rawValue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}]},"doc://com.apple.appkit/documentation/AppKit/application-kit-versions-for-nsbrowser-functionality":{"type":"topic","abstract":[{"text":"The version of the AppKit.framework containing a specific bug fix or capability.","type":"text"}],"title":"Application Kit Versions for NSBrowser Functionality","role":"collectionGroup","url":"/documentation/appkit/application-kit-versions-for-nsbrowser-functionality","identifier":"doc://com.apple.appkit/documentation/AppKit/application-kit-versions-for-nsbrowser-functionality","kind":"article"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowserDelegate/browser(_:validateDrop:proposedRow:column:dropOperation:)":{"type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowserDelegate/browser(_:validateDrop:proposedRow:column:dropOperation:)","url":"/documentation/appkit/nsbrowserdelegate/browser(_:validatedrop:proposedrow:column:dropoperation:)","title":"browser(_:validateDrop:proposedRow:column:dropOperation:)","abstract":[{"text":"Sent to the delegate during a dragging session to determine whether a drop should be accepted and to obtain the drop location. This method is required for a browser to be a drag destination.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"browser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSBrowser","preciseIdentifier":"c:objc(cs)NSBrowser","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"validateDrop","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"NSDraggingInfo","preciseIdentifier":"c:objc(pl)NSDraggingInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"proposedRow","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"column"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"dropOperation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSBrowser","preciseIdentifier":"c:objc(cs)NSBrowser"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSBrowserDropOperation","kind":"typeIdentifier","text":"DropOperation"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@E@NSDragOperation","kind":"typeIdentifier","text":"NSDragOperation"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"browser:validateDrop:proposedRow:column:dropOperation:"}]},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"type":"text","text":"Describes an unsigned integer."}],"url":"/documentation/objectivec/nsuinteger","kind":"symbol","role":"symbol","title":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/autoColumnResizing":{"title":"NSBrowser.ColumnResizingType.autoColumnResizing","navigatorTitle":[{"text":"NSBrowserAutoColumnResizing","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoColumnResizing","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"/documentation/appkit/nsbrowser/columnresizingtype-swift.enum/autocolumnresizing","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/autoColumnResizing"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration","op":"replace"},{"path":"/metadata/title","value":"NSBrowserColumnResizingType","op":"replace"},{"path":"/metadata/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"NSBrowserColumnResizingType","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"NSBrowserColumnResizingType","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace","path":"/hierarchy"},{"value":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/noColumnResizing","doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/autoColumnResizing","doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/userColumnResizing"]}],"op":"replace","path":"/topicSections"},{"value":null,"op":"replace","path":"/relationshipsSections"},{"value":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/DropOperation","doc://com.apple.appkit/documentation/AppKit/application-kit-versions-for-nsbrowser-functionality"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSBrowserColumnResizingType"},{"kind":"text","text":" : "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum~1noColumnResizing/title","value":"NSBrowserNoColumnResizing"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum~1noColumnResizing/fragments","value":[{"kind":"identifier","text":"NSBrowserNoColumnResizing"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum/title","value":"NSBrowserColumnResizingType"},{"op":"replace","value":[{"text":"NSBrowserColumnResizingType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum/fragments"},{"op":"replace","value":[{"text":"NSBrowserColumnResizingType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum/navigatorTitle"},{"op":"replace","value":"columnResizingType","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnResizingType-swift.property/title"},{"op":"replace","value":[{"kind":"identifier","text":"columnResizingType"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnResizingType-swift.property/fragments"},{"op":"replace","value":"NSBrowserUserColumnResizing","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum~1userColumnResizing/title"},{"op":"replace","value":[{"text":"NSBrowserUserColumnResizing","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum~1userColumnResizing/fragments"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1DropOperation/title","value":"NSBrowserDropOperation","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1DropOperation/fragments","value":[{"kind":"identifier","text":"NSBrowserDropOperation"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1DropOperation/navigatorTitle","value":[{"text":"NSBrowserDropOperation","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title","value":"NSBrowser","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments","value":[{"kind":"identifier","text":"NSBrowser"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle","value":[{"text":"NSBrowser","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowserDelegate~1browser(_:validateDrop:proposedRow:column:dropOperation:)/title","value":"browser:validateDrop:proposedRow:column:dropOperation:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowserDelegate~1browser(_:validateDrop:proposedRow:column:dropOperation:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"browser:validateDrop:proposedRow:column:dropOperation:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum~1autoColumnResizing/title","value":"NSBrowserAutoColumnResizing","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum~1autoColumnResizing/fragments","value":[{"kind":"identifier","text":"NSBrowserAutoColumnResizing"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}