{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"columnContentWidth"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forColumnWidth"},{"kind":"text","text":" "},{"kind":"internalParam","text":"columnWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"columnWidth","content":[{"type":"paragraph","inlineContent":[{"text":"The width of the column. This width is the entire scrolling text view.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The width of the content for the column. This is the width of the matrix in the column."}],"type":"paragraph"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"columnContentWidth(forColumnWidth:)","modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSBrowser(im)columnContentWidthForColumnWidth:","platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"columnContentWidth"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forColumnWidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"columnContentWidthForColumnWidth:","kind":"identifier"}]},"abstract":[{"text":"Returns the content width for a given column width.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnContentWidth(forColumnWidth:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbrowser/columncontentwidth(forcolumnwidth:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbrowser/columncontentwidth(forcolumnwidth:)"]}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/removeSavedColumns(withAutosaveName:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnsAutosaveName-swift.property","doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnsAutosaveName-swift.typealias","doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnWidth(forColumnContentWidth:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property","doc://com.apple.appkit/documentation/AppKit/NSBrowser/prefersAllColumnUserResizing","doc://com.apple.appkit/documentation/AppKit/NSBrowser/width(ofColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/setWidth(_:ofColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/defaultColumnWidth()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/setDefaultColumnWidth(_:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/rowHeight"],"title":"Sizing","generated":true,"anchor":"Sizing"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnWidth(forColumnContentWidth:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnWidth(forColumnContentWidth:)","role":"symbol","navigatorTitle":[{"text":"columnWidthForColumnContentWidth:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsbrowser/columnwidth(forcolumncontentwidth:)","abstract":[{"type":"text","text":"Returns the column width for the width of the given column’s content."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"columnWidth","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forColumnContentWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"columnWidth(forColumnContentWidth:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/removeSavedColumns(withAutosaveName:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/removeSavedColumns(withAutosaveName:)","role":"symbol","navigatorTitle":[{"text":"removeSavedColumnsWithAutosaveName:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsbrowser/removesavedcolumns(withautosavename:)","abstract":[{"text":"Removes the column configuration data stored under the given name from the application’s user defaults.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeSavedColumns"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAutosaveName"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSBrowser","text":"NSBrowser","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSBrowserColumnsAutosaveName","text":"ColumnsAutosaveName","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"removeSavedColumns(withAutosaveName:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnContentWidth(forColumnWidth:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnContentWidth(forColumnWidth:)","role":"symbol","navigatorTitle":[{"text":"columnContentWidthForColumnWidth:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsbrowser/columncontentwidth(forcolumnwidth:)","abstract":[{"text":"Returns the content width for a given column width.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"columnContentWidth","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forColumnWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"columnContentWidth(forColumnWidth:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSBrowser","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser","navigatorTitle":[{"text":"NSBrowser","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface that displays a hierarchically organized list of data items that can be navigated and selected."}],"type":"topic","title":"NSBrowser","url":"/documentation/appkit/nsbrowser"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","abstract":[{"text":"The basic type for all floating-point values.","type":"text"}],"type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/defaultColumnWidth()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/defaultColumnWidth()","role":"symbol","navigatorTitle":[{"text":"defaultColumnWidth","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsbrowser/defaultcolumnwidth()","abstract":[{"text":"Returns the default column width of the browser’s columns.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"defaultColumnWidth","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"defaultColumnWidth()","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/rowHeight":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/rowHeight","role":"symbol","navigatorTitle":[{"text":"rowHeight","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsbrowser/rowheight","abstract":[{"type":"text","text":"The height of the browser’s rows."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"rowHeight","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property":{"type":"topic","abstract":[{"type":"text","text":"A constant indicating the browser’s column resizing type."}],"title":"columnResizingType","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"columnResizingType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBrowser","text":"NSBrowser","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSBrowserColumnResizingType","text":"ColumnResizingType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"columnResizingType","kind":"identifier"}],"url":"/documentation/appkit/nsbrowser/columnresizingtype-swift.property","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/setWidth(_:ofColumn:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/setWidth(_:ofColumn:)","role":"symbol","navigatorTitle":[{"text":"setWidth:ofColumn:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsbrowser/setwidth(_:ofcolumn:)","abstract":[{"text":"Sets the width of the specified column.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setWidth","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"ofColumn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setWidth(_:ofColumn:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/prefersAllColumnUserResizing":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/prefersAllColumnUserResizing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefersAllColumnUserResizing"}],"type":"topic","url":"/documentation/appkit/nsbrowser/prefersallcolumnuserresizing","abstract":[{"text":"A Boolean that indicates whether the browser is set to resize all columns simultaneously rather than resizing a single column at a time.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"prefersAllColumnUserResizing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"prefersAllColumnUserResizing","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnsAutosaveName-swift.typealias":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ColumnsAutosaveName","kind":"identifier"}],"abstract":[],"title":"NSBrowser.ColumnsAutosaveName","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnsAutosaveName-swift.typealias","navigatorTitle":[{"kind":"identifier","text":"ColumnsAutosaveName"}],"type":"topic","url":"/documentation/appkit/nsbrowser/columnsautosavename-swift.typealias"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/setDefaultColumnWidth(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDefaultColumnWidth","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"kind":"symbol","title":"setDefaultColumnWidth(_:)","abstract":[{"type":"text","text":"Sets the default column width for new browser columns that do not otherwise have an initial width from defaults or the browser’s delegate."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/setDefaultColumnWidth(_:)","type":"topic","url":"/documentation/appkit/nsbrowser/setdefaultcolumnwidth(_:)","navigatorTitle":[{"kind":"identifier","text":"setDefaultColumnWidth:"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/width(ofColumn:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/width(ofColumn:)","role":"symbol","navigatorTitle":[{"text":"widthOfColumn:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsbrowser/width(ofcolumn:)","abstract":[{"text":"Returns the width of the specified column.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofColumn"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"width(ofColumn:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnsAutosaveName-swift.property":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"columnsAutosaveName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSBrowser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBrowser"},{"text":".","kind":"text"},{"text":"ColumnsAutosaveName","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSBrowserColumnsAutosaveName"}],"abstract":[{"type":"text","text":"The name used to automatically save the browser’s column configuration."}],"title":"columnsAutosaveName","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnsAutosaveName-swift.property","navigatorTitle":[{"text":"columnsAutosaveName","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsbrowser/columnsautosavename-swift.property"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"role":"symbol","type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","kind":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"CGFloat","kind":"identifier"}],"abstract":[{"text":"The basic type for floating-point scalar values in Core Graphics and related frameworks.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"columnContentWidthForColumnWidth:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"columnContentWidthForColumnWidth:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"path":"/hierarchy","op":"replace"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Sizing","title":"Sizing","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/removeSavedColumns(withAutosaveName:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnsAutosaveName-swift.property","doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnsAutosaveName-swift.typealias","doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnWidth(forColumnContentWidth:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property","doc://com.apple.appkit/documentation/AppKit/NSBrowser/prefersAllColumnUserResizing","doc://com.apple.appkit/documentation/AppKit/NSBrowser/width(ofColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/setWidth(_:ofColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/defaultColumnWidth()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/setDefaultColumnWidth(_:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/rowHeight"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"columnContentWidthForColumnWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"columnWidth","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"columnWidth","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The width of the column. This width is the entire scrolling text view."}]}]}]},"path":"/primaryContentSections/1"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The width of the content for the column. This is the width of the matrix in the column.","type":"text"}]}]},"path":"/primaryContentSections/2"},{"op":"replace","value":"columnWidthForColumnContentWidth:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnWidth(forColumnContentWidth:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"columnWidthForColumnContentWidth:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnWidth(forColumnContentWidth:)/fragments"},{"op":"replace","value":"removeSavedColumnsWithAutosaveName:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1removeSavedColumns(withAutosaveName:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"removeSavedColumnsWithAutosaveName:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1removeSavedColumns(withAutosaveName:)/fragments"},{"op":"replace","value":"columnContentWidthForColumnWidth:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnContentWidth(forColumnWidth:)/title"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnContentWidth(forColumnWidth:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"columnContentWidthForColumnWidth:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title","op":"replace","value":"NSBrowser"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments","op":"replace","value":[{"kind":"identifier","text":"NSBrowser"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle","value":[{"text":"NSBrowser","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1defaultColumnWidth()/title","value":"defaultColumnWidth","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1defaultColumnWidth()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"defaultColumnWidth"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1rowHeight/title","value":"rowHeight","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1rowHeight/fragments","value":[{"text":"rowHeight","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnResizingType-swift.property/title","value":"columnResizingType","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnResizingType-swift.property/fragments","value":[{"kind":"identifier","text":"columnResizingType"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setWidth(_:ofColumn:)/title","value":"setWidth:ofColumn:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setWidth(_:ofColumn:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setWidth:ofColumn:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1prefersAllColumnUserResizing/title","value":"prefersAllColumnUserResizing","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1prefersAllColumnUserResizing/fragments","value":[{"text":"prefersAllColumnUserResizing","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnsAutosaveName-swift.typealias/title","value":"NSBrowserColumnsAutosaveName","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnsAutosaveName-swift.typealias/fragments","value":[{"kind":"identifier","text":"NSBrowserColumnsAutosaveName"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnsAutosaveName-swift.typealias/navigatorTitle","value":[{"kind":"identifier","text":"NSBrowserColumnsAutosaveName"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setDefaultColumnWidth(_:)/title","value":"setDefaultColumnWidth:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setDefaultColumnWidth(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setDefaultColumnWidth:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1width(ofColumn:)/title","value":"widthOfColumn:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1width(ofColumn:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"widthOfColumn:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnsAutosaveName-swift.property/title","value":"columnsAutosaveName","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnsAutosaveName-swift.property/fragments","value":[{"kind":"identifier","text":"columnsAutosaveName"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}