{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbrowser/displayallcolumns"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"displayAllColumns","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}],"metadata":{"modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"displayAllColumns"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(cs)NSBrowser(im)displayAllColumns","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"displayAllColumns"}],"title":"displayAllColumns","platforms":[{"deprecated":false,"name":"macOS","deprecatedAt":"10.3","introducedAt":"10.0","unavailable":false,"beta":false}],"role":"symbol"},"deprecationSummary":[{"inlineContent":[{"text":"Use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/setNeedsDisplay(_:)"},{"text":" instead.","type":"text"}],"type":"paragraph"}],"kind":"symbol","abstract":[{"type":"text","text":"Updates the browser to display all loaded columns."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/displayAllColumns","interfaceLanguage":"occ"},"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/validateVisibleColumns()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/addColumn()"]},{"anchor":"Deprecated","generated":true,"title":"Deprecated","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/updateScroller","doc://com.apple.appkit/documentation/AppKit/NSBrowser/scrollViaScroller:","doc://com.apple.appkit/documentation/AppKit/NSBrowser/displayColumn:","doc://com.apple.appkit/documentation/AppKit/NSBrowser/column(of:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/matrix(inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/matrixClass()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/setMatrixClass(_:)"]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSBrowser/updateScroller":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/updateScroller","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateScroller"}],"url":"/documentation/appkit/nsbrowser/updatescroller","title":"updateScroller","deprecated":true,"abstract":[{"type":"text","text":"Updates the horizontal scroller to reflect column positions."}],"navigatorTitle":[{"kind":"identifier","text":"updateScroller"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/scrollViaScroller:":{"title":"scrollViaScroller:","url":"/documentation/appkit/nsbrowser/scrollviascroller:","abstract":[{"type":"text","text":"Scrolls columns left or right based on an "},{"type":"codeVoice","code":"NSScroller"},{"type":"text","text":"."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/scrollViaScroller:","deprecated":true,"type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"scrollViaScroller:","kind":"identifier"}],"navigatorTitle":[{"text":"scrollViaScroller:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView/setNeedsDisplay(_:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setNeedsDisplayInRect:"}],"role":"symbol","title":"setNeedsDisplay(_:)","abstract":[{"type":"text","text":"Marks the region of the view within the specified rectangle as needing display, increasing the view’s existing invalid region to include it."}],"url":"/documentation/appkit/nsview/setneedsdisplay(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNeedsDisplay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/setNeedsDisplay(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/matrixClass()":{"title":"matrixClass()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/matrixClass()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matrixClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsbrowser/matrixclass()","abstract":[{"type":"text","text":"Returns the matrix class used in the browser’s columns."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"matrixClass","kind":"identifier"}],"deprecated":true},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/displayAllColumns":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/displayAllColumns","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"displayAllColumns"}],"url":"/documentation/appkit/nsbrowser/displayallcolumns","title":"displayAllColumns","deprecated":true,"abstract":[{"type":"text","text":"Updates the browser to display all loaded columns."}],"navigatorTitle":[{"kind":"identifier","text":"displayAllColumns"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/addColumn()":{"abstract":[{"type":"text","text":"Adds a column to the right of the last column."}],"role":"symbol","url":"/documentation/appkit/nsbrowser/addcolumn()","title":"addColumn()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addColumn"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/addColumn()","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"addColumn"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/validateVisibleColumns()":{"type":"topic","abstract":[{"text":"Validates the browser’s visible columns.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"validateVisibleColumns"}],"title":"validateVisibleColumns()","role":"symbol","url":"/documentation/appkit/nsbrowser/validatevisiblecolumns()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/validateVisibleColumns()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validateVisibleColumns"},{"kind":"text","text":"()"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSBrowser","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser","navigatorTitle":[{"text":"NSBrowser","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface that displays a hierarchically organized list of data items that can be navigated and selected."}],"type":"topic","title":"NSBrowser","url":"/documentation/appkit/nsbrowser"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/setMatrixClass(_:)":{"title":"setMatrixClass(_:)","url":"/documentation/appkit/nsbrowser/setmatrixclass(_:)","abstract":[{"type":"text","text":"Sets the matrix class to be used in the browser’s columns."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/setMatrixClass(_:)","deprecated":true,"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMatrixClass","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setMatrixClass:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/column(of:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/column(of:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"column"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSMatrix","kind":"typeIdentifier","text":"NSMatrix"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"/documentation/appkit/nsbrowser/column(of:)","title":"column(of:)","deprecated":true,"abstract":[{"type":"text","text":"Returns the column number in which the given matrix is located."}],"navigatorTitle":[{"kind":"identifier","text":"columnOfMatrix:"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/displayColumn:":{"title":"displayColumn:","url":"/documentation/appkit/nsbrowser/displaycolumn:","abstract":[{"type":"text","text":"Updates the browser to display the given column."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/displayColumn:","deprecated":true,"type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"displayColumn:","kind":"identifier"}],"navigatorTitle":[{"text":"displayColumn:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/matrix(inColumn:)":{"title":"matrix(inColumn:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/matrix(inColumn:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matrix","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inColumn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSMatrix","preciseIdentifier":"c:objc(cs)NSMatrix","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/appkit/nsbrowser/matrix(incolumn:)","abstract":[{"text":"Returns the matrix located in the specified column.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"matrixInColumn:","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setNeedsDisplay(_:)/title","value":"setNeedsDisplayInRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setNeedsDisplay(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setNeedsDisplayInRect:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1matrixClass()/title","value":"matrixClass"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1matrixClass()/fragments","value":[{"text":"- ","kind":"text"},{"text":"matrixClass","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1addColumn()/title","value":"addColumn"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1addColumn()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addColumn"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1validateVisibleColumns()/title","value":"validateVisibleColumns"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1validateVisibleColumns()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateVisibleColumns"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title","value":"NSBrowser"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments","value":[{"kind":"identifier","text":"NSBrowser"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle","value":[{"text":"NSBrowser","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setMatrixClass(_:)/title","value":"setMatrixClass:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setMatrixClass(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMatrixClass:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1column(of:)/title","value":"columnOfMatrix:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1column(of:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"columnOfMatrix:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1matrix(inColumn:)/title","value":"matrixInColumn:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1matrix(inColumn:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"matrixInColumn:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}