{"metadata":{"externalID":"c:objc(cs)NSBrowser(im)itemAtIndexPath:","role":"symbol","platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.6"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"item"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"modules":[{"name":"AppKit"}],"symbolKind":"method","title":"item(at:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"itemAtIndexPath:"}]},"abstract":[{"type":"text","text":"Returns the item at the specified index path."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbrowser/item(at:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbrowser/item(at:)"]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"item","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","identifier":"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The index path of the item to return.","type":"text"}]}],"name":"indexPath"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"text":"The item.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method can only be used if the delegate implements the item data source methods. The specified index path must be displayable in the browser."}]}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/item(at:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Accessing-Components","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadedCell(atRow:column:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/editItem(at:with:select:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/item(atRow:inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/indexPath(forColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/isLeafItem(_:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/parentForItems(inColumn:)"],"generated":true,"title":"Accessing Components"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSBrowser":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSBrowser","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser","navigatorTitle":[{"text":"NSBrowser","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface that displays a hierarchically organized list of data items that can be navigated and selected."}],"type":"topic","title":"NSBrowser","url":"/documentation/appkit/nsbrowser"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/isLeafItem(_:)":{"abstract":[{"text":"Returns whether the specified item is a leaf item.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isLeafItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/isLeafItem(_:)","kind":"symbol","type":"topic","title":"isLeafItem(_:)","navigatorTitle":[{"text":"isLeafItem:","kind":"identifier"}],"url":"/documentation/appkit/nsbrowser/isleafitem(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV":{"title":"IndexPath","type":"topic","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"IndexPath"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV","abstract":[{"type":"text","text":"A list of indexes that together represent the path to a specific location in a tree of nested arrays. "}],"role":"symbol","url":"/documentation/foundation/indexpath","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/item(at:)":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/item(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"item","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"type":"topic","title":"item(at:)","role":"symbol","abstract":[{"text":"Returns the item at the specified index path.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"itemAtIndexPath:"}],"url":"/documentation/appkit/nsbrowser/item(at:)"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadedCell(atRow:column:)":{"abstract":[{"text":"Loads, if necessary, and returns the cell at the specified row and column location.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadedCell","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atRow","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"column"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadedCell(atRow:column:)","kind":"symbol","type":"topic","title":"loadedCell(atRow:column:)","navigatorTitle":[{"kind":"identifier","text":"loadedCellAtRow:column:"}],"url":"/documentation/appkit/nsbrowser/loadedcell(atrow:column:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/editItem(at:with:select:)":{"type":"topic","abstract":[{"text":"Begins editing the item at the specified path.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"editItemAtIndexPath:withEvent:select:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/editItem(at:with:select:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"select"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol","title":"editItem(at:with:select:)","url":"/documentation/appkit/nsbrowser/edititem(at:with:select:)"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/parentForItems(inColumn:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parentForItems","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inColumn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"title":"parentForItems(inColumn:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/parentForItems(inColumn:)","navigatorTitle":[{"kind":"identifier","text":"parentForItemsInColumn:"}],"url":"/documentation/appkit/nsbrowser/parentforitems(incolumn:)","type":"topic","abstract":[{"text":"Returns the item that contains the children located in the specified column.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath":{"abstract":[{"type":"text","text":"An object containing a list of indexes that bridges to ; use  when you need reference semantics or other Foundation-specific behavior."}],"type":"topic","title":"NSIndexPath","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSIndexPath"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath","role":"symbol","url":"/documentation/foundation/nsindexpath"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/indexPath(forColumn:)":{"abstract":[{"type":"text","text":"Returns the index path of the item whose children are displayed in the given column."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forColumn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/indexPath(forColumn:)","kind":"symbol","type":"topic","title":"indexPath(forColumn:)","navigatorTitle":[{"kind":"identifier","text":"indexPathForColumn:"}],"url":"/documentation/appkit/nsbrowser/indexpath(forcolumn:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/item(atRow:inColumn:)":{"abstract":[{"type":"text","text":"Returns the item located at the specified row and column."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"item","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atRow","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/item(atRow:inColumn:)","kind":"symbol","type":"topic","title":"item(atRow:inColumn:)","navigatorTitle":[{"kind":"identifier","text":"itemAtRow:inColumn:"}],"url":"/documentation/appkit/nsbrowser/item(atrow:incolumn:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"10.6","unavailable":false,"name":"macOS","beta":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"itemAtIndexPath:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"itemAtIndexPath:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Accessing Components","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadedCell(atRow:column:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/editItem(at:with:select:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/item(atRow:inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/indexPath(forColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/isLeafItem(_:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/parentForItems(inColumn:)"],"anchor":"Accessing-Components"}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"itemAtIndexPath:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath","text":"NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index path of the item to return."}]}],"name":"indexPath"}]}},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The item."}],"type":"paragraph"}]},"path":"/primaryContentSections/2"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title","value":"NSBrowser"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments","value":[{"kind":"identifier","text":"NSBrowser"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle","value":[{"text":"NSBrowser","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1isLeafItem(_:)/title","value":"isLeafItem:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1isLeafItem(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"isLeafItem:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1item(at:)/title","value":"itemAtIndexPath:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1item(at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemAtIndexPath:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1loadedCell(atRow:column:)/title","value":"loadedCellAtRow:column:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1loadedCell(atRow:column:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadedCellAtRow:column:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1editItem(at:with:select:)/title","value":"editItemAtIndexPath:withEvent:select:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1editItem(at:with:select:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"editItemAtIndexPath:withEvent:select:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1parentForItems(inColumn:)/title","value":"parentForItemsInColumn:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1parentForItems(inColumn:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parentForItemsInColumn:"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSIndexPath/abstract","value":[{"type":"text","text":"A list of indexes that together represent the path to a specific location in a tree of nested arrays."}]},{"value":"indexPathForColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1indexPath(forColumn:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexPathForColumn:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1indexPath(forColumn:)/fragments","op":"replace"},{"value":"itemAtRow:inColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1item(atRow:inColumn:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"itemAtRow:inColumn:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1item(atRow:inColumn:)/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}