{"abstract":[{"type":"text","text":"The index of the last visible column."}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Managing-Columns","title":"Managing Columns","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/addColumn()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedColumn","doc://com.apple.appkit/documentation/AppKit/NSBrowser/lastColumn","doc://com.apple.appkit/documentation/AppKit/NSBrowser/firstVisibleColumn","doc://com.apple.appkit/documentation/AppKit/NSBrowser/numberOfVisibleColumns","doc://com.apple.appkit/documentation/AppKit/NSBrowser/validateVisibleColumns()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/isLoaded","doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadColumnZero()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/reloadColumn(_:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"metadata":{"platforms":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"title":"lastVisibleColumn","modules":[{"name":"AppKit"}],"navigatorTitle":[{"text":"lastVisibleColumn","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastVisibleColumn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)NSBrowser(py)lastVisibleColumn"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastVisibleColumn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/lastVisibleColumn"},"variants":[{"paths":["/documentation/appkit/nsbrowser/lastvisiblecolumn"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsbrowser/lastvisiblecolumn"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/lastColumn":{"abstract":[{"text":"The index of the last column loaded.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/lastColumn","role":"symbol","navigatorTitle":[{"text":"lastColumn","kind":"identifier"}],"type":"topic","title":"lastColumn","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastColumn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","url":"/documentation/appkit/nsbrowser/lastcolumn"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/addColumn()":{"abstract":[{"type":"text","text":"Adds a column to the right of the last column."}],"role":"symbol","url":"/documentation/appkit/nsbrowser/addcolumn()","title":"addColumn()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addColumn"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/addColumn()","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"addColumn"}]},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/validateVisibleColumns()":{"type":"topic","abstract":[{"text":"Validates the browser’s visible columns.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"validateVisibleColumns"}],"title":"validateVisibleColumns()","role":"symbol","url":"/documentation/appkit/nsbrowser/validatevisiblecolumns()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/validateVisibleColumns()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validateVisibleColumns"},{"kind":"text","text":"()"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSBrowser","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser","navigatorTitle":[{"text":"NSBrowser","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface that displays a hierarchically organized list of data items that can be navigated and selected."}],"type":"topic","title":"NSBrowser","url":"/documentation/appkit/nsbrowser"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/isLoaded":{"url":"/documentation/appkit/nsbrowser/isloaded","title":"isLoaded","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/isLoaded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"A Boolean that indicates whether column 0 is loaded.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"loaded","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/reloadColumn(_:)":{"abstract":[{"text":"Reloads the given column.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/reloadColumn(_:)","role":"symbol","navigatorTitle":[{"text":"reloadColumn:","kind":"identifier"}],"type":"topic","title":"reloadColumn(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reloadColumn","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"/documentation/appkit/nsbrowser/reloadcolumn(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/numberOfVisibleColumns":{"url":"/documentation/appkit/nsbrowser/numberofvisiblecolumns","title":"numberOfVisibleColumns","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/numberOfVisibleColumns","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfVisibleColumns","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of visible columns."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"numberOfVisibleColumns"}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/lastVisibleColumn":{"url":"/documentation/appkit/nsbrowser/lastvisiblecolumn","title":"lastVisibleColumn","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/lastVisibleColumn","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastVisibleColumn","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The index of the last visible column."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"lastVisibleColumn"}],"type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/firstVisibleColumn":{"type":"topic","abstract":[{"text":"The index of the first visible column.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"firstVisibleColumn"}],"title":"firstVisibleColumn","role":"symbol","url":"/documentation/appkit/nsbrowser/firstvisiblecolumn","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/firstVisibleColumn","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"firstVisibleColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedColumn":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectedColumn"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedColumn","url":"/documentation/appkit/nsbrowser/selectedcolumn","kind":"symbol","abstract":[{"text":"The index of the last column with a selected item.","type":"text"}],"title":"selectedColumn","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadColumnZero()":{"url":"/documentation/appkit/nsbrowser/loadcolumnzero()","title":"loadColumnZero()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadColumnZero()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadColumnZero","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Loads column 0; unloads previously loaded columns.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"loadColumnZero","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"lastVisibleColumn","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"lastVisibleColumn","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Managing Columns","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/addColumn()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedColumn","doc://com.apple.appkit/documentation/AppKit/NSBrowser/lastColumn","doc://com.apple.appkit/documentation/AppKit/NSBrowser/firstVisibleColumn","doc://com.apple.appkit/documentation/AppKit/NSBrowser/numberOfVisibleColumns","doc://com.apple.appkit/documentation/AppKit/NSBrowser/validateVisibleColumns()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/isLoaded","doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadColumnZero()","doc://com.apple.appkit/documentation/AppKit/NSBrowser/reloadColumn(_:)"],"anchor":"Managing-Columns","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastVisibleColumn"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1lastColumn/title","value":"lastColumn"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1lastColumn/fragments","value":[{"kind":"identifier","text":"lastColumn"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1addColumn()/title","value":"addColumn"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1addColumn()/fragments","value":[{"text":"- ","kind":"text"},{"text":"addColumn","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1validateVisibleColumns()/title","value":"validateVisibleColumns"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1validateVisibleColumns()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateVisibleColumns"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title","value":"NSBrowser"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments","value":[{"text":"NSBrowser","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle","value":[{"kind":"identifier","text":"NSBrowser"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1isLoaded/title","value":"loaded"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1isLoaded/fragments","value":[{"text":"loaded","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1reloadColumn(_:)/title","value":"reloadColumn:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1reloadColumn(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reloadColumn:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1numberOfVisibleColumns/title","value":"numberOfVisibleColumns"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1numberOfVisibleColumns/fragments","value":[{"text":"numberOfVisibleColumns","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1lastVisibleColumn/title","value":"lastVisibleColumn"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1lastVisibleColumn/fragments","value":[{"kind":"identifier","text":"lastVisibleColumn"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1firstVisibleColumn/title","value":"firstVisibleColumn"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1firstVisibleColumn/fragments","value":[{"kind":"identifier","text":"firstVisibleColumn"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedColumn/title","value":"selectedColumn"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedColumn/fragments","value":[{"text":"selectedColumn","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1loadColumnZero()/title","value":"loadColumnZero"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1loadColumnZero()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadColumnZero"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}