{
  "abstract": [
    {
      "text": "A Boolean that indicates whether the browser is set to resize all columns simultaneously rather than resizing a single column at a time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/prefersAllColumnUserResizing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSBrowser(py)prefersAllColumnUserResizing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "prefersAllColumnUserResizing"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "prefersAllColumnUserResizing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "prefersAllColumnUserResizing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "prefersAllColumnUserResizing"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the browser is set to resize all columns simultaneously. The default value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This setting applies only to browsers that allow the user to resize columns (see the constant ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/userColumnResizing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). Holding down the Option key while resizing switches the type of resizing used. This setting is persistent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser": {
      "abstract": [
        {
          "text": "An interface that displays a hierarchically organized list of data items that can be navigated and selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBrowser"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBrowser"
        }
      ],
      "role": "symbol",
      "title": "NSBrowser",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/userColumnResizing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userColumnResizing"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnResizingType-swift.enum/userColumnResizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBrowserUserColumnResizing"
        }
      ],
      "role": "symbol",
      "title": "NSBrowser.ColumnResizingType.userColumnResizing",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/columnresizingtype-swift.enum/usercolumnresizing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnsAutosaveName-swift.typealias": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColumnsAutosaveName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnsAutosaveName-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColumnsAutosaveName"
        }
      ],
      "role": "symbol",
      "title": "NSBrowser.ColumnsAutosaveName",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/columnsautosavename-swift.typealias"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnContentWidth(forColumnWidth:)": {
      "abstract": [
        {
          "text": "Returns the content width for a given column width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnContentWidth"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forColumnWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnContentWidth(forColumnWidth:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnContentWidthForColumnWidth:"
        }
      ],
      "role": "symbol",
      "title": "columnContentWidth(forColumnWidth:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/columncontentwidth(forcolumnwidth:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property": {
      "abstract": [
        {
          "text": "A constant indicating the browser’s column resizing type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnResizingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBrowser",
          "text": "NSBrowser"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBrowserColumnResizingType",
          "text": "ColumnResizingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnResizingType"
        }
      ],
      "role": "symbol",
      "title": "columnResizingType",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/columnresizingtype-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnWidth(forColumnContentWidth:)": {
      "abstract": [
        {
          "text": "Returns the column width for the width of the given column’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnWidth"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forColumnContentWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnWidth(forColumnContentWidth:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnWidthForColumnContentWidth:"
        }
      ],
      "role": "symbol",
      "title": "columnWidth(forColumnContentWidth:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/columnwidth(forcolumncontentwidth:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnsAutosaveName-swift.property": {
      "abstract": [
        {
          "text": "The name used to automatically save the browser’s column configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnsAutosaveName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBrowser",
          "text": "NSBrowser"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBrowserColumnsAutosaveName",
          "text": "ColumnsAutosaveName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnsAutosaveName-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnsAutosaveName"
        }
      ],
      "role": "symbol",
      "title": "columnsAutosaveName",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/columnsautosavename-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/defaultColumnWidth()": {
      "abstract": [
        {
          "text": "Returns the default column width of the browser’s columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultColumnWidth"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/defaultColumnWidth()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultColumnWidth"
        }
      ],
      "role": "symbol",
      "title": "defaultColumnWidth()",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/defaultcolumnwidth()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/prefersAllColumnUserResizing": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the browser is set to resize all columns simultaneously rather than resizing a single column at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersAllColumnUserResizing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/prefersAllColumnUserResizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersAllColumnUserResizing"
        }
      ],
      "role": "symbol",
      "title": "prefersAllColumnUserResizing",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/prefersallcolumnuserresizing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/removeSavedColumns(withAutosaveName:)": {
      "abstract": [
        {
          "text": "Removes the column configuration data stored under the given name from the application’s user defaults.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSavedColumns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAutosaveName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBrowser",
          "text": "NSBrowser"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBrowserColumnsAutosaveName",
          "text": "ColumnsAutosaveName"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/removeSavedColumns(withAutosaveName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSavedColumnsWithAutosaveName:"
        }
      ],
      "role": "symbol",
      "title": "removeSavedColumns(withAutosaveName:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/removesavedcolumns(withautosavename:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/rowHeight": {
      "abstract": [
        {
          "text": "The height of the browser’s rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/rowHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowHeight"
        }
      ],
      "role": "symbol",
      "title": "rowHeight",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/rowheight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/setDefaultColumnWidth(_:)": {
      "abstract": [
        {
          "text": "Sets the default column width for new browser columns that do not otherwise have an initial width from defaults or the browser’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDefaultColumnWidth"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/setDefaultColumnWidth(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDefaultColumnWidth:"
        }
      ],
      "role": "symbol",
      "title": "setDefaultColumnWidth(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/setdefaultcolumnwidth(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/setWidth(_:ofColumn:)": {
      "abstract": [
        {
          "text": "Sets the width of the specified column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setWidth"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/setWidth(_:ofColumn:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setWidth:ofColumn:"
        }
      ],
      "role": "symbol",
      "title": "setWidth(_:ofColumn:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/setwidth(_:ofcolumn:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser/width(ofColumn:)": {
      "abstract": [
        {
          "text": "Returns the width of the specified column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser/width(ofColumn:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widthOfColumn:"
        }
      ],
      "role": "symbol",
      "title": "width(ofColumn:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser/width(ofcolumn:)"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sizing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/removeSavedColumns(withAutosaveName:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnsAutosaveName-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnsAutosaveName-swift.typealias",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnContentWidth(forColumnWidth:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnWidth(forColumnContentWidth:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/width(ofColumn:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/setWidth(_:ofColumn:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/defaultColumnWidth()",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/setDefaultColumnWidth(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser/rowHeight"
      ],
      "title": "Sizing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "prefersAllColumnUserResizing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersAllColumnUserResizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sizing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/removeSavedColumns(withAutosaveName:)",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnsAutosaveName-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/ColumnsAutosaveName-swift.typealias",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnContentWidth(forColumnWidth:)",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnWidth(forColumnContentWidth:)",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/columnResizingType-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/width(ofColumn:)",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/setWidth(_:ofColumn:)",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/defaultColumnWidth()",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/setDefaultColumnWidth(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser/rowHeight"
              ],
              "title": "Sizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "prefersAllColumnUserResizing"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1rowHeight/title",
          "value": "rowHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1rowHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnsAutosaveName-swift.typealias/title",
          "value": "NSBrowserColumnsAutosaveName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnsAutosaveName-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowserColumnsAutosaveName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnsAutosaveName-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowserColumnsAutosaveName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnWidth(forColumnContentWidth:)/title",
          "value": "columnWidthForColumnContentWidth:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnWidth(forColumnContentWidth:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "columnWidthForColumnContentWidth:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title",
          "value": "NSBrowser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1defaultColumnWidth()/title",
          "value": "defaultColumnWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1defaultColumnWidth()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "defaultColumnWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnContentWidth(forColumnWidth:)/title",
          "value": "columnContentWidthForColumnWidth:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnContentWidth(forColumnWidth:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "columnContentWidthForColumnWidth:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1prefersAllColumnUserResizing/title",
          "value": "prefersAllColumnUserResizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1prefersAllColumnUserResizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersAllColumnUserResizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnResizingType-swift.property/title",
          "value": "columnResizingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnResizingType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columnResizingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum~1userColumnResizing/title",
          "value": "NSBrowserUserColumnResizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1ColumnResizingType-swift.enum~1userColumnResizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowserUserColumnResizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1width(ofColumn:)/title",
          "value": "widthOfColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1width(ofColumn:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "widthOfColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setWidth(_:ofColumn:)/title",
          "value": "setWidth:ofColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setWidth(_:ofColumn:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setWidth:ofColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1removeSavedColumns(withAutosaveName:)/title",
          "value": "removeSavedColumnsWithAutosaveName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1removeSavedColumns(withAutosaveName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "removeSavedColumnsWithAutosaveName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setDefaultColumnWidth(_:)/title",
          "value": "setDefaultColumnWidth:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1setDefaultColumnWidth(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDefaultColumnWidth:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnsAutosaveName-swift.property/title",
          "value": "columnsAutosaveName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1columnsAutosaveName-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columnsAutosaveName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbrowser/prefersallcolumnuserresizing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbrowser/prefersallcolumnuserresizing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
