{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell(inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCells","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectAll(_:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedRow(inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRow(_:inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPath","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPaths"],"title":"Managing Selection","anchor":"Managing-Selection"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbrowser/selectedcell"]}],"abstract":[{"type":"text","text":"The last (rightmost and lowest) selected cell."}],"metadata":{"externalID":"c:objc(cs)NSBrowser(py)selectedCell","fragments":[{"text":"selectedCell","kind":"identifier"}],"modules":[{"name":"AppKit"}],"navigatorTitle":[{"text":"selectedCell","kind":"identifier"}],"title":"selectedCell","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","platforms":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedCell","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"When the value of this property is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", there is no selection.","type":"text"}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell"},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectAll(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectAll:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectAll(_:)","url":"/documentation/appkit/nsbrowser/selectall(_:)","kind":"symbol","abstract":[{"text":"Selects all cells in the last column of the browser.","type":"text"}],"title":"selectAll(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectAll"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCells":{"url":"/documentation/appkit/nsbrowser/selectedcells","title":"selectedCells","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCells","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCells"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSCell","preciseIdentifier":"c:objc(cs)NSCell"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"All cells selected in the rightmost column."}],"role":"symbol","navigatorTitle":[{"text":"selectedCells","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPaths":{"abstract":[{"text":"An array containing the index paths of all items selected in the browser.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPaths","role":"symbol","navigatorTitle":[{"text":"selectionIndexPaths","kind":"identifier"}],"type":"topic","title":"selectionIndexPaths","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionIndexPaths","kind":"identifier"},{"text":": [","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","url":"/documentation/appkit/nsbrowser/selectionindexpaths"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedRow(inColumn:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectedRowInColumn:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedRow(inColumn:)","url":"/documentation/appkit/nsbrowser/selectedrow(incolumn:)","kind":"symbol","abstract":[{"text":"Returns the row index of the selected cell in the specified column.","type":"text"}],"title":"selectedRow(inColumn:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedRow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSBrowser","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser","navigatorTitle":[{"text":"NSBrowser","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface that displays a hierarchically organized list of data items that can be navigated and selected."}],"type":"topic","title":"NSBrowser","url":"/documentation/appkit/nsbrowser"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRow(_:inColumn:)":{"abstract":[{"text":"Selects the cell at the specified row and column index.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRow(_:inColumn:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectRow:inColumn:"}],"type":"topic","title":"selectRow(_:inColumn:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectRow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"inColumn","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nsbrowser/selectrow(_:incolumn:)"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPath":{"abstract":[{"type":"text","text":"The index path of the item selected in the browser."}],"role":"symbol","url":"/documentation/appkit/nsbrowser/selectionindexpath","title":"selectionIndexPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPath","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectionIndexPath"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell":{"type":"topic","abstract":[{"text":"The last (rightmost and lowest) selected cell.","type":"text"}],"title":"selectedCell","role":"symbol","url":"/documentation/appkit/nsbrowser/selectedcell","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell","kind":"symbol","fragments":[{"text":"selectedCell","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell(inColumn:)":{"abstract":[{"text":"Returns the last (lowest) cell selected in the given column.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell(inColumn:)","role":"symbol","navigatorTitle":[{"text":"selectedCellInColumn:","kind":"identifier"}],"type":"topic","title":"selectedCell(inColumn:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedCell","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inColumn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"kind":"symbol","url":"/documentation/appkit/nsbrowser/selectedcell(incolumn:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectAll(_:)/title","value":"selectAll:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectAll(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectAll:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedCells/title","value":"selectedCells"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedCells/fragments","value":[{"kind":"identifier","text":"selectedCells"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectionIndexPaths/title","value":"selectionIndexPaths"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectionIndexPaths/fragments","value":[{"kind":"identifier","text":"selectionIndexPaths"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedRow(inColumn:)/title","value":"selectedRowInColumn:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedRow(inColumn:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectedRowInColumn:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title","value":"NSBrowser"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments","value":[{"kind":"identifier","text":"NSBrowser"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle","value":[{"text":"NSBrowser","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectRow(_:inColumn:)/title","value":"selectRow:inColumn:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectRow(_:inColumn:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectRow:inColumn:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectionIndexPath/title","value":"selectionIndexPath"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectionIndexPath/fragments","value":[{"text":"selectionIndexPath","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedCell(inColumn:)/title","value":"selectedCellInColumn:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedCell(inColumn:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectedCellInColumn:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}