{"variants":[{"paths":["/documentation/appkit/nsbrowser/selectedrow(incolumn:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsbrowser/selectedrow(incolumn:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"roleHeading":"Instance Method","title":"selectedRow(inColumn:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedRow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inColumn"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"externalID":"c:objc(cs)NSBrowser(im)selectedRowInColumn:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"selectedRowInColumn:"}],"role":"symbol","modules":[{"name":"AppKit"}]},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadedCell(atRow:column:)"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell(inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCells","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectAll(_:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRow(_:inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPath","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPaths"],"anchor":"Managing-Selection","generated":true,"title":"Managing Selection"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedRow(inColumn:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedRow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inColumn","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"column","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The column index specifying the column for which to return the selected row.","type":"text"}]}],"name":"column"}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The row index of the selected cell in the specified column. Returns ","type":"text"},{"code":"-1","type":"codeVoice"},{"text":" if there is no selection.","type":"text"}]}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"abstract":[{"type":"text","text":"Returns the row index of the selected cell in the specified column."}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedRow(inColumn:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectedRowInColumn:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedRow(inColumn:)","url":"/documentation/appkit/nsbrowser/selectedrow(incolumn:)","kind":"symbol","abstract":[{"text":"Returns the row index of the selected cell in the specified column.","type":"text"}],"title":"selectedRow(inColumn:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedRow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell(inColumn:)":{"abstract":[{"text":"Returns the last (lowest) cell selected in the given column.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell(inColumn:)","role":"symbol","navigatorTitle":[{"text":"selectedCellInColumn:","kind":"identifier"}],"type":"topic","title":"selectedCell(inColumn:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedCell","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inColumn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"kind":"symbol","url":"/documentation/appkit/nsbrowser/selectedcell(incolumn:)"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPath":{"abstract":[{"type":"text","text":"The index path of the item selected in the browser."}],"role":"symbol","url":"/documentation/appkit/nsbrowser/selectionindexpath","title":"selectionIndexPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPath","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectionIndexPath"}]},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRow(_:inColumn:)":{"abstract":[{"text":"Selects the cell at the specified row and column index.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRow(_:inColumn:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectRow:inColumn:"}],"type":"topic","title":"selectRow(_:inColumn:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectRow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"inColumn","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nsbrowser/selectrow(_:incolumn:)"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSBrowser","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser","navigatorTitle":[{"text":"NSBrowser","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface that displays a hierarchically organized list of data items that can be navigated and selected."}],"type":"topic","title":"NSBrowser","url":"/documentation/appkit/nsbrowser"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCells":{"url":"/documentation/appkit/nsbrowser/selectedcells","title":"selectedCells","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCells","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCells"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSCell","preciseIdentifier":"c:objc(cs)NSCell"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"All cells selected in the rightmost column."}],"role":"symbol","navigatorTitle":[{"text":"selectedCells","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPaths":{"abstract":[{"text":"An array containing the index paths of all items selected in the browser.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPaths","role":"symbol","navigatorTitle":[{"text":"selectionIndexPaths","kind":"identifier"}],"type":"topic","title":"selectionIndexPaths","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionIndexPaths","kind":"identifier"},{"text":": [","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","url":"/documentation/appkit/nsbrowser/selectionindexpaths"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectAll(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectAll:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectAll(_:)","url":"/documentation/appkit/nsbrowser/selectall(_:)","kind":"symbol","abstract":[{"text":"Selects all cells in the last column of the browser.","type":"text"}],"title":"selectAll(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectAll"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell":{"type":"topic","abstract":[{"text":"The last (rightmost and lowest) selected cell.","type":"text"}],"title":"selectedCell","role":"symbol","url":"/documentation/appkit/nsbrowser/selectedcell","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell","kind":"symbol","fragments":[{"text":"selectedCell","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadedCell(atRow:column:)":{"abstract":[{"text":"Loads, if necessary, and returns the cell at the specified row and column location.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadedCell","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atRow","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"column"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadedCell(atRow:column:)","kind":"symbol","type":"topic","title":"loadedCell(atRow:column:)","navigatorTitle":[{"kind":"identifier","text":"loadedCellAtRow:column:"}],"url":"/documentation/appkit/nsbrowser/loadedcell(atrow:column:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"selectedRowInColumn:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectedRowInColumn:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/loadedCell(atRow:column:)"]},{"title":"Managing Selection","anchor":"Managing-Selection","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCell(inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedCells","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectAll(_:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRow(_:inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPath","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectionIndexPaths"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"selectedRowInColumn:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"column","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"name":"column","content":[{"inlineContent":[{"text":"The column index specifying the column for which to return the selected row.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The row index of the selected cell in the specified column. Returns "},{"type":"codeVoice","code":"-1"},{"type":"text","text":" if there is no selection."}]}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedRow(inColumn:)/title","op":"replace","value":"selectedRowInColumn:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedRow(inColumn:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectedRowInColumn:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedCell(inColumn:)/title","op":"replace","value":"selectedCellInColumn:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedCell(inColumn:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectedCellInColumn:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectionIndexPath/title","op":"replace","value":"selectionIndexPath"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectionIndexPath/fragments","op":"replace","value":[{"text":"selectionIndexPath","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectRow(_:inColumn:)/title","op":"replace","value":"selectRow:inColumn:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectRow(_:inColumn:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectRow:inColumn:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title","op":"replace","value":"NSBrowser"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments","op":"replace","value":[{"text":"NSBrowser","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSBrowser"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedCells/title","op":"replace","value":"selectedCells"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedCells/fragments","op":"replace","value":[{"text":"selectedCells","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectionIndexPaths/title","op":"replace","value":"selectionIndexPaths"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectionIndexPaths/fragments","op":"replace","value":[{"text":"selectionIndexPaths","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectAll(_:)/title","op":"replace","value":"selectAll:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectAll(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectAll:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1loadedCell(atRow:column:)/title","op":"replace","value":"loadedCellAtRow:column:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1loadedCell(atRow:column:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadedCellAtRow:column:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}