{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","title":"selectedRowIndexes(inColumn:)","symbolKind":"method","platforms":[{"beta":false,"introducedAt":"10.5","name":"macOS","unavailable":false,"deprecated":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedRowIndexes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inColumn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)NSBrowser(im)selectedRowIndexesInColumn:","modules":[{"name":"AppKit"}],"navigatorTitle":[{"text":"selectedRowIndexesInColumn:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedRowIndexes(inColumn:)"},"sections":[],"kind":"symbol","abstract":[{"text":"Provides the indexes of the selected rows in a given column of the browser.","type":"text"}],"variants":[{"paths":["/documentation/appkit/nsbrowser/selectedrowindexes(incolumn:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsbrowser/selectedrowindexes(incolumn:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsBranchSelection","doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsEmptySelection","doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsMultipleSelection","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRowIndexes(_:inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsTypeSelect"],"anchor":"Managing-Selection-Behavior","title":"Managing Selection Behavior"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedRowIndexes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inColumn"},{"kind":"text","text":" "},{"kind":"internalParam","text":"column"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"column","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The column whose selected rows are provided."}]}]}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"Rows selected in column ","type":"text"},{"type":"codeVoice","code":"columnIndex"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsMultipleSelection":{"url":"/documentation/appkit/nsbrowser/allowsmultipleselection","abstract":[{"type":"text","text":"A Boolean that indicates whether the user can select multiple items."}],"title":"allowsMultipleSelection","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsMultipleSelection","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsMultipleSelection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"allowsMultipleSelection","kind":"identifier"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsTypeSelect":{"url":"/documentation/appkit/nsbrowser/allowstypeselect","abstract":[{"type":"text","text":"A Boolean that indicates whether the browser allows keystroke-based selection (type select)."}],"title":"allowsTypeSelect","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsTypeSelect","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsTypeSelect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"allowsTypeSelect","kind":"identifier"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRowIndexes(_:inColumn:)":{"url":"/documentation/appkit/nsbrowser/selectrowindexes(_:incolumn:)","abstract":[{"type":"text","text":"Specifies the selected rows in a given column of the browser."}],"title":"selectRowIndexes(_:inColumn:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRowIndexes(_:inColumn:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"selectRowIndexes","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inColumn"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"selectRowIndexes:inColumn:","kind":"identifier"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsEmptySelection":{"url":"/documentation/appkit/nsbrowser/allowsemptyselection","abstract":[{"type":"text","text":"A Boolean that indicates whether there can be nothing selected."}],"title":"allowsEmptySelection","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsEmptySelection","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowsEmptySelection","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowsEmptySelection"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSBrowser","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser","navigatorTitle":[{"text":"NSBrowser","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface that displays a hierarchically organized list of data items that can be navigated and selected."}],"type":"topic","title":"NSBrowser","url":"/documentation/appkit/nsbrowser"},"doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV":{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV","url":"/documentation/foundation/indexset","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"IndexSet"}],"kind":"symbol","type":"topic","title":"IndexSet","role":"symbol","abstract":[{"text":"A collection of unique integer values that represent the indexes of elements in another collection. ","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedRowIndexes(inColumn:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedRowIndexes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inColumn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectedRowIndexesInColumn:"}],"title":"selectedRowIndexes(inColumn:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectedRowIndexes(inColumn:)","url":"/documentation/appkit/nsbrowser/selectedrowindexes(incolumn:)","abstract":[{"text":"Provides the indexes of the selected rows in a given column of the browser.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsBranchSelection":{"kind":"symbol","url":"/documentation/appkit/nsbrowser/allowsbranchselection","navigatorTitle":[{"text":"allowsBranchSelection","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsBranchSelection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsBranchSelection","title":"allowsBranchSelection","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A Boolean that indicates whether the user can select branch items."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"10.5","beta":false,"name":"macOS","deprecated":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"selectedRowIndexesInColumn:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectedRowIndexesInColumn:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBrowser"]]}},{"path":"/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsBranchSelection","doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsEmptySelection","doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsMultipleSelection","doc://com.apple.appkit/documentation/AppKit/NSBrowser/selectRowIndexes(_:inColumn:)","doc://com.apple.appkit/documentation/AppKit/NSBrowser/allowsTypeSelect"],"generated":true,"anchor":"Managing-Selection-Behavior","title":"Managing Selection Behavior"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexSet","text":"NSIndexSet","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"selectedRowIndexesInColumn:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"column","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The column whose selected rows are provided."}],"type":"paragraph"}],"name":"column"}]},"path":"/primaryContentSections/1","op":"replace"},{"value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Rows selected in column "},{"type":"codeVoice","code":"columnIndex"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"value":"allowsMultipleSelection","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1allowsMultipleSelection/title","op":"replace"},{"value":[{"text":"allowsMultipleSelection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1allowsMultipleSelection/fragments","op":"replace"},{"value":"allowsTypeSelect","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1allowsTypeSelect/title","op":"replace"},{"value":[{"text":"allowsTypeSelect","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1allowsTypeSelect/fragments","op":"replace"},{"value":"selectRowIndexes:inColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectRowIndexes(_:inColumn:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"selectRowIndexes:inColumn:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectRowIndexes(_:inColumn:)/fragments","op":"replace"},{"value":"allowsEmptySelection","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1allowsEmptySelection/title","op":"replace"},{"value":[{"kind":"identifier","text":"allowsEmptySelection"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1allowsEmptySelection/fragments","op":"replace"},{"op":"replace","value":"NSBrowser","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title"},{"op":"replace","value":[{"text":"NSBrowser","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSBrowser"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle"},{"op":"replace","value":"selectedRowIndexesInColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedRowIndexes(inColumn:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectedRowIndexesInColumn:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1selectedRowIndexes(inColumn:)/fragments"},{"op":"replace","value":"allowsBranchSelection","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1allowsBranchSelection/title"},{"op":"replace","value":[{"text":"allowsBranchSelection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser~1allowsBranchSelection/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}