{
  "abstract": [
    {
      "text": "A policy that routes output to the shared long-form audio output.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longFormAudio"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioSessionRouteSharingPolicy@AVAudioSessionRouteSharingPolicyLongFormAudio",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "longFormAudio"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionRouteSharingPolicyLongFormAudio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVAudioSession.RouteSharingPolicy.longFormAudio"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "longFormAudio"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps that play long-form audio, such as music or audio books, can use this policy to play to the same output as the built-in Music and Podcast apps. Long-form audio apps should also use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework to add support for remote control events and to provide Now Playing information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Apps running in watchOS that use this policy are able to play audio in the background, as long as the audio session can activate an eligible audio route. These apps must activate their audio session using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/activate(options:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. This ensures that the user has the opportunity to pick an appropriate audio route when the audio session can’t select one automatically.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum": {
      "abstract": [
        {
          "text": "Cases that indicate the possible route-sharing policies for an audio session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RouteSharingPolicy"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RouteSharingPolicy"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteSharingPolicy",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routesharingpolicy-swift.enum"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/default": {
      "abstract": [
        {
          "text": "A policy that follows standard rules for routing audio output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSharingPolicyDefault"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteSharingPolicy.default",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routesharingpolicy-swift.enum/default"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/independent": {
      "abstract": [
        {
          "text": "A policy in which the route picker UI directs videos to a wireless route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "independent"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/independent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSharingPolicyIndependent"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteSharingPolicy.independent",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routesharingpolicy-swift.enum/independent"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longForm": {
      "abstract": [
        {
          "text": "A policy that routes output to the shared long-form audio output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longForm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionRouteSharingPolicy",
          "text": "RouteSharingPolicy"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longForm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSharingPolicyLongForm"
        }
      ],
      "role": "symbol",
      "title": "longForm",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routesharingpolicy-swift.enum/longform"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longFormAudio": {
      "abstract": [
        {
          "text": "A policy that routes output to the shared long-form audio output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longFormAudio"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longFormAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSharingPolicyLongFormAudio"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteSharingPolicy.longFormAudio",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routesharingpolicy-swift.enum/longformaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longFormVideo": {
      "abstract": [
        {
          "text": "A policy that routes output to the shared long-form video output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longFormVideo"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longFormVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSharingPolicyLongFormVideo"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteSharingPolicy.longFormVideo",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routesharingpolicy-swift.enum/longformvideo"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/activate(options:completionHandler:)": {
      "abstract": [
        {
          "text": "Activates an audio session asynchronously on watchOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionActivationOptions",
          "text": "AVAudioSessionActivationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/activate(options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activateWithOptions:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "activate(options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/activate(options:completionhandler:)"
    },
    "doc://com.apple.documentation/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/MediaPlayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Route-sharing-policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/default",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longFormVideo",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/independent",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longForm"
      ],
      "title": "Route-sharing policies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSessionRouteSharingPolicyLongFormAudio"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSharingPolicyLongFormAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Route-sharing-policies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/default",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longFormVideo",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/independent",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum/longForm"
              ],
              "title": "Route-sharing policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudioSessionRouteSharingPolicyLongFormAudio"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1longFormAudio/title",
          "value": "AVAudioSessionRouteSharingPolicyLongFormAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1longFormAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSharingPolicyLongFormAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1default/title",
          "value": "AVAudioSessionRouteSharingPolicyDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSharingPolicyDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1activate(options:completionHandler:)/title",
          "value": "activateWithOptions:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1activate(options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activateWithOptions:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1longFormVideo/title",
          "value": "AVAudioSessionRouteSharingPolicyLongFormVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1longFormVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSharingPolicyLongFormVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1independent/title",
          "value": "AVAudioSessionRouteSharingPolicyIndependent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1independent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSharingPolicyIndependent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1longForm/title",
          "value": "AVAudioSessionRouteSharingPolicyLongForm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum~1longForm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSharingPolicyLongForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum/title",
          "value": "AVAudioSessionRouteSharingPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSharingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSharingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/routesharingpolicy-swift.enum/longformaudio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/routesharingpolicy-swift.enum/longformaudio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
