{
  "abstract": [
    {
      "text": "The center along the x-axis of the object’s alignment rectangle.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/centerX"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSLayoutAttribute@NSLayoutAttributeCenterX",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "centerX"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLayoutAttributeCenterX"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSLayoutConstraint.Attribute.centerX"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "centerX"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint": {
      "abstract": [
        {
          "text": "The relationship between two user interface objects that must be satisfied by the constraint-based layout system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute": {
      "abstract": [
        {
          "text": "The part of the object’s visual representation that should be used to get the value for the constraint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/bottom": {
      "abstract": [
        {
          "text": "The bottom of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeBottom"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.bottom",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/bottom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/centerX": {
      "abstract": [
        {
          "text": "The center along the x-axis of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerX"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/centerX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeCenterX"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.centerX",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/centerx"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/centerY": {
      "abstract": [
        {
          "text": "The center along the y-axis of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerY"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/centerY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeCenterY"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.centerY",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/centery"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/firstBaseline": {
      "abstract": [
        {
          "text": "The object’s baseline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstBaseline"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/firstBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeFirstBaseline"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.firstBaseline",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/firstbaseline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/height": {
      "abstract": [
        {
          "text": "The height of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "height"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/height",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeHeight"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.height",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/height"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/lastBaseline": {
      "abstract": [
        {
          "text": "The object’s baseline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastBaseline"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/lastBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeLastBaseline"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.lastBaseline",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/lastbaseline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/leading": {
      "abstract": [
        {
          "text": "The leading edge of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeLeading"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.leading",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/leading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/left": {
      "abstract": [
        {
          "text": "The left side of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeLeft"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.left",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/left"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/notAnAttribute": {
      "abstract": [
        {
          "text": "A placeholder value for indicating that the constraint’s second item and second attribute aren’t used in any calculations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAnAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/notAnAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeNotAnAttribute"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.notAnAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/notanattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/right": {
      "abstract": [
        {
          "text": "The right side of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeRight"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.right",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/right"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/top": {
      "abstract": [
        {
          "text": "The top of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeTop"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.top",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/top"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/trailing": {
      "abstract": [
        {
          "text": "The trailing edge of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.trailing",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/trailing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/width": {
      "abstract": [
        {
          "text": "The width of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/width",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeWidth"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.width",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/attribute/width"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/left",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/right",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/top",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/bottom",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/leading",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/trailing",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/width",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/height",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/centerY",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/lastBaseline",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/firstBaseline",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/notAnAttribute"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLayoutAttributeCenterX"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeCenterX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/left",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/right",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/top",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/bottom",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/leading",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/trailing",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/width",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/height",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/centerY",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/lastBaseline",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/firstBaseline",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Attribute/notAnAttribute"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSLayoutAttributeCenterX"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1leading/title",
          "value": "NSLayoutAttributeLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1width/title",
          "value": "NSLayoutAttributeWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1width/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1height/title",
          "value": "NSLayoutAttributeHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1height/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute/title",
          "value": "NSLayoutAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1centerX/title",
          "value": "NSLayoutAttributeCenterX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1centerX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeCenterX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1notAnAttribute/title",
          "value": "NSLayoutAttributeNotAnAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1notAnAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeNotAnAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1top/title",
          "value": "NSLayoutAttributeTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1left/title",
          "value": "NSLayoutAttributeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/title",
          "value": "NSLayoutConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1right/title",
          "value": "NSLayoutAttributeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1lastBaseline/title",
          "value": "NSLayoutAttributeLastBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1lastBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeLastBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1centerY/title",
          "value": "NSLayoutAttributeCenterY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1centerY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeCenterY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1bottom/title",
          "value": "NSLayoutAttributeBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1trailing/title",
          "value": "NSLayoutAttributeTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1firstBaseline/title",
          "value": "NSLayoutAttributeFirstBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Attribute~1firstBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeFirstBaseline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nslayoutconstraint/attribute/centerx"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nslayoutconstraint/attribute/centerx"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
