{
  "abstract": [
    {
      "text": "Reports an event to the system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDiscoverySession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDiscoverySession/report(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DDDiscoverySession(im)reportEvent:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "report"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)DDDeviceEvent",
        "text": "DDDeviceEvent"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "DeviceDiscoveryExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "reportEvent:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "report(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "report"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inEvent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDeviceEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)DDDeviceEvent",
              "text": "DDDeviceEvent"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The event to report.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inEvent"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The extension updates the system with the discovery status of the device of interest by passing event objects (",
              "type": "text"
            },
            {
              "code": "DDEvent",
              "type": "codeVoice"
            },
            {
              "text": ") through this function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension": {
      "abstract": [
        {
          "text": "Stream media to a third-party device that a user selects in a system menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "DeviceDiscoveryExtension",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDeviceEvent": {
      "abstract": [
        {
          "text": "An object that provides a device or communicates its change in status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDDeviceEvent"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDeviceEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDeviceEvent"
        }
      ],
      "role": "symbol",
      "title": "DDDeviceEvent",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddeviceevent"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDiscoverySession": {
      "abstract": [
        {
          "text": "An object that relays device discovery events from the extension to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDDiscoverySession"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDiscoverySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDiscoverySession"
        }
      ],
      "role": "symbol",
      "title": "DDDiscoverySession",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddiscoverysession"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDiscoverySession/report(_:)": {
      "abstract": [
        {
          "text": "Reports an event to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "report"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDDeviceEvent",
          "text": "DDDeviceEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDiscoverySession/report(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportEvent:"
        }
      ],
      "role": "symbol",
      "title": "report(_:)",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddiscoverysession/report(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "reportEvent:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDiscoverySession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "reportEvent:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDeviceEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)DDDeviceEvent",
                    "text": "DDDeviceEvent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inEvent"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The event to report.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inEvent"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDiscoverySession/title",
          "value": "DDDiscoverySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDiscoverySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDiscoverySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDiscoverySession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDiscoverySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDiscoverySession~1report(_:)/title",
          "value": "reportEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDiscoverySession~1report(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDeviceEvent/title",
          "value": "DDDeviceEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDeviceEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDeviceEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/devicediscoveryextension/dddiscoverysession/report(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/devicediscoveryextension/dddiscoverysession/report(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
