{
  "abstract": [
    {
      "text": "The type of map item detail accessory presentation to use.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MapKit",
    "externalID": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MapItemDetailPresentationStyle"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MapItemDetailPresentationStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MKSelectionAccessory.MapItemDetailPresentationStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MapItemDetailPresentationStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailSelectionAccessoryPresentationStyle/automaticWithPresentationViewController:": {
      "abstract": [
        {
          "text": "An appropriate presentation style will be chosen automatically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "automaticWithPresentationViewController:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailSelectionAccessoryPresentationStyle/automaticWithPresentationViewController:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticWithPresentationViewController:"
        }
      ],
      "role": "symbol",
      "title": "automaticWithPresentationViewController:",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemdetailselectionaccessorypresentationstyle/automaticwithpresentationviewcontroller:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailSelectionAccessoryPresentationStyle/calloutWithCalloutStyle:": {
      "abstract": [
        {
          "text": "Show map item detail as an annotation callout on the map",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "calloutWithCalloutStyle:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailSelectionAccessoryPresentationStyle/calloutWithCalloutStyle:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calloutWithCalloutStyle:"
        }
      ],
      "role": "symbol",
      "title": "calloutWithCalloutStyle:",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemdetailselectionaccessorypresentationstyle/calloutwithcalloutstyle:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController": {
      "abstract": [
        {
          "text": "An object that displays detailed information about a map item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItemDetailViewController"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItemDetailViewController"
        }
      ],
      "role": "symbol",
      "title": "MKMapItemDetailViewController",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemdetailviewcontroller"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate": {
      "abstract": [
        {
          "text": "The methods that you use to receive events from an associated map view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItemDetailViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItemDetailViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "MKMapItemDetailViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemdetailviewcontrollerdelegate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory": {
      "abstract": [
        {
          "text": "The type of accessory to display for a selected annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKSelectionAccessory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKSelectionAccessory"
        }
      ],
      "role": "symbol",
      "title": "MKSelectionAccessory",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle": {
      "abstract": [
        {
          "text": "The type of map item detail accessory presentation to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "MKSelectionAccessory.MapItemDetailPresentationStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle": {
      "abstract": [
        {
          "text": "The style to use for a map item detail callout presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CalloutStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CalloutStyle"
        }
      ],
      "role": "symbol",
      "title": "MKSelectionAccessory.MapItemDetailPresentationStyle.CalloutStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle/calloutstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/automatic(presentationViewController:)-648ee": {
      "abstract": [
        {
          "text": "An appropriate presentation style will be chosen automatically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "presentationViewController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/automatic(presentationViewController:)-648ee",
      "kind": "symbol",
      "role": "symbol",
      "title": "automatic(presentationViewController:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle/automatic(presentationviewcontroller:)-648ee"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/automatic(presentationViewController:)-9t9vt": {
      "abstract": [
        {
          "text": "An appropriate presentation style will be chosen automatically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "presentationViewController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/automatic(presentationViewController:)-9t9vt",
      "kind": "symbol",
      "role": "symbol",
      "title": "automatic(presentationViewController:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle/automatic(presentationviewcontroller:)-9t9vt"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/callout": {
      "abstract": [
        {
          "text": "Show map item detail as an annotation callout on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/callout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callout"
        }
      ],
      "role": "symbol",
      "title": "callout",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle/callout"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/callout(_:)": {
      "abstract": [
        {
          "text": "Show map item detail as an annotation callout on the map",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
          "text": "MapItemDetailPresentationStyle"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapItemDetailSelectionAccessoryCalloutStyle",
          "text": "CalloutStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/callout(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "callout(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle/callout(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/openInMaps": {
      "abstract": [
        {
          "text": "Display a small “Open in Apple Maps” link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openInMaps"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/openInMaps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openInMaps"
        }
      ],
      "role": "symbol",
      "title": "openInMaps",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle/openinmaps"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/sheet(presentedFrom:)": {
      "abstract": [
        {
          "text": "Show map item detail by presenting a sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "presentedFrom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/sheet(presentedFrom:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sheetPresentedFromViewController:"
        }
      ],
      "role": "symbol",
      "title": "sheet(presentedFrom:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle/sheet(presentedfrom:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Place-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle"
      ],
      "title": "Place information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-presentation-style",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/automatic(presentationViewController:)-648ee",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/automatic(presentationViewController:)-9t9vt",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/callout",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/callout(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/openInMaps",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/sheet(presentedFrom:)"
      ],
      "title": "Creating a presentation style"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKMapItemDetailSelectionAccessoryPresentationStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-presentation-style",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailSelectionAccessoryPresentationStyle/automaticWithPresentationViewController:",
                "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/callout",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailSelectionAccessoryPresentationStyle/calloutWithCalloutStyle:",
                "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/openInMaps",
                "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/sheet(presentedFrom:)"
              ],
              "title": "Creating a presentation style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Place-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController",
                "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory",
                "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle"
              ],
              "title": "Place information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1CalloutStyle/title",
          "value": "MKMapItemDetailSelectionAccessoryCalloutStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1CalloutStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryCalloutStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1CalloutStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryCalloutStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1sheet(presentedFrom:)/title",
          "value": "sheetPresentedFromViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1sheet(presentedFrom:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sheetPresentedFromViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1callout/title",
          "value": "callout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1callout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewController/title",
          "value": "MKMapItemDetailViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/title",
          "value": "MKMapItemDetailSelectionAccessoryPresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1openInMaps/title",
          "value": "openInMaps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1openInMaps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "openInMaps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewControllerDelegate/title",
          "value": "MKMapItemDetailViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/title",
          "value": "MKSelectionAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSelectionAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSelectionAccessory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
