{
  "abstract": [
    {
      "text": "Detailed information about a place",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/mapItemDetail(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKSelectionAccessory(cm)mapItemDetailWithPresentationStyle:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mapItemDetail"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
        "text": "MKSelectionAccessory"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
        "text": "MapItemDetailPresentationStyle"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
        "text": "MKSelectionAccessory"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mapItemDetailWithPresentationStyle:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "mapItemDetail(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mapItemDetail"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "presentationStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
              "text": "MKSelectionAccessory"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
              "text": "MapItemDetailPresentationStyle"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
              "text": "MKSelectionAccessory"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The presentation style to use",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "presentationStyle"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Supported for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemAnnotation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation": {
      "abstract": [
        {
          "text": "A class that describes an annotation element on the map’s display such as a point of interest, territorial boundary, or physical feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemAnnotation": {
      "abstract": [
        {
          "text": "An annotation that represents a map item",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItemAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItemAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKMapItemAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory": {
      "abstract": [
        {
          "text": "The type of accessory to display for a selected annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKSelectionAccessory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKSelectionAccessory"
        }
      ],
      "role": "symbol",
      "title": "MKSelectionAccessory",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle": {
      "abstract": [
        {
          "text": "The type of map item detail accessory presentation to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "MKSelectionAccessory.MapItemDetailPresentationStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/mapItemDetail(_:)": {
      "abstract": [
        {
          "text": "Detailed information about a place",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapItemDetail"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
          "text": "MapItemDetailPresentationStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/mapItemDetail(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapItemDetailWithPresentationStyle:"
        }
      ],
      "role": "symbol",
      "title": "mapItemDetail(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetail(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mapItemDetailWithPresentationStyle:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "mapItemDetailWithPresentationStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
                    "text": "MKSelectionAccessory"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "mapItemDetailWithPresentationStyle:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
                    "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "presentationStyle"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The presentation style to use",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "presentationStyle"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/title",
          "value": "MKSelectionAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSelectionAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSelectionAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemAnnotation/title",
          "value": "MKMapItemAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1mapItemDetail(_:)/title",
          "value": "mapItemDetailWithPresentationStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1mapItemDetail(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "mapItemDetailWithPresentationStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/title",
          "value": "MKMapFeatureAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/title",
          "value": "MKMapItemDetailSelectionAccessoryPresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkselectionaccessory/mapitemdetail(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkselectionaccessory/mapitemdetail(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
