{
  "abstract": [
    {
      "text": "Selects a record or a set of records in the record list.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/select(_:byExtendingSelection:)-9eldk"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ABPeoplePickerView(im)selectRecord:byExtendingSelection:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "select"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ABRecord",
        "text": "ABRecord"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "byExtendingSelection"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "selectRecord:byExtendingSelection:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "select(_:byExtendingSelection:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "select"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "record"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ABRecord",
              "text": "ABRecord"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "byExtendingSelection"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "extend"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The record to be selected, or to be added to the current selection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "record"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to extend the current selection; otherwise, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "extend"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView": {
      "abstract": [
        {
          "text": "An object you use to customize the behavior of people-picker views in an app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPeoplePickerView"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerView"
        }
      ],
      "role": "symbol",
      "title": "ABPeoplePickerView",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/allowsGroupSelection": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the user can select entire groups in the group column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsGroupSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/allowsGroupSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsGroupSelection"
        }
      ],
      "role": "symbol",
      "title": "allowsGroupSelection",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/allowsgroupselection"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/allowsMultipleSelection": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether multiple groups, records, or values of multivalue properties can be selected at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsMultipleSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/allowsMultipleSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsMultipleSelection"
        }
      ],
      "role": "symbol",
      "title": "allowsMultipleSelection",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/allowsmultipleselection"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselect(_:)-1yy11": {
      "abstract": [
        {
          "text": "Deselects a record selected in the record list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABRecord",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselect(_:)-1yy11",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deselectRecord:"
        }
      ],
      "role": "symbol",
      "title": "deselect(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/deselect(_:)-1yy11"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselect(_:)-3x7tl": {
      "abstract": [
        {
          "text": "Deselects a group selected in the group list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABGroup",
          "text": "ABGroup"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselect(_:)-3x7tl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deselectGroup:"
        }
      ],
      "role": "symbol",
      "title": "deselect(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/deselect(_:)-3x7tl"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselectAll(_:)": {
      "abstract": [
        {
          "text": "Deselects all selected groups, records, and values in multivalue properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deselectAll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselectAll(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deselectAll:"
        }
      ],
      "role": "symbol",
      "title": "deselectAll(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/deselectall(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselectIdentifier(_:for:)": {
      "abstract": [
        {
          "text": "Deselects a value selected in a multivalue property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deselectIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPerson",
          "text": "ABPerson"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselectIdentifier(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deselectIdentifier:forPerson:"
        }
      ],
      "role": "symbol",
      "title": "deselectIdentifier(_:for:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/deselectidentifier(_:for:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/select(_:byExtendingSelection:)-6mrii": {
      "abstract": [
        {
          "text": "Selects a group or a set of groups in the group list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "select"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABGroup",
          "text": "ABGroup"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "byExtendingSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/select(_:byExtendingSelection:)-6mrii",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectGroup:byExtendingSelection:"
        }
      ],
      "role": "symbol",
      "title": "select(_:byExtendingSelection:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/select(_:byextendingselection:)-6mrii"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/select(_:byExtendingSelection:)-9eldk": {
      "abstract": [
        {
          "text": "Selects a record or a set of records in the record list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "select"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABRecord",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "byExtendingSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/select(_:byExtendingSelection:)-9eldk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectRecord:byExtendingSelection:"
        }
      ],
      "role": "symbol",
      "title": "select(_:byExtendingSelection:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/select(_:byextendingselection:)-9eldk"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectIdentifier(_:for:byExtendingSelection:)": {
      "abstract": [
        {
          "text": "Selects a value or a set of values in a multivalue property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPerson",
          "text": "ABPerson"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "byExtendingSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectIdentifier(_:for:byExtendingSelection:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectIdentifier:forPerson:byExtendingSelection:"
        }
      ],
      "role": "symbol",
      "title": "selectIdentifier(_:for:byExtendingSelection:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/selectidentifier(_:for:byextendingselection:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedGroups": {
      "abstract": [
        {
          "text": "The groups selected in the group list. (read-only)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedGroups"
        }
      ],
      "role": "symbol",
      "title": "selectedGroups",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/selectedgroups"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedIdentifiers(for:)": {
      "abstract": [
        {
          "text": "Returns the identifiers of the selected values in a multivalue property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedIdentifiers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPerson",
          "text": "ABPerson"
        },
        {
          "kind": "text",
          "text": "!) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedIdentifiers(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedIdentifiersForPerson:"
        }
      ],
      "role": "symbol",
      "title": "selectedIdentifiers(for:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/selectedidentifiers(for:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedRecords": {
      "abstract": [
        {
          "text": "The selection in the records list. (read-only)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedRecords"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedRecords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedRecords"
        }
      ],
      "role": "symbol",
      "title": "selectedRecords",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/selectedrecords"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedValues()": {
      "abstract": [
        {
          "text": "Returns an array of all the values selected in the displayed multivalue property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedValues"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedValues()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedValues"
        }
      ],
      "role": "symbol",
      "title": "selectedValues()",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview/selectedvalues()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class": {
      "abstract": [
        {
          "text": "An abstract class that defines the common properties for all Address Book records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "role": "symbol",
      "title": "ABRecord",
      "type": "topic",
      "url": "/documentation/addressbook/abrecord-swift.class"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selecting-Groups-and-Records",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/allowsGroupSelection",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/allowsMultipleSelection",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselectAll(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselect(_:)-3x7tl",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselectIdentifier(_:for:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselect(_:)-1yy11",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedGroups",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedIdentifiers(for:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedRecords",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedValues()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/select(_:byExtendingSelection:)-6mrii",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectIdentifier(_:for:byExtendingSelection:)"
      ],
      "title": "Selecting Groups and Records"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "selectRecord:byExtendingSelection:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectRecord:byExtendingSelection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selecting-Groups-and-Records",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/allowsGroupSelection",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/allowsMultipleSelection",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselectAll(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselect(_:)-3x7tl",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselectIdentifier(_:for:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/deselect(_:)-1yy11",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedGroups",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedIdentifiers(for:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedRecords",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectedValues()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/select(_:byExtendingSelection:)-6mrii",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView/selectIdentifier(_:for:byExtendingSelection:)"
              ],
              "title": "Selecting Groups and Records"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "selectRecord:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ABRecord",
                    "text": "ABRecord"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "record"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "byExtendingSelection:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "extend"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The record to be selected, or to be added to the current selection.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "record"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/true",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to extend the current selection; otherwise, ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "extend"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1select(_:byExtendingSelection:)-9eldk/title",
          "value": "selectRecord:byExtendingSelection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1select(_:byExtendingSelection:)-9eldk/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectRecord:byExtendingSelection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1allowsGroupSelection/title",
          "value": "allowsGroupSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1allowsGroupSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsGroupSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1deselectAll(_:)/title",
          "value": "deselectAll:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1deselectAll(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deselectAll:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1deselectIdentifier(_:for:)/title",
          "value": "deselectIdentifier:forPerson:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1deselectIdentifier(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deselectIdentifier:forPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectedGroups/title",
          "value": "selectedGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectedGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1deselect(_:)-1yy11/title",
          "value": "deselectRecord:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1deselect(_:)-1yy11/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deselectRecord:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectedIdentifiers(for:)/title",
          "value": "selectedIdentifiersForPerson:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectedIdentifiers(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectedIdentifiersForPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1select(_:byExtendingSelection:)-6mrii/title",
          "value": "selectGroup:byExtendingSelection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1select(_:byExtendingSelection:)-6mrii/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectGroup:byExtendingSelection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1allowsMultipleSelection/title",
          "value": "allowsMultipleSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1allowsMultipleSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsMultipleSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectIdentifier(_:for:byExtendingSelection:)/title",
          "value": "selectIdentifier:forPerson:byExtendingSelection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectIdentifier(_:for:byExtendingSelection:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectIdentifier:forPerson:byExtendingSelection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectedValues()/title",
          "value": "selectedValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectedValues()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectedValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.class/title",
          "value": "ABRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectedRecords/title",
          "value": "selectedRecords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1selectedRecords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedRecords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1deselect(_:)-3x7tl/title",
          "value": "deselectGroup:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView~1deselect(_:)-3x7tl/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deselectGroup:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView/title",
          "value": "ABPeoplePickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abpeoplepickerview/select(_:byextendingselection:)-9eldk"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abpeoplepickerview/select(_:byextendingselection:)-9eldk"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
