{"variants":[{"paths":["/documentation/appkit/nscollectionviewsectionheaderview/sectioncollapsebutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscollectionviewsectionheaderview/sectioncollapsebutton"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView"]]},"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.12","name":"macOS"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"sectionCollapseButton","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"AppKit"}],"title":"sectionCollapseButton","role":"symbol","externalID":"c:objc(pl)NSCollectionViewSectionHeaderView(py)sectionCollapseButton","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sectionCollapseButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSButton","text":"NSButton"},{"kind":"text","text":"?"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView/sectionCollapseButton"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@IBOutlet","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sectionCollapseButton","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSButton","text":"NSButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSButton"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"For the best user experience, set this property to the button that lets users control the collapsing of a section so that the collection view can show and hide the button appropriately, based on whether the section’s items can be displayed in the available space. The collection view uses its ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionView/toggleSectionCollapse(_:)","isActive":true,"type":"reference"},{"text":" property to access this button.","type":"text"}]}]}],"sections":[],"abstract":[{"text":"A control that lets users collapse and open a collection view section.","type":"text"}],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView":{"abstract":[{"text":"A protocol that defines a button to control the collapse of a collection view’s section.","type":"text"}],"url":"/documentation/appkit/nscollectionviewsectionheaderview","kind":"symbol","role":"symbol","title":"NSCollectionViewSectionHeaderView","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewSectionHeaderView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSCollectionViewSectionHeaderView"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView/sectionCollapseButton":{"url":"/documentation/appkit/nscollectionviewsectionheaderview/sectioncollapsebutton","navigatorTitle":[{"kind":"identifier","text":"sectionCollapseButton"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sectionCollapseButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSButton","preciseIdentifier":"c:objc(cs)NSButton","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"sectionCollapseButton","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView/sectionCollapseButton","abstract":[{"text":"A control that lets users collapse and open a collection view section.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSButton":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSButton","kind":"identifier"}],"title":"NSButton","url":"/documentation/appkit/nsbutton","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSButton","type":"topic","abstract":[{"text":"A control that defines an area on the screen that a user clicks to trigger an action.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSButton","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionView/toggleSectionCollapse(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggleSectionCollapse"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"toggleSectionCollapse:","kind":"identifier"}],"title":"toggleSectionCollapse(_:)","url":"/documentation/appkit/nscollectionview/togglesectioncollapse(_:)","abstract":[{"text":"Collapses the section in which the sender resides into a single horizontally scrollable row.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionView/toggleSectionCollapse(_:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"macOS","introducedAt":"10.12","beta":false,"deprecated":false,"unavailable":false}],"op":"replace"},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"sectionCollapseButton"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"sectionCollapseButton"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSButton","text":"NSButton","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSButton"},{"text":" * ","kind":"text"},{"text":"sectionCollapseButton","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"NSCollectionViewSectionHeaderView","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView/title"},{"value":[{"text":"NSCollectionViewSectionHeaderView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView/fragments"},{"value":[{"kind":"identifier","text":"NSCollectionViewSectionHeaderView"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView/navigatorTitle"},{"value":"sectionCollapseButton","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView~1sectionCollapseButton/title","op":"replace"},{"value":[{"text":"sectionCollapseButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView~1sectionCollapseButton/fragments","op":"replace"},{"value":"NSButton","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title","op":"replace"},{"value":[{"text":"NSButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments","op":"replace"},{"value":[{"text":"NSButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle","op":"replace"},{"value":"toggleSectionCollapse:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1toggleSectionCollapse(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toggleSectionCollapse:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1toggleSectionCollapse(_:)/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}