{
  "abstract": [
    {
      "text": "Creates a multiarray sharing the surface of a pixel buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(pixelBuffer:shape:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreML",
    "externalID": "c:objc(cs)MLMultiArray(im)initWithPixelBuffer:shape:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "pixelBuffer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CVPixelBufferRef",
        "text": "CVPixelBuffer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "shape"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithPixelBuffer:shape:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(pixelBuffer:shape:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "pixelBuffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVPixelBufferRef",
              "text": "CVPixelBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "shape"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The pixel buffer owned by the instance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pixelBuffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The shape of the ",
                  "type": "text"
                },
                {
                  "code": "MLMultiArray",
                  "type": "codeVoice"
                },
                {
                  "text": ". The last dimension of ",
                  "type": "text"
                },
                {
                  "code": "shape",
                  "type": "codeVoice"
                },
                {
                  "text": " must match the pixel buffer’s width. The product of the rest of the dimensions must match the height.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "shape"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this initializer to create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/IOSurface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "-backed ",
              "type": "text"
            },
            {
              "code": "MLMultiArray",
              "type": "codeVoice"
            },
            {
              "text": " that reduces the inference latency by avoiding the buffer copy to and from some compute units.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The instance will own the pixel buffer and release it on the deallocation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The pixel buffer’s pixel format type must be ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_OneComponent16Half",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The ",
              "type": "text"
            },
            {
              "code": "MLMultiArray",
              "type": "codeVoice"
            },
            {
              "text": " data type is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float16",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray": {
      "abstract": [
        {
          "text": "A machine learning collection type that stores numeric values in an array with multiple dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMultiArray"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArray"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArray",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-3eqoq": {
      "abstract": [
        {
          "text": "Creates a multiarray from a collection of integers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-3eqoq",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(_:)-3eqoq"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-8bsfu": {
      "abstract": [
        {
          "text": "Creates a multiarray from a collection of doubles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-8bsfu",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(_:)-8bsfu"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-fh2x": {
      "abstract": [
        {
          "text": "Creates a multiarray from a collection of floats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-fh2x",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(_:)-fh2x"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-wk41": {
      "abstract": [
        {
          "text": "Creates a multiarray from a shaped array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ShapedArray"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "ShapedArray"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-wk41",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(_:)-wk41"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(byConcatenatingMultiArrays:alongAxis:dataType:)": {
      "abstract": [
        {
          "text": "Merges an array of multiarrays into one multiarray along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byConcatenatingMultiArrays"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLMultiArray",
          "text": "MLMultiArray"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "alongAxis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMultiArrayDataType",
          "text": "MLMultiArrayDataType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(byConcatenatingMultiArrays:alongAxis:dataType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "multiArrayByConcatenatingMultiArrays:alongAxis:dataType:"
        }
      ],
      "role": "symbol",
      "title": "init(byConcatenatingMultiArrays:alongAxis:dataType:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(byconcatenatingmultiarrays:alongaxis:datatype:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(dataPointer:shape:dataType:strides:deallocator:)": {
      "abstract": [
        {
          "text": "Creates a multiarray from a data pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "dataPointer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "dataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMultiArrayDataType",
          "text": "MLMultiArrayDataType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "strides"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(dataPointer:shape:dataType:strides:deallocator:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDataPointer:shape:dataType:strides:deallocator:error:"
        }
      ],
      "role": "symbol",
      "title": "init(dataPointer:shape:dataType:strides:deallocator:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(datapointer:shape:datatype:strides:deallocator:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(pixelBuffer:shape:)": {
      "abstract": [
        {
          "text": "Creates a multiarray sharing the surface of a pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "pixelBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(pixelBuffer:shape:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPixelBuffer:shape:"
        }
      ],
      "role": "symbol",
      "title": "init(pixelBuffer:shape:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(pixelbuffer:shape:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(shape:dataType:)": {
      "abstract": [
        {
          "text": "Creates a multidimensional array with a shape and type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "dataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMultiArrayDataType",
          "text": "MLMultiArrayDataType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(shape:dataType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithShape:dataType:error:"
        }
      ],
      "role": "symbol",
      "title": "init(shape:dataType:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(shape:datatype:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType": {
      "abstract": [
        {
          "text": "Constants that define the underlying element types a multiarray can store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataType"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataType"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArrayDataType",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float16": {
      "abstract": [
        {
          "text": "Designates the multiarray’s elements as 16-bit floats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float16"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataTypeFloat16"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArrayDataType.float16",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype/float16"
    },
    "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_OneComponent16Half": {
      "abstract": [
        {
          "text": "6-bit one component IEEE half-precision float, 16-bit little-endian samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_OneComponent16Half"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_OneComponent16Half",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCVPixelFormatType_OneComponent16Half",
      "type": "topic",
      "url": "/documentation/CoreVideo/kCVPixelFormatType_OneComponent16Half"
    },
    "doc://com.apple.documentation/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/IOSurface"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef": {
      "abstract": [
        {
          "text": "A reference to a Core Video pixel buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/CoreVideo/CVPixelBuffer"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Multiarray",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-3eqoq",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-fh2x",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-8bsfu",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(shape:dataType:)",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-wk41",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(dataPointer:shape:dataType:strides:deallocator:)",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(byConcatenatingMultiArrays:alongAxis:dataType:)",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType"
      ],
      "title": "Creating a Multiarray"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithPixelBuffer:shape:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPixelBuffer:shape:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArray"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Multiarray",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(shape:dataType:)",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(dataPointer:shape:dataType:strides:deallocator:)",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(byConcatenatingMultiArrays:alongAxis:dataType:)",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType"
              ],
              "title": "Creating a Multiarray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithPixelBuffer:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CVPixelBufferRef",
                    "text": "CVPixelBufferRef"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pixelBuffer"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "shape:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSNumber *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "shape"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The pixel buffer owned by the instance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pixelBuffer"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The shape of the ",
                        "type": "text"
                      },
                      {
                        "code": "MLMultiArray",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". The last dimension of ",
                        "type": "text"
                      },
                      {
                        "code": "shape",
                        "type": "codeVoice"
                      },
                      {
                        "text": " must match the pixel buffer’s width. The product of the rest of the dimensions must match the height.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "shape"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreVideo~1kCVPixelFormatType_OneComponent16Half/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_OneComponent16Half"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray/title",
          "value": "MLMultiArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float16/title",
          "value": "MLMultiArrayDataTypeFloat16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataTypeFloat16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVPixelBufferRef/title",
          "value": "CVPixelBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVPixelBufferRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVImageBufferRef",
              "text": "CVImageBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVPixelBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(pixelBuffer:shape:)/title",
          "value": "initWithPixelBuffer:shape:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(pixelBuffer:shape:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPixelBuffer:shape:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(byConcatenatingMultiArrays:alongAxis:dataType:)/title",
          "value": "multiArrayByConcatenatingMultiArrays:alongAxis:dataType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(byConcatenatingMultiArrays:alongAxis:dataType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "multiArrayByConcatenatingMultiArrays:alongAxis:dataType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType/title",
          "value": "MLMultiArrayDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(dataPointer:shape:dataType:strides:deallocator:)/title",
          "value": "initWithDataPointer:shape:dataType:strides:deallocator:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(dataPointer:shape:dataType:strides:deallocator:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDataPointer:shape:dataType:strides:deallocator:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(shape:dataType:)/title",
          "value": "initWithShape:dataType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(shape:dataType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithShape:dataType:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlmultiarray/init(pixelbuffer:shape:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlmultiarray/init(pixelbuffer:shape:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
