{
  "abstract": [
    {
      "text": "A constant that resets a dimension’s value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/unspecifiedDimension"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSSplitViewItemUnspecifiedDimension",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unspecifiedDimension"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSplitViewItemUnspecifiedDimension"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "unspecifiedDimension"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unspecifiedDimension"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this constant with any sizing-related ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to reset its value to the standard system default.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem": {
      "abstract": [
        {
          "text": "An item in a split view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSplitViewItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewItem"
        }
      ],
      "role": "symbol",
      "title": "NSSplitViewItem",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/automaticMaximumThickness": {
      "abstract": [
        {
          "text": "The maximum thickness of the split view item when it resizes due to automatic sizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticMaximumThickness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/automaticMaximumThickness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticMaximumThickness"
        }
      ],
      "role": "symbol",
      "title": "automaticMaximumThickness",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/automaticmaximumthickness"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/maximumThickness": {
      "abstract": [
        {
          "text": "The maximum thickness of the split view item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumThickness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/maximumThickness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumThickness"
        }
      ],
      "role": "symbol",
      "title": "maximumThickness",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/maximumthickness"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/minimumThickness": {
      "abstract": [
        {
          "text": "The minimum thickness of the split view item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumThickness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/minimumThickness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumThickness"
        }
      ],
      "role": "symbol",
      "title": "minimumThickness",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/minimumthickness"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/preferredThicknessFraction": {
      "abstract": [
        {
          "text": "The preferred thickness of the split view item relative to the split view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredThicknessFraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/preferredThicknessFraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredThicknessFraction"
        }
      ],
      "role": "symbol",
      "title": "preferredThicknessFraction",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/preferredthicknessfraction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/unspecifiedDimension": {
      "abstract": [
        {
          "text": "A constant that resets a dimension’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecifiedDimension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/unspecifiedDimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewItemUnspecifiedDimension"
        }
      ],
      "role": "symbol",
      "title": "unspecifiedDimension",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/unspecifieddimension"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Item-Thickness",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/automaticMaximumThickness",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/preferredThicknessFraction",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/minimumThickness",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/maximumThickness"
      ],
      "title": "Managing the Item Thickness"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSplitViewItemUnspecifiedDimension"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItemUnspecifiedDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Item-Thickness",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/automaticMaximumThickness",
                "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/preferredThicknessFraction",
                "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/minimumThickness",
                "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/maximumThickness"
              ],
              "title": "Managing the Item Thickness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSSplitViewItemUnspecifiedDimension"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem/title",
          "value": "NSSplitViewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1maximumThickness/title",
          "value": "maximumThickness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1maximumThickness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumThickness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1automaticMaximumThickness/title",
          "value": "automaticMaximumThickness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1automaticMaximumThickness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticMaximumThickness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1preferredThicknessFraction/title",
          "value": "preferredThicknessFraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1preferredThicknessFraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredThicknessFraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1unspecifiedDimension/title",
          "value": "NSSplitViewItemUnspecifiedDimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1unspecifiedDimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItemUnspecifiedDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1minimumThickness/title",
          "value": "minimumThickness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1minimumThickness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumThickness"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssplitviewitem/unspecifieddimension"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssplitviewitem/unspecifieddimension"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
