{
  "abstract": [
    {
      "text": "The file type and creator codes for the item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/typeAndCreator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSFileProviderItem(py)typeAndCreator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "typeAndCreator"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@NSFileProviderTypeAndCreator",
        "text": "NSFileProviderTypeAndCreator"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "typeAndCreator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "typeAndCreator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "typeAndCreator"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTypeAndCreator",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@NSFileProviderTypeAndCreator",
              "text": "NSFileProviderTypeAndCreator"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property contains two values: the file type code and the creator code. The system synchronizes both codes at the same time, so define both, even if you’re just changing one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you modify this property, the system sets the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTypeAndCreator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value passed to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension/createItem(basedOn:fields:contents:options:request:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension/modifyItem(_:baseVersion:changedFields:contents:options:request:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods. The system also writes the type and creator codes in the ",
              "type": "text"
            },
            {
              "code": "FileInfo",
              "type": "codeVoice"
            },
            {
              "text": " structure, if relevant.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderFavoriteRankUnranked": {
      "abstract": [
        {
          "text": "A value that indicates that the item is not ranked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderFavoriteRankUnranked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderFavoriteRankUnranked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderFavoriteRankUnranked"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderFavoriteRankUnranked",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderfavoriterankunranked"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderFileSystemFlags": {
      "abstract": [
        {
          "text": "Flags that define an item’s on-disk properties and its appearance in the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderFileSystemFlags"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderFileSystemFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderFileSystemFlags"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderFileSystemFlags",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderfilesystemflags"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol": {
      "abstract": [
        {
          "text": "A protocol that defines the properties of an item managed by the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderItemProtocol"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderItemProtocol",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemprotocol"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/extendedAttributes": {
      "abstract": [
        {
          "text": "The extended file attributes synced by the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/extendedAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedAttributes"
        }
      ],
      "role": "symbol",
      "title": "extendedAttributes",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemprotocol/extendedattributes"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/favoriteRank": {
      "abstract": [
        {
          "text": "A 64-bit, unsigned integer indicating the order of the favorite item in the Favorites list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "favoriteRank"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/favoriteRank",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "favoriteRank"
        }
      ],
      "role": "symbol",
      "title": "favoriteRank",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemprotocol/favoriterank"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/fileSystemFlags": {
      "abstract": [
        {
          "text": "Flags that define an item’s on-disk properties and its appearance in the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileSystemFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderFileSystemFlags",
          "text": "NSFileProviderFileSystemFlags"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/fileSystemFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileSystemFlags"
        }
      ],
      "role": "symbol",
      "title": "fileSystemFlags",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemprotocol/filesystemflags"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/tagData": {
      "abstract": [
        {
          "text": "An abstract data blob representing the tags associated with the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tagData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/tagData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tagData"
        }
      ],
      "role": "symbol",
      "title": "tagData",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemprotocol/tagdata"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/typeAndCreator": {
      "abstract": [
        {
          "text": "The file type and creator codes for the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeAndCreator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSFileProviderTypeAndCreator",
          "text": "NSFileProviderTypeAndCreator"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/typeAndCreator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeAndCreator"
        }
      ],
      "role": "symbol",
      "title": "typeAndCreator",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemprotocol/typeandcreator"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/userInfo": {
      "abstract": [
        {
          "text": "A property list that contains additional data about the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/userInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemprotocol/userinfo"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension/createItem(basedOn:fields:contents:options:request:completionHandler:)": {
      "abstract": [
        {
          "text": "Tells the file provider to create or import an item based on a template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "basedOn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItem",
          "text": "NSFileProviderItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fields"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemFields",
          "text": "NSFileProviderItemFields"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderCreateItemOptions",
          "text": "NSFileProviderCreateItemOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "request"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFileProviderRequest",
          "text": "NSFileProviderRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItem",
          "text": "NSFileProviderItem"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemFields",
          "text": "NSFileProviderItemFields"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension/createItem(basedOn:fields:contents:options:request:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createItemBasedOnTemplate:fields:contents:options:request:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "createItem(basedOn:fields:contents:options:request:completionHandler:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderreplicatedextension/createitem(basedon:fields:contents:options:request:completionhandler:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension/modifyItem(_:baseVersion:changedFields:contents:options:request:completionHandler:)": {
      "abstract": [
        {
          "text": "Tells the file provider that an item’s content or metadata changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modifyItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItem",
          "text": "NSFileProviderItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "baseVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFileProviderItemVersion",
          "text": "NSFileProviderItemVersion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "changedFields"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemFields",
          "text": "NSFileProviderItemFields"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderModifyItemOptions",
          "text": "NSFileProviderModifyItemOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "request"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFileProviderRequest",
          "text": "NSFileProviderRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItem",
          "text": "NSFileProviderItem"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemFields",
          "text": "NSFileProviderItemFields"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension/modifyItem(_:baseVersion:changedFields:contents:options:request:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modifyItem:baseVersion:changedFields:contents:options:request:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "modifyItem(_:baseVersion:changedFields:contents:options:request:completionHandler:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderreplicatedextension/modifyitem(_:baseversion:changedfields:contents:options:request:completionhandler:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTypeAndCreator": {
      "abstract": [
        {
          "text": "A structure that contains the file type and file creator codes for an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTypeAndCreator"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTypeAndCreator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTypeAndCreator"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTypeAndCreator",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertypeandcreator"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/extendedAttributes",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/fileSystemFlags",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderFileSystemFlags",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/tagData",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/userInfo",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/favoriteRank",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderFavoriteRankUnranked"
      ],
      "title": "Managing Metadata"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "typeAndCreator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeAndCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/extendedAttributes",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/fileSystemFlags",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderFileSystemFlags",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/tagData",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/userInfo",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/favoriteRank",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderFavoriteRankUnranked"
              ],
              "title": "Managing Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTypeAndCreator",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@NSFileProviderTypeAndCreator",
                    "text": "NSFileProviderTypeAndCreator"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "typeAndCreator"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1typeAndCreator/title",
          "value": "typeAndCreator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1typeAndCreator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeAndCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1tagData/title",
          "value": "tagData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1tagData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tagData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1userInfo/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1userInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension~1modifyItem(_:baseVersion:changedFields:contents:options:request:completionHandler:)/title",
          "value": "modifyItem:baseVersion:changedFields:contents:options:request:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension~1modifyItem(_:baseVersion:changedFields:contents:options:request:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "modifyItem:baseVersion:changedFields:contents:options:request:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension~1createItem(basedOn:fields:contents:options:request:completionHandler:)/title",
          "value": "createItemBasedOnTemplate:fields:contents:options:request:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension~1createItem(basedOn:fields:contents:options:request:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createItemBasedOnTemplate:fields:contents:options:request:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1fileSystemFlags/title",
          "value": "fileSystemFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1fileSystemFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fileSystemFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1favoriteRank/title",
          "value": "favoriteRank"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1favoriteRank/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "favoriteRank"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderFavoriteRankUnranked/title",
          "value": "NSFileProviderFavoriteRankUnranked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderFavoriteRankUnranked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderFavoriteRankUnranked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1extendedAttributes/title",
          "value": "extendedAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1extendedAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol/title",
          "value": "NSFileProviderItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderFileSystemFlags/title",
          "value": "NSFileProviderFileSystemFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderFileSystemFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderFileSystemFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderFileSystemFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderFileSystemFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTypeAndCreator/title",
          "value": "NSFileProviderTypeAndCreator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTypeAndCreator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTypeAndCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTypeAndCreator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTypeAndCreator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovideritemprotocol/typeandcreator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovideritemprotocol/typeandcreator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
