{
  "abstract": [
    {
      "text": "An option that rotates the image 90 degrees counterclockwise and then scales it, while preserving its aspect ratio, to fit on the long side.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFitRotate90CCW"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VNImageCropAndScaleOption@VNImageCropAndScaleOptionScaleFitRotate90CCW",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "scaleFitRotate90CCW"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "VNImageCropAndScaleOption.scaleFitRotate90CCW"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scaleFitRotate90CCW"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This option optimizes portrait images to fit into landscape buffers for algorithms that are rotation agnostic, and fills the remaining space with transparent pixels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption": {
      "abstract": [
        {
          "text": "Options that define how Vision crops and scales an input-image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOption"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOption"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/centerCrop": {
      "abstract": [
        {
          "text": "An option that scales the image to fit its shorter side within the input dimensions, while preserving its aspect ratio, and center-crops the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerCrop"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/centerCrop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionCenterCrop"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.centerCrop",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/centercrop"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill": {
      "abstract": [
        {
          "text": "An option that scales the image to fill the input dimensions, resizing it if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFill"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionScaleFill"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.scaleFill",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/scalefill"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFillRotate90CCW": {
      "abstract": [
        {
          "text": "An option that rotates the image 90 degrees counterclockwise and then scales it to fill the input dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFillRotate90CCW"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFillRotate90CCW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionScaleFillRotate90CCW"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.scaleFillRotate90CCW",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/scalefillrotate90ccw"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFit": {
      "abstract": [
        {
          "text": "An option that scales the image to fit its longer side within the input dimensions, while preserving its aspect ratio, and center-crops the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFit"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionScaleFit"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.scaleFit",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/scalefit"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFitRotate90CCW": {
      "abstract": [
        {
          "text": "An option that rotates the image 90 degrees counterclockwise and then scales it, while preserving its aspect ratio, to fit on the long side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFitRotate90CCW"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFitRotate90CCW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.scaleFitRotate90CCW",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/scalefitrotate90ccw"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Crop-and-Scale-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/centerCrop",
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFit",
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill",
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFillRotate90CCW"
      ],
      "title": "Crop and Scale Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Crop-and-Scale-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/centerCrop",
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFit",
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill",
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFillRotate90CCW"
              ],
              "title": "Crop and Scale Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFillRotate90CCW/title",
          "value": "VNImageCropAndScaleOptionScaleFillRotate90CCW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFillRotate90CCW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFillRotate90CCW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1centerCrop/title",
          "value": "VNImageCropAndScaleOptionCenterCrop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1centerCrop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionCenterCrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFitRotate90CCW/title",
          "value": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFitRotate90CCW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFitRotate90CCW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFit/title",
          "value": "VNImageCropAndScaleOptionScaleFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption/title",
          "value": "VNImageCropAndScaleOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFill/title",
          "value": "VNImageCropAndScaleOptionScaleFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFill"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnimagecropandscaleoption/scalefitrotate90ccw"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnimagecropandscaleoption/scalefitrotate90ccw"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
