{
  "abstract": [
    {
      "text": "An unknown error occurred.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorUnknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@CMError@CMErrorUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMErrorUnknown"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@CMError",
        "text": "CMError"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMErrorUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CMErrorUnknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMErrorUnknown"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@CMError",
              "text": "CMError"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMError": {
      "abstract": [
        {
          "text": "Defines motion errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMError"
        }
      ],
      "role": "symbol",
      "title": "CMError",
      "type": "topic",
      "url": "/documentation/coremotion/cmerror"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorDeviceRequiresMovement": {
      "abstract": [
        {
          "text": "The device must move for a sampling of motion data to occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorDeviceRequiresMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorDeviceRequiresMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorDeviceRequiresMovement"
        }
      ],
      "role": "symbol",
      "title": "CMErrorDeviceRequiresMovement",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrordevicerequiresmovement"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorInvalidAction": {
      "abstract": [
        {
          "text": "The specified action is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorInvalidAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorInvalidAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorInvalidAction"
        }
      ],
      "role": "symbol",
      "title": "CMErrorInvalidAction",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrorinvalidaction"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorInvalidParameter": {
      "abstract": [
        {
          "text": "The specified parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorInvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorInvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "CMErrorInvalidParameter",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrorinvalidparameter"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotAuthorized": {
      "abstract": [
        {
          "text": "The app isn’t currently authorized to use motion activity support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorMotionActivityNotAuthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorMotionActivityNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "CMErrorMotionActivityNotAuthorized",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrormotionactivitynotauthorized"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotAvailable": {
      "abstract": [
        {
          "text": "Motion activity support isn’t available on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorMotionActivityNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorMotionActivityNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "CMErrorMotionActivityNotAvailable",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrormotionactivitynotavailable"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotEntitled": {
      "abstract": [
        {
          "text": "The app is missing an entitlement for the requested activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorMotionActivityNotEntitled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotEntitled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorMotionActivityNotEntitled"
        }
      ],
      "role": "symbol",
      "title": "CMErrorMotionActivityNotEntitled",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrormotionactivitynotentitled"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNULL": {
      "abstract": [
        {
          "text": "No error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorNULL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNULL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorNULL"
        }
      ],
      "role": "symbol",
      "title": "CMErrorNULL",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrornull"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNilData": {
      "abstract": [
        {
          "text": "Core Motion didn’t return any data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorNilData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNilData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorNilData"
        }
      ],
      "role": "symbol",
      "title": "CMErrorNilData",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrornildata"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotAuthorized": {
      "abstract": [
        {
          "text": "The app isn’t authorized to use the Core Motion framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorNotAuthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "CMErrorNotAuthorized",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrornotauthorized"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotAvailable": {
      "abstract": [
        {
          "text": "The requested service isn’t available on this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "CMErrorNotAvailable",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrornotavailable"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotEntitled": {
      "abstract": [
        {
          "text": "The app is missing a required entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorNotEntitled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotEntitled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorNotEntitled"
        }
      ],
      "role": "symbol",
      "title": "CMErrorNotEntitled",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrornotentitled"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorSize": {
      "abstract": [
        {
          "text": "The data is the incorrect size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorSize"
        }
      ],
      "role": "symbol",
      "title": "CMErrorSize",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrorsize"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorTrueNorthNotAvailable": {
      "abstract": [
        {
          "text": "True north isn’t available on this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorTrueNorthNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorTrueNorthNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorTrueNorthNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "CMErrorTrueNorthNotAvailable",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrortruenorthnotavailable"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorUnknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@CMError",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CMErrorUnknown",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrorunknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorDeviceRequiresMovement",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorInvalidAction",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorInvalidParameter",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotAuthorized",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotAvailable",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotEntitled",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNilData",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNULL",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotAuthorized",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotAvailable",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotEntitled",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorSize",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorTrueNorthNotAvailable"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMError"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorDeviceRequiresMovement",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorInvalidAction",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorInvalidParameter",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotAuthorized",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotAvailable",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorMotionActivityNotEntitled",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNilData",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNULL",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotAuthorized",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotAvailable",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorNotEntitled",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorSize",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorTrueNorthNotAvailable"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CMErrorUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNotEntitled/title",
          "value": "CMErrorNotEntitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNotEntitled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorNotEntitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorDeviceRequiresMovement/title",
          "value": "CMErrorDeviceRequiresMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorDeviceRequiresMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorDeviceRequiresMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorMotionActivityNotEntitled/title",
          "value": "CMErrorMotionActivityNotEntitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorMotionActivityNotEntitled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorMotionActivityNotEntitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNilData/title",
          "value": "CMErrorNilData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNilData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorNilData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorMotionActivityNotAuthorized/title",
          "value": "CMErrorMotionActivityNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorMotionActivityNotAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorMotionActivityNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorSize/title",
          "value": "CMErrorSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorMotionActivityNotAvailable/title",
          "value": "CMErrorMotionActivityNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorMotionActivityNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorMotionActivityNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorInvalidAction/title",
          "value": "CMErrorInvalidAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorInvalidAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorInvalidAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorTrueNorthNotAvailable/title",
          "value": "CMErrorTrueNorthNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorTrueNorthNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorTrueNorthNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorUnknown/title",
          "value": "CMErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNULL/title",
          "value": "CMErrorNULL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNULL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorNULL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNotAuthorized/title",
          "value": "CMErrorNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNotAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorInvalidParameter/title",
          "value": "CMErrorInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorInvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMError/title",
          "value": "CMError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNotAvailable/title",
          "value": "CMErrorNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorNotAvailable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmerrorunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmerrorunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
