{
  "abstract": [
    {
      "text": "A delegate that receives information about fall detection events and authorization status changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CMFallDetectionDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMFallDetectionDelegate"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMFallDetectionDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CMFallDetectionDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMFallDetectionDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate": {
      "abstract": [
        {
          "text": "A delegate that receives information about fall detection events and authorization status changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFallDetectionDelegate"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFallDetectionDelegate"
        }
      ],
      "role": "symbol",
      "title": "CMFallDetectionDelegate",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectiondelegate"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate/fallDetectionManager(_:didDetect:completionHandler:)": {
      "abstract": [
        {
          "text": "Indicates a fall detection event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fallDetectionManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMFallDetectionManager",
          "text": "CMFallDetectionManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDetect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMFallDetectionEvent",
          "text": "CMFallDetectionEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate/fallDetectionManager(_:didDetect:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fallDetectionManager:didDetectEvent:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "fallDetectionManager(_:didDetect:completionHandler:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectiondelegate/falldetectionmanager(_:diddetect:completionhandler:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate/fallDetectionManagerDidChangeAuthorization(_:)": {
      "abstract": [
        {
          "text": "Indicates the fall detection authorization status changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fallDetectionManagerDidChangeAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMFallDetectionManager",
          "text": "CMFallDetectionManager"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate/fallDetectionManagerDidChangeAuthorization(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fallDetectionManagerDidChangeAuthorization:"
        }
      ],
      "role": "symbol",
      "title": "fallDetectionManagerDidChangeAuthorization(_:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectiondelegate/falldetectionmanagerdidchangeauthorization(_:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent": {
      "abstract": [
        {
          "text": "An object that contains data about a fall detection event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFallDetectionEvent"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFallDetectionEvent"
        }
      ],
      "role": "symbol",
      "title": "CMFallDetectionEvent",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionevent"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionManager": {
      "abstract": [
        {
          "text": "An object for managing fall detection events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFallDetectionManager"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFallDetectionManager"
        }
      ],
      "role": "symbol",
      "title": "CMFallDetectionManager",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionmanager"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSFallDetectionUsageDescription": {
      "abstract": [
        {
          "text": "A message to the user that explains the app’s request for permission to access fall detection event data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSFallDetectionUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFallDetectionUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSFallDetectionUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fall-detection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionManager",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSFallDetectionUsageDescription"
      ],
      "title": "Fall detection"
    }
  ],
  "topicSections": [
    {
      "anchor": "Detecting-Falls",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate/fallDetectionManager(_:didDetect:completionHandler:)"
      ],
      "title": "Detecting Falls"
    },
    {
      "anchor": "Detecting-Authorization-Changes",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate/fallDetectionManagerDidChangeAuthorization(_:)"
      ],
      "title": "Detecting Authorization Changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMFallDetectionDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Detecting-Falls",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate/fallDetectionManager(_:didDetect:completionHandler:)"
              ],
              "title": "Detecting Falls"
            },
            {
              "anchor": "Detecting-Authorization-Changes",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionDelegate/fallDetectionManagerDidChangeAuthorization(_:)"
              ],
              "title": "Detecting Authorization Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Fall-detection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionManager",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSFallDetectionUsageDescription"
              ],
              "title": "Fall detection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMFallDetectionDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionDelegate/title",
          "value": "CMFallDetectionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionDelegate~1fallDetectionManagerDidChangeAuthorization(_:)/title",
          "value": "fallDetectionManagerDidChangeAuthorization:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionDelegate~1fallDetectionManagerDidChangeAuthorization(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fallDetectionManagerDidChangeAuthorization:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionManager/title",
          "value": "CMFallDetectionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent/title",
          "value": "CMFallDetectionEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionDelegate~1fallDetectionManager(_:didDetect:completionHandler:)/title",
          "value": "fallDetectionManager:didDetectEvent:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionDelegate~1fallDetectionManager(_:didDetect:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fallDetectionManager:didDetectEvent:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmfalldetectiondelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmfalldetectiondelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
