{
  "abstract": [
    {
      "text": "The type of block callback for handling gyroscope data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMGyroHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMGyroHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMGyroHandler"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMGyroHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMGyroHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMGyroHandler"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMGyroData",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMGyroData",
              "text": "CMGyroData"
            },
            {
              "kind": "text",
              "text": "?, (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Blocks of type ",
              "type": "text"
            },
            {
              "code": "CMGyroHandler",
              "type": "codeVoice"
            },
            {
              "text": " are called when there is gyroscope data to process. You pass the block into ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startGyroUpdates(to:withHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " as the second argument. Blocks of this type return no value but take two arguments:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object that encapsulates a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMRotationRate",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " structure with fields holding rotation-rate values for the three axes of movement.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "gyroData",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An error object representing an error encountered in providing gyroscope data. If an error occurs, you should stop gyroscope updates and inform the user of the problem. If there is no error, this argument is ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". Core Motion errors are of the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorDomain",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " domain and the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMError",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " type.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "error",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMError": {
      "abstract": [
        {
          "text": "Defines motion errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMError"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMError"
        }
      ],
      "role": "symbol",
      "title": "CMError",
      "type": "topic",
      "url": "/documentation/coremotion/cmerror"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for Core Motion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CMErrorDomain",
      "type": "topic",
      "url": "/documentation/coremotion/cmerrordomain"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMGyroData": {
      "abstract": [
        {
          "text": "A single measurement of the device’s rotation rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMGyroData"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMGyroData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMGyroData"
        }
      ],
      "role": "symbol",
      "title": "CMGyroData",
      "type": "topic",
      "url": "/documentation/coremotion/cmgyrodata"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMGyroHandler": {
      "abstract": [
        {
          "text": "The type of block callback for handling gyroscope data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMGyroHandler"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMGyroHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMGyroHandler"
        }
      ],
      "role": "symbol",
      "title": "CMGyroHandler",
      "type": "topic",
      "url": "/documentation/coremotion/cmgyrohandler"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/gyroData": {
      "abstract": [
        {
          "text": "The latest sample of gyroscope data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gyroData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMGyroData",
          "text": "CMGyroData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/gyroData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gyroData"
        }
      ],
      "role": "symbol",
      "title": "gyroData",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/gyrodata"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/gyroUpdateInterval": {
      "abstract": [
        {
          "text": "The interval, in seconds, for providing gyroscope updates to the block handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gyroUpdateInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/gyroUpdateInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gyroUpdateInterval"
        }
      ],
      "role": "symbol",
      "title": "gyroUpdateInterval",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/gyroupdateinterval"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startGyroUpdates()": {
      "abstract": [
        {
          "text": "Starts gyroscope updates without a handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startGyroUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startGyroUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startGyroUpdates"
        }
      ],
      "role": "symbol",
      "title": "startGyroUpdates()",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/startgyroupdates()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startGyroUpdates(to:withHandler:)": {
      "abstract": [
        {
          "text": "Starts gyroscope updates on an operation queue and with a specified handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startGyroUpdates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOperationQueue",
          "text": "OperationQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMGyroHandler",
          "text": "CMGyroHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startGyroUpdates(to:withHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startGyroUpdatesToQueue:withHandler:"
        }
      ],
      "role": "symbol",
      "title": "startGyroUpdates(to:withHandler:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/startgyroupdates(to:withhandler:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopGyroUpdates()": {
      "abstract": [
        {
          "text": "Stops gyroscope updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopGyroUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopGyroUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopGyroUpdates"
        }
      ],
      "role": "symbol",
      "title": "stopGyroUpdates()",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/stopgyroupdates()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMRotationRate": {
      "abstract": [
        {
          "text": "The type of structures representing a measurement of rotation rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMRotationRate"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMRotationRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMRotationRate"
        }
      ],
      "role": "symbol",
      "title": "CMRotationRate",
      "type": "topic",
      "url": "/documentation/coremotion/cmrotationrate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Gyroscope-Updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/gyroUpdateInterval",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startGyroUpdates(to:withHandler:)",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startGyroUpdates()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopGyroUpdates()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/gyroData"
      ],
      "title": "Managing Gyroscope Updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMGyroHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMGyroHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMGyroHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Gyroscope-Updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/gyroUpdateInterval",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startGyroUpdates(to:withHandler:)",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startGyroUpdates()",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopGyroUpdates()",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/gyroData"
              ],
              "title": "Managing Gyroscope Updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*$objc(cs)CMGyroData#*$objc(cs)NSError)",
                    "text": "void (^)(CMGyroData *, NSError *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMGyroHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startGyroUpdates()/title",
          "value": "startGyroUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startGyroUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startGyroUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMGyroData/title",
          "value": "CMGyroData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMGyroData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMGyroData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMGyroData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMGyroData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMRotationRate/title",
          "value": "CMRotationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMRotationRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMRotationRate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMGyroHandler/title",
          "value": "CMGyroHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMGyroHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMGyroHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMGyroHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMGyroHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1gyroData/title",
          "value": "gyroData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1gyroData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gyroData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startGyroUpdates(to:withHandler:)/title",
          "value": "startGyroUpdatesToQueue:withHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startGyroUpdates(to:withHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startGyroUpdatesToQueue:withHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1gyroUpdateInterval/title",
          "value": "gyroUpdateInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1gyroUpdateInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gyroUpdateInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1stopGyroUpdates()/title",
          "value": "stopGyroUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1stopGyroUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopGyroUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorDomain/title",
          "value": "CMErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMError/title",
          "value": "CMError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmgyrohandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmgyrohandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
