{
  "abstract": [
    {
      "text": "Indicates the calibration accuracy of a magnetic field estimate",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CMMagneticFieldCalibrationAccuracy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMMagneticFieldCalibrationAccuracy"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMMagneticFieldCalibrationAccuracy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CMMagneticFieldCalibrationAccuracy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracy"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "One of the ",
              "type": "text"
            },
            {
              "code": "enum",
              "type": "codeVoice"
            },
            {
              "text": " constants of the ",
              "type": "text"
            },
            {
              "code": "CMMagneticFieldCalibrationAccuracy",
              "type": "codeVoice"
            },
            {
              "text": " type is the value of the accuracy field of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure returned from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotion/magneticField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField": {
      "abstract": [
        {
          "text": "Calibrated magnetic field data and an estimate of the accuracy of the calibration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMCalibratedMagneticField"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMCalibratedMagneticField"
        }
      ],
      "role": "symbol",
      "title": "CMCalibratedMagneticField",
      "type": "topic",
      "url": "/documentation/coremotion/cmcalibratedmagneticfield"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotion/magneticField": {
      "abstract": [
        {
          "text": "Returns the magnetic field vector with respect to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magneticField"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMCalibratedMagneticField",
          "text": "CMCalibratedMagneticField"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotion/magneticField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magneticField"
        }
      ],
      "role": "symbol",
      "title": "magneticField",
      "type": "topic",
      "url": "/documentation/coremotion/cmdevicemotion/magneticfield"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy": {
      "abstract": [
        {
          "text": "Indicates the calibration accuracy of a magnetic field estimate",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracy"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/high": {
      "abstract": [
        {
          "text": "The accuracy of the magnetic field calibration is high.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracyHigh"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy.high",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/high"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/init(rawvalue:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/low": {
      "abstract": [
        {
          "text": "The accuracy of the magnetic field calibration is low.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracyLow"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy.low",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/low"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/medium": {
      "abstract": [
        {
          "text": "The accuracy of the magnetic field calibration is medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracyMedium"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy.medium",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/medium"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/uncalibrated": {
      "abstract": [
        {
          "text": "The magnetic field estimate is not calibrated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uncalibrated"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/uncalibrated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracyUncalibrated"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy.uncalibrated",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/uncalibrated"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Calibrated-Magnetic-Field",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotion/magneticField",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField"
      ],
      "title": "Getting the Calibrated Magnetic Field"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/uncalibrated",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/low",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/medium",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/high"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMMagneticFieldCalibrationAccuracy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/uncalibrated",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/low",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/medium",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/high"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Calibrated-Magnetic-Field",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotion/magneticField",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMCalibratedMagneticField"
              ],
              "title": "Getting the Calibrated Magnetic Field"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMMagneticFieldCalibrationAccuracy"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1low/title",
          "value": "CMMagneticFieldCalibrationAccuracyLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracyLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1medium/title",
          "value": "CMMagneticFieldCalibrationAccuracyMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracyMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1uncalibrated/title",
          "value": "CMMagneticFieldCalibrationAccuracyUncalibrated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1uncalibrated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracyUncalibrated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDeviceMotion~1magneticField/title",
          "value": "magneticField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDeviceMotion~1magneticField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magneticField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1high/title",
          "value": "CMMagneticFieldCalibrationAccuracyHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracyHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMCalibratedMagneticField/title",
          "value": "CMCalibratedMagneticField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMCalibratedMagneticField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMCalibratedMagneticField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMCalibratedMagneticField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMCalibratedMagneticField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy/title",
          "value": "CMMagneticFieldCalibrationAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
