{
  "abstract": [
    {
      "text": "A block that reports the motion updates that occurred between the specified query interval.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivityQueryHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMMotionActivityQueryHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMMotionActivityQueryHandler"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMMotionActivityQueryHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMMotionActivityQueryHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMMotionActivityQueryHandler"
            },
            {
              "kind": "text",
              "text": " = (["
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMMotionActivity",
              "text": "CMMotionActivity"
            },
            {
              "kind": "text",
              "text": "]?, (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This block takes the following parameters:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivity",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " objects indicating the updates that occurred. The objects in the array are ordered by the time at which they occurred in the specified time interval. Use the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivity/startDate",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property in each motion object to determine when the update occurred.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "activities",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An error object indicating that there was a problem gathering the data or ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if the motion data was determined correctly.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "error",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivity": {
      "abstract": [
        {
          "text": "The data for a single motion update event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMotionActivity"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMotionActivity"
        }
      ],
      "role": "symbol",
      "title": "CMMotionActivity",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionactivity"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivity/startDate": {
      "abstract": [
        {
          "text": "The time at which the change in motion occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivity/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionactivity/startdate"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivityManager/queryActivityStarting(from:to:to:withHandler:)": {
      "abstract": [
        {
          "text": "Gathers and returns historical motion data for the specified time period",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryActivityStarting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOperationQueue",
          "text": "OperationQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMotionActivityQueryHandler",
          "text": "CMMotionActivityQueryHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivityManager/queryActivityStarting(from:to:to:withHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryActivityStartingFromDate:toDate:toQueue:withHandler:"
        }
      ],
      "role": "symbol",
      "title": "queryActivityStarting(from:to:to:withHandler:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionactivitymanager/queryactivitystarting(from:to:to:withhandler:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivityQueryHandler": {
      "abstract": [
        {
          "text": "A block that reports the motion updates that occurred between the specified query interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMotionActivityQueryHandler"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivityQueryHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMotionActivityQueryHandler"
        }
      ],
      "role": "symbol",
      "title": "CMMotionActivityQueryHandler",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionactivityqueryhandler"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Historical-Activity-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivityManager/queryActivityStarting(from:to:to:withHandler:)"
      ],
      "title": "Getting Historical Activity Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMMotionActivityQueryHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionActivityQueryHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionActivityQueryHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Historical-Activity-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionActivityManager/queryActivityStarting(from:to:to:withHandler:)"
              ],
              "title": "Getting Historical Activity Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)",
                    "text": "void (^)(NSArray<CMMotionActivity *> *, NSError *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMMotionActivityQueryHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivityQueryHandler/title",
          "value": "CMMotionActivityQueryHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivityQueryHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionActivityQueryHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivityQueryHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionActivityQueryHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivity/title",
          "value": "CMMotionActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivityManager~1queryActivityStarting(from:to:to:withHandler:)/title",
          "value": "queryActivityStartingFromDate:toDate:toQueue:withHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivityManager~1queryActivityStarting(from:to:to:withHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "queryActivityStartingFromDate:toDate:toQueue:withHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivity~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionActivity~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmmotionactivityqueryhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmmotionactivityqueryhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
