{
  "abstract": [
    {
      "text": "A class that represents odometer data for workouts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMOdometerData",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMOdometerData"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMOdometerData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CMOdometerData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMOdometerData"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To get the measurements, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/speed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/slope-96hlt",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. To compute distances, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaDistance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaAltitude",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateData": {
      "abstract": [
        {
          "text": "A class that represents heart rate data collected at 1 Hz.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMHighFrequencyHeartRateData"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMHighFrequencyHeartRateData"
        }
      ],
      "role": "symbol",
      "title": "CMHighFrequencyHeartRateData",
      "type": "topic",
      "url": "/documentation/coremotion/cmhighfrequencyheartratedata"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData": {
      "abstract": [
        {
          "text": "A class that represents odometer data for workouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMOdometerData"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMOdometerData"
        }
      ],
      "role": "symbol",
      "title": "CMOdometerData",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaAltitude": {
      "abstract": [
        {
          "text": "The change in altitude above mean sea level associated with the location, measured in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deltaAltitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaAltitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deltaAltitude"
        }
      ],
      "role": "symbol",
      "title": "deltaAltitude",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/deltaaltitude"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaDistance": {
      "abstract": [
        {
          "text": "The change in distance that the user travels since the last location, measured in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deltaDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deltaDistance"
        }
      ],
      "role": "symbol",
      "title": "deltaDistance",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/deltadistance"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaDistanceAccuracy": {
      "abstract": [
        {
          "text": "The accuracy of the change in distance value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deltaDistanceAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaDistanceAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deltaDistanceAccuracy"
        }
      ],
      "role": "symbol",
      "title": "deltaDistanceAccuracy",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/deltadistanceaccuracy"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/endDate": {
      "abstract": [
        {
          "text": "The time that the device stops recording the odometer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/endDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endDate"
        }
      ],
      "role": "symbol",
      "title": "endDate",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/enddate"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/gpsDate": {
      "abstract": [
        {
          "text": "The time of the GPS measurement associated with the location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gpsDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/gpsDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gpsDate"
        }
      ],
      "role": "symbol",
      "title": "gpsDate",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/gpsdate"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/maxAbsSlope-96ulr": {
      "abstract": [
        {
          "text": "The maximum absolute slope at the location toward all directions, measured in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "maxAbsSlope"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/maxAbsSlope-96ulr",
      "kind": "symbol",
      "role": "symbol",
      "title": "maxAbsSlope",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/maxabsslope-96ulr"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/maxAbsSlope-9mnfd": {
      "abstract": [
        {
          "text": "The maximum absolute slope at the location toward all directions, measured in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxAbsSlope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/maxAbsSlope-9mnfd",
      "kind": "symbol",
      "role": "symbol",
      "title": "maxAbsSlope",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/maxabsslope-9mnfd"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/originDevice": {
      "abstract": [
        {
          "text": "The device that measures the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "originDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMOdometerOriginDevice",
          "text": "CMOdometerOriginDevice"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/originDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "originDevice"
        }
      ],
      "role": "symbol",
      "title": "originDevice",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/origindevice"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/slope-96hlt": {
      "abstract": [
        {
          "text": "The slope at the location toward the direction of travel, measured in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "slope"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/slope-96hlt",
      "kind": "symbol",
      "role": "symbol",
      "title": "slope",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/slope-96hlt"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/slope-9h3m4": {
      "abstract": [
        {
          "text": "The slope at the location toward the direction of travel, measured in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/slope-9h3m4",
      "kind": "symbol",
      "role": "symbol",
      "title": "slope",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/slope-9h3m4"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/speed": {
      "abstract": [
        {
          "text": "The instantaneous velocity of the device, measured in meters per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationSpeed",
          "text": "CLLocationSpeed"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/speed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speed"
        }
      ],
      "role": "symbol",
      "title": "speed",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/speed"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/speedAccuracy": {
      "abstract": [
        {
          "text": "The accuracy of the speed value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speedAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationSpeedAccuracy",
          "text": "CLLocationSpeedAccuracy"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/speedAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speedAccuracy"
        }
      ],
      "role": "symbol",
      "title": "speedAccuracy",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/speedaccuracy"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/startDate": {
      "abstract": [
        {
          "text": "The time that the device starts recording the odometer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/startdate"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/verticalAccuracy": {
      "abstract": [
        {
          "text": "The validity of the altitude values and their estimated uncertainty, measured in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/verticalAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticalAccuracy"
        }
      ],
      "role": "symbol",
      "title": "verticalAccuracy",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerdata/verticalaccuracy"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice": {
      "abstract": [
        {
          "text": "The device that the odometer sample originates from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMOdometerOriginDevice"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMOdometerOriginDevice"
        }
      ],
      "role": "symbol",
      "title": "CMOdometerOriginDevice",
      "type": "topic",
      "url": "/documentation/coremotion/cmodometerorigindevice"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometer": {
      "abstract": [
        {
          "text": "An object for fetching the system-generated live walking data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPedometer"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPedometer"
        }
      ],
      "role": "symbol",
      "title": "CMPedometer",
      "type": "topic",
      "url": "/documentation/coremotion/cmpedometer"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometerData": {
      "abstract": [
        {
          "text": "Information about the distance traveled by a user on foot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPedometerData"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometerData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPedometerData"
        }
      ],
      "role": "symbol",
      "title": "CMPedometerData",
      "type": "topic",
      "url": "/documentation/coremotion/cmpedometerdata"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometerEvent": {
      "abstract": [
        {
          "text": "A change in the user’s pedestrian activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPedometerEvent"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometerEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPedometerEvent"
        }
      ],
      "role": "symbol",
      "title": "CMPedometerEvent",
      "type": "topic",
      "url": "/documentation/coremotion/cmpedometerevent"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMStepCounter": {
      "abstract": [
        {
          "text": "The number of steps the user has taken with the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStepCounter"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMStepCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStepCounter"
        }
      ],
      "role": "symbol",
      "title": "CMStepCounter",
      "type": "topic",
      "url": "/documentation/coremotion/cmstepcounter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pedometer-and-fitness",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometer",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometerData",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometerEvent",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMStepCounter",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateData"
      ],
      "title": "Pedometer and fitness"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-speed-and-slope",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/speed",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/slope-9h3m4",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/maxAbsSlope-9mnfd"
      ],
      "title": "Getting speed and slope"
    },
    {
      "anchor": "Getting-date-and-times",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/startDate",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/endDate",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/gpsDate"
      ],
      "title": "Getting date and times"
    },
    {
      "anchor": "Measuring-distances",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaDistance",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaAltitude"
      ],
      "title": "Measuring distances"
    },
    {
      "anchor": "Getting-the-location-accuracy",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/speedAccuracy",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/verticalAccuracy",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaDistanceAccuracy"
      ],
      "title": "Getting the location accuracy"
    },
    {
      "anchor": "Getting-the-device",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/originDevice",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice"
      ],
      "title": "Getting the device"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMOdometerData"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-speed-and-slope",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/speed",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/slope-96hlt",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/maxAbsSlope-96ulr"
              ],
              "title": "Getting speed and slope"
            },
            {
              "anchor": "Getting-date-and-times",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/startDate",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/endDate",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/gpsDate"
              ],
              "title": "Getting date and times"
            },
            {
              "anchor": "Measuring-distances",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaDistance",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaAltitude"
              ],
              "title": "Measuring distances"
            },
            {
              "anchor": "Getting-the-location-accuracy",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/speedAccuracy",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/verticalAccuracy",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/deltaDistanceAccuracy"
              ],
              "title": "Getting the location accuracy"
            },
            {
              "anchor": "Getting-the-device",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerData/originDevice",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMOdometerOriginDevice"
              ],
              "title": "Getting the device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Pedometer-and-fitness",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometer",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometerData",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMPedometerEvent",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMStepCounter",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateData"
              ],
              "title": "Pedometer and fitness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMOdometerData"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1speedAccuracy/title",
          "value": "speedAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1speedAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "speedAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData/title",
          "value": "CMOdometerData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerOriginDevice/title",
          "value": "CMOdometerOriginDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerOriginDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerOriginDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerOriginDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMOdometerOriginDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1gpsDate/title",
          "value": "gpsDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1gpsDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gpsDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1endDate/title",
          "value": "endDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1endDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1verticalAccuracy/title",
          "value": "verticalAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1verticalAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1deltaAltitude/title",
          "value": "deltaAltitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1deltaAltitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deltaAltitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMPedometerData/title",
          "value": "CMPedometerData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMPedometerData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPedometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMPedometerData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPedometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1deltaDistance/title",
          "value": "deltaDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1deltaDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deltaDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMPedometerEvent/title",
          "value": "CMPedometerEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMPedometerEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPedometerEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMPedometerEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPedometerEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1speed/title",
          "value": "speed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1speed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "speed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1originDevice/title",
          "value": "originDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1originDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "originDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1deltaDistanceAccuracy/title",
          "value": "deltaDistanceAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMOdometerData~1deltaDistanceAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deltaDistanceAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateData/title",
          "value": "CMHighFrequencyHeartRateData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMPedometer/title",
          "value": "CMPedometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMPedometer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPedometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMPedometer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPedometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMStepCounter/title",
          "value": "CMStepCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMStepCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStepCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMStepCounter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStepCounter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmodometerdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmodometerdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
