{
  "abstract": [
    {
      "text": "A delegate that receives updates about ambient pressure, water pressure, water temperature, and submersion events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CMWaterSubmersionManagerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMWaterSubmersionManagerDelegate"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMWaterSubmersionManagerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CMWaterSubmersionManagerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionManagerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.coremotion/documentation/CoreMotion/accessing-submersion-data"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system calls your delegate’s methods to provide updated data to your app. When the watch isn’t submerged, your app receives event, measurement, and error messages. However, the measurement updates include only surface pressure and submersion state data. After submersion, the measurement updates include depth and water pressure data. The watch also begins receiving water temperature updates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The system calls all the delegate’s methods on an anonymous background queue. Typically, you need to dispatch this data to the main queue or pass it to a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/MainActor",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object before updating the user interface.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The system sends measurement and temperature updates three times a second while the watch is submerged. When the watch is on the surface, the system provides updates at a slower rate, and may stop providing updates if the watch isn’t moving.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionEvent": {
      "abstract": [
        {
          "text": "An event indicating that the device’s submersion state has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionEvent"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionEvent"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionEvent",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionevent"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManager": {
      "abstract": [
        {
          "text": "An object for managing the collection of pressure and temperature data during submersion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionManager"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionManager"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionManager",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmanager"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate": {
      "abstract": [
        {
          "text": "A delegate that receives updates about ambient pressure, water pressure, water temperature, and submersion events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionManagerDelegate"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionManagerDelegate"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionManagerDelegate",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmanagerdelegate"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-18wua": {
      "abstract": [
        {
          "text": "Provides the delegate with updated water temperature data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMWaterSubmersionManager",
          "text": "CMWaterSubmersionManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMWaterTemperature",
          "text": "CMWaterTemperature"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-18wua",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manager:didUpdateTemperature:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "manager(_:didUpdate:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmanagerdelegate/manager(_:didupdate:)-18wua"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-6qux6": {
      "abstract": [
        {
          "text": "Tells the delegate when a water submersion event occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMWaterSubmersionManager",
          "text": "CMWaterSubmersionManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMWaterSubmersionEvent",
          "text": "CMWaterSubmersionEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-6qux6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manager:didUpdateEvent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "manager(_:didUpdate:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmanagerdelegate/manager(_:didupdate:)-6qux6"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-7nhjb": {
      "abstract": [
        {
          "text": "Provides the delegate with a new set of pressure and depth measurements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMWaterSubmersionManager",
          "text": "CMWaterSubmersionManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMWaterSubmersionMeasurement",
          "text": "CMWaterSubmersionMeasurement"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-7nhjb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manager:didUpdateMeasurement:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "manager(_:didUpdate:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmanagerdelegate/manager(_:didupdate:)-7nhjb"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:errorOccurred:)": {
      "abstract": [
        {
          "text": "Tells the delegate when an error occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMWaterSubmersionManager",
          "text": "CMWaterSubmersionManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "errorOccurred"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:errorOccurred:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manager:errorOccurred:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "manager(_:errorOccurred:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmanagerdelegate/manager(_:erroroccurred:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement": {
      "abstract": [
        {
          "text": "An update that contains data about the pressure and depth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionMeasurement"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionMeasurement"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterTemperature": {
      "abstract": [
        {
          "text": "An update that contains data about the water temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMWaterTemperature"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterTemperature"
        }
      ],
      "role": "symbol",
      "title": "CMWaterTemperature",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatertemperature"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/accessing-submersion-data": {
      "abstract": [
        {
          "text": "Use a water-submersion manager to receive water pressure, temperature, and depth data on Apple Watch Ultra.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/accessing-submersion-data",
      "kind": "article",
      "role": "article",
      "title": "Accessing submersion data",
      "type": "topic",
      "url": "/documentation/coremotion/accessing-submersion-data"
    },
    "doc://com.apple.documentation/documentation/Swift/MainActor": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/MainActor",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Water-submersion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/accessing-submersion-data",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManager",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionEvent",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterTemperature"
      ],
      "title": "Water submersion"
    }
  ],
  "topicSections": [
    {
      "anchor": "Receiving-updates",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-6qux6",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-7nhjb",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-18wua",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:errorOccurred:)"
      ],
      "title": "Receiving updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMWaterSubmersionManagerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Receiving-updates",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-6qux6",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-7nhjb",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:didUpdate:)-18wua",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManagerDelegate/manager(_:errorOccurred:)"
              ],
              "title": "Receiving updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Water-submersion",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/accessing-submersion-data",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionManager",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionEvent",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterTemperature"
              ],
              "title": "Water submersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMWaterSubmersionManagerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterTemperature/title",
          "value": "CMWaterTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterTemperature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate~1manager(_:didUpdate:)-6qux6/title",
          "value": "manager:didUpdateEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate~1manager(_:didUpdate:)-6qux6/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "manager:didUpdateEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate~1manager(_:errorOccurred:)/title",
          "value": "manager:errorOccurred:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate~1manager(_:errorOccurred:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "manager:errorOccurred:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManager/title",
          "value": "CMWaterSubmersionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement/title",
          "value": "CMWaterSubmersionMeasurement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate/title",
          "value": "CMWaterSubmersionManagerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionEvent/title",
          "value": "CMWaterSubmersionEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate~1manager(_:didUpdate:)-7nhjb/title",
          "value": "manager:didUpdateMeasurement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate~1manager(_:didUpdate:)-7nhjb/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "manager:didUpdateMeasurement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate~1manager(_:didUpdate:)-18wua/title",
          "value": "manager:didUpdateTemperature:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionManagerDelegate~1manager(_:didUpdate:)-18wua/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "manager:didUpdateTemperature:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmwatersubmersionmanagerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmwatersubmersionmanagerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
