{
  "abstract": [
    {
      "text": "Retrieve data from the Apple Watch’s movement disorder manager.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/getting-movement-disorder-symptom-data"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Getting movement disorder symptom data"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class provides a power-efficient approach for you to continuously measure and record tremors and dyskinetic symptoms for Parkinson’s disease for your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Apple doesn’t market the movement disorder monitoring as a regulated medical device. Depending on how your app uses the API, you may need to meet additional regulatory obligations. Seek the relevant regulatory advice as needed for your app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "When you begin retrieving data from the movement disorder manager, Apple Watch starts to gather motion data. To preserve battery life, the manager doesn’t perform calculations in real time. Instead, it periodically and opportunistically analyzes the raw data, saving the results on the user’s device. To preserve disk space, the manager only keeps results for seven days. During this time, you can use the manager to query for the results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about the scientific validation and algorithms behind disorder detection and recording, see ",
              "type": "text"
            },
            {
              "identifier": "http://stm.sciencemag.org/cgi/content/full/13/579/eabd7865?ijkey=Md/cIhqXrFvws&keytype=ref&siteid=scitransmed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or download a PDF from ",
              "type": "text"
            },
            {
              "identifier": "https://stm.sciencemag.org/content/scitransmed/13/579/eabd7865.full.pdf?ijkey=Md/cIhqXrFvws&keytype=ref&siteid=scitransmed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Apps that use the ",
              "type": "text"
            },
            {
              "code": "CMMovementDisorderManager",
              "type": "codeVoice"
            },
            {
              "text": " must:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Confirm the user’s diagnosis of Parkinson’s disease.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Only report on symptoms diagnosed by a clinician or self-reported by the user.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Remind the user to wear Apple Watch on their most affected arm in order to collect the most useful data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To use the Movement Disorder API, your app must adhere to the Movement Disorder Program Requirements. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/adhering-to-the-movement-disorder-data-collection-requirements",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Additionally, your app must follow best practices for handling the user’s health data, as defined by the HealthKit guidelines. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/HealthKit/protecting-user-privacy",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To retrieve Parkinson’s tremors or dyskinetic symptoms data from a watchOS app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Provide a motion usage description in your WatchKit extension’s ",
                      "type": "text"
                    },
                    {
                      "code": "Info.plist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Instantiate a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Ensure that movement disorder monitoring is available on the current device.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Begin monitoring the user.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Query for tremors or dyskinetic symptoms.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Provide-the-motion-usage-description",
          "level": 3,
          "text": "Provide the motion usage description",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your watchOS app must provide an ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSMotionUsageDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key with a ",
              "type": "text"
            },
            {
              "code": "String",
              "type": "codeVoice"
            },
            {
              "text": " value in the WatchKit extension’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file. The system displays the motion usage description whenever it asks a user for permission to record their data. The description string appears in the Motion and Fitness authorization prompt.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "At a minimum, your description must contain the following text: “In addition, this app would like to access your tremor and dyskinetic symptom data. This is only intended for use in those already diagnosed with Parkinson’s disease.”",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can include additional information explaining why the user should grant your app permission, and what your app intends to do with the data after this text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Monitor-and-query-for-results",
          "level": 3,
          "text": "Monitor and query for results",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following example shows how to set up your movement disorder manager, and begin monitoring the user’s symptoms:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Check to see if the movement disorder manager is available.",
            "guard CMMovementDisorderManager.isAvailable() else {",
            "    // The movement disorder manager is not availble on this device.",
            "    return",
            "}",
            "",
            "// Instantiate the Movement Disorder Manager",
            "movementDisorderManager = CMMovementDisorderManager()",
            "",
            "// Start monitoring the user. The maximum duration is seven days.",
            "movementDisorderManager.monitorKinesias(forDuration: 60.0 * 60.0 * 24.0 * 7.0)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After you start monitoring, the manager leverages the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to record high-rate accelerometer data passively. When enabled, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " records 100 Hz samples. The movement disorder algorithms then periodically and opportunistically use this data to calculate tremors and dyskinetic symptoms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The movement disorder manager stores the results of these calculations on the device for seven days. To access the results, use the manager to query for the desired results, as shown in this example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Get the end date for the last batch of results.",
            "guard let endDate = movementDisorderManager.lastProcessedDate() else {",
            "    // The manager has not processed any results yet.",
            "    return",
            "}",
            "",
            "// Get the last batch of tremor results.",
            "movementDisorderManager.queryTremor(from: previousDate, to: endDate) { (tremorResults, error) in",
            "    ",
            "    // Check for errors.",
            "    if let error = error {",
            "        // Handle the error here.",
            "        print(\"*** An error occurred: \\(error.localizedDescription) ***\")",
            "        return",
            "    }",
            "    ",
            "    // Do something with the tremor results here.",
            "}",
            "",
            "// Get the last batch of dyskinetic symptom results.",
            "movementDisorderManager.queryDyskineticSymptom(from: previousDate, to: endDate) { (dyskineticSymptomResults, error) in",
            "    ",
            "    // Check for errors.",
            "    if let error = error {",
            "        // Handle the error here.",
            "        print(\"*** An error occurred: \\(error.localizedDescription) ***\")",
            "        return",
            "    }",
            "    ",
            "    // Do something with the dyskinetic symptom results here.",
            "}",
            "",
            "previousDate = endDate"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To extend the monitoring past the initial expiration date, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesias(forDuration:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method again.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Understand-the-managers-limitations",
          "level": 3,
          "text": "Understand the manager’s limitations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " measures resting tremors from Parkinson’s disease in the 3-7 Hz range. It returns metrics about the presence and relative severity of resting tremor as a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMTremorResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " also computes metrics about choreiform dyskinetic symptoms, measuring the likely presence or absence of dyskinetic symptoms as observed at the wrist where the user wears their Apple Watch. It returns the results as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMDyskineticSymptomResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " operates under the following constraints:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The user should wear Apple Watch on the most affected arm.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Employ dyskinetic symptom tracking only for users who have chorea on the affected arm, either self-reported or diagnosed by a clinician.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "There are many types of tremors. The movement disorder manager explicitly tracks resting tremor; it doesn’t track action tremor or postural tremor, and it may not track finger tremor.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The manager doesn’t explicitly track dystonia.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The results may include false positives and false negatives. The user’s activity, watch band fit, and concomitant conditions (such as restless legs syndrome and non-Parkinsonian tremor) can affect the quality of the results.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The manager only explicitly measures symptoms from the wrist wearing Apple Watch. However, Apple Watch may sense symptoms transmitted through the body from other affected body parts, possibly resulting in misleading or false metrics.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMDyskineticSymptomResult": {
      "abstract": [
        {
          "text": "A result object that contains data about the likely presence of dyskinetic symptoms during a one-minute interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMDyskineticSymptomResult"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMDyskineticSymptomResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMDyskineticSymptomResult"
        }
      ],
      "role": "symbol",
      "title": "CMDyskineticSymptomResult",
      "type": "topic",
      "url": "/documentation/coremotion/cmdyskineticsymptomresult"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager": {
      "abstract": [
        {
          "text": "A manager for recording and querying movement disorder data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMovementDisorderManager"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMovementDisorderManager"
        }
      ],
      "role": "symbol",
      "title": "CMMovementDisorderManager",
      "type": "topic",
      "url": "/documentation/coremotion/cmmovementdisordermanager"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesias(forDuration:)": {
      "abstract": [
        {
          "text": "Calculate and store tremor and dyskinetic symptom results for the duration of the specified time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monitorKinesias"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesias(forDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "monitorKinesiasForDuration:"
        }
      ],
      "role": "symbol",
      "title": "monitorKinesias(forDuration:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmovementdisordermanager/monitorkinesias(forduration:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder": {
      "abstract": [
        {
          "text": "An object that gathers and retrieves accelerometer data from a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSensorRecorder"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSensorRecorder"
        }
      ],
      "role": "symbol",
      "title": "CMSensorRecorder",
      "type": "topic",
      "url": "/documentation/coremotion/cmsensorrecorder"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMTremorResult": {
      "abstract": [
        {
          "text": "A result object that contains data about the presence and strength of tremors during a one-minute interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTremorResult"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMTremorResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTremorResult"
        }
      ],
      "role": "symbol",
      "title": "CMTremorResult",
      "type": "topic",
      "url": "/documentation/coremotion/cmtremorresult"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/adhering-to-the-movement-disorder-data-collection-requirements": {
      "abstract": [
        {
          "text": "Ensure that your users understand and have control over the data your app collects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/adhering-to-the-movement-disorder-data-collection-requirements",
      "kind": "article",
      "role": "article",
      "title": "Adhering to the movement disorder data collection requirements",
      "type": "topic",
      "url": "/documentation/coremotion/adhering-to-the-movement-disorder-data-collection-requirements"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/movement-disorder-algorithm-changelog": {
      "abstract": [
        {
          "text": "A chronological log of notable changes to the movement disorder algorithm.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/movement-disorder-algorithm-changelog",
      "kind": "article",
      "role": "article",
      "title": "Movement disorder algorithm changelog",
      "type": "topic",
      "url": "/documentation/coremotion/movement-disorder-algorithm-changelog"
    },
    "doc://com.apple.documentation/documentation/HealthKit/protecting-user-privacy": {
      "abstract": [
        {
          "text": "Respect and safeguard your user’s privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/protecting-user-privacy",
      "kind": "article",
      "role": "article",
      "title": "Protecting user privacy",
      "type": "topic",
      "url": "/documentation/HealthKit/protecting-user-privacy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "http://stm.sciencemag.org/cgi/content/full/13/579/eabd7865?ijkey=Md/cIhqXrFvws&keytype=ref&siteid=scitransmed": {
      "identifier": "http://stm.sciencemag.org/cgi/content/full/13/579/eabd7865?ijkey=Md/cIhqXrFvws&keytype=ref&siteid=scitransmed",
      "title": "Smartwatch inertial sensors continuously monitor real-world motor fluctuations in Parkinson’s disease",
      "titleInlineContent": [
        {
          "text": "Smartwatch inertial sensors continuously monitor real-world motor fluctuations in Parkinson’s disease",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://stm.sciencemag.org/cgi/content/full/13/579/eabd7865?ijkey=Md/cIhqXrFvws&keytype=ref&siteid=scitransmed"
    },
    "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSMotionUsageDescription": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSMotionUsageDescription",
      "title": "NSMotionUsageDescription",
      "titleInlineContent": [
        {
          "text": "NSMotionUsageDescription",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSMotionUsageDescription"
    },
    "https://stm.sciencemag.org/content/scitransmed/13/579/eabd7865.full.pdf?ijkey=Md/cIhqXrFvws&keytype=ref&siteid=scitransmed": {
      "identifier": "https://stm.sciencemag.org/content/scitransmed/13/579/eabd7865.full.pdf?ijkey=Md/cIhqXrFvws&keytype=ref&siteid=scitransmed",
      "title": "Science Translational Medicine Magazine",
      "titleInlineContent": [
        {
          "text": "Science Translational Medicine Magazine",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://stm.sciencemag.org/content/scitransmed/13/579/eabd7865.full.pdf?ijkey=Md/cIhqXrFvws&keytype=ref&siteid=scitransmed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Movement-disorder",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/adhering-to-the-movement-disorder-data-collection-requirements",
        "doc://com.apple.coremotion/documentation/CoreMotion/movement-disorder-algorithm-changelog",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMTremorResult",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMDyskineticSymptomResult"
      ],
      "title": "Movement disorder"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Movement-disorder",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/adhering-to-the-movement-disorder-data-collection-requirements",
                "doc://com.apple.coremotion/documentation/CoreMotion/movement-disorder-algorithm-changelog",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMTremorResult",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMDyskineticSymptomResult"
              ],
              "title": "Movement disorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDyskineticSymptomResult/title",
          "value": "CMDyskineticSymptomResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDyskineticSymptomResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMDyskineticSymptomResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDyskineticSymptomResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMDyskineticSymptomResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1monitorKinesias(forDuration:)/title",
          "value": "monitorKinesiasForDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1monitorKinesias(forDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "monitorKinesiasForDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMTremorResult/title",
          "value": "CMTremorResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMTremorResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTremorResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMTremorResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTremorResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder/title",
          "value": "CMSensorRecorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSensorRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSensorRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager/title",
          "value": "CMMovementDisorderManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMovementDisorderManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMovementDisorderManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/getting-movement-disorder-symptom-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/getting-movement-disorder-symptom-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
