{
  "abstract": [
    {
      "text": "A security type to represent use of Wi-Fi protected access (WPA), WPA2, and WPA3 standards using enterprise-level seciurity.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/enterprise"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEHotspotNetworkSecurityType@NEHotspotNetworkSecurityTypeEnterprise",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "enterprise"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEHotspotNetworkSecurityTypeEnterprise"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEHotspotNetworkSecurityType.enterprise"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "enterprise"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType": {
      "abstract": [
        {
          "text": "An enumeration of constants that define Wi-Fi hotspot network security types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityType"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/WEP": {
      "abstract": [
        {
          "text": "A security type to represent use of Wired Equivalent Privacy (WEP).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WEP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/WEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypeWEP"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.WEP",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/wep"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/enterprise": {
      "abstract": [
        {
          "text": "A security type to represent use of Wi-Fi protected access (WPA), WPA2, and WPA3 standards using enterprise-level seciurity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enterprise"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/enterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypeEnterprise"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.enterprise",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/enterprise"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/open": {
      "abstract": [
        {
          "text": "A security type to represent an open network with no security protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/open",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypeOpen"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.open",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/open"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/personal": {
      "abstract": [
        {
          "text": "A security type to represent use of Wi-Fi protected access (WPA), WPA2, and WPA3 standards using a pre-shared secret.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "personal"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/personal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypePersonal"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.personal",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/personal"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/unknown": {
      "abstract": [
        {
          "text": "A value that represents an unknown security type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotNetworkSecurityTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotNetworkSecurityType.unknown",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotnetworksecuritytype/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Security-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/open",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/WEP",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/personal",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/unknown"
      ],
      "title": "Security types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEHotspotNetworkSecurityTypeEnterprise"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypeEnterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Security-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/open",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/WEP",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/personal",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotNetworkSecurityType/unknown"
              ],
              "title": "Security types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEHotspotNetworkSecurityTypeEnterprise"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1open/title",
          "value": "NEHotspotNetworkSecurityTypeOpen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1open/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypeOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1WEP/title",
          "value": "NEHotspotNetworkSecurityTypeWEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1WEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypeWEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType/title",
          "value": "NEHotspotNetworkSecurityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1enterprise/title",
          "value": "NEHotspotNetworkSecurityTypeEnterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1enterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypeEnterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1personal/title",
          "value": "NEHotspotNetworkSecurityTypePersonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1personal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypePersonal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1unknown/title",
          "value": "NEHotspotNetworkSecurityTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotNetworkSecurityType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotNetworkSecurityTypeUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspotnetworksecuritytype/enterprise"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nehotspotnetworksecuritytype/enterprise"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
