{
  "abstract": [
    {
      "text": "The array of players associated with the session.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/players"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPNowPlayingSession(py)players",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "players"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVPlayer",
        "text": "AVPlayer"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "players"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "players"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "players"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AVPlayer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVPlayer",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession": {
      "abstract": [
        {
          "text": "An object that manages Now Playing information and remote commands for multiple players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingSession"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingSession"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingSession",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayingsession"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/addPlayer(_:)": {
      "abstract": [
        {
          "text": "Adds a player to the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPlayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayer",
          "text": "AVPlayer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/addPlayer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPlayer:"
        }
      ],
      "role": "symbol",
      "title": "addPlayer(_:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayingsession/addplayer(_:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/players": {
      "abstract": [
        {
          "text": "The array of players associated with the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "players"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayer",
          "text": "AVPlayer"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/players",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "players"
        }
      ],
      "role": "symbol",
      "title": "players",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayingsession/players"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/removePlayer(_:)": {
      "abstract": [
        {
          "text": "Removes a player from the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removePlayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayer",
          "text": "AVPlayer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/removePlayer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removePlayer:"
        }
      ],
      "role": "symbol",
      "title": "removePlayer(_:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayingsession/removeplayer(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AVPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-players",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/addPlayer(_:)",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/removePlayer(_:)"
      ],
      "title": "Managing players"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "players"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "players"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-players",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/addPlayer(_:)",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/removePlayer(_:)"
              ],
              "title": "Managing players"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<AVPlayer *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "players"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession~1players/title",
          "value": "players"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession~1players/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "players"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession/title",
          "value": "MPNowPlayingSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)AVPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession~1addPlayer(_:)/title",
          "value": "addPlayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession~1addPlayer(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPlayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession~1removePlayer(_:)/title",
          "value": "removePlayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession~1removePlayer(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removePlayer:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpnowplayingsession/players"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpnowplayingsession/players"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
