{
  "abstract": [
    {
      "text": "The remote command center associated with the session.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/remoteCommandCenter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPNowPlayingSession(py)remoteCommandCenter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "remoteCommandCenter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPRemoteCommandCenter",
        "text": "MPRemoteCommandCenter"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "remoteCommandCenter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "remoteCommandCenter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "remoteCommandCenter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPRemoteCommandCenter",
              "text": "MPRemoteCommandCenter"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession": {
      "abstract": [
        {
          "text": "An object that manages Now Playing information and remote commands for multiple players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingSession"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingSession"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingSession",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayingsession"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/remoteCommandCenter": {
      "abstract": [
        {
          "text": "The remote command center associated with the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteCommandCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPRemoteCommandCenter",
          "text": "MPRemoteCommandCenter"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession/remoteCommandCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remoteCommandCenter"
        }
      ],
      "role": "symbol",
      "title": "remoteCommandCenter",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayingsession/remotecommandcenter"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter": {
      "abstract": [
        {
          "text": "An object that responds to remote control events sent by external accessories and system controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRemoteCommandCenter"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandCenter"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandCenter",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandcenter"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "remoteCommandCenter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remoteCommandCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MPRemoteCommandCenter",
                    "text": "MPRemoteCommandCenter"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "remoteCommandCenter"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter/title",
          "value": "MPRemoteCommandCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession/title",
          "value": "MPNowPlayingSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession~1remoteCommandCenter/title",
          "value": "remoteCommandCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession~1remoteCommandCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remoteCommandCenter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpnowplayingsession/remotecommandcenter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpnowplayingsession/remotecommandcenter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
