{
  "abstract": [
    {
      "text": "Initializes a passkey credential request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ASPasskeyCredentialRequest(cm)requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "credentialIdentity"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialIdentity",
        "text": "ASPasskeyCredentialIdentity"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "clientDataHash"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DataV",
        "text": "Data"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "userVerificationPreference"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
        "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "supportedAlgorithms"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "credentialIdentity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialIdentity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialIdentity",
              "text": "ASPasskeyCredentialIdentity"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "clientDataHash"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "userVerificationPreference"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
              "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "supportedAlgorithms"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identity of the requested passkey credential.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "credentialIdentity"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Hash of the client data from the passkey authentication challenge.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "clientDataHash"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The relying party’s user verification preference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "userVerificationPreference"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of numbers that represent cryptographic signature algorithms the identifying party supports.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "supportedAlgorithms"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "supportedAlgorithms",
              "type": "codeVoice"
            },
            {
              "text": " parameter is empty for credential assertion requests. For credential registration requests, it contains one or more numbers from the Internet Assigned Numbers Authority (IANA) ",
              "type": "text"
            },
            {
              "identifier": "https://www.iana.org/assignments/cose/cose.xhtml#algorithms",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference": {
      "abstract": [
        {
          "text": "A structure that defines the relying party’s user verification preference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationPublicKeyCredentialUserVerificationPreference",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationpublickeycredentialuserverificationpreference"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialIdentity": {
      "abstract": [
        {
          "text": "A description that uniquely identifies a particular passkey credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPasskeyCredentialIdentity"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPasskeyCredentialIdentity"
        }
      ],
      "role": "symbol",
      "title": "ASPasskeyCredentialIdentity",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialidentity"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest": {
      "abstract": [
        {
          "text": "A class that represents a request to supply a passkey credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPasskeyCredentialRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPasskeyCredentialRequest"
        }
      ],
      "role": "symbol",
      "title": "ASPasskeyCredentialRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy": {
      "abstract": [
        {
          "text": "Initializes a passkey credential request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "credentialIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialIdentity",
          "text": "ASPasskeyCredentialIdentity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userVerificationPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
          "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supportedAlgorithms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
        }
      ],
      "role": "symbol",
      "title": "init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/init(credentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:)-1jihy"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-52txr": {
      "abstract": [
        {
          "text": "Initializes a passkey credential request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "credentialIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialIdentity",
          "text": "ASPasskeyCredentialIdentity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userVerificationPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
          "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supportedAlgorithms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASCOSEAlgorithmIdentifier",
          "text": "ASCOSEAlgorithmIdentifier"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-52txr",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/init(credentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:)-52txr"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:": {
      "abstract": [
        {
          "text": "Initializes a passkey credential request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
        }
      ],
      "role": "symbol",
      "title": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/initwithcredentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSData": {
      "abstract": [
        {
          "text": "A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSData",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSData",
      "type": "topic",
      "url": "/documentation/foundation/nsdata"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DataV": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    },
    "https://www.iana.org/assignments/cose/cose.xhtml#algorithms": {
      "identifier": "https://www.iana.org/assignments/cose/cose.xhtml#algorithms",
      "title": "Concise Binary Object Representation Object Signing and Encryption (COSE) algorithms registry",
      "titleInlineContent": [
        {
          "text": "Concise Binary Object Representation Object Signing and Encryption (COSE) algorithms registry",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.iana.org/assignments/cose/cose.xhtml#algorithms"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-passkey-credential-requests",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-52txr"
      ],
      "title": "Creating passkey credential requests"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-passkey-credential-requests",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
              ],
              "title": "Creating passkey credential requests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "requestWithCredentialIdentity:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialIdentity",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialIdentity",
                    "text": "ASPasskeyCredentialIdentity"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "credentialIdentity"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "clientDataHash:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSData",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSData",
                    "text": "NSData"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "clientDataHash"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "userVerificationPreference:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
                    "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "userVerificationPreference"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "supportedAlgorithms:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSNumber *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "supportedAlgorithms"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The identity of the requested passkey credential.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "credentialIdentity"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Hash of the client data from the passkey authentication challenge.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "clientDataHash"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The relying party’s user verification preference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "userVerificationPreference"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of numbers that represent cryptographic signature algorithms the identifying party supports.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "supportedAlgorithms"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSData/abstract",
          "value": [
            {
              "text": "A static byte buffer in memory.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest/title",
          "value": "ASPasskeyCredentialRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialIdentity/title",
          "value": "ASPasskeyCredentialIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy/title",
          "value": "requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialUserVerificationPreference/title",
          "value": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialUserVerificationPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialUserVerificationPreference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/aspasskeycredentialrequest/init(credentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:)-1jihy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/aspasskeycredentialrequest/init(credentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:)-1jihy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
