{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scannerDevice:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ICScannerDevice","text":"ICScannerDevice","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scanner"},{"kind":"text","text":" "},{"kind":"identifier","text":"didScanToURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"]}]},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"If the ","type":"text"},{"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit","type":"reference","isActive":true},{"text":" is a document feeder, then this message is sent once for each scanned page.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This method has been deprecated. Use "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-10whl"},{"type":"text","text":" for file-based transfer, or "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-6tht3"},{"type":"text","text":" for memory-based transfer."}],"type":"paragraph"}]}],"variants":[{"paths":["/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice:didscantourl:data:"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Tells the client when the scanner device receives the requested scan."}],"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice:didScanToURL:data:"},"metadata":{"modules":[{"name":"ImageCaptureCore"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)ICScannerDeviceDelegate(im)scannerDevice:didScanToURL:data:","platforms":[{"beta":false,"deprecatedAt":"10.7","introducedAt":"10.6","unavailable":false,"deprecated":false,"name":"macOS"}],"title":"scannerDevice:didScanToURL:data:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"scannerDevice:didScanToURL:data:","kind":"identifier"}],"navigatorTitle":[{"text":"scannerDevice:didScanToURL:data:","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFunctionalUnit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ICScannerFunctionalUnit","kind":"typeIdentifier","text":"ICScannerFunctionalUnit"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit","url":"/documentation/imagecapturecore/icscannerdevice/selectedfunctionalunit","abstract":[{"text":"The currently selected functional unit on the scanner.","type":"text"}],"title":"selectedFunctionalUnit","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedFunctionalUnit"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate":{"abstract":[{"type":"text","text":"Methods for determining availability, selecting a functional unit, and performing scans on connected scanners."}],"url":"/documentation/imagecapturecore/icscannerdevicedelegate","navigatorTitle":[{"kind":"identifier","text":"ICScannerDeviceDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ICScannerDeviceDelegate"}],"type":"topic","title":"ICScannerDeviceDelegate","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate","kind":"symbol","role":"symbol"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-10whl":{"type":"topic","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-10whl","navigatorTitle":[{"kind":"identifier","text":"scannerDevice:didScanToURL:"}],"url":"/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice(_:didscanto:)-10whl","role":"symbol","abstract":[{"type":"text","text":"Tells the client when the scanner receives the requested scan."}],"title":"scannerDevice(_:didScanTo:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannerDevice"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ICScannerDevice","text":"ICScannerDevice"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":")"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSURL":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","url":"/documentation/foundation/nsurl","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSURL"}],"role":"symbol","abstract":[{"text":"An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"kind":"symbol","title":"NSURL","type":"topic"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-6tht3":{"url":"/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice(_:didscanto:)-6tht3","title":"scannerDevice(_:didScanTo:)","type":"topic","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-6tht3","navigatorTitle":[{"kind":"identifier","text":"scannerDevice:didScanToBandData:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannerDevice"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ICScannerDevice","preciseIdentifier":"c:objc(cs)ICScannerDevice"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ICScannerBandData","text":"ICScannerBandData"},{"kind":"text","text":")"}],"abstract":[{"text":"Tells the client when the scanner receives the requested scan progress notification and a band of data is sent for each notification received.","type":"text"}],"role":"symbol"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice":{"title":"ICScannerDevice","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice","url":"/documentation/imagecapturecore/icscannerdevice","kind":"symbol","navigatorTitle":[{"text":"ICScannerDevice","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ICScannerDevice","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"An object that represents a scanner.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSData":{"fragments":[{"text":"class ","kind":"text"},{"text":"NSData","kind":"identifier"}],"type":"topic","role":"symbol","title":"NSData","url":"/documentation/foundation/nsdata","abstract":[{"type":"text","text":"A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior."}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData","kind":"symbol"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore":{"title":"ImageCaptureCore","role":"collection","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","abstract":[{"text":"Browse for media devices and control them programmatically from your app.","type":"text"}],"type":"topic","url":"/documentation/imagecapturecore"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice:didScanToURL:data:":{"role":"symbol","title":"scannerDevice:didScanToURL:data:","kind":"symbol","abstract":[{"type":"text","text":"Tells the client when the scanner device receives the requested scan."}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice:didScanToURL:data:","url":"/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice:didscantourl:data:","navigatorTitle":[{"kind":"identifier","text":"scannerDevice:didScanToURL:data:"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scannerDevice:didScanToURL:data:"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","title":"Technologies","abstract":[{"text":"","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1selectedFunctionalUnit/title","value":"selectedFunctionalUnit","op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1selectedFunctionalUnit/fragments","value":[{"kind":"identifier","text":"selectedFunctionalUnit"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/title","value":"ICScannerDeviceDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/fragments","value":[{"text":"ICScannerDeviceDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/navigatorTitle","value":[{"text":"ICScannerDeviceDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didScanTo:)-10whl/title","value":"scannerDevice:didScanToURL:","op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didScanTo:)-10whl/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scannerDevice:didScanToURL:"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract","value":[{"type":"text","text":"An object that represents the location of a resource, such as an item on a remote server or the path to a local file. "}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didScanTo:)-6tht3/title","value":"scannerDevice:didScanToBandData:","op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didScanTo:)-6tht3/fragments","value":[{"text":"- ","kind":"text"},{"text":"scannerDevice:didScanToBandData:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/title","value":"ICScannerDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/fragments","value":[{"text":"ICScannerDevice","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/navigatorTitle","value":[{"text":"ICScannerDevice","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSData/abstract","value":[{"text":"A static byte buffer in memory.","type":"text"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}