{
  "abstract": [
    {
      "text": "Returns a Boolean value that indicates whether the current device supports device discovery.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI",
        "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI/DDDevicePickerViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI/DDDevicePickerViewController/isSupportedForBrowseDescriptor:parameters:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DDDevicePickerViewController(cm)isSupportedForBrowseDescriptor:parameters:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "isSupportedForBrowseDescriptor:parameters:"
      }
    ],
    "modules": [
      {
        "name": "DeviceDiscoveryUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "isSupportedForBrowseDescriptor:parameters:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "isSupportedForBrowseDescriptor:parameters:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "isSupportedForBrowseDescriptor:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@nw_browse_descriptor_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
              "text": "nw_browse_descriptor_t"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "browseDescriptor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parameters:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@nw_parameters_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_parameters_t",
              "text": "nw_parameters_t"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "parameters"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A descriptor for your application service. To create an application service descriptor, call ",
                  "type": "text"
                },
                {
                  "code": "NWBrowser.Descriptor.applicationService(name:options:)",
                  "type": "codeVoice"
                },
                {
                  "text": " and provide a name for the service.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "browseDescriptor"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Parameters for your network connection. Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Network/NWParameters/applicationService",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to create a default set of parameters that create an encrypted connection with the other devices. You can also add ",
                  "type": "text"
                },
                {
                  "code": "a",
                  "type": "codeVoice"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Network/NWProtocolFramer",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to provide an application-level messaging protocol.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "parameters"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI": {
      "abstract": [
        {
          "text": "Display an interface that lets users connect a tvOS app to a mobile device over the local network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI",
      "kind": "symbol",
      "role": "collection",
      "title": "DeviceDiscoveryUI",
      "type": "topic",
      "url": "/documentation/devicediscoveryui"
    },
    "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI/DDDevicePickerViewController": {
      "abstract": [
        {
          "text": "A UIKit view that displays other devices on the network, and creates an encrypted connection to a copy of your app running on that device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDDevicePickerViewController"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI/DDDevicePickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDevicePickerViewController"
        }
      ],
      "role": "symbol",
      "title": "DDDevicePickerViewController",
      "type": "topic",
      "url": "/documentation/devicediscoveryui/dddevicepickerviewcontroller"
    },
    "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI/DDDevicePickerViewController/initWithBrowseDescriptor:parameters:": {
      "abstract": [
        {
          "text": "Creates a view controller that displays the other, available devices on your local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithBrowseDescriptor:parameters:"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI/DDDevicePickerViewController/initWithBrowseDescriptor:parameters:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBrowseDescriptor:parameters:"
        }
      ],
      "role": "symbol",
      "title": "initWithBrowseDescriptor:parameters:",
      "type": "topic",
      "url": "/documentation/devicediscoveryui/dddevicepickerviewcontroller/initwithbrowsedescriptor:parameters:"
    },
    "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI/DDDevicePickerViewController/isSupportedForBrowseDescriptor:parameters:": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the current device supports device discovery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "isSupportedForBrowseDescriptor:parameters:"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI/DDDevicePickerViewController/isSupportedForBrowseDescriptor:parameters:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isSupportedForBrowseDescriptor:parameters:"
        }
      ],
      "role": "symbol",
      "title": "isSupportedForBrowseDescriptor:parameters:",
      "type": "topic",
      "url": "/documentation/devicediscoveryui/dddevicepickerviewcontroller/issupportedforbrowsedescriptor:parameters:"
    },
    "doc://com.apple.documentation/documentation/Network/NWParameters/applicationService": {
      "abstract": [
        {
          "text": "The default parameters for connecting with other, local devices that are running your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Network12NWParametersC",
          "text": "NWParameters"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network/NWParameters/applicationService",
      "kind": "symbol",
      "role": "symbol",
      "title": "applicationService",
      "type": "topic",
      "url": "/documentation/Network/NWParameters/applicationService"
    },
    "doc://com.apple.documentation/documentation/Network/NWProtocolFramer": {
      "abstract": [
        {
          "text": "A customizable network protocol for defining application message parsers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWProtocolFramer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network/NWProtocolFramer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NWProtocolFramer",
      "type": "topic",
      "url": "/documentation/Network/NWProtocolFramer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:@T@nw_browse_descriptor_t": {
      "abstract": [
        {
          "text": "A service description used to discover Bonjour services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": " = any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_nw_browse_descriptor",
          "text": "OS_nw_browse_descriptor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@nw_browse_descriptor_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "nw_browse_descriptor_t",
      "type": "topic",
      "url": "/documentation/Network/nw_browse_descriptor_t"
    },
    "doc://com.externally.resolved.symbol/c:@T@nw_parameters_t": {
      "abstract": [
        {
          "text": "An object that stores the protocols to use for connections, options for sending data, and network path constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": " = any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_nw_parameters",
          "text": "OS_nw_parameters"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@nw_parameters_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "nw_parameters_t",
      "type": "topic",
      "url": "/documentation/Network/nw_parameters_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-device-picker-view-controllers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.devicediscoveryui/documentation/DeviceDiscoveryUI/DDDevicePickerViewController/initWithBrowseDescriptor:parameters:"
      ],
      "title": "Creating device picker view controllers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@nw_parameters_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_parameters",
              "text": "NSObject<OS_nw_parameters>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "nw_parameters_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@nw_browse_descriptor_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_browse_descriptor",
              "text": "NSObject<OS_nw_browse_descriptor>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryui~1documentation~1DeviceDiscoveryUI~1DDDevicePickerViewController/title",
          "value": "DDDevicePickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryui~1documentation~1DeviceDiscoveryUI~1DDDevicePickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDevicePickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryui~1documentation~1DeviceDiscoveryUI~1DDDevicePickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDevicePickerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/devicediscoveryui/dddevicepickerviewcontroller/issupportedforbrowsedescriptor:parameters:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
