{
  "abstract": [
    {
      "text": "The CDA document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocumentSample"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocumentSample/document"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKCDADocumentSample(py)document",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "document"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKCDADocument",
        "text": "HKCDADocument"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "document"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "document"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "document"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocument",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKCDADocument",
              "text": "HKCDADocument"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the user is authorized to access the document’s data, this property contains an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object representing that data. Otherwise, it is set to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The user is asked to authorize each CDA document the first time that document is returned by an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDocumentQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " query. The user can change the access permissions in the Health app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For samples returned by an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", this property is always set to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". To access the document’s data from these samples, create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDocumentQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " query for the sample’s UUID.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery": {
      "abstract": [
        {
          "text": "A query that returns changes to the HealthKit store, including a snapshot of new changes and continuous monitoring as a long-running query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQuery"
        }
      ],
      "role": "symbol",
      "title": "HKAnchoredObjectQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkanchoredobjectquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocument": {
      "abstract": [
        {
          "text": "An object representing a Clinical Document Architecture (CDA) document in HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCDADocument"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCDADocument"
        }
      ],
      "role": "symbol",
      "title": "HKCDADocument",
      "type": "topic",
      "url": "/documentation/healthkit/hkcdadocument"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocumentSample": {
      "abstract": [
        {
          "text": "A Clinical Document Architecture (CDA) sample that stores a single document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCDADocumentSample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocumentSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCDADocumentSample"
        }
      ],
      "role": "symbol",
      "title": "HKCDADocumentSample",
      "type": "topic",
      "url": "/documentation/healthkit/hkcdadocumentsample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocumentSample/document": {
      "abstract": [
        {
          "text": "The CDA document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "document"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCDADocument",
          "text": "HKCDADocument"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocumentSample/document",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "document"
        }
      ],
      "role": "symbol",
      "title": "document",
      "type": "topic",
      "url": "/documentation/healthkit/hkcdadocumentsample/document"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDocumentQuery": {
      "abstract": [
        {
          "text": "A query that returns a snapshot of all matching documents currently saved in the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDocumentQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDocumentQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDocumentQuery"
        }
      ],
      "role": "symbol",
      "title": "HKDocumentQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkdocumentquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery": {
      "abstract": [
        {
          "text": "A general query that returns a snapshot of all the matching samples currently saved in the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSampleQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSampleQuery"
        }
      ],
      "role": "symbol",
      "title": "HKSampleQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplequery"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Document",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocument"
      ],
      "title": "Accessing the Document"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "document"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocumentSample"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Document",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocument"
              ],
              "title": "Accessing the Document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCDADocument",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HKCDADocument",
                    "text": "HKCDADocument"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "document"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/title",
          "value": "HKAnchoredObjectQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAnchoredObjectQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAnchoredObjectQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDocumentQuery/title",
          "value": "HKDocumentQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDocumentQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDocumentQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDocumentQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDocumentQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCDADocumentSample/title",
          "value": "HKCDADocumentSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCDADocumentSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCDADocumentSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCDADocumentSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCDADocumentSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCDADocument/title",
          "value": "HKCDADocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCDADocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCDADocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCDADocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCDADocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCDADocumentSample~1document/title",
          "value": "document"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCDADocumentSample~1document/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/title",
          "value": "HKSampleQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleQuery"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcdadocumentsample/document"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcdadocumentsample/document"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
