{
  "abstract": [
    {
      "text": "The protected resource case for access to the media library.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/mediaLibrary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCUIProtectedResource@XCUIProtectedResourceMediaLibrary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mediaLibrary"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIProtectedResourceMediaLibrary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "XCUIProtectedResource.mediaLibrary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mediaLibrary"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource": {
      "abstract": [
        {
          "text": "A system resource that requires user authorization to access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIProtectedResource"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResource"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/bluetooth": {
      "abstract": [
        {
          "text": "The protected resource case for Bluetooth utilization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetooth"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/bluetooth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceBluetooth"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.bluetooth",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/bluetooth"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/calendar": {
      "abstract": [
        {
          "text": "The protected resource case for acces to Calendar data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendar"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/calendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceCalendar"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.calendar",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/calendar"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/camera": {
      "abstract": [
        {
          "text": "The protected resource case for access to the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "camera"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/camera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceCamera"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.camera",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/camera"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/contacts": {
      "abstract": [
        {
          "text": "The protected resource case for access to Contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contacts"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/contacts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceContacts"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.contacts",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/contacts"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/health": {
      "abstract": [
        {
          "text": "The protected resource case for access to Health data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "health"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/health",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceHealth"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.health",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/health"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/homeKit": {
      "abstract": [
        {
          "text": "The protected resource case for access to Home data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeKit"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/homeKit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceHomeKit"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.homeKit",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/homekit"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/keyboardNetwork": {
      "abstract": [
        {
          "text": "The protected resource case for access to the keyboard network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardNetwork"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/keyboardNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceKeyboardNetwork"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.keyboardNetwork",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/keyboardnetwork"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/localNetwork": {
      "abstract": [
        {
          "text": "The protected resource case for finding and communicating with devices on the local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localNetwork"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/localNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceLocalNetwork"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.localNetwork",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/localnetwork"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/location": {
      "abstract": [
        {
          "text": "The protected resource case for Location Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceLocation"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.location",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/location"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/mediaLibrary": {
      "abstract": [
        {
          "text": "The protected resource case for access to the media library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaLibrary"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/mediaLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceMediaLibrary"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.mediaLibrary",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/medialibrary"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/microphone": {
      "abstract": [
        {
          "text": "The protected resource case for access to the microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microphone"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/microphone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceMicrophone"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.microphone",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/microphone"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/photos": {
      "abstract": [
        {
          "text": "The protected resource case for access to Photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photos"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/photos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourcePhotos"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.photos",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/photos"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/reminders": {
      "abstract": [
        {
          "text": "The protected resource case for access to Reminders data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reminders"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/reminders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceReminders"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.reminders",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/reminders"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/systemRootDirectory": {
      "abstract": [
        {
          "text": "The protected resource case for access to the system root directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemRootDirectory"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/systemRootDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceSystemRootDirectory"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.systemRootDirectory",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/systemrootdirectory"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDesktopDirectory": {
      "abstract": [
        {
          "text": "The protected resource case for access to the Desktop directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDesktopDirectory"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDesktopDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceUserDesktopDirectory"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.userDesktopDirectory",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/userdesktopdirectory"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userTracking": {
      "abstract": [
        {
          "text": "The protected resource case for access to tracking data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userTracking"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userTracking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceUserTracking"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.userTracking",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/usertracking"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protected-resources",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/location",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userTracking",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/contacts",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/calendar",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/reminders",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/photos",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/bluetooth",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/localNetwork",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/microphone",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/camera",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/health",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/homeKit",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/keyboardNetwork",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/systemRootDirectory",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDesktopDirectory"
      ],
      "title": "Protected resources"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIProtectedResourceMediaLibrary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protected-resources",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/location",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userTracking",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/contacts",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/calendar",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/reminders",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/photos",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/bluetooth",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/localNetwork",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/microphone",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/camera",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/health",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/homeKit",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/keyboardNetwork",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/systemRootDirectory",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDesktopDirectory"
              ],
              "title": "Protected resources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "XCUIProtectedResourceMediaLibrary"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1camera/title",
          "value": "XCUIProtectedResourceCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1camera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1systemRootDirectory/title",
          "value": "XCUIProtectedResourceSystemRootDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1systemRootDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceSystemRootDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1reminders/title",
          "value": "XCUIProtectedResourceReminders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1reminders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceReminders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1keyboardNetwork/title",
          "value": "XCUIProtectedResourceKeyboardNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1keyboardNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceKeyboardNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1localNetwork/title",
          "value": "XCUIProtectedResourceLocalNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1localNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceLocalNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1photos/title",
          "value": "XCUIProtectedResourcePhotos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1photos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourcePhotos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1bluetooth/title",
          "value": "XCUIProtectedResourceBluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1bluetooth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceBluetooth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userTracking/title",
          "value": "XCUIProtectedResourceUserTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userTracking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceUserTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1calendar/title",
          "value": "XCUIProtectedResourceCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1calendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1health/title",
          "value": "XCUIProtectedResourceHealth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1health/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceHealth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userDesktopDirectory/title",
          "value": "XCUIProtectedResourceUserDesktopDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userDesktopDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceUserDesktopDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource/title",
          "value": "XCUIProtectedResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1mediaLibrary/title",
          "value": "XCUIProtectedResourceMediaLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1mediaLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1contacts/title",
          "value": "XCUIProtectedResourceContacts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1contacts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceContacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1microphone/title",
          "value": "XCUIProtectedResourceMicrophone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1microphone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceMicrophone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1homeKit/title",
          "value": "XCUIProtectedResourceHomeKit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1homeKit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceHomeKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1location/title",
          "value": "XCUIProtectedResourceLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceLocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuiprotectedresource/medialibrary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuiprotectedresource/medialibrary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
