{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeB5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICScannerDocumentType@ICScannerDocumentTypeB5",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "typeB5"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICScannerDocumentTypeB5"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ICScannerDocumentType.typeB5"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "typeB5"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType": {
      "abstract": [
        {
          "text": "The supported document size types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type10": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type10"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType10"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type10",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type10"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type10R": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type10R"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type10R",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType10R"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type10R",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type10r"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type110": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type110"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type110",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType110"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type110",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type110"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type11R": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type11R"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type11R",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType11R"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type11R",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type11r"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type12R": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type12R"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type12R",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType12R"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type12R",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type12r"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type135": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type135"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type135",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType135"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type135",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type135"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type2A0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2A0"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type2A0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType2A0"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type2A0",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type2a0"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type3R": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type3R"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type3R",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType3R"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type3R",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type3r"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type4A0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type4A0"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type4A0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType4A0"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type4A0",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type4a0"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type4R": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type4R"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type4R",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType4R"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type4R",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type4r"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type5R": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type5R"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type5R",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType5R"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type5R",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type5r"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type6R": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type6R"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type6R",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType6R"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type6R",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type6r"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type8R": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type8R"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type8R",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType8R"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.type8R",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/type8r"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeA0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeA0"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeA0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentTypeA0"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.typeA0",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/typea0"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeA1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeA1"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeA1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentTypeA1"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.typeA1",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/typea1"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeB5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeB5"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeB5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentTypeB5"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType.typeB5",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype/typeb5"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type10",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type10R",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type110",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type11R",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type12R",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type135",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type2A0",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type3R",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type4A0",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type4R",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type5R",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type6R",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type8R",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeA0",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeA1"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICScannerDocumentTypeB5"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentTypeB5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type10",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type10R",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type110",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type11R",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type12R",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type135",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type2A0",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type3R",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type4A0",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type4R",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type5R",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type6R",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/type8R",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeA0",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType/typeA1"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ICScannerDocumentTypeB5"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type11R/title",
          "value": "ICScannerDocumentType11R"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type11R/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType11R"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type8R/title",
          "value": "ICScannerDocumentType8R"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type8R/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType8R"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type6R/title",
          "value": "ICScannerDocumentType6R"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type6R/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType6R"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type3R/title",
          "value": "ICScannerDocumentType3R"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type3R/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType3R"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type4A0/title",
          "value": "ICScannerDocumentType4A0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type4A0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType4A0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type10/title",
          "value": "ICScannerDocumentType10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type135/title",
          "value": "ICScannerDocumentType135"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type135/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType135"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type12R/title",
          "value": "ICScannerDocumentType12R"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type12R/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType12R"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type4R/title",
          "value": "ICScannerDocumentType4R"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type4R/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType4R"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType/title",
          "value": "ICScannerDocumentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1typeA1/title",
          "value": "ICScannerDocumentTypeA1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1typeA1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentTypeA1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1typeB5/title",
          "value": "ICScannerDocumentTypeB5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1typeB5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentTypeB5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type2A0/title",
          "value": "ICScannerDocumentType2A0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type2A0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType2A0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type10R/title",
          "value": "ICScannerDocumentType10R"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type10R/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType10R"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1typeA0/title",
          "value": "ICScannerDocumentTypeA0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1typeA0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentTypeA0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type110/title",
          "value": "ICScannerDocumentType110"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type110/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType110"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type5R/title",
          "value": "ICScannerDocumentType5R"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType~1type5R/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType5R"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerdocumenttype/typeb5"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerdocumenttype/typeb5"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
