{
  "abstract": [
    {
      "text": "Constants for error codes returned by the framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INIntentErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INIntentError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INExtension": {
      "abstract": [
        {
          "text": "The entry point for an Intents extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INExtension"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INExtension"
        }
      ],
      "role": "symbol",
      "title": "INExtension",
      "type": "topic",
      "url": "/documentation/intents/inextension"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError": {
      "abstract": [
        {
          "text": "Errors returned by SiriKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentError"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentError"
        }
      ],
      "role": "symbol",
      "title": "INIntentError",
      "type": "topic",
      "url": "/documentation/intents/inintenterror"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code": {
      "abstract": [
        {
          "text": "Constants for error codes returned by the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/decodingGeneric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodingGeneric"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/decodingGeneric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorDecodingGeneric"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.decodingGeneric",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/decodinggeneric"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingAllInteractions": {
      "abstract": [
        {
          "text": "The system was unable to delete all donated INInteraction objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletingAllInteractions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingAllInteractions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorDeletingAllInteractions"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.deletingAllInteractions",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/deletingallinteractions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingInteractionWithGroupIdentifier": {
      "abstract": [
        {
          "text": "The system was unable to delete the INInteraction objects using their group identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletingInteractionWithGroupIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingInteractionWithGroupIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorDeletingInteractionWithGroupIdentifier"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.deletingInteractionWithGroupIdentifier",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/deletinginteractionwithgroupidentifier"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingInteractionWithIdentifiers": {
      "abstract": [
        {
          "text": "The system was unable to delete the specified set of INInteraction objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletingInteractionWithIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingInteractionWithIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorDeletingInteractionWithIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.deletingInteractionWithIdentifiers",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/deletinginteractionwithidentifiers"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/donatingInteraction": {
      "abstract": [
        {
          "text": "The INInteraction object could not be donated to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "donatingInteraction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/donatingInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorDonatingInteraction"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.donatingInteraction",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/donatinginteraction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/encodingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodingFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/encodingFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorEncodingFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.encodingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/encodingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/encodingGeneric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodingGeneric"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/encodingGeneric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorEncodingGeneric"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.encodingGeneric",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/encodinggeneric"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/extensionBringUpFailed": {
      "abstract": [
        {
          "text": "There was an error while trying to communicate with the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionBringUpFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/extensionBringUpFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorExtensionBringUpFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.extensionBringUpFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/extensionbringupfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/extensionLaunchingTimeout": {
      "abstract": [
        {
          "text": "The extension failed to launch in a timely manner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionLaunchingTimeout"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/extensionLaunchingTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorExtensionLaunchingTimeout"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.extensionLaunchingTimeout",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/extensionlaunchingtimeout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageGeneric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageGeneric"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageGeneric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageGeneric"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageGeneric",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imagegeneric"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageLoadingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageLoadingFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageLoadingFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageLoadingFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageLoadingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageloadingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageNoServiceAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageNoServiceAvailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageNoServiceAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageNoServiceAvailable"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageNoServiceAvailable",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imagenoserviceavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyInvalid"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageProxyInvalid"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageProxyInvalid",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageproxyinvalid"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyLoop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyLoop"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyLoop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageProxyLoop"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageProxyLoop",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageproxyloop"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyTimeout"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageProxyTimeout"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageProxyTimeout",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageproxytimeout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageRetrievalFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageRetrievalFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageRetrievalFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageRetrievalFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageRetrievalFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageretrievalfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageScalingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageScalingFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageScalingFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageScalingFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageScalingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imagescalingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageServiceFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageServiceFailure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageServiceFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageServiceFailure"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageServiceFailure",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageservicefailure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageStorageFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageStorageFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageStorageFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageStorageFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageStorageFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imagestoragefailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/intentSupportedByMultipleExtension": {
      "abstract": [
        {
          "text": "An intent was supported by more than one Intents extension in the same app. An app may have multiple Intents extensions, but each one must support a unique set of intents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intentSupportedByMultipleExtension"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/intentSupportedByMultipleExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorIntentSupportedByMultipleExtension"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.intentSupportedByMultipleExtension",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/intentsupportedbymultipleextension"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/interactionOperationNotSupported": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object could not be donated or deleted because those capabilities are not supported on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactionOperationNotSupported"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/interactionOperationNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorInteractionOperationNotSupported"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.interactionOperationNotSupported",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/interactionoperationnotsupported"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/invalidIntentName": {
      "abstract": [
        {
          "text": "The extension declared support for a nonexistent intent. Check your extension’s ",
          "type": "text"
        },
        {
          "code": "Info.plist",
          "type": "codeVoice"
        },
        {
          "text": " file to make sure all intent names are spelled correctly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidIntentName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/invalidIntentName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorInvalidIntentName"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.invalidIntentName",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/invalidintentname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/invalidUserVocabularyFileLocation": {
      "abstract": [
        {
          "text": "An invalid location was specified for the user vocabulary file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidUserVocabularyFileLocation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/invalidUserVocabularyFileLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorInvalidUserVocabularyFileLocation"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.invalidUserVocabularyFileLocation",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/invaliduservocabularyfilelocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/missingInformation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingInformation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/missingInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorMissingInformation"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.missingInformation",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/missinginformation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noAppAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAppAvailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noAppAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorNoAppAvailable"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.noAppAvailable",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/noappavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noAppIntent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAppIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noAppIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorNoAppIntent"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.noAppIntent",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/noappintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noHandlerProvidedForIntent": {
      "abstract": [
        {
          "text": "No object was provided to handle the specified intent. If your extension declares support for an intent in its ",
          "type": "text"
        },
        {
          "code": "Info.plist",
          "type": "codeVoice"
        },
        {
          "text": " file, the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentHandlerProviding/handler(for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method of its ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INExtension",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object must provide a corresponding handler object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noHandlerProvidedForIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noHandlerProvidedForIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorNoHandlerProvidedForIntent"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.noHandlerProvidedForIntent",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/nohandlerprovidedforintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/permissionDenied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionDenied"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/permissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorPermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.permissionDenied",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/permissiondenied"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/requestTimedOut": {
      "abstract": [
        {
          "text": "The underlying request timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestTimedOut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/requestTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorRequestTimedOut"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.requestTimedOut",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/requesttimedout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/restrictedIntentsNotSupportedByExtension": {
      "abstract": [
        {
          "text": "An intent was listed in the ",
          "type": "text"
        },
        {
          "code": "IntentsRestrictedWhileLocked",
          "type": "codeVoice"
        },
        {
          "text": " key of the app’s ",
          "type": "text"
        },
        {
          "code": "Info.plist",
          "type": "codeVoice"
        },
        {
          "text": ", but not in the ",
          "type": "text"
        },
        {
          "code": "IntentsSupported",
          "type": "codeVoice"
        },
        {
          "text": " key. All intents in the ",
          "type": "text"
        },
        {
          "code": "IntentsRestrictedWhileLocked",
          "type": "codeVoice"
        },
        {
          "text": " key must also be present in the ",
          "type": "text"
        },
        {
          "code": "IntentsSupported",
          "type": "codeVoice"
        },
        {
          "text": " key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedIntentsNotSupportedByExtension"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/restrictedIntentsNotSupportedByExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorRestrictedIntentsNotSupportedByExtension"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.restrictedIntentsNotSupportedByExtension",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/restrictedintentsnotsupportedbyextension"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/unableToCreateAppIntentRepresentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unableToCreateAppIntentRepresentation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/unableToCreateAppIntentRepresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorUnableToCreateAppIntentRepresentation"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.unableToCreateAppIntentRepresentation",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/unabletocreateappintentrepresentation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutCreationFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceShortcutCreationFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutCreationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorVoiceShortcutCreationFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.voiceShortcutCreationFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/voiceshortcutcreationfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutDeleteFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceShortcutDeleteFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutDeleteFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorVoiceShortcutDeleteFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.voiceShortcutDeleteFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/voiceshortcutdeletefailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutGetFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceShortcutGetFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutGetFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorVoiceShortcutGetFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.voiceShortcutGetFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/voiceshortcutgetfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the Intents framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "INIntentErrorDomain",
      "type": "topic",
      "url": "/documentation/intents/inintenterrordomain"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentHandlerProviding/handler(for:)": {
      "abstract": [
        {
          "text": "Returns the object capable of handling the specified intent in an extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntent",
          "text": "INIntent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentHandlerProviding/handler(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handlerForIntent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handler(for:)",
      "type": "topic",
      "url": "/documentation/intents/inintenthandlerproviding/handler(for:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INInteraction": {
      "abstract": [
        {
          "text": "An interaction between the user and your app involving an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "role": "symbol",
      "title": "INInteraction",
      "type": "topic",
      "url": "/documentation/intents/ininteraction"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError",
        "doc://com.apple.sirikit/documentation/Intents/INIntentErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Encoding-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/decodingGeneric",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/encodingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/encodingGeneric"
      ],
      "title": "Encoding Errors"
    },
    {
      "anchor": "Image-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageGeneric",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageLoadingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageNoServiceAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageServiceFailure",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyInvalid",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyLoop",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyTimeout",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageRetrievalFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageStorageFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageScalingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/permissionDenied"
      ],
      "title": "Image Errors"
    },
    {
      "anchor": "Voice-Shortcut-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutCreationFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutDeleteFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutGetFailed"
      ],
      "title": "Voice Shortcut Errors"
    },
    {
      "anchor": "Interaction-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/interactionOperationNotSupported",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/donatingInteraction",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingAllInteractions",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingInteractionWithIdentifiers",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingInteractionWithGroupIdentifier"
      ],
      "title": "Interaction Errors"
    },
    {
      "anchor": "Extension-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/extensionLaunchingTimeout",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/extensionBringUpFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noAppAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/intentSupportedByMultipleExtension",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/restrictedIntentsNotSupportedByExtension",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noHandlerProvidedForIntent",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/invalidIntentName"
      ],
      "title": "Extension Errors"
    },
    {
      "anchor": "Other-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/requestTimedOut",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/invalidUserVocabularyFileLocation",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/missingInformation"
      ],
      "title": "Other Errors"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noAppIntent",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/unableToCreateAppIntentRepresentation"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INIntentErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Encoding-Errors",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/decodingGeneric",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/encodingFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/encodingGeneric"
              ],
              "title": "Encoding Errors"
            },
            {
              "anchor": "Image-Errors",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageGeneric",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageLoadingFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageNoServiceAvailable",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageServiceFailure",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyInvalid",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyLoop",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyTimeout",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageRetrievalFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageStorageFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageScalingFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/permissionDenied"
              ],
              "title": "Image Errors"
            },
            {
              "anchor": "Voice-Shortcut-Errors",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutCreationFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutDeleteFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/voiceShortcutGetFailed"
              ],
              "title": "Voice Shortcut Errors"
            },
            {
              "anchor": "Interaction-Errors",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/interactionOperationNotSupported",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/donatingInteraction",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingAllInteractions",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingInteractionWithIdentifiers",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/deletingInteractionWithGroupIdentifier"
              ],
              "title": "Interaction Errors"
            },
            {
              "anchor": "Extension-Errors",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/extensionLaunchingTimeout",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/extensionBringUpFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noAppAvailable",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/intentSupportedByMultipleExtension",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/restrictedIntentsNotSupportedByExtension",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noHandlerProvidedForIntent",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/invalidIntentName"
              ],
              "title": "Extension Errors"
            },
            {
              "anchor": "Other-Errors",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/requestTimedOut",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/invalidUserVocabularyFileLocation",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/missingInformation"
              ],
              "title": "Other Errors"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/noAppIntent",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/unableToCreateAppIntentRepresentation"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INIntentErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1deletingInteractionWithGroupIdentifier/title",
          "value": "INIntentErrorDeletingInteractionWithGroupIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1deletingInteractionWithGroupIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorDeletingInteractionWithGroupIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1deletingInteractionWithIdentifiers/title",
          "value": "INIntentErrorDeletingInteractionWithIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1deletingInteractionWithIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorDeletingInteractionWithIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1restrictedIntentsNotSupportedByExtension/title",
          "value": "INIntentErrorRestrictedIntentsNotSupportedByExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1restrictedIntentsNotSupportedByExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorRestrictedIntentsNotSupportedByExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageGeneric/title",
          "value": "INIntentErrorImageGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageGeneric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1voiceShortcutGetFailed/title",
          "value": "INIntentErrorVoiceShortcutGetFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1voiceShortcutGetFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorVoiceShortcutGetFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1invalidUserVocabularyFileLocation/title",
          "value": "INIntentErrorInvalidUserVocabularyFileLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1invalidUserVocabularyFileLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorInvalidUserVocabularyFileLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1missingInformation/title",
          "value": "INIntentErrorMissingInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1missingInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorMissingInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/title",
          "value": "INIntentErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyTimeout/title",
          "value": "INIntentErrorImageProxyTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageProxyTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1intentSupportedByMultipleExtension/title",
          "value": "INIntentErrorIntentSupportedByMultipleExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1intentSupportedByMultipleExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorIntentSupportedByMultipleExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/title",
          "value": "INInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyInvalid/title",
          "value": "INIntentErrorImageProxyInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageProxyInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageServiceFailure/title",
          "value": "INIntentErrorImageServiceFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageServiceFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageServiceFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1encodingFailed/title",
          "value": "INIntentErrorEncodingFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1encodingFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorEncodingFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1permissionDenied/title",
          "value": "INIntentErrorPermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1permissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorPermissionDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentHandlerProviding~1handler(for:)/title",
          "value": "handlerForIntent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentHandlerProviding~1handler(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handlerForIntent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1deletingAllInteractions/title",
          "value": "INIntentErrorDeletingAllInteractions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1deletingAllInteractions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorDeletingAllInteractions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1extensionLaunchingTimeout/title",
          "value": "INIntentErrorExtensionLaunchingTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1extensionLaunchingTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorExtensionLaunchingTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1invalidIntentName/title",
          "value": "INIntentErrorInvalidIntentName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1invalidIntentName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorInvalidIntentName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1noAppAvailable/title",
          "value": "INIntentErrorNoAppAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1noAppAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorNoAppAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentErrorDomain/title",
          "value": "INIntentErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyLoop/title",
          "value": "INIntentErrorImageProxyLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyLoop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageProxyLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1encodingGeneric/title",
          "value": "INIntentErrorEncodingGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1encodingGeneric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorEncodingGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1noHandlerProvidedForIntent/title",
          "value": "INIntentErrorNoHandlerProvidedForIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1noHandlerProvidedForIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorNoHandlerProvidedForIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageStorageFailed/title",
          "value": "INIntentErrorImageStorageFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageStorageFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageStorageFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageNoServiceAvailable/title",
          "value": "INIntentErrorImageNoServiceAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageNoServiceAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageNoServiceAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1voiceShortcutDeleteFailed/title",
          "value": "INIntentErrorVoiceShortcutDeleteFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1voiceShortcutDeleteFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorVoiceShortcutDeleteFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageRetrievalFailed/title",
          "value": "INIntentErrorImageRetrievalFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageRetrievalFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageRetrievalFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1extensionBringUpFailed/title",
          "value": "INIntentErrorExtensionBringUpFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1extensionBringUpFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorExtensionBringUpFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1donatingInteraction/title",
          "value": "INIntentErrorDonatingInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1donatingInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorDonatingInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1voiceShortcutCreationFailed/title",
          "value": "INIntentErrorVoiceShortcutCreationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1voiceShortcutCreationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorVoiceShortcutCreationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageScalingFailed/title",
          "value": "INIntentErrorImageScalingFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageScalingFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageScalingFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1noAppIntent/title",
          "value": "INIntentErrorNoAppIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1noAppIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorNoAppIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1interactionOperationNotSupported/title",
          "value": "INIntentErrorInteractionOperationNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1interactionOperationNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorInteractionOperationNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1unableToCreateAppIntentRepresentation/title",
          "value": "INIntentErrorUnableToCreateAppIntentRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1unableToCreateAppIntentRepresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorUnableToCreateAppIntentRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1requestTimedOut/title",
          "value": "INIntentErrorRequestTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1requestTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorRequestTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INExtension/title",
          "value": "INExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1decodingGeneric/title",
          "value": "INIntentErrorDecodingGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1decodingGeneric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorDecodingGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageLoadingFailed/title",
          "value": "INIntentErrorImageLoadingFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageLoadingFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageLoadingFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inintenterror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inintenterror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
