{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageGeneric"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC17INIntentErrorCodeLeV12imageGenericSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "imageGeneric"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
        "text": "INIntentError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INIntentErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "imageGeneric"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "imageGeneric"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
              "text": "INIntentError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INIntentErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError": {
      "abstract": [
        {
          "text": "Errors returned by SiriKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentError"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentError"
        }
      ],
      "role": "symbol",
      "title": "INIntentError",
      "type": "topic",
      "url": "/documentation/intents/inintenterror"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code": {
      "abstract": [
        {
          "text": "Constants for error codes returned by the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageGeneric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageGeneric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageGeneric",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageGeneric",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imagegeneric"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageLoadingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageLoadingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageLoadingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageLoadingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageloadingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageNoServiceAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageNoServiceAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageNoServiceAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageNoServiceAvailable",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imagenoserviceavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProxyInvalid",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageproxyinvalid"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyLoop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyLoop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyLoop",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProxyLoop",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageproxyloop"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyTimeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProxyTimeout",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageproxytimeout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageRetrievalFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageRetrievalFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageRetrievalFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageRetrievalFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageretrievalfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageScalingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageScalingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageScalingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageScalingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imagescalingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageServiceFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageServiceFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageServiceFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageServiceFailure",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageservicefailure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageStorageFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageStorageFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageStorageFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageStorageFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imagestoragefailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/permissionDenied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/permissionDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "permissionDenied",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/permissiondenied"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageLoadingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageNoServiceAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageServiceFailure",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyInvalid",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyLoop",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyTimeout",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageRetrievalFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageStorageFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageScalingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/permissionDenied"
      ],
      "title": "Image Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/title",
          "value": "INIntentErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inintenterror/imagegeneric"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
