{
  "abstract": [
    {
      "text": "Returns a query for all descendants of the element matching the type you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/descendants(matching:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCUIElement(im)descendantsMatchingType:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "descendants"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "matching"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCUIElement",
        "text": "XCUIElement"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@XCUIElementType",
        "text": "ElementType"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
        "text": "XCUIElementQuery"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "descendantsMatchingType:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "descendants(matching:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "descendants"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "matching"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCUIElement",
              "text": "XCUIElement"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@XCUIElementType",
              "text": "ElementType"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementQuery",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
              "text": "XCUIElementQuery"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Because ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol, you can use the protocol’s properties as shorthand for calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/descendants(matching:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for different element types. For example, rather than calling ",
              "type": "text"
            },
            {
              "code": "table.descendants(matching: .cell)",
              "type": "codeVoice"
            },
            {
              "text": ", you can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/cells",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property from the protocol to retrieve ",
              "type": "text"
            },
            {
              "code": "table.cells",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType": {
      "abstract": [
        {
          "text": "The types of UI element that you find, inspect, and interact with in a UI test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/elementtype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/children(matching:)": {
      "abstract": [
        {
          "text": "Returns a query for all direct children of the element matching the type you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "children"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIElementType",
          "text": "ElementType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/children(matching:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "childrenMatchingType:"
        }
      ],
      "role": "symbol",
      "title": "children(matching:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/children(matching:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/descendants(matching:)": {
      "abstract": [
        {
          "text": "Returns a query for all descendants of the element matching the type you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descendants"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIElementType",
          "text": "ElementType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/descendants(matching:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descendantsMatchingType:"
        }
      ],
      "role": "symbol",
      "title": "descendants(matching:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/descendants(matching:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementQuery": {
      "abstract": [
        {
          "text": "An object that defines the search criteria a test uses to identify UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementQuery"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementQuery",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementquery"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider": {
      "abstract": [
        {
          "text": "A type that provides ready-made queries for locating descendant UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementTypeQueryProvider"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeQueryProvider"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementTypeQueryProvider",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/cells": {
      "abstract": [
        {
          "text": "A query that matches cell elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cells"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/cells",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cells"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cells",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/cells"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Querying-Descendant-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/children(matching:)"
      ],
      "title": "Querying Descendant Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "descendantsMatchingType:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "descendantsMatchingType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Querying-Descendant-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/children(matching:)"
              ],
              "title": "Querying Descendant Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementQuery",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
                    "text": "XCUIElementQuery"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "descendantsMatchingType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@XCUIElementType",
                    "text": "XCUIElementType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "type"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1ElementType/title",
          "value": "XCUIElementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1ElementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1ElementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider/title",
          "value": "XCUIElementTypeQueryProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeQueryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeQueryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1descendants(matching:)/title",
          "value": "descendantsMatchingType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1descendants(matching:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "descendantsMatchingType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1cells/title",
          "value": "cells"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1cells/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cells"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1children(matching:)/title",
          "value": "childrenMatchingType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1children(matching:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "childrenMatchingType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementQuery/title",
          "value": "XCUIElementQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementQuery"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuielement/descendants(matching:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuielement/descendants(matching:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
