{
  "abstract": [
    {
      "text": "Flags for simulating combination keystrokes with keys, such as Control, Option, Shift, and Command.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "XCTest",
    "externalID": "c:@E@XCUIKeyModifierFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "KeyModifierFlags"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "KeyModifierFlags"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "XCUIElement.KeyModifierFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "KeyModifierFlags"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these flags with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/typeKey(_:modifierFlags:)-9ubn",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/perform(withKeyModifiers:block:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods to simulate combination keystrokes while an action occurs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Available in macOS and in iPadOS 15 and later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags": {
      "abstract": [
        {
          "text": "Flags for simulating combination keystrokes with keys, such as Control, Option, Shift, and Command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KeyModifierFlags"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.KeyModifierFlags",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/equatable-implementations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/OptionSet-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/OptionSet-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OptionSet Implementations",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/optionset-implementations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/SetAlgebra-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/SetAlgebra-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SetAlgebra Implementations",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/setalgebra-implementations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/alphaShift": {
      "abstract": [
        {
          "text": "The Caps Lock key in a combination keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/alphaShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierAlphaShift"
        }
      ],
      "role": "symbol",
      "title": "alphaShift",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/alphashift"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/alternate": {
      "abstract": [
        {
          "text": "The Option key in a combination keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/alternate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierAlternate"
        }
      ],
      "role": "symbol",
      "title": "alternate",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/alternate"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/capsLock": {
      "abstract": [
        {
          "text": "The Caps Lock key in a combination keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capsLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/capsLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierCapsLock"
        }
      ],
      "role": "symbol",
      "title": "capsLock",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/capslock"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/command": {
      "abstract": [
        {
          "text": "The Command key in a combination keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "command"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierCommand"
        }
      ],
      "role": "symbol",
      "title": "command",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/command"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/control": {
      "abstract": [
        {
          "text": "The Control key in a combination keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "control"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/control",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierControl"
        }
      ],
      "role": "symbol",
      "title": "control",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/control"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/function": {
      "abstract": [
        {
          "text": "The Function (Fn) key in a combination keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "function"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/function",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierFunction"
        }
      ],
      "role": "symbol",
      "title": "function",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/function"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a flag that represents a key in a combination keystroke with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/init(rawvalue:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/option": {
      "abstract": [
        {
          "text": "The Option key in a combination keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "option"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/option",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierOption"
        }
      ],
      "role": "symbol",
      "title": "option",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/option"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/shift": {
      "abstract": [
        {
          "text": "The Shift key in a combination keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/shift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierShift"
        }
      ],
      "role": "symbol",
      "title": "shift",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags/shift"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/perform(withKeyModifiers:block:)": {
      "abstract": [
        {
          "text": "Executes a block of code while holding a combination keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withKeyModifiers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/perform(withKeyModifiers:block:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performWithKeyModifiers:block:"
        }
      ],
      "role": "symbol",
      "title": "perform(withKeyModifiers:block:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/perform(withkeymodifiers:block:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/typeKey(_:modifierFlags:)-1cubt": {
      "abstract": [
        {
          "text": "Types a single key with the flags you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modifierFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/typeKey(_:modifierFlags:)-1cubt",
      "kind": "symbol",
      "role": "symbol",
      "title": "typeKey(_:modifierFlags:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/typekey(_:modifierflags:)-1cubt"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/typeKey(_:modifierFlags:)-9ubn": {
      "abstract": [
        {
          "text": "Types a single key that a string represents with the flags you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modifierFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIKeyModifierFlags",
          "text": "KeyModifierFlags"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/typeKey(_:modifierFlags:)-9ubn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeKey:modifierFlags:"
        }
      ],
      "role": "symbol",
      "title": "typeKey(_:modifierFlags:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/typekey(_:modifierflags:)-9ubn"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyModifierFlags/XCUIKeyModifierNone": {
      "abstract": [
        {
          "text": "Indicates that no key modifier should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierNone"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyModifierFlags/XCUIKeyModifierNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUIKeyModifierNone",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeymodifierflags/xcuikeymodifiernone"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey": {
      "abstract": [
        {
          "text": "Constants to represent keys that have no typewritten equivalent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKey"
        }
      ],
      "role": "symbol",
      "title": "XCUIKeyboardKey",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Combining-Keystrokes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/typeKey(_:modifierFlags:)-9ubn",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/typeKey(_:modifierFlags:)-1cubt",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/perform(withKeyModifiers:block:)"
      ],
      "title": "Combining Keystrokes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Flags-for-Combination-Keys",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/command",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/control",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/option",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/shift",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/capsLock",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/function"
      ],
      "title": "Flags for Combination Keys"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Legacy-Flags-for-Combination-Keys",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/alphaShift",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/alternate"
      ],
      "title": "Legacy Flags for Combination Keys"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/Equatable-Implementations",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/OptionSet-Implementations",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/SetAlgebra-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIKeyModifierFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Flags-for-Combination-Keys",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/command",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/control",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/option",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/shift",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/capsLock",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/function"
              ],
              "title": "Flags for Combination Keys"
            },
            {
              "anchor": "Legacy-Flags-for-Combination-Keys",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/alphaShift",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags/alternate"
              ],
              "title": "Legacy Flags for Combination Keys"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyModifierFlags/XCUIKeyModifierNone"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Combining-Keystrokes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/typeKey(_:modifierFlags:)-9ubn",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/perform(withKeyModifiers:block:)"
              ],
              "title": "Combining Keystrokes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIKeyModifierFlags"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1shift/title",
          "value": "XCUIKeyModifierShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1shift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1capsLock/title",
          "value": "XCUIKeyModifierCapsLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1capsLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierCapsLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1function/title",
          "value": "XCUIKeyModifierFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1function/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1option/title",
          "value": "XCUIKeyModifierOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1option/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1typeKey(_:modifierFlags:)-9ubn/title",
          "value": "typeKey:modifierFlags:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1typeKey(_:modifierFlags:)-9ubn/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "typeKey:modifierFlags:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1perform(withKeyModifiers:block:)/title",
          "value": "performWithKeyModifiers:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1perform(withKeyModifiers:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "performWithKeyModifiers:block:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1control/title",
          "value": "XCUIKeyModifierControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1control/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1alternate/title",
          "value": "XCUIKeyModifierAlternate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1alternate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierAlternate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags/title",
          "value": "XCUIKeyModifierFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1command/title",
          "value": "XCUIKeyModifierCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1alphaShift/title",
          "value": "XCUIKeyModifierAlphaShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags~1alphaShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierAlphaShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey/title",
          "value": "XCUIKeyboardKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuielement/keymodifierflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuielement/keymodifierflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
