{
  "abstract": [
    {
      "text": "Creates a new settings instance from an array of rules and a default action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSettings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSettings/init(rules:defaultAction:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEFilterSettings(im)initWithRules:defaultAction:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "rules"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NEFilterRule",
        "text": "NEFilterRule"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "defaultAction"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NEFilterAction",
        "text": "NEFilterAction"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithRules:defaultAction:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(rules:defaultAction:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "rules"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRule",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEFilterRule",
              "text": "NEFilterRule"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "defaultAction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NEFilterAction",
              "text": "NEFilterAction"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array containing an ordered list of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRule",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects. The maximum number of rules that this array can contain is 1000.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rules"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to take for flows of network data that don’t match any of the specified rules. The default ",
                  "type": "text"
                },
                {
                  "code": "defaultAction",
                  "type": "codeVoice"
                },
                {
                  "text": " is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/filterData",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". If ",
                  "type": "text"
                },
                {
                  "code": "defaultAction",
                  "type": "codeVoice"
                },
                {
                  "text": " is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/allow",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/drop",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", then the ",
                  "type": "text"
                },
                {
                  "code": "rules",
                  "type": "codeVoice"
                },
                {
                  "text": " array must contain at least one ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRule",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "defaultAction"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction": {
      "abstract": [
        {
          "text": "The actions a data provider can take on a filter flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterAction"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterAction"
        }
      ],
      "role": "symbol",
      "title": "NEFilterAction",
      "type": "topic",
      "url": "/documentation/networkextension/nefilteraction"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/allow": {
      "abstract": [
        {
          "text": "Allow the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/allow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterActionAllow"
        }
      ],
      "role": "symbol",
      "title": "NEFilterAction.allow",
      "type": "topic",
      "url": "/documentation/networkextension/nefilteraction/allow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/drop": {
      "abstract": [
        {
          "text": "Drop the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterActionDrop"
        }
      ],
      "role": "symbol",
      "title": "NEFilterAction.drop",
      "type": "topic",
      "url": "/documentation/networkextension/nefilteraction/drop"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/filterData": {
      "abstract": [
        {
          "text": "Filter data on the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filterData"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/filterData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterActionFilterData"
        }
      ],
      "role": "symbol",
      "title": "NEFilterAction.filterData",
      "type": "topic",
      "url": "/documentation/networkextension/nefilteraction/filterdata"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRule": {
      "abstract": [
        {
          "text": "A rule for filters that combines a rule to match network traffic and an action to take when the rule matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterRule"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterRule"
        }
      ],
      "role": "symbol",
      "title": "NEFilterRule",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterrule"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSettings": {
      "abstract": [
        {
          "text": "The rules and other settings that define the operation of a filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterSettings"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterSettings"
        }
      ],
      "role": "symbol",
      "title": "NEFilterSettings",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltersettings"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSettings/init(rules:defaultAction:)": {
      "abstract": [
        {
          "text": "Creates a new settings instance from an array of rules and a default action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rules"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEFilterRule",
          "text": "NEFilterRule"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "defaultAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEFilterAction",
          "text": "NEFilterAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSettings/init(rules:defaultAction:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRules:defaultAction:"
        }
      ],
      "role": "symbol",
      "title": "init(rules:defaultAction:)",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltersettings/init(rules:defaultaction:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Filter-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRule"
      ],
      "title": "Creating Filter Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithRules:defaultAction:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRules:defaultAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterSettings"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Filter-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRule"
              ],
              "title": "Creating Filter Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithRules:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NEFilterRule *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rules"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "defaultAction:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NEFilterAction",
                    "text": "NEFilterAction"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "defaultAction"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array containing an ordered list of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRule",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " objects. The maximum number of rules that this array can contain is 1000.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "rules"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to take for flows of network data that don’t match any of the specified rules. The default ",
                        "type": "text"
                      },
                      {
                        "code": "defaultAction",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/filterData",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". If ",
                        "type": "text"
                      },
                      {
                        "code": "defaultAction",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/allow",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterAction/drop",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", then the ",
                        "type": "text"
                      },
                      {
                        "code": "rules",
                        "type": "codeVoice"
                      },
                      {
                        "text": " array must contain at least one ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterRule",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "defaultAction"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterRule/title",
          "value": "NEFilterRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterAction~1filterData/title",
          "value": "NEFilterActionFilterData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterAction~1filterData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterActionFilterData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterAction~1allow/title",
          "value": "NEFilterActionAllow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterAction~1allow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterActionAllow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterAction~1drop/title",
          "value": "NEFilterActionDrop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterAction~1drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterActionDrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSettings/title",
          "value": "NEFilterSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterAction/title",
          "value": "NEFilterAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSettings~1init(rules:defaultAction:)/title",
          "value": "initWithRules:defaultAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterSettings~1init(rules:defaultAction:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRules:defaultAction:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nefiltersettings/init(rules:defaultaction:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nefiltersettings/init(rules:defaultaction:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
