{
  "abstract": [
    {
      "text": "An identity authority is a database that stores information about identities. The ",
      "type": "text"
    },
    {
      "code": "CBIdentityAuthority",
      "type": "codeVoice"
    },
    {
      "text": " class defines one or more identity authorities. You can search this database for identities in conjunction with the ",
      "type": "text"
    },
    {
      "code": "CBIdentity",
      "type": "codeVoice"
    },
    {
      "text": " class factory methods.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.collaboration/documentation/Collaboration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBIdentityAuthority",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CBIdentityAuthority"
      }
    ],
    "modules": [
      {
        "name": "Collaboration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CBIdentityAuthority"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CBIdentityAuthority"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.collaboration/documentation/Collaboration": {
      "abstract": [
        {
          "text": "Find and access identities, that is, users and groups. Display the Identity Picker, which lets users create and select identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration",
      "kind": "symbol",
      "role": "collection",
      "title": "Collaboration",
      "type": "topic",
      "url": "/documentation/collaboration"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority": {
      "abstract": [
        {
          "text": "An identity authority is a database that stores information about identities. The ",
          "type": "text"
        },
        {
          "code": "CBIdentityAuthority",
          "type": "codeVoice"
        },
        {
          "text": " class defines one or more identity authorities. You can search this database for identities in conjunction with the ",
          "type": "text"
        },
        {
          "code": "CBIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class factory methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBIdentityAuthority"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBIdentityAuthority"
        }
      ],
      "role": "symbol",
      "title": "CBIdentityAuthority",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/CSIdentityAuthority": {
      "abstract": [
        {
          "text": "Returns an identity authority for use with the Core Services Identity API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSIdentityAuthority"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/CSIdentityAuthority",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSIdentityAuthority",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority/csidentityauthority"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/default()": {
      "abstract": [
        {
          "text": "Returns an identity authority that contains the identities in both the local and the network-bound authorities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBIdentityAuthority",
          "text": "CBIdentityAuthority"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/default()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultIdentityAuthority"
        }
      ],
      "role": "symbol",
      "title": "default()",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority/default()"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/identityAuthorityWithCSIdentityAuthority:": {
      "abstract": [
        {
          "text": "Returns an identity authority specified by a given Core Services Identity authority object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "identityAuthorityWithCSIdentityAuthority:"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/identityAuthorityWithCSIdentityAuthority:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identityAuthorityWithCSIdentityAuthority:"
        }
      ],
      "role": "symbol",
      "title": "identityAuthorityWithCSIdentityAuthority:",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority/identityauthoritywithcsidentityauthority:"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/local()": {
      "abstract": [
        {
          "text": "Returns the identity authority on the local system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "local"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBIdentityAuthority",
          "text": "CBIdentityAuthority"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/local()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localIdentityAuthority"
        }
      ],
      "role": "symbol",
      "title": "local()",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority/local()"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/localizedName": {
      "abstract": [
        {
          "text": "Returns the localized name of the identity authority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/localizedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedName"
        }
      ],
      "role": "symbol",
      "title": "localizedName",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority/localizedname"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/managed()": {
      "abstract": [
        {
          "text": "Returns the identity authority that contains all the identities in bound network directory servers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managed"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBIdentityAuthority",
          "text": "CBIdentityAuthority"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/managed()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "managedIdentityAuthority"
        }
      ],
      "role": "symbol",
      "title": "managed()",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority/managed()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Accessing-Identity-Authorities",
      "identifiers": [
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/localizedName",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/local()",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/managed()",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/default()"
      ],
      "title": "Accessing Identity Authorities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CBIdentityAuthority"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.collaboration/documentation/Collaboration"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Interacting-with-the-Core-Services-Identity-API",
              "identifiers": [
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/CSIdentityAuthority",
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/identityAuthorityWithCSIdentityAuthority:"
              ],
              "title": "Interacting with the Core Services Identity API"
            },
            {
              "anchor": "Accessing-Identity-Authorities",
              "identifiers": [
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/localizedName",
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/local()",
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/managed()",
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/default()"
              ],
              "title": "Accessing Identity Authorities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CBIdentityAuthority"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority~1managed()/title",
          "value": "managedIdentityAuthority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority~1managed()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "managedIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/title",
          "value": "CBIdentityAuthority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority~1default()/title",
          "value": "defaultIdentityAuthority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority~1default()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority~1local()/title",
          "value": "localIdentityAuthority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority~1local()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority~1localizedName/title",
          "value": "localizedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority~1localizedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/collaboration/cbidentityauthority"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/collaboration/cbidentityauthority"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
