{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient/interfaceNames()-swift.method"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CWWiFiClient(im)interfaceNames",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "interfaceNames"
      },
      {
        "kind": "text",
        "text": "() -> ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "interfaceNames"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "interfaceNames()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "interfaceNames"
            },
            {
              "kind": "text",
              "text": "() -> ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "]?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient": {
      "abstract": [
        {
          "text": "A wrapper around the entire Wi-Fi subsystem that you use to access interfaces and set up event notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWWiFiClient"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWWiFiClient"
        }
      ],
      "role": "symbol",
      "title": "CWWiFiClient",
      "type": "topic",
      "url": "/documentation/corewlan/cwwificlient"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient/interfaceNames()-swift.method": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interfaceNames"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient/interfaceNames()-swift.method",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interfaceNames"
        }
      ],
      "role": "symbol",
      "title": "interfaceNames()",
      "type": "topic",
      "url": "/documentation/corewlan/cwwificlient/interfacenames()-swift.method"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "interfaceNames"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "interfaceNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSString *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "interfaceNames"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient/title",
          "value": "CWWiFiClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWWiFiClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWWiFiClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient~1interfaceNames()-swift.method/title",
          "value": "interfaceNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient~1interfaceNames()-swift.method/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "interfaceNames"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwwificlient/interfacenames()-swift.method"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwwificlient/interfacenames()-swift.method"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
