{"metadata":{"modules":[{"name":"PhotosUI"}],"externalID":"c:objc(cs)PHProjectInfo(py)projectType","role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.13","name":"macOS"}],"symbolKind":"property","roleHeading":"Instance Property","title":"projectType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projectType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PHProjectType","kind":"typeIdentifier","preciseIdentifier":"c:@T@PHProjectType"}],"navigatorTitle":[{"text":"projectType","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/photosui/phprojectinfo/projecttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/photosui/phprojectinfo/projecttype"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"seeAlsoSections":[{"anchor":"Determining-Project-Type","title":"Determining Project Type","identifiers":["doc://com.apple.photokit/documentation/PhotosUI/PHProjectType","doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/creationSource-swift.property","doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/sections","doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription","doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource","doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator","doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum"],"generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/PhotosUI","doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"projectType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@PHProjectType","kind":"typeIdentifier","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectType","text":"PHProjectType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"See the "},{"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController","isActive":true,"type":"reference"},{"type":"text","text":" protocol for more information on configuring the options."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"The project type that the user selected from the project extension options."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/projectType"},"references":{"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/creationSource-swift.property":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"creationSource","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creationSource","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHProjectInfo","text":"PHProjectInfo","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@PHProjectCreationSource","text":"CreationSource","kind":"typeIdentifier"}],"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/creationSource-swift.property","abstract":[{"type":"text","text":"The source from which the project was created."}],"kind":"symbol","url":"/documentation/photosui/phprojectinfo/creationsource-swift.property","title":"creationSource"},"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo":{"kind":"symbol","type":"topic","title":"PHProjectInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PHProjectInfo"}],"url":"/documentation/photosui/phprojectinfo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PHProjectInfo"}],"abstract":[{"text":"Information about the project extension.","type":"text"}],"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo"},"doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource":{"title":"PHProjectTypeDescriptionDataSource","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource","url":"/documentation/photosui/phprojecttypedescriptiondatasource","abstract":[{"text":"A protocol that you use to provide the project with type description data.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PHProjectTypeDescriptionDataSource","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"PHProjectTypeDescriptionDataSource","kind":"identifier"}]},"doc://com.apple.photokit/documentation/PhotosUI/PHProjectType":{"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectType","url":"/documentation/photosui/phprojecttype","title":"PHProjectType","abstract":[{"type":"text","text":"The type descriptor of a project extension."}],"navigatorTitle":[{"text":"PHProjectType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PHProjectType","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/sections":{"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/sections","url":"/documentation/photosui/phprojectinfo/sections","title":"sections","abstract":[{"type":"text","text":"An array of project sections, each containing one or more section content objects."}],"navigatorTitle":[{"kind":"identifier","text":"sections"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PHProjectSection","preciseIdentifier":"c:objc(cs)PHProjectSection"},{"kind":"text","text":"]"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription":{"kind":"symbol","title":"PHProjectTypeDescription","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription","abstract":[{"type":"text","text":"An extensible enumerator for "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectType"},{"type":"text","text":" that’s presented to users in the project picker."}],"type":"topic","role":"symbol","url":"/documentation/photosui/phprojecttypedescription","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PHProjectTypeDescription","kind":"identifier"}],"navigatorTitle":[{"text":"PHProjectTypeDescription","kind":"identifier"}]},"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CreationSource"}],"url":"/documentation/photosui/phprojectinfo/creationsource-swift.enum","type":"topic","title":"PHProjectInfo.CreationSource","navigatorTitle":[{"kind":"identifier","text":"CreationSource"}],"role":"symbol","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum","abstract":[{"text":"Defines the source of a project extension.","type":"text"}]},"doc://com.apple.photokit/documentation/PhotosUI":{"type":"topic","identifier":"doc://com.apple.photokit/documentation/PhotosUI","title":"PhotosUI","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality."}],"url":"/documentation/photosui"},"doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PHProjectExtensionController","kind":"identifier"}],"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController","title":"PHProjectExtensionController","navigatorTitle":[{"text":"PHProjectExtensionController","kind":"identifier"}],"url":"/documentation/photosui/phprojectextensioncontroller","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol defining the life cycle and supported types of project extensions."}]},"doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator":{"type":"topic","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator","abstract":[{"text":"A protocol that you use to tell the project when and how to invalidate type and footer text.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PHProjectTypeDescriptionInvalidator"}],"title":"PHProjectTypeDescriptionInvalidator","url":"/documentation/photosui/phprojecttypedescriptioninvalidator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHProjectTypeDescriptionInvalidator"}],"role":"symbol"},"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/projectType":{"kind":"symbol","url":"/documentation/photosui/phprojectinfo/projecttype","type":"topic","role":"symbol","title":"projectType","abstract":[{"type":"text","text":"The project type that the user selected from the project extension options."}],"navigatorTitle":[{"text":"projectType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projectType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PHProjectType","kind":"typeIdentifier","preciseIdentifier":"c:@T@PHProjectType"}],"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/projectType"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"10.13","name":"macOS","beta":false,"deprecated":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"projectType","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"projectType","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/PhotosUI","doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Determining Project Type","anchor":"Determining-Project-Type","identifiers":["doc://com.apple.photokit/documentation/PhotosUI/PHProjectType","doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/creationSource-swift.property","doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/sections","doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription","doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource","doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator","doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum"],"generated":true}],"path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHProjectType","preciseIdentifier":"c:@T@PHProjectType","text":"PHProjectType"},{"kind":"text","text":" "},{"kind":"identifier","text":"projectType"},{"kind":"text","text":";"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":"creationSource","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1creationSource-swift.property/title"},{"op":"replace","value":[{"text":"creationSource","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1creationSource-swift.property/fragments"},{"op":"replace","value":"PHProjectInfo","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/title"},{"op":"replace","value":[{"text":"PHProjectInfo","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/fragments"},{"op":"replace","value":[{"text":"PHProjectInfo","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/navigatorTitle"},{"op":"replace","value":"PHProjectTypeDescriptionDataSource","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/title"},{"op":"replace","value":[{"text":"PHProjectTypeDescriptionDataSource","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PHProjectTypeDescriptionDataSource"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/navigatorTitle"},{"op":"replace","value":"PHProjectType","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/title"},{"op":"replace","value":[{"kind":"identifier","text":"PHProjectType"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/fragments"},{"op":"replace","value":[{"text":"PHProjectType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/navigatorTitle"},{"op":"replace","value":"sections","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1sections/title"},{"op":"replace","value":[{"text":"sections","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1sections/fragments"},{"op":"replace","value":"PHProjectTypeDescription","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription/title"},{"op":"replace","value":[{"kind":"identifier","text":"PHProjectTypeDescription"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription/fragments"},{"op":"replace","value":[{"text":"PHProjectTypeDescription","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription/navigatorTitle"},{"op":"replace","value":"PHProjectCreationSource","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum/title"},{"op":"replace","value":[{"text":"PHProjectCreationSource","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PHProjectCreationSource"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum/navigatorTitle"},{"op":"replace","value":"PHProjectExtensionController","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController/title"},{"op":"replace","value":[{"kind":"identifier","text":"PHProjectExtensionController"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PHProjectExtensionController"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController/navigatorTitle"},{"op":"replace","value":"PHProjectTypeDescriptionInvalidator","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator/title"},{"op":"replace","value":[{"text":"PHProjectTypeDescriptionInvalidator","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator/fragments"},{"op":"replace","value":[{"text":"PHProjectTypeDescriptionInvalidator","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator/navigatorTitle"},{"op":"replace","value":"projectType","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1projectType/title"},{"op":"replace","value":[{"text":"projectType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1projectType/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}