{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum"]]},"sections":[],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conditional","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyleConditional","kind":"identifier"}],"title":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest.RequestStyle.conditional","role":"symbol","modules":[{"name":"Authentication Services"}],"platforms":[{"deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"introducedAt":"18.0","deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"introducedAt":"15.0","deprecated":false,"name":"macOS"},{"unavailable":false,"beta":false,"introducedAt":"2.0","deprecated":false,"name":"visionOS"}],"externalID":"c:@E@ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle@ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyleConditional"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Perform a conditional request. This style of request is meant to opportunistically add passkeys to existing","type":"text"},{"text":" ","type":"text"},{"text":"password-based accounts, at the discretion of the user’s credential manager. It should be performed","type":"text"},{"text":" ","type":"text"},{"text":"shortly after a user has signed in with a password. If the user is using a password and passkey manager,","type":"text"},{"text":" ","type":"text"},{"text":"and certain internal conditions of that credential manager are met (e.g. the user signed in recently with a","type":"text"},{"text":" ","type":"text"},{"text":"matching password-based account and does not yet have a passkey for this account), then this request","type":"text"},{"text":" ","type":"text"},{"text":"may proceed automatically, without further user interaction. If any of the internal conditions are not met,","type":"text"},{"text":" ","type":"text"},{"text":"this request will return an error without showing any UI to the user, and may be retried the next time they","type":"text"},{"text":" ","type":"text"},{"text":"sign in.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conditional"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"]}]}],"variants":[{"paths":["/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/requeststyle-swift.enum/conditional"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/requeststyle-swift.enum/conditional"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum/conditional"},"references":{"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest","abstract":[{"text":"The object for registering a new platform public key credential.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"title":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum/conditional":{"url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/requeststyle-swift.enum/conditional","abstract":[{"type":"text","text":"Perform a conditional request. This style of request is meant to opportunistically add passkeys to existing"},{"type":"text","text":" "},{"type":"text","text":"password-based accounts, at the discretion of the user’s credential manager. It should be performed"},{"type":"text","text":" "},{"type":"text","text":"shortly after a user has signed in with a password. If the user is using a password and passkey manager,"},{"type":"text","text":" "},{"type":"text","text":"and certain internal conditions of that credential manager are met (e.g. the user signed in recently with a"},{"type":"text","text":" "},{"type":"text","text":"matching password-based account and does not yet have a passkey for this account), then this request"},{"type":"text","text":" "},{"type":"text","text":"may proceed automatically, without further user interaction. If any of the internal conditions are not met,"},{"type":"text","text":" "},{"type":"text","text":"this request will return an error without showing any UI to the user, and may be retried the next time they"},{"text":" ","type":"text"},{"text":"sign in.","type":"text"}],"navigatorTitle":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyleConditional","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"conditional","kind":"identifier"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum/conditional","title":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest.RequestStyle.conditional","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum":{"title":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest.RequestStyle","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestStyle","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"RequestStyle","kind":"identifier"}],"url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/requeststyle-swift.enum","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"introducedAt":"15.0","deprecated":false,"name":"macOS"},{"unavailable":false,"beta":false,"introducedAt":"2.0","deprecated":false,"name":"visionOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyleConditional"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyleConditional"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum"]]}},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyleConditional","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/title","value":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/fragments","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/navigatorTitle","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1RequestStyle-swift.enum~1conditional/title","value":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyleConditional","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1RequestStyle-swift.enum~1conditional/fragments","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyleConditional"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1RequestStyle-swift.enum/title","value":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1RequestStyle-swift.enum/fragments","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1RequestStyle-swift.enum/navigatorTitle","value":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}