{
  "abstract": [
    {
      "text": "The type of block for handling updates to the view’s configuration using the current state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/ConfigurationUpdateHandler-swift.typealias"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So023UITableViewHeaderFooterB0C5UIKitE26ConfigurationUpdateHandlera",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ConfigurationUpdateHandler"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ConfigurationUpdateHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "UITableViewHeaderFooterView.ConfigurationUpdateHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ConfigurationUpdateHandler"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITableViewHeaderFooterView",
              "text": "UITableViewHeaderFooterView"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit24UIViewConfigurationStateV",
              "text": "UIViewConfigurationState"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The header footer view to configure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "headerFooterView"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The new state to use for updating the header footer view’s configuration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "state"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView": {
      "abstract": [
        {
          "text": "A reusable view that you place at the top or bottom of a table section to display additional information for that section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewHeaderFooterView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewHeaderFooterView"
        }
      ],
      "role": "symbol",
      "title": "UITableViewHeaderFooterView",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/ConfigurationUpdateHandler-swift.typealias": {
      "abstract": [
        {
          "text": "The type of block for handling updates to the view’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ConfigurationUpdateHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/ConfigurationUpdateHandler-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ConfigurationUpdateHandler"
        }
      ],
      "role": "symbol",
      "title": "UITableViewHeaderFooterView.ConfigurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview/configurationupdatehandler-swift.typealias"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationState-7xj7r": {
      "abstract": [
        {
          "text": "The current configuration state of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UIViewConfigurationStateV",
          "text": "UIViewConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationState-7xj7r",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationState",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview/configurationstate-7xj7r"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationUpdateHandler-49slo": {
      "abstract": [
        {
          "text": "A block for handling updates to the view’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewHeaderFooterView",
          "text": "UITableViewHeaderFooterView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So023UITableViewHeaderFooterB0C5UIKitE26ConfigurationUpdateHandlera",
          "text": "ConfigurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationUpdateHandler-49slo",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview/configurationupdatehandler-49slo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/setNeedsUpdateConfiguration()": {
      "abstract": [
        {
          "text": "Informs the view to update its configuration for its current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNeedsUpdateConfiguration"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/setNeedsUpdateConfiguration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsUpdateConfiguration"
        }
      ],
      "role": "symbol",
      "title": "setNeedsUpdateConfiguration()",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview/setneedsupdateconfiguration()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/updateConfiguration(using:)": {
      "abstract": [
        {
          "text": "Updates the view’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UIViewConfigurationStateV",
          "text": "UIViewConfigurationState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/updateConfiguration(using:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateConfiguration(using:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview/updateconfiguration(using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct": {
      "abstract": [
        {
          "text": "A structure that encapsulates a view’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewConfigurationState"
        }
      ],
      "role": "symbol",
      "title": "UIViewConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-swift.struct"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-state",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationState-7xj7r",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/setNeedsUpdateConfiguration()",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/updateConfiguration(using:)",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationUpdateHandler-49slo"
      ],
      "title": "Managing the state"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewHeaderFooterView~1setNeedsUpdateConfiguration()/title",
          "value": "setNeedsUpdateConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewHeaderFooterView~1setNeedsUpdateConfiguration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setNeedsUpdateConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewHeaderFooterView/title",
          "value": "UITableViewHeaderFooterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewHeaderFooterView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewHeaderFooterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewHeaderFooterView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewHeaderFooterView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableviewheaderfooterview/configurationupdatehandler-swift.typealias"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
