{
  "abstract": [
    {
      "text": "Returns a Boolean value indicating whether a state machine currently in this state is allowed to transition into the specified state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState/isValidNextState(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKState(im)isValidNextState:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isValidNextState"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s8AnyClassa",
        "text": "AnyClass"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "isValidNextState:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "isValidNextState(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isValidNextState"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "stateClass"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s8AnyClassa",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s8AnyClassa",
              "text": "AnyClass"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A custom ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class used in the same state machine as this state.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "stateClass"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if a transition into the specified state should be allowed; otherwise, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/canEnterState(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/enter(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/currentState",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is this state, the state machine calls this method to determine whether a transition to the proposed next state is allowed. Override this method in each custom state class you implement to choose which other states should be valid transitions from this state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "GameplayKit may call this method at any time. Your implementation of this method should describe the static relationships between state classes that determine the set of edges in a state machine’s state graph. Do not use this method to conditionally control state transitions—instead, perform such conditional logic before calling a state machine’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/enter(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "By restricting the set of valid state transitions, you can use a state machine to enforce invariant conditions in your code. For example, if one state class can be entered only after a state machine has passed through a series of other states, code in that state class can safely assume that any actions performed by those other states have already occurred.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState": {
      "abstract": [
        {
          "text": "The abstract superclass for defining state-specific logic as part of a state machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKState"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKState"
        }
      ],
      "role": "symbol",
      "title": "GKState",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstate"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState/isValidNextState(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether a state machine currently in this state is allowed to transition into the specified state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isValidNextState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState/isValidNextState(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isValidNextState:"
        }
      ],
      "role": "symbol",
      "title": "isValidNextState(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstate/isvalidnextstate(_:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState/stateMachine": {
      "abstract": [
        {
          "text": "The state machine that owns this state object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateMachine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKStateMachine",
          "text": "GKStateMachine"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState/stateMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stateMachine"
        }
      ],
      "role": "symbol",
      "title": "stateMachine",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstate/statemachine"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine": {
      "abstract": [
        {
          "text": "A finite-state machine—a collection of state objects that each define logic for a particular state of gameplay and rules for transitioning between states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKStateMachine"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKStateMachine"
        }
      ],
      "role": "symbol",
      "title": "GKStateMachine",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstatemachine"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/canEnterState(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether it is valid for the state machine to transition from its current state to a state of the specified class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canEnterState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/canEnterState(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canEnterState:"
        }
      ],
      "role": "symbol",
      "title": "canEnterState(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstatemachine/canenterstate(_:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/currentState": {
      "abstract": [
        {
          "text": "The state machine’s current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKState",
          "text": "GKState"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/currentState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentState"
        }
      ],
      "role": "symbol",
      "title": "currentState",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstatemachine/currentstate"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/enter(_:)": {
      "abstract": [
        {
          "text": "Attempts to transition the state machine from its current state to a state of the specified class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKStateMachine/enter(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enterState:"
        }
      ],
      "role": "symbol",
      "title": "enter(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkstatemachine/enter(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:@T@Class": {
      "abstract": [
        {
          "text": "An opaque type that represents an Objective-C class.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@Class",
      "kind": "symbol",
      "role": "symbol",
      "title": "Class",
      "type": "topic",
      "url": "/documentation/objectivec/class"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:s8AnyClassa": {
      "abstract": [
        {
          "text": "The protocol to which all class types implicitly conform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": " = any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9AnyObjecta",
          "text": "AnyObject"
        },
        {
          "kind": "text",
          "text": ".Type"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8AnyClassa",
      "kind": "symbol",
      "role": "symbol",
      "title": "AnyClass",
      "type": "topic",
      "url": "/documentation/Swift/AnyClass"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-State-Machines",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState/stateMachine"
      ],
      "title": "Working with State Machines"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "isValidNextState:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isValidNextState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gameplaykit/documentation/GameplayKit",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-State-Machines",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState/stateMachine"
              ],
              "title": "Working with State Machines"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "isValidNextState:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@Class",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@Class",
                    "text": "Class"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "stateClass"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A custom ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKState",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " class used in the same state machine as this state.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "stateClass"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if a transition into the specified state should be allowed; otherwise, ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKState~1stateMachine/title",
          "value": "stateMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKState~1stateMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStateMachine~1canEnterState(_:)/title",
          "value": "canEnterState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStateMachine~1canEnterState(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canEnterState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStateMachine~1enter(_:)/title",
          "value": "enterState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStateMachine~1enter(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enterState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKState/title",
          "value": "GKState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStateMachine/title",
          "value": "GKStateMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStateMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStateMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKState~1isValidNextState(_:)/title",
          "value": "isValidNextState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKState~1isValidNextState(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isValidNextState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStateMachine~1currentState/title",
          "value": "currentState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKStateMachine~1currentState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gkstate/isvalidnextstate(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gkstate/isvalidnextstate(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
