{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didPublishL2CAPChannel:error:)"},"kind":"symbol","seeAlsoSections":[{"anchor":"Using-L2CAP-Channels","identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didUnpublishL2CAPChannel:error:)","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didOpen:error:)"],"title":"Using L2CAP Channels","generated":true}],"abstract":[{"type":"text","text":"Tells the delegate that the peripheral manager created a listener for incoming L2CAP channel connections."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager","text":"CBPeripheralManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBPeripheralManager"},{"text":", ","kind":"text"},{"text":"didPublishL2CAPChannel","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"PSM","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPPSM","text":"CBL2CAPPSM","kind":"typeIdentifier","preciseIdentifier":"c:@T@CBL2CAPPSM"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The peripheral manager that published the channel.","type":"text"}]}],"name":"peripheral"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The Protocol/Service Multiplexer (PSM) of the published channel.","type":"text"}]}],"name":"PSM"},{"content":[{"inlineContent":[{"text":"The error that prevented publishing, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred.","type":"text"}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The peripheral manager calls this method after you call ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/publishL2CAPChannel(withEncryption:)"},{"text":". The ","type":"text"},{"code":"PSM","type":"codeVoice"},{"text":" parameter contains the PSM assigned for the published channel.","type":"text"}]}],"kind":"content"}],"metadata":{"role":"symbol","symbolKind":"method","platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"6.0","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"6.0","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.9","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"9.0","unavailable":false},{"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false},{"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"2.0","deprecated":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheralManager"},{"text":"(","kind":"text"},{"text":"CBPeripheralManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBPeripheralManager"},{"text":", ","kind":"text"},{"text":"didPublishL2CAPChannel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CBL2CAPPSM","text":"CBL2CAPPSM","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"Core Bluetooth"}],"navigatorTitle":[{"text":"peripheralManager:didPublishL2CAPChannel:error:","kind":"identifier"}],"title":"peripheralManager(_:didPublishL2CAPChannel:error:)","externalID":"c:objc(pl)CBPeripheralManagerDelegate(im)peripheralManager:didPublishL2CAPChannel:error:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/corebluetooth/cbperipheralmanagerdelegate/peripheralmanager(_:didpublishl2capchannel:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/corebluetooth/cbperipheralmanagerdelegate/peripheralmanager(_:didpublishl2capchannel:error:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate"]]},"references":{"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didOpen:error:)":{"navigatorTitle":[{"text":"peripheralManager:didOpenL2CAPChannel:error:","kind":"identifier"}],"abstract":[{"text":"Tells the delegate that the peripheral manager opened an L2CAP channel.","type":"text"}],"kind":"symbol","role":"symbol","title":"peripheralManager(_:didOpen:error:)","type":"topic","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didOpen:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheralManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CBPeripheralManager","text":"CBPeripheralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didOpen","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CBL2CAPChannel","text":"CBL2CAPChannel","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"url":"/documentation/corebluetooth/cbperipheralmanagerdelegate/peripheralmanager(_:didopen:error:)"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didUnpublishL2CAPChannel:error:)":{"title":"peripheralManager(_:didUnpublishL2CAPChannel:error:)","url":"/documentation/corebluetooth/cbperipheralmanagerdelegate/peripheralmanager(_:didunpublishl2capchannel:error:)","kind":"symbol","navigatorTitle":[{"text":"peripheralManager:didUnpublishL2CAPChannel:error:","kind":"identifier"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didUnpublishL2CAPChannel:error:)","abstract":[{"text":"Tells the delegate that the peripheral manager removed a published service from the local system.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheralManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CBPeripheralManager","text":"CBPeripheralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUnpublishL2CAPChannel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBL2CAPPSM","preciseIdentifier":"c:@T@CBL2CAPPSM","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate":{"navigatorTitle":[{"text":"CBPeripheralManagerDelegate","kind":"identifier"}],"role":"symbol","type":"topic","url":"/documentation/corebluetooth/cbperipheralmanagerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBPeripheralManagerDelegate","kind":"identifier"}],"abstract":[{"text":"A protocol that provides updates for local peripheral state and interactions with remote central devices.","type":"text"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate","title":"CBPeripheralManagerDelegate","kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth":{"title":"Core Bluetooth","abstract":[{"text":"Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.","type":"text"}],"url":"/documentation/corebluetooth","kind":"symbol","type":"topic","role":"collection","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager":{"title":"CBPeripheralManager","abstract":[{"type":"text","text":"An object that manages and advertises peripheral services exposed by this app."}],"url":"/documentation/corebluetooth/cbperipheralmanager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBPeripheralManager"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBPeripheralManager"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","title":"Technologies","role":"overview","url":"/documentation/technologies"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPPSM":{"role":"symbol","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPPSM","abstract":[{"type":"text","text":"The type of PSM identifiers."}],"title":"CBL2CAPPSM","type":"topic","url":"/documentation/corebluetooth/cbl2cappsm","navigatorTitle":[{"text":"CBL2CAPPSM","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CBL2CAPPSM","kind":"identifier"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:s5ErrorP":{"kind":"symbol","abstract":[{"type":"text","text":"A type representing an error value that can be thrown."}],"title":"Error","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","url":"/documentation/Swift/Error","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Sendable","kind":"typeIdentifier","preciseIdentifier":"s:s8SendableP"}]},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/publishL2CAPChannel(withEncryption:)":{"type":"topic","url":"/documentation/corebluetooth/cbperipheralmanager/publishl2capchannel(withencryption:)","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/publishL2CAPChannel(withEncryption:)","title":"publishL2CAPChannel(withEncryption:)","kind":"symbol","abstract":[{"text":"Creates a listener for incoming L2CAP channel connections.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishL2CAPChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withEncryption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"publishL2CAPChannelWithEncryption:"}],"role":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didPublishL2CAPChannel:error:)":{"url":"/documentation/corebluetooth/cbperipheralmanagerdelegate/peripheralmanager(_:didpublishl2capchannel:error:)","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didPublishL2CAPChannel:error:)","type":"topic","abstract":[{"type":"text","text":"Tells the delegate that the peripheral manager created a listener for incoming L2CAP channel connections."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peripheralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBPeripheralManager","preciseIdentifier":"c:objc(cs)CBPeripheralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didPublishL2CAPChannel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CBL2CAPPSM","text":"CBL2CAPPSM","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"peripheralManager:didPublishL2CAPChannel:error:","kind":"identifier"}],"title":"peripheralManager(_:didPublishL2CAPChannel:error:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"5.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"5.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.10","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"9.0","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false},{"deprecated":false,"beta":false,"name":"watchOS","introducedAt":"4.0","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"peripheralManager:didPublishL2CAPChannel:error:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"peripheralManager:didPublishL2CAPChannel:error:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Using-L2CAP-Channels","identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didUnpublishL2CAPChannel:error:)","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManager(_:didOpen:error:)"],"generated":true,"title":"Using L2CAP Channels"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"peripheralManager:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBPeripheralManager","text":"CBPeripheralManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPublishL2CAPChannel:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPPSM","kind":"typeIdentifier","preciseIdentifier":"c:@T@CBL2CAPPSM","text":"CBL2CAPPSM"},{"kind":"text","text":") "},{"kind":"internalParam","text":"PSM"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The peripheral manager that published the channel.","type":"text"}],"type":"paragraph"}],"name":"peripheral"},{"content":[{"inlineContent":[{"text":"The Protocol/Service Multiplexer (PSM) of the published channel.","type":"text"}],"type":"paragraph"}],"name":"PSM"},{"content":[{"inlineContent":[{"text":"The error that prevented publishing, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred.","type":"text"}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"}},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate~1peripheralManager(_:didOpen:error:)/title","op":"replace","value":"peripheralManager:didOpenL2CAPChannel:error:"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate~1peripheralManager(_:didOpen:error:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheralManager:didOpenL2CAPChannel:error:"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate~1peripheralManager(_:didUnpublishL2CAPChannel:error:)/title","op":"replace","value":"peripheralManager:didUnpublishL2CAPChannel:error:"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate~1peripheralManager(_:didUnpublishL2CAPChannel:error:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"peripheralManager:didUnpublishL2CAPChannel:error:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate/title","op":"replace","value":"CBPeripheralManagerDelegate"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate/fragments","op":"replace","value":[{"text":"CBPeripheralManagerDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate/navigatorTitle","op":"replace","value":[{"text":"CBPeripheralManagerDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager/title","op":"replace","value":"CBPeripheralManager"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager/fragments","op":"replace","value":[{"kind":"identifier","text":"CBPeripheralManager"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager/navigatorTitle","op":"replace","value":[{"text":"CBPeripheralManager","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPPSM/title","op":"replace","value":"CBL2CAPPSM"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPPSM/fragments","op":"replace","value":[{"text":"CBL2CAPPSM","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPPSM/navigatorTitle","op":"replace","value":[{"text":"CBL2CAPPSM","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1publishL2CAPChannel(withEncryption:)/title","op":"replace","value":"publishL2CAPChannelWithEncryption:"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1publishL2CAPChannel(withEncryption:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"publishL2CAPChannelWithEncryption:"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate~1peripheralManager(_:didPublishL2CAPChannel:error:)/title","op":"replace","value":"peripheralManager:didPublishL2CAPChannel:error:"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate~1peripheralManager(_:didPublishL2CAPChannel:error:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"peripheralManager:didPublishL2CAPChannel:error:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}