{
  "abstract": [
    {
      "text": "Resolves a detent to its value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/Detent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetent/resolvedValueInContext:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UISheetPresentationControllerDetent(im)resolvedValueInContext:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "resolvedValueInContext:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "resolvedValueInContext:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "resolvedValueInContext:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGFloat",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "resolvedValueInContext:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)UISheetPresentationControllerDetentResolutionContext",
              "text": "id<UISheetPresentationControllerDetentResolutionContext>"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A context for resolving custom detent values. This context is available in the ",
                  "type": "text"
                },
                {
                  "code": "resolver",
                  "type": "codeVoice"
                },
                {
                  "text": " block of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetent/customDetentWithIdentifier:resolver:",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgfloat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that represents the value of the detent, or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetentInactive",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the detent is inactive in the provided context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use this method to get the values of the system ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/Detent/Identifier-swift.struct/medium",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/Detent/Identifier-swift.struct/large",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " detents, or the value of a custom detent. Use this method inside ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetent/customDetentWithIdentifier:resolver:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to construct a custom detent according to the values of known detents.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cgfloat": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgfloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/Detent": {
      "abstract": [
        {
          "text": "An object that represents a height where a sheet naturally rests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Detent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/Detent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Detent"
        }
      ],
      "role": "symbol",
      "title": "UISheetPresentationController.Detent",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/detent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/Detent/Identifier-swift.struct/large": {
      "abstract": [
        {
          "text": "The identifier for the system’s large detent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "large"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISheetPresentationController",
          "text": "UISheetPresentationController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISheetPresentationControllerDetent",
          "text": "Detent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UISheetPresentationControllerDetentIdentifier",
          "text": "Identifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/Detent/Identifier-swift.struct/large",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISheetPresentationControllerDetentIdentifierLarge"
        }
      ],
      "role": "symbol",
      "title": "large",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/detent/identifier-swift.struct/large"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/Detent/Identifier-swift.struct/medium": {
      "abstract": [
        {
          "text": "The identifier for the system’s medium detent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISheetPresentationController",
          "text": "UISheetPresentationController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISheetPresentationControllerDetent",
          "text": "Detent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UISheetPresentationControllerDetentIdentifier",
          "text": "Identifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/Detent/Identifier-swift.struct/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISheetPresentationControllerDetentIdentifierMedium"
        }
      ],
      "role": "symbol",
      "title": "medium",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/detent/identifier-swift.struct/medium"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetent/customDetentWithIdentifier:resolver:": {
      "abstract": [
        {
          "text": "Creates a custom detent for a sheet by computing its value according to the properties of the provided context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "customDetentWithIdentifier:resolver:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetent/customDetentWithIdentifier:resolver:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customDetentWithIdentifier:resolver:"
        }
      ],
      "role": "symbol",
      "title": "customDetentWithIdentifier:resolver:",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontrollerdetent/customdetentwithidentifier:resolver:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetent/resolvedValueInContext:": {
      "abstract": [
        {
          "text": "Resolves a detent to its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "resolvedValueInContext:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetent/resolvedValueInContext:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolvedValueInContext:"
        }
      ],
      "role": "symbol",
      "title": "resolvedValueInContext:",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontrollerdetent/resolvedvalueincontext:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetentInactive": {
      "abstract": [
        {
          "text": "A value that represents an inactive detent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UISheetPresentationControllerDetentInactive"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetentInactive",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISheetPresentationControllerDetentInactive",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontrollerdetentinactive"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetentResolutionContext": {
      "abstract": [
        {
          "text": "A context for resolving custom detent values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISheetPresentationControllerDetentResolutionContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetentResolutionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISheetPresentationControllerDetentResolutionContext"
        }
      ],
      "role": "symbol",
      "title": "UISheetPresentationControllerDetentResolutionContext",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontrollerdetentresolutioncontext"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-custom-detent",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetent/customDetentWithIdentifier:resolver:",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetentResolutionContext",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerDetentInactive"
      ],
      "title": "Creating a custom detent"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1Detent~1Identifier-swift.struct~1large/title",
          "value": "UISheetPresentationControllerDetentIdentifierLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1Detent~1Identifier-swift.struct~1large/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISheetPresentationControllerDetentIdentifierLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationControllerDetentResolutionContext/title",
          "value": "UISheetPresentationControllerDetentResolutionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationControllerDetentResolutionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISheetPresentationControllerDetentResolutionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationControllerDetentResolutionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISheetPresentationControllerDetentResolutionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1Detent/title",
          "value": "UISheetPresentationControllerDetent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1Detent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISheetPresentationControllerDetent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1Detent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISheetPresentationControllerDetent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1Detent~1Identifier-swift.struct~1medium/title",
          "value": "UISheetPresentationControllerDetentIdentifierMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1Detent~1Identifier-swift.struct~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISheetPresentationControllerDetentIdentifierMedium"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisheetpresentationcontrollerdetent/resolvedvalueincontext:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
