{
  "abstract": [
    {
      "text": "A 2-bit indexed pixel format with white equal to zero.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format2IndexedGray_WhiteIsZero"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So22vImageCVImageFormatRefa10AccelerateE0C0O30format2IndexedGray_WhiteIsZeroyA2EmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "format2IndexedGray_WhiteIsZero"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "vImageCVImageFormat.Format.format2IndexedGray_WhiteIsZero"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "format2IndexedGray_WhiteIsZero"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This pixel format supports color spaces that are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcolorspacemodel/indexed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat": {
      "abstract": [
        {
          "text": "A mutable description of image encoding in a Core Video pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format": {
      "abstract": [
        {
          "text": "Constants that specify the format of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat.Format",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format1IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "A 1-bit indexed pixel format with white equal to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format1IndexedGray_WhiteIsZero"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format1IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format1IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format1indexedgray_whiteiszero"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format1Monochrome": {
      "abstract": [
        {
          "text": "A 1-bit indexed pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format1Monochrome"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format1Monochrome",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format1Monochrome",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format1monochrome"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format2Indexed": {
      "abstract": [
        {
          "text": "A 2-bit indexed pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format2Indexed"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format2Indexed",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format2Indexed",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format2indexed"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format2IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "A 2-bit indexed pixel format with white equal to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format2IndexedGray_WhiteIsZero"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format2IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format2IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format2indexedgray_whiteiszero"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format4Indexed": {
      "abstract": [
        {
          "text": "A 4-bit indexed pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format4Indexed"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format4Indexed",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format4Indexed",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format4indexed"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format4IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "A 4-bit indexed pixel format with white equal to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format4IndexedGray_WhiteIsZero"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format4IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format4IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format4indexedgray_whiteiszero"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format8Indexed": {
      "abstract": [
        {
          "text": "An 8-bit indexed pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format8Indexed"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format8Indexed",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format8Indexed",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format8indexed"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format8IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "An 8-bit indexed pixel format with white equal to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format8IndexedGray_WhiteIsZero"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format8IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format8IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format8indexedgray_whiteiszero"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgcolorspacemodel/indexed": {
      "abstract": [
        {
          "text": "An indexed color space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "case "
        },
        {
          "kind": "identifier",
          "text": "indexed"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcolorspacemodel/indexed",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGColorSpaceModel.indexed",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcolorspacemodel/indexed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Indexed-color-format-constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format1Monochrome",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format1IndexedGray_WhiteIsZero",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format2Indexed",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format4Indexed",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format4IndexedGray_WhiteIsZero",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format8Indexed",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format8IndexedGray_WhiteIsZero"
      ],
      "title": "Indexed color format constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcolorspacemodel~1indexed/title",
          "value": "kCGColorSpaceModelIndexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/title",
          "value": "vImageCVImageFormatRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimagecvimageformat/format/format2indexedgray_whiteiszero"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
