{
  "abstract": [
    {
      "text": "A video-range, two-plane YpCbCr 4:2:2 pixel format with 10 bits per channel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr10BiPlanarVideoRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So22vImageCVImageFormatRefa10AccelerateE0C0O35format422YpCbCr10BiPlanarVideoRangeyA2EmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "format422YpCbCr10BiPlanarVideoRange"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "vImageCVImageFormat.Format.format422YpCbCr10BiPlanarVideoRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "format422YpCbCr10BiPlanarVideoRange"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This format defines luminance and chrominance data in the range ",
              "type": "text"
            },
            {
              "code": "64...940",
              "type": "codeVoice"
            },
            {
              "text": ", and stores 10 bits in the most significant bits of 16 bits.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat": {
      "abstract": [
        {
          "text": "A mutable description of image encoding in a Core Video pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format": {
      "abstract": [
        {
          "text": "Constants that specify the format of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat.Format",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr10": {
      "abstract": [
        {
          "text": "A component YpCbCr 4:2:2 pixel format with 10 bits per channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format422YpCbCr10"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr10",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format422YpCbCr10",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format422ypcbcr10"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr10BiPlanarFullRange": {
      "abstract": [
        {
          "text": "A full-range, two-plane YpCbCr 4:2:2 pixel format with 10 bits per channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format422YpCbCr10BiPlanarFullRange"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr10BiPlanarFullRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format422YpCbCr10BiPlanarFullRange",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format422ypcbcr10biplanarfullrange"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr10BiPlanarVideoRange": {
      "abstract": [
        {
          "text": "A video-range, two-plane YpCbCr 4:2:2 pixel format with 10 bits per channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format422YpCbCr10BiPlanarVideoRange"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr10BiPlanarVideoRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format422YpCbCr10BiPlanarVideoRange",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format422ypcbcr10biplanarvideorange"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr16": {
      "abstract": [
        {
          "text": "A video-range, two-plane YpCbCr 4:2:2 pixel format with 16 bits per channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format422YpCbCr16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr16",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format422YpCbCr16",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format422ypcbcr16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr8": {
      "abstract": [
        {
          "text": "A component YpCbCr 4:2:2 pixel format with 8 bits per channel and ordered CbYp₀CrYp₁.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format422YpCbCr8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr8",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format422YpCbCr8",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format422ypcbcr8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr8FullRange": {
      "abstract": [
        {
          "text": "A full-range, component YpCbCr 4:2:2 pixel format with 8 bits per channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format422YpCbCr8FullRange"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr8FullRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format422YpCbCr8FullRange",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format422ypcbcr8fullrange"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr8_yuvs": {
      "abstract": [
        {
          "text": "A component YpCbCr 4:2:2 pixel format with 8 bits per channel and ordered Yp₀CbYp₁Cr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format422YpCbCr8_yuvs"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr8_yuvs",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat.Format.format422YpCbCr8_yuvs",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat/format/format422ypcbcr8_yuvs"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "422-YpCbCr-format-constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr8",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr8_yuvs",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr8FullRange",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr10",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr10BiPlanarFullRange",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat/Format/format422YpCbCr16"
      ],
      "title": "4:2:2 YpCbCr format constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/title",
          "value": "vImageCVImageFormatRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimagecvimageformat/format/format422ypcbcr10biplanarvideorange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
