{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the compiler compiles vertex shaders conservatively to generate consistent position calculations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCompileOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/preserveInvariance"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLCompileOptions(py)preserveInvariance",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "preserveInvariance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "preserveInvariance"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "preserveInvariance"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "preserveInvariance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the Metal shader compiler looks at the position value in all vertex output structures that it compiles. If the position value also has the ",
              "type": "text"
            },
            {
              "code": "[[invariant]]",
              "type": "codeVoice"
            },
            {
              "text": " attribute, the compiler compiles the corresponding vertex shader conservatively to guarantee that the GPU performs the calculations the same way. You need to preserve invariance when your renderer contains multiple render passes and requires the same position calculations in each render pass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions": {
      "abstract": [
        {
          "text": "Compilation settings for a Metal shader library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCompileOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompileOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLCompileOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/enableLogging": {
      "abstract": [
        {
          "text": "A Boolean value that enables shader logging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableLogging"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/enableLogging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableLogging"
        }
      ],
      "role": "symbol",
      "title": "enableLogging",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/enablelogging"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/fastMathEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the compiler can perform optimizations for floating-point arithmetic that may violate the IEEE 754 standard.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fastMathEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/fastMathEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fastMathEnabled"
        }
      ],
      "role": "symbol",
      "title": "fastMathEnabled",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/fastmathenabled"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/languageVersion": {
      "abstract": [
        {
          "text": "The language version for interpreting the library source code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "languageVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLLanguageVersion",
          "text": "MTLLanguageVersion"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/languageVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "languageVersion"
        }
      ],
      "role": "symbol",
      "title": "languageVersion",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/languageversion"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/libraries": {
      "abstract": [
        {
          "text": "An array of dynamic libraries the Metal compiler links against.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "libraries"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDynamicLibrary",
          "text": "MTLDynamicLibrary"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/libraries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "libraries"
        }
      ],
      "role": "symbol",
      "title": "libraries",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/libraries"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/mathFloatingPointFunctions": {
      "abstract": [
        {
          "text": "The FP32 math functions Metal uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mathFloatingPointFunctions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLMathFloatingPointFunctions",
          "text": "MTLMathFloatingPointFunctions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/mathFloatingPointFunctions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mathFloatingPointFunctions"
        }
      ],
      "role": "symbol",
      "title": "mathFloatingPointFunctions",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/mathfloatingpointfunctions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/mathMode": {
      "abstract": [
        {
          "text": "An indication of whether the compiler can perform optimizations for floating-point arithmetic that may violate the IEEE 754 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mathMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLMathMode",
          "text": "MTLMathMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/mathMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mathMode"
        }
      ],
      "role": "symbol",
      "title": "mathMode",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/mathmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/optimizationLevel": {
      "abstract": [
        {
          "text": "An option that tells the compiler what to prioritize when it compiles Metal shader code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optimizationLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLLibraryOptimizationLevel",
          "text": "MTLLibraryOptimizationLevel"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/optimizationLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optimizationLevel"
        }
      ],
      "role": "symbol",
      "title": "optimizationLevel",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/optimizationlevel"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/preprocessorMacros": {
      "abstract": [
        {
          "text": "A list of preprocessor macros to apply when compiling the library source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preprocessorMacros"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/preprocessorMacros",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preprocessorMacros"
        }
      ],
      "role": "symbol",
      "title": "preprocessorMacros",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/preprocessormacros"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/preserveInvariance": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the compiler compiles vertex shaders conservatively to generate consistent position calculations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preserveInvariance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/preserveInvariance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preserveInvariance"
        }
      ],
      "role": "symbol",
      "title": "preserveInvariance",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/preserveinvariance"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Compiler-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/enableLogging",
        "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/mathMode",
        "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/mathFloatingPointFunctions",
        "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/languageVersion",
        "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/preprocessorMacros",
        "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/optimizationLevel",
        "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/libraries",
        "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/fastMathEnabled"
      ],
      "title": "Configuring the Compiler Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "preserveInvariance"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preserveInvariance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLCompileOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Compiler-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/enableLogging",
                "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/mathMode",
                "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/mathFloatingPointFunctions",
                "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/languageVersion",
                "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/preprocessorMacros",
                "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/optimizationLevel",
                "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/libraries",
                "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/fastMathEnabled"
              ],
              "title": "Configuring the Compiler Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "preserveInvariance"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1preprocessorMacros/title",
          "value": "preprocessorMacros"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1preprocessorMacros/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preprocessorMacros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1enableLogging/title",
          "value": "enableLogging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1enableLogging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enableLogging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1languageVersion/title",
          "value": "languageVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1languageVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "languageVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1mathFloatingPointFunctions/title",
          "value": "mathFloatingPointFunctions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1mathFloatingPointFunctions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mathFloatingPointFunctions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1mathMode/title",
          "value": "mathMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1mathMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mathMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1libraries/title",
          "value": "libraries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1libraries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "libraries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1preserveInvariance/title",
          "value": "preserveInvariance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1preserveInvariance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preserveInvariance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions/title",
          "value": "MTLCompileOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompileOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompileOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1fastMathEnabled/title",
          "value": "fastMathEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1fastMathEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fastMathEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1optimizationLevel/title",
          "value": "optimizationLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1optimizationLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optimizationLevel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcompileoptions/preserveinvariance"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcompileoptions/preserveinvariance"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
