{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeSpentRecoveringFromStall"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVMetricPlayerItemPlaybackSummaryEvent(py)timeSpentRecoveringFromStall",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "timeSpentRecoveringFromStall"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTimeInterval",
        "text": "TimeInterval"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "timeSpentRecoveringFromStall"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "timeSpentRecoveringFromStall"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "timeSpentRecoveringFromStall"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTimeInterval",
              "text": "TimeInterval"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent": {
      "abstract": [
        {
          "text": "An event that represents the combined metrics for the entire playback session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemPlaybackSummaryEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemPlaybackSummaryEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemPlaybackSummaryEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/errorEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetricErrorEvent",
          "text": "AVMetricErrorEvent"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/errorEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errorEvent"
        }
      ],
      "role": "symbol",
      "title": "errorEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/errorevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/mediaResourceRequestCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaResourceRequestCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/mediaResourceRequestCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaResourceRequestCount"
        }
      ],
      "role": "symbol",
      "title": "mediaResourceRequestCount",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/mediaresourcerequestcount"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/playbackDuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/playbackDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackDuration"
        }
      ],
      "role": "symbol",
      "title": "playbackDuration",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/playbackduration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/recoverableErrorCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recoverableErrorCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/recoverableErrorCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recoverableErrorCount"
        }
      ],
      "role": "symbol",
      "title": "recoverableErrorCount",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/recoverableerrorcount"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/stallCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stallCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/stallCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stallCount"
        }
      ],
      "role": "symbol",
      "title": "stallCount",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/stallcount"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeSpentInInitialStartup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeSpentInInitialStartup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeSpentInInitialStartup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeSpentInInitialStartup"
        }
      ],
      "role": "symbol",
      "title": "timeSpentInInitialStartup",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/timespentininitialstartup"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeSpentRecoveringFromStall": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeSpentRecoveringFromStall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeSpentRecoveringFromStall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeSpentRecoveringFromStall"
        }
      ],
      "role": "symbol",
      "title": "timeSpentRecoveringFromStall",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/timespentrecoveringfromstall"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeWeightedAverageBitrate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeWeightedAverageBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeWeightedAverageBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeWeightedAverageBitrate"
        }
      ],
      "role": "symbol",
      "title": "timeWeightedAverageBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/timeweightedaveragebitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeWeightedPeakBitrate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeWeightedPeakBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeWeightedPeakBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeWeightedPeakBitrate"
        }
      ],
      "role": "symbol",
      "title": "timeWeightedPeakBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/timeweightedpeakbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/variantSwitchCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "variantSwitchCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/variantSwitchCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "variantSwitchCount"
        }
      ],
      "role": "symbol",
      "title": "variantSwitchCount",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/variantswitchcount"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "TimeInterval",
      "type": "topic",
      "url": "/documentation/foundation/timeinterval"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-event",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/errorEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/mediaResourceRequestCount",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/playbackDuration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/recoverableErrorCount",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/stallCount",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeSpentInInitialStartup",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeWeightedAverageBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeWeightedPeakBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/variantSwitchCount"
      ],
      "title": "Inspecting the event"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "timeSpentRecoveringFromStall"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeSpentRecoveringFromStall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-event",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/errorEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/mediaResourceRequestCount",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/playbackDuration",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/recoverableErrorCount",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/stallCount",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeSpentInInitialStartup",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeWeightedAverageBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/timeWeightedPeakBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent/variantSwitchCount"
              ],
              "title": "Inspecting the event"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTimeInterval",
                    "text": "NSTimeInterval"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "timeSpentRecoveringFromStall"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1stallCount/title",
          "value": "stallCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1stallCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stallCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1playbackDuration/title",
          "value": "playbackDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1playbackDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1timeSpentInInitialStartup/title",
          "value": "timeSpentInInitialStartup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1timeSpentInInitialStartup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeSpentInInitialStartup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1timeWeightedPeakBitrate/title",
          "value": "timeWeightedPeakBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1timeWeightedPeakBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeWeightedPeakBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1errorEvent/title",
          "value": "errorEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1errorEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errorEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent/title",
          "value": "AVMetricPlayerItemPlaybackSummaryEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemPlaybackSummaryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemPlaybackSummaryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title",
          "value": "NSTimeInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1recoverableErrorCount/title",
          "value": "recoverableErrorCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1recoverableErrorCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recoverableErrorCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1mediaResourceRequestCount/title",
          "value": "mediaResourceRequestCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1mediaResourceRequestCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaResourceRequestCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1timeSpentRecoveringFromStall/title",
          "value": "timeSpentRecoveringFromStall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1timeSpentRecoveringFromStall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeSpentRecoveringFromStall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1variantSwitchCount/title",
          "value": "variantSwitchCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1variantSwitchCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "variantSwitchCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1timeWeightedAverageBitrate/title",
          "value": "timeWeightedAverageBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent~1timeWeightedAverageBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeWeightedAverageBitrate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/timespentrecoveringfromstall"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent/timespentrecoveringfromstall"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
