{
  "abstract": [
    {
      "text": "The peripheral is already advertising.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/alreadyAdvertising"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC7CBErrorLeV18alreadyAdvertisingSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "alreadyAdvertising"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC7CBErrorLeV",
        "text": "CBError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CBError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "alreadyAdvertising"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "alreadyAdvertising"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC7CBErrorLeV",
              "text": "CBError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CBError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct": {
      "abstract": [
        {
          "text": "An error that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "role": "symbol",
      "title": "CBError",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The codes for errors that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/alreadyAdvertising": {
      "abstract": [
        {
          "text": "The peripheral is already advertising.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyAdvertising"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/alreadyAdvertising",
      "kind": "symbol",
      "role": "symbol",
      "title": "alreadyAdvertising",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/alreadyadvertising"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionFailed": {
      "abstract": [
        {
          "text": "The connection failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionFailed",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/connectionfailed"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionLimitReached": {
      "abstract": [
        {
          "text": "The device already has the maximum number of connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionLimitReached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionLimitReached",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionLimitReached",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/connectionlimitreached"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionTimeout": {
      "abstract": [
        {
          "text": "The connection timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionTimeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionTimeout",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/connectiontimeout"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidHandle": {
      "abstract": [
        {
          "text": "The specified attribute handle is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidHandle",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidHandle",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/invalidhandle"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidParameters": {
      "abstract": [
        {
          "text": "The specified parameters are invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidParameters",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/invalidparameters"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/notConnected": {
      "abstract": [
        {
          "text": "The device isn’t currently connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/notConnected",
      "kind": "symbol",
      "role": "symbol",
      "title": "notConnected",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/notconnected"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationCancelled": {
      "abstract": [
        {
          "text": "The error represents a canceled operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "operationCancelled",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/operationcancelled"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationNotSupported": {
      "abstract": [
        {
          "text": "The operation isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "operationNotSupported",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/operationnotsupported"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/outOfSpace": {
      "abstract": [
        {
          "text": "The device has run out of space to complete the intended operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/outOfSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "outOfSpace",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/outofspace"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/peripheralDisconnected": {
      "abstract": [
        {
          "text": "The peripheral disconnected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peripheralDisconnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/peripheralDisconnected",
      "kind": "symbol",
      "role": "symbol",
      "title": "peripheralDisconnected",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/peripheraldisconnected"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/unknown"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknownDevice": {
      "abstract": [
        {
          "text": "The device is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknownDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/unknowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unkownDevice": {
      "abstract": [
        {
          "text": "A misspelled version of the unknown device error code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unkownDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unkownDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "unkownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/unkowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/uuidNotAllowed": {
      "abstract": [
        {
          "text": "The specified UUID isn’t permitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uuidNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/uuidNotAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "uuidNotAllowed",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/uuidnotallowed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknown",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidParameters",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidHandle",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/notConnected",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/outOfSpace",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationCancelled",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionTimeout",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/peripheralDisconnected",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/uuidNotAllowed",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionFailed",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionLimitReached",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationNotSupported",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknownDevice",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unkownDevice"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/title",
          "value": "CBError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cberror-swift.struct/alreadyadvertising"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
