{
  "abstract": [
    {
      "text": "The codes for errors that Core Bluetooth returns during Bluetooth transactions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CBError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CBError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct": {
      "abstract": [
        {
          "text": "An error that Core Bluetooth returns while using Attribute Protocol (ATT).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBATTError"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTError"
        }
      ],
      "role": "symbol",
      "title": "CBATTError",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The possible errors returned by a GATT server (a remote peripheral) during Bluetooth low energy ATT transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Core Bluetooth ATT errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBATTErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CBATTErrorDomain",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterrordomain"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-c.enum/CBErrorUnknownDevice": {
      "abstract": [
        {
          "text": "The device is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CBErrorUnknownDevice"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-c.enum/CBErrorUnknownDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "CBErrorUnknownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-c.enum/cberrorunknowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct": {
      "abstract": [
        {
          "text": "An error that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "role": "symbol",
      "title": "CBError",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The codes for errors that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising": {
      "abstract": [
        {
          "text": "The peripheral is already advertising.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyAdvertising"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorAlreadyAdvertising"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.alreadyAdvertising",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/alreadyadvertising"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed": {
      "abstract": [
        {
          "text": "The connection failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorConnectionFailed"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.connectionFailed",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/connectionfailed"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached": {
      "abstract": [
        {
          "text": "The device already has the maximum number of connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionLimitReached"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorConnectionLimitReached"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.connectionLimitReached",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/connectionlimitreached"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout": {
      "abstract": [
        {
          "text": "The connection timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionTimeout"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorConnectionTimeout"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.connectionTimeout",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/connectiontimeout"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/encryptionTimedOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptionTimedOut"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/encryptionTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorEncryptionTimedOut"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.encryptionTimedOut",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/encryptiontimedout"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle": {
      "abstract": [
        {
          "text": "The specified attribute handle is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHandle"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorInvalidHandle"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.invalidHandle",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/invalidhandle"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters": {
      "abstract": [
        {
          "text": "The specified parameters are invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameters"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorInvalidParameters"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.invalidParameters",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/invalidparameters"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattExceededBackgroundNotificationLimit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leGattExceededBackgroundNotificationLimit"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattExceededBackgroundNotificationLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorLeGattExceededBackgroundNotificationLimit"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.leGattExceededBackgroundNotificationLimit",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/legattexceededbackgroundnotificationlimit"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattNearBackgroundNotificationLimit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leGattNearBackgroundNotificationLimit"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattNearBackgroundNotificationLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorLeGattNearBackgroundNotificationLimit"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.leGattNearBackgroundNotificationLimit",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/legattnearbackgroundnotificationlimit"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected": {
      "abstract": [
        {
          "text": "The device isn’t currently connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnected"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorNotConnected"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.notConnected",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/notconnected"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled": {
      "abstract": [
        {
          "text": "The error represents a canceled operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationCancelled"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorOperationCancelled"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.operationCancelled",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/operationcancelled"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported": {
      "abstract": [
        {
          "text": "The operation isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationNotSupported"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorOperationNotSupported"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.operationNotSupported",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/operationnotsupported"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace": {
      "abstract": [
        {
          "text": "The device has run out of space to complete the intended operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfSpace"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorOutOfSpace"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.outOfSpace",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/outofspace"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peerRemovedPairingInformation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerRemovedPairingInformation"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peerRemovedPairingInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorPeerRemovedPairingInformation"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.peerRemovedPairingInformation",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/peerremovedpairinginformation"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected": {
      "abstract": [
        {
          "text": "The peripheral disconnected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peripheralDisconnected"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorPeripheralDisconnected"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.peripheralDisconnected",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/peripheraldisconnected"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/tooManyLEPairedDevices": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tooManyLEPairedDevices"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/tooManyLEPairedDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorTooManyLEPairedDevices"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.tooManyLEPairedDevices",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/toomanylepaireddevices"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.unknown",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/unknown"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknownDevice": {
      "abstract": [
        {
          "text": "The device is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknownDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/unknowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice": {
      "abstract": [
        {
          "text": "A misspelled version of the unknown device error code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unkownDevice"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorUnkownDevice"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.unkownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/unkowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed": {
      "abstract": [
        {
          "text": "The specified UUID isn’t permitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uuidNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorUUIDNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.uuidNotAllowed",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/uuidnotallowed"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Core Bluetooth errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CBErrorDomain",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknownDevice",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/encryptionTimedOut",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattExceededBackgroundNotificationLimit",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattNearBackgroundNotificationLimit",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peerRemovedPairingInformation",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/tooManyLEPairedDevices"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CBError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-c.enum/CBErrorUnknownDevice",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice"
              ],
              "title": "Error Codes"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/encryptionTimedOut",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattExceededBackgroundNotificationLimit",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattNearBackgroundNotificationLimit",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peerRemovedPairingInformation",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/tooManyLEPairedDevices"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CBError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidParameters/title",
          "value": "CBErrorInvalidParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorInvalidParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1peerRemovedPairingInformation/title",
          "value": "CBErrorPeerRemovedPairingInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1peerRemovedPairingInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorPeerRemovedPairingInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1encryptionTimedOut/title",
          "value": "CBErrorEncryptionTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1encryptionTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorEncryptionTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1leGattExceededBackgroundNotificationLimit/title",
          "value": "CBErrorLeGattExceededBackgroundNotificationLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1leGattExceededBackgroundNotificationLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorLeGattExceededBackgroundNotificationLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1peripheralDisconnected/title",
          "value": "CBErrorPeripheralDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1peripheralDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorPeripheralDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionLimitReached/title",
          "value": "CBErrorConnectionLimitReached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionLimitReached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorConnectionLimitReached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1alreadyAdvertising/title",
          "value": "CBErrorAlreadyAdvertising"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1alreadyAdvertising/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorAlreadyAdvertising"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationCancelled/title",
          "value": "CBErrorOperationCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorOperationCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionFailed/title",
          "value": "CBErrorConnectionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorConnectionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionTimeout/title",
          "value": "CBErrorConnectionTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorConnectionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1outOfSpace/title",
          "value": "CBErrorOutOfSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1outOfSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorOutOfSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unkownDevice/title",
          "value": "CBErrorUnkownDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unkownDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorUnkownDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1uuidNotAllowed/title",
          "value": "CBErrorUUIDNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1uuidNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorUUIDNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationNotSupported/title",
          "value": "CBErrorOperationNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorOperationNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code/title",
          "value": "CBATTError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1tooManyLEPairedDevices/title",
          "value": "CBErrorTooManyLEPairedDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1tooManyLEPairedDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorTooManyLEPairedDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidHandle/title",
          "value": "CBErrorInvalidHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorInvalidHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1leGattNearBackgroundNotificationLimit/title",
          "value": "CBErrorLeGattNearBackgroundNotificationLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1leGattNearBackgroundNotificationLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorLeGattNearBackgroundNotificationLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/title",
          "value": "CBError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unknown/title",
          "value": "CBErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTErrorDomain/title",
          "value": "CBATTErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBErrorDomain/title",
          "value": "CBErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1notConnected/title",
          "value": "CBErrorNotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1notConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorNotConnected"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cberror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cberror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
