{
  "abstract": [
    {
      "text": "Returns an opaque object for use with the Core Services Identity API.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.collaboration/documentation/Collaboration",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/CSIdentity"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBIdentity(py)CSIdentity",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CSIdentity"
      }
    ],
    "modules": [
      {
        "name": "Collaboration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSIdentity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "CSIdentity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CSIdentityRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSIdentityRef",
              "text": "CSIdentityRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSIdentity"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The opaque object for use with the Core Services Identity API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method, along with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/identityWithCSIdentity:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", is used for interoperability with the Core Services Identity API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.collaboration/documentation/Collaboration": {
      "abstract": [
        {
          "text": "Find and access identities, that is, users and groups. Display the Identity Picker, which lets users create and select identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration",
      "kind": "symbol",
      "role": "collection",
      "title": "Collaboration",
      "type": "topic",
      "url": "/documentation/collaboration"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CBIdentity",
          "type": "codeVoice"
        },
        {
          "text": " object is used for accessing the attributes of an identity stored in an identity authority. You can use an identity object for finding identities, and storing them in an access control list (ACL). If you need to edit these attributes, take advantage of the ",
          "type": "text"
        },
        {
          "code": "CSIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class in Core Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBIdentity"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBIdentity"
        }
      ],
      "role": "symbol",
      "title": "CBIdentity",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/CSIdentity": {
      "abstract": [
        {
          "text": "Returns an opaque object for use with the Core Services Identity API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSIdentity"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/CSIdentity",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSIdentity",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity/csidentity"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/identityWithCSIdentity:": {
      "abstract": [
        {
          "text": "Returns an identity object created from the specified Core Services Identity opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "identityWithCSIdentity:"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/identityWithCSIdentity:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identityWithCSIdentity:"
        }
      ],
      "role": "symbol",
      "title": "identityWithCSIdentity:",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity/identitywithcsidentity:"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/persistentReference": {
      "abstract": [
        {
          "text": "Returns a persistent reference to store a reference to an identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentReference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/persistentReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistentReference"
        }
      ],
      "role": "symbol",
      "title": "persistentReference",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity/persistentreference"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CSIdentityRef": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CSIdentity"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CSIdentityRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSIdentity",
      "type": "topic",
      "url": "/documentation/coreservices/csidentity"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Storing-Identities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/persistentReference"
      ],
      "title": "Storing Identities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity/title",
          "value": "CBIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity~1persistentReference/title",
          "value": "persistentReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity~1persistentReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "persistentReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CSIdentityRef/title",
          "value": "CSIdentityRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/collaboration/cbidentity/csidentity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
