{
  "abstract": [
    {
      "text": "Returns an identity object created from the specified Core Services Identity opaque object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.collaboration/documentation/Collaboration",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/identityWithCSIdentity:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBIdentity(cm)identityWithCSIdentity:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "identityWithCSIdentity:"
      }
    ],
    "modules": [
      {
        "name": "Collaboration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "identityWithCSIdentity:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "identityWithCSIdentity:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CBIdentity",
              "text": "CBIdentity"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "identityWithCSIdentity:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CSIdentityRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSIdentityRef",
              "text": "CSIdentityRef"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "csIdentity"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Core Services Identity opaque object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "csIdentity"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The identity object for use with the Collaboration framework.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is used for interoperability with the Core Services Identity API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.collaboration/documentation/Collaboration": {
      "abstract": [
        {
          "text": "Find and access identities, that is, users and groups. Display the Identity Picker, which lets users create and select identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration",
      "kind": "symbol",
      "role": "collection",
      "title": "Collaboration",
      "type": "topic",
      "url": "/documentation/collaboration"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CBIdentity",
          "type": "codeVoice"
        },
        {
          "text": " object is used for accessing the attributes of an identity stored in an identity authority. You can use an identity object for finding identities, and storing them in an access control list (ACL). If you need to edit these attributes, take advantage of the ",
          "type": "text"
        },
        {
          "code": "CSIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class in Core Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBIdentity"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBIdentity"
        }
      ],
      "role": "symbol",
      "title": "CBIdentity",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/identityWithCSIdentity:": {
      "abstract": [
        {
          "text": "Returns an identity object created from the specified Core Services Identity opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "identityWithCSIdentity:"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/identityWithCSIdentity:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identityWithCSIdentity:"
        }
      ],
      "role": "symbol",
      "title": "identityWithCSIdentity:",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity/identitywithcsidentity:"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/init(name:authority:)": {
      "abstract": [
        {
          "text": "Returns the identity object with the given name from the specified identity authority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "authority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBIdentityAuthority",
          "text": "CBIdentityAuthority"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/init(name:authority:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identityWithName:authority:"
        }
      ],
      "role": "symbol",
      "title": "init(name:authority:)",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity/init(name:authority:)"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/init(persistentReference:)": {
      "abstract": [
        {
          "text": "Returns the identity object matching the persistent reference data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "persistentReference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/init(persistentReference:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identityWithPersistentReference:"
        }
      ],
      "role": "symbol",
      "title": "init(persistentReference:)",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity/init(persistentreference:)"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/init(uuidString:authority:)": {
      "abstract": [
        {
          "text": "Returns the identity object with the given UUID from the specified identity authority.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "uuidString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "authority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBIdentityAuthority",
          "text": "CBIdentityAuthority"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/init(uuidString:authority:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identityWithUUIDString:authority:"
        }
      ],
      "role": "symbol",
      "title": "init(uuidString:authority:)",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity/init(uuidstring:authority:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CSIdentityRef": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CSIdentity"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CSIdentityRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSIdentity",
      "type": "topic",
      "url": "/documentation/coreservices/csidentity"
    },
    "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490",
      "title": "Identity Services Programming Guide",
      "titleInlineContent": [
        {
          "text": "Identity Services Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Finding-Identities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/init(name:authority:)",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/init(persistentReference:)",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity/init(uuidString:authority:)"
      ],
      "title": "Finding Identities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity~1init(persistentReference:)/title",
          "value": "identityWithPersistentReference:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity~1init(persistentReference:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "identityWithPersistentReference:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity/title",
          "value": "CBIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity~1init(uuidString:authority:)/title",
          "value": "identityWithUUIDString:authority:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity~1init(uuidString:authority:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "identityWithUUIDString:authority:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CSIdentityRef/title",
          "value": "CSIdentityRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity~1init(name:authority:)/title",
          "value": "identityWithName:authority:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity~1init(name:authority:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "identityWithName:authority:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/collaboration/cbidentity/identitywithcsidentity:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
