{
  "abstract": [
    {
      "text": "An information button that has a dark background.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIButton",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/infoDark"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIButtonType@UIButtonTypeInfoDark",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "infoDark"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIButtonTypeInfoDark"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIButton.ButtonType.infoDark"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "infoDark"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum": {
      "abstract": [
        {
          "text": "Specifies the style of a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "role": "symbol",
      "title": "UIButton.ButtonType",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/close": {
      "abstract": [
        {
          "text": "A close button to dismiss panels and views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "close"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/close",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonTypeClose"
        }
      ],
      "role": "symbol",
      "title": "UIButton.ButtonType.close",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum/close"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/contactAdd": {
      "abstract": [
        {
          "text": "A contact add button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contactAdd"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/contactAdd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonTypeContactAdd"
        }
      ],
      "role": "symbol",
      "title": "UIButton.ButtonType.contactAdd",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum/contactadd"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/custom": {
      "abstract": [
        {
          "text": "No button style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/custom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonTypeCustom"
        }
      ],
      "role": "symbol",
      "title": "UIButton.ButtonType.custom",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum/custom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/detailDisclosure": {
      "abstract": [
        {
          "text": "A detail disclosure button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detailDisclosure"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/detailDisclosure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonTypeDetailDisclosure"
        }
      ],
      "role": "symbol",
      "title": "UIButton.ButtonType.detailDisclosure",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum/detaildisclosure"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/infoDark": {
      "abstract": [
        {
          "text": "An information button that has a dark background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "infoDark"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/infoDark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonTypeInfoDark"
        }
      ],
      "role": "symbol",
      "title": "UIButton.ButtonType.infoDark",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum/infodark"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/infoLight": {
      "abstract": [
        {
          "text": "An information button that has a light background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "infoLight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/infoLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonTypeInfoLight"
        }
      ],
      "role": "symbol",
      "title": "UIButton.ButtonType.infoLight",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum/infolight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/plain": {
      "abstract": [
        {
          "text": "A standard system button without a blurred background view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plain"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/plain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonTypePlain"
        }
      ],
      "role": "symbol",
      "title": "UIButton.ButtonType.plain",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum/plain"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/roundedRect": {
      "abstract": [
        {
          "text": "A rounded-rectangle style button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roundedRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIButtonType",
          "text": "ButtonType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/roundedRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonTypeRoundedRect"
        }
      ],
      "role": "symbol",
      "title": "roundedRect",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum/roundedrect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/system": {
      "abstract": [
        {
          "text": "A system style button, such as those shown in navigation bars and toolbars.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "system"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/system",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonTypeSystem"
        }
      ],
      "role": "symbol",
      "title": "UIButton.ButtonType.system",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttontype-swift.enum/system"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/custom",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/system",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/detailDisclosure",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/infoLight",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/contactAdd",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/plain",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/close",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/roundedRect"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIButtonTypeInfoDark"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypeInfoDark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/custom",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/system",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/detailDisclosure",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/infoLight",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/contactAdd",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/plain",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/close",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/ButtonType-swift.enum/roundedRect"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIButtonTypeInfoDark"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1infoDark/title",
          "value": "UIButtonTypeInfoDark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1infoDark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypeInfoDark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1system/title",
          "value": "UIButtonTypeSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1system/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypeSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1detailDisclosure/title",
          "value": "UIButtonTypeDetailDisclosure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1detailDisclosure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypeDetailDisclosure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum/title",
          "value": "UIButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1plain/title",
          "value": "UIButtonTypePlain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1plain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypePlain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1custom/title",
          "value": "UIButtonTypeCustom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1custom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypeCustom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1roundedRect/title",
          "value": "UIButtonTypeRoundedRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1roundedRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypeRoundedRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1close/title",
          "value": "UIButtonTypeClose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1close/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypeClose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1infoLight/title",
          "value": "UIButtonTypeInfoLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1infoLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypeInfoLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1contactAdd/title",
          "value": "UIButtonTypeContactAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ButtonType-swift.enum~1contactAdd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonTypeContactAdd"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibutton/buttontype-swift.enum/infodark"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uibutton/buttontype-swift.enum/infodark"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
