{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIMenuController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIMenuController/setMenuVisible(_:animated:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMenuVisible"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"menuVisible","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"parameters":[{"name":"menuVisible","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" if the menu should be shown, "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":" if it should be hidden."}]}]},{"name":"animated","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" if the showing or hiding of the menu should be animated, otherwise "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":"."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before showing the menu, be sure to position it relative to the selection. See "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuController/setTargetRect(_:in:)"},{"type":"text","text":" for details. If you do not set the target rect before displaying the menu, it appears at screen coordinates (0.0, 0.0)."}]}]}],"abstract":[{"type":"text","text":"Shows or hides the editing menu, optionally animating the action."}],"sections":[],"kind":"symbol","seeAlsoSections":[{"anchor":"Showing-and-hiding-the-menu","title":"Showing and hiding the menu","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIMenuController/showMenu(from:rect:)","doc://com.apple.uikit/documentation/UIKit/UIMenuController/hideMenu(from:)","doc://com.apple.uikit/documentation/UIKit/UIMenuController/hideMenu()","doc://com.apple.uikit/documentation/UIKit/UIMenuController/isMenuVisible"],"generated":true}],"variants":[{"paths":["/documentation/uikit/uimenucontroller/setmenuvisible(_:animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uimenucontroller/setmenuvisible(_:animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"setMenuVisible(_:animated:)","navigatorTitle":[{"kind":"identifier","text":"setMenuVisible:animated:"}],"symbolKind":"method","platforms":[{"deprecated":false,"name":"iOS","deprecatedAt":"13.0","unavailable":false,"message":"Use showMenuFromView:rect: or hideMenuFromView: instead.","beta":false,"introducedAt":"3.0"},{"deprecated":false,"name":"iPadOS","deprecatedAt":"13.0","unavailable":false,"message":"Use showMenuFromView:rect: or hideMenuFromView: instead.","beta":false,"introducedAt":"3.0"},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.1","message":"Use showMenuFromView:rect: or hideMenuFromView: instead.","unavailable":false,"deprecatedAt":"13.1"}],"externalID":"c:objc(cs)UIMenuController(im)setMenuVisible:animated:","modules":[{"name":"UIKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMenuVisible"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"references":{"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMenuController/hideMenu(from:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuController/hideMenu(from:)","type":"topic","url":"/documentation/uikit/uimenucontroller/hidemenu(from:)","abstract":[],"deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideMenu"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"hideMenuFromView:"}],"title":"hideMenu(from:)","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMenuController/showMenu(from:rect:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showMenu"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":", "},{"text":"rect","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"type":"topic","title":"showMenu(from:rect:)","url":"/documentation/uikit/uimenucontroller/showmenu(from:rect:)","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuController/showMenu(from:rect:)","navigatorTitle":[{"text":"showMenuFromView:rect:","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMenuController/isMenuVisible":{"deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuController/isMenuVisible","abstract":[{"type":"text","text":"The visibility of the editing menu."}],"title":"isMenuVisible","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isMenuVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"menuVisible"}],"role":"symbol","url":"/documentation/uikit/uimenucontroller/ismenuvisible","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIMenuController/setTargetRect(_:in:)":{"role":"symbol","title":"setTargetRect(_:in:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuController/setTargetRect(_:in:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTargetRect"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":")"}],"deprecated":true,"kind":"symbol","url":"/documentation/uikit/uimenucontroller/settargetrect(_:in:)","navigatorTitle":[{"text":"setTargetRect:inView:","kind":"identifier"}],"abstract":[{"text":"Sets the area in a view above or below which the editing menu is positioned.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit/UIMenuController/hideMenu()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hideMenu"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hideMenu"}],"title":"hideMenu()","deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuController/hideMenu()","type":"topic","url":"/documentation/uikit/uimenucontroller/hidemenu()","abstract":[]},"doc://com.apple.uikit/documentation/UIKit/UIMenuController/setMenuVisible(_:animated:)":{"navigatorTitle":[{"text":"setMenuVisible:animated:","kind":"identifier"}],"url":"/documentation/uikit/uimenucontroller/setmenuvisible(_:animated:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMenuVisible","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Shows or hides the editing menu, optionally animating the action.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuController/setMenuVisible(_:animated:)","deprecated":true,"title":"setMenuVisible(_:animated:)","role":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIMenuController":{"abstract":[{"text":"The menu interface for the Cut, Copy, Paste, Select, Select All, and Delete commands.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIMenuController","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuController","type":"topic","deprecated":true,"title":"UIMenuController","kind":"symbol","role":"symbol","url":"/documentation/uikit/uimenucontroller","navigatorTitle":[{"text":"UIMenuController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","deprecatedAt":"13.0","deprecated":false,"introducedAt":"3.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"3.0","unavailable":false,"deprecatedAt":"13.0"},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.1","unavailable":false,"deprecatedAt":"13.1"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"setMenuVisible:animated:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setMenuVisible:animated:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIMenuController"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Showing-and-hiding-the-menu","title":"Showing and hiding the menu","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIMenuController/showMenu(from:rect:)","doc://com.apple.uikit/documentation/UIKit/UIMenuController/hideMenu(from:)","doc://com.apple.uikit/documentation/UIKit/UIMenuController/hideMenu()","doc://com.apple.uikit/documentation/UIKit/UIMenuController/isMenuVisible"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMenuVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":") "},{"text":"menuVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"animated:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"name":"menuVisible","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":" if the menu should be shown, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":" if it should be hidden.","type":"text"}]}]},{"name":"animated","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"text":" if the showing or hiding of the menu should be animated, otherwise ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"text":".","type":"text"}]}]}]},"path":"/primaryContentSections/1","op":"replace"},{"op":"add","value":[],"path":"/deprecationSummary"},{"op":"replace","value":"hideMenuFromView:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1hideMenu(from:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"hideMenuFromView:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1hideMenu(from:)/fragments"},{"op":"replace","value":"showMenuFromView:rect:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1showMenu(from:rect:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"showMenuFromView:rect:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1showMenu(from:rect:)/fragments"},{"op":"replace","value":"menuVisible","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1isMenuVisible/title"},{"op":"replace","value":[{"kind":"identifier","text":"menuVisible"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1isMenuVisible/fragments"},{"op":"replace","value":"setTargetRect:inView:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1setTargetRect(_:in:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTargetRect:inView:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1setTargetRect(_:in:)/fragments"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1hideMenu()/title","op":"replace","value":"hideMenu"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1hideMenu()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hideMenu"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1setMenuVisible(_:animated:)/title","op":"replace","value":"setMenuVisible:animated:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController~1setMenuVisible(_:animated:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setMenuVisible:animated:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController/title","op":"replace","value":"UIMenuController"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController/fragments","op":"replace","value":[{"kind":"identifier","text":"UIMenuController"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController/navigatorTitle","op":"replace","value":[{"text":"UIMenuController","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}