{
  "abstract": [
    {
      "text": "Positions the text so that the top of the text is on the node’s origin.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/top"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKLabelVerticalAlignmentMode@SKLabelVerticalAlignmentModeTop",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "top"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKLabelVerticalAlignmentModeTop"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKLabelVerticalAlignmentMode.top"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "top"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode": {
      "abstract": [
        {
          "text": "Options for aligning text vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentMode"
        }
      ],
      "role": "symbol",
      "title": "SKLabelVerticalAlignmentMode",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelverticalalignmentmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/baseline": {
      "abstract": [
        {
          "text": "Positions the text so that the font’s baseline lies on the node’s origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseline"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/baseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentModeBaseline"
        }
      ],
      "role": "symbol",
      "title": "SKLabelVerticalAlignmentMode.baseline",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelverticalalignmentmode/baseline"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/bottom": {
      "abstract": [
        {
          "text": "Positions the text so that the bottom of the text is on the node’s origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentModeBottom"
        }
      ],
      "role": "symbol",
      "title": "SKLabelVerticalAlignmentMode.bottom",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelverticalalignmentmode/bottom"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/center": {
      "abstract": [
        {
          "text": "Centers the text vertically on the node’s origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentModeCenter"
        }
      ],
      "role": "symbol",
      "title": "SKLabelVerticalAlignmentMode.center",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelverticalalignmentmode/center"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/top": {
      "abstract": [
        {
          "text": "Positions the text so that the top of the text is on the node’s origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKLabelVerticalAlignmentModeTop"
        }
      ],
      "role": "symbol",
      "title": "SKLabelVerticalAlignmentMode.top",
      "type": "topic",
      "url": "/documentation/spritekit/sklabelverticalalignmentmode/top"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/baseline",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/center",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/bottom"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKLabelVerticalAlignmentModeTop"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentModeTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/baseline",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/center",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKLabelVerticalAlignmentMode/bottom"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKLabelVerticalAlignmentModeTop"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1baseline/title",
          "value": "SKLabelVerticalAlignmentModeBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1baseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentModeBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1center/title",
          "value": "SKLabelVerticalAlignmentModeCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentModeCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode/title",
          "value": "SKLabelVerticalAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1top/title",
          "value": "SKLabelVerticalAlignmentModeTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentModeTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1bottom/title",
          "value": "SKLabelVerticalAlignmentModeBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKLabelVerticalAlignmentMode~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKLabelVerticalAlignmentModeBottom"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/sklabelverticalalignmentmode/top"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/sklabelverticalalignmentmode/top"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
