{
  "abstract": [
    {
      "text": "The placement you prefer when the system activates the window scene.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationRequestOptions/placement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIWindowSceneActivationRequestOptions(py)placement",
    "fragments": [
      {
        "kind": "identifier",
        "text": "placement"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "placement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "placement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-c.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIWindowScenePlacement",
              "text": "UIWindowScenePlacement"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "placement"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Provide a scene placement to influence how the system positions the scene on activation. Set the value to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " to indicate that the system should determine the most appropriate placement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions": {
      "abstract": [
        {
          "text": "An object that contains information you want the system to use when activating a new window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationRequestOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationrequestoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationRequestOptions/placement": {
      "abstract": [
        {
          "text": "The placement you prefer when the system activates the window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "placement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationRequestOptions/placement",
      "kind": "symbol",
      "role": "symbol",
      "title": "placement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneactivationrequestoptions/placement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-c.class": {
      "abstract": [
        {
          "text": "The placement of a window scene in the workspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIWindowScenePlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindowScenePlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneplacement-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneProminentPlacement-c.class": {
      "abstract": [
        {
          "text": "A placement that indicates the system should present the window more prominently than others in the space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneProminentPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneProminentPlacement-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindowSceneProminentPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneprominentplacement-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePushPlacement-c.class": {
      "abstract": [
        {
          "text": "A placement that indicates the system needs to present the window by pushing it onto another window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIWindowScenePushPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePushPlacement-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindowScenePushPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenepushplacement-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneStandardPlacement-c.class": {
      "abstract": [
        {
          "text": "A placement that indicates the system should present the window using the default style of the system in the space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIWindowSceneStandardPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneStandardPlacement-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindowSceneStandardPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenestandardplacement-c.class"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Positioning-windows",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePlacement-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneProminentPlacement-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneStandardPlacement-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScenePushPlacement-c.class"
      ],
      "title": "Positioning windows"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/title",
          "value": "UIWindowSceneActivationRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwindowsceneactivationrequestoptions/placement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
