{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/decrementUseCount()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOSurface(im)decrementUseCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "decrementUseCount"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "decrementUseCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "decrementUseCount()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "decrementUseCount"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface": {
      "abstract": [
        {
          "text": "Data type representing an IOSurface opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurface"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurface"
        }
      ],
      "role": "symbol",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/allAttachments()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allAttachments"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/allAttachments()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allAttachments"
        }
      ],
      "role": "symbol",
      "title": "allAttachments()",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/allattachments()"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/attachment(forKey:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/attachment(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentForKey:"
        }
      ],
      "role": "symbol",
      "title": "attachment(forKey:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/attachment(forkey:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/baseAddressOfPlane(at:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseAddressOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/baseAddressOfPlane(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "baseAddressOfPlaneAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "baseAddressOfPlane(at:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/baseaddressofplane(at:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/bytesPerElementOfPlane(at:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytesPerElementOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/bytesPerElementOfPlane(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bytesPerElementOfPlaneAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "bytesPerElementOfPlane(at:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/bytesperelementofplane(at:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/bytesPerRowOfPlane(at:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytesPerRowOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/bytesPerRowOfPlane(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bytesPerRowOfPlaneAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "bytesPerRowOfPlane(at:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/bytesperrowofplane(at:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/decrementUseCount()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementUseCount"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/decrementUseCount()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decrementUseCount"
        }
      ],
      "role": "symbol",
      "title": "decrementUseCount()",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/decrementusecount()"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/elementHeightOfPlane(at:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementHeightOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/elementHeightOfPlane(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementHeightOfPlaneAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "elementHeightOfPlane(at:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/elementheightofplane(at:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/elementWidthOfPlane(at:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementWidthOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/elementWidthOfPlane(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementWidthOfPlaneAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "elementWidthOfPlane(at:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/elementwidthofplane(at:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/heightOfPlane(at:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heightOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/heightOfPlane(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "heightOfPlaneAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "heightOfPlane(at:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/heightofplane(at:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/incrementUseCount()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incrementUseCount"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/incrementUseCount()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "incrementUseCount"
        }
      ],
      "role": "symbol",
      "title": "incrementUseCount()",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/incrementusecount()"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/lock(options:seed:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOSurfaceLockOptions",
          "text": "IOSurfaceLockOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "seed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@kern_return_t",
          "text": "kern_return_t"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/lock(options:seed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lockWithOptions:seed:"
        }
      ],
      "role": "symbol",
      "title": "lock(options:seed:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/lock(options:seed:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/removeAllAttachments()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllAttachments"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/removeAllAttachments()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllAttachments"
        }
      ],
      "role": "symbol",
      "title": "removeAllAttachments()",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/removeallattachments()"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/removeAttachment(forKey:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/removeAttachment(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAttachmentForKey:"
        }
      ],
      "role": "symbol",
      "title": "removeAttachment(forKey:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/removeattachment(forkey:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setAllAttachments(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAllAttachments"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setAllAttachments(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAllAttachments:"
        }
      ],
      "role": "symbol",
      "title": "setAllAttachments(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/setallattachments(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setAttachment(_:forKey:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setAttachment(_:forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAttachment:forKey:"
        }
      ],
      "role": "symbol",
      "title": "setAttachment(_:forKey:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/setattachment(_:forkey:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setPurgeable(_:oldState:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPurgeable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOSurfacePurgeabilityState",
          "text": "IOSurfacePurgeabilityState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "oldState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOSurfacePurgeabilityState",
          "text": "IOSurfacePurgeabilityState"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@kern_return_t",
          "text": "kern_return_t"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setPurgeable(_:oldState:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPurgeable:oldState:"
        }
      ],
      "role": "symbol",
      "title": "setPurgeable(_:oldState:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface/setpurgeable(_:oldstate:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/allAttachments()",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/attachment(forKey:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/baseAddressOfPlane(at:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/bytesPerElementOfPlane(at:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/bytesPerRowOfPlane(at:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/elementHeightOfPlane(at:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/elementWidthOfPlane(at:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/heightOfPlane(at:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/incrementUseCount()",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/lock(options:seed:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/removeAllAttachments()",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/removeAttachment(forKey:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setAllAttachments(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setAttachment(_:forKey:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setPurgeable(_:oldState:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "decrementUseCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "decrementUseCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iosurface/documentation/IOSurface",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/allAttachments()",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/attachment(forKey:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/baseAddressOfPlane(at:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/bytesPerElementOfPlane(at:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/bytesPerRowOfPlane(at:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/elementHeightOfPlane(at:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/elementWidthOfPlane(at:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/heightOfPlane(at:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/incrementUseCount()",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/lock(options:seed:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/removeAllAttachments()",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/removeAttachment(forKey:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setAllAttachments(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setAttachment(_:forKey:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface/setPurgeable(_:oldState:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "decrementUseCount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1elementWidthOfPlane(at:)/title",
          "value": "elementWidthOfPlaneAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1elementWidthOfPlane(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "elementWidthOfPlaneAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/title",
          "value": "IOSurface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1baseAddressOfPlane(at:)/title",
          "value": "baseAddressOfPlaneAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1baseAddressOfPlane(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "baseAddressOfPlaneAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1bytesPerRowOfPlane(at:)/title",
          "value": "bytesPerRowOfPlaneAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1bytesPerRowOfPlane(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "bytesPerRowOfPlaneAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1elementHeightOfPlane(at:)/title",
          "value": "elementHeightOfPlaneAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1elementHeightOfPlane(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "elementHeightOfPlaneAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1bytesPerElementOfPlane(at:)/title",
          "value": "bytesPerElementOfPlaneAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1bytesPerElementOfPlane(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "bytesPerElementOfPlaneAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1allAttachments()/title",
          "value": "allAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1allAttachments()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "allAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1setAttachment(_:forKey:)/title",
          "value": "setAttachment:forKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1setAttachment(_:forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAttachment:forKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1removeAllAttachments()/title",
          "value": "removeAllAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1removeAllAttachments()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1decrementUseCount()/title",
          "value": "decrementUseCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1decrementUseCount()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "decrementUseCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1setPurgeable(_:oldState:)/title",
          "value": "setPurgeable:oldState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1setPurgeable(_:oldState:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPurgeable:oldState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1setAllAttachments(_:)/title",
          "value": "setAllAttachments:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1setAllAttachments(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAllAttachments:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1incrementUseCount()/title",
          "value": "incrementUseCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1incrementUseCount()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "incrementUseCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1removeAttachment(forKey:)/title",
          "value": "removeAttachmentForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1removeAttachment(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAttachmentForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1heightOfPlane(at:)/title",
          "value": "heightOfPlaneAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1heightOfPlane(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "heightOfPlaneAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1lock(options:seed:)/title",
          "value": "lockWithOptions:seed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1lock(options:seed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lockWithOptions:seed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1attachment(forKey:)/title",
          "value": "attachmentForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface~1attachment(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attachmentForKey:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurface/decrementusecount()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/iosurface/decrementusecount()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
