{
  "abstract": [
    {
      "text": "A playlist with contents that iTunes generates by evaluating a set of rules, such as ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "90s Music",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " or ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "Songs from 1999",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/smart"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ITLibPlaylistKind@ITLibPlaylistKindSmart",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "smart"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibPlaylistKindSmart"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ITLibPlaylistKind.smart"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "smart"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind": {
      "abstract": [
        {
          "text": "These constants specify the possible kinds of playlists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/folder": {
      "abstract": [
        {
          "text": "A playlist folder that the user or iTunes creates, such as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "My Playlist Folder",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Genius Mixes",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "folder"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/folder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindFolder"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.folder",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/folder"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/genius": {
      "abstract": [
        {
          "text": "A playlist iTunes creates of songs that go well with a song the user specifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genius"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/genius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindGenius"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.genius",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/genius"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/geniusMix": {
      "abstract": [
        {
          "text": "An ongoing playlist in a particular genre—like a commercial-free radio station playing the user’s favorite songs—that iTunes creates from music in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geniusMix"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/geniusMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindGeniusMix"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.geniusMix",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/geniusmix"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/regular": {
      "abstract": [
        {
          "text": "A standard playlist that the user or iTunes creates, such as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Music",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Movies",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Pop Mix",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "My Awesome Playlist",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regular"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/regular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindRegular"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.regular",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/regular"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/smart": {
      "abstract": [
        {
          "text": "A playlist with contents that iTunes generates by evaluating a set of rules, such as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "90s Music",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Songs from 1999",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smart"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/smart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindSmart"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.smart",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/smart"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Playlist-Kinds",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/regular",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/genius",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/folder",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/geniusMix"
      ],
      "title": "Playlist Kinds"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibPlaylistKindSmart"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindSmart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Playlist-Kinds",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/regular",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/genius",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/folder",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/geniusMix"
              ],
              "title": "Playlist Kinds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ITLibPlaylistKindSmart"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1geniusMix/title",
          "value": "ITLibPlaylistKindGeniusMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1geniusMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindGeniusMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1smart/title",
          "value": "ITLibPlaylistKindSmart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1smart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindSmart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1regular/title",
          "value": "ITLibPlaylistKindRegular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1regular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindRegular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1genius/title",
          "value": "ITLibPlaylistKindGenius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1genius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindGenius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1folder/title",
          "value": "ITLibPlaylistKindFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1folder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/title",
          "value": "ITLibPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibplaylistkind/smart"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibplaylistkind/smart"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
