{
  "abstract": [
    {
      "text": "Attempts to get symbol information for the address.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolInfo()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTSourceCodeFrame(im)symbolInfoWithError:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "symbolInfo"
      },
      {
        "kind": "text",
        "text": "() "
      },
      {
        "kind": "keyword",
        "text": "throws"
      },
      {
        "kind": "text",
        "text": " -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCTSourceCodeSymbolInfo",
        "text": "XCTSourceCodeSymbolInfo"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "symbolInfoWithError:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "symbolInfo()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "symbolInfo"
            },
            {
              "kind": "text",
              "text": "() "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTSourceCodeSymbolInfo",
              "text": "XCTSourceCodeSymbolInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Symbol information for the address.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method can fail if required symbol data is not available. The system makes only one attempt to retrieve the symbol information. If that attempt fails, the system stores the error and returns it for future requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame": {
      "abstract": [
        {
          "text": "An object that represents a single frame in a call stack that supports retrieval of symbol information for the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeFrame"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeFrame"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeFrame",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodeframe"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/address": {
      "abstract": [
        {
          "text": "An address that represents a specific frame in a call stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "address"
        }
      ],
      "role": "symbol",
      "title": "address",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodeframe/address"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolInfo": {
      "abstract": [
        {
          "text": "Symbolication information for the referenced frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTSourceCodeSymbolInfo",
          "text": "XCTSourceCodeSymbolInfo"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolInfo"
        }
      ],
      "role": "symbol",
      "title": "symbolInfo",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodeframe/symbolinfo"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolInfo()": {
      "abstract": [
        {
          "text": "Attempts to get symbol information for the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolInfo"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTSourceCodeSymbolInfo",
          "text": "XCTSourceCodeSymbolInfo"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolInfo()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolInfoWithError:"
        }
      ],
      "role": "symbol",
      "title": "symbolInfo()",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodeframe/symbolinfo()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolicationError": {
      "abstract": [
        {
          "text": "An optional error that describes a failed symbolication attempt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolicationError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolicationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolicationError"
        }
      ],
      "role": "symbol",
      "title": "symbolicationError",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodeframe/symbolicationerror"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo": {
      "abstract": [
        {
          "text": "An object that contains symbolication information for a specified frame in a call stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeSymbolInfo"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeSymbolInfo"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeSymbolInfo",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodesymbolinfo"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Frame-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/address",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolInfo",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolicationError"
      ],
      "title": "Frame Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "symbolInfoWithError:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "symbolInfoWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Frame-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/address",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolInfo",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame/symbolicationError"
              ],
              "title": "Frame Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)XCTSourceCodeSymbolInfo",
                    "text": "XCTSourceCodeSymbolInfo"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "symbolInfoWithError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Symbol information for the address.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame/title",
          "value": "XCTSourceCodeFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame~1symbolInfo()/title",
          "value": "symbolInfoWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame~1symbolInfo()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "symbolInfoWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeSymbolInfo/title",
          "value": "XCTSourceCodeSymbolInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeSymbolInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeSymbolInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeSymbolInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeSymbolInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame~1symbolInfo/title",
          "value": "symbolInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame~1symbolInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame~1symbolicationError/title",
          "value": "symbolicationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame~1symbolicationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolicationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame~1address/title",
          "value": "address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame~1address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "address"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctsourcecodeframe/symbolinfo()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctsourcecodeframe/symbolinfo()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
