{
  "abstract": [
    {
      "text": "The data that makes up a context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI",
        "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "data",
    "url": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Data-data.dictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "data:classkit_api:Context.Data",
    "fragments": [
      {
        "kind": "text",
        "text": "object "
      },
      {
        "kind": "identifier",
        "text": "Context.Data"
      }
    ],
    "modules": [
      {
        "name": "ClassKit Catalog API"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Context.Data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "ClassKit"
      }
    ],
    "role": "symbol",
    "roleHeading": "Dictionary",
    "symbolKind": "dictionary",
    "title": "Context.Data"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "data"
          ],
          "platforms": [
            "Unsupported OS: classkit_api"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "Context.Data"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A name that the system presents to the user if you choose the custom context type. The API ignores this field if the ",
                  "type": "text"
                },
                {
                  "code": "type",
                  "type": "codeVoice"
                },
                {
                  "text": " field is anything besides ",
                  "type": "text"
                },
                {
                  "code": "custom",
                  "type": "codeVoice"
                },
                {
                  "text": ". For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/customTypeName",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "customTypeName",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ],
          "typeDetails": [
            {
              "baseType": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "default",
              "value": "0"
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The position of a context relative to its siblings. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/displayOrder",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "displayOrder",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "number"
            }
          ],
          "typeDetails": [
            {
              "baseType": "number"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifier path, given as an array of strings, that locates the context within the data store’s context hierarchy. Each string in the array represents a context, starting from the main app context, through any ancestor contexts, down to the child context. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/identifierPath",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Like in your app, limit identifier paths to a maximum of eight entries, and 256 total characters.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Unlike in your app, when communicating with the ClassKit Catalog API, you must explicitly specify the main app context as part of the identifier path.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "identifierPath",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "[string]"
            }
          ],
          "typeDetails": [
            {
              "arrayMode": true,
              "baseType": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "default",
              "value": "true"
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean that indicates whether teachers can assign the context as a task. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/isAssignable",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "isAssignable",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ],
          "typeDetails": [
            {
              "baseType": "boolean"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The kinds of progress reporting that the context can perform. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/progressReportingCapabilities",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "If you don’t include a ",
                  "type": "text"
                },
                {
                  "code": "duration",
                  "type": "codeVoice"
                },
                {
                  "text": " capability when creating a context, the system adds one with an empty ",
                  "type": "text"
                },
                {
                  "code": "details",
                  "type": "codeVoice"
                },
                {
                  "text": " field.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "progressReportingCapabilities",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "["
            },
            {
              "identifier": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Data-data.dictionary/ProgressReportingCapabilities-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:classkit_api:Context.Data.ProgressReportingCapabilities",
              "text": "Context.Data.ProgressReportingCapabilities"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ],
          "typeDetails": [
            {
              "arrayMode": true,
              "baseType": "dictionary"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The range of ages, measured in years, for which you deem a context’s content suitable. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/suggestedAge",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Format the age range as an array with two integers, the first of which indicates a lower bound (set to ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": " to indicate no lower bound), and the second of which indicates an upper bound (set to the maximum value of ",
                  "type": "text"
                },
                {
                  "code": "2^63-2",
                  "type": "codeVoice"
                },
                {
                  "text": " to indicate no upper bound). For example, for ages 4 to 6, set the value to ",
                  "type": "text"
                },
                {
                  "code": "[4, 6]",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "If you don’t set a value for this field, the system assumes suitability for all ages.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "suggestedAge",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "[number]"
            }
          ],
          "typeDetails": [
            {
              "arrayMode": true,
              "baseType": "number"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A suggested time range to complete a task, measured in minutes. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/suggestedCompletionTime",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Format the completion time range as an array with two integers, the first of which indicates a lower bound (set to ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": " to indicate no lower bound), and the second of which indicates an upper bound (set to the maximum value of ",
                  "type": "text"
                },
                {
                  "code": "2^63-2",
                  "type": "codeVoice"
                },
                {
                  "text": " to indicate no upper bound). For example, for a completion time of 10 to 15 minutes, set the value to ",
                  "type": "text"
                },
                {
                  "code": "[10, 15]",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "suggestedCompletionTime",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "[number]"
            }
          ],
          "typeDetails": [
            {
              "arrayMode": true,
              "baseType": "number"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "maximumLength",
              "value": "4000"
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional, user-visible description of the context. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/summary",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "summary",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ],
          "typeDetails": [
            {
              "baseType": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An identifier for the thumbnail associated with the context. To access a thumbnail in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/thumbnail",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "When creating a context, provide an identifier, and then use the same identifier when you upload the corresponding thumbnail image with a call to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Create-or-Replace-a-Thumbnail",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "thumbnailId",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ],
          "typeDetails": [
            {
              "baseType": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "minimumLength",
              "value": "1"
            },
            {
              "kind": "maximumLength",
              "value": "256"
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the context as it appears to users, which must contain at least one non-whitespace character. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/title",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "title",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ],
          "typeDetails": [
            {
              "baseType": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "allowedValues",
              "values": [
                "artsAndMusic",
                "computerScienceAndEngineering",
                "healthAndFitness",
                "literacyAndWriting",
                "math",
                "science",
                "socialScience",
                "worldLanguage"
              ]
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The area of study to which a context relates. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/topic",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "topic",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ],
          "typeDetails": [
            {
              "baseType": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "allowedValues",
              "values": [
                "app",
                "audio",
                "book",
                "challenge",
                "chapter",
                "course",
                "custom",
                "document",
                "exercise",
                "game",
                "lesson",
                "level",
                "none",
                "page",
                "quiz",
                "section",
                "task",
                "video"
              ]
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The kind of content a context represents. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/type",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "type",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ],
          "typeDetails": [
            {
              "baseType": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that leads to the content in your app associated with the current context. For the equivalent property in your app, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/universalLinkURL",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "universalLinkURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ],
          "typeDetails": [
            {
              "baseType": "string"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "attributes": [
        {
          "kind": "allowedTypes",
          "values": []
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/preparing-context-data"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The description for each field includes a link to the equivalent property of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI": {
      "abstract": [
        {
          "text": "Declare the activities supported by your educational app through a web interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit Catalog API",
      "type": "topic",
      "url": "/documentation/classkitcatalogapi"
    },
    "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context": {
      "abstract": [
        {
          "text": "An area of your app that represents an assignable task, like a quiz or a chapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "identifier": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "role": "symbol",
      "title": "Context",
      "type": "topic",
      "url": "/documentation/classkitcatalogapi/context"
    },
    "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Data-data.dictionary": {
      "abstract": [
        {
          "text": "The data that makes up a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Context.Data"
        }
      ],
      "identifier": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Data-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Context.Data"
        }
      ],
      "role": "symbol",
      "title": "Context.Data",
      "type": "topic",
      "url": "/documentation/classkitcatalogapi/context/data-data.dictionary"
    },
    "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Data-data.dictionary/ProgressReportingCapabilities-data.dictionary": {
      "abstract": [
        {
          "text": "The progress reporting capabilities supported by a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Context.Data.ProgressReportingCapabilities"
        }
      ],
      "identifier": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Data-data.dictionary/ProgressReportingCapabilities-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Context.Data.ProgressReportingCapabilities"
        }
      ],
      "role": "symbol",
      "title": "Context.Data.ProgressReportingCapabilities",
      "type": "topic",
      "url": "/documentation/classkitcatalogapi/context/data-data.dictionary/progressreportingcapabilities-data.dictionary"
    },
    "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Metadata-data.dictionary": {
      "abstract": [
        {
          "text": "Information that helps the system categorize a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Context.Metadata"
        }
      ],
      "identifier": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Metadata-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Context.Metadata"
        }
      ],
      "role": "symbol",
      "title": "Context.Metadata",
      "type": "topic",
      "url": "/documentation/classkitcatalogapi/context/metadata-data.dictionary"
    },
    "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Create-or-Replace-a-Thumbnail": {
      "abstract": [
        {
          "text": "Store an image that represents one of your app’s assignable activities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Create-or-Replace-a-Thumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Create or Replace a Thumbnail"
        }
      ],
      "role": "symbol",
      "title": "Create or Replace a Thumbnail",
      "type": "topic",
      "url": "/documentation/classkitcatalogapi/create-or-replace-a-thumbnail"
    },
    "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/preparing-context-data": {
      "abstract": [
        {
          "text": "Adjust how you manage context data when working with the web API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/preparing-context-data",
      "kind": "article",
      "role": "article",
      "title": "Preparing Context Data",
      "type": "topic",
      "url": "/documentation/classkitcatalogapi/preparing-context-data"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext": {
      "abstract": [
        {
          "text": "An area of your app that represents an assignable task, like a quiz or a chapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContext"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLSContext",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/customTypeName": {
      "abstract": [
        {
          "text": "An optional name that the system presents to the user if you choose the custom context type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customTypeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/customTypeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "customTypeName",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/customTypeName"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/displayOrder": {
      "abstract": [
        {
          "text": "The position of a context relative to its siblings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/displayOrder",
      "kind": "symbol",
      "role": "symbol",
      "title": "displayOrder",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/displayOrder"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/identifierPath": {
      "abstract": [
        {
          "text": "The identifier path that locates the context within the data store’s context hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifierPath"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "] { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/identifierPath",
      "kind": "symbol",
      "role": "symbol",
      "title": "identifierPath",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/identifierPath"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/isAssignable": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether teachers can assign the context as a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAssignable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/isAssignable",
      "kind": "symbol",
      "role": "symbol",
      "title": "isAssignable",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/isAssignable"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/progressReportingCapabilities": {
      "abstract": [
        {
          "text": "The kinds of progress reporting that the context can perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progressReportingCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLSProgressReportingCapability",
          "text": "CLSProgressReportingCapability"
        },
        {
          "kind": "text",
          "text": "> { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/progressReportingCapabilities",
      "kind": "symbol",
      "role": "symbol",
      "title": "progressReportingCapabilities",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/progressReportingCapabilities"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/suggestedAge": {
      "abstract": [
        {
          "text": "The range of ages, measured in years, for which you deem a context’s content suitable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suggestedAge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/suggestedAge",
      "kind": "symbol",
      "role": "symbol",
      "title": "suggestedAge",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/suggestedAge"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/suggestedCompletionTime": {
      "abstract": [
        {
          "text": "A suggested time range to complete a task, measured in minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suggestedCompletionTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/suggestedCompletionTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "suggestedCompletionTime",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/suggestedCompletionTime"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/summary": {
      "abstract": [
        {
          "text": "An optional, user-visible description of the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "summary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/summary",
      "kind": "symbol",
      "role": "symbol",
      "title": "summary",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/summary"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/thumbnail": {
      "abstract": [
        {
          "text": "An optional thumbnail image associated with the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbnail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/thumbnail",
      "kind": "symbol",
      "role": "symbol",
      "title": "thumbnail",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/thumbnail"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/title": {
      "abstract": [
        {
          "text": "The name of the context as it appears to users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/title",
      "kind": "symbol",
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/title"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/topic": {
      "abstract": [
        {
          "text": "The area of study to which a context relates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSContextTopic",
          "text": "CLSContextTopic"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/topic",
      "kind": "symbol",
      "role": "symbol",
      "title": "topic",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/topic"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/type": {
      "abstract": [
        {
          "text": "The kind of content a context represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLSContextType",
          "text": "CLSContextType"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/type",
      "kind": "symbol",
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/type"
    },
    "doc://com.apple.documentation/documentation/ClassKit/CLSContext/universalLinkURL": {
      "abstract": [
        {
          "text": "A URL that leads to the content in your app associated with the current context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "universalLinkURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/CLSContext/universalLinkURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "universalLinkURL",
      "type": "topic",
      "url": "/documentation/ClassKit/CLSContext/universalLinkURL"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Metadata-data.dictionary"
      ],
      "title": "Objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Progress-Reporting",
      "identifiers": [
        "doc://com.apple.classkitcatalogapi/documentation/ClassKitCatalogAPI/Context/Data-data.dictionary/ProgressReportingCapabilities-data.dictionary"
      ],
      "title": "Progress Reporting"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1progressReportingCapabilities/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSSet",
              "text": "NSSet<CLSProgressReportingCapability *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "progressReportingCapabilities"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1customTypeName/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "customTypeName"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1suggestedCompletionTime/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readwrite"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@_NSRange",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "suggestedCompletionTime"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1universalLinkURL/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "universalLinkURL"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1thumbnail/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGImageRef",
              "text": "CGImageRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "thumbnail"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1type/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CLSContextType",
              "text": "CLSContextType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1identifierPath/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSString *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "identifierPath"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1isAssignable/title",
          "value": "assignable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1isAssignable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readwrite"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isAssignable"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "assignable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1summary/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "summary"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1topic/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CLSContextTopic",
              "text": "CLSContextTopic"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "topic"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLSContext"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLSObject",
              "text": "CLSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1title/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "title"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1suggestedAge/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readwrite"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@_NSRange",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "suggestedAge"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ClassKit~1CLSContext~1displayOrder/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "displayOrder"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkitcatalogapi/context/data-data.dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "data"
        }
      ]
    }
  ]
}
