{
  "abstract": [
    {
      "text": "Starts formatting the file system with the given options.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSManageableResourceMaintenanceOperations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSManageableResourceMaintenanceOperations/startFormat(task:options:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FSManageableResourceMaintenanceOperations(im)startFormatWithTask:options:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "startFormat"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "task"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)FSTask",
        "text": "FSTask"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)FSTaskOptions",
        "text": "FSTaskOptions"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "throws"
      },
      {
        "kind": "text",
        "text": " -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSProgress",
        "text": "Progress"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startFormatWithTask:options:error:"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "startFormat(task:options:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startFormat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "task"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSTask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)FSTask",
              "text": "FSTask"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSTaskOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)FSTaskOptions",
              "text": "FSTaskOptions"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSProgress",
              "text": "Progress"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A task object you use to communicate back to the client.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "task"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Options for performing the format.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsprogress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that you use to update progress as the format operation progresses. Return ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if starting to format the file system encountered an error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSManageableResourceMaintenanceOperations": {
      "abstract": [
        {
          "text": "Maintenance operations for a file system’s resources.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSManageableResourceMaintenanceOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSManageableResourceMaintenanceOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSManageableResourceMaintenanceOperations"
        }
      ],
      "role": "symbol",
      "title": "FSManageableResourceMaintenanceOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsmanageableresourcemaintenanceoperations"
    },
    "doc://FSKit/documentation/FSKit/FSManageableResourceMaintenanceOperations/startFormat(task:options:)": {
      "abstract": [
        {
          "text": "Starts formatting the file system with the given options.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startFormat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "task"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSTask",
          "text": "FSTask"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSTaskOptions",
          "text": "FSTaskOptions"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSManageableResourceMaintenanceOperations/startFormat(task:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startFormatWithTask:options:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "startFormat(task:options:)",
      "type": "topic",
      "url": "/documentation/fskit/fsmanageableresourcemaintenanceoperations/startformat(task:options:)"
    },
    "doc://FSKit/documentation/FSKit/FSTask": {
      "abstract": [
        {
          "text": "A class that enables a file system module to pass log messages and completion notifications to clients.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSTask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSTask"
        }
      ],
      "role": "symbol",
      "title": "FSTask",
      "type": "topic",
      "url": "/documentation/fskit/fstask"
    },
    "doc://FSKit/documentation/FSKit/FSTaskOptions": {
      "abstract": [
        {
          "text": "A class that passes command options to a task, optionally providing security-scoped URLs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSTaskOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSTaskOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSTaskOptions"
        }
      ],
      "role": "symbol",
      "title": "FSTaskOptions",
      "type": "topic",
      "url": "/documentation/fskit/fstaskoptions"
    },
    "doc://com.apple.documentation/documentation/Swift/Error": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Error",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/foundation/nsprogress": {
      "abstract": [
        {
          "text": "An object that conveys ongoing progress to the user for a specified task.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsprogress",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSProgress",
      "type": "topic",
      "url": "/documentation/foundation/nsprogress"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress": {
      "abstract": [
        {
          "text": "An object that conveys ongoing progress to the user for a specified task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "Progress",
      "type": "topic",
      "url": "/documentation/foundation/progress"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startFormatWithTask:options:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startFormatWithTask:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit",
                "doc://FSKit/documentation/FSKit/FSManageableResourceMaintenanceOperations"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSProgress",
                    "text": "NSProgress"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "startFormatWithTask:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://FSKit/documentation/FSKit/FSTask",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)FSTask",
                    "text": "FSTask"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "task"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "options:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://FSKit/documentation/FSKit/FSTaskOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)FSTaskOptions",
                    "text": "FSTaskOptions"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A task object you use to communicate back to the client.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "task"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Options for performing the format.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "In Objective-C, a pointer to an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". Populate this with any error that occurs when starting the format. In Swift, throw an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/Swift/Error",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " instead.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/foundation/nsprogress",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object that you use to update progress as the format operation progresses. Return ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if starting to format the file system encountered an error.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSManageableResourceMaintenanceOperations~1startFormat(task:options:)/title",
          "value": "startFormatWithTask:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSManageableResourceMaintenanceOperations~1startFormat(task:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startFormatWithTask:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSTaskOptions/title",
          "value": "FSTaskOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSTaskOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSTaskOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSTaskOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSTaskOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSTask/title",
          "value": "FSTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSManageableResourceMaintenanceOperations/title",
          "value": "FSManageableResourceMaintenanceOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSManageableResourceMaintenanceOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSManageableResourceMaintenanceOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSManageableResourceMaintenanceOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSManageableResourceMaintenanceOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSProgress/title",
          "value": "NSProgress"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    },
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsprogress/title",
          "value": "Progress"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsprogress/fragments",
          "value": [
            {
              "kind": "text",
              "text": "class "
            },
            {
              "kind": "identifier",
              "text": "Progress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsmanageableresourcemaintenanceoperations/startformat(task:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsmanageableresourcemaintenanceoperations/startformat(task:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
