{
  "abstract": [
    {
      "text": "A protocol defining subclasses that represent entries made using a handle and a format string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.oslog/documentation/OSLog"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)OSLogEntryWithPayload",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OSLogEntryWithPayload"
      }
    ],
    "modules": [
      {
        "name": "OSLog"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OSLogEntryWithPayload"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "OSLogEntryWithPayload"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OSLogEntryWithPayload"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.oslog/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/oslog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry": {
      "abstract": [
        {
          "text": "A single entry from the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntry"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntry"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity": {
      "abstract": [
        {
          "text": "An entry generated by an activity event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryActivity"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryActivity"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryActivity",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryactivity"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary": {
      "abstract": [
        {
          "text": "The metadata that partitions sequences of other entries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryBoundary"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryBoundary"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryBoundary",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryboundary"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess": {
      "abstract": [
        {
          "text": "A protocol that defines subclasses containing metadata about a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryFromProcess"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryFromProcess"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryFromProcess",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryfromprocess"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog": {
      "abstract": [
        {
          "text": "A log entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryLog"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLog"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost": {
      "abstract": [
        {
          "text": "An entry containing a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntrySignpost"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntrySignpost"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntrySignpost",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrysignpost"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload": {
      "abstract": [
        {
          "text": "A protocol defining subclasses that represent entries made using a handle and a format string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryWithPayload"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryWithPayload"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryWithPayload",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrywithpayload"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/category": {
      "abstract": [
        {
          "text": "The payload’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "category"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/category",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "category"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "category",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrywithpayload/category"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/components": {
      "abstract": [
        {
          "text": "The payload’s components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "components"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSLogMessageComponent",
          "text": "OSLogMessageComponent"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/components",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "components"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "components",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrywithpayload/components"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/formatString": {
      "abstract": [
        {
          "text": "The payload’s format string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/formatString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "formatString"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "formatString",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrywithpayload/formatstring"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/subsystem": {
      "abstract": [
        {
          "text": "The payload’s subsystem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subsystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/subsystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subsystem"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "subsystem",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrywithpayload/subsystem"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Log-Entries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess"
      ],
      "title": "Log Entries"
    }
  ],
  "topicSections": [
    {
      "anchor": "Elements-of-a-Payload",
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/category",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/components",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/formatString",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/subsystem"
      ],
      "title": "Elements of a Payload"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OSLogEntryWithPayload"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryWithPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryWithPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.oslog/documentation/OSLog"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Elements-of-a-Payload",
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/category",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/components",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/formatString",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload/subsystem"
              ],
              "title": "Elements of a Payload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Log-Entries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess"
              ],
              "title": "Log Entries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OSLogEntryWithPayload"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload~1components/title",
          "value": "components"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload~1components/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload~1formatString/title",
          "value": "formatString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload~1formatString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "formatString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload~1category/title",
          "value": "category"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload~1category/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "category"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/title",
          "value": "OSLogEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/title",
          "value": "OSLogEntryFromProcess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryFromProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryFromProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/title",
          "value": "OSLogEntryLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryActivity/title",
          "value": "OSLogEntryActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryBoundary/title",
          "value": "OSLogEntryBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryBoundary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload/title",
          "value": "OSLogEntryWithPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryWithPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryWithPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload~1subsystem/title",
          "value": "subsystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload~1subsystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subsystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntrySignpost/title",
          "value": "OSLogEntrySignpost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntrySignpost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntrySignpost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntrySignpost/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntrySignpost"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/oslog/oslogentrywithpayload"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/oslog/oslogentrywithpayload"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
