{
  "abstract": [
    {
      "text": "A single entry from the unified logging system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.oslog/documentation/OSLog"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)OSLogEntry",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OSLogEntry"
      }
    ],
    "modules": [
      {
        "name": "OSLog"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OSLogEntry"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "OSLogEntry"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.oslog/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/oslog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry": {
      "abstract": [
        {
          "text": "A single entry from the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntry"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntry"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum": {
      "abstract": [
        {
          "text": "A classification of how the entry was to be stored and rotated at the point when it was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StoreCategory"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StoreCategory"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/composedMessage": {
      "abstract": [
        {
          "text": "The fully formatted message for the entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composedMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/composedMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "composedMessage"
        }
      ],
      "role": "symbol",
      "title": "composedMessage",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/composedmessage"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/date": {
      "abstract": [
        {
          "text": "The timestamp of the entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/date",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "date"
        }
      ],
      "role": "symbol",
      "title": "date",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/date"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/init(coder:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/init(coder:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/init(coder:)"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/storeCategory-swift.property": {
      "abstract": [
        {
          "text": "The current log entry’s storage tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSLogEntry",
          "text": "OSLogEntry"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSLogEntryStoreCategory",
          "text": "StoreCategory"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/storeCategory-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeCategory"
        }
      ],
      "role": "symbol",
      "title": "storeCategory",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.property"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity": {
      "abstract": [
        {
          "text": "An entry generated by an activity event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryActivity"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryActivity"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryActivity",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryactivity"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary": {
      "abstract": [
        {
          "text": "The metadata that partitions sequences of other entries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryBoundary"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryBoundary"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryBoundary",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryboundary"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess": {
      "abstract": [
        {
          "text": "A protocol that defines subclasses containing metadata about a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryFromProcess"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryFromProcess"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryFromProcess",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryfromprocess"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog": {
      "abstract": [
        {
          "text": "A log entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryLog"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLog"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost": {
      "abstract": [
        {
          "text": "An entry containing a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntrySignpost"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntrySignpost"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntrySignpost",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrysignpost"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload": {
      "abstract": [
        {
          "text": "A protocol defining subclasses that represent entries made using a handle and a format string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryWithPayload"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryWithPayload"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryWithPayload",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrywithpayload"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Log-Entries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload"
      ],
      "title": "Log Entries"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Log-Entry-Data",
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/composedMessage",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/date"
      ],
      "title": "Accessing Log Entry Data"
    },
    {
      "anchor": "Accessing-Store-Categories",
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/storeCategory-swift.property",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum"
      ],
      "title": "Accessing Store Categories"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/init(coder:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OSLogEntry"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.oslog/documentation/OSLog"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Log-Entry-Data",
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/composedMessage",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/date"
              ],
              "title": "Accessing Log Entry Data"
            },
            {
              "anchor": "Accessing-Store-Categories",
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/storeCategory-swift.property",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum"
              ],
              "title": "Accessing Store Categories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Log-Entries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload"
              ],
              "title": "Log Entries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OSLogEntry"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1date/title",
          "value": "date"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1date/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum/title",
          "value": "OSLogEntryStoreCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/title",
          "value": "OSLogEntryFromProcess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryFromProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryFromProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntrySignpost/title",
          "value": "OSLogEntrySignpost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntrySignpost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntrySignpost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntrySignpost/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntrySignpost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/title",
          "value": "OSLogEntryLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/title",
          "value": "OSLogEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1storeCategory-swift.property/title",
          "value": "storeCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1storeCategory-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storeCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload/title",
          "value": "OSLogEntryWithPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryWithPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryWithPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryBoundary/title",
          "value": "OSLogEntryBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryBoundary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1composedMessage/title",
          "value": "composedMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1composedMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "composedMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryActivity/title",
          "value": "OSLogEntryActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryActivity"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/oslog/oslogentry"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/oslog/oslogentry"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
