{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode/sessionNotActive"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKVehicleConnectionErrorCode@PKVehicleConnectionErrorCodeSessionNotActive",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sessionNotActive"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKVehicleConnectionErrorCodeSessionNotActive"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKVehicleConnectionErrorCode.sessionNotActive"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sessionNotActive"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionErrorCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionErrorCode"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionErrorCode",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionerrorcode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode/sessionNotActive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotActive"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode/sessionNotActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionErrorCodeSessionNotActive"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionErrorCode.sessionNotActive",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionerrorcode/sessionnotactive"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKVehicleConnectionErrorCodeSessionNotActive"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionErrorCodeSessionNotActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKVehicleConnectionErrorCodeSessionNotActive"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode~1sessionNotActive/title",
          "value": "PKVehicleConnectionErrorCodeSessionNotActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode~1sessionNotActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionErrorCodeSessionNotActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode/title",
          "value": "PKVehicleConnectionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkvehicleconnectionerrorcode/sessionnotactive"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkvehicleconnectionerrorcode/sessionnotactive"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
