{
  "abstract": [
    {
      "text": "Suggests shortcuts the user may want to add to Siri.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter/setShortcutSuggestions(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INVoiceShortcutCenter(im)setShortcutSuggestions:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setShortcutSuggestions"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7Intents10INShortcutO",
        "text": "INShortcut"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setShortcutSuggestions:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setShortcutSuggestions(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setShortcutSuggestions"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "suggestions"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7Intents10INShortcutO",
              "text": "INShortcut"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A list of suggested shortcuts that the Settings app shows to the user in the ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "Siri & Search",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " section.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "suggestions"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To replace the list of shortcut suggestions, call setShortcutSuggestions(_:), passing in a new list of suggestions. To remove suggestions made by your app, call the same method, passing in an empty array. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Changes to the list of shortcut suggestions don’t effect shortcuts that the user added to Siri.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/SiriKit/offering-actions-in-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Suggest shortcuts users may want to add to Siri or combine with other actions in their own shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Offering Actions in the Shortcuts App",
      "type": "topic",
      "url": "/documentation/SiriKit/offering-actions-in-the-shortcuts-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum": {
      "abstract": [
        {
          "text": "An action available in your app that the system may suggest to a user or a user may add to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcut"
        }
      ],
      "role": "symbol",
      "title": "INShortcut",
      "type": "topic",
      "url": "/documentation/intents/inshortcut-swift.enum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutReference": {
      "abstract": [
        {
          "text": "An object representing an action available in your app that the system may suggest to a user or a user may add to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcutReference"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutReference"
        }
      ],
      "role": "symbol",
      "title": "INShortcutReference",
      "type": "topic",
      "url": "/documentation/intents/inshortcutreference"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter": {
      "abstract": [
        {
          "text": "Retrieve the user’s shortcuts and make shortcut suggestions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVoiceShortcutCenter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVoiceShortcutCenter"
        }
      ],
      "role": "symbol",
      "title": "INVoiceShortcutCenter",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcutcenter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter/setShortcutSuggestions(_:)": {
      "abstract": [
        {
          "text": "Suggests shortcuts the user may want to add to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setShortcutSuggestions"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Intents10INShortcutO",
          "text": "INShortcut"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter/setShortcutSuggestions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setShortcutSuggestions:"
        }
      ],
      "role": "symbol",
      "title": "setShortcutSuggestions(_:)",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcutcenter/setshortcutsuggestions(_:)"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Suggest shortcuts users may want to add to Siri or combine with other actions in their own shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Offering Actions in the Shortcuts App",
      "type": "topic",
      "url": "/documentation/sirikit/offering-actions-in-the-shortcuts-app"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-Suggested-Shortcuts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INShortcutReference"
      ],
      "title": "Setting Suggested Shortcuts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setShortcutSuggestions:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setShortcutSuggestions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-Suggested-Shortcuts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INShortcutReference"
              ],
              "title": "Setting Suggested Shortcuts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setShortcutSuggestions:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<INShortcut *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "suggestions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A list of suggested shortcuts that the Settings app shows to the user in the ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "Siri & Search",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " section.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "suggestions"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter~1setShortcutSuggestions(_:)/title",
          "value": "setShortcutSuggestions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter~1setShortcutSuggestions(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setShortcutSuggestions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/title",
          "value": "INShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/title",
          "value": "INVoiceShortcutCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcutCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcutCenter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/invoiceshortcutcenter/setshortcutsuggestions(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/invoiceshortcutcenter/setshortcutsuggestions(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
