{
  "abstract": [
    {
      "text": "Returns whether the input value of an element changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/change(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)GCDevicePhysicalInputStateDiff(im)changeForElement:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "change"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
        "text": "GCPhysicalInputElement"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@GCDevicePhysicalInputElementChange",
        "text": "GCDevicePhysicalInputElementChange"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "changeForElement:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "change(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "change"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "element"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
              "text": "GCPhysicalInputElement"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputElementChange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@GCDevicePhysicalInputElementChange",
              "text": "GCDevicePhysicalInputElementChange"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The element whose value changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "element"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Description of the change to the element.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gamecontroller/documentation/GameController/handling-input-events"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputElementChange": {
      "abstract": [
        {
          "text": "Possible values that describe whether the input value of an element changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDevicePhysicalInputElementChange"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputElementChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDevicePhysicalInputElementChange"
        }
      ],
      "role": "symbol",
      "title": "GCDevicePhysicalInputElementChange",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputelementchange"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff": {
      "abstract": [
        {
          "text": "The common functions for objects that contain the differences between a current and previous input state object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDevicePhysicalInputStateDiff"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDevicePhysicalInputStateDiff"
        }
      ],
      "role": "symbol",
      "title": "GCDevicePhysicalInputStateDiff",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstatediff"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/change(for:)": {
      "abstract": [
        {
          "text": "Returns whether the input value of an element changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "change"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
          "text": "GCPhysicalInputElement"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GCDevicePhysicalInputElementChange",
          "text": "GCDevicePhysicalInputElementChange"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/change(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeForElement:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "change(for:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstatediff/change(for:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/changedElements": {
      "abstract": [
        {
          "text": "Returns the elements that changed since the previous input state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "changedElements"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/changedElements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changedElements"
        }
      ],
      "role": "symbol",
      "title": "changedElements",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstatediff/changedelements"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/changedElements()-2zzwm": {
      "abstract": [
        {
          "text": "Returns the elements that changed since the previous input state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changedElements"
        },
        {
          "kind": "text",
          "text": "() -> ("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST",
          "text": "Sequence"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
          "text": "GCPhysicalInputElement"
        },
        {
          "kind": "text",
          "text": ">)?\n"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/changedElements()-2zzwm",
      "kind": "symbol",
      "role": "symbol",
      "title": "changedElements()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstatediff/changedelements()-2zzwm"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/changedElements()-9cdq4": {
      "abstract": [
        {
          "text": "Returns the elements that changed since the previous input state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changedElements"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEnumerator",
          "text": "NSEnumerator"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/changedElements()-9cdq4",
      "kind": "symbol",
      "role": "symbol",
      "title": "changedElements()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstatediff/changedelements()-9cdq4"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement": {
      "abstract": [
        {
          "text": "The common properties of physical input elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElement"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/handling-input-events": {
      "abstract": [
        {
          "text": "Receive controller input using either polling or callbacks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/handling-input-events",
      "kind": "article",
      "role": "article",
      "title": "Handling input events",
      "type": "topic",
      "url": "/documentation/gamecontroller/handling-input-events"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputElementChange",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/changedElements()-9cdq4",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/changedElements()-2zzwm"
      ],
      "title": "Getting changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "changeForElement:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "changeForElement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-changes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputElementChange",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputStateDiff/changedElements"
              ],
              "title": "Getting changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputElementChange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@GCDevicePhysicalInputElementChange",
                    "text": "GCDevicePhysicalInputElementChange"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "changeForElement:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)GCPhysicalInputElement",
                    "text": "id<GCPhysicalInputElement>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "element"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The element whose value changes.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "element"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Description of the change to the element.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement/title",
          "value": "GCPhysicalInputElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputElementChange/title",
          "value": "GCDevicePhysicalInputElementChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputElementChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevicePhysicalInputElementChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputElementChange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevicePhysicalInputElementChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputStateDiff~1change(for:)/title",
          "value": "changeForElement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputStateDiff~1change(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "changeForElement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputStateDiff/title",
          "value": "GCDevicePhysicalInputStateDiff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputStateDiff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevicePhysicalInputStateDiff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputStateDiff/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevicePhysicalInputStateDiff"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcdevicephysicalinputstatediff/change(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcdevicephysicalinputstatediff/change(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
