{
  "abstract": [
    {
      "text": "Constants that represent a hearing device ear.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Accessibility",
    "externalID": "c:@E@AXHearingDeviceEar",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Ear"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Ear"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AXMFiHearingDevice.Ear"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Ear"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXHearingDeviceEar/AXHearingDeviceEarNone": {
      "abstract": [
        {
          "text": "A constant that represents neither ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXHearingDeviceEarNone"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXHearingDeviceEar/AXHearingDeviceEarNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXHearingDeviceEarNone",
      "type": "topic",
      "url": "/documentation/accessibility/axhearingdeviceear/axhearingdeviceearnone"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice": {
      "abstract": [
        {
          "text": "A namespace for hearing device accessibility symbols in Swift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMFiHearingDevice"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMFiHearingDevice"
        }
      ],
      "role": "symbol",
      "title": "AXMFiHearingDevice",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear": {
      "abstract": [
        {
          "text": "Constants that represent a hearing device ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Ear"
        }
      ],
      "role": "symbol",
      "title": "AXMFiHearingDevice.Ear",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/both": {
      "abstract": [
        {
          "text": "A constant that represents both ears.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "both"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AXMFiHearingDevice",
          "text": "AXMFiHearingDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXHearingDeviceEar",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/both",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXHearingDeviceEarBoth"
        }
      ],
      "role": "symbol",
      "title": "both",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear/both"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a structure that represents a hearing device ear with the raw value you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear/init(rawvalue:)"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/left": {
      "abstract": [
        {
          "text": "A constant that represents the left ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AXMFiHearingDevice",
          "text": "AXMFiHearingDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXHearingDeviceEar",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXHearingDeviceEarLeft"
        }
      ],
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear/left"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/right": {
      "abstract": [
        {
          "text": "A constant that represents the right ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AXMFiHearingDevice",
          "text": "AXMFiHearingDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXHearingDeviceEar",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXHearingDeviceEarRight"
        }
      ],
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear/right"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEar()": {
      "abstract": [
        {
          "text": "Returns which ears enable streaming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamingEar"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AXMFiHearingDevice",
          "text": "AXMFiHearingDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXHearingDeviceEar",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEar()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMFiHearingDeviceStreamingEar"
        }
      ],
      "role": "symbol",
      "title": "streamingEar()",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/streamingear()"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEarDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that the system posts when there’s a change to which ears enable streaming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamingEarDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEarDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMFiHearingDeviceStreamingEarDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "streamingEarDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/streamingeardidchangenotification"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Streaming-status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEar()",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEarDidChangeNotification"
      ],
      "title": "Streaming status"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/both",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/left",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/right"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializer",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/init(rawValue:)"
      ],
      "title": "Initializer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AXHearingDeviceEar"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Accessibility/documentation/Accessibility"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXHearingDeviceEar/AXHearingDeviceEarNone",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/both",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/left",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/right"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Streaming-status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEar()",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEarDidChangeNotification"
              ],
              "title": "Streaming status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AXHearingDeviceEar"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1right/title",
          "value": "AXHearingDeviceEarRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEarRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1both/title",
          "value": "AXHearingDeviceEarBoth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1both/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEarBoth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1left/title",
          "value": "AXHearingDeviceEarLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEarLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1streamingEar()/title",
          "value": "AXMFiHearingDeviceStreamingEar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1streamingEar()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMFiHearingDeviceStreamingEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1streamingEarDidChangeNotification/title",
          "value": "AXMFiHearingDeviceStreamingEarDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1streamingEarDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMFiHearingDeviceStreamingEarDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear/title",
          "value": "AXHearingDeviceEar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/axmfihearingdevice/ear"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/axmfihearingdevice/ear"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
