{
  "abstract": [
    {
      "text": "Constants that represent buttons that a person can press.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPress"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIPressType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PressType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PressType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIPress.PressType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PressType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress": {
      "abstract": [
        {
          "text": "An object that represents the presence or movement of a button press on the screen for a particular event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPress"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPress"
        }
      ],
      "role": "symbol",
      "title": "UIPress",
      "type": "topic",
      "url": "/documentation/uikit/uipress"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum": {
      "abstract": [
        {
          "text": "Constants that represent the phases of a button press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "role": "symbol",
      "title": "UIPress.Phase",
      "type": "topic",
      "url": "/documentation/uikit/uipress/phase-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType": {
      "abstract": [
        {
          "text": "Constants that represent buttons that a person can press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PressType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PressType"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/downArrow": {
      "abstract": [
        {
          "text": "A constant that represents the down arrow button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/downArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeDownArrow"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.downArrow",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/downarrow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/leftArrow": {
      "abstract": [
        {
          "text": "A constant that represents the left arrow button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/leftArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeLeftArrow"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.leftArrow",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/leftarrow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/menu": {
      "abstract": [
        {
          "text": "A constant that represents the menu button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/menu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeMenu"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.menu",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/menu"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageDown": {
      "abstract": [
        {
          "text": "A constant that represents the page down button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageDown"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypePageDown"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.pageDown",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/pagedown"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageUp": {
      "abstract": [
        {
          "text": "A constant that represents the page up button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageUp"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypePageUp"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.pageUp",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/pageup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/playPause": {
      "abstract": [
        {
          "text": "A constant that represents the play/pause button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playPause"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/playPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypePlayPause"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.playPause",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/playpause"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/rightArrow": {
      "abstract": [
        {
          "text": "A constant that represents the right arrow button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/rightArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeRightArrow"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.rightArrow",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/rightarrow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/select": {
      "abstract": [
        {
          "text": "A constant that represents the select button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "select"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/select",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeSelect"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.select",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/select"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/tvRemoteFourColors": {
      "abstract": [
        {
          "text": "Represents a button on a TV remote labeled with four colors, analogous to the four separate color buttons found on some TV remotes. When this button is",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "pressed, an app should perform the appropriate color action or if there are multiple color actions available provide UI to choose the specific color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvRemoteFourColors"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/tvRemoteFourColors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeTVRemoteFourColors"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.tvRemoteFourColors",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/tvremotefourcolors"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/tvRemoteOneTwoThree": {
      "abstract": [
        {
          "text": "Represents a button on a TV remote labeled with 123. When this button is pressed, an app should provide UI to enter a specific channel number if channel",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "numbers are available. If no channel numbers exist the app should provide UI to toggle channel category filters, search for channels by name or search for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "currently airing shows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvRemoteOneTwoThree"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/tvRemoteOneTwoThree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeTVRemoteOneTwoThree"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.tvRemoteOneTwoThree",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/tvremoteonetwothree"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/upArrow": {
      "abstract": [
        {
          "text": "A constant that represents the up arrow button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/upArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeUpArrow"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.upArrow",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/uparrow"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Actions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/playPause",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/select",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/menu"
      ],
      "title": "Actions"
    },
    {
      "anchor": "Navigation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/upArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/downArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/leftArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/rightArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageDown",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageUp"
      ],
      "title": "Navigation"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/tvRemoteFourColors",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/tvRemoteOneTwoThree"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPressType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Actions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/playPause",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/select",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/menu"
              ],
              "title": "Actions"
            },
            {
              "anchor": "Navigation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/upArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/downArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/leftArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/rightArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageDown",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageUp"
              ],
              "title": "Navigation"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/tvRemoteFourColors",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/tvRemoteOneTwoThree"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPress/Phase-swift.enum"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIPressType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1tvRemoteFourColors/title",
          "value": "UIPressTypeTVRemoteFourColors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1tvRemoteFourColors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeTVRemoteFourColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum/title",
          "value": "UIPressPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1Phase-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1playPause/title",
          "value": "UIPressTypePlayPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1playPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypePlayPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1select/title",
          "value": "UIPressTypeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1select/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1upArrow/title",
          "value": "UIPressTypeUpArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1upArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeUpArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1menu/title",
          "value": "UIPressTypeMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1menu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1tvRemoteOneTwoThree/title",
          "value": "UIPressTypeTVRemoteOneTwoThree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1tvRemoteOneTwoThree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeTVRemoteOneTwoThree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1pageDown/title",
          "value": "UIPressTypePageDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1pageDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypePageDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1leftArrow/title",
          "value": "UIPressTypeLeftArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1leftArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeLeftArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress/title",
          "value": "UIPress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1downArrow/title",
          "value": "UIPressTypeDownArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1downArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeDownArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType/title",
          "value": "UIPressType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1rightArrow/title",
          "value": "UIPressTypeRightArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1rightArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeRightArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1pageUp/title",
          "value": "UIPressTypePageUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1pageUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypePageUp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipress/presstype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipress/presstype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
