{
  "abstract": [
    {
      "text": "The payload to use for accessory setup.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/payload"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HMAccessorySetupRequest(py)payload",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "payload"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HMAccessorySetupPayload",
        "text": "HMAccessorySetupPayload"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "payload"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "payload"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "payload"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupPayload",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HMAccessorySetupPayload",
              "text": "HMAccessorySetupPayload"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupPayload",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupPayload": {
      "abstract": [
        {
          "text": "A payload for authenticating a HomeKit accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessorySetupPayload"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessorySetupPayload"
        }
      ],
      "role": "symbol",
      "title": "HMAccessorySetupPayload",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetuppayload"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest": {
      "abstract": [
        {
          "text": "An object that describes how to add and setup up new accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessorySetupRequest"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessorySetupRequest"
        }
      ],
      "role": "symbol",
      "title": "HMAccessorySetupRequest",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetuprequest"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/homeUniqueIdentifier": {
      "abstract": [
        {
          "text": "The identifier corresponding to the home that the accessory should be added to when being set up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeUniqueIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/homeUniqueIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "homeUniqueIdentifier"
        }
      ],
      "role": "symbol",
      "title": "homeUniqueIdentifier",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetuprequest/homeuniqueidentifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/payload": {
      "abstract": [
        {
          "text": "The payload to use for accessory setup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessorySetupPayload",
          "text": "HMAccessorySetupPayload"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/payload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "payload"
        }
      ],
      "role": "symbol",
      "title": "payload",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetuprequest/payload"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/suggestedAccessoryName": {
      "abstract": [
        {
          "text": "The name that the framework suggests when the user names the accessory being set up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suggestedAccessoryName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/suggestedAccessoryName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestedAccessoryName"
        }
      ],
      "role": "symbol",
      "title": "suggestedAccessoryName",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetuprequest/suggestedaccessoryname"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/suggestedRoomUniqueIdentifier": {
      "abstract": [
        {
          "text": "The identifier corresponding to the room that the framework suggests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suggestedRoomUniqueIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/suggestedRoomUniqueIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestedRoomUniqueIdentifier"
        }
      ],
      "role": "symbol",
      "title": "suggestedRoomUniqueIdentifier",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetuprequest/suggestedroomuniqueidentifier"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-up-accessorices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/homeUniqueIdentifier",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/suggestedAccessoryName",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/suggestedRoomUniqueIdentifier"
      ],
      "title": "Setting up accessorices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "payload"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "payload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-up-accessorices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/homeUniqueIdentifier",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/suggestedAccessoryName",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest/suggestedRoomUniqueIdentifier"
              ],
              "title": "Setting up accessorices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupPayload",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HMAccessorySetupPayload",
                    "text": "HMAccessorySetupPayload"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "payload"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest~1suggestedAccessoryName/title",
          "value": "suggestedAccessoryName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest~1suggestedAccessoryName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "suggestedAccessoryName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupPayload/title",
          "value": "HMAccessorySetupPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest~1payload/title",
          "value": "payload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest~1payload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "payload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest~1homeUniqueIdentifier/title",
          "value": "homeUniqueIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest~1homeUniqueIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "homeUniqueIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest/title",
          "value": "HMAccessorySetupRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest~1suggestedRoomUniqueIdentifier/title",
          "value": "suggestedRoomUniqueIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest~1suggestedRoomUniqueIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "suggestedRoomUniqueIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmaccessorysetuprequest/payload"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmaccessorysetuprequest/payload"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
