{
  "abstract": [
    {
      "text": "The value that defines how the disk synchronizes with the underlying storage when the guest operating system flushes data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/synchronizationMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VZDiskBlockDeviceStorageDeviceAttachment(py)synchronizationMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "synchronizationMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@VZDiskSynchronizationMode",
        "text": "VZDiskSynchronizationMode"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "synchronizationMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "synchronizationMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "synchronizationMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskSynchronizationMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VZDiskSynchronizationMode",
              "text": "VZDiskSynchronizationMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment": {
      "abstract": [
        {
          "text": "A storage device attachment that uses a disk to store data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZDiskBlockDeviceStorageDeviceAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskBlockDeviceStorageDeviceAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZDiskBlockDeviceStorageDeviceAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskblockdevicestoragedeviceattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/fileHandle": {
      "abstract": [
        {
          "text": "A file handle to a block device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFileHandle",
          "text": "FileHandle"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/fileHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileHandle"
        }
      ],
      "role": "symbol",
      "title": "fileHandle",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskblockdevicestoragedeviceattachment/filehandle"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/isReadOnly": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether this disk attachment is read-only; otherwise, if the file handle allows writes, the device can write data into it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isReadOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/isReadOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readOnly"
        }
      ],
      "role": "symbol",
      "title": "isReadOnly",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskblockdevicestoragedeviceattachment/isreadonly"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/synchronizationMode": {
      "abstract": [
        {
          "text": "The value that defines how the disk synchronizes with the underlying storage when the guest operating system flushes data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "synchronizationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZDiskSynchronizationMode",
          "text": "VZDiskSynchronizationMode"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/synchronizationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "synchronizationMode"
        }
      ],
      "role": "symbol",
      "title": "synchronizationMode",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskblockdevicestoragedeviceattachment/synchronizationmode"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskSynchronizationMode": {
      "abstract": [
        {
          "text": "Values that describe the synchronization modes available to the guest OS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZDiskSynchronizationMode"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskSynchronizationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskSynchronizationMode"
        }
      ],
      "role": "symbol",
      "title": "VZDiskSynchronizationMode",
      "type": "topic",
      "url": "/documentation/virtualization/vzdisksynchronizationmode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-block-storage-device-details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/fileHandle",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/isReadOnly"
      ],
      "title": "Getting the block storage device details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "synchronizationMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "synchronizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-block-storage-device-details",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/fileHandle",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment/isReadOnly"
              ],
              "title": "Getting the block storage device details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskSynchronizationMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@VZDiskSynchronizationMode",
                    "text": "VZDiskSynchronizationMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "synchronizationMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment~1isReadOnly/title",
          "value": "readOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment~1isReadOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment~1synchronizationMode/title",
          "value": "synchronizationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment~1synchronizationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "synchronizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment~1fileHandle/title",
          "value": "fileHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment~1fileHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fileHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment/title",
          "value": "VZDiskBlockDeviceStorageDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskBlockDeviceStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskBlockDeviceStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskSynchronizationMode/title",
          "value": "VZDiskSynchronizationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskSynchronizationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskSynchronizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskSynchronizationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskSynchronizationMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzdiskblockdevicestoragedeviceattachment/synchronizationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzdiskblockdevicestoragedeviceattachment/synchronizationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
