{
  "abstract": [
    {
      "text": "Creates and returns a snapshotter object based on the specified options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/init(options:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKMapSnapshotter(im)initWithOptions:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKMapSnapshotter",
        "text": "MKMapSnapshotter"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKMapSnapshotOptions",
        "text": "Options"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithOptions:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(options:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKMapSnapshotter",
              "text": "MKMapSnapshotter"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKMapSnapshotOptions",
              "text": "Options"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The options to use when capturing the map imagery. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". This parameter may not be ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An initialized snapshotter object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter": {
      "abstract": [
        {
          "text": "A utility class for capturing a map and its content into an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapSnapshotter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapSnapshotter"
        }
      ],
      "role": "symbol",
      "title": "MKMapSnapshotter",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options": {
      "abstract": [
        {
          "text": "The options the snapshotter initializer uses to create a snapshotter to capture map-based imagery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "MKMapSnapshotter.Options",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/init(options:)": {
      "abstract": [
        {
          "text": "Creates and returns a snapshotter object based on the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapSnapshotter",
          "text": "MKMapSnapshotter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapSnapshotOptions",
          "text": "Options"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/init(options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "init(options:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/init(options:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-snapshotter-object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options"
      ],
      "title": "Creating a snapshotter object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithOptions:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-snapshotter-object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options"
              ],
              "title": "Creating a snapshotter object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithOptions:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MKMapSnapshotOptions",
                    "text": "MKMapSnapshotOptions"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The options to use when capturing the map imagery. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". This parameter may not be ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An initialized snapshotter object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter/title",
          "value": "MKMapSnapshotter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1init(options:)/title",
          "value": "initWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1init(options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options/title",
          "value": "MKMapSnapshotOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkmapsnapshotter/init(options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkmapsnapshotter/init(options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
