{
  "abstract": [
    {
      "text": "The options the snapshotter initializer uses to create a snapshotter to capture map-based imagery.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MapKit",
    "externalID": "c:objc(cs)MKMapSnapshotOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Options"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Options"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MKMapSnapshotter.Options"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Options"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After creating and configuring an instance of this class, you pass that instance to an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The snapshotter uses the configuration options to determine which portion of the map to capture, the viewing angle to use for the camera, and the map’s overall appearance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS 10.14 and later, you can apply a light or dark appearance to your map snapshots by modifying the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/appearance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of your snapshot options. Even if you specify a custom appearance, users can use the Maps app to force all maps to adopt a light appearance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter": {
      "abstract": [
        {
          "text": "A utility class for capturing a map and its content into an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapSnapshotter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapSnapshotter"
        }
      ],
      "role": "symbol",
      "title": "MKMapSnapshotter",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options": {
      "abstract": [
        {
          "text": "The options the snapshotter initializer uses to create a snapshotter to capture map-based imagery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "MKMapSnapshotter.Options",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/appearance": {
      "abstract": [
        {
          "text": "The visual style (light or dark) to apply to the map when rendering the snapshot image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAppearance",
          "text": "NSAppearance"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/appearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appearance"
        }
      ],
      "role": "symbol",
      "title": "appearance",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/appearance"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/camera": {
      "abstract": [
        {
          "text": "The camera to use when taking the map snapshot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "camera"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapCamera",
          "text": "MKMapCamera"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/camera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "camera"
        }
      ],
      "role": "symbol",
      "title": "camera",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/camera"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapRect": {
      "abstract": [
        {
          "text": "The map rectangle that you want to capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKMapRect",
          "text": "MKMapRect"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapRect"
        }
      ],
      "role": "symbol",
      "title": "mapRect",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/maprect"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapType": {
      "abstract": [
        {
          "text": "The map’s visual style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapType",
          "text": "MKMapType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapType"
        }
      ],
      "role": "symbol",
      "title": "mapType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/maptype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/pointOfInterestFilter": {
      "abstract": [
        {
          "text": "The filter to use for determining the points of interest that appear in the snapshot.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointOfInterestFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKPointOfInterestFilter",
          "text": "MKPointOfInterestFilter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/pointOfInterestFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointOfInterestFilter"
        }
      ],
      "role": "symbol",
      "title": "pointOfInterestFilter",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/pointofinterestfilter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/preferredConfiguration": {
      "abstract": [
        {
          "text": "The map configuration style to use for snapshots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapConfiguration",
          "text": "MKMapConfiguration"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/preferredConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredConfiguration"
        }
      ],
      "role": "symbol",
      "title": "preferredConfiguration",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/preferredconfiguration"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/region": {
      "abstract": [
        {
          "text": "The area of the map that you want to capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "region"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKCoordinateRegion",
          "text": "MKCoordinateRegion"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/region",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "region"
        }
      ],
      "role": "symbol",
      "title": "region",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/region"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/scale": {
      "abstract": [
        {
          "text": "The scale factor to use when creating the image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scale"
        }
      ],
      "role": "symbol",
      "title": "scale",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/scale"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsBuildings": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the map displays extruded building information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsBuildings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsBuildings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsBuildings"
        }
      ],
      "role": "symbol",
      "title": "showsBuildings",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/showsbuildings"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsPointsOfInterest": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the map displays point-of-interest information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPointsOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsPointsOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsPointsOfInterest"
        }
      ],
      "role": "symbol",
      "title": "showsPointsOfInterest",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/showspointsofinterest"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/size": {
      "abstract": [
        {
          "text": "The size of the image that you want to create.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/size"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/traitCollection": {
      "abstract": [
        {
          "text": "Traits that determine the appearance of the map snapshot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/traitCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "traitCollection"
        }
      ],
      "role": "symbol",
      "title": "traitCollection",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/traitcollection"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/init(options:)": {
      "abstract": [
        {
          "text": "Creates and returns a snapshotter object based on the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapSnapshotter",
          "text": "MKMapSnapshotter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapSnapshotOptions",
          "text": "Options"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/init(options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "init(options:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/init(options:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-snapshotter-object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/init(options:)"
      ],
      "title": "Creating a snapshotter object"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-snapshot-region",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/region",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapRect",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/camera"
      ],
      "title": "Configuring the snapshot region"
    },
    {
      "anchor": "Configuring-the-map-data",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/preferredConfiguration",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapType",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsBuildings",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/pointOfInterestFilter",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsPointsOfInterest"
      ],
      "title": "Configuring the map data"
    },
    {
      "anchor": "Configuring-the-image-output",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/traitCollection",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/size",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/appearance",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/scale"
      ],
      "title": "Configuring the image output"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKMapSnapshotOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-snapshot-region",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/region",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapRect",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/camera"
              ],
              "title": "Configuring the snapshot region"
            },
            {
              "anchor": "Configuring-the-map-data",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/preferredConfiguration",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapType",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsBuildings",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/pointOfInterestFilter",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsPointsOfInterest"
              ],
              "title": "Configuring the map data"
            },
            {
              "anchor": "Configuring-the-image-output",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/traitCollection",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/size",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/appearance",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/scale"
              ],
              "title": "Configuring the image output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-snapshotter-object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/init(options:)"
              ],
              "title": "Creating a snapshotter object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKMapSnapshotOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1showsBuildings/title",
          "value": "showsBuildings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1showsBuildings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsBuildings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1scale/title",
          "value": "scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options/title",
          "value": "MKMapSnapshotOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1init(options:)/title",
          "value": "initWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1init(options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1showsPointsOfInterest/title",
          "value": "showsPointsOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1showsPointsOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsPointsOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1appearance/title",
          "value": "appearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1appearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1region/title",
          "value": "region"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1region/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "region"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1preferredConfiguration/title",
          "value": "preferredConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1preferredConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1mapType/title",
          "value": "mapType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1mapType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1traitCollection/title",
          "value": "traitCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1traitCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "traitCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter/title",
          "value": "MKMapSnapshotter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSnapshotter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1pointOfInterestFilter/title",
          "value": "pointOfInterestFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1pointOfInterestFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointOfInterestFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1mapRect/title",
          "value": "mapRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1mapRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mapRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1camera/title",
          "value": "camera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1camera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "camera"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkmapsnapshotter/options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkmapsnapshotter/options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
