{
  "abstract": [
    {
      "text": "A value that represents a unique identifier for the virtual machine.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/machineIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VZGenericPlatformConfiguration(py)machineIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "machineIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VZGenericMachineIdentifier",
        "text": "VZGenericMachineIdentifier"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "machineIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "machineIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "machineIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VZGenericMachineIdentifier",
              "text": "VZGenericMachineIdentifier"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier": {
      "abstract": [
        {
          "text": "An object that represents a unique identifier for a virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZGenericMachineIdentifier"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZGenericMachineIdentifier"
        }
      ],
      "role": "symbol",
      "title": "VZGenericMachineIdentifier",
      "type": "topic",
      "url": "/documentation/virtualization/vzgenericmachineidentifier"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration": {
      "abstract": [
        {
          "text": "The platform configuration for a generic Intel or ARM virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZGenericPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZGenericPlatformConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZGenericPlatformConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzgenericplatformconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether nested virtualization is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNestedVirtualizationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nestedVirtualizationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isNestedVirtualizationEnabled",
      "type": "topic",
      "url": "/documentation/virtualization/vzgenericplatformconfiguration/isnestedvirtualizationenabled"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationSupported": {
      "abstract": [
        {
          "text": "A Boolean value that describes whether the platform configuration supports nested virtualization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNestedVirtualizationSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nestedVirtualizationSupported"
        }
      ],
      "role": "symbol",
      "title": "isNestedVirtualizationSupported",
      "type": "topic",
      "url": "/documentation/virtualization/vzgenericplatformconfiguration/isnestedvirtualizationsupported"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/machineIdentifier": {
      "abstract": [
        {
          "text": "A value that represents a unique identifier for the virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "machineIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZGenericMachineIdentifier",
          "text": "VZGenericMachineIdentifier"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/machineIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "machineIdentifier"
        }
      ],
      "role": "symbol",
      "title": "machineIdentifier",
      "type": "topic",
      "url": "/documentation/virtualization/vzgenericplatformconfiguration/machineidentifier"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-the-platform-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationEnabled",
        "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationSupported",
        "doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier"
      ],
      "title": "Identifying the platform configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "machineIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "machineIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization",
                "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-the-platform-configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationEnabled",
                "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationSupported",
                "doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier"
              ],
              "title": "Identifying the platform configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VZGenericMachineIdentifier",
                    "text": "VZGenericMachineIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "machineIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration/title",
          "value": "VZGenericPlatformConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZGenericPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZGenericPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1isNestedVirtualizationSupported/title",
          "value": "nestedVirtualizationSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1isNestedVirtualizationSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nestedVirtualizationSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1isNestedVirtualizationEnabled/title",
          "value": "nestedVirtualizationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1isNestedVirtualizationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nestedVirtualizationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier/title",
          "value": "VZGenericMachineIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZGenericMachineIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZGenericMachineIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1machineIdentifier/title",
          "value": "machineIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1machineIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "machineIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzgenericplatformconfiguration/machineidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzgenericplatformconfiguration/machineidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
