{
  "abstract": [
    {
      "text": "Copy file to destination. Behaves the same as ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557010-copypath",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use -[NSFileManager copyItemAtURL:toURL:error:] instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/copyOperation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSWorkspaceCopyOperation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "copyOperation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSWorkspace",
        "text": "NSWorkspace"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
        "text": "FileOperationName"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWorkspaceCopyOperation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.11",
        "introducedAt": "10.0",
        "message": "Use -[NSFileManager copyItemAtURL:toURL:error:] instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "copyOperation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "copyOperation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWorkspace",
              "text": "NSWorkspace"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
              "text": "FileOperationName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace": {
      "abstract": [
        {
          "text": "A workspace that can launch other apps and perform a variety of file-handling services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName": {
      "abstract": [
        {
          "text": "These constants specify different types of file operations used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/performFileOperation(_:source:destination:files:tag:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FileOperationName"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace.FileOperationName",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/compressOperation": {
      "abstract": [
        {
          "text": "Compress file. This operation always returns an error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compressOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/compressOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceCompressOperation"
        }
      ],
      "role": "symbol",
      "title": "compressOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/compressoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/copyOperation": {
      "abstract": [
        {
          "text": "Copy file to destination. Behaves the same as ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557010-copypath",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/copyOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceCopyOperation"
        }
      ],
      "role": "symbol",
      "title": "copyOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/copyoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/decompressOperation": {
      "abstract": [
        {
          "text": "Decompress file. This operation always returns an error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decompressOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/decompressOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDecompressOperation"
        }
      ],
      "role": "symbol",
      "title": "decompressOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/decompressoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/decryptOperation": {
      "abstract": [
        {
          "text": "Decrypt file. This operation always returns an error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decryptOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/decryptOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDecryptOperation"
        }
      ],
      "role": "symbol",
      "title": "decryptOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/decryptoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/destroyOperation": {
      "abstract": [
        {
          "text": "Destroy file. Behaves the same as  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1556998-removefileatpath",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destroyOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/destroyOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDestroyOperation"
        }
      ],
      "role": "symbol",
      "title": "destroyOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/destroyoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/duplicateOperation": {
      "abstract": [
        {
          "text": "Duplicate file in source directory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/duplicateOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDuplicateOperation"
        }
      ],
      "role": "symbol",
      "title": "duplicateOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/duplicateoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/encryptOperation": {
      "abstract": [
        {
          "text": "Encrypt file. This operation always returns an error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/encryptOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceEncryptOperation"
        }
      ],
      "role": "symbol",
      "title": "encryptOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/encryptoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/linkOperation": {
      "abstract": [
        {
          "text": "Create hard link to file in destination. Behaves the same as ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557003-linkpath",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/linkOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceLinkOperation"
        }
      ],
      "role": "symbol",
      "title": "linkOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/linkoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/moveOperation": {
      "abstract": [
        {
          "text": "Move file to destination. Behaves the same as ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1556999-movepath",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/moveOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceMoveOperation"
        }
      ],
      "role": "symbol",
      "title": "moveOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/moveoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/recycleOperation": {
      "abstract": [
        {
          "text": "Move file to trash. The file is moved to the trash folder on the volume containing the file using the same semantics as ",
          "type": "text"
        },
        {
          "code": "NSWorkspaceMoveOperation",
          "type": "codeVoice"
        },
        {
          "text": ". If a file with the same name currently exists in the trash folder, the new file is renamed. If no trash folder exists on the volume containing the file, the operation fails.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recycleOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/recycleOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceRecycleOperation"
        }
      ],
      "role": "symbol",
      "title": "recycleOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/fileoperationname/recycleoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/performFileOperation(_:source:destination:files:tag:)": {
      "abstract": [
        {
          "text": "Performs a file operation on a set of files in a particular directory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performFileOperation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
          "text": "FileOperationName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "files"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "tag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/performFileOperation(_:source:destination:files:tag:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performFileOperation:source:destination:files:tag:"
        }
      ],
      "role": "symbol",
      "title": "performFileOperation(_:source:destination:files:tag:)",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/performfileoperation(_:source:destination:files:tag:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1556998-removefileatpath": {
      "abstract": [
        {
          "text": "Deletes the file, link, or directory (including, recursively, all subdirectories, files, and links in the directory) identified by a given path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1556998-removefileatpath",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeFileAtPath:handler:",
      "type": "topic",
      "url": "/documentation/foundation/nsfilemanager/1556998-removefileatpath"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1556999-movepath": {
      "abstract": [
        {
          "text": "Moves the directory or file specified by a given path to a different location in the file system identified by another path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1556999-movepath",
      "kind": "symbol",
      "role": "symbol",
      "title": "movePath:toPath:handler:",
      "type": "topic",
      "url": "/documentation/foundation/nsfilemanager/1556999-movepath"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557003-linkpath": {
      "abstract": [
        {
          "text": "Creates a link from a source to a destination.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557003-linkpath",
      "kind": "symbol",
      "role": "symbol",
      "title": "linkPath:toPath:handler:",
      "type": "topic",
      "url": "/documentation/foundation/nsfilemanager/1557003-linkpath"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557010-copypath": {
      "abstract": [
        {
          "text": "Copies the directory or file specified in a given path to a different location in the file system identified by another path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557010-copypath",
      "kind": "symbol",
      "role": "symbol",
      "title": "copyPath:toPath:handler:",
      "type": "topic",
      "url": "/documentation/foundation/nsfilemanager/1557010-copypath"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/compressOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/decompressOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/decryptOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/destroyOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/duplicateOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/encryptOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/linkOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/moveOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/recycleOperation"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.11",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWorkspaceCopyOperation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceCopyOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/compressOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/decompressOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/decryptOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/destroyOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/duplicateOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/encryptOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/linkOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/moveOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName/recycleOperation"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/FileOperationName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSWorkspaceFileOperationName",
                    "text": "NSWorkspaceFileOperationName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSWorkspaceCopyOperation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use -[NSFileManager copyItemAtURL:toURL:error:] instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1recycleOperation/title",
          "value": "NSWorkspaceRecycleOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1recycleOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceRecycleOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1performFileOperation(_:source:destination:files:tag:)/title",
          "value": "performFileOperation:source:destination:files:tag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1performFileOperation(_:source:destination:files:tag:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performFileOperation:source:destination:files:tag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1linkOperation/title",
          "value": "NSWorkspaceLinkOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1linkOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceLinkOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1duplicateOperation/title",
          "value": "NSWorkspaceDuplicateOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1duplicateOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDuplicateOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1copyOperation/title",
          "value": "NSWorkspaceCopyOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1copyOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceCopyOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1encryptOperation/title",
          "value": "NSWorkspaceEncryptOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1encryptOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceEncryptOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1moveOperation/title",
          "value": "NSWorkspaceMoveOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1moveOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceMoveOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1decryptOperation/title",
          "value": "NSWorkspaceDecryptOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1decryptOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDecryptOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1destroyOperation/title",
          "value": "NSWorkspaceDestroyOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1destroyOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDestroyOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1compressOperation/title",
          "value": "NSWorkspaceCompressOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1compressOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceCompressOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/title",
          "value": "NSWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1decompressOperation/title",
          "value": "NSWorkspaceDecompressOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName~1decompressOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDecompressOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName/title",
          "value": "NSWorkspaceFileOperationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceFileOperationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1FileOperationName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceFileOperationName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsworkspace/fileoperationname/copyoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsworkspace/fileoperationname/copyoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
