{"metadata":{"roleHeading":"Instance Subscript","title":"subscript(_:)","role":"symbol","modules":[{"name":"Model I/O"}],"fragments":[{"kind":"keyword","text":"subscript"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"text":"MDLMaterialProperty","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MDLMaterialProperty"},{"text":"?","kind":"text"}],"platforms":[{"beta":false,"introducedAt":"9.0","name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"9.0","name":"iPadOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"10.11","name":"macOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"9.0","name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false}],"symbolKind":"subscript","navigatorTitle":[{"text":"objectAtIndexedSubscript:","kind":"identifier"}],"externalID":"c:objc(cs)MDLMaterial(im)objectAtIndexedSubscript:"},"abstract":[{"type":"text","text":"Returns the material property at the specified index in the material, for use with subscript syntax."}],"kind":"symbol","identifier":{"url":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/subscript(_:)-19j2","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/modelio/mdlmaterial/subscript(_:)-19j2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/modelio/mdlmaterial/subscript(_:)-19j2"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"subscript"},{"text":"(","kind":"text"},{"text":"idx","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"MDLMaterialProperty","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MDLMaterialProperty"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"idx","content":[{"type":"paragraph","inlineContent":[{"text":"An index in the material’s list of material properties; must be less than the value of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/count","type":"reference"},{"text":".","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"The material property at the specified index.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"The ordering of material properties in a material is arbitrary, but you can use this method (together with the count property) to iterate through the material’s complete list of material properties. You can also iterate through material properties using ","type":"text"},{"identifier":"https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/Enumeration.html#//apple_ref/doc/uid/TP40008195-CH17-SW3","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/subscript(_:)-323j3","doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/count"],"title":"Accessing material properties with subscript syntax","generated":true,"anchor":"Accessing-material-properties-with-subscript-syntax"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMaterial"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial":{"type":"topic","url":"/documentation/modelio/mdlmaterial","abstract":[{"type":"text","text":"A collection of material properties that together describe the intended surface appearance for rendering a 3D object."}],"kind":"symbol","role":"symbol","title":"MDLMaterial","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MDLMaterial"}],"navigatorTitle":[{"kind":"identifier","text":"MDLMaterial"}]},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/subscript(_:)-19j2":{"title":"subscript(_:)","role":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/subscript(_:)-19j2","kind":"symbol","fragments":[{"text":"subscript","kind":"keyword"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MDLMaterialProperty","text":"MDLMaterialProperty","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Returns the material property at the specified index in the material, for use with subscript syntax.","type":"text"}],"url":"/documentation/modelio/mdlmaterial/subscript(_:)-19j2","navigatorTitle":[{"text":"objectAtIndexedSubscript:","kind":"identifier"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/count":{"title":"count","role":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/count","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"count","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"text":"The number of material properties in the material.","type":"text"}],"url":"/documentation/modelio/mdlmaterial/count","navigatorTitle":[{"text":"count","kind":"identifier"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty":{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty","kind":"symbol","title":"MDLMaterialProperty","url":"/documentation/modelio/mdlmaterialproperty","abstract":[{"type":"text","text":"A definition for one specific aspect of the rendering parameters for a material."}],"role":"symbol","navigatorTitle":[{"text":"MDLMaterialProperty","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMaterialProperty","kind":"identifier"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/subscript(_:)-323j3":{"title":"subscript(_:)","role":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/subscript(_:)-323j3","kind":"symbol","fragments":[{"text":"subscript","kind":"keyword"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MDLMaterialProperty","text":"MDLMaterialProperty","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Returns the material property with the specified name, for use with subscript syntax.","type":"text"}],"url":"/documentation/modelio/mdlmaterial/subscript(_:)-323j3","navigatorTitle":[{"text":"objectForKeyedSubscript:","kind":"identifier"}],"type":"topic"},"https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/Enumeration.html#//apple_ref/doc/uid/TP40008195-CH17-SW3":{"url":"https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/Enumeration.html#//apple_ref/doc/uid/TP40008195-CH17-SW3","titleInlineContent":[{"text":"Fast Enumeration","type":"text"}],"identifier":"https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/Enumeration.html#//apple_ref/doc/uid/TP40008195-CH17-SW3","type":"link","title":"Fast Enumeration"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","url":"/documentation/objectivec/nsuinteger","abstract":[{"type":"text","text":"Describes an unsigned integer."}],"type":"topic","role":"symbol","kind":"symbol","title":"NSUInteger"},"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","title":"Int","url":"/documentation/Swift/Int","abstract":[{"type":"text","text":"A signed integer value type."}],"role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"9.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"9.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"10.11"},{"beta":false,"unavailable":false,"deprecated":false,"name":"tvOS","introducedAt":"9.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"objectAtIndexedSubscript:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"objectAtIndexedSubscript:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMaterial"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/subscript(_:)-323j3","doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/count"],"title":"Accessing material properties with subscript syntax","generated":true,"anchor":"Accessing-material-properties-with-subscript-syntax"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"MDLMaterialProperty","preciseIdentifier":"c:objc(cs)MDLMaterialProperty","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"objectAtIndexedSubscript:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"idx","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An index in the material’s list of material properties; must be less than the value of ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterial/count","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"name":"idx"}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"op":"replace","path":"/primaryContentSections/2","value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The material property at the specified index.","type":"text"}]}],"kind":"content"}},{"value":"MDLMaterial","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/title"},{"value":[{"kind":"identifier","text":"MDLMaterial"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/fragments"},{"value":[{"text":"MDLMaterial","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/navigatorTitle"},{"value":"objectAtIndexedSubscript:","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial~1subscript(_:)-19j2/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"objectAtIndexedSubscript:"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial~1subscript(_:)-19j2/fragments"},{"value":"count","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial~1count/title"},{"value":[{"text":"count","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial~1count/fragments"},{"value":"MDLMaterialProperty","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/title"},{"value":[{"text":"MDLMaterialProperty","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/fragments"},{"value":[{"kind":"identifier","text":"MDLMaterialProperty"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/navigatorTitle"},{"value":"objectForKeyedSubscript:","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial~1subscript(_:)-323j3/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"objectForKeyedSubscript:"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial~1subscript(_:)-323j3/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}