{"variants":[{"paths":["/documentation/exposurenotification/enexposureconfiguration/neardurationweight"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/exposurenotification/enexposureconfiguration/neardurationweight"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nearDurationWeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"This property is available in iOS 12.5, and in iOS 13.7 and later."}],"type":"paragraph"}],"style":"important","name":"Important","type":"aside"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.exposurenotification/documentation/ExposureNotification","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration"]]},"seeAlsoSections":[{"generated":true,"title":"Configuring Duration","anchor":"Configuring-Duration","identifiers":["doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/immediateDurationWeight","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/mediumDurationWeight","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/otherDurationWeight","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/daysSinceLastExposureThreshold"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/nearDurationWeight"},"sections":[],"abstract":[{"type":"text","text":"The weight assigned to a risk level indicating the duration of the user’s exposure at close distance."}],"metadata":{"symbolKind":"property","title":"nearDurationWeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nearDurationWeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"nearDurationWeight","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)ENExposureConfiguration(py)nearDurationWeight","modules":[{"name":"Exposure Notification"}],"platforms":[{"name":"iOS","introducedAt":"12.5","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"12.5","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"12.5","deprecated":false,"unavailable":false,"beta":false}],"role":"symbol"},"references":{"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration":{"kind":"symbol","title":"ENExposureConfiguration","abstract":[{"text":"The object that contains parameters for configuring exposure notification risk scoring behavior.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ENExposureConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ENExposureConfiguration","kind":"identifier"}],"identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration","url":"/documentation/exposurenotification/enexposureconfiguration","type":"topic"},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/mediumDurationWeight":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediumDurationWeight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"kind":"symbol","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/mediumDurationWeight","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mediumDurationWeight"}],"url":"/documentation/exposurenotification/enexposureconfiguration/mediumdurationweight","title":"mediumDurationWeight","abstract":[{"type":"text","text":"The weight assigned to a risk level indicating the duration of the user’s exposure at medium distance."}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/nearDurationWeight":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nearDurationWeight","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"kind":"symbol","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/nearDurationWeight","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nearDurationWeight"}],"url":"/documentation/exposurenotification/enexposureconfiguration/neardurationweight","title":"nearDurationWeight","abstract":[{"type":"text","text":"The weight assigned to a risk level indicating the duration of the user’s exposure at close distance."}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification":{"abstract":[{"type":"text","text":"Implement a COVID-19 exposure notification system that protects user privacy."}],"type":"topic","title":"Exposure Notification","role":"collection","url":"/documentation/exposurenotification","kind":"symbol","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification"},"doc://com.externally.resolved.symbol/s:Sd":{"url":"/documentation/Swift/Double","identifier":"doc://com.externally.resolved.symbol/s:Sd","title":"Double","abstract":[{"text":"A double-precision, floating-point value type.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Double"}]},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","role":"overview","url":"/documentation/technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds":{"kind":"symbol","title":"attenuationDurationThresholds","url":"/documentation/exposurenotification/enexposureconfiguration/attenuationdurationthresholds","abstract":[{"text":"The configurable signal-loss thresholds for calculating exposure risk.","type":"text"}],"identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attenuationDurationThresholds","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"attenuationDurationThresholds"}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/immediateDurationWeight":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"immediateDurationWeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"kind":"symbol","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/immediateDurationWeight","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"immediateDurationWeight"}],"url":"/documentation/exposurenotification/enexposureconfiguration/immediatedurationweight","title":"immediateDurationWeight","abstract":[{"type":"text","text":"The weight assigned to a risk level indicating the duration of the user’s exposure at immediate distance."}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/otherDurationWeight":{"kind":"symbol","title":"otherDurationWeight","url":"/documentation/exposurenotification/enexposureconfiguration/otherdurationweight","abstract":[{"text":"The weight assigned to a risk level indicating the duration of the user’s exposure at a large distance.","type":"text"}],"identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/otherDurationWeight","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"otherDurationWeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"otherDurationWeight"}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/daysSinceLastExposureThreshold":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"daysSinceLastExposureThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/daysSinceLastExposureThreshold","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"daysSinceLastExposureThreshold"}],"url":"/documentation/exposurenotification/enexposureconfiguration/dayssincelastexposurethreshold","title":"daysSinceLastExposureThreshold","abstract":[{"type":"text","text":"The number of days to consider when calculating the risk level."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"deprecated":false,"introducedAt":"12.5","unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"introducedAt":"12.5","unavailable":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"introducedAt":"12.5","unavailable":false,"name":"Mac Catalyst"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"nearDurationWeight","path":"/metadata/title","op":"replace"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"nearDurationWeight"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.exposurenotification/documentation/ExposureNotification","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Configuring-Duration","generated":true,"title":"Configuring Duration","identifiers":["doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/immediateDurationWeight","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/mediumDurationWeight","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/otherDurationWeight","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/daysSinceLastExposureThreshold"]}],"op":"replace","path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"nearDurationWeight","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"value":"ENExposureConfiguration","op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/title"},{"value":[{"kind":"identifier","text":"ENExposureConfiguration"}],"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/fragments"},{"value":[{"kind":"identifier","text":"ENExposureConfiguration"}],"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/navigatorTitle"},{"value":"mediumDurationWeight","op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1mediumDurationWeight/title"},{"value":[{"kind":"identifier","text":"mediumDurationWeight"}],"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1mediumDurationWeight/fragments"},{"value":"nearDurationWeight","op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1nearDurationWeight/title"},{"value":[{"text":"nearDurationWeight","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1nearDurationWeight/fragments"},{"value":"attenuationDurationThresholds","op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1attenuationDurationThresholds/title"},{"value":[{"text":"attenuationDurationThresholds","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1attenuationDurationThresholds/fragments"},{"value":"immediateDurationWeight","op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1immediateDurationWeight/title"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1immediateDurationWeight/fragments","value":[{"text":"immediateDurationWeight","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1otherDurationWeight/title","value":"otherDurationWeight","op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1otherDurationWeight/fragments","value":[{"text":"otherDurationWeight","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1daysSinceLastExposureThreshold/title","value":"daysSinceLastExposureThreshold","op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1daysSinceLastExposureThreshold/fragments","value":[{"kind":"identifier","text":"daysSinceLastExposureThreshold"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}