{
  "abstract": [
    {
      "text": "The weight assigned to a risk level based on a confirmed clinical diagnosis.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedClinicalDiagnosisWeight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ENExposureConfiguration(py)reportTypeConfirmedClinicalDiagnosisWeight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "reportTypeConfirmedClinicalDiagnosisWeight"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "reportTypeConfirmedClinicalDiagnosisWeight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "reportTypeConfirmedClinicalDiagnosisWeight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reportTypeConfirmedClinicalDiagnosisWeight"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This property is available in iOS 12.5, and in iOS 13.7 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration": {
      "abstract": [
        {
          "text": "The object that contains parameters for configuring exposure notification risk scoring behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ENExposureConfiguration",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedClinicalDiagnosisWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level based on a confirmed clinical diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeConfirmedClinicalDiagnosisWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedClinicalDiagnosisWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeConfirmedClinicalDiagnosisWeight"
        }
      ],
      "role": "symbol",
      "title": "reportTypeConfirmedClinicalDiagnosisWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttypeconfirmedclinicaldiagnosisweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedTestWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level based on a confirmed test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeConfirmedTestWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedTestWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeConfirmedTestWeight"
        }
      ],
      "role": "symbol",
      "title": "reportTypeConfirmedTestWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttypeconfirmedtestweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeNoneMap": {
      "abstract": [
        {
          "text": "The report type to map an unknown diagnosis to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeNoneMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENDiagnosisReportType",
          "text": "ENDiagnosisReportType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeNoneMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeNoneMap"
        }
      ],
      "role": "symbol",
      "title": "reportTypeNoneMap",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttypenonemap"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeRecursiveWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level based on an exposure to someone exposed to someone else.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeRecursiveWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeRecursiveWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeRecursiveWeight"
        }
      ],
      "role": "symbol",
      "title": "reportTypeRecursiveWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttyperecursiveweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeSelfReportedWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level based on a self-reported diagnoisis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeSelfReportedWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeSelfReportedWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeSelfReportedWeight"
        }
      ],
      "role": "symbol",
      "title": "reportTypeSelfReportedWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttypeselfreportedweight"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Report-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedTestWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeRecursiveWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeSelfReportedWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeNoneMap"
      ],
      "title": "Configuring Report Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "reportTypeConfirmedClinicalDiagnosisWeight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeConfirmedClinicalDiagnosisWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Report-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedTestWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeRecursiveWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeSelfReportedWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeNoneMap"
              ],
              "title": "Configuring Report Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "reportTypeConfirmedClinicalDiagnosisWeight"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeNoneMap/title",
          "value": "reportTypeNoneMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeNoneMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeNoneMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeRecursiveWeight/title",
          "value": "reportTypeRecursiveWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeRecursiveWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeRecursiveWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeConfirmedClinicalDiagnosisWeight/title",
          "value": "reportTypeConfirmedClinicalDiagnosisWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeConfirmedClinicalDiagnosisWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeConfirmedClinicalDiagnosisWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/title",
          "value": "ENExposureConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeSelfReportedWeight/title",
          "value": "reportTypeSelfReportedWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeSelfReportedWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeSelfReportedWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeConfirmedTestWeight/title",
          "value": "reportTypeConfirmedTestWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeConfirmedTestWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeConfirmedTestWeight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/enexposureconfiguration/reporttypeconfirmedclinicaldiagnosisweight"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/enexposureconfiguration/reporttypeconfirmedclinicaldiagnosisweight"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
