{
  "abstract": [
    {
      "text": "Indicates no text drag options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/UITextDragOptionsNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITextDragOptions@UITextDragOptionsNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UITextDragOptionsNone"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextDragOptionsNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "UITextDragOptionsNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "UITextDragOptionsNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions": {
      "abstract": [
        {
          "text": "A set of options that determine the behavior of a draggable text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDragOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDragOptions"
        }
      ],
      "role": "symbol",
      "title": "UITextDragOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/UITextDragOptionsNone": {
      "abstract": [
        {
          "text": "Indicates no text drag options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextDragOptionsNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/UITextDragOptionsNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextDragOptionsNone",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragoptions/uitextdragoptionsnone"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/stripTextColorFromPreviews": {
      "abstract": [
        {
          "text": "Strips the foreground and background colors for a system-provided text drag preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stripTextColorFromPreviews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITextDragOptions",
          "text": "UITextDragOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/stripTextColorFromPreviews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDragOptionStripTextColorFromPreviews"
        }
      ],
      "role": "symbol",
      "title": "stripTextColorFromPreviews",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragoptions/striptextcolorfrompreviews"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-drag-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/stripTextColorFromPreviews"
      ],
      "title": "Text drag options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/title",
          "value": "UITextDragOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions~1stripTextColorFromPreviews/title",
          "value": "UITextDragOptionStripTextColorFromPreviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions~1stripTextColorFromPreviews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragOptionStripTextColorFromPreviews"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextdragoptions/uitextdragoptionsnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
