{
  "abstract": [
    {
      "text": "Asks the delegate for the targeted drag item preview that will appear during the lift animation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:previewForLifting:session:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIDragInteractionDelegate(im)dragInteraction:previewForLiftingItem:session:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dragInteraction"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIDragInteraction",
        "text": "UIDragInteraction"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "previewForLifting"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIDragItem",
        "text": "UIDragItem"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "session"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)UIDragSession",
        "text": "UIDragSession"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITargetedDragPreview",
        "text": "UITargetedDragPreview"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dragInteraction:previewForLiftingItem:session:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "dragInteraction(_:previewForLifting:session:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dragInteraction"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "interaction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteraction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIDragInteraction",
              "text": "UIDragInteraction"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "previewForLifting"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "item"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIDragItem",
              "text": "UIDragItem"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIDragSession",
              "text": "UIDragSession"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITargetedDragPreview",
              "text": "UITargetedDragPreview"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The interaction that called this method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "interaction"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The drag item represented by the preview.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "item"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The current drag session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A targeted drag item preview you create, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " to tell the system not to display the lift animation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t provide this method, the system creates a preview based on the view owned by the drag interaction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragInteraction": {
      "abstract": [
        {
          "text": "An interaction to enable dragging of items from a view, employing a delegate to provide drag items and to respond to calls from the drag session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIDragInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uidraginteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate": {
      "abstract": [
        {
          "text": "The interface for configuring and controlling a drag interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIDragInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uidraginteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:prefersFullSizePreviewsFor:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether the preview should appear in its original size or a scaled size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dragInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragInteraction",
          "text": "UIDragInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "prefersFullSizePreviewsFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:prefersFullSizePreviewsFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dragInteraction:prefersFullSizePreviewsForSession:"
        }
      ],
      "role": "symbol",
      "title": "dragInteraction(_:prefersFullSizePreviewsFor:)",
      "type": "topic",
      "url": "/documentation/uikit/uidraginteractiondelegate/draginteraction(_:prefersfullsizepreviewsfor:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:previewForCancelling:withDefault:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the targeted drag item preview to show during the cancellation animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dragInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragInteraction",
          "text": "UIDragInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "previewForCancelling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedDragPreview",
          "text": "UITargetedDragPreview"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedDragPreview",
          "text": "UITargetedDragPreview"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:previewForCancelling:withDefault:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dragInteraction:previewForCancellingItem:withDefault:"
        }
      ],
      "role": "symbol",
      "title": "dragInteraction(_:previewForCancelling:withDefault:)",
      "type": "topic",
      "url": "/documentation/uikit/uidraginteractiondelegate/draginteraction(_:previewforcancelling:withdefault:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:previewForLifting:session:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the targeted drag item preview that will appear during the lift animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dragInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragInteraction",
          "text": "UIDragInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "previewForLifting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedDragPreview",
          "text": "UITargetedDragPreview"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:previewForLifting:session:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dragInteraction:previewForLiftingItem:session:"
        }
      ],
      "role": "symbol",
      "title": "dragInteraction(_:previewForLifting:session:)",
      "type": "topic",
      "url": "/documentation/uikit/uidraginteractiondelegate/draginteraction(_:previewforlifting:session:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragItem": {
      "abstract": [
        {
          "text": "A representation of an underlying data item as a person drags it from one location to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragItem"
        }
      ],
      "role": "symbol",
      "title": "UIDragItem",
      "type": "topic",
      "url": "/documentation/uikit/uidragitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragSession": {
      "abstract": [
        {
          "text": "The interface for configuring a drag session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragSession"
        }
      ],
      "role": "symbol",
      "title": "UIDragSession",
      "type": "topic",
      "url": "/documentation/uikit/uidragsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview": {
      "abstract": [
        {
          "text": "A drag item preview used by the system during lift, drop, or cancellation animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITargetedDragPreview"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITargetedDragPreview"
        }
      ],
      "role": "symbol",
      "title": "UITargetedDragPreview",
      "type": "topic",
      "url": "/documentation/uikit/uitargeteddragpreview"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-drag-previews",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:previewForCancelling:withDefault:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:prefersFullSizePreviewsFor:)"
      ],
      "title": "Providing drag previews"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dragInteraction:previewForLiftingItem:session:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dragInteraction:previewForLiftingItem:session:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-drag-previews",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:previewForCancelling:withDefault:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:prefersFullSizePreviewsFor:)"
              ],
              "title": "Providing drag previews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UITargetedDragPreview",
                    "text": "UITargetedDragPreview"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "dragInteraction:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteraction",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIDragInteraction",
                    "text": "UIDragInteraction"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "interaction"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "previewForLiftingItem:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIDragItem",
                    "text": "UIDragItem"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "item"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "session:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)UIDragSession",
                    "text": "id<UIDragSession>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "session"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The interaction that called this method.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "interaction"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The drag item represented by the preview.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "item"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The current drag session.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "session"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A targeted drag item preview you create, or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " to tell the system not to display the lift animation.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem/title",
          "value": "UIDragItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragSession/title",
          "value": "UIDragSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate~1dragInteraction(_:prefersFullSizePreviewsFor:)/title",
          "value": "dragInteraction:prefersFullSizePreviewsForSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate~1dragInteraction(_:prefersFullSizePreviewsFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dragInteraction:prefersFullSizePreviewsForSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteraction/title",
          "value": "UIDragInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedDragPreview/title",
          "value": "UITargetedDragPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedDragPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITargetedDragPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedDragPreview/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITargetedDragPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate~1dragInteraction(_:previewForLifting:session:)/title",
          "value": "dragInteraction:previewForLiftingItem:session:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate~1dragInteraction(_:previewForLifting:session:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dragInteraction:previewForLiftingItem:session:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate~1dragInteraction(_:previewForCancelling:withDefault:)/title",
          "value": "dragInteraction:previewForCancellingItem:withDefault:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate~1dragInteraction(_:previewForCancelling:withDefault:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dragInteraction:previewForCancellingItem:withDefault:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate/title",
          "value": "UIDragInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragInteractionDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidraginteractiondelegate/draginteraction(_:previewforlifting:session:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidraginteractiondelegate/draginteraction(_:previewforlifting:session:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
