{"metadata":{"role":"symbol","title":"mIncomingDataListenerRefCon","fragments":[{"text":"mIncomingDataListenerRefCon","kind":"identifier"}],"modules":[{"name":"IOBluetooth"}],"navigatorTitle":[{"text":"mIncomingDataListenerRefCon","kind":"identifier"}],"externalID":"c:objc(cs)IOBluetoothRFCOMMChannel@mIncomingDataListenerRefCon","symbolKind":"ivar","platforms":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"roleHeading":"Instance Variable"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mIncomingDataListenerRefCon"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iobluetooth/iobluetoothrfcommchannel/mincomingdatalistenerrefcon"]}],"identifier":{"url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel/mIncomingDataListenerRefCon","interfaceLanguage":"occ"},"references":{"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel/mIncomingDataListenerRefCon":{"kind":"symbol","url":"/documentation/iobluetooth/iobluetoothrfcommchannel/mincomingdatalistenerrefcon","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel/mIncomingDataListenerRefCon","abstract":[],"type":"topic","fragments":[{"text":"mIncomingDataListenerRefCon","kind":"identifier"}],"title":"mIncomingDataListenerRefCon","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel":{"type":"topic","kind":"symbol","abstract":[{"text":"An instance of this class represents an RFCOMM channel as defined by the Bluetooth SDP spec..","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IOBluetoothRFCOMMChannel"}],"url":"/documentation/iobluetooth/iobluetoothrfcommchannel","role":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOBluetoothRFCOMMChannel"}],"title":"IOBluetoothRFCOMMChannel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel/title","value":"IOBluetoothRFCOMMChannel","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel/fragments","value":[{"text":"IOBluetoothRFCOMMChannel","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel/navigatorTitle","value":[{"text":"IOBluetoothRFCOMMChannel","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}