{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"mIsIncoming","kind":"identifier"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["/documentation/iobluetooth/iobluetoothrfcommchannel/misincoming"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"mIsIncoming"}],"title":"mIsIncoming","symbolKind":"ivar","platforms":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"modules":[{"name":"IOBluetooth"}],"navigatorTitle":[{"kind":"identifier","text":"mIsIncoming"}],"externalID":"c:objc(cs)IOBluetoothRFCOMMChannel@mIsIncoming","roleHeading":"Instance Variable"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel"]]},"identifier":{"url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel/mIsIncoming","interfaceLanguage":"occ"},"sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel/mIsIncoming":{"kind":"symbol","url":"/documentation/iobluetooth/iobluetoothrfcommchannel/misincoming","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel/mIsIncoming","abstract":[],"type":"topic","fragments":[{"text":"mIsIncoming","kind":"identifier"}],"title":"mIsIncoming","role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","type":"topic","url":"/documentation/objectivec/bool","title":"BOOL","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel":{"type":"topic","kind":"symbol","abstract":[{"text":"An instance of this class represents an RFCOMM channel as defined by the Bluetooth SDP spec..","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IOBluetoothRFCOMMChannel"}],"url":"/documentation/iobluetooth/iobluetoothrfcommchannel","role":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOBluetoothRFCOMMChannel"}],"title":"IOBluetoothRFCOMMChannel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel/title","value":"IOBluetoothRFCOMMChannel","op":"replace"},{"value":[{"text":"IOBluetoothRFCOMMChannel","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel/fragments"},{"value":[{"text":"IOBluetoothRFCOMMChannel","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}