{"metadata":{"title":"register(forChannelOpenNotifications:selector:)","externalID":"c:objc(cs)IOBluetoothRFCOMMChannel(cm)registerForChannelOpenNotifications:selector:","role":"symbol","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"register","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forChannelOpenNotifications","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!, ","kind":"text"},{"text":"selector","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"text":"IOBluetoothUserNotification","preciseIdentifier":"c:objc(cs)IOBluetoothUserNotification","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"platforms":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"modules":[{"name":"IOBluetooth"}],"navigatorTitle":[{"text":"registerForChannelOpenNotifications:selector:","kind":"identifier"}]},"variants":[{"paths":["/documentation/iobluetooth/iobluetoothrfcommchannel/register(forchannelopennotifications:selector:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/iobluetooth/iobluetoothrfcommchannel/register(forchannelopennotifications:selector:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel/register(forChannelOpenNotifications:selector:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"register","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forChannelOpenNotifications","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!, ","kind":"text"},{"text":"selector","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV"},{"text":"!) -> ","kind":"text"},{"text":"IOBluetoothUserNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)IOBluetoothUserNotification","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotification"},{"text":"!","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"object","content":[{"inlineContent":[{"type":"text","text":"Target object"}],"type":"paragraph"}]},{"name":"selector","content":[{"inlineContent":[{"text":"Selector to be called on the target object when a new RFCOMM channel is opened. the format for the selector is: -(void) selectorName:(IOBluetoothUserNotification *)inNotification channel:(IOBluetoothRFCOMMChannel *)newChannel","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"Returns an IOBluetoothUserNotification representing the outstanding RFCOMM channel notification. To unregister the notification, call -unregister on the resulting IOBluetoothUserNotification object. If an error is encountered creating the notification, nil is returned. The returned IOBluetoothUserNotification will be valid for as long as the notification is registered. It is not necessary to retain the result. Once -unregister is called on it, it will no longer be valid.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"inlineContent":[{"text":"The given selector will be called on the target object whenever any RFCOMM channel is opened. The selector should accept two arguments. The first is the user notification object. The second is the IOBluetoothRFCOMMChannel that was opened.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel"]]},"abstract":[{"text":"Allows a client to register for RFCOMM channel open notifications for any RFCOMM channel.","type":"text"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV":{"identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","title":"Selector","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Selector"}],"type":"topic","url":"/documentation/objectivec/selector","role":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.externally.resolved.symbol/c:@T@SEL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","title":"SEL","kind":"symbol","type":"topic","url":"/documentation/objectivec/sel","role":"symbol","abstract":[{"type":"text","text":"Defines an opaque type that represents a method selector."}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel/register(forChannelOpenNotifications:selector:)":{"title":"register(forChannelOpenNotifications:selector:)","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"register","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forChannelOpenNotifications","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!, ","kind":"text"},{"text":"selector","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"text":"IOBluetoothUserNotification","preciseIdentifier":"c:objc(cs)IOBluetoothUserNotification","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[{"text":"Allows a client to register for RFCOMM channel open notifications for any RFCOMM channel.","type":"text"}],"url":"/documentation/iobluetooth/iobluetoothrfcommchannel/register(forchannelopennotifications:selector:)","role":"symbol","navigatorTitle":[{"text":"registerForChannelOpenNotifications:selector:","kind":"identifier"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel/register(forChannelOpenNotifications:selector:)"},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel":{"type":"topic","kind":"symbol","abstract":[{"text":"An instance of this class represents an RFCOMM channel as defined by the Bluetooth SDP spec..","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IOBluetoothRFCOMMChannel"}],"url":"/documentation/iobluetooth/iobluetoothrfcommchannel","role":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOBluetoothRFCOMMChannel"}],"title":"IOBluetoothRFCOMMChannel"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotification":{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotification","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOBluetoothUserNotification","kind":"identifier"}],"type":"topic","url":"/documentation/iobluetooth/iobluetoothusernotification","navigatorTitle":[{"text":"IOBluetoothUserNotification","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Represents a registered notification.","type":"text"}],"title":"IOBluetoothUserNotification","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Method","op":"replace","path":"/metadata/roleHeading"},{"value":"registerForChannelOpenNotifications:selector:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerForChannelOpenNotifications:selector:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannel"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotification","kind":"typeIdentifier","text":"IOBluetoothUserNotification","preciseIdentifier":"c:objc(cs)IOBluetoothUserNotification"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"registerForChannelOpenNotifications:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":" "},{"kind":"identifier","text":"selector:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","kind":"typeIdentifier","text":"SEL","preciseIdentifier":"c:@T@SEL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"selector"},{"kind":"text","text":";"}],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"name":"object","content":[{"inlineContent":[{"type":"text","text":"Target object"}],"type":"paragraph"}]},{"name":"selector","content":[{"inlineContent":[{"text":"Selector to be called on the target object when a new RFCOMM channel is opened. the format for the selector is: -(void) selectorName:(IOBluetoothUserNotification *)inNotification channel:(IOBluetoothRFCOMMChannel *)newChannel","type":"text"}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1","op":"replace"},{"value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Returns an IOBluetoothUserNotification representing the outstanding RFCOMM channel notification. To unregister the notification, call -unregister on the resulting IOBluetoothUserNotification object. If an error is encountered creating the notification, nil is returned. The returned IOBluetoothUserNotification will be valid for as long as the notification is registered. It is not necessary to retain the result. Once -unregister is called on it, it will no longer be valid."}],"type":"paragraph"}]},"path":"/primaryContentSections/2","op":"replace"},{"value":"registerForChannelOpenNotifications:selector:","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel~1register(forChannelOpenNotifications:selector:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"registerForChannelOpenNotifications:selector:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel~1register(forChannelOpenNotifications:selector:)/fragments","op":"replace"},{"value":"IOBluetoothRFCOMMChannel","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel/title","op":"replace"},{"value":[{"text":"IOBluetoothRFCOMMChannel","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"IOBluetoothRFCOMMChannel"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannel/navigatorTitle","op":"replace"},{"value":"IOBluetoothUserNotification","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUserNotification/title","op":"replace"},{"value":[{"text":"IOBluetoothUserNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUserNotification/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"IOBluetoothUserNotification"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUserNotification/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}