{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics/chronologicalMerge(with:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:12AVFoundation9AVMetricsV18chronologicalMerge4with_AA15AVMergedMetricsVyxqd__qd_0_qd_0_Qp_QPGACyqd__G_ACyqd_0_Gqd_0_QptRvd_0_So13AVMetricEventCRbd__ALRbd_0_r0_lF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "chronologicalMerge"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "genericParameter",
        "text": "OtherSecondMetric"
      },
      {
        "kind": "text",
        "text": ", each "
      },
      {
        "kind": "genericParameter",
        "text": "MetricEventPack"
      },
      {
        "kind": "text",
        "text": ">("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:12AVFoundation9AVMetricsV",
        "text": "AVMetrics"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "OtherSecondMetric"
      },
      {
        "kind": "text",
        "text": ">, repeat "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:12AVFoundation9AVMetricsV",
        "text": "AVMetrics"
      },
      {
        "kind": "text",
        "text": "<each "
      },
      {
        "kind": "typeIdentifier",
        "text": "MetricEventPack"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:12AVFoundation15AVMergedMetricsV",
        "text": "AVMergedMetrics"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "MetricEvent"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "OtherSecondMetric"
      },
      {
        "kind": "text",
        "text": ", repeat each "
      },
      {
        "kind": "typeIdentifier",
        "text": "MetricEventPack"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "chronologicalMerge(with:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "chronologicalMerge"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "OtherSecondMetric"
            },
            {
              "kind": "text",
              "text": ", each "
            },
            {
              "kind": "genericParameter",
              "text": "MetricEventPack"
            },
            {
              "kind": "text",
              "text": ">("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "secondMetric"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:12AVFoundation9AVMetricsV",
              "text": "AVMetrics"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "OtherSecondMetric"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "metrics"
            },
            {
              "kind": "text",
              "text": ": repeat "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:12AVFoundation9AVMetricsV",
              "text": "AVMetrics"
            },
            {
              "kind": "text",
              "text": "<each "
            },
            {
              "kind": "typeIdentifier",
              "text": "MetricEventPack"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMergedMetrics",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:12AVFoundation15AVMergedMetricsV",
              "text": "AVMergedMetrics"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "MetricEvent"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "OtherSecondMetric"
            },
            {
              "kind": "text",
              "text": ", repeat each "
            },
            {
              "kind": "typeIdentifier",
              "text": "MetricEventPack"
            },
            {
              "kind": "text",
              "text": "> "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "OtherSecondMetric"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVMetricEvent",
              "text": "AVMetricEvent"
            },
            {
              "kind": "text",
              "text": ", repeat each "
            },
            {
              "kind": "typeIdentifier",
              "text": "MetricEventPack"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVMetricEvent",
              "text": "AVMetricEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMergedMetrics": {
      "abstract": [
        {
          "text": "An asynchronous stream of metric information from different publishers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMergedMetrics"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMergedMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMergedMetrics"
        }
      ],
      "role": "symbol",
      "title": "AVMergedMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avmergedmetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent": {
      "abstract": [
        {
          "text": "A base class that represents a metric event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics": {
      "abstract": [
        {
          "text": "An asynchronous stream of metric information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetrics"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetrics"
        }
      ],
      "role": "symbol",
      "title": "AVMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics/chronologicalMerge(with:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chronologicalMerge"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "OtherSecondMetric"
        },
        {
          "kind": "text",
          "text": ", each "
        },
        {
          "kind": "genericParameter",
          "text": "MetricEventPack"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation9AVMetricsV",
          "text": "AVMetrics"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "OtherSecondMetric"
        },
        {
          "kind": "text",
          "text": ">, repeat "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation9AVMetricsV",
          "text": "AVMetrics"
        },
        {
          "kind": "text",
          "text": "<each "
        },
        {
          "kind": "typeIdentifier",
          "text": "MetricEventPack"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVMergedMetricsV",
          "text": "AVMergedMetrics"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "MetricEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "OtherSecondMetric"
        },
        {
          "kind": "text",
          "text": ", repeat each "
        },
        {
          "kind": "typeIdentifier",
          "text": "MetricEventPack"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics/chronologicalMerge(with:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "chronologicalMerge(with:_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetrics/chronologicalmerge(with:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/title",
          "value": "AVMetricEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetrics/chronologicalmerge(with:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
