{
  "abstract": [
    {
      "text": "The HealthKit data is unavailable because it’s protected and the device is locked.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDatabaseInaccessible"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKErrorCode@HKErrorDatabaseInaccessible",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "errorDatabaseInaccessible"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKErrorDatabaseInaccessible"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKError.Code.errorDatabaseInaccessible"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "errorDatabaseInaccessible"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.healthkit/documentation/HealthKit/executing-statistics-collection-queries"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error occurs when your app queries for HealthKit data while the device is locked. You can, however, still save data. This data is saved into a temporary file, which is merged with HealthKit’s data when the user unlocks their device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError": {
      "abstract": [
        {
          "text": "An error returned from a HealthKit method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKError"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKError"
        }
      ],
      "role": "symbol",
      "title": "HKError",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code": {
      "abstract": [
        {
          "text": "Error codes returned by HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAnotherWorkoutSessionStarted": {
      "abstract": [
        {
          "text": "Another app started a workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorAnotherWorkoutSessionStarted"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAnotherWorkoutSessionStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorAnotherWorkoutSessionStarted"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorAnotherWorkoutSessionStarted",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/erroranotherworkoutsessionstarted"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationDenied": {
      "abstract": [
        {
          "text": "The user hasn’t given the app permission to save data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorAuthorizationDenied"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorAuthorizationDenied",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorauthorizationdenied"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationNotDetermined": {
      "abstract": [
        {
          "text": "The app hasn’t yet asked the user for the authorization required to complete the task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorAuthorizationNotDetermined"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationNotDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorAuthorizationNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorAuthorizationNotDetermined",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorauthorizationnotdetermined"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDatabaseInaccessible": {
      "abstract": [
        {
          "text": "The HealthKit data is unavailable because it’s protected and the device is locked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDatabaseInaccessible"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDatabaseInaccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorDatabaseInaccessible"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorDatabaseInaccessible",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errordatabaseinaccessible"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataRestricted": {
      "abstract": [
        {
          "text": "A Mobile Device Management (MDM) profile restricts the use of HealthKit on this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorHealthDataRestricted"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataRestricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorHealthDataRestricted"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorHealthDataRestricted",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorhealthdatarestricted"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataUnavailable": {
      "abstract": [
        {
          "text": "HealthKit accessed on an unsupported device, such as an iPad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorHealthDataUnavailable"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorHealthDataUnavailable"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorHealthDataUnavailable",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorhealthdataunavailable"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorInvalidArgument": {
      "abstract": [
        {
          "text": "The app passed an invalid argument to the HealthKit API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorInvalidArgument"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorInvalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorInvalidArgument"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorInvalidArgument",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorinvalidargument"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNoData": {
      "abstract": [
        {
          "text": "Data is unavailable for the requested query and predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorNoData"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNoData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorNoData"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorNoData",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errornodata"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied": {
      "abstract": [
        {
          "text": "The user hasn’t granted the application authorization to access all the required clinical record types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorRequiredAuthorizationDenied"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorRequiredAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorRequiredAuthorizationDenied",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorrequiredauthorizationdenied"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserCanceled": {
      "abstract": [
        {
          "text": "The user canceled the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorUserCanceled"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorUserCanceled"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorUserCanceled",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorusercanceled"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserExitedWorkoutSession": {
      "abstract": [
        {
          "text": "The user exited your application while a workout session was running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorUserExitedWorkoutSession"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserExitedWorkoutSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorUserExitedWorkoutSession"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorUserExitedWorkoutSession",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/erroruserexitedworkoutsession"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/executing-statistics-collection-queries": {
      "abstract": [
        {
          "text": "Calculate statistical data for graphs and charts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/executing-statistics-collection-queries",
      "kind": "article",
      "role": "article",
      "title": "Executing Statistics Collection Queries",
      "type": "topic",
      "url": "/documentation/healthkit/executing-statistics-collection-queries"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataUnavailable",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataRestricted",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorInvalidArgument",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationDenied",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationNotDetermined",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserCanceled",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAnotherWorkoutSessionStarted",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserExitedWorkoutSession",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNoData"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKErrorDatabaseInaccessible"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorDatabaseInaccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataUnavailable",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataRestricted",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorInvalidArgument",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationDenied",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationNotDetermined",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserCanceled",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAnotherWorkoutSessionStarted",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserExitedWorkoutSession",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNoData"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKErrorDatabaseInaccessible"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAnotherWorkoutSessionStarted/title",
          "value": "HKErrorAnotherWorkoutSessionStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAnotherWorkoutSessionStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorAnotherWorkoutSessionStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAuthorizationDenied/title",
          "value": "HKErrorAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAuthorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorUserCanceled/title",
          "value": "HKErrorUserCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorUserCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorUserCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorNoData/title",
          "value": "HKErrorNoData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorNoData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorNoData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorDatabaseInaccessible/title",
          "value": "HKErrorDatabaseInaccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorDatabaseInaccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorDatabaseInaccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAuthorizationNotDetermined/title",
          "value": "HKErrorAuthorizationNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAuthorizationNotDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorAuthorizationNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorHealthDataUnavailable/title",
          "value": "HKErrorHealthDataUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorHealthDataUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorHealthDataUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code/title",
          "value": "HKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorInvalidArgument/title",
          "value": "HKErrorInvalidArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorInvalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorInvalidArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorUserExitedWorkoutSession/title",
          "value": "HKErrorUserExitedWorkoutSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorUserExitedWorkoutSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorUserExitedWorkoutSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorHealthDataRestricted/title",
          "value": "HKErrorHealthDataRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorHealthDataRestricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorHealthDataRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorRequiredAuthorizationDenied/title",
          "value": "HKErrorRequiredAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorRequiredAuthorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorRequiredAuthorizationDenied"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkerror/code/errordatabaseinaccessible"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkerror/code/errordatabaseinaccessible"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
