{
  "abstract": [
    {
      "text": "A key that represents the name of the camera model.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyModel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataCommonKeyModel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "commonKeyModel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataKey",
        "text": "AVMetadataKey"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataCommonKeyModel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "commonKeyModel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "commonKeyModel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataKey",
              "text": "AVMetadataKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey": {
      "abstract": [
        {
          "text": "A structure that defines a metadata key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAccessibilityDescription": {
      "abstract": [
        {
          "text": "A key that represents the accessibility description for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyAccessibilityDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAccessibilityDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyAccessibilityDescription"
        }
      ],
      "role": "symbol",
      "title": "commonKeyAccessibilityDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeyaccessibilitydescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAlbumName": {
      "abstract": [
        {
          "text": "A key that represents the name of the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyAlbumName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAlbumName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyAlbumName"
        }
      ],
      "role": "symbol",
      "title": "commonKeyAlbumName",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeyalbumname"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtist": {
      "abstract": [
        {
          "text": "A key that represents the name of the artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyArtist"
        }
      ],
      "role": "symbol",
      "title": "commonKeyArtist",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeyartist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtwork": {
      "abstract": [
        {
          "text": "A key that represents an image relating to the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyArtwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyArtwork"
        }
      ],
      "role": "symbol",
      "title": "commonKeyArtwork",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeyartwork"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAuthor": {
      "abstract": [
        {
          "text": "A key that represents the name of the author.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyAuthor"
        }
      ],
      "role": "symbol",
      "title": "commonKeyAuthor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeyauthor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyContributor": {
      "abstract": [
        {
          "text": "A key that represents the name of the contributor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyContributor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyContributor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyContributor"
        }
      ],
      "role": "symbol",
      "title": "commonKeyContributor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeycontributor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCopyrights": {
      "abstract": [
        {
          "text": "A key that represents the copyright statement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyCopyrights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCopyrights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyCopyrights"
        }
      ],
      "role": "symbol",
      "title": "commonKeyCopyrights",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeycopyrights"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreationDate": {
      "abstract": [
        {
          "text": "A key that represents the date of the original recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyCreationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyCreationDate"
        }
      ],
      "role": "symbol",
      "title": "commonKeyCreationDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeycreationdate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreator": {
      "abstract": [
        {
          "text": "A key that represents the name of the creator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyCreator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyCreator"
        }
      ],
      "role": "symbol",
      "title": "commonKeyCreator",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeycreator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyDescription": {
      "abstract": [
        {
          "text": "A key that represents the description of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyDescription"
        }
      ],
      "role": "symbol",
      "title": "commonKeyDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeydescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyFormat": {
      "abstract": [
        {
          "text": "A key that represents the file format of the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyFormat"
        }
      ],
      "role": "symbol",
      "title": "commonKeyFormat",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeyformat"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyIdentifier": {
      "abstract": [
        {
          "text": "A key that represents the ID for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "commonKeyIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeyidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLanguage": {
      "abstract": [
        {
          "text": "A key that represents the language of the text or lyrics spoken or sung in the audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyLanguage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLanguage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyLanguage"
        }
      ],
      "role": "symbol",
      "title": "commonKeyLanguage",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeylanguage"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLastModifiedDate": {
      "abstract": [
        {
          "text": "A key that represents the last modification date of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyLastModifiedDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLastModifiedDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyLastModifiedDate"
        }
      ],
      "role": "symbol",
      "title": "commonKeyLastModifiedDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeylastmodifieddate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLocation": {
      "abstract": [
        {
          "text": "A key that represents the location information for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyLocation"
        }
      ],
      "role": "symbol",
      "title": "commonKeyLocation",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeylocation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyModel": {
      "abstract": [
        {
          "text": "A key that represents the name of the camera model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonKeyModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonKeyModel"
        }
      ],
      "role": "symbol",
      "title": "commonKeyModel",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/commonkeymodel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-Metadata-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAccessibilityDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAlbumName",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtist",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtwork",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAuthor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyContributor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCopyrights",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreationDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreator",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyFormat",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyIdentifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLanguage",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLastModifiedDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLocation"
      ],
      "title": "Common Metadata Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataCommonKeyModel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common-Metadata-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAccessibilityDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAlbumName",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtist",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtwork",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAuthor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyContributor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCopyrights",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreationDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreator",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyFormat",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyIdentifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLanguage",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLastModifiedDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLocation"
              ],
              "title": "Common Metadata Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataKey",
                    "text": "AVMetadataKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataCommonKeyModel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyContributor/title",
          "value": "AVMetadataCommonKeyContributor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyContributor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyContributor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyArtist/title",
          "value": "AVMetadataCommonKeyArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/title",
          "value": "AVMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAlbumName/title",
          "value": "AVMetadataCommonKeyAlbumName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAlbumName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyAlbumName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyIdentifier/title",
          "value": "AVMetadataCommonKeyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCreator/title",
          "value": "AVMetadataCommonKeyCreator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCreator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyModel/title",
          "value": "AVMetadataCommonKeyModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLocation/title",
          "value": "AVMetadataCommonKeyLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLanguage/title",
          "value": "AVMetadataCommonKeyLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLanguage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyDescription/title",
          "value": "AVMetadataCommonKeyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCopyrights/title",
          "value": "AVMetadataCommonKeyCopyrights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCopyrights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyCopyrights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyFormat/title",
          "value": "AVMetadataCommonKeyFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAccessibilityDescription/title",
          "value": "AVMetadataCommonKeyAccessibilityDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAccessibilityDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyAccessibilityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLastModifiedDate/title",
          "value": "AVMetadataCommonKeyLastModifiedDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLastModifiedDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyLastModifiedDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyArtwork/title",
          "value": "AVMetadataCommonKeyArtwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyArtwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyArtwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCreationDate/title",
          "value": "AVMetadataCommonKeyCreationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCreationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyCreationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAuthor/title",
          "value": "AVMetadataCommonKeyAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonKeyAuthor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/commonkeymodel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/commonkeymodel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
