{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey"]]},"metadata":{"role":"symbol","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"AVFoundation"}],"extendedModule":"AVFoundation","externalID":"c:@AVMetadataCommonKeyDescription","navigatorTitle":[{"text":"AVMetadataCommonKeyDescription","kind":"identifier"}],"platforms":[{"introducedAt":"4.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"4.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"10.7","name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"9.0","name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"1.0","name":"watchOS","unavailable":false,"beta":false,"deprecated":false}],"title":"commonKeyDescription"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avmetadatakey/commonkeydescription"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avmetadatakey/commonkeydescription"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyDescription"},"abstract":[{"text":"A key that represents the description of the media.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonKeyDescription"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey","text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Common-Metadata-Keys","title":"Common Metadata Keys","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAccessibilityDescription","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAlbumName","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtwork","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAuthor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyContributor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCopyrights","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreationDate","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreator","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyFormat","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyIdentifier","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLanguage","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLastModifiedDate","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLocation","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyMake"],"generated":true}],"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyContributor":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonKeyContributor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"type":"topic","abstract":[{"type":"text","text":"A key that represents the name of the contributor."}],"kind":"symbol","role":"symbol","title":"commonKeyContributor","url":"/documentation/avfoundation/avmetadatakey/commonkeycontributor","navigatorTitle":[{"kind":"identifier","text":"AVMetadataCommonKeyContributor"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyContributor"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAuthor":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyAuthor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AVMetadataKey","text":"AVMetadataKey","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"AVMetadataCommonKeyAuthor","kind":"identifier"}],"url":"/documentation/avfoundation/avmetadatakey/commonkeyauthor","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAuthor","abstract":[{"text":"A key that represents the name of the author.","type":"text"}],"kind":"symbol","title":"commonKeyAuthor"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyDescription":{"abstract":[{"text":"A key that represents the description of the media.","type":"text"}],"title":"commonKeyDescription","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyDescription","role":"symbol","url":"/documentation/avfoundation/avmetadatakey/commonkeydescription","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AVMetadataKey","text":"AVMetadataKey","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"AVMetadataCommonKeyDescription","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyIdentifier":{"url":"/documentation/avfoundation/avmetadatakey/commonkeyidentifier","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVMetadataCommonKeyIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"A key that represents the ID for the media."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyIdentifier","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonKeyIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"title":"commonKeyIdentifier"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAlbumName":{"abstract":[{"type":"text","text":"A key that represents the name of the album."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonKeyAlbumName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"}],"type":"topic","title":"commonKeyAlbumName","role":"symbol","url":"/documentation/avfoundation/avmetadatakey/commonkeyalbumname","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAlbumName","navigatorTitle":[{"kind":"identifier","text":"AVMetadataCommonKeyAlbumName"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCopyrights":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCopyrights","abstract":[{"text":"A key that represents the copyright statement.","type":"text"}],"kind":"symbol","title":"commonKeyCopyrights","url":"/documentation/avfoundation/avmetadatakey/commonkeycopyrights","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyCopyrights","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"AVMetadataCommonKeyCopyrights","kind":"identifier"}],"role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreator":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyCreator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreator","type":"topic","title":"commonKeyCreator","kind":"symbol","navigatorTitle":[{"text":"AVMetadataCommonKeyCreator","kind":"identifier"}],"abstract":[{"text":"A key that represents the name of the creator.","type":"text"}],"url":"/documentation/avfoundation/avmetadatakey/commonkeycreator"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreationDate":{"navigatorTitle":[{"text":"AVMetadataCommonKeyCreationDate","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyCreationDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A key that represents the date of the original recording."}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreationDate","title":"commonKeyCreationDate","url":"/documentation/avfoundation/avmetadatakey/commonkeycreationdate"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtist":{"url":"/documentation/avfoundation/avmetadatakey/commonkeyartist","title":"commonKeyArtist","navigatorTitle":[{"text":"AVMetadataCommonKeyArtist","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtist","kind":"symbol","abstract":[{"text":"A key that represents the name of the artist.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyArtist","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAccessibilityDescription":{"kind":"symbol","navigatorTitle":[{"text":"AVMetadataCommonKeyAccessibilityDescription","kind":"identifier"}],"role":"symbol","title":"commonKeyAccessibilityDescription","url":"/documentation/avfoundation/avmetadatakey/commonkeyaccessibilitydescription","abstract":[{"type":"text","text":"A key that represents the accessibility description for the media."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyAccessibilityDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAccessibilityDescription","type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyMake":{"url":"/documentation/avfoundation/avmetadatakey/commonkeymake","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyMake","navigatorTitle":[{"text":"AVMetadataCommonKeyMake","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonKeyMake"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"title":"commonKeyMake","abstract":[{"type":"text","text":"A key that represents the name of the camera maker."}],"role":"symbol","type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLastModifiedDate":{"title":"commonKeyLastModifiedDate","kind":"symbol","url":"/documentation/avfoundation/avmetadatakey/commonkeylastmodifieddate","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLastModifiedDate","abstract":[{"text":"A key that represents the last modification date of the media.","type":"text"}],"navigatorTitle":[{"text":"AVMetadataCommonKeyLastModifiedDate","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyLastModifiedDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtwork":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonKeyArtwork"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"navigatorTitle":[{"text":"AVMetadataCommonKeyArtwork","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtwork","role":"symbol","title":"commonKeyArtwork","url":"/documentation/avfoundation/avmetadatakey/commonkeyartwork","type":"topic","abstract":[{"type":"text","text":"A key that represents an image relating to the album."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLanguage":{"url":"/documentation/avfoundation/avmetadatakey/commonkeylanguage","navigatorTitle":[{"kind":"identifier","text":"AVMetadataCommonKeyLanguage"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonKeyLanguage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey","text":"AVMetadataKey"}],"type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLanguage","abstract":[{"type":"text","text":"A key that represents the language of the text or lyrics spoken or sung in the audio."}],"title":"commonKeyLanguage","kind":"symbol","role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLocation":{"role":"symbol","title":"commonKeyLocation","kind":"symbol","navigatorTitle":[{"text":"AVMetadataCommonKeyLocation","kind":"identifier"}],"abstract":[{"type":"text","text":"A key that represents the location information for the media."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLocation","url":"/documentation/avfoundation/avmetadatakey/commonkeylocation","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonKeyLocation"},{"kind":"text","text":": "},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVMetadataKey","kind":"identifier"}],"navigatorTitle":[{"text":"AVMetadataKey","kind":"identifier"}],"abstract":[{"type":"text","text":"A structure that defines a metadata key."}],"type":"topic","title":"AVMetadataKey","url":"/documentation/avfoundation/avmetadatakey","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyFormat":{"navigatorTitle":[{"text":"AVMetadataCommonKeyFormat","kind":"identifier"}],"title":"commonKeyFormat","type":"topic","url":"/documentation/avfoundation/avmetadatakey/commonkeyformat","role":"symbol","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyFormat","abstract":[{"text":"A key that represents the file format of the media content.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commonKeyFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"4.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"4.0","unavailable":false,"beta":false,"name":"iPadOS"},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"introducedAt":"10.7","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false},{"name":"watchOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}],"op":"replace"},{"value":"Global Variable","path":"/metadata/roleHeading","op":"replace"},{"value":"AVMetadataCommonKeyDescription","path":"/metadata/title","op":"replace"},{"value":"var","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"AVMetadataCommonKeyDescription","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAccessibilityDescription","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAlbumName","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyArtwork","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyAuthor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyContributor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCopyrights","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreationDate","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyCreator","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyFormat","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyIdentifier","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLanguage","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLastModifiedDate","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyLocation","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/commonKeyMake"],"title":"Common Metadata Keys","anchor":"Common-Metadata-Keys"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"AVMetadataKey","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVMetadataCommonKeyDescription","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"AVMetadataCommonKeyContributor","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyContributor/title","op":"replace"},{"value":[{"text":"AVMetadataCommonKeyContributor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyContributor/fragments","op":"replace"},{"value":"AVMetadataCommonKeyAuthor","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAuthor/title"},{"value":[{"kind":"identifier","text":"AVMetadataCommonKeyAuthor"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAuthor/fragments"},{"value":"AVMetadataCommonKeyDescription","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyDescription/title"},{"value":[{"text":"AVMetadataCommonKeyDescription","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyDescription/fragments"},{"value":"AVMetadataCommonKeyIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyIdentifier/title"},{"value":[{"text":"AVMetadataCommonKeyIdentifier","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyIdentifier/fragments"},{"value":"AVMetadataCommonKeyAlbumName","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAlbumName/title"},{"value":[{"text":"AVMetadataCommonKeyAlbumName","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAlbumName/fragments"},{"value":"AVMetadataCommonKeyCopyrights","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCopyrights/title"},{"value":[{"kind":"identifier","text":"AVMetadataCommonKeyCopyrights"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCopyrights/fragments"},{"value":"AVMetadataCommonKeyCreator","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCreator/title"},{"value":[{"kind":"identifier","text":"AVMetadataCommonKeyCreator"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCreator/fragments"},{"value":"AVMetadataCommonKeyCreationDate","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCreationDate/title"},{"value":[{"text":"AVMetadataCommonKeyCreationDate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyCreationDate/fragments"},{"value":"AVMetadataCommonKeyArtist","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyArtist/title"},{"value":[{"text":"AVMetadataCommonKeyArtist","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyArtist/fragments"},{"value":"AVMetadataCommonKeyAccessibilityDescription","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAccessibilityDescription/title"},{"value":[{"kind":"identifier","text":"AVMetadataCommonKeyAccessibilityDescription"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyAccessibilityDescription/fragments"},{"value":"AVMetadataCommonKeyMake","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyMake/title"},{"value":[{"kind":"identifier","text":"AVMetadataCommonKeyMake"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyMake/fragments"},{"value":"AVMetadataCommonKeyLastModifiedDate","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLastModifiedDate/title"},{"value":[{"kind":"identifier","text":"AVMetadataCommonKeyLastModifiedDate"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLastModifiedDate/fragments"},{"value":"AVMetadataCommonKeyArtwork","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyArtwork/title"},{"value":[{"text":"AVMetadataCommonKeyArtwork","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyArtwork/fragments"},{"value":"AVMetadataCommonKeyLanguage","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLanguage/title"},{"value":[{"kind":"identifier","text":"AVMetadataCommonKeyLanguage"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLanguage/fragments"},{"value":"AVMetadataCommonKeyLocation","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLocation/title"},{"value":[{"kind":"identifier","text":"AVMetadataCommonKeyLocation"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyLocation/fragments"},{"value":"AVMetadataKey","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/title"},{"value":[{"text":"AVMetadataKey","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/fragments"},{"value":[{"kind":"identifier","text":"AVMetadataKey"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/navigatorTitle"},{"value":"AVMetadataCommonKeyFormat","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyFormat/title"},{"value":[{"kind":"identifier","text":"AVMetadataCommonKeyFormat"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1commonKeyFormat/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}