{
  "abstract": [
    {
      "text": "A key that represents the location of other tags in a file or stream.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeySeek"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataID3MetadataKeySeek",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "id3MetadataKeySeek"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataKey",
        "text": "AVMetadataKey"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataID3MetadataKeySeek"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "id3MetadataKeySeek"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "id3MetadataKeySeek"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataKey",
              "text": "AVMetadataKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey": {
      "abstract": [
        {
          "text": "A structure that defines a metadata key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAlbumSortOrder": {
      "abstract": [
        {
          "text": "A key that represents how to sort the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyAlbumSortOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAlbumSortOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyAlbumSortOrder"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyAlbumSortOrder",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeyalbumsortorder"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAlbumTitle": {
      "abstract": [
        {
          "text": "A key that represents the title of the recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyAlbumTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAlbumTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyAlbumTitle"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyAlbumTitle",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeyalbumtitle"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAttachedPicture": {
      "abstract": [
        {
          "text": "A key that represents an image relating to the audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyAttachedPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAttachedPicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyAttachedPicture"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyAttachedPicture",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeyattachedpicture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAudioEncryption": {
      "abstract": [
        {
          "text": "A key that represents the encryption details of the audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyAudioEncryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAudioEncryption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyAudioEncryption"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyAudioEncryption",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeyaudioencryption"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAudioSeekPointIndex": {
      "abstract": [
        {
          "text": "A key that represents the list of seek points within the audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyAudioSeekPointIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAudioSeekPointIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyAudioSeekPointIndex"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyAudioSeekPointIndex",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeyaudioseekpointindex"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyBand": {
      "abstract": [
        {
          "text": "A key that represents additional information about the performers in the recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyBand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyBand"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyBand",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeyband"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyBeatsPerMinute": {
      "abstract": [
        {
          "text": "A key that represents the beats per minute of the audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyBeatsPerMinute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyBeatsPerMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyBeatsPerMinute"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyBeatsPerMinute",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeybeatsperminute"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyComments": {
      "abstract": [
        {
          "text": "A key that represents additional text information for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyComments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyComments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyComments"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyComments",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeycomments"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCommercial": {
      "abstract": [
        {
          "text": "A key that represents the commercial details for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyCommercial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCommercial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyCommercial"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyCommercial",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeycommercial"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCommercialInformation": {
      "abstract": [
        {
          "text": "A key that represents the webpage containing purchasing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyCommercialInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCommercialInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyCommercialInformation"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyCommercialInformation",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeycommercialinformation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyComposer": {
      "abstract": [
        {
          "text": "A key that represents the name of the composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyComposer"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyComposer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeycomposer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyConductor": {
      "abstract": [
        {
          "text": "A key that represents the name of the conductor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyConductor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyConductor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyConductor"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyConductor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeyconductor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyContentGroupDescription": {
      "abstract": [
        {
          "text": "A key that indicates the sound belongs to a larger category of sounds or music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyContentGroupDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyContentGroupDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyContentGroupDescription"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyContentGroupDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeycontentgroupdescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyContentType": {
      "abstract": [
        {
          "text": "A key that represents the media content type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyContentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyContentType"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyContentType",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeycontenttype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCopyright": {
      "abstract": [
        {
          "text": "A key that represents the copyright statement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeyCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeyCopyright"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeyCopyright",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeycopyright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeySeek": {
      "abstract": [
        {
          "text": "A key that represents the location of other tags in a file or stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataKeySeek"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeySeek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataID3MetadataKeySeek"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataKeySeek",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/id3metadatakeyseek"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "ID3-Metadata-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAlbumSortOrder",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAlbumTitle",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAttachedPicture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAudioEncryption",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAudioSeekPointIndex",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyBand",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyBeatsPerMinute",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyComments",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCommercial",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCommercialInformation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyComposer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyConductor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyContentGroupDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyContentType",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCopyright"
      ],
      "title": "ID3 Metadata Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataID3MetadataKeySeek"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeySeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "ID3-Metadata-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAlbumSortOrder",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAlbumTitle",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAttachedPicture",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAudioEncryption",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyAudioSeekPointIndex",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyBand",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyBeatsPerMinute",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyComments",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCommercial",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCommercialInformation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyComposer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyConductor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyContentGroupDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyContentType",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/id3MetadataKeyCopyright"
              ],
              "title": "ID3 Metadata Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataKey",
                    "text": "AVMetadataKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataID3MetadataKeySeek"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyCommercialInformation/title",
          "value": "AVMetadataID3MetadataKeyCommercialInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyCommercialInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyCommercialInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAudioEncryption/title",
          "value": "AVMetadataID3MetadataKeyAudioEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAudioEncryption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyAudioEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAudioSeekPointIndex/title",
          "value": "AVMetadataID3MetadataKeyAudioSeekPointIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAudioSeekPointIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyAudioSeekPointIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyConductor/title",
          "value": "AVMetadataID3MetadataKeyConductor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyConductor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyConductor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyContentGroupDescription/title",
          "value": "AVMetadataID3MetadataKeyContentGroupDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyContentGroupDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyContentGroupDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyCommercial/title",
          "value": "AVMetadataID3MetadataKeyCommercial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyCommercial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyCommercial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyBeatsPerMinute/title",
          "value": "AVMetadataID3MetadataKeyBeatsPerMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyBeatsPerMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyBeatsPerMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAlbumTitle/title",
          "value": "AVMetadataID3MetadataKeyAlbumTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAlbumTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyAlbumTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyComposer/title",
          "value": "AVMetadataID3MetadataKeyComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyComments/title",
          "value": "AVMetadataID3MetadataKeyComments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyComments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyComments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/title",
          "value": "AVMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyContentType/title",
          "value": "AVMetadataID3MetadataKeyContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeySeek/title",
          "value": "AVMetadataID3MetadataKeySeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeySeek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeySeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAttachedPicture/title",
          "value": "AVMetadataID3MetadataKeyAttachedPicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAttachedPicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyAttachedPicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyBand/title",
          "value": "AVMetadataID3MetadataKeyBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAlbumSortOrder/title",
          "value": "AVMetadataID3MetadataKeyAlbumSortOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyAlbumSortOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyAlbumSortOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyCopyright/title",
          "value": "AVMetadataID3MetadataKeyCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1id3MetadataKeyCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataID3MetadataKeyCopyright"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/id3metadatakeyseek"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/id3metadatakeyseek"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
