{"metadata":{"externalID":"c:@AVMetadataiTunesMetadataKeyAcknowledgement","extendedModule":"AVFoundation","modules":[{"name":"AVFoundation"}],"roleHeading":"Type Property","platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"4.0"},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"4.0"},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.1"},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"10.7"},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"9.0"},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"1.0"},{"name":"watchOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"title":"iTunesMetadataKeyAcknowledgement","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyAcknowledgement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey","text":"AVMetadataKey"}],"navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAcknowledgement"}],"role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey"]]},"variants":[{"paths":["/documentation/avfoundation/avmetadatakey/itunesmetadatakeyacknowledgement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avmetadatakey/itunesmetadatakeyacknowledgement"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"title":"iTunes Metadata Keys","anchor":"iTunes-Metadata-Keys","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAccountKind","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbum","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbumArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAppleID","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArranger","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtDirector","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtistID","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAuthor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyBeatsPerMin","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyComposer","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyConductor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyContentRating","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCopyright","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCoverArt"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A key that represents the acknowledgement information in iTunes.","type":"text"}],"kind":"symbol","identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAcknowledgement","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyAcknowledgement","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AVMetadataKey","text":"AVMetadataKey","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyBeatsPerMin":{"role":"symbol","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyBeatsPerMin","kind":"identifier"}],"title":"iTunesMetadataKeyBeatsPerMin","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyBeatsPerMin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"abstract":[{"text":"A key that represents the beats per minute of a track in iTunes.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyBeatsPerMin","type":"topic","kind":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeybeatspermin"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAcknowledgement":{"navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAcknowledgement"}],"title":"iTunesMetadataKeyAcknowledgement","abstract":[{"type":"text","text":"A key that represents the acknowledgement information in iTunes."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyAcknowledgement"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"role":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyacknowledgement","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAcknowledgement","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbumArtist":{"abstract":[{"text":"A key that represents the artist for the album.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbumArtist","title":"iTunesMetadataKeyAlbumArtist","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyAlbumArtist","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyAlbumArtist","kind":"identifier"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyalbumartist","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVMetadataKey","kind":"identifier"}],"navigatorTitle":[{"text":"AVMetadataKey","kind":"identifier"}],"abstract":[{"type":"text","text":"A structure that defines a metadata key."}],"type":"topic","title":"AVMetadataKey","url":"/documentation/avfoundation/avmetadatakey","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyComposer":{"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyComposer","title":"iTunesMetadataKeyComposer","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyComposer","kind":"identifier"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeycomposer","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyComposer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"A key that represents the name of the composer.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyConductor":{"abstract":[{"type":"text","text":"A key that represents the name of the conductor."}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyConductor","title":"iTunesMetadataKeyConductor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyConductor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"}],"navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyConductor"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyconductor","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAppleID":{"navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyAppleID","kind":"identifier"}],"title":"iTunesMetadataKeyAppleID","abstract":[{"text":"A key that represents an Apple ID.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyAppleID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"role":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyappleid","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAppleID","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtDirector":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtDirector","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyArtDirector","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyArtDirector","kind":"identifier"}],"abstract":[{"text":"A key that represents the name of the art director.","type":"text"}],"type":"topic","title":"iTunesMetadataKeyArtDirector","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyartdirector","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCopyright":{"abstract":[{"text":"A key that represents the copyright statement in iTunes.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCopyright","title":"iTunesMetadataKeyCopyright","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyCopyright","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyCopyright","kind":"identifier"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeycopyright","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArranger":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArranger","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyArranger"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArranger"}],"abstract":[{"type":"text","text":"A key that represents the name of the arranger."}],"type":"topic","title":"iTunesMetadataKeyArranger","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyarranger","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCoverArt":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyCoverArt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"title":"iTunesMetadataKeyCoverArt","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeycoverart","kind":"symbol","abstract":[{"type":"text","text":"A key that represents an album cover image."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCoverArt","type":"topic","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyCoverArt","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtistID":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArtistID"}],"title":"iTunesMetadataKeyArtistID","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyArtistID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"}],"abstract":[{"type":"text","text":"A key that represents the ID for an artist."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtistID","type":"topic","kind":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyartistid"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAccountKind":{"role":"symbol","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyAccountKind","kind":"identifier"}],"title":"iTunesMetadataKeyAccountKind","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyAccountKind","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"abstract":[{"text":"A key that represents the kind of iTunes account.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAccountKind","type":"topic","kind":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyaccountkind"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyContentRating":{"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyContentRating","title":"iTunesMetadataKeyContentRating","navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyContentRating"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeycontentrating","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyContentRating"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"role":"symbol","abstract":[{"type":"text","text":"A key that represents the content rating in iTunes."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbum":{"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyalbum","navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAlbum"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbum","title":"iTunesMetadataKeyAlbum","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyAlbum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"}],"type":"topic","abstract":[{"type":"text","text":"A key that represents the name of the album in iTunes."}],"role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAuthor":{"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAuthor","title":"iTunesMetadataKeyAuthor","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyAuthor","kind":"identifier"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyauthor","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyAuthor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"A key that represents the name of the author.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtist":{"navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArtist"}],"title":"iTunesMetadataKeyArtist","abstract":[{"type":"text","text":"A key that represents the name of the artist."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyArtist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"}],"role":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyartist","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtist","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","beta":false,"unavailable":false,"introducedAt":"4.0","deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"4.0","deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.1","deprecated":false},{"name":"macOS","beta":false,"unavailable":false,"introducedAt":"10.7","deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"introducedAt":"9.0","deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0","deprecated":false},{"name":"watchOS","beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Global Variable","path":"/metadata/roleHeading"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyAcknowledgement","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"AVMetadataiTunesMetadataKeyAcknowledgement","kind":"identifier"}],"path":"/metadata/fragments"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"iTunes Metadata Keys","anchor":"iTunes-Metadata-Keys","generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAccountKind","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbum","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbumArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAppleID","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArranger","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtDirector","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtistID","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAuthor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyBeatsPerMin","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyComposer","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyConductor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyContentRating","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCopyright","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCoverArt"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey","text":"AVMetadataKey","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAcknowledgement"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"AVMetadataiTunesMetadataKeyBeatsPerMin","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyBeatsPerMin/title"},{"value":[{"text":"AVMetadataiTunesMetadataKeyBeatsPerMin","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyBeatsPerMin/fragments"},{"value":"AVMetadataiTunesMetadataKeyAcknowledgement","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAcknowledgement/title"},{"value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAcknowledgement"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAcknowledgement/fragments"},{"value":"AVMetadataiTunesMetadataKeyAlbumArtist","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAlbumArtist/title"},{"value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAlbumArtist"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAlbumArtist/fragments"},{"value":"AVMetadataKey","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/title"},{"value":[{"kind":"identifier","text":"AVMetadataKey"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/fragments"},{"value":[{"text":"AVMetadataKey","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/navigatorTitle"},{"value":"AVMetadataiTunesMetadataKeyComposer","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyComposer/title"},{"op":"replace","value":[{"text":"AVMetadataiTunesMetadataKeyComposer","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyComposer/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyConductor","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyConductor/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyConductor"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyConductor/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyAppleID","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAppleID/title"},{"op":"replace","value":[{"text":"AVMetadataiTunesMetadataKeyAppleID","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAppleID/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyArtDirector","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtDirector/title"},{"op":"replace","value":[{"text":"AVMetadataiTunesMetadataKeyArtDirector","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtDirector/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyCopyright","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyCopyright/title"},{"op":"replace","value":[{"text":"AVMetadataiTunesMetadataKeyCopyright","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyCopyright/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyArranger","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArranger/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArranger"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArranger/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyCoverArt","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyCoverArt/title"},{"op":"replace","value":[{"text":"AVMetadataiTunesMetadataKeyCoverArt","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyCoverArt/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyArtistID","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtistID/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArtistID"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtistID/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyAccountKind","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAccountKind/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAccountKind"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAccountKind/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyContentRating","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyContentRating/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyContentRating"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyContentRating/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyAlbum","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAlbum/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAlbum"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAlbum/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyAuthor","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAuthor/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAuthor"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAuthor/fragments"},{"op":"replace","value":"AVMetadataiTunesMetadataKeyArtist","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtist/title"},{"op":"replace","value":[{"text":"AVMetadataiTunesMetadataKeyArtist","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtist/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}