{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyContentRating"},"kind":"symbol","abstract":[{"type":"text","text":"A key that represents the content rating in iTunes."}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyContentRating"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"role":"symbol","platforms":[{"introducedAt":"4.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"4.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"introducedAt":"10.7","beta":false,"name":"macOS","unavailable":false,"deprecated":false},{"introducedAt":"9.0","beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"watchOS","unavailable":false,"deprecated":false}],"navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyContentRating","kind":"identifier"}],"roleHeading":"Type Property","extendedModule":"AVFoundation","modules":[{"name":"AVFoundation"}],"title":"iTunesMetadataKeyContentRating","externalID":"c:@AVMetadataiTunesMetadataKeyContentRating"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey"]]},"seeAlsoSections":[{"anchor":"iTunes-Metadata-Keys","title":"iTunes Metadata Keys","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAccountKind","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAcknowledgement","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbum","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbumArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAppleID","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArranger","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtDirector","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtistID","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAuthor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyBeatsPerMin","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyComposer","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyConductor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCopyright","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCoverArt"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyContentRating"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey","text":"AVMetadataKey"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]}],"variants":[{"paths":["/documentation/avfoundation/avmetadatakey/itunesmetadatakeycontentrating"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avmetadatakey/itunesmetadatakeycontentrating"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtistID":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArtistID"}],"title":"iTunesMetadataKeyArtistID","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyArtistID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"}],"abstract":[{"type":"text","text":"A key that represents the ID for an artist."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtistID","type":"topic","kind":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyartistid"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyComposer":{"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyComposer","title":"iTunesMetadataKeyComposer","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyComposer","kind":"identifier"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeycomposer","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyComposer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"A key that represents the name of the composer.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAppleID":{"navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyAppleID","kind":"identifier"}],"title":"iTunesMetadataKeyAppleID","abstract":[{"text":"A key that represents an Apple ID.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyAppleID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"role":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyappleid","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAppleID","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbumArtist":{"abstract":[{"text":"A key that represents the artist for the album.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbumArtist","title":"iTunesMetadataKeyAlbumArtist","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyAlbumArtist","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyAlbumArtist","kind":"identifier"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyalbumartist","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtist":{"navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArtist"}],"title":"iTunesMetadataKeyArtist","abstract":[{"type":"text","text":"A key that represents the name of the artist."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyArtist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"}],"role":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyartist","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtist","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbum":{"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyalbum","navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAlbum"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbum","title":"iTunesMetadataKeyAlbum","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyAlbum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"}],"type":"topic","abstract":[{"type":"text","text":"A key that represents the name of the album in iTunes."}],"role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyContentRating":{"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyContentRating","title":"iTunesMetadataKeyContentRating","navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyContentRating"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeycontentrating","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyContentRating"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"role":"symbol","abstract":[{"type":"text","text":"A key that represents the content rating in iTunes."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCoverArt":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyCoverArt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"title":"iTunesMetadataKeyCoverArt","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeycoverart","kind":"symbol","abstract":[{"type":"text","text":"A key that represents an album cover image."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCoverArt","type":"topic","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyCoverArt","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAccountKind":{"role":"symbol","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyAccountKind","kind":"identifier"}],"title":"iTunesMetadataKeyAccountKind","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyAccountKind","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"abstract":[{"text":"A key that represents the kind of iTunes account.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAccountKind","type":"topic","kind":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyaccountkind"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAuthor":{"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAuthor","title":"iTunesMetadataKeyAuthor","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyAuthor","kind":"identifier"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyauthor","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyAuthor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"A key that represents the name of the author.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyBeatsPerMin":{"role":"symbol","navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyBeatsPerMin","kind":"identifier"}],"title":"iTunesMetadataKeyBeatsPerMin","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyBeatsPerMin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVMetadataKey"}],"abstract":[{"text":"A key that represents the beats per minute of a track in iTunes.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyBeatsPerMin","type":"topic","kind":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeybeatspermin"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArranger":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArranger","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyArranger"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArranger"}],"abstract":[{"type":"text","text":"A key that represents the name of the arranger."}],"type":"topic","title":"iTunesMetadataKeyArranger","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyarranger","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtDirector":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtDirector","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyArtDirector","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyArtDirector","kind":"identifier"}],"abstract":[{"text":"A key that represents the name of the art director.","type":"text"}],"type":"topic","title":"iTunesMetadataKeyArtDirector","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyartdirector","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVMetadataKey","kind":"identifier"}],"navigatorTitle":[{"text":"AVMetadataKey","kind":"identifier"}],"abstract":[{"type":"text","text":"A structure that defines a metadata key."}],"type":"topic","title":"AVMetadataKey","url":"/documentation/avfoundation/avmetadatakey","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCopyright":{"abstract":[{"text":"A key that represents the copyright statement in iTunes.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCopyright","title":"iTunesMetadataKeyCopyright","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iTunesMetadataKeyCopyright","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"AVMetadataiTunesMetadataKeyCopyright","kind":"identifier"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeycopyright","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyConductor":{"abstract":[{"type":"text","text":"A key that represents the name of the conductor."}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyConductor","title":"iTunesMetadataKeyConductor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyConductor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"}],"navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyConductor"}],"url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyconductor","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAcknowledgement":{"navigatorTitle":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAcknowledgement"}],"title":"iTunesMetadataKeyAcknowledgement","abstract":[{"type":"text","text":"A key that represents the acknowledgement information in iTunes."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTunesMetadataKeyAcknowledgement"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AVMetadataKey","kind":"typeIdentifier","text":"AVMetadataKey"}],"role":"symbol","url":"/documentation/avfoundation/avmetadatakey/itunesmetadatakeyacknowledgement","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAcknowledgement","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"4.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"4.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"introducedAt":"10.7","beta":false,"name":"macOS","unavailable":false,"deprecated":false},{"introducedAt":"9.0","beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"watchOS","unavailable":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Global Variable"},{"op":"replace","path":"/metadata/title","value":"AVMetadataiTunesMetadataKeyContentRating"},{"op":"replace","path":"/metadata/symbolKind","value":"var"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyContentRating"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"iTunes-Metadata-Keys","generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAccountKind","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAcknowledgement","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbum","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAlbumArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAppleID","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArranger","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtDirector","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtist","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyArtistID","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyAuthor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyBeatsPerMin","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyComposer","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyConductor","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCopyright","doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/iTunesMetadataKeyCoverArt"],"title":"iTunes Metadata Keys"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"AVMetadataKey","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey","preciseIdentifier":"c:@T@AVMetadataKey"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyContentRating"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtistID/title","value":"AVMetadataiTunesMetadataKeyArtistID"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtistID/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArtistID"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyComposer/title","value":"AVMetadataiTunesMetadataKeyComposer"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyComposer/fragments","value":[{"text":"AVMetadataiTunesMetadataKeyComposer","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAppleID/title","value":"AVMetadataiTunesMetadataKeyAppleID"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAppleID/fragments","value":[{"text":"AVMetadataiTunesMetadataKeyAppleID","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAlbumArtist/title","value":"AVMetadataiTunesMetadataKeyAlbumArtist"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAlbumArtist/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAlbumArtist"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtist/title","value":"AVMetadataiTunesMetadataKeyArtist"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtist/fragments","value":[{"text":"AVMetadataiTunesMetadataKeyArtist","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAlbum/title","value":"AVMetadataiTunesMetadataKeyAlbum"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAlbum/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAlbum"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyContentRating/title","value":"AVMetadataiTunesMetadataKeyContentRating"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyContentRating/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyContentRating"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyCoverArt/title","value":"AVMetadataiTunesMetadataKeyCoverArt"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyCoverArt/fragments","value":[{"text":"AVMetadataiTunesMetadataKeyCoverArt","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAccountKind/title","value":"AVMetadataiTunesMetadataKeyAccountKind"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAccountKind/fragments","value":[{"text":"AVMetadataiTunesMetadataKeyAccountKind","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAuthor/title","value":"AVMetadataiTunesMetadataKeyAuthor"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAuthor/fragments","value":[{"text":"AVMetadataiTunesMetadataKeyAuthor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyBeatsPerMin/title","value":"AVMetadataiTunesMetadataKeyBeatsPerMin"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyBeatsPerMin/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyBeatsPerMin"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArranger/title","value":"AVMetadataiTunesMetadataKeyArranger"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArranger/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArranger"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtDirector/title","value":"AVMetadataiTunesMetadataKeyArtDirector"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyArtDirector/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyArtDirector"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/title","value":"AVMetadataKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/fragments","value":[{"kind":"identifier","text":"AVMetadataKey"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/navigatorTitle","value":[{"text":"AVMetadataKey","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyCopyright/title","value":"AVMetadataiTunesMetadataKeyCopyright"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyCopyright/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyCopyright"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyConductor/title","value":"AVMetadataiTunesMetadataKeyConductor"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyConductor/fragments","value":[{"text":"AVMetadataiTunesMetadataKeyConductor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAcknowledgement/title","value":"AVMetadataiTunesMetadataKeyAcknowledgement"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1iTunesMetadataKeyAcknowledgement/fragments","value":[{"kind":"identifier","text":"AVMetadataiTunesMetadataKeyAcknowledgement"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}