{
  "abstract": [
    {
      "text": "A key that represents the classification of the media content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyMediaClassification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadata3GPUserDataKeyMediaClassification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "metadata3GPUserDataKeyMediaClassification"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataKey",
        "text": "AVMetadataKey"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadata3GPUserDataKeyMediaClassification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "metadata3GPUserDataKeyMediaClassification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "metadata3GPUserDataKeyMediaClassification"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataKey",
              "text": "AVMetadataKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey": {
      "abstract": [
        {
          "text": "A structure that defines a metadata key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyAlbumAndTrack": {
      "abstract": [
        {
          "text": "A key that represents the text for the album and track titles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyAlbumAndTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyAlbumAndTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyAlbumAndTrack"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyAlbumAndTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeyalbumandtrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyAuthor": {
      "abstract": [
        {
          "text": "A key that represents the author of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyAuthor"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyAuthor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeyauthor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyCollection": {
      "abstract": [
        {
          "text": "A key that represents the collection name for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyCollection"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyCollection",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeycollection"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyCopyright": {
      "abstract": [
        {
          "text": "A key that represents the copyright statement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyCopyright"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyCopyright",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeycopyright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyDescription": {
      "abstract": [
        {
          "text": "A key that represents the description for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyDescription"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeydescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyGenre": {
      "abstract": [
        {
          "text": "A key that represents the genre of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyGenre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyGenre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyGenre"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyGenre",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeygenre"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyKeywordList": {
      "abstract": [
        {
          "text": "A key that represents the list of keywords for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyKeywordList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyKeywordList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyKeywordList"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyKeywordList",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeykeywordlist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyLocation": {
      "abstract": [
        {
          "text": "A key that represents the location information for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyLocation"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyLocation",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeylocation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyMediaClassification": {
      "abstract": [
        {
          "text": "A key that represents the classification of the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyMediaClassification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyMediaClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyMediaClassification"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyMediaClassification",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeymediaclassification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyMediaRating": {
      "abstract": [
        {
          "text": "A key that represents the rating of the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyMediaRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyMediaRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyMediaRating"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyMediaRating",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeymediarating"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyPerformer": {
      "abstract": [
        {
          "text": "A key that represents information about the performer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyPerformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyPerformer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyPerformer"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyPerformer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeyperformer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyRecordingYear": {
      "abstract": [
        {
          "text": "A key that represents the recording year for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyRecordingYear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyRecordingYear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyRecordingYear"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyRecordingYear",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeyrecordingyear"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyThumbnail": {
      "abstract": [
        {
          "text": "A key that represents the media thumbnail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyThumbnail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyThumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyThumbnail"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyThumbnail",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeythumbnail"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyTitle": {
      "abstract": [
        {
          "text": "A key that represents the title for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyTitle"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyTitle",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeytitle"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyUserRating": {
      "abstract": [
        {
          "text": "A key that represents the user rating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata3GPUserDataKeyUserRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyUserRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadata3GPUserDataKeyUserRating"
        }
      ],
      "role": "symbol",
      "title": "metadata3GPUserDataKeyUserRating",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeyuserrating"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "3GP-User-Metadata-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyAlbumAndTrack",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyAuthor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyCollection",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyCopyright",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyGenre",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyKeywordList",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyLocation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyMediaRating",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyPerformer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyRecordingYear",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyThumbnail",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyTitle",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyUserRating"
      ],
      "title": "3GP User Metadata Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadata3GPUserDataKeyMediaClassification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyMediaClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "3GP-User-Metadata-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyAlbumAndTrack",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyAuthor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyCollection",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyCopyright",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyGenre",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyKeywordList",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyLocation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyMediaRating",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyPerformer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyRecordingYear",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyThumbnail",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyTitle",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/metadata3GPUserDataKeyUserRating"
              ],
              "title": "3GP User Metadata Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataKey",
                    "text": "AVMetadataKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadata3GPUserDataKeyMediaClassification"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyKeywordList/title",
          "value": "AVMetadata3GPUserDataKeyKeywordList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyKeywordList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyKeywordList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyTitle/title",
          "value": "AVMetadata3GPUserDataKeyTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyThumbnail/title",
          "value": "AVMetadata3GPUserDataKeyThumbnail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyThumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyThumbnail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyCollection/title",
          "value": "AVMetadata3GPUserDataKeyCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyCopyright/title",
          "value": "AVMetadata3GPUserDataKeyCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyDescription/title",
          "value": "AVMetadata3GPUserDataKeyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyUserRating/title",
          "value": "AVMetadata3GPUserDataKeyUserRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyUserRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyUserRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyLocation/title",
          "value": "AVMetadata3GPUserDataKeyLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/title",
          "value": "AVMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyAlbumAndTrack/title",
          "value": "AVMetadata3GPUserDataKeyAlbumAndTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyAlbumAndTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyAlbumAndTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyRecordingYear/title",
          "value": "AVMetadata3GPUserDataKeyRecordingYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyRecordingYear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyRecordingYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyMediaClassification/title",
          "value": "AVMetadata3GPUserDataKeyMediaClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyMediaClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyMediaClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyMediaRating/title",
          "value": "AVMetadata3GPUserDataKeyMediaRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyMediaRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyMediaRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyAuthor/title",
          "value": "AVMetadata3GPUserDataKeyAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyPerformer/title",
          "value": "AVMetadata3GPUserDataKeyPerformer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyPerformer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyPerformer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyGenre/title",
          "value": "AVMetadata3GPUserDataKeyGenre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1metadata3GPUserDataKeyGenre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadata3GPUserDataKeyGenre"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeymediaclassification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/metadata3gpuserdatakeymediaclassification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
