{
  "abstract": [
    {
      "text": "A key that represents the phonogram rights statement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyPhonogramRights"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataQuickTimeUserDataKeyPhonogramRights",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "quickTimeUserDataKeyPhonogramRights"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataKey",
        "text": "AVMetadataKey"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataQuickTimeUserDataKeyPhonogramRights"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "quickTimeUserDataKeyPhonogramRights"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "quickTimeUserDataKeyPhonogramRights"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataKey",
              "text": "AVMetadataKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey": {
      "abstract": [
        {
          "text": "A structure that defines a metadata key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAccessibilityDescription": {
      "abstract": [
        {
          "text": "A key that represents the accessibility description for the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyAccessibilityDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAccessibilityDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyAccessibilityDescription"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyAccessibilityDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeyaccessibilitydescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAlbum": {
      "abstract": [
        {
          "text": "A key that represents the name of the album or collection in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAlbum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyAlbum"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyAlbum",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeyalbum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyArranger": {
      "abstract": [
        {
          "text": "A key that represents the name of the arranger of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyArranger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyArranger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyArranger"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyArranger",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeyarranger"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyArtist": {
      "abstract": [
        {
          "text": "A key that represents the name of the artist of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyArtist"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyArtist",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeyartist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAuthor": {
      "abstract": [
        {
          "text": "A key that represents the name of the author of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyAuthor"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyAuthor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeyauthor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyChapter": {
      "abstract": [
        {
          "text": "A key that represents the name of the chapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyChapter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyChapter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyChapter"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyChapter",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeychapter"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyComment": {
      "abstract": [
        {
          "text": "A key that represents a comment regarding the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyComment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyComment"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyComment",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeycomment"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyComposer": {
      "abstract": [
        {
          "text": "A key that represents the name of the composer of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyComposer"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyComposer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeycomposer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCopyright": {
      "abstract": [
        {
          "text": "A key that represents the copyright statement in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyCopyright"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyCopyright",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeycopyright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCreationDate": {
      "abstract": [
        {
          "text": "A key that represents the creation date of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyCreationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCreationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyCreationDate"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyCreationDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeycreationdate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCredits": {
      "abstract": [
        {
          "text": "A key that represents the credits of movie source content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyCredits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCredits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyCredits"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyCredits",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeycredits"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDescription": {
      "abstract": [
        {
          "text": "A key that represents the description of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyDescription"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeydescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDirector": {
      "abstract": [
        {
          "text": "A key that represents the name of the director of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyDirector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDirector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyDirector"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyDirector",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeydirector"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDisclaimer": {
      "abstract": [
        {
          "text": "A key that represents the disclaimer regarding the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyDisclaimer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDisclaimer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyDisclaimer"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyDisclaimer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeydisclaimer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyEncodedBy": {
      "abstract": [
        {
          "text": "A key that represents the name of the person or organization responsible for encoding the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyEncodedBy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyEncodedBy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyEncodedBy"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyEncodedBy",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeyencodedby"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyPhonogramRights": {
      "abstract": [
        {
          "text": "A key that represents the phonogram rights statement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataKeyPhonogramRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyPhonogramRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeUserDataKeyPhonogramRights"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataKeyPhonogramRights",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeyphonogramrights"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "QuickTime-User-Metadata-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAccessibilityDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAlbum",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyArranger",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyArtist",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAuthor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyChapter",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyComment",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyComposer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCopyright",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCreationDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCredits",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDirector",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDisclaimer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyEncodedBy"
      ],
      "title": "QuickTime User Metadata Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataQuickTimeUserDataKeyPhonogramRights"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyPhonogramRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "QuickTime-User-Metadata-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAccessibilityDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAlbum",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyArranger",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyArtist",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyAuthor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyChapter",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyComment",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyComposer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCopyright",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCreationDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyCredits",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDirector",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyDisclaimer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeUserDataKeyEncodedBy"
              ],
              "title": "QuickTime User Metadata Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataKey",
                    "text": "AVMetadataKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataQuickTimeUserDataKeyPhonogramRights"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyAuthor/title",
          "value": "AVMetadataQuickTimeUserDataKeyAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyPhonogramRights/title",
          "value": "AVMetadataQuickTimeUserDataKeyPhonogramRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyPhonogramRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyPhonogramRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyEncodedBy/title",
          "value": "AVMetadataQuickTimeUserDataKeyEncodedBy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyEncodedBy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyEncodedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyAlbum/title",
          "value": "AVMetadataQuickTimeUserDataKeyAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyAlbum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyComposer/title",
          "value": "AVMetadataQuickTimeUserDataKeyComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyCredits/title",
          "value": "AVMetadataQuickTimeUserDataKeyCredits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyCredits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyCredits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyDirector/title",
          "value": "AVMetadataQuickTimeUserDataKeyDirector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyDirector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyDirector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyCreationDate/title",
          "value": "AVMetadataQuickTimeUserDataKeyCreationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyCreationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyCreationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyChapter/title",
          "value": "AVMetadataQuickTimeUserDataKeyChapter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyChapter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyChapter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyAccessibilityDescription/title",
          "value": "AVMetadataQuickTimeUserDataKeyAccessibilityDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyAccessibilityDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyAccessibilityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/title",
          "value": "AVMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyDisclaimer/title",
          "value": "AVMetadataQuickTimeUserDataKeyDisclaimer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyDisclaimer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyDisclaimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyArtist/title",
          "value": "AVMetadataQuickTimeUserDataKeyArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyArranger/title",
          "value": "AVMetadataQuickTimeUserDataKeyArranger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyArranger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyArranger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyComment/title",
          "value": "AVMetadataQuickTimeUserDataKeyComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyDescription/title",
          "value": "AVMetadataQuickTimeUserDataKeyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyCopyright/title",
          "value": "AVMetadataQuickTimeUserDataKeyCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeUserDataKeyCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeUserDataKeyCopyright"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeyphonogramrights"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/quicktimeuserdatakeyphonogramrights"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
