{
  "abstract": [
    {
      "text": "A key that represents an image relating to the movie file content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArtwork"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataQuickTimeMetadataKeyArtwork",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "quickTimeMetadataKeyArtwork"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataKey",
        "text": "AVMetadataKey"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataQuickTimeMetadataKeyArtwork"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "quickTimeMetadataKeyArtwork"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "quickTimeMetadataKeyArtwork"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataKey",
              "text": "AVMetadataKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey": {
      "abstract": [
        {
          "text": "A structure that defines a metadata key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAccessibilityDescription": {
      "abstract": [
        {
          "text": "A key that represents the accessibility description for the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyAccessibilityDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAccessibilityDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyAccessibilityDescription"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyAccessibilityDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeyaccessibilitydescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAlbum": {
      "abstract": [
        {
          "text": "A key that represents the name of the album or collection in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAlbum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyAlbum"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyAlbum",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeyalbum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArranger": {
      "abstract": [
        {
          "text": "A key that represents the name of the arranger of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyArranger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArranger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyArranger"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyArranger",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeyarranger"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArtist": {
      "abstract": [
        {
          "text": "A key that represents the name of the artist of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyArtist"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyArtist",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeyartist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArtwork": {
      "abstract": [
        {
          "text": "A key that represents an image relating to the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyArtwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArtwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyArtwork"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyArtwork",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeyartwork"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAuthor": {
      "abstract": [
        {
          "text": "A key that represents the name of the author of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyAuthor"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyAuthor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeyauthor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCameraFrameReadoutTime": {
      "abstract": [
        {
          "text": "A key that represents the camera frame readout time in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyCameraFrameReadoutTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCameraFrameReadoutTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyCameraFrameReadoutTime"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyCameraFrameReadoutTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeycameraframereadouttime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCameraIdentifier": {
      "abstract": [
        {
          "text": "A key that represents the camera identifier in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyCameraIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCameraIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyCameraIdentifier"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyCameraIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeycameraidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCollectionUser": {
      "abstract": [
        {
          "text": "A key that represents a name that indicates a user-defined collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyCollectionUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCollectionUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyCollectionUser"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyCollectionUser",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeycollectionuser"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyComment": {
      "abstract": [
        {
          "text": "A key that represents a comment regarding the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyComment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyComment"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyComment",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeycomment"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyComposer": {
      "abstract": [
        {
          "text": "A key that represents the name of the composer of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyComposer"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyComposer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeycomposer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyContentIdentifier": {
      "abstract": [
        {
          "text": "A key that represents the content identifier in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyContentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyContentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyContentIdentifier"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyContentIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeycontentidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCopyright": {
      "abstract": [
        {
          "text": "A key that represents the copyright statement for the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyCopyright"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyCopyright",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeycopyright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCreationDate": {
      "abstract": [
        {
          "text": "A key that represents the creation date of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyCreationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCreationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyCreationDate"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyCreationDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeycreationdate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCredits": {
      "abstract": [
        {
          "text": "A key that represents the credits of the movie source content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyCredits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCredits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyCredits"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyCredits",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeycredits"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyDescription": {
      "abstract": [
        {
          "text": "A key that represents the description of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataKeyDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataQuickTimeMetadataKeyDescription"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataKeyDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeydescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "QuickTime-Metadata-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAccessibilityDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAlbum",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArranger",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArtist",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAuthor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCameraFrameReadoutTime",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCameraIdentifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCollectionUser",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyComment",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyComposer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyContentIdentifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCopyright",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCreationDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCredits",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyDescription"
      ],
      "title": "QuickTime Metadata Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataQuickTimeMetadataKeyArtwork"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyArtwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "QuickTime-Metadata-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAccessibilityDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAlbum",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArranger",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyArtist",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyAuthor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCameraFrameReadoutTime",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCameraIdentifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCollectionUser",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyComment",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyComposer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyContentIdentifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCopyright",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCreationDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyCredits",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey/quickTimeMetadataKeyDescription"
              ],
              "title": "QuickTime Metadata Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataKey",
                    "text": "AVMetadataKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataQuickTimeMetadataKeyArtwork"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCollectionUser/title",
          "value": "AVMetadataQuickTimeMetadataKeyCollectionUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCollectionUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyCollectionUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCopyright/title",
          "value": "AVMetadataQuickTimeMetadataKeyCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyAlbum/title",
          "value": "AVMetadataQuickTimeMetadataKeyAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyAlbum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyComment/title",
          "value": "AVMetadataQuickTimeMetadataKeyComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyArtist/title",
          "value": "AVMetadataQuickTimeMetadataKeyArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyComposer/title",
          "value": "AVMetadataQuickTimeMetadataKeyComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCameraFrameReadoutTime/title",
          "value": "AVMetadataQuickTimeMetadataKeyCameraFrameReadoutTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCameraFrameReadoutTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyCameraFrameReadoutTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCreationDate/title",
          "value": "AVMetadataQuickTimeMetadataKeyCreationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCreationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyCreationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyAccessibilityDescription/title",
          "value": "AVMetadataQuickTimeMetadataKeyAccessibilityDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyAccessibilityDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyAccessibilityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyDescription/title",
          "value": "AVMetadataQuickTimeMetadataKeyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyArranger/title",
          "value": "AVMetadataQuickTimeMetadataKeyArranger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyArranger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyArranger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCredits/title",
          "value": "AVMetadataQuickTimeMetadataKeyCredits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCredits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyCredits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyAuthor/title",
          "value": "AVMetadataQuickTimeMetadataKeyAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/title",
          "value": "AVMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyArtwork/title",
          "value": "AVMetadataQuickTimeMetadataKeyArtwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyArtwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyArtwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyContentIdentifier/title",
          "value": "AVMetadataQuickTimeMetadataKeyContentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyContentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyContentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCameraIdentifier/title",
          "value": "AVMetadataQuickTimeMetadataKeyCameraIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey~1quickTimeMetadataKeyCameraIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataQuickTimeMetadataKeyCameraIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeyartwork"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadatakey/quicktimemetadatakeyartwork"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
