{
  "abstract": [
    {
      "text": "Masks for the appearance style bit field.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/imagekit",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/imagekit",
        "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
        "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/1564248-cell-appearance-style-masks"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Cell Appearance Style Masks"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes": {
      "abstract": [
        {
          "text": "Attributes for the group style. Used by the",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Group Style Attributes",
      "type": "topic",
      "url": "/documentation/quartz/1564247-group-style-attributes"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleNone": {
      "abstract": [
        {
          "text": "No style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCellsStyleNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCellsStyleNone"
        }
      ],
      "role": "symbol",
      "title": "IKCellsStyleNone",
      "type": "topic",
      "url": "/documentation/quartz/ikcellsstylenone"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleOutlined": {
      "abstract": [
        {
          "text": "Cells are outlined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCellsStyleOutlined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleOutlined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCellsStyleOutlined"
        }
      ],
      "role": "symbol",
      "title": "IKCellsStyleOutlined",
      "type": "topic",
      "url": "/documentation/quartz/ikcellsstyleoutlined"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleShadowed": {
      "abstract": [
        {
          "text": "Cells use shadows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCellsStyleShadowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleShadowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCellsStyleShadowed"
        }
      ],
      "role": "symbol",
      "title": "IKCellsStyleShadowed",
      "type": "topic",
      "url": "/documentation/quartz/ikcellsstyleshadowed"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleSubtitled": {
      "abstract": [
        {
          "text": "Cells display a subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCellsStyleSubtitled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleSubtitled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCellsStyleSubtitled"
        }
      ],
      "role": "symbol",
      "title": "IKCellsStyleSubtitled",
      "type": "topic",
      "url": "/documentation/quartz/ikcellsstylesubtitled"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleTitled": {
      "abstract": [
        {
          "text": "Cells display a title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCellsStyleTitled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleTitled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCellsStyleTitled"
        }
      ],
      "role": "symbol",
      "title": "IKCellsStyleTitled",
      "type": "topic",
      "url": "/documentation/quartz/ikcellsstyletitled"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation": {
      "abstract": [
        {
          "text": "These constants specify the locations for dropping items onto the browser view. Used by the method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserDropOperation",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdropoperation"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView": {
      "abstract": [
        {
          "text": "A view for displaying and browsing a large collection of images and movies.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserView",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)": {
      "abstract": [
        {
          "text": "Allows the class to retarget the drop action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDrop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IKImageBrowserDropOperation",
          "text": "IKImageBrowserDropOperation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDropIndex:dropOperation:"
        }
      ],
      "role": "symbol",
      "title": "setDrop(_:dropOperation:)",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserview/setdrop(_:dropoperation:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/group-keys": {
      "abstract": [
        {
          "text": "Keys for group attributes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/group-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Group Keys",
      "type": "topic",
      "url": "/documentation/quartz/group-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit",
      "type": "topic",
      "url": "/documentation/quartz/imagekit"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Enumerations",
      "type": "topic",
      "url": "/documentation/quartz/quartz-enumerations"
    },
    "doc://com.apple.quartz/documentation/Quartz/view-options-keys": {
      "abstract": [
        {
          "text": "Keys for image browser view options. You set and retrieve values for these keys by sending the view ",
          "type": "text"
        },
        {
          "code": "setValue:forKey",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "valueForKey:",
          "type": "codeVoice"
        },
        {
          "text": " messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/view-options-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Options Keys",
      "type": "topic",
      "url": "/documentation/quartz/view-options-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes",
        "doc://com.apple.quartz/documentation/Quartz/view-options-keys",
        "doc://com.apple.quartz/documentation/Quartz/group-keys",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleNone",
        "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleShadowed",
        "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleOutlined",
        "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleTitled",
        "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleSubtitled"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleNone",
                "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleShadowed",
                "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleOutlined",
                "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleTitled",
                "doc://com.apple.quartz/documentation/Quartz/IKCellsStyleSubtitled"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes",
                "doc://com.apple.quartz/documentation/Quartz/view-options-keys",
                "doc://com.apple.quartz/documentation/Quartz/group-keys",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleSubtitled/title",
          "value": "IKCellsStyleSubtitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleSubtitled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCellsStyleSubtitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleNone/title",
          "value": "IKCellsStyleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCellsStyleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleTitled/title",
          "value": "IKCellsStyleTitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleTitled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCellsStyleTitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/title",
          "value": "IKImageBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleShadowed/title",
          "value": "IKCellsStyleShadowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleShadowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCellsStyleShadowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView~1setDrop(_:dropOperation:)/title",
          "value": "setDropIndex:dropOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView~1setDrop(_:dropOperation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDropIndex:dropOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleOutlined/title",
          "value": "IKCellsStyleOutlined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCellsStyleOutlined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCellsStyleOutlined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/title",
          "value": "IKImageBrowserDropOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropOperation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/1564248-cell-appearance-style-masks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/1564248-cell-appearance-style-masks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
