{
  "abstract": [
    {
      "text": "Attributes of a composition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
        "doc://com.apple.quartz/documentation/Quartz/QCComposition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/attribute-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Attribute Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCComposition": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCComposition",
          "type": "codeVoice"
        },
        {
          "text": " class represents a Quartz Composer composition that either:",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "role": "symbol",
      "title": "QCComposition",
      "type": "topic",
      "url": "/documentation/quartz/qccomposition"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeBuiltInKey": {
      "abstract": [
        {
          "text": "The key for the composition origin.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeBuiltInKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeBuiltInKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeBuiltInKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeBuiltInKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributebuiltinkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCategoryKey": {
      "abstract": [
        {
          "text": "A key representing a composition category.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeCategoryKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCategoryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeCategoryKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeCategoryKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributecategorykey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCopyrightKey": {
      "abstract": [
        {
          "text": "The key for composition copyright information. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeCopyrightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCopyrightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeCopyrightKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeCopyrightKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributecopyrightkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeDescriptionKey": {
      "abstract": [
        {
          "text": "The key for the composition description. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeDescriptionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeDescriptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeDescriptionKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeDescriptionKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributedescriptionkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeHasConsumersKey": {
      "abstract": [
        {
          "text": "The key for a composition that has consumer patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeHasConsumersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeHasConsumersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeHasConsumersKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeHasConsumersKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributehasconsumerskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeNameKey": {
      "abstract": [
        {
          "text": "The key for the composition name. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeNameKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeNameKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributenamekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/composition-categories": {
      "abstract": [
        {
          "text": "Categories for compositions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/composition-categories",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composition Categories",
      "type": "topic",
      "url": "/documentation/quartz/composition-categories"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys": {
      "abstract": [
        {
          "text": "Input ports of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocol Input Keys",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocol-input-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys": {
      "abstract": [
        {
          "text": "Output ports of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocol Output Keys",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocol-output-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocols": {
      "abstract": [
        {
          "text": "Protocols for a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocols",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocols"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/composition-categories",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocols"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeNameKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeDescriptionKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCopyrightKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeBuiltInKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeHasConsumersKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCategoryKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeNameKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeDescriptionKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCopyrightKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeBuiltInKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeHasConsumersKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCategoryKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/composition-categories",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocols"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeCategoryKey/title",
          "value": "QCCompositionAttributeCategoryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeCategoryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeBuiltInKey/title",
          "value": "QCCompositionAttributeBuiltInKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeBuiltInKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeBuiltInKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeCopyrightKey/title",
          "value": "QCCompositionAttributeCopyrightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeCopyrightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeCopyrightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeHasConsumersKey/title",
          "value": "QCCompositionAttributeHasConsumersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeHasConsumersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeHasConsumersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeNameKey/title",
          "value": "QCCompositionAttributeNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeDescriptionKey/title",
          "value": "QCCompositionAttributeDescriptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeDescriptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/title",
          "value": "QCComposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/attribute-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/attribute-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
