{
  "abstract": [
    {
      "text": "Categories for compositions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
        "doc://com.apple.quartz/documentation/Quartz/QCComposition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/composition-categories"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Composition Categories"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCComposition": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCComposition",
          "type": "codeVoice"
        },
        {
          "text": " class represents a Quartz Composer composition that either:",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "role": "symbol",
      "title": "QCComposition",
      "type": "topic",
      "url": "/documentation/quartz/qccomposition"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryDistortion": {
      "abstract": [
        {
          "text": "A composition that produces a distortion effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryDistortion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryDistortion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryDistortion"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionCategoryDistortion",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioncategorydistortion"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryStylize": {
      "abstract": [
        {
          "text": "A composition that produces a stylize effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryStylize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryStylize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryStylize"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionCategoryStylize",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioncategorystylize"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryUtility": {
      "abstract": [
        {
          "text": "A utility composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryUtility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryUtility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryUtility"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionCategoryUtility",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioncategoryutility"
    },
    "doc://com.apple.quartz/documentation/Quartz/attribute-keys": {
      "abstract": [
        {
          "text": "Attributes of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Attribute Keys",
      "type": "topic",
      "url": "/documentation/quartz/attribute-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys": {
      "abstract": [
        {
          "text": "Input ports of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocol Input Keys",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocol-input-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys": {
      "abstract": [
        {
          "text": "Output ports of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocol Output Keys",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocol-output-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocols": {
      "abstract": [
        {
          "text": "Protocols for a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocols",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocols"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/attribute-keys",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocols"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryDistortion",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryStylize",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryUtility"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryDistortion",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryStylize",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryUtility"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/attribute-keys",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocols"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryUtility/title",
          "value": "QCCompositionCategoryUtility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryUtility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionCategoryUtility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/title",
          "value": "QCComposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryStylize/title",
          "value": "QCCompositionCategoryStylize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryStylize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionCategoryStylize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryDistortion/title",
          "value": "QCCompositionCategoryDistortion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryDistortion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionCategoryDistortion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/composition-categories"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/composition-categories"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
