{
  "abstract": [
    {
      "text": "These symbols are deprecated and should no longer be used.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/pdfkit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/deprecated-annotations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "title": "Deprecated Annotations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/PDFKit/PDFAction": {
      "abstract": [
        {
          "text": "An action that is performed when, for example, a PDF annotation is activated or an outline item is clicked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAction"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAction",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAction"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotation": {
      "abstract": [
        {
          "text": "An annotation in a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotation",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotation",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotation"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationButtonWidget": {
      "abstract": [
        {
          "text": "A `PDFAnnotationButtonWidget` object provides user interactivity on a page of a PDF document. There are three types of buttons available: push button, radio button, and checkbox.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationButtonWidget"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationButtonWidget",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationButtonWidget",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationButtonWidget"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationChoiceWidget": {
      "abstract": [
        {
          "text": "A `PDFAnnotationChoiceWidget` object provides user interactivity on a page of a PDF document, in the form of pop-up menus and lists.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationChoiceWidget"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationChoiceWidget",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationChoiceWidget",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationChoiceWidget"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationCircle": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationCircle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationCircle",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationCircle",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationCircle"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationFreeText": {
      "abstract": [
        {
          "text": "A `PDFAnnotationFreeText` object displays text on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationFreeText"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationFreeText",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationFreeText",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationFreeText"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationInk": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationInk"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationInk",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationInk",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationInk"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationLine": {
      "abstract": [
        {
          "text": "A `PDFAnnotationLine` object displays a single line on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationLine"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationLine",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationLine",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationLine"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationLink": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationLink"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationLink",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationLink",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationLink"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationMarkup": {
      "abstract": [
        {
          "text": "A `PDFAnnotationMarkup` object appears as highlighting, underlining, or a strikethrough style applied to the text of a document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationMarkup"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationMarkup",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationMarkup",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationMarkup"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationPopup": {
      "abstract": [
        {
          "text": "A `PDFAnnotationPopup` object provides user interactivity on a PDF page in the form of a pop-up menu.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationPopup"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationPopup",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationPopup",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationPopup"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationSquare": {
      "abstract": [
        {
          "text": "A rectangle annotation on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationSquare"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationSquare",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationSquare",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationSquare"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationStamp": {
      "abstract": [
        {
          "text": "A `PDFAnnotationStamp` object allows you to display a word or phrase, such as “Confidential,” in a PDF page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationStamp"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationStamp",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationStamp"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationText": {
      "abstract": [
        {
          "text": "A `PDFAnnotationText` object displays as an icon (such as a “sticky note”) attached to a specified point in the PDF document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationText"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationText",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationText",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationText"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationTextWidget": {
      "abstract": [
        {
          "text": "A `PDFAnnotationTextWidget` object allows you to manage the appearance and content of text fields.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextWidget"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationTextWidget",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotationTextWidget",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotationTextWidget"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAppearanceCharacteristics": {
      "abstract": [
        {
          "text": "An object that represents appearance characteristics of a widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristics"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAppearanceCharacteristics",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAppearanceCharacteristics",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAppearanceCharacteristics"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFBorder": {
      "abstract": [
        {
          "text": "An optional border for an annotation that lies completely within the annotation rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFBorder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFBorder",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFBorder",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFBorder"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFDestination": {
      "abstract": [
        {
          "text": "A `PDFDestination` object describes a point on a PDF page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDestination"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFDestination",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDestination",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFDestination"
    },
    "doc://com.apple.documentation/documentation/PDFKit/adding-custom-graphics-to-a-pdf": {
      "abstract": [
        {
          "text": "Create and add custom annotation and page graphics to your PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/adding-custom-graphics-to-a-pdf",
      "kind": "article",
      "role": "article",
      "title": "Adding Custom Graphics to a PDF",
      "type": "topic",
      "url": "/documentation/PDFKit/adding-custom-graphics-to-a-pdf"
    },
    "doc://com.apple.documentation/documentation/PDFKit/adding-widgets-to-a-pdf-document": {
      "abstract": [
        {
          "text": "Add text, button, and choice widgets to a PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/adding-widgets-to-a-pdf-document",
      "kind": "article",
      "role": "article",
      "title": "Adding Widgets to a PDF Document",
      "type": "topic",
      "url": "/documentation/PDFKit/adding-widgets-to-a-pdf-document"
    },
    "doc://com.apple.documentation/documentation/PDFKit/custom-graphics": {
      "abstract": [
        {
          "text": "Demonstrates adding a watermark to a PDF page.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/custom-graphics",
      "kind": "article",
      "role": "sampleCode",
      "title": "Custom Graphics",
      "type": "topic",
      "url": "/documentation/PDFKit/custom-graphics"
    },
    "doc://com.apple.documentation/documentation/PDFKit/pdf-widgets": {
      "abstract": [
        {
          "text": "Demonstrates adding widgets—interactive form elements—to a PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/pdf-widgets",
      "kind": "article",
      "role": "sampleCode",
      "title": "PDF Widgets",
      "type": "topic",
      "url": "/documentation/PDFKit/pdf-widgets"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/pdfkit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/pdfkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/quartz/pdfkit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Annotations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/PDFKit/adding-widgets-to-a-pdf-document",
        "doc://com.apple.documentation/documentation/PDFKit/adding-custom-graphics-to-a-pdf",
        "doc://com.apple.documentation/documentation/PDFKit/custom-graphics",
        "doc://com.apple.documentation/documentation/PDFKit/pdf-widgets",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotation",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAction",
        "doc://com.apple.documentation/documentation/PDFKit/PDFDestination",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAppearanceCharacteristics",
        "doc://com.apple.documentation/documentation/PDFKit/PDFBorder"
      ],
      "title": "Annotations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Deprecated-Annotation-Types",
      "identifiers": [
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationButtonWidget",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationChoiceWidget",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationCircle",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationFreeText",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationInk",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationLine",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationLink",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationMarkup",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationPopup",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationSquare",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationStamp",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationText",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationTextWidget"
      ],
      "title": "Deprecated Annotation Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-Annotation-Types",
              "identifiers": [
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationButtonWidget",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationChoiceWidget",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationCircle",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationFreeText",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationInk",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationLine",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationLink",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationMarkup",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationPopup",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationSquare",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationStamp",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationText",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotationTextWidget"
              ],
              "title": "Deprecated Annotation Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Annotations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/PDFKit/adding-widgets-to-a-pdf-document",
                "doc://com.apple.documentation/documentation/PDFKit/adding-custom-graphics-to-a-pdf",
                "doc://com.apple.documentation/documentation/PDFKit/custom-graphics",
                "doc://com.apple.documentation/documentation/PDFKit/pdf-widgets",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotation",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAction",
                "doc://com.apple.documentation/documentation/PDFKit/PDFDestination",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAppearanceCharacteristics",
                "doc://com.apple.documentation/documentation/PDFKit/PDFBorder"
              ],
              "title": "Annotations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationText/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationText"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAppearanceCharacteristics/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristics"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationLink/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationLink"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationMarkup/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationMarkup"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationLine/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationTextWidget/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextWidget"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationSquare/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationSquare"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFDestination/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFDestination"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationFreeText/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationFreeText"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationStamp/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationStamp"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationCircle/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationCircle"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFBorder/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFBorder"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationInk/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationInk"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationChoiceWidget"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationPopup/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationPopup"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAction"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotationButtonWidget/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PDFAnnotation",
              "text": "PDFAnnotation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/deprecated-annotations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/deprecated-annotations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
