{
  "abstract": [
    {
      "text": "Arguments to the method ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugIn/execute(_:atTime:withArguments:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugIn"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/execution-arguments"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Execution Arguments"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugIn": {
      "abstract": [
        {
          "text": "A base class to subclass for writing custom patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugIn"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugIn"
        }
      ],
      "role": "symbol",
      "title": "QCPlugIn",
      "type": "topic",
      "url": "/documentation/quartz/qcplugin"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugIn/execute(_:atTime:withArguments:)": {
      "abstract": [
        {
          "text": "Performs the processing or rendering tasks appropriate for the custom patch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QCPlugInContext",
          "text": "QCPlugInContext"
        },
        {
          "kind": "text",
          "text": ")!, "
        },
        {
          "kind": "externalParam",
          "text": "atTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withArguments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugIn/execute(_:atTime:withArguments:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "execute:atTime:withArguments:"
        }
      ],
      "role": "symbol",
      "title": "execute(_:atTime:withArguments:)",
      "type": "topic",
      "url": "/documentation/quartz/qcplugin/execute(_:attime:witharguments:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionArgumentEventKey": {
      "abstract": [
        {
          "text": "The current event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionArgumentEventKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionArgumentEventKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionArgumentEventKey"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInExecutionArgumentEventKey",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginexecutionargumenteventkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionArgumentMouseLocationKey": {
      "abstract": [
        {
          "text": "The current location of the mouse (as an ",
          "type": "text"
        },
        {
          "code": "NSPoint",
          "type": "codeVoice"
        },
        {
          "text": " object stored in an ",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " object) in normalized coordinates relative to the OpenGL context viewport ([0,1]x[0,1] with the origin (",
          "type": "text"
        },
        {
          "code": "0,0",
          "type": "codeVoice"
        },
        {
          "text": ") at the lower-left corner).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionArgumentMouseLocationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionArgumentMouseLocationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionArgumentMouseLocationKey"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInExecutionArgumentMouseLocationKey",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginexecutionargumentmouselocationkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode": {
      "abstract": [
        {
          "text": "Execution modes for custom patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionMode"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInExecutionMode",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginexecutionmode"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode": {
      "abstract": [
        {
          "text": "Time modes for custom patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInTimeMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInTimeMode"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInTimeMode",
      "type": "topic",
      "url": "/documentation/quartz/qcplugintimemode"
    },
    "doc://com.apple.quartz/documentation/Quartz/input-and-output-port-attributes": {
      "abstract": [
        {
          "text": "Attributes for input and output ports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/input-and-output-port-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input and Output Port Attributes",
      "type": "topic",
      "url": "/documentation/quartz/input-and-output-port-attributes"
    },
    "doc://com.apple.quartz/documentation/Quartz/patch-attributes": {
      "abstract": [
        {
          "text": "Attributes for custom patches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/patch-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Patch Attributes",
      "type": "topic",
      "url": "/documentation/quartz/patch-attributes"
    },
    "doc://com.apple.quartz/documentation/Quartz/pixel-formats": {
      "abstract": [
        {
          "text": "Supported image pixel formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/pixel-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Formats",
      "type": "topic",
      "url": "/documentation/quartz/pixel-formats"
    },
    "doc://com.apple.quartz/documentation/Quartz/port-input-and-output-types": {
      "abstract": [
        {
          "text": "Data types for input and output ports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/port-input-and-output-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Port Input and Output Types",
      "type": "topic",
      "url": "/documentation/quartz/port-input-and-output-types"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/patch-attributes",
        "doc://com.apple.quartz/documentation/Quartz/input-and-output-port-attributes",
        "doc://com.apple.quartz/documentation/Quartz/port-input-and-output-types",
        "doc://com.apple.quartz/documentation/Quartz/pixel-formats",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionArgumentEventKey",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionArgumentMouseLocationKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionArgumentEventKey",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionArgumentMouseLocationKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/patch-attributes",
                "doc://com.apple.quartz/documentation/Quartz/input-and-output-port-attributes",
                "doc://com.apple.quartz/documentation/Quartz/port-input-and-output-types",
                "doc://com.apple.quartz/documentation/Quartz/pixel-formats",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/title",
          "value": "QCPlugInTimeMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTimeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTimeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn~1execute(_:atTime:withArguments:)/title",
          "value": "execute:atTime:withArguments:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn~1execute(_:atTime:withArguments:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "execute:atTime:withArguments:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionArgumentMouseLocationKey/title",
          "value": "QCPlugInExecutionArgumentMouseLocationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionArgumentMouseLocationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInExecutionArgumentMouseLocationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionArgumentEventKey/title",
          "value": "QCPlugInExecutionArgumentEventKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionArgumentEventKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInExecutionArgumentEventKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn/title",
          "value": "QCPlugIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionMode/title",
          "value": "QCPlugInExecutionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInExecutionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInExecutionMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/execution-arguments"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/execution-arguments"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
