{
  "abstract": [
    {
      "text": "Keys for filter browser options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/imagekit",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserPanel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/filter-browser-option-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Filter Browser Option Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserDefaultInputImage": {
      "abstract": [
        {
          "text": "The key for the default input image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserDefaultInputImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserDefaultInputImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserDefaultInputImage"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserDefaultInputImage",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserdefaultinputimage"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeCategories": {
      "abstract": [
        {
          "text": "The key for excluding filter categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserExcludeCategories"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeCategories",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserExcludeCategories"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserExcludeCategories",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserexcludecategories"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeFilters": {
      "abstract": [
        {
          "text": "The key for excluding filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserExcludeFilters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeFilters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserExcludeFilters"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserExcludeFilters",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserexcludefilters"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserPanel": {
      "abstract": [
        {
          "text": "Presents a user interface for browsing filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserPanel"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserPanel"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserPanel",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserpanel"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowCategories": {
      "abstract": [
        {
          "text": "The key for showing categories. The associated value is a  ",
          "type": "text"
        },
        {
          "code": "BOOL",
          "type": "codeVoice"
        },
        {
          "text": " value that determines if the filter browser should show the category list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserShowCategories"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowCategories",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserShowCategories"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserShowCategories",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowsershowcategories"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowPreview": {
      "abstract": [
        {
          "text": "The associated value is a  ",
          "type": "text"
        },
        {
          "code": "BOOL",
          "type": "codeVoice"
        },
        {
          "text": " value that determines if the filter browser should provide a preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserShowPreview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserShowPreview"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserShowPreview",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowsershowpreview"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit",
      "type": "topic",
      "url": "/documentation/quartz/imagekit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserDefaultInputImage",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeCategories",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeFilters",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowCategories",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowPreview"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserDefaultInputImage",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeCategories",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeFilters",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowCategories",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowPreview"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserDefaultInputImage/title",
          "value": "IKFilterBrowserDefaultInputImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserDefaultInputImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserDefaultInputImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserExcludeFilters/title",
          "value": "IKFilterBrowserExcludeFilters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserExcludeFilters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserExcludeFilters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserExcludeCategories/title",
          "value": "IKFilterBrowserExcludeCategories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserExcludeCategories/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserExcludeCategories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserShowCategories/title",
          "value": "IKFilterBrowserShowCategories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserShowCategories/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserShowCategories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserPanel/title",
          "value": "IKFilterBrowserPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserShowPreview/title",
          "value": "IKFilterBrowserShowPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserShowPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserShowPreview"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/filter-browser-option-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/filter-browser-option-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
