{"metadata":{"role":"symbol","modules":[{"name":"Quartz"}],"title":"globalUpdateOK","symbolKind":"var","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"globalUpdateOK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6Darwin0A7BooleanV","text":"DarwinBoolean"}],"platforms":[{"name":"macOS","unavailable":false,"beta":false,"introducedAt":"10.4","deprecated":false}],"roleHeading":"Global Variable","externalID":"c:@globalUpdateOK","navigatorTitle":[{"kind":"identifier","text":"globalUpdateOK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.quartz/documentation/Quartz/globalUpdateOK"},"kind":"symbol","sections":[],"seeAlsoSections":[{"anchor":"Constants","generated":true,"identifiers":["doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain","doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain","doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain"],"title":"Constants"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/quartz/globalupdateok"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/quartz/globalupdateok"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"globalUpdateOK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6Darwin0A7BooleanV","text":"DarwinBoolean"}],"platforms":["macOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"kQuartzFilterApplicationDomain"}],"url":"/documentation/quartz/kquartzfilterapplicationdomain","title":"kQuartzFilterApplicationDomain","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kQuartzFilterApplicationDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic"},"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain":{"identifier":"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kQuartzFilterPrintingDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"/documentation/quartz/kquartzfilterprintingdomain","abstract":[],"title":"kQuartzFilterPrintingDomain","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kQuartzFilterPrintingDomain"}]},"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain","title":"kQuartzFilterPDFWorkflowDomain","url":"/documentation/quartz/kquartzfilterpdfworkflowdomain","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kQuartzFilterPDFWorkflowDomain"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kQuartzFilterPDFWorkflowDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.apple.quartz/documentation/Quartz":{"identifier":"doc://com.apple.quartz/documentation/Quartz","kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Allow users to browse, edit, and save images, using slideshows and Core Image filters."}],"title":"Quartz","url":"/documentation/quartz"},"doc://com.apple.quartz/documentation/Quartz/globalUpdateOK":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.quartz/documentation/Quartz/globalUpdateOK","title":"globalUpdateOK","url":"/documentation/quartz/globalupdateok","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"globalUpdateOK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"globalUpdateOK","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DarwinBoolean","preciseIdentifier":"s:6Darwin0A7BooleanV"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"10.4","beta":false,"name":"macOS","deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Global Variable","op":"replace","path":"/metadata/roleHeading"},{"value":"globalUpdateOK","op":"replace","path":"/metadata/title"},{"value":"var","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"globalUpdateOK"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Constants","generated":true,"identifiers":["doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain","doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain","doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain"],"title":"Constants"}],"op":"replace","path":"/seeAlsoSections"},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Boolean","preciseIdentifier":"c:@T@Boolean"},{"kind":"text","text":" "},{"kind":"identifier","text":"globalUpdateOK"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"kQuartzFilterApplicationDomain","op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterApplicationDomain/title"},{"value":[{"kind":"identifier","text":"kQuartzFilterApplicationDomain"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterApplicationDomain/fragments"},{"value":"kQuartzFilterPrintingDomain","op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPrintingDomain/title"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPrintingDomain/fragments","op":"replace","value":[{"text":"kQuartzFilterPrintingDomain","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPDFWorkflowDomain/title","op":"replace","value":"kQuartzFilterPDFWorkflowDomain"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPDFWorkflowDomain/fragments","op":"replace","value":[{"kind":"identifier","text":"kQuartzFilterPDFWorkflowDomain"}]},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1globalUpdateOK/title","op":"replace","value":"globalUpdateOK"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1globalUpdateOK/fragments","op":"replace","value":[{"text":"globalUpdateOK","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}