{
  "abstract": [
    {
      "text": "A key for the range of a group.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserGroupRangeKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@IKImageBrowserGroupRangeKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IKImageBrowserGroupRangeKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IKImageBrowserGroupRangeKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "IKImageBrowserGroupRangeKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IKImageBrowserGroupRangeKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The associated value is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsvalue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. This is required if the view uses grouping",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsvalue": {
      "abstract": [
        {
          "text": "A simple container for a single C or Objective-C data item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSValue"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSValue",
      "type": "topic",
      "url": "/documentation/foundation/nsvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserDefaultInputImage": {
      "abstract": [
        {
          "text": "The key for the default input image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserDefaultInputImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserDefaultInputImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserDefaultInputImage"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserDefaultInputImage",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserdefaultinputimage"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeCategories": {
      "abstract": [
        {
          "text": "The key for excluding filter categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserExcludeCategories"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeCategories",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserExcludeCategories"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserExcludeCategories",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserexcludecategories"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeFilters": {
      "abstract": [
        {
          "text": "The key for excluding filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserExcludeFilters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeFilters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserExcludeFilters"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserExcludeFilters",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserexcludefilters"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserFilterDoubleClickNotification": {
      "abstract": [
        {
          "text": "Posted when the user double-clicks a filter in the filter browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserFilterDoubleClickNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserFilterDoubleClickNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "IKFilterBrowserFilterDoubleClickNotification",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserfilterdoubleclicknotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserFilterSelectedNotification": {
      "abstract": [
        {
          "text": "Posted when the user clicks a filter name in the filter browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserFilterSelectedNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserFilterSelectedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "IKFilterBrowserFilterSelectedNotification",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserfilterselectednotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowCategories": {
      "abstract": [
        {
          "text": "The key for showing categories. The associated value is a  ",
          "type": "text"
        },
        {
          "code": "BOOL",
          "type": "codeVoice"
        },
        {
          "text": " value that determines if the filter browser should show the category list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserShowCategories"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowCategories",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserShowCategories"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserShowCategories",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowsershowcategories"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowPreview": {
      "abstract": [
        {
          "text": "The associated value is a  ",
          "type": "text"
        },
        {
          "code": "BOOL",
          "type": "codeVoice"
        },
        {
          "text": " value that determines if the filter browser should provide a preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserShowPreview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserShowPreview"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserShowPreview",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowsershowpreview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserWillPreviewFilterNotification": {
      "abstract": [
        {
          "text": "Posted before showing a filter preview, allowing an application to set the parameters of a filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserWillPreviewFilterNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserWillPreviewFilterNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "IKFilterBrowserWillPreviewFilterNotification",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserwillpreviewfilternotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserBackgroundColorKey": {
      "abstract": [
        {
          "text": "A key for the background color of the image browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserBackgroundColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserBackgroundColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserBackgroundColorKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserBackgroundColorKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserbackgroundcolorkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellBackgroundLayer": {
      "abstract": [
        {
          "text": "Layer displayed in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellBackgroundLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellBackgroundLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellBackgroundLayer"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellBackgroundLayer",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellbackgroundlayer"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellForegroundLayer": {
      "abstract": [
        {
          "text": "Layer displayed in the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellForegroundLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellForegroundLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellForegroundLayer"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellForegroundLayer",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellforegroundlayer"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellPlaceHolderLayer": {
      "abstract": [
        {
          "text": "Layer displayed as a placeholder when an image is not yet available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellPlaceHolderLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellPlaceHolderLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellPlaceHolderLayer"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellPlaceHolderLayer",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellplaceholderlayer"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellSelectionLayer": {
      "abstract": [
        {
          "text": "Layer displayed as the selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellSelectionLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellSelectionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellSelectionLayer"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellSelectionLayer",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellselectionlayer"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsHighlightedTitleAttributesKey": {
      "abstract": [
        {
          "text": "A key for the highlighted title attribute for an item in the image browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsHighlightedTitleAttributesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsHighlightedTitleAttributesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsHighlightedTitleAttributesKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellsHighlightedTitleAttributesKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellshighlightedtitleattributeskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsOutlineColorKey": {
      "abstract": [
        {
          "text": "A key for the outline color for an item in the image browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsOutlineColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsOutlineColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsOutlineColorKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellsOutlineColorKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellsoutlinecolorkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsSubtitleAttributesKey": {
      "abstract": [
        {
          "text": "A key for  a subtitle attribute for an item in the image browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsSubtitleAttributesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsSubtitleAttributesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsSubtitleAttributesKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellsSubtitleAttributesKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellssubtitleattributeskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropBefore": {
      "abstract": [
        {
          "text": "Drop the item before the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropBefore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IKImageBrowserDropOperation",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropBefore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropBefore"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserDropBefore",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdropbefore"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOn": {
      "abstract": [
        {
          "text": "Drop the item on the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IKImageBrowserDropOperation",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOn"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserDropOn",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdropon"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserGroupRangeKey": {
      "abstract": [
        {
          "text": "A key for the range of a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserGroupRangeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserGroupRangeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserGroupRangeKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserGroupRangeKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsergrouprangekey"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOn",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropBefore",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserDefaultInputImage",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeCategories",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeFilters",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowCategories",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowPreview",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserBackgroundColorKey",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellBackgroundLayer",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellForegroundLayer",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellPlaceHolderLayer",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellSelectionLayer",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsHighlightedTitleAttributesKey",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsOutlineColorKey",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsSubtitleAttributesKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IKImageBrowserGroupRangeKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserGroupRangeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserFilterDoubleClickNotification",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserFilterSelectedNotification",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserWillPreviewFilterNotification",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOn",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropBefore",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserDefaultInputImage",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeCategories",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserExcludeFilters",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowCategories",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserShowPreview",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserBackgroundColorKey",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellBackgroundLayer",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellForegroundLayer",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellPlaceHolderLayer",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellSelectionLayer"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IKImageBrowserGroupRangeKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsHighlightedTitleAttributesKey/title",
          "value": "IKImageBrowserCellsHighlightedTitleAttributesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsHighlightedTitleAttributesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellsHighlightedTitleAttributesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserExcludeCategories/title",
          "value": "IKFilterBrowserExcludeCategories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserExcludeCategories/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserExcludeCategories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserShowCategories/title",
          "value": "IKFilterBrowserShowCategories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserShowCategories/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserShowCategories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsSubtitleAttributesKey/title",
          "value": "IKImageBrowserCellsSubtitleAttributesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsSubtitleAttributesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellsSubtitleAttributesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserBackgroundColorKey/title",
          "value": "IKImageBrowserBackgroundColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserBackgroundColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserBackgroundColorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOn/title",
          "value": "IKImageBrowserDropOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellSelectionLayer/title",
          "value": "IKImageBrowserCellSelectionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellSelectionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellSelectionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsOutlineColorKey/title",
          "value": "IKImageBrowserCellsOutlineColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsOutlineColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellsOutlineColorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropBefore/title",
          "value": "IKImageBrowserDropBefore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropBefore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropBefore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserExcludeFilters/title",
          "value": "IKFilterBrowserExcludeFilters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserExcludeFilters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserExcludeFilters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserGroupRangeKey/title",
          "value": "IKImageBrowserGroupRangeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserGroupRangeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserGroupRangeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellBackgroundLayer/title",
          "value": "IKImageBrowserCellBackgroundLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellBackgroundLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellBackgroundLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellForegroundLayer/title",
          "value": "IKImageBrowserCellForegroundLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellForegroundLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellForegroundLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellPlaceHolderLayer/title",
          "value": "IKImageBrowserCellPlaceHolderLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellPlaceHolderLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellPlaceHolderLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserShowPreview/title",
          "value": "IKFilterBrowserShowPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserShowPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserShowPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserDefaultInputImage/title",
          "value": "IKFilterBrowserDefaultInputImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserDefaultInputImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserDefaultInputImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/ikimagebrowsergrouprangekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/ikimagebrowsergrouprangekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
