{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "code": "IKImageEditPanelDataSource",
      "type": "codeVoice"
    },
    {
      "text": " protocol describes the methods that an ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object uses to access the contents of its data source object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)IKImageEditPanelDataSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IKImageEditPanelDataSource"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IKImageEditPanelDataSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "IKImageEditPanelDataSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IKImageEditPanelDataSource"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKCameraDeviceView",
          "type": "codeVoice"
        },
        {
          "text": " class displays the contents of the selected camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCameraDeviceView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCameraDeviceView"
        }
      ],
      "role": "symbol",
      "title": "IKCameraDeviceView",
      "type": "topic",
      "url": "/documentation/quartz/ikcameradeviceview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKCameraDeviceViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol is adopted by the delegate of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class. It allows downloading of camera content, handling selection changes, and handling errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "IKCameraDeviceViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/ikcameradeviceviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKDeviceBrowserView",
          "type": "codeVoice"
        },
        {
          "text": " allows you to select a camera or scanner from a list of the available devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserView"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserView",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKDeviceBrowserViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " defines the methods that the delegate of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class can implement. All the methods are optional.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider": {
      "abstract": [
        {
          "text": "A protocol used to provide a custom UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterCustomUIProvider"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterCustomUIProvider"
        }
      ],
      "role": "symbol",
      "title": "IKFilterCustomUIProvider",
      "type": "topic",
      "url": "/documentation/quartz/ikfiltercustomuiprovider"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView": {
      "abstract": [
        {
          "text": "A view for displaying and browsing a large collection of images and movies.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserView",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageEditPanel",
          "type": "codeVoice"
        },
        {
          "text": " class provides a panel, that is, a utility window that floats on top of document windows, optimized for image editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageEditPanel"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageEditPanel"
        }
      ],
      "role": "symbol",
      "title": "IKImageEditPanel",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpanel"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageEditPanelDataSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol describes the methods that an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageEditPanelDataSource"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageEditPanelDataSource"
        }
      ],
      "role": "symbol",
      "title": "IKImageEditPanelDataSource",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasAdjustMode": {
      "abstract": [
        {
          "text": "Returns whether the adjust mode view tab should be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasAdjustMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasAdjustMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasAdjustMode"
        }
      ],
      "role": "symbol",
      "title": "hasAdjustMode",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource/hasadjustmode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasDetailsMode": {
      "abstract": [
        {
          "text": "Returns whether the details mode view tab should be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasDetailsMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasDetailsMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasDetailsMode"
        }
      ],
      "role": "symbol",
      "title": "hasDetailsMode",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource/hasdetailsmode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasEffectsMode": {
      "abstract": [
        {
          "text": "Returns whether the effects mode view tab should be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasEffectsMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasEffectsMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasEffectsMode"
        }
      ],
      "role": "symbol",
      "title": "hasEffectsMode",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource/haseffectsmode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/image": {
      "abstract": [
        {
          "text": "Returns an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource/image"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/imageProperties": {
      "abstract": [
        {
          "text": "Returns a dictionary of the image properties associated with the image in the image edit panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProperties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/imageProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageProperties"
        }
      ],
      "role": "symbol",
      "title": "imageProperties",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource/imageproperties"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/setImage(_:imageProperties:)": {
      "abstract": [
        {
          "text": "Sets an image with the specified properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "imageProperties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/setImage(_:imageProperties:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setImage:imageProperties:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setImage(_:imageProperties:)",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource/setimage(_:imageproperties:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/thumbnail(withMaximumSize:)": {
      "abstract": [
        {
          "text": "Returns a thumbnail image whose size is no larger than the specified size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbnail"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMaximumSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/thumbnail(withMaximumSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "thumbnailWithMaximumSize:"
        }
      ],
      "role": "symbol",
      "title": "thumbnail(withMaximumSize:)",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource/thumbnail(withmaximumsize:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKScannerDeviceView",
          "type": "codeVoice"
        },
        {
          "text": " class displays a view that allows scanning. It can be customized by specifying the display mode. The delegate receives the scanned data and must implement the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKScannerDeviceView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKScannerDeviceView"
        }
      ],
      "role": "symbol",
      "title": "IKScannerDeviceView",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKScannerDeviceViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines the delegate protocol that the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegate must conform to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "IKScannerDeviceViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshow": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKSlideshow",
          "type": "codeVoice"
        },
        {
          "text": " class encapsulates a data source and options for a slideshow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshow"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshow"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshow",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshow"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKSlideshowDataSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol describes the methods that an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshow",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowDataSource"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowDataSource"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowDataSource",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowdatasource"
    },
    "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageBrowserDataSource",
          "type": "codeVoice"
        },
        {
          "text": " informal protocol declares the methods that an instance of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "  class uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IKImageBrowserDataSource Protocol",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdatasource-protocol"
    },
    "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageBrowserDelegate",
          "type": "codeVoice"
        },
        {
          "text": " is an informal protocol for the delegate of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. You can implement these methods to perform custom tasks when in response to events in the image browser view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IKImageBrowserDelegate Protocol",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdelegate-protocol"
    },
    "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageBrowserItem",
          "type": "codeVoice"
        },
        {
          "text": " informal protocol declares the methods that an instance of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class uses to access the contents of its data source for a given item. Some of the methods in this protocol are needed frequently, so you should implement them efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IKImageBrowserItem Protocol",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowseritem-protocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate",
        "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider",
        "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol",
        "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol",
        "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol",
        "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-and-Setting-Image-Properties",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/imageProperties",
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/setImage(_:imageProperties:)"
      ],
      "title": "Getting and Setting Image Properties"
    },
    {
      "anchor": "Getting-Images-From-the-Data-Source",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/image",
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/thumbnail(withMaximumSize:)"
      ],
      "title": "Getting Images From the Data Source"
    },
    {
      "anchor": "New-Methods",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasAdjustMode",
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasDetailsMode",
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasEffectsMode"
      ],
      "title": "New Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IKImageEditPanelDataSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-and-Setting-Image-Properties",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/imageProperties",
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/setImage(_:imageProperties:)"
              ],
              "title": "Getting and Setting Image Properties"
            },
            {
              "anchor": "Getting-Images-From-the-Data-Source",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/image",
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/thumbnail(withMaximumSize:)"
              ],
              "title": "Getting Images From the Data Source"
            },
            {
              "anchor": "New-Methods",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasAdjustMode",
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasDetailsMode",
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource/hasEffectsMode"
              ],
              "title": "New Methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate",
                "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider",
                "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol",
                "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol",
                "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol",
                "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IKImageEditPanelDataSource"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1imageProperties/title",
          "value": "imageProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1imageProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1setImage(_:imageProperties:)/title",
          "value": "setImage:imageProperties:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1setImage(_:imageProperties:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setImage:imageProperties:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/title",
          "value": "IKSlideshow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView/title",
          "value": "IKScannerDeviceView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanel/title",
          "value": "IKImageEditPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/title",
          "value": "IKImageBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDelegate/title",
          "value": "IKDeviceBrowserViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterCustomUIProvider/title",
          "value": "IKFilterCustomUIProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterCustomUIProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterCustomUIProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterCustomUIProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterCustomUIProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1thumbnail(withMaximumSize:)/title",
          "value": "thumbnailWithMaximumSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1thumbnail(withMaximumSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "thumbnailWithMaximumSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1hasEffectsMode/title",
          "value": "hasEffectsMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1hasEffectsMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasEffectsMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource/title",
          "value": "IKImageEditPanelDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView/title",
          "value": "IKCameraDeviceView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1hasAdjustMode/title",
          "value": "hasAdjustMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1hasAdjustMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasAdjustMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserView/title",
          "value": "IKDeviceBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1hasDetailsMode/title",
          "value": "hasDetailsMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource~1hasDetailsMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasDetailsMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowDataSource/title",
          "value": "IKSlideshowDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate/title",
          "value": "IKScannerDeviceViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDelegate/title",
          "value": "IKCameraDeviceViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/ikimageeditpaneldatasource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/ikimageeditpaneldatasource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
