{
  "abstract": [
    {
      "text": "A Core Graphics image source representation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCGImageSourceRepresentationType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@IKImageBrowserCGImageSourceRepresentationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IKImageBrowserCGImageSourceRepresentationType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IKImageBrowserCGImageSourceRepresentationType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "IKImageBrowserCGImageSourceRepresentationType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IKImageBrowserCGImageSourceRepresentationType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ImageIO/CGImageSource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "  object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/ImageIO/CGImageSource": {
      "abstract": [
        {
          "text": "An opaque type that you use to read image data from a URL, data object, or data consumer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSource"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ImageIO/CGImageSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGImageSource",
      "type": "topic",
      "url": "/documentation/ImageIO/CGImageSource"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCGImageRepresentationType": {
      "abstract": [
        {
          "text": "An image representation for Core Graphics images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCGImageRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCGImageRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCGImageRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCGImageRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercgimagerepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCGImageSourceRepresentationType": {
      "abstract": [
        {
          "text": "A Core Graphics image source representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCGImageSourceRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCGImageSourceRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCGImageSourceRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCGImageSourceRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercgimagesourcerepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserIconRefPathRepresentationType": {
      "abstract": [
        {
          "text": "A path to an icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserIconRefPathRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserIconRefPathRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserIconRefPathRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserIconRefPathRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsericonrefpathrepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserIconRefRepresentationType": {
      "abstract": [
        {
          "text": "An icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserIconRefRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserIconRefRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserIconRefRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserIconRefRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsericonrefrepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSBitmapImageRepresentationType": {
      "abstract": [
        {
          "text": "A bitmap image representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserNSBitmapImageRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSBitmapImageRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserNSBitmapImageRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserNSBitmapImageRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsernsbitmapimagerepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSDataRepresentationType": {
      "abstract": [
        {
          "text": "An data representation of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserNSDataRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSDataRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserNSDataRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserNSDataRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsernsdatarepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSImageRepresentationType": {
      "abstract": [
        {
          "text": "An image representation type for image objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserNSImageRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSImageRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserNSImageRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserNSImageRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsernsimagerepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSURLRepresentationType": {
      "abstract": [
        {
          "text": "A URL image representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserNSURLRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSURLRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserNSURLRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserNSURLRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsernsurlrepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserPDFPageRepresentationType": {
      "abstract": [
        {
          "text": "A PDF page representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserPDFPageRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserPDFPageRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserPDFPageRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserPDFPageRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserpdfpagerepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserPathRepresentationType": {
      "abstract": [
        {
          "text": "A file path image representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserPathRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserPathRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserPathRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserPathRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserpathrepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQCCompositionPathRepresentationType": {
      "abstract": [
        {
          "text": "A  path (NSString) or URL (NSURL) to a Quartz Composer composition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserQCCompositionPathRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQCCompositionPathRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserQCCompositionPathRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserQCCompositionPathRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserqccompositionpathrepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQCCompositionRepresentationType": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserQCCompositionRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQCCompositionRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserQCCompositionRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserQCCompositionRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserqccompositionrepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQTMoviePathRepresentationType": {
      "abstract": [
        {
          "text": "A path (NSString) or URL (NSURL) to a QuickTime movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserQTMoviePathRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQTMoviePathRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserQTMoviePathRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserQTMoviePathRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserqtmoviepathrepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQTMovieRepresentationType": {
      "abstract": [
        {
          "text": "A   ",
          "type": "text"
        },
        {
          "code": "QTMovie",
          "type": "codeVoice"
        },
        {
          "text": "  object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserQTMovieRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQTMovieRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserQTMovieRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserQTMovieRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserqtmovierepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQuickLookPathRepresentationType": {
      "abstract": [
        {
          "text": "A path (NSString) or URL (NSURL) to load data using QuickLook.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserQuickLookPathRepresentationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQuickLookPathRepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserQuickLookPathRepresentationType"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserQuickLookPathRepresentationType",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserquicklookpathrepresentationtype"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCComposition": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCComposition",
          "type": "codeVoice"
        },
        {
          "text": " class represents a Quartz Composer composition that either:",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "role": "symbol",
      "title": "QCComposition",
      "type": "topic",
      "url": "/documentation/quartz/qccomposition"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserPathRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSURLRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSImageRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCGImageRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSDataRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSBitmapImageRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQTMovieRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQTMoviePathRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQCCompositionRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQCCompositionPathRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQuickLookPathRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserIconRefPathRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserIconRefRepresentationType",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserPDFPageRepresentationType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IKImageBrowserCGImageSourceRepresentationType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCGImageSourceRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserPathRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSURLRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSImageRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCGImageRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSDataRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserNSBitmapImageRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQTMovieRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQTMoviePathRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQCCompositionRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQCCompositionPathRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserQuickLookPathRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserIconRefPathRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserIconRefRepresentationType",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserPDFPageRepresentationType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IKImageBrowserCGImageSourceRepresentationType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQuickLookPathRepresentationType/title",
          "value": "IKImageBrowserQuickLookPathRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQuickLookPathRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserQuickLookPathRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserNSImageRepresentationType/title",
          "value": "IKImageBrowserNSImageRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserNSImageRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserNSImageRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQTMovieRepresentationType/title",
          "value": "IKImageBrowserQTMovieRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQTMovieRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserQTMovieRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserNSDataRepresentationType/title",
          "value": "IKImageBrowserNSDataRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserNSDataRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserNSDataRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQCCompositionRepresentationType/title",
          "value": "IKImageBrowserQCCompositionRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQCCompositionRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserQCCompositionRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserPathRepresentationType/title",
          "value": "IKImageBrowserPathRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserPathRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserPathRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ImageIO~1CGImageSource/title",
          "value": "CGImageSourceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ImageIO~1CGImageSource/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGImageSource",
              "text": "CGImageSource"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserNSBitmapImageRepresentationType/title",
          "value": "IKImageBrowserNSBitmapImageRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserNSBitmapImageRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserNSBitmapImageRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCGImageSourceRepresentationType/title",
          "value": "IKImageBrowserCGImageSourceRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCGImageSourceRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCGImageSourceRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserPDFPageRepresentationType/title",
          "value": "IKImageBrowserPDFPageRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserPDFPageRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserPDFPageRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserNSURLRepresentationType/title",
          "value": "IKImageBrowserNSURLRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserNSURLRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserNSURLRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/title",
          "value": "QCComposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserIconRefPathRepresentationType/title",
          "value": "IKImageBrowserIconRefPathRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserIconRefPathRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserIconRefPathRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserIconRefRepresentationType/title",
          "value": "IKImageBrowserIconRefRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserIconRefRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserIconRefRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQTMoviePathRepresentationType/title",
          "value": "IKImageBrowserQTMoviePathRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQTMoviePathRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserQTMoviePathRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQCCompositionPathRepresentationType/title",
          "value": "IKImageBrowserQCCompositionPathRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserQCCompositionPathRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserQCCompositionPathRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCGImageRepresentationType/title",
          "value": "IKImageBrowserCGImageRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCGImageRepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCGImageRepresentationType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/ikimagebrowsercgimagesourcerepresentationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/ikimagebrowsercgimagesourcerepresentationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
