{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "code": "IKScannerDeviceViewDelegate",
      "type": "codeVoice"
    },
    {
      "text": " protocol defines the delegate protocol that the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " delegate must conform to.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)IKScannerDeviceViewDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IKScannerDeviceViewDelegate"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IKScannerDeviceViewDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "IKScannerDeviceViewDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKCameraDeviceView",
          "type": "codeVoice"
        },
        {
          "text": " class displays the contents of the selected camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCameraDeviceView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCameraDeviceView"
        }
      ],
      "role": "symbol",
      "title": "IKCameraDeviceView",
      "type": "topic",
      "url": "/documentation/quartz/ikcameradeviceview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKCameraDeviceViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol is adopted by the delegate of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class. It allows downloading of camera content, handling selection changes, and handling errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "IKCameraDeviceViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/ikcameradeviceviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKDeviceBrowserView",
          "type": "codeVoice"
        },
        {
          "text": " allows you to select a camera or scanner from a list of the available devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserView"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserView",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKDeviceBrowserViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " defines the methods that the delegate of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class can implement. All the methods are optional.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider": {
      "abstract": [
        {
          "text": "A protocol used to provide a custom UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterCustomUIProvider"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterCustomUIProvider"
        }
      ],
      "role": "symbol",
      "title": "IKFilterCustomUIProvider",
      "type": "topic",
      "url": "/documentation/quartz/ikfiltercustomuiprovider"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView": {
      "abstract": [
        {
          "text": "A view for displaying and browsing a large collection of images and movies.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserView",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageEditPanel",
          "type": "codeVoice"
        },
        {
          "text": " class provides a panel, that is, a utility window that floats on top of document windows, optimized for image editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageEditPanel"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageEditPanel"
        }
      ],
      "role": "symbol",
      "title": "IKImageEditPanel",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpanel"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageEditPanelDataSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol describes the methods that an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageEditPanelDataSource"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageEditPanelDataSource"
        }
      ],
      "role": "symbol",
      "title": "IKImageEditPanelDataSource",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKScannerDeviceView",
          "type": "codeVoice"
        },
        {
          "text": " class displays a view that allows scanning. It can be customized by specifying the display mode. The delegate receives the scanned data and must implement the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKScannerDeviceView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKScannerDeviceView"
        }
      ],
      "role": "symbol",
      "title": "IKScannerDeviceView",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKScannerDeviceViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines the delegate protocol that the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegate must conform to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "IKScannerDeviceViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didEncounterError:)": {
      "abstract": [
        {
          "text": "Invoked whenever the scanner encounters an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDeviceView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IKScannerDeviceView",
          "text": "IKScannerDeviceView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didEncounterError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didEncounterError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDeviceView:didEncounterError:"
        }
      ],
      "role": "symbol",
      "title": "scannerDeviceView(_:didEncounterError:)",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceviewdelegate/scannerdeviceview(_:didencountererror:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:error:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDeviceView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IKScannerDeviceView",
          "text": "IKScannerDeviceView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didScanTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDeviceView:didScanToURL:error:"
        }
      ],
      "role": "symbol",
      "title": "scannerDeviceView(_:didScanTo:error:)",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceviewdelegate/scannerdeviceview(_:didscanto:error:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:fileData:error:)": {
      "abstract": [
        {
          "text": "Invoked when the scan has completed and the data is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDeviceView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IKScannerDeviceView",
          "text": "IKScannerDeviceView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didScanTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "fileData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:fileData:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDeviceView:didScanToURL:fileData:error:"
        }
      ],
      "role": "symbol",
      "title": "scannerDeviceView(_:didScanTo:fileData:error:)",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceviewdelegate/scannerdeviceview(_:didscanto:filedata:error:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:scanInfo:error:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDeviceView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IKScannerDeviceView",
          "text": "IKScannerDeviceView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didScanTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerBandData",
          "text": "ICScannerBandData"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "scanInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:scanInfo:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDeviceView:didScanToBandData:scanInfo:error:"
        }
      ],
      "role": "symbol",
      "title": "scannerDeviceView(_:didScanTo:scanInfo:error:)",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceviewdelegate/scannerdeviceview(_:didscanto:scaninfo:error:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshow": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKSlideshow",
          "type": "codeVoice"
        },
        {
          "text": " class encapsulates a data source and options for a slideshow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshow"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshow"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshow",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshow"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKSlideshowDataSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol describes the methods that an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshow",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowDataSource"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowDataSource"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowDataSource",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowdatasource"
    },
    "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageBrowserDataSource",
          "type": "codeVoice"
        },
        {
          "text": " informal protocol declares the methods that an instance of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "  class uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IKImageBrowserDataSource Protocol",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdatasource-protocol"
    },
    "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageBrowserDelegate",
          "type": "codeVoice"
        },
        {
          "text": " is an informal protocol for the delegate of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. You can implement these methods to perform custom tasks when in response to events in the image browser view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IKImageBrowserDelegate Protocol",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdelegate-protocol"
    },
    "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageBrowserItem",
          "type": "codeVoice"
        },
        {
          "text": " informal protocol declares the methods that an instance of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class uses to access the contents of its data source for a given item. Some of the methods in this protocol are needed frequently, so you should implement them efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IKImageBrowserItem Protocol",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowseritem-protocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate",
        "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider",
        "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol",
        "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol",
        "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol",
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Scan-Completed",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:fileData:error:)"
      ],
      "title": "Scan Completed"
    },
    {
      "anchor": "Scanner-Encountered-Error",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didEncounterError:)"
      ],
      "title": "Scanner Encountered Error"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:error:)",
        "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:scanInfo:error:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IKScannerDeviceViewDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Scan-Completed",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:fileData:error:)"
              ],
              "title": "Scan Completed"
            },
            {
              "anchor": "Scanner-Encountered-Error",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didEncounterError:)"
              ],
              "title": "Scanner Encountered Error"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:error:)",
                "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate/scannerDeviceView(_:didScanTo:scanInfo:error:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate",
                "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider",
                "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol",
                "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol",
                "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol",
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IKScannerDeviceViewDelegate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDelegate/title",
          "value": "IKDeviceBrowserViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate/title",
          "value": "IKScannerDeviceViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterCustomUIProvider/title",
          "value": "IKFilterCustomUIProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterCustomUIProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterCustomUIProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterCustomUIProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterCustomUIProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowDataSource/title",
          "value": "IKSlideshowDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/title",
          "value": "IKSlideshow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate~1scannerDeviceView(_:didScanTo:fileData:error:)/title",
          "value": "scannerDeviceView:didScanToURL:fileData:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate~1scannerDeviceView(_:didScanTo:fileData:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDeviceView:didScanToURL:fileData:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate~1scannerDeviceView(_:didScanTo:scanInfo:error:)/title",
          "value": "scannerDeviceView:didScanToBandData:scanInfo:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate~1scannerDeviceView(_:didScanTo:scanInfo:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDeviceView:didScanToBandData:scanInfo:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserView/title",
          "value": "IKDeviceBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/title",
          "value": "IKImageBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView/title",
          "value": "IKCameraDeviceView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate~1scannerDeviceView(_:didEncounterError:)/title",
          "value": "scannerDeviceView:didEncounterError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate~1scannerDeviceView(_:didEncounterError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDeviceView:didEncounterError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate~1scannerDeviceView(_:didScanTo:error:)/title",
          "value": "scannerDeviceView:didScanToURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate~1scannerDeviceView(_:didScanTo:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDeviceView:didScanToURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanel/title",
          "value": "IKImageEditPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView/title",
          "value": "IKScannerDeviceView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDelegate/title",
          "value": "IKCameraDeviceViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource/title",
          "value": "IKImageEditPanelDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanelDataSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/ikscannerdeviceviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/ikscannerdeviceviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
