{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/imagekit"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ImageKit"
  },
  "references": {
    "doc://com.apple.documentation/documentation/coreimage/cifilter": {
      "abstract": [
        {
          "text": "An image processor that produces an image by manipulating one or more input images or by generating new image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CIFilter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/cifilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "CIFilter",
      "type": "topic",
      "url": "/documentation/coreimage/cifilter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKCameraDeviceView",
          "type": "codeVoice"
        },
        {
          "text": " class displays the contents of the selected camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCameraDeviceView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCameraDeviceView"
        }
      ],
      "role": "symbol",
      "title": "IKCameraDeviceView",
      "type": "topic",
      "url": "/documentation/quartz/ikcameradeviceview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKCameraDeviceViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol is adopted by the delegate of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class. It allows downloading of camera content, handling selection changes, and handling errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "IKCameraDeviceViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/ikcameradeviceviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKDeviceBrowserView",
          "type": "codeVoice"
        },
        {
          "text": " allows you to select a camera or scanner from a list of the available devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserView"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserView",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKDeviceBrowserViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " defines the methods that the delegate of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class can implement. All the methods are optional.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserPanel": {
      "abstract": [
        {
          "text": "Presents a user interface for browsing filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserPanel"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserPanel"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserPanel",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserpanel"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKFilterBrowserView",
          "type": "codeVoice"
        },
        {
          "text": " class is used as a container for the elements of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserPanel",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterBrowserView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterBrowserView"
        }
      ],
      "role": "symbol",
      "title": "IKFilterBrowserView",
      "type": "topic",
      "url": "/documentation/quartz/ikfilterbrowserview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider": {
      "abstract": [
        {
          "text": "A protocol used to provide a custom UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterCustomUIProvider"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterCustomUIProvider"
        }
      ],
      "role": "symbol",
      "title": "IKFilterCustomUIProvider",
      "type": "topic",
      "url": "/documentation/quartz/ikfiltercustomuiprovider"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView": {
      "abstract": [
        {
          "text": "Input parameters for filtering core image filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKFilterUIView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKFilterUIView"
        }
      ],
      "role": "symbol",
      "title": "IKFilterUIView",
      "type": "topic",
      "url": "/documentation/quartz/ikfilteruiview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell": {
      "abstract": [
        {
          "text": "A class used to display a cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCell"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCell"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCell",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercell"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell/cellState()": {
      "abstract": [
        {
          "text": "Returns the current cell state of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellState"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IKImageBrowserCellState",
          "text": "IKImageBrowserCellState"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell/cellState()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cellState"
        }
      ],
      "role": "symbol",
      "title": "cellState()",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercell/cellstate()"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellState": {
      "abstract": [
        {
          "text": "The possible states for the browser cell. These values are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell/cellState()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellState"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellState"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellState",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellstate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation": {
      "abstract": [
        {
          "text": "These constants specify the locations for dropping items onto the browser view. Used by the method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserDropOperation",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdropoperation"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView": {
      "abstract": [
        {
          "text": "A view for displaying and browsing a large collection of images and movies.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserView",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)": {
      "abstract": [
        {
          "text": "Allows the class to retarget the drop action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDrop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IKImageBrowserDropOperation",
          "text": "IKImageBrowserDropOperation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDropIndex:dropOperation:"
        }
      ],
      "role": "symbol",
      "title": "setDrop(_:dropOperation:)",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserview/setdrop(_:dropoperation:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageEditPanel",
          "type": "codeVoice"
        },
        {
          "text": " class provides a panel, that is, a utility window that floats on top of document windows, optimized for image editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageEditPanel"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageEditPanel"
        }
      ],
      "role": "symbol",
      "title": "IKImageEditPanel",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpanel"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageEditPanelDataSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol describes the methods that an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageEditPanelDataSource"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageEditPanelDataSource"
        }
      ],
      "role": "symbol",
      "title": "IKImageEditPanelDataSource",
      "type": "topic",
      "url": "/documentation/quartz/ikimageeditpaneldatasource"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageView": {
      "abstract": [
        {
          "text": "A view that allows displaying and minor editing of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageView"
        }
      ],
      "role": "symbol",
      "title": "IKImageView",
      "type": "topic",
      "url": "/documentation/quartz/ikimageview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTaker": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKPictureTaker",
          "type": "codeVoice"
        },
        {
          "text": " class represents a panel that allows users to choose images by browsing the file system. The picture taker panel provides an Open Recent menu, supports image cropping, and supports taking snapshots from an iSight or other digital camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTaker"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTaker"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTaker",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetaker"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSaveOptions": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKSaveOptions",
          "type": "codeVoice"
        },
        {
          "text": " class initializes, adds, and manages user interface options for saving image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSaveOptions"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSaveOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSaveOptions"
        }
      ],
      "role": "symbol",
      "title": "IKSaveOptions",
      "type": "topic",
      "url": "/documentation/quartz/iksaveoptions"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKScannerDeviceView",
          "type": "codeVoice"
        },
        {
          "text": " class displays a view that allows scanning. It can be customized by specifying the display mode. The delegate receives the scanned data and must implement the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKScannerDeviceView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKScannerDeviceView"
        }
      ],
      "role": "symbol",
      "title": "IKScannerDeviceView",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKScannerDeviceViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines the delegate protocol that the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegate must conform to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "IKScannerDeviceViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshow": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKSlideshow",
          "type": "codeVoice"
        },
        {
          "text": " class encapsulates a data source and options for a slideshow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshow"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshow"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshow",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshow"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKSlideshowDataSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol describes the methods that an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshow",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowDataSource"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowDataSource"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowDataSource",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowdatasource"
    },
    "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageBrowserDataSource",
          "type": "codeVoice"
        },
        {
          "text": " informal protocol declares the methods that an instance of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "  class uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IKImageBrowserDataSource Protocol",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdatasource-protocol"
    },
    "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageBrowserDelegate",
          "type": "codeVoice"
        },
        {
          "text": " is an informal protocol for the delegate of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. You can implement these methods to perform custom tasks when in response to events in the image browser view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IKImageBrowserDelegate Protocol",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdelegate-protocol"
    },
    "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKImageBrowserItem",
          "type": "codeVoice"
        },
        {
          "text": " informal protocol declares the methods that an instance of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class uses to access the contents of its data source for a given item. Some of the methods in this protocol are needed frequently, so you should implement them efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IKImageBrowserItem Protocol",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowseritem-protocol"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit-quartz-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit-quartz-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit Constants",
      "type": "topic",
      "url": "/documentation/quartz/imagekit-quartz-constants"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Enumerations",
      "type": "topic",
      "url": "/documentation/quartz/quartz-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView",
        "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserPanel",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserView",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell",
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel",
        "doc://com.apple.quartz/documentation/Quartz/IKImageView",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTaker",
        "doc://com.apple.quartz/documentation/Quartz/IKSaveOptions",
        "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshow"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate",
        "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate",
        "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider",
        "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol",
        "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol",
        "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol",
        "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource",
        "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Informal-Protocols",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellState",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation"
      ],
      "title": "Informal Protocols"
    },
    {
      "anchor": "Extended-Types",
      "identifiers": [
        "doc://com.apple.documentation/documentation/coreimage/cifilter"
      ],
      "title": "Extended Types"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/imagekit-quartz-constants",
        "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Deprecated-symbols",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView"
      ],
      "title": "Deprecated symbols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView",
                "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserView",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserPanel",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterBrowserView",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterUIView",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell",
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanel",
                "doc://com.apple.quartz/documentation/Quartz/IKImageView",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTaker",
                "doc://com.apple.quartz/documentation/Quartz/IKSaveOptions",
                "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshow"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Protocols",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDelegate",
                "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDelegate",
                "doc://com.apple.quartz/documentation/Quartz/IKFilterCustomUIProvider",
                "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdatasource-protocol",
                "doc://com.apple.quartz/documentation/Quartz/ikimagebrowserdelegate-protocol",
                "doc://com.apple.quartz/documentation/Quartz/ikimagebrowseritem-protocol",
                "doc://com.apple.quartz/documentation/Quartz/IKImageEditPanelDataSource",
                "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDelegate",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowDataSource"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Informal-Protocols",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellState",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation"
              ],
              "title": "Informal Protocols"
            },
            {
              "anchor": "Extended-Types",
              "identifiers": [
                "doc://com.apple.documentation/documentation/coreimage/cifilter"
              ],
              "title": "Extended Types"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/imagekit-quartz-constants",
                "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Deprecated-symbols",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView"
              ],
              "title": "Deprecated symbols"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserPanel/title",
          "value": "IKFilterBrowserPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView/title",
          "value": "IKScannerDeviceView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDelegate/title",
          "value": "IKDeviceBrowserViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCell~1cellState()/title",
          "value": "cellState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCell~1cellState()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cellState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserView/title",
          "value": "IKDeviceBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView/title",
          "value": "IKFilterUIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterUIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterUIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterUIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/title",
          "value": "IKImageBrowserDropOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowDataSource/title",
          "value": "IKSlideshowDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageView/title",
          "value": "IKImageView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTaker/title",
          "value": "IKPictureTaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTaker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate/title",
          "value": "IKScannerDeviceViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanel/title",
          "value": "IKImageEditPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCell/title",
          "value": "IKImageBrowserCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSaveOptions/title",
          "value": "IKSaveOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSaveOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSaveOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSaveOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSaveOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/title",
          "value": "IKImageBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellState/title",
          "value": "IKImageBrowserCellState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/title",
          "value": "IKSlideshow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView/title",
          "value": "IKCameraDeviceView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource/title",
          "value": "IKImageEditPanelDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageEditPanelDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageEditPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserView/title",
          "value": "IKFilterBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterCustomUIProvider/title",
          "value": "IKFilterCustomUIProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterCustomUIProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterCustomUIProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKFilterCustomUIProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKFilterCustomUIProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDelegate/title",
          "value": "IKCameraDeviceViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView~1setDrop(_:dropOperation:)/title",
          "value": "setDropIndex:dropOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView~1setDrop(_:dropOperation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDropIndex:dropOperation:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/imagekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/imagekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
