{
  "abstract": [
    {
      "text": "No time dependency. The custom patch does not depend on time at all. (It does not use the ",
      "type": "text"
    },
    {
      "code": "time",
      "type": "codeVoice"
    },
    {
      "text": "  parameter of the ",
      "type": "text"
    },
    {
      "code": "execute:atTime:withArguments:",
      "type": "codeVoice"
    },
    {
      "text": " method.)",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@QCPlugInTimeMode@kQCPlugInTimeModeNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kQCPlugInTimeModeNone"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@QCPlugInTimeMode",
        "text": "QCPlugInTimeMode"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kQCPlugInTimeModeNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kQCPlugInTimeModeNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kQCPlugInTimeModeNone"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@QCPlugInTimeMode",
              "text": "QCPlugInTimeMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode": {
      "abstract": [
        {
          "text": "Time modes for custom patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInTimeMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInTimeMode"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInTimeMode",
      "type": "topic",
      "url": "/documentation/quartz/qcplugintimemode"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeIdle": {
      "abstract": [
        {
          "text": "An idle time dependency. The custom patch does not depend on time but needs the system to execute it periodically. For example if the custom patch connects to a piece of hardware, to ensure that it pulls data from the hardware, you would set the custom patch time dependency to idle time mode. This time mode is  typically used with providers.]]",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQCPlugInTimeModeIdle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@QCPlugInTimeMode",
          "text": "QCPlugInTimeMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeIdle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQCPlugInTimeModeIdle"
        }
      ],
      "role": "symbol",
      "title": "kQCPlugInTimeModeIdle",
      "type": "topic",
      "url": "/documentation/quartz/kqcplugintimemodeidle"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeNone": {
      "abstract": [
        {
          "text": "No time dependency. The custom patch does not depend on time at all. (It does not use the ",
          "type": "text"
        },
        {
          "code": "time",
          "type": "codeVoice"
        },
        {
          "text": "  parameter of the ",
          "type": "text"
        },
        {
          "code": "execute:atTime:withArguments:",
          "type": "codeVoice"
        },
        {
          "text": " method.)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQCPlugInTimeModeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@QCPlugInTimeMode",
          "text": "QCPlugInTimeMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQCPlugInTimeModeNone"
        }
      ],
      "role": "symbol",
      "title": "kQCPlugInTimeModeNone",
      "type": "topic",
      "url": "/documentation/quartz/kqcplugintimemodenone"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeTimeBase": {
      "abstract": [
        {
          "text": "A time base dependency. The custom patch does depend on time explicitly and has a time base defined by the system. (It uses the ",
          "type": "text"
        },
        {
          "code": "time",
          "type": "codeVoice"
        },
        {
          "text": "  parameter of the ",
          "type": "text"
        },
        {
          "code": "execute:atTime:withArguments:",
          "type": "codeVoice"
        },
        {
          "text": " method.)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQCPlugInTimeModeTimeBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@QCPlugInTimeMode",
          "text": "QCPlugInTimeMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeTimeBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQCPlugInTimeModeTimeBase"
        }
      ],
      "role": "symbol",
      "title": "kQCPlugInTimeModeTimeBase",
      "type": "topic",
      "url": "/documentation/quartz/kqcplugintimemodetimebase"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeIdle",
        "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeTimeBase"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kQCPlugInTimeModeNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQCPlugInTimeModeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeIdle",
                "doc://com.apple.quartz/documentation/Quartz/kQCPlugInTimeModeTimeBase"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kQCPlugInTimeModeNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQCPlugInTimeModeIdle/title",
          "value": "kQCPlugInTimeModeIdle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQCPlugInTimeModeIdle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQCPlugInTimeModeIdle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQCPlugInTimeModeNone/title",
          "value": "kQCPlugInTimeModeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQCPlugInTimeModeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQCPlugInTimeModeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/title",
          "value": "QCPlugInTimeMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTimeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTimeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQCPlugInTimeModeTimeBase/title",
          "value": "kQCPlugInTimeModeTimeBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQCPlugInTimeModeTimeBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQCPlugInTimeModeTimeBase"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/kqcplugintimemodenone"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/kqcplugintimemodenone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
