{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kQuartzFilterPDFWorkflowDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS","text":"String","preciseIdentifier":"s:SS"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/quartz/kquartzfilterpdfworkflowdomain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/quartz/kquartzfilterpdfworkflowdomain"]}],"kind":"symbol","metadata":{"roleHeading":"Global Variable","modules":[{"name":"Quartz"}],"role":"symbol","title":"kQuartzFilterPDFWorkflowDomain","platforms":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.4"}],"navigatorTitle":[{"text":"kQuartzFilterPDFWorkflowDomain","kind":"identifier"}],"symbolKind":"var","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kQuartzFilterPDFWorkflowDomain","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"externalID":"c:@kQuartzFilterPDFWorkflowDomain"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz"]]},"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.quartz/documentation/Quartz/globalUpdateOK","doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain","doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain"],"title":"Constants","anchor":"Constants"}],"references":{"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain","title":"kQuartzFilterPDFWorkflowDomain","url":"/documentation/quartz/kquartzfilterpdfworkflowdomain","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kQuartzFilterPDFWorkflowDomain"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kQuartzFilterPDFWorkflowDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.apple.quartz/documentation/Quartz/globalUpdateOK":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.quartz/documentation/Quartz/globalUpdateOK","title":"globalUpdateOK","url":"/documentation/quartz/globalupdateok","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"globalUpdateOK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"globalUpdateOK","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DarwinBoolean","preciseIdentifier":"s:6Darwin0A7BooleanV"}]},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}],"title":"String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"url":"/documentation/Swift/String"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"type":"topic","title":"NSString","url":"/documentation/foundation/nsstring"},"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"kQuartzFilterApplicationDomain"}],"url":"/documentation/quartz/kquartzfilterapplicationdomain","title":"kQuartzFilterApplicationDomain","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kQuartzFilterApplicationDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain"},"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain":{"identifier":"doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kQuartzFilterPrintingDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"/documentation/quartz/kquartzfilterprintingdomain","abstract":[],"title":"kQuartzFilterPrintingDomain","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kQuartzFilterPrintingDomain"}]},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic"},"doc://com.apple.quartz/documentation/Quartz":{"identifier":"doc://com.apple.quartz/documentation/Quartz","kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Allow users to browse, edit, and save images, using slideshows and Core Image filters."}],"title":"Quartz","url":"/documentation/quartz"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"10.4","deprecated":false,"beta":false,"name":"macOS","unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Global Variable"},{"path":"/metadata/title","op":"replace","value":"kQuartzFilterPDFWorkflowDomain"},{"path":"/metadata/symbolKind","op":"replace","value":"var"},{"value":[{"text":"kQuartzFilterPDFWorkflowDomain","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.quartz/documentation/Quartz/globalUpdateOK","doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain","doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain"],"anchor":"Constants","title":"Constants","generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"kQuartzFilterPDFWorkflowDomain"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"kQuartzFilterPDFWorkflowDomain","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPDFWorkflowDomain/title","op":"replace"},{"value":[{"kind":"identifier","text":"kQuartzFilterPDFWorkflowDomain"}],"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPDFWorkflowDomain/fragments","op":"replace"},{"value":"globalUpdateOK","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1globalUpdateOK/title","op":"replace"},{"value":[{"kind":"identifier","text":"globalUpdateOK"}],"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1globalUpdateOK/fragments","op":"replace"},{"value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace"},{"value":"kQuartzFilterApplicationDomain","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterApplicationDomain/title","op":"replace"},{"value":[{"kind":"identifier","text":"kQuartzFilterApplicationDomain"}],"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterApplicationDomain/fragments","op":"replace"},{"value":"kQuartzFilterPrintingDomain","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPrintingDomain/title","op":"replace"},{"value":[{"kind":"identifier","text":"kQuartzFilterPrintingDomain"}],"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPrintingDomain/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}