{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/pdfkit"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "title": "PDFKit"
  },
  "references": {
    "doc://com.apple.documentation/documentation/PDFKit/PDFAction": {
      "abstract": [
        {
          "text": "An action that is performed when, for example, a PDF annotation is activated or an outline item is clicked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAction"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAction",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAction"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotation": {
      "abstract": [
        {
          "text": "An annotation in a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotation",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAnnotation",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAnnotation"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFAppearanceCharacteristics": {
      "abstract": [
        {
          "text": "An object that represents appearance characteristics of a widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristics"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFAppearanceCharacteristics",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFAppearanceCharacteristics",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFAppearanceCharacteristics"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFBorder": {
      "abstract": [
        {
          "text": "An optional border for an annotation that lies completely within the annotation rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFBorder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFBorder",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFBorder",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFBorder"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFDestination": {
      "abstract": [
        {
          "text": "A `PDFDestination` object describes a point on a PDF page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDestination"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFDestination",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDestination",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFDestination"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFDocument": {
      "abstract": [
        {
          "text": "An object that represents PDF data or a PDF file and defines methods for writing, searching, and selecting PDF data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocument"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFDocument",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocument",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFDocument"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFOutline": {
      "abstract": [
        {
          "text": "A `PDFOutline` object is an element in a tree-structured hierarchy that can represent the structure of a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFOutline"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFOutline",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFOutline",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFOutline"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFPage": {
      "abstract": [
        {
          "text": "`PDFPage`, a subclass of `NSObject`, defines methods used to render PDF pages and work with annotations, text, and selections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFPage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFPage",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFPage",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFPage"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFSelection": {
      "abstract": [
        {
          "text": "A `PDFSelection` object identifies a contiguous or noncontiguous selection of text in a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFSelection"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFSelection",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFSelection",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFSelection"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFThumbnailView": {
      "abstract": [
        {
          "text": "An object that contains a set of thumbnails, each of which represents a page in a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFThumbnailView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFThumbnailView",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFThumbnailView",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFThumbnailView"
    },
    "doc://com.apple.documentation/documentation/PDFKit/PDFView": {
      "abstract": [
        {
          "text": "An object that encapsulates the functionality of PDF Kit into a single widget that you can add to your application using Interface Builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/PDFView",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFView",
      "type": "topic",
      "url": "/documentation/PDFKit/PDFView"
    },
    "doc://com.apple.documentation/documentation/PDFKit/adding-custom-graphics-to-a-pdf": {
      "abstract": [
        {
          "text": "Create and add custom annotation and page graphics to your PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/adding-custom-graphics-to-a-pdf",
      "kind": "article",
      "role": "article",
      "title": "Adding Custom Graphics to a PDF",
      "type": "topic",
      "url": "/documentation/PDFKit/adding-custom-graphics-to-a-pdf"
    },
    "doc://com.apple.documentation/documentation/PDFKit/adding-widgets-to-a-pdf-document": {
      "abstract": [
        {
          "text": "Add text, button, and choice widgets to a PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/adding-widgets-to-a-pdf-document",
      "kind": "article",
      "role": "article",
      "title": "Adding Widgets to a PDF Document",
      "type": "topic",
      "url": "/documentation/PDFKit/adding-widgets-to-a-pdf-document"
    },
    "doc://com.apple.documentation/documentation/PDFKit/custom-graphics": {
      "abstract": [
        {
          "text": "Demonstrates adding a watermark to a PDF page.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/custom-graphics",
      "kind": "article",
      "role": "sampleCode",
      "title": "Custom Graphics",
      "type": "topic",
      "url": "/documentation/PDFKit/custom-graphics"
    },
    "doc://com.apple.documentation/documentation/PDFKit/pdf-widgets": {
      "abstract": [
        {
          "text": "Demonstrates adding widgets—interactive form elements—to a PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit/pdf-widgets",
      "kind": "article",
      "role": "sampleCode",
      "title": "PDF Widgets",
      "type": "topic",
      "url": "/documentation/PDFKit/pdf-widgets"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/deprecated-annotations": {
      "abstract": [
        {
          "text": "These symbols are deprecated and should no longer be used.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/deprecated-annotations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Annotations",
      "type": "topic",
      "url": "/documentation/quartz/deprecated-annotations"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-pdfkit": {
      "abstract": [
        {
          "text": "Create and modify PDF documents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-pdfkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz PDFKit Symbols",
      "type": "topic",
      "url": "/documentation/quartz/quartz-pdfkit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Views",
      "identifiers": [
        "doc://com.apple.documentation/documentation/PDFKit/PDFView",
        "doc://com.apple.documentation/documentation/PDFKit/PDFThumbnailView"
      ],
      "title": "Views"
    },
    {
      "anchor": "Content-Model",
      "identifiers": [
        "doc://com.apple.documentation/documentation/PDFKit/PDFDocument",
        "doc://com.apple.documentation/documentation/PDFKit/PDFPage",
        "doc://com.apple.documentation/documentation/PDFKit/PDFOutline",
        "doc://com.apple.documentation/documentation/PDFKit/PDFSelection"
      ],
      "title": "Content Model"
    },
    {
      "anchor": "Annotations",
      "identifiers": [
        "doc://com.apple.documentation/documentation/PDFKit/adding-widgets-to-a-pdf-document",
        "doc://com.apple.documentation/documentation/PDFKit/adding-custom-graphics-to-a-pdf",
        "doc://com.apple.documentation/documentation/PDFKit/custom-graphics",
        "doc://com.apple.documentation/documentation/PDFKit/pdf-widgets",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotation",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAction",
        "doc://com.apple.documentation/documentation/PDFKit/PDFDestination",
        "doc://com.apple.documentation/documentation/PDFKit/PDFAppearanceCharacteristics",
        "doc://com.apple.documentation/documentation/PDFKit/PDFBorder",
        "doc://com.apple.quartz/documentation/Quartz/deprecated-annotations"
      ],
      "title": "Annotations"
    },
    {
      "anchor": "PDFKit-Documentation",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/quartz-pdfkit"
      ],
      "title": "PDFKit Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Views",
              "identifiers": [
                "doc://com.apple.documentation/documentation/PDFKit/PDFView",
                "doc://com.apple.documentation/documentation/PDFKit/PDFThumbnailView"
              ],
              "title": "Views"
            },
            {
              "anchor": "Content-Model",
              "identifiers": [
                "doc://com.apple.documentation/documentation/PDFKit/PDFDocument",
                "doc://com.apple.documentation/documentation/PDFKit/PDFPage",
                "doc://com.apple.documentation/documentation/PDFKit/PDFOutline",
                "doc://com.apple.documentation/documentation/PDFKit/PDFSelection"
              ],
              "title": "Content Model"
            },
            {
              "anchor": "Annotations",
              "identifiers": [
                "doc://com.apple.documentation/documentation/PDFKit/adding-widgets-to-a-pdf-document",
                "doc://com.apple.documentation/documentation/PDFKit/adding-custom-graphics-to-a-pdf",
                "doc://com.apple.documentation/documentation/PDFKit/custom-graphics",
                "doc://com.apple.documentation/documentation/PDFKit/pdf-widgets",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAnnotation",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAction",
                "doc://com.apple.documentation/documentation/PDFKit/PDFDestination",
                "doc://com.apple.documentation/documentation/PDFKit/PDFAppearanceCharacteristics",
                "doc://com.apple.documentation/documentation/PDFKit/PDFBorder",
                "doc://com.apple.quartz/documentation/Quartz/deprecated-annotations"
              ],
              "title": "Annotations"
            },
            {
              "anchor": "PDFKit-Documentation",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/quartz-pdfkit"
              ],
              "title": "PDFKit Documentation"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFDocument/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFDocument"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAppearanceCharacteristics/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristics"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFDestination/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFDestination"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAction"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFThumbnailView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFThumbnailView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFPage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFPage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSView",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFSelection/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFSelection"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFAnnotation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFBorder/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFBorder"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PDFKit~1PDFOutline/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFOutline"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/pdfkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/pdfkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
