{
  "abstract": [
    {
      "text": "Keys for customizing the picture taker appearance and behavior. These values are set by sending the picture taker instance ",
      "type": "text"
    },
    {
      "code": "setValue:forKey",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/imagekit",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTaker"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/picture-taker-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Picture Taker Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTaker": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKPictureTaker",
          "type": "codeVoice"
        },
        {
          "text": " class represents a panel that allows users to choose images by browsing the file system. The picture taker panel provides an Open Recent menu, supports image cropping, and supports taking snapshots from an iSight or other digital camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTaker"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTaker"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTaker",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetaker"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsEditingKey": {
      "abstract": [
        {
          "text": "A key for allowing image editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerAllowsEditingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsEditingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerAllowsEditingKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerAllowsEditingKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakerallowseditingkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsFileChoosingKey": {
      "abstract": [
        {
          "text": "A key for allowing the user to choose a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerAllowsFileChoosingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsFileChoosingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerAllowsFileChoosingKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerAllowsFileChoosingKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakerallowsfilechoosingkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsVideoCaptureKey": {
      "abstract": [
        {
          "text": "A key for allowing video capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerAllowsVideoCaptureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsVideoCaptureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerAllowsVideoCaptureKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerAllowsVideoCaptureKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakerallowsvideocapturekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerCropAreaSizeKey": {
      "abstract": [
        {
          "text": "A key for the cropping area size. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " object (",
          "type": "text"
        },
        {
          "code": "NSSize",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerCropAreaSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerCropAreaSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerCropAreaSizeKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerCropAreaSizeKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakercropareasizekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerImageTransformsKey": {
      "abstract": [
        {
          "text": "A n image transformation key. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSDictionary",
          "type": "codeVoice"
        },
        {
          "text": " object that can be serialized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerImageTransformsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerImageTransformsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerImageTransformsKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerImageTransformsKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakerimagetransformskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerInformationalTextKey": {
      "abstract": [
        {
          "text": "A key for informational text. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "NSAttributedString",
          "type": "codeVoice"
        },
        {
          "text": " object whose default value is ",
          "type": "text"
        },
        {
          "code": "\"Drag Image Here\"",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerInformationalTextKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerInformationalTextKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerInformationalTextKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerInformationalTextKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakerinformationaltextkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerOutputImageMaxSizeKey": {
      "abstract": [
        {
          "text": "A key for the maximum size of the output image. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " object (",
          "type": "text"
        },
        {
          "code": "NSSize",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerOutputImageMaxSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerOutputImageMaxSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerOutputImageMaxSizeKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerOutputImageMaxSizeKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakeroutputimagemaxsizekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerRemainOpenAfterValidateKey": {
      "abstract": [
        {
          "text": "A key that determines if the picture taker UI should remain open after the user selects done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerRemainOpenAfterValidateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerRemainOpenAfterValidateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerRemainOpenAfterValidateKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerRemainOpenAfterValidateKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakerremainopenaftervalidatekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowAddressBookPictureKey": {
      "abstract": [
        {
          "text": "A key for showing the address book picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerShowAddressBookPictureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowAddressBookPictureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerShowAddressBookPictureKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerShowAddressBookPictureKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakershowaddressbookpicturekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowEffectsKey": {
      "abstract": [
        {
          "text": "A key for showing effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerShowEffectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowEffectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerShowEffectsKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerShowEffectsKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakershoweffectskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowEmptyPictureKey": {
      "abstract": [
        {
          "text": "A key for showing an empty picture. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSImage",
          "type": "codeVoice"
        },
        {
          "text": " object. The default value is ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ". If set to an image, the picture taker automatically shows an image at the end of the Recent Pictures pop-up menu. that means “no picture.”",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerShowEmptyPictureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowEmptyPictureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerShowEmptyPictureKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerShowEmptyPictureKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakershowemptypicturekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerUpdateRecentPictureKey": {
      "abstract": [
        {
          "text": "A key for allowing a recent picture to be updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKPictureTakerUpdateRecentPictureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerUpdateRecentPictureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKPictureTakerUpdateRecentPictureKey"
        }
      ],
      "role": "symbol",
      "title": "IKPictureTakerUpdateRecentPictureKey",
      "type": "topic",
      "url": "/documentation/quartz/ikpicturetakerupdaterecentpicturekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit",
      "type": "topic",
      "url": "/documentation/quartz/imagekit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsVideoCaptureKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsFileChoosingKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerUpdateRecentPictureKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsEditingKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowEffectsKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerInformationalTextKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerImageTransformsKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerOutputImageMaxSizeKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerCropAreaSizeKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowAddressBookPictureKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowEmptyPictureKey",
        "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerRemainOpenAfterValidateKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsVideoCaptureKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsFileChoosingKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerUpdateRecentPictureKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerAllowsEditingKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowEffectsKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerInformationalTextKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerImageTransformsKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerOutputImageMaxSizeKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerCropAreaSizeKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowAddressBookPictureKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerShowEmptyPictureKey",
                "doc://com.apple.quartz/documentation/Quartz/IKPictureTakerRemainOpenAfterValidateKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTaker/title",
          "value": "IKPictureTaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTaker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerRemainOpenAfterValidateKey/title",
          "value": "IKPictureTakerRemainOpenAfterValidateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerRemainOpenAfterValidateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerRemainOpenAfterValidateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerImageTransformsKey/title",
          "value": "IKPictureTakerImageTransformsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerImageTransformsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerImageTransformsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerInformationalTextKey/title",
          "value": "IKPictureTakerInformationalTextKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerInformationalTextKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerInformationalTextKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerUpdateRecentPictureKey/title",
          "value": "IKPictureTakerUpdateRecentPictureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerUpdateRecentPictureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerUpdateRecentPictureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerShowEffectsKey/title",
          "value": "IKPictureTakerShowEffectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerShowEffectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerShowEffectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerAllowsVideoCaptureKey/title",
          "value": "IKPictureTakerAllowsVideoCaptureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerAllowsVideoCaptureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerAllowsVideoCaptureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerOutputImageMaxSizeKey/title",
          "value": "IKPictureTakerOutputImageMaxSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerOutputImageMaxSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerOutputImageMaxSizeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerAllowsEditingKey/title",
          "value": "IKPictureTakerAllowsEditingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerAllowsEditingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerAllowsEditingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerShowAddressBookPictureKey/title",
          "value": "IKPictureTakerShowAddressBookPictureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerShowAddressBookPictureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerShowAddressBookPictureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerShowEmptyPictureKey/title",
          "value": "IKPictureTakerShowEmptyPictureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerShowEmptyPictureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerShowEmptyPictureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerAllowsFileChoosingKey/title",
          "value": "IKPictureTakerAllowsFileChoosingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerAllowsFileChoosingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerAllowsFileChoosingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerCropAreaSizeKey/title",
          "value": "IKPictureTakerCropAreaSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKPictureTakerCropAreaSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKPictureTakerCropAreaSizeKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/picture-taker-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/picture-taker-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
