{
  "abstract": [
    {
      "text": "A composition that produces a stylize effect.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryStylize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@QCCompositionCategoryStylize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QCCompositionCategoryStylize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QCCompositionCategoryStylize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.4",
        "message": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "QCCompositionCategoryStylize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QCCompositionCategoryStylize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeBuiltInKey": {
      "abstract": [
        {
          "text": "The key for the composition origin.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeBuiltInKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeBuiltInKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeBuiltInKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeBuiltInKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributebuiltinkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCategoryKey": {
      "abstract": [
        {
          "text": "A key representing a composition category.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeCategoryKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCategoryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeCategoryKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeCategoryKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributecategorykey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCopyrightKey": {
      "abstract": [
        {
          "text": "The key for composition copyright information. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeCopyrightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCopyrightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeCopyrightKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeCopyrightKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributecopyrightkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeDescriptionKey": {
      "abstract": [
        {
          "text": "The key for the composition description. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeDescriptionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeDescriptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeDescriptionKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeDescriptionKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributedescriptionkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeHasConsumersKey": {
      "abstract": [
        {
          "text": "The key for a composition that has consumer patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeHasConsumersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeHasConsumersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeHasConsumersKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeHasConsumersKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributehasconsumerskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeIsTimeDependentKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeIsTimeDependentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeIsTimeDependentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeIsTimeDependentKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeIsTimeDependentKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributeistimedependentkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeNameKey": {
      "abstract": [
        {
          "text": "The key for the composition name. The associated value is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeNameKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeNameKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributenamekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryDistortion": {
      "abstract": [
        {
          "text": "A composition that produces a distortion effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryDistortion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryDistortion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryDistortion"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionCategoryDistortion",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioncategorydistortion"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryStylize": {
      "abstract": [
        {
          "text": "A composition that produces a stylize effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryStylize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryStylize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryStylize"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionCategoryStylize",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioncategorystylize"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryUtility": {
      "abstract": [
        {
          "text": "A utility composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryUtility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryUtility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionCategoryUtility"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionCategoryUtility",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioncategoryutility"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputAudioPeak",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be in the ",
          "type": "text"
        },
        {
          "code": "[0,1]",
          "type": "codeVoice"
        },
        {
          "text": " range as a mono signal with no decay applied.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioPeakKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioPeakKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputAudioPeakKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputaudiopeakkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey": {
      "abstract": [
        {
          "text": "A structure input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputAudioSpectrum",
          "type": "codeVoice"
        },
        {
          "text": ". The structure must contain 16 values in the ",
          "type": "text"
        },
        {
          "code": "[0,1]",
          "type": "codeVoice"
        },
        {
          "text": " range representing 16 spectrum bands of the mono signal from low to high frequencies with no decay applied.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioSpectrumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioSpectrumKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputAudioSpectrumKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputaudiospectrumkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey": {
      "abstract": [
        {
          "text": "An image input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputDestinationImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputDestinationImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputDestinationImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputDestinationImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputdestinationimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey": {
      "abstract": [
        {
          "text": "An image input port whose key is  ",
          "type": "text"
        },
        {
          "code": "inputImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputPace",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be in the ",
          "type": "text"
        },
        {
          "code": "[0,1]",
          "type": "codeVoice"
        },
        {
          "text": " range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputPaceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputPaceKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputPaceKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputpacekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey": {
      "abstract": [
        {
          "text": "A Boolean input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputPreviewMode",
          "type": "codeVoice"
        },
        {
          "text": ". When the value of this input port is set to ",
          "type": "text"
        },
        {
          "code": "TRUE",
          "type": "codeVoice"
        },
        {
          "text": ", the composition that provides this port must be able to run in a low-quality mode that produces a preview of the composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputPreviewModeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputPreviewModeKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputPreviewModeKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputpreviewmodekey"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeBuiltInKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCategoryKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCopyrightKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeDescriptionKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeHasConsumersKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeIsTimeDependentKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeNameKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryDistortion",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryUtility",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QCCompositionCategoryStylize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionCategoryStylize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeBuiltInKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCategoryKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeCopyrightKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeDescriptionKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeHasConsumersKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeIsTimeDependentKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeNameKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryDistortion",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionCategoryUtility",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QCCompositionCategoryStylize"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPreviewModeKey/title",
          "value": "QCCompositionInputPreviewModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPreviewModeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputPreviewModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeCopyrightKey/title",
          "value": "QCCompositionAttributeCopyrightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeCopyrightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeCopyrightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputImageKey/title",
          "value": "QCCompositionInputImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeDescriptionKey/title",
          "value": "QCCompositionAttributeDescriptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeDescriptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeNameKey/title",
          "value": "QCCompositionAttributeNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeHasConsumersKey/title",
          "value": "QCCompositionAttributeHasConsumersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeHasConsumersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeHasConsumersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeCategoryKey/title",
          "value": "QCCompositionAttributeCategoryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeCategoryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryStylize/title",
          "value": "QCCompositionCategoryStylize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryStylize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionCategoryStylize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeIsTimeDependentKey/title",
          "value": "QCCompositionAttributeIsTimeDependentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeIsTimeDependentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeIsTimeDependentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioPeakKey/title",
          "value": "QCCompositionInputAudioPeakKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioPeakKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputAudioPeakKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioSpectrumKey/title",
          "value": "QCCompositionInputAudioSpectrumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioSpectrumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputAudioSpectrumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPaceKey/title",
          "value": "QCCompositionInputPaceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPaceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputPaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeBuiltInKey/title",
          "value": "QCCompositionAttributeBuiltInKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeBuiltInKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeBuiltInKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryUtility/title",
          "value": "QCCompositionCategoryUtility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryUtility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionCategoryUtility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputDestinationImageKey/title",
          "value": "QCCompositionInputDestinationImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputDestinationImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputDestinationImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryDistortion/title",
          "value": "QCCompositionCategoryDistortion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionCategoryDistortion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionCategoryDistortion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/qccompositioncategorystylize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/qccompositioncategorystylize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
