{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "code": "QCRenderer",
      "type": "codeVoice"
    },
    {
      "text": " protocol defines the methods used to pass data to the input ports or retrieve data from the output ports of the root patch of a Quartz Composer composition. This protocol is adopted by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCView",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", and ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " classes.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)QCCompositionRenderer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QCCompositionRenderer"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QCCompositionRenderer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.4",
        "message": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "QCCompositionRenderer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QCCompositionRenderer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer": {
      "abstract": [
        {
          "text": "A layer that loads, plays, and controls Quartz Composer compositions in a Core Animation layer hierarchy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionLayer"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionLayer"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionLayer",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionlayer"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCCompositionPickerView",
          "type": "codeVoice"
        },
        {
          "text": " class allows users to browse compositions that are in the Quartz Composer composition repository, and to preview them. You can set the default input parameters for a composition preview  by using the method setDefaultValue:forInputKey:.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionPickerView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionPickerView"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionPickerView",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionpickerview"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCRenderer",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines the methods used to pass data to the input ports or retrieve data from the output ports of the root patch of a Quartz Composer composition. This protocol is adopted by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " classes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionRenderer"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionRenderer"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionRenderer",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/attributes()": {
      "abstract": [
        {
          "text": "Returns the attributes of the composition associated with the renderer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/attributes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributes"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "attributes()",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/attributes()"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/inputKeys()": {
      "abstract": [
        {
          "text": "Returns an array that contains the keys that identify the input ports of the root patch of the composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputKeys"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/inputKeys()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputKeys"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputKeys()",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/inputkeys()"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/outputKeys()": {
      "abstract": [
        {
          "text": "Returns an array that contains the keys that identify the output ports of the root patch of the composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputKeys"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/outputKeys()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputKeys"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputKeys()",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/outputkeys()"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/propertyListFromInputValues()": {
      "abstract": [
        {
          "text": "Returns a property list object that represents the current values for all the input keys of the composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertyListFromInputValues"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/propertyListFromInputValues()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertyListFromInputValues"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "propertyListFromInputValues()",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/propertylistfrominputvalues()"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/setInputValuesWithPropertyList(_:)": {
      "abstract": [
        {
          "text": "Sets the values for the input keys of the composition from a previously saved property list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setInputValuesWithPropertyList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/setInputValuesWithPropertyList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setInputValuesWithPropertyList:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setInputValuesWithPropertyList(_:)",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/setinputvalueswithpropertylist(_:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/setValue(_:forInputKey:)": {
      "abstract": [
        {
          "text": "Sets the value for an input port of a composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "forInputKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/setValue(_:forInputKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setValue:forInputKey:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setValue(_:forInputKey:)",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/setvalue(_:forinputkey:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/userInfo()": {
      "abstract": [
        {
          "text": "Returns a mutable dictionary for storing arbitrary information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableDictionary",
          "text": "NSMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/userInfo()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "userInfo()",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/userinfo()"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forInputKey:)": {
      "abstract": [
        {
          "text": "Returns the value for an input port of a composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forInputKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forInputKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForInputKey:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "value(forInputKey:)",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/value(forinputkey:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forOutputKey:)": {
      "abstract": [
        {
          "text": "Returns the value for an output port of a composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forOutputKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forOutputKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForOutputKey:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "value(forOutputKey:)",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/value(foroutputkey:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forOutputKey:ofType:)": {
      "abstract": [
        {
          "text": "Returns the current value on an output port (identified by its key) of the root patch of the composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forOutputKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forOutputKey:ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForOutputKey:ofType:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "value(forOutputKey:ofType:)",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer/value(foroutputkey:oftype:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugIn/execute(_:atTime:withArguments:)": {
      "abstract": [
        {
          "text": "Performs the processing or rendering tasks appropriate for the custom patch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QCPlugInContext",
          "text": "QCPlugInContext"
        },
        {
          "kind": "text",
          "text": ")!, "
        },
        {
          "kind": "externalParam",
          "text": "atTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withArguments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugIn/execute(_:atTime:withArguments:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "execute:atTime:withArguments:"
        }
      ],
      "role": "symbol",
      "title": "execute(_:atTime:withArguments:)",
      "type": "topic",
      "url": "/documentation/quartz/qcplugin/execute(_:attime:witharguments:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInContext": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCPlugInContext",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines methods that you use only from within the execution method (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugIn/execute(_:atTime:withArguments:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ") of a ",
          "type": "text"
        },
        {
          "code": "QCPlugIn",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInContext"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInContext"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInContext",
      "type": "topic",
      "url": "/documentation/quartz/qcplugincontext"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInInputImageSource": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCPlugInInputImageSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol eliminates the need to use explicit image types for the image input ports on your custom patch. Not only does using the protocol avoid restrictions of a specific image type, but it avoids impedance mismatches, and provides better performance by deferring pixel computation until it is needed. When you need to access the pixels in an image, you simply convert the image to a representation (texture or buffer) using one of the methods defined by the ",
          "type": "text"
        },
        {
          "code": "QCPlugInInputImageSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol. Use a texture representation when you want to use input images on the GPU. Use a buffer representation when you want to use input images on the CPU.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInInputImageSource"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInInputImageSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInInputImageSource"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInInputImageSource",
      "type": "topic",
      "url": "/documentation/quartz/qcplugininputimagesource"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInOutputImageProvider": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCPlugInOuputImageProvider",
          "type": "codeVoice"
        },
        {
          "text": " protocol eliminates the need to use explicit image types for the image output ports on a custom patch. The methods in this protocol are called by the Quartz Composer engine when the output image is needed. If your custom patch has an image output port, you need to implement the appropriate methods for rendering image data and to supply information about the rendering destination and the image bounds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInOutputImageProvider"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInOutputImageProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInOutputImageProvider"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInOutputImageProvider",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginoutputimageprovider"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCRenderer": {
      "abstract": [
        {
          "text": "A base class for low-level rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCRenderer"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCRenderer"
        }
      ],
      "role": "symbol",
      "title": "QCRenderer",
      "type": "topic",
      "url": "/documentation/quartz/qcrenderer"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCView",
          "type": "codeVoice"
        },
        {
          "text": " class is a custom ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": " class that loads, plays, and controls Quartz Composer compositions. It is an autonomous view that is driven by an internal timer running on the main thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCView"
        }
      ],
      "role": "symbol",
      "title": "QCView",
      "type": "topic",
      "url": "/documentation/quartz/qcview"
    },
    "doc://com.apple.quartz/documentation/Quartz/qccompositionparameterviewdelegate": {
      "abstract": [
        {
          "text": "A protocol for composition parameter view’s delegate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/qccompositionparameterviewdelegate",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QCCompositionParameterViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionparameterviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/qccompositionpickerviewdelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCCompositionPickerViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " informal protocol defines methods that allow  your application to respond to changes in a composition picker view (a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/qccompositionpickerviewdelegate",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QCCompositionPickerViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionpickerviewdelegate"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
        "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
        "doc://com.apple.quartz/documentation/Quartz/QCView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/qccompositionparameterviewdelegate",
        "doc://com.apple.quartz/documentation/Quartz/qccompositionpickerviewdelegate",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInContext",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInInputImageSource",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInOutputImageProvider"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Passing-and-Retrieving-Values-From-a-Composition",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/setValue(_:forInputKey:)",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forInputKey:)",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forOutputKey:)",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forOutputKey:ofType:)"
      ],
      "title": "Passing and Retrieving Values From a Composition"
    },
    {
      "anchor": "Getting-Input-and-Output-Keys",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/inputKeys()",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/outputKeys()"
      ],
      "title": "Getting Input and Output Keys"
    },
    {
      "anchor": "Getting-Attributes",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/attributes()"
      ],
      "title": "Getting Attributes"
    },
    {
      "anchor": "Storing-Arbitrary-Information",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/userInfo()"
      ],
      "title": "Storing Arbitrary Information"
    },
    {
      "anchor": "Saving-and-Restoring-Input-Values",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/propertyListFromInputValues()",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/setInputValuesWithPropertyList(_:)"
      ],
      "title": "Saving and Restoring Input Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QCCompositionRenderer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Passing-and-Retrieving-Values-From-a-Composition",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/setValue(_:forInputKey:)",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forInputKey:)",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forOutputKey:)",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/value(forOutputKey:ofType:)"
              ],
              "title": "Passing and Retrieving Values From a Composition"
            },
            {
              "anchor": "Getting-Input-and-Output-Keys",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/inputKeys()",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/outputKeys()"
              ],
              "title": "Getting Input and Output Keys"
            },
            {
              "anchor": "Getting-Attributes",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/attributes()"
              ],
              "title": "Getting Attributes"
            },
            {
              "anchor": "Storing-Arbitrary-Information",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/userInfo()"
              ],
              "title": "Storing Arbitrary Information"
            },
            {
              "anchor": "Saving-and-Restoring-Input-Values",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/propertyListFromInputValues()",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer/setInputValuesWithPropertyList(_:)"
              ],
              "title": "Saving and Restoring Input Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
                "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
                "doc://com.apple.quartz/documentation/Quartz/QCView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/qccompositionparameterviewdelegate",
                "doc://com.apple.quartz/documentation/Quartz/qccompositionpickerviewdelegate",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInContext",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInInputImageSource",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInOutputImageProvider"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QCCompositionRenderer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/title",
          "value": "QCRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1propertyListFromInputValues()/title",
          "value": "propertyListFromInputValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1propertyListFromInputValues()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "propertyListFromInputValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1outputKeys()/title",
          "value": "outputKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1outputKeys()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "outputKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1attributes()/title",
          "value": "attributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1attributes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1value(forInputKey:)/title",
          "value": "valueForInputKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1value(forInputKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueForInputKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1value(forOutputKey:ofType:)/title",
          "value": "valueForOutputKey:ofType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1value(forOutputKey:ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueForOutputKey:ofType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/title",
          "value": "QCView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer/title",
          "value": "QCCompositionRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInOutputImageProvider/title",
          "value": "QCPlugInOutputImageProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInOutputImageProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInOutputImageProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInOutputImageProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInOutputImageProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInInputImageSource/title",
          "value": "QCPlugInInputImageSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInInputImageSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInInputImageSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInInputImageSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInInputImageSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1userInfo()/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1userInfo()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInContext/title",
          "value": "QCPlugInContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1inputKeys()/title",
          "value": "inputKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1inputKeys()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "inputKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1value(forOutputKey:)/title",
          "value": "valueForOutputKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1value(forOutputKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueForOutputKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn~1execute(_:atTime:withArguments:)/title",
          "value": "execute:atTime:withArguments:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn~1execute(_:atTime:withArguments:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "execute:atTime:withArguments:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerView/title",
          "value": "QCCompositionPickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionPickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionPickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionLayer/title",
          "value": "QCCompositionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1setValue(_:forInputKey:)/title",
          "value": "setValue:forInputKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1setValue(_:forInputKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setValue:forInputKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1setInputValuesWithPropertyList(_:)/title",
          "value": "setInputValuesWithPropertyList:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer~1setInputValuesWithPropertyList(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setInputValuesWithPropertyList:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/qccompositionrenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/qccompositionrenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
