{"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSView"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement","doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility","doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer","doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSDraggingDestination","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding","doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider","doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring","doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification","doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer","doc://com.externally.resolved.symbol/s:s8SendableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/render(atTime:arguments:)"],"anchor":"Performing-Custom-Operations-During-Rendering","title":"Performing Custom Operations During Rendering"},{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/loadComposition(fromFile:)","doc://com.apple.quartz/documentation/Quartz/QCView/load(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/loadedComposition()","doc://com.apple.quartz/documentation/Quartz/QCView/unloadComposition()"],"anchor":"Loading-a-Composition","title":"Loading a Composition"},{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/erase()","doc://com.apple.quartz/documentation/Quartz/QCView/eraseColor()","doc://com.apple.quartz/documentation/Quartz/QCView/setEraseColor(_:)"],"anchor":"Managing-the-Erase-Color","title":"Managing the Erase Color"},{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/eventForwardingMask()","doc://com.apple.quartz/documentation/Quartz/QCView/setEventForwardingMask(_:)"],"anchor":"Setting-and-Getting-Event-Masks","title":"Setting and Getting Event Masks"},{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/maxRenderingFrameRate()","doc://com.apple.quartz/documentation/Quartz/QCView/setMaxRenderingFrameRate(_:)"],"anchor":"Setting-and-Getting-the-Maximum-Frame-Rate","title":"Setting and Getting the Maximum Frame Rate"},{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/startRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/isRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/autostartsRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/setAutostartsRendering(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/stopRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/pauseRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/isPausedRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/resumeRendering()"],"anchor":"Managing-Rendering","title":"Managing Rendering"},{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/play(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/start(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/stop(_:)"],"anchor":"Using-Interface-Builder","title":"Using Interface Builder"},{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/snapshotImage()","doc://com.apple.quartz/documentation/Quartz/QCView/createSnapshotImage(ofType:)"],"anchor":"Taking-Snapshot-Images","title":"Taking Snapshot Images"},{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/openGLContext()","doc://com.apple.quartz/documentation/Quartz/QCView/openGLPixelFormat()"],"anchor":"Working-With-OpenGL","title":"Working With OpenGL"}],"metadata":{"navigatorTitle":[{"text":"QCView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QCView","kind":"identifier"}],"symbolKind":"class","platforms":[{"unavailable":false,"deprecatedAt":"10.15","introducedAt":"10.4","deprecated":false,"name":"macOS","message":"QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)","beta":false}],"title":"QCView","externalID":"c:objc(cs)QCView","modules":[{"name":"Quartz"}],"roleHeading":"Class","role":"symbol"},"seeAlsoSections":[{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCComposition","doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer","doc://com.apple.quartz/documentation/Quartz/QCCompositionParameterView","doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerPanel","doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView","doc://com.apple.quartz/documentation/Quartz/QCCompositionRepository","doc://com.apple.quartz/documentation/Quartz/QCPatchController","doc://com.apple.quartz/documentation/Quartz/QCPlugIn","doc://com.apple.quartz/documentation/Quartz/QCPlugInViewController","doc://com.apple.quartz/documentation/Quartz/QCRenderer"],"generated":true,"anchor":"Classes","title":"Classes"}],"deprecationSummary":[{"inlineContent":[{"text":"QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/quartz/qcview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/quartz/qcview"]}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"QCView"},{"type":"text","text":" class is a custom "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":" class that loads, plays, and controls Quartz Composer compositions. It is an autonomous view that is driven by an internal timer running on the main thread."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz"]]},"identifier":{"url":"doc://com.apple.quartz/documentation/Quartz/QCView","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QCView"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"text":"The view can be set to render a composition automatically when it is placed onscreen. The view stops rendering when it is placed offscreen. When not rendering, the view is filled with the current erase color. The rendered composition automatically synchronizes to the vertical retrace of the monitor.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"When you archive a ","type":"text"},{"code":"QCView","type":"codeVoice"},{"text":" object, it saves the composition that’s loaded at the time the view is archived.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If you want to perform custom operations while a composition is rendering such as setting input parameters or drawing OpenGL content, you need to subclass "},{"type":"codeVoice","code":"QCView"},{"type":"text","text":" and implement the "},{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/render(atTime:arguments:)","type":"reference","isActive":true},{"type":"text","text":" method."}],"type":"paragraph"}]}],"sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic"},"doc://com.apple.quartz/documentation/Quartz/QCView/load(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadComposition:"}],"deprecated":true,"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/load(_:)","url":"/documentation/quartz/qcview/load(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"QCComposition","preciseIdentifier":"c:objc(cs)QCComposition"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","title":"load(_:)","abstract":[{"type":"text","text":"Loads a "},{"type":"reference","identifier":"doc://com.apple.quartz/documentation/Quartz/QCComposition","isActive":true},{"type":"text","text":" object into the view."}]},"doc://com.apple.quartz/documentation/Quartz/QCViewDidStopRenderingNotification":{"fragments":[{"text":"QCViewDidStopRenderingNotification","kind":"identifier"}],"kind":"symbol","type":"topic","title":"QCViewDidStopRenderingNotification","role":"symbol","abstract":[{"type":"text","text":"Posted when the view stops rendering."}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCViewDidStopRenderingNotification","url":"/documentation/quartz/qcviewdidstoprenderingnotification"},"doc://com.apple.quartz/documentation/Quartz/QCPlugIn":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"QCPlugIn","kind":"identifier"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCPlugIn","role":"symbol","navigatorTitle":[{"text":"QCPlugIn","kind":"identifier"}],"type":"topic","deprecated":true,"title":"QCPlugIn","url":"/documentation/quartz/qcplugin","abstract":[{"text":"A base class to subclass for writing custom patches.","type":"text"}]},"doc://com.apple.quartz/documentation/Quartz/QCView/openGLPixelFormat()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openGLPixelFormat","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSOpenGLPixelFormat","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOpenGLPixelFormat"},{"text":"!","kind":"text"}],"url":"/documentation/quartz/qcview/openglpixelformat()","deprecated":true,"role":"symbol","title":"openGLPixelFormat()","navigatorTitle":[{"text":"openGLPixelFormat","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/openGLPixelFormat()","abstract":[{"type":"text","text":"Returns the OpenGL pixel format used by the view."}]},"doc://com.apple.quartz/documentation/Quartz":{"identifier":"doc://com.apple.quartz/documentation/Quartz","kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Allow users to browse, edit, and save images, using slideshows and Core Image filters."}],"title":"Quartz","url":"/documentation/quartz"},"doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding","title":"NSStandardKeyBindingResponding","url":"/documentation/AppKit/NSStandardKeyBindingResponding","fragments":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}]},"doc://com.apple.quartz/documentation/Quartz/QCView/pauseRendering()":{"abstract":[{"type":"text","text":"Pauses rendering in the view."}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/pauseRendering()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseRendering"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"pauseRendering"}],"role":"symbol","kind":"symbol","title":"pauseRendering()","deprecated":true,"type":"topic","url":"/documentation/quartz/qcview/pauserendering()"},"doc://com.apple.quartz/documentation/Quartz/QCRenderer":{"deprecated":true,"abstract":[{"type":"text","text":"A base class for low-level rendering."}],"kind":"symbol","type":"topic","role":"symbol","title":"QCRenderer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QCRenderer","kind":"identifier"}],"url":"/documentation/quartz/qcrenderer","navigatorTitle":[{"text":"QCRenderer","kind":"identifier"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCRenderer"},"doc://com.apple.quartz/documentation/Quartz/QCView/maxRenderingFrameRate()":{"navigatorTitle":[{"text":"maxRenderingFrameRate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"maxRenderingFrameRate","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"deprecated":true,"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/maxRenderingFrameRate()","abstract":[{"type":"text","text":"Returns the maximum frame rate for rendering."}],"type":"topic","kind":"symbol","title":"maxRenderingFrameRate()","url":"/documentation/quartz/qcview/maxrenderingframerate()","role":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/render(atTime:arguments:)":{"url":"/documentation/quartz/qcview/render(attime:arguments:)","type":"topic","identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/render(atTime:arguments:)","navigatorTitle":[{"text":"renderAtTime:arguments:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arguments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Overrides to perform  your custom operations prior to or after rendering a frame of a composition."}],"deprecated":true,"title":"render(atTime:arguments:)"},"doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerPanel":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"QCCompositionPickerPanel"},{"type":"text","text":" class represents a utility window that allows users to browse compositions that are in the Quartz Composer composition repository and, if supported, preview the composition. The "},{"type":"codeVoice","code":"QCCompositionPickerPanel"},{"type":"text","text":" class cannot be subclassed."}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerPanel","role":"symbol","title":"QCCompositionPickerPanel","navigatorTitle":[{"text":"QCCompositionPickerPanel","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"QCCompositionPickerPanel","kind":"identifier"}],"deprecated":true,"url":"/documentation/quartz/qccompositionpickerpanel","type":"topic","kind":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/resumeRendering()":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/resumeRendering()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resumeRendering","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"resumeRendering","kind":"identifier"}],"deprecated":true,"title":"resumeRendering()","kind":"symbol","abstract":[{"text":"Resumes rendering a paused composition.","type":"text"}],"url":"/documentation/quartz/qcview/resumerendering()","role":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/loadedComposition()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadedComposition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"QCComposition","preciseIdentifier":"c:objc(cs)QCComposition"},{"kind":"text","text":"!"}],"url":"/documentation/quartz/qcview/loadedcomposition()","abstract":[{"text":"Returns the composition loaded in the view.","type":"text"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/loadedComposition()","title":"loadedComposition()","deprecated":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadedComposition"}]},"doc://com.apple.quartz/documentation/Quartz/QCView/eraseColor()":{"url":"/documentation/quartz/qcview/erasecolor()","kind":"symbol","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eraseColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSColor"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"eraseColor"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/eraseColor()","role":"symbol","type":"topic","title":"eraseColor()","abstract":[{"type":"text","text":"Retrieves the current color used to erase the view."}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSDraggingDestination":{"type":"topic","abstract":[{"text":"A set of methods that the destination object (or recipient) of a dragged image must implement.","type":"text"}],"role":"symbol","title":"NSDraggingDestination","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSDraggingDestination","kind":"symbol","url":"/documentation/AppKit/NSDraggingDestination","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDraggingDestination","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification":{"url":"/documentation/AppKit/NSUserInterfaceItemIdentification","kind":"symbol","abstract":[{"text":"A set of methods used to associate a unique identifier with objects in your user interface.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSUserInterfaceItemIdentification","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification"},"doc://com.apple.quartz/documentation/Quartz/QCView/stop(_:)":{"abstract":[{"text":"Stops rendering a composition in a view.","type":"text"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/stop(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"stop:","kind":"identifier"}],"role":"symbol","type":"topic","title":"stop(_:)","kind":"symbol","url":"/documentation/quartz/qcview/stop(_:)"},"doc://com.apple.quartz/documentation/Quartz/QCView/setEraseColor(_:)":{"url":"/documentation/quartz/qcview/seterasecolor(_:)","kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEraseColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSColor","text":"NSColor"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"setEraseColor:"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/setEraseColor(_:)","role":"symbol","type":"topic","title":"setEraseColor(_:)","abstract":[{"type":"text","text":"Sets the color used to erase the view."}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"title":"NSCoding","kind":"symbol","fragments":[{"kind":"text","text":"protocol "},{"text":"NSCoding","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that enables an object to be encoded and decoded for archiving and distribution."}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","url":"/documentation/foundation/nscoding","role":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/isRendering()":{"url":"/documentation/quartz/qcview/isrendering()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRendering","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/isRendering()","type":"topic","role":"symbol","title":"isRendering()","abstract":[{"type":"text","text":"Checks whether a composition is rendering in the view."}],"navigatorTitle":[{"text":"isRendering","kind":"identifier"}],"deprecated":true},"doc://com.apple.quartz/documentation/Quartz/QCCompositionParameterView":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCCompositionParameterView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"QCCompositionParameterView","kind":"identifier"}],"url":"/documentation/quartz/qccompositionparameterview","abstract":[{"type":"text","text":"A class that allows users to edit the input parameters of a composition in real time. The composition can be rendering in any of the following objects: "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.quartz/documentation/Quartz/QCRenderer"},{"type":"text","text":", "},{"isActive":true,"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView","type":"reference"},{"text":", or ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer","type":"reference"},{"text":".","type":"text"}],"title":"QCCompositionParameterView","deprecated":true,"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"QCCompositionParameterView","kind":"identifier"}]},"doc://com.apple.quartz/documentation/Quartz/QCViewDidStartRenderingNotification":{"fragments":[{"text":"QCViewDidStartRenderingNotification","kind":"identifier"}],"kind":"symbol","type":"topic","title":"QCViewDidStartRenderingNotification","role":"symbol","abstract":[{"type":"text","text":"Posted when the view starts rendering."}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCViewDidStartRenderingNotification","url":"/documentation/quartz/qcviewdidstartrenderingnotification"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","title":"NSObjectProtocol","url":"/documentation/objectivec/nsobjectprotocol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSObjectProtocol"}],"kind":"symbol","abstract":[{"type":"text","text":"The group of methods that are fundamental to all Objective-C objects."}]},"doc://com.apple.quartz/documentation/Quartz/QCView/setEventForwardingMask(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setEventForwardingMask","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","deprecated":true,"type":"topic","title":"setEventForwardingMask(_:)","navigatorTitle":[{"text":"setEventForwardingMask:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Sets the mask used to filter which types of events are forwarded from the view to the composition during rendering."}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/setEventForwardingMask(_:)","url":"/documentation/quartz/qcview/seteventforwardingmask(_:)"},"doc://com.externally.resolved.symbol/c:objc(cs)NSView":{"kind":"symbol","title":"NSView","fragments":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSView","kind":"identifier"}],"url":"/documentation/AppKit/NSView","type":"topic","abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSView"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"type":"topic","title":"Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","url":"/documentation/Swift/Sendable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/start(_:)":{"abstract":[{"text":"Starts rendering a composition in a view.","type":"text"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/start(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"start:"}],"role":"symbol","type":"topic","title":"start(_:)","kind":"symbol","url":"/documentation/quartz/qcview/start(_:)"},"doc://com.apple.quartz/documentation/Quartz/QCView/unloadComposition()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unloadComposition"}],"deprecated":true,"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/unloadComposition()","url":"/documentation/quartz/qcview/unloadcomposition()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unloadComposition"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","title":"unloadComposition()","abstract":[{"type":"text","text":"Unloads the composition from the view."}]},"doc://com.apple.quartz/documentation/Quartz/QCComposition":{"navigatorTitle":[{"text":"QCComposition","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QCComposition","kind":"identifier"}],"deprecated":true,"kind":"symbol","type":"topic","url":"/documentation/quartz/qccomposition","title":"QCComposition","abstract":[{"text":"The ","type":"text"},{"code":"QCComposition","type":"codeVoice"},{"text":" class represents a Quartz Composer composition that either:","type":"text"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCComposition","role":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/startRendering()":{"abstract":[{"text":"Starts rendering the composition that is in the view.","type":"text"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/startRendering()","title":"startRendering()","type":"topic","url":"/documentation/quartz/qcview/startrendering()","role":"symbol","kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"startRendering","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRendering","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization":{"type":"topic","abstract":[{"type":"text","text":"A set of methods for getting and setting the appearance attributes of a view."}],"role":"symbol","title":"NSAppearanceCustomization","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization","kind":"symbol","url":"/documentation/AppKit/NSAppearanceCustomization","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAppearanceCustomization","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}]},"doc://com.apple.quartz/documentation/Quartz/QCView/erase()":{"navigatorTitle":[{"text":"erase","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"erase","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","kind":"symbol","deprecated":true,"url":"/documentation/quartz/qcview/erase()","identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/erase()","title":"erase()","abstract":[{"text":"Clears the view using the current erase color.","type":"text"}]},"doc://com.apple.quartz/documentation/Quartz/QCView/setMaxRenderingFrameRate(_:)":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/setMaxRenderingFrameRate(_:)","type":"topic","title":"setMaxRenderingFrameRate(_:)","kind":"symbol","url":"/documentation/quartz/qcview/setmaxrenderingframerate(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setMaxRenderingFrameRate","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Sets the maximum rendering frame rate."}],"deprecated":true,"navigatorTitle":[{"text":"setMaxRenderingFrameRate:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement","url":"/documentation/AppKit/NSAccessibilityElementProtocol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary to interact with an assistive app."}],"title":"NSAccessibilityElementProtocol","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityElementProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}]},"doc://com.apple.quartz/documentation/Quartz/QCView/stopRendering()":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/stopRendering()","title":"stopRendering()","url":"/documentation/quartz/qcview/stoprendering()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopRendering"},{"kind":"text","text":"()"}],"deprecated":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopRendering"}],"type":"topic","abstract":[{"type":"text","text":"Stops rendering the composition that is in the view."}]},"doc://com.apple.quartz/documentation/Quartz/QCView":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"QCView"},{"type":"text","text":" class is a custom "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":" class that loads, plays, and controls Quartz Composer compositions. It is an autonomous view that is driven by an internal timer running on the main thread."}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QCView"}],"navigatorTitle":[{"kind":"identifier","text":"QCView"}],"role":"symbol","kind":"symbol","title":"QCView","deprecated":true,"type":"topic","url":"/documentation/quartz/qcview"},"doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer":{"url":"/documentation/AppKit/NSAnimatablePropertyContainer","abstract":[{"type":"text","text":"A set of methods that defines a way to add animation to an existing class with a minimum of API impact."}],"title":"NSAnimatablePropertyContainer","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAnimatablePropertyContainer","kind":"identifier"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer"},"doc://com.apple.quartz/documentation/Quartz/QCView/loadComposition(fromFile:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadComposition","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromFile"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"/documentation/quartz/qcview/loadcomposition(fromfile:)","abstract":[{"text":"Loads the composition file located at the specified path.","type":"text"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/loadComposition(fromFile:)","title":"loadComposition(fromFile:)","deprecated":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"loadCompositionFromFile:","kind":"identifier"}]},"doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer":{"url":"/documentation/quartz/qccompositionrenderer","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QCCompositionRenderer","kind":"identifier"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer","type":"topic","role":"symbol","title":"QCCompositionRenderer","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"QCRenderer"},{"type":"text","text":" protocol defines the methods used to pass data to the input ports or retrieve data from the output ports of the root patch of a Quartz Composer composition. This protocol is adopted by the "},{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCRenderer","type":"reference","isActive":true},{"type":"text","text":", "},{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView","type":"reference","isActive":true},{"type":"text","text":", and "},{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer","type":"reference","isActive":true},{"type":"text","text":" classes."}],"navigatorTitle":[{"text":"QCCompositionRenderer","kind":"identifier"}],"deprecated":true},"doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that marks classes to restore the state of your app to continue a user activity."}],"title":"NSUserActivityRestoring","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserActivityRestoring"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"url":"/documentation/AppKit/NSUserActivityRestoring"},"doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView":{"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"QCCompositionPickerView"},{"text":" class allows users to browse compositions that are in the Quartz Composer composition repository, and to preview them. You can set the default input parameters for a composition preview  by using the method setDefaultValue:forInputKey:.","type":"text"}],"deprecated":true,"type":"topic","title":"QCCompositionPickerView","navigatorTitle":[{"text":"QCCompositionPickerView","kind":"identifier"}],"role":"symbol","url":"/documentation/quartz/qccompositionpickerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QCCompositionPickerView","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView"},"doc://com.apple.quartz/documentation/Quartz/QCCompositionRepository":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCCompositionRepository","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QCCompositionRepository"}],"url":"/documentation/quartz/qccompositionrepository","abstract":[{"text":"The ","type":"text"},{"code":"QCCompositionRepository","type":"codeVoice"},{"text":" class represents a system-wide centralized repository of built-in and installed Quartz Composer compositions (","type":"text"},{"code":"/Library/Compositions","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"~/Library/Compositions"},{"type":"text","text":"). The "},{"type":"codeVoice","code":"QCCompositionRepository"},{"text":" class cannot be subclassed.","type":"text"}],"title":"QCCompositionRepository","deprecated":true,"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"QCCompositionRepository"}]},"doc://com.apple.quartz/documentation/Quartz/QCPatchController":{"role":"symbol","deprecated":true,"title":"QCPatchController","abstract":[],"type":"topic","identifier":"doc://com.apple.quartz/documentation/Quartz/QCPatchController","navigatorTitle":[{"kind":"identifier","text":"QCPatchController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QCPatchController"}],"kind":"symbol","url":"/documentation/quartz/qcpatchcontroller"},"doc://com.apple.quartz/documentation/Quartz/QCView/play(_:)":{"abstract":[{"text":"Plays or pauses a composition in a view.","type":"text"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/play(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"play:","kind":"identifier"}],"role":"symbol","type":"topic","title":"play(_:)","kind":"symbol","url":"/documentation/quartz/qcview/play(_:)"},"doc://com.apple.quartz/documentation/Quartz/QCView/snapshotImage()":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/snapshotImage()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"snapshotImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"snapshotImage","kind":"identifier"}],"type":"topic","url":"/documentation/quartz/qcview/snapshotimage()","deprecated":true,"title":"snapshotImage()","kind":"symbol","abstract":[{"type":"text","text":"Returns an "},{"code":"NSImage","type":"codeVoice"},{"type":"text","text":" object of the current image in the view."}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility":{"type":"topic","title":"NSAccessibilityProtocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility","url":"/documentation/AppKit/NSAccessibilityProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"abstract":[{"type":"text","text":"The complete list of properties and methods for accessible elements."}],"kind":"symbol","role":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCPlugInViewController":{"deprecated":true,"abstract":[{"type":"text","text":"The "},{"code":"QCPlugInViewController","type":"codeVoice"},{"text":" class communicates (through Cocoa bindings) between a custom patch and the view used for the internal settings of the custom patch. Only custom patches that use internal settings exposed to the user need to use the ","type":"text"},{"type":"codeVoice","code":"QCPlugInViewController"},{"text":" class.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QCPlugInViewController","kind":"identifier"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCPlugInViewController","kind":"symbol","type":"topic","title":"QCPlugInViewController","url":"/documentation/quartz/qcpluginviewcontroller","role":"symbol","navigatorTitle":[{"text":"QCPlugInViewController","kind":"identifier"}]},"doc://com.apple.quartz/documentation/Quartz/QCView/openGLContext()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openGLContext","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSOpenGLContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOpenGLContext"},{"text":"!","kind":"text"}],"url":"/documentation/quartz/qcview/openglcontext()","deprecated":true,"role":"symbol","title":"openGLContext()","navigatorTitle":[{"text":"openGLContext","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/openGLContext()","abstract":[{"type":"text","text":"Returns the OpenGL context used by the view."}]},"doc://com.apple.quartz/documentation/Quartz/QCView/autostartsRendering()":{"url":"/documentation/quartz/qcview/autostartsrendering()","role":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"autostartsRendering"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","abstract":[{"type":"text","text":"Checks whether the view is set to start rendering automatically."}],"type":"topic","title":"autostartsRendering()","identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/autostartsRendering()","navigatorTitle":[{"kind":"identifier","text":"autostartsRendering"}]},"doc://com.externally.resolved.symbol/s:ScM":{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"url":"/documentation/Swift/MainActor"},"doc://com.externally.resolved.symbol/s:SQ":{"type":"topic","abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"role":"symbol","title":"Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}]},"doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer":{"deprecated":true,"url":"/documentation/quartz/qccompositionlayer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QCCompositionLayer","kind":"identifier"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer","title":"QCCompositionLayer","type":"topic","navigatorTitle":[{"text":"QCCompositionLayer","kind":"identifier"}],"abstract":[{"type":"text","text":"A layer that loads, plays, and controls Quartz Composer compositions in a Core Animation layer hierarchy."}],"kind":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/createSnapshotImage(ofType:)":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/createSnapshotImage(ofType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createSnapshotImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ofType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"createSnapshotImageOfType:"}],"type":"topic","url":"/documentation/quartz/qcview/createsnapshotimage(oftype:)","deprecated":true,"title":"createSnapshotImage(ofType:)","kind":"symbol","abstract":[{"type":"text","text":"Returns the current image in the view as an image object of the provided image type."}],"role":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/eventForwardingMask()":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/eventForwardingMask()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"eventForwardingMask","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"eventForwardingMask","kind":"identifier"}],"type":"topic","url":"/documentation/quartz/qcview/eventforwardingmask()","deprecated":true,"title":"eventForwardingMask()","kind":"symbol","abstract":[{"type":"text","text":"Retrieves the mask used to filter which types of events are forwarded from the view to the composition during rendering."}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}]},"doc://com.apple.quartz/documentation/Quartz/QCView/setAutostartsRendering(_:)":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/setAutostartsRendering(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAutostartsRendering"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAutostartsRendering:"}],"deprecated":true,"title":"setAutostartsRendering(_:)","kind":"symbol","abstract":[{"text":"Sets whether the composition that is in the view starts rendering automatically when the view is put on the screen.","type":"text"}],"url":"/documentation/quartz/qcview/setautostartsrendering(_:)","role":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"identifier":"doc://com.externally.resolved.symbol/s:SH","title":"Hashable","url":"/documentation/Swift/Hashable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","kind":"typeIdentifier","preciseIdentifier":"s:SQ"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider","url":"/documentation/AppKit/NSTouchBarProvider","abstract":[{"type":"text","text":"A protocol that an object adopts to create a bar object in your app."}],"title":"NSTouchBarProvider","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTouchBarProvider","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomStringConvertible"}],"kind":"symbol","abstract":[{"type":"text","text":"A type with a customized textual representation."}]},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","kind":"symbol","type":"topic","title":"CVarArg","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP"},"doc://com.apple.quartz/documentation/Quartz/QCView/isPausedRendering()":{"url":"/documentation/quartz/qcview/ispausedrendering()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPausedRendering"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/isPausedRendering()","type":"topic","role":"symbol","title":"isPausedRendering()","abstract":[{"type":"text","text":"Returns whether or not the rendering in the view is paused."}],"navigatorTitle":[{"kind":"identifier","text":"isPausedRendering"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecatedAt":"10.15","introducedAt":"10.4","deprecated":false,"name":"macOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Class"},{"op":"replace","path":"/metadata/title","value":"QCView"},{"op":"replace","path":"/metadata/symbolKind","value":"class"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"QCView"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"QCView"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz"]]}},{"op":"replace","path":"/topicSections","value":[{"anchor":"Performing-Custom-Operations-During-Rendering","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/render(atTime:arguments:)"],"title":"Performing Custom Operations During Rendering"},{"anchor":"Loading-a-Composition","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/loadComposition(fromFile:)","doc://com.apple.quartz/documentation/Quartz/QCView/load(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/loadedComposition()","doc://com.apple.quartz/documentation/Quartz/QCView/unloadComposition()"],"title":"Loading a Composition"},{"anchor":"Managing-the-Erase-Color","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/erase()","doc://com.apple.quartz/documentation/Quartz/QCView/eraseColor()","doc://com.apple.quartz/documentation/Quartz/QCView/setEraseColor(_:)"],"title":"Managing the Erase Color"},{"anchor":"Setting-and-Getting-Event-Masks","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/eventForwardingMask()","doc://com.apple.quartz/documentation/Quartz/QCView/setEventForwardingMask(_:)"],"title":"Setting and Getting Event Masks"},{"anchor":"Setting-and-Getting-the-Maximum-Frame-Rate","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/maxRenderingFrameRate()","doc://com.apple.quartz/documentation/Quartz/QCView/setMaxRenderingFrameRate(_:)"],"title":"Setting and Getting the Maximum Frame Rate"},{"anchor":"Managing-Rendering","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/startRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/isRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/autostartsRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/setAutostartsRendering(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/stopRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/pauseRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/isPausedRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/resumeRendering()"],"title":"Managing Rendering"},{"anchor":"Using-Interface-Builder","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/play(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/start(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/stop(_:)"],"title":"Using Interface Builder"},{"anchor":"Taking-Snapshot-Images","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/snapshotImage()","doc://com.apple.quartz/documentation/Quartz/QCView/createSnapshotImage(ofType:)"],"title":"Taking Snapshot Images"},{"anchor":"Working-With-OpenGL","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/openGLContext()","doc://com.apple.quartz/documentation/Quartz/QCView/openGLPixelFormat()"],"title":"Working With OpenGL"},{"anchor":"Notifications","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCViewDidStartRenderingNotification","doc://com.apple.quartz/documentation/Quartz/QCViewDidStopRenderingNotification"],"title":"Notifications"}]},{"op":"replace","path":"/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSView"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer"]}]},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCComposition","doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer","doc://com.apple.quartz/documentation/Quartz/QCCompositionParameterView","doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerPanel","doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView","doc://com.apple.quartz/documentation/Quartz/QCCompositionRepository","doc://com.apple.quartz/documentation/Quartz/QCPatchController","doc://com.apple.quartz/documentation/Quartz/QCPlugIn","doc://com.apple.quartz/documentation/Quartz/QCPlugInViewController","doc://com.apple.quartz/documentation/Quartz/QCRenderer"],"title":"Classes","generated":true,"anchor":"Classes"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QCView","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSView","preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSView"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)","type":"text"}]}]},{"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1load(_:)/title","value":"loadComposition:"},{"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1load(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadComposition:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn/title","value":"QCPlugIn"},{"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn/fragments","value":[{"text":"QCPlugIn","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn/navigatorTitle","value":[{"text":"QCPlugIn","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1openGLPixelFormat()/title","value":"openGLPixelFormat"},{"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1openGLPixelFormat()/fragments","value":[{"text":"- ","kind":"text"},{"text":"openGLPixelFormat","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSStandardKeyBindingResponding/fragments","value":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1pauseRendering()/title","value":"pauseRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1pauseRendering()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pauseRendering"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/title","value":"QCRenderer","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/fragments","value":[{"kind":"identifier","text":"QCRenderer"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/navigatorTitle","value":[{"text":"QCRenderer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1maxRenderingFrameRate()/title","value":"maxRenderingFrameRate","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1maxRenderingFrameRate()/fragments","value":[{"text":"- ","kind":"text"},{"text":"maxRenderingFrameRate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1render(atTime:arguments:)/title","value":"renderAtTime:arguments:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1render(atTime:arguments:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renderAtTime:arguments:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerPanel/title","value":"QCCompositionPickerPanel","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerPanel/fragments","value":[{"text":"QCCompositionPickerPanel","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerPanel/navigatorTitle","value":[{"kind":"identifier","text":"QCCompositionPickerPanel"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1resumeRendering()/title","value":"resumeRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1resumeRendering()/fragments","value":[{"text":"- ","kind":"text"},{"text":"resumeRendering","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1loadedComposition()/title","value":"loadedComposition","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1loadedComposition()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadedComposition"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1eraseColor()/title","value":"eraseColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1eraseColor()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eraseColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSDraggingDestination/fragments","value":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDraggingDestination"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserInterfaceItemIdentification/fragments","value":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1stop(_:)/title","value":"stop:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1stop(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"stop:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setEraseColor(_:)/title","value":"setEraseColor:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setEraseColor(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEraseColor:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1isRendering()/title","value":"isRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1isRendering()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isRendering"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionParameterView/title","value":"QCCompositionParameterView","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionParameterView/fragments","value":[{"text":"QCCompositionParameterView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionParameterView/navigatorTitle","value":[{"text":"QCCompositionParameterView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setEventForwardingMask(_:)/title","value":"setEventForwardingMask:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setEventForwardingMask(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEventForwardingMask:"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSView/fragments","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSResponder","text":"NSResponder","kind":"typeIdentifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1start(_:)/title","value":"start:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1start(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"start:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1unloadComposition()/title","value":"unloadComposition","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1unloadComposition()/fragments","value":[{"text":"- ","kind":"text"},{"text":"unloadComposition","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/title","value":"QCComposition","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/fragments","value":[{"kind":"identifier","text":"QCComposition"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/navigatorTitle","value":[{"kind":"identifier","text":"QCComposition"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1startRendering()/title","value":"startRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1startRendering()/fragments","value":[{"text":"- ","kind":"text"},{"text":"startRendering","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAppearanceCustomization/fragments","value":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAppearanceCustomization","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1erase()/title","value":"erase","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1erase()/fragments","value":[{"text":"- ","kind":"text"},{"text":"erase","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setMaxRenderingFrameRate(_:)/title","value":"setMaxRenderingFrameRate:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setMaxRenderingFrameRate(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setMaxRenderingFrameRate:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibilityElement/title","value":"NSAccessibilityElement","op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibilityElement/fragments","value":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityElement","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1stopRendering()/title","value":"stopRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1stopRendering()/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopRendering","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/title","value":"QCView","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/fragments","value":[{"kind":"identifier","text":"QCView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/navigatorTitle","value":[{"kind":"identifier","text":"QCView"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAnimatablePropertyContainer/fragments","value":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAnimatablePropertyContainer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1loadComposition(fromFile:)/title","value":"loadCompositionFromFile:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1loadComposition(fromFile:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadCompositionFromFile:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer/title","value":"QCCompositionRenderer","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer/fragments","value":[{"kind":"identifier","text":"QCCompositionRenderer"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer/navigatorTitle","value":[{"kind":"identifier","text":"QCCompositionRenderer"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserActivityRestoring/fragments","value":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserActivityRestoring","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerView/title","value":"QCCompositionPickerView","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerView/fragments","value":[{"text":"QCCompositionPickerView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerView/navigatorTitle","value":[{"text":"QCCompositionPickerView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRepository/title","value":"QCCompositionRepository","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRepository/fragments","value":[{"text":"QCCompositionRepository","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRepository/navigatorTitle","value":[{"text":"QCCompositionRepository","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPatchController/title","value":"QCPatchController","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPatchController/fragments","value":[{"text":"QCPatchController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPatchController/navigatorTitle","value":[{"text":"QCPatchController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1play(_:)/title","value":"play:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1play(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"play:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1snapshotImage()/title","value":"snapshotImage","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1snapshotImage()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"snapshotImage"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibility/title","value":"NSAccessibility","op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibility/fragments","value":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibility","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInViewController/title","value":"QCPlugInViewController","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInViewController/fragments","value":[{"text":"QCPlugInViewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInViewController/navigatorTitle","value":[{"kind":"identifier","text":"QCPlugInViewController"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1openGLContext()/title","value":"openGLContext","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1openGLContext()/fragments","value":[{"text":"- ","kind":"text"},{"text":"openGLContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1autostartsRendering()/title","value":"autostartsRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1autostartsRendering()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"autostartsRendering"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionLayer/title","value":"QCCompositionLayer","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionLayer/fragments","value":[{"text":"QCCompositionLayer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionLayer/navigatorTitle","value":[{"text":"QCCompositionLayer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1createSnapshotImage(ofType:)/title","value":"createSnapshotImageOfType:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1createSnapshotImage(ofType:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"createSnapshotImageOfType:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1eventForwardingMask()/title","value":"eventForwardingMask","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1eventForwardingMask()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eventForwardingMask"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setAutostartsRendering(_:)/title","value":"setAutostartsRendering:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setAutostartsRendering(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setAutostartsRendering:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments","value":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSTouchBarProvider"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1isPausedRendering()/title","value":"isPausedRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1isPausedRendering()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPausedRendering"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}