{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/quartz-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Quartz Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInBufferReleaseCallback": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInBufferReleaseCallback"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInBufferReleaseCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInBufferReleaseCallback"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInBufferReleaseCallback",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginbufferreleasecallback"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInTextureReleaseCallback": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInTextureReleaseCallback"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInTextureReleaseCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInTextureReleaseCallback"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInTextureReleaseCallback",
      "type": "topic",
      "url": "/documentation/quartz/qcplugintexturereleasecallback"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer Constants",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer-constants"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer Enumerations",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer-enumerations"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Constants",
      "type": "topic",
      "url": "/documentation/quartz/quartz-constants"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Enumerations",
      "type": "topic",
      "url": "/documentation/quartz/quartz-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
        "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInBufferReleaseCallback",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInTextureReleaseCallback"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInBufferReleaseCallback",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInTextureReleaseCallback"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
                "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
                "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants",
                "doc://com.apple.quartz/documentation/Quartz/quartz-composer-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTextureReleaseCallback/title",
          "value": "QCPlugInTextureReleaseCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTextureReleaseCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTextureReleaseCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTextureReleaseCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTextureReleaseCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInBufferReleaseCallback/title",
          "value": "QCPlugInBufferReleaseCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInBufferReleaseCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInBufferReleaseCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInBufferReleaseCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInBufferReleaseCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/quartz-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/quartz-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
