{
  "abstract": [
    {
      "text": "Create and modify PDF documents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/pdfkit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/quartz-pdfkit"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Quartz PDFKit Symbols"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For full documentation of these symbols, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PDFKit",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/PDFKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidAddFilterNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterManagerDidAddFilterNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidAddFilterNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kQuartzFilterManagerDidAddFilterNotification",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfiltermanagerdidaddfilternotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidModifyFilterNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterManagerDidModifyFilterNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidModifyFilterNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kQuartzFilterManagerDidModifyFilterNotification",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfiltermanagerdidmodifyfilternotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidRemoveFilterNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterManagerDidRemoveFilterNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidRemoveFilterNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kQuartzFilterManagerDidRemoveFilterNotification",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfiltermanagerdidremovefilternotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidSelectFilterNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterManagerDidSelectFilterNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidSelectFilterNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kQuartzFilterManagerDidSelectFilterNotification",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfiltermanagerdidselectfilternotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/pdfkit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/pdfkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/quartz/pdfkit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Quartz-PDFKit",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidAddFilterNotification",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidModifyFilterNotification",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidRemoveFilterNotification",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidSelectFilterNotification"
              ],
              "title": "Quartz PDFKit"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/quartz-pdfkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/quartz-pdfkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
