{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/quartz-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Quartz Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeIsTimeDependentKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeIsTimeDependentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeIsTimeDependentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionAttributeIsTimeDependentKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionAttributeIsTimeDependentKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionattributeistimedependentkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeCategoriesKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInAttributeCategoriesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeCategoriesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInAttributeCategoriesKey"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInAttributeCategoriesKey",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginattributecategorieskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeCopyrightKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInAttributeCopyrightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeCopyrightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInAttributeCopyrightKey"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInAttributeCopyrightKey",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginattributecopyrightkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeExamplesKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInAttributeExamplesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeExamplesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInAttributeExamplesKey"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInAttributeExamplesKey",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginattributeexampleskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/globalUpdateOK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "globalUpdateOK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/globalUpdateOK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "globalUpdateOK"
        }
      ],
      "role": "symbol",
      "title": "globalUpdateOK",
      "type": "topic",
      "url": "/documentation/quartz/globalupdateok"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQuartzFilterApplicationDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterApplicationDomain"
        }
      ],
      "role": "symbol",
      "title": "kQuartzFilterApplicationDomain",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfilterapplicationdomain"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQuartzFilterPDFWorkflowDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterPDFWorkflowDomain"
        }
      ],
      "role": "symbol",
      "title": "kQuartzFilterPDFWorkflowDomain",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfilterpdfworkflowdomain"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQuartzFilterPrintingDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterPrintingDomain"
        }
      ],
      "role": "symbol",
      "title": "kQuartzFilterPrintingDomain",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfilterprintingdomain"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/globalUpdateOK",
        "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain",
        "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain",
        "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Deprecated-constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeIsTimeDependentKey",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeCategoriesKey",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeCopyrightKey",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeExamplesKey"
      ],
      "title": "Deprecated constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/globalUpdateOK",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated-constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionAttributeIsTimeDependentKey",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeCategoriesKey",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeCopyrightKey",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInAttributeExamplesKey"
              ],
              "title": "Deprecated constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterApplicationDomain/title",
          "value": "kQuartzFilterApplicationDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterApplicationDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQuartzFilterApplicationDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInAttributeExamplesKey/title",
          "value": "QCPlugInAttributeExamplesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInAttributeExamplesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInAttributeExamplesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInAttributeCopyrightKey/title",
          "value": "QCPlugInAttributeCopyrightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInAttributeCopyrightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInAttributeCopyrightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1globalUpdateOK/title",
          "value": "globalUpdateOK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1globalUpdateOK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "globalUpdateOK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInAttributeCategoriesKey/title",
          "value": "QCPlugInAttributeCategoriesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInAttributeCategoriesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInAttributeCategoriesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPrintingDomain/title",
          "value": "kQuartzFilterPrintingDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPrintingDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQuartzFilterPrintingDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeIsTimeDependentKey/title",
          "value": "QCCompositionAttributeIsTimeDependentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionAttributeIsTimeDependentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionAttributeIsTimeDependentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPDFWorkflowDomain/title",
          "value": "kQuartzFilterPDFWorkflowDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPDFWorkflowDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQuartzFilterPDFWorkflowDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/quartz-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/quartz-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
