{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/quartz-composer-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Quartz Composer Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode": {
      "abstract": [
        {
          "text": "Execution modes for custom patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionMode"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInExecutionMode",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginexecutionmode"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode": {
      "abstract": [
        {
          "text": "Time modes for custom patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInTimeMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInTimeMode"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInTimeMode",
      "type": "topic",
      "url": "/documentation/quartz/qcplugintimemode"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer Constants",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer-constants"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Constants",
      "type": "topic",
      "url": "/documentation/quartz/quartz-constants"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Data Types",
      "type": "topic",
      "url": "/documentation/quartz/quartz-data-types"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Enumerations",
      "type": "topic",
      "url": "/documentation/quartz/quartz-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/quartz-data-types",
        "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
        "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/quartz-data-types",
                "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
                "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
                "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionMode/title",
          "value": "QCPlugInExecutionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInExecutionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInExecutionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/title",
          "value": "QCPlugInTimeMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTimeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTimeMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/quartz-composer-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/quartz-composer-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
