{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-filter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/quartz-filter-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Quartz Filter Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQuartzFilterApplicationDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterApplicationDomain"
        }
      ],
      "role": "symbol",
      "title": "kQuartzFilterApplicationDomain",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfilterapplicationdomain"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidAddFilterNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterManagerDidAddFilterNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidAddFilterNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kQuartzFilterManagerDidAddFilterNotification",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfiltermanagerdidaddfilternotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidModifyFilterNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterManagerDidModifyFilterNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidModifyFilterNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kQuartzFilterManagerDidModifyFilterNotification",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfiltermanagerdidmodifyfilternotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidRemoveFilterNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterManagerDidRemoveFilterNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidRemoveFilterNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kQuartzFilterManagerDidRemoveFilterNotification",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfiltermanagerdidremovefilternotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidSelectFilterNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterManagerDidSelectFilterNotification"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidSelectFilterNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kQuartzFilterManagerDidSelectFilterNotification",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfiltermanagerdidselectfilternotification"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQuartzFilterPDFWorkflowDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterPDFWorkflowDomain"
        }
      ],
      "role": "symbol",
      "title": "kQuartzFilterPDFWorkflowDomain",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfilterpdfworkflowdomain"
    },
    "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQuartzFilterPrintingDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQuartzFilterPrintingDomain"
        }
      ],
      "role": "symbol",
      "title": "kQuartzFilterPrintingDomain",
      "type": "topic",
      "url": "/documentation/quartz/kquartzfilterprintingdomain"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-filter": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-filter",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Filter",
      "type": "topic",
      "url": "/documentation/quartz/quartz-filter"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain",
        "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain",
        "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterApplicationDomain",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPDFWorkflowDomain",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterPrintingDomain",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidAddFilterNotification",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidModifyFilterNotification",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidRemoveFilterNotification",
                "doc://com.apple.quartz/documentation/Quartz/kQuartzFilterManagerDidSelectFilterNotification"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPrintingDomain/title",
          "value": "kQuartzFilterPrintingDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPrintingDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQuartzFilterPrintingDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPDFWorkflowDomain/title",
          "value": "kQuartzFilterPDFWorkflowDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterPDFWorkflowDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQuartzFilterPDFWorkflowDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterApplicationDomain/title",
          "value": "kQuartzFilterApplicationDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1kQuartzFilterApplicationDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQuartzFilterApplicationDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/quartz-filter-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/quartz-filter-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
