{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/quartz-composer"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.4",
        "name": "macOS"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Quartz Composer"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCComposition": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCComposition",
          "type": "codeVoice"
        },
        {
          "text": " class represents a Quartz Composer composition that either:",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "role": "symbol",
      "title": "QCComposition",
      "type": "topic",
      "url": "/documentation/quartz/qccomposition"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer": {
      "abstract": [
        {
          "text": "A layer that loads, plays, and controls Quartz Composer compositions in a Core Animation layer hierarchy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionLayer"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionLayer"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionLayer",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionlayer"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionParameterView": {
      "abstract": [
        {
          "text": "A class that allows users to edit the input parameters of a composition in real time. The composition can be rendering in any of the following objects: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionParameterView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionParameterView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionParameterView"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionParameterView",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionparameterview"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerPanel": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCCompositionPickerPanel",
          "type": "codeVoice"
        },
        {
          "text": " class represents a utility window that allows users to browse compositions that are in the Quartz Composer composition repository and, if supported, preview the composition. The ",
          "type": "text"
        },
        {
          "code": "QCCompositionPickerPanel",
          "type": "codeVoice"
        },
        {
          "text": " class cannot be subclassed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionPickerPanel"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionPickerPanel"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionPickerPanel",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionpickerpanel"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCCompositionPickerView",
          "type": "codeVoice"
        },
        {
          "text": " class allows users to browse compositions that are in the Quartz Composer composition repository, and to preview them. You can set the default input parameters for a composition preview  by using the method setDefaultValue:forInputKey:.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionPickerView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionPickerView"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionPickerView",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionpickerview"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCRenderer",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines the methods used to pass data to the input ports or retrieve data from the output ports of the root patch of a Quartz Composer composition. This protocol is adopted by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " classes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionRenderer"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionRenderer"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionRenderer",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrenderer"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionRepository": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCCompositionRepository",
          "type": "codeVoice"
        },
        {
          "text": " class represents a system-wide centralized repository of built-in and installed Quartz Composer compositions (",
          "type": "text"
        },
        {
          "code": "/Library/Compositions",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "~/Library/Compositions",
          "type": "codeVoice"
        },
        {
          "text": "). The ",
          "type": "text"
        },
        {
          "code": "QCCompositionRepository",
          "type": "codeVoice"
        },
        {
          "text": " class cannot be subclassed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionRepository"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionRepository",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionRepository"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionRepository",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionrepository"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPatchController": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPatchController"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPatchController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPatchController"
        }
      ],
      "role": "symbol",
      "title": "QCPatchController",
      "type": "topic",
      "url": "/documentation/quartz/qcpatchcontroller"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugIn": {
      "abstract": [
        {
          "text": "A base class to subclass for writing custom patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugIn"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugIn"
        }
      ],
      "role": "symbol",
      "title": "QCPlugIn",
      "type": "topic",
      "url": "/documentation/quartz/qcplugin"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugIn/execute(_:atTime:withArguments:)": {
      "abstract": [
        {
          "text": "Performs the processing or rendering tasks appropriate for the custom patch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QCPlugInContext",
          "text": "QCPlugInContext"
        },
        {
          "kind": "text",
          "text": ")!, "
        },
        {
          "kind": "externalParam",
          "text": "atTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withArguments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugIn/execute(_:atTime:withArguments:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "execute:atTime:withArguments:"
        }
      ],
      "role": "symbol",
      "title": "execute(_:atTime:withArguments:)",
      "type": "topic",
      "url": "/documentation/quartz/qcplugin/execute(_:attime:witharguments:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInContext": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCPlugInContext",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines methods that you use only from within the execution method (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugIn/execute(_:atTime:withArguments:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ") of a ",
          "type": "text"
        },
        {
          "code": "QCPlugIn",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInContext"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInContext"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInContext",
      "type": "topic",
      "url": "/documentation/quartz/qcplugincontext"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode": {
      "abstract": [
        {
          "text": "Execution modes for custom patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInExecutionMode"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInExecutionMode",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginexecutionmode"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInInputImageSource": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCPlugInInputImageSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol eliminates the need to use explicit image types for the image input ports on your custom patch. Not only does using the protocol avoid restrictions of a specific image type, but it avoids impedance mismatches, and provides better performance by deferring pixel computation until it is needed. When you need to access the pixels in an image, you simply convert the image to a representation (texture or buffer) using one of the methods defined by the ",
          "type": "text"
        },
        {
          "code": "QCPlugInInputImageSource",
          "type": "codeVoice"
        },
        {
          "text": " protocol. Use a texture representation when you want to use input images on the GPU. Use a buffer representation when you want to use input images on the CPU.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInInputImageSource"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInInputImageSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInInputImageSource"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInInputImageSource",
      "type": "topic",
      "url": "/documentation/quartz/qcplugininputimagesource"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInOutputImageProvider": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCPlugInOuputImageProvider",
          "type": "codeVoice"
        },
        {
          "text": " protocol eliminates the need to use explicit image types for the image output ports on a custom patch. The methods in this protocol are called by the Quartz Composer engine when the output image is needed. If your custom patch has an image output port, you need to implement the appropriate methods for rendering image data and to supply information about the rendering destination and the image bounds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInOutputImageProvider"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInOutputImageProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInOutputImageProvider"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInOutputImageProvider",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginoutputimageprovider"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode": {
      "abstract": [
        {
          "text": "Time modes for custom patches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInTimeMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInTimeMode"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInTimeMode",
      "type": "topic",
      "url": "/documentation/quartz/qcplugintimemode"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCPlugInViewController": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCPlugInViewController",
          "type": "codeVoice"
        },
        {
          "text": " class communicates (through Cocoa bindings) between a custom patch and the view used for the internal settings of the custom patch. Only custom patches that use internal settings exposed to the user need to use the ",
          "type": "text"
        },
        {
          "code": "QCPlugInViewController",
          "type": "codeVoice"
        },
        {
          "text": " class.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCPlugInViewController"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCPlugInViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCPlugInViewController"
        }
      ],
      "role": "symbol",
      "title": "QCPlugInViewController",
      "type": "topic",
      "url": "/documentation/quartz/qcpluginviewcontroller"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCRenderer": {
      "abstract": [
        {
          "text": "A base class for low-level rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCRenderer"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCRenderer"
        }
      ],
      "role": "symbol",
      "title": "QCRenderer",
      "type": "topic",
      "url": "/documentation/quartz/qcrenderer"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCView",
          "type": "codeVoice"
        },
        {
          "text": " class is a custom ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": " class that loads, plays, and controls Quartz Composer compositions. It is an autonomous view that is driven by an internal timer running on the main thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCView"
        }
      ],
      "role": "symbol",
      "title": "QCView",
      "type": "topic",
      "url": "/documentation/quartz/qcview"
    },
    "doc://com.apple.quartz/documentation/Quartz/qccompositionparameterviewdelegate": {
      "abstract": [
        {
          "text": "A protocol for composition parameter view’s delegate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/qccompositionparameterviewdelegate",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QCCompositionParameterViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionparameterviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/qccompositionpickerviewdelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCCompositionPickerViewDelegate",
          "type": "codeVoice"
        },
        {
          "text": " informal protocol defines methods that allow  your application to respond to changes in a composition picker view (a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/qccompositionpickerviewdelegate",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QCCompositionPickerViewDelegate",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionpickerviewdelegate"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer Constants",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer-constants"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer Enumerations",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer-enumerations"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Constants",
      "type": "topic",
      "url": "/documentation/quartz/quartz-constants"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Data Types",
      "type": "topic",
      "url": "/documentation/quartz/quartz-data-types"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Enumerations",
      "type": "topic",
      "url": "/documentation/quartz/quartz-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCComposition",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionParameterView",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerPanel",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRepository",
        "doc://com.apple.quartz/documentation/Quartz/QCPatchController",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugIn",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInViewController",
        "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
        "doc://com.apple.quartz/documentation/Quartz/QCView"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/qccompositionparameterviewdelegate",
        "doc://com.apple.quartz/documentation/Quartz/qccompositionpickerviewdelegate",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInContext",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInInputImageSource",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInOutputImageProvider"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode",
        "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/quartz-data-types",
        "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
        "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCComposition",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionLayer",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionParameterView",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerPanel",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionPickerView",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRepository",
                "doc://com.apple.quartz/documentation/Quartz/QCPatchController",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugIn",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInViewController",
                "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
                "doc://com.apple.quartz/documentation/Quartz/QCView"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Protocols",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/qccompositionparameterviewdelegate",
                "doc://com.apple.quartz/documentation/Quartz/qccompositionpickerviewdelegate",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionRenderer",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInContext",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInInputImageSource",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInOutputImageProvider"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInExecutionMode",
                "doc://com.apple.quartz/documentation/Quartz/QCPlugInTimeMode"
              ],
              "title": "Structures"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/quartz-data-types",
                "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
                "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations",
                "doc://com.apple.quartz/documentation/Quartz/quartz-composer-constants",
                "doc://com.apple.quartz/documentation/Quartz/quartz-composer-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRepository/title",
          "value": "QCCompositionRepository"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRepository/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionRepository"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRepository/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionRepository"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionParameterView/title",
          "value": "QCCompositionParameterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionParameterView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionParameterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionParameterView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionParameterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionLayer/title",
          "value": "QCCompositionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInViewController/title",
          "value": "QCPlugInViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn/title",
          "value": "QCPlugIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionMode/title",
          "value": "QCPlugInExecutionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInExecutionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInExecutionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInExecutionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInOutputImageProvider/title",
          "value": "QCPlugInOutputImageProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInOutputImageProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInOutputImageProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInOutputImageProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInOutputImageProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPatchController/title",
          "value": "QCPatchController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPatchController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPatchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPatchController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPatchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer/title",
          "value": "QCCompositionRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/title",
          "value": "QCPlugInTimeMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTimeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInTimeMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInTimeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInContext/title",
          "value": "QCPlugInContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerPanel/title",
          "value": "QCCompositionPickerPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionPickerPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionPickerPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn~1execute(_:atTime:withArguments:)/title",
          "value": "execute:atTime:withArguments:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugIn~1execute(_:atTime:withArguments:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "execute:atTime:withArguments:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/title",
          "value": "QCRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/title",
          "value": "QCView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInInputImageSource/title",
          "value": "QCPlugInInputImageSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInInputImageSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInInputImageSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCPlugInInputImageSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCPlugInInputImageSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/title",
          "value": "QCComposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerView/title",
          "value": "QCCompositionPickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionPickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionPickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionPickerView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/quartz-composer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/quartz-composer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
