{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/quartz-filter"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Quartz Filter"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QuartzFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QuartzFilter"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QuartzFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QuartzFilter"
        }
      ],
      "role": "symbol",
      "title": "QuartzFilter",
      "type": "topic",
      "url": "/documentation/quartz/quartzfilter"
    },
    "doc://com.apple.quartz/documentation/Quartz/QuartzFilterManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QuartzFilterManager"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QuartzFilterManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QuartzFilterManager"
        }
      ],
      "role": "symbol",
      "title": "QuartzFilterManager",
      "type": "topic",
      "url": "/documentation/quartz/quartzfiltermanager"
    },
    "doc://com.apple.quartz/documentation/Quartz/QuartzFilterView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QuartzFilterView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QuartzFilterView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QuartzFilterView"
        }
      ],
      "role": "symbol",
      "title": "QuartzFilterView",
      "type": "topic",
      "url": "/documentation/quartz/quartzfilterview"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-filter-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-filter-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Filter Constants",
      "type": "topic",
      "url": "/documentation/quartz/quartz-filter-constants"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QuartzFilter",
        "doc://com.apple.quartz/documentation/Quartz/QuartzFilterManager",
        "doc://com.apple.quartz/documentation/Quartz/QuartzFilterView"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/quartz-filter-constants"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QuartzFilter",
                "doc://com.apple.quartz/documentation/Quartz/QuartzFilterManager",
                "doc://com.apple.quartz/documentation/Quartz/QuartzFilterView"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/quartz-filter-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QuartzFilterView/title",
          "value": "QuartzFilterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QuartzFilterView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QuartzFilterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QuartzFilterView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QuartzFilterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QuartzFilter/title",
          "value": "QuartzFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QuartzFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QuartzFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QuartzFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QuartzFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QuartzFilterManager/title",
          "value": "QuartzFilterManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QuartzFilterManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QuartzFilterManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QuartzFilterManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QuartzFilterManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/quartz-filter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/quartz-filter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
