{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/imagekit"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/quartz-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Quartz Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes": {
      "abstract": [
        {
          "text": "Attributes for the group style. Used by the",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Group Style Attributes",
      "type": "topic",
      "url": "/documentation/quartz/1564247-group-style-attributes"
    },
    "doc://com.apple.quartz/documentation/Quartz/1564248-cell-appearance-style-masks": {
      "abstract": [
        {
          "text": "Masks for the appearance style bit field.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/1564248-cell-appearance-style-masks",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell Appearance Style Masks",
      "type": "topic",
      "url": "/documentation/quartz/1564248-cell-appearance-style-masks"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView/mode": {
      "abstract": [
        {
          "text": "Specifies the display mode of the camera device view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IKCameraDeviceViewDisplayMode",
          "text": "IKCameraDeviceViewDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView/mode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mode"
        }
      ],
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/quartz/ikcameradeviceview/mode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDisplayMode": {
      "abstract": [
        {
          "text": "These constants specify the display mode used by the camera view. These constants are used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView/mode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "IKCameraDeviceViewDisplayMode",
      "type": "topic",
      "url": "/documentation/quartz/ikcameradeviceviewdisplaymode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewTransferMode": {
      "abstract": [
        {
          "text": "These constants specify the transfer mode used by the camera view. These constants are used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceView/mode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewTransferMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewTransferMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKCameraDeviceViewTransferMode"
        }
      ],
      "role": "symbol",
      "title": "IKCameraDeviceViewTransferMode",
      "type": "topic",
      "url": "/documentation/quartz/ikcameradeviceviewtransfermode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode": {
      "abstract": [
        {
          "text": "These constants specify the display mode of the device browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserViewDisplayMode",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserviewdisplaymode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell/cellState()": {
      "abstract": [
        {
          "text": "Returns the current cell state of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellState"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IKImageBrowserCellState",
          "text": "IKImageBrowserCellState"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell/cellState()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cellState"
        }
      ],
      "role": "symbol",
      "title": "cellState()",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercell/cellstate()"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellState": {
      "abstract": [
        {
          "text": "The possible states for the browser cell. These values are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCell/cellState()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellState"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellState"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellState",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellstate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation": {
      "abstract": [
        {
          "text": "These constants specify the locations for dropping items onto the browser view. Used by the method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserDropOperation",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdropoperation"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)": {
      "abstract": [
        {
          "text": "Allows the class to retarget the drop action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDrop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IKImageBrowserDropOperation",
          "text": "IKImageBrowserDropOperation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDropIndex:dropOperation:"
        }
      ],
      "role": "symbol",
      "title": "setDrop(_:dropOperation:)",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserview/setdrop(_:dropoperation:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView/mode": {
      "abstract": [
        {
          "text": "The display mode used by the device view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IKScannerDeviceViewDisplayMode",
          "text": "IKScannerDeviceViewDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView/mode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mode"
        }
      ],
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceview/mode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView/transferMode": {
      "abstract": [
        {
          "text": "Determines how the scanned content is provided to the delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transferMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IKScannerDeviceViewTransferMode",
          "text": "IKScannerDeviceViewTransferMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView/transferMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transferMode"
        }
      ],
      "role": "symbol",
      "title": "transferMode",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceview/transfermode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDisplayMode": {
      "abstract": [
        {
          "text": "These constants specify the display mode the scanner view will use. They are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView/mode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "IKScannerDeviceViewDisplayMode",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceviewdisplaymode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewTransferMode": {
      "abstract": [
        {
          "text": "These constants determine how the scanner data is returned to the delegate. They are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceView/transferMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewTransferMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewTransferMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKScannerDeviceViewTransferMode"
        }
      ],
      "role": "symbol",
      "title": "IKScannerDeviceViewTransferMode",
      "type": "topic",
      "url": "/documentation/quartz/ikscannerdeviceviewtransfermode"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit",
      "type": "topic",
      "url": "/documentation/quartz/imagekit"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit-quartz-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit-quartz-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit Constants",
      "type": "topic",
      "url": "/documentation/quartz/imagekit-quartz-constants"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/imagekit-quartz-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/1564248-cell-appearance-style-masks",
        "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes",
        "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDisplayMode",
        "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewTransferMode",
        "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellState",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation",
        "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDisplayMode",
        "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewTransferMode"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/1564248-cell-appearance-style-masks",
                "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes",
                "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewDisplayMode",
                "doc://com.apple.quartz/documentation/Quartz/IKCameraDeviceViewTransferMode",
                "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellState",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation",
                "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewDisplayMode",
                "doc://com.apple.quartz/documentation/Quartz/IKScannerDeviceViewTransferMode"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/imagekit-quartz-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView~1mode/title",
          "value": "mode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView~1mode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView~1setDrop(_:dropOperation:)/title",
          "value": "setDropIndex:dropOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView~1setDrop(_:dropOperation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDropIndex:dropOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/title",
          "value": "IKImageBrowserDropOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCell~1cellState()/title",
          "value": "cellState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCell~1cellState()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cellState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDisplayMode/title",
          "value": "IKCameraDeviceViewDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewDisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewTransferMode/title",
          "value": "IKCameraDeviceViewTransferMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewTransferMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewTransferMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceViewTransferMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKCameraDeviceViewTransferMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellState/title",
          "value": "IKImageBrowserCellState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode/title",
          "value": "IKDeviceBrowserViewDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDisplayMode/title",
          "value": "IKScannerDeviceViewDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewDisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView~1mode/title",
          "value": "mode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKCameraDeviceView~1mode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView~1transferMode/title",
          "value": "transferMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceView~1transferMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transferMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewTransferMode/title",
          "value": "IKScannerDeviceViewTransferMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewTransferMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewTransferMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKScannerDeviceViewTransferMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKScannerDeviceViewTransferMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/quartz-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/quartz-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
