{
  "abstract": [
    {
      "text": "Keys for slideshow options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/imagekit",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshow"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/slideshow-option-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Slideshow Option Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshow": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IKSlideshow",
          "type": "codeVoice"
        },
        {
          "text": " class encapsulates a data source and options for a slideshow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshow"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshow"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshow",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshow"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowAudioFile": {
      "abstract": [
        {
          "text": "A key specifying the audio file played during the slideshow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowAudioFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowAudioFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowAudioFile"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowAudioFile",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowaudiofile"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplayBox": {
      "abstract": [
        {
          "text": "A key for the PDF display box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowPDFDisplayBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplayBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowPDFDisplayBox"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowPDFDisplayBox",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowpdfdisplaybox"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplayMode": {
      "abstract": [
        {
          "text": "A key for the PDF display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowPDFDisplayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowPDFDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowPDFDisplayMode",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowpdfdisplaymode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplaysAsBook": {
      "abstract": [
        {
          "text": "A key for displaying the slideshow as a book. The associated value is a ",
          "type": "text"
        },
        {
          "code": "Boolean",
          "type": "codeVoice"
        },
        {
          "text": " data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowPDFDisplaysAsBook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplaysAsBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowPDFDisplaysAsBook"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowPDFDisplaysAsBook",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowpdfdisplaysasbook"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowScreen": {
      "abstract": [
        {
          "text": "A key specifying the screen on which the slideshow is displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowScreen"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowScreen",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowscreen"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowStartIndex": {
      "abstract": [
        {
          "text": "A key for the slideshow item index. The associated value is an index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowStartIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowStartIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowStartIndex"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowStartIndex",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowstartindex"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowStartPaused": {
      "abstract": [
        {
          "text": "A key for starting in a paused state. The associated value is a ",
          "type": "text"
        },
        {
          "code": "Boolean",
          "type": "codeVoice"
        },
        {
          "text": " data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowStartPaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowStartPaused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowStartPaused"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowStartPaused",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowstartpaused"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKSlideshowWrapAround": {
      "abstract": [
        {
          "text": "A key for starting the slideshow over after the last slide shows. The associated value is a ",
          "type": "text"
        },
        {
          "code": "Boolean",
          "type": "codeVoice"
        },
        {
          "text": " data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKSlideshowWrapAround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKSlideshowWrapAround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKSlideshowWrapAround"
        }
      ],
      "role": "symbol",
      "title": "IKSlideshowWrapAround",
      "type": "topic",
      "url": "/documentation/quartz/ikslideshowwraparound"
    },
    "doc://com.apple.quartz/documentation/Quartz/bundle-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for exporting slideshow items to an application.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/bundle-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bundle Identifiers",
      "type": "topic",
      "url": "/documentation/quartz/bundle-identifiers"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit",
      "type": "topic",
      "url": "/documentation/quartz/imagekit"
    },
    "doc://com.apple.quartz/documentation/Quartz/slideshow-modes": {
      "abstract": [
        {
          "text": "The kind of items in the slideshow.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/slideshow-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Slideshow Modes",
      "type": "topic",
      "url": "/documentation/quartz/slideshow-modes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/bundle-identifiers",
        "doc://com.apple.quartz/documentation/Quartz/slideshow-modes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowWrapAround",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowStartPaused",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowStartIndex",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplayBox",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplayMode",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplaysAsBook",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowScreen",
        "doc://com.apple.quartz/documentation/Quartz/IKSlideshowAudioFile"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowWrapAround",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowStartPaused",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowStartIndex",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplayBox",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplayMode",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowPDFDisplaysAsBook",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowScreen",
                "doc://com.apple.quartz/documentation/Quartz/IKSlideshowAudioFile"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/bundle-identifiers",
                "doc://com.apple.quartz/documentation/Quartz/slideshow-modes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowStartIndex/title",
          "value": "IKSlideshowStartIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowStartIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowStartIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowWrapAround/title",
          "value": "IKSlideshowWrapAround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowWrapAround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowWrapAround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowPDFDisplayBox/title",
          "value": "IKSlideshowPDFDisplayBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowPDFDisplayBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowPDFDisplayBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowAudioFile/title",
          "value": "IKSlideshowAudioFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowAudioFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowAudioFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowScreen/title",
          "value": "IKSlideshowScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/title",
          "value": "IKSlideshow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowPDFDisplaysAsBook/title",
          "value": "IKSlideshowPDFDisplaysAsBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowPDFDisplaysAsBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowPDFDisplaysAsBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowPDFDisplayMode/title",
          "value": "IKSlideshowPDFDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowPDFDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowPDFDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowStartPaused/title",
          "value": "IKSlideshowStartPaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKSlideshowStartPaused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKSlideshowStartPaused"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/slideshow-option-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/slideshow-option-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
