{
  "abstract": [
    {
      "text": "Input ports of a composition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
        "doc://com.apple.quartz/documentation/Quartz/QCComposition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Standard Protocol Input Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCComposition": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCComposition",
          "type": "codeVoice"
        },
        {
          "text": " class represents a Quartz Composer composition that either:",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "role": "symbol",
      "title": "QCComposition",
      "type": "topic",
      "url": "/documentation/quartz/qccomposition"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputAudioPeak",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be in the ",
          "type": "text"
        },
        {
          "code": "[0,1]",
          "type": "codeVoice"
        },
        {
          "text": " range as a mono signal with no decay applied.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioPeakKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioPeakKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputAudioPeakKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputaudiopeakkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey": {
      "abstract": [
        {
          "text": "A structure input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputAudioSpectrum",
          "type": "codeVoice"
        },
        {
          "text": ". The structure must contain 16 values in the ",
          "type": "text"
        },
        {
          "code": "[0,1]",
          "type": "codeVoice"
        },
        {
          "text": " range representing 16 spectrum bands of the mono signal from low to high frequencies with no decay applied.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioSpectrumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioSpectrumKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputAudioSpectrumKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputaudiospectrumkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey": {
      "abstract": [
        {
          "text": "An image input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputDestinationImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputDestinationImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputDestinationImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputDestinationImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputdestinationimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey": {
      "abstract": [
        {
          "text": "An image input port whose key is  ",
          "type": "text"
        },
        {
          "code": "inputImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputPace",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be in the ",
          "type": "text"
        },
        {
          "code": "[0,1]",
          "type": "codeVoice"
        },
        {
          "text": " range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputPaceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputPaceKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputPaceKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputpacekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey": {
      "abstract": [
        {
          "text": "A Boolean input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputPreviewMode",
          "type": "codeVoice"
        },
        {
          "text": ". When the value of this input port is set to ",
          "type": "text"
        },
        {
          "code": "TRUE",
          "type": "codeVoice"
        },
        {
          "text": ", the composition that provides this port must be able to run in a low-quality mode that produces a preview of the composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputPreviewModeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputPreviewModeKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputPreviewModeKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputpreviewmodekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPrimaryColorKey": {
      "abstract": [
        {
          "text": "A color input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputPrimaryColor",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputPrimaryColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPrimaryColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputPrimaryColorKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputPrimaryColorKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputprimarycolorkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSArticleDurationKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputRSSArticleDuration",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be expressed in seconds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputRSSArticleDurationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSArticleDurationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputRSSArticleDurationKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputRSSArticleDurationKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputrssarticledurationkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSFeedURLKey": {
      "abstract": [
        {
          "text": "A string input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputRSSFeedURL",
          "type": "codeVoice"
        },
        {
          "text": ". This port must be passed an http or feed scheme URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputRSSFeedURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSFeedURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputRSSFeedURLKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputRSSFeedURLKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputrssfeedurlkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputScreenImageKey": {
      "abstract": [
        {
          "text": "An image input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputScreenImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputScreenImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputScreenImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputScreenImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputScreenImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputscreenimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSecondaryColorKey": {
      "abstract": [
        {
          "text": "A color input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputSecondaryColor",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputSecondaryColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSecondaryColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputSecondaryColorKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputSecondaryColorKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputsecondarycolorkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSourceImageKey": {
      "abstract": [
        {
          "text": "An  image input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputSourceImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputSourceImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSourceImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputSourceImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputSourceImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputsourceimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackInfoKey": {
      "abstract": [
        {
          "text": "A structure input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputTrackInfo",
          "type": "codeVoice"
        },
        {
          "text": ". The structure contains optional entries, such as “name”, “artist”, “album”, “duration”, “artwork”, and so on.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackInfoKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputTrackInfoKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputtrackinfokey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackPositionKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputTrackPosition",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be expressed in seconds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackPositionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackPositionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackPositionKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputTrackPositionKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputtrackpositionkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackSignalKey": {
      "abstract": [
        {
          "text": "A Boolean input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputTrackSignal",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackSignalKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackSignalKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackSignalKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputTrackSignalKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputtracksignalkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputXKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputX",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be normalized to the image width with the origin on the left.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputXKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputXKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputXKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputXKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputxkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputYKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputY",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be normalized to the image height with the origin at the bottom.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputYKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputYKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputYKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputYKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputykey"
    },
    "doc://com.apple.quartz/documentation/Quartz/attribute-keys": {
      "abstract": [
        {
          "text": "Attributes of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Attribute Keys",
      "type": "topic",
      "url": "/documentation/quartz/attribute-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/composition-categories": {
      "abstract": [
        {
          "text": "Categories for compositions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/composition-categories",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composition Categories",
      "type": "topic",
      "url": "/documentation/quartz/composition-categories"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys": {
      "abstract": [
        {
          "text": "Output ports of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocol Output Keys",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocol-output-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocols": {
      "abstract": [
        {
          "text": "Protocols for a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocols",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocols"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/attribute-keys",
        "doc://com.apple.quartz/documentation/Quartz/composition-categories",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocols"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSourceImageKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSFeedURLKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSArticleDurationKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputXKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputYKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputScreenImageKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackPositionKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackInfoKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackSignalKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPrimaryColorKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSecondaryColorKey",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSourceImageKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSFeedURLKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSArticleDurationKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputXKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputYKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputScreenImageKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackPositionKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackInfoKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackSignalKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPrimaryColorKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSecondaryColorKey",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/attribute-keys",
                "doc://com.apple.quartz/documentation/Quartz/composition-categories",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocols"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputScreenImageKey/title",
          "value": "QCCompositionInputScreenImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputScreenImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputScreenImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPreviewModeKey/title",
          "value": "QCCompositionInputPreviewModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPreviewModeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputPreviewModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputXKey/title",
          "value": "QCCompositionInputXKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputXKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputXKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackPositionKey/title",
          "value": "QCCompositionInputTrackPositionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackPositionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputTrackPositionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioPeakKey/title",
          "value": "QCCompositionInputAudioPeakKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioPeakKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputAudioPeakKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioSpectrumKey/title",
          "value": "QCCompositionInputAudioSpectrumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioSpectrumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputAudioSpectrumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackInfoKey/title",
          "value": "QCCompositionInputTrackInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputTrackInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/title",
          "value": "QCComposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputSecondaryColorKey/title",
          "value": "QCCompositionInputSecondaryColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputSecondaryColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputSecondaryColorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPrimaryColorKey/title",
          "value": "QCCompositionInputPrimaryColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPrimaryColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputPrimaryColorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPaceKey/title",
          "value": "QCCompositionInputPaceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPaceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputPaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputRSSFeedURLKey/title",
          "value": "QCCompositionInputRSSFeedURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputRSSFeedURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputRSSFeedURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputYKey/title",
          "value": "QCCompositionInputYKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputYKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputYKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputImageKey/title",
          "value": "QCCompositionInputImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackSignalKey/title",
          "value": "QCCompositionInputTrackSignalKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackSignalKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputTrackSignalKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputDestinationImageKey/title",
          "value": "QCCompositionInputDestinationImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputDestinationImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputDestinationImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputSourceImageKey/title",
          "value": "QCCompositionInputSourceImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputSourceImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputSourceImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputRSSArticleDurationKey/title",
          "value": "QCCompositionInputRSSArticleDurationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputRSSArticleDurationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputRSSArticleDurationKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/standard-protocol-input-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/standard-protocol-input-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
