{
  "abstract": [
    {
      "text": "Protocols for a composition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
        "doc://com.apple.quartz/documentation/Quartz/QCComposition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/standard-protocols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Standard Protocols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCComposition": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCComposition",
          "type": "codeVoice"
        },
        {
          "text": " class represents a Quartz Composer composition that either:",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "role": "symbol",
      "title": "QCComposition",
      "type": "topic",
      "url": "/documentation/quartz/qccomposition"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputAudioPeak",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be in the ",
          "type": "text"
        },
        {
          "code": "[0,1]",
          "type": "codeVoice"
        },
        {
          "text": " range as a mono signal with no decay applied.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioPeakKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioPeakKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputAudioPeakKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputaudiopeakkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey": {
      "abstract": [
        {
          "text": "A structure input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputAudioSpectrum",
          "type": "codeVoice"
        },
        {
          "text": ". The structure must contain 16 values in the ",
          "type": "text"
        },
        {
          "code": "[0,1]",
          "type": "codeVoice"
        },
        {
          "text": " range representing 16 spectrum bands of the mono signal from low to high frequencies with no decay applied.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioSpectrumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputAudioSpectrumKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputAudioSpectrumKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputaudiospectrumkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey": {
      "abstract": [
        {
          "text": "An image input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputDestinationImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputDestinationImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputDestinationImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputDestinationImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputdestinationimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey": {
      "abstract": [
        {
          "text": "An image input port whose key is  ",
          "type": "text"
        },
        {
          "code": "inputImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputPace",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be in the ",
          "type": "text"
        },
        {
          "code": "[0,1]",
          "type": "codeVoice"
        },
        {
          "text": " range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputPaceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputPaceKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputPaceKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputpacekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey": {
      "abstract": [
        {
          "text": "A Boolean input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputPreviewMode",
          "type": "codeVoice"
        },
        {
          "text": ". When the value of this input port is set to ",
          "type": "text"
        },
        {
          "code": "TRUE",
          "type": "codeVoice"
        },
        {
          "text": ", the composition that provides this port must be able to run in a low-quality mode that produces a preview of the composition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputPreviewModeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputPreviewModeKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputPreviewModeKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputpreviewmodekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPrimaryColorKey": {
      "abstract": [
        {
          "text": "A color input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputPrimaryColor",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputPrimaryColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPrimaryColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputPrimaryColorKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputPrimaryColorKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputprimarycolorkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSArticleDurationKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputRSSArticleDuration",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be expressed in seconds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputRSSArticleDurationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSArticleDurationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputRSSArticleDurationKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputRSSArticleDurationKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputrssarticledurationkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSFeedURLKey": {
      "abstract": [
        {
          "text": "A string input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputRSSFeedURL",
          "type": "codeVoice"
        },
        {
          "text": ". This port must be passed an http or feed scheme URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputRSSFeedURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSFeedURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputRSSFeedURLKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputRSSFeedURLKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputrssfeedurlkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputScreenImageKey": {
      "abstract": [
        {
          "text": "An image input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputScreenImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputScreenImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputScreenImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputScreenImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputScreenImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputscreenimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSecondaryColorKey": {
      "abstract": [
        {
          "text": "A color input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputSecondaryColor",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputSecondaryColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSecondaryColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputSecondaryColorKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputSecondaryColorKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputsecondarycolorkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSourceImageKey": {
      "abstract": [
        {
          "text": "An  image input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputSourceImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputSourceImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSourceImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputSourceImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputSourceImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputsourceimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackInfoKey": {
      "abstract": [
        {
          "text": "A structure input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputTrackInfo",
          "type": "codeVoice"
        },
        {
          "text": ". The structure contains optional entries, such as “name”, “artist”, “album”, “duration”, “artwork”, and so on.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackInfoKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputTrackInfoKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputtrackinfokey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackSignalKey": {
      "abstract": [
        {
          "text": "A Boolean input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputTrackSignal",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackSignalKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackSignalKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputTrackSignalKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputTrackSignalKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputtracksignalkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputXKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputX",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be normalized to the image width with the origin on the left.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputXKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputXKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputXKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputXKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputxkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputYKey": {
      "abstract": [
        {
          "text": "A number input port whose key is ",
          "type": "text"
        },
        {
          "code": "inputY",
          "type": "codeVoice"
        },
        {
          "text": ". The value must be normalized to the image height with the origin at the bottom.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionInputYKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputYKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionInputYKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionInputYKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositioninputykey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionOutputImageKey": {
      "abstract": [
        {
          "text": "An image output port whose key is ",
          "type": "text"
        },
        {
          "code": "outputImage",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionOutputImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionOutputImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionOutputImageKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionOutputImageKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionoutputimagekey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionOutputWebPageURLKey": {
      "abstract": [
        {
          "text": "A string output port whose key is ",
          "type": "text"
        },
        {
          "code": "outputWebPageURL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionOutputWebPageURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionOutputWebPageURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionOutputWebPageURLKey"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionOutputWebPageURLKey",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionoutputwebpageurlkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolGraphicAnimation": {
      "abstract": [
        {
          "text": "A composition that renders a generic graphical animation. It has the option to use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPrimaryColorKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the primary color of the animation, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSecondaryColorKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the secondary color of the animation, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPaceKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the global pace of the animation, and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to indicate if the animation should run in lower-quality for preview purposes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolGraphicAnimation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolGraphicAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolGraphicAnimation"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionProtocolGraphicAnimation",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionprotocolgraphicanimation"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolGraphicTransition": {
      "abstract": [
        {
          "text": "A  composition that performs a transition between two images, using a transition time in range of ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ". A conforming composition must use the input keys ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputSourceImageKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the starting image and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputDestinationImageKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the image to transition to. The composition can optionally use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to indicate if the animation should run in lower-quality for preview purposes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolGraphicTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolGraphicTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolGraphicTransition"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionProtocolGraphicTransition",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionprotocolgraphictransition"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolImageFilter": {
      "abstract": [
        {
          "text": "A  composition that  applies an effect to a source image.  A conforming composition must use the input key ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputImageKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the source image and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionOutputImageKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the output image. The composition can optionally use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputXKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to specify the X position of the center point of the effect, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputYKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to specify the Y position of the center point of the effect, and",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to indicate if the animation should run in lower-quality for preview purposes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolImageFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolImageFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolImageFilter"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionProtocolImageFilter",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionprotocolimagefilter"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolMusicVisualizer": {
      "abstract": [
        {
          "text": "A  composition that acts as a visualizer for music.  A conforming composition must use the input key ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioPeakKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the instantaneous audio peak and the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputAudioSpectrumKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "  for the instantaneous audio spectrum. It can optionally use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackInfoKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to indicate it receives information about the current  track and the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputTrackSignalKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to indicate the start of a new track.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolMusicVisualizer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolMusicVisualizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolMusicVisualizer"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionProtocolMusicVisualizer",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionprotocolmusicvisualizer"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolRSSVisualizer": {
      "abstract": [
        {
          "text": "A  composition that acts as a visualizer for an RSS feed.  A conforming composition must use the input key ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSFeedURLKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the URL to use for the RSS feed. It can optionally use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputRSSArticleDurationKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to specify the duration of each feed article.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolRSSVisualizer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolRSSVisualizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolRSSVisualizer"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionProtocolRSSVisualizer",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionprotocolrssvisualizer"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolScreenSaver": {
      "abstract": [
        {
          "text": "A composition that can be used as a screen saver. The composition has the option to use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputScreenImageKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for a screenshot image of the screen that the screen saver runs on, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionInputPreviewModeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to indicate if the animation should run in lower-quality for preview purposes, and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionOutputWebPageURLKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for a  URL to open in the default web browser when screen saver exits (only allowed if screen saver password is disabled).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolScreenSaver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolScreenSaver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCCompositionProtocolScreenSaver"
        }
      ],
      "role": "symbol",
      "title": "QCCompositionProtocolScreenSaver",
      "type": "topic",
      "url": "/documentation/quartz/qccompositionprotocolscreensaver"
    },
    "doc://com.apple.quartz/documentation/Quartz/attribute-keys": {
      "abstract": [
        {
          "text": "Attributes of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Attribute Keys",
      "type": "topic",
      "url": "/documentation/quartz/attribute-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/composition-categories": {
      "abstract": [
        {
          "text": "Categories for compositions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/composition-categories",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composition Categories",
      "type": "topic",
      "url": "/documentation/quartz/composition-categories"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys": {
      "abstract": [
        {
          "text": "Input ports of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocol Input Keys",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocol-input-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys": {
      "abstract": [
        {
          "text": "Output ports of a composition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Protocol Output Keys",
      "type": "topic",
      "url": "/documentation/quartz/standard-protocol-output-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/attribute-keys",
        "doc://com.apple.quartz/documentation/Quartz/composition-categories",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys",
        "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolGraphicAnimation",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolGraphicTransition",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolImageFilter",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolScreenSaver",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolRSSVisualizer",
        "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolMusicVisualizer"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolGraphicAnimation",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolGraphicTransition",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolImageFilter",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolScreenSaver",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolRSSVisualizer",
                "doc://com.apple.quartz/documentation/Quartz/QCCompositionProtocolMusicVisualizer"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/attribute-keys",
                "doc://com.apple.quartz/documentation/Quartz/composition-categories",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocol-input-keys",
                "doc://com.apple.quartz/documentation/Quartz/standard-protocol-output-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolScreenSaver/title",
          "value": "QCCompositionProtocolScreenSaver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolScreenSaver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionProtocolScreenSaver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputScreenImageKey/title",
          "value": "QCCompositionInputScreenImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputScreenImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputScreenImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPreviewModeKey/title",
          "value": "QCCompositionInputPreviewModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPreviewModeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputPreviewModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionOutputImageKey/title",
          "value": "QCCompositionOutputImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionOutputImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionOutputImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/title",
          "value": "QCComposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioPeakKey/title",
          "value": "QCCompositionInputAudioPeakKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioPeakKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputAudioPeakKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputYKey/title",
          "value": "QCCompositionInputYKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputYKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputYKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputSourceImageKey/title",
          "value": "QCCompositionInputSourceImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputSourceImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputSourceImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolRSSVisualizer/title",
          "value": "QCCompositionProtocolRSSVisualizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolRSSVisualizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionProtocolRSSVisualizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputRSSFeedURLKey/title",
          "value": "QCCompositionInputRSSFeedURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputRSSFeedURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputRSSFeedURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolMusicVisualizer/title",
          "value": "QCCompositionProtocolMusicVisualizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolMusicVisualizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionProtocolMusicVisualizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackInfoKey/title",
          "value": "QCCompositionInputTrackInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputTrackInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputImageKey/title",
          "value": "QCCompositionInputImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputSecondaryColorKey/title",
          "value": "QCCompositionInputSecondaryColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputSecondaryColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputSecondaryColorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputDestinationImageKey/title",
          "value": "QCCompositionInputDestinationImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputDestinationImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputDestinationImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioSpectrumKey/title",
          "value": "QCCompositionInputAudioSpectrumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputAudioSpectrumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputAudioSpectrumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputXKey/title",
          "value": "QCCompositionInputXKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputXKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputXKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackSignalKey/title",
          "value": "QCCompositionInputTrackSignalKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputTrackSignalKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputTrackSignalKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputRSSArticleDurationKey/title",
          "value": "QCCompositionInputRSSArticleDurationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputRSSArticleDurationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputRSSArticleDurationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPrimaryColorKey/title",
          "value": "QCCompositionInputPrimaryColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPrimaryColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputPrimaryColorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPaceKey/title",
          "value": "QCCompositionInputPaceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionInputPaceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionInputPaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolGraphicTransition/title",
          "value": "QCCompositionProtocolGraphicTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolGraphicTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionProtocolGraphicTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolImageFilter/title",
          "value": "QCCompositionProtocolImageFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolImageFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionProtocolImageFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionOutputWebPageURLKey/title",
          "value": "QCCompositionOutputWebPageURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionOutputWebPageURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionOutputWebPageURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolGraphicAnimation/title",
          "value": "QCCompositionProtocolGraphicAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCCompositionProtocolGraphicAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCCompositionProtocolGraphicAnimation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/standard-protocols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/standard-protocols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
