{
  "abstract": [
    {
      "text": "Image Kit tools modes referenced by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageView/currentToolMode",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/imagekit",
        "doc://com.apple.quartz/documentation/Quartz/IKImageView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/tool-modes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Tool Modes"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageView": {
      "abstract": [
        {
          "text": "A view that allows displaying and minor editing of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageView"
        }
      ],
      "role": "symbol",
      "title": "IKImageView",
      "type": "topic",
      "url": "/documentation/quartz/ikimageview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageView/currentToolMode": {
      "abstract": [
        {
          "text": "Specifies the current tool mode for the image view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentToolMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageView/currentToolMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentToolMode"
        }
      ],
      "role": "symbol",
      "title": "currentToolMode",
      "type": "topic",
      "url": "/documentation/quartz/ikimageview/currenttoolmode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKToolModeAnnotate": {
      "abstract": [
        {
          "text": "The annotation tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKToolModeAnnotate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKToolModeAnnotate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKToolModeAnnotate"
        }
      ],
      "role": "symbol",
      "title": "IKToolModeAnnotate",
      "type": "topic",
      "url": "/documentation/quartz/iktoolmodeannotate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKToolModeCrop": {
      "abstract": [
        {
          "text": "The crop tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKToolModeCrop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKToolModeCrop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKToolModeCrop"
        }
      ],
      "role": "symbol",
      "title": "IKToolModeCrop",
      "type": "topic",
      "url": "/documentation/quartz/iktoolmodecrop"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKToolModeMove": {
      "abstract": [
        {
          "text": "The move tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKToolModeMove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKToolModeMove",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKToolModeMove"
        }
      ],
      "role": "symbol",
      "title": "IKToolModeMove",
      "type": "topic",
      "url": "/documentation/quartz/iktoolmodemove"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKToolModeNone": {
      "abstract": [
        {
          "text": "No tool is set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKToolModeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKToolModeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKToolModeNone"
        }
      ],
      "role": "symbol",
      "title": "IKToolModeNone",
      "type": "topic",
      "url": "/documentation/quartz/iktoolmodenone"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKToolModeRotate": {
      "abstract": [
        {
          "text": "The rotation tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKToolModeRotate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKToolModeRotate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKToolModeRotate"
        }
      ],
      "role": "symbol",
      "title": "IKToolModeRotate",
      "type": "topic",
      "url": "/documentation/quartz/iktoolmoderotate"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelect": {
      "abstract": [
        {
          "text": "The selection tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKToolModeSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKToolModeSelect"
        }
      ],
      "role": "symbol",
      "title": "IKToolModeSelect",
      "type": "topic",
      "url": "/documentation/quartz/iktoolmodeselect"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectEllipse": {
      "abstract": [
        {
          "text": "The selection ellipse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKToolModeSelectEllipse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectEllipse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKToolModeSelectEllipse"
        }
      ],
      "role": "symbol",
      "title": "IKToolModeSelectEllipse",
      "type": "topic",
      "url": "/documentation/quartz/iktoolmodeselectellipse"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectLasso": {
      "abstract": [
        {
          "text": "The selection lasso.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKToolModeSelectLasso"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectLasso",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKToolModeSelectLasso"
        }
      ],
      "role": "symbol",
      "title": "IKToolModeSelectLasso",
      "type": "topic",
      "url": "/documentation/quartz/iktoolmodeselectlasso"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectRect": {
      "abstract": [
        {
          "text": "Same as ",
          "type": "text"
        },
        {
          "code": "IKToolModeSelect",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKToolModeSelectRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKToolModeSelectRect"
        }
      ],
      "role": "symbol",
      "title": "IKToolModeSelectRect",
      "type": "topic",
      "url": "/documentation/quartz/iktoolmodeselectrect"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit",
      "type": "topic",
      "url": "/documentation/quartz/imagekit"
    },
    "doc://com.apple.quartz/documentation/Quartz/overlay-types": {
      "abstract": [
        {
          "text": "A layer level.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/overlay-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Overlay Types",
      "type": "topic",
      "url": "/documentation/quartz/overlay-types"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/overlay-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKToolModeNone",
        "doc://com.apple.quartz/documentation/Quartz/IKToolModeMove",
        "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelect",
        "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectRect",
        "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectEllipse",
        "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectLasso",
        "doc://com.apple.quartz/documentation/Quartz/IKToolModeCrop",
        "doc://com.apple.quartz/documentation/Quartz/IKToolModeRotate",
        "doc://com.apple.quartz/documentation/Quartz/IKToolModeAnnotate"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKToolModeNone",
                "doc://com.apple.quartz/documentation/Quartz/IKToolModeMove",
                "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelect",
                "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectRect",
                "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectEllipse",
                "doc://com.apple.quartz/documentation/Quartz/IKToolModeSelectLasso",
                "doc://com.apple.quartz/documentation/Quartz/IKToolModeCrop",
                "doc://com.apple.quartz/documentation/Quartz/IKToolModeRotate",
                "doc://com.apple.quartz/documentation/Quartz/IKToolModeAnnotate"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/overlay-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeSelectLasso/title",
          "value": "IKToolModeSelectLasso"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeSelectLasso/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKToolModeSelectLasso"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeMove/title",
          "value": "IKToolModeMove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeMove/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKToolModeMove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageView~1currentToolMode/title",
          "value": "currentToolMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageView~1currentToolMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentToolMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeRotate/title",
          "value": "IKToolModeRotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeRotate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKToolModeRotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageView/title",
          "value": "IKImageView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeNone/title",
          "value": "IKToolModeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKToolModeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeSelectRect/title",
          "value": "IKToolModeSelectRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeSelectRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKToolModeSelectRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeAnnotate/title",
          "value": "IKToolModeAnnotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeAnnotate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKToolModeAnnotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeSelect/title",
          "value": "IKToolModeSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKToolModeSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeCrop/title",
          "value": "IKToolModeCrop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeCrop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKToolModeCrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeSelectEllipse/title",
          "value": "IKToolModeSelectEllipse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKToolModeSelectEllipse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKToolModeSelectEllipse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/tool-modes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/tool-modes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
