{
  "abstract": [
    {
      "text": "Keys for image browser view options. You set and retrieve values for these keys by sending the view ",
      "type": "text"
    },
    {
      "code": "setValue:forKey",
      "type": "codeVoice"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "code": "valueForKey:",
      "type": "codeVoice"
    },
    {
      "text": " messages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/imagekit",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/view-options-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "View Options Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes": {
      "abstract": [
        {
          "text": "Attributes for the group style. Used by the",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Group Style Attributes",
      "type": "topic",
      "url": "/documentation/quartz/1564247-group-style-attributes"
    },
    "doc://com.apple.quartz/documentation/Quartz/1564248-cell-appearance-style-masks": {
      "abstract": [
        {
          "text": "Masks for the appearance style bit field.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/1564248-cell-appearance-style-masks",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell Appearance Style Masks",
      "type": "topic",
      "url": "/documentation/quartz/1564248-cell-appearance-style-masks"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserBackgroundColorKey": {
      "abstract": [
        {
          "text": "A key for the background color of the image browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserBackgroundColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserBackgroundColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserBackgroundColorKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserBackgroundColorKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserbackgroundcolorkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsHighlightedTitleAttributesKey": {
      "abstract": [
        {
          "text": "A key for the highlighted title attribute for an item in the image browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsHighlightedTitleAttributesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsHighlightedTitleAttributesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsHighlightedTitleAttributesKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellsHighlightedTitleAttributesKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellshighlightedtitleattributeskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsOutlineColorKey": {
      "abstract": [
        {
          "text": "A key for the outline color for an item in the image browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsOutlineColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsOutlineColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsOutlineColorKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellsOutlineColorKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellsoutlinecolorkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsSubtitleAttributesKey": {
      "abstract": [
        {
          "text": "A key for  a subtitle attribute for an item in the image browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsSubtitleAttributesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsSubtitleAttributesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsSubtitleAttributesKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellsSubtitleAttributesKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellssubtitleattributeskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsTitleAttributesKey": {
      "abstract": [
        {
          "text": "A key for  title attribute of an item in the image browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsTitleAttributesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsTitleAttributesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserCellsTitleAttributesKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserCellsTitleAttributesKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowsercellstitleattributeskey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation": {
      "abstract": [
        {
          "text": "These constants specify the locations for dropping items onto the browser view. Used by the method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserDropOperation"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserDropOperation",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserdropoperation"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserSelectionColorKey": {
      "abstract": [
        {
          "text": "A key for the color that indicates a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserSelectionColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserSelectionColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserSelectionColorKey"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserSelectionColorKey",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserselectioncolorkey"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView": {
      "abstract": [
        {
          "text": "A view for displaying and browsing a large collection of images and movies.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKImageBrowserView"
        }
      ],
      "role": "symbol",
      "title": "IKImageBrowserView",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserview"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)": {
      "abstract": [
        {
          "text": "Allows the class to retarget the drop action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDrop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IKImageBrowserDropOperation",
          "text": "IKImageBrowserDropOperation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserView/setDrop(_:dropOperation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDropIndex:dropOperation:"
        }
      ],
      "role": "symbol",
      "title": "setDrop(_:dropOperation:)",
      "type": "topic",
      "url": "/documentation/quartz/ikimagebrowserview/setdrop(_:dropoperation:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/group-keys": {
      "abstract": [
        {
          "text": "Keys for group attributes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/group-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Group Keys",
      "type": "topic",
      "url": "/documentation/quartz/group-keys"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit",
      "type": "topic",
      "url": "/documentation/quartz/imagekit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/1564248-cell-appearance-style-masks",
        "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes",
        "doc://com.apple.quartz/documentation/Quartz/group-keys",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserBackgroundColorKey",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserSelectionColorKey",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsOutlineColorKey",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsTitleAttributesKey",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsHighlightedTitleAttributesKey",
        "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsSubtitleAttributesKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserBackgroundColorKey",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserSelectionColorKey",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsOutlineColorKey",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsTitleAttributesKey",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsHighlightedTitleAttributesKey",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserCellsSubtitleAttributesKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/1564248-cell-appearance-style-masks",
                "doc://com.apple.quartz/documentation/Quartz/1564247-group-style-attributes",
                "doc://com.apple.quartz/documentation/Quartz/group-keys",
                "doc://com.apple.quartz/documentation/Quartz/IKImageBrowserDropOperation"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/title",
          "value": "IKImageBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsSubtitleAttributesKey/title",
          "value": "IKImageBrowserCellsSubtitleAttributesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsSubtitleAttributesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellsSubtitleAttributesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserSelectionColorKey/title",
          "value": "IKImageBrowserSelectionColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserSelectionColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserSelectionColorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsHighlightedTitleAttributesKey/title",
          "value": "IKImageBrowserCellsHighlightedTitleAttributesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsHighlightedTitleAttributesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellsHighlightedTitleAttributesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsOutlineColorKey/title",
          "value": "IKImageBrowserCellsOutlineColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsOutlineColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellsOutlineColorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView~1setDrop(_:dropOperation:)/title",
          "value": "setDropIndex:dropOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserView~1setDrop(_:dropOperation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDropIndex:dropOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/title",
          "value": "IKImageBrowserDropOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserDropOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsTitleAttributesKey/title",
          "value": "IKImageBrowserCellsTitleAttributesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserCellsTitleAttributesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserCellsTitleAttributesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserBackgroundColorKey/title",
          "value": "IKImageBrowserBackgroundColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKImageBrowserBackgroundColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKImageBrowserBackgroundColorKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/view-options-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/view-options-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
