{
  "abstract": [
    {
      "text": "The delegate to notify when editing an event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkitui/documentation/EventKitUI",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController/editViewDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)EKEventEditViewController(py)editViewDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "editViewDelegate"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)EKEventEditViewDelegate",
        "text": "EKEventEditViewDelegate"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "EventKit UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "editViewDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "editViewDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "weak"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "editViewDelegate"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)EKEventEditViewDelegate",
              "text": "EKEventEditViewDelegate"
            },
            {
              "kind": "text",
              "text": ")? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI": {
      "abstract": [
        {
          "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit UI",
      "type": "topic",
      "url": "/documentation/eventkitui"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController": {
      "abstract": [
        {
          "text": "A view controller for creating, editing, and deleting calendar events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventEditViewController"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewController"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewController",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewcontroller"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController/editViewDelegate": {
      "abstract": [
        {
          "text": "The delegate to notify when editing an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editViewDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)EKEventEditViewDelegate",
          "text": "EKEventEditViewDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController/editViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "editViewDelegate",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewcontroller/editviewdelegate"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate": {
      "abstract": [
        {
          "text": "A notification sent to the delegate when the user finishes editing an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventEditViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewDelegate",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewdelegate"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Event-Editing-Interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate"
      ],
      "title": "Managing the Event Editing Interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "editViewDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkitui/documentation/EventKitUI",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Event-Editing-Interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate"
              ],
              "title": "Managing the Event Editing Interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "weak"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)EKEventEditViewDelegate",
                    "text": "id<EKEventEditViewDelegate>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "editViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewDelegate/title",
          "value": "EKEventEditViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController~1editViewDelegate/title",
          "value": "editViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController~1editViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController/title",
          "value": "EKEventEditViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkitui/ekeventeditviewcontroller/editviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkitui/ekeventeditviewcontroller/editviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
