{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor/region"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/passkit/pkidentitynationalidcarddescriptor/region"]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.passkit/documentation/PassKit","doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"region","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation6LocaleV","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation6LocaleV6RegionV","preciseIdentifier":"s:10Foundation6LocaleV6RegionV","text":"Region","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"s:So34PKIdentityNationalIDCardDescriptorC7PassKitE6region10Foundation6LocaleV6RegionVSgvp","extendedModule":"PassKit","role":"symbol","modules":[{"name":"PassKit (Apple Pay and Wallet)"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"region"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier","text":"Locale"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Foundation6LocaleV6RegionV","kind":"typeIdentifier","text":"Region"},{"kind":"text","text":"?"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"18.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"18.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"}],"title":"region","symbolKind":"property"},"abstract":[{"text":"A string used to specify the region associated with the ID.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.passkit/documentation/PassKit":{"type":"topic","title":"PassKit (Apple Pay and Wallet)","abstract":[{"text":"Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.","type":"text"}],"identifier":"doc://com.apple.passkit/documentation/PassKit","url":"/documentation/passkit","kind":"symbol","role":"collection"},"doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PKIdentityNationalIDCardDescriptor"}],"identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/passkit/pkidentitynationalidcarddescriptor","abstract":[{"type":"text","text":"An object for requesting information from a user’s national ID card."}],"navigatorTitle":[{"kind":"identifier","text":"PKIdentityNationalIDCardDescriptor"}],"title":"PKIdentityNationalIDCardDescriptor"},"doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor/region":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"region"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV6RegionV","text":"Region"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityNationalIDCardDescriptor/region","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/passkit/pkidentitynationalidcarddescriptor/region","abstract":[{"type":"text","text":"A string used to specify the region associated with the ID."}],"title":"region"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview"},"doc://com.externally.resolved.symbol/s:10Foundation6LocaleV":{"fragments":[{"text":"struct ","kind":"text"},{"text":"Locale","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation6LocaleV","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/foundation/locale","abstract":[{"type":"text","text":"Information about linguistic, cultural, and technological conventions for use in formatting data for presentation."}],"title":"Locale"},"doc://com.externally.resolved.symbol/s:10Foundation6LocaleV6RegionV":{"fragments":[{"text":"struct ","kind":"text"},{"text":"Locale.Region","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation6LocaleV6RegionV","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/foundation/locale/region","abstract":[{"type":"text","text":"A type that represents a geographic region, for use in specifying a locale or language."}],"title":"Locale.Region"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"PKIdentityNationalIDCardDescriptor","path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityNationalIDCardDescriptor/title","op":"replace"},{"value":[{"kind":"identifier","text":"PKIdentityNationalIDCardDescriptor"}],"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityNationalIDCardDescriptor/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PKIdentityNationalIDCardDescriptor"}],"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityNationalIDCardDescriptor/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}