{
  "abstract": [
    {
      "text": "Constants that define the minimum and maximum number of peers supported in a session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/minimum_and_maximum_supported_peers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Multipeer Connectivity"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Minimum and Maximum Supported Peers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity": {
      "abstract": [
        {
          "text": "Support peer-to-peer connectivity and the discovery of nearby devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Multipeer Connectivity",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCEncryptionPreference": {
      "abstract": [
        {
          "text": "Indicates whether a session should use encryption when communicating with nearby peers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCEncryptionPreference"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCEncryptionPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCEncryptionPreference"
        }
      ],
      "role": "symbol",
      "title": "MCEncryptionPreference",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcencryptionpreference"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code": {
      "abstract": [
        {
          "text": "Error codes found in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " error domain ",
          "type": "text"
        },
        {
          "code": "NSError",
          "type": "codeVoice"
        },
        {
          "text": " objects returned by methods in the Multipeer Connectivity framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MCError.Code",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror/code"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSError",
          "type": "codeVoice"
        },
        {
          "text": " domain constant. If the ",
          "type": "text"
        },
        {
          "code": "domain",
          "type": "codeVoice"
        },
        {
          "text": " value for an ",
          "type": "text"
        },
        {
          "code": "NSError",
          "type": "codeVoice"
        },
        {
          "text": " object is equal to ",
          "type": "text"
        },
        {
          "code": "MCErrorDomain",
          "type": "codeVoice"
        },
        {
          "text": ", then the error was produced by the Multipeer Connectivity framework itself, as opposed to a lower-level framework on which it depends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MCErrorDomain",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerrordomain"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSession": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "MCSession",
          "type": "codeVoice"
        },
        {
          "text": " object enables and manages communication among all peers in a Multipeer Connectivity session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCSession"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCSession"
        }
      ],
      "role": "symbol",
      "title": "MCSession",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcsession"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSessionSendDataMode": {
      "abstract": [
        {
          "text": "Indicates whether delivery of data should be guaranteed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCSessionSendDataMode"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSessionSendDataMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCSessionSendDataMode"
        }
      ],
      "role": "symbol",
      "title": "MCSessionSendDataMode",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcsessionsenddatamode"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSessionState": {
      "abstract": [
        {
          "text": "Indicates the current state of a given peer within a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCSessionState"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSessionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCSessionState"
        }
      ],
      "role": "symbol",
      "title": "MCSessionState",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcsessionstate"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMaximumNumberOfPeers": {
      "abstract": [
        {
          "text": "The maximum number of peers that a session can support, including the local peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMCSessionMaximumNumberOfPeers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMaximumNumberOfPeers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMCSessionMaximumNumberOfPeers"
        }
      ],
      "role": "symbol",
      "title": "kMCSessionMaximumNumberOfPeers",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/kmcsessionmaximumnumberofpeers"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMinimumNumberOfPeers": {
      "abstract": [
        {
          "text": "The minimum number of peers that a session can support, including the local peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMCSessionMinimumNumberOfPeers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMinimumNumberOfPeers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMCSessionMinimumNumberOfPeers"
        }
      ],
      "role": "symbol",
      "title": "kMCSessionMinimumNumberOfPeers",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/kmcsessionminimumnumberofpeers"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/multipeer_connectivity_error_domain": {
      "abstract": [
        {
          "text": "The error domain for errors specific to Multipeer Connectivity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/multipeer_connectivity_error_domain",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multipeer Connectivity Error Domain",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/multipeer_connectivity_error_domain"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSessionSendDataMode",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSessionState",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCEncryptionPreference",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/multipeer_connectivity_error_domain"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMaximumNumberOfPeers",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMinimumNumberOfPeers"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMaximumNumberOfPeers",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMinimumNumberOfPeers"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSessionSendDataMode",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSessionState",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCEncryptionPreference",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/multipeer_connectivity_error_domain"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code/title",
          "value": "MCErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1kMCSessionMaximumNumberOfPeers/title",
          "value": "kMCSessionMaximumNumberOfPeers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1kMCSessionMaximumNumberOfPeers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMCSessionMaximumNumberOfPeers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCEncryptionPreference/title",
          "value": "MCEncryptionPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCEncryptionPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCEncryptionPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCEncryptionPreference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MCEncryptionPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1kMCSessionMinimumNumberOfPeers/title",
          "value": "kMCSessionMinimumNumberOfPeers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1kMCSessionMinimumNumberOfPeers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMCSessionMinimumNumberOfPeers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSession/title",
          "value": "MCSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCErrorDomain/title",
          "value": "MCErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSessionSendDataMode/title",
          "value": "MCSessionSendDataMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSessionSendDataMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCSessionSendDataMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSessionSendDataMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MCSessionSendDataMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSessionState/title",
          "value": "MCSessionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSessionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCSessionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSessionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MCSessionState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/multipeerconnectivity/minimum_and_maximum_supported_peers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/multipeerconnectivity/minimum_and_maximum_supported_peers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
