{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/multipeerconnectivity_constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Multipeer Connectivity"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MultipeerConnectivity Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity": {
      "abstract": [
        {
          "text": "Support peer-to-peer connectivity and the discovery of nearby devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Multipeer Connectivity",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSError",
          "type": "codeVoice"
        },
        {
          "text": " domain constant. If the ",
          "type": "text"
        },
        {
          "code": "domain",
          "type": "codeVoice"
        },
        {
          "text": " value for an ",
          "type": "text"
        },
        {
          "code": "NSError",
          "type": "codeVoice"
        },
        {
          "text": " object is equal to ",
          "type": "text"
        },
        {
          "code": "MCErrorDomain",
          "type": "codeVoice"
        },
        {
          "text": ", then the error was produced by the Multipeer Connectivity framework itself, as opposed to a lower-level framework on which it depends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MCErrorDomain",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerrordomain"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMaximumNumberOfPeers": {
      "abstract": [
        {
          "text": "The maximum number of peers that a session can support, including the local peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMCSessionMaximumNumberOfPeers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMaximumNumberOfPeers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMCSessionMaximumNumberOfPeers"
        }
      ],
      "role": "symbol",
      "title": "kMCSessionMaximumNumberOfPeers",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/kmcsessionmaximumnumberofpeers"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMinimumNumberOfPeers": {
      "abstract": [
        {
          "text": "The minimum number of peers that a session can support, including the local peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMCSessionMinimumNumberOfPeers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMinimumNumberOfPeers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMCSessionMinimumNumberOfPeers"
        }
      ],
      "role": "symbol",
      "title": "kMCSessionMinimumNumberOfPeers",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/kmcsessionminimumnumberofpeers"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/multipeerconnectivity_enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/multipeerconnectivity_enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MultipeerConnectivity Enumerations",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/multipeerconnectivity_enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/multipeerconnectivity_enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMaximumNumberOfPeers",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMinimumNumberOfPeers"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMaximumNumberOfPeers",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/kMCSessionMinimumNumberOfPeers"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/multipeerconnectivity_enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1kMCSessionMaximumNumberOfPeers/title",
          "value": "kMCSessionMaximumNumberOfPeers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1kMCSessionMaximumNumberOfPeers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMCSessionMaximumNumberOfPeers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1kMCSessionMinimumNumberOfPeers/title",
          "value": "kMCSessionMinimumNumberOfPeers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1kMCSessionMinimumNumberOfPeers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMCSessionMinimumNumberOfPeers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCErrorDomain/title",
          "value": "MCErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/multipeerconnectivity/multipeerconnectivity_constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/multipeerconnectivity/multipeerconnectivity_constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
