{"kind":"symbol","variants":[{"paths":["/documentation/sensorkit/srsensorreaderdelegate/sensorreaderdidstoprecording(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/sensorkit/srsensorreaderdelegate/sensorreaderdidstoprecording(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Recording Data","identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderWillStartRecording(_:)","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:startRecordingFailedWithError:)","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:stopRecordingFailedWithError:)"],"generated":true,"anchor":"Recording-Data"}],"abstract":[{"type":"text","text":"Notifies the delegate when a reader stops recording."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sensorReaderDidStopRecording","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"reader"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SRSensorReader","kind":"typeIdentifier","text":"SRSensorReader","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The reader that stopped recording."}],"type":"paragraph"}],"name":"reader"}],"kind":"parameters"}],"identifier":{"url":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderDidStopRecording(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"sensorReaderDidStopRecording:"}],"roleHeading":"Instance Method","title":"sensorReaderDidStopRecording(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensorReaderDidStopRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SRSensorReader","preciseIdentifier":"c:objc(cs)SRSensorReader"},{"kind":"text","text":")"}],"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"14.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"beta":false}],"modules":[{"name":"SensorKit"}],"externalID":"c:objc(pl)SRSensorReaderDelegate(im)sensorReaderDidStopRecording:","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderDidStopRecording(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sensorReaderDidStopRecording","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SRSensorReader","preciseIdentifier":"c:objc(cs)SRSensorReader","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"type":"text","text":"Notifies the delegate when a reader stops recording."}],"title":"sensorReaderDidStopRecording(_:)","navigatorTitle":[{"kind":"identifier","text":"sensorReaderDidStopRecording:"}],"type":"topic","url":"/documentation/sensorkit/srsensorreaderdelegate/sensorreaderdidstoprecording(_:)","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderDidStopRecording(_:)"},"doc://com.apple.sensorkit/documentation/SensorKit":{"type":"topic","title":"SensorKit","abstract":[{"type":"text","text":"Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch."}],"url":"/documentation/sensorkit","role":"collection","identifier":"doc://com.apple.sensorkit/documentation/SensorKit","kind":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader","role":"symbol","abstract":[{"text":"An object that establishes user authorization and records data for a particular sensor.","type":"text"}],"kind":"symbol","title":"SRSensorReader","navigatorTitle":[{"kind":"identifier","text":"SRSensorReader"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRSensorReader"}],"url":"/documentation/sensorkit/srsensorreader"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderWillStartRecording(_:)":{"url":"/documentation/sensorkit/srsensorreaderdelegate/sensorreaderwillstartrecording(_:)","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderWillStartRecording(_:)","title":"sensorReaderWillStartRecording(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sensorReaderWillStartRecording:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sensorReaderWillStartRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SRSensorReader","text":"SRSensorReader"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies the delegate when a reader starts recording."}],"type":"topic","role":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:startRecordingFailedWithError:)":{"url":"/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:startrecordingfailedwitherror:)","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:startRecordingFailedWithError:)","title":"sensorReader(_:startRecordingFailedWithError:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sensorReader:startRecordingFailedWithError:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sensorReader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SRSensorReader","text":"SRSensorReader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"startRecordingFailedWithError"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Provides the delegate with a reason when the reader fails to record."}],"type":"topic","role":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate","role":"symbol","abstract":[{"text":"A set of callbacks the framework invokes to notify the app of sensor-related events.","type":"text"}],"kind":"symbol","title":"SRSensorReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"SRSensorReaderDelegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRSensorReaderDelegate"}],"url":"/documentation/sensorkit/srsensorreaderdelegate"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:stopRecordingFailedWithError:)":{"type":"topic","title":"sensorReader(_:stopRecordingFailedWithError:)","navigatorTitle":[{"kind":"identifier","text":"sensorReader:stopRecordingFailedWithError:"}],"kind":"symbol","abstract":[{"text":"Provides the delegate with a reason when the reader fails to stop recording.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensorReader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SRSensorReader","text":"SRSensorReader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stopRecordingFailedWithError"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"role":"symbol","url":"/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:stoprecordingfailedwitherror:)","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:stopRecordingFailedWithError:)"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0","name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0","name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0","name":"Mac Catalyst"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","value":"sensorReaderDidStopRecording:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sensorReaderDidStopRecording:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Recording-Data","generated":true,"identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderWillStartRecording(_:)","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:startRecordingFailedWithError:)","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:stopRecordingFailedWithError:)"],"title":"Recording Data"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sensorReaderDidStopRecording:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SRSensorReader","kind":"typeIdentifier","text":"SRSensorReader","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reader"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"reader","content":[{"inlineContent":[{"type":"text","text":"The reader that stopped recording."}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1"},{"op":"replace","value":"sensorReaderDidStopRecording:","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReaderDidStopRecording(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sensorReaderDidStopRecording:"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReaderDidStopRecording(_:)/fragments"},{"op":"replace","value":"SRSensorReader","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/title"},{"op":"replace","value":[{"text":"SRSensorReader","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SRSensorReader"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/navigatorTitle"},{"op":"replace","value":"sensorReaderWillStartRecording:","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReaderWillStartRecording(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sensorReaderWillStartRecording:"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReaderWillStartRecording(_:)/fragments"},{"op":"replace","value":"sensorReader:startRecordingFailedWithError:","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:startRecordingFailedWithError:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sensorReader:startRecordingFailedWithError:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:startRecordingFailedWithError:)/fragments"},{"op":"replace","value":"SRSensorReaderDelegate","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRSensorReaderDelegate"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/fragments"},{"op":"replace","value":[{"text":"SRSensorReaderDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/navigatorTitle"},{"op":"replace","value":"sensorReader:stopRecordingFailedWithError:","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:stopRecordingFailedWithError:)/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:stopRecordingFailedWithError:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sensorReader:stopRecordingFailedWithError:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}