{"variants":[{"paths":["/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:failedwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:failedwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensorReader"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"reader"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensorReader","preciseIdentifier":"c:objc(cs)SRSensorReader","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fetching"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fetchRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRFetchRequest","preciseIdentifier":"c:objc(cs)SRFetchRequest","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failedWithError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": any "},{"text":"Error","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The sensor reader for which the fetch failed.","type":"text"}],"type":"paragraph"}],"name":"reader"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The original fetch request."}]}],"name":"fetchRequest"},{"content":[{"inlineContent":[{"text":"An object that describes the cause of failure.","type":"text"}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"}],"sections":[],"metadata":{"title":"sensorReader(_:fetching:failedWithError:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sensorReader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SRSensorReader","text":"SRSensorReader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fetching"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SRFetchRequest","text":"SRFetchRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failedWithError"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sensorReader:fetchingRequest:failedWithError:"}],"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"14.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"14.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"14.0","beta":false}],"externalID":"c:objc(pl)SRSensorReaderDelegate(im)sensorReader:fetchingRequest:failedWithError:","modules":[{"name":"SensorKit"}]},"kind":"symbol","abstract":[{"type":"text","text":"Provides the delegate with a fetch failure reason."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate"]]},"identifier":{"url":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Reading Recorded Data","identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)"],"anchor":"Reading-Recorded-Data","generated":true}],"references":{"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensorReader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SRSensorReader","text":"SRSensorReader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fetching"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SRFetchRequest","kind":"typeIdentifier","text":"SRFetchRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failedWithError"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"type":"topic","title":"sensorReader(_:fetching:failedWithError:)","abstract":[{"type":"text","text":"Provides the delegate with a fetch failure reason."}],"navigatorTitle":[{"kind":"identifier","text":"sensorReader:fetchingRequest:failedWithError:"}],"url":"/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:failedwitherror:)","role":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)","kind":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader","role":"symbol","abstract":[{"text":"An object that establishes user authorization and records data for a particular sensor.","type":"text"}],"kind":"symbol","title":"SRSensorReader","navigatorTitle":[{"kind":"identifier","text":"SRSensorReader"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRSensorReader"}],"url":"/documentation/sensorkit/srsensorreader"},"doc://com.externally.resolved.symbol/s:s5ErrorP":{"abstract":[{"text":"A type representing an error value that can be thrown.","type":"text"}],"role":"symbol","kind":"symbol","url":"/documentation/Swift/Error","type":"topic","title":"Error","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Sendable","preciseIdentifier":"s:s8SendableP"}]},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)":{"role":"symbol","abstract":[{"text":"Provides the delegate with a completed fetch request.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"sensorReader:didCompleteFetch:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensorReader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SRSensorReader","preciseIdentifier":"c:objc(cs)SRSensorReader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteFetch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRFetchRequest","preciseIdentifier":"c:objc(cs)SRFetchRequest"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)","title":"sensorReader(_:didCompleteFetch:)","url":"/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:didcompletefetch:)"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)":{"title":"sensorReader(_:fetching:didFetchResult:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensorReader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SRSensorReader","text":"SRSensorReader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fetching"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SRFetchRequest","kind":"typeIdentifier","text":"SRFetchRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFetchResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SRFetchResult","kind":"typeIdentifier","text":"SRFetchResult"},{"kind":"text","text":"<AnyObject>) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"type":"text","text":"Provides the delegate with a fetch result."}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)","navigatorTitle":[{"kind":"identifier","text":"sensorReader:fetchingRequest:didFetchResult:"}],"url":"/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:didfetchresult:)"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate","role":"symbol","abstract":[{"text":"A set of callbacks the framework invokes to notify the app of sensor-related events.","type":"text"}],"kind":"symbol","title":"SRSensorReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"SRSensorReaderDelegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRSensorReaderDelegate"}],"url":"/documentation/sensorkit/srsensorreaderdelegate"},"doc://com.apple.sensorkit/documentation/SensorKit":{"type":"topic","title":"SensorKit","abstract":[{"type":"text","text":"Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch."}],"url":"/documentation/sensorkit","role":"collection","identifier":"doc://com.apple.sensorkit/documentation/SensorKit","kind":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest","role":"symbol","abstract":[{"text":"An object that defines the criteria for a sample query.","type":"text"}],"kind":"symbol","title":"SRFetchRequest","navigatorTitle":[{"kind":"identifier","text":"SRFetchRequest"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRFetchRequest"}],"url":"/documentation/sensorkit/srfetchrequest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"14.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"14.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"path":"/metadata/title","value":"sensorReader:fetchingRequest:failedWithError:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sensorReader:fetchingRequest:failedWithError:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)","doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)"],"generated":true,"title":"Reading Recorded Data","anchor":"Reading-Recorded-Data"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"sensorReader:"},{"kind":"text","text":"("},{"text":"SRSensorReader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SRSensorReader","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader"},{"text":" *) ","kind":"text"},{"text":"reader","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fetchingRequest:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SRFetchRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SRFetchRequest","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest"},{"text":" *) ","kind":"text"},{"text":"fetchRequest","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"failedWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"reader","content":[{"inlineContent":[{"type":"text","text":"The sensor reader for which the fetch failed."}],"type":"paragraph"}]},{"name":"fetchRequest","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The original fetch request."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object that describes the cause of failure."}]}]}]},"path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:failedWithError:)/title","value":"sensorReader:fetchingRequest:failedWithError:","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:failedWithError:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sensorReader:fetchingRequest:failedWithError:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/title","value":"SRSensorReader","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/fragments","value":[{"text":"SRSensorReader","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/navigatorTitle","value":[{"text":"SRSensorReader","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didCompleteFetch:)/title","value":"sensorReader:didCompleteFetch:","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didCompleteFetch:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sensorReader:didCompleteFetch:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:didFetchResult:)/title","value":"sensorReader:fetchingRequest:didFetchResult:","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:didFetchResult:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"sensorReader:fetchingRequest:didFetchResult:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/title","value":"SRSensorReaderDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/fragments","value":[{"kind":"identifier","text":"SRSensorReaderDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/navigatorTitle","value":[{"text":"SRSensorReaderDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/title","value":"SRFetchRequest","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/fragments","value":[{"text":"SRFetchRequest","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/navigatorTitle","value":[{"kind":"identifier","text":"SRFetchRequest"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}