{
  "abstract": [
    {
      "text": "Provides the delegate with a fetch result.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SRSensorReaderDelegate(im)sensorReader:fetchingRequest:didFetchResult:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sensorReader"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRSensorReader",
        "text": "SRSensorReader"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "fetching"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRFetchRequest",
        "text": "SRFetchRequest"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didFetchResult"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRFetchResult",
        "text": "SRFetchResult"
      },
      {
        "kind": "text",
        "text": "<AnyObject>) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sensorReader:fetchingRequest:didFetchResult:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "sensorReader(_:fetching:didFetchResult:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sensorReader"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "reader"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRSensorReader",
              "text": "SRSensorReader"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "fetching"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "fetchRequest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRFetchRequest",
              "text": "SRFetchRequest"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didFetchResult"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "result"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRFetchResult",
              "text": "SRFetchResult"
            },
            {
              "kind": "text",
              "text": "<AnyObject>) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The sensor reader for which the fetch provides results.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "reader"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The completed fetch request.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "fetchRequest"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The fetch request’s result.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "result"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The framework expects the app to know the result’s type based on the reader’s sensor. To see a list of result types per sensor, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample#Sample-types",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When a fetch produces multiple results, the framework invokes this callback once for each result.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To reuse a fetch result within the scope of this function, create a copy of ",
              "type": "text"
            },
            {
              "code": "fetchResult",
              "type": "codeVoice"
            },
            {
              "text": " rather than assigning a strong reference to it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest": {
      "abstract": [
        {
          "text": "An object that defines the criteria for a sample query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "SRFetchRequest",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchrequest"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult": {
      "abstract": [
        {
          "text": "Recorded data that a sensor reader fetches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRFetchResult"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRFetchResult"
        }
      ],
      "role": "symbol",
      "title": "SRFetchResult",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchresult"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample#Sample-types": {
      "abstract": [],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample#Sample-types",
      "kind": "section",
      "title": "Sample types",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchresult/sample#Sample-types"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader": {
      "abstract": [
        {
          "text": "An object that establishes user authorization and records data for a particular sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSensorReader"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorReader"
        }
      ],
      "role": "symbol",
      "title": "SRSensorReader",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreader"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate": {
      "abstract": [
        {
          "text": "A set of callbacks the framework invokes to notify the app of sensor-related events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSensorReaderDelegate"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorReaderDelegate"
        }
      ],
      "role": "symbol",
      "title": "SRSensorReaderDelegate",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)": {
      "abstract": [
        {
          "text": "Provides the delegate with a completed fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didCompleteFetch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFetchRequest",
          "text": "SRFetchRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:didCompleteFetch:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:didCompleteFetch:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:didcompletefetch:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)": {
      "abstract": [
        {
          "text": "Provides the delegate with a fetch result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fetching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFetchRequest",
          "text": "SRFetchRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFetchResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFetchResult",
          "text": "SRFetchResult"
        },
        {
          "kind": "text",
          "text": "<AnyObject>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:fetchingRequest:didFetchResult:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:fetching:didFetchResult:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:didfetchresult:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)": {
      "abstract": [
        {
          "text": "Provides the delegate with a fetch failure reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fetching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFetchRequest",
          "text": "SRFetchRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "failedWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:fetchingRequest:failedWithError:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:fetching:failedWithError:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:failedwitherror:)"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-Recorded-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)"
      ],
      "title": "Reading Recorded Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sensorReader:fetchingRequest:didFetchResult:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:fetchingRequest:didFetchResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-Recorded-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)"
              ],
              "title": "Reading Recorded Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "sensorReader:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SRSensorReader",
                    "text": "SRSensorReader"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "reader"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "fetchingRequest:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SRFetchRequest",
                    "text": "SRFetchRequest"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "fetchRequest"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didFetchResult:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SRFetchResult",
                    "text": "SRFetchResult"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "result"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The sensor reader for which the fetch provides results.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "reader"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The completed fetch request.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "fetchRequest"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The fetch request’s result.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "result"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:failedWithError:)/title",
          "value": "sensorReader:fetchingRequest:failedWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:failedWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:fetchingRequest:failedWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:didFetchResult:)/title",
          "value": "sensorReader:fetchingRequest:didFetchResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:didFetchResult:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:fetchingRequest:didFetchResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult/title",
          "value": "SRFetchResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/title",
          "value": "SRSensorReader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/title",
          "value": "SRFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/title",
          "value": "SRSensorReaderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReaderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReaderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didCompleteFetch:)/title",
          "value": "sensorReader:didCompleteFetch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didCompleteFetch:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:didCompleteFetch:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:didfetchresult:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:didfetchresult:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
