{
  "abstract": [
    {
      "text": "The callback for collecting the names of an object’s properties.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/getPropertyNames"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@JSClassDefinition@FI@getPropertyNames",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "getPropertyNames"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectGetPropertyNamesCallback",
        "text": "JSObjectGetPropertyNamesCallback"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "getPropertyNames"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "getPropertyNames"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "getPropertyNames"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyNamesCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectGetPropertyNamesCallback",
              "text": "JSObjectGetPropertyNamesCallback"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition": {
      "abstract": [
        {
          "text": "A structure that contains properties and callbacks that define a type of object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSClassDefinition"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSClassDefinition"
        }
      ],
      "role": "symbol",
      "title": "JSClassDefinition",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/callAsFunction": {
      "abstract": [
        {
          "text": "The callback for calling an object as a function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callAsFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectCallAsFunctionCallback",
          "text": "JSObjectCallAsFunctionCallback"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/callAsFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callAsFunction"
        }
      ],
      "role": "symbol",
      "title": "callAsFunction",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/callasfunction"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/deleteProperty": {
      "abstract": [
        {
          "text": "The callback for deleting a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectDeletePropertyCallback",
          "text": "JSObjectDeletePropertyCallback"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/deleteProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteProperty"
        }
      ],
      "role": "symbol",
      "title": "deleteProperty",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/deleteproperty"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/finalize": {
      "abstract": [
        {
          "text": "The callback for preparing the object for garbage collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finalize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectFinalizeCallback",
          "text": "JSObjectFinalizeCallback"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/finalize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finalize"
        }
      ],
      "role": "symbol",
      "title": "finalize",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/finalize"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/getProperty": {
      "abstract": [
        {
          "text": "The callback for getting a property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectGetPropertyCallback",
          "text": "JSObjectGetPropertyCallback"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/getProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getProperty"
        }
      ],
      "role": "symbol",
      "title": "getProperty",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/getproperty"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/getPropertyNames": {
      "abstract": [
        {
          "text": "The callback for collecting the names of an object’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getPropertyNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectGetPropertyNamesCallback",
          "text": "JSObjectGetPropertyNamesCallback"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/getPropertyNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getPropertyNames"
        }
      ],
      "role": "symbol",
      "title": "getPropertyNames",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/getpropertynames"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/hasProperty": {
      "abstract": [
        {
          "text": "The callback for determining whether an object has a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectHasPropertyCallback",
          "text": "JSObjectHasPropertyCallback"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/hasProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasProperty"
        }
      ],
      "role": "symbol",
      "title": "hasProperty",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/hasproperty"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/initialize": {
      "abstract": [
        {
          "text": "The callback for creating the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectInitializeCallback",
          "text": "JSObjectInitializeCallback"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/initialize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initialize"
        }
      ],
      "role": "symbol",
      "title": "initialize",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/initialize"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/setProperty": {
      "abstract": [
        {
          "text": "The callback for setting a property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectSetPropertyCallback",
          "text": "JSObjectSetPropertyCallback"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/setProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setProperty"
        }
      ],
      "role": "symbol",
      "title": "setProperty",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/setproperty"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback": {
      "abstract": [
        {
          "text": "The callback type for calling an object as a function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectCallAsFunctionCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectCallAsFunctionCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectCallAsFunctionCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectcallasfunctioncallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeletePropertyCallback": {
      "abstract": [
        {
          "text": "The callback type for deleting a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectDeletePropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeletePropertyCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectDeletePropertyCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectDeletePropertyCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectdeletepropertycallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectFinalizeCallback": {
      "abstract": [
        {
          "text": "The callback type for finalizing an object (preparing it for garbage collection).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectFinalizeCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectFinalizeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectFinalizeCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectFinalizeCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectfinalizecallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyCallback": {
      "abstract": [
        {
          "text": "The callback type for getting a property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectGetPropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectGetPropertyCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectGetPropertyCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectgetpropertycallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyNamesCallback": {
      "abstract": [
        {
          "text": "The callback type for collecting the names of an object’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectGetPropertyNamesCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyNamesCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectGetPropertyNamesCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectGetPropertyNamesCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectgetpropertynamescallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasPropertyCallback": {
      "abstract": [
        {
          "text": "The callback type for determining whether an object has a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectHasPropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasPropertyCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectHasPropertyCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectHasPropertyCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjecthaspropertycallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectInitializeCallback": {
      "abstract": [
        {
          "text": "The callback type for first creating an object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectInitializeCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectInitializeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectInitializeCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectInitializeCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectinitializecallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectSetPropertyCallback": {
      "abstract": [
        {
          "text": "The callback type for setting a property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectSetPropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectSetPropertyCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectSetPropertyCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectSetPropertyCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectsetpropertycallback"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Callbacks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/initialize",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectInitializeCallback",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/finalize",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectFinalizeCallback",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/hasProperty",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasPropertyCallback",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/getProperty",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyCallback",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/setProperty",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectSetPropertyCallback",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/deleteProperty",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeletePropertyCallback",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyNamesCallback",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/callAsFunction",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback"
      ],
      "title": "Managing Callbacks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "getPropertyNames"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getPropertyNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Callbacks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/initialize",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectInitializeCallback",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/finalize",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectFinalizeCallback",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/hasProperty",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasPropertyCallback",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/getProperty",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyCallback",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/setProperty",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectSetPropertyCallback",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/deleteProperty",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeletePropertyCallback",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyNamesCallback",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/callAsFunction",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback"
              ],
              "title": "Managing Callbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyNamesCallback",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@JSObjectGetPropertyNamesCallback",
                    "text": "JSObjectGetPropertyNamesCallback"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "getPropertyNames"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyCallback/title",
          "value": "JSObjectGetPropertyCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyNamesCallback/title",
          "value": "JSObjectGetPropertyNamesCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyNamesCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetPropertyNamesCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyNamesCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetPropertyNamesCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1setProperty/title",
          "value": "setProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1setProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition/title",
          "value": "JSClassDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1finalize/title",
          "value": "finalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1finalize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "finalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectSetPropertyCallback/title",
          "value": "JSObjectSetPropertyCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectSetPropertyCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectSetPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectSetPropertyCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectSetPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectInitializeCallback/title",
          "value": "JSObjectInitializeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectInitializeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectInitializeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectInitializeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectInitializeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1getProperty/title",
          "value": "getProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1getProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1deleteProperty/title",
          "value": "deleteProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1deleteProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deleteProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1getPropertyNames/title",
          "value": "getPropertyNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1getPropertyNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getPropertyNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectFinalizeCallback/title",
          "value": "JSObjectFinalizeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectFinalizeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectFinalizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectFinalizeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectFinalizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasPropertyCallback/title",
          "value": "JSObjectHasPropertyCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasPropertyCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectHasPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasPropertyCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectHasPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1callAsFunction/title",
          "value": "callAsFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1callAsFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callAsFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectDeletePropertyCallback/title",
          "value": "JSObjectDeletePropertyCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectDeletePropertyCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectDeletePropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectDeletePropertyCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectDeletePropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1initialize/title",
          "value": "initialize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1initialize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initialize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunctionCallback/title",
          "value": "JSObjectCallAsFunctionCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunctionCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectCallAsFunctionCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunctionCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectCallAsFunctionCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1hasProperty/title",
          "value": "hasProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition~1hasProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasProperty"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jsclassdefinition/getpropertynames"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jsclassdefinition/getpropertynames"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
