{
  "abstract": [
    {
      "text": "Creates a class definition with the specified values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/init(version:attributes:className:parentClass:staticValues:staticFunctions:initialize:finalize:hasProperty:getProperty:setProperty:deleteProperty:getPropertyNames:callAsFunction:callAsConstructor:hasInstance:convertToType:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So17JSClassDefinitiona7version10attributes9className11parentClass12staticValues0I9Functions10initialize8finalize11hasProperty03getO003setO006deleteO00pO5Names14callAsFunction0tU11Constructor0N8Instance13convertToTypeABs5Int32V_s6UInt32VSPys4Int8VGSgs13OpaquePointerVSgSPySo13JSStaticValueaGSgSPySo08JSStaticV0aGSgyA2__A2_tXCSgyA2_XCSgSbA2__A2_A2_tXCSgA2_A2__A2_A2_SpyA2_GSgtXCSgSbA2__A2_A2_A2_A15_tXCSgSbA2__A2_A2_A15_tXCSgyA2__A2_A2_tXCSgA2_A2__A2_A2_SiSPyA2_GSgA15_tXCSgA2_A2__A2_SiA21_A15_tXCSgA18_A2_A2__A2_So6JSTypeaA15_tXCSgtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "version"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "attributes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSClassAttributes",
        "text": "JSClassAttributes"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "className"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "externalParam",
        "text": "parentClass"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSClassRef",
        "text": "JSClassRef"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "staticValues"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@JSStaticValue",
        "text": "JSStaticValue"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "externalParam",
        "text": "staticFunctions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@JSStaticFunction",
        "text": "JSStaticFunction"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "externalParam",
        "text": "initialize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectInitializeCallback",
        "text": "JSObjectInitializeCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "finalize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectFinalizeCallback",
        "text": "JSObjectFinalizeCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "hasProperty"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectHasPropertyCallback",
        "text": "JSObjectHasPropertyCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "getProperty"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectGetPropertyCallback",
        "text": "JSObjectGetPropertyCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "setProperty"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectSetPropertyCallback",
        "text": "JSObjectSetPropertyCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "deleteProperty"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectDeletePropertyCallback",
        "text": "JSObjectDeletePropertyCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "getPropertyNames"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectGetPropertyNamesCallback",
        "text": "JSObjectGetPropertyNamesCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "callAsFunction"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectCallAsFunctionCallback",
        "text": "JSObjectCallAsFunctionCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "callAsConstructor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectCallAsConstructorCallback",
        "text": "JSObjectCallAsConstructorCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "hasInstance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectHasInstanceCallback",
        "text": "JSObjectHasInstanceCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "convertToType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectConvertToTypeCallback",
        "text": "JSObjectConvertToTypeCallback"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(version:attributes:className:parentClass:staticValues:staticFunctions:initialize:finalize:hasProperty:getProperty:setProperty:deleteProperty:getPropertyNames:callAsFunction:callAsConstructor:hasInstance:convertToType:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "version"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "attributes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassAttributes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSClassAttributes",
              "text": "JSClassAttributes"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "className"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "parentClass"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSClassRef",
              "text": "JSClassRef"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "staticValues"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@JSStaticValue",
              "text": "JSStaticValue"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "staticFunctions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@JSStaticFunction",
              "text": "JSStaticFunction"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "initialize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectInitializeCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectInitializeCallback",
              "text": "JSObjectInitializeCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "finalize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectFinalizeCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectFinalizeCallback",
              "text": "JSObjectFinalizeCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "hasProperty"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasPropertyCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectHasPropertyCallback",
              "text": "JSObjectHasPropertyCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "getProperty"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectGetPropertyCallback",
              "text": "JSObjectGetPropertyCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "setProperty"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectSetPropertyCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectSetPropertyCallback",
              "text": "JSObjectSetPropertyCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "deleteProperty"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeletePropertyCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectDeletePropertyCallback",
              "text": "JSObjectDeletePropertyCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "getPropertyNames"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyNamesCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectGetPropertyNamesCallback",
              "text": "JSObjectGetPropertyNamesCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "callAsFunction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectCallAsFunctionCallback",
              "text": "JSObjectCallAsFunctionCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "callAsConstructor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsConstructorCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectCallAsConstructorCallback",
              "text": "JSObjectCallAsConstructorCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "hasInstance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasInstanceCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectHasInstanceCallback",
              "text": "JSObjectHasInstanceCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "convertToType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectConvertToTypeCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectConvertToTypeCallback",
              "text": "JSObjectConvertToTypeCallback"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassAttributes": {
      "abstract": [
        {
          "text": "A set of JavaScript class attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSClassAttributes"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSClassAttributes"
        }
      ],
      "role": "symbol",
      "title": "JSClassAttributes",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassattributes"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition": {
      "abstract": [
        {
          "text": "A structure that contains properties and callbacks that define a type of object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSClassDefinition"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSClassDefinition"
        }
      ],
      "role": "symbol",
      "title": "JSClassDefinition",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/init()": {
      "abstract": [
        {
          "text": "Creates an empty class definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/init()"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/init(version:attributes:className:parentClass:staticValues:staticFunctions:initialize:finalize:hasProperty:getProperty:setProperty:deleteProperty:getPropertyNames:callAsFunction:callAsConstructor:hasInstance:convertToType:)": {
      "abstract": [
        {
          "text": "Creates a class definition with the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSClassAttributes",
          "text": "JSClassAttributes"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "className"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "parentClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSClassRef",
          "text": "JSClassRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "staticValues"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@JSStaticValue",
          "text": "JSStaticValue"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "staticFunctions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@JSStaticFunction",
          "text": "JSStaticFunction"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "initialize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectInitializeCallback",
          "text": "JSObjectInitializeCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "finalize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectFinalizeCallback",
          "text": "JSObjectFinalizeCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "hasProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectHasPropertyCallback",
          "text": "JSObjectHasPropertyCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "getProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectGetPropertyCallback",
          "text": "JSObjectGetPropertyCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "setProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectSetPropertyCallback",
          "text": "JSObjectSetPropertyCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "deleteProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectDeletePropertyCallback",
          "text": "JSObjectDeletePropertyCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "getPropertyNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectGetPropertyNamesCallback",
          "text": "JSObjectGetPropertyNamesCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "callAsFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectCallAsFunctionCallback",
          "text": "JSObjectCallAsFunctionCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "callAsConstructor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectCallAsConstructorCallback",
          "text": "JSObjectCallAsConstructorCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "hasInstance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectHasInstanceCallback",
          "text": "JSObjectHasInstanceCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "convertToType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectConvertToTypeCallback",
          "text": "JSObjectConvertToTypeCallback"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/init(version:attributes:className:parentClass:staticValues:staticFunctions:initialize:finalize:hasProperty:getProperty:setProperty:deleteProperty:getPropertyNames:callAsFunction:callAsConstructor:hasInstance:convertToType:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:attributes:className:parentClass:staticValues:staticFunctions:initialize:finalize:hasProperty:getProperty:setProperty:deleteProperty:getPropertyNames:callAsFunction:callAsConstructor:hasInstance:convertToType:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassdefinition/init(version:attributes:classname:parentclass:staticvalues:staticfunctions:initialize:finalize:hasproperty:getproperty:setproperty:deleteproperty:getpropertynames:callasfunction:callasconstructor:hasinstance:converttotype:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef": {
      "abstract": [
        {
          "text": "A JavaScript class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSClassRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSClassRef"
        }
      ],
      "role": "symbol",
      "title": "JSClassRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsConstructorCallback": {
      "abstract": [
        {
          "text": "The callback type for using an object as a constructor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectCallAsConstructorCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsConstructorCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectCallAsConstructorCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectCallAsConstructorCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectcallasconstructorcallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback": {
      "abstract": [
        {
          "text": "The callback type for calling an object as a function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectCallAsFunctionCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectCallAsFunctionCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectCallAsFunctionCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectcallasfunctioncallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectConvertToTypeCallback": {
      "abstract": [
        {
          "text": "The callback type for converting an object to a particular JavaScript type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectConvertToTypeCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectConvertToTypeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectConvertToTypeCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectConvertToTypeCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectconverttotypecallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeletePropertyCallback": {
      "abstract": [
        {
          "text": "The callback type for deleting a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectDeletePropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeletePropertyCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectDeletePropertyCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectDeletePropertyCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectdeletepropertycallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectFinalizeCallback": {
      "abstract": [
        {
          "text": "The callback type for finalizing an object (preparing it for garbage collection).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectFinalizeCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectFinalizeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectFinalizeCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectFinalizeCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectfinalizecallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyCallback": {
      "abstract": [
        {
          "text": "The callback type for getting a property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectGetPropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectGetPropertyCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectGetPropertyCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectgetpropertycallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyNamesCallback": {
      "abstract": [
        {
          "text": "The callback type for collecting the names of an object’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectGetPropertyNamesCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyNamesCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectGetPropertyNamesCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectGetPropertyNamesCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectgetpropertynamescallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasInstanceCallback": {
      "abstract": [
        {
          "text": "The callback type for checking whether an object is an instance of a particular type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectHasInstanceCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasInstanceCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectHasInstanceCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectHasInstanceCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjecthasinstancecallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasPropertyCallback": {
      "abstract": [
        {
          "text": "The callback type for determining whether an object has a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectHasPropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasPropertyCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectHasPropertyCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectHasPropertyCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjecthaspropertycallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectInitializeCallback": {
      "abstract": [
        {
          "text": "The callback type for first creating an object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectInitializeCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectInitializeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectInitializeCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectInitializeCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectinitializecallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectSetPropertyCallback": {
      "abstract": [
        {
          "text": "The callback type for setting a property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectSetPropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectSetPropertyCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectSetPropertyCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectSetPropertyCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectsetpropertycallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction": {
      "abstract": [
        {
          "text": "A statically declared function property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStaticFunction"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStaticFunction"
        }
      ],
      "role": "symbol",
      "title": "JSStaticFunction",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstaticfunction"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticValue": {
      "abstract": [
        {
          "text": "A statically declared value property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStaticValue"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStaticValue"
        }
      ],
      "role": "symbol",
      "title": "JSStaticValue",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstaticvalue"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Class-Definition",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassDefinition/init()",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassAttributes"
      ],
      "title": "Creating a Class Definition"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassRef/title",
          "value": "JSClassRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStaticValue/title",
          "value": "JSStaticValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStaticValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStaticValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStaticValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStaticValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectDeletePropertyCallback/title",
          "value": "JSObjectDeletePropertyCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectDeletePropertyCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectDeletePropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectDeletePropertyCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectDeletePropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectConvertToTypeCallback/title",
          "value": "JSObjectConvertToTypeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectConvertToTypeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectConvertToTypeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectConvertToTypeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectConvertToTypeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasInstanceCallback/title",
          "value": "JSObjectHasInstanceCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasInstanceCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectHasInstanceCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasInstanceCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectHasInstanceCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyCallback/title",
          "value": "JSObjectGetPropertyCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectInitializeCallback/title",
          "value": "JSObjectInitializeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectInitializeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectInitializeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectInitializeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectInitializeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectSetPropertyCallback/title",
          "value": "JSObjectSetPropertyCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectSetPropertyCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectSetPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectSetPropertyCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectSetPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStaticFunction/title",
          "value": "JSStaticFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStaticFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStaticFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStaticFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStaticFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyNamesCallback/title",
          "value": "JSObjectGetPropertyNamesCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyNamesCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetPropertyNamesCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyNamesCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetPropertyNamesCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsConstructorCallback/title",
          "value": "JSObjectCallAsConstructorCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsConstructorCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectCallAsConstructorCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsConstructorCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectCallAsConstructorCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunctionCallback/title",
          "value": "JSObjectCallAsFunctionCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunctionCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectCallAsFunctionCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunctionCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectCallAsFunctionCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition/title",
          "value": "JSClassDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassAttributes/title",
          "value": "JSClassAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectFinalizeCallback/title",
          "value": "JSObjectFinalizeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectFinalizeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectFinalizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectFinalizeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectFinalizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasPropertyCallback/title",
          "value": "JSObjectHasPropertyCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasPropertyCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectHasPropertyCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasPropertyCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectHasPropertyCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jsclassdefinition/init(version:attributes:classname:parentclass:staticvalues:staticfunctions:initialize:finalize:hasproperty:getproperty:setproperty:deleteproperty:getpropertynames:callasfunction:callasconstructor:hasinstance:converttotype:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
