{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "code": "IMKStateSetting",
      "type": "codeVoice"
    },
    {
      "text": " protocol defines methods for setting or accessing values that indicate the state of an input method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)IMKStateSetting",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IMKStateSetting"
      }
    ],
    "modules": [
      {
        "name": "InputMethodKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IMKStateSetting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "IMKStateSetting"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IMKStateSetting"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit": {
      "abstract": [
        {
          "text": "Develop input methods and manage communication with client applications, candidates windows, and input method modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
      "kind": "symbol",
      "role": "collection",
      "title": "InputMethodKit",
      "type": "topic",
      "url": "/documentation/inputmethodkit"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IMKInputController",
          "type": "codeVoice"
        },
        {
          "text": " class provides a base class for custom input controller classes. The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKServer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "  class, which is allocated in the main function of an input method, creates an input controller object for each input session created by a client application. For every input session there is a corresponding ",
          "type": "text"
        },
        {
          "code": "IMKInputController",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKInputController"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKInputController"
        }
      ],
      "role": "symbol",
      "title": "IMKInputController",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkinputcontroller"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKMouseHandling": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IMKMouseHandling",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines methods that your input method can implement to handle mouse events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKMouseHandling"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKMouseHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKMouseHandling"
        }
      ],
      "role": "symbol",
      "title": "IMKMouseHandling",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkmousehandling"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKServer": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IMKServer",
          "type": "codeVoice"
        },
        {
          "text": " class manages client connections to your input method.  When you write the main function for your input method, you create an ",
          "type": "text"
        },
        {
          "code": "IMKServer",
          "type": "codeVoice"
        },
        {
          "text": " object.  You should never need to override this class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKServer"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKServer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKServer"
        }
      ],
      "role": "symbol",
      "title": "IMKServer",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkserver"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IMKStateSetting",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines methods for setting or accessing values that indicate the state of an input method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKStateSetting"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKStateSetting"
        }
      ],
      "role": "symbol",
      "title": "IMKStateSetting",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkstatesetting"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/activateServer(_:)": {
      "abstract": [
        {
          "text": "Activates the input method server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activateServer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/activateServer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activateServer:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "activateServer(_:)",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkstatesetting/activateserver(_:)"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/deactivateServer(_:)": {
      "abstract": [
        {
          "text": "Deactivates the input method server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deactivateServer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/deactivateServer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deactivateServer:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "deactivateServer(_:)",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkstatesetting/deactivateserver(_:)"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/modes(_:)": {
      "abstract": [
        {
          "text": "Returns the modes dictionary associated with the input method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/modes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modes:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "modes(_:)",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkstatesetting/modes(_:)"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/recognizedEvents(_:)": {
      "abstract": [
        {
          "text": "Returns an unsigned integer that contains a union of event masks",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizedEvents"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/recognizedEvents(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recognizedEvents:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "recognizedEvents(_:)",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkstatesetting/recognizedevents(_:)"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/setValue(_:forTag:client:)": {
      "abstract": [
        {
          "text": "Set the value for the provided key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "forTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "client"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/setValue(_:forTag:client:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setValue:forTag:client:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setValue(_:forTag:client:)",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkstatesetting/setvalue(_:fortag:client:)"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/showPreferences(_:)": {
      "abstract": [
        {
          "text": "Displays a preferences window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showPreferences"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/showPreferences(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showPreferences:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "showPreferences(_:)",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkstatesetting/showpreferences(_:)"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/value(forTag:client:)": {
      "abstract": [
        {
          "text": "Returns a value object whose key is the provided tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "client"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/value(forTag:client:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForTag:client:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "value(forTag:client:)",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkstatesetting/value(fortag:client:)"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/imkserverinput": {
      "abstract": [
        {
          "code": "IMKServerInput",
          "type": "codeVoice"
        },
        {
          "text": " is an informal protocol that defines methods for receiving text events. This is intentionally not a formal protocol because there are three ways to receive events. An input method chooses one of the following approaches and implements the appropriate methods:",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/imkserverinput",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IMKServerInput",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkserverinput"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKMouseHandling",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/imkserverinput"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Activating-and-Deactivating-the-Server",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/activateServer(_:)",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/deactivateServer(_:)"
      ],
      "title": "Activating and Deactivating the Server"
    },
    {
      "anchor": "Showing-a-Preferences-Window",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/showPreferences(_:)"
      ],
      "title": "Showing a Preferences Window"
    },
    {
      "anchor": "Getting-the-Supported-Events",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/recognizedEvents(_:)"
      ],
      "title": "Getting the Supported Events"
    },
    {
      "anchor": "Getting-the-Mode-Dictionary",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/modes(_:)"
      ],
      "title": "Getting the Mode Dictionary"
    },
    {
      "anchor": "Getting-and-Setting-Values",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/value(forTag:client:)",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/setValue(_:forTag:client:)"
      ],
      "title": "Getting and Setting Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IMKStateSetting"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKStateSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKStateSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Activating-and-Deactivating-the-Server",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/activateServer(_:)",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/deactivateServer(_:)"
              ],
              "title": "Activating and Deactivating the Server"
            },
            {
              "anchor": "Showing-a-Preferences-Window",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/showPreferences(_:)"
              ],
              "title": "Showing a Preferences Window"
            },
            {
              "anchor": "Getting-the-Supported-Events",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/recognizedEvents(_:)"
              ],
              "title": "Getting the Supported Events"
            },
            {
              "anchor": "Getting-the-Mode-Dictionary",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/modes(_:)"
              ],
              "title": "Getting the Mode Dictionary"
            },
            {
              "anchor": "Getting-and-Setting-Values",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/value(forTag:client:)",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStateSetting/setValue(_:forTag:client:)"
              ],
              "title": "Getting and Setting Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKMouseHandling",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/imkserverinput"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IMKStateSetting"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1activateServer(_:)/title",
          "value": "activateServer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1activateServer(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activateServer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1value(forTag:client:)/title",
          "value": "valueForTag:client:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1value(forTag:client:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueForTag:client:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting/title",
          "value": "IMKStateSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKStateSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKStateSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1modes(_:)/title",
          "value": "modes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1modes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "modes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKMouseHandling/title",
          "value": "IMKMouseHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKMouseHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKMouseHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKMouseHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKMouseHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1showPreferences(_:)/title",
          "value": "showPreferences:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1showPreferences(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showPreferences:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1setValue(_:forTag:client:)/title",
          "value": "setValue:forTag:client:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1setValue(_:forTag:client:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setValue:forTag:client:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController/title",
          "value": "IMKInputController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKInputController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKInputController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKServer/title",
          "value": "IMKServer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKServer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKServer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1recognizedEvents(_:)/title",
          "value": "recognizedEvents:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1recognizedEvents(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recognizedEvents:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1deactivateServer(_:)/title",
          "value": "deactivateServer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStateSetting~1deactivateServer(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deactivateServer:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/inputmethodkit/imkstatesetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/inputmethodkit/imkstatesetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
