{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448307-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "InputMethodKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit": {
      "abstract": [
        {
          "text": "Develop input methods and manage communication with client applications, candidates windows, and input method modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
      "kind": "symbol",
      "role": "collection",
      "title": "InputMethodKit",
      "type": "topic",
      "url": "/documentation/inputmethodkit"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "InputMethodKit Enumerations",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448298-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448298-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations-1448298-anonymous"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations-1448301-anonymous"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKScrollingGridCandidatePanel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIMKScrollingGridCandidatePanel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKScrollingGridCandidatePanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIMKScrollingGridCandidatePanel"
        }
      ],
      "role": "symbol",
      "title": "kIMKScrollingGridCandidatePanel",
      "type": "topic",
      "url": "/documentation/inputmethodkit/kimkscrollinggridcandidatepanel"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKSingleColumnScrollingCandidatePanel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIMKSingleColumnScrollingCandidatePanel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKSingleColumnScrollingCandidatePanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIMKSingleColumnScrollingCandidatePanel"
        }
      ],
      "role": "symbol",
      "title": "kIMKSingleColumnScrollingCandidatePanel",
      "type": "topic",
      "url": "/documentation/inputmethodkit/kimksinglecolumnscrollingcandidatepanel"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKSingleRowSteppingCandidatePanel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIMKSingleRowSteppingCandidatePanel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKSingleRowSteppingCandidatePanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIMKSingleRowSteppingCandidatePanel"
        }
      ],
      "role": "symbol",
      "title": "kIMKSingleRowSteppingCandidatePanel",
      "type": "topic",
      "url": "/documentation/inputmethodkit/kimksinglerowsteppingcandidatepanel"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448298-anonymous",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKScrollingGridCandidatePanel",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKSingleColumnScrollingCandidatePanel",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKSingleRowSteppingCandidatePanel"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKScrollingGridCandidatePanel",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKSingleColumnScrollingCandidatePanel",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKSingleRowSteppingCandidatePanel"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448298-anonymous",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKSingleColumnScrollingCandidatePanel/title",
          "value": "kIMKSingleColumnScrollingCandidatePanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKSingleColumnScrollingCandidatePanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIMKSingleColumnScrollingCandidatePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKScrollingGridCandidatePanel/title",
          "value": "kIMKScrollingGridCandidatePanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKScrollingGridCandidatePanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIMKScrollingGridCandidatePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKSingleRowSteppingCandidatePanel/title",
          "value": "kIMKSingleRowSteppingCandidatePanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKSingleRowSteppingCandidatePanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIMKSingleRowSteppingCandidatePanel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-enumerations-1448307-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-enumerations-1448307-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
