{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "InputMethodKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "InputMethodKit Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit": {
      "abstract": [
        {
          "text": "Develop input methods and manage communication with client applications, candidates windows, and input method modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
      "kind": "symbol",
      "role": "collection",
      "title": "InputMethodKit",
      "type": "topic",
      "url": "/documentation/inputmethodkit"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesOpacityAttributeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKCandidatesOpacityAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesOpacityAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKCandidatesOpacityAttributeName"
        }
      ],
      "role": "symbol",
      "title": "IMKCandidatesOpacityAttributeName",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkcandidatesopacityattributename"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesSendServerKeyEventFirst": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKCandidatesSendServerKeyEventFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesSendServerKeyEventFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKCandidatesSendServerKeyEventFirst"
        }
      ],
      "role": "symbol",
      "title": "IMKCandidatesSendServerKeyEventFirst",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkcandidatessendserverkeyeventfirst"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKControllerClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKControllerClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKControllerClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKControllerClass"
        }
      ],
      "role": "symbol",
      "title": "IMKControllerClass",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkcontrollerclass"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKDelegateClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKDelegateClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKDelegateClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKDelegateClass"
        }
      ],
      "role": "symbol",
      "title": "IMKDelegateClass",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkdelegateclass"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKModeDictionary": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKModeDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKModeDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKModeDictionary"
        }
      ],
      "role": "symbol",
      "title": "IMKModeDictionary",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkmodedictionary"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-data_types": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-data_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "InputMethodKit Data Types",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-data_types"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "InputMethodKit Enumerations",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-data_types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesOpacityAttributeName",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesSendServerKeyEventFirst",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKControllerClass",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKDelegateClass",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKModeDictionary"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesOpacityAttributeName",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesSendServerKeyEventFirst",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKControllerClass",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKDelegateClass",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKModeDictionary"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-data_types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatesSendServerKeyEventFirst/title",
          "value": "IMKCandidatesSendServerKeyEventFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatesSendServerKeyEventFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKCandidatesSendServerKeyEventFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKDelegateClass/title",
          "value": "IMKDelegateClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKDelegateClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKDelegateClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatesOpacityAttributeName/title",
          "value": "IMKCandidatesOpacityAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatesOpacityAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKCandidatesOpacityAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKModeDictionary/title",
          "value": "IMKModeDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKModeDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKModeDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKControllerClass/title",
          "value": "IMKControllerClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKControllerClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKControllerClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
