{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-data_types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "InputMethodKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "InputMethodKit Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit": {
      "abstract": [
        {
          "text": "Develop input methods and manage communication with client applications, candidates windows, and input method modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
      "kind": "symbol",
      "role": "collection",
      "title": "InputMethodKit",
      "type": "topic",
      "url": "/documentation/inputmethodkit"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatePanelType": {
      "abstract": [
        {
          "text": "Types of candidates windows provide by the Input Method Kit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKCandidatePanelType"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatePanelType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKCandidatePanelType"
        }
      ],
      "role": "symbol",
      "title": "IMKCandidatePanelType",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkcandidatepaneltype"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesLocationHint": {
      "abstract": [
        {
          "text": "Hints that suggest where to place the candidates window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKCandidatesLocationHint"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesLocationHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKCandidatesLocationHint"
        }
      ],
      "role": "symbol",
      "title": "IMKCandidatesLocationHint",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkcandidateslocationhint"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStyleType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKStyleType"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStyleType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKStyleType"
        }
      ],
      "role": "symbol",
      "title": "IMKStyleType",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkstyletype"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "InputMethodKit Constants",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-constants"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "InputMethodKit Enumerations",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatePanelType",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesLocationHint",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStyleType"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatePanelType",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKCandidatesLocationHint",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKStyleType"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatesLocationHint/title",
          "value": "IMKCandidatesLocationHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatesLocationHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKCandidatesLocationHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatesLocationHint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKCandidatesLocationHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatePanelType/title",
          "value": "IMKCandidatePanelType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatePanelType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKCandidatePanelType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKCandidatePanelType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKCandidatePanelType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStyleType/title",
          "value": "IMKStyleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStyleType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKStyleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKStyleType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKStyleType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-data_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-data_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
