{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448298-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "InputMethodKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit": {
      "abstract": [
        {
          "text": "Develop input methods and manage communication with client applications, candidates windows, and input method modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
      "kind": "symbol",
      "role": "collection",
      "title": "InputMethodKit",
      "type": "topic",
      "url": "/documentation/inputmethodkit"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "InputMethodKit Enumerations",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations-1448301-anonymous"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448307-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448307-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations-1448307-anonymous"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesAboveHint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIMKLocateCandidatesAboveHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesAboveHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIMKLocateCandidatesAboveHint"
        }
      ],
      "role": "symbol",
      "title": "kIMKLocateCandidatesAboveHint",
      "type": "topic",
      "url": "/documentation/inputmethodkit/kimklocatecandidatesabovehint"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesBelowHint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIMKLocateCandidatesBelowHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesBelowHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIMKLocateCandidatesBelowHint"
        }
      ],
      "role": "symbol",
      "title": "kIMKLocateCandidatesBelowHint",
      "type": "topic",
      "url": "/documentation/inputmethodkit/kimklocatecandidatesbelowhint"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesLeftHint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIMKLocateCandidatesLeftHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesLeftHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIMKLocateCandidatesLeftHint"
        }
      ],
      "role": "symbol",
      "title": "kIMKLocateCandidatesLeftHint",
      "type": "topic",
      "url": "/documentation/inputmethodkit/kimklocatecandidateslefthint"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesRightHint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIMKLocateCandidatesRightHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesRightHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIMKLocateCandidatesRightHint"
        }
      ],
      "role": "symbol",
      "title": "kIMKLocateCandidatesRightHint",
      "type": "topic",
      "url": "/documentation/inputmethodkit/kimklocatecandidatesrighthint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448307-anonymous",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesAboveHint",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesBelowHint",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesLeftHint",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesRightHint"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesAboveHint",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesBelowHint",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesLeftHint",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKLocateCandidatesRightHint"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448307-anonymous",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKLocateCandidatesLeftHint/title",
          "value": "kIMKLocateCandidatesLeftHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKLocateCandidatesLeftHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIMKLocateCandidatesLeftHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKLocateCandidatesBelowHint/title",
          "value": "kIMKLocateCandidatesBelowHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKLocateCandidatesBelowHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIMKLocateCandidatesBelowHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKLocateCandidatesAboveHint/title",
          "value": "kIMKLocateCandidatesAboveHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKLocateCandidatesAboveHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIMKLocateCandidatesAboveHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKLocateCandidatesRightHint/title",
          "value": "kIMKLocateCandidatesRightHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKLocateCandidatesRightHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIMKLocateCandidatesRightHint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-enumerations-1448298-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-enumerations-1448298-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
