{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "InputMethodKit"
      }
    ],
    "role": "collectionGroup",
    "title": "InputMethodKit Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit": {
      "abstract": [
        {
          "text": "Develop input methods and manage communication with client applications, candidates windows, and input method modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
      "kind": "symbol",
      "role": "collection",
      "title": "InputMethodKit",
      "type": "topic",
      "url": "/documentation/inputmethodkit"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "InputMethodKit Constants",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-constants"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-data_types": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-data_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "InputMethodKit Data Types",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-data_types"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448298-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448298-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations-1448298-anonymous"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations-1448301-anonymous"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448307-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448307-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/inputmethodkit/inputmethodkit-enumerations-1448307-anonymous"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-constants",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-data_types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448298-anonymous",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448307-anonymous",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448298-anonymous",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448307-anonymous",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-enumerations-1448301-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-constants",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/inputmethodkit-data_types"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/inputmethodkit/inputmethodkit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
