{
  "abstract": [
    {
      "text": "Tells the delegate that the manager completed the request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemextensions/documentation/SystemExtensions",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate/request(_:didFinishWithResult:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)OSSystemExtensionRequestDelegate(im)request:didFinishWithResult:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "request"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)OSSystemExtensionRequest",
        "text": "OSSystemExtensionRequest"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didFinishWithResult"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)OSSystemExtensionRequest",
        "text": "OSSystemExtensionRequest"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OSSystemExtensionRequestResult",
        "text": "Result"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "System Extensions"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "request:didFinishWithResult:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "request(_:didFinishWithResult:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "request"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "request"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)OSSystemExtensionRequest",
              "text": "OSSystemExtensionRequest"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didFinishWithResult"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "result"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)OSSystemExtensionRequest",
              "text": "OSSystemExtensionRequest"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest/Result",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OSSystemExtensionRequestResult",
              "text": "Result"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The request that completed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "request"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Additional information about the completion state.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "result"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the request completes with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest/Result/willCompleteAfterReboot",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " result, then the extension isn’t active until after the next restart. After restarting, the most recently-processed request determines the extension’s state. Consider the following scenarios:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Activate extension and restart: the extension is active upon restarting.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Activate extension, deactivate extension, and restart: the extension is inactive upon restarting.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions": {
      "abstract": [
        {
          "text": "Install and manage user space code that extends the capabilities of macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions",
      "kind": "symbol",
      "role": "collection",
      "title": "System Extensions",
      "type": "topic",
      "url": "/documentation/systemextensions"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest": {
      "abstract": [
        {
          "text": "A request to activate or deactivate a system extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionRequest"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionRequest"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionRequest",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionrequest"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest/Result": {
      "abstract": [
        {
          "text": "The result of a completed request, possibly including additional information about the extension’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest/Result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionRequest.Result",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionrequest/result"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest/Result/willCompleteAfterReboot": {
      "abstract": [
        {
          "text": "The request requires a restart to complete successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willCompleteAfterReboot"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest/Result/willCompleteAfterReboot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionRequestWillCompleteAfterReboot"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionRequest.Result.willCompleteAfterReboot",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionrequest/result/willcompleteafterreboot"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate": {
      "abstract": [
        {
          "text": "A type that receives updates about the progress of a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionRequestDelegate"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionRequestDelegate"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionRequestDelegate",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionrequestdelegate"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate/request(_:didFailWithError:)": {
      "abstract": [
        {
          "text": "Tells the delegate the manager failed to complete the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "request"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSSystemExtensionRequest",
          "text": "OSSystemExtensionRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate/request(_:didFailWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "request:didFailWithError:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "request(_:didFailWithError:)",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionrequestdelegate/request(_:didfailwitherror:)"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate/request(_:didFinishWithResult:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the manager completed the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "request"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSSystemExtensionRequest",
          "text": "OSSystemExtensionRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishWithResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSSystemExtensionRequest",
          "text": "OSSystemExtensionRequest"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionRequestResult",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate/request(_:didFinishWithResult:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "request:didFinishWithResult:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "request(_:didFinishWithResult:)",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionrequestdelegate/request(_:didfinishwithresult:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Success-and-Failure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest/Result",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate/request(_:didFailWithError:)"
      ],
      "title": "Handling Success and Failure"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "request:didFinishWithResult:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "request:didFinishWithResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemextensions/documentation/SystemExtensions",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Success-and-Failure",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest/Result",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequestDelegate/request(_:didFailWithError:)"
              ],
              "title": "Handling Success and Failure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "request:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)OSSystemExtensionRequest",
                    "text": "OSSystemExtensionRequest"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "request"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didFinishWithResult:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest/Result",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@OSSystemExtensionRequestResult",
                    "text": "OSSystemExtensionRequestResult"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "result"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The request that completed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "request"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Additional information about the completion state.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "result"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest~1Result~1willCompleteAfterReboot/title",
          "value": "OSSystemExtensionRequestWillCompleteAfterReboot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest~1Result~1willCompleteAfterReboot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionRequestWillCompleteAfterReboot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest/title",
          "value": "OSSystemExtensionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequestDelegate~1request(_:didFinishWithResult:)/title",
          "value": "request:didFinishWithResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequestDelegate~1request(_:didFinishWithResult:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "request:didFinishWithResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest~1Result/title",
          "value": "OSSystemExtensionRequestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest~1Result/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionRequestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest~1Result/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionRequestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequestDelegate/title",
          "value": "OSSystemExtensionRequestDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequestDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionRequestDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequestDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionRequestDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequestDelegate~1request(_:didFailWithError:)/title",
          "value": "request:didFailWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequestDelegate~1request(_:didFailWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "request:didFailWithError:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemextensions/ossystemextensionrequestdelegate/request(_:didfinishwithresult:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemextensions/ossystemextensionrequestdelegate/request(_:didfinishwithresult:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
