{
  "abstract": [
    {
      "text": "An algorithm to use when the source data doesn’t need localization.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/stereoPassThrough"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudio3DMixingRenderingAlgorithm@AVAudio3DMixingRenderingAlgorithmStereoPassThrough",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "stereoPassThrough"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVAudio3DMixingRenderingAlgorithm.stereoPassThrough"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "stereoPassThrough"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This takes mono and stereo input and passes it to channels 1 and 2 without localization. If the input and output ",
              "type": "text"
            },
            {
              "code": "AudioChannelLayout",
              "type": "codeVoice"
            },
            {
              "text": " differ, mixing happens according to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/kAudioFormatProperty_MatrixMixMap",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the layouts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm": {
      "abstract": [
        {
          "text": "The types of rendering algorithms available per input bus of the environment node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTF": {
      "abstract": [
        {
          "text": "A high-quality algorithm that uses filtering to emulate 3D space in headphones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HRTF"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmHRTF"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.HRTF",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/hrtf"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTFHQ": {
      "abstract": [
        {
          "text": "A higher-quality head-related transfer function rendering algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HRTFHQ"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTFHQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmHRTFHQ"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.HRTFHQ",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/hrtfhq"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/auto": {
      "abstract": [
        {
          "text": "Automatically selects the highest-quality rendering algorithm available for the current playback hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmAuto"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.auto",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/auto"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/equalPowerPanning": {
      "abstract": [
        {
          "text": "An algorithm that pans the data of the mixer bus into a stereo field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "equalPowerPanning"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/equalPowerPanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmEqualPowerPanning"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.equalPowerPanning",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/equalpowerpanning"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/soundField": {
      "abstract": [
        {
          "text": "An algorithm that renders to multichannel hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "soundField"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/soundField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmSoundField"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.soundField",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/soundfield"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/sphericalHead": {
      "abstract": [
        {
          "text": "An algorithm that emulates 3D space in headphones by simulating interaural time delays and other spatial cues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sphericalHead"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/sphericalHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmSphericalHead"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.sphericalHead",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/sphericalhead"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/stereoPassThrough": {
      "abstract": [
        {
          "text": "An algorithm to use when the source data doesn’t need localization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stereoPassThrough"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/stereoPassThrough",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.stereoPassThrough",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/stereopassthrough"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/kAudioFormatProperty_MatrixMixMap": {
      "abstract": [
        {
          "text": "A matrix of scaling coefficients for converting audio from one channel map to another in a standard way, if one is known. Otherwise, an error is returned. Set the `inSpecifier` parameter to an array of two pointers to `AudioChannelLayout` structures. The first points to the input layout, the second to the output layout. The value is a two dimensional array of `Float32` values, where the first dimension (rows) is the input channel and the second dimension (columns) is the output channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatProperty_MatrixMixMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatPropertyID",
          "text": "AudioFormatPropertyID"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/kAudioFormatProperty_MatrixMixMap",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioFormatProperty_MatrixMixMap",
      "type": "topic",
      "url": "/documentation/AudioToolbox/kAudioFormatProperty_MatrixMixMap"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Rendering-Algorithms",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/auto",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/equalPowerPanning",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTF",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTFHQ",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/soundField",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/sphericalHead"
      ],
      "title": "Rendering Algorithms"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Rendering-Algorithms",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/auto",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/equalPowerPanning",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTF",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTFHQ",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/soundField",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/sphericalHead"
              ],
              "title": "Rendering Algorithms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1auto/title",
          "value": "AVAudio3DMixingRenderingAlgorithmAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1equalPowerPanning/title",
          "value": "AVAudio3DMixingRenderingAlgorithmEqualPowerPanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1equalPowerPanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmEqualPowerPanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1sphericalHead/title",
          "value": "AVAudio3DMixingRenderingAlgorithmSphericalHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1sphericalHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmSphericalHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1HRTFHQ/title",
          "value": "AVAudio3DMixingRenderingAlgorithmHRTFHQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1HRTFHQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmHRTFHQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/title",
          "value": "AVAudio3DMixingRenderingAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1kAudioFormatProperty_MatrixMixMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatProperty_MatrixMixMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1soundField/title",
          "value": "AVAudio3DMixingRenderingAlgorithmSoundField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1soundField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmSoundField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1stereoPassThrough/title",
          "value": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1stereoPassThrough/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1HRTF/title",
          "value": "AVAudio3DMixingRenderingAlgorithmHRTF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1HRTF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmHRTF"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/stereopassthrough"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/stereopassthrough"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
