{
  "abstract": [
    {
      "text": "The keyboard code for the Home key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/home"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "GameController",
    "externalID": "c:@GCKeyCodeHome",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "home"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@GCKeyCode",
        "text": "GCKeyCode"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCKeyCodeHome"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "home"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "home"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GCKeyCode",
              "text": "GCKeyCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode": {
      "abstract": [
        {
          "text": "The key codes for keys on a keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCode"
        }
      ],
      "role": "symbol",
      "title": "GCKeyCode",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/deleteForward": {
      "abstract": [
        {
          "text": "The keyboard code for the Delete-Forward key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteForward"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/deleteForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeDeleteForward"
        }
      ],
      "role": "symbol",
      "title": "deleteForward",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/deleteforward"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/downArrow": {
      "abstract": [
        {
          "text": "The keyboard code for the Down Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/downArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeDownArrow"
        }
      ],
      "role": "symbol",
      "title": "downArrow",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/downarrow"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/end": {
      "abstract": [
        {
          "text": "The keyboard code for the End key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/end",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeEnd"
        }
      ],
      "role": "symbol",
      "title": "end",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/end"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/home": {
      "abstract": [
        {
          "text": "The keyboard code for the Home key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeHome"
        }
      ],
      "role": "symbol",
      "title": "home",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/home"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/insert": {
      "abstract": [
        {
          "text": "The keyboard code for the Insert key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/insert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeInsert"
        }
      ],
      "role": "symbol",
      "title": "insert",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/insert"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/leftArrow": {
      "abstract": [
        {
          "text": "The keyboard code for the Left Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/leftArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeLeftArrow"
        }
      ],
      "role": "symbol",
      "title": "leftArrow",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/leftarrow"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pageDown": {
      "abstract": [
        {
          "text": "The keyboard code for the Page Down key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pageDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodePageDown"
        }
      ],
      "role": "symbol",
      "title": "pageDown",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/pagedown"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pageUp": {
      "abstract": [
        {
          "text": "The keyboard code for the Page Up key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pageUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodePageUp"
        }
      ],
      "role": "symbol",
      "title": "pageUp",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/pageup"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pause": {
      "abstract": [
        {
          "text": "The keyboard code for the Pause key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodePause"
        }
      ],
      "role": "symbol",
      "title": "pause",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/pause"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/printScreen": {
      "abstract": [
        {
          "text": "The keyboard code for the Print Screen key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/printScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodePrintScreen"
        }
      ],
      "role": "symbol",
      "title": "printScreen",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/printscreen"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/rightArrow": {
      "abstract": [
        {
          "text": "The keyboard code for the Right Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/rightArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeRightArrow"
        }
      ],
      "role": "symbol",
      "title": "rightArrow",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/rightarrow"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/scrollLock": {
      "abstract": [
        {
          "text": "The keyboard code for the Scroll Lock key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/scrollLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeScrollLock"
        }
      ],
      "role": "symbol",
      "title": "scrollLock",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/scrolllock"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/upArrow": {
      "abstract": [
        {
          "text": "The keyboard code for the Up Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/upArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeUpArrow"
        }
      ],
      "role": "symbol",
      "title": "upArrow",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/uparrow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Directional-and-Similar-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/printScreen",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/scrollLock",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pause",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/insert",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pageUp",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/deleteForward",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/end",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pageDown",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/rightArrow",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/leftArrow",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/downArrow",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/upArrow"
      ],
      "title": "Directional and Similar Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCKeyCodeHome"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Directional-and-Similar-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/printScreen",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/scrollLock",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pause",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/insert",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pageUp",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/deleteForward",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/end",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/pageDown",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/rightArrow",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/leftArrow",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/downArrow",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/upArrow"
              ],
              "title": "Directional and Similar Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@GCKeyCode",
                    "text": "GCKeyCode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCKeyCodeHome"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1upArrow/title",
          "value": "GCKeyCodeUpArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1upArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeUpArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1pageUp/title",
          "value": "GCKeyCodePageUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1pageUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodePageUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1pause/title",
          "value": "GCKeyCodePause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1pause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodePause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1deleteForward/title",
          "value": "GCKeyCodeDeleteForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1deleteForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeDeleteForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1end/title",
          "value": "GCKeyCodeEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1end/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1insert/title",
          "value": "GCKeyCodeInsert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1insert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeInsert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/title",
          "value": "GCKeyCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1home/title",
          "value": "GCKeyCodeHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1downArrow/title",
          "value": "GCKeyCodeDownArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1downArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeDownArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1printScreen/title",
          "value": "GCKeyCodePrintScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1printScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodePrintScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1rightArrow/title",
          "value": "GCKeyCodeRightArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1rightArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeRightArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1scrollLock/title",
          "value": "GCKeyCodeScrollLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1scrollLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeScrollLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1leftArrow/title",
          "value": "GCKeyCodeLeftArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1leftArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeLeftArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1pageDown/title",
          "value": "GCKeyCodePageDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1pageDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodePageDown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gckeycode/home"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gckeycode/home"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
