{
  "abstract": [
    {
      "text": "The keyboard code for the keypad 7 or Home key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad7"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "GameController",
    "externalID": "c:@GCKeyCodeKeypad7",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "keypad7"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@GCKeyCode",
        "text": "GCKeyCode"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCKeyCodeKeypad7"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "keypad7"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "keypad7"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GCKeyCode",
              "text": "GCKeyCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode": {
      "abstract": [
        {
          "text": "The key codes for keys on a keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCode"
        }
      ],
      "role": "symbol",
      "title": "GCKeyCode",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad0": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 0 or Insert key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad0"
        }
      ],
      "role": "symbol",
      "title": "keypad0",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad0"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad1": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 1 or End key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad1"
        }
      ],
      "role": "symbol",
      "title": "keypad1",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad1"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad2": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 2 or Down Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad2"
        }
      ],
      "role": "symbol",
      "title": "keypad2",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad2"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad3": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 3 or Page Down key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad3"
        }
      ],
      "role": "symbol",
      "title": "keypad3",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad3"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad4": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 4 or Left Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad4"
        }
      ],
      "role": "symbol",
      "title": "keypad4",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad4"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad5": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 5 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad5"
        }
      ],
      "role": "symbol",
      "title": "keypad5",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad5"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad6": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 6 or Right Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad6"
        }
      ],
      "role": "symbol",
      "title": "keypad6",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad6"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad7": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 7 or Home key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad7"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad7"
        }
      ],
      "role": "symbol",
      "title": "keypad7",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad7"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad8": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 8 or Up Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad8"
        }
      ],
      "role": "symbol",
      "title": "keypad8",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad8"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad9": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 9 or Page Up key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypad9"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypad9"
        }
      ],
      "role": "symbol",
      "title": "keypad9",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypad9"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadAsterisk": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad * key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypadAsterisk"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadAsterisk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypadAsterisk"
        }
      ],
      "role": "symbol",
      "title": "keypadAsterisk",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypadasterisk"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadEnter": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad Enter key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypadEnter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadEnter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypadEnter"
        }
      ],
      "role": "symbol",
      "title": "keypadEnter",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypadenter"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadHyphen": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad - key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypadHyphen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadHyphen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypadHyphen"
        }
      ],
      "role": "symbol",
      "title": "keypadHyphen",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypadhyphen"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadNumLock": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad Num Lock or Clear key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypadNumLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadNumLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypadNumLock"
        }
      ],
      "role": "symbol",
      "title": "keypadNumLock",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypadnumlock"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadPlus": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad + key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypadPlus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadPlus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypadPlus"
        }
      ],
      "role": "symbol",
      "title": "keypadPlus",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypadplus"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadSlash": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad / key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keypadSlash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadSlash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeypadSlash"
        }
      ],
      "role": "symbol",
      "title": "keypadSlash",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keypadslash"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Keypad-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadNumLock",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadSlash",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadAsterisk",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadHyphen",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadPlus",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadEnter",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad1",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad2",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad3",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad4",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad5",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad6",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad8",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad9",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad0"
      ],
      "title": "Keypad Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCKeyCodeKeypad7"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Keypad-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadNumLock",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadSlash",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadAsterisk",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadHyphen",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadPlus",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypadEnter",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad1",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad2",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad3",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad4",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad5",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad6",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad8",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad9",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keypad0"
              ],
              "title": "Keypad Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@GCKeyCode",
                    "text": "GCKeyCode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCKeyCodeKeypad7"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadAsterisk/title",
          "value": "GCKeyCodeKeypadAsterisk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadAsterisk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypadAsterisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadPlus/title",
          "value": "GCKeyCodeKeypadPlus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadPlus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypadPlus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/title",
          "value": "GCKeyCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad4/title",
          "value": "GCKeyCodeKeypad4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadHyphen/title",
          "value": "GCKeyCodeKeypadHyphen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadHyphen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypadHyphen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad8/title",
          "value": "GCKeyCodeKeypad8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad7/title",
          "value": "GCKeyCodeKeypad7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad9/title",
          "value": "GCKeyCodeKeypad9"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad9"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadNumLock/title",
          "value": "GCKeyCodeKeypadNumLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadNumLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypadNumLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad6/title",
          "value": "GCKeyCodeKeypad6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad5/title",
          "value": "GCKeyCodeKeypad5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad3/title",
          "value": "GCKeyCodeKeypad3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad1/title",
          "value": "GCKeyCodeKeypad1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadEnter/title",
          "value": "GCKeyCodeKeypadEnter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadEnter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypadEnter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad0/title",
          "value": "GCKeyCodeKeypad0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad2/title",
          "value": "GCKeyCodeKeypad2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypad2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypad2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadSlash/title",
          "value": "GCKeyCodeKeypadSlash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keypadSlash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeypadSlash"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gckeycode/keypad7"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gckeycode/keypad7"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
