{
  "abstract": [
    {
      "text": "The keyboard code for the z or Z character.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyZ"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "GameController",
    "externalID": "c:@GCKeyCodeKeyZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "keyZ"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@GCKeyCode",
        "text": "GCKeyCode"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCKeyCodeKeyZ"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "keyZ"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "keyZ"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GCKeyCode",
              "text": "GCKeyCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode": {
      "abstract": [
        {
          "text": "The key codes for keys on a keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCode"
        }
      ],
      "role": "symbol",
      "title": "GCKeyCode",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyA": {
      "abstract": [
        {
          "text": "The keyboard code for the a or A character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyA"
        }
      ],
      "role": "symbol",
      "title": "keyA",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keya"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyB": {
      "abstract": [
        {
          "text": "The keyboard code for the b or B character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyB"
        }
      ],
      "role": "symbol",
      "title": "keyB",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyb"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyC": {
      "abstract": [
        {
          "text": "The keyboard code for the c or C character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyC"
        }
      ],
      "role": "symbol",
      "title": "keyC",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyc"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyD": {
      "abstract": [
        {
          "text": "The keyboard code for the d or D character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyD"
        }
      ],
      "role": "symbol",
      "title": "keyD",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyd"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyE": {
      "abstract": [
        {
          "text": "The keyboard code for the e or E character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyE"
        }
      ],
      "role": "symbol",
      "title": "keyE",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keye"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyF": {
      "abstract": [
        {
          "text": "The keyboard code for the f or F character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyF"
        }
      ],
      "role": "symbol",
      "title": "keyF",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyf"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyG": {
      "abstract": [
        {
          "text": "The keyboard code for the g or G character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyG"
        }
      ],
      "role": "symbol",
      "title": "keyG",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyg"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyH": {
      "abstract": [
        {
          "text": "The keyboard code for the h or H character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyH"
        }
      ],
      "role": "symbol",
      "title": "keyH",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyh"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyI": {
      "abstract": [
        {
          "text": "The keyboard code for the i or I character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyI"
        }
      ],
      "role": "symbol",
      "title": "keyI",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyi"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyJ": {
      "abstract": [
        {
          "text": "The keyboard code for the j or J character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyJ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyJ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyJ"
        }
      ],
      "role": "symbol",
      "title": "keyJ",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyj"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyK": {
      "abstract": [
        {
          "text": "The keyboard code for the k or K character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyK"
        }
      ],
      "role": "symbol",
      "title": "keyK",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyk"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyL": {
      "abstract": [
        {
          "text": "The keyboard code for the l or L character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyL"
        }
      ],
      "role": "symbol",
      "title": "keyL",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyl"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyM": {
      "abstract": [
        {
          "text": "The keyboard code for the m or M character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyM"
        }
      ],
      "role": "symbol",
      "title": "keyM",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keym"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyN": {
      "abstract": [
        {
          "text": "The keyboard code for the n or N character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyN"
        }
      ],
      "role": "symbol",
      "title": "keyN",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyn"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyO": {
      "abstract": [
        {
          "text": "The keyboard code for the o or O character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyO"
        }
      ],
      "role": "symbol",
      "title": "keyO",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyo"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyZ": {
      "abstract": [
        {
          "text": "The keyboard code for the z or Z character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCodeKeyZ"
        }
      ],
      "role": "symbol",
      "title": "keyZ",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode/keyz"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Letter-and-Number-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyA",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyB",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyC",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyD",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyE",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyF",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyG",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyH",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyI",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyJ",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyK",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyL",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyM",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyN",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyO"
      ],
      "title": "Letter and Number Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCKeyCodeKeyZ"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Letter-and-Number-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyA",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyB",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyC",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyD",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyE",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyF",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyG",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyH",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyI",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyJ",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyK",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyL",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyM",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyN",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode/keyO"
              ],
              "title": "Letter and Number Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@GCKeyCode",
                    "text": "GCKeyCode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCKeyCodeKeyZ"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyE/title",
          "value": "GCKeyCodeKeyE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyG/title",
          "value": "GCKeyCodeKeyG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyF/title",
          "value": "GCKeyCodeKeyF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyD/title",
          "value": "GCKeyCodeKeyD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyA/title",
          "value": "GCKeyCodeKeyA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyI/title",
          "value": "GCKeyCodeKeyI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyN/title",
          "value": "GCKeyCodeKeyN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyJ/title",
          "value": "GCKeyCodeKeyJ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyJ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyJ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyC/title",
          "value": "GCKeyCodeKeyC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyB/title",
          "value": "GCKeyCodeKeyB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyM/title",
          "value": "GCKeyCodeKeyM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/title",
          "value": "GCKeyCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyZ/title",
          "value": "GCKeyCodeKeyZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyK/title",
          "value": "GCKeyCodeKeyK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyH/title",
          "value": "GCKeyCodeKeyH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyO/title",
          "value": "GCKeyCodeKeyO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyL/title",
          "value": "GCKeyCodeKeyL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode~1keyL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCodeKeyL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gckeycode/keyz"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gckeycode/keyz"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
