{
  "abstract": [
    {
      "text": "Item metadata request is being serviced.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/alreadyFetching"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICReturnMetadataErrorCode@ICReturnMetadataAlreadyFetching",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "alreadyFetching"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICReturnMetadataAlreadyFetching"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ICReturnMetadataError.Code.alreadyFetching"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "alreadyFetching"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError": {
      "abstract": [
        {
          "text": "A metadata error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnMetadataError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnMetadataError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/alreadyFetching": {
      "abstract": [
        {
          "text": "Item metadata request is being serviced.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyFetching"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/alreadyFetching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnMetadataAlreadyFetching"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError.Code.alreadyFetching",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/code/alreadyfetching"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/canceled": {
      "abstract": [
        {
          "text": "Item metadata request has been canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canceled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/canceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnMetadataCanceled"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError.Code.canceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/code/canceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/invalid": {
      "abstract": [
        {
          "text": "Item metadata request completed with invalid result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnMetadataInvalid"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError.Code.invalid",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/code/invalid"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/notAvailable": {
      "abstract": [
        {
          "text": "Item does not have metadata available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAvailable"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/notAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnMetadataNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError.Code.notAvailable",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/code/notavailable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/canceled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/invalid",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/notAvailable",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/canceled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/invalid",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/notAvailable"
      ],
      "title": "Error Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICReturnMetadataAlreadyFetching"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataAlreadyFetching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/canceled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/invalid",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/notAvailable",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/canceled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/invalid",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code/notAvailable"
              ],
              "title": "Error Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ICReturnMetadataAlreadyFetching"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code~1notAvailable/title",
          "value": "ICReturnMetadataNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code~1notAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code~1alreadyFetching/title",
          "value": "ICReturnMetadataAlreadyFetching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code~1alreadyFetching/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataAlreadyFetching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code~1invalid/title",
          "value": "ICReturnMetadataInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/title",
          "value": "ICReturnMetadataErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code~1canceled/title",
          "value": "ICReturnMetadataCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code~1canceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataCanceled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icreturnmetadataerror/code/alreadyfetching"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icreturnmetadataerror/code/alreadyfetching"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
