{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MDLMaterialPropertyNode","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode","text":"MDLMaterialPropertyNode"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"connections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MDLMaterialPropertyConnection","text":"MDLMaterialPropertyConnection","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection"},{"kind":"text","text":"])"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/modelio/mdlmaterialpropertygraph/init(nodes:connections:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlmaterialpropertygraph/init(nodes:connections:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph/init(nodes:connections:)"},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nodes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MDLMaterialPropertyNode","preciseIdentifier":"c:objc(cs)MDLMaterialPropertyNode","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"connections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MDLMaterialPropertyConnection","preciseIdentifier":"c:objc(cs)MDLMaterialPropertyConnection"},{"kind":"text","text":"])"}],"title":"init(nodes:connections:)","role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"10.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"10.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.12","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"10.0","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"roleHeading":"Initializer","symbolKind":"init","externalID":"c:objc(cs)MDLMaterialPropertyGraph(im)initWithNodes:connections:","navigatorTitle":[{"kind":"identifier","text":"initWithNodes:connections:"}],"modules":[{"name":"Model I/O"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MDLMaterialPropertyConnection"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MDLMaterialPropertyConnection"}],"kind":"symbol","role":"symbol","title":"MDLMaterialPropertyConnection","url":"/documentation/modelio/mdlmaterialpropertyconnection","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph/init(nodes:connections:)":{"title":"init(nodes:connections:)","abstract":[],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph/init(nodes:connections:)","url":"/documentation/modelio/mdlmaterialpropertygraph/init(nodes:connections:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nodes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MDLMaterialPropertyNode","kind":"typeIdentifier","text":"MDLMaterialPropertyNode"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"connections"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)MDLMaterialPropertyConnection","kind":"typeIdentifier","text":"MDLMaterialPropertyConnection"},{"kind":"text","text":"])"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNodes:connections:"}],"kind":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph":{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMaterialPropertyGraph","kind":"identifier"}],"title":"MDLMaterialPropertyGraph","type":"topic","kind":"symbol","url":"/documentation/modelio/mdlmaterialpropertygraph","role":"symbol","navigatorTitle":[{"text":"MDLMaterialPropertyGraph","kind":"identifier"}],"abstract":[]},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode":{"title":"MDLMaterialPropertyNode","kind":"symbol","url":"/documentation/modelio/mdlmaterialpropertynode","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MDLMaterialPropertyNode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MDLMaterialPropertyNode","kind":"identifier"}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyNode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"10.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"10.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.12","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"10.0","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"initWithNodes:connections:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNodes:connections:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyGraph"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNodes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MDLMaterialPropertyNode *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nodes"},{"kind":"text","text":" "},{"kind":"identifier","text":"connections:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MDLMaterialPropertyConnection *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connections"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"MDLMaterialPropertyConnection","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/title"},{"op":"replace","value":[{"text":"MDLMaterialPropertyConnection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/fragments"},{"value":[{"text":"MDLMaterialPropertyConnection","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/navigatorTitle"},{"value":"initWithNodes:connections:","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph~1init(nodes:connections:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithNodes:connections:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph~1init(nodes:connections:)/fragments"},{"value":"MDLMaterialPropertyGraph","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph/title"},{"value":[{"text":"MDLMaterialPropertyGraph","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph/fragments"},{"value":[{"text":"MDLMaterialPropertyGraph","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyGraph/navigatorTitle"},{"value":"MDLMaterialPropertyNode","op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyNode/title"},{"value":[{"text":"MDLMaterialPropertyNode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyNode/fragments"},{"value":[{"kind":"identifier","text":"MDLMaterialPropertyNode"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyNode/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}