{
  "abstract": [
    {
      "text": "An error that indicates the peer Bluetooth accessory isn’t connected or paired.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/accessoryPeerDeviceUnavailable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NIErrorCode@NIErrorCodeAccessoryPeerDeviceUnavailable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessoryPeerDeviceUnavailable"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NIErrorCodeAccessoryPeerDeviceUnavailable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NIError.Code.accessoryPeerDeviceUnavailable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessoryPeerDeviceUnavailable"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For more on the backgrounding requirements of accessory interaction, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError": {
      "abstract": [
        {
          "text": "An error Nearby Interaction reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIError"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIError"
        }
      ],
      "role": "symbol",
      "title": "NIError",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code": {
      "abstract": [
        {
          "text": "Codes that identify errors in Nearby Interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/accessoryPeerDeviceUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates the peer Bluetooth accessory isn’t connected or paired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryPeerDeviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/accessoryPeerDeviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeAccessoryPeerDeviceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.accessoryPeerDeviceUnavailable",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/accessorypeerdeviceunavailable"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeExtendedDistanceSessionsLimitExceeded": {
      "abstract": [
        {
          "text": "An error that indicates the device exceeds the available number of active extended distance sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeExtendedDistanceSessionsLimitExceeded"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeExtendedDistanceSessionsLimitExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeActiveExtendedDistanceSessionsLimitExceeded"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.activeExtendedDistanceSessionsLimitExceeded",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/activeextendeddistancesessionslimitexceeded"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeSessionsLimitExceeded": {
      "abstract": [
        {
          "text": "An error code that indicates that the app reached the maximum number of sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeSessionsLimitExceeded"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeSessionsLimitExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeActiveSessionsLimitExceeded"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.activeSessionsLimitExceeded",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/activesessionslimitexceeded"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/incompatiblePeerDevice": {
      "abstract": [
        {
          "text": "An error that indicates the peer device isn’t compatible with this Nearby Interaction session instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatiblePeerDevice"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/incompatiblePeerDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeIncompatiblePeerDevice"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.incompatiblePeerDevice",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/incompatiblepeerdevice"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidARConfiguration": {
      "abstract": [
        {
          "text": "An error that indicates the framework can’t begin Camera Assistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidARConfiguration"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidARConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeInvalidARConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.invalidARConfiguration",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/invalidarconfiguration"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidConfiguration": {
      "abstract": [
        {
          "text": "An error code that indicates that the nearby-interaction configuration isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConfiguration"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeInvalidConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.invalidConfiguration",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/invalidconfiguration"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/resourceUsageTimeout": {
      "abstract": [
        {
          "text": "An error code that indicates that the framework timed out the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceUsageTimeout"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/resourceUsageTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeResourceUsageTimeout"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.resourceUsageTimeout",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/resourceusagetimeout"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/sessionFailed": {
      "abstract": [
        {
          "text": "An error code that indicates that the session failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionFailed"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/sessionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeSessionFailed"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.sessionFailed",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/sessionfailed"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/unsupportedPlatform": {
      "abstract": [
        {
          "text": "An error code that indicates that the framework doesn’t support the device platform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedPlatform"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/unsupportedPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeUnsupportedPlatform"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.unsupportedPlatform",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/unsupportedplatform"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/userDidNotAllow": {
      "abstract": [
        {
          "text": "An error code that indicates that the user declined the request to share their relative position with nearby devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDidNotAllow"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/userDidNotAllow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeUserDidNotAllow"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.userDidNotAllow",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/userdidnotallow"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration": {
      "abstract": [
        {
          "text": "A configuration that enables interaction between iPhone and third-party accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NINearbyAccessoryConfiguration"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyAccessoryConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NINearbyAccessoryConfiguration",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyaccessoryconfiguration"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeSessionsLimitExceeded",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidConfiguration",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/resourceUsageTimeout",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/sessionFailed",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/unsupportedPlatform",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/userDidNotAllow",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidARConfiguration",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/incompatiblePeerDevice",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeExtendedDistanceSessionsLimitExceeded"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NIErrorCodeAccessoryPeerDeviceUnavailable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeAccessoryPeerDeviceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeSessionsLimitExceeded",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidConfiguration",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/resourceUsageTimeout",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/sessionFailed",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/unsupportedPlatform",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/userDidNotAllow",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidARConfiguration",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/incompatiblePeerDevice",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeExtendedDistanceSessionsLimitExceeded"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NIErrorCodeAccessoryPeerDeviceUnavailable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1invalidConfiguration/title",
          "value": "NIErrorCodeInvalidConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1invalidConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeInvalidConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1resourceUsageTimeout/title",
          "value": "NIErrorCodeResourceUsageTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1resourceUsageTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeResourceUsageTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1userDidNotAllow/title",
          "value": "NIErrorCodeUserDidNotAllow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1userDidNotAllow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeUserDidNotAllow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1incompatiblePeerDevice/title",
          "value": "NIErrorCodeIncompatiblePeerDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1incompatiblePeerDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeIncompatiblePeerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1accessoryPeerDeviceUnavailable/title",
          "value": "NIErrorCodeAccessoryPeerDeviceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1accessoryPeerDeviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeAccessoryPeerDeviceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1invalidARConfiguration/title",
          "value": "NIErrorCodeInvalidARConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1invalidARConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeInvalidARConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1sessionFailed/title",
          "value": "NIErrorCodeSessionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1sessionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeSessionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1activeSessionsLimitExceeded/title",
          "value": "NIErrorCodeActiveSessionsLimitExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1activeSessionsLimitExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeActiveSessionsLimitExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code/title",
          "value": "NIErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration/title",
          "value": "NINearbyAccessoryConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyAccessoryConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyAccessoryConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1activeExtendedDistanceSessionsLimitExceeded/title",
          "value": "NIErrorCodeActiveExtendedDistanceSessionsLimitExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1activeExtendedDistanceSessionsLimitExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeActiveExtendedDistanceSessionsLimitExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1unsupportedPlatform/title",
          "value": "NIErrorCodeUnsupportedPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1unsupportedPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeUnsupportedPlatform"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/nierror/code/accessorypeerdeviceunavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/nearbyinteraction/nierror/code/accessorypeerdeviceunavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
