{
  "abstract": [
    {
      "text": "An array of format descriptions for the track.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/formatDescriptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)METrackInfo(py)formatDescriptions",
    "fragments": [
      {
        "kind": "identifier",
        "text": "formatDescriptions"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "formatDescriptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "formatDescriptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSArray",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSArray",
              "text": "NSArray"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "formatDescriptions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo": {
      "abstract": [
        {
          "text": "An object that includes track properties parsed from the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "METrackInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "METrackInfo"
        }
      ],
      "role": "symbol",
      "title": "METrackInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/extendedLanguageTag": {
      "abstract": [
        {
          "text": "A string that indicates the language tag associated with the track, as an IETF BCP 47 (RFC 4646) language identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedLanguageTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/extendedLanguageTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedLanguageTag"
        }
      ],
      "role": "symbol",
      "title": "extendedLanguageTag",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/extendedlanguagetag"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/formatDescriptions": {
      "abstract": [
        {
          "text": "An array of format descriptions for the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "formatDescriptions"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/formatDescriptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "formatDescriptions",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/formatdescriptions"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/isEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the track is enabled by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/isenabled"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/mediaType": {
      "abstract": [
        {
          "text": "The media type of the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/mediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaType"
        }
      ],
      "role": "symbol",
      "title": "mediaType",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/mediatype"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalSize": {
      "abstract": [
        {
          "text": "Indicates the natural dimensions of the media data referenced by the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "naturalSize"
        }
      ],
      "role": "symbol",
      "title": "naturalSize",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/naturalsize"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalTimescale": {
      "abstract": [
        {
          "text": "The natural timescale of the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalTimescale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimeScale",
          "text": "CMTimeScale"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalTimescale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "naturalTimescale"
        }
      ],
      "role": "symbol",
      "title": "naturalTimescale",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/naturaltimescale"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/nominalFrameRate": {
      "abstract": [
        {
          "text": "The frame rate of the track in frames per second, as a 32-bit floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nominalFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/nominalFrameRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nominalFrameRate"
        }
      ],
      "role": "symbol",
      "title": "nominalFrameRate",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/nominalframerate"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/preferredTransform": {
      "abstract": [
        {
          "text": "Indicates the preferred affine display transform of the track media for visual display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/preferredTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredTransform"
        }
      ],
      "role": "symbol",
      "title": "preferredTransform",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/preferredtransform"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/requiresFrameReordering": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether frame reordering occurs in the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresFrameReordering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/requiresFrameReordering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresFrameReordering"
        }
      ],
      "role": "symbol",
      "title": "requiresFrameReordering",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/requiresframereordering"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackEdits": {
      "abstract": [
        {
          "text": "An array of edit segments for the given track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "trackEdits"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackEdits",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackEdits",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/trackedits"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackID": {
      "abstract": [
        {
          "text": "An integer that identifies the track within the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPersistentTrackID",
          "text": "CMPersistentTrackID"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackID"
        }
      ],
      "role": "symbol",
      "title": "trackID",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/trackid"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSArray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSArray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-track-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/mediaType",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackID",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/isEnabled",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalTimescale",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/extendedLanguageTag",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalSize",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/preferredTransform",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/nominalFrameRate",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/requiresFrameReordering",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackEdits"
      ],
      "title": "Inspecting track information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1requiresFrameReordering/title",
          "value": "requiresFrameReordering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1requiresFrameReordering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresFrameReordering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1nominalFrameRate/title",
          "value": "nominalFrameRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1nominalFrameRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nominalFrameRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSArray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1naturalTimescale/title",
          "value": "naturalTimescale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1naturalTimescale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "naturalTimescale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1extendedLanguageTag/title",
          "value": "extendedLanguageTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1extendedLanguageTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedLanguageTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo/title",
          "value": "METrackInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "METrackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "METrackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1naturalSize/title",
          "value": "naturalSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1naturalSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "naturalSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1trackID/title",
          "value": "trackID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1trackID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1mediaType/title",
          "value": "mediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1mediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1preferredTransform/title",
          "value": "preferredTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1preferredTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredTransform"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/metrackinfo/formatdescriptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
