{
  "abstract": [
    {
      "text": "An array of edit segments for the given track.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackEdits"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)METrackInfo(py)trackEdits",
    "fragments": [
      {
        "kind": "identifier",
        "text": "trackEdits"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "trackEdits"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "trackEdits"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSValue *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "trackEdits"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each value in the array contains a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeMapping",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that describes the track edit. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeMapping/target",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " time ranges for successive edits need to partition the time range from ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " to the track’s duration. In other words, for the first edit at index ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ", the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRange/start",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " needs to be ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTime/zero",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and for each additional edit (index > 0), the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRange/start",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " needs to match the value returned from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRangeGetEnd(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the edit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A track can have an empty ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackEdits",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array, which means that there’s nothing in the track and the track duration is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ". This property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " for media asset formats that don’t support edit segments.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each NSValue in the array contains a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeMapping",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object describing the track edit. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeMapping/target",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " time ranges for successive edits must partition the time range from ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " to the track’s duration. In other words, for edit (index = 0) the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRange/start",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " must be ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTime/zero",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", while for edit (index > 0), the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRange/start",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " must match the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRangeGetEnd(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for edit (index - 1). It is valid for a track to have an empty ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackEdits",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array; this means that there is nothing at all in the track and the track duration is zero. If this property is implemented for media asset formats that do not support edit segments, it can return nil.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/CoreMedia/CMTime/zero": {
      "abstract": [
        {
          "text": "A value that represents time zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTime/zero",
      "kind": "symbol",
      "role": "symbol",
      "title": "zero",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTime/zero"
    },
    "doc://com.apple.documentation/documentation/CoreMedia/CMTimeMapping": {
      "abstract": [
        {
          "text": "A structure that maps a segment of a source time range to a target time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMapping"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeMapping",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTimeMapping",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTimeMapping"
    },
    "doc://com.apple.documentation/documentation/CoreMedia/CMTimeMapping/target": {
      "abstract": [
        {
          "text": "A time range on the target timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeMapping/target",
      "kind": "symbol",
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTimeMapping/target"
    },
    "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRange/start": {
      "abstract": [
        {
          "text": "The start time of the time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRange/start",
      "kind": "symbol",
      "role": "symbol",
      "title": "start",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTimeRange/start"
    },
    "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRangeGetEnd(_:)": {
      "abstract": [
        {
          "text": "Returns a time value that represents the end of a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetEnd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMTimeRangeGetEnd(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTimeRangeGetEnd(_:)",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTimeRangeGetEnd(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo": {
      "abstract": [
        {
          "text": "An object that includes track properties parsed from the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "METrackInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "METrackInfo"
        }
      ],
      "role": "symbol",
      "title": "METrackInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/extendedLanguageTag": {
      "abstract": [
        {
          "text": "A string that indicates the language tag associated with the track, as an IETF BCP 47 (RFC 4646) language identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedLanguageTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/extendedLanguageTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedLanguageTag"
        }
      ],
      "role": "symbol",
      "title": "extendedLanguageTag",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/extendedlanguagetag"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/formatDescriptions": {
      "abstract": [
        {
          "text": "An array of format descriptions for the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "formatDescriptions"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/formatDescriptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "formatDescriptions",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/formatdescriptions"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/isEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the track is enabled by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/isenabled"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/mediaType": {
      "abstract": [
        {
          "text": "The media type of the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/mediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaType"
        }
      ],
      "role": "symbol",
      "title": "mediaType",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/mediatype"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalSize": {
      "abstract": [
        {
          "text": "Indicates the natural dimensions of the media data referenced by the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "naturalSize"
        }
      ],
      "role": "symbol",
      "title": "naturalSize",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/naturalsize"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalTimescale": {
      "abstract": [
        {
          "text": "The natural timescale of the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalTimescale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimeScale",
          "text": "CMTimeScale"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalTimescale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "naturalTimescale"
        }
      ],
      "role": "symbol",
      "title": "naturalTimescale",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/naturaltimescale"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/nominalFrameRate": {
      "abstract": [
        {
          "text": "The frame rate of the track in frames per second, as a 32-bit floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nominalFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/nominalFrameRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nominalFrameRate"
        }
      ],
      "role": "symbol",
      "title": "nominalFrameRate",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/nominalframerate"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/preferredTransform": {
      "abstract": [
        {
          "text": "Indicates the preferred affine display transform of the track media for visual display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/preferredTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredTransform"
        }
      ],
      "role": "symbol",
      "title": "preferredTransform",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/preferredtransform"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/requiresFrameReordering": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether frame reordering occurs in the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresFrameReordering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/requiresFrameReordering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresFrameReordering"
        }
      ],
      "role": "symbol",
      "title": "requiresFrameReordering",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/requiresframereordering"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackEdits": {
      "abstract": [
        {
          "text": "An array of edit segments for the given track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "trackEdits"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackEdits",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackEdits",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/trackedits"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackID": {
      "abstract": [
        {
          "text": "An integer that identifies the track within the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPersistentTrackID",
          "text": "CMPersistentTrackID"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackID"
        }
      ],
      "role": "symbol",
      "title": "trackID",
      "type": "topic",
      "url": "/documentation/mediaextension/metrackinfo/trackid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-track-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/mediaType",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/trackID",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/isEnabled",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/formatDescriptions",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalTimescale",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/extendedLanguageTag",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/naturalSize",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/preferredTransform",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/nominalFrameRate",
        "doc://com.apple.mediaextension/documentation/MediaExtension/METrackInfo/requiresFrameReordering"
      ],
      "title": "Inspecting track information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTime~1zero/title",
          "value": "kCMTimeZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTime~1zero/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMTimeZero"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTimeRangeGetEnd(_:)/title",
          "value": "CMTimeRangeGetEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTimeRangeGetEnd(_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTimeRangeGetEnd"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTimeRange",
              "text": "CMTimeRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1requiresFrameReordering/title",
          "value": "requiresFrameReordering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1requiresFrameReordering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresFrameReordering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1naturalTimescale/title",
          "value": "naturalTimescale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1naturalTimescale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "naturalTimescale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1mediaType/title",
          "value": "mediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1mediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1trackID/title",
          "value": "trackID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1trackID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTimeRange~1start/fragments",
          "value": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "start"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1extendedLanguageTag/title",
          "value": "extendedLanguageTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1extendedLanguageTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedLanguageTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo/title",
          "value": "METrackInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "METrackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "METrackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1naturalSize/title",
          "value": "naturalSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1naturalSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "naturalSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTimeMapping~1target/fragments",
          "value": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTimeRange",
              "text": "CMTimeRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "target"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTimeMapping/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMTimeMapping"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1nominalFrameRate/title",
          "value": "nominalFrameRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1nominalFrameRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nominalFrameRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1preferredTransform/title",
          "value": "preferredTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1METrackInfo~1preferredTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredTransform"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/metrackinfo/trackedits"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
