{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_compute_projection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@cp_drawable_compute_projection",
    "fragments": [
      {
        "kind": "identifier",
        "text": "cp_drawable_compute_projection"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cp_drawable_compute_projection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "cp_drawable_compute_projection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@simd_float4x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_float4x4",
              "text": "simd_float4x4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cp_drawable_compute_projection"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@cp_drawable_t",
              "text": "cp_drawable_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "drawable"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@cp_axis_direction_convention",
              "text": "cp_axis_direction_convention"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "normalized_device_coordinates_convension"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@size_t",
              "text": "size_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "view_index"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention": {
      "abstract": [
        {
          "text": "Constants that indicate the axis and direction to use for a perspective projection matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AxisDirectionConvention"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AxisDirectionConvention"
        }
      ],
      "role": "symbol",
      "title": "AxisDirectionConvention",
      "type": "topic",
      "url": "/documentation/compositorservices/axisdirectionconvention"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_compute_projection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_drawable_compute_projection"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_compute_projection",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_drawable_compute_projection",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_drawable_compute_projection"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t": {
      "abstract": [
        {
          "text": "A type that provides the textures and information you need to draw a frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_drawable_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_drawable_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_drawable_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@SA@simd_float4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4x4"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@simd_float4x4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4"
    },
    "doc://com.externally.resolved.symbol/c:@T@size_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "size_t",
      "type": "topic",
      "url": "/documentation/kernel/size_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@simd_float4x4/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "simd_float4x4"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention/title",
          "value": "cp_axis_direction_convention"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_axis_direction_convention"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_axis_direction_convention"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/cp_drawable_compute_projection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
