{
  "abstract": [
    {
      "text": "Returns the next frame to use for drawing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_query_next_frame"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@cp_layer_renderer_query_next_frame",
    "fragments": [
      {
        "kind": "identifier",
        "text": "cp_layer_renderer_query_next_frame"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cp_layer_renderer_query_next_frame"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "cp_layer_renderer_query_next_frame"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@cp_frame_t",
              "text": "cp_frame_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_query_next_frame"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@cp_layer_renderer_t",
              "text": "cp_layer_renderer_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "layer_renderer"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The layer that manages the drawing destination.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "layer_renderer"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A frame type to use for drawing operations. The function returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the layer is paused, invalidated, or has too many frames already in use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function retrieves the next frame for you to use in your drawing operations. The system maintains a limited number of frames, so don’t try to render more than one frame in advance. If this function returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", wait a short time and try again. When the system finishes displaying a rendered frame onscreen, it returns that frame to the shared pool and makes it available for you to use again.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The index of each returned frame is always greater than the index of the previous frame. The system increments index values sequentially so you can differentiate frames you are currently drawing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerFrameIndex": {
      "abstract": [
        {
          "text": "A frame index in the layer’s timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerFrameIndex"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerFrameIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerFrameIndex"
        }
      ],
      "role": "symbol",
      "title": "LayerFrameIndex",
      "type": "topic",
      "url": "/documentation/compositorservices/layerframeindex"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_t": {
      "abstract": [
        {
          "text": "A type that provides access to the timing information",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and data types you need to render a single frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_frame_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_frame_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_frame_t"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_query_next_frame": {
      "abstract": [
        {
          "text": "Returns the next frame to use for drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_query_next_frame"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_query_next_frame",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_query_next_frame",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_query_next_frame"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_t": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drawing-a-frame-of-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerFrameIndex"
      ],
      "title": "Drawing a frame of content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerFrameIndex/title",
          "value": "cp_layer_frame_index_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerFrameIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_frame_index_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerFrameIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_frame_index_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/cp_layer_renderer_query_next_frame"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
