{
  "abstract": [
    {
      "text": "Returns the texture configuration for the drawable views in the layer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_get_layout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@cp_layer_renderer_configuration_get_layout",
    "fragments": [
      {
        "kind": "identifier",
        "text": "cp_layer_renderer_configuration_get_layout"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cp_layer_renderer_configuration_get_layout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "cp_layer_renderer_configuration_get_layout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Layout",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@cp_layer_renderer_layout",
              "text": "cp_layer_renderer_layout"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_configuration_get_layout"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@cp_layer_renderer_configuration_t",
              "text": "cp_layer_renderer_configuration_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "configuration"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The layer configuration details.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "configuration"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The layout of the textures in the layer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Layouts define how Compositor Services creates the color and depth textures it passes to your app. A layout might use separate textures for each view, or combine the content from multiple views into a single texture. The layout type also determines which Metal texture type the compositor creates for you. For more information about the supported layouts, see ",
              "type": "text"
            },
            {
              "code": "cp_layer_renderer_layout",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Layout": {
      "abstract": [
        {
          "text": "Constants that specify the organization of the textures you use for drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Layout"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Layout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Layout"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Layout",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/layout"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_get_layout": {
      "abstract": [
        {
          "text": "Returns the texture configuration for the drawable views in the layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_configuration_get_layout"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_get_layout",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_configuration_get_layout",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_configuration_get_layout"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_set_layout": {
      "abstract": [
        {
          "text": "Changes the layout configuration for the drawable views in the layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_configuration_set_layout"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_set_layout",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_configuration_set_layout",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_configuration_set_layout"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_t": {
      "abstract": [
        {
          "text": "A type that stores the texture formats, layout information, and other details you use to configure your rendering loop code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_configuration_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_configuration_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_configuration_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-texture-layout",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_set_layout",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Layout"
      ],
      "title": "Configuring the texture layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Layout/title",
          "value": "cp_layer_renderer_layout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Layout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_layout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Layout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_layout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/cp_layer_renderer_configuration_get_layout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
