{
  "abstract": [
    {
      "text": "A type that specifies the organization of one of the drawable’s textures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_texture_topology_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@cp_texture_topology_t",
    "fragments": [
      {
        "kind": "identifier",
        "text": "cp_texture_topology_t"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cp_texture_topology_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "cp_texture_topology_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cp_texture_topology",
              "text": "cp_texture_topology"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "cp_texture_topology_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Metal supports multiple organizations for the textures you use for drawing. Use this type to identify one of the organizations available to use in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/arrayLength": {
      "abstract": [
        {
          "text": "The number of items in the texture array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrayLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/arrayLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_texture_topology_get_array_length"
        }
      ],
      "role": "symbol",
      "title": "arrayLength",
      "type": "topic",
      "url": "/documentation/compositorservices/texturetopology/arraylength"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/textureType": {
      "abstract": [
        {
          "text": "The texture type value that specifies how the underlying texture organizes its views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureType",
          "text": "MTLTextureType"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/textureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_texture_topology_get_texture_type"
        }
      ],
      "role": "symbol",
      "title": "textureType",
      "type": "topic",
      "url": "/documentation/compositorservices/texturetopology/texturetype"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology": {
      "abstract": [
        {
          "text": "Retrieves the texture topology at the specified index in the layer’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_properties_get_texture_topology"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_properties_get_texture_topology",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_properties_get_texture_topology"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology_count": {
      "abstract": [
        {
          "text": "Returns the number of texture topologies available for you to inspect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_properties_get_texture_topology_count"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology_count",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_properties_get_texture_topology_count",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_properties_get_texture_topology_count"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_texture_topology_t": {
      "abstract": [
        {
          "text": "A type that specifies the organization of one of the drawable’s textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_texture_topology_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_texture_topology_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_texture_topology_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_texture_topology_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-layers-texture-topology",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology_count",
        "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology",
        "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/arrayLength",
        "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/textureType"
      ],
      "title": "Getting the layer’s texture topology"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-topology-type",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/textureType"
      ],
      "title": "Getting the topology type"
    },
    {
      "anchor": "Getting-the-array-length",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/arrayLength"
      ],
      "title": "Getting the array length"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1TextureTopology~1textureType/title",
          "value": "cp_texture_topology_get_texture_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1TextureTopology~1textureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_texture_topology_get_texture_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1TextureTopology~1arrayLength/title",
          "value": "cp_texture_topology_get_array_length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1TextureTopology~1arrayLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_texture_topology_get_array_length"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/cp_texture_topology_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
