{
  "abstract": [
    {
      "text": "A type that provides details about the textures associated with a view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_view_texture_map_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@cp_view_texture_map_t",
    "fragments": [
      {
        "kind": "identifier",
        "text": "cp_view_texture_map_t"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cp_view_texture_map_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "cp_view_texture_map_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@cp_view_texture_map",
              "text": "cp_view_texture_map"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "cp_view_texture_map_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A texture map helps you locate the content for a specific view within a texture. Texture maps are especially important when a layer uses a single texture to manage multiple views. For example, a head-mounted display might store the images for both the left and right eyes in a single texture. Pass this type to other functions to get specific details about the current texture, such as its view bounds or its index into a texture array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/sliceIndex": {
      "abstract": [
        {
          "text": "The index of the view’s texture in an array-based texture type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sliceIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/sliceIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_view_texture_map_get_slice_index"
        }
      ],
      "role": "symbol",
      "title": "sliceIndex",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable/view/texturemap-swift.struct/sliceindex"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/textureIndex": {
      "abstract": [
        {
          "text": "The index of the view’s textures in the drawable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/textureIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_view_texture_map_get_texture_index"
        }
      ],
      "role": "symbol",
      "title": "textureIndex",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable/view/texturemap-swift.struct/textureindex"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/viewport": {
      "abstract": [
        {
          "text": "The portion of the texture that the view uses to draw its content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLViewport",
          "text": "MTLViewport"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/viewport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_view_texture_map_get_viewport"
        }
      ],
      "role": "symbol",
      "title": "viewport",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable/view/texturemap-swift.struct/viewport"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/textureMap-swift.property": {
      "abstract": [
        {
          "text": "The texture map for a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cp_drawable_t",
          "text": "Drawable"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cp_view_t",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cp_view_texture_map_t",
          "text": "TextureMap"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/textureMap-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_view_get_view_texture_map"
        }
      ],
      "role": "symbol",
      "title": "textureMap",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable/view/texturemap-swift.property"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_view_texture_map_t": {
      "abstract": [
        {
          "text": "A type that provides details about the textures associated with a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_view_texture_map_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_view_texture_map_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_view_texture_map_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_view_texture_map_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-views-texture-map",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/textureMap-swift.property",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/textureIndex",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/sliceIndex",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/viewport"
      ],
      "title": "Getting the view’s texture map"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-viewport",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/viewport"
      ],
      "title": "Getting the viewport"
    },
    {
      "anchor": "Getting-the-texture-indices",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/sliceIndex",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/textureIndex"
      ],
      "title": "Getting the texture indices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1TextureMap-swift.struct~1sliceIndex/title",
          "value": "cp_view_texture_map_get_slice_index"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1TextureMap-swift.struct~1sliceIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_view_texture_map_get_slice_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1TextureMap-swift.struct~1viewport/title",
          "value": "cp_view_texture_map_get_viewport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1TextureMap-swift.struct~1viewport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_view_texture_map_get_viewport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1TextureMap-swift.struct~1textureIndex/title",
          "value": "cp_view_texture_map_get_texture_index"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1TextureMap-swift.struct~1textureIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_view_texture_map_get_texture_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1textureMap-swift.property/title",
          "value": "cp_view_get_view_texture_map"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1textureMap-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_view_get_view_texture_map"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/cp_view_texture_map_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
