{
  "abstract": [
    {
      "text": "Present a mixed immersion style space to draw content in a person’s surroundings,",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "and choose how upper limbs appear with respect to rendered content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/interacting-with-virtual-content-blended-with-passthrough"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Interacting with virtual content blended with passthrough"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC24 session 10092:",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc24/10092/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "0096f3314c24/InteractingWithVirtualContentBlendedWithPassthrough.zip": {
      "checksum": "0096f3314c24b6a29c2c6bf351d28f8336344308cd313ba62b26de60379a0d90f61a343eca472f91389d32f40e47390eb3bc13af029df94cfa2a10bb2e2d6e37",
      "identifier": "0096f3314c24/InteractingWithVirtualContentBlendedWithPassthrough.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/0096f3314c24/InteractingWithVirtualContentBlendedWithPassthrough.zip"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer": {
      "abstract": [
        {
          "text": "A type that you use with an immersive space to display fully immersive content using Metal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompositorLayer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompositorLayer"
        }
      ],
      "role": "symbol",
      "title": "CompositorLayer",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorlayer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration": {
      "abstract": [
        {
          "text": "An interface for specifying the texture configurations and rendering behaviors to use with your Metal rendering engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompositorLayerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompositorLayerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CompositorLayerConfiguration",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorlayerconfiguration"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/DefaultCompositorLayerConfiguration": {
      "abstract": [
        {
          "text": "A type that configures the layer with the default texture configurations and rendering behaviors for the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DefaultCompositorLayerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/DefaultCompositorLayerConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DefaultCompositorLayerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "DefaultCompositorLayerConfiguration",
      "type": "topic",
      "url": "/documentation/compositorservices/defaultcompositorlayerconfiguration"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal": {
      "abstract": [
        {
          "text": "Create a fully immersive experience in visionOS using a custom Metal-based rendering engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal",
      "kind": "article",
      "role": "article",
      "title": "Drawing fully immersive content using Metal",
      "type": "topic",
      "url": "/documentation/compositorservices/drawing-fully-immersive-content-using-metal"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/wwdc24/10092/": {
      "identifier": "https://developer.apple.com/wwdc24/10092/",
      "title": "Render Metal with passthrough in visionOS",
      "titleInlineContent": [
        {
          "text": "Render Metal with passthrough in visionOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc24/10092/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "0096f3314c24/InteractingWithVirtualContentBlendedWithPassthrough.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-integration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal",
        "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer",
        "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration",
        "doc://com.apple.compositorservices/documentation/CompositorServices/DefaultCompositorLayerConfiguration"
      ],
      "title": "App integration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-integration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal"
              ],
              "title": "App integration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/interacting-with-virtual-content-blended-with-passthrough"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compositorservices/interacting-with-virtual-content-blended-with-passthrough"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
