{
  "abstract": [
    {
      "text": "Information about the textures and views that the system created for your drawing code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices",
        "doc://com.apple.compositorservices/documentation/CompositorServices/layer-renderer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/layer-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Layer properties"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "At layer-creation time, the system constructs the textures you use for drawing and stores information about those textures in the layer’s properties. Use that information to configure your render pipeline and set up any app-specific data structures. For example, use the information to get the size and type of the textures. If you want to set up your app’s render pipeline before the layer is available, create a ",
              "type": "text"
            },
            {
              "code": "cp_layer_properties_t",
              "type": "codeVoice"
            },
            {
              "text": " type from the same configuration details you use to construct the layer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/viewport": {
      "abstract": [
        {
          "text": "The portion of the texture that the view uses to draw its content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLViewport",
          "text": "MTLViewport"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/viewport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_view_texture_map_get_viewport"
        }
      ],
      "role": "symbol",
      "title": "viewport",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable/view/texturemap-swift.struct/viewport"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/arrayLength": {
      "abstract": [
        {
          "text": "The number of items in the texture array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrayLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/arrayLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_texture_topology_get_array_length"
        }
      ],
      "role": "symbol",
      "title": "arrayLength",
      "type": "topic",
      "url": "/documentation/compositorservices/texturetopology/arraylength"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/textureType": {
      "abstract": [
        {
          "text": "The texture type value that specifies how the underlying texture organizes its views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureType",
          "text": "MTLTextureType"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/textureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_texture_topology_get_texture_type"
        }
      ],
      "role": "symbol",
      "title": "textureType",
      "type": "topic",
      "url": "/documentation/compositorservices/texturetopology/texturetype"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_get_properties": {
      "abstract": [
        {
          "text": "Returns the configured properties of the specified layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_get_properties"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_get_properties",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_get_properties",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_get_properties"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_create_using_configuration": {
      "abstract": [
        {
          "text": "Creates a new opaque type to store layer-related properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_properties_create_using_configuration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_create_using_configuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_properties_create_using_configuration",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_properties_create_using_configuration"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology": {
      "abstract": [
        {
          "text": "Retrieves the texture topology at the specified index in the layer’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_properties_get_texture_topology"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_properties_get_texture_topology",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_properties_get_texture_topology"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology_count": {
      "abstract": [
        {
          "text": "Returns the number of texture topologies available for you to inspect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_properties_get_texture_topology_count"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology_count",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_properties_get_texture_topology_count",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_properties_get_texture_topology_count"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_view_count": {
      "abstract": [
        {
          "text": "Returns the number of views that you must fill with content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_properties_get_view_count"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_view_count",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_properties_get_view_count",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_properties_get_view_count"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_t": {
      "abstract": [
        {
          "text": "A type that describes the organization of the layer’s textures and the relationships between those textures and the views you use for drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_properties_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_properties_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_properties_t"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_texture_topology_t": {
      "abstract": [
        {
          "text": "A type that specifies the organization of one of the drawable’s textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_texture_topology_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_texture_topology_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_texture_topology_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_texture_topology_t"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/layer-capabilities": {
      "abstract": [
        {
          "text": "The color formats, depth formats, and features that you can use to configure your rendering engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/layer-capabilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layer capabilities",
      "type": "topic",
      "url": "/documentation/compositorservices/layer-capabilities"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/layer-configuration": {
      "abstract": [
        {
          "text": "The pixel formats, depth mask, texture layout,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and other drawing-related settings you use to configure your drawing code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/layer-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layer configuration",
      "type": "topic",
      "url": "/documentation/compositorservices/layer-configuration"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/layer-renderer": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/layer-renderer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layer renderer",
      "type": "topic",
      "url": "/documentation/compositorservices/layer-renderer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-layer",
      "generated": true,
      "identifiers": [],
      "title": "Configuring the layer"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-view-port-information",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/viewport"
      ],
      "title": "Getting view port information"
    },
    {
      "anchor": "Getting-the-layers-texture-topology",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/arrayLength",
        "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/textureType"
      ],
      "title": "Getting the layer’s texture topology"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-a-layers-properties",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_get_properties",
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_t"
              ],
              "title": "Getting a layer’s properties"
            },
            {
              "anchor": "Creating-new-layer-properties",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_create_using_configuration"
              ],
              "title": "Creating new layer properties"
            },
            {
              "anchor": "Getting-view-port-information",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_view_count",
                "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View/TextureMap-swift.struct/viewport"
              ],
              "title": "Getting view port information"
            },
            {
              "anchor": "Getting-the-layers-texture-topology",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology_count",
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_properties_get_texture_topology",
                "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/arrayLength",
                "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology/textureType",
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_texture_topology_t"
              ],
              "title": "Getting the layer’s texture topology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-layer",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/layer-capabilities",
                "doc://com.apple.compositorservices/documentation/CompositorServices/layer-configuration"
              ],
              "title": "Configuring the layer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1TextureTopology~1arrayLength/title",
          "value": "cp_texture_topology_get_array_length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1TextureTopology~1arrayLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_texture_topology_get_array_length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1TextureMap-swift.struct~1viewport/title",
          "value": "cp_view_texture_map_get_viewport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1View~1TextureMap-swift.struct~1viewport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_view_texture_map_get_viewport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1TextureTopology~1textureType/title",
          "value": "cp_texture_topology_get_texture_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1TextureTopology~1textureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_texture_topology_get_texture_type"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/layer-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compositorservices/layer-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
