{
  "abstract": [
    {
      "text": "A type that provides the Metal types and timing information you need to draw your content.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LayerRenderer"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LayerRenderer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "LayerRenderer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LayerRenderer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A layer renderer type creates a bridge between a SwiftUI scene and the Metal code you use to draw fully immersive experiences. When you present an immersive space with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " content, the system creates a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type and makes it available to the content’s closure. Use the information in the layer renderer to set up your app’s rendering loop, and to start drawing frames of content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each layer renderer has information that tells the system how to configure the Metal textures and data types your app needs. Compositor Services provides a default configuration for layers, but you can customize the configuration as needed. Specify your custom configuration details using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol and pass a type with those details to the initializer for your immersive space’s content. Use the layer renderer’s capability information to validate any configuration choices you make.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about how to create and configure a layer renderer and use it to run your rendering loop, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_cp_layer_renderer_capabilities": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_OBJECT_cp_layer_renderer_capabilities"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_cp_layer_renderer_capabilities",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_OBJECT_cp_layer_renderer_capabilities",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_object_cp_layer_renderer_capabilities"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_cp_layer_renderer_configuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_OBJECT_cp_layer_renderer_configuration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_cp_layer_renderer_configuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_OBJECT_cp_layer_renderer_configuration",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_object_cp_layer_renderer_configuration"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_cp_layer_renderer_properties": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_OBJECT_cp_layer_renderer_properties"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_cp_layer_renderer_properties",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_OBJECT_cp_layer_renderer_properties",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_object_cp_layer_renderer_properties"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer": {
      "abstract": [
        {
          "text": "A type that you use with an immersive space to display fully immersive content using Metal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompositorLayer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompositorLayer"
        }
      ],
      "role": "symbol",
      "title": "CompositorLayer",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorlayer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration": {
      "abstract": [
        {
          "text": "An interface for specifying the texture configurations and rendering behaviors to use with your Metal rendering engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompositorLayerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompositorLayerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CompositorLayerConfiguration",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorlayerconfiguration"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities": {
      "abstract": [
        {
          "text": "The color formats, depth formats, and features that you can use to configure your rendering engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Capabilities"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Capabilities"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Capabilities",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/capabilities"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Clock": {
      "abstract": [
        {
          "text": "A type that supports operations that require a precise time measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Clock"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Clock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Clock"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Clock",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/clock"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct": {
      "abstract": [
        {
          "text": "A type that stores the texture formats, layout information, and other details you use to configure your rendering loop code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Configuration",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable": {
      "abstract": [
        {
          "text": "A type that provides the textures and information you need to draw a frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Drawable"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Drawable"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Drawable",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Frame": {
      "abstract": [
        {
          "text": "A type that provides access to the timing information and data types you need to render a single frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Frame"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Frame"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Frame",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/frame"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Properties-swift.struct": {
      "abstract": [
        {
          "text": "A type that describes the organization of the layer renderer’s textures and the relationships between those textures and the views you use for drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Properties"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Properties-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Properties"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Properties",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/properties-swift.struct"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/State-swift.enum": {
      "abstract": [
        {
          "text": "The states of the layer renderer, which tell you how to proceed with drawing operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.State",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/state-swift.enum"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/configuration-swift.property": {
      "abstract": [
        {
          "text": "The configuration details for the specified layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/configuration-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.property"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/device": {
      "abstract": [
        {
          "text": "The GPU device that the layer renderer uses for drawing operations",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/device",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_get_device"
        }
      ],
      "role": "symbol",
      "title": "device",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/device"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/minimumFrameRepeatCount": {
      "abstract": [
        {
          "text": "The number of additional frames for which the system displays the same content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumFrameRepeatCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/minimumFrameRepeatCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_get_minimum_frame_repeat_count"
        }
      ],
      "role": "symbol",
      "title": "minimumFrameRepeatCount",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/minimumframerepeatcount"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/onSpatialEvent": {
      "abstract": [
        {
          "text": "A closure that receives spatial event updates from the layer renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onSpatialEvent"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI22SpatialEventCollectionV",
          "text": "SpatialEventCollection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/onSpatialEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "onSpatialEvent",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/onspatialevent"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/properties-swift.property": {
      "abstract": [
        {
          "text": "The configured properties of the layer renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "properties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE10PropertiesV",
          "text": "Properties"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/properties-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "properties",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/properties-swift.property"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/queryNextFrame()": {
      "abstract": [
        {
          "text": "Returns the next frame to use for drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryNextFrame"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cp_frame_t",
          "text": "Frame"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/queryNextFrame()",
      "kind": "symbol",
      "role": "symbol",
      "title": "queryNextFrame()",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/querynextframe()"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/state-swift.property": {
      "abstract": [
        {
          "text": "A value that indicates whether the layer renderer is currently visible",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and ready for you to draw content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@cp_layer_renderer_state",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/state-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_get_state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/state-swift.property"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/waitUntilRunning()": {
      "abstract": [
        {
          "text": "Stops further execution of your code until the layer renderer leaves the paused state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waitUntilRunning"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/waitUntilRunning()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_wait_until_running"
        }
      ],
      "role": "symbol",
      "title": "waitUntilRunning()",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/waituntilrunning()"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t": {
      "abstract": [
        {
          "text": "A type that provides the textures and information you need to draw a frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_drawable_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_drawable_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_drawable_t"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal": {
      "abstract": [
        {
          "text": "Create a fully immersive experience in visionOS using a custom Metal-based rendering engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal",
      "kind": "article",
      "role": "article",
      "title": "Drawing fully immersive content using Metal",
      "type": "topic",
      "url": "/documentation/compositorservices/drawing-fully-immersive-content-using-metal"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Render-loop-setup",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Frame"
      ],
      "title": "Render-loop setup"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-layer-renderer",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/configuration-swift.property",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities"
      ],
      "title": "Configuring the layer renderer"
    },
    {
      "anchor": "Getting-the-layer-renderer-properties",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/properties-swift.property",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Properties-swift.struct"
      ],
      "title": "Getting the layer renderer properties"
    },
    {
      "anchor": "Getting-the-GPU-device",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/device"
      ],
      "title": "Getting the GPU device"
    },
    {
      "anchor": "Managing-the-rendering-loop",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/state-swift.property",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/waitUntilRunning()",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/State-swift.enum",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Clock"
      ],
      "title": "Managing the rendering loop"
    },
    {
      "anchor": "Drawing-a-frame-of-content",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/queryNextFrame()",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Frame",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable"
      ],
      "title": "Drawing a frame of content"
    },
    {
      "anchor": "Handling-events",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/onSpatialEvent"
      ],
      "title": "Handling events"
    },
    {
      "anchor": "Configuring-the-frame-update-rate",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/minimumFrameRepeatCount"
      ],
      "title": "Configuring the frame update rate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CP_OBJECT_cp_layer_renderer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.compositorservices/documentation/CompositorServices"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-layer-renderer",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_cp_layer_renderer_configuration",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_cp_layer_renderer_capabilities"
              ],
              "title": "Configuring the layer renderer"
            },
            {
              "anchor": "Getting-the-layer-renderer-properties",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_cp_layer_renderer_properties"
              ],
              "title": "Getting the layer renderer properties"
            },
            {
              "anchor": "Getting-the-GPU-device",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/device"
              ],
              "title": "Getting the GPU device"
            },
            {
              "anchor": "Managing-the-rendering-loop",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/state-swift.property",
                "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/waitUntilRunning()",
                "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/State-swift.enum"
              ],
              "title": "Managing the rendering loop"
            },
            {
              "anchor": "Drawing-a-frame-of-content",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t"
              ],
              "title": "Drawing a frame of content"
            },
            {
              "anchor": "Configuring-the-frame-update-rate",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/minimumFrameRepeatCount"
              ],
              "title": "Configuring the frame update rate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CP_OBJECT_cp_layer_renderer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/title",
          "value": "CP_OBJECT_cp_layer_renderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1device/title",
          "value": "cp_layer_renderer_get_device"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1device/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_get_device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1waitUntilRunning()/title",
          "value": "cp_layer_renderer_wait_until_running"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1waitUntilRunning()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_wait_until_running"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1minimumFrameRepeatCount/title",
          "value": "cp_layer_renderer_get_minimum_frame_repeat_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1minimumFrameRepeatCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_get_minimum_frame_repeat_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1State-swift.enum/title",
          "value": "cp_layer_renderer_state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1state-swift.property/title",
          "value": "cp_layer_renderer_get_state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1state-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_get_state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/layerrenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compositorservices/layerrenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
