{
  "abstract": [
    {
      "text": "Common types and utilities to manage your app’s rendering process.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/utilities"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Utilities"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these functions to manage timing in your app’s render loop.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_release": {
      "abstract": [
        {
          "text": "Decrements the reference count of the specified object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_release"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_release",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_release",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_release"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_retain": {
      "abstract": [
        {
          "text": "Increments the reference count of the specified object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_retain"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_retain",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_retain",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_retain"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time_t": {
      "abstract": [
        {
          "text": "A Mach absolute time clock value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_time_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_time_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_time_t"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time_to_cf_time_interval": {
      "abstract": [
        {
          "text": "Converts a Mach absolute time value to a Core Foundation time value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_time_to_cf_time_interval"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time_to_cf_time_interval",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_time_to_cf_time_interval",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_time_to_cf_time_interval"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time_wait_until": {
      "abstract": [
        {
          "text": "Blocks the current thread until the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_time_wait_until"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time_wait_until",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_time_wait_until",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_time_wait_until"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/frames": {
      "abstract": [
        {
          "text": "A type that represents a single frame of content, manages the pace of animations,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and provides access to the drawable environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/frames",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Frames",
      "type": "topic",
      "url": "/documentation/compositorservices/frames"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/layer-renderer": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/layer-renderer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layer renderer",
      "type": "topic",
      "url": "/documentation/compositorservices/layer-renderer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Putting-the-current-thread-to-sleep",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time_wait_until"
              ],
              "title": "Putting the current thread to sleep"
            },
            {
              "anchor": "Converting-time-values",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time_to_cf_time_interval",
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time_t"
              ],
              "title": "Converting time values"
            },
            {
              "anchor": "Retaining-and-releasing-types",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_retain",
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_release"
              ],
              "title": "Retaining and releasing types"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Render-loop-setup",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/layer-renderer",
                "doc://com.apple.compositorservices/documentation/CompositorServices/frames"
              ],
              "title": "Render-loop setup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/utilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compositorservices/utilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
