{
  "abstract": [
    {
      "text": "Receive and process a Crash Detection event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safetykit/documentation/SafetyKit",
        "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionDelegate/crashDetectionManager(_:didDetect:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SACrashDetectionDelegate(im)crashDetectionManager:didDetectEvent:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "crashDetectionManager"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SACrashDetectionManager",
        "text": "SACrashDetectionManager"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didDetect"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SACrashDetectionEvent",
        "text": "SACrashDetectionEvent"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "SafetyKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "crashDetectionManager:didDetectEvent:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "crashDetectionManager(_:didDetect:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "crashDetectionManager"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "crashDetectionManager"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SACrashDetectionManager",
              "text": "SACrashDetectionManager"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didDetect"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "event"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SACrashDetectionEvent",
              "text": "SACrashDetectionEvent"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Crash Detection manager that detected the event.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "crashDetectionManager"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Crash Detection event.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "event"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To receive Crash Detection events, create a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance and set its delegate early in the app life cycle, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/applicationDidFinishLaunching(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Use the iOS Simulator to test Crash Detection events and the background functionality of your app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Following a Crash Detection event, the system launches the app in the background. When the app launches, it performs critical tasks related to the Crash Detection event, such as placing a network request or scheduling a local notification. If the system generates multiple Crash Detection events while the app isn’t running, it reports the most recent event on the next app launch. The system may report the same Crash Detection event across different launches of your app, so always check ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/date",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " before processing it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/applicationDidFinishLaunching(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the app has finished launching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidFinishLaunching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/applicationDidFinishLaunching(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "applicationDidFinishLaunching(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/applicationDidFinishLaunching(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit": {
      "abstract": [
        {
          "text": "Detect and respond to car crash events in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SafetyKit",
      "type": "topic",
      "url": "/documentation/safetykit"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionDelegate": {
      "abstract": [
        {
          "text": "The protocol that an object adopts to receive Crash Detection events and changes to the authorization status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SACrashDetectionDelegate"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SACrashDetectionDelegate"
        }
      ],
      "role": "symbol",
      "title": "SACrashDetectionDelegate",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectiondelegate"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionDelegate/crashDetectionManager(_:didDetect:)": {
      "abstract": [
        {
          "text": "Receive and process a Crash Detection event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crashDetectionManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SACrashDetectionManager",
          "text": "SACrashDetectionManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDetect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SACrashDetectionEvent",
          "text": "SACrashDetectionEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionDelegate/crashDetectionManager(_:didDetect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "crashDetectionManager:didDetectEvent:"
        }
      ],
      "role": "symbol",
      "title": "crashDetectionManager(_:didDetect:)",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectiondelegate/crashdetectionmanager(_:diddetect:)"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent": {
      "abstract": [
        {
          "text": "Describes the information about a vehicular crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SACrashDetectionEvent"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SACrashDetectionEvent"
        }
      ],
      "role": "symbol",
      "title": "SACrashDetectionEvent",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/date": {
      "abstract": [
        {
          "text": "The date and time the crash occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/date",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "date"
        }
      ],
      "role": "symbol",
      "title": "date",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent/date"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionManager": {
      "abstract": [
        {
          "text": "Provides registration and management of Crash Detection events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SACrashDetectionManager"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SACrashDetectionManager"
        }
      ],
      "role": "symbol",
      "title": "SACrashDetectionManager",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionmanager"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "crashDetectionManager:didDetectEvent:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "crashDetectionManager:didDetectEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.safetykit/documentation/SafetyKit",
                "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "crashDetectionManager:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionManager",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SACrashDetectionManager",
                    "text": "SACrashDetectionManager"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "crashDetectionManager"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didDetectEvent:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SACrashDetectionEvent",
                    "text": "SACrashDetectionEvent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "event"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The Crash Detection manager that detected the event.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "crashDetectionManager"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The Crash Detection event.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "event"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidFinishLaunching(_:)/title",
          "value": "applicationDidFinishLaunching:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidFinishLaunching(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "applicationDidFinishLaunching:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionManager/title",
          "value": "SACrashDetectionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionDelegate/title",
          "value": "SACrashDetectionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent/title",
          "value": "SACrashDetectionEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1date/title",
          "value": "date"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1date/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionDelegate~1crashDetectionManager(_:didDetect:)/title",
          "value": "crashDetectionManager:didDetectEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionDelegate~1crashDetectionManager(_:didDetect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "crashDetectionManager:didDetectEvent:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safetykit/sacrashdetectiondelegate/crashdetectionmanager(_:diddetect:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safetykit/sacrashdetectiondelegate/crashdetectionmanager(_:diddetect:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
