{
  "abstract": [
    {
      "text": "A notification the system posts when the list of authorized routes changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avrouting/documentation/AVRouting",
        "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/authorizedRoutesDidChange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVRouting",
    "externalID": "c:@AVCustomRoutingControllerAuthorizedRoutesDidChangeNotification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "authorizedRoutesDidChange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNotification",
        "text": "NSNotification"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSNotificationName",
        "text": "Name"
      }
    ],
    "modules": [
      {
        "name": "AVRouting"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCustomRoutingControllerAuthorizedRoutesDidChangeNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "authorizedRoutesDidChange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "authorizedRoutesDidChange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNotification",
              "text": "NSNotification"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSNotificationName",
              "text": "Name"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avrouting/documentation/AVRouting": {
      "abstract": [
        {
          "text": "Display custom destinations to stream media in the system route picker.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting",
      "kind": "symbol",
      "role": "collection",
      "title": "AVRouting",
      "type": "topic",
      "url": "/documentation/avrouting"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController": {
      "abstract": [
        {
          "text": "An object that manages the connection from a device to a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCustomRoutingController"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCustomRoutingController"
        }
      ],
      "role": "symbol",
      "title": "AVCustomRoutingController",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingcontroller"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/authorizedRoutes": {
      "abstract": [
        {
          "text": "A list of authorized routes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizedRoutes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCustomDeviceRoute",
          "text": "AVCustomDeviceRoute"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/authorizedRoutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizedRoutes"
        }
      ],
      "role": "symbol",
      "title": "authorizedRoutes",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingcontroller/authorizedroutes"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/authorizedRoutesDidChange": {
      "abstract": [
        {
          "text": "A notification the system posts when the list of authorized routes changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizedRoutesDidChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/authorizedRoutesDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCustomRoutingControllerAuthorizedRoutesDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "authorizedRoutesDidChange",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingcontroller/authorizedroutesdidchange"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/invalidateAuthorization(for:)": {
      "abstract": [
        {
          "text": "Revokes an app’s authorization to connect to a route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCustomDeviceRoute",
          "text": "AVCustomDeviceRoute"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/invalidateAuthorization(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateAuthorizationForRoute:"
        }
      ],
      "role": "symbol",
      "title": "invalidateAuthorization(for:)",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingcontroller/invalidateauthorization(for:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSNotificationName": {
      "abstract": [
        {
          "text": "A structure that defines the name of a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSNotification.Name"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification.Name",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification": {
      "abstract": [
        {
          "text": "An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNotification"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-authorization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/authorizedRoutes",
        "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/invalidateAuthorization(for:)"
      ],
      "title": "Managing authorization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCustomRoutingControllerAuthorizedRoutesDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingControllerAuthorizedRoutesDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avrouting/documentation/AVRouting"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-authorization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/authorizedRoutes",
                "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController/invalidateAuthorization(for:)"
              ],
              "title": "Managing authorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSNotificationName",
                    "text": "NSNotificationName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCustomRoutingControllerAuthorizedRoutesDidChangeNotification"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController/title",
          "value": "AVCustomRoutingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController~1authorizedRoutesDidChange/title",
          "value": "AVCustomRoutingControllerAuthorizedRoutesDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController~1authorizedRoutesDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingControllerAuthorizedRoutesDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController~1authorizedRoutes/title",
          "value": "authorizedRoutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController~1authorizedRoutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authorizedRoutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController~1invalidateAuthorization(for:)/title",
          "value": "invalidateAuthorizationForRoute:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController~1invalidateAuthorization(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateAuthorizationForRoute:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title",
          "value": "NSNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract",
          "value": [
            {
              "text": "A container for information broadcast through a notification center to all registered observers.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avrouting/avcustomroutingcontroller/authorizedroutesdidchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avrouting/avcustomroutingcontroller/authorizedroutesdidchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
