{
  "abstract": [
    {
      "text": "Identifies the type that indicates the join reason.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pushtotalk/documentation/PushToTalk"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PTChannelJoinReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PTChannelJoinReason"
      }
    ],
    "modules": [
      {
        "name": "Push to Talk"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PTChannelJoinReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PTChannelJoinReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PTChannelJoinReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/pushtotalk"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason": {
      "abstract": [
        {
          "text": "Identifies the type that indicates the join reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelJoinReason"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelJoinReason"
        }
      ],
      "role": "symbol",
      "title": "PTChannelJoinReason",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneljoinreason"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/channelRestoration": {
      "abstract": [
        {
          "text": "A join reason that indicates the app rejoined a channel through channel restoration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelRestoration"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/channelRestoration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelJoinReasonChannelRestoration"
        }
      ],
      "role": "symbol",
      "title": "PTChannelJoinReason.channelRestoration",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneljoinreason/channelrestoration"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/developerRequest": {
      "abstract": [
        {
          "text": "A join reason that indicates the app calls the join channel method while in the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "developerRequest"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/developerRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelJoinReasonDeveloperRequest"
        }
      ],
      "role": "symbol",
      "title": "PTChannelJoinReason.developerRequest",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneljoinreason/developerrequest"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneljoinreason/init(rawvalue:)"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelLeaveReason": {
      "abstract": [
        {
          "text": "Identifies the type that indicates the leave reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelLeaveReason"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelLeaveReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelLeaveReason"
        }
      ],
      "role": "symbol",
      "title": "PTChannelLeaveReason",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelleavereason"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManagerDelegate": {
      "abstract": [
        {
          "text": "A type that represents your life cycle of a channel manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelManagerDelegate"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManagerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelManagerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PTChannelManagerDelegate",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelmanagerdelegate"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource": {
      "abstract": [
        {
          "text": "Identifies the type that indicates the transmission request source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSource"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSource"
        }
      ],
      "role": "symbol",
      "title": "PTChannelTransmitRequestSource",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneltransmitrequestsource"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTServiceStatus": {
      "abstract": [
        {
          "text": "Identifies the type that indicates the status of the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTServiceStatus"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTServiceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTServiceStatus"
        }
      ],
      "role": "symbol",
      "title": "PTServiceStatus",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptservicestatus"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode": {
      "abstract": [
        {
          "text": "Identifies the type of audio transmission modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTTransmissionMode"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTTransmissionMode"
        }
      ],
      "role": "symbol",
      "title": "PTTransmissionMode",
      "type": "topic",
      "url": "/documentation/pushtotalk/pttransmissionmode"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Channel-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManagerDelegate",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTServiceStatus",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelLeaveReason",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource"
      ],
      "title": "Channel management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Join-reasons",
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/developerRequest",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/channelRestoration"
      ],
      "title": "Join reasons"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PTChannelJoinReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelJoinReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelJoinReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pushtotalk/documentation/PushToTalk"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Join-reasons",
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/developerRequest",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason/channelRestoration"
              ],
              "title": "Join reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Channel-management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManagerDelegate",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTServiceStatus",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelLeaveReason",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource"
              ],
              "title": "Channel management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PTChannelJoinReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason~1developerRequest/title",
          "value": "PTChannelJoinReasonDeveloperRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason~1developerRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelJoinReasonDeveloperRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason/title",
          "value": "PTChannelJoinReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelJoinReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelJoinReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelLeaveReason/title",
          "value": "PTChannelLeaveReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelLeaveReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelLeaveReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelLeaveReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelLeaveReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelManagerDelegate/title",
          "value": "PTChannelManagerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelManagerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelManagerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason~1channelRestoration/title",
          "value": "PTChannelJoinReasonChannelRestoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason~1channelRestoration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelJoinReasonChannelRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode/title",
          "value": "PTTransmissionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource/title",
          "value": "PTChannelTransmitRequestSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTServiceStatus/title",
          "value": "PTServiceStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTServiceStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTServiceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTServiceStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTServiceStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushtotalk/ptchanneljoinreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pushtotalk/ptchanneljoinreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
