{
  "abstract": [
    {
      "text": "Returns an image object that contains the specified portion of the drawing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/image(from:scale:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKDrawing(im)imageFromRect:scale:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "image"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "from"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGRect",
        "text": "CGRect"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "scale"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIImage",
        "text": "UIImage"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "imageFromRect:scale:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "image(from:scale:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "image"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "scale"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSImage",
              "text": "NSImage"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "image"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "scale"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIImage",
              "text": "UIImage"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The portion of the drawing that you want to capture. Specify a rectangle in the canvas’ coordinate system.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The scale factor at which to create the image. Specifying scale factors greater than ",
                  "type": "text"
                },
                {
                  "code": "1.0",
                  "type": "codeVoice"
                },
                {
                  "text": " creates an image with more detail. For example, you might specify a scale factor of ",
                  "type": "text"
                },
                {
                  "code": "2.0",
                  "type": "codeVoice"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "code": "3.0",
                  "type": "codeVoice"
                },
                {
                  "text": " when displaying the image on a Retina display.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "scale"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new image object that contains the rendered content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method creates a new image and renders content from the canvas into that image at the specified scale factor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference": {
      "abstract": [
        {
          "text": "A data structure that contains the drawing information captured by a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDrawingReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDrawingReference"
        }
      ],
      "role": "symbol",
      "title": "PKDrawingReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/image(from:scale:)": {
      "abstract": [
        {
          "text": "Returns an image object that contains the specified portion of the drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/image(from:scale:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageFromRect:scale:"
        }
      ],
      "role": "symbol",
      "title": "image(from:scale:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/image(from:scale:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGRect": {
      "abstract": [
        {
          "text": "A structure that contains the location and dimensions of a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGRect",
      "type": "topic",
      "url": "/documentation/corefoundation/cgrect"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/AppKit/NSImage"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/UIKit/UIImage"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "imageFromRect:scale:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageFromRect:scale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pencilkit/documentation/PencilKit",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIImage",
                    "text": "UIImage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "imageFromRect:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGRect",
                    "text": "CGRect"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rect"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "scale:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "scale"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSImage",
                    "text": "NSImage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "imageFromRect:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGRect",
                    "text": "CGRect"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rect"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "scale:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "scale"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The portion of the drawing that you want to capture. Specify a rectangle in the canvas’ coordinate system.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "rect"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The scale factor at which to create the image. Specifying scale factors greater than ",
                        "type": "text"
                      },
                      {
                        "code": "1.0",
                        "type": "codeVoice"
                      },
                      {
                        "text": " creates an image with more detail. For example, you might specify a scale factor of ",
                        "type": "text"
                      },
                      {
                        "code": "2.0",
                        "type": "codeVoice"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "code": "3.0",
                        "type": "codeVoice"
                      },
                      {
                        "text": " when displaying the image on a Retina display.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "scale"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new image object that contains the rendered content.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1image(from:scale:)/title",
          "value": "imageFromRect:scale:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1image(from:scale:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageFromRect:scale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/title",
          "value": "PKDrawing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pkdrawingreference/image(from:scale:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pencilkit/pkdrawingreference/image(from:scale:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
