{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.CFBundleIcons.CFBundleAlternateIcons.AppIconReferenceName",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AppIconReferenceName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "AppIconReferenceName"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "AppIconReferenceName",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons": {
      "abstract": [
        {
          "text": "Information about all of the icons used by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon files (iOS 5)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
      "kind": "symbol",
      "name": "CFBundleIcons",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIcons"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIcons",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons": {
      "abstract": [
        {
          "text": "A list of alternate icons for the Home screen and Settings app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons",
      "kind": "symbol",
      "name": "CFBundleAlternateIcons",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleAlternateIcons"
        }
      ],
      "role": "symbol",
      "title": "CFBundleAlternateIcons",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundlealternateicons"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName",
      "kind": "symbol",
      "name": "AppIconReferenceName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppIconReferenceName"
        }
      ],
      "role": "symbol",
      "title": "AppIconReferenceName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundlealternateicons/appiconreferencename"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName/CFBundleIconFiles": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName/CFBundleIconFiles",
      "kind": "symbol",
      "name": "CFBundleIconFiles",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIconFiles"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIconFiles",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundlealternateicons/appiconreferencename/cfbundleiconfiles"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName/UIPrerenderedIcon": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName/UIPrerenderedIcon",
      "kind": "symbol",
      "name": "UIPrerenderedIcon",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrerenderedIcon"
        }
      ],
      "role": "symbol",
      "title": "UIPrerenderedIcon",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundlealternateicons/appiconreferencename/uiprerenderedicon"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Property-List-Keys",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName/CFBundleIconFiles",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName/UIPrerenderedIcon"
      ],
      "title": "Property List Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AppIconReferenceName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AppIconReferenceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Property-List-Keys",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName/CFBundleIconFiles",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons/CFBundleAlternateIcons/AppIconReferenceName/UIPrerenderedIcon"
              ],
              "title": "Property List Keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundleAlternateIcons~1AppIconReferenceName/title",
          "value": "AppIconReferenceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundleAlternateIcons~1AppIconReferenceName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AppIconReferenceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundleAlternateIcons~1AppIconReferenceName~1CFBundleIconFiles/title",
          "value": "CFBundleIconFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundleAlternateIcons~1AppIconReferenceName~1CFBundleIconFiles/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIconFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundleAlternateIcons~1AppIconReferenceName~1UIPrerenderedIcon/title",
          "value": "UIPrerenderedIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundleAlternateIcons~1AppIconReferenceName~1UIPrerenderedIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrerenderedIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons/title",
          "value": "CFBundleIcons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIcons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundleAlternateIcons/title",
          "value": "CFBundleAlternateIcons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons~1CFBundleAlternateIcons/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleAlternateIcons"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundlealternateicons/appiconreferencename"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfbundleicons/cfbundlealternateicons/appiconreferencename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
