{"sections":[],"kind":"symbol","metadata":{"externalID":"c:objc(pl)NSCollectionViewPrefetching(im)collectionView:cancelPrefetchingForItemsAtIndexPaths:","navigatorTitle":[{"kind":"identifier","text":"collectionView:cancelPrefetchingForItemsAtIndexPaths:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSCollectionView","preciseIdentifier":"c:objc(cs)NSCollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancelPrefetchingForItemsAt"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"])"}],"modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","introducedAt":"10.10","beta":false,"deprecated":false,"unavailable":false}],"role":"symbol","roleHeading":"Instance Method","title":"collectionView(_:cancelPrefetchingForItemsAt:)","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching/collectionView(_:prefetchItemsAt:)"]}],"variants":[{"paths":["/documentation/appkit/nscollectionviewprefetching/collectionview(_:cancelprefetchingforitemsat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscollectionviewprefetching/collectionview(_:cancelprefetchingforitemsat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching/collectionView(_:cancelPrefetchingForItemsAt:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSCollectionView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionView","preciseIdentifier":"c:objc(cs)NSCollectionView"},{"text":", ","kind":"text"},{"text":"cancelPrefetchingForItemsAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPaths","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":"])","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching/collectionView(_:cancelPrefetchingForItemsAt:)":{"title":"collectionView(_:cancelPrefetchingForItemsAt:)","navigatorTitle":[{"text":"collectionView:cancelPrefetchingForItemsAtIndexPaths:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching/collectionView(_:cancelPrefetchingForItemsAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCollectionView","preciseIdentifier":"c:objc(cs)NSCollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cancelPrefetchingForItemsAt","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"kind":"symbol","abstract":[],"url":"/documentation/appkit/nscollectionviewprefetching/collectionview(_:cancelprefetchingforitemsat:)"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching":{"title":"NSCollectionViewPrefetching","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching","type":"topic","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewPrefetching"}],"navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewPrefetching"}],"url":"/documentation/appkit/nscollectionviewprefetching"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionView":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionView","navigatorTitle":[{"text":"NSCollectionView","kind":"identifier"}],"abstract":[{"type":"text","text":"An ordered collection of data items displayed in a customizable layout."}],"type":"topic","title":"NSCollectionView","url":"/documentation/appkit/nscollectionview"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV":{"title":"IndexPath","type":"topic","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"IndexPath"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV","abstract":[{"type":"text","text":"A list of indexes that together represent the path to a specific location in a tree of nested arrays. "}],"role":"symbol","url":"/documentation/foundation/indexpath","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching/collectionView(_:prefetchItemsAt:)":{"required":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching/collectionView(_:prefetchItemsAt:)","role":"symbol","navigatorTitle":[{"text":"collectionView:prefetchItemsAtIndexPaths:","kind":"identifier"}],"url":"/documentation/appkit/nscollectionviewprefetching/collectionview(_:prefetchitemsat:)","title":"collectionView(_:prefetchItemsAt:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"text":"NSCollectionView","preciseIdentifier":"c:objc(cs)NSCollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"prefetchItemsAt","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}]},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"collectionView:cancelPrefetchingForItemsAtIndexPaths:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:cancelPrefetchingForItemsAtIndexPaths:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching/collectionView(_:prefetchItemsAt:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSCollectionView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionView","kind":"typeIdentifier","text":"NSCollectionView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"text":"cancelPrefetchingForItemsAtIndexPaths:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSIndexPath *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indexPaths","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"collectionView:cancelPrefetchingForItemsAtIndexPaths:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching~1collectionView(_:cancelPrefetchingForItemsAt:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cancelPrefetchingForItemsAtIndexPaths:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching~1collectionView(_:cancelPrefetchingForItemsAt:)/fragments"},{"op":"replace","value":"NSCollectionViewPrefetching","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewPrefetching"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewPrefetching"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching/navigatorTitle"},{"op":"replace","value":"NSCollectionView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/title"},{"op":"replace","value":[{"text":"NSCollectionView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/fragments"},{"op":"replace","value":[{"text":"NSCollectionView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/navigatorTitle"},{"op":"replace","value":"collectionView:prefetchItemsAtIndexPaths:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching~1collectionView(_:prefetchItemsAt:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:prefetchItemsAtIndexPaths:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching~1collectionView(_:prefetchItemsAt:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}