{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedString","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The attributed string of the receiver’s text storage.","type":"text"}]}],"kind":"content"},{"content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Implementation of this method is optional. A class adopting the "},{"type":"codeVoice","code":"NSTextInputClient"},{"type":"text","text":" protocol can implement this interface if it can be done efficiently to enable callers of this interface to access arbitrary portions of the receiver’s content more efficiently."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Returns an attributed string representing the receiver’s text storage."}],"sections":[],"metadata":{"navigatorTitle":[{"text":"attributedString","kind":"identifier"}],"platforms":[{"introducedAt":"10.0","deprecated":false,"unavailable":false,"name":"macOS","beta":false}],"roleHeading":"Instance Method","title":"attributedString()","externalID":"c:objc(pl)NSTextInputClient(im)attributedString","role":"symbol","symbolKind":"method","modules":[{"name":"AppKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedString","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nstextinputclient/attributedstring()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nstextinputclient/attributedstring()"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient"]]},"seeAlsoSections":[{"generated":true,"anchor":"Storing-text","title":"Storing text","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)"]}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient","kind":"symbol","navigatorTitle":[{"text":"NSTextInputClient","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSTextInputClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextInputClient","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of methods that text views need to implement to interact properly with the text input management system."}],"url":"/documentation/appkit/nstextinputclient"},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)":{"navigatorTitle":[{"text":"attributedSubstringForProposedRange:actualRange:","kind":"identifier"}],"url":"/documentation/appkit/nstextinputclient/attributedsubstring(forproposedrange:actualrange:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)","required":true,"title":"attributedSubstring(forProposedRange:actualRange:)","kind":"symbol","type":"topic","abstract":[{"text":"Returns an attributed string derived from the given range in the receiver’s text storage.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedSubstring","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forProposedRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"actualRange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRangePointer","text":"NSRangePointer","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()":{"navigatorTitle":[{"text":"attributedString","kind":"identifier"}],"abstract":[{"text":"Returns an attributed string representing the receiver’s text storage.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedString","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"}],"title":"attributedString()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()","kind":"symbol","type":"topic","url":"/documentation/appkit/nstextinputclient/attributedstring()"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)":{"navigatorTitle":[{"text":"insertText:replacementRange:","kind":"identifier"}],"url":"/documentation/appkit/nstextinputclient/inserttext(_:replacementrange:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)","required":true,"title":"insertText(_:replacementRange:)","kind":"symbol","type":"topic","abstract":[{"text":"Inserts the given string into the receiver, replacing the specified content.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"replacementRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString":{"kind":"symbol","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSAttributedString","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","abstract":[{"type":"text","text":"A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering."}],"type":"topic","title":"NSAttributedString","url":"/documentation/foundation/nsattributedstring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"path":"/metadata/title","op":"replace","value":"attributedString"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"attributedString"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Storing-text","title":"Storing text","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"attributedString"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The attributed string of the receiver’s text storage.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/title","op":"replace","value":"NSTextInputClient"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/fragments","op":"replace","value":[{"text":"NSTextInputClient","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/navigatorTitle","op":"replace","value":[{"text":"NSTextInputClient","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedSubstring(forProposedRange:actualRange:)/title","op":"replace","value":"attributedSubstringForProposedRange:actualRange:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedSubstring(forProposedRange:actualRange:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"attributedSubstringForProposedRange:actualRange:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedString()/title","op":"replace","value":"attributedString"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedString()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"attributedString","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1insertText(_:replacementRange:)/title","op":"replace","value":"insertText:replacementRange:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1insertText(_:replacementRange:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"insertText:replacementRange:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}