{"metadata":{"modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","platforms":[{"deprecated":false,"introducedAt":"10.0","unavailable":false,"name":"macOS","beta":false}],"symbolKind":"method","required":true,"externalID":"c:objc(pl)NSTextInputClient(im)attributedSubstringForProposedRange:actualRange:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"attributedSubstring","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forProposedRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"actualRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRangePointer","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRangePointer"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"attributedSubstringForProposedRange:actualRange:"}],"title":"attributedSubstring(forProposedRange:actualRange:)","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient"]]},"variants":[{"paths":["/documentation/appkit/nstextinputclient/attributedsubstring(forproposedrange:actualrange:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nstextinputclient/attributedsubstring(forproposedrange:actualrange:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributedSubstring"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProposedRange"},{"kind":"text","text":" "},{"kind":"internalParam","text":"range"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"actualRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRangePointer","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRangePointer","preciseIdentifier":"c:@T@NSRangePointer"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"NSAttributedString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"parameters":[{"name":"range","content":[{"type":"paragraph","inlineContent":[{"text":"The range in the text storage from which to create the returned string.","type":"text"}]}]},{"name":"actualRange","content":[{"inlineContent":[{"type":"text","text":"The actual range of the returned string if it was adjusted, for example, to a grapheme cluster boundary or for performance or other reasons. "},{"type":"codeVoice","code":"NULL"},{"type":"text","text":" if range was not adjusted."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The string created from the given range. May return "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"An implementation of this method should be prepared for ","type":"text"},{"code":"aRange","type":"codeVoice"},{"text":" to be out of bounds. For example, the InkWell text input service can ask for the contents of the text input client that extends beyond the document’s range. In this case, you should return the intersection of the document’s range and ","type":"text"},{"code":"aRange","type":"codeVoice"},{"text":". If the location of ","type":"text"},{"code":"aRange","type":"codeVoice"},{"text":" is completely outside of the document’s range, return ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"Returns an attributed string derived from the given range in the receiver’s text storage.","type":"text"}],"kind":"symbol","seeAlsoSections":[{"anchor":"Storing-text","title":"Storing text","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)"],"generated":true}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient","kind":"symbol","navigatorTitle":[{"text":"NSTextInputClient","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSTextInputClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextInputClient","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of methods that text views need to implement to interact properly with the text input management system."}],"url":"/documentation/appkit/nstextinputclient"},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)":{"navigatorTitle":[{"text":"insertText:replacementRange:","kind":"identifier"}],"url":"/documentation/appkit/nstextinputclient/inserttext(_:replacementrange:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)","required":true,"title":"insertText(_:replacementRange:)","kind":"symbol","type":"topic","abstract":[{"text":"Inserts the given string into the receiver, replacing the specified content.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"replacementRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)":{"navigatorTitle":[{"text":"attributedSubstringForProposedRange:actualRange:","kind":"identifier"}],"url":"/documentation/appkit/nstextinputclient/attributedsubstring(forproposedrange:actualrange:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)","required":true,"title":"attributedSubstring(forProposedRange:actualRange:)","kind":"symbol","type":"topic","abstract":[{"text":"Returns an attributed string derived from the given range in the receiver’s text storage.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedSubstring","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forProposedRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"actualRange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRangePointer","text":"NSRangePointer","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.externally.resolved.symbol/c:@S@_NSRange":{"role":"symbol","type":"topic","abstract":[{"text":"A Swift-only concrete structure that backs the range type alias.","type":"text"}],"url":"/documentation/foundation/nsrange-jio","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"_NSRange"}],"identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","title":"_NSRange"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:@T@NSRangePointer":{"kind":"symbol","url":"/documentation/foundation/nsrangepointer","role":"symbol","abstract":[{"type":"text","text":"Type indicating a parameter is a pointer to an `NSRange` structure."}],"title":"NSRangePointer","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRangePointer","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRangePointer","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString":{"kind":"symbol","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSAttributedString","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","abstract":[{"type":"text","text":"A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering."}],"type":"topic","title":"NSAttributedString","url":"/documentation/foundation/nsattributedstring"},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()":{"navigatorTitle":[{"text":"attributedString","kind":"identifier"}],"abstract":[{"text":"Returns an attributed string representing the receiver’s text storage.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedString","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"}],"title":"attributedString()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()","kind":"symbol","type":"topic","url":"/documentation/appkit/nstextinputclient/attributedstring()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"attributedSubstringForProposedRange:actualRange:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"attributedSubstringForProposedRange:actualRange:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Storing text","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)"],"anchor":"Storing-text","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSAttributedString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"attributedSubstringForProposedRange:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSRange","text":"NSRange"},{"kind":"text","text":") "},{"kind":"internalParam","text":"range"},{"kind":"text","text":" "},{"kind":"identifier","text":"actualRange:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRangePointer","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRangePointer","text":"NSRangePointer"},{"kind":"text","text":") "},{"kind":"internalParam","text":"actualRange"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The range in the text storage from which to create the returned string.","type":"text"}]}],"name":"range"},{"content":[{"inlineContent":[{"text":"The actual range of the returned string if it was adjusted, for example, to a grapheme cluster boundary or for performance or other reasons. ","type":"text"},{"type":"codeVoice","code":"NULL"},{"text":" if range was not adjusted.","type":"text"}],"type":"paragraph"}],"name":"actualRange"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"/primaryContentSections/2","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The string created from the given range. May return ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/title","value":"NSTextInputClient","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/fragments","value":[{"kind":"identifier","text":"NSTextInputClient"}],"op":"replace"},{"value":[{"kind":"identifier","text":"NSTextInputClient"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/navigatorTitle"},{"value":"insertText:replacementRange:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1insertText(_:replacementRange:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"insertText:replacementRange:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1insertText(_:replacementRange:)/fragments"},{"value":"attributedSubstringForProposedRange:actualRange:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedSubstring(forProposedRange:actualRange:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"attributedSubstringForProposedRange:actualRange:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedSubstring(forProposedRange:actualRange:)/fragments"},{"value":"attributedString","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedString()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"attributedString","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedString()/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}