{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nstextinputclient/inserttext(_:replacementrange:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nstextinputclient/inserttext(_:replacementrange:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"replacementRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"string","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text to insert, either an "},{"type":"codeVoice","code":"NSString"},{"type":"text","text":" or "},{"type":"codeVoice","code":"NSAttributedString"},{"type":"text","text":" instance."}]}]},{"name":"replacementRange","content":[{"inlineContent":[{"type":"text","text":"The range of content to replace in the receiver’s text storage."}],"type":"paragraph"}]}]},{"kind":"mentions","mentions":["doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard"]},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"This method is the entry point for inserting text typed by the user and is generally not suitable for other purposes. Programmatic modification of the text is best done by operating on the text storage directly. Because this method pertains to the actions of the user, the text view must be editable for the insertion to work."}],"type":"paragraph"}]}],"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inserts the given string into the receiver, replacing the specified content.","type":"text"}],"metadata":{"title":"insertText(_:replacementRange:)","externalID":"c:objc(pl)NSTextInputClient(im)insertText:replacementRange:","platforms":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"insertText:replacementRange:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertText"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":")"}],"required":true,"symbolKind":"method","role":"symbol","modules":[{"name":"AppKit"}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient"]]},"seeAlsoSections":[{"generated":true,"title":"Storing text","anchor":"Storing-text","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)"]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)":{"navigatorTitle":[{"text":"attributedSubstringForProposedRange:actualRange:","kind":"identifier"}],"url":"/documentation/appkit/nstextinputclient/attributedsubstring(forproposedrange:actualrange:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)","required":true,"title":"attributedSubstring(forProposedRange:actualRange:)","kind":"symbol","type":"topic","abstract":[{"text":"Returns an attributed string derived from the given range in the receiver’s text storage.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedSubstring","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forProposedRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"actualRange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRangePointer","text":"NSRangePointer","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)":{"navigatorTitle":[{"text":"insertText:replacementRange:","kind":"identifier"}],"url":"/documentation/appkit/nstextinputclient/inserttext(_:replacementrange:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/insertText(_:replacementRange:)","required":true,"title":"insertText(_:replacementRange:)","kind":"symbol","type":"topic","abstract":[{"text":"Inserts the given string into the receiver, replacing the specified content.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"replacementRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard":{"type":"topic","url":"/documentation/appkit/supporting-writing-tools-via-the-pasteboard","title":"Supporting Writing Tools via the pasteboard","abstract":[{"type":"text","text":"Adopt a simplified version of the Writing Tools experience in a custom"},{"type":"text","text":" "},{"type":"text","text":"view using the pasteboard and macOS services."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard","kind":"article","role":"article"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient","kind":"symbol","navigatorTitle":[{"text":"NSTextInputClient","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSTextInputClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextInputClient","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of methods that text views need to implement to interact properly with the text input management system."}],"url":"/documentation/appkit/nstextinputclient"},"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()":{"navigatorTitle":[{"text":"attributedString","kind":"identifier"}],"abstract":[{"text":"Returns an attributed string representing the receiver’s text storage.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedString","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"}],"title":"attributedString()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()","kind":"symbol","type":"topic","url":"/documentation/appkit/nstextinputclient/attributedstring()"},"doc://com.externally.resolved.symbol/c:@S@_NSRange":{"role":"symbol","type":"topic","abstract":[{"text":"A Swift-only concrete structure that backs the range type alias.","type":"text"}],"url":"/documentation/foundation/nsrange-jio","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"_NSRange"}],"identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","title":"_NSRange"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"insertText:replacementRange:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"insertText:replacementRange:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Storing text","anchor":"Storing-text","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedString()","doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/attributedSubstring(forProposedRange:actualRange:)"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"insertText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"replacementRange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRange","preciseIdentifier":"c:@S@_NSRange","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange"},{"text":") ","kind":"text"},{"text":"replacementRange","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text to insert, either an "},{"type":"codeVoice","code":"NSString"},{"type":"text","text":" or "},{"type":"codeVoice","code":"NSAttributedString"},{"type":"text","text":" instance."}]}],"name":"string"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The range of content to replace in the receiver’s text storage."}]}],"name":"replacementRange"}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"value":"attributedSubstringForProposedRange:actualRange:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedSubstring(forProposedRange:actualRange:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"attributedSubstringForProposedRange:actualRange:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedSubstring(forProposedRange:actualRange:)/fragments","op":"replace"},{"value":"insertText:replacementRange:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1insertText(_:replacementRange:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"insertText:replacementRange:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1insertText(_:replacementRange:)/fragments","op":"replace"},{"value":"NSTextInputClient","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/title","op":"replace"},{"value":[{"text":"NSTextInputClient","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSTextInputClient"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/navigatorTitle","op":"replace"},{"value":"attributedString","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedString()/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"attributedString","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1attributedString()/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}