{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the Mono Audio setting is in an enabled state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isMonoAudioEnabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@F@UIAccessibilityIsMonoAudioEnabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isMonoAudioEnabled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilityIsMonoAudioEnabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "isMonoAudioEnabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isMonoAudioEnabled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility": {
      "abstract": [
        {
          "text": "A namespace for accessibility symbols for UIKit apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibility"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibility"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isAssistiveTouchRunning": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether AssistiveTouch is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAssistiveTouchRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isAssistiveTouchRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsAssistiveTouchRunning"
        }
      ],
      "role": "symbol",
      "title": "isAssistiveTouchRunning",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isassistivetouchrunning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isBoldTextEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Bold Text setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBoldTextEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isBoldTextEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsBoldTextEnabled"
        }
      ],
      "role": "symbol",
      "title": "isBoldTextEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isboldtextenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isClosedCaptioningEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Closed Captions + SDH setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isClosedCaptioningEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isClosedCaptioningEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsClosedCaptioningEnabled"
        }
      ],
      "role": "symbol",
      "title": "isClosedCaptioningEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isclosedcaptioningenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isDarkerSystemColorsEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Increase Contrast setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDarkerSystemColorsEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isDarkerSystemColorsEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityDarkerSystemColorsEnabled"
        }
      ],
      "role": "symbol",
      "title": "isDarkerSystemColorsEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isdarkersystemcolorsenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isGrayscaleEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Color Filters and the Grayscale settings are in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isGrayscaleEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isGrayscaleEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsGrayscaleEnabled"
        }
      ],
      "role": "symbol",
      "title": "isGrayscaleEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isgrayscaleenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isGuidedAccessEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Guided Access setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isGuidedAccessEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isGuidedAccessEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsGuidedAccessEnabled"
        }
      ],
      "role": "symbol",
      "title": "isGuidedAccessEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isguidedaccessenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isInvertColorsEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Classic Invert setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInvertColorsEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isInvertColorsEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsInvertColorsEnabled"
        }
      ],
      "role": "symbol",
      "title": "isInvertColorsEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isinvertcolorsenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isMonoAudioEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Mono Audio setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isMonoAudioEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isMonoAudioEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsMonoAudioEnabled"
        }
      ],
      "role": "symbol",
      "title": "isMonoAudioEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/ismonoaudioenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isOnOffSwitchLabelsEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the On/Off Labels setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isOnOffSwitchLabelsEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isOnOffSwitchLabelsEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsOnOffSwitchLabelsEnabled"
        }
      ],
      "role": "symbol",
      "title": "isOnOffSwitchLabelsEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isonoffswitchlabelsenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isReduceMotionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Reduce Motion setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isReduceMotionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isReduceMotionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsReduceMotionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isReduceMotionEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isreducemotionenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isReduceTransparencyEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Reduce Transparency setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isReduceTransparencyEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isReduceTransparencyEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsReduceTransparencyEnabled"
        }
      ],
      "role": "symbol",
      "title": "isReduceTransparencyEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isreducetransparencyenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isShakeToUndoEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Shake to Undo setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isShakeToUndoEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isShakeToUndoEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsShakeToUndoEnabled"
        }
      ],
      "role": "symbol",
      "title": "isShakeToUndoEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isshaketoundoenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSpeakScreenEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Speak Screen setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSpeakScreenEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSpeakScreenEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsSpeakScreenEnabled"
        }
      ],
      "role": "symbol",
      "title": "isSpeakScreenEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isspeakscreenenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSpeakSelectionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Speak Selection setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSpeakSelectionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSpeakSelectionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsSpeakSelectionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isSpeakSelectionEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isspeakselectionenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSwitchControlRunning": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Switch Control setting is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSwitchControlRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSwitchControlRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsSwitchControlRunning"
        }
      ],
      "role": "symbol",
      "title": "isSwitchControlRunning",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isswitchcontrolrunning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isVoiceOverRunning": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether VoiceOver is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isVoiceOverRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isVoiceOverRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIsVoiceOverRunning"
        }
      ],
      "role": "symbol",
      "title": "isVoiceOverRunning",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/isvoiceoverrunning"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Capabilities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isAssistiveTouchRunning",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isVoiceOverRunning",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSwitchControlRunning",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isShakeToUndoEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isClosedCaptioningEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isBoldTextEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isDarkerSystemColorsEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isGrayscaleEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isGuidedAccessEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isInvertColorsEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isReduceMotionEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isReduceTransparencyEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSpeakScreenEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSpeakSelectionEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isOnOffSwitchLabelsEnabled"
      ],
      "title": "Capabilities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityIsMonoAudioEnabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsMonoAudioEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Capabilities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isAssistiveTouchRunning",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isVoiceOverRunning",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSwitchControlRunning",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isShakeToUndoEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isClosedCaptioningEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isBoldTextEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isDarkerSystemColorsEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isGrayscaleEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isGuidedAccessEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isInvertColorsEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isReduceMotionEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isReduceTransparencyEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSpeakScreenEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isSpeakSelectionEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/isOnOffSwitchLabelsEnabled"
              ],
              "title": "Capabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityIsMonoAudioEnabled"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isAssistiveTouchRunning/title",
          "value": "UIAccessibilityIsAssistiveTouchRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isAssistiveTouchRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsAssistiveTouchRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isReduceMotionEnabled/title",
          "value": "UIAccessibilityIsReduceMotionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isReduceMotionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsReduceMotionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isSpeakSelectionEnabled/title",
          "value": "UIAccessibilityIsSpeakSelectionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isSpeakSelectionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsSpeakSelectionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isMonoAudioEnabled/title",
          "value": "UIAccessibilityIsMonoAudioEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isMonoAudioEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsMonoAudioEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isSpeakScreenEnabled/title",
          "value": "UIAccessibilityIsSpeakScreenEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isSpeakScreenEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsSpeakScreenEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isBoldTextEnabled/title",
          "value": "UIAccessibilityIsBoldTextEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isBoldTextEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsBoldTextEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isInvertColorsEnabled/title",
          "value": "UIAccessibilityIsInvertColorsEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isInvertColorsEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsInvertColorsEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isSwitchControlRunning/title",
          "value": "UIAccessibilityIsSwitchControlRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isSwitchControlRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsSwitchControlRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isGrayscaleEnabled/title",
          "value": "UIAccessibilityIsGrayscaleEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isGrayscaleEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsGrayscaleEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isOnOffSwitchLabelsEnabled/title",
          "value": "UIAccessibilityIsOnOffSwitchLabelsEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isOnOffSwitchLabelsEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsOnOffSwitchLabelsEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isGuidedAccessEnabled/title",
          "value": "UIAccessibilityIsGuidedAccessEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isGuidedAccessEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsGuidedAccessEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isDarkerSystemColorsEnabled/title",
          "value": "UIAccessibilityDarkerSystemColorsEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isDarkerSystemColorsEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityDarkerSystemColorsEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isVoiceOverRunning/title",
          "value": "UIAccessibilityIsVoiceOverRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isVoiceOverRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsVoiceOverRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isShakeToUndoEnabled/title",
          "value": "UIAccessibilityIsShakeToUndoEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isShakeToUndoEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsShakeToUndoEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isReduceTransparencyEnabled/title",
          "value": "UIAccessibilityIsReduceTransparencyEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isReduceTransparencyEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsReduceTransparencyEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isClosedCaptioningEnabled/title",
          "value": "UIAccessibilityIsClosedCaptioningEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1isClosedCaptioningEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIsClosedCaptioningEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibility/ismonoaudioenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibility/ismonoaudioenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
