{
  "abstract": [
    {
      "text": "An accessibility notification that an app can send.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@T@UIAccessibilityNotifications",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Notification"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Notification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIAccessibility.Notification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Notification"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility": {
      "abstract": [
        {
          "text": "A namespace for accessibility symbols for UIKit apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibility"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibility"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier": {
      "abstract": [
        {
          "text": "Identifiers for assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AssistiveTechnologyIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AssistiveTechnologyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.AssistiveTechnologyIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/assistivetechnologyidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification": {
      "abstract": [
        {
          "text": "An accessibility notification that an app can send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Notification"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.Notification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/announcement": {
      "abstract": [
        {
          "text": "A notification that an app posts when it needs to convey an announcement to the assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "announcement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/announcement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityAnnouncementNotification"
        }
      ],
      "role": "symbol",
      "title": "announcement",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/announcement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an accessibility notification with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/layoutChanged": {
      "abstract": [
        {
          "text": "A notification that an app posts when the layout of a screen changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/layoutChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityLayoutChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "layoutChanged",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/layoutchanged"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pageScrolled": {
      "abstract": [
        {
          "text": "A notification that an app posts when a scroll action completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageScrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pageScrolled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPageScrolledNotification"
        }
      ],
      "role": "symbol",
      "title": "pageScrolled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/pagescrolled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pauseAssistiveTechnology": {
      "abstract": [
        {
          "text": "A notification that pauses an assistive app’s operations temporarily.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseAssistiveTechnology"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pauseAssistiveTechnology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPauseAssistiveTechnologyNotification"
        }
      ],
      "role": "symbol",
      "title": "pauseAssistiveTechnology",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/pauseassistivetechnology"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/resumeAssistiveTechnology": {
      "abstract": [
        {
          "text": "A notification that resumes an assistive app’s operations temporarily.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumeAssistiveTechnology"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/resumeAssistiveTechnology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityResumeAssistiveTechnologyNotification"
        }
      ],
      "role": "symbol",
      "title": "resumeAssistiveTechnology",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/resumeassistivetechnology"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/screenChanged": {
      "abstract": [
        {
          "text": "A notification that an app posts when a new view appears that occupies a major portion of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/screenChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScreenChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "screenChanged",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/screenchanged"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)": {
      "abstract": [
        {
          "text": "Posts a notification to assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "post"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "notification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPostNotification"
        }
      ],
      "role": "symbol",
      "title": "post(notification:argument:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/post(notification:argument:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/notification-dictionary-keys": {
      "abstract": [
        {
          "text": "Handle notifications with keys in the user info dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/notification-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Notification dictionary keys",
      "type": "topic",
      "url": "/documentation/uikit/notification-dictionary-keys"
    },
    "doc://com.apple.uikit/documentation/UIKit/notification-names": {
      "abstract": [
        {
          "text": "The names of notifications that the accessibility system generates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/notification-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Notification names",
      "type": "topic",
      "url": "/documentation/uikit/notification-names"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/notification-names",
        "doc://com.apple.uikit/documentation/UIKit/notification-dictionary-keys",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)"
      ],
      "title": "Handling notifications"
    }
  ],
  "topicSections": [
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/announcement",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/layoutChanged",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/screenChanged",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pageScrolled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pauseAssistiveTechnology",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/resumeAssistiveTechnology",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier"
      ],
      "title": "Notifications"
    },
    {
      "anchor": "Initializer",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/init(rawValue:)"
      ],
      "title": "Initializer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityNotifications"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/announcement",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/layoutChanged",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/screenChanged",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pageScrolled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pauseAssistiveTechnology",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/resumeAssistiveTechnology",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/notification-names",
                "doc://com.apple.uikit/documentation/UIKit/notification-dictionary-keys",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)"
              ],
              "title": "Handling notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityNotifications"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1pauseAssistiveTechnology/title",
          "value": "UIAccessibilityPauseAssistiveTechnologyNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1pauseAssistiveTechnology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPauseAssistiveTechnologyNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1post(notification:argument:)/title",
          "value": "UIAccessibilityPostNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1post(notification:argument:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPostNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1layoutChanged/title",
          "value": "UIAccessibilityLayoutChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1layoutChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityLayoutChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1resumeAssistiveTechnology/title",
          "value": "UIAccessibilityResumeAssistiveTechnologyNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1resumeAssistiveTechnology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityResumeAssistiveTechnologyNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1screenChanged/title",
          "value": "UIAccessibilityScreenChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1screenChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScreenChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/title",
          "value": "UIAccessibilityAssistiveTechnologyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTechnologyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTechnologyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1announcement/title",
          "value": "UIAccessibilityAnnouncementNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1announcement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAnnouncementNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification/title",
          "value": "UIAccessibilityNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1pageScrolled/title",
          "value": "UIAccessibilityPageScrolledNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1pageScrolled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPageScrolledNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibility/notification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibility/notification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
