{
  "abstract": [
    {
      "text": "Creates an anchored object query descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQueryDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQueryDescriptor/init(predicates:anchor:limit:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9HealthKit31HKAnchoredObjectQueryDescriptorV10predicates6anchor5limitACyxGSayAA17HKSamplePredicateVyxGG_So13HKQueryAnchorCSgSiSgtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "predicates"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
        "text": "HKSamplePredicate"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "Sample"
      },
      {
        "kind": "text",
        "text": ">], "
      },
      {
        "kind": "externalParam",
        "text": "anchor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKQueryAnchor",
        "text": "HKQueryAnchor"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "limit"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(predicates:anchor:limit:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "predicates"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
              "text": "HKSamplePredicate"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "Sample"
            },
            {
              "kind": "text",
              "text": ">], "
            },
            {
              "kind": "externalParam",
              "text": "anchor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQueryAnchor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKQueryAnchor",
              "text": "HKQueryAnchor"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "limit"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": "? = nil)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of sample predicates that define the type of data that the query returns. To query for multiple types of data, provide a sample predicate for each type.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "predicates"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An anchor that a previous anchored object query returned. The anchor object corresponds to the last object that the previous query returned. The current query returns only samples and deleted objects newer than the anchor. Pass ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " to receive all the matching samples and recently deleted objects currently in the HealthKit store.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "anchor"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional value that specifies the maximum number of samples that the query returns. If you don’t specify the limit, the system returns all matching samples in the HealthKit store.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "limit"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system sets the descriptor’s ",
              "type": "text"
            },
            {
              "code": "HKAnchoredObjectQueryDescriptor/Output",
              "type": "codeVoice"
            },
            {
              "text": " type based on the ",
              "type": "text"
            },
            {
              "code": "predicates",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that runs anchored object queries using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKAnchoredObjectQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkanchoredobjectquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQueryDescriptor/init(predicates:anchor:limit:)": {
      "abstract": [
        {
          "text": "Creates an anchored object query descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "predicates"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit17HKSamplePredicateV",
          "text": "HKSamplePredicate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Sample"
        },
        {
          "kind": "text",
          "text": ">], "
        },
        {
          "kind": "externalParam",
          "text": "anchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQueryAnchor",
          "text": "HKQueryAnchor"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "limit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQueryDescriptor/init(predicates:anchor:limit:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(predicates:anchor:limit:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkanchoredobjectquerydescriptor/init(predicates:anchor:limit:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQueryAnchor": {
      "abstract": [
        {
          "text": "An object used to identify all the samples previously returned by an anchored object query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQueryAnchor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQueryAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQueryAnchor"
        }
      ],
      "role": "symbol",
      "title": "HKQueryAnchor",
      "type": "topic",
      "url": "/documentation/healthkit/hkqueryanchor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate": {
      "abstract": [
        {
          "text": "A predicate for queries that return a collection of matching sample objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSamplePredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSamplePredicate"
        }
      ],
      "role": "symbol",
      "title": "HKSamplePredicate",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryAnchor/title",
          "value": "HKQueryAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQueryAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQueryAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkanchoredobjectquerydescriptor/init(predicates:anchor:limit:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
