{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether MetalFX calculates the exposure for each frame.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalfx/documentation/MetalFX",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isAutoExposureEnabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLFXTemporalScalerDescriptor(py)autoExposureEnabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isAutoExposureEnabled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "MetalFX"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "autoExposureEnabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "isAutoExposureEnabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isAutoExposureEnabled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set this property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create a temporal scaler that automatically calculates the exposure level for each image it scales.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Temporal scaler instances that use auto exposure ignore its ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/exposureTexture",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalfx/documentation/MetalFX": {
      "abstract": [
        {
          "text": "Boost your Metal app’s performance by upscaling lower-resolution content to save GPU time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalFX",
      "type": "topic",
      "url": "/documentation/metalfx"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/exposureTexture": {
      "abstract": [
        {
          "text": "A texture that sets the exposure level for the color texture input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exposureTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/exposureTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exposureTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "exposureTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/exposuretexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor": {
      "abstract": [
        {
          "text": "A set of properties that configure a temporal scaling effect, and a factory method that creates the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXTemporalScalerDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXTemporalScalerDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLFXTemporalScalerDescriptor",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/colorTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the input color texture for the temporal scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/colorTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorTextureFormat"
        }
      ],
      "role": "symbol",
      "title": "colorTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/colortextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/depthTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the input depth texture for the temporal scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/depthTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depthTextureFormat"
        }
      ],
      "role": "symbol",
      "title": "depthTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/depthtextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputContentMaxScale": {
      "abstract": [
        {
          "text": "The largest scale factor the temporal scaler you create with this descriptor can use to generate output textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputContentMaxScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputContentMaxScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputContentMaxScale"
        }
      ],
      "role": "symbol",
      "title": "inputContentMaxScale",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/inputcontentmaxscale"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputContentMinScale": {
      "abstract": [
        {
          "text": "The smallest scale factor the temporal scaler you create with this descriptor can use to generate output textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputContentMinScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputContentMinScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputContentMinScale"
        }
      ],
      "role": "symbol",
      "title": "inputContentMinScale",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/inputcontentminscale"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputHeight": {
      "abstract": [
        {
          "text": "The height of the input color texture for the temporal scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputHeight"
        }
      ],
      "role": "symbol",
      "title": "inputHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/inputheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputWidth": {
      "abstract": [
        {
          "text": "The width of the input color texture for the temporal scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputWidth"
        }
      ],
      "role": "symbol",
      "title": "inputWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/inputwidth"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isAutoExposureEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether MetalFX calculates the exposure for each frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutoExposureEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isAutoExposureEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoExposureEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutoExposureEnabled",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/isautoexposureenabled"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isInputContentPropertiesEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the temporal scaler you create with this descriptor uses dynamic resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInputContentPropertiesEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isInputContentPropertiesEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputContentPropertiesEnabled"
        }
      ],
      "role": "symbol",
      "title": "isInputContentPropertiesEnabled",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/isinputcontentpropertiesenabled"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isReactiveMaskTextureEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a temporal scaler you create with the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "descriptor applies a reactive mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isReactiveMaskTextureEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isReactiveMaskTextureEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reactiveMaskTextureEnabled"
        }
      ],
      "role": "symbol",
      "title": "isReactiveMaskTextureEnabled",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/isreactivemasktextureenabled"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/motionTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the input motion texture for the temporal scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/motionTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTextureFormat"
        }
      ],
      "role": "symbol",
      "title": "motionTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/motiontextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/reactiveMaskTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the reactive mask input texture for a temporal scaler you",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "create with the descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactiveMaskTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/reactiveMaskTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reactiveMaskTextureFormat"
        }
      ],
      "role": "symbol",
      "title": "reactiveMaskTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/reactivemasktextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/requiresSynchronousInitialization": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether MetalFX compiles a temporal scaling effect’s",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "underlying upscaler as it creates the instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresSynchronousInitialization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/requiresSynchronousInitialization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresSynchronousInitialization"
        }
      ],
      "role": "symbol",
      "title": "requiresSynchronousInitialization",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/requiressynchronousinitialization"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-temporal-effects-input",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputWidth",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputHeight",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isInputContentPropertiesEnabled",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputContentMinScale",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputContentMaxScale",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/colorTextureFormat",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/motionTextureFormat",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/depthTextureFormat",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/requiresSynchronousInitialization",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isReactiveMaskTextureEnabled",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/reactiveMaskTextureFormat"
      ],
      "title": "Configuring a temporal effect’s input"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "autoExposureEnabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoExposureEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalfx/documentation/MetalFX",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-a-temporal-effects-input",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputWidth",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputHeight",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isInputContentPropertiesEnabled",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputContentMinScale",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/inputContentMaxScale",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/colorTextureFormat",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/motionTextureFormat",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/depthTextureFormat",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/requiresSynchronousInitialization",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/isReactiveMaskTextureEnabled",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/reactiveMaskTextureFormat"
              ],
              "title": "Configuring a temporal effect’s input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "getter"
                  },
                  {
                    "kind": "text",
                    "text": "="
                  },
                  {
                    "kind": "identifier",
                    "text": "isAutoExposureEnabled"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "autoExposureEnabled"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1colorTextureFormat/title",
          "value": "colorTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1colorTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1inputHeight/title",
          "value": "inputHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1inputHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1requiresSynchronousInitialization/title",
          "value": "requiresSynchronousInitialization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1requiresSynchronousInitialization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresSynchronousInitialization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1motionTextureFormat/title",
          "value": "motionTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1motionTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1reactiveMaskTextureFormat/title",
          "value": "reactiveMaskTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1reactiveMaskTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reactiveMaskTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1inputContentMaxScale/title",
          "value": "inputContentMaxScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1inputContentMaxScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputContentMaxScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1isInputContentPropertiesEnabled/title",
          "value": "inputContentPropertiesEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1isInputContentPropertiesEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputContentPropertiesEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1exposureTexture/title",
          "value": "exposureTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1exposureTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exposureTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1isAutoExposureEnabled/title",
          "value": "autoExposureEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1isAutoExposureEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoExposureEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1inputWidth/title",
          "value": "inputWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1inputWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1inputContentMinScale/title",
          "value": "inputContentMinScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1inputContentMinScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputContentMinScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor/title",
          "value": "MTLFXTemporalScalerDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1isReactiveMaskTextureEnabled/title",
          "value": "reactiveMaskTextureEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1isReactiveMaskTextureEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reactiveMaskTextureEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1depthTextureFormat/title",
          "value": "depthTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1depthTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depthTextureFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalfx/mtlfxtemporalscalerdescriptor/isautoexposureenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalfx/mtlfxtemporalscalerdescriptor/isautoexposureenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
