{"seeAlsoSections":[{"anchor":"Adding-devices-to-the-VM","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/consoleDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/networkDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/serialPorts","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/storageDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/entropyDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/directorySharingDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/graphicsDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/keyboards","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/platform","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/pointingDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/usbControllers"],"title":"Adding devices to the VM","generated":true}],"kind":"symbol","abstract":[{"type":"text","text":"The list of audio devices."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/virtualization/vzvirtualmachineconfiguration/audiodevices"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/virtualization/vzvirtualmachineconfiguration/audiodevices"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioDevices"},{"kind":"text","text":": ["},{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZAudioDeviceConfiguration","text":"VZAudioDeviceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)VZAudioDeviceConfiguration"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The default value of this property is an empty array. If your VM exposes one or more audio devices, assign an array of "},{"isActive":true,"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZAudioDeviceConfiguration","type":"reference"},{"type":"text","text":" objects to this property."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration"]]},"metadata":{"title":"audioDevices","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"audioDevices"}],"externalID":"c:objc(cs)VZVirtualMachineConfiguration(py)audioDevices","platforms":[{"introducedAt":"12.0","deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioDevices"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)VZAudioDeviceConfiguration","kind":"typeIdentifier","text":"VZAudioDeviceConfiguration"},{"kind":"text","text":"]"}],"modules":[{"name":"Virtualization"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/audioDevices","interfaceLanguage":"swift"},"references":{"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration":{"type":"topic","abstract":[{"type":"text","text":"The environment attributes and list of devices to use during the configuration of macOS or Linux VMs."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration","title":"VZVirtualMachineConfiguration","navigatorTitle":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/serialPorts":{"title":"serialPorts","role":"symbol","navigatorTitle":[{"text":"serialPorts","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The array of serial ports that you expose to the guest operating system.","type":"text"}],"type":"topic","url":"/documentation/virtualization/vzvirtualmachineconfiguration/serialports","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/serialPorts","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serialPorts","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)VZSerialPortConfiguration","text":"VZSerialPortConfiguration","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/platform":{"type":"topic","abstract":[{"text":"The hardware platform to use.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"platform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)VZPlatformConfiguration","text":"VZPlatformConfiguration"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/platform","title":"platform","navigatorTitle":[{"kind":"identifier","text":"platform"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration/platform"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/graphicsDevices":{"title":"graphicsDevices","role":"symbol","navigatorTitle":[{"text":"graphicsDevices","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The list of graphics devices.","type":"text"}],"type":"topic","url":"/documentation/virtualization/vzvirtualmachineconfiguration/graphicsdevices","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/graphicsDevices","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"graphicsDevices","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)VZGraphicsDeviceConfiguration","text":"VZGraphicsDeviceConfiguration","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/storageDevices":{"type":"topic","abstract":[{"type":"text","text":"The array of storage devices that you expose to the guest operating system."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"storageDevices"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)VZStorageDeviceConfiguration","kind":"typeIdentifier","text":"VZStorageDeviceConfiguration"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/storageDevices","title":"storageDevices","navigatorTitle":[{"kind":"identifier","text":"storageDevices"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration/storagedevices"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices":{"type":"topic","abstract":[{"text":"The socket device that you use to implement port-based communication with the guest operating system.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"socketDevices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)VZSocketDeviceConfiguration","text":"VZSocketDeviceConfiguration"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices","title":"socketDevices","navigatorTitle":[{"kind":"identifier","text":"socketDevices"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration/socketdevices"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/consoleDevices":{"type":"topic","abstract":[{"text":"The array of console devices that you expose to the guest operating system.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consoleDevices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)VZConsoleDeviceConfiguration","text":"VZConsoleDeviceConfiguration"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/consoleDevices","title":"consoleDevices","navigatorTitle":[{"kind":"identifier","text":"consoleDevices"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration/consoledevices"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/audioDevices":{"type":"topic","abstract":[{"type":"text","text":"The list of audio devices."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioDevices"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)VZAudioDeviceConfiguration","kind":"typeIdentifier","text":"VZAudioDeviceConfiguration"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/audioDevices","title":"audioDevices","navigatorTitle":[{"kind":"identifier","text":"audioDevices"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration/audiodevices"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/pointingDevices":{"title":"pointingDevices","role":"symbol","navigatorTitle":[{"text":"pointingDevices","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The list of pointing devices.","type":"text"}],"type":"topic","url":"/documentation/virtualization/vzvirtualmachineconfiguration/pointingdevices","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/pointingDevices","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pointingDevices","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)VZPointingDeviceConfiguration","text":"VZPointingDeviceConfiguration","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/directorySharingDevices":{"title":"directorySharingDevices","role":"symbol","navigatorTitle":[{"text":"directorySharingDevices","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The list of directory sharing devices.","type":"text"}],"type":"topic","url":"/documentation/virtualization/vzvirtualmachineconfiguration/directorysharingdevices","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/directorySharingDevices","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"directorySharingDevices","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)VZDirectorySharingDeviceConfiguration","text":"VZDirectorySharingDeviceConfiguration","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/keyboards":{"type":"topic","abstract":[{"text":"The list of keyboards.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboards"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)VZKeyboardConfiguration","text":"VZKeyboardConfiguration"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/keyboards","title":"keyboards","navigatorTitle":[{"kind":"identifier","text":"keyboards"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration/keyboards"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/entropyDevices":{"type":"topic","abstract":[{"text":"The array of randomization devices that you expose to the guest operating system.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"entropyDevices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)VZEntropyDeviceConfiguration","text":"VZEntropyDeviceConfiguration"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/entropyDevices","title":"entropyDevices","navigatorTitle":[{"kind":"identifier","text":"entropyDevices"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration/entropydevices"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/usbControllers":{"title":"usbControllers","role":"symbol","navigatorTitle":[{"text":"usbControllers","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The list of configured USB controllers for the VM.","type":"text"}],"type":"topic","url":"/documentation/virtualization/vzvirtualmachineconfiguration/usbcontrollers","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/usbControllers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usbControllers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"VZUSBControllerConfiguration","preciseIdentifier":"c:objc(cs)VZUSBControllerConfiguration","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZAudioDeviceConfiguration":{"title":"VZAudioDeviceConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VZAudioDeviceConfiguration"}],"kind":"symbol","abstract":[{"text":"The base class for an audio device configuration.","type":"text"}],"type":"topic","url":"/documentation/virtualization/vzaudiodeviceconfiguration","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZAudioDeviceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VZAudioDeviceConfiguration"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/networkDevices":{"title":"networkDevices","role":"symbol","navigatorTitle":[{"text":"networkDevices","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The array of network devices that you expose to the guest operating system.","type":"text"}],"type":"topic","url":"/documentation/virtualization/vzvirtualmachineconfiguration/networkdevices","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/networkDevices","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkDevices"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)VZNetworkDeviceConfiguration","text":"VZNetworkDeviceConfiguration","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"12.0","deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"audioDevices","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"audioDevices"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Adding-devices-to-the-VM","title":"Adding devices to the VM","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/consoleDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/networkDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/serialPorts","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/storageDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/entropyDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/directorySharingDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/graphicsDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/keyboards","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/platform","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/pointingDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/usbControllers"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<VZAudioDeviceConfiguration *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"audioDevices","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/title","value":"VZVirtualMachineConfiguration","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/fragments","value":[{"kind":"identifier","text":"VZVirtualMachineConfiguration"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/navigatorTitle","value":[{"kind":"identifier","text":"VZVirtualMachineConfiguration"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1serialPorts/title","value":"serialPorts","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1serialPorts/fragments","value":[{"kind":"identifier","text":"serialPorts"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1platform/title","value":"platform","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1platform/fragments","value":[{"kind":"identifier","text":"platform"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1graphicsDevices/title","value":"graphicsDevices","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1graphicsDevices/fragments","value":[{"text":"graphicsDevices","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1storageDevices/title","value":"storageDevices","op":"replace"},{"op":"replace","value":[{"text":"storageDevices","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1storageDevices/fragments"},{"op":"replace","value":"socketDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1socketDevices/title"},{"op":"replace","value":[{"text":"socketDevices","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1socketDevices/fragments"},{"op":"replace","value":"consoleDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1consoleDevices/title"},{"op":"replace","value":[{"kind":"identifier","text":"consoleDevices"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1consoleDevices/fragments"},{"op":"replace","value":"audioDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1audioDevices/title"},{"op":"replace","value":[{"text":"audioDevices","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1audioDevices/fragments"},{"op":"replace","value":"pointingDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1pointingDevices/title"},{"op":"replace","value":[{"kind":"identifier","text":"pointingDevices"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1pointingDevices/fragments"},{"op":"replace","value":"directorySharingDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1directorySharingDevices/title"},{"op":"replace","value":[{"text":"directorySharingDevices","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1directorySharingDevices/fragments"},{"op":"replace","value":"keyboards","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1keyboards/title"},{"op":"replace","value":[{"text":"keyboards","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1keyboards/fragments"},{"op":"replace","value":"entropyDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1entropyDevices/title"},{"op":"replace","value":[{"kind":"identifier","text":"entropyDevices"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1entropyDevices/fragments"},{"op":"replace","value":"usbControllers","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1usbControllers/title"},{"op":"replace","value":[{"text":"usbControllers","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1usbControllers/fragments"},{"op":"replace","value":"VZAudioDeviceConfiguration","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioDeviceConfiguration/title"},{"op":"replace","value":[{"kind":"identifier","text":"VZAudioDeviceConfiguration"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioDeviceConfiguration/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VZAudioDeviceConfiguration"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioDeviceConfiguration/navigatorTitle"},{"op":"replace","value":"networkDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1networkDevices/title"},{"op":"replace","value":[{"kind":"identifier","text":"networkDevices"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1networkDevices/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}