{"metadata":{"modules":[{"name":"Virtualization"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cpuCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"CPUCount","kind":"identifier"}],"externalID":"c:objc(cs)VZVirtualMachineConfiguration(py)CPUCount","title":"cpuCount","platforms":[{"beta":false,"deprecated":false,"introducedAt":"11.0","name":"macOS","unavailable":false}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/cpuCount"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/virtualization/vzvirtualmachineconfiguration/cpucount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/virtualization/vzvirtualmachineconfiguration/cpucount"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration"]]},"seeAlsoSections":[{"anchor":"Setting-the-number-of-CPUs","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/minimumAllowedCPUCount","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/maximumAllowedCPUCount"],"generated":true,"title":"Setting the number of CPUs"}],"abstract":[{"text":"The number of CPUs you make available to the guest operating system.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cpuCount"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The value of this property must be greater than or equal to the value in ","type":"text"},{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/minimumAllowedCPUCount","isActive":true,"type":"reference"},{"text":", and less than or equal to the value in ","type":"text"},{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/maximumAllowedCPUCount","isActive":true,"type":"reference"},{"text":". The system uses the number of physical CPUs on the current system to determine a default value.","type":"text"}]}],"kind":"content"}],"kind":"symbol","sections":[],"references":{"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/cpuCount":{"url":"/documentation/virtualization/vzvirtualmachineconfiguration/cpucount","role":"symbol","title":"cpuCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cpuCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/cpuCount","kind":"symbol","type":"topic","navigatorTitle":[{"text":"CPUCount","kind":"identifier"}],"abstract":[{"text":"The number of CPUs you make available to the guest operating system.","type":"text"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration":{"type":"topic","abstract":[{"type":"text","text":"The environment attributes and list of devices to use during the configuration of macOS or Linux VMs."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration","title":"VZVirtualMachineConfiguration","navigatorTitle":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/maximumAllowedCPUCount":{"url":"/documentation/virtualization/vzvirtualmachineconfiguration/maximumallowedcpucount","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumAllowedCPUCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maximumAllowedCPUCount"}],"abstract":[{"type":"text","text":"The maximum number of CPUs you may configure for the VM."}],"title":"maximumAllowedCPUCount","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/maximumAllowedCPUCount"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","title":"Int","role":"symbol","abstract":[{"text":"A signed integer value type.","type":"text"}],"kind":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"type":"topic","url":"/documentation/Swift/Int"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"role":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","abstract":[{"type":"text","text":"Describes an unsigned integer."}],"url":"/documentation/objectivec/nsuinteger","kind":"symbol","title":"NSUInteger"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/minimumAllowedCPUCount":{"navigatorTitle":[{"kind":"identifier","text":"minimumAllowedCPUCount"}],"role":"symbol","title":"minimumAllowedCPUCount","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumAllowedCPUCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/minimumAllowedCPUCount","kind":"symbol","url":"/documentation/virtualization/vzvirtualmachineconfiguration/minimumallowedcpucount","abstract":[{"text":"The minimum number of CPUs you may configure for the VM.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"11.0","beta":false,"name":"macOS","deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"CPUCount","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"CPUCount"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Setting the number of CPUs","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/minimumAllowedCPUCount","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/maximumAllowedCPUCount"],"anchor":"Setting-the-number-of-CPUs","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"CPUCount"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0"},{"value":"CPUCount","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1cpuCount/title"},{"value":[{"kind":"identifier","text":"CPUCount"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1cpuCount/fragments"},{"value":"VZVirtualMachineConfiguration","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/title"},{"value":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/fragments"},{"value":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/navigatorTitle"},{"value":"maximumAllowedCPUCount","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1maximumAllowedCPUCount/title"},{"value":[{"text":"maximumAllowedCPUCount","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1maximumAllowedCPUCount/fragments"},{"value":"minimumAllowedCPUCount","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1minimumAllowedCPUCount/title"},{"value":[{"kind":"identifier","text":"minimumAllowedCPUCount"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1minimumAllowedCPUCount/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}