{
  "abstract": [
    {
      "text": "The hardware platform to use.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/platform"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VZVirtualMachineConfiguration(py)platform",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "platform"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VZPlatformConfiguration",
        "text": "VZPlatformConfiguration"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "platform"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "platform"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "platform"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VZPlatformConfiguration",
              "text": "VZPlatformConfiguration"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This can be an instance of either ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The default is ",
              "type": "text"
            },
            {
              "code": "VZGenericPlatformConfiguration",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration": {
      "abstract": [
        {
          "text": "The platform configuration for a generic Intel or ARM virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZGenericPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZGenericPlatformConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZGenericPlatformConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzgenericplatformconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration": {
      "abstract": [
        {
          "text": "The platform configuration for booting macOS on Apple silicon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacPlatformConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZMacPlatformConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacplatformconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration": {
      "abstract": [
        {
          "text": "The base class for a platform configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZPlatformConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZPlatformConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzplatformconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration": {
      "abstract": [
        {
          "text": "The environment attributes and list of devices to use during the configuration of macOS or Linux VMs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtualMachineConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachineConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/audioDevices": {
      "abstract": [
        {
          "text": "The list of audio devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZAudioDeviceConfiguration",
          "text": "VZAudioDeviceConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/audioDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioDevices"
        }
      ],
      "role": "symbol",
      "title": "audioDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/audiodevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/consoleDevices": {
      "abstract": [
        {
          "text": "The array of console devices that you expose to the guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "consoleDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZConsoleDeviceConfiguration",
          "text": "VZConsoleDeviceConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/consoleDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "consoleDevices"
        }
      ],
      "role": "symbol",
      "title": "consoleDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/consoledevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/directorySharingDevices": {
      "abstract": [
        {
          "text": "The list of directory sharing devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directorySharingDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZDirectorySharingDeviceConfiguration",
          "text": "VZDirectorySharingDeviceConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/directorySharingDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "directorySharingDevices"
        }
      ],
      "role": "symbol",
      "title": "directorySharingDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/directorysharingdevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/entropyDevices": {
      "abstract": [
        {
          "text": "The array of randomization devices that you expose to the guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entropyDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZEntropyDeviceConfiguration",
          "text": "VZEntropyDeviceConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/entropyDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "entropyDevices"
        }
      ],
      "role": "symbol",
      "title": "entropyDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/entropydevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/graphicsDevices": {
      "abstract": [
        {
          "text": "The list of graphics devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicsDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZGraphicsDeviceConfiguration",
          "text": "VZGraphicsDeviceConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/graphicsDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "graphicsDevices"
        }
      ],
      "role": "symbol",
      "title": "graphicsDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/graphicsdevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/keyboards": {
      "abstract": [
        {
          "text": "The list of keyboards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboards"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZKeyboardConfiguration",
          "text": "VZKeyboardConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/keyboards",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyboards"
        }
      ],
      "role": "symbol",
      "title": "keyboards",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/keyboards"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/networkDevices": {
      "abstract": [
        {
          "text": "The array of network devices that you expose to the guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZNetworkDeviceConfiguration",
          "text": "VZNetworkDeviceConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/networkDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkDevices"
        }
      ],
      "role": "symbol",
      "title": "networkDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/networkdevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/platform": {
      "abstract": [
        {
          "text": "The hardware platform to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "platform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZPlatformConfiguration",
          "text": "VZPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/platform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "platform"
        }
      ],
      "role": "symbol",
      "title": "platform",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/platform"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/pointingDevices": {
      "abstract": [
        {
          "text": "The list of pointing devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointingDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZPointingDeviceConfiguration",
          "text": "VZPointingDeviceConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/pointingDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointingDevices"
        }
      ],
      "role": "symbol",
      "title": "pointingDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/pointingdevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/serialPorts": {
      "abstract": [
        {
          "text": "The array of serial ports that you expose to the guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serialPorts"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZSerialPortConfiguration",
          "text": "VZSerialPortConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/serialPorts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serialPorts"
        }
      ],
      "role": "symbol",
      "title": "serialPorts",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/serialports"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices": {
      "abstract": [
        {
          "text": "The socket device that you use to implement port-based communication with the guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "socketDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZSocketDeviceConfiguration",
          "text": "VZSocketDeviceConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "socketDevices"
        }
      ],
      "role": "symbol",
      "title": "socketDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/socketdevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/storageDevices": {
      "abstract": [
        {
          "text": "The array of storage devices that you expose to the guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storageDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZStorageDeviceConfiguration",
          "text": "VZStorageDeviceConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/storageDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storageDevices"
        }
      ],
      "role": "symbol",
      "title": "storageDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/storagedevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/usbControllers": {
      "abstract": [
        {
          "text": "The list of configured USB controllers for the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usbControllers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZUSBControllerConfiguration",
          "text": "VZUSBControllerConfiguration"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/usbControllers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usbControllers"
        }
      ],
      "role": "symbol",
      "title": "usbControllers",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration/usbcontrollers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adding-devices-to-the-VM",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/consoleDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/networkDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/serialPorts",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/storageDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/entropyDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/audioDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/directorySharingDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/graphicsDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/keyboards",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/pointingDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/usbControllers"
      ],
      "title": "Adding devices to the VM"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "platform"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "platform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adding-devices-to-the-VM",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/consoleDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/networkDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/serialPorts",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/storageDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/entropyDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/audioDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/directorySharingDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/graphicsDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/keyboards",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/pointingDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/usbControllers"
              ],
              "title": "Adding devices to the VM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VZPlatformConfiguration",
                    "text": "VZPlatformConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "platform"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1graphicsDevices/title",
          "value": "graphicsDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1graphicsDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "graphicsDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1serialPorts/title",
          "value": "serialPorts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1serialPorts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serialPorts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1directorySharingDevices/title",
          "value": "directorySharingDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1directorySharingDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "directorySharingDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1storageDevices/title",
          "value": "storageDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1storageDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storageDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/title",
          "value": "VZVirtualMachineConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1audioDevices/title",
          "value": "audioDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1audioDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audioDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1networkDevices/title",
          "value": "networkDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1networkDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/title",
          "value": "VZMacPlatformConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1pointingDevices/title",
          "value": "pointingDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1pointingDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointingDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1consoleDevices/title",
          "value": "consoleDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1consoleDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "consoleDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration/title",
          "value": "VZGenericPlatformConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZGenericPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZGenericPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1entropyDevices/title",
          "value": "entropyDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1entropyDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "entropyDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1keyboards/title",
          "value": "keyboards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1keyboards/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1usbControllers/title",
          "value": "usbControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1usbControllers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usbControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1socketDevices/title",
          "value": "socketDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1socketDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "socketDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1platform/title",
          "value": "platform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1platform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "platform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/title",
          "value": "VZPlatformConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZPlatformConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzvirtualmachineconfiguration/platform"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzvirtualmachineconfiguration/platform"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
