{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/virtualization/vzvirtualmachineconfiguration/validate()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/virtualization/vzvirtualmachineconfiguration/validate()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/validate()"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"extendedModule":"Virtualization","title":"validate()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"validateWithError:","kind":"identifier"}],"externalID":"c:objc(cs)VZVirtualMachineConfiguration(im)validateWithError:","roleHeading":"Instance Method","platforms":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false}],"modules":[{"name":"Virtualization"}],"role":"symbol","symbolKind":"method"},"abstract":[{"text":"Validates the current configuration settings and reports any issues that might prevent the successful initialization of the VM.","type":"text"}],"seeAlsoSections":[{"title":"Validating the configuration","generated":true,"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/validateSaveRestoreSupport()"],"anchor":"Validating-the-configuration"}],"references":{"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/validate()":{"url":"/documentation/virtualization/vzvirtualmachineconfiguration/validate()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validateWithError:"}],"abstract":[{"type":"text","text":"Validates the current configuration settings and reports any issues that might prevent the successful initialization of the VM."}],"title":"validate()","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/validate()"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"abstract":[{"type":"text","text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information."}],"title":"NSError","fragments":[{"kind":"text","text":"class "},{"text":"NSError","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","kind":"symbol","url":"/documentation/foundation/nserror","type":"topic","role":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","role":"symbol","kind":"symbol","abstract":[{"text":"A false value.","type":"text"}],"type":"topic","url":"/documentation/swift/false","identifier":"doc://com.apple.documentation/documentation/swift/false"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","role":"symbol","kind":"symbol","abstract":[{"text":"A true value.","type":"text"}],"type":"topic","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true"},"doc://com.apple.documentation/documentation/foundation/nsdebugdescriptionerrorkey":{"identifier":"doc://com.apple.documentation/documentation/foundation/nsdebugdescriptionerrorkey","url":"/documentation/foundation/nsdebugdescriptionerrorkey","abstract":[{"type":"text","text":""}],"role":"symbol","fragments":[{"kind":"text","text":"let "},{"kind":"identifier","text":"NSDebugDescriptionErrorKey"},{"text":": String","kind":"text"}],"kind":"symbol","type":"topic","title":"NSDebugDescriptionErrorKey"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration":{"type":"topic","abstract":[{"type":"text","text":"The environment attributes and list of devices to use during the configuration of macOS or Linux VMs."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration","title":"VZVirtualMachineConfiguration","navigatorTitle":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/validateSaveRestoreSupport()":{"url":"/documentation/virtualization/vzvirtualmachineconfiguration/validatesaverestoresupport()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateSaveRestoreSupport"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validateSaveRestoreSupportWithError:"}],"abstract":[{"type":"text","text":"Determines whether the framework can save or restore the VM’s current configuration."}],"title":"validateSaveRestoreSupport()","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/validateSaveRestoreSupport()"},"doc://com.apple.documentation/documentation/foundation/nserror/1411580-userinfo":{"identifier":"doc://com.apple.documentation/documentation/foundation/nserror/1411580-userinfo","url":"/documentation/foundation/nserror/1411580-userinfo","abstract":[{"text":"The user info dictionary. ","type":"text"}],"role":"symbol","fragments":[{"text":"var ","kind":"text"},{"text":"userInfo","kind":"identifier"},{"text":": [String : Any]","kind":"text"}],"kind":"symbol","type":"topic","title":"userInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"deprecated":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"validateWithError:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithError:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Validating-the-configuration","generated":true,"title":"Validating the configuration","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/validateSaveRestoreSupport()"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An error object if validation failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the configuration is valid. The value of the "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsdebugdescriptionerrorkey","isActive":true},{"type":"text","text":" key in the error’s "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nserror/1411580-userinfo","isActive":true},{"type":"text","text":" dictionary contains the reason the configuration is invalid."}],"type":"paragraph"}],"name":"error"}]},"path":"/primaryContentSections/1","op":"add"},{"value":{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" if the configuration is valid, or "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":" if it’s invalid."}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/2","op":"add"},{"value":"validateWithError:","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1validate()/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithError:"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1validate()/fragments","op":"replace"},{"value":"VZVirtualMachineConfiguration","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/title","op":"replace"},{"value":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/fragments","op":"replace"},{"value":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/navigatorTitle","op":"replace"},{"value":"validateSaveRestoreSupportWithError:","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1validateSaveRestoreSupport()/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateSaveRestoreSupportWithError:"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1validateSaveRestoreSupport()/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}