{
  "abstract": [
    {
      "text": "Creates a scheduled output object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput/init(sequenceNumber:hostTimeInNanoseconds:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMIOExtensionScheduledOutput(im)initWithSequenceNumber:hostTimeInNanoseconds:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "sequenceNumber"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt64V",
        "text": "UInt64"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "hostTimeInNanoseconds"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt64V",
        "text": "UInt64"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithSequenceNumber:hostTimeInNanoseconds:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(sequenceNumber:hostTimeInNanoseconds:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "sequenceNumber"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt64V",
              "text": "UInt64"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "hostTimeInNanoseconds"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt64V",
              "text": "UInt64"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The buffer sequence number that was output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sequenceNumber"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The host time in nanoseconds when the buffer was output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "hostTimeInNanoseconds"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput": {
      "abstract": [
        {
          "text": "An object that represents scheduled output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionScheduledOutput"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionScheduledOutput"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionScheduledOutput",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionscheduledoutput"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput/init(sequenceNumber:hostTimeInNanoseconds:)": {
      "abstract": [
        {
          "text": "Creates a scheduled output object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sequenceNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "hostTimeInNanoseconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput/init(sequenceNumber:hostTimeInNanoseconds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSequenceNumber:hostTimeInNanoseconds:"
        }
      ],
      "role": "symbol",
      "title": "init(sequenceNumber:hostTimeInNanoseconds:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionscheduledoutput/init(sequencenumber:hosttimeinnanoseconds:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput/scheduledOutputWithSequenceNumber:hostTimeInNanoseconds:": {
      "abstract": [
        {
          "text": "Returns a new scheduled output object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "scheduledOutputWithSequenceNumber:hostTimeInNanoseconds:"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput/scheduledOutputWithSequenceNumber:hostTimeInNanoseconds:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheduledOutputWithSequenceNumber:hostTimeInNanoseconds:"
        }
      ],
      "role": "symbol",
      "title": "scheduledOutputWithSequenceNumber:hostTimeInNanoseconds:",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionscheduledoutput/scheduledoutputwithsequencenumber:hosttimeinnanoseconds:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint64_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint64_t",
      "type": "topic",
      "url": "/documentation/kernel/uint64_t"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt64V": {
      "abstract": [
        {
          "text": "A 64-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt64",
      "type": "topic",
      "url": "/documentation/Swift/UInt64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithSequenceNumber:hostTimeInNanoseconds:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSequenceNumber:hostTimeInNanoseconds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Scheduled-Output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionScheduledOutput/scheduledOutputWithSequenceNumber:hostTimeInNanoseconds:"
              ],
              "title": "Creating a Scheduled Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithSequenceNumber:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint64_t",
                    "text": "uint64_t"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sequenceNumber"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "hostTimeInNanoseconds:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint64_t",
                    "text": "uint64_t"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "hostTimeInNanoseconds"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The buffer sequence number that was output.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sequenceNumber"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The host time in nanoseconds when the buffer was output.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "hostTimeInNanoseconds"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionScheduledOutput~1init(sequenceNumber:hostTimeInNanoseconds:)/title",
          "value": "initWithSequenceNumber:hostTimeInNanoseconds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionScheduledOutput~1init(sequenceNumber:hostTimeInNanoseconds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSequenceNumber:hostTimeInNanoseconds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionScheduledOutput/title",
          "value": "CMIOExtensionScheduledOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionScheduledOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionScheduledOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionScheduledOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionScheduledOutput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionscheduledoutput/init(sequencenumber:hosttimeinnanoseconds:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionscheduledoutput/init(sequencenumber:hosttimeinnanoseconds:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
