{
  "abstract": [
    {
      "text": "Requests a badge for the given file or directory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Finder-Sync/documentation/FinderSync",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/requestBadgeIdentifier(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FIFinderSync(im)requestBadgeIdentifierForURL:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "requestBadgeIdentifier"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Finder Sync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "requestBadgeIdentifierForURL:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "requestBadgeIdentifier(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "requestBadgeIdentifier"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The URL of a file or directory inside the extension’s monitored",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "directories.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "url"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Override this method to receive notifications whenever a new item becomes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "visible in the Finder. Check the item’s state, and call",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to set an appropriate",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "badge.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Finder-Sync/documentation/FinderSync": {
      "abstract": [
        {
          "text": "Modify the Finder’s user interface to express file synchronization and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync",
      "kind": "symbol",
      "role": "collection",
      "title": "Finder Sync",
      "type": "topic",
      "url": "/documentation/findersync"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)": {
      "abstract": [
        {
          "text": "Sets the badge for a file or directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBadgeIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBadgeIdentifier:forURL:"
        }
      ],
      "role": "symbol",
      "title": "setBadgeIdentifier(_:for:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/setbadgeidentifier(_:for:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol": {
      "abstract": [
        {
          "text": "The group of methods to implement for modifying the Finder user interface to express file synchronization status and control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIFinderSyncProtocol"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIFinderSyncProtocol"
        }
      ],
      "role": "symbol",
      "title": "FIFinderSyncProtocol",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/beginObservingDirectory(at:)": {
      "abstract": [
        {
          "text": "Tells the extension that the user is looking at a monitored directory or at",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "one of its subdirectories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginObservingDirectory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/beginObservingDirectory(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginObservingDirectoryAtURL:"
        }
      ],
      "role": "symbol",
      "title": "beginObservingDirectory(at:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/beginobservingdirectory(at:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/endObservingDirectory(at:)": {
      "abstract": [
        {
          "text": "Tells the extension that the user has stopped looking at a monitored",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "directory or at one of its subdirectories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endObservingDirectory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/endObservingDirectory(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endObservingDirectoryAtURL:"
        }
      ],
      "role": "symbol",
      "title": "endObservingDirectory(at:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/endobservingdirectory(at:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/menu(for:)": {
      "abstract": [
        {
          "text": "Requests a custom menu from the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FIMenuKind",
          "text": "FIMenuKind"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/menu(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuForMenuKind:"
        }
      ],
      "role": "symbol",
      "title": "menu(for:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/menu(for:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/requestBadgeIdentifier(for:)": {
      "abstract": [
        {
          "text": "Requests a badge for the given file or directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestBadgeIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/requestBadgeIdentifier(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestBadgeIdentifierForURL:"
        }
      ],
      "role": "symbol",
      "title": "requestBadgeIdentifier(for:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/requestbadgeidentifier(for:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemImage": {
      "abstract": [
        {
          "text": "The image for the extension’s toolbar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarItemImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbarItemImage"
        }
      ],
      "role": "symbol",
      "title": "toolbarItemImage",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/toolbaritemimage"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemName": {
      "abstract": [
        {
          "text": "The name of the extension’s toolbar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarItemName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbarItemName"
        }
      ],
      "role": "symbol",
      "title": "toolbarItemName",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/toolbaritemname"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemToolTip": {
      "abstract": [
        {
          "text": "The tooltip text for the extension’s toolbar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarItemToolTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemToolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbarItemToolTip"
        }
      ],
      "role": "symbol",
      "title": "toolbarItemToolTip",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/toolbaritemtooltip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Managing-Badges-Shortcut-Menus-and-Toolbar-Buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/beginObservingDirectory(at:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/endObservingDirectory(at:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/menu(for:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemImage",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemName",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemToolTip"
      ],
      "title": "Managing Badges, Shortcut Menus, and Toolbar Buttons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "requestBadgeIdentifierForURL:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestBadgeIdentifierForURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Finder-Sync/documentation/FinderSync",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Managing-Badges-Shortcut-Menus-and-Toolbar-Buttons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/beginObservingDirectory(at:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/endObservingDirectory(at:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/menu(for:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemImage",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemName",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemToolTip"
              ],
              "title": "Managing Badges, Shortcut Menus, and Toolbar Buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "requestBadgeIdentifierForURL:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURL",
                    "text": "NSURL"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "url"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The URL of a file or directory inside the extension’s monitored",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "directories.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "url"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemName/title",
          "value": "toolbarItemName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbarItemName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeIdentifier(_:for:)/title",
          "value": "setBadgeIdentifier:forURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeIdentifier(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBadgeIdentifier:forURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemImage/title",
          "value": "toolbarItemImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbarItemImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol/title",
          "value": "FIFinderSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1endObservingDirectory(at:)/title",
          "value": "endObservingDirectoryAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1endObservingDirectory(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endObservingDirectoryAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemToolTip/title",
          "value": "toolbarItemToolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemToolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbarItemToolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1menu(for:)/title",
          "value": "menuForMenuKind:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1menu(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "menuForMenuKind:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1beginObservingDirectory(at:)/title",
          "value": "beginObservingDirectoryAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1beginObservingDirectory(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginObservingDirectoryAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1requestBadgeIdentifier(for:)/title",
          "value": "requestBadgeIdentifierForURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1requestBadgeIdentifier(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestBadgeIdentifierForURL:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/findersync/fifindersyncprotocol/requestbadgeidentifier(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/findersync/fifindersyncprotocol/requestbadgeidentifier(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
