{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadgroupMemoryAlignment"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding/threadgroupMemoryAlignment"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["/documentation/metal/mtlthreadgroupbinding/threadgroupmemoryalignment"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metal/mtlthreadgroupbinding/threadgroupmemoryalignment"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","required":true,"title":"threadgroupMemoryAlignment","navigatorTitle":[{"text":"threadgroupMemoryAlignment","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threadgroupMemoryAlignment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"Metal"}],"platforms":[{"deprecated":false,"introducedAt":"16.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"16.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"16.0","beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"16.0"},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"symbolKind":"property","externalID":"c:objc(pl)MTLThreadgroupBinding(py)threadgroupMemoryAlignment"},"references":{"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"title":"NSUInteger","abstract":[{"text":"Describes an unsigned integer.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","role":"symbol","url":"/documentation/objectivec/nsuinteger"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.externally.resolved.symbol/s:Si":{"kind":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","url":"/documentation/Swift/Int","abstract":[{"text":"A signed integer value type.","type":"text"}],"fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding/threadgroupMemoryAlignment":{"navigatorTitle":[{"text":"threadgroupMemoryAlignment","kind":"identifier"}],"role":"symbol","abstract":[],"url":"/documentation/metal/mtlthreadgroupbinding/threadgroupmemoryalignment","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threadgroupMemoryAlignment","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"required":true,"title":"threadgroupMemoryAlignment","type":"topic","identifier":"doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding/threadgroupMemoryAlignment","kind":"symbol"},"doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding":{"identifier":"doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding","role":"symbol","kind":"symbol","url":"/documentation/metal/mtlthreadgroupbinding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MTLThreadgroupBinding"}],"type":"topic","title":"MTLThreadgroupBinding","navigatorTitle":[{"kind":"identifier","text":"MTLThreadgroupBinding"}],"abstract":[]},"doc://com.apple.metal/documentation/Metal":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc://com.apple.metal/documentation/Metal","title":"Metal","abstract":[{"text":"Render advanced 3D graphics and compute data in parallel with graphics processors.","type":"text"}],"url":"/documentation/metal"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"introducedAt":"16.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"16.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"16.0","beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"introducedAt":"13.0","beta":false,"name":"macOS","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"16.0"},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"threadgroupMemoryAlignment","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"threadgroupMemoryAlignment","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"threadgroupMemoryAlignment","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"threadgroupMemoryAlignment","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding~1threadgroupMemoryAlignment/title"},{"value":[{"kind":"identifier","text":"threadgroupMemoryAlignment"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding~1threadgroupMemoryAlignment/fragments"},{"value":"MTLThreadgroupBinding","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/title"},{"value":[{"kind":"identifier","text":"MTLThreadgroupBinding"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/fragments"},{"value":[{"kind":"identifier","text":"MTLThreadgroupBinding"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}