{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/uiaccessibilitycontainertype/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","roleHeading":"Initializer","externalID":"s:So28UIAccessibilityContainerTypeV8rawValueABSgSi_tcfc","title":"init(rawValue:)","platforms":[{"introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"introducedAt":"13.1","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"},{"introducedAt":"4.0","unavailable":false,"deprecated":false,"beta":false,"name":"watchOS"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"modules":[{"name":"UIKit"}],"role":"symbol"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType"]]},"sections":[],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIAccessibilityContainerType"}],"url":"/documentation/uikit/uiaccessibilitycontainertype","abstract":[{"type":"text","text":"Constants that indicate the type of content in a data-based container."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType","navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityContainerType"}],"title":"UIAccessibilityContainerType","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/init(rawValue:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/init(rawValue:)","role":"symbol","title":"init(rawValue:)","type":"topic","url":"/documentation/uikit/uiaccessibilitycontainertype/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"UIAccessibilityContainerType","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityContainerType"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityContainerType"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}