{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landmark","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/landmark"},"abstract":[{"type":"text","text":"Landmark data."}],"variants":[{"paths":["/documentation/uikit/uiaccessibilitycontainertype/landmark"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiaccessibilitycontainertype/landmark"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"UIAccessibilityContainerType.landmark","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"landmark","kind":"identifier"}],"modules":[{"name":"UIKit"}],"roleHeading":"Case","externalID":"c:@E@UIAccessibilityContainerType@UIAccessibilityContainerTypeLandmark","symbolKind":"case","navigatorTitle":[{"text":"UIAccessibilityContainerTypeLandmark","kind":"identifier"}],"role":"symbol","platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"11.0","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"11.0","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"beta":false,"deprecated":false,"name":"tvOS","introducedAt":"11.0","unavailable":false},{"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","unavailable":false},{"beta":false,"deprecated":false,"name":"watchOS","introducedAt":"4.0","unavailable":false}]},"seeAlsoSections":[{"generated":true,"anchor":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/none","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/dataTable","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/list","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/semanticGroup"],"title":"Constants"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIAccessibilityContainerType"}],"url":"/documentation/uikit/uiaccessibilitycontainertype","abstract":[{"type":"text","text":"Constants that indicate the type of content in a data-based container."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType","navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityContainerType"}],"title":"UIAccessibilityContainerType","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/list":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeList","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/list","abstract":[{"text":"A list of data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/list","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"list","kind":"identifier"}],"title":"UIAccessibilityContainerType.list","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/none":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeNone","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/none","abstract":[{"text":"No additional data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/none","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"UIAccessibilityContainerType.none","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/landmark":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeLandmark","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/landmark","abstract":[{"text":"Landmark data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/landmark","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landmark","kind":"identifier"}],"title":"UIAccessibilityContainerType.landmark","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/semanticGroup":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeSemanticGroup","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/semanticGroup","abstract":[{"text":"A semantic group of data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/semanticgroup","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"semanticGroup","kind":"identifier"}],"title":"UIAccessibilityContainerType.semanticGroup","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/dataTable":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeDataTable","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/dataTable","abstract":[{"text":"A table that contains structured data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/datatable","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataTable","kind":"identifier"}],"title":"UIAccessibilityContainerType.dataTable","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"11.0","name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"11.0","name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"11.0","name":"tvOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"4.0","name":"watchOS","deprecated":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"UIAccessibilityContainerTypeLandmark"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"UIAccessibilityContainerTypeLandmark","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/none","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/dataTable","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/list","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/semanticGroup"],"generated":true,"anchor":"Constants","title":"Constants"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"UIAccessibilityContainerTypeLandmark","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/title","op":"replace","value":"UIAccessibilityContainerType"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/fragments","op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityContainerType"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityContainerType"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1list/title","op":"replace","value":"UIAccessibilityContainerTypeList"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1list/fragments","op":"replace","value":[{"text":"UIAccessibilityContainerTypeList","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1none/title","op":"replace","value":"UIAccessibilityContainerTypeNone"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1none/fragments","op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityContainerTypeNone"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1landmark/title","op":"replace","value":"UIAccessibilityContainerTypeLandmark"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1landmark/fragments","op":"replace","value":[{"text":"UIAccessibilityContainerTypeLandmark","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1semanticGroup/title","op":"replace","value":"UIAccessibilityContainerTypeSemanticGroup"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1semanticGroup/fragments","op":"replace","value":[{"text":"UIAccessibilityContainerTypeSemanticGroup","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1dataTable/title","op":"replace","value":"UIAccessibilityContainerTypeDataTable"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1dataTable/fragments","op":"replace","value":[{"text":"UIAccessibilityContainerTypeDataTable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}