{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"list"}]}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/list","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A list of data."}],"variants":[{"paths":["/documentation/uikit/uiaccessibilitycontainertype/list"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiaccessibilitycontainertype/list"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeList","kind":"identifier"}],"modules":[{"name":"UIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"list","kind":"identifier"}],"title":"UIAccessibilityContainerType.list","role":"symbol","roleHeading":"Case","externalID":"c:@E@UIAccessibilityContainerType@UIAccessibilityContainerTypeList","platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"11.0","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"11.0","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"11.0","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false},{"deprecated":false,"beta":false,"name":"watchOS","introducedAt":"4.0","unavailable":false}],"symbolKind":"case"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/none","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/dataTable","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/landmark","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/semanticGroup"],"anchor":"Constants","title":"Constants","generated":true}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/semanticGroup":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeSemanticGroup","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/semanticGroup","abstract":[{"text":"A semantic group of data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/semanticgroup","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"semanticGroup","kind":"identifier"}],"title":"UIAccessibilityContainerType.semanticGroup","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/dataTable":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeDataTable","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/dataTable","abstract":[{"text":"A table that contains structured data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/datatable","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataTable","kind":"identifier"}],"title":"UIAccessibilityContainerType.dataTable","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIAccessibilityContainerType"}],"url":"/documentation/uikit/uiaccessibilitycontainertype","abstract":[{"type":"text","text":"Constants that indicate the type of content in a data-based container."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType","navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityContainerType"}],"title":"UIAccessibilityContainerType","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/list":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeList","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/list","abstract":[{"text":"A list of data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/list","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"list","kind":"identifier"}],"title":"UIAccessibilityContainerType.list","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/landmark":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeLandmark","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/landmark","abstract":[{"text":"Landmark data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/landmark","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landmark","kind":"identifier"}],"title":"UIAccessibilityContainerType.landmark","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/none":{"navigatorTitle":[{"text":"UIAccessibilityContainerTypeNone","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/none","abstract":[{"text":"No additional data.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitycontainertype/none","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"UIAccessibilityContainerType.none","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"11.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"11.0","deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","deprecated":false},{"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"11.0","deprecated":false},{"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"1.0","deprecated":false},{"unavailable":false,"name":"watchOS","beta":false,"introducedAt":"4.0","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"op":"replace","value":"UIAccessibilityContainerTypeList","path":"/metadata/title"},{"op":"replace","value":"case","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"UIAccessibilityContainerTypeList","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/none","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/dataTable","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/landmark","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType/semanticGroup"],"title":"Constants","generated":true,"anchor":"Constants"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"UIAccessibilityContainerTypeList"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1semanticGroup/title","value":"UIAccessibilityContainerTypeSemanticGroup"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1semanticGroup/fragments","value":[{"text":"UIAccessibilityContainerTypeSemanticGroup","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1dataTable/title","value":"UIAccessibilityContainerTypeDataTable"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1dataTable/fragments","value":[{"kind":"identifier","text":"UIAccessibilityContainerTypeDataTable"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/title","value":"UIAccessibilityContainerType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/fragments","value":[{"kind":"identifier","text":"UIAccessibilityContainerType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/navigatorTitle","value":[{"kind":"identifier","text":"UIAccessibilityContainerType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1list/title","value":"UIAccessibilityContainerTypeList"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1list/fragments","value":[{"text":"UIAccessibilityContainerTypeList","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1landmark/title","value":"UIAccessibilityContainerTypeLandmark"},{"op":"replace","value":[{"text":"UIAccessibilityContainerTypeLandmark","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1landmark/fragments"},{"op":"replace","value":"UIAccessibilityContainerTypeNone","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1none/title"},{"op":"replace","value":[{"text":"UIAccessibilityContainerTypeNone","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType~1none/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}