{
  "abstract": [
    {
      "text": "The content to append to the note.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent/content"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INAppendToNoteIntent(py)content",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "content"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INNoteContent",
        "text": "INNoteContent"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "content"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "INAppendToNoteIntent is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "INAppendToNoteIntent is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INAppendToNoteIntent is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INAppendToNoteIntent is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "4.0",
        "message": "INAppendToNoteIntent is deprecated. There is no replacement.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "content"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "content"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INNoteContent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INNoteContent",
              "text": "INNoteContent"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent": {
      "abstract": [
        {
          "text": "A request to append content to a note.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAppendToNoteIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAppendToNoteIntent"
        }
      ],
      "role": "symbol",
      "title": "INAppendToNoteIntent",
      "type": "topic",
      "url": "/documentation/intents/inappendtonoteintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent/content": {
      "abstract": [
        {
          "text": "The content to append to the note.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "content"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INNoteContent",
          "text": "INNoteContent"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent/content",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "content"
        }
      ],
      "role": "symbol",
      "title": "content",
      "type": "topic",
      "url": "/documentation/intents/inappendtonoteintent/content"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent/targetNote": {
      "abstract": [
        {
          "text": "The note to receive the additional content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetNote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INNote",
          "text": "INNote"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent/targetNote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetNote"
        }
      ],
      "role": "symbol",
      "title": "targetNote",
      "type": "topic",
      "url": "/documentation/intents/inappendtonoteintent/targetnote"
    },
    "doc://com.apple.sirikit/documentation/Intents/INNoteContent": {
      "abstract": [
        {
          "text": "An abstract class that defines the types of content contained in notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INNoteContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INNoteContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INNoteContent"
        }
      ],
      "role": "symbol",
      "title": "INNoteContent",
      "type": "topic",
      "url": "/documentation/intents/innotecontent"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Note-Content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent/targetNote"
      ],
      "title": "Getting the Note Content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "content"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Note-Content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAppendToNoteIntent/targetNote"
              ],
              "title": "Getting the Note Content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INNoteContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INNoteContent",
                    "text": "INNoteContent"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "content"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INNoteContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INNoteContent",
                    "text": "INNoteContent"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "content"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAppendToNoteIntent~1content/title",
          "value": "content"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAppendToNoteIntent~1content/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAppendToNoteIntent~1targetNote/title",
          "value": "targetNote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAppendToNoteIntent~1targetNote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "targetNote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNoteContent/title",
          "value": "INNoteContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNoteContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INNoteContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNoteContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INNoteContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAppendToNoteIntent/title",
          "value": "INAppendToNoteIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAppendToNoteIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAppendToNoteIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAppendToNoteIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAppendToNoteIntent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inappendtonoteintent/content"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inappendtonoteintent/content"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
