{
  "abstract": [
    {
      "text": "The rear-right car seat.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rearRight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INCarSeat@INCarSeatRearRight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rearRight"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INCarSeatRearRight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INCarSeat is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INCarSeat is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INCarSeat is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INCarSeat is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INCarSeat.rearRight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rearRight"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In cars with three rows of seating, rear seats are the second row.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat": {
      "abstract": [
        {
          "text": "Constants indicating a seat position.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarSeat"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeat"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat",
      "type": "topic",
      "url": "/documentation/intents/incarseat"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/all": {
      "abstract": [
        {
          "text": "All seats in the car.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatAll"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.all",
      "type": "topic",
      "url": "/documentation/intents/incarseat/all"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/driver": {
      "abstract": [
        {
          "text": "The driver’s seat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "driver"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/driver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatDriver"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.driver",
      "type": "topic",
      "url": "/documentation/intents/incarseat/driver"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/front": {
      "abstract": [
        {
          "text": "The front seats.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "front"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/front",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatFront"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.front",
      "type": "topic",
      "url": "/documentation/intents/incarseat/front"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/frontLeft": {
      "abstract": [
        {
          "text": "The front-left car seat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontLeft"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/frontLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatFrontLeft"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.frontLeft",
      "type": "topic",
      "url": "/documentation/intents/incarseat/frontleft"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/frontRight": {
      "abstract": [
        {
          "text": "The front-right car seat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontRight"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/frontRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatFrontRight"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.frontRight",
      "type": "topic",
      "url": "/documentation/intents/incarseat/frontright"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/passenger": {
      "abstract": [
        {
          "text": "The front passenger’s seat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passenger"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/passenger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatPassenger"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.passenger",
      "type": "topic",
      "url": "/documentation/intents/incarseat/passenger"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rear": {
      "abstract": [
        {
          "text": "The rear seats.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rear"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatRear"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.rear",
      "type": "topic",
      "url": "/documentation/intents/incarseat/rear"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rearLeft": {
      "abstract": [
        {
          "text": "The rear-left car seat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rearLeft"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rearLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatRearLeft"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.rearLeft",
      "type": "topic",
      "url": "/documentation/intents/incarseat/rearleft"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rearRight": {
      "abstract": [
        {
          "text": "The rear-right car seat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rearRight"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rearRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatRearRight"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.rearRight",
      "type": "topic",
      "url": "/documentation/intents/incarseat/rearright"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRow": {
      "abstract": [
        {
          "text": "The third row seats.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirdRow"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatThirdRow"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.thirdRow",
      "type": "topic",
      "url": "/documentation/intents/incarseat/thirdrow"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRowLeft": {
      "abstract": [
        {
          "text": "The left seat in third-row seating.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirdRowLeft"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRowLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatThirdRowLeft"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.thirdRowLeft",
      "type": "topic",
      "url": "/documentation/intents/incarseat/thirdrowleft"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRowRight": {
      "abstract": [
        {
          "text": "The right seat in third-row seating.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirdRowRight"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRowRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatThirdRowRight"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.thirdRowRight",
      "type": "topic",
      "url": "/documentation/intents/incarseat/thirdrowright"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeat/unknown": {
      "abstract": [
        {
          "text": "An unknown seat position.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeat/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatUnknown"
        }
      ],
      "role": "symbol",
      "title": "INCarSeat.unknown",
      "type": "topic",
      "url": "/documentation/intents/incarseat/unknown"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/driver",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/passenger",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/frontLeft",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/frontRight",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/front",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rearLeft",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rear",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRowLeft",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRowRight",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRow",
        "doc://com.apple.sirikit/documentation/Intents/INCarSeat/all"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INCarSeatRearRight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatRearRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/driver",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/passenger",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/frontLeft",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/frontRight",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/front",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rearLeft",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/rear",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRowLeft",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRowRight",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/thirdRow",
                "doc://com.apple.sirikit/documentation/Intents/INCarSeat/all"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INCarSeatRearRight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat/title",
          "value": "INCarSeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1passenger/title",
          "value": "INCarSeatPassenger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1passenger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatPassenger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1frontRight/title",
          "value": "INCarSeatFrontRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1frontRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatFrontRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1driver/title",
          "value": "INCarSeatDriver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1driver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatDriver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1thirdRow/title",
          "value": "INCarSeatThirdRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1thirdRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatThirdRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1thirdRowRight/title",
          "value": "INCarSeatThirdRowRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1thirdRowRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatThirdRowRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1frontLeft/title",
          "value": "INCarSeatFrontLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1frontLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatFrontLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1rearLeft/title",
          "value": "INCarSeatRearLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1rearLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatRearLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1thirdRowLeft/title",
          "value": "INCarSeatThirdRowLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1thirdRowLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatThirdRowLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1front/title",
          "value": "INCarSeatFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1front/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1rear/title",
          "value": "INCarSeatRear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1rear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatRear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1unknown/title",
          "value": "INCarSeatUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1all/title",
          "value": "INCarSeatAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1rearRight/title",
          "value": "INCarSeatRearRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeat~1rearRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatRearRight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/incarseat/rearright"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/incarseat/rearright"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
