{
  "abstract": [
    {
      "text": "A table row subrole.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/tableRow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSAccessibilityTableRowSubrole",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tableRow"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@NSAccessibility",
        "text": "NSAccessibility"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
        "text": "Subrole"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityTableRowSubrole"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "tableRow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tableRow"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@NSAccessibility",
              "text": "NSAccessibility"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
              "text": "Subrole"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct": {
      "abstract": [
        {
          "text": "A namespace for accessibility symbols for AppKit apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole": {
      "abstract": [
        {
          "text": "Values that describe specialized object subtypes that accessibility elements represent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Subrole"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Subrole",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/closeButton": {
      "abstract": [
        {
          "text": "A window’s close button subrole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closeButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/closeButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCloseButtonSubrole"
        }
      ],
      "role": "symbol",
      "title": "closeButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/closebutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/collectionListSubrole": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionListSubrole"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/collectionListSubrole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCollectionListSubrole"
        }
      ],
      "role": "symbol",
      "title": "collectionListSubrole",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/collectionlistsubrole"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/contentList": {
      "abstract": [
        {
          "text": "A subrole for content that is organized in a list, but is not in a list control or table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/contentList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityContentListSubrole"
        }
      ],
      "role": "symbol",
      "title": "contentList",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/contentlist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/decrementArrow": {
      "abstract": [
        {
          "text": "A decrement arrow subrole (the down arrow in a scroll bar).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/decrementArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityDecrementArrowSubrole"
        }
      ],
      "role": "symbol",
      "title": "decrementArrow",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/decrementarrow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/decrementPage": {
      "abstract": [
        {
          "text": "A decrement page subrole (the decrement area in the scroll track of a scroll bar).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/decrementPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityDecrementPageSubrole"
        }
      ],
      "role": "symbol",
      "title": "decrementPage",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/decrementpage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/definitionList": {
      "abstract": [
        {
          "text": "A subrole for a content list in a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "definitionList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/definitionList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityDefinitionListSubrole"
        }
      ],
      "role": "symbol",
      "title": "definitionList",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/definitionlist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/descriptionList": {
      "abstract": [
        {
          "text": "A description list subrole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptionList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/descriptionList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityDescriptionListSubrole"
        }
      ],
      "role": "symbol",
      "title": "descriptionList",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/descriptionlist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/dialog": {
      "abstract": [
        {
          "text": "A dialog subrole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dialog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/dialog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityDialogSubrole"
        }
      ],
      "role": "symbol",
      "title": "dialog",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/dialog"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/floatingWindow": {
      "abstract": [
        {
          "text": "A floating window subrole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatingWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/floatingWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFloatingWindowSubrole"
        }
      ],
      "role": "symbol",
      "title": "floatingWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/floatingwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/fullScreenButton": {
      "abstract": [
        {
          "text": "A window’s full-screen button subrole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/fullScreenButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFullScreenButtonSubrole"
        }
      ],
      "role": "symbol",
      "title": "fullScreenButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/fullscreenbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/incrementArrow": {
      "abstract": [
        {
          "text": "An increment arrow subrole (the up arrow in a scroll bar).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incrementArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/incrementArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityIncrementArrowSubrole"
        }
      ],
      "role": "symbol",
      "title": "incrementArrow",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/incrementarrow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/incrementPage": {
      "abstract": [
        {
          "text": "An increment page subrole (the increment area in the scroll track of a scroll bar).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incrementPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/incrementPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityIncrementPageSubrole"
        }
      ],
      "role": "symbol",
      "title": "incrementPage",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/incrementpage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/minimizeButton": {
      "abstract": [
        {
          "text": "A window’s minimize button subrole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimizeButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/minimizeButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMinimizeButtonSubrole"
        }
      ],
      "role": "symbol",
      "title": "minimizeButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/minimizebutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/outlineRow": {
      "abstract": [
        {
          "text": "An outline row subrole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outlineRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/outlineRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityOutlineRowSubrole"
        }
      ],
      "role": "symbol",
      "title": "outlineRow",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/outlinerow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/ratingIndicator": {
      "abstract": [
        {
          "text": "A rating indicator subrole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ratingIndicator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/ratingIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRatingIndicatorSubrole"
        }
      ],
      "role": "symbol",
      "title": "ratingIndicator",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/ratingindicator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/tableRow": {
      "abstract": [
        {
          "text": "A table row subrole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/tableRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityTableRowSubrole"
        }
      ],
      "role": "symbol",
      "title": "tableRow",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole/tablerow"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Subroles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/closeButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/collectionListSubrole",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/contentList",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/decrementArrow",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/decrementPage",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/definitionList",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/descriptionList",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/dialog",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/floatingWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/fullScreenButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/incrementArrow",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/incrementPage",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/minimizeButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/outlineRow",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/ratingIndicator"
      ],
      "title": "Subroles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessibilityTableRowSubrole"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityTableRowSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Subroles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/closeButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/collectionListSubrole",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/contentList",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/decrementArrow",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/decrementPage",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/definitionList",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/descriptionList",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/dialog",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/floatingWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/fullScreenButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/incrementArrow",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/incrementPage",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/minimizeButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/outlineRow",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole/ratingIndicator"
              ],
              "title": "Subroles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSAccessibilitySubrole",
                    "text": "NSAccessibilitySubrole"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSAccessibilityTableRowSubrole"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1closeButton/title",
          "value": "NSAccessibilityCloseButtonSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1closeButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCloseButtonSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1minimizeButton/title",
          "value": "NSAccessibilityMinimizeButtonSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1minimizeButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMinimizeButtonSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1incrementArrow/title",
          "value": "NSAccessibilityIncrementArrowSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1incrementArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityIncrementArrowSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1ratingIndicator/title",
          "value": "NSAccessibilityRatingIndicatorSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1ratingIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRatingIndicatorSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole/title",
          "value": "NSAccessibilitySubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1incrementPage/title",
          "value": "NSAccessibilityIncrementPageSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1incrementPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityIncrementPageSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1floatingWindow/title",
          "value": "NSAccessibilityFloatingWindowSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1floatingWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFloatingWindowSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1collectionListSubrole/title",
          "value": "NSAccessibilityCollectionListSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1collectionListSubrole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCollectionListSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1descriptionList/title",
          "value": "NSAccessibilityDescriptionListSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1descriptionList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDescriptionListSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1definitionList/title",
          "value": "NSAccessibilityDefinitionListSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1definitionList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDefinitionListSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1decrementPage/title",
          "value": "NSAccessibilityDecrementPageSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1decrementPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDecrementPageSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1outlineRow/title",
          "value": "NSAccessibilityOutlineRowSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1outlineRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOutlineRowSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1fullScreenButton/title",
          "value": "NSAccessibilityFullScreenButtonSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1fullScreenButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFullScreenButtonSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1dialog/title",
          "value": "NSAccessibilityDialogSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1dialog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDialogSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1decrementArrow/title",
          "value": "NSAccessibilityDecrementArrowSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1decrementArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDecrementArrowSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1tableRow/title",
          "value": "NSAccessibilityTableRowSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1tableRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityTableRowSubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1contentList/title",
          "value": "NSAccessibilityContentListSubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole~1contentList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityContentListSubrole"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/subrole/tablerow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/subrole/tablerow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
