{
  "abstract": [
    {
      "text": "Ultra-high-definition 4K video resolution.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolution4K"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVTopShelfCarouselItemMediaOptions@TVTopShelfCarouselItemVideoResolution4K",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "videoResolution4K"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
        "text": "TVTopShelfCarouselItem"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
        "text": "MediaOptions"
      }
    ],
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVTopShelfCarouselItemVideoResolution4K"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "videoResolution4K"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "videoResolution4K"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
              "text": "TVTopShelfCarouselItem"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
              "text": "MediaOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specify this constant, or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolutionHD",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant, but not both.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem": {
      "abstract": [
        {
          "text": "An item containing images, video, and other information that you want to display using a carousel-based interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItem"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItem"
        }
      ],
      "role": "symbol",
      "title": "TVTopShelfCarouselItem",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct": {
      "abstract": [
        {
          "text": "Constants indicating the item’s audio and video capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MediaOptions"
        }
      ],
      "role": "symbol",
      "title": "TVTopShelfCarouselItem.MediaOptions",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioDescription": {
      "abstract": [
        {
          "text": "Audio content with audio descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItemAudioDescription"
        }
      ],
      "role": "symbol",
      "title": "audioDescription",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/audiodescription"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioDolbyAtmos": {
      "abstract": [
        {
          "text": "Audio content with Dolby Atmos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioDolbyAtmos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioDolbyAtmos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItemAudioDolbyAtmos"
        }
      ],
      "role": "symbol",
      "title": "audioDolbyAtmos",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/audiodolbyatmos"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioTranscriptionClosedCaptioning": {
      "abstract": [
        {
          "text": "Audio content with closed captioning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioTranscriptionClosedCaptioning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioTranscriptionClosedCaptioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItemAudioTranscriptionClosedCaptioning"
        }
      ],
      "role": "symbol",
      "title": "audioTranscriptionClosedCaptioning",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/audiotranscriptionclosedcaptioning"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioTranscriptionSDH": {
      "abstract": [
        {
          "text": "Audio content with subtitles for people who are deaf or hard of hearing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioTranscriptionSDH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioTranscriptionSDH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItemAudioTranscriptionSDH"
        }
      ],
      "role": "symbol",
      "title": "audioTranscriptionSDH",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/audiotranscriptionsdh"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoColorSpaceDolbyVision": {
      "abstract": [
        {
          "text": "Dolby Vision video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoColorSpaceDolbyVision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoColorSpaceDolbyVision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItemVideoColorSpaceDolbyVision"
        }
      ],
      "role": "symbol",
      "title": "videoColorSpaceDolbyVision",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/videocolorspacedolbyvision"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoColorSpaceHDR": {
      "abstract": [
        {
          "text": "High-dynamic-range video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoColorSpaceHDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoColorSpaceHDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItemVideoColorSpaceHDR"
        }
      ],
      "role": "symbol",
      "title": "videoColorSpaceHDR",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/videocolorspacehdr"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolution4K": {
      "abstract": [
        {
          "text": "Ultra-high-definition 4K video resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoResolution4K"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolution4K",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItemVideoResolution4K"
        }
      ],
      "role": "symbol",
      "title": "videoResolution4K",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/videoresolution4k"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolutionHD": {
      "abstract": [
        {
          "text": "High-definition video resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoResolutionHD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolutionHD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItemVideoResolutionHD"
        }
      ],
      "role": "symbol",
      "title": "videoResolutionHD",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/videoresolutionhd"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolutionHD",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoColorSpaceHDR",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoColorSpaceDolbyVision",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioDolbyAtmos",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioTranscriptionClosedCaptioning",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioTranscriptionSDH",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioDescription"
      ],
      "title": "Media Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVTopShelfCarouselItemVideoResolution4K"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemVideoResolution4K"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvservices/documentation/TVServices",
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolutionHD",
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoColorSpaceHDR",
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoColorSpaceDolbyVision",
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioDolbyAtmos",
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioTranscriptionClosedCaptioning",
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioTranscriptionSDH",
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/audioDescription"
              ],
              "title": "Media Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "TVTopShelfCarouselItemVideoResolution4K"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoResolutionHD/title",
          "value": "TVTopShelfCarouselItemVideoResolutionHD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoResolutionHD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemVideoResolutionHD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct/title",
          "value": "TVTopShelfCarouselItemMediaOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemMediaOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemMediaOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1audioDescription/title",
          "value": "TVTopShelfCarouselItemAudioDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1audioDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemAudioDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1audioTranscriptionSDH/title",
          "value": "TVTopShelfCarouselItemAudioTranscriptionSDH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1audioTranscriptionSDH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemAudioTranscriptionSDH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1audioTranscriptionClosedCaptioning/title",
          "value": "TVTopShelfCarouselItemAudioTranscriptionClosedCaptioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1audioTranscriptionClosedCaptioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemAudioTranscriptionClosedCaptioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoColorSpaceHDR/title",
          "value": "TVTopShelfCarouselItemVideoColorSpaceHDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoColorSpaceHDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemVideoColorSpaceHDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1audioDolbyAtmos/title",
          "value": "TVTopShelfCarouselItemAudioDolbyAtmos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1audioDolbyAtmos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemAudioDolbyAtmos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoColorSpaceDolbyVision/title",
          "value": "TVTopShelfCarouselItemVideoColorSpaceDolbyVision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoColorSpaceDolbyVision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemVideoColorSpaceDolbyVision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoResolution4K/title",
          "value": "TVTopShelfCarouselItemVideoResolution4K"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoResolution4K/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemVideoResolution4K"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem/title",
          "value": "TVTopShelfCarouselItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/videoresolution4k"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/videoresolution4k"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
