{
  "abstract": [
    {
      "text": "Constants that describe the available charging connector types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INCar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Intents",
    "externalID": "c:@T@INCarChargingConnectorType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ChargingConnectorType"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ChargingConnectorType"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "INCar.ChargingConnectorType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ChargingConnectorType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar": {
      "abstract": [
        {
          "text": "A specific electric vehicle that Maps uses during route planning and navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCar"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCar"
        }
      ],
      "role": "symbol",
      "title": "INCar",
      "type": "topic",
      "url": "/documentation/intents/incar"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType": {
      "abstract": [
        {
          "text": "Constants that describe the available charging connector types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ChargingConnectorType"
        }
      ],
      "role": "symbol",
      "title": "INCar.ChargingConnectorType",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/ccs1": {
      "abstract": [
        {
          "text": "The CCS1 charging connector type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ccs1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/ccs1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeCCS1"
        }
      ],
      "role": "symbol",
      "title": "ccs1",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/ccs1"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/ccs2": {
      "abstract": [
        {
          "text": "The CCS2 charging connector type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ccs2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/ccs2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeCCS2"
        }
      ],
      "role": "symbol",
      "title": "ccs2",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/ccs2"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/chaDeMo": {
      "abstract": [
        {
          "text": "The CHAdeMO charging connector type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chaDeMo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/chaDeMo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeCHAdeMO"
        }
      ],
      "role": "symbol",
      "title": "chaDeMo",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/chademo"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/gbtAC": {
      "abstract": [
        {
          "text": "The GB/T AC charging connector type for alternating current.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gbtAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/gbtAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeGBTAC"
        }
      ],
      "role": "symbol",
      "title": "gbtAC",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/gbtac"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/gbtDC": {
      "abstract": [
        {
          "text": "The GB/T DC charging connector type for direct current.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gbtDC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/gbtDC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeGBTDC"
        }
      ],
      "role": "symbol",
      "title": "gbtDC",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/gbtdc"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a charging connector type using the provided string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/j1772": {
      "abstract": [
        {
          "text": "The J1772 charging connector type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "j1772"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/j1772",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeJ1772"
        }
      ],
      "role": "symbol",
      "title": "j1772",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/j1772"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/mennekes": {
      "abstract": [
        {
          "text": "The Mennekes charging connector type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mennekes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/mennekes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeMennekes"
        }
      ],
      "role": "symbol",
      "title": "mennekes",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/mennekes"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsAC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nacsAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeNACSAC"
        }
      ],
      "role": "symbol",
      "title": "nacsAC",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/nacsac"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsDC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nacsDC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsDC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeNACSDC"
        }
      ],
      "role": "symbol",
      "title": "nacsDC",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/nacsdc"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/tesla": {
      "abstract": [
        {
          "text": "The charging connector type for Tesla electric vehicles.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tesla"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/tesla",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeTesla"
        }
      ],
      "role": "symbol",
      "title": "tesla",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/tesla"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/supportedChargingConnectors": {
      "abstract": [
        {
          "text": "The charging connectors that the electric vehicle supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedChargingConnectors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/supportedChargingConnectors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedChargingConnectors"
        }
      ],
      "role": "symbol",
      "title": "supportedChargingConnectors",
      "type": "topic",
      "url": "/documentation/intents/incar/supportedchargingconnectors"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Cars-Supported-Charging-Connectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCar/supportedChargingConnectors"
      ],
      "title": "Getting the Car’s Supported Charging Connectors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Charging-Connector-Type",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/init(rawValue:)"
      ],
      "title": "Creating a Charging Connector Type"
    },
    {
      "anchor": "Charging-Connector-Types",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/ccs1",
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/ccs2",
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/chaDeMo",
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/gbtAC",
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/gbtDC",
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/j1772",
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/mennekes",
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/tesla"
      ],
      "title": "Charging Connector Types"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsAC",
        "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsDC"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INCarChargingConnectorType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Charging-Connector-Types",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/ccs1",
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/ccs2",
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/chaDeMo",
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/gbtAC",
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/gbtDC",
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/j1772",
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/mennekes",
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/tesla"
              ],
              "title": "Charging Connector Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Cars-Supported-Charging-Connectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCar/supportedChargingConnectors"
              ],
              "title": "Getting the Car’s Supported Charging Connectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "INCarChargingConnectorType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1chaDeMo/title",
          "value": "INCarChargingConnectorTypeCHAdeMO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1chaDeMo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeCHAdeMO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1ccs2/title",
          "value": "INCarChargingConnectorTypeCCS2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1ccs2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeCCS2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1mennekes/title",
          "value": "INCarChargingConnectorTypeMennekes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1mennekes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeMennekes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1gbtAC/title",
          "value": "INCarChargingConnectorTypeGBTAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1gbtAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeGBTAC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1supportedChargingConnectors/title",
          "value": "supportedChargingConnectors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1supportedChargingConnectors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedChargingConnectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1gbtDC/title",
          "value": "INCarChargingConnectorTypeGBTDC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1gbtDC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeGBTDC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1tesla/title",
          "value": "INCarChargingConnectorTypeTesla"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1tesla/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeTesla"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType/title",
          "value": "INCarChargingConnectorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar/title",
          "value": "INCar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1nacsDC/title",
          "value": "INCarChargingConnectorTypeNACSDC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1nacsDC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeNACSDC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1ccs1/title",
          "value": "INCarChargingConnectorTypeCCS1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1ccs1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeCCS1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1j1772/title",
          "value": "INCarChargingConnectorTypeJ1772"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1j1772/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeJ1772"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1nacsAC/title",
          "value": "INCarChargingConnectorTypeNACSAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1nacsAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeNACSAC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/incar/chargingconnectortype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/incar/chargingconnectortype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
