{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/largeblob-5ismm"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"largeBlob"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:22AuthenticationServices60ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInputV","text":"ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput"},{"kind":"text","text":"?"}],"role":"symbol","title":"largeBlob","extendedModule":"AuthenticationServices","externalID":"s:So61ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestC22AuthenticationServicesE9largeBlobAC0acde5LargekF5InputVSgvp","symbolKind":"property","platforms":[{"deprecated":false,"beta":false,"introducedAt":"17.0","name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"17.0","name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"17.0","name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"14.0","name":"macOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false}],"modules":[{"name":"Authentication Services"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"largeBlob"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22AuthenticationServices60ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInputV","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput-swift.struct","kind":"typeIdentifier","text":"ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/largeBlob-5ismm","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/largeBlob-5ismm":{"url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/largeblob-5ismm","abstract":[],"title":"largeBlob","type":"topic","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/largeBlob-5ismm","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"largeBlob","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput","kind":"typeIdentifier","preciseIdentifier":"s:22AuthenticationServices60ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInputV"},{"text":"?","kind":"text"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput-swift.struct":{"url":"/documentation/authenticationservices/asauthorizationpublickeycredentiallargeblobregistrationinput-swift.struct","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput","kind":"identifier"}],"navigatorTitle":[{"text":"ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput","kind":"identifier"}],"abstract":[],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput-swift.struct","kind":"symbol","type":"topic","title":"ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest","abstract":[{"text":"The object for registering a new platform public key credential.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"title":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/title","op":"replace","value":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/fragments","op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"}]},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}