{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/requeststyle-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/requeststyle-swift.property"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/requestStyle-swift.property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","preciseIdentifier":"c:objc(cs)ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum","preciseIdentifier":"c:@E@ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","text":"RequestStyle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"symbol","symbolKind":"property","title":"requestStyle","externalID":"c:objc(cs)ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest(py)requestStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","text":"RequestStyle"}],"navigatorTitle":[{"kind":"identifier","text":"requestStyle"}],"modules":[{"name":"Authentication Services"}],"roleHeading":"Instance Property","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"18.0"},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"introducedAt":"15.0","unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"2.0","unavailable":false}]},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/requestStyle-swift.property":{"title":"requestStyle","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","text":"RequestStyle","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"requestStyle","kind":"identifier"}],"url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/requeststyle-swift.property","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/requestStyle-swift.property","role":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum":{"title":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest.RequestStyle","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestStyle","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"RequestStyle","kind":"identifier"}],"url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest/requeststyle-swift.enum","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum","role":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest","abstract":[{"text":"The object for registering a new platform public key credential.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"title":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"introducedAt":"15.0","unavailable":false},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"2.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"requestStyle"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"requestStyle"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","kind":"typeIdentifier","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/RequestStyle-swift.enum"},{"text":" ","kind":"text"},{"text":"requestStyle","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1requestStyle-swift.property/title","value":"requestStyle","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1requestStyle-swift.property/fragments","value":[{"text":"requestStyle","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1RequestStyle-swift.enum/title","value":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1RequestStyle-swift.enum/fragments","value":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest~1RequestStyle-swift.enum/navigatorTitle","value":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequestStyle","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/title","value":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/fragments","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/navigatorTitle","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}