{
  "abstract": [
    {
      "text": "A controller that acts as a bridge between your Finder Sync extension and the Finder itself.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Finder-Sync/documentation/FinderSync"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)FIFinderSyncController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FIFinderSyncController"
      }
    ],
    "modules": [
      {
        "name": "Finder Sync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FIFinderSyncController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "FIFinderSyncController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FIFinderSyncController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the Finder Sync controller to configure your extension, to set badges",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on items in the Finder’s window, and to get a list of selected and targeted",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Finder-Sync/documentation/FinderSync": {
      "abstract": [
        {
          "text": "Modify the Finder’s user interface to express file synchronization and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync",
      "kind": "symbol",
      "role": "collection",
      "title": "Finder Sync",
      "type": "topic",
      "url": "/documentation/findersync"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class": {
      "abstract": [
        {
          "text": "A type to subclass to add badges, custom shortcut menus, and toolbar buttons to the Finder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIFinderSync"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIFinderSync"
        }
      ],
      "role": "symbol",
      "title": "FIFinderSync",
      "type": "topic",
      "url": "/documentation/findersync/fifindersync-swift.class"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController": {
      "abstract": [
        {
          "text": "A controller that acts as a bridge between your Finder Sync extension and the Finder itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIFinderSyncController"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIFinderSyncController"
        }
      ],
      "role": "symbol",
      "title": "FIFinderSyncController",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/default()": {
      "abstract": [
        {
          "text": "Returns the shared Finder Sync controller object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/default()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultController"
        }
      ],
      "role": "symbol",
      "title": "default()",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/default()"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/directoryURLs": {
      "abstract": [
        {
          "text": "The directories managed by this extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directoryURLs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/directoryURLs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "directoryURLs"
        }
      ],
      "role": "symbol",
      "title": "directoryURLs",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/directoryurls"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/isExtensionEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isExtensionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/isExtensionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extensionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isExtensionEnabled",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/isextensionenabled"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/lastUsedDateForItem(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastUsedDateForItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/lastUsedDateForItem(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastUsedDateForItemWithURL:"
        }
      ],
      "role": "symbol",
      "title": "lastUsedDateForItem(with:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/lastuseddateforitem(with:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/selectedItemURLs()": {
      "abstract": [
        {
          "text": "Returns an array of selected items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedItemURLs"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/selectedItemURLs()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedItemURLs"
        }
      ],
      "role": "symbol",
      "title": "selectedItemURLs()",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/selecteditemurls()"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)": {
      "abstract": [
        {
          "text": "Sets the badge for a file or directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBadgeIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBadgeIdentifier:forURL:"
        }
      ],
      "role": "symbol",
      "title": "setBadgeIdentifier(_:for:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/setbadgeidentifier(_:for:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeImage(_:label:forBadgeIdentifier:)": {
      "abstract": [
        {
          "text": "Sets the badge image and label for the given ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBadgeImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forBadgeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeImage(_:label:forBadgeIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBadgeImage:label:forBadgeIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "setBadgeImage(_:label:forBadgeIdentifier:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/setbadgeimage(_:label:forbadgeidentifier:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setLastUsedDate(_:forItemWith:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setLastUsedDate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forItemWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setLastUsedDate(_:forItemWith:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setLastUsedDate:forItemWithURL:completion:"
        }
      ],
      "role": "symbol",
      "title": "setLastUsedDate(_:forItemWith:completion:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/setlastuseddate(_:foritemwith:completion:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setTagData(_:forItemWith:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTagData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forItemWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setTagData(_:forItemWith:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTagData:forItemWithURL:completion:"
        }
      ],
      "role": "symbol",
      "title": "setTagData(_:forItemWith:completion:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/settagdata(_:foritemwith:completion:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/showExtensionManagementInterface()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showExtensionManagementInterface"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/showExtensionManagementInterface()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showExtensionManagementInterface"
        }
      ],
      "role": "symbol",
      "title": "showExtensionManagementInterface()",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/showextensionmanagementinterface()"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/tagDataForItem(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tagDataForItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/tagDataForItem(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tagDataForItemWithURL:"
        }
      ],
      "role": "symbol",
      "title": "tagDataForItem(with:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/tagdataforitem(with:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/targetedURL()": {
      "abstract": [
        {
          "text": "Returns the URL of the Finder’s current target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetedURL"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/targetedURL()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetedURL"
        }
      ],
      "role": "symbol",
      "title": "targetedURL()",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/targetedurl()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext": {
      "abstract": [
        {
          "text": "The host app context from which an app extension is invoked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionContext"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionContext",
      "type": "topic",
      "url": "/documentation/foundation/nsextensioncontext"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-the-Finder-Sync-Controller",
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/default()",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/directoryURLs",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/selectedItemURLs()",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeImage(_:label:forBadgeIdentifier:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/targetedURL()"
      ],
      "title": "Managing the Finder Sync Controller"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/lastUsedDateForItem(with:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setLastUsedDate(_:forItemWith:completion:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setTagData(_:forItemWith:completion:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/tagDataForItem(with:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/isExtensionEnabled"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/showExtensionManagementInterface()"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FIFinderSyncController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSyncController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSyncController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Finder-Sync/documentation/FinderSync"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-the-Finder-Sync-Controller",
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/default()",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/directoryURLs",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/selectedItemURLs()",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeImage(_:label:forBadgeIdentifier:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/targetedURL()"
              ],
              "title": "Managing the Finder Sync Controller"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/lastUsedDateForItem(with:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setLastUsedDate(_:forItemWith:completion:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setTagData(_:forItemWith:completion:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/tagDataForItem(with:)"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/isExtensionEnabled"
              ],
              "title": "Type Properties"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/showExtensionManagementInterface()"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FIFinderSyncController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSExtensionContext",
                    "text": "NSExtensionContext"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeIdentifier(_:for:)/title",
          "value": "setBadgeIdentifier:forURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeIdentifier(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBadgeIdentifier:forURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1tagDataForItem(with:)/title",
          "value": "tagDataForItemWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1tagDataForItem(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tagDataForItemWithURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1selectedItemURLs()/title",
          "value": "selectedItemURLs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1selectedItemURLs()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectedItemURLs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setTagData(_:forItemWith:completion:)/title",
          "value": "setTagData:forItemWithURL:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setTagData(_:forItemWith:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTagData:forItemWithURL:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1isExtensionEnabled/title",
          "value": "extensionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1isExtensionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extensionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeImage(_:label:forBadgeIdentifier:)/title",
          "value": "setBadgeImage:label:forBadgeIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeImage(_:label:forBadgeIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBadgeImage:label:forBadgeIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1targetedURL()/title",
          "value": "targetedURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1targetedURL()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "targetedURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1default()/title",
          "value": "defaultController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1default()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1lastUsedDateForItem(with:)/title",
          "value": "lastUsedDateForItemWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1lastUsedDateForItem(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lastUsedDateForItemWithURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSync-swift.class/title",
          "value": "FIFinderSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSync-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSync-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController/title",
          "value": "FIFinderSyncController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSyncController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSyncController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setLastUsedDate(_:forItemWith:completion:)/title",
          "value": "setLastUsedDate:forItemWithURL:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setLastUsedDate(_:forItemWith:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setLastUsedDate:forItemWithURL:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1directoryURLs/title",
          "value": "directoryURLs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1directoryURLs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "directoryURLs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1showExtensionManagementInterface()/title",
          "value": "showExtensionManagementInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1showExtensionManagementInterface()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "showExtensionManagementInterface"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/findersync/fifindersynccontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/findersync/fifindersynccontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
