{
  "abstract": [
    {
      "text": "The group of methods to implement for modifying the Finder user interface to express file synchronization status and control.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Finder-Sync/documentation/FinderSync"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FIFinderSync",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FIFinderSyncProtocol"
      }
    ],
    "modules": [
      {
        "name": "Finder Sync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FIFinderSyncProtocol"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FIFinderSyncProtocol"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FIFinderSyncProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Finder-Sync/documentation/FinderSync": {
      "abstract": [
        {
          "text": "Modify the Finder’s user interface to express file synchronization and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync",
      "kind": "symbol",
      "role": "collection",
      "title": "Finder Sync",
      "type": "topic",
      "url": "/documentation/findersync"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class": {
      "abstract": [
        {
          "text": "A type to subclass to add badges, custom shortcut menus, and toolbar buttons to the Finder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIFinderSync"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIFinderSync"
        }
      ],
      "role": "symbol",
      "title": "FIFinderSync",
      "type": "topic",
      "url": "/documentation/findersync/fifindersync-swift.class"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol": {
      "abstract": [
        {
          "text": "The group of methods to implement for modifying the Finder user interface to express file synchronization status and control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIFinderSyncProtocol"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIFinderSyncProtocol"
        }
      ],
      "role": "symbol",
      "title": "FIFinderSyncProtocol",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/beginObservingDirectory(at:)": {
      "abstract": [
        {
          "text": "Tells the extension that the user is looking at a monitored directory or at",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "one of its subdirectories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginObservingDirectory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/beginObservingDirectory(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginObservingDirectoryAtURL:"
        }
      ],
      "role": "symbol",
      "title": "beginObservingDirectory(at:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/beginobservingdirectory(at:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/endObservingDirectory(at:)": {
      "abstract": [
        {
          "text": "Tells the extension that the user has stopped looking at a monitored",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "directory or at one of its subdirectories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endObservingDirectory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/endObservingDirectory(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endObservingDirectoryAtURL:"
        }
      ],
      "role": "symbol",
      "title": "endObservingDirectory(at:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/endobservingdirectory(at:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/makeListenerEndpoint(forServiceName:itemURL:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeListenerEndpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forServiceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderServiceName",
          "text": "NSFileProviderServiceName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSXPCListenerEndpoint",
          "text": "NSXPCListenerEndpoint"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/makeListenerEndpoint(forServiceName:itemURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeListenerEndpointForServiceName:itemURL:andReturnError:"
        }
      ],
      "role": "symbol",
      "title": "makeListenerEndpoint(forServiceName:itemURL:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/makelistenerendpoint(forservicename:itemurl:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/menu(for:)": {
      "abstract": [
        {
          "text": "Requests a custom menu from the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FIMenuKind",
          "text": "FIMenuKind"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/menu(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuForMenuKind:"
        }
      ],
      "role": "symbol",
      "title": "menu(for:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/menu(for:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/requestBadgeIdentifier(for:)": {
      "abstract": [
        {
          "text": "Requests a badge for the given file or directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestBadgeIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/requestBadgeIdentifier(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestBadgeIdentifierForURL:"
        }
      ],
      "role": "symbol",
      "title": "requestBadgeIdentifier(for:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/requestbadgeidentifier(for:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/supportedServiceNamesForItem(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedServiceNamesForItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderServiceName",
          "text": "NSFileProviderServiceName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/supportedServiceNamesForItem(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedServiceNamesForItemWithURL:"
        }
      ],
      "role": "symbol",
      "title": "supportedServiceNamesForItem(with:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/supportedservicenamesforitem(with:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemImage": {
      "abstract": [
        {
          "text": "The image for the extension’s toolbar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarItemImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbarItemImage"
        }
      ],
      "role": "symbol",
      "title": "toolbarItemImage",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/toolbaritemimage"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemName": {
      "abstract": [
        {
          "text": "The name of the extension’s toolbar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarItemName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbarItemName"
        }
      ],
      "role": "symbol",
      "title": "toolbarItemName",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/toolbaritemname"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemToolTip": {
      "abstract": [
        {
          "text": "The tooltip text for the extension’s toolbar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarItemToolTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemToolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbarItemToolTip"
        }
      ],
      "role": "symbol",
      "title": "toolbarItemToolTip",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/toolbaritemtooltip"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/values(forAttributes:forItemWith:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "values"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSURLResourceKey",
          "text": "URLResourceKey"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "forItemWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSURLResourceKey",
          "text": "URLResourceKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/values(forAttributes:forItemWith:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valuesForAttributes:forItemWithURL:completion:"
        }
      ],
      "role": "symbol",
      "title": "values(forAttributes:forItemWith:completion:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol/values(forattributes:foritemwith:completion:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind": {
      "abstract": [
        {
          "text": "The different kinds of custom menus that the Finder Sync extension can",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIMenuKind"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIMenuKind"
        }
      ],
      "role": "symbol",
      "title": "FIMenuKind",
      "type": "topic",
      "url": "/documentation/findersync/fimenukind"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Managing-Badges-Shortcut-Menus-and-Toolbar-Buttons",
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/beginObservingDirectory(at:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/endObservingDirectory(at:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/menu(for:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/requestBadgeIdentifier(for:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemImage",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemName",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemToolTip"
      ],
      "title": "Managing Badges, Shortcut Menus, and Toolbar Buttons"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/makeListenerEndpoint(forServiceName:itemURL:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/supportedServiceNamesForItem(with:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/values(forAttributes:forItemWith:completion:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FIFinderSync"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Finder-Sync/documentation/FinderSync"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Badges-Shortcut-Menus-and-Toolbar-Buttons",
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/beginObservingDirectory(at:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/endObservingDirectory(at:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/menu(for:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/requestBadgeIdentifier(for:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemImage",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemName",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/toolbarItemToolTip"
              ],
              "title": "Managing Badges, Shortcut Menus, and Toolbar Buttons"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/makeListenerEndpoint(forServiceName:itemURL:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/supportedServiceNamesForItem(with:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol/values(forAttributes:forItemWith:completion:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FIFinderSync"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1menu(for:)/title",
          "value": "menuForMenuKind:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1menu(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "menuForMenuKind:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1values(forAttributes:forItemWith:completion:)/title",
          "value": "valuesForAttributes:forItemWithURL:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1values(forAttributes:forItemWith:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valuesForAttributes:forItemWithURL:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol/title",
          "value": "FIFinderSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1beginObservingDirectory(at:)/title",
          "value": "beginObservingDirectoryAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1beginObservingDirectory(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginObservingDirectoryAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind/title",
          "value": "FIMenuKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIMenuKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIMenuKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1supportedServiceNamesForItem(with:)/title",
          "value": "supportedServiceNamesForItemWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1supportedServiceNamesForItem(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportedServiceNamesForItemWithURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1endObservingDirectory(at:)/title",
          "value": "endObservingDirectoryAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1endObservingDirectory(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endObservingDirectoryAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1requestBadgeIdentifier(for:)/title",
          "value": "requestBadgeIdentifierForURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1requestBadgeIdentifier(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestBadgeIdentifierForURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemToolTip/title",
          "value": "toolbarItemToolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemToolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbarItemToolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemImage/title",
          "value": "toolbarItemImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbarItemImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSync-swift.class/title",
          "value": "FIFinderSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSync-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSync-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemName/title",
          "value": "toolbarItemName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1toolbarItemName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbarItemName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1makeListenerEndpoint(forServiceName:itemURL:)/title",
          "value": "makeListenerEndpointForServiceName:itemURL:andReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol~1makeListenerEndpoint(forServiceName:itemURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeListenerEndpointForServiceName:itemURL:andReturnError:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/findersync/fifindersyncprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/findersync/fifindersyncprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
