{
  "abstract": [
    {
      "text": "Creates a compositional layout that contains only list sections of the specified configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout/layoutWithListConfiguration:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UICollectionViewCompositionalLayout(cm)layoutWithListConfiguration:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "layoutWithListConfiguration:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "layoutWithListConfiguration:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "layoutWithListConfiguration:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "layoutWithListConfiguration:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-c.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UICollectionLayoutListConfiguration",
              "text": "UICollectionLayoutListConfiguration"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "configuration"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-c.class": {
      "abstract": [
        {
          "text": "A configuration for creating a list layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutListConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionLayoutListConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistconfiguration-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout": {
      "abstract": [
        {
          "text": "A layout object that lets you combine items in highly adaptive and flexible visual arrangements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewCompositionalLayout"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewCompositionalLayout"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewCompositionalLayout",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcompositionallayout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout/layoutWithListConfiguration:": {
      "abstract": [
        {
          "text": "Creates a compositional layout that contains only list sections of the specified configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layoutWithListConfiguration:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout/layoutWithListConfiguration:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutWithListConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "layoutWithListConfiguration:",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcompositionallayout/layoutwithlistconfiguration:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-list-layout",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-c.class"
      ],
      "title": "Creating a list layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/title",
          "value": "UICollectionViewCompositionalLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewCompositionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewCompositionalLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionviewcompositionallayout/layoutwithlistconfiguration:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
