{
  "abstract": [
    {
      "text": "Handle a new UDP flow of network data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider/handleNewUDPFlow(_:initialRemoteEndpoint:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEAppProxyProvider(im)handleNewUDPFlow:initialRemoteEndpoint:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "handleNewUDPFlow"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NEAppProxyUDPFlow",
        "text": "NEAppProxyUDPFlow"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "initialRemoteEndpoint"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NWEndpoint",
        "text": "NWEndpoint"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "handleNewUDPFlow:initialRemoteEndpoint:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "handleNewUDPFlow(_:initialRemoteEndpoint:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handleNewUDPFlow"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flow"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEAppProxyUDPFlow",
              "text": "NEAppProxyUDPFlow"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "initialRemoteEndpoint"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "remoteEndpoint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NWEndpoint",
              "text": "NWEndpoint"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The new UDP flow.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flow"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The initial remote endpoint provided by the proxied app when the flow was opened.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "remoteEndpoint"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The framework calls this function to deliver a new UDP data flow to the proxy provider implementation. Subclasses can override this method to perform whatever steps are necessary to ready the proxy to receive data from the flow.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you decide to handle the flow, the subclass implementation of this method should return ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In this case, your implementation is responsible for retaining the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your implementation indicates that it’s ready to handle flow data by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlow/open(withLocalEndpoint:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on the flow.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you decide to not handle the flow and instead terminate it, your implementation of this method should return ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This terminates the flow.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default implementation of this method calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider/handleNewFlow(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and returns its result.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlow/open(withLocalEndpoint:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens the flow, indicating to the system that the caller is ready to start receiving and sending data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withLocalEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWHostEndpoint",
          "text": "NWHostEndpoint"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlow/open(withLocalEndpoint:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openWithLocalEndpoint:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "open(withLocalEndpoint:completionHandler:)",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflow/open(withlocalendpoint:completionhandler:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider": {
      "abstract": [
        {
          "text": "The principal class for an app proxy provider app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEAppProxyProvider"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyProvider"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyProvider",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyprovider"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider/handleNewFlow(_:)": {
      "abstract": [
        {
          "text": "Handle a new flow of network data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleNewFlow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEAppProxyFlow",
          "text": "NEAppProxyFlow"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider/handleNewFlow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleNewFlow:"
        }
      ],
      "role": "symbol",
      "title": "handleNewFlow(_:)",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyprovider/handlenewflow(_:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider/handleNewUDPFlow(_:initialRemoteEndpoint:)": {
      "abstract": [
        {
          "text": "Handle a new UDP flow of network data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleNewUDPFlow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEAppProxyUDPFlow",
          "text": "NEAppProxyUDPFlow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "initialRemoteEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWEndpoint",
          "text": "NWEndpoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider/handleNewUDPFlow(_:initialRemoteEndpoint:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleNewUDPFlow:initialRemoteEndpoint:"
        }
      ],
      "role": "symbol",
      "title": "handleNewUDPFlow(_:initialRemoteEndpoint:)",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyprovider/handlenewudpflow(_:initialremoteendpoint:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow": {
      "abstract": [
        {
          "text": "An object for reading and writing data to and from a UDP conversation being proxied by the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEAppProxyUDPFlow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyUDPFlow"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyUDPFlow",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyudpflow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWBonjourServiceEndpoint": {
      "abstract": [
        {
          "text": "A network endpoint specified as a Bonjour service name, type, and domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWBonjourServiceEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWBonjourServiceEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWBonjourServiceEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NWBonjourServiceEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwbonjourserviceendpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint": {
      "abstract": [
        {
          "text": "An abstract base class, shared by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWHostEndpoint",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWBonjourServiceEndpoint",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", that represents the source or destination of a network connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NWEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwendpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWHostEndpoint": {
      "abstract": [
        {
          "text": "A network endpoint specified by DNS name (or IP address) and port.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWHostEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWHostEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWHostEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NWHostEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwhostendpoint"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-proxied-flows",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider/handleNewFlow(_:)"
      ],
      "title": "Handling proxied flows"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "handleNewUDPFlow:initialRemoteEndpoint:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleNewUDPFlow:initialRemoteEndpoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-proxied-flows",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyProvider/handleNewFlow(_:)"
              ],
              "title": "Handling proxied flows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "handleNewUDPFlow:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NEAppProxyUDPFlow",
                    "text": "NEAppProxyUDPFlow"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flow"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "initialRemoteEndpoint:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NWEndpoint",
                    "text": "NWEndpoint"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "remoteEndpoint"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The new UDP flow.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "flow"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The initial remote endpoint provided by the proxied app when the flow was opened.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "remoteEndpoint"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWHostEndpoint/title",
          "value": "NWHostEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWHostEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWHostEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWHostEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWHostEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyProvider~1handleNewUDPFlow(_:initialRemoteEndpoint:)/title",
          "value": "handleNewUDPFlow:initialRemoteEndpoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyProvider~1handleNewUDPFlow(_:initialRemoteEndpoint:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleNewUDPFlow:initialRemoteEndpoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyProvider/title",
          "value": "NEAppProxyProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWEndpoint/title",
          "value": "NWEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlow~1open(withLocalEndpoint:completionHandler:)/title",
          "value": "openWithLocalEndpoint:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlow~1open(withLocalEndpoint:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openWithLocalEndpoint:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWBonjourServiceEndpoint/title",
          "value": "NWBonjourServiceEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWBonjourServiceEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWBonjourServiceEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWBonjourServiceEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWBonjourServiceEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyProvider~1handleNewFlow(_:)/title",
          "value": "handleNewFlow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyProvider~1handleNewFlow(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleNewFlow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyUDPFlow/title",
          "value": "NEAppProxyUDPFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyUDPFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyUDPFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyUDPFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyUDPFlow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/neappproxyprovider/handlenewudpflow(_:initialremoteendpoint:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/neappproxyprovider/handlenewudpflow(_:initialremoteendpoint:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
