{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.shazamkit/documentation/ShazamKit","doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature"]]},"abstract":[{"type":"text","text":"The raw data for the signature."}],"metadata":{"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"15.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"15.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"15.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS","introducedAt":"12.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS","introducedAt":"15.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"watchOS","introducedAt":"8.0"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataRepresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"role":"symbol","externalID":"c:objc(cs)SHSignature(py)dataRepresentation","modules":[{"name":"ShazamKit"}],"navigatorTitle":[{"kind":"identifier","text":"dataRepresentation"}],"title":"dataRepresentation"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/shazamkit/shsignature/datarepresentation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/shazamkit/shsignature/datarepresentation"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Reading-signature-information","generated":true,"title":"Reading signature information","identifiers":["doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/duration"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataRepresentation"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/dataRepresentation"},"sections":[],"kind":"symbol","references":{"doc://com.apple.shazamkit/documentation/ShazamKit":{"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit","url":"/documentation/shazamkit","type":"topic","role":"collection","kind":"symbol","title":"ShazamKit","abstract":[{"type":"text","text":"Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog."}]},"doc://com.externally.resolved.symbol/s:10Foundation4DataV":{"fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Data"}],"url":"/documentation/foundation/data","type":"topic","kind":"symbol","role":"symbol","title":"Data","abstract":[{"text":"A byte buffer in memory.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSData":{"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSData"}],"url":"/documentation/foundation/nsdata","type":"topic","kind":"symbol","role":"symbol","title":"NSData","abstract":[{"text":"A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/dataRepresentation":{"abstract":[{"type":"text","text":"The raw data for the signature."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataRepresentation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"url":"/documentation/shazamkit/shsignature/datarepresentation","type":"topic","title":"dataRepresentation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dataRepresentation"}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/dataRepresentation","kind":"symbol"},"doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature":{"navigatorTitle":[{"text":"SHSignature","kind":"identifier"}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature","role":"symbol","type":"topic","title":"SHSignature","url":"/documentation/shazamkit/shsignature","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SHSignature","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"An object that contains the opaque data and other information for a signature."}]},"doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/duration":{"abstract":[{"type":"text","text":"The duration of the audio you use to generate the signature."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"url":"/documentation/shazamkit/shsignature/duration","type":"topic","title":"duration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"duration"}],"identifier":"doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/duration","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.0","name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.0","name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"12.0","name":"macOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.0","name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"8.0","name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"dataRepresentation"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"dataRepresentation","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.shazamkit/documentation/ShazamKit","doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","value":[{"title":"Reading signature information","generated":true,"identifiers":["doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/duration"],"anchor":"Reading-signature-information"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"atomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData"},{"text":" * ","kind":"text"},{"text":"dataRepresentation","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]},{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dataRepresentation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSData/abstract","value":[{"text":"A static byte buffer in memory.","type":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1dataRepresentation/title","value":"dataRepresentation","op":"replace"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1dataRepresentation/fragments","value":[{"text":"dataRepresentation","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature/title","value":"SHSignature","op":"replace"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature/fragments","value":[{"kind":"identifier","text":"SHSignature"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature/navigatorTitle","value":[{"kind":"identifier","text":"SHSignature"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1duration/title","value":"duration","op":"replace"},{"path":"/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1duration/fragments","value":[{"text":"duration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}