{
  "abstract": [
    {
      "text": "A protocol that defines haptics and audio capabilities of a device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corehaptics/documentation/CoreHaptics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CHHapticDeviceCapability",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CHHapticDeviceCapability"
      }
    ],
    "modules": [
      {
        "name": "Core Haptics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CHHapticDeviceCapability"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CHHapticDeviceCapability"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CHHapticDeviceCapability"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corehaptics/documentation/CoreHaptics": {
      "abstract": [
        {
          "text": "Compose and play haptic patterns to customize your iOS app’s haptic feedback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Haptics",
      "type": "topic",
      "url": "/documentation/corehaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability": {
      "abstract": [
        {
          "text": "A protocol that defines haptics and audio capabilities of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticDeviceCapability"
        }
      ],
      "role": "symbol",
      "title": "CHHapticDeviceCapability",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticdevicecapability"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forDynamicParameter:)": {
      "abstract": [
        {
          "text": "Requests the haptic device’s attributes for a dynamic parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDynamicParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticDynamicParameter",
          "text": "CHHapticDynamicParameter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticDynamicParameterID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CHHapticParameterAttributes",
          "text": "CHHapticParameterAttributes"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forDynamicParameter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributesForDynamicParameter:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "attributes(forDynamicParameter:)",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticdevicecapability/attributes(fordynamicparameter:)"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forEventParameter:eventType:)": {
      "abstract": [
        {
          "text": "Returns the haptic device’s attributes for an event parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forEventParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "eventType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventType",
          "text": "EventType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CHHapticParameterAttributes",
          "text": "CHHapticParameterAttributes"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forEventParameter:eventType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributesForEventParameter:eventType:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "attributes(forEventParameter:eventType:)",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticdevicecapability/attributes(foreventparameter:eventtype:)"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/supportsAudio": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device supports audio event playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/supportsAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsAudio"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsAudio",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticdevicecapability/supportsaudio"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/supportsHaptics": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device supports haptic event playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsHaptics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/supportsHaptics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsHaptics"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsHaptics",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticdevicecapability/supportshaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/capabilitiesForHardware()": {
      "abstract": [
        {
          "text": "Returns a device capability object that describes the device’s haptic support and limitations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capabilitiesForHardware"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CHHapticDeviceCapability",
          "text": "CHHapticDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/capabilitiesForHardware()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "capabilitiesForHardware"
        }
      ],
      "role": "symbol",
      "title": "capabilitiesForHardware()",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/capabilitiesforhardware()"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticParameterAttributes": {
      "abstract": [
        {
          "text": "A protocol for providing default, mininum, and maximum values of a parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticParameterAttributes"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticParameterAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticParameterAttributes"
        }
      ],
      "role": "symbol",
      "title": "CHHapticParameterAttributes",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticparameterattributes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Querying-System-Capabilities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/capabilitiesForHardware()",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticParameterAttributes",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forDynamicParameter:)"
      ],
      "title": "Querying System Capabilities"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-Support-for-Haptics",
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/supportsAudio",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/supportsHaptics"
      ],
      "title": "Determining Support for Haptics"
    },
    {
      "anchor": "Determining-Supported-Parameters",
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forDynamicParameter:)",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forEventParameter:eventType:)"
      ],
      "title": "Determining Supported Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CHHapticDeviceCapability"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticDeviceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticDeviceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corehaptics/documentation/CoreHaptics"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-Support-for-Haptics",
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/supportsAudio",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/supportsHaptics"
              ],
              "title": "Determining Support for Haptics"
            },
            {
              "anchor": "Determining-Supported-Parameters",
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forDynamicParameter:)",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forEventParameter:eventType:)"
              ],
              "title": "Determining Supported Parameters"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Querying-System-Capabilities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/capabilitiesForHardware()",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticParameterAttributes",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticDeviceCapability/attributes(forDynamicParameter:)"
              ],
              "title": "Querying System Capabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CHHapticDeviceCapability"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability~1attributes(forDynamicParameter:)/title",
          "value": "attributesForDynamicParameter:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability~1attributes(forDynamicParameter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributesForDynamicParameter:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability~1supportsHaptics/title",
          "value": "supportsHaptics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability~1supportsHaptics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsHaptics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability/title",
          "value": "CHHapticDeviceCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticDeviceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticDeviceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability~1attributes(forEventParameter:eventType:)/title",
          "value": "attributesForEventParameter:eventType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability~1attributes(forEventParameter:eventType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributesForEventParameter:eventType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability~1supportsAudio/title",
          "value": "supportsAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticDeviceCapability~1supportsAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticParameterAttributes/title",
          "value": "CHHapticParameterAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticParameterAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticParameterAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticParameterAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticParameterAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1capabilitiesForHardware()/title",
          "value": "capabilitiesForHardware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1capabilitiesForHardware()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "capabilitiesForHardware"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corehaptics/chhapticdevicecapability"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corehaptics/chhapticdevicecapability"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
