{
  "abstract": [
    {
      "text": "Create and play a transient haptic pattern from a dictionary literal inline.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corehaptics/documentation/CoreHaptics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corehaptics/documentation/CoreHaptics/playing-a-single-tap-haptic-pattern"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Haptics"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Playing a single-tap haptic pattern"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This article describes how to define the haptic pattern for a single haptic tap and how to play that haptic pattern through a haptic engine.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-haptic-engine",
          "level": 3,
          "text": "Create a haptic engine",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is your app’s interface to the haptic device. An instance of a haptic engine allows you to create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPatternPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticAdvancedPatternPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to play individual haptics. Create the haptic engine as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/preparing-your-app-to-play-haptics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Specify-a-dictionary-literal",
          "level": 3,
          "text": "Specify a dictionary literal",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The next step is to create a dictionary literal representing the haptic. The following represents a single haptic tap:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let hapticDict = [",
                    "    CHHapticPattern.Key.pattern: [",
                    "        [CHHapticPattern.Key.event: [",
                    "            CHHapticPattern.Key.eventType: CHHapticEvent.EventType.hapticTransient,",
                    "            CHHapticPattern.Key.time: CHHapticTimeImmediate,",
                    "            CHHapticPattern.Key.eventDuration: 1.0]",
                    "        ]",
                    "    ]",
                    "]"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSDictionary* hapticDict = @{",
                    "    CHHapticPatternKeyPattern: @[ ",
                    "        @{ CHHapticPatternKeyEvent: @{",
                    "            CHHapticPatternKeyEventType: CHHapticEventTypeHapticTransient,",
                    "            CHHapticPatternKeyTime: @(CHHapticTimeImmediate),",
                    "            CHHapticPatternKeyEventDuration: @1.0 },",
                    "        },",
                    "    ],",
                    "};"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Each entry in the dictionary shown above is a haptic event, with an event type, a start time, and a duration. In this case, the event type is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/EventType/hapticTransient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " because a single tap is a transient pattern — a quick impulse. The time is ",
              "type": "text"
            },
            {
              "code": "CHHapticTimeImmediate",
              "type": "codeVoice"
            },
            {
              "text": " to indicate that the event begins immediately, right after time ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ". The duration of ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": " indicates that the event lasts one second.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-haptic-pattern-player-from-the-dictionary",
          "level": 3,
          "text": "Create a haptic pattern player from the dictionary",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Initialize a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " from the dictionary you just created.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let pattern = try CHHapticPattern(dictionary: hapticDict)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSError* error;",
                    "CHHapticPattern* pattern = [[CHHapticPattern alloc] initWithDictionary:hapticDict error:&error];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re ready to play your haptic, create a player for that pattern. Each player is responsible for playing one pattern. You can reuse a player to play its pattern as many times as you like.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use one of the haptic engine’s factory methods, like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/makePlayer(with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", to create the haptic pattern player.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let player = try engine.makePlayer(with: pattern)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSError* error = nil;",
                    "id<CHHapticPatternPlayer> player = [_engine createPlayerWithPattern:pattern error:&error];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "If you call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPatternPlayer/start(atTime:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on a player that’s already playing, it restarts itself at the beginning of the pattern.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Haptic players are inexpensive, lightweight objects, so create and discard them freely. Unless your app requires real-time, latency-free haptic feedback in response to user interaction — like precise ticks on a dial — you can create your player right before playing the haptic.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Start-the-engine-and-play-the-haptic-pattern",
          "level": 3,
          "text": "Start the engine and play the haptic pattern",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Start the haptic engine before you play a haptic player, and stop the engine once you’ve finished playing all haptic patterns. Play the haptic by calling the player’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPatternPlayer/start(atTime:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "// Stop the engine after it completes the playback.",
                    "engine.notifyWhenPlayersFinished { error in",
                    "    return .stopEngine",
                    "}",
                    "",
                    "try engine.start()",
                    "try player.start(atTime: 0)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "// Stop the engine after it completes the playback.",
                    "[_engine notifyWhenPlayersFinished:^CHHapticEngineFinishedAction(NSError * _Nullable error) {",
                    "    return CHHapticEngineFinishedActionStopEngine;",
                    "}];",
                    "    ",
                    "[_engine startWithCompletionHandler:^(NSError* returnedError) {",
                    "    NSError* error;",
                    "    [self.player startAtTime:0 error:&error];",
                    "}];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "If the engine is in a running state when you call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/start()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the system plays the haptic at the scheduled time. Playback follows a “fire and forget” model, so your app doesn’t need to keep the player and pattern in memory once you’ve called ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/start()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You need to retain your engine so it doesn’t exit scope during your program.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Unless you’re playing several haptic patterns in succession, bookend haptic playback with starting and stopping the engine. Starting the engine ensures that the haptic engine is in a running state when you schedule a haptic to play. Stopping the engine after you finish playing the haptic conserves power and allows it to prepare for the next time your app needs haptic playback. Be aware that your engine may stop on its own in auto-shutdown mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corehaptics/documentation/CoreHaptics": {
      "abstract": [
        {
          "text": "Compose and play haptic patterns to customize your iOS app’s haptic feedback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Haptics",
      "type": "topic",
      "url": "/documentation/corehaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticAdvancedPatternPlayer": {
      "abstract": [
        {
          "text": "A protocol that defines an advanced pattern player capable of looping, seeking, pausing, and resuming haptic playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticAdvancedPatternPlayer"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticAdvancedPatternPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticAdvancedPatternPlayer"
        }
      ],
      "role": "symbol",
      "title": "CHHapticAdvancedPatternPlayer",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticadvancedpatternplayer"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine": {
      "abstract": [
        {
          "text": "An object that represents the connection to the haptic server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticEngine"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngine"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/makePlayer(with:)": {
      "abstract": [
        {
          "text": "Creates a standard haptic pattern player from a haptic pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makePlayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticPattern",
          "text": "CHHapticPattern"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CHHapticPatternPlayer",
          "text": "CHHapticPatternPlayer"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/makePlayer(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createPlayerWithPattern:error:"
        }
      ],
      "role": "symbol",
      "title": "makePlayer(with:)",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/makeplayer(with:)"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/start()": {
      "abstract": [
        {
          "text": "Synchronously starts the haptic engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/start()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "start()",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/start()"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/EventType/hapticTransient": {
      "abstract": [
        {
          "text": "A brief impulse occurring at a specific point in time, like the feedback from toggling a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hapticTransient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventType",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/EventType/hapticTransient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventTypeHapticTransient"
        }
      ],
      "role": "symbol",
      "title": "hapticTransient",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/eventtype/haptictransient"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern": {
      "abstract": [
        {
          "text": "An object representing a haptic waveform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticPattern"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPattern"
        }
      ],
      "role": "symbol",
      "title": "CHHapticPattern",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpattern"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPatternPlayer": {
      "abstract": [
        {
          "text": "A protocol that defines a standard pattern player capable of playing haptic patterns with fixed parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticPatternPlayer"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPatternPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticPatternPlayer"
        }
      ],
      "role": "symbol",
      "title": "CHHapticPatternPlayer",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpatternplayer"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPatternPlayer/start(atTime:)": {
      "abstract": [
        {
          "text": "Starts playing the pattern at the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPatternPlayer/start(atTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startAtTime:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "start(atTime:)",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticpatternplayer/start(attime:)"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/preparing-your-app-to-play-haptics": {
      "abstract": [
        {
          "text": "Set up your app to play haptics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/preparing-your-app-to-play-haptics",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to play haptics",
      "type": "topic",
      "url": "/documentation/corehaptics/preparing-your-app-to-play-haptics"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/preparing-your-app-to-play-haptics",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPatternPlayer",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticAdvancedPatternPlayer"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/preparing-your-app-to-play-haptics",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPattern",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticPatternPlayer",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticAdvancedPatternPlayer"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/title",
          "value": "CHHapticEngine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1start()/title",
          "value": "startAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1start()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPatternPlayer/title",
          "value": "CHHapticPatternPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPatternPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPatternPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPatternPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1makePlayer(with:)/title",
          "value": "createPlayerWithPattern:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1makePlayer(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createPlayerWithPattern:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPatternPlayer~1start(atTime:)/title",
          "value": "startAtTime:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPatternPlayer~1start(atTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAtTime:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticAdvancedPatternPlayer/title",
          "value": "CHHapticAdvancedPatternPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticAdvancedPatternPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticAdvancedPatternPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticAdvancedPatternPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticAdvancedPatternPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1EventType~1hapticTransient/title",
          "value": "CHHapticEventTypeHapticTransient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1EventType~1hapticTransient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventTypeHapticTransient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern/title",
          "value": "CHHapticPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticPattern/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticPattern"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corehaptics/playing-a-single-tap-haptic-pattern"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corehaptics/playing-a-single-tap-haptic-pattern"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
