{
  "abstract": [
    {
      "text": "A type that represents the permissions that a user grants.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application/Permissions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So11CKContainerC8CloudKitE11ApplicationO11Permissionsa",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Permissions"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Permissions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "8.0",
        "message": "renamed to CKContainer.ApplicationPermissions",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "8.0",
        "message": "renamed to CKContainer.ApplicationPermissions",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "13.1",
        "message": "renamed to CKContainer.ApplicationPermissions",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "10.10",
        "message": "renamed to CKContainer.ApplicationPermissions",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "9.0",
        "message": "renamed to CKContainer.ApplicationPermissions",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "message": "renamed to CKContainer.ApplicationPermissions",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "3.0",
        "message": "renamed to CKContainer.ApplicationPermissions",
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "Swift",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CKContainer.Application.Permissions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Permissions"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKContainer",
              "text": "CKContainer"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CKApplicationPermissions",
              "text": "ApplicationPermissions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer": {
      "abstract": [
        {
          "text": "A conduit to your app’s databases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "role": "symbol",
      "title": "CKContainer",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application": {
      "abstract": [
        {
          "text": "A collection of types for app permissions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Application"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Application"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.Application",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/application"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application/PermissionBlock": {
      "abstract": [
        {
          "text": "A type that represents a handler that processes the outcome of a permission’s request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PermissionBlock"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application/PermissionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PermissionBlock"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.Application.PermissionBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/application/permissionblock"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application/PermissionStatus": {
      "abstract": [
        {
          "text": "A type that represents the status of a permission.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PermissionStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application/PermissionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PermissionStatus"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.Application.PermissionStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/application/permissionstatus"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application/Permissions": {
      "abstract": [
        {
          "text": "A type that represents the permissions that a user grants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Permissions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application/Permissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Permissions"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.Application.Permissions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/application/permissions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissions": {
      "abstract": [
        {
          "text": "Constants that represent the permissions that a user grants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ApplicationPermissions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ApplicationPermissions"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.ApplicationPermissions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/applicationpermissions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Container-Application-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application/PermissionBlock",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/Application/PermissionStatus"
      ],
      "title": "Container Application Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/title",
          "value": "CKContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissions/title",
          "value": "CKApplicationPermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckcontainer/application/permissions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
