{
  "abstract": [
    {
      "text": "The color to use for the separators of the item the configuration applies to when the item is in a multiple-selection group.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class/multipleSelectionColor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIListSeparatorConfiguration(py)multipleSelectionColor",
    "fragments": [
      {
        "kind": "identifier",
        "text": "multipleSelectionColor"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "multipleSelectionColor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "multipleSelectionColor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIColor",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "multipleSelectionColor"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class": {
      "abstract": [
        {
          "text": "A configuration that controls the list separator appearance in a list section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIListSeparatorConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIListSeparatorConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uilistseparatorconfiguration-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class/color": {
      "abstract": [
        {
          "text": "The color to use for the separators of the item the configuration applies to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class/color",
      "kind": "symbol",
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/uikit/uilistseparatorconfiguration-c.class/color"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class/multipleSelectionColor": {
      "abstract": [
        {
          "text": "The color to use for the separators of the item the configuration applies to when the item is in a multiple-selection group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "multipleSelectionColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class/multipleSelectionColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "multipleSelectionColor",
      "type": "topic",
      "url": "/documentation/uikit/uilistseparatorconfiguration-c.class/multipleselectioncolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class/visualEffect": {
      "abstract": [
        {
          "text": "The visual effect to use for the separators of the item the configuration applies to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "visualEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class/visualEffect",
      "kind": "symbol",
      "role": "symbol",
      "title": "visualEffect",
      "type": "topic",
      "url": "/documentation/uikit/uilistseparatorconfiguration-c.class/visualeffect"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-separator-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class/color",
        "doc://com.apple.uikit/documentation/UIKit/UIListSeparatorConfiguration-c.class/visualEffect"
      ],
      "title": "Configuring separator appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title",
          "value": "UIColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uilistseparatorconfiguration-c.class/multipleselectioncolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
