{
  "abstract": [
    {
      "text": "The insets (or outsets, if negative) for the background and stroke, relative to the edges of the containing view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/backgroundInsets"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit25UIBackgroundConfigurationV16backgroundInsetsSo017NSDirectionalEdgeE0Vvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "backgroundInsets"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
        "text": "NSDirectionalEdgeInsets"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "backgroundInsets"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "backgroundInsets"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
              "text": "NSDirectionalEdgeInsets"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property applies to the custom view. The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSDirectionalEdgeInsetsZero",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSDirectionalEdgeInsetsZero": {
      "abstract": [
        {
          "text": "A directional edge insets structure whose top, leading, bottom, and trailing fields all have a value of `0`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsetsZero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSDirectionalEdgeInsetsZero",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDirectionalEdgeInsetsZero",
      "type": "topic",
      "url": "/documentation/AppKit/NSDirectionalEdgeInsetsZero"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets": {
      "abstract": [
        {
          "text": "The inset distances for views, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "NSDirectionalEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/nsdirectionaledgeinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A configuration that describes a specific background appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIBackgroundConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/backgroundColor": {
      "abstract": [
        {
          "text": "The color of the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/backgroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/backgroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/backgroundColorTransformer": {
      "abstract": [
        {
          "text": "The color transformer for resolving the background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColorTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit31UIConfigurationColorTransformerV",
          "text": "UIConfigurationColorTransformer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/backgroundColorTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "backgroundColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/backgroundcolortransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/backgroundInsets": {
      "abstract": [
        {
          "text": "The insets (or outsets, if negative) for the background and stroke, relative to the edges of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/backgroundInsets",
      "kind": "symbol",
      "role": "symbol",
      "title": "backgroundInsets",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/backgroundinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/cornerRadius": {
      "abstract": [
        {
          "text": "The preferred corner radius, using a continuous corner curve, for the background and stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/cornerRadius",
      "kind": "symbol",
      "role": "symbol",
      "title": "cornerRadius",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/cornerradius"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/customView": {
      "abstract": [
        {
          "text": "A custom view for the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/customView",
      "kind": "symbol",
      "role": "symbol",
      "title": "customView",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/customview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/edgesAddingLayoutMarginsToBackgroundInsets": {
      "abstract": [
        {
          "text": "The edges on which the configuration adds the containing view’s layout margins to the background insets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edgesAddingLayoutMarginsToBackgroundInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDirectionalRectEdge",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/edgesAddingLayoutMarginsToBackgroundInsets",
      "kind": "symbol",
      "role": "symbol",
      "title": "edgesAddingLayoutMarginsToBackgroundInsets",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/edgesaddinglayoutmarginstobackgroundinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/image": {
      "abstract": [
        {
          "text": "The image displayed in the view’s background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/imageContentMode": {
      "abstract": [
        {
          "text": "A property that determines the layout of a background image in a view when its bounds change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageContentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewContentMode",
          "text": "ContentMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/imageContentMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageContentMode",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/imagecontentmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/resolvedBackgroundColor(for:)": {
      "abstract": [
        {
          "text": "Generates the resolved background color for the specified tint color, using the background color and color transformer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolvedBackgroundColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/resolvedBackgroundColor(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "resolvedBackgroundColor(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/resolvedbackgroundcolor(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/resolvedStrokeColor(for:)": {
      "abstract": [
        {
          "text": "Generates the resolved stroke color for the specified tint color, using the stroke color and color transformer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolvedStrokeColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/resolvedStrokeColor(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "resolvedStrokeColor(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/resolvedstrokecolor(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeColor": {
      "abstract": [
        {
          "text": "The color of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "strokeColor",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/strokecolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeColorTransformer": {
      "abstract": [
        {
          "text": "The color transformer for resolving the stroke color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeColorTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit31UIConfigurationColorTransformerV",
          "text": "UIConfigurationColorTransformer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeColorTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "strokeColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/strokecolortransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeOutset": {
      "abstract": [
        {
          "text": "The outset (or inset, if negative) for the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeOutset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeOutset",
      "kind": "symbol",
      "role": "symbol",
      "title": "strokeOutset",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/strokeoutset"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeWidth": {
      "abstract": [
        {
          "text": "The width of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeWidth",
      "kind": "symbol",
      "role": "symbol",
      "title": "strokeWidth",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/strokewidth"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/visualEffect": {
      "abstract": [
        {
          "text": "The visual effect that the configuration applies to the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visualEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIVisualEffect",
          "text": "UIVisualEffect"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/visualEffect",
      "kind": "symbol",
      "role": "symbol",
      "title": "visualEffect",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/visualeffect"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-background",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/customView",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/cornerRadius",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/edgesAddingLayoutMarginsToBackgroundInsets",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/backgroundColor",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/backgroundColorTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/resolvedBackgroundColor(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/visualEffect",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeColor",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeColorTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/resolvedStrokeColor(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeWidth",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/strokeOutset",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/image",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/imageContentMode"
      ],
      "title": "Customizing the background"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalEdgeInsets/title",
          "value": "NSDirectionalEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalEdgeInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSDirectionalEdgeInsetsZero/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
              "text": "NSDirectionalEdgeInsets"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsetsZero"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibackgroundconfiguration-swift.struct/backgroundinsets"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
