{
  "abstract": [
    {
      "text": "Creates the default configuration you use to style a grouped list header or footer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/listGroupedHeaderFooter()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:5UIKit25UIBackgroundConfigurationV23listGroupedHeaderFooterACyFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "listGroupedHeaderFooter"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit25UIBackgroundConfigurationV",
        "text": "UIBackgroundConfiguration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use the generic listHeader() or listFooter() background configuration",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use the generic listHeader() or listFooter() background configuration",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use the generic listHeader() or listFooter() background configuration",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "listGroupedHeaderFooter()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "listGroupedHeaderFooter"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit25UIBackgroundConfigurationV",
              "text": "UIBackgroundConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default configuration for a grouped list header or footer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create this configuration to update the styling for the background of a header or footer in a table view or collection view list. When you apply this configuration, the background of the header or footer matches the system default styling for a header or footer in a grouped list.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For an appearance consistent with system defaults, use this background configuration for a header or footer in these contexts:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A table view that you configure with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/grouped",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/insetGrouped",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " enumeration cases.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A a collection view list that you configure with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct/Appearance-swift.enum/grouped",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct/Appearance-swift.enum/insetGrouped",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " enumeration cases.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A configuration that describes a specific background appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIBackgroundConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/listGroupedHeaderFooter()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a grouped list header or footer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listGroupedHeaderFooter"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit25UIBackgroundConfigurationV",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/listGroupedHeaderFooter()",
      "kind": "symbol",
      "role": "symbol",
      "title": "listGroupedHeaderFooter()",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/listgroupedheaderfooter()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/listPlainHeaderFooter()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a plain list header or footer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listPlainHeaderFooter"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit25UIBackgroundConfigurationV",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/listPlainHeaderFooter()",
      "kind": "symbol",
      "role": "symbol",
      "title": "listPlainHeaderFooter()",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/listplainheaderfooter()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/listSidebarHeader()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a sidebar list header.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listSidebarHeader"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit25UIBackgroundConfigurationV",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/listSidebarHeader()",
      "kind": "symbol",
      "role": "symbol",
      "title": "listSidebarHeader()",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct/listsidebarheader()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct/Appearance-swift.enum/grouped": {
      "abstract": [
        {
          "text": "The grouped list appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grouped"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct/Appearance-swift.enum/grouped",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionLayoutListConfiguration.Appearance.grouped",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistconfiguration-swift.struct/appearance-swift.enum/grouped"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct/Appearance-swift.enum/insetGrouped": {
      "abstract": [
        {
          "text": "The inset grouped list appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insetGrouped"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct/Appearance-swift.enum/insetGrouped",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionLayoutListConfiguration.Appearance.insetGrouped",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistconfiguration-swift.struct/appearance-swift.enum/insetgrouped"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/grouped": {
      "abstract": [
        {
          "text": "A table view where sections have distinct groups of rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grouped"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/grouped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewStyleGrouped"
        }
      ],
      "role": "symbol",
      "title": "UITableView.Style.grouped",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/style-swift.enum/grouped"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/insetGrouped": {
      "abstract": [
        {
          "text": "A table view where the grouped sections are inset with rounded corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insetGrouped"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/insetGrouped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewStyleInsetGrouped"
        }
      ],
      "role": "symbol",
      "title": "UITableView.Style.insetGrouped",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/style-swift.enum/insetgrouped"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-header-and-footer-background-configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/listPlainHeaderFooter()",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct/listSidebarHeader()"
      ],
      "title": "Creating header and footer background configurations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1grouped/title",
          "value": "UITableViewStyleGrouped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1grouped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewStyleGrouped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1insetGrouped/title",
          "value": "UITableViewStyleInsetGrouped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1insetGrouped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewStyleInsetGrouped"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibackgroundconfiguration-swift.struct/listgroupedheaderfooter()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
