{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.identitylookup/documentation/IdentityLookup",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse/transactionalSubActions-4bfqz"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "IdentityLookup",
    "externalID": "s:So40ILMessageFilterCapabilitiesQueryResponseC14IdentityLookupE23transactionalSubActionsSaySo0abI6ActionVGvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "transactionalSubActions"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ILMessageFilterSubAction",
        "text": "ILMessageFilterSubAction"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "SMS and Call Reporting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "transactionalSubActions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@nonobjc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "final"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "transactionalSubActions"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ILMessageFilterSubAction",
              "text": "ILMessageFilterSubAction"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup": {
      "abstract": [
        {
          "text": "Create app extensions to manage and report unwanted SMS messages and spam calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup",
      "kind": "symbol",
      "role": "collection",
      "title": "SMS and Call Reporting",
      "type": "topic",
      "url": "/documentation/identitylookup"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse": {
      "abstract": [
        {
          "text": "A response to a message filter capabilities query request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterCapabilitiesQueryResponse"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterCapabilitiesQueryResponse"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterCapabilitiesQueryResponse",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryresponse"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse/promotionalSubActions-98kzj": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "promotionalSubActions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ILMessageFilterSubAction",
          "text": "ILMessageFilterSubAction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse/promotionalSubActions-98kzj",
      "kind": "symbol",
      "role": "symbol",
      "title": "promotionalSubActions",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryresponse/promotionalsubactions-98kzj"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse/transactionalSubActions-4bfqz": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalSubActions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ILMessageFilterSubAction",
          "text": "ILMessageFilterSubAction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse/transactionalSubActions-4bfqz",
      "kind": "symbol",
      "role": "symbol",
      "title": "transactionalSubActions",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryresponse/transactionalsubactions-4bfqz"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction": {
      "abstract": [
        {
          "text": "Responds to a received message with a filter subaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubAction"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubAction"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-Subactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterCapabilitiesQueryResponse/promotionalSubActions-98kzj"
      ],
      "title": "Setting the Subactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction/title",
          "value": "ILMessageFilterSubAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryResponse/title",
          "value": "ILMessageFilterCapabilitiesQueryResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterCapabilitiesQueryResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterCapabilitiesQueryResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterCapabilitiesQueryResponse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltercapabilitiesqueryresponse/transactionalsubactions-4bfqz"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
