{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsform/preferredtextfieldwidth()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsform/preferredtextfieldwidth()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Auto-Layout-Sizing","title":"Auto Layout Sizing","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSForm/setPreferredTextFieldWidth(_:)"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredTextFieldWidth","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The field’s width.","type":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"If the width is negative, the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","isActive":true,"type":"reference"},{"text":" matches the historic behavior, which is that it is large enough to accommodate the title, bezel, and the current text.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The default is -1."}],"type":"paragraph"}]}],"kind":"symbol","abstract":[{"type":"text","text":"The preferred width of the form’s cells when using Auto Layout."}],"metadata":{"symbolKind":"method","title":"preferredTextFieldWidth()","roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(cs)NSForm(im)preferredTextFieldWidth","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTextFieldWidth"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"platforms":[{"deprecated":false,"deprecatedAt":"10.10","introducedAt":"10.8","name":"macOS","beta":false,"unavailable":false}],"modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"preferredTextFieldWidth"}]},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSForm"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSForm/preferredTextFieldWidth()","interfaceLanguage":"swift"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSForm/preferredTextFieldWidth()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/preferredTextFieldWidth()","title":"preferredTextFieldWidth()","abstract":[{"type":"text","text":"The preferred width of the form’s cells when using Auto Layout."}],"url":"/documentation/appkit/nsform/preferredtextfieldwidth()","kind":"symbol","navigatorTitle":[{"text":"preferredTextFieldWidth","kind":"identifier"}],"deprecated":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTextFieldWidth"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSFormCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSFormCell","kind":"symbol","navigatorTitle":[{"text":"NSFormCell","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSFormCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSFormCell","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"NSFormCell"},{"text":" class is used to implement text entry fields in a form. The left part of an ","type":"text"},{"type":"codeVoice","code":"NSFormCell"},{"text":" object contains a title. The right part contains an editable text entry field.","type":"text"}],"url":"/documentation/appkit/nsformcell"},"doc://com.apple.appkit/documentation/AppKit/NSForm":{"type":"topic","kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"NSForm","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm","url":"/documentation/appkit/nsform","title":"NSForm","role":"symbol","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"NSForm"},{"type":"text","text":" object is a vertical matrix of "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFormCell"},{"type":"text","text":" objects to implement the fields."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSForm","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSForm/setPreferredTextFieldWidth(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setPreferredTextFieldWidth(_:)","title":"setPreferredTextFieldWidth(_:)","abstract":[{"type":"text","text":"Sets the preferred text field width used by Auto Layout."}],"url":"/documentation/appkit/nsform/setpreferredtextfieldwidth(_:)","kind":"symbol","navigatorTitle":[{"text":"setPreferredTextFieldWidth:","kind":"identifier"}],"deprecated":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredTextFieldWidth"},{"kind":"text","text":"("},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","abstract":[{"text":"The basic type for all floating-point values.","type":"text"}],"type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"role":"symbol","type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","kind":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"CGFloat","kind":"identifier"}],"abstract":[{"text":"The basic type for floating-point scalar values in Core Graphics and related frameworks.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSSize","text":"NSSize","kind":"typeIdentifier"}],"url":"/documentation/appkit/nscell/cellsize","title":"cellSize","navigatorTitle":[{"text":"cellSize","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","abstract":[{"type":"text","text":"The minimum size needed to display the cell."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"name":"macOS","introducedAt":"10.8","beta":false,"deprecated":false,"deprecatedAt":"10.10"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"preferredTextFieldWidth"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preferredTextFieldWidth"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSForm"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Auto Layout Sizing","anchor":"Auto-Layout-Sizing","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSForm/setPreferredTextFieldWidth(_:)"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"identifier","text":"preferredTextFieldWidth"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The field’s width.","type":"text"}]}]},"path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1preferredTextFieldWidth()/title","value":"preferredTextFieldWidth"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1preferredTextFieldWidth()/fragments","value":[{"text":"- ","kind":"text"},{"text":"preferredTextFieldWidth","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/title","value":"NSFormCell"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/fragments","value":[{"text":"NSFormCell","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/navigatorTitle","value":[{"text":"NSFormCell","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/title","value":"NSForm"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/fragments","value":[{"text":"NSForm","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/navigatorTitle","value":[{"kind":"identifier","text":"NSForm"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setPreferredTextFieldWidth(_:)/title","value":"setPreferredTextFieldWidth:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setPreferredTextFieldWidth(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPreferredTextFieldWidth:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/title","op":"replace","value":"cellSize"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/fragments","op":"replace","value":[{"text":"cellSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}