{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSForm/setEntryWidth(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Changing-the-Appearance-of-All-the-Entries","title":"Changing the Appearance of All the Entries","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSForm/setBezeled(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setBordered(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setFrameSize(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setInterlineSpacing(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleAlignment(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleBaseWritingDirection(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTextAlignment(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTextBaseWritingDirection(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleFont(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTextFont(_:)"],"generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSForm"]]},"deprecationSummary":[{"inlineContent":[{"text":"Use NSTextField directly instead, and consider NSStackView for layout assistance","type":"text"}],"type":"paragraph"}],"sections":[],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setEntryWidth","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setEntryWidth:","kind":"identifier"}],"roleHeading":"Instance Method","platforms":[{"unavailable":false,"name":"macOS","deprecatedAt":"10.10","beta":false,"introducedAt":"10.0","deprecated":false,"message":"Use NSTextField directly instead, and consider NSStackView for layout assistance"}],"title":"setEntryWidth(_:)","modules":[{"name":"AppKit"}],"role":"symbol","externalID":"c:objc(cs)NSForm(im)setEntryWidth:"},"variants":[{"paths":["/documentation/appkit/nsform/setentrywidth(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsform/setentrywidth(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setEntryWidth","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"width","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The width of all entries, measured in points in the user coordinate space. This value represents the width of both the title and the text field.","type":"text"}]}],"name":"width"}],"kind":"parameters"}],"kind":"symbol","abstract":[{"text":"Sets the width of all the entries in the receiver.","type":"text"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleAlignment(_:)":{"type":"topic","abstract":[{"type":"text","text":"Sets the alignment for all of the entry titles."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"setTitleAlignment:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleAlignment(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setTitleAlignment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"title":"setTitleAlignment(_:)","url":"/documentation/appkit/nsform/settitlealignment(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSForm":{"type":"topic","kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"NSForm","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm","url":"/documentation/appkit/nsform","title":"NSForm","role":"symbol","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"NSForm"},{"type":"text","text":" object is a vertical matrix of "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFormCell"},{"type":"text","text":" objects to implement the fields."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSForm","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSForm/setEntryWidth(_:)":{"type":"topic","abstract":[{"type":"text","text":"Sets the width of all the entries in the receiver."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"setEntryWidth:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setEntryWidth(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEntryWidth"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"title":"setEntryWidth(_:)","url":"/documentation/appkit/nsform/setentrywidth(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleFont(_:)":{"type":"topic","abstract":[{"type":"text","text":"Sets the font for all of the entry titles."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"setTitleFont:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleFont(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitleFont"},{"text":"(","kind":"text"},{"text":"NSFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSFont"},{"text":")","kind":"text"}],"deprecated":true,"title":"setTitleFont(_:)","url":"/documentation/appkit/nsform/settitlefont(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSFormCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSFormCell","kind":"symbol","navigatorTitle":[{"text":"NSFormCell","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSFormCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSFormCell","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"NSFormCell"},{"text":" class is used to implement text entry fields in a form. The left part of an ","type":"text"},{"type":"codeVoice","code":"NSFormCell"},{"text":" object contains a title. The right part contains an editable text entry field.","type":"text"}],"url":"/documentation/appkit/nsformcell"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSForm/setTextBaseWritingDirection(_:)":{"type":"topic","abstract":[{"type":"text","text":"Sets the writing direction for the text content of every control embedded in the form."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"setTextBaseWritingDirection:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setTextBaseWritingDirection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTextBaseWritingDirection"},{"text":"(","kind":"text"},{"text":"NSWritingDirection","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWritingDirection"},{"text":")","kind":"text"}],"deprecated":true,"title":"setTextBaseWritingDirection(_:)","url":"/documentation/appkit/nsform/settextbasewritingdirection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSForm/setFrameSize(_:)":{"type":"topic","title":"setFrameSize(_:)","navigatorTitle":[{"text":"setFrameSize:","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/appkit/nsform/setframesize(_:)","abstract":[{"type":"text","text":"Sets the size of the receiver’s frame size to the specified value."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setFrameSize(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFrameSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSForm/setTextAlignment(_:)":{"type":"topic","title":"setTextAlignment(_:)","navigatorTitle":[{"text":"setTextAlignment:","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/appkit/nsform/settextalignment(_:)","abstract":[{"type":"text","text":"Sets the alignment for all of the receiver’s editable text."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setTextAlignment(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setTextAlignment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":")","kind":"text"}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleBaseWritingDirection(_:)":{"abstract":[{"text":"Sets the writing direction for the title of every control embedded in the form.","type":"text"}],"deprecated":true,"type":"topic","kind":"symbol","navigatorTitle":[{"text":"setTitleBaseWritingDirection:","kind":"identifier"}],"title":"setTitleBaseWritingDirection(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTitleBaseWritingDirection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSWritingDirection","preciseIdentifier":"c:@E@NSWritingDirection","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleBaseWritingDirection(_:)","role":"symbol","url":"/documentation/appkit/nsform/settitlebasewritingdirection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSForm/setInterlineSpacing(_:)":{"abstract":[{"text":"Sets the spacing between entries","type":"text"}],"deprecated":true,"type":"topic","kind":"symbol","navigatorTitle":[{"text":"setInterlineSpacing:","kind":"identifier"}],"title":"setInterlineSpacing(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setInterlineSpacing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setInterlineSpacing(_:)","role":"symbol","url":"/documentation/appkit/nsform/setinterlinespacing(_:)"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","abstract":[{"text":"The basic type for all floating-point values.","type":"text"}],"type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat"},"doc://com.apple.appkit/documentation/AppKit/NSForm/setBordered(_:)":{"abstract":[{"type":"text","text":"Sets whether the receiver’s entries should display a border around their editable text fields."}],"deprecated":true,"type":"topic","kind":"symbol","navigatorTitle":[{"text":"setBordered:","kind":"identifier"}],"title":"setBordered(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBordered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setBordered(_:)","role":"symbol","url":"/documentation/appkit/nsform/setbordered(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSForm/setBezeled(_:)":{"type":"topic","title":"setBezeled(_:)","navigatorTitle":[{"text":"setBezeled:","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/appkit/nsform/setbezeled(_:)","abstract":[{"text":"Sets whether the receiver’s entries should display a bezel around their editable text.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setBezeled(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBezeled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSForm/setTextFont(_:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"setTextFont:","kind":"identifier"}],"deprecated":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setTextFont"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSFont","kind":"typeIdentifier","text":"NSFont"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Sets the font for all of the receiver’s editable text fields"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSForm/setTextFont(_:)","title":"setTextFont(_:)","url":"/documentation/appkit/nsform/settextfont(_:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"role":"symbol","type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","kind":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"CGFloat","kind":"identifier"}],"abstract":[{"text":"The basic type for floating-point scalar values in Core Graphics and related frameworks.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.0","deprecated":false,"deprecatedAt":"10.10"}],"op":"replace"},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"setEntryWidth:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEntryWidth:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSForm"]]}},{"op":"add","path":"/topicSections","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Changing-the-Appearance-of-All-the-Entries","title":"Changing the Appearance of All the Entries","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSForm/setBezeled(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setBordered(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setFrameSize(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setInterlineSpacing(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleAlignment(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleBaseWritingDirection(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTextAlignment(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTextBaseWritingDirection(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTitleFont(_:)","doc://com.apple.appkit/documentation/AppKit/NSForm/setTextFont(_:)"],"generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setEntryWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"width","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The width of all entries, measured in points in the user coordinate space. This value represents the width of both the title and the text field."}],"type":"paragraph"}],"name":"width"}]},"path":"/primaryContentSections/1","op":"replace"},{"path":"/deprecationSummary","op":"replace","value":[{"inlineContent":[{"text":"Use NSTextField directly instead, and consider NSStackView for layout assistance","type":"text"}],"type":"paragraph"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTitleAlignment(_:)/title","op":"replace","value":"setTitleAlignment:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTitleAlignment(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setTitleAlignment:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/title","op":"replace","value":"NSForm"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/fragments","op":"replace","value":[{"text":"NSForm","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSForm"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setEntryWidth(_:)/title","op":"replace","value":"setEntryWidth:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setEntryWidth(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEntryWidth:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTitleFont(_:)/title","op":"replace","value":"setTitleFont:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTitleFont(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setTitleFont:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/title","op":"replace","value":"NSFormCell"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/fragments","op":"replace","value":[{"text":"NSFormCell","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/navigatorTitle","op":"replace","value":[{"text":"NSFormCell","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTextBaseWritingDirection(_:)/title","op":"replace","value":"setTextBaseWritingDirection:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTextBaseWritingDirection(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTextBaseWritingDirection:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setFrameSize(_:)/title","op":"replace","value":"setFrameSize:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setFrameSize(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setFrameSize:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTextAlignment(_:)/title","op":"replace","value":"setTextAlignment:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTextAlignment(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTextAlignment:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTitleBaseWritingDirection(_:)/title","op":"replace","value":"setTitleBaseWritingDirection:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTitleBaseWritingDirection(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setTitleBaseWritingDirection:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setInterlineSpacing(_:)/title","op":"replace","value":"setInterlineSpacing:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setInterlineSpacing(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setInterlineSpacing:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setBordered(_:)/title","op":"replace","value":"setBordered:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setBordered(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setBordered:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setBezeled(_:)/title","op":"replace","value":"setBezeled:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setBezeled(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setBezeled:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTextFont(_:)/title","op":"replace","value":"setTextFont:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm~1setTextFont(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTextFont:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}