{
  "abstract": [
    {
      "text": "A type identifier for records of clinical notes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/clinicalNoteRecord"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "c:@HKClinicalTypeIdentifierClinicalNoteRecord",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "clinicalNoteRecord"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
        "text": "HKClinicalTypeIdentifier"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKClinicalTypeIdentifierClinicalNoteRecord"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "clinicalNoteRecord"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "clinicalNoteRecord"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
              "text": "HKClinicalTypeIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Clinical notes can have one or more attached files. While these files are often PDFs, HTML, or text files, they can be any format. Check the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment/contentType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to determine the file type. For more information on accessing the attachments, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app has permission to read ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/clinicalNoteRecord",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " samples, it can also access the attachments. For more information on reading clinical note records, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/accessing-health-records",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment": {
      "abstract": [
        {
          "text": "A file that is attached to a sample in the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAttachment"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAttachment"
        }
      ],
      "role": "symbol",
      "title": "HKAttachment",
      "type": "topic",
      "url": "/documentation/healthkit/hkattachment"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment/contentType": {
      "abstract": [
        {
          "text": "The type of data stored in the attached file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment/contentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentType"
        }
      ],
      "role": "symbol",
      "title": "contentType",
      "type": "topic",
      "url": "/documentation/healthkit/hkattachment/contenttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalType": {
      "abstract": [
        {
          "text": "A type that identifies samples that contain clinical record data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKClinicalType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalType"
        }
      ],
      "role": "symbol",
      "title": "HKClinicalType",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier": {
      "abstract": [
        {
          "text": "A type identifier for the different categories of clinical records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKClinicalTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/allergyRecord": {
      "abstract": [
        {
          "text": "A type identifier for records of allergic or intolerant reactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allergyRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/allergyRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierAllergyRecord"
        }
      ],
      "role": "symbol",
      "title": "allergyRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/allergyrecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/clinicalNoteRecord": {
      "abstract": [
        {
          "text": "A type identifier for records of clinical notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clinicalNoteRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/clinicalNoteRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierClinicalNoteRecord"
        }
      ],
      "role": "symbol",
      "title": "clinicalNoteRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/clinicalnoterecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/conditionRecord": {
      "abstract": [
        {
          "text": "A type identifier for records of a condition, problem, diagnosis, or other event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditionRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/conditionRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierConditionRecord"
        }
      ],
      "role": "symbol",
      "title": "conditionRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/conditionrecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/coverageRecord": {
      "abstract": [
        {
          "text": "A type identifier for records containing information about the user’s insurance coverage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coverageRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/coverageRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierCoverageRecord"
        }
      ],
      "role": "symbol",
      "title": "coverageRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/coveragerecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/immunizationRecord": {
      "abstract": [
        {
          "text": "A type identifier for records of the current or historical administration of vaccines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "immunizationRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/immunizationRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierImmunizationRecord"
        }
      ],
      "role": "symbol",
      "title": "immunizationRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/immunizationrecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/labResultRecord": {
      "abstract": [
        {
          "text": "A type identifier for records of lab results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "labResultRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/labResultRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierLabResultRecord"
        }
      ],
      "role": "symbol",
      "title": "labResultRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/labresultrecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/medicationRecord": {
      "abstract": [
        {
          "text": "A type identifier for records of medication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medicationRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/medicationRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierMedicationRecord"
        }
      ],
      "role": "symbol",
      "title": "medicationRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/medicationrecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/procedureRecord": {
      "abstract": [
        {
          "text": "A type identifier for records of procedures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "procedureRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/procedureRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierProcedureRecord"
        }
      ],
      "role": "symbol",
      "title": "procedureRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/procedurerecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/vitalSignRecord": {
      "abstract": [
        {
          "text": "A type identifier for records of vital signs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vitalSignRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/vitalSignRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierVitalSignRecord"
        }
      ],
      "role": "symbol",
      "title": "vitalSignRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/vitalsignrecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for findings and interpretation of diagnostic tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diagnosticReport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeDiagnosticReport"
        }
      ],
      "role": "symbol",
      "title": "diagnosticReport",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/diagnosticreport"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for document references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentReference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeDocumentReference"
        }
      ],
      "role": "symbol",
      "title": "documentReference",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/documentreference"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/accessing-health-records": {
      "abstract": [
        {
          "text": "Read clinical record data from the HealthKit store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/accessing-health-records",
      "kind": "article",
      "role": "article",
      "title": "Accessing Health Records",
      "type": "topic",
      "url": "/documentation/healthkit/accessing-health-records"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Clinical-Record-Type-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/allergyRecord",
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/conditionRecord",
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/immunizationRecord",
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/labResultRecord",
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/medicationRecord",
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/procedureRecord",
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/vitalSignRecord",
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/coverageRecord"
      ],
      "title": "Clinical Record Type Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKClinicalTypeIdentifierClinicalNoteRecord"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierClinicalNoteRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Clinical-Record-Type-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/allergyRecord",
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/conditionRecord",
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/immunizationRecord",
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/labResultRecord",
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/medicationRecord",
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/procedureRecord",
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/vitalSignRecord",
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/coverageRecord"
              ],
              "title": "Clinical Record Type Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
                    "text": "HKClinicalTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKClinicalTypeIdentifierClinicalNoteRecord"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1documentReference/title",
          "value": "HKFHIRResourceTypeDocumentReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1documentReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeDocumentReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachment~1contentType/title",
          "value": "contentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachment~1contentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1immunizationRecord/title",
          "value": "HKClinicalTypeIdentifierImmunizationRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1immunizationRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierImmunizationRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1vitalSignRecord/title",
          "value": "HKClinicalTypeIdentifierVitalSignRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1vitalSignRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierVitalSignRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1conditionRecord/title",
          "value": "HKClinicalTypeIdentifierConditionRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1conditionRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierConditionRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1medicationRecord/title",
          "value": "HKClinicalTypeIdentifierMedicationRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1medicationRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierMedicationRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1allergyRecord/title",
          "value": "HKClinicalTypeIdentifierAllergyRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1allergyRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierAllergyRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier/title",
          "value": "HKClinicalTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1diagnosticReport/title",
          "value": "HKFHIRResourceTypeDiagnosticReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1diagnosticReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeDiagnosticReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1clinicalNoteRecord/title",
          "value": "HKClinicalTypeIdentifierClinicalNoteRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1clinicalNoteRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierClinicalNoteRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalType/title",
          "value": "HKClinicalType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1procedureRecord/title",
          "value": "HKClinicalTypeIdentifierProcedureRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1procedureRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierProcedureRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1labResultRecord/title",
          "value": "HKClinicalTypeIdentifierLabResultRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1labResultRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierLabResultRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1coverageRecord/title",
          "value": "HKClinicalTypeIdentifierCoverageRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1coverageRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierCoverageRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachment/title",
          "value": "HKAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAttachment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkclinicaltypeidentifier/clinicalnoterecord"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkclinicaltypeidentifier/clinicalnoterecord"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
