{
  "abstract": [
    {
      "text": "The number of rows for treating the particle image as a grid of animation frames.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceRowCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNParticleSystem(py)imageSequenceRowCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "imageSequenceRowCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "imageSequenceRowCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "imageSequenceRowCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "imageSequenceRowCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To specify a sequence of frames for animating each particle, arrange the frames as a grid in a single image, as shown in ",
              "type": "text"
            },
            {
              "identifier": "/documentation/scenekit/scnparticlesystem/1524153-particleimage#1965925",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Then use this property and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to specify the arrangement of frames in the image, and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrame",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties to define animation timing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ". If the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value is also ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " (the default), this specifies no animation for particle images.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "/documentation/scenekit/scnparticlesystem/1524153-particleimage#1965925": {
      "identifier": "/documentation/scenekit/scnparticlesystem/1524153-particleimage#1965925",
      "title": "Figure 1",
      "titleInlineContent": [
        {
          "text": "Figure 1",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/scenekit/scnparticlesystem/1524153-particleimage#1965925"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode": {
      "abstract": [
        {
          "text": "Options for animating each particle with a sequence of images, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNParticleImageSequenceAnimationMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleImageSequenceAnimationMode"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleImageSequenceAnimationMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleimagesequenceanimationmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem": {
      "abstract": [
        {
          "text": "An object that animates and renders a system of small image sprites using a high-level simulation whose general behavior you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNParticleSystem"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleSystem"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleSystem",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode": {
      "abstract": [
        {
          "text": "The animation mode for particle image animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceAnimationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNParticleImageSequenceAnimationMode",
          "text": "SCNParticleImageSequenceAnimationMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceAnimationMode"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceAnimationMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceanimationmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount": {
      "abstract": [
        {
          "text": "The number of columns for treating the particle image as a grid of animation frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceColumnCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceColumnCount"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceColumnCount",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequencecolumncount"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRate": {
      "abstract": [
        {
          "text": "The rate, in frames per second, of particle image animation. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceFrameRate"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceFrameRate",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceframerate"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRateVariation": {
      "abstract": [
        {
          "text": "The range, in frames per second, of randomized frame rates for particle image animation. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceFrameRateVariation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRateVariation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceFrameRateVariation"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceFrameRateVariation",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceframeratevariation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrame": {
      "abstract": [
        {
          "text": "The index of the first frame in a particle image animation. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceInitialFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceInitialFrame"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceInitialFrame",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceinitialframe"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrameVariation": {
      "abstract": [
        {
          "text": "The range of randomized initial frames for particle image animation. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceInitialFrameVariation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrameVariation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceInitialFrameVariation"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceInitialFrameVariation",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceinitialframevariation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceRowCount": {
      "abstract": [
        {
          "text": "The number of rows for treating the particle image as a grid of animation frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceRowCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceRowCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceRowCount"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceRowCount",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequencerowcount"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animating-Particle-Images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrame",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrameVariation",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRate",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRateVariation",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode"
      ],
      "title": "Animating Particle Images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "imageSequenceRowCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceRowCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Animating-Particle-Images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrame",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrameVariation",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRate",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRateVariation",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode"
              ],
              "title": "Animating Particle Images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "imageSequenceRowCount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceColumnCount/title",
          "value": "imageSequenceColumnCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceColumnCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceColumnCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceRowCount/title",
          "value": "imageSequenceRowCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceRowCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceRowCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceInitialFrame/title",
          "value": "imageSequenceInitialFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceInitialFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceInitialFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceFrameRateVariation/title",
          "value": "imageSequenceFrameRateVariation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceFrameRateVariation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceFrameRateVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceInitialFrameVariation/title",
          "value": "imageSequenceInitialFrameVariation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceInitialFrameVariation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceInitialFrameVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceAnimationMode/title",
          "value": "imageSequenceAnimationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceAnimationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceAnimationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceFrameRate/title",
          "value": "imageSequenceFrameRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceFrameRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceFrameRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem/title",
          "value": "SCNParticleSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode/title",
          "value": "SCNParticleImageSequenceAnimationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnparticlesystem/imagesequencerowcount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnparticlesystem/imagesequencerowcount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
