{
  "abstract": [
    {
      "text": "A Boolean value that determines whether particles are removed from the scene upon colliding with another object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleDiesOnCollision"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNParticleSystem(py)particleDiesOnCollision",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "particleDiesOnCollision"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "particleDiesOnCollision"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "particleDiesOnCollision"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "particleDiesOnCollision"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property has no effect if the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/colliderNodes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array is empty or contains no nodes with attached geometry.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", specifying that particles remain in the scene after a collision. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleBounce",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleFriction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties determine whether and how particles bounce or slide after colliding with a geometry.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem": {
      "abstract": [
        {
          "text": "An object that animates and renders a system of small image sprites using a high-level simulation whose general behavior you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNParticleSystem"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleSystem"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleSystem",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/acceleration": {
      "abstract": [
        {
          "text": "The constant acceleration vector, in units per second per second, applied to all particles in the system. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceleration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/acceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceleration"
        }
      ],
      "role": "symbol",
      "title": "acceleration",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/acceleration"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/colliderNodes": {
      "abstract": [
        {
          "text": "The nodes whose geometry the system’s particles can collide with.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colliderNodes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/colliderNodes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colliderNodes"
        }
      ],
      "role": "symbol",
      "title": "colliderNodes",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/collidernodes"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/dampingFactor": {
      "abstract": [
        {
          "text": "A factor that slows particles relative to their velocity. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dampingFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/dampingFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dampingFactor"
        }
      ],
      "role": "symbol",
      "title": "dampingFactor",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/dampingfactor"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/isAffectedByGravity": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether gravity, as defined by the scene’s physics simulation, affects the motion of particles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAffectedByGravity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/isAffectedByGravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "affectedByGravity"
        }
      ],
      "role": "symbol",
      "title": "isAffectedByGravity",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/isaffectedbygravity"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/isAffectedByPhysicsFields": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether physics fields in the scene affect the motion of particles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAffectedByPhysicsFields"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/isAffectedByPhysicsFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "affectedByPhysicsFields"
        }
      ],
      "role": "symbol",
      "title": "isAffectedByPhysicsFields",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/isaffectedbyphysicsfields"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleBounce": {
      "abstract": [
        {
          "text": "The restitution coefficient of each particle in the system. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleBounce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleBounce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleBounce"
        }
      ],
      "role": "symbol",
      "title": "particleBounce",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particlebounce"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleBounceVariation": {
      "abstract": [
        {
          "text": "The range of randomized restitution coefficients for particles. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleBounceVariation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleBounceVariation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleBounceVariation"
        }
      ],
      "role": "symbol",
      "title": "particleBounceVariation",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particlebouncevariation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleCharge": {
      "abstract": [
        {
          "text": "The electric charge, in coulombs, of each particle in the system. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleCharge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleCharge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleCharge"
        }
      ],
      "role": "symbol",
      "title": "particleCharge",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particlecharge"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleChargeVariation": {
      "abstract": [
        {
          "text": "The range, in coulombs, of randomized particle charges. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleChargeVariation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleChargeVariation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleChargeVariation"
        }
      ],
      "role": "symbol",
      "title": "particleChargeVariation",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particlechargevariation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleDiesOnCollision": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether particles are removed from the scene upon colliding with another object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleDiesOnCollision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleDiesOnCollision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleDiesOnCollision"
        }
      ],
      "role": "symbol",
      "title": "particleDiesOnCollision",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particlediesoncollision"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleFriction": {
      "abstract": [
        {
          "text": "The friction coefficient of each particle in the system. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleFriction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleFriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleFriction"
        }
      ],
      "role": "symbol",
      "title": "particleFriction",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particlefriction"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleFrictionVariation": {
      "abstract": [
        {
          "text": "The range of randomized friction coefficients for particles. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleFrictionVariation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleFrictionVariation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleFrictionVariation"
        }
      ],
      "role": "symbol",
      "title": "particleFrictionVariation",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particlefrictionvariation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleMass": {
      "abstract": [
        {
          "text": "The mass, in kilograms, of each particle in the system. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleMass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleMass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleMass"
        }
      ],
      "role": "symbol",
      "title": "particleMass",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particlemass"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleMassVariation": {
      "abstract": [
        {
          "text": "The range, in kilograms, of randomized particle masses. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleMassVariation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleMassVariation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleMassVariation"
        }
      ],
      "role": "symbol",
      "title": "particleMassVariation",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particlemassvariation"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Simulating-Physics-for-Particles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/isAffectedByGravity",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/isAffectedByPhysicsFields",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/colliderNodes",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/acceleration",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/dampingFactor",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleMass",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleMassVariation",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleCharge",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleChargeVariation",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleBounce",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleBounceVariation",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleFriction",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleFrictionVariation"
      ],
      "title": "Simulating Physics for Particles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "particleDiesOnCollision"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleDiesOnCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Simulating-Physics-for-Particles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/isAffectedByGravity",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/isAffectedByPhysicsFields",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/colliderNodes",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/acceleration",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/dampingFactor",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleMass",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleMassVariation",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleCharge",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleChargeVariation",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleBounce",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleBounceVariation",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleFriction",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleFrictionVariation"
              ],
              "title": "Simulating Physics for Particles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "particleDiesOnCollision"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleCharge/title",
          "value": "particleCharge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleCharge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleCharge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleMassVariation/title",
          "value": "particleMassVariation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleMassVariation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleMassVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleFrictionVariation/title",
          "value": "particleFrictionVariation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleFrictionVariation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleFrictionVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1colliderNodes/title",
          "value": "colliderNodes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1colliderNodes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colliderNodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleBounce/title",
          "value": "particleBounce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleBounce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleBounce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1acceleration/title",
          "value": "acceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1acceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleMass/title",
          "value": "particleMass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleMass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleMass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1isAffectedByGravity/title",
          "value": "affectedByGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1isAffectedByGravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "affectedByGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleBounceVariation/title",
          "value": "particleBounceVariation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleBounceVariation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleBounceVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleDiesOnCollision/title",
          "value": "particleDiesOnCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleDiesOnCollision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleDiesOnCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleChargeVariation/title",
          "value": "particleChargeVariation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleChargeVariation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleChargeVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem/title",
          "value": "SCNParticleSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleFriction/title",
          "value": "particleFriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleFriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleFriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1dampingFactor/title",
          "value": "dampingFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1dampingFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dampingFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1isAffectedByPhysicsFields/title",
          "value": "affectedByPhysicsFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1isAffectedByPhysicsFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "affectedByPhysicsFields"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnparticlesystem/particlediesoncollision"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnparticlesystem/particlediesoncollision"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
