{
  "abstract": [
    {
      "text": "A coordinate pair that describes the sample’s light brightness and tint.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/chromaticity-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRAmbientLightSample(py)chromaticity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "chromaticity"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRAmbientLightSample",
        "text": "SRAmbientLightSample"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SRAmbientLightChromaticity",
        "text": "Chromaticity"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "chromaticity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "chromaticity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "chromaticity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRAmbientLightSample",
              "text": "SRAmbientLightSample"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SRAmbientLightChromaticity",
              "text": "Chromaticity"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample": {
      "abstract": [
        {
          "text": "The amount of ambient light in the user’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct": {
      "abstract": [
        {
          "text": "A coordinate pair that describes light brightness and tint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Chromaticity"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Chromaticity"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.Chromaticity",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/chromaticity-swift.struct"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement": {
      "abstract": [
        {
          "text": "Directional values that describe light-source location with respect to the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SensorPlacement"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SensorPlacement"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/chromaticity-swift.property": {
      "abstract": [
        {
          "text": "A coordinate pair that describes the sample’s light brightness and tint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chromaticity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRAmbientLightSample",
          "text": "SRAmbientLightSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SRAmbientLightChromaticity",
          "text": "Chromaticity"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/chromaticity-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chromaticity"
        }
      ],
      "role": "symbol",
      "title": "chromaticity",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/chromaticity-swift.property"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/lux": {
      "abstract": [
        {
          "text": "An object that describes the sample’s luminous flux.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lux"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitIlluminance",
          "text": "UnitIlluminance"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/lux",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lux"
        }
      ],
      "role": "symbol",
      "title": "lux",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/lux"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/placement": {
      "abstract": [
        {
          "text": "The light’s location relative to the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRAmbientLightSample",
          "text": "SRAmbientLightSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRAmbientLightSensorPlacement",
          "text": "SensorPlacement"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/placement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placement"
        }
      ],
      "role": "symbol",
      "title": "placement",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/placement"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measuring-light-level",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/lux",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/placement",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement"
      ],
      "title": "Measuring light level"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "chromaticity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chromaticity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measuring-light-level",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/lux",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/placement",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement"
              ],
              "title": "Measuring light level"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@SRAmbientLightChromaticity",
                    "text": "SRAmbientLightChromaticity"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "chromaticity"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/title",
          "value": "SRAmbientLightSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1lux/title",
          "value": "lux"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1lux/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lux"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1chromaticity-swift.property/title",
          "value": "chromaticity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1chromaticity-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chromaticity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1Chromaticity-swift.struct/title",
          "value": "SRAmbientLightChromaticity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1Chromaticity-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightChromaticity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1Chromaticity-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightChromaticity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement/title",
          "value": "SRAmbientLightSensorPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1placement/title",
          "value": "placement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1placement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srambientlightsample/chromaticity-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srambientlightsample/chromaticity-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
