{
  "abstract": [
    {
      "text": "Directional values that describe light-source location with respect to the sensor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "c:@E@SRAmbientLightSensorPlacement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SensorPlacement"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SensorPlacement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SRAmbientLightSample.SensorPlacement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SensorPlacement"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample": {
      "abstract": [
        {
          "text": "The amount of ambient light in the user’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct": {
      "abstract": [
        {
          "text": "A coordinate pair that describes light brightness and tint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Chromaticity"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Chromaticity"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.Chromaticity",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/chromaticity-swift.struct"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement": {
      "abstract": [
        {
          "text": "Directional values that describe light-source location with respect to the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SensorPlacement"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SensorPlacement"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottom": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the bottom of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontBottom"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontBottom"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontBottom",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontbottom"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomLeft": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the bottom-left of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontBottomLeft"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontBottomLeft",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontbottomleft"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomRight": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the bottom-right of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontBottomRight"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontBottomRight"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontBottomRight",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontbottomright"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontLeft": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the left of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontLeft"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontLeft"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontLeft",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontleft"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontRight": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the right of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontRight"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontRight"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontRight",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontright"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTop": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the top of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontTop"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontTop"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontTop",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/fronttop"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopLeft": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the top-left of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontTopLeft"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontTopLeft"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontTopLeft",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/fronttopleft"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopRight": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the top-right of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontTopRight"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontTopRight"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontTopRight",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/fronttopright"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/init(rawvalue:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/unknown": {
      "abstract": [
        {
          "text": "Indicates that the sensor can’t determine the light source’s location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementUnknown"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.unknown",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/unknown"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/chromaticity-swift.property": {
      "abstract": [
        {
          "text": "A coordinate pair that describes the sample’s light brightness and tint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chromaticity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRAmbientLightSample",
          "text": "SRAmbientLightSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SRAmbientLightChromaticity",
          "text": "Chromaticity"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/chromaticity-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chromaticity"
        }
      ],
      "role": "symbol",
      "title": "chromaticity",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/chromaticity-swift.property"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/lux": {
      "abstract": [
        {
          "text": "An object that describes the sample’s luminous flux.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lux"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitIlluminance",
          "text": "UnitIlluminance"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/lux",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lux"
        }
      ],
      "role": "symbol",
      "title": "lux",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/lux"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/placement": {
      "abstract": [
        {
          "text": "The light’s location relative to the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRAmbientLightSample",
          "text": "SRAmbientLightSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRAmbientLightSensorPlacement",
          "text": "SensorPlacement"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/placement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placement"
        }
      ],
      "role": "symbol",
      "title": "placement",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/placement"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measuring-light-level",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/chromaticity-swift.property",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/lux",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/placement"
      ],
      "title": "Measuring light level"
    }
  ],
  "topicSections": [
    {
      "anchor": "Placement-configurations",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottom",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomLeft",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomRight",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontLeft",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontRight",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTop",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopLeft",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopRight",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/unknown"
      ],
      "title": "Placement configurations"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRAmbientLightSensorPlacement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Placement-configurations",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottom",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomLeft",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomRight",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontLeft",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontRight",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTop",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopLeft",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopRight",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/unknown"
              ],
              "title": "Placement configurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measuring-light-level",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/chromaticity-swift.property",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/Chromaticity-swift.struct",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/lux",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/placement"
              ],
              "title": "Measuring light level"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SRAmbientLightSensorPlacement"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTopLeft/title",
          "value": "SRAmbientLightSensorPlacementFrontTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTopLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontLeft/title",
          "value": "SRAmbientLightSensorPlacementFrontLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTop/title",
          "value": "SRAmbientLightSensorPlacementFrontTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottomLeft/title",
          "value": "SRAmbientLightSensorPlacementFrontBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement/title",
          "value": "SRAmbientLightSensorPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1placement/title",
          "value": "placement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1placement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTopRight/title",
          "value": "SRAmbientLightSensorPlacementFrontTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTopRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottom/title",
          "value": "SRAmbientLightSensorPlacementFrontBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1Chromaticity-swift.struct/title",
          "value": "SRAmbientLightChromaticity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1Chromaticity-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightChromaticity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1Chromaticity-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightChromaticity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontRight/title",
          "value": "SRAmbientLightSensorPlacementFrontRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/title",
          "value": "SRAmbientLightSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1unknown/title",
          "value": "SRAmbientLightSensorPlacementUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1chromaticity-swift.property/title",
          "value": "chromaticity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1chromaticity-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chromaticity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottomRight/title",
          "value": "SRAmbientLightSensorPlacementFrontBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1lux/title",
          "value": "lux"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1lux/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lux"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srambientlightsample/sensorplacement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srambientlightsample/sensorplacement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
