{"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"training","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"If set to ","type":"text"},{"code":"YES","type":"codeVoice"},{"text":" then the layer will produce training state tensor as a secondary output.","type":"text"},{"text":" ","type":"text"},{"text":"Default value: ","type":"text"},{"code":"NO","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/metalperformanceshadersgraph/mpsgraphlstmdescriptor/training"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/metalperformanceshadersgraph/mpsgraphlstmdescriptor/training"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor"]]},"metadata":{"modules":[{"name":"Metal Performance Shaders Graph"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"training","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","title":"training","role":"symbol","externalID":"c:objc(cs)MPSGraphLSTMDescriptor(py)training","roleHeading":"Instance Property","navigatorTitle":[{"text":"training","kind":"identifier"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"15.4"},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"15.4"},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"15.4"},{"unavailable":false,"beta":false,"name":"macOS","deprecated":false,"introducedAt":"12.3"},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"15.4"},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0"}]},"kind":"symbol","abstract":[{"type":"text","text":"A parameter that enables the LSTM layer to support training."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor/training"},"sections":[],"references":{"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph":{"role":"collection","kind":"symbol","url":"/documentation/metalperformanceshadersgraph","abstract":[{"type":"text","text":"Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine."}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","title":"Metal Performance Shaders Graph","type":"topic"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor/training":{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor/training","type":"topic","abstract":[{"text":"A parameter that enables the LSTM layer to support training.","type":"text"}],"url":"/documentation/metalperformanceshadersgraph/mpsgraphlstmdescriptor/training","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"training","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"training","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"training","kind":"identifier"}]},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor":{"role":"symbol","abstract":[{"text":"The class that defines the parameters for a long short-term memory (LSTM) operation.","type":"text"}],"title":"MPSGraphLSTMDescriptor","kind":"symbol","type":"topic","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor","url":"/documentation/metalperformanceshadersgraph/mpsgraphlstmdescriptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSGraphLSTMDescriptor"}],"navigatorTitle":[{"kind":"identifier","text":"MPSGraphLSTMDescriptor"}]},"doc://com.externally.resolved.symbol/s:Sb":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"kind":"symbol","title":"Bool","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"url":"/documentation/Swift/Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"15.4"},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"15.4"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"15.4"},{"deprecated":false,"name":"macOS","unavailable":false,"beta":false,"introducedAt":"12.3"},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"15.4"},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"training"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"training","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor"]]}},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"training","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphLSTMDescriptor~1training/title","value":"training","op":"replace"},{"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphLSTMDescriptor~1training/fragments","value":[{"text":"training","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphLSTMDescriptor/title","value":"MPSGraphLSTMDescriptor","op":"replace"},{"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphLSTMDescriptor/fragments","value":[{"kind":"identifier","text":"MPSGraphLSTMDescriptor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphLSTMDescriptor/navigatorTitle","value":[{"kind":"identifier","text":"MPSGraphLSTMDescriptor"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}