{
  "abstract": [
    {
      "text": "The notification can’t save because you haven’t added it to a notification collection and saved the collection first.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKError",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationSavedWithoutCollection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKErrorCode@EKErrorNotificationSavedWithoutCollection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notificationSavedWithoutCollection"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKErrorNotificationSavedWithoutCollection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "EKError.Code.notificationSavedWithoutCollection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notificationSavedWithoutCollection"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError": {
      "abstract": [
        {
          "text": "An EventKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "role": "symbol",
      "title": "EKError",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code": {
      "abstract": [
        {
          "text": "Error codes for EventKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmGreaterThanRecurrence": {
      "abstract": [
        {
          "text": "The alarm interval is greater than the recurrence interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alarmGreaterThanRecurrence"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmGreaterThanRecurrence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorAlarmGreaterThanRecurrence"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.alarmGreaterThanRecurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/alarmgreaterthanrecurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarHasNoSource": {
      "abstract": [
        {
          "text": "You can’t save the calendar without setting a source first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarHasNoSource"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarHasNoSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorCalendarHasNoSource"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.calendarHasNoSource",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/calendarhasnosource"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarReadOnly": {
      "abstract": [
        {
          "text": "The calendar is read-only and you can’t add events to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarReadOnly"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarReadOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorCalendarReadOnly"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.calendarReadOnly",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/calendarreadonly"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/datesInverted": {
      "abstract": [
        {
          "text": "The event’s end date occurs before its start date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datesInverted"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/datesInverted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorDatesInverted"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.datesInverted",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/datesinverted"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/durationGreaterThanRecurrence": {
      "abstract": [
        {
          "text": "The duration of an event is greater than its recurrence interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationGreaterThanRecurrence"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/durationGreaterThanRecurrence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorDurationGreaterThanRecurrence"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.durationGreaterThanRecurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/durationgreaterthanrecurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventNotMutable": {
      "abstract": [
        {
          "text": "The event isn’t mutable and you can’t save or delete it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventNotMutable"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventNotMutable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorEventNotMutable"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.eventNotMutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/eventnotmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/internalFailure": {
      "abstract": [
        {
          "text": "An internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalFailure"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/internalFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorInternalFailure"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.internalFailure",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/internalfailure"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidSpan": {
      "abstract": [
        {
          "text": "The system encountered an invalid span during a save or deletion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSpan"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidSpan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorInvalidSpan"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.invalidSpan",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/invalidspan"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invitesCannotBeMoved": {
      "abstract": [
        {
          "text": "You can’t move the event because it’s an invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invitesCannotBeMoved"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invitesCannotBeMoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorInvitesCannotBeMoved"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.invitesCannotBeMoved",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/invitescannotbemoved"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noCalendar": {
      "abstract": [
        {
          "text": "The event isn’t associated with a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCalendar"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noCalendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNoCalendar"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.noCalendar",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/nocalendar"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noEndDate": {
      "abstract": [
        {
          "text": "The event has no end date set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noEndDate"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noEndDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNoEndDate"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.noEndDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/noenddate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noStartDate": {
      "abstract": [
        {
          "text": "The event has no start date set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noStartDate"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNoStartDate"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.noStartDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/nostartdate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationSavedWithoutCollection": {
      "abstract": [
        {
          "text": "The notification can’t save because you haven’t added it to a notification collection and saved the collection first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationSavedWithoutCollection"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/notificationSavedWithoutCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorNotificationSavedWithoutCollection"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.notificationSavedWithoutCollection",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/notificationsavedwithoutcollection"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/objectBelongsToDifferentStore": {
      "abstract": [
        {
          "text": "The object belongs to a different calendar store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectBelongsToDifferentStore"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/objectBelongsToDifferentStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorObjectBelongsToDifferentStore"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.objectBelongsToDifferentStore",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/objectbelongstodifferentstore"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateCollidesWithOtherOccurrence": {
      "abstract": [
        {
          "text": "The event’s start date collides with another occurrence of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDateCollidesWithOtherOccurrence"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateCollidesWithOtherOccurrence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorStartDateCollidesWithOtherOccurrence"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.startDateCollidesWithOtherOccurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/startdatecollideswithotheroccurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateTooFarInFuture": {
      "abstract": [
        {
          "text": "The start date is further into the future than the calendar can display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDateTooFarInFuture"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateTooFarInFuture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorStartDateTooFarInFuture"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code.startDateTooFarInFuture",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code/startdatetoofarinfuture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventNotMutable",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noCalendar",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noStartDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noEndDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/datesInverted",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/internalFailure",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarReadOnly",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/durationGreaterThanRecurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmGreaterThanRecurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateTooFarInFuture",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateCollidesWithOtherOccurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/objectBelongsToDifferentStore",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invitesCannotBeMoved",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidSpan",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarHasNoSource"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKErrorNotificationSavedWithoutCollection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNotificationSavedWithoutCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/eventNotMutable",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noCalendar",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noStartDate",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/noEndDate",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/datesInverted",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/internalFailure",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarReadOnly",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/durationGreaterThanRecurrence",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/alarmGreaterThanRecurrence",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateTooFarInFuture",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/startDateCollidesWithOtherOccurrence",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/objectBelongsToDifferentStore",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invitesCannotBeMoved",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/invalidSpan",
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code/calendarHasNoSource"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EKErrorNotificationSavedWithoutCollection"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1alarmGreaterThanRecurrence/title",
          "value": "EKErrorAlarmGreaterThanRecurrence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1alarmGreaterThanRecurrence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorAlarmGreaterThanRecurrence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noEndDate/title",
          "value": "EKErrorNoEndDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noEndDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNoEndDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/title",
          "value": "EKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarReadOnly/title",
          "value": "EKErrorCalendarReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarReadOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCalendarReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1internalFailure/title",
          "value": "EKErrorInternalFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1internalFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorInternalFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1datesInverted/title",
          "value": "EKErrorDatesInverted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1datesInverted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorDatesInverted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1startDateCollidesWithOtherOccurrence/title",
          "value": "EKErrorStartDateCollidesWithOtherOccurrence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1startDateCollidesWithOtherOccurrence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorStartDateCollidesWithOtherOccurrence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noStartDate/title",
          "value": "EKErrorNoStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNoStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1startDateTooFarInFuture/title",
          "value": "EKErrorStartDateTooFarInFuture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1startDateTooFarInFuture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorStartDateTooFarInFuture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1notificationSavedWithoutCollection/title",
          "value": "EKErrorNotificationSavedWithoutCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1notificationSavedWithoutCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNotificationSavedWithoutCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1objectBelongsToDifferentStore/title",
          "value": "EKErrorObjectBelongsToDifferentStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1objectBelongsToDifferentStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorObjectBelongsToDifferentStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarHasNoSource/title",
          "value": "EKErrorCalendarHasNoSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1calendarHasNoSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCalendarHasNoSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1durationGreaterThanRecurrence/title",
          "value": "EKErrorDurationGreaterThanRecurrence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1durationGreaterThanRecurrence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorDurationGreaterThanRecurrence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1eventNotMutable/title",
          "value": "EKErrorEventNotMutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1eventNotMutable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorEventNotMutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noCalendar/title",
          "value": "EKErrorNoCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1noCalendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorNoCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invalidSpan/title",
          "value": "EKErrorInvalidSpan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invalidSpan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorInvalidSpan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invitesCannotBeMoved/title",
          "value": "EKErrorInvitesCannotBeMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code~1invitesCannotBeMoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorInvitesCannotBeMoved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekerror/code/notificationsavedwithoutcollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekerror/code/notificationsavedwithoutcollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
