{
  "abstract": [
    {
      "text": "The layout fragment measurements are available without text line fragments.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/calculatedUsageBounds"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextLayoutFragmentState@NSTextLayoutFragmentStateCalculatedUsageBounds",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "calculatedUsageBounds"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutFragmentStateCalculatedUsageBounds"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTextLayoutFragment.State.calculatedUsageBounds"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "calculatedUsageBounds"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment": {
      "abstract": [
        {
          "text": "A class that represents the layout fragment typically corresponding to a rendering surface, such as a layer or view subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragment"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutFragment",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum": {
      "abstract": [
        {
          "text": "Values that describe the possible layout states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutFragment.State",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/state-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/calculatedUsageBounds": {
      "abstract": [
        {
          "text": "The layout fragment measurements are available without text line fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculatedUsageBounds"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/calculatedUsageBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragmentStateCalculatedUsageBounds"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutFragment.State.calculatedUsageBounds",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/state-swift.enum/calculatedusagebounds"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/estimatedUsageBounds": {
      "abstract": [
        {
          "text": "The text layout manager hasn’t performed a full layout yet for the region covered by this layout fragment and is returning an estimated bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "estimatedUsageBounds"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/estimatedUsageBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragmentStateEstimatedUsageBounds"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutFragment.State.estimatedUsageBounds",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/state-swift.enum/estimatedusagebounds"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/layoutAvailable": {
      "abstract": [
        {
          "text": "Measurements for the text line fragments and layout fragment are available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAvailable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/layoutAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragmentStateLayoutAvailable"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutFragment.State.layoutAvailable",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/state-swift.enum/layoutavailable"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/none": {
      "abstract": [
        {
          "text": "No layout information is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragmentStateNone"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutFragment.State.none",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/state-swift.enum/none"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants-that-describe-layout-bounds",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/estimatedUsageBounds",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/layoutAvailable",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/none"
      ],
      "title": "Constants that describe layout bounds"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextLayoutFragmentStateCalculatedUsageBounds"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentStateCalculatedUsageBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants-that-describe-layout-bounds",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/estimatedUsageBounds",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/layoutAvailable",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/State-swift.enum/none"
              ],
              "title": "Constants that describe layout bounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTextLayoutFragmentStateCalculatedUsageBounds"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum~1estimatedUsageBounds/title",
          "value": "NSTextLayoutFragmentStateEstimatedUsageBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum~1estimatedUsageBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentStateEstimatedUsageBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum~1layoutAvailable/title",
          "value": "NSTextLayoutFragmentStateLayoutAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum~1layoutAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentStateLayoutAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum~1none/title",
          "value": "NSTextLayoutFragmentStateNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentStateNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum~1calculatedUsageBounds/title",
          "value": "NSTextLayoutFragmentStateCalculatedUsageBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum~1calculatedUsageBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentStateCalculatedUsageBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum/title",
          "value": "NSTextLayoutFragmentState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment/title",
          "value": "NSTextLayoutFragment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextlayoutfragment/state-swift.enum/calculatedusagebounds"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextlayoutfragment/state-swift.enum/calculatedusagebounds"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
