{"variants":[{"paths":["/documentation/uikit/uiviewcontrolleranimatedtransitioning/interruptibleanimator(using:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiviewcontrolleranimatedtransitioning/interruptibleanimator(using:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning"]]},"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interruptibleAnimator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"UIViewImplicitlyAnimating","preciseIdentifier":"c:objc(pl)UIViewImplicitlyAnimating","kind":"typeIdentifier"}],"platforms":[{"introducedAt":"10.0","name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"10.0","name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"13.1","name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"10.0","name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false,"unavailable":false}],"navigatorTitle":[{"text":"interruptibleAnimatorForTransition:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"UIKit"}],"externalID":"c:objc(pl)UIViewControllerAnimatedTransitioning(im)interruptibleAnimatorForTransition:","roleHeading":"Instance Method","title":"interruptibleAnimator(using:)"},"abstract":[{"type":"text","text":"Returns the interruptible animator to use during the transition."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning/interruptibleAnimator(using:)"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interruptibleAnimator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"transitionContext","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"UIViewControllerContextTransitioning","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"text":") -> any ","kind":"text"},{"text":"UIViewImplicitlyAnimating","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating","preciseIdentifier":"c:objc(pl)UIViewImplicitlyAnimating"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"transitionContext","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context object containing information to use during the transition."}]}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An animator object that supports the modification of its running animations."}]}],"kind":"content"},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Implement this method when you want to perform your transitions using an interruptible animator object, such as a ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator","isActive":true,"type":"reference"},{"text":" object. You must return the same animator object for the duration of the transition.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator":{"role":"symbol","abstract":[{"type":"text","text":"A class that animates changes to views and allows the dynamic modification of those animations."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewPropertyAnimator"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator","title":"UIViewPropertyAnimator","navigatorTitle":[{"text":"UIViewPropertyAnimator","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uiviewpropertyanimator"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning","kind":"symbol","type":"topic","title":"UIViewControllerContextTransitioning","navigatorTitle":[{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"abstract":[{"text":"A set of methods that provide contextual information for transition animations between view controllers.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning","type":"topic","url":"/documentation/uikit/uiviewcontrolleranimatedtransitioning","title":"UIViewControllerAnimatedTransitioning","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIViewControllerAnimatedTransitioning"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewControllerAnimatedTransitioning"}],"abstract":[{"text":"A set of methods for implementing the animations for a custom view controller transition.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning/interruptibleAnimator(using:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interruptibleAnimator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewImplicitlyAnimating","text":"UIViewImplicitlyAnimating","kind":"typeIdentifier"}],"url":"/documentation/uikit/uiviewcontrolleranimatedtransitioning/interruptibleanimator(using:)","navigatorTitle":[{"text":"interruptibleAnimatorForTransition:","kind":"identifier"}],"title":"interruptibleAnimator(using:)","abstract":[{"text":"Returns the interruptible animator to use during the transition.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning/interruptibleAnimator(using:)"},"doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating":{"navigatorTitle":[{"text":"UIViewImplicitlyAnimating","kind":"identifier"}],"type":"topic","abstract":[{"text":"An interface for modifying an animation while it’s running.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewImplicitlyAnimating","kind":"identifier"}],"url":"/documentation/uikit/uiviewimplicitlyanimating","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating","title":"UIViewImplicitlyAnimating","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"unavailable":false,"introducedAt":"10.0","name":"iOS","deprecated":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"10.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.1","unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"10.0","unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0","unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"interruptibleAnimatorForTransition:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"interruptibleAnimatorForTransition:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id<UIViewImplicitlyAnimating>","preciseIdentifier":"c:Qoobjc(pl)UIViewImplicitlyAnimating","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"interruptibleAnimatorForTransition:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<UIViewControllerContextTransitioning>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"transitionContext","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context object containing information to use during the transition."}]}],"name":"transitionContext"}],"kind":"parameters"}},{"op":"replace","path":"/primaryContentSections/2","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"An animator object that supports the modification of its running animations.","type":"text"}],"type":"paragraph"}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPropertyAnimator/title","op":"replace","value":"UIViewPropertyAnimator"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPropertyAnimator/fragments","op":"replace","value":[{"text":"UIViewPropertyAnimator","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPropertyAnimator/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIViewPropertyAnimator"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/title","op":"replace","value":"UIViewControllerContextTransitioning"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/fragments","op":"replace","value":[{"text":"UIViewControllerContextTransitioning","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIViewControllerContextTransitioning"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/title","op":"replace","value":"UIViewControllerAnimatedTransitioning"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/fragments","op":"replace","value":[{"kind":"identifier","text":"UIViewControllerAnimatedTransitioning"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIViewControllerAnimatedTransitioning"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning~1interruptibleAnimator(using:)/title","op":"replace","value":"interruptibleAnimatorForTransition:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning~1interruptibleAnimator(using:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"interruptibleAnimatorForTransition:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/title","op":"replace","value":"UIViewImplicitlyAnimating"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/fragments","op":"replace","value":[{"text":"UIViewImplicitlyAnimating","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIViewImplicitlyAnimating"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}