{
  "abstract": [
    {
      "text": "Constants that describe the ability to authorize helper executables or modify daemon applications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.servicemanagement/documentation/ServiceManagement/authorization-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Service Management"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Authorization Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement": {
      "abstract": [
        {
          "text": "Manage startup items, launch agents, and launch daemons from within an app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement",
      "kind": "symbol",
      "role": "collection",
      "title": "Service Management",
      "type": "topic",
      "url": "/documentation/servicemanagement"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMAppService": {
      "abstract": [
        {
          "text": "An object the framework uses to control helper executables that live inside an app’s main bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMAppService"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMAppService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMAppService"
        }
      ],
      "role": "symbol",
      "title": "SMAppService",
      "type": "topic",
      "url": "/documentation/servicemanagement/smappservice"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobBless(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Submits the executable for the given label as a job to ",
          "type": "text"
        },
        {
          "code": "launchd",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMJobBless"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRef",
          "text": "AuthorizationRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobBless(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMJobBless"
        }
      ],
      "role": "symbol",
      "title": "SMJobBless(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/servicemanagement/smjobbless(_:_:_:_:)"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightBlessPrivilegedHelper": {
      "abstract": [
        {
          "text": "The authorization rights key for approving and installing a privileged helper tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMRightBlessPrivilegedHelper"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightBlessPrivilegedHelper",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMRightBlessPrivilegedHelper"
        }
      ],
      "role": "symbol",
      "title": "kSMRightBlessPrivilegedHelper",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmrightblessprivilegedhelper"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightModifySystemDaemons": {
      "abstract": [
        {
          "text": "The authorization rights key for modifying system daemons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMRightModifySystemDaemons"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightModifySystemDaemons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMRightModifySystemDaemons"
        }
      ],
      "role": "symbol",
      "title": "kSMRightModifySystemDaemons",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmrightmodifysystemdaemons"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/property-list-keys": {
      "abstract": [
        {
          "text": "Property list keys that describe the kinds of applications, daemons, and helper executables the framework manages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/property-list-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property List Keys",
      "type": "topic",
      "url": "/documentation/servicemanagement/property-list-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMAppService",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobBless(_:_:_:_:)",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/property-list-keys"
      ],
      "title": "Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightBlessPrivilegedHelper",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightBlessPrivilegedHelper",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightModifySystemDaemons",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightModifySystemDaemons"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightBlessPrivilegedHelper",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightBlessPrivilegedHelper",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightModifySystemDaemons",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMRightModifySystemDaemons"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMAppService",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobBless(_:_:_:_:)",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/property-list-keys"
              ],
              "title": "Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMJobBless(_:_:_:_:)/title",
          "value": "SMJobBless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMJobBless(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMJobBless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMAppService/title",
          "value": "SMAppService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMAppService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMAppService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMAppService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SMAppService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMRightBlessPrivilegedHelper/title",
          "value": "kSMRightBlessPrivilegedHelper"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMRightBlessPrivilegedHelper/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMRightBlessPrivilegedHelper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMRightModifySystemDaemons/title",
          "value": "kSMRightModifySystemDaemons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMRightModifySystemDaemons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMRightModifySystemDaemons"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/servicemanagement/authorization-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/servicemanagement/authorization-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
