{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.servicemanagement/documentation/ServiceManagement/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Service Management"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement": {
      "abstract": [
        {
          "text": "Manage startup items, launch agents, and launch daemons from within an app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement",
      "kind": "symbol",
      "role": "collection",
      "title": "Service Management",
      "type": "topic",
      "url": "/documentation/servicemanagement"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMCopyAllJobDictionaries(_:)": {
      "abstract": [
        {
          "text": "Copies the job description dictionaries for all jobs in the specified domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMCopyAllJobDictionaries"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMCopyAllJobDictionaries(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMCopyAllJobDictionaries"
        }
      ],
      "role": "symbol",
      "title": "SMCopyAllJobDictionaries(_:)",
      "type": "topic",
      "url": "/documentation/servicemanagement/smcopyalljobdictionaries(_:)"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobCopyDictionary(_:_:)": {
      "abstract": [
        {
          "text": "Copies the job description dictionary for the specified job label.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMJobCopyDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobCopyDictionary(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMJobCopyDictionary"
        }
      ],
      "role": "symbol",
      "title": "SMJobCopyDictionary(_:_:)",
      "type": "topic",
      "url": "/documentation/servicemanagement/smjobcopydictionary(_:_:)"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobRemove(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Removes the job with the specified label from the specified domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMJobRemove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobRemove(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMJobRemove"
        }
      ],
      "role": "symbol",
      "title": "SMJobRemove(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/servicemanagement/smjobremove(_:_:_:_:_:)"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobSubmit(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Submits the specified job to the specified domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMJobSubmit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobSubmit(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMJobSubmit"
        }
      ],
      "role": "symbol",
      "title": "SMJobSubmit(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/servicemanagement/smjobsubmit(_:_:_:_:)"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainFramework": {
      "abstract": [
        {
          "text": "A Service Management error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorDomainFramework"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainFramework",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorDomainFramework"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorDomainFramework",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrordomainframework"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainIPC": {
      "abstract": [
        {
          "text": "A Service Management IPC error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorDomainIPC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainIPC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorDomainIPC"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorDomainIPC",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrordomainipc"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainLaunchd": {
      "abstract": [
        {
          "text": "A Service Management ",
          "type": "text"
        },
        {
          "code": "launchd",
          "type": "codeVoice"
        },
        {
          "text": " error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorDomainLaunchd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainLaunchd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorDomainLaunchd"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorDomainLaunchd",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrordomainlaunchd"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/ksminfokeyauthorizedclients": {
      "abstract": [
        {
          "text": "The authorized clients property list key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/ksminfokeyauthorizedclients",
      "kind": "article",
      "role": "article",
      "title": "kSMInfoKeyAuthorizedClients",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksminfokeyauthorizedclients"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/ksminfokeyprivilegedexecutables": {
      "abstract": [
        {
          "text": "The privileged executables property list key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/ksminfokeyprivilegedexecutables",
      "kind": "article",
      "role": "article",
      "title": "kSMInfoKeyPrivilegedExecutables",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksminfokeyprivilegedexecutables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-Constants",
      "identifiers": [
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainFramework",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainIPC",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainLaunchd"
      ],
      "title": "Deprecated Constants"
    },
    {
      "anchor": "Deprecated-Functions",
      "identifiers": [
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMCopyAllJobDictionaries(_:)",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobCopyDictionary(_:_:)",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobRemove(_:_:_:_:_:)",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobSubmit(_:_:_:_:)"
      ],
      "title": "Deprecated Functions"
    },
    {
      "anchor": "Deprecated-Property-List-Keys",
      "identifiers": [
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/ksminfokeyauthorizedclients",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/ksminfokeyprivilegedexecutables"
      ],
      "title": "Deprecated Property List Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-Constants",
              "identifiers": [
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainFramework",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainIPC",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorDomainLaunchd"
              ],
              "title": "Deprecated Constants"
            },
            {
              "anchor": "Deprecated-Functions",
              "identifiers": [
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMCopyAllJobDictionaries(_:)",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobCopyDictionary(_:_:)",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobRemove(_:_:_:_:_:)",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/SMJobSubmit(_:_:_:_:)"
              ],
              "title": "Deprecated Functions"
            },
            {
              "anchor": "Deprecated-Property-List-Keys",
              "identifiers": [
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/ksminfokeyauthorizedclients",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/ksminfokeyprivilegedexecutables"
              ],
              "title": "Deprecated Property List Keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorDomainIPC/title",
          "value": "kSMErrorDomainIPC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorDomainIPC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorDomainIPC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMJobRemove(_:_:_:_:_:)/title",
          "value": "SMJobRemove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMJobRemove(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMJobRemove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorDomainLaunchd/title",
          "value": "kSMErrorDomainLaunchd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorDomainLaunchd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorDomainLaunchd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMCopyAllJobDictionaries(_:)/title",
          "value": "SMCopyAllJobDictionaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMCopyAllJobDictionaries(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMCopyAllJobDictionaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMJobCopyDictionary(_:_:)/title",
          "value": "SMJobCopyDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMJobCopyDictionary(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMJobCopyDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorDomainFramework/title",
          "value": "kSMErrorDomainFramework"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorDomainFramework/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorDomainFramework"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMJobSubmit(_:_:_:_:)/title",
          "value": "SMJobSubmit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1SMJobSubmit(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMJobSubmit"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/servicemanagement/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/servicemanagement/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
