{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobPlistNotFound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kSMErrorInternalFailure@kSMErrorJobPlistNotFound",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSMErrorJobPlistNotFound"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Service Management"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSMErrorJobPlistNotFound"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSMErrorJobPlistNotFound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSMErrorJobPlistNotFound"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement": {
      "abstract": [
        {
          "text": "Manage startup items, launch agents, and launch daemons from within an app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement",
      "kind": "symbol",
      "role": "collection",
      "title": "Service Management",
      "type": "topic",
      "url": "/documentation/servicemanagement"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorAlreadyRegistered": {
      "abstract": [
        {
          "text": "The application is already registered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorAlreadyRegistered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorAlreadyRegistered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorAlreadyRegistered"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorAlreadyRegistered",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerroralreadyregistered"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorAuthorizationFailure": {
      "abstract": [
        {
          "text": "The authorization requested failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorAuthorizationFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorAuthorizationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorAuthorizationFailure"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorAuthorizationFailure",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrorauthorizationfailure"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInternalFailure": {
      "abstract": [
        {
          "text": "An internal failure has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorInternalFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInternalFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorInternalFailure"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorInternalFailure",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrorinternalfailure"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInvalidPlist": {
      "abstract": [
        {
          "text": "The app’s property list is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorInvalidPlist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInvalidPlist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorInvalidPlist"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorInvalidPlist",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrorinvalidplist"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInvalidSignature": {
      "abstract": [
        {
          "text": "The app’s code signature doesn’t meet the requirements to perform the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorInvalidSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInvalidSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorInvalidSignature"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorInvalidSignature",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrorinvalidsignature"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobMustBeEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorJobMustBeEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobMustBeEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorJobMustBeEnabled"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorJobMustBeEnabled",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrorjobmustbeenabled"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobNotFound": {
      "abstract": [
        {
          "text": "The system can’t find the specified job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorJobNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorJobNotFound"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorJobNotFound",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrorjobnotfound"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobPlistNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorJobPlistNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobPlistNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorJobPlistNotFound"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorJobPlistNotFound",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrorjobplistnotfound"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorLaunchDeniedByUser": {
      "abstract": [
        {
          "text": "The user denied the app’s launch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorLaunchDeniedByUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorLaunchDeniedByUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorLaunchDeniedByUser"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorLaunchDeniedByUser",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrorlaunchdeniedbyuser"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorServiceUnavailable": {
      "abstract": [
        {
          "text": "The service necessary to perform this operation is unavailable or is no longer accepting requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorServiceUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorServiceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorServiceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorServiceUnavailable",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrorserviceunavailable"
    },
    "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorToolNotValid": {
      "abstract": [
        {
          "text": "The specified path doesn’t exist or the helper tool at the specified path isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSMErrorToolNotValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorToolNotValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMErrorToolNotValid"
        }
      ],
      "role": "symbol",
      "title": "kSMErrorToolNotValid",
      "type": "topic",
      "url": "/documentation/servicemanagement/ksmerrortoolnotvalid"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorAlreadyRegistered",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorAuthorizationFailure",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInternalFailure",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInvalidPlist",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInvalidSignature",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobMustBeEnabled",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobNotFound",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorLaunchDeniedByUser",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorServiceUnavailable",
        "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorToolNotValid"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSMErrorJobPlistNotFound"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorJobPlistNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorAlreadyRegistered",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorAuthorizationFailure",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInternalFailure",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInvalidPlist",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorInvalidSignature",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobMustBeEnabled",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorJobNotFound",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorLaunchDeniedByUser",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorServiceUnavailable",
                "doc://com.apple.servicemanagement/documentation/ServiceManagement/kSMErrorToolNotValid"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSMErrorJobPlistNotFound"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorServiceUnavailable/title",
          "value": "kSMErrorServiceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorServiceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorServiceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorJobPlistNotFound/title",
          "value": "kSMErrorJobPlistNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorJobPlistNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorJobPlistNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorJobMustBeEnabled/title",
          "value": "kSMErrorJobMustBeEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorJobMustBeEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorJobMustBeEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorAuthorizationFailure/title",
          "value": "kSMErrorAuthorizationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorAuthorizationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorAuthorizationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorInvalidPlist/title",
          "value": "kSMErrorInvalidPlist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorInvalidPlist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorInvalidPlist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorAlreadyRegistered/title",
          "value": "kSMErrorAlreadyRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorAlreadyRegistered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorAlreadyRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorLaunchDeniedByUser/title",
          "value": "kSMErrorLaunchDeniedByUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorLaunchDeniedByUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorLaunchDeniedByUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorInvalidSignature/title",
          "value": "kSMErrorInvalidSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorInvalidSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorInvalidSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorJobNotFound/title",
          "value": "kSMErrorJobNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorJobNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorJobNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorInternalFailure/title",
          "value": "kSMErrorInternalFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorInternalFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorInternalFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorToolNotValid/title",
          "value": "kSMErrorToolNotValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.servicemanagement~1documentation~1ServiceManagement~1kSMErrorToolNotValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMErrorToolNotValid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/servicemanagement/ksmerrorjobplistnotfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/servicemanagement/ksmerrorjobplistnotfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
