{
  "abstract": [
    {
      "text": "The system bookmarks button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/bookmarks"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIBarButtonSystemItem@UIBarButtonSystemItemBookmarks",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bookmarks"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIBarButtonSystemItemBookmarks"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIBarButtonItem.SystemItem.bookmarks"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bookmarks"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem": {
      "abstract": [
        {
          "text": "A specialized button for placement on a toolbar, navigation bar, or shortcuts bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem": {
      "abstract": [
        {
          "text": "Constants that define system-supplied images for bar button items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/action": {
      "abstract": [
        {
          "text": "The system action button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "action"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemAction"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.action",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/action"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/add": {
      "abstract": [
        {
          "text": "The system plus button containing an icon of a plus sign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemAdd"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.add",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/add"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/bookmarks": {
      "abstract": [
        {
          "text": "The system bookmarks button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bookmarks"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/bookmarks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemBookmarks"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.bookmarks",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/bookmarks"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/camera": {
      "abstract": [
        {
          "text": "The system camera button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "camera"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/camera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemCamera"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.camera",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/camera"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/cancel": {
      "abstract": [
        {
          "text": "The system Cancel button, localized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/cancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemCancel"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.cancel",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/cancel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/compose": {
      "abstract": [
        {
          "text": "The system compose button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compose"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/compose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemCompose"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.compose",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/compose"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/done": {
      "abstract": [
        {
          "text": "The system Done button, localized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "done"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/done",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemDone"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.done",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/done"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/edit": {
      "abstract": [
        {
          "text": "The system Edit button, localized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edit"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/edit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemEdit"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.edit",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/edit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fixedSpace": {
      "abstract": [
        {
          "text": "Blank space to add between other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixedSpace"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fixedSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemFixedSpace"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.fixedSpace",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/fixedspace"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/flexibleSpace": {
      "abstract": [
        {
          "text": "Blank space to add between other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexibleSpace"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/flexibleSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemFlexibleSpace"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.flexibleSpace",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/flexiblespace"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/organize": {
      "abstract": [
        {
          "text": "The system organize button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "organize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/organize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemOrganize"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.organize",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/organize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/refresh": {
      "abstract": [
        {
          "text": "The system refresh button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refresh"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/refresh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemRefresh"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.refresh",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/refresh"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/reply": {
      "abstract": [
        {
          "text": "The system reply button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reply"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/reply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemReply"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.reply",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/reply"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/save": {
      "abstract": [
        {
          "text": "The system Save button, localized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/save",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemSave"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.save",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/save"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/search": {
      "abstract": [
        {
          "text": "The system search button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemSearch"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.search",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/search"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/stop": {
      "abstract": [
        {
          "text": "The system stop button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/stop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemStop"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.stop",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/stop"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/done",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/cancel",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/edit",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/save",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/add",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/flexibleSpace",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fixedSpace",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/compose",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/reply",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/action",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/organize",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/search",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/refresh",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/stop",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/camera"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIBarButtonSystemItemBookmarks"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemBookmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/done",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/cancel",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/edit",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/save",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/add",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/flexibleSpace",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fixedSpace",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/compose",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/reply",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/action",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/organize",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/search",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/refresh",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/stop",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/camera"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIBarButtonSystemItemBookmarks"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1stop/title",
          "value": "UIBarButtonSystemItemStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1stop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1add/title",
          "value": "UIBarButtonSystemItemAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/title",
          "value": "UIBarButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1bookmarks/title",
          "value": "UIBarButtonSystemItemBookmarks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1bookmarks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemBookmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1refresh/title",
          "value": "UIBarButtonSystemItemRefresh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1refresh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemRefresh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1camera/title",
          "value": "UIBarButtonSystemItemCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1camera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1organize/title",
          "value": "UIBarButtonSystemItemOrganize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1organize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemOrganize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1fixedSpace/title",
          "value": "UIBarButtonSystemItemFixedSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1fixedSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemFixedSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem/title",
          "value": "UIBarButtonSystemItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1done/title",
          "value": "UIBarButtonSystemItemDone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1done/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemDone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1search/title",
          "value": "UIBarButtonSystemItemSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1action/title",
          "value": "UIBarButtonSystemItemAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1cancel/title",
          "value": "UIBarButtonSystemItemCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1cancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1reply/title",
          "value": "UIBarButtonSystemItemReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1reply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1save/title",
          "value": "UIBarButtonSystemItemSave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1save/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemSave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1compose/title",
          "value": "UIBarButtonSystemItemCompose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1compose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemCompose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1edit/title",
          "value": "UIBarButtonSystemItemEdit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1edit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemEdit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1flexibleSpace/title",
          "value": "UIBarButtonSystemItemFlexibleSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1flexibleSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemFlexibleSpace"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibarbuttonitem/systemitem/bookmarks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uibarbuttonitem/systemitem/bookmarks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
