{
  "abstract": [
    {
      "text": "The group of error codes that pass from the attribution response to the completion handler block.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This has been replaced by functionality in AdServices.framework's AAAttribution class.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iad/documentation/iAd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC13ADClientErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ADClientError"
      }
    ],
    "modules": [
      {
        "name": "iAd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ADClientError"
      }
    ],
    "platforms": [],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "ADClientError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ADClientError"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.iad/documentation/iAd/iad-changelog"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.iad/documentation/iAd/ADClient/requestAttributionDetails(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, error codes are passed from the attribution response to the completion handler block.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iad/documentation/iAd": {
      "abstract": [
        {
          "text": "The Apple Search Ads iAd Attribution API is a legacy framework for attributing app data that originates from Apple Search Ads campaigns on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd",
      "kind": "symbol",
      "role": "collection",
      "title": "iAd",
      "type": "topic",
      "url": "/documentation/iad"
    },
    "doc://com.apple.iad/documentation/iAd/ADClient/requestAttributionDetails(_:)": {
      "abstract": [
        {
          "text": "Gets an attribution response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAttributionDetails"
        },
        {
          "kind": "text",
          "text": "((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClient/requestAttributionDetails(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAttributionDetailsWithBlock:"
        }
      ],
      "role": "symbol",
      "title": "requestAttributionDetails(_:)",
      "type": "topic",
      "url": "/documentation/iad/adclient/requestattributiondetails(_:)"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct": {
      "abstract": [
        {
          "text": "The group of error codes that pass from the attribution response to the completion handler block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "role": "symbol",
      "title": "ADClientError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The error codes that pass from the attribution response to the completion handler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/corruptResponse": {
      "abstract": [
        {
          "text": "The response received from the attribution server was corrupt.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "corruptResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/corruptResponse",
      "kind": "symbol",
      "role": "symbol",
      "title": "corruptResponse",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/corruptresponse"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/errorDomain": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/errordomain"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/limitAdTracking": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limitAdTracking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/limitAdTracking",
      "kind": "symbol",
      "role": "symbol",
      "title": "limitAdTracking",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/limitadtracking"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/missingData": {
      "abstract": [
        {
          "text": "The downloaded app received a payload lacking enough data to perform an attribution check.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/missingData",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingData",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/missingdata"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestClientError": {
      "abstract": [
        {
          "text": "The response received from the attribution server had an HTTP 4xx status code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestClientError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestClientError",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestClientError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/requestclienterror"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestNetworkError": {
      "abstract": [
        {
          "text": "The communication with the attribution server had a network error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestNetworkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestNetworkError",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestNetworkError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/requestnetworkerror"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestServerError": {
      "abstract": [
        {
          "text": "The response received from the attribution server had an HTTP 5xx status code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestServerError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestServerError",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestServerError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/requestservererror"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/trackingRestrictedOrDenied": {
      "abstract": [
        {
          "text": "The user is restricted or has denied tracking for the calling application.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingRestrictedOrDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/trackingRestrictedOrDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackingRestrictedOrDenied",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/trackingrestrictedordenied"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unknown": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/unknown"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unsupportedPlatform": {
      "abstract": [
        {
          "text": "The attribution API was called on an unsupported platform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedPlatform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unsupportedPlatform",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedPlatform",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/unsupportedplatform"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientErrorDomain": {
      "abstract": [
        {
          "text": "The error domain that passes to the completion handler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ADClientErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ADClientErrorDomain",
      "type": "topic",
      "url": "/documentation/iad/adclienterrordomain"
    },
    "doc://com.apple.iad/documentation/iAd/iad-changelog": {
      "abstract": [
        {
          "text": "Learn what’s new in the Apple Search Ads iAd Attribution API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/iad-changelog",
      "kind": "article",
      "role": "article",
      "title": "iAd Changelog",
      "type": "topic",
      "url": "/documentation/iad/iad-changelog"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Attribution-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/ADClientErrorDomain",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code"
      ],
      "title": "Attribution Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/corruptResponse",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestClientError",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestNetworkError",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/requestServerError",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/trackingRestrictedOrDenied",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/missingData",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unsupportedPlatform",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/limitAdTracking",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unknown",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Error-Characteristics",
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/ADClientErrorDomain"
      ],
      "title": "Error Characteristics"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient~1requestAttributionDetails(_:)/title",
          "value": "requestAttributionDetailsWithBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient~1requestAttributionDetails(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestAttributionDetailsWithBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientErrorDomain/title",
          "value": "ADClientErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/title",
          "value": "ADClientError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iad/adclienterror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
