{
  "abstract": [
    {
      "text": "Reference symbols from the legacy iAd framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iad/documentation/iAd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iad/documentation/iAd/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "iAd"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "iAd was a legacy framework that integrates with ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/apple_search_ads",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " campaigns. iAd technology is deprecated in macOS and iOS. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AdServices",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework for current attribution integration with the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/apple_search_ads",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " Campaign Management API.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AdServices": {
      "abstract": [
        {
          "text": "Attribute app-download campaigns that originate from the App Store, Apple News, or Stocks on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdServices",
      "kind": "symbol",
      "role": "collection",
      "title": "AdServices",
      "type": "topic",
      "url": "/documentation/AdServices"
    },
    "doc://com.apple.documentation/documentation/apple_search_ads": {
      "abstract": [
        {
          "text": "Drive app discovery by creating and managing campaigns with the Apple Search Ads Campaign Management API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple_search_ads",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Search Ads",
      "type": "topic",
      "url": "/documentation/apple_search_ads"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iad/documentation/iAd": {
      "abstract": [
        {
          "text": "The Apple Search Ads iAd Attribution API is a legacy framework for attributing app data that originates from Apple Search Ads campaigns on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd",
      "kind": "symbol",
      "role": "collection",
      "title": "iAd",
      "type": "topic",
      "url": "/documentation/iad"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-c.enum/ADClientErrorLimitAdTracking": {
      "abstract": [
        {
          "text": "Limited ad tracking is in an enabled state for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADClientErrorLimitAdTracking"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-c.enum/ADClientErrorLimitAdTracking",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADClientErrorLimitAdTracking",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-c.enum/adclienterrorlimitadtracking"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/limitAdTracking": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limitAdTracking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/limitAdTracking",
      "kind": "symbol",
      "role": "symbol",
      "title": "limitAdTracking",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/limitadtracking"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "The response from the attribution server has an unknown error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code.unknown",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/unknown"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unknown": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/limitAdTracking",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/unknown",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unknown"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.iad/documentation/iAd/ADClientError-c.enum/ADClientErrorLimitAdTracking",
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1unknown/title",
          "value": "ADClientErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iad/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iad/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
