{
  "abstract": [
    {
      "text": "Learn what’s new in the Apple Search Ads iAd Attribution API.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iad/documentation/iAd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iad/documentation/iAd/iad-changelog"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "iAd"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "iAd Changelog"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Release date",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Release details",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "February 2023",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "After February 7, 2023, all requests made to the Apple Search Ads iAd Attribution API will return with a value of ",
                      "type": "text"
                    },
                    {
                      "code": "\"iad-attribution\"",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "=",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "false",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", or errors.  See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.iad/documentation/iAd/ADClient/requestAttributionDetails(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "June 2020",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Updated error responses. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " enumerations.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "October 2019",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Added ",
                      "type": "text"
                    },
                    {
                      "code": "iad-keyword-id",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to the attribution dictionary. See Retrieve the Attribution Dictionary in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution#Retrieve-the-Attribution-Dictionary",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The Apple Search Ads iAd Attribution API is deprecated. Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AdServices",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework for current attribution integration with the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/apple_search_ads",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " Campaign Management API for devices using iOS 14.3 and later. Attribution isn’t available for downloads and redownloads from devices using iOS 14.2 or earlier.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AdServices": {
      "abstract": [
        {
          "text": "Attribute app-download campaigns that originate from the App Store, Apple News, or Stocks on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdServices",
      "kind": "symbol",
      "role": "collection",
      "title": "AdServices",
      "type": "topic",
      "url": "/documentation/AdServices"
    },
    "doc://com.apple.documentation/documentation/apple_search_ads": {
      "abstract": [
        {
          "text": "Drive app discovery by creating and managing campaigns with the Apple Search Ads Campaign Management API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple_search_ads",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Search Ads",
      "type": "topic",
      "url": "/documentation/apple_search_ads"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iad/documentation/iAd": {
      "abstract": [
        {
          "text": "The Apple Search Ads iAd Attribution API is a legacy framework for attributing app data that originates from Apple Search Ads campaigns on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd",
      "kind": "symbol",
      "role": "collection",
      "title": "iAd",
      "type": "topic",
      "url": "/documentation/iad"
    },
    "doc://com.apple.iad/documentation/iAd/ADClient": {
      "abstract": [
        {
          "text": "The parent class you use to request an attribution response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ADClient"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClient"
        }
      ],
      "role": "symbol",
      "title": "ADClient",
      "type": "topic",
      "url": "/documentation/iad/adclient"
    },
    "doc://com.apple.iad/documentation/iAd/ADClient/requestAttributionDetails(_:)": {
      "abstract": [
        {
          "text": "Gets an attribution response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAttributionDetails"
        },
        {
          "kind": "text",
          "text": "((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClient/requestAttributionDetails(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAttributionDetailsWithBlock:"
        }
      ],
      "role": "symbol",
      "title": "requestAttributionDetails(_:)",
      "type": "topic",
      "url": "/documentation/iad/adclient/requestattributiondetails(_:)"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct": {
      "abstract": [
        {
          "text": "The group of error codes that pass from the attribution response to the completion handler block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "role": "symbol",
      "title": "ADClientError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct"
    },
    "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution": {
      "abstract": [
        {
          "text": "Retrieve the attribution dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution",
      "kind": "article",
      "role": "article",
      "title": "Setting Up Apple Search Ads Attribution",
      "type": "topic",
      "url": "/documentation/iad/setting-up-apple-search-ads-attribution"
    },
    "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution#Retrieve-the-Attribution-Dictionary": {
      "abstract": [],
      "identifier": "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution#Retrieve-the-Attribution-Dictionary",
      "kind": "section",
      "title": "Retrieve the Attribution Dictionary",
      "type": "topic",
      "url": "/documentation/iad/setting-up-apple-search-ads-attribution#Retrieve-the-Attribution-Dictionary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution",
        "doc://com.apple.iad/documentation/iAd/ADClient"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution",
                "doc://com.apple.iad/documentation/iAd/ADClient"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient~1requestAttributionDetails(_:)/title",
          "value": "requestAttributionDetailsWithBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient~1requestAttributionDetails(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestAttributionDetailsWithBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient/title",
          "value": "ADClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClient"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iad/iad-changelog"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iad/iad-changelog"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
