{
  "abstract": [
    {
      "text": "Does a soft reset of the CGL library if true.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption/NSOpenGLGOResetLibrary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSOpenGLGlobalOption@NSOpenGLGOResetLibrary",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSOpenGLGOResetLibrary"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSOpenGLGOResetLibrary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.4",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSOpenGLGOResetLibrary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSOpenGLGOResetLibrary"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption": {
      "abstract": [
        {
          "text": "Constants that specify OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLGlobalOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGlobalOption"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLGlobalOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglglobaloption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption/NSOpenGLGOResetLibrary": {
      "abstract": [
        {
          "text": "Does a soft reset of the CGL library if true.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGOResetLibrary"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption/NSOpenGLGOResetLibrary",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGOResetLibrary",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglglobaloption/nsopenglgoresetlibrary"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLGlobalOption/title",
          "value": "NSOpenGLGlobalOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLGlobalOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLGlobalOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLGlobalOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLGlobalOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsopenglglobaloption/nsopenglgoresetlibrary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
