{
  "abstract": [
    {
      "text": "The current video frame image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousCIImageFilteringRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousCIImageFilteringRequest/sourceImage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAsynchronousCIImageFilteringRequest(py)sourceImage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sourceImage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CIImage",
        "text": "CIImage"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sourceImage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "sourceImage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sourceImage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CIImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CIImage",
              "text": "CIImage"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To apply a Core Image filter to this image, assign it to the ",
              "type": "text"
            },
            {
              "code": "inputImage",
              "type": "codeVoice"
            },
            {
              "text": " parameter of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/cifilter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, or use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/ciimage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " convenience method such as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/ciimage/1437589-applyingfilter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The pixel format for this image is the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/ciformat/1438064-bgra8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " format (of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_32BGRA",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type). Unlike when processing video with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousVideoCompositionRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousVideoCompositionRequest/renderContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/renderTransform",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is already applied to this image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousCIImageFilteringRequest": {
      "abstract": [
        {
          "text": "An object that supports using Core Image filters to process an individual video frame in a video composition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsynchronousCIImageFilteringRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousCIImageFilteringRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsynchronousCIImageFilteringRequest"
        }
      ],
      "role": "symbol",
      "title": "AVAsynchronousCIImageFilteringRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avasynchronousciimagefilteringrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousCIImageFilteringRequest/sourceImage": {
      "abstract": [
        {
          "text": "The current video frame image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIImage",
          "text": "CIImage"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousCIImageFilteringRequest/sourceImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceImage"
        }
      ],
      "role": "symbol",
      "title": "sourceImage",
      "type": "topic",
      "url": "/documentation/avfoundation/avasynchronousciimagefilteringrequest/sourceimage"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousVideoCompositionRequest": {
      "abstract": [
        {
          "text": "An object that contains information a video compositor needs to render an output pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsynchronousVideoCompositionRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousVideoCompositionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsynchronousVideoCompositionRequest"
        }
      ],
      "role": "symbol",
      "title": "AVAsynchronousVideoCompositionRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avasynchronousvideocompositionrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousVideoCompositionRequest/renderContext": {
      "abstract": [
        {
          "text": "The rendering context of the video composition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVVideoCompositionRenderContext",
          "text": "AVVideoCompositionRenderContext"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousVideoCompositionRequest/renderContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renderContext"
        }
      ],
      "role": "symbol",
      "title": "renderContext",
      "type": "topic",
      "url": "/documentation/avfoundation/avasynchronousvideocompositionrequest/rendercontext"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/renderTransform": {
      "abstract": [
        {
          "text": "A transform to apply to the source image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/renderTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renderTransform"
        }
      ],
      "role": "symbol",
      "title": "renderTransform",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocompositionrendercontext/rendertransform"
    },
    "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_32BGRA": {
      "abstract": [
        {
          "text": "32-bit BGRA.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_32BGRA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_32BGRA",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCVPixelFormatType_32BGRA",
      "type": "topic",
      "url": "/documentation/CoreVideo/kCVPixelFormatType_32BGRA"
    },
    "doc://com.apple.documentation/documentation/coreimage/cifilter": {
      "abstract": [
        {
          "text": "An image processor that produces an image by manipulating one or more input images or by generating new image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CIFilter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/cifilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "CIFilter",
      "type": "topic",
      "url": "/documentation/coreimage/cifilter"
    },
    "doc://com.apple.documentation/documentation/coreimage/ciformat/1438064-bgra8": {
      "abstract": [
        {
          "text": "A 32-bit-per-pixel, fixed-point pixel format in which the blue, green, and red color components precede the alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "BGRA8"
        },
        {
          "kind": "text",
          "text": ": CIFormat"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/ciformat/1438064-bgra8",
      "kind": "symbol",
      "role": "symbol",
      "title": "BGRA8",
      "type": "topic",
      "url": "/documentation/coreimage/ciformat/1438064-bgra8"
    },
    "doc://com.apple.documentation/documentation/coreimage/ciimage": {
      "abstract": [
        {
          "text": "A representation of an image to be processed or produced by Core Image filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CIImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/ciimage",
      "kind": "symbol",
      "role": "symbol",
      "title": "CIImage",
      "type": "topic",
      "url": "/documentation/coreimage/ciimage"
    },
    "doc://com.apple.documentation/documentation/coreimage/ciimage/1437589-applyingfilter": {
      "abstract": [
        {
          "text": "Returns a new image created by applying a filter to the original image with the specified name and parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "applyingFilter"
        },
        {
          "kind": "text",
          "text": "(String, "
        },
        {
          "kind": "identifier",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": [String : Any]) -> CIImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/ciimage/1437589-applyingfilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "applyingFilter(_:parameters:)",
      "type": "topic",
      "url": "/documentation/coreimage/ciimage/1437589-applyingfilter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)CIImage": {
      "abstract": [
        {
          "text": "A representation of an image to be processed or produced by Core Image filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CIImage"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CIImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "CIImage",
      "type": "topic",
      "url": "/documentation/coreimage/ciimage"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sourceImage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousCIImageFilteringRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CIImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CIImage",
                    "text": "CIImage"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "sourceImage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousVideoCompositionRequest/title",
          "value": "AVAsynchronousVideoCompositionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousVideoCompositionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousVideoCompositionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousVideoCompositionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousVideoCompositionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousCIImageFilteringRequest~1sourceImage/title",
          "value": "sourceImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousCIImageFilteringRequest~1sourceImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreVideo~1kCVPixelFormatType_32BGRA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_32BGRA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousVideoCompositionRequest~1renderContext/title",
          "value": "renderContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousVideoCompositionRequest~1renderContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "renderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coreimage~1ciformat~11438064-bgra8/title",
          "value": "kCIFormatBGRA8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coreimage~1ciimage~11437589-applyingfilter/title",
          "value": "imageByApplyingFilter:withInputParameters:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousCIImageFilteringRequest/title",
          "value": "AVAsynchronousCIImageFilteringRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousCIImageFilteringRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousCIImageFilteringRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousCIImageFilteringRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousCIImageFilteringRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCompositionRenderContext~1renderTransform/title",
          "value": "renderTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCompositionRenderContext~1renderTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "renderTransform"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avasynchronousciimagefilteringrequest/sourceimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avasynchronousciimagefilteringrequest/sourceimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
