{
  "abstract": [
    {
      "text": "The option to execute the forward pass for inference only.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/forwardForInference"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCExecutionOptions@MLCExecutionOptionsForwardForInference",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "forwardForInference"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MLCExecutionOptions",
        "text": "MLCExecutionOptions"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCExecutionOptionsForwardForInference"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "forwardForInference"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "forwardForInference"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MLCExecutionOptions",
              "text": "MLCExecutionOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you include this option and execute a training graph using one of the ",
              "type": "text"
            },
            {
              "code": "execute",
              "type": "codeVoice"
            },
            {
              "text": " methods, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/execute(inputsData:lossLabelsData:lossLabelWeightsData:batchSize:options:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the framework only executes the forward pass of the training graph, and it executes that forward pass for inference only.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you include this option and execute a training graph using one of the ",
              "type": "text"
            },
            {
              "code": "executeForward",
              "type": "codeVoice"
            },
            {
              "text": " methods, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/executeForward(batchSize:options:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the framework executes the forward pass for inference only.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions": {
      "abstract": [
        {
          "text": "A bitmask that specifies the options you use when executing a graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCExecutionOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCExecutionOptions"
        }
      ],
      "role": "symbol",
      "title": "MLCExecutionOptions",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcexecutionoptions"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/forwardForInference": {
      "abstract": [
        {
          "text": "The option to execute the forward pass for inference only.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forwardForInference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCExecutionOptions",
          "text": "MLCExecutionOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/forwardForInference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCExecutionOptionsForwardForInference"
        }
      ],
      "role": "symbol",
      "title": "forwardForInference",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcexecutionoptions/forwardforinference"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an execution option with the specified raw value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcexecutionoptions/init(rawvalue:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/perLayerProfiling": {
      "abstract": [
        {
          "text": "The option to enable additional per-layer profiling information using signposts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perLayerProfiling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCExecutionOptions",
          "text": "MLCExecutionOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/perLayerProfiling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCExecutionOptionsPerLayerProfiling"
        }
      ],
      "role": "symbol",
      "title": "perLayerProfiling",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcexecutionoptions/perlayerprofiling"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/profiling": {
      "abstract": [
        {
          "text": "The option to return profiling information in the callback before returning from execution.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "profiling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCExecutionOptions",
          "text": "MLCExecutionOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/profiling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCExecutionOptionsProfiling"
        }
      ],
      "role": "symbol",
      "title": "profiling",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcexecutionoptions/profiling"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/skipWritingInputDataToDevice": {
      "abstract": [
        {
          "text": "The option to skip writing input data to device memory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "skipWritingInputDataToDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCExecutionOptions",
          "text": "MLCExecutionOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/skipWritingInputDataToDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCExecutionOptionsSkipWritingInputDataToDevice"
        }
      ],
      "role": "symbol",
      "title": "skipWritingInputDataToDevice",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcexecutionoptions/skipwritinginputdatatodevice"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/synchronous": {
      "abstract": [
        {
          "text": "The option to execute the graph synchronously.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "synchronous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCExecutionOptions",
          "text": "MLCExecutionOptions"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/synchronous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCExecutionOptionsSynchronous"
        }
      ],
      "role": "symbol",
      "title": "synchronous",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcexecutionoptions/synchronous"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/execute(inputsData:lossLabelsData:lossLabelWeightsData:batchSize:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Executes the training graph with the input data, batch size, execution options, and completion handler you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inputsData"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorData",
          "text": "MLCTensorData"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "lossLabelsData"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorData",
          "text": "MLCTensorData"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "lossLabelWeightsData"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorData",
          "text": "MLCTensorData"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCExecutionOptions",
          "text": "MLCExecutionOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MLCGraphCompletionHandler",
          "text": "MLCGraphCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/execute(inputsData:lossLabelsData:lossLabelWeightsData:batchSize:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executeWithInputsData:lossLabelsData:lossLabelWeightsData:batchSize:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "execute(inputsData:lossLabelsData:lossLabelWeightsData:batchSize:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctraininggraph/execute(inputsdata:losslabelsdata:losslabelweightsdata:batchsize:options:completionhandler:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/executeForward(batchSize:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Executes the forward pass of the training graph with the batch size, execution options, and completion handler you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "executeForward"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCExecutionOptions",
          "text": "MLCExecutionOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MLCGraphCompletionHandler",
          "text": "MLCGraphCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/executeForward(batchSize:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executeForwardWithBatchSize:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "executeForward(batchSize:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctraininggraph/executeforward(batchsize:options:completionhandler:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Execution-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/init(rawValue:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/skipWritingInputDataToDevice",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/synchronous",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/profiling",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/perLayerProfiling"
      ],
      "title": "Execution Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCExecutionOptionsForwardForInference"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCExecutionOptionsForwardForInference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Execution-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/skipWritingInputDataToDevice",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/synchronous",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/profiling",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCExecutionOptions/perLayerProfiling"
              ],
              "title": "Execution Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLCExecutionOptionsForwardForInference"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions/title",
          "value": "MLCExecutionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCExecutionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCExecutionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph~1execute(inputsData:lossLabelsData:lossLabelWeightsData:batchSize:options:completionHandler:)/title",
          "value": "executeWithInputsData:lossLabelsData:lossLabelWeightsData:batchSize:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph~1execute(inputsData:lossLabelsData:lossLabelWeightsData:batchSize:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "executeWithInputsData:lossLabelsData:lossLabelWeightsData:batchSize:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1skipWritingInputDataToDevice/title",
          "value": "MLCExecutionOptionsSkipWritingInputDataToDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1skipWritingInputDataToDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCExecutionOptionsSkipWritingInputDataToDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1forwardForInference/title",
          "value": "MLCExecutionOptionsForwardForInference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1forwardForInference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCExecutionOptionsForwardForInference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1synchronous/title",
          "value": "MLCExecutionOptionsSynchronous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1synchronous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCExecutionOptionsSynchronous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1profiling/title",
          "value": "MLCExecutionOptionsProfiling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1profiling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCExecutionOptionsProfiling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1perLayerProfiling/title",
          "value": "MLCExecutionOptionsPerLayerProfiling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCExecutionOptions~1perLayerProfiling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCExecutionOptionsPerLayerProfiling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph~1executeForward(batchSize:options:completionHandler:)/title",
          "value": "executeForwardWithBatchSize:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph~1executeForward(batchSize:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "executeForwardWithBatchSize:options:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcexecutionoptions/forwardforinference"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcexecutionoptions/forwardforinference"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
