{
  "abstract": [
    {
      "text": "The time and date when the system recorded the measurements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/date"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMWaterSubmersionMeasurement(py)date",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "date"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DateV",
        "text": "Date"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "date"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "date"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "date"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DateV",
              "text": "Date"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement": {
      "abstract": [
        {
          "text": "An update that contains data about the pressure and depth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionMeasurement"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionMeasurement"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState": {
      "abstract": [
        {
          "text": "A state based on the device’s depth under water.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DepthState"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DepthState"
        }
      ],
      "role": "symbol",
      "title": "CMWaterSubmersionMeasurement.DepthState",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depthstate"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/date": {
      "abstract": [
        {
          "text": "The time and date when the system recorded the measurements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/date",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "date"
        }
      ],
      "role": "symbol",
      "title": "date",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/date"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/depth": {
      "abstract": [
        {
          "text": "The depth under water.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/depth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depth"
        }
      ],
      "role": "symbol",
      "title": "depth",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/depth"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/pressure": {
      "abstract": [
        {
          "text": "The water pressure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitPressure",
          "text": "UnitPressure"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/pressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pressure"
        }
      ],
      "role": "symbol",
      "title": "pressure",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/pressure"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/submersionState": {
      "abstract": [
        {
          "text": "The depth state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "submersionState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMWaterSubmersionMeasurement",
          "text": "CMWaterSubmersionMeasurement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMWaterSubmersionDepthState",
          "text": "DepthState"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/submersionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "submersionState"
        }
      ],
      "role": "symbol",
      "title": "submersionState",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/submersionstate"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/surfacePressure": {
      "abstract": [
        {
          "text": "The surface air pressure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "surfacePressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitPressure",
          "text": "UnitPressure"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/surfacePressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "surfacePressure"
        }
      ],
      "role": "symbol",
      "title": "surfacePressure",
      "type": "topic",
      "url": "/documentation/coremotion/cmwatersubmersionmeasurement/surfacepressure"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DateV": {
      "abstract": [
        {
          "text": "A specific point in time, independent of any calendar or time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Date",
      "type": "topic",
      "url": "/documentation/foundation/date"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/depth",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/pressure",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/surfacePressure",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/submersionState",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState"
      ],
      "title": "Accessing the data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "date"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/depth",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/pressure",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/surfacePressure",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/submersionState",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMWaterSubmersionMeasurement/DepthState"
              ],
              "title": "Accessing the data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDate",
                    "text": "NSDate"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "date"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1depth/title",
          "value": "depth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1depth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState/title",
          "value": "CMWaterSubmersionDepthState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1DepthState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionDepthState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1pressure/title",
          "value": "pressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1pressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1surfacePressure/title",
          "value": "surfacePressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1surfacePressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "surfacePressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1submersionState/title",
          "value": "submersionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1submersionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "submersionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1date/title",
          "value": "date"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement~1date/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement/title",
          "value": "CMWaterSubmersionMeasurement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMWaterSubmersionMeasurement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionMeasurement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmwatersubmersionmeasurement/date"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmwatersubmersionmeasurement/date"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
