{
  "abstract": [
    {
      "text": "The corner radius that the sheet attempts to present with.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-3mb5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So29UISheetPresentationControllerC5UIKitE21preferredCornerRadius14CoreFoundation7CGFloatVSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "preferredCornerRadius"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "preferredCornerRadius"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "preferredCornerRadius"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". This property only has an effect when the sheet is at the front of its sheet stack.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController": {
      "abstract": [
        {
          "text": "A presentation controller that manages the appearance and behavior of a sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISheetPresentationController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISheetPresentationController"
        }
      ],
      "role": "symbol",
      "title": "UISheetPresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-3mb5": {
      "abstract": [
        {
          "text": "The corner radius that the sheet attempts to present with.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredCornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-3mb5",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredCornerRadius",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/preferredcornerradius-3mb5"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the sheet attaches to the bottom edge of the screen in a compact-height size class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersEdgeAttachedInCompactHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersEdgeAttachedInCompactHeight"
        }
      ],
      "role": "symbol",
      "title": "prefersEdgeAttachedInCompactHeight",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/prefersedgeattachedincompactheight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the sheet shows a grabber at the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersGrabberVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersGrabberVisible"
        }
      ],
      "role": "symbol",
      "title": "prefersGrabberVisible",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/prefersgrabbervisible"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the sheet sizes itself for readable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersPageSizing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersPageSizing"
        }
      ],
      "role": "symbol",
      "title": "prefersPageSizing",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/preferspagesizing"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/widthFollowsPreferredContentSizeWhenEdgeAttached": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the sheet’s width matches its view controller’s preferred content size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widthFollowsPreferredContentSizeWhenEdgeAttached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/widthFollowsPreferredContentSizeWhenEdgeAttached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widthFollowsPreferredContentSizeWhenEdgeAttached"
        }
      ],
      "role": "symbol",
      "title": "widthFollowsPreferredContentSizeWhenEdgeAttached",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/widthfollowspreferredcontentsizewhenedgeattached"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/widthFollowsPreferredContentSizeWhenEdgeAttached"
      ],
      "title": "Managing the appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController/title",
          "value": "UISheetPresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISheetPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISheetPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersEdgeAttachedInCompactHeight/title",
          "value": "prefersEdgeAttachedInCompactHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersEdgeAttachedInCompactHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersEdgeAttachedInCompactHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersGrabberVisible/title",
          "value": "prefersGrabberVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersGrabberVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersGrabberVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersPageSizing/title",
          "value": "prefersPageSizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersPageSizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersPageSizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1widthFollowsPreferredContentSizeWhenEdgeAttached/title",
          "value": "widthFollowsPreferredContentSizeWhenEdgeAttached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1widthFollowsPreferredContentSizeWhenEdgeAttached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widthFollowsPreferredContentSizeWhenEdgeAttached"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisheetpresentationcontroller/preferredcornerradius-3mb5"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
