{"abstract":[{"type":"text","text":"A Boolean value that determines whether the sheet’s width matches its view controller’s preferred content size."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthFollowsPreferredContentSizeWhenEdgeAttached"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The default value is "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":", which means the sheet’s width equals the width of its container’s safe area. Set this value to "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" to use your view controller’s "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredContentSize"},{"type":"text","text":" to determine the width of the sheet instead."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This property doesn’t have an effect when the sheet is in a compact-width and regular-height size class, or when "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight"},{"type":"text","text":" is "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"metadata":{"externalID":"c:objc(cs)UISheetPresentationController(py)widthFollowsPreferredContentSizeWhenEdgeAttached","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"widthFollowsPreferredContentSizeWhenEdgeAttached"}],"modules":[{"name":"UIKit"}],"symbolKind":"property","title":"widthFollowsPreferredContentSizeWhenEdgeAttached","platforms":[{"beta":false,"unavailable":false,"introducedAt":"15.0","name":"iOS","deprecated":false},{"beta":false,"introducedAt":"15.0","unavailable":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"introducedAt":"15.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthFollowsPreferredContentSizeWhenEdgeAttached"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uisheetpresentationcontroller/widthfollowspreferredcontentsizewhenedgeattached"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uisheetpresentationcontroller/widthfollowspreferredcontentsizewhenedgeattached"]}],"seeAlsoSections":[{"anchor":"Managing-the-appearance","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible","doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing","doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight","doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-3mb5"],"title":"Managing the appearance","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/widthFollowsPreferredContentSizeWhenEdgeAttached","interfaceLanguage":"swift"},"references":{"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-358tc":{"title":"preferredCornerRadius","abstract":[{"text":"The corner radius that the sheet attempts to present with.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-358tc","type":"topic","fragments":[{"text":"preferredCornerRadius","kind":"identifier"}],"url":"/documentation/uikit/uisheetpresentationcontroller/preferredcornerradius-358tc","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredContentSize":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredContentSize","navigatorTitle":[{"text":"preferredContentSize","kind":"identifier"}],"title":"preferredContentSize","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"url":"/documentation/uikit/uiviewcontroller/preferredcontentsize","abstract":[{"type":"text","text":"The preferred size for the view controller’s view."}]},"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerAutomaticDimension":{"title":"UISheetPresentationControllerAutomaticDimension","abstract":[{"text":"The default value to apply to a dimension.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerAutomaticDimension","type":"topic","fragments":[{"text":"UISheetPresentationControllerAutomaticDimension","kind":"identifier"}],"url":"/documentation/uikit/uisheetpresentationcontrollerautomaticdimension","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible":{"title":"prefersGrabberVisible","abstract":[{"text":"A Boolean value that determines whether the sheet shows a grabber at the top.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefersGrabberVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"prefersGrabberVisible","kind":"identifier"}],"url":"/documentation/uikit/uisheetpresentationcontroller/prefersgrabbervisible","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight":{"title":"prefersEdgeAttachedInCompactHeight","abstract":[{"text":"A Boolean value that determines whether the sheet attaches to the bottom edge of the screen in a compact-height size class.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefersEdgeAttachedInCompactHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"prefersEdgeAttachedInCompactHeight","kind":"identifier"}],"url":"/documentation/uikit/uisheetpresentationcontroller/prefersedgeattachedincompactheight","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/widthFollowsPreferredContentSizeWhenEdgeAttached":{"title":"widthFollowsPreferredContentSizeWhenEdgeAttached","abstract":[{"text":"A Boolean value that determines whether the sheet’s width matches its view controller’s preferred content size.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/widthFollowsPreferredContentSizeWhenEdgeAttached","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthFollowsPreferredContentSizeWhenEdgeAttached","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"widthFollowsPreferredContentSizeWhenEdgeAttached","kind":"identifier"}],"url":"/documentation/uikit/uisheetpresentationcontroller/widthfollowspreferredcontentsizewhenedgeattached","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing":{"title":"prefersPageSizing","abstract":[{"text":"A Boolean value that indicates whether the sheet sizes itself for readable content.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefersPageSizing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"prefersPageSizing","kind":"identifier"}],"url":"/documentation/uikit/uisheetpresentationcontroller/preferspagesizing","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-3mb5":{"title":"preferredCornerRadius","abstract":[{"text":"The corner radius that the sheet attempts to present with.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-3mb5","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredCornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uisheetpresentationcontroller/preferredcornerradius-3mb5","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController","type":"topic","url":"/documentation/uikit/uisheetpresentationcontroller","title":"UISheetPresentationController","role":"symbol","navigatorTitle":[{"text":"UISheetPresentationController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISheetPresentationController","kind":"identifier"}],"abstract":[{"type":"text","text":"A presentation controller that manages the appearance and behavior of a sheet."}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"introducedAt":"15.0","unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"introducedAt":"15.0","unavailable":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"introducedAt":"15.0","deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"widthFollowsPreferredContentSizeWhenEdgeAttached"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"widthFollowsPreferredContentSizeWhenEdgeAttached","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Managing-the-appearance","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible","doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing","doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight","doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-358tc","doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerAutomaticDimension"],"title":"Managing the appearance"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"widthFollowsPreferredContentSizeWhenEdgeAttached","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1preferredContentSize/title","op":"replace","value":"preferredContentSize"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1preferredContentSize/fragments","op":"replace","value":[{"text":"preferredContentSize","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersGrabberVisible/title","op":"replace","value":"prefersGrabberVisible"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersGrabberVisible/fragments","op":"replace","value":[{"kind":"identifier","text":"prefersGrabberVisible"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersEdgeAttachedInCompactHeight/title","op":"replace","value":"prefersEdgeAttachedInCompactHeight"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersEdgeAttachedInCompactHeight/fragments","op":"replace","value":[{"text":"prefersEdgeAttachedInCompactHeight","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1widthFollowsPreferredContentSizeWhenEdgeAttached/title","op":"replace","value":"widthFollowsPreferredContentSizeWhenEdgeAttached"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1widthFollowsPreferredContentSizeWhenEdgeAttached/fragments","op":"replace","value":[{"kind":"identifier","text":"widthFollowsPreferredContentSizeWhenEdgeAttached"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersPageSizing/title","op":"replace","value":"prefersPageSizing"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersPageSizing/fragments","op":"replace","value":[{"text":"prefersPageSizing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController/title","op":"replace","value":"UISheetPresentationController"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController/fragments","op":"replace","value":[{"kind":"identifier","text":"UISheetPresentationController"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UISheetPresentationController"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}