{
  "abstract": [
    {
      "text": "Down or right by a large amount.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementPage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSScrollerPart@NSScrollerIncrementPage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "incrementPage"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSScrollerIncrementPage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSScroller.Part.incrementPage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "incrementPage"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/floatValue": {
      "abstract": [
        {
          "text": "The value of the receiver’s cell as a single-precision floating-point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/floatValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "floatValue"
        }
      ],
      "role": "symbol",
      "title": "floatValue",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/floatvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller": {
      "abstract": [
        {
          "text": "An object that controls scrolling of a document view within a scroll view or other type of container view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScroller"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScroller"
        }
      ],
      "role": "symbol",
      "title": "NSScroller",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part": {
      "abstract": [
        {
          "text": "These constants specify the different parts of the scroller:",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Part"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Part"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementLine": {
      "abstract": [
        {
          "text": "Up or left by a small amount.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementLine"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerDecrementLine"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.decrementLine",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/decrementline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementPage": {
      "abstract": [
        {
          "text": "Up or left by a large amount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementPage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerDecrementPage"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.decrementPage",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/decrementpage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementLine": {
      "abstract": [
        {
          "text": "Down or right by a small amount.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incrementLine"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerIncrementLine"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.incrementLine",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/incrementline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementPage": {
      "abstract": [
        {
          "text": "Down or right by a large amount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incrementPage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerIncrementPage"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.incrementPage",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/incrementpage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knob": {
      "abstract": [
        {
          "text": "Directly to the scroller’s value, as given by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/floatValue",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "knob"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerKnob"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.knob",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/knob"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knobSlot": {
      "abstract": [
        {
          "text": "Directly to the scroller’s value, as given by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/floatValue",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "knobSlot"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knobSlot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerKnobSlot"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.knobSlot",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/knobslot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/noPart": {
      "abstract": [
        {
          "text": "Don’t scroll at all.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noPart"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/noPart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerNoPart"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.noPart",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/nopart"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knob",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knobSlot",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementLine",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementPage",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementLine",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/noPart"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSScrollerIncrementPage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerIncrementPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knob",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knobSlot",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementLine",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementPage",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementLine",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/noPart"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSScrollerIncrementPage"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1decrementLine/title",
          "value": "NSScrollerDecrementLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1decrementLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerDecrementLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1incrementLine/title",
          "value": "NSScrollerIncrementLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1incrementLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerIncrementLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1decrementPage/title",
          "value": "NSScrollerDecrementPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1decrementPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerDecrementPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1knobSlot/title",
          "value": "NSScrollerKnobSlot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1knobSlot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerKnobSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/title",
          "value": "NSScroller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1incrementPage/title",
          "value": "NSScrollerIncrementPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1incrementPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerIncrementPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1noPart/title",
          "value": "NSScrollerNoPart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1noPart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerNoPart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part/title",
          "value": "NSScrollerPart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerPart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerPart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1floatValue/title",
          "value": "floatValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1floatValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "floatValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1knob/title",
          "value": "NSScrollerKnob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1knob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerKnob"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscroller/part/incrementpage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsscroller/part/incrementpage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
