{
  "abstract": [
    {
      "text": "Codes for the errors that Shazam produces.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.shazamkit/documentation/ShazamKit",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SHErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "ShazamKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SHError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit": {
      "abstract": [
        {
          "text": "Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ShazamKit",
      "type": "topic",
      "url": "/documentation/shazamkit"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError": {
      "abstract": [
        {
          "text": "An error type that you create, or the system creates, to indicate problems with a catalog, match attempt, or signature, or when saving to a user’s Shazam library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHError"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHError"
        }
      ],
      "role": "symbol",
      "title": "SHError",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code": {
      "abstract": [
        {
          "text": "Codes for the errors that Shazam produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/audioDiscontinuity": {
      "abstract": [
        {
          "text": "The error code to indicate the use of noncontiguous audio to request a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioDiscontinuity"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/audioDiscontinuity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeAudioDiscontinuity"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.audioDiscontinuity",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/audiodiscontinuity"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/customCatalogInvalid": {
      "abstract": [
        {
          "text": "The error code to indicate when the custom catalog fails to load due to an invalid format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customCatalogInvalid"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/customCatalogInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeCustomCatalogInvalid"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.customCatalogInvalid",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/customcataloginvalid"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/customCatalogInvalidURL": {
      "abstract": [
        {
          "text": "The error code to indicate that the format for the custom catalog URL is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customCatalogInvalidURL"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/customCatalogInvalidURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeCustomCatalogInvalidURL"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.customCatalogInvalidURL",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/customcataloginvalidurl"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/init(rawvalue:)"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/internalError": {
      "abstract": [
        {
          "text": "The error code to indicate a generic framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeInternalError"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.internalError",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/internalerror"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/invalidAudioFormat": {
      "abstract": [
        {
          "text": "The error code to indicate an unsupported audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/invalidAudioFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeInvalidAudioFormat"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.invalidAudioFormat",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/invalidaudioformat"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/matchAttemptFailed": {
      "abstract": [
        {
          "text": "The error code to indicate when a Shazam Music catalog server issue prevents finding a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchAttemptFailed"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/matchAttemptFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeMatchAttemptFailed"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.matchAttemptFailed",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/matchattemptfailed"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/mediaItemFetchFailed": {
      "abstract": [
        {
          "text": "The error code to indicate when the system fails to fetch one or more media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaItemFetchFailed"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/mediaItemFetchFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeMediaItemFetchFailed"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.mediaItemFetchFailed",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/mediaitemfetchfailed"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/mediaLibrarySyncFailed": {
      "abstract": [
        {
          "text": "The error code to indicate when the system fails to add one or more media items to the user’s Shazam library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaLibrarySyncFailed"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/mediaLibrarySyncFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeMediaLibrarySyncFailed"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.mediaLibrarySyncFailed",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/medialibrarysyncfailed"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/signatureDurationInvalid": {
      "abstract": [
        {
          "text": "The error code to indicate that the length of the generated signature is too long or too short to make a match in the catalog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureDurationInvalid"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/signatureDurationInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeSignatureDurationInvalid"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.signatureDurationInvalid",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/signaturedurationinvalid"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/signatureInvalid": {
      "abstract": [
        {
          "text": "The error code to indicate that the system is unable to generate a signature from the audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalid"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/signatureInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorCodeSignatureInvalid"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code.signatureInvalid",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code/signatureinvalid"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for specific errors for ShazamKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SHErrorDomain",
      "type": "topic",
      "url": "/documentation/shazamkit/sherrordomain"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/error-constants": {
      "abstract": [
        {
          "text": "Error code constants for framework operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/error-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Constants",
      "type": "topic",
      "url": "/documentation/shazamkit/error-constants"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-an-error",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/error-constants"
      ],
      "title": "Inspecting an error"
    }
  ],
  "topicSections": [
    {
      "anchor": "Matching-errors",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/matchAttemptFailed"
      ],
      "title": "Matching errors"
    },
    {
      "anchor": "Signature-errors",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/signatureInvalid",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/signatureDurationInvalid"
      ],
      "title": "Signature errors"
    },
    {
      "anchor": "Audio-format-errors",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/invalidAudioFormat",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/audioDiscontinuity"
      ],
      "title": "Audio format errors"
    },
    {
      "anchor": "Catalog-errors",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/customCatalogInvalidURL",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/customCatalogInvalid"
      ],
      "title": "Catalog errors"
    },
    {
      "anchor": "Library-sync-errors",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/mediaItemFetchFailed",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/mediaLibrarySyncFailed"
      ],
      "title": "Library sync errors"
    },
    {
      "anchor": "Framework-errors",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/internalError"
      ],
      "title": "Framework errors"
    },
    {
      "anchor": "Querying-the-error-domain",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHErrorDomain"
      ],
      "title": "Querying the error domain"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SHErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.shazamkit/documentation/ShazamKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Matching-errors",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/matchAttemptFailed"
              ],
              "title": "Matching errors"
            },
            {
              "anchor": "Signature-errors",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/signatureInvalid",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/signatureDurationInvalid"
              ],
              "title": "Signature errors"
            },
            {
              "anchor": "Audio-format-errors",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/invalidAudioFormat",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/audioDiscontinuity"
              ],
              "title": "Audio format errors"
            },
            {
              "anchor": "Catalog-errors",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/customCatalogInvalidURL",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/customCatalogInvalid"
              ],
              "title": "Catalog errors"
            },
            {
              "anchor": "Library-sync-errors",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/mediaItemFetchFailed",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/mediaLibrarySyncFailed"
              ],
              "title": "Library sync errors"
            },
            {
              "anchor": "Framework-errors",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code/internalError"
              ],
              "title": "Framework errors"
            },
            {
              "anchor": "Querying-the-error-domain",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHErrorDomain"
              ],
              "title": "Querying the error domain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-an-error",
              "generated": true,
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/error-constants"
              ],
              "title": "Inspecting an error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SHErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1signatureDurationInvalid/title",
          "value": "SHErrorCodeSignatureDurationInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1signatureDurationInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeSignatureDurationInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1matchAttemptFailed/title",
          "value": "SHErrorCodeMatchAttemptFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1matchAttemptFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeMatchAttemptFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1internalError/title",
          "value": "SHErrorCodeInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1customCatalogInvalidURL/title",
          "value": "SHErrorCodeCustomCatalogInvalidURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1customCatalogInvalidURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeCustomCatalogInvalidURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1customCatalogInvalid/title",
          "value": "SHErrorCodeCustomCatalogInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1customCatalogInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeCustomCatalogInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code/title",
          "value": "SHErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1invalidAudioFormat/title",
          "value": "SHErrorCodeInvalidAudioFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1invalidAudioFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeInvalidAudioFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1audioDiscontinuity/title",
          "value": "SHErrorCodeAudioDiscontinuity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1audioDiscontinuity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeAudioDiscontinuity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1mediaItemFetchFailed/title",
          "value": "SHErrorCodeMediaItemFetchFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1mediaItemFetchFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeMediaItemFetchFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1mediaLibrarySyncFailed/title",
          "value": "SHErrorCodeMediaLibrarySyncFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1mediaLibrarySyncFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeMediaLibrarySyncFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHErrorDomain/title",
          "value": "SHErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1signatureInvalid/title",
          "value": "SHErrorCodeSignatureInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code~1signatureInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCodeSignatureInvalid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/shazamkit/sherror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/shazamkit/sherror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
