{
  "abstract": [
    {
      "text": "The error code to indicate that the length of the generated signature is too long or too short to make a match in the catalog.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.shazamkit/documentation/ShazamKit",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/signatureDurationInvalid"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11SHErrorCodeLeV24signatureDurationInvalidSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "signatureDurationInvalid"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11SHErrorCodeLeV",
        "text": "SHError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SHErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "ShazamKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "signatureDurationInvalid"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "signatureDurationInvalid"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11SHErrorCodeLeV",
              "text": "SHError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SHErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error occurs when the length of the generated signature is less than ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/minimumQuerySignatureDuration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or greater than ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/maximumQuerySignatureDuration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the session ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSession/catalog",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit": {
      "abstract": [
        {
          "text": "Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ShazamKit",
      "type": "topic",
      "url": "/documentation/shazamkit"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/maximumQuerySignatureDuration": {
      "abstract": [
        {
          "text": "The maximum duration of a query signature that you use to match reference signatures in the catalog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumQuerySignatureDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/maximumQuerySignatureDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumQuerySignatureDuration"
        }
      ],
      "role": "symbol",
      "title": "maximumQuerySignatureDuration",
      "type": "topic",
      "url": "/documentation/shazamkit/shcatalog/maximumquerysignatureduration"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/minimumQuerySignatureDuration": {
      "abstract": [
        {
          "text": "The minimum duration of a query signature that you use to match reference signatures in the catalog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumQuerySignatureDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/minimumQuerySignatureDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumQuerySignatureDuration"
        }
      ],
      "role": "symbol",
      "title": "minimumQuerySignatureDuration",
      "type": "topic",
      "url": "/documentation/shazamkit/shcatalog/minimumquerysignatureduration"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError": {
      "abstract": [
        {
          "text": "An error type that you create, or the system creates, to indicate problems with a catalog, match attempt, or signature, or when saving to a user’s Shazam library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHError"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHError"
        }
      ],
      "role": "symbol",
      "title": "SHError",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code": {
      "abstract": [
        {
          "text": "Codes for the errors that Shazam produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SHError.Code",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/code"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/audioDiscontinuity": {
      "abstract": [
        {
          "text": "The error code to indicate the use of noncontiguous audio to request a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioDiscontinuity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/audioDiscontinuity",
      "kind": "symbol",
      "role": "symbol",
      "title": "audioDiscontinuity",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/audiodiscontinuity"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/customCatalogInvalid": {
      "abstract": [
        {
          "text": "The error code to indicate when the custom catalog fails to load due to an invalid format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customCatalogInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/customCatalogInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "customCatalogInvalid",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/customcataloginvalid"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/customCatalogInvalidURL": {
      "abstract": [
        {
          "text": "The error code to indicate that the format for the custom catalog URL is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customCatalogInvalidURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/customCatalogInvalidURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "customCatalogInvalidURL",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/customcataloginvalidurl"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/internalError": {
      "abstract": [
        {
          "text": "The error code to indicate a generic framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/internalerror"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/invalidAudioFormat": {
      "abstract": [
        {
          "text": "The error code to indicate an unsupported audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAudioFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/invalidAudioFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidAudioFormat",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/invalidaudioformat"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/matchAttemptFailed": {
      "abstract": [
        {
          "text": "The error code to indicate when a Shazam Music catalog server issue prevents finding a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchAttemptFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/matchAttemptFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "matchAttemptFailed",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/matchattemptfailed"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/mediaItemFetchFailed": {
      "abstract": [
        {
          "text": "The error code to indicate when the system fails to fetch one or more media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaItemFetchFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/mediaItemFetchFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaItemFetchFailed",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/mediaitemfetchfailed"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/mediaLibrarySyncFailed": {
      "abstract": [
        {
          "text": "The error code that indicates when the system fails to add media items to or remove items from the user’s Shazam library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaLibrarySyncFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/mediaLibrarySyncFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaLibrarySyncFailed",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/medialibrarysyncfailed"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/signatureDurationInvalid": {
      "abstract": [
        {
          "text": "The error code to indicate that the length of the generated signature is too long or too short to make a match in the catalog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureDurationInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/signatureDurationInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureDurationInvalid",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/signaturedurationinvalid"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/signatureInvalid": {
      "abstract": [
        {
          "text": "The error code to indicate that the system is unable to generate a signature from the audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SHErrorCodeLeV",
          "text": "SHError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SHErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/signatureInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureInvalid",
      "type": "topic",
      "url": "/documentation/shazamkit/sherror/signatureinvalid"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSession/catalog": {
      "abstract": [
        {
          "text": "The catalog object containing the reference signatures and their associated metadata that the session uses to perform matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "catalog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SHCatalog",
          "text": "SHCatalog"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSession/catalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "catalog"
        }
      ],
      "role": "symbol",
      "title": "catalog",
      "type": "topic",
      "url": "/documentation/shazamkit/shsession/catalog"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/matchAttemptFailed",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/signatureInvalid",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/invalidAudioFormat",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/internalError",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/audioDiscontinuity",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/customCatalogInvalidURL",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/customCatalogInvalid",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/mediaItemFetchFailed",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHError/mediaLibrarySyncFailed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSession~1catalog/title",
          "value": "catalog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSession~1catalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "catalog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog~1minimumQuerySignatureDuration/title",
          "value": "minimumQuerySignatureDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog~1minimumQuerySignatureDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumQuerySignatureDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code/title",
          "value": "SHErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog~1maximumQuerySignatureDuration/title",
          "value": "maximumQuerySignatureDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog~1maximumQuerySignatureDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumQuerySignatureDuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/shazamkit/sherror/signaturedurationinvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
