{
  "abstract": [
    {
      "text": "Indicates a buffer processes after existing buffers in the queue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHASEPushStreamBufferOptions@PHASEPushStreamBufferDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
        "text": "PHASEPushStreamBufferOptions"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASEPushStreamBufferDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
              "text": "PHASEPushStreamBufferOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions": {
      "abstract": [
        {
          "text": "Options that inform PHASE of an audio-stream buffer’s playback priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "role": "symbol",
      "title": "PHASEPushStreamBufferOptions",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/default": {
      "abstract": [
        {
          "text": "Indicates a buffer processes after existing buffers in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/default"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interrupts": {
      "abstract": [
        {
          "text": "Indicates a buffer begins processing immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interrupts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interrupts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferInterrupts"
        }
      ],
      "role": "symbol",
      "title": "interrupts",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/interrupts"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interruptsAtLoop": {
      "abstract": [
        {
          "text": "Indicates a buffer begins processing when an existing buffer loops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interruptsAtLoop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interruptsAtLoop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferInterruptsAtLoop"
        }
      ],
      "role": "symbol",
      "title": "interruptsAtLoop",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/interruptsatloop"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/loops": {
      "abstract": [
        {
          "text": "Indicates a buffer restarts after it finishes processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHASEPushStreamBufferOptions",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/loops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferLoops"
        }
      ],
      "role": "symbol",
      "title": "loops",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/loops"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interrupts",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interruptsAtLoop",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/loops"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASEPushStreamBufferDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interrupts",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/interruptsAtLoop",
                "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/loops"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHASEPushStreamBufferDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/title",
          "value": "PHASEPushStreamBufferOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1interruptsAtLoop/title",
          "value": "PHASEPushStreamBufferInterruptsAtLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1interruptsAtLoop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferInterruptsAtLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1interrupts/title",
          "value": "PHASEPushStreamBufferInterrupts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1interrupts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferInterrupts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1default/title",
          "value": "PHASEPushStreamBufferDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1loops/title",
          "value": "PHASEPushStreamBufferLoops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions~1loops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferLoops"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasepushstreambufferoptions/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasepushstreambufferoptions/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
