{
  "abstract": [
    {
      "text": "Creates a push stream buffer option with the given raw value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE",
        "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/init(rawValue:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So28PHASEPushStreamBufferOptionsV8rawValueABSu_tcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "rawValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Su",
        "text": "UInt"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(rawValue:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Su",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Su",
              "text": "UInt"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A raw value for the option’s enumeration case.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rawValue"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions": {
      "abstract": [
        {
          "text": "Options that inform PHASE of an audio-stream buffer’s playback priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEPushStreamBufferOptions"
        }
      ],
      "role": "symbol",
      "title": "PHASEPushStreamBufferOptions",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a push stream buffer option with the given raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEPushStreamBufferOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/phase/phasepushstreambufferoptions/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:Su": {
      "abstract": [
        {
          "text": "An unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Su",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt",
      "type": "topic",
      "url": "/documentation/Swift/UInt"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/title",
          "value": "PHASEPushStreamBufferOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEPushStreamBufferOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEPushStreamBufferOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasepushstreambufferoptions/init(rawvalue:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
