{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventConnectionCompleteResults"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventConnectionCompleteResults/init(connectionHandle:deviceAddress:linkType:encryptionMode:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So42BluetoothHCIEventConnectionCompleteResultsV16connectionHandle13deviceAddress8linkType14encryptionModeABs6UInt16V_So0a6DeviceI0Vs5UInt8VALtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "connectionHandle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
        "text": "BluetoothConnectionHandle"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "deviceAddress"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
        "text": "BluetoothDeviceAddress"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "linkType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothLinkType",
        "text": "BluetoothLinkType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "encryptionMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothHCIEncryptionMode",
        "text": "BluetoothHCIEncryptionMode"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(connectionHandle:deviceAddress:linkType:encryptionMode:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "connectionHandle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
              "text": "BluetoothConnectionHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "deviceAddress"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
              "text": "BluetoothDeviceAddress"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "linkType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLinkType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothLinkType",
              "text": "BluetoothLinkType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "encryptionMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEncryptionMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothHCIEncryptionMode",
              "text": "BluetoothHCIEncryptionMode"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "role": "symbol",
      "title": "BluetoothConnectionHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothconnectionhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceaddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEncryptionMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIEncryptionMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEncryptionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIEncryptionMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIEncryptionMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciencryptionmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventConnectionCompleteResults": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIEventConnectionCompleteResults"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventConnectionCompleteResults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIEventConnectionCompleteResults"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIEventConnectionCompleteResults",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcieventconnectioncompleteresults"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventConnectionCompleteResults/init(connectionHandle:deviceAddress:linkType:encryptionMode:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "connectionHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
          "text": "BluetoothConnectionHandle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deviceAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
          "text": "BluetoothDeviceAddress"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "linkType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothLinkType",
          "text": "BluetoothLinkType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "encryptionMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothHCIEncryptionMode",
          "text": "BluetoothHCIEncryptionMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEventConnectionCompleteResults/init(connectionHandle:deviceAddress:linkType:encryptionMode:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(connectionHandle:deviceAddress:linkType:encryptionMode:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcieventconnectioncompleteresults/init(connectionhandle:deviceaddress:linktype:encryptionmode:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLinkType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLinkType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLinkType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLinkType"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLinkType",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothlinktype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEncryptionMode/title",
          "value": "BluetoothHCIEncryptionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEncryptionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEncryptionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEncryptionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEncryptionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEventConnectionCompleteResults/title",
          "value": "BluetoothHCIEventConnectionCompleteResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEventConnectionCompleteResults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEventConnectionCompleteResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEventConnectionCompleteResults/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEventConnectionCompleteResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLinkType/title",
          "value": "BluetoothLinkType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLinkType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLinkType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLinkType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLinkType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/title",
          "value": "BluetoothConnectionHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/title",
          "value": "BluetoothDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcieventconnectioncompleteresults/init(connectionhandle:deviceaddress:linktype:encryptionmode:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
