{
  "abstract": [
    {
      "text": "An annotation view ends dragging.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView",
        "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/ending"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MKAnnotationViewDragState@MKAnnotationViewDragStateEnding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ending"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKAnnotationViewDragStateEnding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MKAnnotationView.DragState.ending"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ending"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A user action indicates the user dropped the view. The map view automatically moves annotation views to this state in response to appropriate user actions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView": {
      "abstract": [
        {
          "text": "The visual representation of one of your annotation objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKAnnotationView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAnnotationView"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotationView",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotationview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the drag state of an annotation view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DragState"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DragState"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotationView.DragState",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotationview/dragstate-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/canceling": {
      "abstract": [
        {
          "text": "An annotation view cancels drag operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canceling"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/canceling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAnnotationViewDragStateCanceling"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotationView.DragState.canceling",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotationview/dragstate-swift.enum/canceling"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/dragging": {
      "abstract": [
        {
          "text": "An annotation view is actively dragging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dragging"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/dragging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAnnotationViewDragStateDragging"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotationView.DragState.dragging",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotationview/dragstate-swift.enum/dragging"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/ending": {
      "abstract": [
        {
          "text": "An annotation view ends dragging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ending"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/ending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAnnotationViewDragStateEnding"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotationView.DragState.ending",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotationview/dragstate-swift.enum/ending"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/none": {
      "abstract": [
        {
          "text": "An annotation view that doesn’t have a drag operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAnnotationViewDragStateNone"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotationView.DragState.none",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotationview/dragstate-swift.enum/none"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/starting": {
      "abstract": [
        {
          "text": "An annotation view begins dragging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "starting"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/starting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAnnotationViewDragStateStarting"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotationView.DragState.starting",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotationview/dragstate-swift.enum/starting"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/none",
        "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/starting",
        "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/dragging",
        "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/canceling"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKAnnotationViewDragStateEnding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationViewDragStateEnding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/none",
                "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/starting",
                "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/dragging",
                "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView/DragState-swift.enum/canceling"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MKAnnotationViewDragStateEnding"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1none/title",
          "value": "MKAnnotationViewDragStateNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationViewDragStateNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum/title",
          "value": "MKAnnotationViewDragState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationViewDragState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationViewDragState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView/title",
          "value": "MKAnnotationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1starting/title",
          "value": "MKAnnotationViewDragStateStarting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1starting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationViewDragStateStarting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1dragging/title",
          "value": "MKAnnotationViewDragStateDragging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1dragging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationViewDragStateDragging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1ending/title",
          "value": "MKAnnotationViewDragStateEnding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1ending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationViewDragStateEnding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1canceling/title",
          "value": "MKAnnotationViewDragStateCanceling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView~1DragState-swift.enum~1canceling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationViewDragStateCanceling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkannotationview/dragstate-swift.enum/ending"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkannotationview/dragstate-swift.enum/ending"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
