{
  "abstract": [
    {
      "text": "Styles for a Preview View.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklookui/documentation/QuickLookUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@QLPreviewViewStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QLPreviewViewStyle"
      }
    ],
    "modules": [
      {
        "name": "Quick Look UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLPreviewViewStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "QLPreviewViewStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QLPreviewViewStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look UI",
      "type": "topic",
      "url": "/documentation/quicklookui"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:)": {
      "abstract": [
        {
          "text": "Creates a preview view with the provided frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:)",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/init(frame:)"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:style:)": {
      "abstract": [
        {
          "text": "Creates a preview view with the provided frame and style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLPreviewViewStyle",
          "text": "QLPreviewViewStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:style:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:style:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:style:)",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/init(frame:style:)"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle": {
      "abstract": [
        {
          "text": "Styles for a Preview View.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewViewStyle"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewViewStyle"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewViewStyle",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewviewstyle"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/compact": {
      "abstract": [
        {
          "text": "Provides a compact preview style suited for smaller previews or inspectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compact"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/compact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewViewStyleCompact"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewViewStyle.compact",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewviewstyle/compact"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewviewstyle/init(rawvalue:)"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/normal": {
      "abstract": [
        {
          "text": "Provides the default preview style for larger, full-sized previews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewViewStyleNormal"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewViewStyle.normal",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewviewstyle/normal"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Preview-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:style:)",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:)"
      ],
      "title": "Creating a Preview View"
    }
  ],
  "topicSections": [
    {
      "anchor": "Choosing-a-Preview-Style",
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/normal",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/compact"
      ],
      "title": "Choosing a Preview Style"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLPreviewViewStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklookui/documentation/QuickLookUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Choosing-a-Preview-Style",
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/normal",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle/compact"
              ],
              "title": "Choosing a Preview Style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Preview-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:style:)",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:)"
              ],
              "title": "Creating a Preview View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLPreviewViewStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1init(frame:style:)/title",
          "value": "initWithFrame:style:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1init(frame:style:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:style:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle~1compact/title",
          "value": "QLPreviewViewStyleCompact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle~1compact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewViewStyleCompact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle~1normal/title",
          "value": "QLPreviewViewStyleNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewViewStyleNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1init(frame:)/title",
          "value": "initWithFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1init(frame:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle/title",
          "value": "QLPreviewViewStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewViewStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewviewstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewviewstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
