{
  "abstract": [
    {
      "text": "A Quick Look preview of an item that you can embed into your view hierarchy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklookui/documentation/QuickLookUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)QLPreviewView",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QLPreviewView"
      }
    ],
    "modules": [
      {
        "name": "Quick Look UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLPreviewView"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "QLPreviewView"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QLPreviewView"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look UI",
      "type": "topic",
      "url": "/documentation/quicklookui"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem": {
      "abstract": [
        {
          "text": "A protocol that defines a set of properties you implement to make a preview of your application’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItem",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewitem"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItemLoadingBlock": {
      "abstract": [
        {
          "text": "A type that defines a block used to load a Quick Look preview item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItemLoadingBlock"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItemLoadingBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemLoadingBlock"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemLoadingBlock",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewitemloadingblock"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel": {
      "abstract": [
        {
          "text": "A class that implements the Quick Look preview panel to display a preview of a list of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewPanel"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewPanel"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewPanel",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDataSource": {
      "abstract": [
        {
          "text": "A protocol that the Quick Look preview panel uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewPanelDataSource"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewPanelDataSource"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewPanelDataSource",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpaneldatasource"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDelegate": {
      "abstract": [
        {
          "text": "A protocol for the delegate of the Quick Look preview panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewPanelDelegate"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewPanelDelegate"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewPanelDelegate",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpaneldelegate"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView": {
      "abstract": [
        {
          "text": "A Quick Look preview of an item that you can embed into your view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewView"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewView"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewView",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/autostarts": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the preview starts automatically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autostarts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/autostarts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autostarts"
        }
      ],
      "role": "symbol",
      "title": "autostarts",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/autostarts"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/close()": {
      "abstract": [
        {
          "text": "Closes the view, releasing the current preview item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "close"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/close()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "close"
        }
      ],
      "role": "symbol",
      "title": "close()",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/close()"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/displayState": {
      "abstract": [
        {
          "text": "The current display state of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/previewItem",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/displayState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayState"
        }
      ],
      "role": "symbol",
      "title": "displayState",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/displaystate"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:)": {
      "abstract": [
        {
          "text": "Creates a preview view with the provided frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:)",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/init(frame:)"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:style:)": {
      "abstract": [
        {
          "text": "Creates a preview view with the provided frame and style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLPreviewViewStyle",
          "text": "QLPreviewViewStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:style:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:style:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:style:)",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/init(frame:style:)"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/previewItem": {
      "abstract": [
        {
          "text": "The item to preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewItem"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QLPreviewItem",
          "text": "QLPreviewItem"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/previewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewItem"
        }
      ],
      "role": "symbol",
      "title": "previewItem",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/previewitem"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/refreshPreviewItem()": {
      "abstract": [
        {
          "text": "Updates the preview to display the currently previewed item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refreshPreviewItem"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/refreshPreviewItem()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "refreshPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "refreshPreviewItem()",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/refreshpreviewitem()"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/shouldCloseWithWindow": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the preview should close when its window closes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldCloseWithWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/shouldCloseWithWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldCloseWithWindow"
        }
      ],
      "role": "symbol",
      "title": "shouldCloseWithWindow",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview/shouldclosewithwindow"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle": {
      "abstract": [
        {
          "text": "Styles for a Preview View.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewViewStyle"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewViewStyle"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewViewStyle",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewviewstyle"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSView",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/AppKit/NSView"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/AppKit/NSAccessibilityProtocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/AppKit/NSAccessibilityElementProtocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer": {
      "abstract": [
        {
          "text": "A set of methods that defines a way to add animation to an existing class with a minimum of API impact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAnimatablePropertyContainer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAnimatablePropertyContainer",
      "type": "topic",
      "url": "/documentation/AppKit/NSAnimatablePropertyContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization": {
      "abstract": [
        {
          "text": "A set of methods for getting and setting the appearance attributes of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppearanceCustomization"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppearanceCustomization",
      "type": "topic",
      "url": "/documentation/AppKit/NSAppearanceCustomization"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSDraggingDestination": {
      "abstract": [
        {
          "text": "A set of methods that the destination object (or recipient) of a dragged image must implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingDestination"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSDraggingDestination",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDraggingDestination",
      "type": "topic",
      "url": "/documentation/AppKit/NSDraggingDestination"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding": {
      "abstract": [
        {
          "text": "Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStandardKeyBindingResponding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStandardKeyBindingResponding",
      "type": "topic",
      "url": "/documentation/AppKit/NSStandardKeyBindingResponding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring": {
      "abstract": [
        {
          "text": "A protocol that marks classes to restore the state of your app to continue a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserInterfaceItemIdentification"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSView"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSDraggingDestination",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Previews",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDataSource",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDelegate",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItemLoadingBlock"
      ],
      "title": "Previews"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Preview-View",
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:style:)",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:)",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle"
      ],
      "title": "Creating a Preview View"
    },
    {
      "anchor": "Displaying-a-Preview",
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/previewItem",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/refreshPreviewItem()",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/displayState",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/autostarts"
      ],
      "title": "Displaying a Preview"
    },
    {
      "anchor": "Closing-a-Preview",
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/shouldCloseWithWindow",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/close()"
      ],
      "title": "Closing a Preview"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLPreviewView"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklookui/documentation/QuickLookUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Preview-View",
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:style:)",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/init(frame:)",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewViewStyle"
              ],
              "title": "Creating a Preview View"
            },
            {
              "anchor": "Displaying-a-Preview",
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/previewItem",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/refreshPreviewItem()",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/displayState",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/autostarts"
              ],
              "title": "Displaying a Preview"
            },
            {
              "anchor": "Closing-a-Preview",
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/shouldCloseWithWindow",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView/close()"
              ],
              "title": "Closing a Preview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSView"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Previews",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDataSource",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDelegate",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItemLoadingBlock"
              ],
              "title": "Previews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLPreviewView"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSView",
                    "text": "NSView"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1close()/title",
          "value": "close"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1close()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "close"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibilityElement/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibilityElement/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibility/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibility/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem/title",
          "value": "QLPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAnimatablePropertyContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAnimatablePropertyContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1autostarts/title",
          "value": "autostarts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1autostarts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autostarts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1previewItem/title",
          "value": "previewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1previewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView/title",
          "value": "QLPreviewView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel/title",
          "value": "QLPreviewPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1displayState/title",
          "value": "displayState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1displayState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAppearanceCustomization/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAppearanceCustomization"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDataSource/title",
          "value": "QLPreviewPanelDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1shouldCloseWithWindow/title",
          "value": "shouldCloseWithWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1shouldCloseWithWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldCloseWithWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDelegate/title",
          "value": "QLPreviewPanelDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle/title",
          "value": "QLPreviewViewStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewViewStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1init(frame:style:)/title",
          "value": "initWithFrame:style:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1init(frame:style:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:style:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSStandardKeyBindingResponding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSStandardKeyBindingResponding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItemLoadingBlock/title",
          "value": "QLPreviewItemLoadingBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItemLoadingBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemLoadingBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItemLoadingBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemLoadingBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1refreshPreviewItem()/title",
          "value": "refreshPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1refreshPreviewItem()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "refreshPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1init(frame:)/title",
          "value": "initWithFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView~1init(frame:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSDraggingDestination/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDraggingDestination"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewview"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewview"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
