{
  "abstract": [
    {
      "text": "A class that you subclass to provide a data-based Quick Look preview extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklookui/documentation/QuickLookUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)QLPreviewProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QLPreviewProvider"
      }
    ],
    "modules": [
      {
        "name": "Quick Look UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLPreviewProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "QLPreviewProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QLPreviewProvider"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you subclass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", conform your subclass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewingController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To provide a data-based Quick Look extension, make the following modifications to your Info.plist file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the Boolean key ",
                      "type": "text"
                    },
                    {
                      "code": "QLIsDataBasedPreview",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the type identifiers for your extension’s supported content types to the ",
                      "type": "text"
                    },
                    {
                      "code": "QLSupportedContentTypes",
                      "type": "codeVoice"
                    },
                    {
                      "text": " array.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Change the value of ",
                      "type": "text"
                    },
                    {
                      "code": "NSExtensionPrincipalClass",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to the name of your subclass. For example, if you named your subclass ",
                      "type": "text"
                    },
                    {
                      "code": "PreviewProvider",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", set the value to ",
                      "type": "text"
                    },
                    {
                      "code": "$(PRODUCT_MODULE_NAME).PreviewProvider",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "After updating the extension’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewingController/providePreview(for:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to return a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewReply",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the provided ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLFilePreviewRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look UI",
      "type": "topic",
      "url": "/documentation/quicklookui"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLFilePreviewRequest": {
      "abstract": [
        {
          "text": "A Quick Look preview request that indicates the content to preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLFilePreviewRequest"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLFilePreviewRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLFilePreviewRequest"
        }
      ],
      "role": "symbol",
      "title": "QLFilePreviewRequest",
      "type": "topic",
      "url": "/documentation/quicklookui/qlfilepreviewrequest"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewProvider": {
      "abstract": [
        {
          "text": "A class that you subclass to provide a data-based Quick Look preview extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewProvider"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewProvider"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewProvider",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewprovider"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewReply": {
      "abstract": [
        {
          "text": "The class you create when providing a data-based Quick Look preview extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewReply"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewReply"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewReply",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewreply"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewReplyAttachment": {
      "abstract": [
        {
          "text": "An attachment for a Quick Look preview reply that provides additional content for the system to display a preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewReplyAttachment"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewReplyAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewReplyAttachment"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewReplyAttachment",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewreplyattachment"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewingController": {
      "abstract": [
        {
          "text": "A protocol for implementing a custom controller to create previews of files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewingController"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewingController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewingController"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewingController",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewingcontroller"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewingController/providePreview(for:completionHandler:)": {
      "abstract": [
        {
          "text": "Prepares the preview of a file identified within a file preview request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providePreview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLFilePreviewRequest",
          "text": "QLFilePreviewRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLPreviewReply",
          "text": "QLPreviewReply"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewingController/providePreview(for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "providePreviewForFileRequest:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "providePreview(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewingcontroller/providepreview(for:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling": {
      "abstract": [
        {
          "text": "The interface an app extension uses to respond to a request from a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionRequestHandling",
      "type": "topic",
      "url": "/documentation/foundation/nsextensionrequesthandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-based-Preview-Extensions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLFilePreviewRequest",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewReply",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewReplyAttachment"
      ],
      "title": "Data-based Preview Extensions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLPreviewProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklookui/documentation/QuickLookUI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-based-Preview-Extensions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLFilePreviewRequest",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewReply",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewReplyAttachment"
              ],
              "title": "Data-based Preview Extensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLPreviewProvider"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLFilePreviewRequest/title",
          "value": "QLFilePreviewRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLFilePreviewRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLFilePreviewRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLFilePreviewRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLFilePreviewRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewProvider/title",
          "value": "QLPreviewProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewingController/title",
          "value": "QLPreviewingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewingController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewingController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewingController~1providePreview(for:completionHandler:)/title",
          "value": "providePreviewForFileRequest:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewingController~1providePreview(for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "providePreviewForFileRequest:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewReplyAttachment/title",
          "value": "QLPreviewReplyAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewReplyAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReplyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewReplyAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReplyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewReply/title",
          "value": "QLPreviewReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReply"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
