{
  "abstract": [
    {
      "text": "A class that implements the Quick Look preview panel to display a preview of a list of items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklookui/documentation/QuickLookUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)QLPreviewPanel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QLPreviewPanel"
      }
    ],
    "modules": [
      {
        "name": "Quick Look UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLPreviewPanel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "QLPreviewPanel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QLPreviewPanel"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Every application has a single shared instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " accessible through ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/shared()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The preview panel follows the responder chain and adapts to the first responder willing to control it. A preview panel controller provides the content through methods defined in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDataSource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can’t subclass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "; you can, however, customize its behavior using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/delegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". See the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol for the methods to customize a preview panel’s behavior.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look UI",
      "type": "topic",
      "url": "/documentation/quicklookui"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem": {
      "abstract": [
        {
          "text": "A protocol that defines a set of properties you implement to make a preview of your application’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItem",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewitem"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItemLoadingBlock": {
      "abstract": [
        {
          "text": "A type that defines a block used to load a Quick Look preview item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItemLoadingBlock"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItemLoadingBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemLoadingBlock"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemLoadingBlock",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewitemloadingblock"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel": {
      "abstract": [
        {
          "text": "A class that implements the Quick Look preview panel to display a preview of a list of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewPanel"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewPanel"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewPanel",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentController": {
      "abstract": [
        {
          "text": "The current first responder accepting to control the preview panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentController"
        }
      ],
      "role": "symbol",
      "title": "currentController",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/currentcontroller"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentPreviewItem": {
      "abstract": [
        {
          "text": "The currently previewed item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentPreviewItem"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QLPreviewItem",
          "text": "QLPreviewItem"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "currentPreviewItem",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/currentpreviewitem"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentPreviewItemIndex": {
      "abstract": [
        {
          "text": "The index of the current preview item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentPreviewItemIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentPreviewItemIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentPreviewItemIndex"
        }
      ],
      "role": "symbol",
      "title": "currentPreviewItemIndex",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/currentpreviewitemindex"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/dataSource": {
      "abstract": [
        {
          "text": "The preview panel data source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataSource"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QLPreviewPanelDataSource",
          "text": "QLPreviewPanelDataSource"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/dataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataSource"
        }
      ],
      "role": "symbol",
      "title": "dataSource",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/datasource"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/delegate": {
      "abstract": [
        {
          "text": "The delegate object that controls the preview panel’s behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": AnyObject!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/delegate"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/displayState": {
      "abstract": [
        {
          "text": "The preview panel’s display state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/displayState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayState"
        }
      ],
      "role": "symbol",
      "title": "displayState",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/displaystate"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/enterFullScreenMode(_:withOptions:)": {
      "abstract": [
        {
          "text": "Instructs the panel to enter full screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enterFullScreenMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScreen",
          "text": "NSScreen"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "withOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/enterFullScreenMode(_:withOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enterFullScreenMode:withOptions:"
        }
      ],
      "role": "symbol",
      "title": "enterFullScreenMode(_:withOptions:)",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/enterfullscreenmode(_:withoptions:)"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/exitFullScreenMode(options:)": {
      "abstract": [
        {
          "text": "Instructs the panel to exit full screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exitFullScreenMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/exitFullScreenMode(options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exitFullScreenModeWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "exitFullScreenMode(options:)",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/exitfullscreenmode(options:)"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/isInFullScreenMode": {
      "abstract": [
        {
          "text": "The property that indicates whether the panel is in full screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInFullScreenMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/isInFullScreenMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inFullScreenMode"
        }
      ],
      "role": "symbol",
      "title": "isInFullScreenMode",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/isinfullscreenmode"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/refreshCurrentPreviewItem()": {
      "abstract": [
        {
          "text": "Asks the preview panel to recompute the preview of the current preview item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refreshCurrentPreviewItem"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/refreshCurrentPreviewItem()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "refreshCurrentPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "refreshCurrentPreviewItem()",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/refreshcurrentpreviewitem()"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/reloadData()": {
      "abstract": [
        {
          "text": "Asks the preview panel to reload its data from its data source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reloadData"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/reloadData()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reloadData"
        }
      ],
      "role": "symbol",
      "title": "reloadData()",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/reloaddata()"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/shared()": {
      "abstract": [
        {
          "text": "Returns the shared Quick Look preview panel instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLPreviewPanel",
          "text": "QLPreviewPanel"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/shared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedPreviewPanel"
        }
      ],
      "role": "symbol",
      "title": "shared()",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/shared()"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/sharedPreviewPanelExists()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the system has created a shared Quick Look preview panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sharedPreviewPanelExists"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/sharedPreviewPanelExists()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedPreviewPanelExists"
        }
      ],
      "role": "symbol",
      "title": "sharedPreviewPanelExists()",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/sharedpreviewpanelexists()"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/updateController()": {
      "abstract": [
        {
          "text": "Asks the preview panel to update its current controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateController"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/updateController()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateController"
        }
      ],
      "role": "symbol",
      "title": "updateController()",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/updatecontroller()"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDataSource": {
      "abstract": [
        {
          "text": "A protocol that the Quick Look preview panel uses to access the contents of its data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewPanelDataSource"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewPanelDataSource"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewPanelDataSource",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpaneldatasource"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDelegate": {
      "abstract": [
        {
          "text": "A protocol for the delegate of the Quick Look preview panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewPanelDelegate"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewPanelDelegate"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewPanelDelegate",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpaneldelegate"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView": {
      "abstract": [
        {
          "text": "A Quick Look preview of an item that you can embed into your view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewView"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewView"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewView",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewview"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSPanel": {
      "abstract": [
        {
          "text": "A special kind of window that typically performs a function that is auxiliary to the main window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPanel"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPanel",
      "type": "topic",
      "url": "/documentation/AppKit/NSPanel"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/AppKit/NSAccessibilityProtocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/AppKit/NSAccessibilityElementProtocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer": {
      "abstract": [
        {
          "text": "A set of methods that defines a way to add animation to an existing class with a minimum of API impact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAnimatablePropertyContainer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAnimatablePropertyContainer",
      "type": "topic",
      "url": "/documentation/AppKit/NSAnimatablePropertyContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization": {
      "abstract": [
        {
          "text": "A set of methods for getting and setting the appearance attributes of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppearanceCustomization"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppearanceCustomization",
      "type": "topic",
      "url": "/documentation/AppKit/NSAppearanceCustomization"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSMenuItemValidation": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuItemValidation"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSMenuItemValidation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMenuItemValidation",
      "type": "topic",
      "url": "/documentation/AppKit/NSMenuItemValidation"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding": {
      "abstract": [
        {
          "text": "Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStandardKeyBindingResponding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStandardKeyBindingResponding",
      "type": "topic",
      "url": "/documentation/AppKit/NSStandardKeyBindingResponding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring": {
      "abstract": [
        {
          "text": "A protocol that marks classes to restore the state of your app to continue a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserInterfaceItemIdentification"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceValidations": {
      "abstract": [
        {
          "text": "A protocol that a custom class can adopt to manage the enabled state of a UI element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceValidations"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceValidations",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserInterfaceValidations",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserInterfaceValidations"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSPanel"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSMenuItemValidation",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceValidations"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Previews",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDataSource",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDelegate",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItemLoadingBlock"
      ],
      "title": "Previews"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Shared-Panel",
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/shared()",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/sharedPreviewPanelExists()"
      ],
      "title": "Accessing the Shared Panel"
    },
    {
      "anchor": "Accessing-the-Preview-Panel-Controller",
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentController",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/updateController()"
      ],
      "title": "Accessing the Preview Panel Controller"
    },
    {
      "anchor": "Managing-the-Preview-Items",
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/dataSource",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/reloadData()",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/refreshCurrentPreviewItem()",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentPreviewItemIndex",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentPreviewItem",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/displayState"
      ],
      "title": "Managing the Preview Items"
    },
    {
      "anchor": "The-Panels-Delegate",
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/delegate"
      ],
      "title": "The Panel’s Delegate"
    },
    {
      "anchor": "Managing-Full-Screen-Mode",
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/enterFullScreenMode(_:withOptions:)",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/exitFullScreenMode(options:)",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/isInFullScreenMode"
      ],
      "title": "Managing Full Screen Mode"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLPreviewPanel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklookui/documentation/QuickLookUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Shared-Panel",
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/shared()",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/sharedPreviewPanelExists()"
              ],
              "title": "Accessing the Shared Panel"
            },
            {
              "anchor": "Accessing-the-Preview-Panel-Controller",
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentController",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/updateController()"
              ],
              "title": "Accessing the Preview Panel Controller"
            },
            {
              "anchor": "Managing-the-Preview-Items",
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/dataSource",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/reloadData()",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/refreshCurrentPreviewItem()",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentPreviewItemIndex",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/currentPreviewItem",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/displayState"
              ],
              "title": "Managing the Preview Items"
            },
            {
              "anchor": "The-Panels-Delegate",
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/delegate"
              ],
              "title": "The Panel’s Delegate"
            },
            {
              "anchor": "Managing-Full-Screen-Mode",
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/enterFullScreenMode(_:withOptions:)",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/exitFullScreenMode(options:)",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/isInFullScreenMode"
              ],
              "title": "Managing Full Screen Mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSPanel"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Previews",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewView",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDataSource",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanelDelegate",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItemLoadingBlock"
              ],
              "title": "Previews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLPreviewPanel"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPanel",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPanel",
                    "text": "NSPanel"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItemLoadingBlock/title",
          "value": "QLPreviewItemLoadingBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItemLoadingBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemLoadingBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItemLoadingBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemLoadingBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDelegate/title",
          "value": "QLPreviewPanelDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1sharedPreviewPanelExists()/title",
          "value": "sharedPreviewPanelExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1sharedPreviewPanelExists()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedPreviewPanelExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1exitFullScreenMode(options:)/title",
          "value": "exitFullScreenModeWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1exitFullScreenMode(options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "exitFullScreenModeWithOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1reloadData()/title",
          "value": "reloadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1reloadData()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reloadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1dataSource/title",
          "value": "dataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1dataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSStandardKeyBindingResponding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSStandardKeyBindingResponding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAnimatablePropertyContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAnimatablePropertyContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1displayState/title",
          "value": "displayState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1displayState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSPanel/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPanel"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWindow",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDataSource/title",
          "value": "QLPreviewPanelDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanelDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanelDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSMenuItemValidation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMenuItemValidation"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1refreshCurrentPreviewItem()/title",
          "value": "refreshCurrentPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1refreshCurrentPreviewItem()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "refreshCurrentPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1currentPreviewItemIndex/title",
          "value": "currentPreviewItemIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1currentPreviewItemIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentPreviewItemIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1currentController/title",
          "value": "currentController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1currentController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem/title",
          "value": "QLPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserInterfaceValidations/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserInterfaceValidations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1updateController()/title",
          "value": "updateController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1updateController()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1isInFullScreenMode/title",
          "value": "inFullScreenMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1isInFullScreenMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inFullScreenMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAppearanceCustomization/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAppearanceCustomization"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1shared()/title",
          "value": "sharedPreviewPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1shared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedPreviewPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1currentPreviewItem/title",
          "value": "currentPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1currentPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibilityElement/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibilityElement/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel/title",
          "value": "QLPreviewPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1enterFullScreenMode(_:withOptions:)/title",
          "value": "enterFullScreenMode:withOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1enterFullScreenMode(_:withOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enterFullScreenMode:withOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView/title",
          "value": "QLPreviewView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibility/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibility/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
