{"seeAlsoSections":[{"anchor":"Responding-to-view-controller-transition-progress","generated":true,"title":"Responding to view controller transition progress","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animateAlongsideTransition(in:animation:completion:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionChanges(_:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionEnds(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"alongsideTransition"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animation"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","text":"UIViewControllerTransitionCoordinatorContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","text":"Void"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","text":"UIViewControllerTransitionCoordinatorContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A block containing the animations you want to perform. These animations run in the same context as the transition animations and therefore have the same default attributes. You may specify ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for this parameter.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The block has no return value and takes the following parameter:","type":"text"}]},{"items":[{"term":{"inlineContent":[{"type":"text","text":"context"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The contextual information for performing the animations. Use this object to get the animation-related information, including the container view in which to run your animations. For more information, see "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","isActive":true,"type":"reference"},{"type":"text","text":"."}]}]}}],"type":"termList"},{"type":"paragraph","inlineContent":[{"text":"The animation you specify must take place in a view descended from the container view.","type":"text"}]}],"name":"animation"},{"content":[{"inlineContent":[{"type":"text","text":"The block of code to execute after the transition finishes. You may specify "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter. The block has no return value and takes the following parameter:"}],"type":"paragraph"},{"items":[{"term":{"inlineContent":[{"type":"text","text":"context"}]},"definition":{"content":[{"inlineContent":[{"type":"text","text":"The contextual information for performing the animations. Use this object to get the animation-related information, including the container view in which to run your animations. For more information, see "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"},{"type":"text","text":"."}],"type":"paragraph"}]}}],"type":"termList"}],"name":"completion"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" if the animations were successfully queued to run or ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"text":" if they were not.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Use this method to perform animations that aren’t handled by the animator objects themselves. All of the animations you specify must occur inside the animation context’s container view (or one of its descendants). Use the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/containerView","type":"reference"},{"text":" property of the context object to get the container view. To perform animations in a view that doesn’t descend from the container view, use the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animateAlongsideTransition(in:animation:completion:)","type":"reference"},{"text":" method instead.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The animations in the "},{"type":"codeVoice","code":"animation"},{"type":"text","text":" parameter are normally performed concurrently with the view controller transition animations. That behavior applies when the animator object’s "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning/animateTransition(using:)","isActive":true},{"type":"text","text":" method is implemented using "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","isActive":true},{"type":"text","text":"-based animations. If the animator object uses Core Animation to animate the layer contents directly, your animations are run shortly after the animateTransition: method returns."}],"type":"paragraph"},{"inlineContent":[{"text":"This method returns ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":" when the block in the ","type":"text"},{"code":"animation","type":"codeVoice"},{"text":" parameter can’t be queued to run. The completion block can still run even when this method returns ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Runs the specified animations at the same time as the view controller transition animations.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiviewcontrollertransitioncoordinator/animate(alongsidetransition:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiviewcontrollertransitioncoordinator/animate(alongsidetransition:completion:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animate(alongsideTransition:completion:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"alongsideTransition"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinatorContext","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((any "},{"text":"UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"animate(alongsideTransition:completion:)","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"}],"required":true,"roleHeading":"Instance Method","modules":[{"name":"UIKit"}],"role":"symbol","externalID":"c:objc(pl)UIViewControllerTransitionCoordinator(im)animateAlongsideTransition:completion:","symbolKind":"method","navigatorTitle":[{"text":"animateAlongsideTransition:completion:","kind":"identifier"}]},"references":{"doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning/animateTransition(using:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning/animateTransition(using:)","type":"topic","url":"/documentation/uikit/uiviewcontrolleranimatedtransitioning/animatetransition(using:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","kind":"typeIdentifier","text":"UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"title":"animateTransition(using:)","abstract":[{"text":"Tells your animator object to perform the transition animations.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"animateTransition:"}]},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext","role":"symbol","title":"UIViewControllerTransitionCoordinatorContext","abstract":[{"type":"text","text":"A set of methods that provides information about an in-progress view controller transition."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animateAlongsideTransition(in:animation:completion:)":{"type":"topic","title":"animateAlongsideTransition(in:animation:completion:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animateAlongsideTransition(in:animation:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animateAlongsideTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"animation"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinatorContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"text":": ((any ","kind":"text"},{"text":"UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Runs the specified animations in a view that’s outside of the designated container view.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"animateAlongsideTransitionInView:animation:completion:"}],"url":"/documentation/uikit/uiviewcontrollertransitioncoordinator/animatealongsidetransition(in:animation:completion:)"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionChanges(_:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionChanges(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifyWhenInteractionChangesUsingBlock:"}],"required":true,"url":"/documentation/uikit/uiviewcontrollertransitioncoordinator/notifywheninteractionchanges(_:)","role":"symbol","title":"notifyWhenInteractionChanges(_:)","abstract":[{"type":"text","text":"Registers a block to be executed when a transition changes from interactive to non-interactive."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyWhenInteractionChanges"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinatorContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/containerView":{"kind":"symbol","url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/containerview","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/containerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"abstract":[{"text":"Returns the view in which the transition takes place.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"containerView"}],"title":"containerView","role":"symbol","type":"topic","required":true},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}],"type":"topic","url":"/documentation/uikit/uiviewcontrollertransitioncoordinator","title":"UIViewControllerTransitionCoordinator","abstract":[{"text":"A set of methods that provides support for animations associated with a view controller transition.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}]},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animate(alongsideTransition:completion:)":{"type":"topic","title":"animate(alongsideTransition:completion:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animate(alongsideTransition:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"alongsideTransition","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"UIViewControllerTransitionCoordinatorContext","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"text":"Runs the specified animations at the same time as the view controller transition animations.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"animateAlongsideTransition:completion:"}],"url":"/documentation/uikit/uiviewcontrollertransitioncoordinator/animate(alongsidetransition:completion:)"},"doc://com.externally.resolved.symbol/s:s4Voida":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Void"},{"kind":"text","text":" = ()"}],"abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}],"title":"Void","url":"/documentation/Swift/Void","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s4Voida"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionEnds(_:)":{"type":"topic","title":"notifyWhenInteractionEnds(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionEnds(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyWhenInteractionEnds","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"UIViewControllerTransitionCoordinatorContext","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"text":"Registers a block to be executed when a transition changes from interactive to non-interactive.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"notifyWhenInteractionEndsUsingBlock:"}],"deprecated":true,"url":"/documentation/uikit/uiviewcontrollertransitioncoordinator/notifywheninteractionends(_:)"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIView":{"title":"UIView","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","abstract":[{"text":"An object that manages the content for a rectangular area on the screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UIView","kind":"identifier"}],"url":"/documentation/uikit/uiview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"deprecated":false,"name":"tvOS"},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"animateAlongsideTransition:completion:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"animateAlongsideTransition:completion:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator"]]}},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Responding to view controller transition progress","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animateAlongsideTransition(in:animation:completion:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionChanges(_:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionEnds(_:)"],"anchor":"Responding-to-view-controller-transition-progress"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"animateAlongsideTransition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","text":"id<UIViewControllerTransitionCoordinatorContext>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerTransitionCoordinatorContext"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"animation"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UIViewControllerTransitionCoordinatorContext","text":"id<UIViewControllerTransitionCoordinatorContext>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"animation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block containing the animations you want to perform. These animations run in the same context as the transition animations and therefore have the same default attributes. You may specify "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The block has no return value and takes the following parameter:"}]},{"type":"termList","items":[{"term":{"inlineContent":[{"text":"context","type":"text"}]},"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The contextual information for performing the animations. Use this object to get the animation-related information, including the container view in which to run your animations. For more information, see "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"},{"type":"text","text":"."}]}]}}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The animation you specify must take place in a view descended from the container view."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The block of code to execute after the transition finishes. You may specify "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for this parameter. The block has no return value and takes the following parameter:"}],"type":"paragraph"},{"items":[{"definition":{"content":[{"inlineContent":[{"type":"text","text":"The contextual information for performing the animations. Use this object to get the animation-related information, including the container view in which to run your animations. For more information, see "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},"term":{"inlineContent":[{"type":"text","text":"context"}]}}],"type":"termList"}]}],"kind":"parameters"},"op":"replace"},{"value":{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"type":"text","text":" if the animations were successfully queued to run or "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true},{"type":"text","text":" if they were not."}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/2","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning~1animateTransition(using:)/title","value":"animateTransition:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning~1animateTransition(using:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"animateTransition:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/title","value":"UIViewControllerTransitionCoordinatorContext","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/fragments","value":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/navigatorTitle","value":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1animateAlongsideTransition(in:animation:completion:)/title","value":"animateAlongsideTransitionInView:animation:completion:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1animateAlongsideTransition(in:animation:completion:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"animateAlongsideTransitionInView:animation:completion:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1notifyWhenInteractionChanges(_:)/title","value":"notifyWhenInteractionChangesUsingBlock:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1notifyWhenInteractionChanges(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"notifyWhenInteractionChangesUsingBlock:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1containerView/title","value":"containerView","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1containerView/fragments","value":[{"kind":"identifier","text":"containerView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator/title","value":"UIViewControllerTransitionCoordinator","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator/fragments","value":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator/navigatorTitle","value":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1animate(alongsideTransition:completion:)/title","value":"animateAlongsideTransition:completion:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1animate(alongsideTransition:completion:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"animateAlongsideTransition:completion:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1notifyWhenInteractionEnds(_:)/title","value":"notifyWhenInteractionEndsUsingBlock:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1notifyWhenInteractionEnds(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notifyWhenInteractionEndsUsingBlock:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title","value":"UIView","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments","value":[{"kind":"identifier","text":"UIView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle","value":[{"kind":"identifier","text":"UIView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}