{
  "abstract": [
    {
      "text": "A window that presents the system’s HomePod configuration view to the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediasetup/documentation/MediaSetup",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext/presentationAnchor()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MSAuthenticationPresentationContext(im)presentationAnchor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "presentationAnchor"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MSPresentationAnchor",
        "text": "MSPresentationAnchor"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Media Setup"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "presentationAnchor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "presentationAnchor()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "presentationAnchor"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSPresentationAnchor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MSPresentationAnchor",
              "text": "MSPresentationAnchor"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Return-Value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The interface element in your app that the system uses to display HomePod configuration information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup": {
      "abstract": [
        {
          "text": "Enable users to configure HomePod speakers to stream music directly from your media service.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Setup",
      "type": "topic",
      "url": "/documentation/mediasetup"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext": {
      "abstract": [
        {
          "text": "A protocol that provides media setup display information to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSAuthenticationPresentationContext"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSAuthenticationPresentationContext"
        }
      ],
      "role": "symbol",
      "title": "MSAuthenticationPresentationContext",
      "type": "topic",
      "url": "/documentation/mediasetup/msauthenticationpresentationcontext"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext/presentationAnchor()": {
      "abstract": [
        {
          "text": "A window that presents the system’s HomePod configuration view to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationAnchor"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MSPresentationAnchor",
          "text": "MSPresentationAnchor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext/presentationAnchor()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationAnchor"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "presentationAnchor()",
      "type": "topic",
      "url": "/documentation/mediasetup/msauthenticationpresentationcontext/presentationanchor()"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSPresentationAnchor": {
      "abstract": [
        {
          "text": "A window that presents a Media Setup configuration view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSPresentationAnchor"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSPresentationAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSPresentationAnchor"
        }
      ],
      "role": "symbol",
      "title": "MSPresentationAnchor",
      "type": "topic",
      "url": "/documentation/mediasetup/mspresentationanchor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Displaying-the-Media-Setup-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSPresentationAnchor"
      ],
      "title": "Displaying the Media Setup View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "presentationAnchor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentationAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediasetup/documentation/MediaSetup",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Displaying-the-Media-Setup-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSPresentationAnchor"
              ],
              "title": "Displaying the Media Setup View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSPresentationAnchor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MSPresentationAnchor",
                    "text": "MSPresentationAnchor"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "presentationAnchor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext~1presentationAnchor()/title",
          "value": "presentationAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext~1presentationAnchor()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentationAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext/title",
          "value": "MSAuthenticationPresentationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSAuthenticationPresentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSAuthenticationPresentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSPresentationAnchor/title",
          "value": "MSPresentationAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSPresentationAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSPresentationAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSPresentationAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSPresentationAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediasetup/msauthenticationpresentationcontext/presentationanchor()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediasetup/msauthenticationpresentationcontext/presentationanchor()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
