{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/other"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextMovement@NSTextMovementOther",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "other"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextMovementOther"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTextMovement.other"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "other"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextMovement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/backtab": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backtab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/backtab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementBacktab"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.backtab",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/backtab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/cancel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/cancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementCancel"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.cancel",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/cancel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/down": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementDown"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.down",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/down"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/left": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementLeft"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.left",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/left"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/other": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementOther"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.other",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/other"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/return": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`return`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/return",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementReturn"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.return",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/return"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/right": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementRight"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.right",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/right"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/tab": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/tab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementTab"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.tab",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/tab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/up": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementUp"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.up",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/up"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Movement-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/return",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/tab",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/backtab",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/left",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/right",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/up",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/down",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/cancel"
      ],
      "title": "Movement Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextMovementOther"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Movement-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/return",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/tab",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/backtab",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/left",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/right",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/up",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/down",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/cancel"
              ],
              "title": "Movement Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTextMovementOther"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1backtab/title",
          "value": "NSTextMovementBacktab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1backtab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementBacktab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1return/title",
          "value": "NSTextMovementReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1return/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1right/title",
          "value": "NSTextMovementRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1cancel/title",
          "value": "NSTextMovementCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1cancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1down/title",
          "value": "NSTextMovementDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1other/title",
          "value": "NSTextMovementOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1left/title",
          "value": "NSTextMovementLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement/title",
          "value": "NSTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1up/title",
          "value": "NSTextMovementUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1tab/title",
          "value": "NSTextMovementTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1tab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementTab"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextmovement/other"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextmovement/other"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
