{
  "abstract": [
    {
      "text": "Returns the range of the line fragment that contains the point you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/lineFragmentRange(for:inContainerAt:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTextSelectionDataSource(im)lineFragmentRangeForPoint:inContainerAtLocation:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lineFragmentRange"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGPoint",
        "text": "CGPoint"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "inContainerAt"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)NSTextLocation",
        "text": "NSTextLocation"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTextRange",
        "text": "NSTextRange"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "lineFragmentRangeForPoint:inContainerAtLocation:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "lineFragmentRange(for:inContainerAt:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lineFragmentRange"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "point"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGPoint",
              "text": "CGPoint"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "inContainerAt"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "location"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSTextLocation",
              "text": "NSTextLocation"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTextRange",
              "text": "NSTextRange"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The starting point that contains the line fragment, in the coordinate system of ",
                  "type": "text"
                },
                {
                  "code": "location",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "point"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The location of the line fragment.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "location"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "code": "NSTextRange",
              "type": "codeVoice"
            },
            {
              "text": " that describes the location of the line fragment, or nil if the range isn’t found.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLocation": {
      "abstract": [
        {
          "text": "An interface you implement that represents an abstract location inside your document’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLocation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLocation"
        }
      ],
      "role": "symbol",
      "title": "NSTextLocation",
      "type": "topic",
      "url": "/documentation/uikit/nstextlocation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextRange": {
      "abstract": [
        {
          "text": "A class that represents a contiguous range between two locations inside document contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextRange"
        }
      ],
      "role": "symbol",
      "title": "NSTextRange",
      "type": "topic",
      "url": "/documentation/uikit/nstextrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource": {
      "abstract": [
        {
          "text": "A set of methods that objects implement to provide data for, and manage text selections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSelectionDataSource"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionDataSource"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionDataSource",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/lineFragmentRange(for:inContainerAt:)": {
      "abstract": [
        {
          "text": "Returns the range of the line fragment that contains the point you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineFragmentRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inContainerAt"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/lineFragmentRange(for:inContainerAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineFragmentRangeForPoint:inContainerAtLocation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lineFragmentRange(for:inContainerAt:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/linefragmentrange(for:incontainerat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/location(_:offsetBy:)": {
      "abstract": [
        {
          "text": "Returns a new location using the location and offset you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offsetBy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/location(_:offsetBy:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationFromLocation:withOffset:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "location(_:offsetBy:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/location(_:offsetby:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/offset(from:to:)": {
      "abstract": [
        {
          "text": "Returns the offset between the two locations you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/offset(from:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offsetFromLocation:toLocation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "offset(from:to:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/offset(from:to:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textRange(for:enclosing:)": {
      "abstract": [
        {
          "text": "Returns a text range that corresponds to selection granularity of the enclosing location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelection",
          "text": "NSTextSelection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionGranularity",
          "text": "Granularity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "enclosing"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textRange(for:enclosing:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textRangeForSelectionGranularity:enclosingLocation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "textRange(for:enclosing:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/textrange(for:enclosing:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGPoint": {
      "abstract": [
        {
          "text": "A structure that contains a point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPoint",
      "type": "topic",
      "url": "/documentation/corefoundation/cgpoint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Finding-specific-content-in-the-selection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/location(_:offsetBy:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/offset(from:to:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textRange(for:enclosing:)"
      ],
      "title": "Finding specific content in the selection"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "lineFragmentRangeForPoint:inContainerAtLocation:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lineFragmentRangeForPoint:inContainerAtLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Finding-specific-content-in-the-selection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/location(_:offsetBy:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/offset(from:to:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textRange(for:enclosing:)"
              ],
              "title": "Finding specific content in the selection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSTextRange",
                    "text": "NSTextRange"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "lineFragmentRangeForPoint:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGPoint",
                    "text": "CGPoint"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "point"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "inContainerAtLocation:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)NSTextLocation",
                    "text": "id<NSTextLocation>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "location"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The starting point that contains the line fragment, in the coordinate system of ",
                        "type": "text"
                      },
                      {
                        "code": "location",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "point"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The location of the line fragment.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "location"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An ",
                    "type": "text"
                  },
                  {
                    "code": "NSTextRange",
                    "type": "codeVoice"
                  },
                  {
                    "text": " that describes the location of the line fragment, or nil if the range isn’t found.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLocation/title",
          "value": "NSTextLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1offset(from:to:)/title",
          "value": "offsetFromLocation:toLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1offset(from:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "offsetFromLocation:toLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1textRange(for:enclosing:)/title",
          "value": "textRangeForSelectionGranularity:enclosingLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1textRange(for:enclosing:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textRangeForSelectionGranularity:enclosingLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1location(_:offsetBy:)/title",
          "value": "locationFromLocation:withOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1location(_:offsetBy:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationFromLocation:withOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1lineFragmentRange(for:inContainerAt:)/title",
          "value": "lineFragmentRangeForPoint:inContainerAtLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1lineFragmentRange(for:inContainerAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lineFragmentRangeForPoint:inContainerAtLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource/title",
          "value": "NSTextSelectionDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange/title",
          "value": "NSTextRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextselectiondatasource/linefragmentrange(for:incontainerat:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextselectiondatasource/linefragmentrange(for:incontainerat:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
