{
  "abstract": [
    {
      "text": "Specifies the camera on the front of the device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController",
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum/front"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIImagePickerControllerCameraDevice@UIImagePickerControllerCameraDeviceFront",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "front"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIImagePickerControllerCameraDeviceFront"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIImagePickerController.CameraDevice.front"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "front"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController": {
      "abstract": [
        {
          "text": "A view controller that manages the system interfaces for taking pictures, recording movies, and choosing items from the user’s media library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImagePickerController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerController"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the camera to use for image or movie capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CameraDevice"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CameraDevice"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.CameraDevice",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/cameradevice-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum/front": {
      "abstract": [
        {
          "text": "Specifies the camera on the front of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "front"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum/front",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerControllerCameraDeviceFront"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.CameraDevice.front",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/cameradevice-swift.enum/front"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum/rear": {
      "abstract": [
        {
          "text": "Specifies the camera on the rear of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rear"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum/rear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerControllerCameraDeviceRear"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.CameraDevice.rear",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/cameradevice-swift.enum/rear"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum/rear"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIImagePickerControllerCameraDeviceFront"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerCameraDeviceFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/CameraDevice-swift.enum/rear"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIImagePickerControllerCameraDeviceFront"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1CameraDevice-swift.enum/title",
          "value": "UIImagePickerControllerCameraDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1CameraDevice-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerCameraDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1CameraDevice-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerCameraDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1CameraDevice-swift.enum~1rear/title",
          "value": "UIImagePickerControllerCameraDeviceRear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1CameraDevice-swift.enum~1rear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerCameraDeviceRear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1CameraDevice-swift.enum~1front/title",
          "value": "UIImagePickerControllerCameraDeviceFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1CameraDevice-swift.enum~1front/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerCameraDeviceFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController/title",
          "value": "UIImagePickerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiimagepickercontroller/cameradevice-swift.enum/front"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiimagepickercontroller/cameradevice-swift.enum/front"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
