{
  "abstract": [
    {
      "text": "Reports to the provider that an outgoing call with the specified unique identifier finished connecting at a particular time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:connectedAt:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CXProvider(im)reportOutgoingCallWithUUID:connectedAtDate:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "reportOutgoingCall"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4UUIDV",
        "text": "UUID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "connectedAt"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DateV",
        "text": "Date"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "reportOutgoingCallWithUUID:connectedAtDate:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "reportOutgoingCall(with:connectedAt:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reportOutgoingCall"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "UUID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4UUIDV",
              "text": "UUID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "connectedAt"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "dateConnected"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DateV",
              "text": "Date"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The unique identifier of the call.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "UUID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time at which the call connected. A call is considered connected when both caller and callee can start communicating.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ", the current time is used.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "dateConnected"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An outgoing call should call this method after calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:startedConnectingAt:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and after the call is connected.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider": {
      "abstract": [
        {
          "text": "An object that represents a telephony provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXProvider"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXProvider"
        }
      ],
      "role": "symbol",
      "title": "CXProvider",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:endedAt:reason:)": {
      "abstract": [
        {
          "text": "Reports to the provider that a call with the specified identifier ended at a given date for a particular reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endedAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXCallEndedReason",
          "text": "CXCallEndedReason"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:endedAt:reason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportCallWithUUID:endedAtDate:reason:"
        }
      ],
      "role": "symbol",
      "title": "reportCall(with:endedAt:reason:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportcall(with:endedat:reason:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)": {
      "abstract": [
        {
          "text": "Reports to the provider that an active call updated its information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "updated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallUpdate",
          "text": "CXCallUpdate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportCallWithUUID:updated:"
        }
      ],
      "role": "symbol",
      "title": "reportCall(with:updated:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportcall(with:updated:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)": {
      "abstract": [
        {
          "text": "Reports a new incoming call with the specified unique identifier to the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportNewIncomingCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "update"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallUpdate",
          "text": "CXCallUpdate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportNewIncomingCallWithUUID:update:completion:"
        }
      ],
      "role": "symbol",
      "title": "reportNewIncomingCall(with:update:completion:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportnewincomingcall(with:update:completion:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingVoIPPushPayload(_:completion:)": {
      "abstract": [
        {
          "text": "Reports a new incoming call after your notification service extension decrypts a VoIP call request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportNewIncomingVoIPPushPayload"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingVoIPPushPayload(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportNewIncomingVoIPPushPayload:completion:"
        }
      ],
      "role": "symbol",
      "title": "reportNewIncomingVoIPPushPayload(_:completion:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportnewincomingvoippushpayload(_:completion:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:connectedAt:)": {
      "abstract": [
        {
          "text": "Reports to the provider that an outgoing call with the specified unique identifier finished connecting at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportOutgoingCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "connectedAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:connectedAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportOutgoingCallWithUUID:connectedAtDate:"
        }
      ],
      "role": "symbol",
      "title": "reportOutgoingCall(with:connectedAt:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportoutgoingcall(with:connectedat:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:startedConnectingAt:)": {
      "abstract": [
        {
          "text": "Reports to the provider that an outgoing call with the specified unique identifier started connecting at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportOutgoingCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startedConnectingAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:startedConnectingAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportOutgoingCallWithUUID:startedConnectingAtDate:"
        }
      ],
      "role": "symbol",
      "title": "reportOutgoingCall(with:startedConnectingAt:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportoutgoingcall(with:startedconnectingat:)"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering": {
      "abstract": [
        {
          "text": "Enable receiving notifications without displaying the notification to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.usernotifications.filtering",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DateV": {
      "abstract": [
        {
          "text": "A specific point in time, independent of any calendar or time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Date",
      "type": "topic",
      "url": "/documentation/foundation/date"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV": {
      "abstract": [
        {
          "text": "A universally unique value to identify types, interfaces, and other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UUID",
      "type": "topic",
      "url": "/documentation/foundation/uuid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reporting-Calls",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingVoIPPushPayload(_:completion:)",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:startedConnectingAt:)",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:endedAt:reason:)"
      ],
      "title": "Reporting Calls"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "reportOutgoingCallWithUUID:connectedAtDate:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportOutgoingCallWithUUID:connectedAtDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reporting-Calls",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingVoIPPushPayload(_:completion:)",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:startedConnectingAt:)",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:endedAt:reason:)"
              ],
              "title": "Reporting Calls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "reportOutgoingCallWithUUID:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSUUID",
                    "text": "NSUUID"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "UUID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "connectedAtDate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDate",
                    "text": "NSDate"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "dateConnected"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The unique identifier of the call.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "UUID"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The time at which the call connected. A call is considered connected when both caller and callee can start communicating.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "If ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", the current time is used.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "dateConnected"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:updated:)/title",
          "value": "reportCallWithUUID:updated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:updated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportCallWithUUID:updated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingCall(with:update:completion:)/title",
          "value": "reportNewIncomingCallWithUUID:update:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingCall(with:update:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportNewIncomingCallWithUUID:update:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportOutgoingCall(with:startedConnectingAt:)/title",
          "value": "reportOutgoingCallWithUUID:startedConnectingAtDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportOutgoingCall(with:startedConnectingAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportOutgoingCallWithUUID:startedConnectingAtDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingVoIPPushPayload(_:completion:)/title",
          "value": "reportNewIncomingVoIPPushPayload:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingVoIPPushPayload(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "reportNewIncomingVoIPPushPayload:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:endedAt:reason:)/title",
          "value": "reportCallWithUUID:endedAtDate:reason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:endedAt:reason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportCallWithUUID:endedAtDate:reason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportOutgoingCall(with:connectedAt:)/title",
          "value": "reportOutgoingCallWithUUID:connectedAtDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportOutgoingCall(with:connectedAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportOutgoingCallWithUUID:connectedAtDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider/title",
          "value": "CXProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxprovider/reportoutgoingcall(with:connectedat:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxprovider/reportoutgoingcall(with:connectedat:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
