{
  "abstract": [
    {
      "text": "A status indicating that the tag supports reading and writing NDEF message data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readWrite"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NFCNDEFStatus@NFCNDEFStatusReadWrite",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "readWrite"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCNDEFStatusReadWrite"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NFCNDEFStatus.readWrite"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "readWrite"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus": {
      "abstract": [
        {
          "text": "Constants that indicate status for an NDEF tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFStatus"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFStatus"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFStatus",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefstatus"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/notSupported": {
      "abstract": [
        {
          "text": "A status indicating that that tag isn’t an NDEF-formatted tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFStatusNotSupported"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFStatus.notSupported",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefstatus/notsupported"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readOnly": {
      "abstract": [
        {
          "text": "A status indicating that the tag supports reading NDEF message data only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readOnly"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFStatusReadOnly"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFStatus.readOnly",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefstatus/readonly"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readWrite": {
      "abstract": [
        {
          "text": "A status indicating that the tag supports reading and writing NDEF message data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readWrite"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFStatusReadWrite"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFStatus.readWrite",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefstatus/readwrite"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Statuses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/notSupported",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readOnly"
      ],
      "title": "Statuses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCNDEFStatusReadWrite"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFStatusReadWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Statuses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/notSupported",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readOnly"
              ],
              "title": "Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NFCNDEFStatusReadWrite"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus~1notSupported/title",
          "value": "NFCNDEFStatusNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFStatusNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus/title",
          "value": "NFCNDEFStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus~1readOnly/title",
          "value": "NFCNDEFStatusReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus~1readOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFStatusReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus~1readWrite/title",
          "value": "NFCNDEFStatusReadWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus~1readWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFStatusReadWrite"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcndefstatus/readwrite"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcndefstatus/readwrite"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
