{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerSidebar/scrollToTarget:animated:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITabBarControllerSidebar(im)scrollToTarget:animated:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "scrollToTarget:animated:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "scrollToTarget:animated:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "scrollToTarget:animated:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "scrollToTarget:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabSidebarScrollTarget",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITabSidebarScrollTarget",
              "text": "UITabSidebarScrollTarget"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "target"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "animated:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "animated"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class": {
      "abstract": [
        {
          "text": "An object for managing and configuring the sidebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sidebar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/Sidebar-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Sidebar"
        }
      ],
      "role": "symbol",
      "title": "UITabBarController.Sidebar",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/sidebar-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerSidebar/scrollToTarget:animated:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "scrollToTarget:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerSidebar/scrollToTarget:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollToTarget:animated:"
        }
      ],
      "role": "symbol",
      "title": "scrollToTarget:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollersidebar/scrolltotarget:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabSidebarScrollTarget": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITabSidebarScrollTarget"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabSidebarScrollTarget",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITabSidebarScrollTarget",
      "type": "topic",
      "url": "/documentation/uikit/uitabsidebarscrolltarget"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class/title",
          "value": "UITabBarControllerSidebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerSidebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1Sidebar-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerSidebar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitabbarcontrollersidebar/scrolltotarget:animated:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
