{
  "abstract": [
    {
      "text": "Tells the delegate that the Wi-Fi power state changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/powerStateDidChangeForWiFiInterface(withName:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CWEventDelegate(im)powerStateDidChangeForWiFiInterfaceWithName:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "powerStateDidChangeForWiFiInterface"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "powerStateDidChangeForWiFiInterfaceWithName:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "powerStateDidChangeForWiFiInterface(withName:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "powerStateDidChangeForWiFiInterface"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "interfaceName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the Wi-Fi interface on which the power changed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "interfaceName"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Register for power state change notifications by sending the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient/startMonitoringEvent(with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " message to a Wi-Fi client object with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " event type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the Wi-Fi interface’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/powerOn()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to query the current Wi-Fi power state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate": {
      "abstract": [
        {
          "text": "The interface a Wi-Fi client object uses to notify its delegate about Wi-Fi events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWEventDelegate"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventDelegate"
        }
      ],
      "role": "symbol",
      "title": "CWEventDelegate",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/bssidDidChangeForWiFiInterface(withName:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the current BSSID has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bssidDidChangeForWiFiInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/bssidDidChangeForWiFiInterface(withName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bssidDidChangeForWiFiInterfaceWithName:"
        }
      ],
      "role": "symbol",
      "title": "bssidDidChangeForWiFiInterface(withName:)",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/bssiddidchangeforwifiinterface(withname:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/clientConnectionInterrupted()": {
      "abstract": [
        {
          "text": "Tells the delegate that the connection to the Wi-Fi subsystem is temporarily interrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientConnectionInterrupted"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/clientConnectionInterrupted()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientConnectionInterrupted"
        }
      ],
      "role": "symbol",
      "title": "clientConnectionInterrupted()",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/clientconnectioninterrupted()"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/clientConnectionInvalidated()": {
      "abstract": [
        {
          "text": "Tells the delegate that the connection to the Wi-Fi subsystem is permanently invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientConnectionInvalidated"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/clientConnectionInvalidated()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientConnectionInvalidated"
        }
      ],
      "role": "symbol",
      "title": "clientConnectionInvalidated()",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/clientconnectioninvalidated()"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/countryCodeDidChangeForWiFiInterface(withName:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the currently adopted country code has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countryCodeDidChangeForWiFiInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/countryCodeDidChangeForWiFiInterface(withName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "countryCodeDidChangeForWiFiInterfaceWithName:"
        }
      ],
      "role": "symbol",
      "title": "countryCodeDidChangeForWiFiInterface(withName:)",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/countrycodedidchangeforwifiinterface(withname:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/linkDidChangeForWiFiInterface(withName:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the Wi-Fi link state changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkDidChangeForWiFiInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/linkDidChangeForWiFiInterface(withName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkDidChangeForWiFiInterfaceWithName:"
        }
      ],
      "role": "symbol",
      "title": "linkDidChangeForWiFiInterface(withName:)",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/linkdidchangeforwifiinterface(withname:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/linkQualityDidChangeForWiFiInterface(withName:rssi:transmitRate:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the link quality has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkQualityDidChangeForWiFiInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rssi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transmitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/linkQualityDidChangeForWiFiInterface(withName:rssi:transmitRate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkQualityDidChangeForWiFiInterfaceWithName:rssi:transmitRate:"
        }
      ],
      "role": "symbol",
      "title": "linkQualityDidChangeForWiFiInterface(withName:rssi:transmitRate:)",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/linkqualitydidchangeforwifiinterface(withname:rssi:transmitrate:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/modeDidChangeForWiFiInterface(withName:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the operating mode has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modeDidChangeForWiFiInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/modeDidChangeForWiFiInterface(withName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modeDidChangeForWiFiInterfaceWithName:"
        }
      ],
      "role": "symbol",
      "title": "modeDidChangeForWiFiInterface(withName:)",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/modedidchangeforwifiinterface(withname:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/powerStateDidChangeForWiFiInterface(withName:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the Wi-Fi power state changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerStateDidChangeForWiFiInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/powerStateDidChangeForWiFiInterface(withName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "powerStateDidChangeForWiFiInterfaceWithName:"
        }
      ],
      "role": "symbol",
      "title": "powerStateDidChangeForWiFiInterface(withName:)",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/powerstatedidchangeforwifiinterface(withname:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/scanCacheUpdatedForWiFiInterface(withName:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the Wi-Fi interface’s scan cache has been updated with new results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanCacheUpdatedForWiFiInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/scanCacheUpdatedForWiFiInterface(withName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scanCacheUpdatedForWiFiInterfaceWithName:"
        }
      ],
      "role": "symbol",
      "title": "scanCacheUpdatedForWiFiInterface(withName:)",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/scancacheupdatedforwifiinterface(withname:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/ssidDidChangeForWiFiInterface(withName:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the current SSID has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssidDidChangeForWiFiInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/ssidDidChangeForWiFiInterface(withName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ssidDidChangeForWiFiInterfaceWithName:"
        }
      ],
      "role": "symbol",
      "title": "ssidDidChangeForWiFiInterface(withName:)",
      "type": "topic",
      "url": "/documentation/corewlan/cweventdelegate/ssiddidchangeforwifiinterface(withname:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange": {
      "abstract": [
        {
          "text": "Posts when the power state of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypePowerDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.powerDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/powerdidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/powerOn()": {
      "abstract": [
        {
          "text": "The interface power state is set to “ON”.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerOn"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/powerOn()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "powerOn"
        }
      ],
      "role": "symbol",
      "title": "powerOn()",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterface/poweron()"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient/startMonitoringEvent(with:)": {
      "abstract": [
        {
          "text": "Register for specific Wi-Fi event notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMonitoringEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CWEventType",
          "text": "CWEventType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient/startMonitoringEvent(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMonitoringEventWithType:error:"
        }
      ],
      "role": "symbol",
      "title": "startMonitoringEvent(with:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwwificlient/startmonitoringevent(with:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/bssidDidChangeForWiFiInterface(withName:)",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/clientConnectionInterrupted()",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/clientConnectionInvalidated()",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/countryCodeDidChangeForWiFiInterface(withName:)",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/linkDidChangeForWiFiInterface(withName:)",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/linkQualityDidChangeForWiFiInterface(withName:rssi:transmitRate:)",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/modeDidChangeForWiFiInterface(withName:)",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/scanCacheUpdatedForWiFiInterface(withName:)",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/ssidDidChangeForWiFiInterface(withName:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "powerStateDidChangeForWiFiInterfaceWithName:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "powerStateDidChangeForWiFiInterfaceWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/bssidDidChangeForWiFiInterface(withName:)",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/clientConnectionInterrupted()",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/clientConnectionInvalidated()",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/countryCodeDidChangeForWiFiInterface(withName:)",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/linkDidChangeForWiFiInterface(withName:)",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/linkQualityDidChangeForWiFiInterface(withName:rssi:transmitRate:)",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/modeDidChangeForWiFiInterface(withName:)",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/scanCacheUpdatedForWiFiInterface(withName:)",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventDelegate/ssidDidChangeForWiFiInterface(withName:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "powerStateDidChangeForWiFiInterfaceWithName:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "interfaceName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name of the Wi-Fi interface on which the power changed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "interfaceName"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1countryCodeDidChangeForWiFiInterface(withName:)/title",
          "value": "countryCodeDidChangeForWiFiInterfaceWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1countryCodeDidChangeForWiFiInterface(withName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "countryCodeDidChangeForWiFiInterfaceWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface~1powerOn()/title",
          "value": "powerOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface~1powerOn()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "powerOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient~1startMonitoringEvent(with:)/title",
          "value": "startMonitoringEventWithType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient~1startMonitoringEvent(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMonitoringEventWithType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1linkQualityDidChangeForWiFiInterface(withName:rssi:transmitRate:)/title",
          "value": "linkQualityDidChangeForWiFiInterfaceWithName:rssi:transmitRate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1linkQualityDidChangeForWiFiInterface(withName:rssi:transmitRate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "linkQualityDidChangeForWiFiInterfaceWithName:rssi:transmitRate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1bssidDidChangeForWiFiInterface(withName:)/title",
          "value": "bssidDidChangeForWiFiInterfaceWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1bssidDidChangeForWiFiInterface(withName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "bssidDidChangeForWiFiInterfaceWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1linkDidChangeForWiFiInterface(withName:)/title",
          "value": "linkDidChangeForWiFiInterfaceWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1linkDidChangeForWiFiInterface(withName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "linkDidChangeForWiFiInterfaceWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1modeDidChangeForWiFiInterface(withName:)/title",
          "value": "modeDidChangeForWiFiInterfaceWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1modeDidChangeForWiFiInterface(withName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "modeDidChangeForWiFiInterfaceWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1clientConnectionInterrupted()/title",
          "value": "clientConnectionInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1clientConnectionInterrupted()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clientConnectionInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1powerStateDidChangeForWiFiInterface(withName:)/title",
          "value": "powerStateDidChangeForWiFiInterfaceWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1powerStateDidChangeForWiFiInterface(withName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "powerStateDidChangeForWiFiInterfaceWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1powerDidChange/title",
          "value": "CWEventTypePowerDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1powerDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypePowerDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate/title",
          "value": "CWEventDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1ssidDidChangeForWiFiInterface(withName:)/title",
          "value": "ssidDidChangeForWiFiInterfaceWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1ssidDidChangeForWiFiInterface(withName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "ssidDidChangeForWiFiInterfaceWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1clientConnectionInvalidated()/title",
          "value": "clientConnectionInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1clientConnectionInvalidated()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clientConnectionInvalidated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1scanCacheUpdatedForWiFiInterface(withName:)/title",
          "value": "scanCacheUpdatedForWiFiInterfaceWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventDelegate~1scanCacheUpdatedForWiFiInterface(withName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scanCacheUpdatedForWiFiInterfaceWithName:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cweventdelegate/powerstatedidchangeforwifiinterface(withname:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cweventdelegate/powerstatedidchangeforwifiinterface(withname:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
