{
  "abstract": [
    {
      "text": "Store pickup of the purchase from the seller’s store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKShippingType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKShippingType/storePickup"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKShippingType@PKShippingTypeStorePickup",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "storePickup"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKShippingTypeStorePickup"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKShippingType.storePickup"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "storePickup"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.passkit/documentation/PassKit/displaying-a-read-only-pickup-address"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShippingType": {
      "abstract": [
        {
          "text": "A complete list of valid shipping types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShippingType"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShippingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShippingType"
        }
      ],
      "role": "symbol",
      "title": "PKShippingType",
      "type": "topic",
      "url": "/documentation/passkit/pkshippingtype"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShippingType/delivery": {
      "abstract": [
        {
          "text": "Delivering the purchase by the seller (for example, pizza, flower, or furniture delivery).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delivery"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShippingType/delivery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShippingTypeDelivery"
        }
      ],
      "role": "symbol",
      "title": "PKShippingType.delivery",
      "type": "topic",
      "url": "/documentation/passkit/pkshippingtype/delivery"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShippingType/servicePickup": {
      "abstract": [
        {
          "text": "Picking up an item from the provided address by the service (for example, transportation or shipping services that provide home pickup).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "servicePickup"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShippingType/servicePickup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShippingTypeServicePickup"
        }
      ],
      "role": "symbol",
      "title": "PKShippingType.servicePickup",
      "type": "topic",
      "url": "/documentation/passkit/pkshippingtype/servicepickup"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShippingType/shipping": {
      "abstract": [
        {
          "text": "Shipping the purchase to the provided address using a third-party shipping company. This is the default shipping type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shipping"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShippingType/shipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShippingTypeShipping"
        }
      ],
      "role": "symbol",
      "title": "PKShippingType.shipping",
      "type": "topic",
      "url": "/documentation/passkit/pkshippingtype/shipping"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShippingType/storePickup": {
      "abstract": [
        {
          "text": "Store pickup of the purchase from the seller’s store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storePickup"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShippingType/storePickup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShippingTypeStorePickup"
        }
      ],
      "role": "symbol",
      "title": "PKShippingType.storePickup",
      "type": "topic",
      "url": "/documentation/passkit/pkshippingtype/storepickup"
    },
    "doc://com.apple.passkit/documentation/PassKit/displaying-a-read-only-pickup-address": {
      "abstract": [
        {
          "text": "Configure a payment request to display a read-only pickup address on the payment sheet.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/displaying-a-read-only-pickup-address",
      "kind": "article",
      "role": "article",
      "title": "Displaying a Read-Only Pickup Address",
      "type": "topic",
      "url": "/documentation/passkit/displaying-a-read-only-pickup-address"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKShippingType/shipping",
        "doc://com.apple.passkit/documentation/PassKit/PKShippingType/delivery",
        "doc://com.apple.passkit/documentation/PassKit/PKShippingType/servicePickup"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKShippingTypeStorePickup"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShippingTypeStorePickup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKShippingType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKShippingType/shipping",
                "doc://com.apple.passkit/documentation/PassKit/PKShippingType/delivery",
                "doc://com.apple.passkit/documentation/PassKit/PKShippingType/servicePickup"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKShippingTypeStorePickup"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType~1storePickup/title",
          "value": "PKShippingTypeStorePickup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType~1storePickup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShippingTypeStorePickup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType~1delivery/title",
          "value": "PKShippingTypeDelivery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType~1delivery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShippingTypeDelivery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType/title",
          "value": "PKShippingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType~1servicePickup/title",
          "value": "PKShippingTypeServicePickup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType~1servicePickup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShippingTypeServicePickup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType~1shipping/title",
          "value": "PKShippingTypeShipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShippingType~1shipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShippingTypeShipping"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkshippingtype/storepickup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkshippingtype/storepickup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
