{
  "abstract": [
    {
      "text": "The joint group names for an animal body pose.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@T@VNAnimalBodyPoseObservationJointsGroupName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JointsGroupName"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JointsGroupName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "VNAnimalBodyPoseObservation.JointsGroupName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JointsGroupName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation": {
      "abstract": [
        {
          "text": "An observation that provides the animal body points the analysis recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservation"
        }
      ],
      "role": "symbol",
      "title": "VNAnimalBodyPoseObservation",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName": {
      "abstract": [
        {
          "text": "The joint names for an animal body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "VNAnimalBodyPoseObservation.JointName",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName": {
      "abstract": [
        {
          "text": "The joint group names for an animal body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointsGroupName"
        }
      ],
      "role": "symbol",
      "title": "VNAnimalBodyPoseObservation.JointsGroupName",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/all": {
      "abstract": [
        {
          "text": "A group name that represents all joints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointsGroupNameAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname/all"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/forelegs": {
      "abstract": [
        {
          "text": "A group name that represents the forelegs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forelegs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/forelegs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointsGroupNameForelegs"
        }
      ],
      "role": "symbol",
      "title": "forelegs",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname/forelegs"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/head": {
      "abstract": [
        {
          "text": "A group name that represents the head.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "head"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/head",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointsGroupNameHead"
        }
      ],
      "role": "symbol",
      "title": "head",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname/head"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/hindlegs": {
      "abstract": [
        {
          "text": "A group name that represents the hindlegs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hindlegs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/hindlegs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointsGroupNameHindlegs"
        }
      ],
      "role": "symbol",
      "title": "hindlegs",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname/hindlegs"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a joint name with the key you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname/init(rawvalue:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/tail": {
      "abstract": [
        {
          "text": "A group name that represents the tail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/tail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointsGroupNameTail"
        }
      ],
      "role": "symbol",
      "title": "tail",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname/tail"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/trunk": {
      "abstract": [
        {
          "text": "A group name that represents the trunk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trunk"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/trunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointsGroupNameTrunk"
        }
      ],
      "role": "symbol",
      "title": "trunk",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname/trunk"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/availableJointGroupNames": {
      "abstract": [
        {
          "text": "The available joint group names in the observation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableJointGroupNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/availableJointGroupNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableJointGroupNames"
        }
      ],
      "role": "symbol",
      "title": "availableJointGroupNames",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/availablejointgroupnames"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/availableJointNames": {
      "abstract": [
        {
          "text": "The names of the available joints in the observation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableJointNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/availableJointNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableJointNames"
        }
      ],
      "role": "symbol",
      "title": "availableJointNames",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/availablejointnames"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/recognizedPoint(_:)": {
      "abstract": [
        {
          "text": "Returns the point for a joint name the observation recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizedPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNRecognizedPoint",
          "text": "VNRecognizedPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/recognizedPoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recognizedPointForJointName:error:"
        }
      ],
      "role": "symbol",
      "title": "recognizedPoint(_:)",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/recognizedpoint(_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/recognizedPoints(_:)": {
      "abstract": [
        {
          "text": "Returns the points for a joint group name the observation recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizedPoints"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNRecognizedPoint",
          "text": "VNRecognizedPoint"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/recognizedPoints(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recognizedPointsForJointsGroupName:error:"
        }
      ],
      "role": "symbol",
      "title": "recognizedPoints(_:)",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/recognizedpoints(_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey": {
      "abstract": [
        {
          "text": "The data type for all recognized-point group keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPointGroupKey",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Points",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/availableJointNames",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/availableJointGroupNames",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/recognizedPoint(_:)",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/recognizedPoints(_:)"
      ],
      "title": "Accessing Points"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Group-Names",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/all",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/forelegs",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/head",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/hindlegs",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/tail",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/trunk"
      ],
      "title": "Getting the Group Names"
    },
    {
      "anchor": "Creating-a-Group-Name",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/init(rawValue:)"
      ],
      "title": "Creating a Group Name"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNAnimalBodyPoseObservationJointsGroupName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Group-Names",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/all",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/forelegs",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/head",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/hindlegs",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/tail",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointsGroupName/trunk"
              ],
              "title": "Getting the Group Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Points",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/availableJointNames",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/availableJointGroupNames",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/recognizedPoint(_:)",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/recognizedPoints(_:)"
              ],
              "title": "Accessing Points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
                    "text": "VNRecognizedPointGroupKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNAnimalBodyPoseObservationJointsGroupName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1forelegs/title",
          "value": "VNAnimalBodyPoseObservationJointsGroupNameForelegs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1forelegs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupNameForelegs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1hindlegs/title",
          "value": "VNAnimalBodyPoseObservationJointsGroupNameHindlegs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1hindlegs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupNameHindlegs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation/title",
          "value": "VNAnimalBodyPoseObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1availableJointNames/title",
          "value": "availableJointNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1availableJointNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableJointNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName/title",
          "value": "VNAnimalBodyPoseObservationJointsGroupName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName/title",
          "value": "VNAnimalBodyPoseObservationJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1recognizedPoints(_:)/title",
          "value": "recognizedPointsForJointsGroupName:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1recognizedPoints(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recognizedPointsForJointsGroupName:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1all/title",
          "value": "VNAnimalBodyPoseObservationJointsGroupNameAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupNameAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1availableJointGroupNames/title",
          "value": "availableJointGroupNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1availableJointGroupNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableJointGroupNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/title",
          "value": "VNRecognizedPointGroupKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1head/title",
          "value": "VNAnimalBodyPoseObservationJointsGroupNameHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1head/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupNameHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1trunk/title",
          "value": "VNAnimalBodyPoseObservationJointsGroupNameTrunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1trunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupNameTrunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1tail/title",
          "value": "VNAnimalBodyPoseObservationJointsGroupNameTail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointsGroupName~1tail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointsGroupNameTail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1recognizedPoint(_:)/title",
          "value": "recognizedPointForJointName:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1recognizedPoint(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recognizedPointForJointName:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnanimalbodyposeobservation/jointsgroupname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
