{
  "abstract": [
    {
      "text": "The strategies that the text system may use to break lines while laying out the paragraph.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/lineBreakStrategy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSMutableParagraphStyle(py)lineBreakStrategy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lineBreakStrategy"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
        "text": "NSParagraphStyle"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSLineBreakStrategy",
        "text": "LineBreakStrategy"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "lineBreakStrategy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "lineBreakStrategy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lineBreakStrategy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
              "text": "NSParagraphStyle"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/LineBreakStrategy-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSLineBreakStrategy",
              "text": "LineBreakStrategy"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Line-break strategies are collections of options the system uses to determine where to break lines in a paragraph. This is different from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/lineBreakMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which controls how to lay out lines of text that don’t fit in a container. The system ignores this property if the paragraph style’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/lineBreakMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property specifies a mode that doesn’t support multiple lines, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLineBreakMode/byClipping",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLineBreakStrategy/NSLineBreakStrategyNone",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSMutableParagraphStyle/tighteningFactorForTruncation": {
      "abstract": [
        {
          "text": "The threshold for using tightening as an alternative to truncation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tighteningFactorForTruncation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSMutableParagraphStyle/tighteningFactorForTruncation",
      "kind": "symbol",
      "role": "symbol",
      "title": "tighteningFactorForTruncation",
      "type": "topic",
      "url": "/documentation/AppKit/NSMutableParagraphStyle/tighteningFactorForTruncation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLineBreakMode/byClipping": {
      "abstract": [
        {
          "text": "The value that indicates lines don’t extend past the edge of the text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byClipping"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLineBreakMode/byClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakByClipping"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode.byClipping",
      "type": "topic",
      "url": "/documentation/uikit/nslinebreakmode/byclipping"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLineBreakStrategy/NSLineBreakStrategyNone": {
      "abstract": [
        {
          "text": "The text system doesn’t use any line-break strategies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLineBreakStrategyNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLineBreakStrategy/NSLineBreakStrategyNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLineBreakStrategyNone",
      "type": "topic",
      "url": "/documentation/uikit/nslinebreakstrategy/nslinebreakstrategynone"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle": {
      "abstract": [
        {
          "text": "An object for changing the values of the subattributes in a paragraph style attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMutableParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMutableParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "NSMutableParagraphStyle",
      "type": "topic",
      "url": "/documentation/uikit/nsmutableparagraphstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/allowsDefaultTighteningForTruncation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system tightens intercharacter spacing before truncating text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDefaultTighteningForTruncation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/allowsDefaultTighteningForTruncation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsDefaultTighteningForTruncation"
        }
      ],
      "role": "symbol",
      "title": "allowsDefaultTighteningForTruncation",
      "type": "topic",
      "url": "/documentation/uikit/nsmutableparagraphstyle/allowsdefaulttighteningfortruncation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/hyphenationFactor": {
      "abstract": [
        {
          "text": "The paragraph’s threshold for hyphenation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hyphenationFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/hyphenationFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hyphenationFactor"
        }
      ],
      "role": "symbol",
      "title": "hyphenationFactor",
      "type": "topic",
      "url": "/documentation/uikit/nsmutableparagraphstyle/hyphenationfactor"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/lineBreakMode": {
      "abstract": [
        {
          "text": "The mode for breaking lines in the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/lineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/nsmutableparagraphstyle/linebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/lineBreakStrategy": {
      "abstract": [
        {
          "text": "The strategies that the text system may use to break lines while laying out the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakStrategy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
          "text": "NSParagraphStyle"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakStrategy",
          "text": "LineBreakStrategy"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/lineBreakStrategy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakStrategy"
        }
      ],
      "role": "symbol",
      "title": "lineBreakStrategy",
      "type": "topic",
      "url": "/documentation/uikit/nsmutableparagraphstyle/linebreakstrategy"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/usesDefaultHyphenation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesDefaultHyphenation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/usesDefaultHyphenation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesDefaultHyphenation"
        }
      ],
      "role": "symbol",
      "title": "usesDefaultHyphenation",
      "type": "topic",
      "url": "/documentation/uikit/nsmutableparagraphstyle/usesdefaulthyphenation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle": {
      "abstract": [
        {
          "text": "The paragraph or ruler attributes for an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle",
      "type": "topic",
      "url": "/documentation/uikit/nsparagraphstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/LineBreakStrategy-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify how the text system breaks lines while laying out paragraphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineBreakStrategy"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/LineBreakStrategy-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineBreakStrategy"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle.LineBreakStrategy",
      "type": "topic",
      "url": "/documentation/uikit/nsparagraphstyle/linebreakstrategy-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/lineBreakMode": {
      "abstract": [
        {
          "text": "The mode for breaking lines in the paragraph that don’t fit within a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/lineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/nsparagraphstyle/linebreakmode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-line-break-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/lineBreakMode",
        "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/hyphenationFactor",
        "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/usesDefaultHyphenation",
        "doc://com.apple.documentation/documentation/AppKit/NSMutableParagraphStyle/tighteningFactorForTruncation",
        "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/allowsDefaultTighteningForTruncation"
      ],
      "title": "Setting line-break information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "lineBreakStrategy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-line-break-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/lineBreakMode",
                "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/hyphenationFactor",
                "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/usesDefaultHyphenation",
                "doc://com.apple.documentation/documentation/AppKit/NSMutableParagraphStyle/tighteningFactorForTruncation",
                "doc://com.apple.uikit/documentation/UIKit/NSMutableParagraphStyle/allowsDefaultTighteningForTruncation"
              ],
              "title": "Setting line-break information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/LineBreakStrategy-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSLineBreakStrategy",
                    "text": "NSLineBreakStrategy"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "lineBreakStrategy"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle/title",
          "value": "NSParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle~1lineBreakMode/title",
          "value": "lineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle~1lineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1lineBreakStrategy/title",
          "value": "lineBreakStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1lineBreakStrategy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1usesDefaultHyphenation/title",
          "value": "usesDefaultHyphenation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1usesDefaultHyphenation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesDefaultHyphenation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1lineBreakMode/title",
          "value": "lineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1lineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1hyphenationFactor/title",
          "value": "hyphenationFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1hyphenationFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hyphenationFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle~1LineBreakStrategy-swift.struct/title",
          "value": "NSLineBreakStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle~1LineBreakStrategy-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle~1LineBreakStrategy-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSMutableParagraphStyle~1tighteningFactorForTruncation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tighteningFactorForTruncation"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLineBreakMode~1byClipping/title",
          "value": "NSLineBreakByClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLineBreakMode~1byClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakByClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1allowsDefaultTighteningForTruncation/title",
          "value": "allowsDefaultTighteningForTruncation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle~1allowsDefaultTighteningForTruncation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsDefaultTighteningForTruncation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle/title",
          "value": "NSMutableParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSMutableParagraphStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableParagraphStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nsmutableparagraphstyle/linebreakstrategy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nsmutableparagraphstyle/linebreakstrategy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
