{
  "abstract": [
    {
      "text": "A type that identifies FHIR resources for a condition, problem, diagnosis, or other event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/condition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "c:@HKFHIRResourceTypeCondition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "condition"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HKFHIRResourceType",
        "text": "HKFHIRResourceType"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKFHIRResourceTypeCondition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "condition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "condition"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HKFHIRResourceType",
              "text": "HKFHIRResourceType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/conditionRecord": {
      "abstract": [
        {
          "text": "A type identifier for records of a condition, problem, diagnosis, or other event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditionRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKClinicalTypeIdentifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/conditionRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifierConditionRecord"
        }
      ],
      "role": "symbol",
      "title": "conditionRecord",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltypeidentifier/conditionrecord"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType": {
      "abstract": [
        {
          "text": "The FHIR resource types supported in HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceType"
        }
      ],
      "role": "symbol",
      "title": "HKFHIRResourceType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/allergyIntolerance": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for allergies and intolerances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allergyIntolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/allergyIntolerance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeAllergyIntolerance"
        }
      ],
      "role": "symbol",
      "title": "allergyIntolerance",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/allergyintolerance"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/condition": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for a condition, problem, diagnosis, or other event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "condition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/condition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeCondition"
        }
      ],
      "role": "symbol",
      "title": "condition",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/condition"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/coverage": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources containing information about the user’s insurance coverage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coverage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/coverage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeCoverage"
        }
      ],
      "role": "symbol",
      "title": "coverage",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/coverage"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for findings and interpretation of diagnostic tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diagnosticReport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeDiagnosticReport"
        }
      ],
      "role": "symbol",
      "title": "diagnosticReport",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/diagnosticreport"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for document references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentReference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeDocumentReference"
        }
      ],
      "role": "symbol",
      "title": "documentReference",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/documentreference"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/immunization": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for the administration of vaccines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "immunization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/immunization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeImmunization"
        }
      ],
      "role": "symbol",
      "title": "immunization",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/immunization"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationDispense": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for the delivery of medication (usually in response to a prescription).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medicationDispense"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationDispense",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeMedicationDispense"
        }
      ],
      "role": "symbol",
      "title": "medicationDispense",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/medicationdispense"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationOrder": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for prescriptions or other orders for medication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medicationOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeMedicationOrder"
        }
      ],
      "role": "symbol",
      "title": "medicationOrder",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/medicationorder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationRequest": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for prescriptions or other orders or requests for medication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medicationRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeMedicationRequest"
        }
      ],
      "role": "symbol",
      "title": "medicationRequest",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/medicationrequest"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationStatement": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for statements about medication taken by the patient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medicationStatement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationStatement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeMedicationStatement"
        }
      ],
      "role": "symbol",
      "title": "medicationStatement",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/medicationstatement"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/observation": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for medical observations, including lab results and vital signs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/observation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeObservation"
        }
      ],
      "role": "symbol",
      "title": "observation",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/observation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/procedure": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for procedures performed on the patient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "procedure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/procedure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeProcedure"
        }
      ],
      "role": "symbol",
      "title": "procedure",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/procedure"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/conditionRecord"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Resource-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/allergyIntolerance",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/immunization",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationOrder",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationDispense",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationStatement",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationRequest",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/observation",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/procedure",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/coverage"
      ],
      "title": "Resource Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKFHIRResourceTypeCondition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalTypeIdentifier/conditionRecord"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Resource-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/allergyIntolerance",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/immunization",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationOrder",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationDispense",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationStatement",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationRequest",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/observation",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/procedure",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/coverage"
              ],
              "title": "Resource Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@HKFHIRResourceType",
                    "text": "HKFHIRResourceType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKFHIRResourceTypeCondition"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationDispense/title",
          "value": "HKFHIRResourceTypeMedicationDispense"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationDispense/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeMedicationDispense"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1conditionRecord/title",
          "value": "HKClinicalTypeIdentifierConditionRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalTypeIdentifier~1conditionRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifierConditionRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1immunization/title",
          "value": "HKFHIRResourceTypeImmunization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1immunization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeImmunization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1diagnosticReport/title",
          "value": "HKFHIRResourceTypeDiagnosticReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1diagnosticReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeDiagnosticReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1observation/title",
          "value": "HKFHIRResourceTypeObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1observation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationStatement/title",
          "value": "HKFHIRResourceTypeMedicationStatement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationStatement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeMedicationStatement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType/title",
          "value": "HKFHIRResourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1allergyIntolerance/title",
          "value": "HKFHIRResourceTypeAllergyIntolerance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1allergyIntolerance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeAllergyIntolerance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1condition/title",
          "value": "HKFHIRResourceTypeCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1condition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1coverage/title",
          "value": "HKFHIRResourceTypeCoverage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1coverage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeCoverage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1procedure/title",
          "value": "HKFHIRResourceTypeProcedure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1procedure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeProcedure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationOrder/title",
          "value": "HKFHIRResourceTypeMedicationOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeMedicationOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1documentReference/title",
          "value": "HKFHIRResourceTypeDocumentReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1documentReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeDocumentReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationRequest/title",
          "value": "HKFHIRResourceTypeMedicationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeMedicationRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkfhirresourcetype/condition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkfhirresourcetype/condition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
