{
  "abstract": [
    {
      "text": "Initializes the intent object with information about the task and the changes that you want to make.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the designated initializer instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent/init(targetTask:status:spatialEventTrigger:temporalEventTrigger:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Intents",
    "externalID": "c:objc(cs)INSetTaskAttributeIntent(im)initWithTargetTask:status:spatialEventTrigger:temporalEventTrigger:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "targetTask"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INTask",
        "text": "INTask"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "status"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INTaskStatus",
        "text": "INTaskStatus"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "spatialEventTrigger"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INSpatialEventTrigger",
        "text": "INSpatialEventTrigger"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "temporalEventTrigger"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INTemporalEventTrigger",
        "text": "INTemporalEventTrigger"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithTargetTask:status:spatialEventTrigger:temporalEventTrigger:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "message": "Use the designated initializer instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "message": "Use the designated initializer instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use the designated initializer instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use the designated initializer instead",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "4.0",
        "message": "Use the designated initializer instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(targetTask:status:spatialEventTrigger:temporalEventTrigger:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "targetTask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INTask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INTask",
              "text": "INTask"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "status"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INTaskStatus",
              "text": "INTaskStatus"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "spatialEventTrigger"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpatialEventTrigger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INSpatialEventTrigger",
              "text": "INSpatialEventTrigger"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "temporalEventTrigger"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTrigger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INTemporalEventTrigger",
              "text": "INTemporalEventTrigger"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The task that you want to modify.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "targetTask"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The new status for the task.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "status"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The location-based trigger, if any, that you want to apply to the task.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "spatialEventTrigger"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time-based trigger, if any, that you want to apply to the task.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "temporalEventTrigger"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An initialized intent object or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the object could not be created.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Normally, you do not create instances of this class yourself. Instead, SiriKit creates instances when the user asks to set the attributes of a task. However, you can use this method during testing to create intent objects in order to validate your intent handling code paths.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent": {
      "abstract": [
        {
          "text": "A request to modify the attributes of a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetTaskAttributeIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetTaskAttributeIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetTaskAttributeIntent",
      "type": "topic",
      "url": "/documentation/intents/insettaskattributeintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent/init(targetTask:status:spatialEventTrigger:temporalEventTrigger:)": {
      "abstract": [
        {
          "text": "Initializes the intent object with information about the task and the changes that you want to make.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetTask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTask",
          "text": "INTask"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INTaskStatus",
          "text": "INTaskStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "spatialEventTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpatialEventTrigger",
          "text": "INSpatialEventTrigger"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "temporalEventTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTemporalEventTrigger",
          "text": "INTemporalEventTrigger"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent/init(targetTask:status:spatialEventTrigger:temporalEventTrigger:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetTask:status:spatialEventTrigger:temporalEventTrigger:"
        }
      ],
      "role": "symbol",
      "title": "init(targetTask:status:spatialEventTrigger:temporalEventTrigger:)",
      "type": "topic",
      "url": "/documentation/intents/insettaskattributeintent/init(targettask:status:spatialeventtrigger:temporaleventtrigger:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent/init(targetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:)": {
      "abstract": [
        {
          "text": "Initializes the intent object with information about the task and the changes that you want to make.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "targetTask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTask",
          "text": "INTask"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "taskTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpeakableString",
          "text": "INSpeakableString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INTaskStatus",
          "text": "INTaskStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "priority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INTaskPriority",
          "text": "INTaskPriority"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "spatialEventTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpatialEventTrigger",
          "text": "INSpatialEventTrigger"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "temporalEventTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTemporalEventTrigger",
          "text": "INTemporalEventTrigger"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent/init(targetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTargetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:"
        }
      ],
      "role": "symbol",
      "title": "init(targetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:)",
      "type": "topic",
      "url": "/documentation/intents/insettaskattributeintent/init(targettask:tasktitle:status:priority:spatialeventtrigger:temporaleventtrigger:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSpatialEventTrigger": {
      "abstract": [
        {
          "text": "A trigger condition based on the user’s arrival or departure from a given location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSpatialEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpatialEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSpatialEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "INSpatialEventTrigger",
      "type": "topic",
      "url": "/documentation/intents/inspatialeventtrigger"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTask": {
      "abstract": [
        {
          "text": "An individual task the user needs to complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTask"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTask"
        }
      ],
      "role": "symbol",
      "title": "INTask",
      "type": "topic",
      "url": "/documentation/intents/intask"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTaskStatus": {
      "abstract": [
        {
          "text": "Constants indicating the completion state of a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTaskStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTaskStatus"
        }
      ],
      "role": "symbol",
      "title": "INTaskStatus",
      "type": "topic",
      "url": "/documentation/intents/intaskstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTrigger": {
      "abstract": [
        {
          "text": "A trigger condition based on a date or time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTemporalEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTemporalEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "INTemporalEventTrigger",
      "type": "topic",
      "url": "/documentation/intents/intemporaleventtrigger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializing-the-Intent-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent/init(targetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:)"
      ],
      "title": "Initializing the Intent Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithTargetTask:status:spatialEventTrigger:temporalEventTrigger:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetTask:status:spatialEventTrigger:temporalEventTrigger:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Initializing-the-Intent-Object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeIntent/init(targetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:)"
              ],
              "title": "Initializing the Intent Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithTargetTask:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INTask",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INTask",
                    "text": "INTask"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "targetTask"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "status:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INTaskStatus",
                    "text": "INTaskStatus"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "status"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "spatialEventTrigger:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpatialEventTrigger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INSpatialEventTrigger",
                    "text": "INSpatialEventTrigger"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "spatialEventTrigger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "temporalEventTrigger:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTrigger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INTemporalEventTrigger",
                    "text": "INTemporalEventTrigger"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "temporalEventTrigger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The task that you want to modify.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "targetTask"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The new status for the task.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "status"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The location-based trigger, if any, that you want to apply to the task.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "spatialEventTrigger"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The time-based trigger, if any, that you want to apply to the task.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "temporalEventTrigger"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An initialized intent object or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the object could not be created.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the designated initializer instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeIntent~1init(targetTask:status:spatialEventTrigger:temporalEventTrigger:)/title",
          "value": "initWithTargetTask:status:spatialEventTrigger:temporalEventTrigger:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeIntent~1init(targetTask:status:spatialEventTrigger:temporalEventTrigger:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetTask:status:spatialEventTrigger:temporalEventTrigger:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemporalEventTrigger/title",
          "value": "INTemporalEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemporalEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemporalEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemporalEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemporalEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpatialEventTrigger/title",
          "value": "INSpatialEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpatialEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpatialEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpatialEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpatialEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskStatus/title",
          "value": "INTaskStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeIntent~1init(targetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:)/title",
          "value": "initWithTargetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeIntent~1init(targetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTargetTask:taskTitle:status:priority:spatialEventTrigger:temporalEventTrigger:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTask/title",
          "value": "INTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeIntent/title",
          "value": "INSetTaskAttributeIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetTaskAttributeIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetTaskAttributeIntent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insettaskattributeintent/init(targettask:status:spatialeventtrigger:temporaleventtrigger:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insettaskattributeintent/init(targettask:status:spatialeventtrigger:temporaleventtrigger:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
