{
  "abstract": [
    {
      "text": "Manage vehicle door locks and get the vehicle’s status.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/SiriKit",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/SiriKit/car-commands"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Car Commands"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Users can lock or unlock the car’s doors and get other car-related information using Siri. Automotive vendors use their Intents app extension to validate the user’s request and communicate with the user’s registered vehicles.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INActivateCarSignalIntent": {
      "abstract": [
        {
          "text": "A request to activate the signals on the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INActivateCarSignalIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INActivateCarSignalIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INActivateCarSignalIntent"
        }
      ],
      "role": "symbol",
      "title": "INActivateCarSignalIntent",
      "type": "topic",
      "url": "/documentation/intents/inactivatecarsignalintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INActivateCarSignalIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for requesting to activate the car’s signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INActivateCarSignalIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INActivateCarSignalIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INActivateCarSignalIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INActivateCarSignalIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inactivatecarsignalintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INActivateCarSignalIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a request to activate a car’s signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INActivateCarSignalIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INActivateCarSignalIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INActivateCarSignalIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INActivateCarSignalIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inactivatecarsignalintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSignalOptions": {
      "abstract": [
        {
          "text": "The signals produced by the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarSignalOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSignalOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSignalOptions"
        }
      ],
      "role": "symbol",
      "title": "INCarSignalOptions",
      "type": "topic",
      "url": "/documentation/intents/incarsignaloptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSignalOptionsResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the signals the intent is managing on the car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarSignalOptionsResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSignalOptionsResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSignalOptionsResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INCarSignalOptionsResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/incarsignaloptionsresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarLockStatusIntent": {
      "abstract": [
        {
          "text": "A request to get the lock status of the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarLockStatusIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarLockStatusIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarLockStatusIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetCarLockStatusIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetcarlockstatusintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarLockStatusIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for requesting the current status of the car’s locks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarLockStatusIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarLockStatusIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarLockStatusIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INGetCarLockStatusIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/ingetcarlockstatusintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarLockStatusIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a request to get the car’s lock status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarLockStatusIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarLockStatusIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarLockStatusIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INGetCarLockStatusIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/ingetcarlockstatusintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntent": {
      "abstract": [
        {
          "text": "A request for the current power level of the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetCarPowerLevelStatusIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetcarpowerlevelstatusintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for requesting a car’s current power level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INGetCarPowerLevelStatusIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/ingetcarpowerlevelstatusintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a request for the vehicle power level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INGetCarPowerLevelStatusIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/ingetcarpowerlevelstatusintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver": {
      "abstract": [
        {
          "text": "The interface for providing updates of a vehicle’s power level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentResponseObserver"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentResponseObserver"
        }
      ],
      "role": "symbol",
      "title": "INGetCarPowerLevelStatusIntentResponseObserver",
      "type": "topic",
      "url": "/documentation/intents/ingetcarpowerlevelstatusintentresponseobserver"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListCarsIntent": {
      "abstract": [
        {
          "text": "An intent for retrieving a list of the user’s electric vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INListCarsIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListCarsIntent"
        }
      ],
      "role": "symbol",
      "title": "INListCarsIntent",
      "type": "topic",
      "url": "/documentation/intents/inlistcarsintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for requesting a list of the user’s electric vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INListCarsIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListCarsIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INListCarsIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inlistcarsintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a request to list the user’s electric vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INListCarsIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListCarsIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INListCarsIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inlistcarsintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntent": {
      "abstract": [
        {
          "text": "A request to lock or unlock the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetCarLockStatusIntent",
      "type": "topic",
      "url": "/documentation/intents/insetcarlockstatusintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for requesting to lock or unlock a car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetCarLockStatusIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetcarlockstatusintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a request to lock or unlock the car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetCarLockStatusIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INSetCarLockStatusIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/insetcarlockstatusintentresponse"
    },
    "doc://com.apple.sirikit/documentation/SiriKit": {
      "abstract": [
        {
          "text": "Empower users to interact with their devices through voice, intelligent suggestions, and personalized workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit",
      "kind": "article",
      "role": "collection",
      "title": "SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers": {
      "abstract": [
        {
          "text": "Identify intents that user notifications specify.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Intent Class Identifiers",
      "type": "topic",
      "url": "/documentation/sirikit/intent-class-identifiers"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes": {
      "abstract": [
        {
          "text": "Create and manage notes and to-do list items.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Lists and Notes",
      "type": "topic",
      "url": "/documentation/sirikit/lists-and-notes"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/media": {
      "abstract": [
        {
          "text": "Listen and control audio through Siri Intents, or listen and watch media content from your app with shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/media",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media",
      "type": "topic",
      "url": "/documentation/sirikit/media"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/messaging": {
      "abstract": [
        {
          "text": "Send messages and search the user’s received messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/messaging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Messaging",
      "type": "topic",
      "url": "/documentation/sirikit/messaging"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/payments": {
      "abstract": [
        {
          "text": "Send payments between users or pay bills.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/payments",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Payments",
      "type": "topic",
      "url": "/documentation/sirikit/payments"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations": {
      "abstract": [
        {
          "text": "Create and manage restaurant reservations with help from the Maps app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Restaurant Reservations",
      "type": "topic",
      "url": "/documentation/sirikit/restaurant-reservations"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/ride-booking": {
      "abstract": [
        {
          "text": "Book rides and report their status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/ride-booking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ride Booking",
      "type": "topic",
      "url": "/documentation/sirikit/ride-booking"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/voip-calling": {
      "abstract": [
        {
          "text": "Initiate calls and search the user’s call history.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/voip-calling",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VoIP Calling",
      "type": "topic",
      "url": "/documentation/sirikit/voip-calling"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/workouts": {
      "abstract": [
        {
          "text": "Start, end, and manage fitness routines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/workouts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workouts",
      "type": "topic",
      "url": "/documentation/sirikit/workouts"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Standard-Intents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes",
        "doc://com.apple.sirikit/documentation/SiriKit/media",
        "doc://com.apple.sirikit/documentation/SiriKit/messaging",
        "doc://com.apple.sirikit/documentation/SiriKit/payments",
        "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations",
        "doc://com.apple.sirikit/documentation/SiriKit/ride-booking",
        "doc://com.apple.sirikit/documentation/SiriKit/voip-calling",
        "doc://com.apple.sirikit/documentation/SiriKit/workouts",
        "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers"
      ],
      "title": "Standard Intents"
    }
  ],
  "topicSections": [
    {
      "anchor": "Get-Car-Lock-Status",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetCarLockStatusIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INGetCarLockStatusIntent",
        "doc://com.apple.sirikit/documentation/Intents/INGetCarLockStatusIntentResponse"
      ],
      "title": "Get Car Lock Status"
    },
    {
      "anchor": "Set-Car-Lock-Status",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntent",
        "doc://com.apple.sirikit/documentation/Intents/INSetCarLockStatusIntentResponse"
      ],
      "title": "Set Car Lock Status"
    },
    {
      "anchor": "Get-Car-Power-Level-Status",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntent",
        "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponse",
        "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver"
      ],
      "title": "Get Car Power Level Status"
    },
    {
      "anchor": "Activate-Car-Signal",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INActivateCarSignalIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INActivateCarSignalIntent",
        "doc://com.apple.sirikit/documentation/Intents/INActivateCarSignalIntentResponse"
      ],
      "title": "Activate Car Signal"
    },
    {
      "abstract": [
        {
          "text": "Maps uses this intent to obtain a list of the user’s electric vehicles available for route planning. Siri does not generate this intent.",
          "type": "text"
        }
      ],
      "anchor": "List-Cars",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INListCarsIntent",
        "doc://com.apple.sirikit/documentation/Intents/INListCarsIntentResponse"
      ],
      "title": "List Cars"
    },
    {
      "anchor": "Data-Objects",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCarSignalOptions"
      ],
      "title": "Data Objects"
    },
    {
      "anchor": "Resolution-Results",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCarSignalOptionsResolutionResult"
      ],
      "title": "Resolution Results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INActivateCarSignalIntentResponse/title",
          "value": "INActivateCarSignalIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INActivateCarSignalIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INActivateCarSignalIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INActivateCarSignalIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INActivateCarSignalIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntent/title",
          "value": "INListCarsIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INActivateCarSignalIntent/title",
          "value": "INActivateCarSignalIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INActivateCarSignalIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INActivateCarSignalIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INActivateCarSignalIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INActivateCarSignalIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentResponse/title",
          "value": "INListCarsIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSignalOptions/title",
          "value": "INCarSignalOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSignalOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSignalOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSignalOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSignalOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarLockStatusIntentHandling/title",
          "value": "INGetCarLockStatusIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarLockStatusIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarLockStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarLockStatusIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarLockStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentHandling/title",
          "value": "INListCarsIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListCarsIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INListCarsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarLockStatusIntentResponse/title",
          "value": "INGetCarLockStatusIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarLockStatusIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarLockStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarLockStatusIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarLockStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling/title",
          "value": "INSetCarLockStatusIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentResponse/title",
          "value": "INSetCarLockStatusIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntent/title",
          "value": "INGetCarPowerLevelStatusIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarLockStatusIntent/title",
          "value": "INGetCarLockStatusIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarLockStatusIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarLockStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarLockStatusIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarLockStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentHandling/title",
          "value": "INGetCarPowerLevelStatusIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponse/title",
          "value": "INGetCarPowerLevelStatusIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntent/title",
          "value": "INSetCarLockStatusIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetCarLockStatusIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetCarLockStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponseObserver/title",
          "value": "INGetCarPowerLevelStatusIntentResponseObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponseObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentResponseObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponseObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentResponseObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INActivateCarSignalIntentHandling/title",
          "value": "INActivateCarSignalIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INActivateCarSignalIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INActivateCarSignalIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INActivateCarSignalIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INActivateCarSignalIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSignalOptionsResolutionResult/title",
          "value": "INCarSignalOptionsResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSignalOptionsResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSignalOptionsResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSignalOptionsResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSignalOptionsResolutionResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
