{
  "abstract": [
    {
      "text": "Perform final validation of the intent parameters and verify that your services are ready to fulfill the intent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/SiriKit"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/SiriKit",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/SiriKit/confirming-the-details-of-an-intent"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Confirming the Details of an Intent"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you resolve the parameters of an intent, but before you handle that intent, SiriKit may ask you to confirm the intent details. The confirmation phase is your chance to perform any final validation of the intent parameters and to verify that any needed services are available. For example, you might confirm that you can communicate with your company’s server. After performing your final validation, you provide SiriKit with a response object indicating how you plan to handle the request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The listing below shows a confirmation method used by a running app to validate an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Because the app uses Core Location to map the user’s run, the method verifies that the needed location services are available and returns a failure code if they are not. Otherwise, the response object contains the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/ready",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " code, which indicates that the app is ready to start the run.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func confirm(startWorkout intent: INStartWorkoutIntent, ",
            "       completion: @escaping (INStartWorkoutIntentResponse) -> Void) {",
            "    var code : INStartWorkoutIntentResponseCode = .ready",
            "    var activity : NSUserActivity? = nil",
            "        ",
            "    // If location services are not available, the user",
            "    // might need to change the type of workout.",
            "    if !CLLocationManager.locationServicesEnabled() {",
            "        code = .failureRequiringAppLaunch",
            "        activity = NSUserActivity(activityType: ",
            "              \"com.example.myRunningApp.noLocationAvailable\")",
            "    }",
            "        ",
            "    // Deliver the response back to SiriKit.",
            "    let response = INStartWorkoutIntentResponse(code: code, ",
            "            userActivity: activity)",
            "    completion(response)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Providing a custom ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object with your response during confirmation is recommended but not required. If SiriKit needs to launch your app for any reason, it passes the provided activity object to your app. Your app can use any information in the object to take further actions. For example, you might include custom data in the user activity object that your app can then use to configure its interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity": {
      "abstract": [
        {
          "text": "A representation of the state of your app at a moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivity",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntent": {
      "abstract": [
        {
          "text": "A request to start a workout for the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntent"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntent",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "A response code that indicates app readiness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/SiriKit": {
      "abstract": [
        {
          "text": "Empower users to interact with their devices through voice, intelligent suggestions, and personalized workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit",
      "kind": "article",
      "role": "collection",
      "title": "SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Add custom intents and parameters to help users interact more quickly and effectively with Siri and the Shortcuts app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Adding User Interactivity with Siri Shortcuts and the Shortcuts App",
      "type": "topic",
      "url": "/documentation/sirikit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face": {
      "abstract": [
        {
          "text": "Inform Siri when your app’s shortcuts may be useful to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
      "kind": "article",
      "role": "article",
      "title": "Defining Relevant Shortcuts for the Siri Watch Face",
      "type": "topic",
      "url": "/documentation/sirikit/defining-relevant-shortcuts-for-the-siri-watch-face"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts": {
      "abstract": [
        {
          "text": "Remove your donations from Siri.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
      "kind": "article",
      "role": "article",
      "title": "Deleting Donated Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/deleting-donated-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers": {
      "abstract": [
        {
          "text": "Provide SiriKit with an intent handler capable of handling a specific intent.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers",
      "kind": "article",
      "role": "article",
      "title": "Dispatching intents to handlers",
      "type": "topic",
      "url": "/documentation/sirikit/dispatching-intents-to-handlers"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/displaying-shortcut-information-in-a-siri-watch-face-card": {
      "abstract": [
        {
          "text": "Display and customize watch-specific shortcut information with a default card template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/displaying-shortcut-information-in-a-siri-watch-face-card",
      "kind": "article",
      "role": "article",
      "title": "Displaying Shortcut Information in a Siri Watch Face Card",
      "type": "topic",
      "url": "/documentation/sirikit/displaying-shortcut-information-in-a-siri-watch-face-card"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/donating-reservations": {
      "abstract": [
        {
          "text": "Inform Siri of reservations made from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/donating-reservations",
      "kind": "article",
      "role": "article",
      "title": "Donating Reservations",
      "type": "topic",
      "url": "/documentation/sirikit/donating-reservations"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/generating-a-list-of-ride-options": {
      "abstract": [
        {
          "text": "Generate ride options for Maps to display to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/generating-a-list-of-ride-options",
      "kind": "article",
      "role": "article",
      "title": "Generating a List of Ride Options",
      "type": "topic",
      "url": "/documentation/sirikit/generating-a-list-of-ride-options"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/handling-an-intent": {
      "abstract": [
        {
          "text": "Fulfill the intent and provide feedback to SiriKit about what you did.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/handling-an-intent",
      "kind": "article",
      "role": "article",
      "title": "Handling an Intent",
      "type": "topic",
      "url": "/documentation/sirikit/handling-an-intent"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/handling-the-ride-booking-intents": {
      "abstract": [
        {
          "text": "Support the different intent-handling sequences for booking rides with Shortcuts or Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/handling-the-ride-booking-intents",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Handling the Ride-Booking Intents",
      "type": "topic",
      "url": "/documentation/sirikit/handling-the-ride-booking-intents"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app": {
      "abstract": [
        {
          "text": "Donate app-specific content, use Siri’s contact suggestions, and adopt the latest platform features to create a more consistent messaging experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app",
      "kind": "article",
      "role": "article",
      "title": "Improving interactions between Siri and your messaging app",
      "type": "topic",
      "url": "/documentation/sirikit/improving-interactions-between-siri-and-your-messaging-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/improving-siri-media-interactions-and-app-selection": {
      "abstract": [
        {
          "text": "Fine-tune voice controls and improve Siri Suggestions by sharing app capabilities, customized names, and listening habits with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
      "kind": "article",
      "role": "article",
      "title": "Improving Siri Media Interactions and App Selection",
      "type": "topic",
      "url": "/documentation/sirikit/improving-siri-media-interactions-and-app-selection"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit": {
      "abstract": [
        {
          "text": "Register your app’s custom terminology, and provide sample phrases for how to use your app with Siri.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Registering Custom Vocabulary with SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit/registering-custom-vocabulary-with-sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents": {
      "abstract": [
        {
          "text": "Resolve, confirm, and handle user requests for your app’s services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resolving and Handling Intents",
      "type": "topic",
      "url": "/documentation/sirikit/resolving-and-handling-intents"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/resolving-the-parameters-of-an-intent": {
      "abstract": [
        {
          "text": "Validate the parameters of an intent and make sure that you have the information you need to continue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/resolving-the-parameters-of-an-intent",
      "kind": "article",
      "role": "article",
      "title": "Resolving the Parameters of an Intent",
      "type": "topic",
      "url": "/documentation/sirikit/resolving-the-parameters-of-an-intent"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/specifying-synonyms-for-your-app-name": {
      "abstract": [
        {
          "text": "Provide alternative names for your app that are more familiar or easier for users to speak.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/specifying-synonyms-for-your-app-name",
      "kind": "article",
      "role": "article",
      "title": "Specifying Synonyms for Your App Name",
      "type": "topic",
      "url": "/documentation/sirikit/specifying-synonyms-for-your-app-name"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
        "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
        "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers",
        "doc://com.apple.sirikit/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
        "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app",
        "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit",
        "doc://com.apple.sirikit/documentation/SiriKit/handling-an-intent",
        "doc://com.apple.sirikit/documentation/SiriKit/resolving-the-parameters-of-an-intent",
        "doc://com.apple.sirikit/documentation/SiriKit/generating-a-list-of-ride-options",
        "doc://com.apple.sirikit/documentation/SiriKit/handling-the-ride-booking-intents",
        "doc://com.apple.sirikit/documentation/SiriKit/displaying-shortcut-information-in-a-siri-watch-face-card",
        "doc://com.apple.sirikit/documentation/SiriKit/donating-reservations",
        "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
        "doc://com.apple.sirikit/documentation/SiriKit/specifying-synonyms-for-your-app-name"
      ],
      "title": "Articles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntent/title",
          "value": "INStartWorkoutIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1ready/title",
          "value": "INStartWorkoutIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeReady"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
