{
  "abstract": [
    {
      "text": "Provide SiriKit with an intent handler capable of handling a specific intent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/SiriKit"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/SiriKit",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Dispatching intents to handlers"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a user makes a request of your app as an intent, SiriKit needs a handler that conforms to the corresponding intent handling protocol. Each intent object has an associated protocol based on the name of the intent. For example, to handle an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", provide an instance of a type that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. The protocol defines the methods that your handler implements to resolve any intent parameters and to let SiriKit know how your app handled the intent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-a-handler-in-your-intents-app-extension",
          "level": 3,
          "text": "Provide a handler in your intents app extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An intents app extension helps you respond to a person’s request quickly, without loading the entire app. For intents you support in an extension, SiriKit loads your intents app extension and creates an instance of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INExtension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclass. Implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentHandlerProviding/handler(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on your extension object to provide SiriKit with the handlers that you use to handle specific intents.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-a-handler-in-your-app",
          "level": 3,
          "text": "Provide a handler in your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you support an intent directly in your app, the system asks your app delegate for the handler. In a macOS app that uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", implement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSApplicationDelegate/application(_:handlerFor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSApplicationDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In an iOS app (or an app built with Mac Catalyst), implement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:handlerFor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If you’re using SwiftUI, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/UIApplicationDelegateAdaptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NSApplicationDelegateAdaptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to include an app delegate in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "On iOS (and Mac Catalyst), the system only invokes the delegate method in apps that support multiple scenes. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/specifying-the-scenes-your-app-supports",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Determine-which-handler-type-to-return",
          "level": 3,
          "text": "Determine which handler type to return",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can define a separate type for handling each intent class to keep your code organized. When the system asks your app delegate or Intents app extension for an intent handler, check the type of the intent you receive to determine which type of handler to return. Return a valid new handler that conforms to the relevant protocol for all intents that your app or extension supports.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code listing shows logic for an app or extension that supports four different intents. The code handles three message intents with one class, ",
              "type": "text"
            },
            {
              "code": "MyMessageHandler",
              "type": "codeVoice"
            },
            {
              "text": ", which implements ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The code provides a separate handler, ",
              "type": "text"
            },
            {
              "code": "MyCallHandler,",
              "type": "codeVoice"
            },
            {
              "text": " which implements ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". After checking the type of the provided intent object, the method creates and returns an instance of the type capable of handling that intent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Inside your implementation of handler(for:) or application(_:handlerFor:), ",
            "// use the type of the intent to determine which handler to provide.",
            "switch intent {",
            "    case is INSendMessageIntent,",
            "            is INSearchForMessagesIntent,",
            "            is INSetMessageAttributeIntent:",
            "        return MyMessageHandler()",
            "",
            "    case is INStartCallIntent:",
            "        return MyCallHandler()",
            "    default:",
            "        // SiriKit doesn't call this method with intents you don't support.",
            "        return nil",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Handle-an-intent-in-multiple-versions-of-iOS",
          "level": 3,
          "text": "Handle an intent in multiple versions of iOS",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 14 and later, you can resolve, confirm, and handle long-running or memory-intensive intents directly in your app. In iOS 13 and earlier, SiriKit required you resolve and confirm all intents in an Intents app extension, then send long-running intents to your app for the final handling step. To continue supporting these intents on earlier versions of iOS, you can implement the methods to resolve and confirm the intent in both your app delegate and Intents app extension. When your extension confirms the intent, respond with a ",
              "type": "text"
            },
            {
              "code": "continueInApp",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "handleInApp",
              "type": "codeVoice"
            },
            {
              "text": " response code so the system sends the intent to the app to handle the intent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/AppKit"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSApplicationDelegate": {
      "abstract": [
        {
          "text": "A set of methods that manage your app’s life cycle and its interaction with common system services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplicationDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSApplicationDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationDelegate",
      "type": "topic",
      "url": "/documentation/AppKit/NSApplicationDelegate"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSApplicationDelegate/application(_:handlerFor:)": {
      "abstract": [
        {
          "text": "Returns an intent handler that’s capable of handling the specified intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handlerFor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntent",
          "text": "INIntent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSApplicationDelegate/application(_:handlerFor:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:handlerFor:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSApplicationDelegate/application(_:handlerFor:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/NSApplicationDelegateAdaptor": {
      "abstract": [
        {
          "text": "A property wrapper type that you use to create an AppKit app delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@propertyWrapper"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplicationDelegateAdaptor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "DelegateType"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "DelegateType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "DelegateType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSApplicationDelegate",
          "text": "NSApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NSApplicationDelegateAdaptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationDelegateAdaptor",
      "type": "topic",
      "url": "/documentation/SwiftUI/NSApplicationDelegateAdaptor"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/UIApplicationDelegateAdaptor": {
      "abstract": [
        {
          "text": "A property wrapper type that you use to create a UIKit app delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@propertyWrapper"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplicationDelegateAdaptor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "DelegateType"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "DelegateType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "DelegateType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIApplicationDelegate",
          "text": "UIApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/UIApplicationDelegateAdaptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationDelegateAdaptor",
      "type": "topic",
      "url": "/documentation/SwiftUI/UIApplicationDelegateAdaptor"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate": {
      "abstract": [
        {
          "text": "A set of methods to manage shared behaviors for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplicationDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationDelegate",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:handlerFor:)": {
      "abstract": [
        {
          "text": "Asks the delegate for an intent handler capable of handling the specified intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handlerFor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntent",
          "text": "INIntent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:handlerFor:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:handlerFor:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:handlerFor:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/specifying-the-scenes-your-app-supports": {
      "abstract": [
        {
          "text": "Tell the system about your app’s scenes, including the objects you use to manage each scene and its initial user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/specifying-the-scenes-your-app-supports",
      "kind": "article",
      "role": "article",
      "title": "Specifying the scenes your app supports",
      "type": "topic",
      "url": "/documentation/UIKit/specifying-the-scenes-your-app-supports"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INExtension": {
      "abstract": [
        {
          "text": "The entry point for an Intents extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INExtension"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INExtension"
        }
      ],
      "role": "symbol",
      "title": "INExtension",
      "type": "topic",
      "url": "/documentation/intents/inextension"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentHandlerProviding/handler(for:)": {
      "abstract": [
        {
          "text": "Returns the object capable of handling the specified intent in an extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntent",
          "text": "INIntent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentHandlerProviding/handler(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handlerForIntent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handler(for:)",
      "type": "topic",
      "url": "/documentation/intents/inintenthandlerproviding/handler(for:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentHandling": {
      "abstract": [
        {
          "text": "An interface that handles requests to search the current user’s messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntent": {
      "abstract": [
        {
          "text": "A request to send a message to the designated recipients.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendMessageIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageIntent"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageIntent",
      "type": "topic",
      "url": "/documentation/intents/insendmessageintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntentHandling": {
      "abstract": [
        {
          "text": "An interface to handle sending messages to one or more designated users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendMessageIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insendmessageintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntentHandling": {
      "abstract": [
        {
          "text": "An interface that handles modifying message attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetMessageAttributeIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetMessageAttributeIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetMessageAttributeIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetmessageattributeintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling": {
      "abstract": [
        {
          "text": "An interface that handles requests to start audio and video calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartCallIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/instartcallintenthandling"
    },
    "doc://com.apple.sirikit/documentation/SiriKit": {
      "abstract": [
        {
          "text": "Empower users to interact with their devices through voice, intelligent suggestions, and personalized workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit",
      "kind": "article",
      "role": "collection",
      "title": "SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Add custom intents and parameters to help users interact more quickly and effectively with Siri and the Shortcuts app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Adding User Interactivity with Siri Shortcuts and the Shortcuts App",
      "type": "topic",
      "url": "/documentation/sirikit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/confirming-the-details-of-an-intent": {
      "abstract": [
        {
          "text": "Perform final validation of the intent parameters and verify that your services are ready to fulfill the intent.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/confirming-the-details-of-an-intent",
      "kind": "article",
      "role": "article",
      "title": "Confirming the Details of an Intent",
      "type": "topic",
      "url": "/documentation/sirikit/confirming-the-details-of-an-intent"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face": {
      "abstract": [
        {
          "text": "Inform Siri when your app’s shortcuts may be useful to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
      "kind": "article",
      "role": "article",
      "title": "Defining Relevant Shortcuts for the Siri Watch Face",
      "type": "topic",
      "url": "/documentation/sirikit/defining-relevant-shortcuts-for-the-siri-watch-face"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts": {
      "abstract": [
        {
          "text": "Remove your donations from Siri.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
      "kind": "article",
      "role": "article",
      "title": "Deleting Donated Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/deleting-donated-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/displaying-shortcut-information-in-a-siri-watch-face-card": {
      "abstract": [
        {
          "text": "Display and customize watch-specific shortcut information with a default card template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/displaying-shortcut-information-in-a-siri-watch-face-card",
      "kind": "article",
      "role": "article",
      "title": "Displaying Shortcut Information in a Siri Watch Face Card",
      "type": "topic",
      "url": "/documentation/sirikit/displaying-shortcut-information-in-a-siri-watch-face-card"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/donating-reservations": {
      "abstract": [
        {
          "text": "Inform Siri of reservations made from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/donating-reservations",
      "kind": "article",
      "role": "article",
      "title": "Donating Reservations",
      "type": "topic",
      "url": "/documentation/sirikit/donating-reservations"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/generating-a-list-of-ride-options": {
      "abstract": [
        {
          "text": "Generate ride options for Maps to display to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/generating-a-list-of-ride-options",
      "kind": "article",
      "role": "article",
      "title": "Generating a List of Ride Options",
      "type": "topic",
      "url": "/documentation/sirikit/generating-a-list-of-ride-options"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/handling-an-intent": {
      "abstract": [
        {
          "text": "Fulfill the intent and provide feedback to SiriKit about what you did.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/handling-an-intent",
      "kind": "article",
      "role": "article",
      "title": "Handling an Intent",
      "type": "topic",
      "url": "/documentation/sirikit/handling-an-intent"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/handling-the-ride-booking-intents": {
      "abstract": [
        {
          "text": "Support the different intent-handling sequences for booking rides with Shortcuts or Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/handling-the-ride-booking-intents",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Handling the Ride-Booking Intents",
      "type": "topic",
      "url": "/documentation/sirikit/handling-the-ride-booking-intents"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app": {
      "abstract": [
        {
          "text": "Donate app-specific content, use Siri’s contact suggestions, and adopt the latest platform features to create a more consistent messaging experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app",
      "kind": "article",
      "role": "article",
      "title": "Improving interactions between Siri and your messaging app",
      "type": "topic",
      "url": "/documentation/sirikit/improving-interactions-between-siri-and-your-messaging-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/improving-siri-media-interactions-and-app-selection": {
      "abstract": [
        {
          "text": "Fine-tune voice controls and improve Siri Suggestions by sharing app capabilities, customized names, and listening habits with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
      "kind": "article",
      "role": "article",
      "title": "Improving Siri Media Interactions and App Selection",
      "type": "topic",
      "url": "/documentation/sirikit/improving-siri-media-interactions-and-app-selection"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit": {
      "abstract": [
        {
          "text": "Register your app’s custom terminology, and provide sample phrases for how to use your app with Siri.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Registering Custom Vocabulary with SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit/registering-custom-vocabulary-with-sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/resolving-the-parameters-of-an-intent": {
      "abstract": [
        {
          "text": "Validate the parameters of an intent and make sure that you have the information you need to continue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/resolving-the-parameters-of-an-intent",
      "kind": "article",
      "role": "article",
      "title": "Resolving the Parameters of an Intent",
      "type": "topic",
      "url": "/documentation/sirikit/resolving-the-parameters-of-an-intent"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/specifying-synonyms-for-your-app-name": {
      "abstract": [
        {
          "text": "Provide alternative names for your app that are more familiar or easier for users to speak.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/specifying-synonyms-for-your-app-name",
      "kind": "article",
      "role": "article",
      "title": "Specifying Synonyms for Your App Name",
      "type": "topic",
      "url": "/documentation/sirikit/specifying-synonyms-for-your-app-name"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
        "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
        "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
        "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app",
        "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit",
        "doc://com.apple.sirikit/documentation/SiriKit/confirming-the-details-of-an-intent",
        "doc://com.apple.sirikit/documentation/SiriKit/handling-an-intent",
        "doc://com.apple.sirikit/documentation/SiriKit/resolving-the-parameters-of-an-intent",
        "doc://com.apple.sirikit/documentation/SiriKit/generating-a-list-of-ride-options",
        "doc://com.apple.sirikit/documentation/SiriKit/handling-the-ride-booking-intents",
        "doc://com.apple.sirikit/documentation/SiriKit/displaying-shortcut-information-in-a-siri-watch-face-card",
        "doc://com.apple.sirikit/documentation/SiriKit/donating-reservations",
        "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
        "doc://com.apple.sirikit/documentation/SiriKit/specifying-synonyms-for-your-app-name"
      ],
      "title": "Articles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handlerFor:)/title",
          "value": "application:handlerForIntent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handlerFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handlerForIntent:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INIntent",
              "text": "INIntent"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIApplicationDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentHandling/title",
          "value": "INSearchForMessagesIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling/title",
          "value": "INStartCallIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INExtension/title",
          "value": "INExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntentHandling/title",
          "value": "INSendMessageIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSApplicationDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSApplicationDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntent/title",
          "value": "INSendMessageIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentHandlerProviding~1handler(for:)/title",
          "value": "handlerForIntent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentHandlerProviding~1handler(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handlerForIntent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSApplicationDelegate~1application(_:handlerFor:)/title",
          "value": "application:handlerForIntent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSApplicationDelegate~1application(_:handlerFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSApplication",
              "text": "NSApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handlerForIntent:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INIntent",
              "text": "INIntent"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetMessageAttributeIntentHandling/title",
          "value": "INSetMessageAttributeIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetMessageAttributeIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetMessageAttributeIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetMessageAttributeIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetMessageAttributeIntentHandling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
