{
  "abstract": [
    {
      "text": "Listen and control audio through Siri Intents, or listen and watch media content from your app with shortcuts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/SiriKit",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/SiriKit/media"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Media"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With the Media domain, users can play and control audio media in your app. Your Intents app extension directs any media-related requests to your app, which then handles the request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Siri can suggest shortcuts to audio available in your app when the user wants to listen to the content. For example, Siri may suggest a playlist to the user after they connect headphones to their iPhone. These suggestions give the user a convenient way to play the media in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In order for Siri to suggest media content, you should donate an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to Siri after the user plays the content (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SiriKit/donating-shortcuts",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). To have Siri suggest new media that might be of interest to the user, save ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " shortcuts for the new content to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpcomingMediaManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/SiriKit/donating-shortcuts": {
      "abstract": [
        {
          "text": "Tell Siri about shortcuts to actions that the user performed in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SiriKit/donating-shortcuts",
      "kind": "article",
      "role": "article",
      "title": "Donating Shortcuts",
      "type": "topic",
      "url": "/documentation/SiriKit/donating-shortcuts"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntent": {
      "abstract": [
        {
          "text": "A request to add a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddMediaIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntent"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntent",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface that adds media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddMediaIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponse": {
      "abstract": [
        {
          "text": "An intents handler’s response to an add media intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaDestinationResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the types of destinations when adding media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddMediaMediaDestinationResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaDestinationResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaDestinationResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaDestinationResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediadestinationresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the media item to add.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaAffinityTypeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the user’s affinity for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaAffinityTypeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaAffinityTypeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaAffinityTypeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INMediaAffinityTypeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inmediaaffinitytyperesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaDestinationResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the media destination types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaDestinationResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaDestinationResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaDestinationResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INMediaDestinationResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inmediadestinationresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItem": {
      "abstract": [
        {
          "text": "An object that describes a piece of media content, such as a song, TV show, artist, or podcast playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaItem"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItem"
        }
      ],
      "role": "symbol",
      "title": "INMediaItem",
      "type": "topic",
      "url": "/documentation/intents/inmediaitem"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for media item types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaItemResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch": {
      "abstract": [
        {
          "text": "An object that describes a media type to search for, such as a station name, song name, or album name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaSearch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSearch"
        }
      ],
      "role": "symbol",
      "title": "INMediaSearch",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext": {
      "abstract": [
        {
          "text": "An object that provides user information to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaUserContext"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaUserContext"
        }
      ],
      "role": "symbol",
      "title": "INMediaUserContext",
      "type": "topic",
      "url": "/documentation/intents/inmediausercontext"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent": {
      "abstract": [
        {
          "text": "An intent that contains information about media playable from your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntent"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntent",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentHandling": {
      "abstract": [
        {
          "text": "The interface an object implements to confirm and handle play media intents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponse": {
      "abstract": [
        {
          "text": "An intents handler’s response to a play media intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the media item to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaPlaybackSpeedResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result that determines the playback speed of a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaPlaybackSpeedResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaPlaybackSpeedResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaPlaybackSpeedResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaPlaybackSpeedResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaplaybackspeedresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocationResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the requested playback queue location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocationResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocationResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocationResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackQueueLocationResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inplaybackqueuelocationresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatModeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the playback repeat modes of a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatModeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatModeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatModeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackRepeatModeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inplaybackrepeatmoderesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaIntent": {
      "abstract": [
        {
          "text": "A request to search for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMediaIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaIntent"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaIntent",
      "type": "topic",
      "url": "/documentation/intents/insearchformediaintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaIntentHandling": {
      "abstract": [
        {
          "text": "The interface that handles media search requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMediaIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insearchformediaintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaIntentResponse": {
      "abstract": [
        {
          "text": "An intents handler’s response to a search media intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMediaIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/insearchformediaintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the media item for which to search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpcomingMediaManager": {
      "abstract": [
        {
          "text": "The manager object you use to suggest media to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUpcomingMediaManager"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpcomingMediaManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpcomingMediaManager"
        }
      ],
      "role": "symbol",
      "title": "INUpcomingMediaManager",
      "type": "topic",
      "url": "/documentation/intents/inupcomingmediamanager"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntent": {
      "abstract": [
        {
          "text": "A request to update the user’s affinity for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntent"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntent",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentHandling": {
      "abstract": [
        {
          "text": "The interface that handles requests to update the user’s preference for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponse": {
      "abstract": [
        {
          "text": "An intents handler’s response to an update media affinity intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for updating the user’s affinity for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUserContext": {
      "abstract": [
        {
          "text": "An object that provides user information to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUserContext"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUserContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUserContext"
        }
      ],
      "role": "symbol",
      "title": "INUserContext",
      "type": "topic",
      "url": "/documentation/intents/inusercontext"
    },
    "doc://com.apple.sirikit/documentation/SiriKit": {
      "abstract": [
        {
          "text": "Empower users to interact with their devices through voice, intelligent suggestions, and personalized workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit",
      "kind": "article",
      "role": "collection",
      "title": "SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/car-commands": {
      "abstract": [
        {
          "text": "Manage vehicle door locks and get the vehicle’s status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/car-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Car Commands",
      "type": "topic",
      "url": "/documentation/sirikit/car-commands"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/improving-siri-media-interactions-and-app-selection": {
      "abstract": [
        {
          "text": "Fine-tune voice controls and improve Siri Suggestions by sharing app capabilities, customized names, and listening habits with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
      "kind": "article",
      "role": "article",
      "title": "Improving Siri Media Interactions and App Selection",
      "type": "topic",
      "url": "/documentation/sirikit/improving-siri-media-interactions-and-app-selection"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers": {
      "abstract": [
        {
          "text": "Identify intents that user notifications specify.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Intent Class Identifiers",
      "type": "topic",
      "url": "/documentation/sirikit/intent-class-identifiers"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes": {
      "abstract": [
        {
          "text": "Create and manage notes and to-do list items.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Lists and Notes",
      "type": "topic",
      "url": "/documentation/sirikit/lists-and-notes"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/managing-audio-with-sirikit": {
      "abstract": [
        {
          "text": "Control audio playback and handle requests to add media using SiriKit Media Intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/managing-audio-with-sirikit",
      "kind": "article",
      "role": "sampleCode",
      "title": "Managing Audio with SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit/managing-audio-with-sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/messaging": {
      "abstract": [
        {
          "text": "Send messages and search the user’s received messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/messaging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Messaging",
      "type": "topic",
      "url": "/documentation/sirikit/messaging"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/payments": {
      "abstract": [
        {
          "text": "Send payments between users or pay bills.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/payments",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Payments",
      "type": "topic",
      "url": "/documentation/sirikit/payments"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations": {
      "abstract": [
        {
          "text": "Create and manage restaurant reservations with help from the Maps app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Restaurant Reservations",
      "type": "topic",
      "url": "/documentation/sirikit/restaurant-reservations"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/ride-booking": {
      "abstract": [
        {
          "text": "Book rides and report their status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/ride-booking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ride Booking",
      "type": "topic",
      "url": "/documentation/sirikit/ride-booking"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/voip-calling": {
      "abstract": [
        {
          "text": "Initiate calls and search the user’s call history.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/voip-calling",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VoIP Calling",
      "type": "topic",
      "url": "/documentation/sirikit/voip-calling"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/workouts": {
      "abstract": [
        {
          "text": "Start, end, and manage fitness routines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/workouts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workouts",
      "type": "topic",
      "url": "/documentation/sirikit/workouts"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Standard-Intents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/car-commands",
        "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes",
        "doc://com.apple.sirikit/documentation/SiriKit/messaging",
        "doc://com.apple.sirikit/documentation/SiriKit/payments",
        "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations",
        "doc://com.apple.sirikit/documentation/SiriKit/ride-booking",
        "doc://com.apple.sirikit/documentation/SiriKit/voip-calling",
        "doc://com.apple.sirikit/documentation/SiriKit/workouts",
        "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers"
      ],
      "title": "Standard Intents"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
        "doc://com.apple.sirikit/documentation/SiriKit/managing-audio-with-sirikit"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Playable-Media-Intents",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponse"
      ],
      "title": "Playable Media Intents"
    },
    {
      "anchor": "Add-Media",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntent",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponse"
      ],
      "title": "Add Media"
    },
    {
      "anchor": "Search-for-Media",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaIntent",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaIntentResponse"
      ],
      "title": "Search for Media"
    },
    {
      "anchor": "Update-Media-Affinity",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntent",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponse"
      ],
      "title": "Update Media Affinity"
    },
    {
      "anchor": "User-Context",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INUserContext",
        "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext"
      ],
      "title": "User Context"
    },
    {
      "anchor": "Data-Objects",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItem",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch"
      ],
      "title": "Data Objects"
    },
    {
      "anchor": "Upcoming-Media",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INUpcomingMediaManager"
      ],
      "title": "Upcoming Media"
    },
    {
      "anchor": "Resolution-Results",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaDestinationResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INMediaDestinationResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INMediaAffinityTypeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaPlaybackSpeedResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatModeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocationResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemResolutionResult"
      ],
      "title": "Resolution Results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaIntent/title",
          "value": "INSearchForMediaIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpcomingMediaManager/title",
          "value": "INUpcomingMediaManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpcomingMediaManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpcomingMediaManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpcomingMediaManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpcomingMediaManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentHandling/title",
          "value": "INAddMediaIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaDestinationResolutionResult/title",
          "value": "INAddMediaMediaDestinationResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaDestinationResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaDestinationResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaDestinationResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaDestinationResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponse/title",
          "value": "INUpdateMediaAffinityIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentHandling/title",
          "value": "INPlayMediaIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponse/title",
          "value": "INAddMediaIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentHandling/title",
          "value": "INUpdateMediaAffinityIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponse/title",
          "value": "INPlayMediaIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemResolutionResult/title",
          "value": "INMediaItemResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem/title",
          "value": "INMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaAffinityTypeResolutionResult/title",
          "value": "INMediaAffinityTypeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaAffinityTypeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaAffinityTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaAffinityTypeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaAffinityTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaIntentResponse/title",
          "value": "INSearchForMediaIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntent/title",
          "value": "INAddMediaIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntent/title",
          "value": "INUpdateMediaAffinityIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocationResolutionResult/title",
          "value": "INPlaybackQueueLocationResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocationResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocationResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocationResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocationResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemResolutionResult/title",
          "value": "INSearchForMediaMediaItemResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch/title",
          "value": "INMediaSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaIntentHandling/title",
          "value": "INSearchForMediaIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaPlaybackSpeedResolutionResult/title",
          "value": "INPlayMediaPlaybackSpeedResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaPlaybackSpeedResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaPlaybackSpeedResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaPlaybackSpeedResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaPlaybackSpeedResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaDestinationResolutionResult/title",
          "value": "INMediaDestinationResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaDestinationResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaDestinationResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaDestinationResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaDestinationResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatModeResolutionResult/title",
          "value": "INPlaybackRepeatModeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatModeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatModeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatModeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatModeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemResolutionResult/title",
          "value": "INUpdateMediaAffinityMediaItemResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUserContext/title",
          "value": "INUserContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUserContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUserContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUserContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUserContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemResolutionResult/title",
          "value": "INAddMediaMediaItemResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext/title",
          "value": "INMediaUserContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemResolutionResult/title",
          "value": "INPlayMediaMediaItemResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent/title",
          "value": "INPlayMediaIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
