{
  "abstract": [
    {
      "text": "Resolve common types of data like strings and dates into specific values that your app recognizes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/SiriKit",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/SiriKit/resolution-results"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Resolution Results"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBooleanResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a Boolean value associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBooleanResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBooleanResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBooleanResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INBooleanResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inbooleanresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmountResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a currency amount associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCurrencyAmountResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmountResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCurrencyAmountResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INCurrencyAmountResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/incurrencyamountresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRangeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a range of dates in a parameter of an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDateComponentsRangeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRangeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDateComponentsRangeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INDateComponentsRangeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/indatecomponentsrangeresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDateComponentsResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the date information associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDateComponentsResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDateComponentsResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INDateComponentsResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/indatecomponentsresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDoubleResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a double value associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDoubleResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDoubleResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDoubleResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INDoubleResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/indoubleresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for an energy parameter associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INEnergyResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEnergyResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INEnergyResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inenergyresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEnumResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for an enumeration associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INEnumResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEnumResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEnumResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INEnumResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inenumresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INFileResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a file associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INFileResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INFileResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INFileResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INFileResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/infileresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntegerResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for an integer value associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntegerResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntegerResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntegerResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INIntegerResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inintegerresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntent": {
      "abstract": [
        {
          "text": "A request to fulfill in your app or Intents extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntent"
        }
      ],
      "role": "symbol",
      "title": "INIntent",
      "type": "topic",
      "url": "/documentation/intents/inintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a parameter of an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INIntentResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResponse": {
      "abstract": [
        {
          "text": "Your response to an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLengthResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a length associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INLengthResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLengthResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INLengthResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INLengthResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inlengthresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMassResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a mass associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMassResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMassResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMassResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INMassResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inmassresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INObjectResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for an Object associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INObjectResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INObjectResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INObjectResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INObjectResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inobjectresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a user as a parameter of an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPersonResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPersonResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inpersonresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlacemarkResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for placemark information associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlacemarkResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlacemarkResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlacemarkResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPlacemarkResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inplacemarkresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSpeakableStringResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a speakable string object associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSpeakableStringResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpeakableStringResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSpeakableStringResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INSpeakableStringResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inspeakablestringresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSpeedResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a speed associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSpeedResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpeedResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSpeedResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INSpeedResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inspeedresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStringResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a string value associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStringResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStringResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStringResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INStringResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/instringresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTemperatureResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the units to use with a temperature value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTemperatureResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTemperatureResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTemperatureResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INTemperatureResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/intemperatureresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTimeIntervalResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a time interval associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTimeIntervalResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTimeIntervalResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTimeIntervalResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INTimeIntervalResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/intimeintervalresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INURLResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the types media destinations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INURLResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INURLResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INURLResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INURLResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inurlresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVolumeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a volume associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVolumeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVolumeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVolumeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INVolumeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/involumeresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/SiriKit": {
      "abstract": [
        {
          "text": "Empower users to interact with their devices through voice, intelligent suggestions, and personalized workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit",
      "kind": "article",
      "role": "collection",
      "title": "SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/common-data-types": {
      "abstract": [
        {
          "text": "Manage common data types such as strings, dates, currencies, images, and contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/common-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Common Data Types",
      "type": "topic",
      "url": "/documentation/sirikit/common-data-types"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers": {
      "abstract": [
        {
          "text": "Provide SiriKit with an intent handler capable of handling a specific intent.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers",
      "kind": "article",
      "role": "article",
      "title": "Dispatching intents to handlers",
      "type": "topic",
      "url": "/documentation/sirikit/dispatching-intents-to-handlers"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/intent-handling-infrastructure": {
      "abstract": [
        {
          "text": "Specify required permissions and provide handlers for the intents your app supports, and configure app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/intent-handling-infrastructure",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Intent Handling Infrastructure",
      "type": "topic",
      "url": "/documentation/sirikit/intent-handling-infrastructure"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/providing-hands-free-app-control-with-intents": {
      "abstract": [
        {
          "text": "Resolve, confirm, and handle intents without an extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/providing-hands-free-app-control-with-intents",
      "kind": "article",
      "role": "sampleCode",
      "title": "Providing Hands-Free App Control with Intents",
      "type": "topic",
      "url": "/documentation/sirikit/providing-hands-free-app-control-with-intents"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents": {
      "abstract": [
        {
          "text": "Resolve, confirm, and handle user requests for your app’s services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resolving and Handling Intents",
      "type": "topic",
      "url": "/documentation/sirikit/resolving-and-handling-intents"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Intents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers",
        "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents",
        "doc://com.apple.sirikit/documentation/Intents/INIntent",
        "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
        "doc://com.apple.sirikit/documentation/SiriKit/intent-handling-infrastructure",
        "doc://com.apple.sirikit/documentation/SiriKit/providing-hands-free-app-control-with-intents",
        "doc://com.apple.sirikit/documentation/SiriKit/common-data-types"
      ],
      "title": "Intents"
    }
  ],
  "topicSections": [
    {
      "anchor": "Base-Class",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult"
      ],
      "title": "Base Class"
    },
    {
      "anchor": "Custom-Resolution-Results",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INEnumResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INObjectResolutionResult"
      ],
      "title": "Custom Resolution Results"
    },
    {
      "anchor": "Contacts",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPersonResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INPlacemarkResolutionResult"
      ],
      "title": "Contacts"
    },
    {
      "anchor": "Files",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INFileResolutionResult"
      ],
      "title": "Files"
    },
    {
      "anchor": "URLs",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INURLResolutionResult"
      ],
      "title": "URLs"
    },
    {
      "anchor": "Strings",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStringResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INSpeakableStringResolutionResult"
      ],
      "title": "Strings"
    },
    {
      "anchor": "Numerical-Values",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntegerResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INDoubleResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INBooleanResolutionResult"
      ],
      "title": "Numerical Values"
    },
    {
      "anchor": "Dates-and-Times",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRangeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INDateComponentsResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INTimeIntervalResolutionResult"
      ],
      "title": "Dates and Times"
    },
    {
      "anchor": "Money",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmountResolutionResult"
      ],
      "title": "Money"
    },
    {
      "anchor": "Measurements",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INLengthResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INMassResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INSpeedResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INTemperatureResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INVolumeResolutionResult"
      ],
      "title": "Measurements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStringResolutionResult/title",
          "value": "INStringResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStringResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStringResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStringResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStringResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INURLResolutionResult/title",
          "value": "INURLResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INURLResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INURLResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INURLResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INURLResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRangeResolutionResult/title",
          "value": "INDateComponentsRangeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRangeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsRangeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRangeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsRangeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonResolutionResult/title",
          "value": "INPersonResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/title",
          "value": "INIntentResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/title",
          "value": "INIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeedResolutionResult/title",
          "value": "INSpeedResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeedResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeedResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeedResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeedResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmountResolutionResult/title",
          "value": "INCurrencyAmountResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmountResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCurrencyAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmountResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCurrencyAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMassResolutionResult/title",
          "value": "INMassResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMassResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMassResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMassResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMassResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLengthResolutionResult/title",
          "value": "INLengthResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLengthResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INLengthResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLengthResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INLengthResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/title",
          "value": "INIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnumResolutionResult/title",
          "value": "INEnumResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnumResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEnumResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnumResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INEnumResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTimeIntervalResolutionResult/title",
          "value": "INTimeIntervalResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTimeIntervalResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTimeIntervalResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTimeIntervalResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTimeIntervalResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVolumeResolutionResult/title",
          "value": "INVolumeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVolumeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVolumeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVolumeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVolumeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsResolutionResult/title",
          "value": "INDateComponentsResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntegerResolutionResult/title",
          "value": "INIntegerResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntegerResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntegerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntegerResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntegerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlacemarkResolutionResult/title",
          "value": "INPlacemarkResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlacemarkResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlacemarkResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlacemarkResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlacemarkResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemperatureResolutionResult/title",
          "value": "INTemperatureResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemperatureResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemperatureResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemperatureResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemperatureResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDoubleResolutionResult/title",
          "value": "INDoubleResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDoubleResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDoubleResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDoubleResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDoubleResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBooleanResolutionResult/title",
          "value": "INBooleanResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBooleanResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBooleanResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBooleanResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBooleanResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakableStringResolutionResult/title",
          "value": "INSpeakableStringResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakableStringResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeakableStringResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakableStringResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeakableStringResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INObjectResolutionResult/title",
          "value": "INObjectResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INObjectResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INObjectResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INObjectResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INObjectResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult/title",
          "value": "INEnergyResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEnergyResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INEnergyResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFileResolutionResult/title",
          "value": "INFileResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFileResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INFileResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFileResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INFileResolutionResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
