{
  "abstract": [
    {
      "text": "Incorporate standard buttons and interfaces into your user interface to offer easy shortcut creation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/SiriKit",
        "doc://com.apple.sirikit/documentation/IntentsUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/SiriKit/shortcut-related-ui"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IntentsUI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Shortcut-Related UI"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDefaultCardTemplate": {
      "abstract": [
        {
          "text": "A card template for customizing the Siri watch face for a shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDefaultCardTemplate"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDefaultCardTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDefaultCardTemplate"
        }
      ],
      "role": "symbol",
      "title": "INDefaultCardTemplate",
      "type": "topic",
      "url": "/documentation/intents/indefaultcardtemplate"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton": {
      "abstract": [
        {
          "text": "A button that allows the user to add or edit a shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButton"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButton"
        }
      ],
      "role": "symbol",
      "title": "INUIAddVoiceShortcutButton",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutbutton"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutViewController": {
      "abstract": [
        {
          "text": "A view controller that guides the user through the steps for adding a shortcut to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutViewController"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutViewController"
        }
      ],
      "role": "symbol",
      "title": "INUIAddVoiceShortcutViewController",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutviewcontroller"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController": {
      "abstract": [
        {
          "text": "A view controller that lets the user edit or remove an existing shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewController"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewController"
        }
      ],
      "role": "symbol",
      "title": "INUIEditVoiceShortcutViewController",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontroller"
    },
    "doc://com.apple.sirikit/documentation/SiriKit": {
      "abstract": [
        {
          "text": "Empower users to interact with their devices through voice, intelligent suggestions, and personalized workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit",
      "kind": "article",
      "role": "collection",
      "title": "SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/configuring-the-view-controller-for-your-custom-interface": {
      "abstract": [
        {
          "text": "Configure your view controller to replace or augment the default interface in Siri or Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/configuring-the-view-controller-for-your-custom-interface",
      "kind": "article",
      "role": "article",
      "title": "Configuring the View Controller for Your Custom Interface",
      "type": "topic",
      "url": "/documentation/sirikit/configuring-the-view-controller-for-your-custom-interface"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/displaying-shortcut-information-in-a-siri-watch-face-card": {
      "abstract": [
        {
          "text": "Display and customize watch-specific shortcut information with a default card template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/displaying-shortcut-information-in-a-siri-watch-face-card",
      "kind": "article",
      "role": "article",
      "title": "Displaying Shortcut Information in a Siri Watch Face Card",
      "type": "topic",
      "url": "/documentation/sirikit/displaying-shortcut-information-in-a-siri-watch-face-card"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Custom-UI-for-Shortcuts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/configuring-the-view-controller-for-your-custom-interface"
      ],
      "title": "Custom UI for Shortcuts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Shortcut-Button",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton"
      ],
      "title": "Shortcut Button"
    },
    {
      "anchor": "Shortcut-Editors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutViewController",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController"
      ],
      "title": "Shortcut Editors"
    },
    {
      "anchor": "Siri-Watch-Face-Cards",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/displaying-shortcut-information-in-a-siri-watch-face-card",
        "doc://com.apple.sirikit/documentation/Intents/INDefaultCardTemplate"
      ],
      "title": "Siri Watch Face Cards"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutViewController/title",
          "value": "INUIAddVoiceShortcutViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDefaultCardTemplate/title",
          "value": "INDefaultCardTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDefaultCardTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDefaultCardTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDefaultCardTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDefaultCardTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/title",
          "value": "INUIAddVoiceShortcutButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController/title",
          "value": "INUIEditVoiceShortcutViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
