{
  "abstract": [
    {
      "text": "Display relevant shortcuts on the Siri watch face and suggest widgets in Smart Stacks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/SiriKit",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/SiriKit/watch-and-widget-support"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Watch and Widget Support"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelevantShortcut",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " describes an action that might be useful or meaningful to the user within a particular context. For instance, a user might want to start a workout when they arrive at the gym, meditate in the morning, or find out about a new episode of their favorite TV show as soon it’s available. The system uses the shortcut’s relevance providers, as well as other signals, to determine when the shortcut is likely relevant to the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Siri watch face updates throughout the day to offer shortcuts or glanceable information. For details on suggesting relevant shortcuts on the Siri watch face, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Users can collect multiple widgets into a Smart Stack. A Smart Stack rotates to widgets and suggests new widgets based on relevance cues. For details on using shortcuts to influence Smart Stacks, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WidgetKit/Widget-Suggestions-In-Smart-Stacks",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face": {
      "abstract": [
        {
          "text": "Inform Siri when your app’s shortcuts may be useful to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
      "kind": "article",
      "role": "article",
      "title": "Defining Relevant Shortcuts for the Siri Watch Face",
      "type": "topic",
      "url": "/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face"
    },
    "doc://com.apple.documentation/documentation/WidgetKit/Widget-Suggestions-In-Smart-Stacks": {
      "abstract": [
        {
          "text": "Donate intents and indicate relevance to automatically show your widget in Smart Stacks when it has useful information to display.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit/Widget-Suggestions-In-Smart-Stacks",
      "kind": "article",
      "role": "article",
      "title": "Increasing the visibility of widgets in Smart Stacks",
      "type": "topic",
      "url": "/documentation/WidgetKit/Widget-Suggestions-In-Smart-Stacks"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider": {
      "abstract": [
        {
          "text": "The provider class that specifies a relevant daily routine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDailyRoutineRelevanceProvider"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineRelevanceProvider"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDateRelevanceProvider": {
      "abstract": [
        {
          "text": "The provider class that specifies a relevant day and time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDateRelevanceProvider"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateRelevanceProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDateRelevanceProvider"
        }
      ],
      "role": "symbol",
      "title": "INDateRelevanceProvider",
      "type": "topic",
      "url": "/documentation/intents/indaterelevanceprovider"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentDonationMetadata"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentDonationMetadata"
        }
      ],
      "role": "symbol",
      "title": "INIntentDonationMetadata",
      "type": "topic",
      "url": "/documentation/intents/inintentdonationmetadata"
    },
    "doc://com.apple.sirikit/documentation/Intents/INInteraction": {
      "abstract": [
        {
          "text": "An interaction between the user and your app involving an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "role": "symbol",
      "title": "INInteraction",
      "type": "topic",
      "url": "/documentation/intents/ininteraction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLocationRelevanceProvider": {
      "abstract": [
        {
          "text": "The provider class that specifies a relevant location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INLocationRelevanceProvider"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLocationRelevanceProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INLocationRelevanceProvider"
        }
      ],
      "role": "symbol",
      "title": "INLocationRelevanceProvider",
      "type": "topic",
      "url": "/documentation/intents/inlocationrelevanceprovider"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRelevanceProvider": {
      "abstract": [
        {
          "text": "An abstract class that represents a relevance provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRelevanceProvider"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelevanceProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRelevanceProvider"
        }
      ],
      "role": "symbol",
      "title": "INRelevanceProvider",
      "type": "topic",
      "url": "/documentation/intents/inrelevanceprovider"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRelevantShortcut": {
      "abstract": [
        {
          "text": "An object that defines a shortcut and its relevance to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRelevantShortcut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelevantShortcut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRelevantShortcut"
        }
      ],
      "role": "symbol",
      "title": "INRelevantShortcut",
      "type": "topic",
      "url": "/documentation/intents/inrelevantshortcut"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRelevantShortcutStore": {
      "abstract": [
        {
          "text": "An object that saves relevant shortcuts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRelevantShortcutStore"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelevantShortcutStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRelevantShortcutStore"
        }
      ],
      "role": "symbol",
      "title": "INRelevantShortcutStore",
      "type": "topic",
      "url": "/documentation/intents/inrelevantshortcutstore"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum": {
      "abstract": [
        {
          "text": "An action available in your app that the system may suggest to a user or a user may add to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcut"
        }
      ],
      "role": "symbol",
      "title": "INShortcut",
      "type": "topic",
      "url": "/documentation/intents/inshortcut-swift.enum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions": {
      "abstract": [
        {
          "text": "Defined contexts in which an intent or activity might be relevant to a user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "role": "symbol",
      "title": "INShortcutAvailabilityOptions",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutReference": {
      "abstract": [
        {
          "text": "An object representing an action available in your app that the system may suggest to a user or a user may add to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcutReference"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutReference"
        }
      ],
      "role": "symbol",
      "title": "INShortcutReference",
      "type": "topic",
      "url": "/documentation/intents/inshortcutreference"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut": {
      "abstract": [
        {
          "text": "A shortcut the user added to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVoiceShortcut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVoiceShortcut"
        }
      ],
      "role": "symbol",
      "title": "INVoiceShortcut",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcut"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter": {
      "abstract": [
        {
          "text": "Retrieve the user’s shortcuts and make shortcut suggestions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVoiceShortcutCenter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVoiceShortcutCenter"
        }
      ],
      "role": "symbol",
      "title": "INVoiceShortcutCenter",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcutcenter"
    },
    "doc://com.apple.sirikit/documentation/SiriKit": {
      "abstract": [
        {
          "text": "Empower users to interact with their devices through voice, intelligent suggestions, and personalized workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit",
      "kind": "article",
      "role": "collection",
      "title": "SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down": {
      "abstract": [
        {
          "text": "Reveal your app’s shortcuts inside the Health app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding Shortcuts for Wind Down",
      "type": "topic",
      "url": "/documentation/sirikit/adding-shortcuts-for-wind-down"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Add custom intents and parameters to help users interact more quickly and effectively with Siri and the Shortcuts app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Adding User Interactivity with Siri Shortcuts and the Shortcuts App",
      "type": "topic",
      "url": "/documentation/sirikit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face": {
      "abstract": [
        {
          "text": "Inform Siri when your app’s shortcuts may be useful to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
      "kind": "article",
      "role": "article",
      "title": "Defining Relevant Shortcuts for the Siri Watch Face",
      "type": "topic",
      "url": "/documentation/sirikit/defining-relevant-shortcuts-for-the-siri-watch-face"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts": {
      "abstract": [
        {
          "text": "Remove your donations from Siri.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
      "kind": "article",
      "role": "article",
      "title": "Deleting Donated Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/deleting-donated-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts": {
      "abstract": [
        {
          "text": "Tell Siri about shortcuts to actions that the user performed in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts",
      "kind": "article",
      "role": "article",
      "title": "Donating Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/donating-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Suggest shortcuts users may want to add to Siri or combine with other actions in their own shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Offering Actions in the Shortcuts App",
      "type": "topic",
      "url": "/documentation/sirikit/offering-actions-in-the-shortcuts-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts": {
      "abstract": [
        {
          "text": "Make it easy for people to use Siri with your app by providing shortcuts to your app’s actions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts",
      "kind": "article",
      "role": "sampleCode",
      "title": "Soup Chef: Accelerating App Interactions with Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/soup-chef-accelerating-app-interactions-with-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents": {
      "abstract": [
        {
          "text": "Integrating App Intents to provide your appʼs actions to Siri and Shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents",
      "kind": "article",
      "role": "sampleCode",
      "title": "Soup Chef with App Intents: Migrating custom intents",
      "type": "topic",
      "url": "/documentation/sirikit/soup-chef-with-app-intents-migrating-custom-intents"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shortcuts-and-Donations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
        "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
        "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents",
        "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
        "doc://com.apple.sirikit/documentation/Intents/INInteraction",
        "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum",
        "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter",
        "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
        "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata"
      ],
      "title": "Shortcuts and Donations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
        "doc://com.apple.sirikit/documentation/Intents/INRelevantShortcut",
        "doc://com.apple.sirikit/documentation/Intents/INRelevantShortcutStore"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Relevance-Providers",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRelevanceProvider",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider",
        "doc://com.apple.sirikit/documentation/Intents/INDateRelevanceProvider",
        "doc://com.apple.sirikit/documentation/Intents/INLocationRelevanceProvider"
      ],
      "title": "Relevance Providers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/title",
          "value": "INInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/title",
          "value": "INVoiceShortcutCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcutCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcutCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/title",
          "value": "INShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/title",
          "value": "INVoiceShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateRelevanceProvider/title",
          "value": "INDateRelevanceProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateRelevanceProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateRelevanceProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider/title",
          "value": "INDailyRoutineRelevanceProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/title",
          "value": "INShortcutAvailabilityOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelevantShortcut/title",
          "value": "INRelevantShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelevantShortcut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelevantShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelevantShortcut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelevantShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLocationRelevanceProvider/title",
          "value": "INLocationRelevanceProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLocationRelevanceProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INLocationRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLocationRelevanceProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INLocationRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelevanceProvider/title",
          "value": "INRelevanceProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelevanceProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelevanceProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelevantShortcutStore/title",
          "value": "INRelevantShortcutStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelevantShortcutStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelevantShortcutStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelevantShortcutStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelevantShortcutStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentDonationMetadata/title",
          "value": "INIntentDonationMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentDonationMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentDonationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentDonationMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentDonationMetadata"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
