{
  "abstract": [
    {
      "text": "Specifies that the scroller has at least a knob, possibly also scroll buttons.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/allScrollerParts"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSUsableScrollerParts@NSAllScrollerParts",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "allScrollerParts"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAllScrollerParts"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSScroller.UsableParts.allScrollerParts"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "allScrollerParts"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller": {
      "abstract": [
        {
          "text": "An object that controls scrolling of a document view within a scroll view or other type of container view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScroller"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScroller"
        }
      ],
      "role": "symbol",
      "title": "NSScroller",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum": {
      "abstract": [
        {
          "text": "These constants specify which parts of the scroller are visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UsableParts"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UsableParts"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.UsableParts",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/usableparts-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/allScrollerParts": {
      "abstract": [
        {
          "text": "Specifies that the scroller has at least a knob, possibly also scroll buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allScrollerParts"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/allScrollerParts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAllScrollerParts"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.UsableParts.allScrollerParts",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/usableparts-swift.enum/allscrollerparts"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/noScrollerParts": {
      "abstract": [
        {
          "text": "Specifies that the scroller has neither a knob nor scroll buttons, only the knob slot.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noScrollerParts"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/noScrollerParts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoScrollerParts"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.UsableParts.noScrollerParts",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/usableparts-swift.enum/noscrollerparts"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/onlyScrollerArrows": {
      "abstract": [
        {
          "text": "Specifies that the scroller has only scroll buttons, no knob.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onlyScrollerArrows"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/onlyScrollerArrows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOnlyScrollerArrows"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.UsableParts.onlyScrollerArrows",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/usableparts-swift.enum/onlyscrollerarrows"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/noScrollerParts",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/onlyScrollerArrows"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAllScrollerParts"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAllScrollerParts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/noScrollerParts",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum/onlyScrollerArrows"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSAllScrollerParts"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/title",
          "value": "NSScroller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum~1noScrollerParts/title",
          "value": "NSNoScrollerParts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum~1noScrollerParts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoScrollerParts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum~1allScrollerParts/title",
          "value": "NSAllScrollerParts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum~1allScrollerParts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAllScrollerParts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum/title",
          "value": "NSUsableScrollerParts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUsableScrollerParts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUsableScrollerParts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum~1onlyScrollerArrows/title",
          "value": "NSOnlyScrollerArrows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum~1onlyScrollerArrows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOnlyScrollerArrows"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscroller/usableparts-swift.enum/allscrollerparts"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsscroller/usableparts-swift.enum/allscrollerparts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
