{
  "abstract": [
    {
      "text": "An object’s property value changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgPropertyChanged"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDINotificationMessageID@kMIDIMsgPropertyChanged",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "msgPropertyChanged"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDIMsgPropertyChanged"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MIDINotificationMessageID.msgPropertyChanged"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "msgPropertyChanged"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This type’s data is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectPropertyChangeNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID": {
      "abstract": [
        {
          "text": "The types of state changes the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINotificationMessageID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINotificationMessageID"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgIOError": {
      "abstract": [
        {
          "text": "A driver I/O error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgIOError"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgIOError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgIOError"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgIOError",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgioerror"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectAdded": {
      "abstract": [
        {
          "text": "The system added a device, entity, or endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgObjectAdded"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectAdded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgObjectAdded"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgObjectAdded",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgobjectadded"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectRemoved": {
      "abstract": [
        {
          "text": "The system removed a device, entity, or endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgObjectRemoved"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgObjectRemoved"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgObjectRemoved",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgobjectremoved"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgPropertyChanged": {
      "abstract": [
        {
          "text": "An object’s property value changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgPropertyChanged"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgPropertyChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgPropertyChanged"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgPropertyChanged",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgpropertychanged"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSerialPortOwnerChanged": {
      "abstract": [
        {
          "text": "The system changed a serial port owner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgSerialPortOwnerChanged"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSerialPortOwnerChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgSerialPortOwnerChanged"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgSerialPortOwnerChanged",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgserialportownerchanged"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSetupChanged": {
      "abstract": [
        {
          "text": "Some aspect of the current MIDI setup changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgSetupChanged"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSetupChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgSetupChanged"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgSetupChanged",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgsetupchanged"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgThruConnectionsChanged": {
      "abstract": [
        {
          "text": "The system created or disposed of a persistent MIDI Thru connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgThruConnectionsChanged"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgThruConnectionsChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgThruConnectionsChanged"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgThruConnectionsChanged",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgthruconnectionschanged"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectPropertyChangeNotification": {
      "abstract": [
        {
          "text": "A message that describes the change to an object property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIObjectPropertyChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectPropertyChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIObjectPropertyChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectPropertyChangeNotification",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjectpropertychangenotification"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Change-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSetupChanged",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectAdded",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectRemoved",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgThruConnectionsChanged",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSerialPortOwnerChanged",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgIOError"
      ],
      "title": "Change Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDIMsgPropertyChanged"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgPropertyChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Change-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSetupChanged",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectAdded",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectRemoved",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgThruConnectionsChanged",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSerialPortOwnerChanged",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgIOError"
              ],
              "title": "Change Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMIDIMsgPropertyChanged"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgIOError/title",
          "value": "kMIDIMsgIOError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgIOError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgIOError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgPropertyChanged/title",
          "value": "kMIDIMsgPropertyChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgPropertyChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgPropertyChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgSetupChanged/title",
          "value": "kMIDIMsgSetupChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgSetupChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgSetupChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgObjectRemoved/title",
          "value": "kMIDIMsgObjectRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgObjectRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgObjectRemoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgSerialPortOwnerChanged/title",
          "value": "kMIDIMsgSerialPortOwnerChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgSerialPortOwnerChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgSerialPortOwnerChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgThruConnectionsChanged/title",
          "value": "kMIDIMsgThruConnectionsChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgThruConnectionsChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgThruConnectionsChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID/title",
          "value": "MIDINotificationMessageID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINotificationMessageID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINotificationMessageID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectPropertyChangeNotification/title",
          "value": "MIDIObjectPropertyChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectPropertyChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectPropertyChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectPropertyChangeNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectPropertyChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgObjectAdded/title",
          "value": "kMIDIMsgObjectAdded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgObjectAdded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgObjectAdded"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midinotificationmessageid/msgpropertychanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midinotificationmessageid/msgpropertychanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
