{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Inter-App Audio API is deprecated in favor of Audio Units",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/pauseButtonColor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CAInterAppAudioTransportView(py)pauseButtonColor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pauseButtonColor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIColor",
        "text": "UIColor"
      }
    ],
    "modules": [
      {
        "name": "CoreAudioKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "pauseButtonColor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "8.0",
        "message": "Inter-App Audio API is deprecated in favor of Audio Units",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "8.0",
        "message": "Inter-App Audio API is deprecated in favor of Audio Units",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "message": "Inter-App Audio API is deprecated in favor of Audio Units",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Inter-App Audio API is deprecated in favor of Audio Units",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "pauseButtonColor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pauseButtonColor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIColor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIColor",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit": {
      "abstract": [
        {
          "text": "Add user interfaces to audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreAudioKit",
      "type": "topic",
      "url": "/documentation/coreaudiokit"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView": {
      "abstract": [
        {
          "text": "A view that provides an audio transport user interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAInterAppAudioTransportView"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAInterAppAudioTransportView"
        }
      ],
      "role": "symbol",
      "title": "CAInterAppAudioTransportView",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/currentTimeLabelFont": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentTimeLabelFont"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/currentTimeLabelFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentTimeLabelFont"
        }
      ],
      "role": "symbol",
      "title": "currentTimeLabelFont",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/currenttimelabelfont"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isConnected": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "connected"
        }
      ],
      "role": "symbol",
      "title": "isConnected",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/isconnected"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isEnabled": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/isenabled"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isPlaying": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPlaying"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isPlaying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playing"
        }
      ],
      "role": "symbol",
      "title": "isPlaying",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/isplaying"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isRecording": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRecording"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isRecording",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recording"
        }
      ],
      "role": "symbol",
      "title": "isRecording",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/isrecording"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/labelColor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "labelColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/labelColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "labelColor"
        }
      ],
      "role": "symbol",
      "title": "labelColor",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/labelcolor"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/pauseButtonColor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseButtonColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/pauseButtonColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseButtonColor"
        }
      ],
      "role": "symbol",
      "title": "pauseButtonColor",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/pausebuttoncolor"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/playButtonColor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playButtonColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/playButtonColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playButtonColor"
        }
      ],
      "role": "symbol",
      "title": "playButtonColor",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/playbuttoncolor"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/recordButtonColor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordButtonColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/recordButtonColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordButtonColor"
        }
      ],
      "role": "symbol",
      "title": "recordButtonColor",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/recordbuttoncolor"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/rewindButtonColor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rewindButtonColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/rewindButtonColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rewindButtonColor"
        }
      ],
      "role": "symbol",
      "title": "rewindButtonColor",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/rewindbuttoncolor"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/setOutputAudioUnit(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setOutputAudioUnit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/setOutputAudioUnit(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setOutputAudioUnit:"
        }
      ],
      "role": "symbol",
      "title": "setOutputAudioUnit(_:)",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview/setoutputaudiounit(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/UIKit/UIColor"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isConnected",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/currentTimeLabelFont",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isEnabled",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/labelColor",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/playButtonColor",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isPlaying",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/recordButtonColor",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isRecording",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/rewindButtonColor",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/setOutputAudioUnit(_:)"
      ],
      "title": "Configuring the View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "pauseButtonColor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pauseButtonColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isConnected",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/currentTimeLabelFont",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isEnabled",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/labelColor",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/playButtonColor",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isPlaying",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/recordButtonColor",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/isRecording",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/rewindButtonColor",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView/setOutputAudioUnit(_:)"
              ],
              "title": "Configuring the View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIColor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIColor",
                    "text": "UIColor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "pauseButtonColor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Inter-App Audio API is deprecated in favor of Audio Units",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView/title",
          "value": "CAInterAppAudioTransportView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAInterAppAudioTransportView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAInterAppAudioTransportView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1rewindButtonColor/title",
          "value": "rewindButtonColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1rewindButtonColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rewindButtonColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1setOutputAudioUnit(_:)/title",
          "value": "setOutputAudioUnit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1setOutputAudioUnit(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setOutputAudioUnit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1recordButtonColor/title",
          "value": "recordButtonColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1recordButtonColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordButtonColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1labelColor/title",
          "value": "labelColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1labelColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "labelColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1isRecording/title",
          "value": "recording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1isRecording/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1isPlaying/title",
          "value": "playing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1isPlaying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1isConnected/title",
          "value": "connected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1isConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "connected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1pauseButtonColor/title",
          "value": "pauseButtonColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1pauseButtonColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pauseButtonColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1currentTimeLabelFont/title",
          "value": "currentTimeLabelFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1currentTimeLabelFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentTimeLabelFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1playButtonColor/title",
          "value": "playButtonColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView~1playButtonColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playButtonColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIColor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiokit/cainterappaudiotransportview/pausebuttoncolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiokit/cainterappaudiotransportview/pausebuttoncolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
