{
  "abstract": [
    {
      "text": "The user must launch your app and verify their credentials to continue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INListRideOptionsIntentResponseCode@INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failureRequiringAppLaunchMustVerifyCredentials"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INListRideOptionsIntentResponseCode.failureRequiringAppLaunchMustVerifyCredentials"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failureRequiringAppLaunchMustVerifyCredentials"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this code when you require the user to login or sign up for your service and the user is currently not logged in or signed up. Specify this code to redirect the user to your app to provide the appropriate credentials. Don’t use this response code for general errors or to force the user to launch your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You were unable to retrieve the list of ride options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failurePreviousRideNeedsFeedback": {
      "abstract": [
        {
          "text": "You can’t book a new ride because an existing ride is currently in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failurePreviousRideNeedsFeedback"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failurePreviousRideNeedsFeedback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeFailurePreviousRideNeedsFeedback"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.failurePreviousRideNeedsFeedback",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/failurepreviousrideneedsfeedback"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to get information about the ride options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials": {
      "abstract": [
        {
          "text": "The user must launch your app and verify their credentials to continue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchMustVerifyCredentials"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.failureRequiringAppLaunchMustVerifyCredentials",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/failurerequiringapplaunchmustverifycredentials"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchNoServiceInArea": {
      "abstract": [
        {
          "text": "You do not provide service in the area requested by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchNoServiceInArea"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchNoServiceInArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchNoServiceInArea"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.failureRequiringAppLaunchNoServiceInArea",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/failurerequiringapplaunchnoserviceinarea"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchPreviousRideNeedsCompletion": {
      "abstract": [
        {
          "text": "You can’t book a new ride because an existing ride is currently in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchPreviousRideNeedsCompletion"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchPreviousRideNeedsCompletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchPreviousRideNeedsCompletion"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.failureRequiringAppLaunchPreviousRideNeedsCompletion",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/failurerequiringapplaunchpreviousrideneedscompletion"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "Your service is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchServiceTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.failureRequiringAppLaunchServiceTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/failurerequiringapplaunchservicetemporarilyunavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "You failed to handle the intent in a timely manner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "You are ready to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/success": {
      "abstract": [
        {
          "text": "You successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "No response didn’t specify a response code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchNoServiceInArea",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchPreviousRideNeedsCompletion",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failurePreviousRideNeedsFeedback"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchNoServiceInArea",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failureRequiringAppLaunchPreviousRideNeedsCompletion",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentResponseCode/failurePreviousRideNeedsFeedback"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunchMustVerifyCredentials/title",
          "value": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunchMustVerifyCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failurePreviousRideNeedsFeedback/title",
          "value": "INListRideOptionsIntentResponseCodeFailurePreviousRideNeedsFeedback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failurePreviousRideNeedsFeedback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeFailurePreviousRideNeedsFeedback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1success/title",
          "value": "INListRideOptionsIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1ready/title",
          "value": "INListRideOptionsIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunchPreviousRideNeedsCompletion/title",
          "value": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchPreviousRideNeedsCompletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunchPreviousRideNeedsCompletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchPreviousRideNeedsCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1unspecified/title",
          "value": "INListRideOptionsIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failure/title",
          "value": "INListRideOptionsIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1inProgress/title",
          "value": "INListRideOptionsIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunchServiceTemporarilyUnavailable/title",
          "value": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunchServiceTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode/title",
          "value": "INListRideOptionsIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunchNoServiceInArea/title",
          "value": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchNoServiceInArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentResponseCode~1failureRequiringAppLaunchNoServiceInArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentResponseCodeFailureRequiringAppLaunchNoServiceInArea"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inlistrideoptionsintentresponsecode/failurerequiringapplaunchmustverifycredentials"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inlistrideoptionsintentresponsecode/failurerequiringapplaunchmustverifycredentials"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
