{
  "abstract": [
    {
      "text": "The normalized axis about which the quaternion’s action rotates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_quatf/axis"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "simd",
    "externalID": "s:So10simd_quatfa0A0E4axiss5SIMD3VySfGvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "axis"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5SIMD3V",
        "text": "SIMD3"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "axis"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "axis"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD3V",
              "text": "SIMD3"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": "> { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf": {
      "abstract": [
        {
          "text": "A single-precision quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_quatf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_quatf"
        }
      ],
      "role": "symbol",
      "title": "simd_quatf",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/angle": {
      "abstract": [
        {
          "text": "The angle, in radians, by which the quaternion’s action rotates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "angle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/angle",
      "kind": "symbol",
      "role": "symbol",
      "title": "angle",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/angle"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/axis": {
      "abstract": [
        {
          "text": "The normalized axis about which the quaternion’s action rotates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "axis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/axis",
      "kind": "symbol",
      "role": "symbol",
      "title": "axis",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/axis"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/conjugate": {
      "abstract": [
        {
          "text": "The conjugate of the quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conjugate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/conjugate",
      "kind": "symbol",
      "role": "symbol",
      "title": "conjugate",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/conjugate"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/imag": {
      "abstract": [
        {
          "text": "The imaginary part of the quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/imag",
      "kind": "symbol",
      "role": "symbol",
      "title": "imag",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/imag"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/inverse": {
      "abstract": [
        {
          "text": "The inverse of the quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inverse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/inverse",
      "kind": "symbol",
      "role": "symbol",
      "title": "inverse",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/inverse"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/length": {
      "abstract": [
        {
          "text": "The length of the quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/length",
      "kind": "symbol",
      "role": "symbol",
      "title": "length",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/length"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/normalized": {
      "abstract": [
        {
          "text": "The unit quaternion of the quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/normalized",
      "kind": "symbol",
      "role": "symbol",
      "title": "normalized",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/normalized"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/real": {
      "abstract": [
        {
          "text": "The real part of the quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "real"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/real",
      "kind": "symbol",
      "role": "symbol",
      "title": "real",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/real"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/vector": {
      "abstract": [
        {
          "text": "The underlying vector of the quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/vector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector"
        }
      ],
      "role": "symbol",
      "title": "vector",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/vector"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD3V": {
      "abstract": [
        {
          "text": "A vector of three scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD3",
      "type": "topic",
      "url": "/documentation/Swift/SIMD3"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Querying-a-quaternions-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/angle",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/conjugate",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/imag",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/real",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/inverse",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/length",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/normalized",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/vector"
      ],
      "title": "Querying a quaternion’s properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatf/title",
          "value": "simd_quatf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_quatf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatf/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_quatf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatf~1vector/title",
          "value": "vector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatf~1vector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_quatf/axis"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
