{
  "abstract": [
    {
      "text": "Creates a new quaternion with an action that’s a rotation between two vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(from:to:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "simd",
    "externalID": "s:So10simd_quatfa0A0E4from2toABs5SIMD3VySfG_AHtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "from"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5SIMD3V",
        "text": "SIMD3"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "externalParam",
        "text": "to"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5SIMD3V",
        "text": "SIMD3"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ">)"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(from:to:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD3V",
              "text": "SIMD3"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "to"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD3V",
              "text": "SIMD3"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ">)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A normalized three-element vector that specifies the start of the rotation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "from"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A normalized three-element vector that specifies the end of the rotation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "to"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf": {
      "abstract": [
        {
          "text": "A single-precision quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_quatf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_quatf"
        }
      ],
      "role": "symbol",
      "title": "simd_quatf",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/init()": {
      "abstract": [
        {
          "text": "Creates a new quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/init()"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(_:)-1hlsg": {
      "abstract": [
        {
          "text": "Creates a new quaternion from a 3 x 3 rotation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(_:)-1hlsg",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/init(_:)-1hlsg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(_:)-3751": {
      "abstract": [
        {
          "text": "Creates a new quaternion from a 4 x 4 rotation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(_:)-3751",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/init(_:)-3751"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(_:)-9rvr0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@UA@SPRotation3D",
          "text": "Rotation3D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(_:)-9rvr0",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/init(_:)-9rvr0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(angle:axis:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion with an action that’s a rotation about an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "angle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "axis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(angle:axis:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(angle:axis:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/init(angle:axis:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(from:to:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion with an action that’s a rotation between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(from:to:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(from:to:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/init(from:to:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(ix:iy:iz:r:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion from four scalar values that specify the imaginary and real parts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "iy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "iz"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "r"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(ix:iy:iz:r:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(ix:iy:iz:r:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/init(ix:iy:iz:r:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(real:imag:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion from a scalar real part and a vector imaginary part.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "real"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "imag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(real:imag:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(real:imag:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/init(real:imag:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(vector:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion from a four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "vector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(vector:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(vector:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatf/init(vector:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD3V": {
      "abstract": [
        {
          "text": "A vector of three scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD3",
      "type": "topic",
      "url": "/documentation/Swift/SIMD3"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializing-a-quaternion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/init()",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(vector:)",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(_:)-1hlsg",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(_:)-3751",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(angle:axis:)",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(ix:iy:iz:r:)",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(real:imag:)",
        "doc://com.apple.accelerate/documentation/simd/simd_quatf/init(_:)-9rvr0"
      ],
      "title": "Initializing a quaternion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatf/title",
          "value": "simd_quatf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_quatf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatf/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_quatf"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_quatf/init(from:to:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
