{
  "abstract": [
    {
      "text": "A structure that defines life cycle callbacks for an audio processing tap object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@MTAudioProcessingTapCallbacks",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTAudioProcessingTapCallbacks"
      }
    ],
    "modules": [
      {
        "name": "Media Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTAudioProcessingTapCallbacks"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTAudioProcessingTapCallbacks"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapCallbacks"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On 64-bit architectures, this struct contains misaligned function pointers. To avoid link-time issues, fill its function pointer fields by using assignment statements, rather than declaring them as global or static structs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox": {
      "abstract": [
        {
          "text": "Enable support for media format readers; tap and process audio from an audio mix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Toolbox",
      "type": "topic",
      "url": "/documentation/mediatoolbox"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks": {
      "abstract": [
        {
          "text": "A structure that defines life cycle callbacks for an audio processing tap object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapCallbacks"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapCallbacks"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapCallbacks",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/clientInfo": {
      "abstract": [
        {
          "text": "App data that the system passes to the initialization callback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/clientInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientInfo"
        }
      ],
      "role": "symbol",
      "title": "clientInfo",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks/clientinfo"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/finalize": {
      "abstract": [
        {
          "text": "A callback to perform any necessary cleanup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finalize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapFinalizeCallback",
          "text": "MTAudioProcessingTapFinalizeCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/finalize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finalize"
        }
      ],
      "role": "symbol",
      "title": "finalize",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks/finalize"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/init": {
      "abstract": [
        {
          "text": "A callback to initialize the tap processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`init`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapInitCallback",
          "text": "MTAudioProcessingTapInitCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/init",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks/init"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/init(version:clientInfo:init:finalize:prepare:unprepare:process:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "init"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapInitCallback",
          "text": "MTAudioProcessingTapInitCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "finalize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapFinalizeCallback",
          "text": "MTAudioProcessingTapFinalizeCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapPrepareCallback",
          "text": "MTAudioProcessingTapPrepareCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "unprepare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapUnprepareCallback",
          "text": "MTAudioProcessingTapUnprepareCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "process"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapProcessCallback",
          "text": "MTAudioProcessingTapProcessCallback"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/init(version:clientInfo:init:finalize:prepare:unprepare:process:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:clientInfo:init:finalize:prepare:unprepare:process:)",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks/init(version:clientinfo:init:finalize:prepare:unprepare:process:)"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/prepare": {
      "abstract": [
        {
          "text": "A callback to prepare the tap processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapPrepareCallback",
          "text": "MTAudioProcessingTapPrepareCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/prepare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepare"
        }
      ],
      "role": "symbol",
      "title": "prepare",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks/prepare"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/process": {
      "abstract": [
        {
          "text": "A callback for processing the audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "process"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapProcessCallback",
          "text": "MTAudioProcessingTapProcessCallback"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/process",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "process"
        }
      ],
      "role": "symbol",
      "title": "process",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks/process"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/unprepare": {
      "abstract": [
        {
          "text": "A callback to perform any necessary cleanup for previous preparation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unprepare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapUnprepareCallback",
          "text": "MTAudioProcessingTapUnprepareCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/unprepare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unprepare"
        }
      ],
      "role": "symbol",
      "title": "unprepare",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks/unprepare"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/version": {
      "abstract": [
        {
          "text": "The version number of the structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks/version"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapFinalizeCallback": {
      "abstract": [
        {
          "text": "A finalization callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapFinalizeCallback"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapFinalizeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapFinalizeCallback"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapFinalizeCallback",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapfinalizecallback"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapInitCallback": {
      "abstract": [
        {
          "text": "An initialization callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapInitCallback"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapInitCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapInitCallback"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapInitCallback",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapinitcallback"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapPrepareCallback": {
      "abstract": [
        {
          "text": "An audio processing preparation callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapPrepareCallback"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapPrepareCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapPrepareCallback"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapPrepareCallback",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtappreparecallback"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapProcessCallback": {
      "abstract": [
        {
          "text": "An audio processing callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapProcessCallback"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapProcessCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapProcessCallback"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapProcessCallback",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapprocesscallback"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapUnprepareCallback": {
      "abstract": [
        {
          "text": "An audio processing unpreparation callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapUnprepareCallback"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapUnprepareCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapUnprepareCallback"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapUnprepareCallback",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapunpreparecallback"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/kMTAudioProcessingTapCallbacksVersion_0": {
      "abstract": [
        {
          "text": "An identifier for version 0 of the callbacks structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMTAudioProcessingTapCallbacksVersion_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/kMTAudioProcessingTapCallbacksVersion_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMTAudioProcessingTapCallbacksVersion_0"
        }
      ],
      "role": "symbol",
      "title": "kMTAudioProcessingTapCallbacksVersion_0",
      "type": "topic",
      "url": "/documentation/mediatoolbox/kmtaudioprocessingtapcallbacksversion_0"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Fields",
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/version",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/clientInfo",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/init",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/finalize",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/prepare",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/unprepare",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/process"
      ],
      "title": "Fields"
    },
    {
      "anchor": "Callback-functions",
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapInitCallback",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapPrepareCallback",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapProcessCallback",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapUnprepareCallback",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapFinalizeCallback"
      ],
      "title": "Callback functions"
    },
    {
      "anchor": "Versions",
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/kMTAudioProcessingTapCallbacksVersion_0"
      ],
      "title": "Versions"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/init(version:clientInfo:init:finalize:prepare:unprepare:process:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTAudioProcessingTapCallbacks"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Fields",
              "identifiers": [
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/version",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/clientInfo",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/init",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/finalize",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/prepare",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/unprepare",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCallbacks/process"
              ],
              "title": "Fields"
            },
            {
              "anchor": "Callback-functions",
              "identifiers": [
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapInitCallback",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapPrepareCallback",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapProcessCallback",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapUnprepareCallback",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapFinalizeCallback"
              ],
              "title": "Callback functions"
            },
            {
              "anchor": "Versions",
              "identifiers": [
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/kMTAudioProcessingTapCallbacksVersion_0"
              ],
              "title": "Versions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTAudioProcessingTapCallbacks"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1init/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1init/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapFinalizeCallback/title",
          "value": "MTAudioProcessingTapFinalizeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapFinalizeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapFinalizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapFinalizeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapFinalizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapPrepareCallback/title",
          "value": "MTAudioProcessingTapPrepareCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapPrepareCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapPrepareCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapPrepareCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapPrepareCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1prepare/title",
          "value": "prepare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1prepare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prepare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1process/title",
          "value": "process"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1process/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "process"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1unprepare/title",
          "value": "unprepare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1unprepare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unprepare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapInitCallback/title",
          "value": "MTAudioProcessingTapInitCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapInitCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapInitCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapInitCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapInitCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1clientInfo/title",
          "value": "clientInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1clientInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clientInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapUnprepareCallback/title",
          "value": "MTAudioProcessingTapUnprepareCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapUnprepareCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapUnprepareCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapUnprepareCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapUnprepareCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1kMTAudioProcessingTapCallbacksVersion_0/title",
          "value": "kMTAudioProcessingTapCallbacksVersion_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1kMTAudioProcessingTapCallbacksVersion_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMTAudioProcessingTapCallbacksVersion_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks/title",
          "value": "MTAudioProcessingTapCallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1finalize/title",
          "value": "finalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCallbacks~1finalize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "finalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapProcessCallback/title",
          "value": "MTAudioProcessingTapProcessCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapProcessCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapProcessCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapProcessCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapProcessCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediatoolbox/mtaudioprocessingtapcallbacks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
