{
  "abstract": [
    {
      "text": "Enables the use of media format readers that support professional video workflows.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTRegisterProfessionalVideoWorkflowFormatReaders()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MTRegisterProfessionalVideoWorkflowFormatReaders",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Media Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MTRegisterProfessionalVideoWorkflowFormatReaders()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this function to indicate to Media Toolbox that your app requires support for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaExtension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " format readers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This functionality is only intended for apps that support professional video workflows. It isn’t recommended for network-facing applications such as web browsers, messaging clients, mail clients, and so on.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "By convention, format readers registered using this function should conform to the abstract ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UniformTypeIdentifiers/UTTypeReference",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of ",
              "type": "text"
            },
            {
              "code": "com.apple.mediaextension-content",
              "type": "codeVoice"
            },
            {
              "text": " which in turn conforms to the abstract type ",
              "type": "text"
            },
            {
              "code": "public.movie",
              "type": "codeVoice"
            },
            {
              "text": ". You can use ",
              "type": "text"
            },
            {
              "code": "com.apple.mediaextension-content",
              "type": "codeVoice"
            },
            {
              "text": " to do type filtering (for example in Open… dialogs).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/MediaExtension"
    },
    "doc://com.apple.documentation/documentation/UniformTypeIdentifiers/UTTypeReference": {
      "abstract": [
        {
          "text": "An object that represents a type of data to load, send, or receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UTTypeReference"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UniformTypeIdentifiers/UTTypeReference",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeReference",
      "type": "topic",
      "url": "/documentation/UniformTypeIdentifiers/UTTypeReference"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox": {
      "abstract": [
        {
          "text": "Enable support for media format readers; tap and process audio from an audio mix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Toolbox",
      "type": "topic",
      "url": "/documentation/mediatoolbox"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTRegisterProfessionalVideoWorkflowFormatReaders()": {
      "abstract": [
        {
          "text": "Enables the use of media format readers that support professional video workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTRegisterProfessionalVideoWorkflowFormatReaders()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
        }
      ],
      "role": "symbol",
      "title": "MTRegisterProfessionalVideoWorkflowFormatReaders()",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtregisterprofessionalvideoworkflowformatreaders()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRegisterProfessionalVideoWorkflowFormatReaders"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTRegisterProfessionalVideoWorkflowFormatReaders()/title",
          "value": "MTRegisterProfessionalVideoWorkflowFormatReaders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTRegisterProfessionalVideoWorkflowFormatReaders()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UniformTypeIdentifiers~1UTTypeReference/title",
          "value": "UTType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UniformTypeIdentifiers~1UTTypeReference/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UTType"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediatoolbox/mtregisterprofessionalvideoworkflowformatreaders()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediatoolbox/mtregisterprofessionalvideoworkflowformatreaders()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
