{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklook/documentation/QuickLook",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@QLPreviewItemEditingMode@QLPreviewItemEditingModeUpdateContents",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "updateContents"
      }
    ],
    "modules": [
      {
        "name": "Quick Look"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLPreviewItemEditingModeUpdateContents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "QLPreviewItemEditingMode.updateContents"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "updateContents"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklook/documentation/QuickLook": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your app, or perform simple edits on previews.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look",
      "type": "topic",
      "url": "/documentation/quicklook"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingMode"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingMode"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemEditingMode",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateContents"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingModeUpdateContents"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemEditingMode.updateContents",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode/updatecontents"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLPreviewItemEditingModeUpdateContents"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingModeUpdateContents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklook/documentation/QuickLook",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "QLPreviewItemEditingModeUpdateContents"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode/title",
          "value": "QLPreviewItemEditingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1updateContents/title",
          "value": "QLPreviewItemEditingModeUpdateContents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1updateContents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingModeUpdateContents"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklook/qlpreviewitemeditingmode/updatecontents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklook/qlpreviewitemeditingmode/updatecontents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
