{
  "abstract": [
    {
      "text": "The report comes from the user, without health authority involvement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/selfReported"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ENDiagnosisReportType@ENDiagnosisReportTypeSelfReported",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "selfReported"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ENDiagnosisReportTypeSelfReported"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ENDiagnosisReportType.selfReported"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "selfReported"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType": {
      "abstract": [
        {
          "text": "The type of a report that describes the origin of a diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportType"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/confirmedClinicalDiagnosis": {
      "abstract": [
        {
          "text": "The report comes from a confirmed clinical diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirmedClinicalDiagnosis"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/confirmedClinicalDiagnosis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportTypeConfirmedClinicalDiagnosis"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType.confirmedClinicalDiagnosis",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype/confirmedclinicaldiagnosis"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/confirmedTest": {
      "abstract": [
        {
          "text": "The report comes from a confirmed test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirmedTest"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/confirmedTest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportTypeConfirmedTest"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType.confirmedTest",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype/confirmedtest"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/recursive": {
      "abstract": [
        {
          "text": "The report comes from a person determined positive based on exposure to another person confirmed positive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recursive"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/recursive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportTypeRecursive"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType.recursive",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype/recursive"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/revoked": {
      "abstract": [
        {
          "text": "The report is a negative test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "revoked"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/revoked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportTypeRevoked"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType.revoked",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype/revoked"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/selfReported": {
      "abstract": [
        {
          "text": "The report comes from the user, without health authority involvement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selfReported"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/selfReported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportTypeSelfReported"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType.selfReported",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype/selfreported"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/unknown": {
      "abstract": [
        {
          "text": "The report is an unknown type or is not available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType.unknown",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/confirmedClinicalDiagnosis",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/confirmedTest",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/recursive",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/revoked",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/unknown"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ENDiagnosisReportTypeSelfReported"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportTypeSelfReported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/confirmedClinicalDiagnosis",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/confirmedTest",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/recursive",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/revoked",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ENDiagnosisReportTypeSelfReported"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1confirmedTest/title",
          "value": "ENDiagnosisReportTypeConfirmedTest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1confirmedTest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportTypeConfirmedTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/title",
          "value": "ENDiagnosisReportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1selfReported/title",
          "value": "ENDiagnosisReportTypeSelfReported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1selfReported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportTypeSelfReported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1revoked/title",
          "value": "ENDiagnosisReportTypeRevoked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1revoked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportTypeRevoked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1confirmedClinicalDiagnosis/title",
          "value": "ENDiagnosisReportTypeConfirmedClinicalDiagnosis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1confirmedClinicalDiagnosis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportTypeConfirmedClinicalDiagnosis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1recursive/title",
          "value": "ENDiagnosisReportTypeRecursive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1recursive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportTypeRecursive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1unknown/title",
          "value": "ENDiagnosisReportTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportTypeUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/endiagnosisreporttype/selfreported"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/endiagnosisreporttype/selfreported"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
