{
  "abstract": [
    {
      "text": "A handler that the framework calls when the guest environment has a new frame to display.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/newFrameEventHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PGDisplay(py)newFrameEventHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "newFrameEventHandler"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@PGDisplayNewFrameEventHandler",
        "text": "PGDisplayNewFrameEventHandler"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Paravirtualized Graphics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "newFrameEventHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "newFrameEventHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "newFrameEventHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayNewFrameEventHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PGDisplayNewFrameEventHandler",
              "text": "PGDisplayNewFrameEventHandler"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics": {
      "abstract": [
        {
          "text": "Add graphics acceleration to your guest driver stack.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
      "kind": "symbol",
      "role": "collection",
      "title": "Paravirtualized Graphics",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay": {
      "abstract": [
        {
          "text": "An object that provides display functionality to the guest operating system in a way that the host-side virtual machine app can intercept.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplay"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplay"
        }
      ],
      "role": "symbol",
      "title": "PGDisplay",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplay"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/cursorGlyphHandler": {
      "abstract": [
        {
          "text": "A handler that the framework calls to change the cursor’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursorGlyphHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDisplayCursorGlyphHandler",
          "text": "PGDisplayCursorGlyphHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/cursorGlyphHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cursorGlyphHandler"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cursorGlyphHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplay/cursorglyphhandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/cursorShowHandler": {
      "abstract": [
        {
          "text": "A handler that the framework calls to change the cursor’s visibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursorShowHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDisplayCursorShowHandler",
          "text": "PGDisplayCursorShowHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/cursorShowHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cursorShowHandler"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cursorShowHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplay/cursorshowhandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/modeChangeHandler": {
      "abstract": [
        {
          "text": "A handler that the framework calls to change the virtual display’s graphics mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modeChangeHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDisplayModeChangeHandler",
          "text": "PGDisplayModeChangeHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/modeChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modeChangeHandler"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "modeChangeHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplay/modechangehandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/newFrameEventHandler": {
      "abstract": [
        {
          "text": "A handler that the framework calls when the guest environment has a new frame to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newFrameEventHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDisplayNewFrameEventHandler",
          "text": "PGDisplayNewFrameEventHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/newFrameEventHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newFrameEventHandler"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "newFrameEventHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplay/newframeeventhandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/queue": {
      "abstract": [
        {
          "text": "The queue that the framework uses when dispatching messages to any of the display’s registered handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/queue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queue"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "queue",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplay/queue"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayNewFrameEventHandler": {
      "abstract": [
        {
          "text": "The block signature for a routine that handles frame updates from the guest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplayNewFrameEventHandler"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayNewFrameEventHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplayNewFrameEventHandler"
        }
      ],
      "role": "symbol",
      "title": "PGDisplayNewFrameEventHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaynewframeeventhandler"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-Display-Handlers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/queue",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/cursorGlyphHandler",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/cursorShowHandler",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/modeChangeHandler"
      ],
      "title": "Inspecting the Display Handlers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "newFrameEventHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "newFrameEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-Display-Handlers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/queue",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/cursorGlyphHandler",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/cursorShowHandler",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay/modeChangeHandler"
              ],
              "title": "Inspecting the Display Handlers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayNewFrameEventHandler",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@PGDisplayNewFrameEventHandler",
                    "text": "PGDisplayNewFrameEventHandler"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "newFrameEventHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1cursorGlyphHandler/title",
          "value": "cursorGlyphHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1cursorGlyphHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cursorGlyphHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1newFrameEventHandler/title",
          "value": "newFrameEventHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1newFrameEventHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "newFrameEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay/title",
          "value": "PGDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayNewFrameEventHandler/title",
          "value": "PGDisplayNewFrameEventHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayNewFrameEventHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayNewFrameEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayNewFrameEventHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayNewFrameEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1cursorShowHandler/title",
          "value": "cursorShowHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1cursorShowHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cursorShowHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1queue/title",
          "value": "queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1queue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1modeChangeHandler/title",
          "value": "modeChangeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay~1modeChangeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modeChangeHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgdisplay/newframeeventhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgdisplay/newframeeventhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
