{
  "abstract": [
    {
      "text": "The preference for the device not to store the resident key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/discouraged"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AuthenticationServices",
    "externalID": "c:@ASAuthorizationPublicKeyCredentialResidentKeyPreferenceDiscouraged",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "discouraged"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialResidentKeyPreference",
        "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceDiscouraged"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "discouraged"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "discouraged"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialResidentKeyPreference",
              "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference": {
      "abstract": [
        {
          "text": "A structure that specifies the relying party’s preference for resident key storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationPublicKeyCredentialResidentKeyPreference",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationpublickeycredentialresidentkeypreference"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/discouraged": {
      "abstract": [
        {
          "text": "The preference for the device not to store the resident key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discouraged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialResidentKeyPreference",
          "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/discouraged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceDiscouraged"
        }
      ],
      "role": "symbol",
      "title": "discouraged",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationpublickeycredentialresidentkeypreference/discouraged"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/preferred": {
      "abstract": [
        {
          "text": "The preference for the device to store the resident key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferred"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialResidentKeyPreference",
          "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/preferred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreferencePreferred"
        }
      ],
      "role": "symbol",
      "title": "preferred",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationpublickeycredentialresidentkeypreference/preferred"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/required": {
      "abstract": [
        {
          "text": "The device must store the resident key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "required"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialResidentKeyPreference",
          "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/required",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceRequired"
        }
      ],
      "role": "symbol",
      "title": "required",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationpublickeycredentialresidentkeypreference/required"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-preferences",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/preferred",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/required"
      ],
      "title": "Getting preferences"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceDiscouraged"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceDiscouraged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-preferences",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/preferred",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference/required"
              ],
              "title": "Getting preferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialResidentKeyPreference",
                    "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceDiscouraged"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference~1preferred/title",
          "value": "ASAuthorizationPublicKeyCredentialResidentKeyPreferencePreferred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference~1preferred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreferencePreferred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference~1required/title",
          "value": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference~1required/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference~1discouraged/title",
          "value": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceDiscouraged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference~1discouraged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreferenceDiscouraged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference/title",
          "value": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialResidentKeyPreference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationpublickeycredentialresidentkeypreference/discouraged"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationpublickeycredentialresidentkeypreference/discouraged"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
