{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/unsupportedOrientation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC21GLKTextureLoaderErrorLeV22unsupportedOrientationSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unsupportedOrientation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC21GLKTextureLoaderErrorLeV",
        "text": "GLKTextureLoaderError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@GLKTextureLoaderError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "unsupportedOrientation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unsupportedOrientation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC21GLKTextureLoaderErrorLeV",
              "text": "GLKTextureLoaderError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@GLKTextureLoaderError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderError"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderError"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Values to be returned when a texture loader encounters an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/unsupportedOrientation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21GLKTextureLoaderErrorLeV",
          "text": "GLKTextureLoaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GLKTextureLoaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/unsupportedOrientation",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedOrientation",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/unsupportedorientation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/title",
          "value": "GLKTextureLoaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glktextureloadererror-swift.struct/unsupportedorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
