{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkdiscretequantitysample/averagequantity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkdiscretequantitysample/averagequantity"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/averageQuantity","interfaceLanguage":"swift"},"abstract":[{"text":"The average of all quantities contained by the sample.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"averageQuantity"}],"externalID":"c:objc(cs)HKDiscreteQuantitySample(py)averageQuantity","platforms":[{"name":"iOS","introducedAt":"13.0","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"13.0","name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"13.0","name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"13.0","name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"6.0","name":"watchOS","beta":false,"deprecated":false,"unavailable":false}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"averageQuantity","modules":[{"name":"HealthKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"averageQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity","text":"HKQuantity"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"@NSCopying","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"averageQuantity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKQuantity","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuantity","text":"HKQuantity","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"seeAlsoSections":[{"generated":true,"title":"Accessing Calculated Values","anchor":"Accessing-Calculated-Values","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/maximumQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/minimumQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/mostRecentQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/mostRecentQuantityDateInterval"]}],"references":{"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/averageQuantity":{"abstract":[{"text":"The average of all quantities contained by the sample.","type":"text"}],"url":"/documentation/healthkit/hkdiscretequantitysample/averagequantity","role":"symbol","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/averageQuantity","title":"averageQuantity","type":"topic","navigatorTitle":[{"kind":"identifier","text":"averageQuantity"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"averageQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity","text":"HKQuantity"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/maximumQuantity":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The maximum quantity contained by the sample."}],"title":"maximumQuantity","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/maximumQuantity","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumQuantity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKQuantity","preciseIdentifier":"c:objc(cs)HKQuantity","kind":"typeIdentifier"}],"url":"/documentation/healthkit/hkdiscretequantitysample/maximumquantity","navigatorTitle":[{"text":"maximumQuantity","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A sample that represents a discrete quantity."}],"title":"HKDiscreteQuantitySample","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKDiscreteQuantitySample","kind":"identifier"}],"url":"/documentation/healthkit/hkdiscretequantitysample","navigatorTitle":[{"text":"HKDiscreteQuantitySample","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/mostRecentQuantityDateInterval":{"abstract":[{"text":"The date interval for the most recent quantity contained by the sample.","type":"text"}],"url":"/documentation/healthkit/hkdiscretequantitysample/mostrecentquantitydateinterval","role":"symbol","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/mostRecentQuantityDateInterval","title":"mostRecentQuantityDateInterval","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mostRecentQuantityDateInterval"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mostRecentQuantityDateInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateInterval","preciseIdentifier":"s:10Foundation12DateIntervalV"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/minimumQuantity":{"abstract":[{"text":"The minimum value contained by the sample.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/minimumQuantity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity","text":"HKQuantity"}],"title":"minimumQuantity","url":"/documentation/healthkit/hkdiscretequantitysample/minimumquantity","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minimumQuantity"}],"kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuantity":{"title":"HKQuantity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKQuantity","kind":"identifier"}],"url":"/documentation/healthkit/hkquantity","abstract":[{"text":"An object that stores a value for a given unit.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuantity","type":"topic","role":"symbol","navigatorTitle":[{"text":"HKQuantity","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/mostRecentQuantity":{"abstract":[{"type":"text","text":"The most recent quantity contained by the sample."}],"url":"/documentation/healthkit/hkdiscretequantitysample/mostrecentquantity","role":"symbol","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/mostRecentQuantity","title":"mostRecentQuantity","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mostRecentQuantity"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mostRecentQuantity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKQuantity","preciseIdentifier":"c:objc(cs)HKQuantity","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","introducedAt":"13.0","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","introducedAt":"13.0","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"13.0","name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"13.0","name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"6.0","name":"watchOS","beta":false,"deprecated":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"averageQuantity","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"averageQuantity"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/maximumQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/minimumQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/mostRecentQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample/mostRecentQuantityDateInterval"],"anchor":"Accessing-Calculated-Values","title":"Accessing Calculated Values","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"HKQuantity","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuantity","preciseIdentifier":"c:objc(cs)HKQuantity","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"averageQuantity","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1averageQuantity/title","value":"averageQuantity"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1averageQuantity/fragments","value":[{"text":"averageQuantity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1maximumQuantity/title","value":"maximumQuantity"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1maximumQuantity/fragments","value":[{"kind":"identifier","text":"maximumQuantity"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample/title","value":"HKDiscreteQuantitySample"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample/fragments","value":[{"text":"HKDiscreteQuantitySample","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample/navigatorTitle","value":[{"kind":"identifier","text":"HKDiscreteQuantitySample"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1mostRecentQuantityDateInterval/title","value":"mostRecentQuantityDateInterval"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1mostRecentQuantityDateInterval/fragments","value":[{"text":"mostRecentQuantityDateInterval","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1minimumQuantity/title","value":"minimumQuantity"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1minimumQuantity/fragments","op":"replace","value":[{"kind":"identifier","text":"minimumQuantity"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/title","op":"replace","value":"HKQuantity"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/fragments","op":"replace","value":[{"text":"HKQuantity","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/navigatorTitle","op":"replace","value":[{"text":"HKQuantity","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1mostRecentQuantity/title","op":"replace","value":"mostRecentQuantity"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample~1mostRecentQuantity/fragments","op":"replace","value":[{"text":"mostRecentQuantity","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}