{
  "abstract": [
    {
      "text": "A string returned by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " API that corresponds to the argument.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.oslog/documentation/OSLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/string(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So21OSLogMessageComponentC0A0E8ArgumentO6stringyAESScAEmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "string"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "OSLog"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "OSLogMessageComponent.Argument.string(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "string"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.oslog/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/oslog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent": {
      "abstract": [
        {
          "text": "The message arguments for a particular entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogMessageComponent"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponent"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum": {
      "abstract": [
        {
          "text": "An object representing data that corresponds to an argument in a message payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Argument"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Argument"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.Argument",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.enum"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/data(_:)": {
      "abstract": [
        {
          "text": "A data object returned by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.oslog/documentation/OSLog",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " API that corresponds to the argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/data(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "OSLogMessageComponent.Argument.data(_:)",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.enum/data(_:)"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/double(_:)": {
      "abstract": [
        {
          "text": "A double returned by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.oslog/documentation/OSLog",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " API that corresponds to the argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/double(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "OSLogMessageComponent.Argument.double(_:)",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.enum/double(_:)"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/signed(_:)": {
      "abstract": [
        {
          "text": "A signed 64-bit integer returned by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.oslog/documentation/OSLog",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " API that corresponds to the argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/signed(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "OSLogMessageComponent.Argument.signed(_:)",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.enum/signed(_:)"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/string(_:)": {
      "abstract": [
        {
          "text": "A string returned by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.oslog/documentation/OSLog",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " API that corresponds to the argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/string(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "OSLogMessageComponent.Argument.string(_:)",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.enum/string(_:)"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/undefined": {
      "abstract": [
        {
          "text": "A undefined object returned by the OSLog API that corresponds to the argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/undefined",
      "kind": "symbol",
      "role": "symbol",
      "title": "OSLogMessageComponent.Argument.undefined",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.enum/undefined"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/unsigned(_:)": {
      "abstract": [
        {
          "text": "An unsigned 64-bit integer returned by the OSLog API that corresponds to the argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsigned"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/unsigned(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "OSLogMessageComponent.Argument.unsigned(_:)",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.enum/unsigned(_:)"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/data(_:)",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/double(_:)",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/signed(_:)",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/undefined",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum/unsigned(_:)"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/title",
          "value": "OSLogMessageComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/oslog/oslogmessagecomponent/argument-swift.enum/string(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
