{
  "abstract": [
    {
      "text": "The button displayed in the status bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSStatusItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/button"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSStatusItem(py)button",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "button"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSStatusBarButton",
        "text": "NSStatusBarButton"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "button"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "button"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "button"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSStatusBarButton",
              "text": "NSStatusBarButton"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The status item automatically creates this button by default. Use this property to customize the appearance and behavior of the button, such as its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/image",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/target",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/action",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/toolTip",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and so on.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/image": {
      "abstract": [
        {
          "text": "The image that appears on the button when it’s in an off state, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if there is no such image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/image"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/action": {
      "abstract": [
        {
          "text": "The default action-message selector associated with the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "action"
        }
      ],
      "role": "symbol",
      "title": "action",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/action"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/target": {
      "abstract": [
        {
          "text": "The target object that receives action messages from the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": AnyObject?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/target",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/target"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton": {
      "abstract": [
        {
          "text": "The appearance and behavior of an item in the systemwide menu bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStatusBarButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStatusBarButton"
        }
      ],
      "role": "symbol",
      "title": "NSStatusBarButton",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusbarbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusItem": {
      "abstract": [
        {
          "text": "An individual element displayed in the system menu bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStatusItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStatusItem"
        }
      ],
      "role": "symbol",
      "title": "NSStatusItem",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/Behavior-swift.struct": {
      "abstract": [
        {
          "text": "A set of optional status item behaviors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Behavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/Behavior-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Behavior"
        }
      ],
      "role": "symbol",
      "title": "NSStatusItem.Behavior",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusitem/behavior-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/behavior-swift.property": {
      "abstract": [
        {
          "text": "The set of allowed behaviors for the status item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSStatusItem",
          "text": "NSStatusItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSStatusItemBehavior",
          "text": "Behavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/behavior-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behavior"
        }
      ],
      "role": "symbol",
      "title": "behavior",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusitem/behavior-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/button": {
      "abstract": [
        {
          "text": "The button displayed in the status bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "button"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSStatusBarButton",
          "text": "NSStatusBarButton"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/button",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "button"
        }
      ],
      "role": "symbol",
      "title": "button",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusitem/button"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/menu": {
      "abstract": [
        {
          "text": "The pull-down menu displayed when the user clicks the status item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/menu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menu"
        }
      ],
      "role": "symbol",
      "title": "menu",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusitem/menu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/toolTip": {
      "abstract": [
        {
          "text": "The text for the view’s tooltip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/toolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolTip"
        }
      ],
      "role": "symbol",
      "title": "toolTip",
      "type": "topic",
      "url": "/documentation/appkit/nsview/tooltip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Status-Items-Behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/behavior-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/Behavior-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/menu"
      ],
      "title": "Managing the Status Item’s Behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "button"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "button"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSStatusItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Status-Items-Behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/behavior-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/Behavior-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSStatusItem/menu"
              ],
              "title": "Managing the Status Item’s Behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSStatusBarButton",
                    "text": "NSStatusBarButton"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "button"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem~1button/title",
          "value": "button"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem~1button/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "button"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1action/title",
          "value": "action"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "action"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem~1behavior-swift.property/title",
          "value": "behavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem~1behavior-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem/title",
          "value": "NSStatusItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem~1Behavior-swift.struct/title",
          "value": "NSStatusItemBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem~1Behavior-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusItemBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem~1Behavior-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusItemBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1target/title",
          "value": "target"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1target/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem~1menu/title",
          "value": "menu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem~1menu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "menu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBarButton/title",
          "value": "NSStatusBarButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBarButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBarButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1toolTip/title",
          "value": "toolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1toolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolTip"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsstatusitem/button"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsstatusitem/button"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
