{
  "abstract": [
    {
      "text": "The material property’s value is a 4 x 4 floating-point matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/matrix44"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLMaterialPropertyType@MDLMaterialPropertyTypeMatrix44",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "matrix44"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLMaterialPropertyTypeMatrix44"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MDLMaterialPropertyType.matrix44"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "matrix44"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/matrix4x4",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to access the material property’s value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/matrix4x4": {
      "abstract": [
        {
          "text": "The 4 x 4 floating-point matrix value for the material property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix4x4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@matrix_float4x4",
          "text": "matrix_float4x4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/matrix4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matrix4x4"
        }
      ],
      "role": "symbol",
      "title": "matrix4x4",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialproperty/matrix4x4"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/type": {
      "abstract": [
        {
          "text": "The data type stored in the material property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialPropertyType",
          "text": "MDLMaterialPropertyType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialproperty/type"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType": {
      "abstract": [
        {
          "text": "Options for the data type of a material property, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/type",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyType"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/URL": {
      "abstract": [
        {
          "text": "The material property’s value is a URL—typically, a URL referencing a texture image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/URL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeURL"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.URL",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/url"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/color": {
      "abstract": [
        {
          "text": "The material property’s value is a uniform color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeColor"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.color",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/color"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float": {
      "abstract": [
        {
          "text": "The material property’s value is a floating-point scalar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeFloat"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.float",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/float"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float2": {
      "abstract": [
        {
          "text": "The material property’s value is a 2-component floating-point vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float2"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeFloat2"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.float2",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/float2"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float3": {
      "abstract": [
        {
          "text": "The material property’s value is a 3-component floating-point vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float3"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeFloat3"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.float3",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/float3"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float4": {
      "abstract": [
        {
          "text": "The material property’s value is a 4-component floating-point vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeFloat4"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.float4",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/float4"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/matrix44": {
      "abstract": [
        {
          "text": "The material property’s value is a 4 x 4 floating-point matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix44"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/matrix44",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeMatrix44"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.matrix44",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/matrix44"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/none": {
      "abstract": [
        {
          "text": "The material property’s value has not been initialized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeNone"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.none",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/none"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/string": {
      "abstract": [
        {
          "text": "The material’s value is a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeString"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.string",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/string"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/texture": {
      "abstract": [
        {
          "text": "The material property’s value is a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureSampler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object that provides both a texture image and texture rendering parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/texture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialPropertyTypeTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialPropertyType.texture",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialpropertytype/texture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureSampler": {
      "abstract": [
        {
          "text": "An object that pairs a source of texture data with sampling parameters to be used in rendering the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTextureSampler"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureSampler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLTextureSampler"
        }
      ],
      "role": "symbol",
      "title": "MDLTextureSampler",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturesampler"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/none",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/string",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/URL",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/texture",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/color",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float2",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float3",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float4"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLMaterialPropertyTypeMatrix44"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeMatrix44"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/none",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/string",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/URL",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/texture",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/color",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float2",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float3",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyType/float4"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MDLMaterialPropertyTypeMatrix44"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1color/title",
          "value": "MDLMaterialPropertyTypeColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1float/title",
          "value": "MDLMaterialPropertyTypeFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1float2/title",
          "value": "MDLMaterialPropertyTypeFloat2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1float2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeFloat2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1float3/title",
          "value": "MDLMaterialPropertyTypeFloat3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1float3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeFloat3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType/title",
          "value": "MDLMaterialPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1float4/title",
          "value": "MDLMaterialPropertyTypeFloat4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1float4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeFloat4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1string/title",
          "value": "MDLMaterialPropertyTypeString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1matrix44/title",
          "value": "MDLMaterialPropertyTypeMatrix44"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1matrix44/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeMatrix44"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1none/title",
          "value": "MDLMaterialPropertyTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1URL/title",
          "value": "MDLMaterialPropertyTypeURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1URL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1texture/title",
          "value": "MDLMaterialPropertyTypeTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyType~1texture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialPropertyTypeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1matrix4x4/title",
          "value": "matrix4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1matrix4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureSampler/title",
          "value": "MDLTextureSampler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureSampler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureSampler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureSampler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLTextureSampler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlmaterialpropertytype/matrix44"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlmaterialpropertytype/matrix44"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
