{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"destructiveButtonIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Button indices start at "},{"type":"codeVoice","code":"0"},{"type":"text","text":". The default value of this property is normally "},{"type":"codeVoice","code":"-1"},{"type":"text","text":", which indicates that no destructive button has been set. However, a destructive button may be created and set automatically by the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/init(title:delegate:cancelButtonTitle:destructiveButtonTitle:)","isActive":true},{"type":"text","text":" method. If you use that method to create a destructive button, you should not change the value of this property."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destructiveButtonIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"symbolKind":"property","title":"destructiveButtonIndex","externalID":"c:objc(cs)UIActionSheet(py)destructiveButtonIndex","modules":[{"name":"UIKit"}],"roleHeading":"Instance Property","platforms":[{"beta":false,"name":"iOS","introducedAt":"2.0","unavailable":false,"deprecated":false,"message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead","deprecatedAt":"8.3"},{"beta":false,"name":"iPadOS","introducedAt":"2.0","unavailable":false,"deprecated":false,"message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead","deprecatedAt":"8.3"},{"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"deprecated":false,"message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead","deprecatedAt":"13.1"}],"navigatorTitle":[{"text":"destructiveButtonIndex","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"The index number of the destructive button.","type":"text"}],"seeAlsoSections":[{"generated":true,"title":"Configuring buttons","anchor":"Configuring-buttons","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIActionSheet/addButton(withTitle:)","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/numberOfButtons","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/buttonTitle(at:)","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/cancelButtonIndex","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/firstOtherButtonIndex"]}],"variants":[{"paths":["/documentation/uikit/uiactionsheet/destructivebuttonindex"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiactionsheet/destructivebuttonindex"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIActionSheet"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/destructiveButtonIndex","interfaceLanguage":"swift"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/destructiveButtonIndex":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"destructiveButtonIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[{"type":"text","text":"The index number of the destructive button."}],"navigatorTitle":[{"kind":"identifier","text":"destructiveButtonIndex"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/destructiveButtonIndex","title":"destructiveButtonIndex","kind":"symbol","deprecated":true,"url":"/documentation/uikit/uiactionsheet/destructivebuttonindex","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/cancelButtonIndex":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButtonIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[{"type":"text","text":"The index number of the cancel button."}],"navigatorTitle":[{"kind":"identifier","text":"cancelButtonIndex"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/cancelButtonIndex","title":"cancelButtonIndex","kind":"symbol","deprecated":true,"url":"/documentation/uikit/uiactionsheet/cancelbuttonindex","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/firstOtherButtonIndex":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstOtherButtonIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/firstOtherButtonIndex","type":"topic","abstract":[{"text":"The index of the first custom button.","type":"text"}],"url":"/documentation/uikit/uiactionsheet/firstotherbuttonindex","deprecated":true,"role":"symbol","title":"firstOtherButtonIndex","navigatorTitle":[{"text":"firstOtherButtonIndex","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/buttonTitle(at:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonTitle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/buttonTitle(at:)","type":"topic","abstract":[{"text":"Returns the title of the button at the specified index.","type":"text"}],"url":"/documentation/uikit/uiactionsheet/buttontitle(at:)","deprecated":true,"role":"symbol","title":"buttonTitle(at:)","navigatorTitle":[{"kind":"identifier","text":"buttonTitleAtIndex:"}]},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/init(title:delegate:cancelButtonTitle:destructiveButtonTitle:)":{"url":"/documentation/uikit/uiactionsheet/init(title:delegate:cancelbuttontitle:destructivebuttontitle:)","deprecated":true,"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/init(title:delegate:cancelButtonTitle:destructiveButtonTitle:)","role":"symbol","title":"init(title:delegate:cancelButtonTitle:destructiveButtonTitle:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIActionSheetDelegate","text":"UIActionSheetDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"cancelButtonTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"destructiveButtonTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Initializes the action sheet using the specified starting parameters.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithTitle:delegate:cancelButtonTitle:destructiveButtonTitle:otherButtonTitles:"}]},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/addButton(withTitle:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/addButton(withTitle:)","type":"topic","abstract":[{"text":"Adds a custom button to the action sheet.","type":"text"}],"url":"/documentation/uikit/uiactionsheet/addbutton(withtitle:)","deprecated":true,"role":"symbol","title":"addButton(withTitle:)","navigatorTitle":[{"text":"addButtonWithTitle:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIActionSheet","kind":"identifier"}],"deprecated":true,"type":"topic","title":"UIActionSheet","url":"/documentation/uikit/uiactionsheet","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet","navigatorTitle":[{"text":"UIActionSheet","kind":"identifier"}],"abstract":[{"type":"text","text":"A view that presents a set of alternatives for how to proceed with a task."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/numberOfButtons":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfButtons","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/numberOfButtons","type":"topic","abstract":[{"text":"The number of buttons on the action sheet.","type":"text"}],"url":"/documentation/uikit/uiactionsheet/numberofbuttons","deprecated":true,"role":"symbol","title":"numberOfButtons","navigatorTitle":[{"kind":"identifier","text":"numberOfButtons"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","introducedAt":"2.0","unavailable":false,"deprecated":false,"deprecatedAt":"8.3"},{"beta":false,"name":"iPadOS","introducedAt":"2.0","unavailable":false,"deprecated":false,"deprecatedAt":"8.3"},{"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"deprecated":false,"deprecatedAt":"13.1"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"destructiveButtonIndex"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"destructiveButtonIndex","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIActionSheet"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIActionSheet/addButton(withTitle:)","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/numberOfButtons","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/buttonTitle(at:)","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/cancelButtonIndex","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/firstOtherButtonIndex"],"title":"Configuring buttons","anchor":"Configuring-buttons","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"destructiveButtonIndex","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"add","path":"/deprecationSummary","value":[]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1destructiveButtonIndex/title","value":"destructiveButtonIndex"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1destructiveButtonIndex/fragments","value":[{"kind":"identifier","text":"destructiveButtonIndex"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1cancelButtonIndex/title","value":"cancelButtonIndex"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1cancelButtonIndex/fragments","value":[{"kind":"identifier","text":"cancelButtonIndex"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1firstOtherButtonIndex/title","value":"firstOtherButtonIndex"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1firstOtherButtonIndex/fragments","value":[{"kind":"identifier","text":"firstOtherButtonIndex"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1buttonTitle(at:)/title","value":"buttonTitleAtIndex:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1buttonTitle(at:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"buttonTitleAtIndex:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1init(title:delegate:cancelButtonTitle:destructiveButtonTitle:)/title","value":"initWithTitle:delegate:cancelButtonTitle:destructiveButtonTitle:otherButtonTitles:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1init(title:delegate:cancelButtonTitle:destructiveButtonTitle:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTitle:delegate:cancelButtonTitle:destructiveButtonTitle:otherButtonTitles:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1addButton(withTitle:)/title","value":"addButtonWithTitle:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1addButton(withTitle:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addButtonWithTitle:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/title","value":"UIActionSheet"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/fragments","value":[{"kind":"identifier","text":"UIActionSheet"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/navigatorTitle","value":[{"text":"UIActionSheet","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1numberOfButtons/title","value":"numberOfButtons"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1numberOfButtons/fragments","value":[{"kind":"identifier","text":"numberOfButtons"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}