{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withClickedButtonIndex","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"buttonIndex","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"buttonIndex","content":[{"type":"paragraph","inlineContent":[{"text":"The index of the button that was clicked. Button indices start at ","type":"text"},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}]}]},{"name":"animated","content":[{"inlineContent":[{"text":"Specify ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"text":" to animate the dismissal of the action sheet or ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"text":" to remove the action sheet without an animation.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"You can use this method to dismiss the action sheet programmatically as needed. The action sheet also calls this method itself in response to the user tapping one of the buttons in the action sheet.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In iOS 4.0, you may want to call this method whenever your application moves to the background. An action sheet is not dismissed automatically when an application moves to the background. This behavior differs from previous versions of the operating system, where they were canceled automatically when the application was terminated. Dismissing the action sheet gives your application a chance to save changes or abort the operation and perform any necessary cleanup in case your application is terminated later."}]}]}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"dismiss(withClickedButtonIndex:animated:)","platforms":[{"deprecatedAt":"8.3","beta":false,"name":"iOS","introducedAt":"2.0","unavailable":false,"message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead","deprecated":false},{"deprecatedAt":"8.3","beta":false,"name":"iPadOS","introducedAt":"2.0","unavailable":false,"message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead","deprecated":false},{"deprecatedAt":"13.1","beta":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead","deprecated":false}],"navigatorTitle":[{"text":"dismissWithClickedButtonIndex:animated:","kind":"identifier"}],"role":"symbol","modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UIActionSheet(im)dismissWithClickedButtonIndex:animated:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withClickedButtonIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"abstract":[{"type":"text","text":"Dismisses the action sheet immediately using an optional animation."}],"variants":[{"paths":["/documentation/uikit/uiactionsheet/dismiss(withclickedbuttonindex:animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiactionsheet/dismiss(withclickedbuttonindex:animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIActionSheet"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/dismiss(withClickedButtonIndex:animated:)"},"references":{"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/dismiss(withClickedButtonIndex:animated:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withClickedButtonIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dismissWithClickedButtonIndex:animated:"}],"abstract":[{"type":"text","text":"Dismisses the action sheet immediately using an optional animation."}],"deprecated":true,"type":"topic","title":"dismiss(withClickedButtonIndex:animated:)","url":"/documentation/uikit/uiactionsheet/dismiss(withclickedbuttonindex:animated:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/dismiss(withClickedButtonIndex:animated:)"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIActionSheet","kind":"identifier"}],"deprecated":true,"type":"topic","title":"UIActionSheet","url":"/documentation/uikit/uiactionsheet","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet","navigatorTitle":[{"text":"UIActionSheet","kind":"identifier"}],"abstract":[{"type":"text","text":"A view that presents a set of alternatives for how to proceed with a task."}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"iOS","deprecatedAt":"8.3"},{"beta":false,"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"iPadOS","deprecatedAt":"8.3"},{"beta":false,"introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst","deprecatedAt":"13.1"}],"path":"/metadata/platforms","op":"replace"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"dismissWithClickedButtonIndex:animated:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dismissWithClickedButtonIndex:animated:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIActionSheet"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"dismissWithClickedButtonIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"buttonIndex","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"animated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"buttonIndex","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index of the button that was clicked. Button indices start at "},{"code":"0","type":"codeVoice"},{"type":"text","text":"."}]}]},{"name":"animated","content":[{"inlineContent":[{"type":"text","text":"Specify "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"type":"text","text":" to animate the dismissal of the action sheet or "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true},{"type":"text","text":" to remove the action sheet without an animation."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"value":[],"path":"/deprecationSummary","op":"add"},{"value":"dismissWithClickedButtonIndex:animated:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1dismiss(withClickedButtonIndex:animated:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"dismissWithClickedButtonIndex:animated:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1dismiss(withClickedButtonIndex:animated:)/fragments","op":"replace"},{"value":"UIActionSheet","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIActionSheet"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/fragments","op":"replace"},{"value":[{"text":"UIActionSheet","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}