{"metadata":{"modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"title","platforms":[{"deprecatedAt":"8.3","beta":false,"introducedAt":"2.0","deprecated":false,"message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead","name":"iOS","unavailable":false},{"deprecatedAt":"8.3","beta":false,"introducedAt":"2.0","deprecated":false,"message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead","name":"iPadOS","unavailable":false},{"deprecatedAt":"13.1","beta":false,"introducedAt":"13.1","deprecated":false,"message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead","name":"Mac Catalyst","unavailable":false}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"title"}],"role":"symbol","externalID":"c:objc(cs)UIActionSheet(py)title","symbolKind":"property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIActionSheet"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"abstract":[{"type":"text","text":"The string that appears in the receiver’s title bar."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/title"},"seeAlsoSections":[{"anchor":"Setting-properties","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIActionSheet/delegate","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/isVisible","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/actionSheetStyle"],"title":"Setting properties","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/uiactionsheet/title"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiactionsheet/title"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIActionSheet","kind":"identifier"}],"deprecated":true,"type":"topic","title":"UIActionSheet","url":"/documentation/uikit/uiactionsheet","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet","navigatorTitle":[{"text":"UIActionSheet","kind":"identifier"}],"abstract":[{"type":"text","text":"A view that presents a set of alternatives for how to proceed with a task."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/isVisible":{"kind":"symbol","url":"/documentation/uikit/uiactionsheet/isvisible","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isVisible","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/isVisible","role":"symbol","navigatorTitle":[{"text":"visible","kind":"identifier"}],"abstract":[{"text":"A Boolean value that indicates whether the receiver is displayed.","type":"text"}],"deprecated":true,"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/actionSheetStyle":{"kind":"symbol","url":"/documentation/uikit/uiactionsheet/actionsheetstyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionSheetStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIActionSheetStyle","preciseIdentifier":"c:@E@UIActionSheetStyle","kind":"typeIdentifier"}],"title":"actionSheetStyle","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/actionSheetStyle","role":"symbol","navigatorTitle":[{"text":"actionSheetStyle","kind":"identifier"}],"abstract":[{"text":"The receiver’s presentation style.","type":"text"}],"deprecated":true,"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/title":{"kind":"symbol","url":"/documentation/uikit/uiactionsheet/title","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"title","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/title","role":"symbol","navigatorTitle":[{"text":"title","kind":"identifier"}],"abstract":[{"text":"The string that appears in the receiver’s title bar.","type":"text"}],"deprecated":true,"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","url":"/documentation/Swift/String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"String"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"text":"NSString","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/delegate":{"role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheet/delegate","deprecated":true,"url":"/documentation/uikit/uiactionsheet/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UIActionSheetDelegate","preciseIdentifier":"c:objc(pl)UIActionSheetDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","abstract":[{"text":"The receiver’s delegate or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if it doesn’t have a delegate.","type":"text"}],"kind":"symbol","title":"delegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecatedAt":"8.3","beta":false,"introducedAt":"2.0","deprecated":false,"name":"iOS","unavailable":false},{"deprecatedAt":"8.3","beta":false,"introducedAt":"2.0","deprecated":false,"name":"iPadOS","unavailable":false},{"deprecatedAt":"13.1","beta":false,"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"title","op":"replace","path":"/metadata/title"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"title","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIActionSheet"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Setting properties","anchor":"Setting-properties","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIActionSheet/delegate","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/isVisible","doc://com.apple.uikit/documentation/UIKit/UIActionSheet/actionSheetStyle"],"generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"title","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":[],"path":"/deprecationSummary","op":"add"},{"value":"UIActionSheet","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/title","op":"replace"},{"value":[{"text":"UIActionSheet","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/fragments","op":"replace"},{"value":[{"text":"UIActionSheet","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/navigatorTitle","op":"replace"},{"value":"visible","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1isVisible/title","op":"replace"},{"value":[{"text":"visible","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1isVisible/fragments","op":"replace"},{"value":"actionSheetStyle","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1actionSheetStyle/title","op":"replace"},{"value":[{"kind":"identifier","text":"actionSheetStyle"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1actionSheetStyle/fragments","op":"replace"},{"value":"title","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1title/title","op":"replace"},{"value":[{"kind":"identifier","text":"title"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1title/fragments","op":"replace"},{"value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace"},{"value":"delegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1delegate/title","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet~1delegate/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}