{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent/init(instrumentID:groupID:duration:extendedParams:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So19ExtendedNoteOnEventV12instrumentID05groupF08duration14extendedParamsABs6UInt32V_AHSfSo011MusicDevicebJ0Vtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "instrumentID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MusicDeviceInstrumentID",
        "text": "MusicDeviceInstrumentID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "groupID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MusicDeviceGroupID",
        "text": "MusicDeviceGroupID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "duration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s7Float32a",
        "text": "Float32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "extendedParams"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@MusicDeviceNoteParams",
        "text": "MusicDeviceNoteParams"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(instrumentID:groupID:duration:extendedParams:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "instrumentID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceInstrumentID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MusicDeviceInstrumentID",
              "text": "MusicDeviceInstrumentID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "groupID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceGroupID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MusicDeviceGroupID",
              "text": "MusicDeviceGroupID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "duration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s7Float32a",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s7Float32a",
              "text": "Float32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "extendedParams"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceNoteParams",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@MusicDeviceNoteParams",
              "text": "MusicDeviceNoteParams"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent": {
      "abstract": [
        {
          "text": "Describes a note-on event with extended parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtendedNoteOnEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtendedNoteOnEvent"
        }
      ],
      "role": "symbol",
      "title": "ExtendedNoteOnEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendednoteonevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent/init(instrumentID:groupID:duration:extendedParams:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "instrumentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicDeviceInstrumentID",
          "text": "MusicDeviceInstrumentID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "groupID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicDeviceGroupID",
          "text": "MusicDeviceGroupID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "extendedParams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MusicDeviceNoteParams",
          "text": "MusicDeviceNoteParams"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent/init(instrumentID:groupID:duration:extendedParams:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(instrumentID:groupID:duration:extendedParams:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendednoteonevent/init(instrumentid:groupid:duration:extendedparams:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceGroupID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicDeviceGroupID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceGroupID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicDeviceGroupID"
        }
      ],
      "role": "symbol",
      "title": "MusicDeviceGroupID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicegroupid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceInstrumentID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicDeviceInstrumentID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceInstrumentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicDeviceInstrumentID"
        }
      ],
      "role": "symbol",
      "title": "MusicDeviceInstrumentID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdeviceinstrumentid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceNoteParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicDeviceNoteParams"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceNoteParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicDeviceNoteParams"
        }
      ],
      "role": "symbol",
      "title": "MusicDeviceNoteParams",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicenoteparams"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s7Float32a": {
      "abstract": [
        {
          "text": "A 32-bit floating point type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7Float32a",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float32",
      "type": "topic",
      "url": "/documentation/Swift/Float32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceGroupID/title",
          "value": "MusicDeviceGroupID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceGroupID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceGroupID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceGroupID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceGroupID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceNoteParams/title",
          "value": "MusicDeviceNoteParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceNoteParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceNoteParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceNoteParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceNoteParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceInstrumentID/title",
          "value": "MusicDeviceInstrumentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceInstrumentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceInstrumentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceInstrumentID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceInstrumentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedNoteOnEvent/title",
          "value": "ExtendedNoteOnEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedNoteOnEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedNoteOnEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedNoteOnEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedNoteOnEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/extendednoteonevent/init(instrumentid:groupid:duration:extendedparams:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
