{
  "abstract": [
    {
      "text": "The number of items in the menu.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/numberOfItems"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPopUpButtonCell(py)numberOfItems",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "numberOfItems"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "numberOfItems"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "numberOfItems"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "numberOfItems"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItem": {
      "abstract": [
        {
          "text": "A command item in an app menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItem"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItem",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSPopUpButtonCell",
          "type": "codeVoice"
        },
        {
          "text": " class defines the visual appearance of pop-up buttons that display pop-up or pull-down menus. Pop-up menus present the user with a set of choices, much the way radio buttons do, but using much less space. Pull-down menus also provide a set of choices but present the information in a slightly different way, usually to provide a set of commands from which the user can choose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPopUpButtonCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPopUpButtonCell"
        }
      ],
      "role": "symbol",
      "title": "NSPopUpButtonCell",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/index(of:)": {
      "abstract": [
        {
          "text": "Returns the index of the specified menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenuItem",
          "text": "NSMenuItem"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/index(of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfItem:"
        }
      ],
      "role": "symbol",
      "title": "index(of:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/index(of:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withRepresentedObject:)": {
      "abstract": [
        {
          "text": "Returns the index of the menu item that holds the specified represented object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexOfItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRepresentedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withRepresentedObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfItemWithRepresentedObject:"
        }
      ],
      "role": "symbol",
      "title": "indexOfItem(withRepresentedObject:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/indexofitem(withrepresentedobject:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTag:)": {
      "abstract": [
        {
          "text": "Returns the index of the menu item with the specified tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexOfItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTag:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfItemWithTag:"
        }
      ],
      "role": "symbol",
      "title": "indexOfItem(withTag:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/indexofitem(withtag:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTarget:andAction:)": {
      "abstract": [
        {
          "text": "Returns the index of the menu item with the specified target and action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexOfItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "andAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTarget:andAction:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfItemWithTarget:andAction:"
        }
      ],
      "role": "symbol",
      "title": "indexOfItem(withTarget:andAction:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/indexofitem(withtarget:andaction:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTitle:)": {
      "abstract": [
        {
          "text": "Returns the index of the item with the specified title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexOfItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTitle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfItemWithTitle:"
        }
      ],
      "role": "symbol",
      "title": "indexOfItem(withTitle:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/indexofitem(withtitle:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/item(at:)": {
      "abstract": [
        {
          "text": "Returns the menu item at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "item"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenuItem",
          "text": "NSMenuItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/item(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "item(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/item(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/item(withTitle:)": {
      "abstract": [
        {
          "text": "Returns the menu item with the specified title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "item"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenuItem",
          "text": "NSMenuItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/item(withTitle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemWithTitle:"
        }
      ],
      "role": "symbol",
      "title": "item(withTitle:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/item(withtitle:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/itemArray": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItem",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects that represent the items in the menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemArray"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenuItem",
          "text": "NSMenuItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/itemArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemArray"
        }
      ],
      "role": "symbol",
      "title": "itemArray",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/itemarray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/lastItem": {
      "abstract": [
        {
          "text": "The last item in the menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenuItem",
          "text": "NSMenuItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/lastItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastItem"
        }
      ],
      "role": "symbol",
      "title": "lastItem",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/lastitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/numberOfItems": {
      "abstract": [
        {
          "text": "The number of items in the menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/numberOfItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfItems"
        }
      ],
      "role": "symbol",
      "title": "numberOfItems",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell/numberofitems"
    },
    "doc://com.apple.documentation/documentation/foundation/nsarray/1409982-count": {
      "abstract": [
        {
          "text": "The number of objects in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray/1409982-count",
      "kind": "symbol",
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/foundation/nsarray/1409982-count"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsarray/1409982-count"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Accessing-the-items",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/itemArray",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/index(of:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTitle:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTag:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withRepresentedObject:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTarget:andAction:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/item(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/item(withTitle:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/lastItem"
      ],
      "title": "Accessing the items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "numberOfItems"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/foundation/nsarray/1409982-count"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Accessing-the-items",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/itemArray",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/index(of:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTitle:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTag:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withRepresentedObject:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/indexOfItem(withTarget:andAction:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/item(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/item(withTitle:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell/lastItem"
              ],
              "title": "Accessing the items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "numberOfItems"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1item(at:)/title",
          "value": "itemAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1item(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "itemAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1item(withTitle:)/title",
          "value": "itemWithTitle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1item(withTitle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "itemWithTitle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1indexOfItem(withTitle:)/title",
          "value": "indexOfItemWithTitle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1indexOfItem(withTitle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfItemWithTitle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell/title",
          "value": "NSPopUpButtonCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopUpButtonCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopUpButtonCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1indexOfItem(withRepresentedObject:)/title",
          "value": "indexOfItemWithRepresentedObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1indexOfItem(withRepresentedObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfItemWithRepresentedObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1indexOfItem(withTag:)/title",
          "value": "indexOfItemWithTag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1indexOfItem(withTag:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfItemWithTag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1indexOfItem(withTarget:andAction:)/title",
          "value": "indexOfItemWithTarget:andAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1indexOfItem(withTarget:andAction:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfItemWithTarget:andAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1lastItem/title",
          "value": "lastItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1lastItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1itemArray/title",
          "value": "itemArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1itemArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1numberOfItems/title",
          "value": "numberOfItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1numberOfItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/title",
          "value": "NSMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1index(of:)/title",
          "value": "indexOfItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell~1index(of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfItem:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspopupbuttoncell/numberofitems"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspopupbuttoncell/numberofitems"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
