{
  "abstract": [
    {
      "text": "Buttons at top or left. This has been deprecated.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Scroller arrows are not used anymore.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsMinEnd"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSScrollArrowPosition@NSScrollerArrowsMinEnd",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "scrollerArrowsMinEnd"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSScrollerArrowsMinEnd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.0",
        "message": "Scroller arrows are not used anymore.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSScroller.ArrowPosition.scrollerArrowsMinEnd"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scrollerArrowsMinEnd"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller": {
      "abstract": [
        {
          "text": "An object that controls scrolling of a document view within a scroll view or other type of container view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScroller"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScroller"
        }
      ],
      "role": "symbol",
      "title": "NSScroller",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition": {
      "abstract": [
        {
          "text": "These constants specify where the scroller’s buttons appear and are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/arrowsPosition",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArrowPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArrowPosition"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.ArrowPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/arrowposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsDefaultSetting": {
      "abstract": [
        {
          "text": "Buttons are displayed according to the system-wide appearance preferences.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollerArrowsDefaultSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScroller",
          "text": "NSScroller"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSScrollArrowPosition",
          "text": "ArrowPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsDefaultSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerArrowsDefaultSetting"
        }
      ],
      "role": "symbol",
      "title": "scrollerArrowsDefaultSetting",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/arrowposition/scrollerarrowsdefaultsetting"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsMaxEnd": {
      "abstract": [
        {
          "text": "Buttons at bottom or right. This constant has been deprecated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollerArrowsMaxEnd"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsMaxEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerArrowsMaxEnd"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.ArrowPosition.scrollerArrowsMaxEnd",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/arrowposition/scrollerarrowsmaxend"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsMinEnd": {
      "abstract": [
        {
          "text": "Buttons at top or left. This has been deprecated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollerArrowsMinEnd"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsMinEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerArrowsMinEnd"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.ArrowPosition.scrollerArrowsMinEnd",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/arrowposition/scrollerarrowsminend"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsNone": {
      "abstract": [
        {
          "text": "No buttons.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollerArrowsNone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerArrowsNone"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.ArrowPosition.scrollerArrowsNone",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/arrowposition/scrollerarrowsnone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/arrowsPosition": {
      "abstract": [
        {
          "text": "The location of the scroll buttons within the scroller, as described in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrowsPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScroller",
          "text": "NSScroller"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSScrollArrowPosition",
          "text": "ArrowPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/arrowsPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrowsPosition"
        }
      ],
      "role": "symbol",
      "title": "arrowsPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/arrowsposition"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsMaxEnd",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsDefaultSetting",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsNone"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSScrollerArrowsMinEnd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerArrowsMinEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsMaxEnd",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsDefaultSetting",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition/scrollerArrowsNone"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSScrollerArrowsMinEnd"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Scroller arrows are not used anymore.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/title",
          "value": "NSScroller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition~1scrollerArrowsDefaultSetting/title",
          "value": "NSScrollerArrowsDefaultSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition~1scrollerArrowsDefaultSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerArrowsDefaultSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition/title",
          "value": "NSScrollArrowPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollArrowPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollArrowPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1arrowsPosition/title",
          "value": "arrowsPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1arrowsPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrowsPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition~1scrollerArrowsNone/title",
          "value": "NSScrollerArrowsNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition~1scrollerArrowsNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerArrowsNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition~1scrollerArrowsMinEnd/title",
          "value": "NSScrollerArrowsMinEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition~1scrollerArrowsMinEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerArrowsMinEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition~1scrollerArrowsMaxEnd/title",
          "value": "NSScrollerArrowsMaxEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition~1scrollerArrowsMaxEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerArrowsMaxEnd"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscroller/arrowposition/scrollerarrowsminend"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsscroller/arrowposition/scrollerarrowsminend"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
