{
  "abstract": [
    {
      "text": "Creates a new custom item with the specified configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/initWithConfiguration:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKToolPickerCustomItem(im)initWithConfiguration:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithConfiguration:"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithConfiguration:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithConfiguration:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithConfiguration:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKToolPickerCustomItemConfiguration",
              "text": "PKToolPickerCustomItemConfiguration"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "configuration"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem": {
      "abstract": [
        {
          "text": "An item that represents a custom tool in the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerCustomItem"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerCustomItem"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerCustomItem",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitem"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/initWithConfiguration:": {
      "abstract": [
        {
          "text": "Creates a new custom item with the specified configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithConfiguration:"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/initWithConfiguration:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "initWithConfiguration:",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitem/initwithconfiguration:"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration": {
      "abstract": [
        {
          "text": "A configuration that specifies the appearance and behavior of a custom tool item and its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKToolPickerCustomItemConfiguration"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKToolPickerCustomItemConfiguration",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem/title",
          "value": "PKToolPickerCustomItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerCustomItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerCustomItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pktoolpickercustomitem/initwithconfiguration:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
