{
  "abstract": [
    {
      "text": "The line height multiple.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineHeightMultiple"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTParagraphStyleSpecifier@kCTParagraphStyleSpecifierLineHeightMultiple",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lineHeightMultiple"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTParagraphStyleSpecifierLineHeightMultiple"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTParagraphStyleSpecifier.lineHeightMultiple"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lineHeightMultiple"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The natural line height of the receiver is multiplied by this factor (if positive) before being constrained by minimum and maximum line height. Type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgfloat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Default value: ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": ". Affects: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFramesetter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFramesetter": {
      "abstract": [
        {
          "text": "Generate text frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFramesetter"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFramesetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFramesetter"
        }
      ],
      "role": "symbol",
      "title": "CTFramesetter",
      "type": "topic",
      "url": "/documentation/coretext/ctframesetter"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier": {
      "abstract": [
        {
          "text": "Constants used to query and modify a paragraph style object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTParagraphStyleSpecifier"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTParagraphStyleSpecifier"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/alignment": {
      "abstract": [
        {
          "text": "The text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/alignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierAlignment"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.alignment",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/alignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/baseWritingDirection": {
      "abstract": [
        {
          "text": "The base writing direction of the lines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/baseWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierBaseWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.baseWritingDirection",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/basewritingdirection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/defaultTabInterval": {
      "abstract": [
        {
          "text": "The document-wide default tab interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultTabInterval"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/defaultTabInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierDefaultTabInterval"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.defaultTabInterval",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/defaulttabinterval"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/firstLineHeadIndent": {
      "abstract": [
        {
          "text": "The distance, in points, from the leading margin of a frame to the beginning of the paragraph’s first line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstLineHeadIndent"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/firstLineHeadIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierFirstLineHeadIndent"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.firstLineHeadIndent",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/firstlineheadindent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/headIndent": {
      "abstract": [
        {
          "text": "The distance, in points, from the leading margin of a text container to the beginning of lines other than the first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headIndent"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/headIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierHeadIndent"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.headIndent",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/headindent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBreakMode": {
      "abstract": [
        {
          "text": "The mode that should be used to break lines when laying out the paragraph’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierLineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.lineBreakMode",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/linebreakmode"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineHeightMultiple": {
      "abstract": [
        {
          "text": "The line height multiple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineHeightMultiple"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineHeightMultiple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierLineHeightMultiple"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.lineHeightMultiple",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/lineheightmultiple"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacing": {
      "abstract": [
        {
          "text": "The space in points added between lines within the paragraph (commonly known as leading).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineSpacing"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierLineSpacing"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.lineSpacing",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/linespacing"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineHeight": {
      "abstract": [
        {
          "text": "The maximum height that any line in the frame will occupy, regardless of the font size or size of any attached graphic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumLineHeight"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierMaximumLineHeight"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.maximumLineHeight",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/maximumlineheight"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineSpacing": {
      "abstract": [
        {
          "text": "The maximum space in points between lines within the paragraph (commonly known as leading).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumLineSpacing"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierMaximumLineSpacing"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.maximumLineSpacing",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/maximumlinespacing"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineHeight": {
      "abstract": [
        {
          "text": "The minimum height that any line in the frame will occupy, regardless of the font size or size of any attached graphic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumLineHeight"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierMinimumLineHeight"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.minimumLineHeight",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/minimumlineheight"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineSpacing": {
      "abstract": [
        {
          "text": "The minimum space in points between lines within the paragraph (commonly known as leading).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumLineSpacing"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierMinimumLineSpacing"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.minimumLineSpacing",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/minimumlinespacing"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacing": {
      "abstract": [
        {
          "text": "The space added at the end of the paragraph to separate it from the following paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphSpacing"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierParagraphSpacing"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.paragraphSpacing",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/paragraphspacing"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacingBefore": {
      "abstract": [
        {
          "text": "The distance between the paragraph’s top and the beginning of its text content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphSpacingBefore"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacingBefore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierParagraphSpacingBefore"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.paragraphSpacingBefore",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/paragraphspacingbefore"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tabStops": {
      "abstract": [
        {
          "text": "The text tab objects, sorted by location, that define the tab stops for the paragraph style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabStops"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tabStops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierTabStops"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.tabStops",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/tabstops"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tailIndent": {
      "abstract": [
        {
          "text": "The distance, in points, from the margin of a frame to the end of lines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tailIndent"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tailIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierTailIndent"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.tailIndent",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/tailindent"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cgfloat": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgfloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/alignment",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/firstLineHeadIndent",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/headIndent",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tailIndent",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tabStops",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/defaultTabInterval",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBreakMode",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineHeight",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineHeight",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacing",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacing",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacingBefore",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/baseWritingDirection",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineSpacing",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineSpacing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTParagraphStyleSpecifierLineHeightMultiple"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierLineHeightMultiple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/alignment",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/firstLineHeadIndent",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/headIndent",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tailIndent",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tabStops",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/defaultTabInterval",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBreakMode",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineHeight",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineHeight",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacing",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacing",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacingBefore",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/baseWritingDirection",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineSpacing",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineSpacing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTParagraphStyleSpecifierLineHeightMultiple"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineSpacing/title",
          "value": "kCTParagraphStyleSpecifierLineSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierLineSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1minimumLineHeight/title",
          "value": "kCTParagraphStyleSpecifierMinimumLineHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1minimumLineHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierMinimumLineHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1paragraphSpacing/title",
          "value": "kCTParagraphStyleSpecifierParagraphSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1paragraphSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierParagraphSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1tailIndent/title",
          "value": "kCTParagraphStyleSpecifierTailIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1tailIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierTailIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFramesetter/title",
          "value": "CTFramesetterRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFramesetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFramesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFramesetter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFramesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1defaultTabInterval/title",
          "value": "kCTParagraphStyleSpecifierDefaultTabInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1defaultTabInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierDefaultTabInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineBreakMode/title",
          "value": "kCTParagraphStyleSpecifierLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1headIndent/title",
          "value": "kCTParagraphStyleSpecifierHeadIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1headIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierHeadIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1tabStops/title",
          "value": "kCTParagraphStyleSpecifierTabStops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1tabStops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierTabStops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1maximumLineHeight/title",
          "value": "kCTParagraphStyleSpecifierMaximumLineHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1maximumLineHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierMaximumLineHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1minimumLineSpacing/title",
          "value": "kCTParagraphStyleSpecifierMinimumLineSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1minimumLineSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierMinimumLineSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1firstLineHeadIndent/title",
          "value": "kCTParagraphStyleSpecifierFirstLineHeadIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1firstLineHeadIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierFirstLineHeadIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1alignment/title",
          "value": "kCTParagraphStyleSpecifierAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1alignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineHeightMultiple/title",
          "value": "kCTParagraphStyleSpecifierLineHeightMultiple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineHeightMultiple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierLineHeightMultiple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1maximumLineSpacing/title",
          "value": "kCTParagraphStyleSpecifierMaximumLineSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1maximumLineSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierMaximumLineSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier/title",
          "value": "CTParagraphStyleSpecifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleSpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleSpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1baseWritingDirection/title",
          "value": "kCTParagraphStyleSpecifierBaseWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1baseWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierBaseWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1paragraphSpacingBefore/title",
          "value": "kCTParagraphStyleSpecifierParagraphSpacingBefore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1paragraphSpacingBefore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierParagraphSpacingBefore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctparagraphstylespecifier/lineheightmultiple"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctparagraphstylespecifier/lineheightmultiple"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
