{
  "abstract": [
    {
      "text": "The panel that shows the Restart, Shut Down, and Log Out options that are displayed as a result of pushing the power key is disabled.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableSessionTermination"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSApplicationPresentationOptions@NSApplicationPresentationDisableSessionTermination",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "disableSessionTermination"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSApplication",
        "text": "NSApplication"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
        "text": "PresentationOptions"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSApplicationPresentationDisableSessionTermination"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "disableSessionTermination"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "disableSessionTermination"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSApplication",
              "text": "NSApplication"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
              "text": "PresentationOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct": {
      "abstract": [
        {
          "text": "Constants that control the presentation of the app, typically for fullscreen apps such as games or kiosks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PresentationOptions"
        }
      ],
      "role": "symbol",
      "title": "NSApplication.PresentationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock": {
      "abstract": [
        {
          "text": "The dock is normally hidden, but automatically appears when moused near.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoHideDock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationAutoHideDock"
        }
      ],
      "role": "symbol",
      "title": "autoHideDock",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/autohidedock"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar": {
      "abstract": [
        {
          "text": "The menu bar is normally hidden, but automatically appears when moused near.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoHideMenuBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationAutoHideMenuBar"
        }
      ],
      "role": "symbol",
      "title": "autoHideMenuBar",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/autohidemenubar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideToolbar": {
      "abstract": [
        {
          "text": "When in fullscreen mode the window toolbar is detached from window and hides and shows with autoHidden menuBar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoHideToolbar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideToolbar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationAutoHideToolbar"
        }
      ],
      "role": "symbol",
      "title": "autoHideToolbar",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/autohidetoolbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableAppleMenu": {
      "abstract": [
        {
          "text": "All Apple Menu items are disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableAppleMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableAppleMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableAppleMenu"
        }
      ],
      "role": "symbol",
      "title": "disableAppleMenu",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disableapplemenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableCursorLocationAssistance": {
      "abstract": [
        {
          "text": "The behavior that allows the user to shake the mouse to locate the cursor is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableCursorLocationAssistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableCursorLocationAssistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableCursorLocationAssistance"
        }
      ],
      "role": "symbol",
      "title": "disableCursorLocationAssistance",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablecursorlocationassistance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableForceQuit": {
      "abstract": [
        {
          "text": "The force quit panel (displayed by pressing Command + Option + Esc) is disabled",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableForceQuit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableForceQuit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableForceQuit"
        }
      ],
      "role": "symbol",
      "title": "disableForceQuit",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disableforcequit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableHideApplication": {
      "abstract": [
        {
          "text": "The app’s “Hide” menu item is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableHideApplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableHideApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableHideApplication"
        }
      ],
      "role": "symbol",
      "title": "disableHideApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablehideapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableMenuBarTransparency": {
      "abstract": [
        {
          "text": "The menu bar transparency appearance is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableMenuBarTransparency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableMenuBarTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableMenuBarTransparency"
        }
      ],
      "role": "symbol",
      "title": "disableMenuBarTransparency",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablemenubartransparency"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableProcessSwitching": {
      "abstract": [
        {
          "text": "The process switching user interface (Command + Tab to cycle through apps) is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableProcessSwitching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableProcessSwitching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableProcessSwitching"
        }
      ],
      "role": "symbol",
      "title": "disableProcessSwitching",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disableprocessswitching"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableSessionTermination": {
      "abstract": [
        {
          "text": "The panel that shows the Restart, Shut Down, and Log Out options that are displayed as a result of pushing the power key is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableSessionTermination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableSessionTermination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableSessionTermination"
        }
      ],
      "role": "symbol",
      "title": "disableSessionTermination",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablesessiontermination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/fullScreen": {
      "abstract": [
        {
          "text": "The app is in fullscreen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/fullScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationFullScreen"
        }
      ],
      "role": "symbol",
      "title": "fullScreen",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/fullscreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock": {
      "abstract": [
        {
          "text": "The dock is entirely hidden and disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hideDock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationHideDock"
        }
      ],
      "role": "symbol",
      "title": "hideDock",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/hidedock"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar": {
      "abstract": [
        {
          "text": "The menu bar is entirely hidden and disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hideMenuBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationHideMenuBar"
        }
      ],
      "role": "symbol",
      "title": "hideMenuBar",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/hidemenubar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationPresentationOptions/NSApplicationPresentationDefault": {
      "abstract": [
        {
          "text": "This is the default presentation mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDefault"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationPresentationOptions/NSApplicationPresentationDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationPresentationDefault",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationpresentationoptions/nsapplicationpresentationdefault"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presentation-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableAppleMenu",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableProcessSwitching",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableForceQuit",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableHideApplication",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableMenuBarTransparency",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/fullScreen",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideToolbar",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableCursorLocationAssistance"
      ],
      "title": "Presentation Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSApplicationPresentationDisableSessionTermination"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableSessionTermination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presentation-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplicationPresentationOptions/NSApplicationPresentationDefault",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableAppleMenu",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableProcessSwitching",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableForceQuit",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableHideApplication",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableMenuBarTransparency",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/fullScreen",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideToolbar",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableCursorLocationAssistance"
              ],
              "title": "Presentation Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSApplicationPresentationDisableSessionTermination"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableSessionTermination/title",
          "value": "NSApplicationPresentationDisableSessionTermination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableSessionTermination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableSessionTermination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableHideApplication/title",
          "value": "NSApplicationPresentationDisableHideApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableHideApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableHideApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1hideMenuBar/title",
          "value": "NSApplicationPresentationHideMenuBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1hideMenuBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationHideMenuBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1fullScreen/title",
          "value": "NSApplicationPresentationFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1fullScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationFullScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableCursorLocationAssistance/title",
          "value": "NSApplicationPresentationDisableCursorLocationAssistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableCursorLocationAssistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableCursorLocationAssistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideToolbar/title",
          "value": "NSApplicationPresentationAutoHideToolbar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideToolbar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationAutoHideToolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableForceQuit/title",
          "value": "NSApplicationPresentationDisableForceQuit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableForceQuit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableForceQuit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableProcessSwitching/title",
          "value": "NSApplicationPresentationDisableProcessSwitching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableProcessSwitching/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableProcessSwitching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title",
          "value": "NSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableAppleMenu/title",
          "value": "NSApplicationPresentationDisableAppleMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableAppleMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableAppleMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct/title",
          "value": "NSApplicationPresentationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideDock/title",
          "value": "NSApplicationPresentationAutoHideDock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideDock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationAutoHideDock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1hideDock/title",
          "value": "NSApplicationPresentationHideDock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1hideDock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationHideDock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableMenuBarTransparency/title",
          "value": "NSApplicationPresentationDisableMenuBarTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableMenuBarTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableMenuBarTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideMenuBar/title",
          "value": "NSApplicationPresentationAutoHideMenuBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideMenuBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationAutoHideMenuBar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablesessiontermination"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablesessiontermination"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
