{
  "abstract": [
    {
      "text": "A list of dictionaries that report the categories of private data your app or third-party SDK collects.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:App_Privacy_Configuration.NSPrivacyCollectedDataTypes",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrivacyCollectedDataTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSPrivacyCollectedDataTypes"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Privacy Nutrition Label Types",
        "name": "NSPrivacyCollectedDataTypes",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "dictionary "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests"
      ]
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration": {
      "abstract": [
        {
          "text": "A data structure that represents the root object in a privacy manifest file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
      "kind": "symbol",
      "name": "App Privacy Configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "App Privacy Configuration"
        }
      ],
      "role": "symbol",
      "title": "App Privacy Configuration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes": {
      "abstract": [
        {
          "text": "A list of dictionaries that report the categories of private data your app or third-party SDK collects.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Nutrition Label Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypes"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType": {
      "abstract": [
        {
          "text": "A string that identifies the type of data your app or third-party SDK collects.",
          "type": "text"
        }
      ],
      "ideTitle": "Collected Data Type",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataType"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeLinked": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether your app or third-party SDK links this data type to the user’s identity.",
          "type": "text"
        }
      ],
      "ideTitle": "Linked to User",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeLinked",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypeLinked",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypeLinked"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypeLinked",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatypelinked"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes": {
      "abstract": [
        {
          "text": "An array of strings that identify reasons your app or third-party SDK collects private data.",
          "type": "text"
        }
      ],
      "ideTitle": "Collection Purposes",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypePurposes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypePurposes"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypePurposes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatypepurposes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeTracking": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether your app or third-party SDK uses this data type to track.",
          "type": "text"
        }
      ],
      "ideTitle": "Used for Tracking",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeTracking",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypeTracking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypeTracking"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypeTracking",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatypetracking"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests": {
      "abstract": [
        {
          "text": "Declare the data collected by your app or by third-party SDKs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests",
      "kind": "article",
      "role": "article",
      "title": "Describing data use in privacy manifests",
      "type": "topic",
      "url": "/documentation/bundleresources/describing-data-use-in-privacy-manifests"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Reporting-categories-of-collected-data",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes"
      ],
      "title": "Reporting categories of collected data"
    },
    {
      "anchor": "Reporting-tracking-and-linking-collected-data",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeLinked",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeTracking"
      ],
      "title": "Reporting tracking and linking collected data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrivacyCollectedDataTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reporting-categories-of-collected-data",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes"
              ],
              "title": "Reporting categories of collected data"
            },
            {
              "anchor": "Reporting-tracking-and-linking-collected-data",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeLinked",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypeTracking"
              ],
              "title": "Reporting tracking and linking collected data"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes/title",
          "value": "NSPrivacyCollectedDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/title",
          "value": "App Privacy Configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "App Privacy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataType/title",
          "value": "NSPrivacyCollectedDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypeTracking/title",
          "value": "NSPrivacyCollectedDataTypeTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypeTracking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypeTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypePurposes/title",
          "value": "NSPrivacyCollectedDataTypePurposes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypePurposes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypePurposes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypeLinked/title",
          "value": "NSPrivacyCollectedDataTypeLinked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypeLinked/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypeLinked"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
