{
  "abstract": [
    {
      "text": "A list of the internet domains your app or third-party SDK uses for tracking.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTrackingDomains"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:App_Privacy_Configuration.NSPrivacyTrackingDomains",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrivacyTrackingDomains"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSPrivacyTrackingDomains"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Privacy Tracking Domains",
        "name": "NSPrivacyTrackingDomains",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the user has not granted tracking permission through the App Tracking Transparency framework, network requests to these domains fail and your app receives an error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration": {
      "abstract": [
        {
          "text": "A data structure that represents the root object in a privacy manifest file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
      "kind": "symbol",
      "name": "App Privacy Configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "App Privacy Configuration"
        }
      ],
      "role": "symbol",
      "title": "App Privacy Configuration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTracking": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app or third-party SDK uses data for tracking.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Tracking Enabled",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTracking",
      "kind": "symbol",
      "name": "NSPrivacyTracking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyTracking"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyTracking",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacytracking"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTrackingDomains": {
      "abstract": [
        {
          "text": "A list of the internet domains your app or third-party SDK uses for tracking.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Tracking Domains",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTrackingDomains",
      "kind": "symbol",
      "name": "NSPrivacyTrackingDomains",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyTrackingDomains"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyTrackingDomains",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacytrackingdomains"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Declaring-tracking",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTracking"
      ],
      "title": "Declaring tracking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrivacyTrackingDomains"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyTrackingDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Declaring-tracking",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyTracking"
              ],
              "title": "Declaring tracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyTracking/title",
          "value": "NSPrivacyTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyTracking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyTrackingDomains/title",
          "value": "NSPrivacyTrackingDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyTrackingDomains/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyTrackingDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/title",
          "value": "App Privacy Configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "App Privacy Configuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration/nsprivacytrackingdomains"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration/nsprivacytrackingdomains"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
