{
  "abstract": [
    {
      "text": "A set of properties that configure a spatial scaling effect, and a factory method that creates the effect.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalfx/documentation/MetalFX"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLFXSpatialScalerDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLFXSpatialScalerDescriptor"
      }
    ],
    "modules": [
      {
        "name": "MetalFX"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLFXSpatialScalerDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTLFXSpatialScalerDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalfx/documentation/MetalFX": {
      "abstract": [
        {
          "text": "Boost your Metal app’s performance by upscaling lower-resolution content to save GPU time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalFX",
      "type": "topic",
      "url": "/documentation/metalfx"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler": {
      "abstract": [
        {
          "text": "An upscaling effect that generates a higher resolution texture in a render pass by spatially analyzing an input texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScaler"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScaler"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScaler",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode": {
      "abstract": [
        {
          "text": "The color space modes for the input and output textures you use with a spatial scaling effect instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerColorProcessingMode"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerColorProcessingMode"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScalerColorProcessingMode",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalercolorprocessingmode"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor": {
      "abstract": [
        {
          "text": "A set of properties that configure a spatial scaling effect, and a factory method that creates the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScalerDescriptor",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/colorProcessingMode": {
      "abstract": [
        {
          "text": "The color space of the input color texture for the spatial scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorProcessingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFXSpatialScalerColorProcessingMode",
          "text": "MTLFXSpatialScalerColorProcessingMode"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/colorProcessingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorProcessingMode"
        }
      ],
      "role": "symbol",
      "title": "colorProcessingMode",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/colorprocessingmode"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/colorTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the input color texture for the spatial scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/colorTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorTextureFormat"
        }
      ],
      "role": "symbol",
      "title": "colorTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/colortextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/inputHeight": {
      "abstract": [
        {
          "text": "The height of the input color texture for the spatial scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/inputHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputHeight"
        }
      ],
      "role": "symbol",
      "title": "inputHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/inputheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/inputWidth": {
      "abstract": [
        {
          "text": "The width of the input color texture for the spatial scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/inputWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputWidth"
        }
      ],
      "role": "symbol",
      "title": "inputWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/inputwidth"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/makeSpatialScaler(device:)": {
      "abstract": [
        {
          "text": "Creates a spatial scaler instance from this descriptor’s current property values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeSpatialScaler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLFXSpatialScaler",
          "text": "MTLFXSpatialScaler"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/makeSpatialScaler(device:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newSpatialScalerWithDevice:"
        }
      ],
      "role": "symbol",
      "title": "makeSpatialScaler(device:)",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/makespatialscaler(device:)"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputHeight": {
      "abstract": [
        {
          "text": "The height of the output color texture for the spatial scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputHeight"
        }
      ],
      "role": "symbol",
      "title": "outputHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/outputheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the output color texture for the spatial scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTextureFormat"
        }
      ],
      "role": "symbol",
      "title": "outputTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/outputtextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputWidth": {
      "abstract": [
        {
          "text": "The width of the output color texture for the spatial scaler you create with this descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputWidth"
        }
      ],
      "role": "symbol",
      "title": "outputWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/outputwidth"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/supportsDevice(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the spatial scaler works with a GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsDevice"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/supportsDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsDevice:"
        }
      ],
      "role": "symbol",
      "title": "supportsDevice(_:)",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/supportsdevice(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Spatial-scaling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode"
      ],
      "title": "Spatial scaling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Checking-a-GPU-devices-scaling-support",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/supportsDevice(_:)"
      ],
      "title": "Checking a GPU device’s scaling support"
    },
    {
      "anchor": "Configuring-a-spatial-scalers-input",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/inputWidth",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/inputHeight",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/colorTextureFormat",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/colorProcessingMode"
      ],
      "title": "Configuring a spatial scaler’s input"
    },
    {
      "anchor": "Configuring-a-spatial-scalers-output",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputWidth",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputHeight",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputTextureFormat"
      ],
      "title": "Configuring a spatial scaler’s output"
    },
    {
      "anchor": "Creating-spatial-scaler-instances",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/makeSpatialScaler(device:)"
      ],
      "title": "Creating spatial scaler instances"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLFXSpatialScalerDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalfx/documentation/MetalFX"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Checking-a-GPU-devices-scaling-support",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/supportsDevice(_:)"
              ],
              "title": "Checking a GPU device’s scaling support"
            },
            {
              "anchor": "Configuring-a-spatial-scalers-input",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/inputWidth",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/inputHeight",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/colorTextureFormat",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/colorProcessingMode"
              ],
              "title": "Configuring a spatial scaler’s input"
            },
            {
              "anchor": "Configuring-a-spatial-scalers-output",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputWidth",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputHeight",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/outputTextureFormat"
              ],
              "title": "Configuring a spatial scaler’s output"
            },
            {
              "anchor": "Creating-spatial-scaler-instances",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/makeSpatialScaler(device:)"
              ],
              "title": "Creating spatial scaler instances"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Spatial-scaling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode"
              ],
              "title": "Spatial scaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLFXSpatialScalerDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor/title",
          "value": "MTLFXSpatialScalerDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1inputHeight/title",
          "value": "inputHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1inputHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1outputWidth/title",
          "value": "outputWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1outputWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1outputHeight/title",
          "value": "outputHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1outputHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1supportsDevice(_:)/title",
          "value": "supportsDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1supportsDevice(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "supportsDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1outputTextureFormat/title",
          "value": "outputTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1outputTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1inputWidth/title",
          "value": "inputWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1inputWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1colorTextureFormat/title",
          "value": "colorTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1colorTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1colorProcessingMode/title",
          "value": "colorProcessingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1colorProcessingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorProcessingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1makeSpatialScaler(device:)/title",
          "value": "newSpatialScalerWithDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1makeSpatialScaler(device:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newSpatialScalerWithDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler/title",
          "value": "MTLFXSpatialScaler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode/title",
          "value": "MTLFXSpatialScalerColorProcessingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalfx/mtlfxspatialscalerdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalfx/mtlfxspatialscalerdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
