{
  "abstract": [
    {
      "text": "An upscaling effect that generates a higher resolution texture in a render pass by analyzing multiple input textures over time.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalfx/documentation/MetalFX"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLFXTemporalScaler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLFXTemporalScaler"
      }
    ],
    "modules": [
      {
        "name": "MetalFX"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLFXTemporalScaler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MTLFXTemporalScaler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScaler"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The MetalFX temporal scaler increases the size of your input texture to a larger output texture. You can use the scaler to upscale every frame of your app’s scene or rendering in real time. With a scaler, you can draw more complicated scenes in less time by intentionally rendering to a lower resolution to save time before upscaling.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance by following these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create and configure an ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instance.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the descriptor’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/makeTemporalScaler(device:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Upscale a rendering by following these steps for every render pass:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the temporal scaler’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTexture",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to the input texture.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the scaler’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentWidth",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentHeight",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the scaler’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTexture",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to your destination texture.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Encode the upscale commands to an ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLCommandBuffer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " by calling the temporal scaler’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/encode(commandBuffer:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Metal/MTLCommandBuffer": {
      "abstract": [
        {
          "text": "A container that stores a sequence of GPU commands that you encode into it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBuffer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLCommandBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCommandBuffer",
      "type": "topic",
      "url": "/documentation/Metal/MTLCommandBuffer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalfx/documentation/MetalFX": {
      "abstract": [
        {
          "text": "Boost your Metal app’s performance by upscaling lower-resolution content to save GPU time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalFX",
      "type": "topic",
      "url": "/documentation/metalfx"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler": {
      "abstract": [
        {
          "text": "An upscaling effect that generates a higher resolution texture in a render pass by analyzing multiple input textures over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXTemporalScaler"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXTemporalScaler"
        }
      ],
      "role": "symbol",
      "title": "MTLFXTemporalScaler",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTexture": {
      "abstract": [
        {
          "text": "An input color texture you set for the temporal scaler that supports the correct color texture usage options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/colortexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the input color texture for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorTextureFormat"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/colortextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture usage options that your app’s input color texture must set to apply the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/colortextureusage"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTexture": {
      "abstract": [
        {
          "text": "An input depth texture you set for the temporal scaler that supports the correct depth texture usage options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depthTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "depthTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/depthtexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the input depth texture for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depthTextureFormat"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "depthTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/depthtextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture usage options that your app’s input depth texture must set to apply the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depthTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "depthTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/depthtextureusage"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/encode(commandBuffer:)": {
      "abstract": [
        {
          "text": "Adds the temporal scaling command to a render pass’s command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "commandBuffer"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCommandBuffer",
          "text": "MTLCommandBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/encode(commandBuffer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encodeToCommandBuffer:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "encode(commandBuffer:)",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/encode(commandbuffer:)"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/exposureTexture": {
      "abstract": [
        {
          "text": "A texture that sets the exposure level for the color texture input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exposureTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/exposureTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exposureTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "exposureTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/exposuretexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/fence": {
      "abstract": [
        {
          "text": "An optional fence instance that you provide to synchronize your app’s untracked resources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fence"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLFence",
          "text": "MTLFence"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/fence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fence"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "fence",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/fence"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the region within the color texture the temporal scaler uses as its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputContentHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputContentHeight"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputContentHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/inputcontentheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentMaxScale": {
      "abstract": [
        {
          "text": "The largest scale factor the temporal scaler uses to generate output textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputContentMaxScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentMaxScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputContentMaxScale"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputContentMaxScale",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/inputcontentmaxscale"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentMinScale": {
      "abstract": [
        {
          "text": "The smallest scale factor the temporal scaler uses to generate output textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputContentMinScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentMinScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputContentMinScale"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputContentMinScale",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/inputcontentminscale"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentWidth": {
      "abstract": [
        {
          "text": "The width, in pixels, of the region within the color texture the temporal scaler uses as its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputContentWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputContentWidth"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputContentWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/inputcontentwidth"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the input color texture for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputHeight"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/inputheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputWidth": {
      "abstract": [
        {
          "text": "The width, in pixels, of the input color texture for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputWidth"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/inputwidth"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/isDepthReversed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the depth texture uses zero to represent the farthest distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDepthReversed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/isDepthReversed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depthReversed"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isDepthReversed",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/isdepthreversed"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/jitterOffsetX": {
      "abstract": [
        {
          "text": "The horizontal component of the subpixel sampling coordinate you use to generate the color texture input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jitterOffsetX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/jitterOffsetX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jitterOffsetX"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "jitterOffsetX",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/jitteroffsetx"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/jitterOffsetY": {
      "abstract": [
        {
          "text": "The vertical component of the subpixel sampling coordinate you use to generate the color texture input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jitterOffsetY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/jitterOffsetY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jitterOffsetY"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "jitterOffsetY",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/jitteroffsety"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTexture": {
      "abstract": [
        {
          "text": "An input motion texture you set for the temporal scaler that supports the correct motion texture usage options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "motionTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/motiontexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the input motion texture for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTextureFormat"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "motionTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/motiontextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture usage options that your app’s input motion texture must set to apply the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "motionTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/motiontextureusage"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionVectorScaleX": {
      "abstract": [
        {
          "text": "The horizontal scale factor the temporal scaler applies to the input motion texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionVectorScaleX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionVectorScaleX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionVectorScaleX"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "motionVectorScaleX",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/motionvectorscalex"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionVectorScaleY": {
      "abstract": [
        {
          "text": "The vertical scale factor the temporal scaler applies to the input motion texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionVectorScaleY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionVectorScaleY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionVectorScaleY"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "motionVectorScaleY",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/motionvectorscaley"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the output color texture for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputHeight"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/outputheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTexture": {
      "abstract": [
        {
          "text": "An output texture that supports the correct depth texture usage options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/outputtexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the output color texture for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTextureFormat"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/outputtextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture usage options that your app’s output texture must set to apply the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/outputtextureusage"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputWidth": {
      "abstract": [
        {
          "text": "The width, in pixels, of the output color texture for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputWidth"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/outputwidth"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/preExposure": {
      "abstract": [
        {
          "text": "The exposure value that you’ve already applied to your color texture input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preExposure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/preExposure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preExposure"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "preExposure",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/preexposure"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveMaskTexture": {
      "abstract": [
        {
          "text": "A reactive-mask texture input you set for a temporal scaler that supports the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "correct usage options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactiveMaskTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveMaskTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reactiveMaskTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "reactiveMaskTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/reactivemasktexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture-usage options that your app’s reactive-mask texture",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "input needs to have for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactiveTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reactiveTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "reactiveTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/reactivetextureusage"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reset": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the temporal scaler discards historical data from previous frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reset"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "reset",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/reset"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor": {
      "abstract": [
        {
          "text": "A set of properties that configure a temporal scaling effect, and a factory method that creates the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXTemporalScalerDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXTemporalScalerDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLFXTemporalScalerDescriptor",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/makeTemporalScaler(device:)": {
      "abstract": [
        {
          "text": "Creates a temporal scaler instance from this descriptor’s current property values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeTemporalScaler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLFXTemporalScaler",
          "text": "MTLFXTemporalScaler"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor/makeTemporalScaler(device:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newTemporalScalerWithDevice:"
        }
      ],
      "role": "symbol",
      "title": "makeTemporalScaler(device:)",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscalerdescriptor/maketemporalscaler(device:)"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/applying-temporal-antialiasing-and-upscaling-using-metalfx": {
      "abstract": [
        {
          "text": "Reduce render workloads while increasing image detail with MetalFX.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/applying-temporal-antialiasing-and-upscaling-using-metalfx",
      "kind": "article",
      "role": "sampleCode",
      "title": "Applying temporal antialiasing and upscaling using MetalFX",
      "type": "topic",
      "url": "/documentation/metalfx/applying-temporal-antialiasing-and-upscaling-using-metalfx"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Temporal-scaling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/applying-temporal-antialiasing-and-upscaling-using-metalfx",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor"
      ],
      "title": "Temporal scaling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-image-input",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTextureUsage",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTexture",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentWidth",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentHeight",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/jitterOffsetX",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/jitterOffsetY",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/exposureTexture",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/preExposure"
      ],
      "title": "Configuring the image input"
    },
    {
      "anchor": "Configuring-the-depth-input",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTextureUsage",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTexture",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/isDepthReversed"
      ],
      "title": "Configuring the depth input"
    },
    {
      "anchor": "Configuring-the-motion-input",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTextureUsage",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTexture",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionVectorScaleX",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionVectorScaleY"
      ],
      "title": "Configuring the motion input"
    },
    {
      "anchor": "Configuring-the-reactive-mask-input",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveTextureUsage",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveMaskTexture"
      ],
      "title": "Configuring the reactive mask input"
    },
    {
      "anchor": "Configuring-the-image-output",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTextureUsage",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTexture"
      ],
      "title": "Configuring the image output"
    },
    {
      "anchor": "Synchronizing-untracked-resources",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/fence"
      ],
      "title": "Synchronizing untracked resources"
    },
    {
      "anchor": "Encoding-a-temporal-scaling-effect",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reset",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/encode(commandBuffer:)"
      ],
      "title": "Encoding a temporal scaling effect"
    },
    {
      "anchor": "Inspecting-the-fixed-settings",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputWidth",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputHeight",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentMinScale",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentMaxScale",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTextureFormat",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTextureFormat",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTextureFormat",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputWidth",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputHeight",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTextureFormat"
      ],
      "title": "Inspecting the fixed settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLFXTemporalScaler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalfx/documentation/MetalFX"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-image-input",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTextureUsage",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTexture",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentWidth",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentHeight",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/jitterOffsetX",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/jitterOffsetY",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/exposureTexture",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/preExposure"
              ],
              "title": "Configuring the image input"
            },
            {
              "anchor": "Configuring-the-depth-input",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTextureUsage",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTexture",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/isDepthReversed"
              ],
              "title": "Configuring the depth input"
            },
            {
              "anchor": "Configuring-the-motion-input",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTextureUsage",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTexture",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionVectorScaleX",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionVectorScaleY"
              ],
              "title": "Configuring the motion input"
            },
            {
              "anchor": "Configuring-the-reactive-mask-input",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveTextureUsage",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveMaskTexture"
              ],
              "title": "Configuring the reactive mask input"
            },
            {
              "anchor": "Configuring-the-image-output",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTextureUsage",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTexture"
              ],
              "title": "Configuring the image output"
            },
            {
              "anchor": "Synchronizing-untracked-resources",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/fence"
              ],
              "title": "Synchronizing untracked resources"
            },
            {
              "anchor": "Encoding-a-temporal-scaling-effect",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reset",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/encode(commandBuffer:)"
              ],
              "title": "Encoding a temporal scaling effect"
            },
            {
              "anchor": "Inspecting-the-fixed-settings",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputWidth",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputHeight",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentMinScale",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/inputContentMaxScale",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/colorTextureFormat",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/depthTextureFormat",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/motionTextureFormat",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputWidth",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputHeight",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/outputTextureFormat"
              ],
              "title": "Inspecting the fixed settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Temporal-scaling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/applying-temporal-antialiasing-and-upscaling-using-metalfx",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScalerDescriptor"
              ],
              "title": "Temporal scaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLFXTemporalScaler"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1jitterOffsetX/title",
          "value": "jitterOffsetX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1jitterOffsetX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jitterOffsetX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1isDepthReversed/title",
          "value": "depthReversed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1isDepthReversed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depthReversed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputWidth/title",
          "value": "outputWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputWidth/title",
          "value": "inputWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLCommandBuffer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLCommandBuffer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1exposureTexture/title",
          "value": "exposureTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1exposureTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exposureTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputContentWidth/title",
          "value": "inputContentWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputContentWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputContentWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputTextureUsage/title",
          "value": "outputTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1preExposure/title",
          "value": "preExposure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1preExposure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preExposure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1colorTexture/title",
          "value": "colorTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1colorTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1makeTemporalScaler(device:)/title",
          "value": "newTemporalScalerWithDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor~1makeTemporalScaler(device:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newTemporalScalerWithDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1depthTextureUsage/title",
          "value": "depthTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1depthTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depthTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reactiveTextureUsage/title",
          "value": "reactiveTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reactiveTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reactiveTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionVectorScaleX/title",
          "value": "motionVectorScaleX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionVectorScaleX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionVectorScaleX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reactiveMaskTexture/title",
          "value": "reactiveMaskTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reactiveMaskTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reactiveMaskTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputTexture/title",
          "value": "outputTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1fence/title",
          "value": "fence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1fence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1jitterOffsetY/title",
          "value": "jitterOffsetY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1jitterOffsetY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jitterOffsetY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1depthTextureFormat/title",
          "value": "depthTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1depthTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depthTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reset/title",
          "value": "reset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor/title",
          "value": "MTLFXTemporalScalerDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScalerDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1encode(commandBuffer:)/title",
          "value": "encodeToCommandBuffer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1encode(commandBuffer:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "encodeToCommandBuffer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputTextureFormat/title",
          "value": "outputTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1depthTexture/title",
          "value": "depthTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1depthTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depthTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputHeight/title",
          "value": "inputHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputHeight/title",
          "value": "outputHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1outputHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler/title",
          "value": "MTLFXTemporalScaler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionTextureUsage/title",
          "value": "motionTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionTextureFormat/title",
          "value": "motionTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1colorTextureFormat/title",
          "value": "colorTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1colorTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionVectorScaleY/title",
          "value": "motionVectorScaleY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionVectorScaleY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionVectorScaleY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1colorTextureUsage/title",
          "value": "colorTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1colorTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputContentMinScale/title",
          "value": "inputContentMinScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputContentMinScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputContentMinScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionTexture/title",
          "value": "motionTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1motionTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputContentHeight/title",
          "value": "inputContentHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputContentHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputContentHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputContentMaxScale/title",
          "value": "inputContentMaxScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1inputContentMaxScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputContentMaxScale"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalfx/mtlfxtemporalscaler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalfx/mtlfxtemporalscaler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
