{
  "abstract": [
    {
      "text": "An upscaling effect that generates a higher resolution texture in a render pass by spatially analyzing an input texture.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalfx/documentation/MetalFX"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLFXSpatialScaler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLFXSpatialScaler"
      }
    ],
    "modules": [
      {
        "name": "MetalFX"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLFXSpatialScaler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MTLFXSpatialScaler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScaler"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The MetalFX spatial scaler increases the size of your input texture to a larger output texture. You can use the scaler to upscale every frame of your app’s scene or rendering in real time. With a scaler, you can draw more complicated scenes in less time by intentionally rendering to a lower resolution to save time before upscaling.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance following these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create and configure an ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instance.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the descriptor’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/makeSpatialScaler(device:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Upscale a rendering by following these steps for every render pass:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the spatial scaler’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTexture",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to the input texture.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the scaler’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentWidth",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentHeight",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the scaler’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTexture",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to your destination texture.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Encode the upscale commands to an ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLCommandBuffer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " by calling the spatial scaler’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/encode(commandBuffer:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Metal/MTLCommandBuffer": {
      "abstract": [
        {
          "text": "A container that stores a sequence of GPU commands that you encode into it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBuffer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLCommandBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCommandBuffer",
      "type": "topic",
      "url": "/documentation/Metal/MTLCommandBuffer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalfx/documentation/MetalFX": {
      "abstract": [
        {
          "text": "Boost your Metal app’s performance by upscaling lower-resolution content to save GPU time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalFX",
      "type": "topic",
      "url": "/documentation/metalfx"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler": {
      "abstract": [
        {
          "text": "An upscaling effect that generates a higher resolution texture in a render pass by spatially analyzing an input texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScaler"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScaler"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScaler",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorProcessingMode": {
      "abstract": [
        {
          "text": "Reflects the color processing mode you set in this spatial scaler’s descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorProcessingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFXSpatialScalerColorProcessingMode",
          "text": "MTLFXSpatialScalerColorProcessingMode"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorProcessingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorProcessingMode"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorProcessingMode",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/colorprocessingmode"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTexture": {
      "abstract": [
        {
          "text": "An input color texture you set for the spatial scaler that supports the correct color texture usage options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/colortexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the input color texture for the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorTextureFormat"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/colortextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture usage options that your app’s input color texture must set to apply the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/colortextureusage"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/encode(commandBuffer:)": {
      "abstract": [
        {
          "text": "Adds the spatial scaler to a render pass’s command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "commandBuffer"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCommandBuffer",
          "text": "MTLCommandBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/encode(commandBuffer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encodeToCommandBuffer:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "encode(commandBuffer:)",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/encode(commandbuffer:)"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/fence": {
      "abstract": [
        {
          "text": "An optional fence instance that you provide to synchronize your app’s untracked resources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fence"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLFence",
          "text": "MTLFence"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/fence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fence"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "fence",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/fence"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the region within the color texture the spatial scaler uses as its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputContentHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputContentHeight"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputContentHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/inputcontentheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentWidth": {
      "abstract": [
        {
          "text": "The width, in pixels, of the region within the color texture the spatial scaler uses as its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputContentWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputContentWidth"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputContentWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/inputcontentwidth"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the input color texture for the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputHeight"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/inputheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputWidth": {
      "abstract": [
        {
          "text": "The width, in pixels, of the input color texture for the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputWidth"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/inputwidth"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the output color texture for the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputHeight"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/outputheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTexture": {
      "abstract": [
        {
          "text": "An output texture that supports the correct depth texture usage options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/outputtexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureFormat": {
      "abstract": [
        {
          "text": "The pixel format of the output color texture for the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTextureFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTextureFormat"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputTextureFormat",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/outputtextureformat"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture usage options that your app’s output texture must set to apply the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/outputtextureusage"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputWidth": {
      "abstract": [
        {
          "text": "The width, in pixels, of the output color texture for the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputWidth"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/outputwidth"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode": {
      "abstract": [
        {
          "text": "The color space modes for the input and output textures you use with a spatial scaling effect instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerColorProcessingMode"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerColorProcessingMode"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScalerColorProcessingMode",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalercolorprocessingmode"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor": {
      "abstract": [
        {
          "text": "A set of properties that configure a spatial scaling effect, and a factory method that creates the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScalerDescriptor",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/makeSpatialScaler(device:)": {
      "abstract": [
        {
          "text": "Creates a spatial scaler instance from this descriptor’s current property values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeSpatialScaler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLFXSpatialScaler",
          "text": "MTLFXSpatialScaler"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor/makeSpatialScaler(device:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newSpatialScalerWithDevice:"
        }
      ],
      "role": "symbol",
      "title": "makeSpatialScaler(device:)",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalerdescriptor/makespatialscaler(device:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Spatial-scaling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode"
      ],
      "title": "Spatial scaling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-image-input",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureUsage",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTexture",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentWidth",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentHeight"
      ],
      "title": "Configuring the image input"
    },
    {
      "anchor": "Configuring-the-image-output",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureUsage",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTexture"
      ],
      "title": "Configuring the image output"
    },
    {
      "anchor": "Synchronizing-untracked-resources",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/fence"
      ],
      "title": "Synchronizing untracked resources"
    },
    {
      "anchor": "Encoding-a-spatial-scaler",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/encode(commandBuffer:)"
      ],
      "title": "Encoding a spatial scaler"
    },
    {
      "anchor": "Inspecting-the-fixed-settings",
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputWidth",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputHeight",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureFormat",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorProcessingMode",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputWidth",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputHeight",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureFormat"
      ],
      "title": "Inspecting the fixed settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLFXSpatialScaler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalfx/documentation/MetalFX"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-image-input",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureUsage",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTexture",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentWidth",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputContentHeight"
              ],
              "title": "Configuring the image input"
            },
            {
              "anchor": "Configuring-the-image-output",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureUsage",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTexture"
              ],
              "title": "Configuring the image output"
            },
            {
              "anchor": "Synchronizing-untracked-resources",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/fence"
              ],
              "title": "Synchronizing untracked resources"
            },
            {
              "anchor": "Encoding-a-spatial-scaler",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/encode(commandBuffer:)"
              ],
              "title": "Encoding a spatial scaler"
            },
            {
              "anchor": "Inspecting-the-fixed-settings",
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputWidth",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/inputHeight",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureFormat",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorProcessingMode",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputWidth",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputHeight",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureFormat"
              ],
              "title": "Inspecting the fixed settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Spatial-scaling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerDescriptor",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode"
              ],
              "title": "Spatial scaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLFXSpatialScaler"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputHeight/title",
          "value": "outputHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1encode(commandBuffer:)/title",
          "value": "encodeToCommandBuffer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1encode(commandBuffer:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "encodeToCommandBuffer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1inputHeight/title",
          "value": "inputHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1inputHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTexture/title",
          "value": "outputTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1makeSpatialScaler(device:)/title",
          "value": "newSpatialScalerWithDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor~1makeSpatialScaler(device:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newSpatialScalerWithDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTextureFormat/title",
          "value": "outputTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor/title",
          "value": "MTLFXSpatialScalerDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputWidth/title",
          "value": "outputWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLCommandBuffer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLCommandBuffer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorTextureUsage/title",
          "value": "colorTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorTextureFormat/title",
          "value": "colorTextureFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorTextureFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorTextureFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorTexture/title",
          "value": "colorTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode/title",
          "value": "MTLFXSpatialScalerColorProcessingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1fence/title",
          "value": "fence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1fence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorProcessingMode/title",
          "value": "colorProcessingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorProcessingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorProcessingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1inputWidth/title",
          "value": "inputWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1inputWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler/title",
          "value": "MTLFXSpatialScaler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTextureUsage/title",
          "value": "outputTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1inputContentWidth/title",
          "value": "inputContentWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1inputContentWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputContentWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1inputContentHeight/title",
          "value": "inputContentHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1inputContentHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputContentHeight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalfx/mtlfxspatialscaler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalfx/mtlfxspatialscaler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
