{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Double"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Double/init(attributes:contents:factor:workspaceRequiredStatic:workspaceRequiredPerRHS:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So28SparseOpaqueSubfactor_Doublea10attributes8contents6factor23workspaceRequiredStatic0hI6PerRHSABSo0A12Attributes_ta_So0aC2_taSo0ab14Factorization_D0aS2itcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "attributes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SparseAttributes_t",
        "text": "SparseAttributes_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "contents"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@SparseSubfactor_t",
        "text": "SparseSubfactor_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "factor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
        "text": "SparseOpaqueFactorization_Double"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "workspaceRequiredStatic"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "workspaceRequiredPerRHS"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(attributes:contents:factor:workspaceRequiredStatic:workspaceRequiredPerRHS:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "attributes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseAttributes_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SparseAttributes_t",
              "text": "SparseAttributes_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "contents"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@SparseSubfactor_t",
              "text": "SparseSubfactor_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "factor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
              "text": "SparseOpaqueFactorization_Double"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "workspaceRequiredStatic"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "workspaceRequiredPerRHS"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseAttributes_t": {
      "abstract": [
        {
          "text": "A structure that represents the attributes of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseAttributes_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseAttributes_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseAttributes_t"
        }
      ],
      "role": "symbol",
      "title": "SparseAttributes_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparseattributes_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double": {
      "abstract": [
        {
          "text": "A structure that represents the factorization of a matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueFactorization_Double",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Double": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueSubfactor_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueSubfactor_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueSubfactor_Double",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquesubfactor_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Double/init(attributes:contents:factor:workspaceRequiredStatic:workspaceRequiredPerRHS:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseAttributes_t",
          "text": "SparseAttributes_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "factor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "workspaceRequiredStatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "workspaceRequiredPerRHS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Double/init(attributes:contents:factor:workspaceRequiredStatic:workspaceRequiredPerRHS:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(attributes:contents:factor:workspaceRequiredStatic:workspaceRequiredPerRHS:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquesubfactor_double/init(attributes:contents:factor:workspacerequiredstatic:workspacerequiredperrhs:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t": {
      "abstract": [
        {
          "text": "Constants that define the subfactor of a factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactor_t"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactor_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactor_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Double/title",
          "value": "SparseOpaqueSubfactor_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSubfactor_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSubfactor_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactor_t/title",
          "value": "SparseSubfactor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/title",
          "value": "SparseOpaqueFactorization_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseAttributes_t/title",
          "value": "SparseAttributes_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseAttributes_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseAttributes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseAttributes_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseAttributes_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparseopaquesubfactor_double/init(attributes:contents:factor:workspacerequiredstatic:workspacerequiredperrhs:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
