{
  "abstract": [
    {
      "text": "Error codes for the voice chat service error domain.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKVoiceChatServiceError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "9.0",
        "message": "No longer supported",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "No longer supported",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "3.0",
        "message": "No longer supported",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "GKVoiceChatServiceError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code": {
      "abstract": [
        {
          "text": "Error codes for the game session domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKPeerConnectionState": {
      "abstract": [
        {
          "text": "The state of a peer known to the session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPeerConnectionState"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerConnectionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPeerConnectionState"
        }
      ],
      "role": "symbol",
      "title": "GKPeerConnectionState",
      "type": "topic",
      "url": "/documentation/gamekit/gkpeerconnectionstate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerConnectionType": {
      "abstract": [
        {
          "text": "Network connections available to the peer picker dialog.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPeerPickerConnectionType"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerConnectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPeerPickerConnectionType"
        }
      ],
      "role": "symbol",
      "title": "GKPeerPickerConnectionType",
      "type": "topic",
      "url": "/documentation/gamekit/gkpeerpickerconnectiontype"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSendDataMode": {
      "abstract": [
        {
          "text": "The mechanism used to transmit data to other peers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSendDataMode"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSendDataMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSendDataMode"
        }
      ],
      "role": "symbol",
      "title": "GKSendDataMode",
      "type": "topic",
      "url": "/documentation/gamekit/gksenddatamode"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the session error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionMode": {
      "abstract": [
        {
          "text": "Modes that determine how a session interacts with other peers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionMode"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionMode"
        }
      ],
      "role": "symbol",
      "title": "GKSessionMode",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionmode"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the voice chat service error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/audioUnavailableError": {
      "abstract": [
        {
          "text": "The audio hardware is unavailable to the voice chat service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioUnavailableError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/audioUnavailableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceAudioUnavailableError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.audioUnavailableError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/audiounavailableerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/clientMissingRequiredMethodsError": {
      "abstract": [
        {
          "text": "The voice chat service did not find an expected method defined by the client.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientMissingRequiredMethodsError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/clientMissingRequiredMethodsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceClientMissingRequiredMethodsError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.clientMissingRequiredMethodsError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/clientmissingrequiredmethodserror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/internalError": {
      "abstract": [
        {
          "text": "A serious error occurred inside the voice chat service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceInternalError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.internalError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/internalerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/invalidCallIDError": {
      "abstract": [
        {
          "text": "The voice chat service didn’t recognize the call identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCallIDError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/invalidCallIDError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceInvalidCallIDError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.invalidCallIDError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/invalidcalliderror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/invalidParameterError": {
      "abstract": [
        {
          "text": "A parameter had an unrecognized value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameterError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/invalidParameterError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceInvalidParameterError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.invalidParameterError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/invalidparametererror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/methodCurrentlyInvalidError": {
      "abstract": [
        {
          "text": "A method on the voice chat service was called when it was not allowed to be called (for example, attempting to connect when the voice chat service was already connected).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "methodCurrentlyInvalidError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/methodCurrentlyInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceMethodCurrentlyInvalidError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.methodCurrentlyInvalidError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/methodcurrentlyinvaliderror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/networkConfigurationError": {
      "abstract": [
        {
          "text": "The voice chat service had problems accessing the network.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkConfigurationError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/networkConfigurationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceNetworkConfigurationError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.networkConfigurationError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/networkconfigurationerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/noRemotePacketsError": {
      "abstract": [
        {
          "text": "The voice chat service stopped receiving packets from the remote participant.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noRemotePacketsError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/noRemotePacketsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceNoRemotePacketsError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.noRemotePacketsError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/noremotepacketserror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/outOfMemoryError": {
      "abstract": [
        {
          "text": "The voice chat service was unable to allocate memory required to operate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfMemoryError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/outOfMemoryError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceOutOfMemoryError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.outOfMemoryError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/outofmemoryerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantBusyError": {
      "abstract": [
        {
          "text": "The remote participant is already connected to a voice chat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantBusyError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantBusyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceRemoteParticipantBusyError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.remoteParticipantBusyError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/remoteparticipantbusyerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantCancelledError": {
      "abstract": [
        {
          "text": "A remote participant attempted to start a voice chat, then canceled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantCancelledError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantCancelledError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceRemoteParticipantCancelledError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.remoteParticipantCancelledError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/remoteparticipantcancellederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantDeclinedInviteError": {
      "abstract": [
        {
          "text": "A remote participant declined an invitation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantDeclinedInviteError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantDeclinedInviteError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceRemoteParticipantDeclinedInviteError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.remoteParticipantDeclinedInviteError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/remoteparticipantdeclinedinviteerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantHangupError": {
      "abstract": [
        {
          "text": "The remote participant in a voice chat stopped the chat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantHangupError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantHangupError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceRemoteParticipantHangupError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.remoteParticipantHangupError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/remoteparticipanthanguperror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantResponseInvalidError": {
      "abstract": [
        {
          "text": "Invalid data was received from a remote participant.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantResponseInvalidError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantResponseInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceRemoteParticipantResponseInvalidError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.remoteParticipantResponseInvalidError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/remoteparticipantresponseinvaliderror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/unableToConnectError": {
      "abstract": [
        {
          "text": "The voice chat service was unable to establish a connection with another user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unableToConnectError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/unableToConnectError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceUnableToConnectError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.unableToConnectError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/unabletoconnecterror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/uninitializedClientError": {
      "abstract": [
        {
          "text": "The application did not set a client before calling voice chat service methods.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uninitializedClientError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/uninitializedClientError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceUninitializedClientError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.uninitializedClientError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/uninitializedclienterror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/unsupportedRemoteVersionError": {
      "abstract": [
        {
          "text": "The other participant is running a different version of the voice chat service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedRemoteVersionError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/unsupportedRemoteVersionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceUnsupportedRemoteVersionError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code.unsupportedRemoteVersionError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code/unsupportedremoteversionerror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code",
        "doc://com.apple.gamekit/documentation/GameKit/GKPeerConnectionState",
        "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerConnectionType",
        "doc://com.apple.gamekit/documentation/GameKit/GKSendDataMode",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionMode",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct"
      ],
      "title": "Deprecated enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/internalError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/noRemotePacketsError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/unableToConnectError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantHangupError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/invalidCallIDError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/audioUnavailableError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/uninitializedClientError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/clientMissingRequiredMethodsError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantBusyError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantCancelledError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantResponseInvalidError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantDeclinedInviteError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/methodCurrentlyInvalidError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/networkConfigurationError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/unsupportedRemoteVersionError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/outOfMemoryError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/invalidParameterError"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.4",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "3.0",
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKVoiceChatServiceError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/internalError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/noRemotePacketsError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/unableToConnectError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantHangupError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/invalidCallIDError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/audioUnavailableError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/uninitializedClientError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/clientMissingRequiredMethodsError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantBusyError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantCancelledError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantResponseInvalidError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/remoteParticipantDeclinedInviteError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/methodCurrentlyInvalidError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/networkConfigurationError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/unsupportedRemoteVersionError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/outOfMemoryError",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code/invalidParameterError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code",
                "doc://com.apple.gamekit/documentation/GameKit/GKPeerConnectionState",
                "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerConnectionType",
                "doc://com.apple.gamekit/documentation/GameKit/GKSendDataMode",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionMode"
              ],
              "title": "Deprecated enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKVoiceChatServiceError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1networkConfigurationError/title",
          "value": "GKVoiceChatServiceNetworkConfigurationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1networkConfigurationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceNetworkConfigurationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/title",
          "value": "GKSessionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code/title",
          "value": "GKVoiceChatServiceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1clientMissingRequiredMethodsError/title",
          "value": "GKVoiceChatServiceClientMissingRequiredMethodsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1clientMissingRequiredMethodsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceClientMissingRequiredMethodsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantDeclinedInviteError/title",
          "value": "GKVoiceChatServiceRemoteParticipantDeclinedInviteError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantDeclinedInviteError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceRemoteParticipantDeclinedInviteError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1uninitializedClientError/title",
          "value": "GKVoiceChatServiceUninitializedClientError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1uninitializedClientError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceUninitializedClientError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantBusyError/title",
          "value": "GKVoiceChatServiceRemoteParticipantBusyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantBusyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceRemoteParticipantBusyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantHangupError/title",
          "value": "GKVoiceChatServiceRemoteParticipantHangupError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantHangupError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceRemoteParticipantHangupError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1audioUnavailableError/title",
          "value": "GKVoiceChatServiceAudioUnavailableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1audioUnavailableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceAudioUnavailableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1invalidCallIDError/title",
          "value": "GKVoiceChatServiceInvalidCallIDError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1invalidCallIDError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceInvalidCallIDError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantResponseInvalidError/title",
          "value": "GKVoiceChatServiceRemoteParticipantResponseInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantResponseInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceRemoteParticipantResponseInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSendDataMode/title",
          "value": "GKSendDataMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSendDataMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSendDataMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSendDataMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSendDataMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantCancelledError/title",
          "value": "GKVoiceChatServiceRemoteParticipantCancelledError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1remoteParticipantCancelledError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceRemoteParticipantCancelledError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1methodCurrentlyInvalidError/title",
          "value": "GKVoiceChatServiceMethodCurrentlyInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1methodCurrentlyInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceMethodCurrentlyInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionMode/title",
          "value": "GKSessionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1noRemotePacketsError/title",
          "value": "GKVoiceChatServiceNoRemotePacketsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1noRemotePacketsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceNoRemotePacketsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1outOfMemoryError/title",
          "value": "GKVoiceChatServiceOutOfMemoryError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1outOfMemoryError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceOutOfMemoryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionError~1Code/title",
          "value": "GKGameSessionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1invalidParameterError/title",
          "value": "GKVoiceChatServiceInvalidParameterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1invalidParameterError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceInvalidParameterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1unsupportedRemoteVersionError/title",
          "value": "GKVoiceChatServiceUnsupportedRemoteVersionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1unsupportedRemoteVersionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceUnsupportedRemoteVersionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerConnectionState/title",
          "value": "GKPeerConnectionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerConnectionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerConnectionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1internalError/title",
          "value": "GKVoiceChatServiceInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1unableToConnectError/title",
          "value": "GKVoiceChatServiceUnableToConnectError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code~1unableToConnectError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceUnableToConnectError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerConnectionType/title",
          "value": "GKPeerPickerConnectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerConnectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerConnectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerConnectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerConnectionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
