{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "deprecated",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "deprecated",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantBusyError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC23GKVoiceChatServiceErrorLeV021remoteParticipantBusyD0SoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "remoteParticipantBusyError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
        "text": "GKVoiceChatServiceError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "9.0",
        "message": "No longer supported",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "No longer supported",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "3.0",
        "message": "No longer supported",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "remoteParticipantBusyError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "remoteParticipantBusyError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
              "text": "GKVoiceChatServiceError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the voice chat service error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/audioUnavailableError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioUnavailableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/audioUnavailableError",
      "kind": "symbol",
      "role": "symbol",
      "title": "audioUnavailableError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/audiounavailableerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/clientMissingRequiredMethodsError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientMissingRequiredMethodsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/clientMissingRequiredMethodsError",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientMissingRequiredMethodsError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/clientmissingrequiredmethodserror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/internalError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/internalerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/invalidCallIDError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCallIDError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/invalidCallIDError",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidCallIDError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/invalidcalliderror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/invalidParameterError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameterError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/invalidParameterError",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidParameterError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/invalidparametererror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/methodCurrentlyInvalidError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "methodCurrentlyInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/methodCurrentlyInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "methodCurrentlyInvalidError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/methodcurrentlyinvaliderror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/networkConfigurationError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkConfigurationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/networkConfigurationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkConfigurationError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/networkconfigurationerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/noRemotePacketsError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noRemotePacketsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/noRemotePacketsError",
      "kind": "symbol",
      "role": "symbol",
      "title": "noRemotePacketsError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/noremotepacketserror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/outOfMemoryError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfMemoryError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/outOfMemoryError",
      "kind": "symbol",
      "role": "symbol",
      "title": "outOfMemoryError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/outofmemoryerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantBusyError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantBusyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantBusyError",
      "kind": "symbol",
      "role": "symbol",
      "title": "remoteParticipantBusyError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/remoteparticipantbusyerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantCancelledError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantCancelledError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantCancelledError",
      "kind": "symbol",
      "role": "symbol",
      "title": "remoteParticipantCancelledError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/remoteparticipantcancellederror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantDeclinedInviteError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantDeclinedInviteError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantDeclinedInviteError",
      "kind": "symbol",
      "role": "symbol",
      "title": "remoteParticipantDeclinedInviteError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/remoteparticipantdeclinedinviteerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantHangupError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantHangupError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantHangupError",
      "kind": "symbol",
      "role": "symbol",
      "title": "remoteParticipantHangupError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/remoteparticipanthanguperror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantResponseInvalidError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteParticipantResponseInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantResponseInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "remoteParticipantResponseInvalidError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/remoteparticipantresponseinvaliderror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/unableToConnectError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unableToConnectError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/unableToConnectError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unableToConnectError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/unabletoconnecterror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/uninitializedClientError": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uninitializedClientError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23GKVoiceChatServiceErrorLeV",
          "text": "GKVoiceChatServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKVoiceChatServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/uninitializedClientError",
      "kind": "symbol",
      "role": "symbol",
      "title": "uninitializedClientError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/uninitializedclienterror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/audioUnavailableError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/clientMissingRequiredMethodsError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/internalError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/invalidCallIDError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/invalidParameterError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/methodCurrentlyInvalidError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/networkConfigurationError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/noRemotePacketsError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/outOfMemoryError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantCancelledError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantDeclinedInviteError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantHangupError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/remoteParticipantResponseInvalidError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/unableToConnectError",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/uninitializedClientError"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code/title",
          "value": "GKVoiceChatServiceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/remoteparticipantbusyerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
