{
  "abstract": [
    {
      "text": "Fetches sample information that occurs after this time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/from"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRFetchRequest(py)from",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "from"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SRAbsoluteTime",
        "text": "SRAbsoluteTime"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "from"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "from"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "from"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRAbsoluteTime",
              "text": "SRAbsoluteTime"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A fetch is exclusive of this time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The framework requires the app to define a value for this property. If an app fails to define this property, the framework responds to the fetch by providing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/fetchRequestInvalid",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to the reader delegate via ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime": {
      "abstract": [
        {
          "text": "A value that describes when the system records the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTime"
        }
      ],
      "role": "symbol",
      "title": "SRAbsoluteTime",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetime"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/current()": {
      "abstract": [
        {
          "text": "Provides the current absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "current"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRAbsoluteTime",
          "text": "SRAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/current()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTimeGetCurrent"
        }
      ],
      "role": "symbol",
      "title": "current()",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetime/current()"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/toCFAbsoluteTime()": {
      "abstract": [
        {
          "text": "Converts an absolute time to a core-foundation absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toCFAbsoluteTime"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAbsoluteTime",
          "text": "CFAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/toCFAbsoluteTime()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTimeToCFAbsoluteTime"
        }
      ],
      "role": "symbol",
      "title": "toCFAbsoluteTime()",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetime/tocfabsolutetime()"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromCFAbsoluteTime": {
      "abstract": [
        {
          "text": "Provides an absolute time equivalent to the argument core-foundation absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTimeFromCFAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromCFAbsoluteTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRAbsoluteTimeFromCFAbsoluteTime",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetimefromcfabsolutetime"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromContinuousTime": {
      "abstract": [
        {
          "text": "Provides an absolute time equivalent to the argument continuous time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTimeFromContinuousTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromContinuousTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRAbsoluteTimeFromContinuousTime",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetimefromcontinuoustime"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/fetchRequestInvalid": {
      "abstract": [
        {
          "text": "Occurs when the app misconfigures a fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchRequestInvalid"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/fetchRequestInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRErrorFetchRequestInvalid"
        }
      ],
      "role": "symbol",
      "title": "SRError.Code.fetchRequestInvalid",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror/code/fetchrequestinvalid"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest": {
      "abstract": [
        {
          "text": "An object that defines the criteria for a sample query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "SRFetchRequest",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchrequest"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/from": {
      "abstract": [
        {
          "text": "Fetches sample information that occurs after this time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRAbsoluteTime",
          "text": "SRAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/from",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "from"
        }
      ],
      "role": "symbol",
      "title": "from",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchrequest/from"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/to": {
      "abstract": [
        {
          "text": "Fetches sample information that occurs before this time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRAbsoluteTime",
          "text": "SRAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/to",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "to"
        }
      ],
      "role": "symbol",
      "title": "to",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchrequest/to"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)": {
      "abstract": [
        {
          "text": "Provides the delegate with a fetch failure reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fetching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFetchRequest",
          "text": "SRFetchRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "failedWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:fetchingRequest:failedWithError:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:fetching:failedWithError:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:failedwitherror:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-the-Time-Range",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/to",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/current()",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/toCFAbsoluteTime()"
      ],
      "title": "Defining the Time Range"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "from"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "from"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Defining-the-Time-Range",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/to",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/current()",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromCFAbsoluteTime",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromContinuousTime",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/toCFAbsoluteTime()"
              ],
              "title": "Defining the Time Range"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SRAbsoluteTime",
                    "text": "SRAbsoluteTime"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "from"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1fetchRequestInvalid/title",
          "value": "SRErrorFetchRequestInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1fetchRequestInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorFetchRequestInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime/title",
          "value": "SRAbsoluteTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAbsoluteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAbsoluteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/title",
          "value": "SRFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime~1current()/title",
          "value": "SRAbsoluteTimeGetCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime~1current()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAbsoluteTimeGetCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime~1toCFAbsoluteTime()/title",
          "value": "SRAbsoluteTimeToCFAbsoluteTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime~1toCFAbsoluteTime()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAbsoluteTimeToCFAbsoluteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest~1to/title",
          "value": "to"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest~1to/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "to"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest~1from/title",
          "value": "from"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest~1from/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "from"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:failedWithError:)/title",
          "value": "sensorReader:fetchingRequest:failedWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:failedWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:fetchingRequest:failedWithError:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srfetchrequest/from"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srfetchrequest/from"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
