{
  "abstract": [
    {
      "text": "A mode that enables manual self-sizing invalidation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/enabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UICollectionViewSelfSizingInvalidation@UICollectionViewSelfSizingInvalidationEnabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "enabled"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICollectionViewSelfSizingInvalidationEnabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UICollectionView.SelfSizingInvalidation.enabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you use this self-sizing invalidation mode, calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/invalidateIntrinsicContentSize()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on a self-sizing cell or its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/contentView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " causes the cell to resize if necessary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView": {
      "abstract": [
        {
          "text": "An object that manages an ordered collection of data items and presents them using customizable layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe modes for invalidating the size of self-sizing collection view cells.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SelfSizingInvalidation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SelfSizingInvalidation"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView.SelfSizingInvalidation",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview/selfsizinginvalidation-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/disabled": {
      "abstract": [
        {
          "text": "A mode that disables self-sizing invalidation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewSelfSizingInvalidationDisabled"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView.SelfSizingInvalidation.disabled",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview/selfsizinginvalidation-swift.enum/disabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/enabled": {
      "abstract": [
        {
          "text": "A mode that enables manual self-sizing invalidation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/enabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewSelfSizingInvalidationEnabled"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView.SelfSizingInvalidation.enabled",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview/selfsizinginvalidation-swift.enum/enabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/enabledIncludingConstraints": {
      "abstract": [
        {
          "text": "A mode that enables automatic self-sizing invalidation after Auto Layout changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabledIncludingConstraints"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/enabledIncludingConstraints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewSelfSizingInvalidationEnabledIncludingConstraints"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView.SelfSizingInvalidation.enabledIncludingConstraints",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview/selfsizinginvalidation-swift.enum/enabledincludingconstraints"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/contentView": {
      "abstract": [
        {
          "text": "The main view that you add your cell’s custom content to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/contentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentView"
        }
      ],
      "role": "symbol",
      "title": "contentView",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcell/contentview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/invalidateIntrinsicContentSize()": {
      "abstract": [
        {
          "text": "Invalidates the view’s intrinsic content size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateIntrinsicContentSize"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/invalidateIntrinsicContentSize()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateIntrinsicContentSize"
        }
      ],
      "role": "symbol",
      "title": "invalidateIntrinsicContentSize()",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidateintrinsiccontentsize()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/disabled",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/enabledIncludingConstraints"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICollectionViewSelfSizingInvalidationEnabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewSelfSizingInvalidationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/disabled",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionView/SelfSizingInvalidation-swift.enum/enabledIncludingConstraints"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UICollectionViewSelfSizingInvalidationEnabled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1SelfSizingInvalidation-swift.enum~1disabled/title",
          "value": "UICollectionViewSelfSizingInvalidationDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1SelfSizingInvalidation-swift.enum~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewSelfSizingInvalidationDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1SelfSizingInvalidation-swift.enum~1enabledIncludingConstraints/title",
          "value": "UICollectionViewSelfSizingInvalidationEnabledIncludingConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1SelfSizingInvalidation-swift.enum~1enabledIncludingConstraints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewSelfSizingInvalidationEnabledIncludingConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1SelfSizingInvalidation-swift.enum/title",
          "value": "UICollectionViewSelfSizingInvalidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1SelfSizingInvalidation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewSelfSizingInvalidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1SelfSizingInvalidation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewSelfSizingInvalidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1invalidateIntrinsicContentSize()/title",
          "value": "invalidateIntrinsicContentSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1invalidateIntrinsicContentSize()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateIntrinsicContentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1SelfSizingInvalidation-swift.enum~1enabled/title",
          "value": "UICollectionViewSelfSizingInvalidationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1SelfSizingInvalidation-swift.enum~1enabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewSelfSizingInvalidationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title",
          "value": "UICollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell~1contentView/title",
          "value": "contentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell~1contentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionview/selfsizinginvalidation-swift.enum/enabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollectionview/selfsizinginvalidation-swift.enum/enabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
