{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please see the release notes and Core Data documentation.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType/init(rawValue:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So41NSPersistentStoreUbiquitousTransitionTypeV8rawValueABSgSu_tcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "rawValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Su",
        "text": "UInt"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "7.0",
        "message": "Please see the release notes and Core Data documentation.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "7.0",
        "message": "Please see the release notes and Core Data documentation.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Please see the release notes and Core Data documentation.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.9",
        "message": "Please see the release notes and Core Data documentation.",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please see the release notes and Core Data documentation.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(rawValue:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Su",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Su",
              "text": "UInt"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that the coordinator posts after its registered stores change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorStoresDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorStoresDidChangeNotification",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinatorstoresdidchangenotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresWillChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts before a coordinator changes its registered stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorStoresWillChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresWillChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorStoresWillChangeNotification",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinatorstoreswillchangenotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType": {
      "abstract": [
        {
          "text": "These constants are used as the value corresponding to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " in the user info dictionary of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresWillChangeNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresDidChangeNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " notifications to identify the type of event leading to a change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionType"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousTransitionType",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitoustransitiontype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitoustransitiontype/init(rawvalue:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionTypeKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousTransitionTypeKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitoustransitiontypekey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Su": {
      "abstract": [
        {
          "text": "An unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Su",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt",
      "type": "topic",
      "url": "/documentation/Swift/UInt"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionTypeKey/title",
          "value": "NSPersistentStoreUbiquitousTransitionTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousTransitionTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionType/title",
          "value": "NSPersistentStoreUbiquitousTransitionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousTransitionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousTransitionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistentstoreubiquitoustransitiontype/init(rawvalue:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
