{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/accelerometerBatch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMBatchedSensorManager(py)accelerometerBatch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accelerometerBatch"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CMAccelerometerData",
        "text": "CMAccelerometerData"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accelerometerBatch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "accelerometerBatch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accelerometerBatch"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMAccelerometerData",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMAccelerometerData",
              "text": "CMAccelerometerData"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMAccelerometerData": {
      "abstract": [
        {
          "text": "A data sample from the device’s three accelerometers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAccelerometerData"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMAccelerometerData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAccelerometerData"
        }
      ],
      "role": "symbol",
      "title": "CMAccelerometerData",
      "type": "topic",
      "url": "/documentation/coremotion/cmaccelerometerdata"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBatchedSensorManager"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBatchedSensorManager"
        }
      ],
      "role": "symbol",
      "title": "CMBatchedSensorManager",
      "type": "topic",
      "url": "/documentation/coremotion/cmbatchedsensormanager"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/AccelerometerUpdates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccelerometerUpdates"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/AccelerometerUpdates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccelerometerUpdates"
        }
      ],
      "role": "symbol",
      "title": "CMBatchedSensorManager.AccelerometerUpdates",
      "type": "topic",
      "url": "/documentation/coremotion/cmbatchedsensormanager/accelerometerupdates"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/accelerometerBatch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accelerometerBatch"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMAccelerometerData",
          "text": "CMAccelerometerData"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/accelerometerBatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accelerometerBatch"
        }
      ],
      "role": "symbol",
      "title": "accelerometerBatch",
      "type": "topic",
      "url": "/documentation/coremotion/cmbatchedsensormanager/accelerometerbatch"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/accelerometerUpdates()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accelerometerUpdates"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMBatchedSensorManager",
          "text": "CMBatchedSensorManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMBatchedSensorManagerC10CoreMotionE20AccelerometerUpdatesV",
          "text": "AccelerometerUpdates"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/accelerometerUpdates()",
      "kind": "symbol",
      "role": "symbol",
      "title": "accelerometerUpdates()",
      "type": "topic",
      "url": "/documentation/coremotion/cmbatchedsensormanager/accelerometerupdates()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/isAccelerometerActive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAccelerometerActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/isAccelerometerActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accelerometerActive"
        }
      ],
      "role": "symbol",
      "title": "isAccelerometerActive",
      "type": "topic",
      "url": "/documentation/coremotion/cmbatchedsensormanager/isaccelerometeractive"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/startAccelerometerUpdates()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startAccelerometerUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/startAccelerometerUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startAccelerometerUpdates"
        }
      ],
      "role": "symbol",
      "title": "startAccelerometerUpdates()",
      "type": "topic",
      "url": "/documentation/coremotion/cmbatchedsensormanager/startaccelerometerupdates()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/startAccelerometerUpdates(handler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startAccelerometerUpdates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMAccelerometerData",
          "text": "CMAccelerometerData"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/startAccelerometerUpdates(handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startAccelerometerUpdatesWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "startAccelerometerUpdates(handler:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmbatchedsensormanager/startaccelerometerupdates(handler:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/stopAccelerometerUpdates()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopAccelerometerUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/stopAccelerometerUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopAccelerometerUpdates"
        }
      ],
      "role": "symbol",
      "title": "stopAccelerometerUpdates()",
      "type": "topic",
      "url": "/documentation/coremotion/cmbatchedsensormanager/stopaccelerometerupdates()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Collecting-accelerometer-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/startAccelerometerUpdates()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/startAccelerometerUpdates(handler:)",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/stopAccelerometerUpdates()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/accelerometerUpdates()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/AccelerometerUpdates",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/isAccelerometerActive"
      ],
      "title": "Collecting accelerometer data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "accelerometerBatch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accelerometerBatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Collecting-accelerometer-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/startAccelerometerUpdates()",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/startAccelerometerUpdates(handler:)",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/stopAccelerometerUpdates()",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMBatchedSensorManager/isAccelerometerActive"
              ],
              "title": "Collecting accelerometer data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<CMAccelerometerData *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "accelerometerBatch"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1isAccelerometerActive/title",
          "value": "accelerometerActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1isAccelerometerActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accelerometerActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1startAccelerometerUpdates()/title",
          "value": "startAccelerometerUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1startAccelerometerUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAccelerometerUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1accelerometerBatch/title",
          "value": "accelerometerBatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1accelerometerBatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accelerometerBatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1stopAccelerometerUpdates()/title",
          "value": "stopAccelerometerUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1stopAccelerometerUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopAccelerometerUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMAccelerometerData/title",
          "value": "CMAccelerometerData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMAccelerometerData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAccelerometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMAccelerometerData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAccelerometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1startAccelerometerUpdates(handler:)/title",
          "value": "startAccelerometerUpdatesWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager~1startAccelerometerUpdates(handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAccelerometerUpdatesWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager/title",
          "value": "CMBatchedSensorManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBatchedSensorManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMBatchedSensorManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBatchedSensorManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmbatchedsensormanager/accelerometerbatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmbatchedsensormanager/accelerometerbatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
