{
  "abstract": [
    {
      "text": "The source color is subtracted from the destination color.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/subtract"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNParticleBlendMode@SCNParticleBlendModeSubtract",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "subtract"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNParticleBlendModeSubtract"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SCNParticleBlendMode.subtract"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "subtract"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode": {
      "abstract": [
        {
          "text": "Options for combining source and destination pixel colors when compositing particles during rendering, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/blendMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNParticleBlendMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleBlendMode"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleBlendMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleblendmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/additive": {
      "abstract": [
        {
          "text": "The source and destination colors are added together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "additive"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/additive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleBlendModeAdditive"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleBlendMode.additive",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleblendmode/additive"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/alpha": {
      "abstract": [
        {
          "text": "The source and destination colors are blended by multiplying the source alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alpha"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleBlendModeAlpha"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleBlendMode.alpha",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleblendmode/alpha"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/multiply": {
      "abstract": [
        {
          "text": "The source color is multiplied by the destination color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiply"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/multiply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleBlendModeMultiply"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleBlendMode.multiply",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleblendmode/multiply"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/replace": {
      "abstract": [
        {
          "text": "The source color replaces the destination color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replace"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/replace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleBlendModeReplace"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleBlendMode.replace",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleblendmode/replace"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/screen": {
      "abstract": [
        {
          "text": "The source color is added to the destination color times the inverted source color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screen"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/screen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleBlendModeScreen"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleBlendMode.screen",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleblendmode/screen"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/subtract": {
      "abstract": [
        {
          "text": "The source color is subtracted from the destination color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtract"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/subtract",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleBlendModeSubtract"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleBlendMode.subtract",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleblendmode/subtract"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/blendMode": {
      "abstract": [
        {
          "text": "The blending mode for compositing particle images into the rendered scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blendMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNParticleBlendMode",
          "text": "SCNParticleBlendMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/blendMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "blendMode"
        }
      ],
      "role": "symbol",
      "title": "blendMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/blendmode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/additive",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/multiply",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/screen",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/alpha",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/replace"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNParticleBlendModeSubtract"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleBlendModeSubtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/additive",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/multiply",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/screen",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/alpha",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleBlendMode/replace"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCNParticleBlendModeSubtract"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1screen/title",
          "value": "SCNParticleBlendModeScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1screen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleBlendModeScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1subtract/title",
          "value": "SCNParticleBlendModeSubtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1subtract/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleBlendModeSubtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode/title",
          "value": "SCNParticleBlendMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleBlendMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleBlendMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1multiply/title",
          "value": "SCNParticleBlendModeMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1multiply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleBlendModeMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1additive/title",
          "value": "SCNParticleBlendModeAdditive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1additive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleBlendModeAdditive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1blendMode/title",
          "value": "blendMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1blendMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blendMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1replace/title",
          "value": "SCNParticleBlendModeReplace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1replace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleBlendModeReplace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1alpha/title",
          "value": "SCNParticleBlendModeAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleBlendMode~1alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleBlendModeAlpha"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnparticleblendmode/subtract"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnparticleblendmode/subtract"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
