{
  "abstract": [
    {
      "text": "Configures the same comparison value for front- and back-facing primitives.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setStencilReferenceValue(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLRenderCommandEncoder(im)setStencilReferenceValue:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setStencilReferenceValue"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setStencilReferenceValue:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setStencilReferenceValue(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setStencilReferenceValue"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "referenceValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A stencil test comparison value the render pipeline applies to both front- and back-facing primitives.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "referenceValue"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The command sets the same reference value for front- and back-facing primitives (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStencilDescriptor/stencilCompareFunction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDepthStencilDescriptor/frontFaceStencil",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDepthStencilDescriptor/backFaceStencil",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). This reference value applies to the stencil state you set with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthStencilState(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The render pass’s default reference value for the front and back stencil compare function is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDepthStencilDescriptor/backFaceStencil": {
      "abstract": [
        {
          "text": "The stencil descriptor for back-facing primitives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backFaceStencil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLStencilDescriptor",
          "text": "MTLStencilDescriptor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDepthStencilDescriptor/backFaceStencil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backFaceStencil"
        }
      ],
      "role": "symbol",
      "title": "backFaceStencil",
      "type": "topic",
      "url": "/documentation/metal/mtldepthstencildescriptor/backfacestencil"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDepthStencilDescriptor/frontFaceStencil": {
      "abstract": [
        {
          "text": "The stencil descriptor for front-facing primitives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontFaceStencil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLStencilDescriptor",
          "text": "MTLStencilDescriptor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDepthStencilDescriptor/frontFaceStencil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frontFaceStencil"
        }
      ],
      "role": "symbol",
      "title": "frontFaceStencil",
      "type": "topic",
      "url": "/documentation/metal/mtldepthstencildescriptor/frontfacestencil"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder": {
      "abstract": [
        {
          "text": "An interface that encodes a render pass into a command buffer, including all its draw calls and configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderCommandEncoder"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderCommandEncoder",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthBias(_:slopeScale:clamp:)": {
      "abstract": [
        {
          "text": "Configures the adjustments a render pass applies to depth values from fragment functions by a scaling factor and bias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDepthBias"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "slopeScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthBias(_:slopeScale:clamp:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDepthBias:slopeScale:clamp:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setDepthBias(_:slopeScale:clamp:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setdepthbias(_:slopescale:clamp:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthClipMode(_:)": {
      "abstract": [
        {
          "text": "Configures how the render pipeline handles fragments outside the near and far planes of the view frustum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDepthClipMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDepthClipMode",
          "text": "MTLDepthClipMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthClipMode(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDepthClipMode:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setDepthClipMode(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setdepthclipmode(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthStencilState(_:)": {
      "abstract": [
        {
          "text": "Configures the combined depth and stencil state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDepthStencilState"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDepthStencilState",
          "text": "MTLDepthStencilState"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthStencilState(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDepthStencilState:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setDepthStencilState(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setdepthstencilstate(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setStencilReferenceValue(_:)": {
      "abstract": [
        {
          "text": "Configures the same comparison value for front- and back-facing primitives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStencilReferenceValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setStencilReferenceValue(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStencilReferenceValue:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setStencilReferenceValue(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setstencilreferencevalue(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setStencilReferenceValues(front:back:)": {
      "abstract": [
        {
          "text": "Configures different comparison values for front- and back-facing primitives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStencilReferenceValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "front"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "back"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setStencilReferenceValues(front:back:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStencilFrontReferenceValue:backReferenceValue:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setStencilReferenceValues(front:back:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setstencilreferencevalues(front:back:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStencilDescriptor/stencilCompareFunction": {
      "abstract": [
        {
          "text": "The comparison that is performed between the masked reference value and a masked value in the stencil attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stencilCompareFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCompareFunction",
          "text": "MTLCompareFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStencilDescriptor/stencilCompareFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stencilCompareFunction"
        }
      ],
      "role": "symbol",
      "title": "stencilCompareFunction",
      "type": "topic",
      "url": "/documentation/metal/mtlstencildescriptor/stencilcomparefunction"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Depth-and-Stencil-Behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthStencilState(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthBias(_:slopeScale:clamp:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthClipMode(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setStencilReferenceValues(front:back:)"
      ],
      "title": "Configuring Depth and Stencil Behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setStencilReferenceValue:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStencilReferenceValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Depth-and-Stencil-Behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthStencilState(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthBias(_:slopeScale:clamp:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setDepthClipMode(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setStencilReferenceValues(front:back:)"
              ],
              "title": "Configuring Depth and Stencil Behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setStencilReferenceValue:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "referenceValue"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A stencil test comparison value the render pipeline applies to both front- and back-facing primitives.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "referenceValue"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setStencilReferenceValue(_:)/title",
          "value": "setStencilReferenceValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setStencilReferenceValue(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStencilReferenceValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setDepthBias(_:slopeScale:clamp:)/title",
          "value": "setDepthBias:slopeScale:clamp:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setDepthBias(_:slopeScale:clamp:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDepthBias:slopeScale:clamp:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setDepthClipMode(_:)/title",
          "value": "setDepthClipMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setDepthClipMode(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDepthClipMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setDepthStencilState(_:)/title",
          "value": "setDepthStencilState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setDepthStencilState(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDepthStencilState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDepthStencilDescriptor~1frontFaceStencil/title",
          "value": "frontFaceStencil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDepthStencilDescriptor~1frontFaceStencil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frontFaceStencil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setStencilReferenceValues(front:back:)/title",
          "value": "setStencilFrontReferenceValue:backReferenceValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setStencilReferenceValues(front:back:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStencilFrontReferenceValue:backReferenceValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDepthStencilDescriptor~1backFaceStencil/title",
          "value": "backFaceStencil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDepthStencilDescriptor~1backFaceStencil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backFaceStencil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStencilDescriptor~1stencilCompareFunction/title",
          "value": "stencilCompareFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStencilDescriptor~1stencilCompareFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stencilCompareFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/title",
          "value": "MTLRenderCommandEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderCommandEncoder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlrendercommandencoder/setstencilreferencevalue(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlrendercommandencoder/setstencilreferencevalue(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
