{"kind":"symbol","variants":[{"paths":["/documentation/appkit/nsgridcolumn/gridview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsgridcolumn/gridview"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement"],"title":"Instance Properties","anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGridColumn"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gridView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSGridView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridView","preciseIdentifier":"c:objc(cs)NSGridView","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"gridView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSGridView","text":"NSGridView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"gridView","kind":"identifier"}],"platforms":[{"unavailable":false,"name":"macOS","introducedAt":"10.12","deprecated":false,"beta":false}],"role":"symbol","externalID":"c:objc(cs)NSGridColumn(py)gridView","title":"gridView","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xPlacement","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSGridCell","text":"NSGridCell","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSGridCellPlacement","text":"Placement","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsgridcolumn/xplacement","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"xPlacement","kind":"identifier"}],"title":"xPlacement"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn":{"abstract":[{"text":"A column within a grid view.","type":"text"}],"navigatorTitle":[{"text":"NSGridColumn","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn","url":"/documentation/appkit/nsgridcolumn","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSGridColumn","kind":"identifier"}],"role":"symbol","title":"NSGridColumn"},"doc://com.apple.appkit/documentation/AppKit/NSGridView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridView","abstract":[{"type":"text","text":"A container that aligns views in a flexible grid of rows and columns."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSGridView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSGridView"}],"title":"NSGridView","kind":"symbol","url":"/documentation/appkit/nsgridview","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gridView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSGridView","text":"NSGridView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/appkit/nsgridcolumn/gridview","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"gridView","kind":"identifier"}],"title":"gridView"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding":{"url":"/documentation/appkit/nsgridcolumn/leadingpadding","abstract":[],"role":"symbol","title":"leadingPadding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"leadingPadding"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsgridcolumn/width","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"width","kind":"identifier"}],"title":"width"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailingPadding","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nsgridcolumn/trailingpadding","navigatorTitle":[{"text":"trailingPadding","kind":"identifier"}],"title":"trailingPadding","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfCells","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsgridcolumn/numberofcells","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"numberOfCells","kind":"identifier"}],"title":"numberOfCells"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nsgridcolumn/ishidden","navigatorTitle":[{"kind":"identifier","text":"hidden"}],"title":"isHidden","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.12","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"gridView","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"gridView"}],"op":"replace","path":"/metadata/fragments"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGridColumn"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement"],"title":"Instance Properties"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSGridView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridView","preciseIdentifier":"c:objc(cs)NSGridView","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"gridView","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1xPlacement/title","value":"xPlacement","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1xPlacement/fragments","value":[{"text":"xPlacement","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn/title","value":"NSGridColumn","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn/fragments","value":[{"kind":"identifier","text":"NSGridColumn"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn/navigatorTitle","value":[{"kind":"identifier","text":"NSGridColumn"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView/title","value":"NSGridView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView/fragments","value":[{"text":"NSGridView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView/navigatorTitle","value":[{"kind":"identifier","text":"NSGridView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1gridView/title","value":"gridView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1gridView/fragments","value":[{"text":"gridView","kind":"identifier"}],"op":"replace"},{"value":"leadingPadding","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1leadingPadding/title","op":"replace"},{"value":[{"text":"leadingPadding","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1leadingPadding/fragments","op":"replace"},{"value":"width","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1width/title","op":"replace"},{"value":[{"text":"width","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1width/fragments","op":"replace"},{"value":"trailingPadding","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1trailingPadding/title","op":"replace"},{"value":[{"text":"trailingPadding","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1trailingPadding/fragments","op":"replace"},{"value":"numberOfCells","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1numberOfCells/title","op":"replace"},{"value":[{"text":"numberOfCells","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1numberOfCells/fragments","op":"replace"},{"value":"hidden","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1isHidden/title","op":"replace"},{"value":[{"text":"hidden","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1isHidden/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}