{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfCells","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]}],"seeAlsoSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement"],"anchor":"Instance-Properties"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGridColumn"]]},"metadata":{"navigatorTitle":[{"text":"numberOfCells","kind":"identifier"}],"title":"numberOfCells","platforms":[{"beta":false,"introducedAt":"10.12","deprecated":false,"name":"macOS","unavailable":false}],"role":"symbol","modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)NSGridColumn(py)numberOfCells","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfCells"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"variants":[{"paths":["/documentation/appkit/nsgridcolumn/numberofcells"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsgridcolumn/numberofcells"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding":{"url":"/documentation/appkit/nsgridcolumn/leadingpadding","abstract":[],"role":"symbol","title":"leadingPadding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"leadingPadding"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfCells","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsgridcolumn/numberofcells","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"numberOfCells","kind":"identifier"}],"title":"numberOfCells"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn":{"abstract":[{"text":"A column within a grid view.","type":"text"}],"navigatorTitle":[{"text":"NSGridColumn","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn","url":"/documentation/appkit/nsgridcolumn","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSGridColumn","kind":"identifier"}],"role":"symbol","title":"NSGridColumn"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xPlacement","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSGridCell","text":"NSGridCell","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSGridCellPlacement","text":"Placement","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsgridcolumn/xplacement","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"xPlacement","kind":"identifier"}],"title":"xPlacement"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nsgridcolumn/ishidden","navigatorTitle":[{"kind":"identifier","text":"hidden"}],"title":"isHidden","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gridView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSGridView","text":"NSGridView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/appkit/nsgridcolumn/gridview","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"gridView","kind":"identifier"}],"title":"gridView"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailingPadding","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nsgridcolumn/trailingpadding","navigatorTitle":[{"text":"trailingPadding","kind":"identifier"}],"title":"trailingPadding","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsgridcolumn/width","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"width","kind":"identifier"}],"title":"width"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false,"introducedAt":"10.12"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"numberOfCells","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"numberOfCells","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSGridColumn"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfCells"},{"kind":"text","text":";"}]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1leadingPadding/title","op":"replace","value":"leadingPadding"},{"value":[{"text":"leadingPadding","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1leadingPadding/fragments","op":"replace"},{"value":"numberOfCells","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1numberOfCells/title","op":"replace"},{"value":[{"text":"numberOfCells","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1numberOfCells/fragments","op":"replace"},{"value":"NSGridColumn","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn/title","op":"replace"},{"value":[{"text":"NSGridColumn","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn/fragments","op":"replace"},{"value":[{"text":"NSGridColumn","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn/navigatorTitle","op":"replace"},{"value":"xPlacement","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1xPlacement/title","op":"replace"},{"value":[{"kind":"identifier","text":"xPlacement"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1xPlacement/fragments","op":"replace"},{"value":"hidden","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1isHidden/title","op":"replace"},{"value":[{"text":"hidden","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1isHidden/fragments","op":"replace"},{"value":"gridView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1gridView/title","op":"replace"},{"value":[{"kind":"identifier","text":"gridView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1gridView/fragments","op":"replace"},{"value":"trailingPadding","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1trailingPadding/title","op":"replace"},{"value":[{"text":"trailingPadding","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1trailingPadding/fragments","op":"replace"},{"value":"width","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1width/title","op":"replace"},{"value":[{"text":"width","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1width/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}