{
  "abstract": [
    {
      "text": "An identifier for the accessory in a session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/accessoryDiscoveryToken"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NINearbyAccessoryConfiguration(py)accessoryDiscoveryToken",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessoryDiscoveryToken"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NIDiscoveryToken",
        "text": "NIDiscoveryToken"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessoryDiscoveryToken"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "accessoryDiscoveryToken"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessoryDiscoveryToken"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIDiscoveryToken",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NIDiscoveryToken",
              "text": "NIDiscoveryToken"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/initiating-and-maintaining-a-session"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property refers to a specific peer accessory. To match ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/distance-676dm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " updates your app receives through a session with a peer using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", compare the argument object’s discovery token with the value of this property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Subsequent sessions with the same peer device produce a different value for this property. For user privacy, the system assigns a random number unique to the session that prevents the correlation of this property with a particular device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIDiscoveryToken": {
      "abstract": [
        {
          "text": "An object that uniquely identifies a peer that participates in an interaction session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIDiscoveryToken"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIDiscoveryToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIDiscoveryToken"
        }
      ],
      "role": "symbol",
      "title": "NIDiscoveryToken",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nidiscoverytoken"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration": {
      "abstract": [
        {
          "text": "A configuration that enables interaction between iPhone and third-party accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NINearbyAccessoryConfiguration"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyAccessoryConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NINearbyAccessoryConfiguration",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyaccessoryconfiguration"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/accessoryDiscoveryToken": {
      "abstract": [
        {
          "text": "An identifier for the accessory in a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryDiscoveryToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NIDiscoveryToken",
          "text": "NIDiscoveryToken"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/accessoryDiscoveryToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryDiscoveryToken"
        }
      ],
      "role": "symbol",
      "title": "accessoryDiscoveryToken",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyaccessoryconfiguration/accessorydiscoverytoken"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/distance-676dm": {
      "abstract": [
        {
          "text": "The distance from the user’s device to the peer device in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/distance-676dm",
      "kind": "symbol",
      "role": "symbol",
      "title": "distance",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/distance-676dm"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdate:)": {
      "abstract": [
        {
          "text": "Notifies you when the session updates nearby objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NISession",
          "text": "NISession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NINearbyObject",
          "text": "NINearbyObject"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didUpdateNearbyObjects:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didUpdate:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisessiondelegate/session(_:didupdate:)"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/initiating-and-maintaining-a-session": {
      "abstract": [
        {
          "text": "Measure the relative position of a nearby device and coach the user to sustain interaction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/initiating-and-maintaining-a-session",
      "kind": "article",
      "role": "article",
      "title": "Initiating and maintaining a session",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/initiating-and-maintaining-a-session"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "accessoryDiscoveryToken"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessoryDiscoveryToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIDiscoveryToken",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NIDiscoveryToken",
                    "text": "NIDiscoveryToken"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessoryDiscoveryToken"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration/title",
          "value": "NINearbyAccessoryConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyAccessoryConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyAccessoryConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdate:)/title",
          "value": "session:didUpdateNearbyObjects:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didUpdateNearbyObjects:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIDiscoveryToken/title",
          "value": "NIDiscoveryToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIDiscoveryToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIDiscoveryToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIDiscoveryToken/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NIDiscoveryToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration~1accessoryDiscoveryToken/title",
          "value": "accessoryDiscoveryToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration~1accessoryDiscoveryToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessoryDiscoveryToken"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/ninearbyaccessoryconfiguration/accessorydiscoverytoken"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/nearbyinteraction/ninearbyaccessoryconfiguration/accessorydiscoverytoken"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
