{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.nearbyinteraction/documentation/NearbyInteraction","doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessoryData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bluetoothPeerIdentifier"},{"kind":"text","text":" "},{"text":"identifier","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The accessory’s configuration data formatted to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"https://developer.apple.com/nearby-interaction"},{"text":".","type":"text"}]}],"name":"accessoryData"},{"content":[{"inlineContent":[{"text":"The accessory’s Bluetooth peer identifier. For more information, see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/CoreBluetooth/CBPeer"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/CoreBluetooth/CBPeer/identifier"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"identifier"}],"kind":"parameters"},{"kind":"mentions","mentions":["doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/initiating-and-maintaining-a-session"]},{"content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this initializer when your app interacts with a Bluetooth accessory that’s paired to the device to enable interaction while your app is in the background.","type":"text"}]}],"kind":"content"}],"sections":[],"identifier":{"url":"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/init(accessoryData:bluetoothPeerIdentifier:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/nearbyinteraction/ninearbyaccessoryconfiguration/init(accessorydata:bluetoothpeeridentifier:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/nearbyinteraction/ninearbyaccessoryconfiguration/init(accessorydata:bluetoothpeeridentifier:)"]}],"metadata":{"symbolKind":"init","role":"symbol","title":"init(accessoryData:bluetoothPeerIdentifier:)","platforms":[{"introducedAt":"16.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"16.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"16.0"}],"externalID":"c:objc(cs)NINearbyAccessoryConfiguration(im)initWithAccessoryData:bluetoothPeerIdentifier:error:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessoryData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bluetoothPeerIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"modules":[{"name":"Nearby Interaction"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAccessoryData:bluetoothPeerIdentifier:error:"}],"roleHeading":"Initializer"},"seeAlsoSections":[{"anchor":"Creating-a-configuration","identifiers":["doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/init(data:)"],"title":"Creating a configuration","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Creates a configuration for an accessory with the given Bluetooth peer identifier."}],"references":{"doc://com.apple.documentation/documentation/CoreBluetooth/CBPeer":{"title":"CBPeer","type":"topic","abstract":[{"type":"text","text":"An object that represents a remote device."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBPeer"}],"identifier":"doc://com.apple.documentation/documentation/CoreBluetooth/CBPeer","kind":"symbol","url":"/documentation/CoreBluetooth/CBPeer","role":"symbol"},"doc://com.externally.resolved.symbol/s:10Foundation4DataV":{"title":"Data","type":"topic","abstract":[{"type":"text","text":"A byte buffer in memory."}],"fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Data"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","kind":"symbol","url":"/documentation/foundation/data","role":"symbol"},"doc://com.apple.documentation/documentation/CoreBluetooth/CBPeer/identifier":{"title":"identifier","type":"topic","abstract":[{"type":"text","text":"The UUID associated with the peer."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"identifier":"doc://com.apple.documentation/documentation/CoreBluetooth/CBPeer/identifier","kind":"symbol","url":"/documentation/CoreBluetooth/CBPeer/identifier","role":"symbol"},"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/initiating-and-maintaining-a-session":{"abstract":[{"type":"text","text":"Measure the relative position of a nearby device and coach the user to sustain interaction."}],"identifier":"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/initiating-and-maintaining-a-session","role":"article","kind":"article","type":"topic","url":"/documentation/nearbyinteraction/initiating-and-maintaining-a-session","title":"Initiating and maintaining a session"},"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction":{"type":"topic","kind":"symbol","url":"/documentation/nearbyinteraction","role":"collection","title":"Nearby Interaction","identifier":"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction","abstract":[{"text":"Locate and interact with nearby devices using identifiers, distance, and direction.","type":"text"}]},"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/init(data:)":{"identifier":"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/init(data:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","kind":"symbol","title":"init(data:)","role":"symbol","abstract":[{"type":"text","text":"Creates a configuration for interaction between iPhone and third-party accessories."}],"url":"/documentation/nearbyinteraction/ninearbyaccessoryconfiguration/init(data:)","navigatorTitle":[{"kind":"identifier","text":"initWithData:error:"}]},"https://developer.apple.com/nearby-interaction":{"identifier":"https://developer.apple.com/nearby-interaction","titleInlineContent":[{"type":"text","text":"Ultra Wideband (UWB) third-party device specification"}],"type":"link","title":"Ultra Wideband (UWB) third-party device specification","url":"https://developer.apple.com/nearby-interaction"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","type":"topic","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NINearbyAccessoryConfiguration","kind":"identifier"}],"url":"/documentation/nearbyinteraction/ninearbyaccessoryconfiguration","role":"symbol","identifier":"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration","abstract":[{"text":"A configuration that enables interaction between iPhone and third-party accessories.","type":"text"}],"type":"topic","title":"NINearbyAccessoryConfiguration","navigatorTitle":[{"text":"NINearbyAccessoryConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/init(accessoryData:bluetoothPeerIdentifier:)":{"identifier":"doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/init(accessoryData:bluetoothPeerIdentifier:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessoryData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"text":"bluetoothPeerIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","kind":"symbol","title":"init(accessoryData:bluetoothPeerIdentifier:)","role":"symbol","abstract":[{"type":"text","text":"Creates a configuration for an accessory with the given Bluetooth peer identifier."}],"url":"/documentation/nearbyinteraction/ninearbyaccessoryconfiguration/init(accessorydata:bluetoothpeeridentifier:)","navigatorTitle":[{"kind":"identifier","text":"initWithAccessoryData:bluetoothPeerIdentifier:error:"}]},"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV":{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"UUID"}],"type":"topic","kind":"symbol","title":"UUID","role":"symbol","abstract":[{"type":"text","text":"A universally unique value to identify types, interfaces, and other items."}],"url":"/documentation/foundation/uuid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"16.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"introducedAt":"16.0","unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"16.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"initWithAccessoryData:bluetoothPeerIdentifier:error:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAccessoryData:bluetoothPeerIdentifier:error:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.nearbyinteraction/documentation/NearbyInteraction","doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Creating a configuration","anchor":"Creating-a-configuration","identifiers":["doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyAccessoryConfiguration/init(data:)"]}],"path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","watchOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithAccessoryData:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"accessoryData","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bluetoothPeerIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The accessory’s configuration data formatted to the "},{"type":"reference","identifier":"https://developer.apple.com/nearby-interaction","isActive":true},{"type":"text","text":"."}]}],"name":"accessoryData"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The accessory’s Bluetooth peer identifier. For more information, see "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/CoreBluetooth/CBPeer"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/CoreBluetooth/CBPeer/identifier"},{"type":"text","text":"."}]}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}],"name":"error"}]},"path":"/primaryContentSections/1"},{"value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBPeer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreBluetooth~1CBPeer/fragments"},{"value":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID"},{"kind":"text","text":" * "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":";"}],"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreBluetooth~1CBPeer~1identifier/fragments"},{"value":"initWithData:error:","op":"replace","path":"/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration~1init(data:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithData:error:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration~1init(data:)/fragments"},{"value":"NINearbyAccessoryConfiguration","op":"replace","path":"/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration/title"},{"value":[{"text":"NINearbyAccessoryConfiguration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration/fragments"},{"value":[{"text":"NINearbyAccessoryConfiguration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration/navigatorTitle"},{"value":"initWithAccessoryData:bluetoothPeerIdentifier:error:","op":"replace","path":"/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration~1init(accessoryData:bluetoothPeerIdentifier:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAccessoryData:bluetoothPeerIdentifier:error:"}],"op":"replace","path":"/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyAccessoryConfiguration~1init(accessoryData:bluetoothPeerIdentifier:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}