{
  "abstract": [
    {
      "text": "The app couldn’t perform the search because the media service is unavailable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/serviceUnavailable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INSearchForMediaMediaItemUnsupportedReason@INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "serviceUnavailable"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INSearchForMediaMediaItemUnsupportedReason.serviceUnavailable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "serviceUnavailable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason": {
      "abstract": [
        {
          "text": "Reasons the app can’t provide results for the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/cellularDataSettings": {
      "abstract": [
        {
          "text": "The cellular data settings don’t allow the user to search for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellularDataSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/cellularDataSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonCellularDataSettings"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.cellularDataSettings",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/cellulardatasettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/explicitContentSettings": {
      "abstract": [
        {
          "text": "The content settings don’t allow the user to search for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "explicitContentSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/explicitContentSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonExplicitContentSettings"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.explicitContentSettings",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/explicitcontentsettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/loginRequired": {
      "abstract": [
        {
          "text": "The user must log in to the app in order to search for media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loginRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/loginRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonLoginRequired"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.loginRequired",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/loginrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/regionRestriction": {
      "abstract": [
        {
          "text": "There are media items that match this request, but they aren’t available in the user’s geographic location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionRestriction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/regionRestriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonRegionRestriction"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.regionRestriction",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/regionrestriction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/restrictedContent": {
      "abstract": [
        {
          "text": "The media item is restricted content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/restrictedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonRestrictedContent"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.restrictedContent",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/restrictedcontent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/serviceUnavailable": {
      "abstract": [
        {
          "text": "The app couldn’t perform the search because the media service is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/serviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.serviceUnavailable",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/serviceunavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/subscriptionRequired": {
      "abstract": [
        {
          "text": "The user must have a subscription to the app’s service in order to search for media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/subscriptionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonSubscriptionRequired"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.subscriptionRequired",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/subscriptionrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/unsupportedMediaType": {
      "abstract": [
        {
          "text": "The media’s type is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedMediaType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/unsupportedMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonUnsupportedMediaType"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.unsupportedMediaType",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/unsupportedmediatype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Limitations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/loginRequired",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/subscriptionRequired",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/unsupportedMediaType",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/explicitContentSettings",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/cellularDataSettings",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/restrictedContent",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/regionRestriction"
      ],
      "title": "Limitations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Limitations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/loginRequired",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/subscriptionRequired",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/unsupportedMediaType",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/explicitContentSettings",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/cellularDataSettings",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/restrictedContent",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/regionRestriction"
              ],
              "title": "Limitations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1loginRequired/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonLoginRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1loginRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonLoginRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1cellularDataSettings/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonCellularDataSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1cellularDataSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonCellularDataSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1subscriptionRequired/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonSubscriptionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1subscriptionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonSubscriptionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1explicitContentSettings/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonExplicitContentSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1explicitContentSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonExplicitContentSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1serviceUnavailable/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1serviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1unsupportedMediaType/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonUnsupportedMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1unsupportedMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonUnsupportedMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1regionRestriction/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonRegionRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1regionRestriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonRegionRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason/title",
          "value": "INSearchForMediaMediaItemUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1restrictedContent/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonRestrictedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1restrictedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonRestrictedContent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchformediamediaitemunsupportedreason/serviceunavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insearchformediamediaitemunsupportedreason/serviceunavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
