{
  "abstract": [
    {
      "text": "XPC dictionary keys used by the ",
      "type": "text"
    },
    {
      "code": "interface_param",
      "type": "codeVoice"
    },
    {
      "text": " argument returned by the completion handler of the ",
      "type": "text"
    },
    {
      "code": "vmnet",
      "type": "codeVoice"
    },
    {
      "text": " function that describes the parameters that should be used to configure the network interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vmnet/documentation/vmnet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vmnet/documentation/vmnet/interface_param_xpc_dictionary_keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "vmnet"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "interface_param XPC Dictionary Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vmnet/documentation/vmnet": {
      "abstract": [
        {
          "text": "Connect with network interfaces to read and write packets on guest operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet",
      "kind": "symbol",
      "role": "collection",
      "title": "vmnet",
      "type": "topic",
      "url": "/documentation/vmnet"
    },
    "doc://com.apple.vmnet/documentation/vmnet/event_xpc_dictionary": {
      "abstract": [
        {
          "text": "XPC dictionary keys used by the ",
          "type": "text"
        },
        {
          "code": "event",
          "type": "codeVoice"
        },
        {
          "text": " value returned to the client in the ",
          "type": "text"
        },
        {
          "code": "handler",
          "type": "codeVoice"
        },
        {
          "text": " callback specified by the ",
          "type": "text"
        },
        {
          "code": "vmnet",
          "type": "codeVoice"
        },
        {
          "text": " function that provides information about the callback event.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/event_xpc_dictionary",
      "kind": "article",
      "role": "collectionGroup",
      "title": "event XPC Dictionary",
      "type": "topic",
      "url": "/documentation/vmnet/event_xpc_dictionary"
    },
    "doc://com.apple.vmnet/documentation/vmnet/interface_desc_xpc_dictionary_keys": {
      "abstract": [
        {
          "text": "XPC dictionary keys supported by the ",
          "type": "text"
        },
        {
          "code": "interface_desc",
          "type": "codeVoice"
        },
        {
          "text": " parameter passed to the ",
          "type": "text"
        },
        {
          "code": "vmnet",
          "type": "codeVoice"
        },
        {
          "text": " function to describe the parameters of the network interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/interface_desc_xpc_dictionary_keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "interface_desc XPC Dictionary Keys",
      "type": "topic",
      "url": "/documentation/vmnet/interface_desc_xpc_dictionary_keys"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_mac_address_key": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_mac_address_key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_mac_address_key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_mac_address_key"
        }
      ],
      "role": "symbol",
      "title": "vmnet_mac_address_key",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_mac_address_key"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_max_packet_size_key": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_max_packet_size_key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_max_packet_size_key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_max_packet_size_key"
        }
      ],
      "role": "symbol",
      "title": "vmnet_max_packet_size_key",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_max_packet_size_key"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_mtu_key": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_mtu_key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_mtu_key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_mtu_key"
        }
      ],
      "role": "symbol",
      "title": "vmnet_mtu_key",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_mtu_key"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/interface_desc_xpc_dictionary_keys",
        "doc://com.apple.vmnet/documentation/vmnet/event_xpc_dictionary"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_mac_address_key",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_mtu_key",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_max_packet_size_key"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_mac_address_key",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_mtu_key",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_max_packet_size_key"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/interface_desc_xpc_dictionary_keys",
                "doc://com.apple.vmnet/documentation/vmnet/event_xpc_dictionary"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_max_packet_size_key/title",
          "value": "vmnet_max_packet_size_key"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_max_packet_size_key/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_max_packet_size_key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_mac_address_key/title",
          "value": "vmnet_mac_address_key"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_mac_address_key/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_mac_address_key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_mtu_key/title",
          "value": "vmnet_mtu_key"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_mtu_key/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_mtu_key"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vmnet/interface_param_xpc_dictionary_keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vmnet/interface_param_xpc_dictionary_keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
