{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vmnet/documentation/vmnet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vmnet/documentation/vmnet/vmnet_data_types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "vmnet"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "vmnet Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vmnet/documentation/vmnet": {
      "abstract": [
        {
          "text": "Connect with network interfaces to read and write packets on guest operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet",
      "kind": "symbol",
      "role": "collection",
      "title": "vmnet",
      "type": "topic",
      "url": "/documentation/vmnet"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_constants": {
      "abstract": [],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vmnet Constants",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_constants"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_functions": {
      "abstract": [],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vmnet Functions",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_functions"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_completion_handler_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_completion_handler_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_completion_handler_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_completion_handler_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_event_callback_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_event_callback_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_event_callback_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_event_callback_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_event_callback_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_event_callback_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_get_ip_port_forwarding_rules_handler_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_get_port_forwarding_rules_handler_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface_completion_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_start_interface_completion_handler_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface_completion_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_start_interface_completion_handler_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_start_interface_completion_handler_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_start_interface_completion_handler_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_constants",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-types",
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_event_callback_t",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface_completion_handler_t"
      ],
      "title": "Data types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-types",
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_event_callback_t",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface_completion_handler_t"
              ],
              "title": "Data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_constants",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules_handler_t/title",
          "value": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_completion_handler_t/title",
          "value": "vmnet_interface_completion_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_completion_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_completion_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_completion_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_completion_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_event_callback_t/title",
          "value": "vmnet_interface_event_callback_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_event_callback_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_event_callback_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_event_callback_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_event_callback_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_start_interface_completion_handler_t/title",
          "value": "vmnet_start_interface_completion_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_start_interface_completion_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_start_interface_completion_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_start_interface_completion_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_start_interface_completion_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules_handler_t/title",
          "value": "vmnet_interface_get_port_forwarding_rules_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vmnet/vmnet_data_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vmnet/vmnet_data_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
