{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vmnet/documentation/vmnet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@vmnet_interface_get_ip_port_forwarding_rules_handler_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
      }
    ],
    "modules": [
      {
        "name": "vmnet"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@xpc_object_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vmnet/documentation/vmnet": {
      "abstract": [
        {
          "text": "Connect with network interfaces to read and write packets on guest operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet",
      "kind": "symbol",
      "role": "collection",
      "title": "vmnet",
      "type": "topic",
      "url": "/documentation/vmnet"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_completion_handler_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_completion_handler_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_completion_handler_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_completion_handler_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_event_callback_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_event_callback_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_event_callback_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_event_callback_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_event_callback_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_event_callback_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_get_ip_port_forwarding_rules_handler_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_get_port_forwarding_rules_handler_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface_completion_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_start_interface_completion_handler_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface_completion_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_start_interface_completion_handler_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_start_interface_completion_handler_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_start_interface_completion_handler_t"
    },
    "doc://com.externally.resolved.symbol/c:@T@xpc_object_t": {
      "abstract": [
        {
          "text": "A type that can describe all XPC objects, including dictionaries, arrays, strings, and numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": " = any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@xpc_object_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_object_t",
      "type": "topic",
      "url": "/documentation/XPC/xpc_object_t"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_event_callback_t",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface_completion_handler_t"
      ],
      "title": "Data types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vmnet/documentation/vmnet"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_event_callback_t",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules_handler_t",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface_completion_handler_t"
              ],
              "title": "Data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*Q$objc(cs)NSObjectobjc(pl)OS_xpc_object)",
                    "text": "void (^)(NSObject<OS_xpc_object> *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules_handler_t/title",
          "value": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_start_interface_completion_handler_t/title",
          "value": "vmnet_start_interface_completion_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_start_interface_completion_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_start_interface_completion_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_start_interface_completion_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_start_interface_completion_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@xpc_object_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_xpc_object",
              "text": "NSObject<OS_xpc_object>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_event_callback_t/title",
          "value": "vmnet_interface_event_callback_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_event_callback_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_event_callback_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_event_callback_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_event_callback_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules_handler_t/title",
          "value": "vmnet_interface_get_port_forwarding_rules_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_completion_handler_t/title",
          "value": "vmnet_interface_completion_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_completion_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_completion_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_completion_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_completion_handler_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules_handler_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
