{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vmnet/documentation/vmnet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vmnet/documentation/vmnet/vmnet_copy_shared_interface_list()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vmnet_copy_shared_interface_list",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vmnet_copy_shared_interface_list"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@xpc_object_t",
        "text": "xpc_object_t"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "vmnet"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vmnet_copy_shared_interface_list"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vmnet_copy_shared_interface_list()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vmnet_copy_shared_interface_list"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@xpc_object_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vmnet/documentation/vmnet": {
      "abstract": [
        {
          "text": "Connect with network interfaces to read and write packets on guest operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet",
      "kind": "symbol",
      "role": "collection",
      "title": "vmnet",
      "type": "topic",
      "url": "/documentation/vmnet"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_copy_shared_interface_list()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_copy_shared_interface_list"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_copy_shared_interface_list()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_copy_shared_interface_list"
        }
      ],
      "role": "symbol",
      "title": "vmnet_copy_shared_interface_list()",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_copy_shared_interface_list()"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_add_ip_port_forwarding_rule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
          "text": "vmnet_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_add_ip_port_forwarding_rule"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_add_port_forwarding_rule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@in_addr",
          "text": "in_addr"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
          "text": "vmnet_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_add_port_forwarding_rule"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_ip_port_forwarding_rules"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_get_ip_port_forwarding_rules_handler_t",
          "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_ip_port_forwarding_rules"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_port_forwarding_rules"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_get_port_forwarding_rules_handler_t",
          "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_port_forwarding_rules"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_get_port_forwarding_rules(_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_remove_ip_port_forwarding_rule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
          "text": "vmnet_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_remove_ip_port_forwarding_rule"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_remove_port_forwarding_rule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
          "text": "vmnet_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_remove_port_forwarding_rule"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_ip_port_forwarding_rule_get_details"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_ip_port_forwarding_rule_get_details"
        }
      ],
      "role": "symbol",
      "title": "vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_port_forwarding_rule_get_details"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@in_addr",
          "text": "in_addr"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_port_forwarding_rule_get_details"
        }
      ],
      "role": "symbol",
      "title": "vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@xpc_object_t": {
      "abstract": [
        {
          "text": "A type that can describe all XPC objects, including dictionaries, arrays, strings, and numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": " = any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_xpc_object",
          "text": "OS_xpc_object"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@xpc_object_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_object_t",
      "type": "topic",
      "url": "/documentation/XPC/xpc_object_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vmnet_copy_shared_interface_list"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_copy_shared_interface_list"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vmnet/documentation/vmnet"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@xpc_object_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@xpc_object_t",
                    "text": "xpc_object_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vmnet_copy_shared_interface_list"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules(_:_:)/title",
          "value": "vmnet_interface_get_port_forwarding_rules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_port_forwarding_rules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_copy_shared_interface_list()/title",
          "value": "vmnet_copy_shared_interface_list"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_copy_shared_interface_list()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_copy_shared_interface_list"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)/title",
          "value": "vmnet_interface_remove_port_forwarding_rule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_remove_port_forwarding_rule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)/title",
          "value": "vmnet_interface_remove_ip_port_forwarding_rule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_remove_ip_port_forwarding_rule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)/title",
          "value": "vmnet_interface_get_ip_port_forwarding_rules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_ip_port_forwarding_rules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)/title",
          "value": "vmnet_ip_port_forwarding_rule_get_details"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_ip_port_forwarding_rule_get_details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@xpc_object_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_xpc_object",
              "text": "NSObject<OS_xpc_object>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)/title",
          "value": "vmnet_interface_add_port_forwarding_rule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_add_port_forwarding_rule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)/title",
          "value": "vmnet_interface_add_ip_port_forwarding_rule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_add_ip_port_forwarding_rule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)/title",
          "value": "vmnet_port_forwarding_rule_get_details"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_port_forwarding_rule_get_details"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vmnet/vmnet_copy_shared_interface_list()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vmnet/vmnet_copy_shared_interface_list()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
