{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vmnet/documentation/vmnet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vmnet/documentation/vmnet/vmnet_functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "vmnet"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "vmnet Functions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vmnet/documentation/vmnet": {
      "abstract": [
        {
          "text": "Connect with network interfaces to read and write packets on guest operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet",
      "kind": "symbol",
      "role": "collection",
      "title": "vmnet",
      "type": "topic",
      "url": "/documentation/vmnet"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_constants": {
      "abstract": [],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vmnet Constants",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_constants"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_copy_shared_interface_list()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_copy_shared_interface_list"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_copy_shared_interface_list()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_copy_shared_interface_list"
        }
      ],
      "role": "symbol",
      "title": "vmnet_copy_shared_interface_list()",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_copy_shared_interface_list()"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_data_types": {
      "abstract": [],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_data_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vmnet Data Types",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_data_types"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_add_ip_port_forwarding_rule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
          "text": "vmnet_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_add_ip_port_forwarding_rule"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_add_port_forwarding_rule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@in_addr",
          "text": "in_addr"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
          "text": "vmnet_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_add_port_forwarding_rule"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_ip_port_forwarding_rules"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_get_ip_port_forwarding_rules_handler_t",
          "text": "vmnet_interface_get_ip_port_forwarding_rules_handler_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_ip_port_forwarding_rules"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_port_forwarding_rules"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_get_port_forwarding_rules_handler_t",
          "text": "vmnet_interface_get_port_forwarding_rules_handler_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_get_port_forwarding_rules"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_get_port_forwarding_rules(_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_remove_ip_port_forwarding_rule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
          "text": "vmnet_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_remove_ip_port_forwarding_rule"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_remove_port_forwarding_rule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
          "text": "vmnet_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_remove_port_forwarding_rule"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_ip_port_forwarding_rule_get_details"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_ip_port_forwarding_rule_get_details"
        }
      ],
      "role": "symbol",
      "title": "vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_port_forwarding_rule_get_details"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@in_addr",
          "text": "in_addr"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_port_forwarding_rule_get_details"
        }
      ],
      "role": "symbol",
      "title": "vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_constants",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_data_types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_copy_shared_interface_list()",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_copy_shared_interface_list()",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_get_port_forwarding_rules(_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_constants",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_data_types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)/title",
          "value": "vmnet_interface_get_ip_port_forwarding_rules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_ip_port_forwarding_rules(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_ip_port_forwarding_rules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)/title",
          "value": "vmnet_interface_remove_ip_port_forwarding_rule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_remove_ip_port_forwarding_rule(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_remove_ip_port_forwarding_rule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules(_:_:)/title",
          "value": "vmnet_interface_get_port_forwarding_rules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_get_port_forwarding_rules(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_get_port_forwarding_rules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)/title",
          "value": "vmnet_ip_port_forwarding_rule_get_details"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_ip_port_forwarding_rule_get_details(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_ip_port_forwarding_rule_get_details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)/title",
          "value": "vmnet_interface_remove_port_forwarding_rule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_remove_port_forwarding_rule(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_remove_port_forwarding_rule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)/title",
          "value": "vmnet_port_forwarding_rule_get_details"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_port_forwarding_rule_get_details(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_port_forwarding_rule_get_details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_copy_shared_interface_list()/title",
          "value": "vmnet_copy_shared_interface_list"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_copy_shared_interface_list()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_copy_shared_interface_list"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)/title",
          "value": "vmnet_interface_add_port_forwarding_rule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_add_port_forwarding_rule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)/title",
          "value": "vmnet_interface_add_ip_port_forwarding_rule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_add_ip_port_forwarding_rule(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_add_ip_port_forwarding_rule"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vmnet/vmnet_functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vmnet/vmnet_functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
