{
  "abstract": [
    {
      "text": "Values returned by functions in the vmnet Framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vmnet/documentation/vmnet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@vmnet_return_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vmnet_return_t"
      }
    ],
    "modules": [
      {
        "name": "vmnet"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vmnet_return_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "vmnet_return_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vmnet_return_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vmnet/documentation/vmnet": {
      "abstract": [
        {
          "text": "Connect with network interfaces to read and write packets on guest operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet",
      "kind": "symbol",
      "role": "collection",
      "title": "vmnet",
      "type": "topic",
      "url": "/documentation/vmnet"
    },
    "doc://com.apple.vmnet/documentation/vmnet/interface_event_t": {
      "abstract": [
        {
          "text": "Interface event types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interface_event_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/interface_event_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interface_event_t"
        }
      ],
      "role": "symbol",
      "title": "interface_event_t",
      "type": "topic",
      "url": "/documentation/vmnet/interface_event_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/interface_ref": {
      "abstract": [
        {
          "text": "A virtual network interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interface_ref"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/interface_ref",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interface_ref"
        }
      ],
      "role": "symbol",
      "title": "interface_ref",
      "type": "topic",
      "url": "/documentation/vmnet/interface_ref"
    },
    "doc://com.apple.vmnet/documentation/vmnet/operating_modes_t": {
      "abstract": [
        {
          "text": "The operating modes for an interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operating_modes_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/operating_modes_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "operating_modes_t"
        }
      ],
      "role": "symbol",
      "title": "operating_modes_t",
      "type": "topic",
      "url": "/documentation/vmnet/operating_modes_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t": {
      "abstract": [
        {
          "text": "Values returned by functions in the vmnet Framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_return_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_BUFFER_EXHAUSTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_BUFFER_EXHAUSTED"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_BUFFER_EXHAUSTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_BUFFER_EXHAUSTED"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_BUFFER_EXHAUSTED",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_buffer_exhausted"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_FAILURE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_FAILURE"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_FAILURE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_FAILURE"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_FAILURE",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_failure"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ACCESS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_INVALID_ACCESS"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ACCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_INVALID_ACCESS"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_INVALID_ACCESS",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_invalid_access"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ARGUMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_INVALID_ARGUMENT"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ARGUMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_INVALID_ARGUMENT"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_INVALID_ARGUMENT",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_invalid_argument"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_MEM_FAILURE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_MEM_FAILURE"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_MEM_FAILURE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_MEM_FAILURE"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_MEM_FAILURE",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_mem_failure"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_NOT_AUTHORIZED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_NOT_AUTHORIZED"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_NOT_AUTHORIZED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_NOT_AUTHORIZED"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_NOT_AUTHORIZED",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_not_authorized"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_PACKET_TOO_BIG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_PACKET_TOO_BIG"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_PACKET_TOO_BIG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_PACKET_TOO_BIG"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_PACKET_TOO_BIG",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_packet_too_big"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SETUP_INCOMPLETE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_SETUP_INCOMPLETE"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SETUP_INCOMPLETE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_SETUP_INCOMPLETE"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_SETUP_INCOMPLETE",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_setup_incomplete"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SHARING_SERVICE_BUSY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_SHARING_SERVICE_BUSY"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SHARING_SERVICE_BUSY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_SHARING_SERVICE_BUSY"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_SHARING_SERVICE_BUSY",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_sharing_service_busy"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SUCCESS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_SUCCESS"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SUCCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_SUCCESS"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_SUCCESS",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_success"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_TOO_MANY_PACKETS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_TOO_MANY_PACKETS"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_TOO_MANY_PACKETS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_TOO_MANY_PACKETS"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_TOO_MANY_PACKETS",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_too_many_packets"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/init(rawvalue:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc": {
      "abstract": [
        {
          "text": "Describes a packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmpktdesc"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmpktdesc"
        }
      ],
      "role": "symbol",
      "title": "vmpktdesc",
      "type": "topic",
      "url": "/documentation/vmnet/vmpktdesc"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc",
        "doc://com.apple.vmnet/documentation/vmnet/interface_ref",
        "doc://com.apple.vmnet/documentation/vmnet/interface_event_t",
        "doc://com.apple.vmnet/documentation/vmnet/operating_modes_t"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SUCCESS",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_FAILURE",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_MEM_FAILURE",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ARGUMENT",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SETUP_INCOMPLETE",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ACCESS",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_PACKET_TOO_BIG",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_BUFFER_EXHAUSTED",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_TOO_MANY_PACKETS"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_NOT_AUTHORIZED",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SHARING_SERVICE_BUSY"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vmnet_return_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_return_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_return_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vmnet/documentation/vmnet"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SUCCESS",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_FAILURE",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_MEM_FAILURE",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ARGUMENT",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SETUP_INCOMPLETE",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ACCESS",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_PACKET_TOO_BIG",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_BUFFER_EXHAUSTED",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_TOO_MANY_PACKETS"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_NOT_AUTHORIZED",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SHARING_SERVICE_BUSY"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc",
                "doc://com.apple.vmnet/documentation/vmnet/interface_ref",
                "doc://com.apple.vmnet/documentation/vmnet/interface_event_t",
                "doc://com.apple.vmnet/documentation/vmnet/operating_modes_t"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vmnet_return_t"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_NOT_AUTHORIZED/title",
          "value": "VMNET_NOT_AUTHORIZED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_NOT_AUTHORIZED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_NOT_AUTHORIZED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SHARING_SERVICE_BUSY/title",
          "value": "VMNET_SHARING_SERVICE_BUSY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SHARING_SERVICE_BUSY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_SHARING_SERVICE_BUSY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_TOO_MANY_PACKETS/title",
          "value": "VMNET_TOO_MANY_PACKETS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_TOO_MANY_PACKETS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_TOO_MANY_PACKETS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_INVALID_ACCESS/title",
          "value": "VMNET_INVALID_ACCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_INVALID_ACCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_INVALID_ACCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1interface_ref/title",
          "value": "interface_ref"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1interface_ref/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interface_ref"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1interface_ref/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "interface_ref"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t/title",
          "value": "vmnet_return_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_return_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_return_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_MEM_FAILURE/title",
          "value": "VMNET_MEM_FAILURE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_MEM_FAILURE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_MEM_FAILURE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_BUFFER_EXHAUSTED/title",
          "value": "VMNET_BUFFER_EXHAUSTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_BUFFER_EXHAUSTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_BUFFER_EXHAUSTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_INVALID_ARGUMENT/title",
          "value": "VMNET_INVALID_ARGUMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_INVALID_ARGUMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_INVALID_ARGUMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SUCCESS/title",
          "value": "VMNET_SUCCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SUCCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_SUCCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1operating_modes_t/title",
          "value": "operating_modes_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1operating_modes_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "operating_modes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1operating_modes_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "operating_modes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_FAILURE/title",
          "value": "VMNET_FAILURE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_FAILURE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_FAILURE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc/title",
          "value": "vmpktdesc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmpktdesc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmpktdesc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1interface_event_t/title",
          "value": "interface_event_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1interface_event_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interface_event_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1interface_event_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "interface_event_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_PACKET_TOO_BIG/title",
          "value": "VMNET_PACKET_TOO_BIG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_PACKET_TOO_BIG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_PACKET_TOO_BIG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SETUP_INCOMPLETE/title",
          "value": "VMNET_SETUP_INCOMPLETE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SETUP_INCOMPLETE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_SETUP_INCOMPLETE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vmnet/vmnet_return_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vmnet/vmnet_return_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
