{
  "abstract": [
    {
      "text": "Stops the interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vmnet/documentation/vmnet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vmnet/documentation/vmnet/vmnet_stop_interface(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vmnet_stop_interface",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vmnet_stop_interface"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@interface_ref",
        "text": "interface_ref"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@dispatch_queue_t",
        "text": "dispatch_queue_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
        "text": "vmnet_interface_completion_handler_t"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@vmnet_return_t",
        "text": "vmnet_return_t"
      }
    ],
    "modules": [
      {
        "name": "vmnet"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vmnet_stop_interface"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vmnet_stop_interface(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vmnet_stop_interface"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "interface"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vmnet/documentation/vmnet/interface_ref",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@interface_ref",
              "text": "interface_ref"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
              "text": "vmnet_interface_completion_handler_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@vmnet_return_t",
              "text": "vmnet_return_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The interface reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "interface"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The queue on which the handler is scheduled.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "queue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block to be executed after interface is started.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "status: ",
                          "type": "text"
                        },
                        {
                          "code": "vmnet",
                          "type": "codeVoice"
                        },
                        {
                          "text": " on success, or ",
                          "type": "text"
                        },
                        {
                          "code": "vmnet",
                          "type": "codeVoice"
                        },
                        {
                          "text": " on failure.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Return-Value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "vmnet",
              "type": "codeVoice"
            },
            {
              "text": " on success, or an error code on failure. See ",
              "type": "text"
            },
            {
              "code": "vmnet",
              "type": "codeVoice"
            },
            {
              "text": " for possible values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After this function is called, any further calls to read/write packets on ",
              "type": "text"
            },
            {
              "code": "interface",
              "type": "codeVoice"
            },
            {
              "text": " will fail.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vmnet/documentation/vmnet": {
      "abstract": [
        {
          "text": "Connect with network interfaces to read and write packets on guest operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet",
      "kind": "symbol",
      "role": "collection",
      "title": "vmnet",
      "type": "topic",
      "url": "/documentation/vmnet"
    },
    "doc://com.apple.vmnet/documentation/vmnet/interface_ref": {
      "abstract": [
        {
          "text": "A virtual network interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interface_ref"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/interface_ref",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interface_ref"
        }
      ],
      "role": "symbol",
      "title": "interface_ref",
      "type": "topic",
      "url": "/documentation/vmnet/interface_ref"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_completion_handler_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_completion_handler_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_completion_handler_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_completion_handler_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_set_event_callback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Schedules a callback to be executed when events for the specified interface are received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_interface_set_event_callback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@interface_event_t",
          "text": "interface_event_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_event_callback_t",
          "text": "vmnet_interface_event_callback_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_set_event_callback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_interface_set_event_callback"
        }
      ],
      "role": "symbol",
      "title": "vmnet_interface_set_event_callback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_interface_set_event_callback(_:_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t": {
      "abstract": [
        {
          "text": "Values returned by functions in the vmnet Framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_return_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface(_:_:_:)": {
      "abstract": [
        {
          "text": "Starts host or shared mode on an interface with a specified configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_start_interface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_start_interface_completion_handler_t",
          "text": "vmnet_start_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_start_interface"
        }
      ],
      "role": "symbol",
      "title": "vmnet_start_interface(_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_start_interface(_:_:_:)"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_stop_interface(_:_:_:)": {
      "abstract": [
        {
          "text": "Stops the interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_stop_interface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@interface_ref",
          "text": "interface_ref"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
          "text": "vmnet_interface_completion_handler_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@vmnet_return_t",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_stop_interface(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_stop_interface"
        }
      ],
      "role": "symbol",
      "title": "vmnet_stop_interface(_:_:_:)",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_stop_interface(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/Dispatch/dispatch_queue_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Starting-and-Stopping-Interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface(_:_:_:)",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_set_event_callback(_:_:_:_:)"
      ],
      "title": "Starting and Stopping Interfaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vmnet_stop_interface"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_stop_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vmnet/documentation/vmnet"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Starting-and-Stopping-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_start_interface(_:_:_:)",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_set_event_callback(_:_:_:_:)"
              ],
              "title": "Starting and Stopping Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@vmnet_return_t",
                    "text": "vmnet_return_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vmnet_stop_interface"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.vmnet/documentation/vmnet/interface_ref",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@interface_ref",
                    "text": "interface_ref"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "interface"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@dispatch_queue_t",
                    "text": "dispatch_queue_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queue"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_interface_completion_handler_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vmnet_interface_completion_handler_t",
                    "text": "vmnet_interface_completion_handler_t"
                  },
                  {
                    "kind": "internalParam",
                    "text": "handler"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The interface reference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "interface"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The queue on which the handler is scheduled.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "queue"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block to be executed after interface is started.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "status: ",
                                "type": "text"
                              },
                              {
                                "code": "vmnet",
                                "type": "codeVoice"
                              },
                              {
                                "text": " on success, or ",
                                "type": "text"
                              },
                              {
                                "code": "vmnet",
                                "type": "codeVoice"
                              },
                              {
                                "text": " on failure.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  }
                ],
                "name": "handler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t/title",
          "value": "vmnet_return_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_return_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_return_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_stop_interface(_:_:_:)/title",
          "value": "vmnet_stop_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_stop_interface(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_stop_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue",
              "text": "NSObject<OS_dispatch_queue>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_completion_handler_t/title",
          "value": "vmnet_interface_completion_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_completion_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_completion_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_completion_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_completion_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1interface_ref/title",
          "value": "interface_ref"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1interface_ref/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interface_ref"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1interface_ref/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "interface_ref"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_set_event_callback(_:_:_:_:)/title",
          "value": "vmnet_interface_set_event_callback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_interface_set_event_callback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_interface_set_event_callback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_start_interface(_:_:_:)/title",
          "value": "vmnet_start_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_start_interface(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_start_interface"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vmnet/vmnet_stop_interface(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vmnet/vmnet_stop_interface(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
