{
  "abstract": [
    {
      "text": "A constant that indicates ITF-14 symbology.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/itf14-9mbkq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@VNBarcodeSymbologyITF14",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "itf14"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VNBarcodeSymbology",
        "text": "VNBarcodeSymbology"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNBarcodeSymbologyITF14"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "itf14"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "itf14"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VNBarcodeSymbology",
              "text": "VNBarcodeSymbology"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology": {
      "abstract": [
        {
          "text": "The barcode symbologies that the framework detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbology"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeSymbology",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/aztec-s3va": {
      "abstract": [
        {
          "text": "A constant that indicates Aztec symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aztec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/aztec-s3va",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyAztec"
        }
      ],
      "role": "symbol",
      "title": "aztec",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/aztec-s3va"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/codabar": {
      "abstract": [
        {
          "text": "A constant that indicates Codabar symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codabar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/codabar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCodabar"
        }
      ],
      "role": "symbol",
      "title": "codabar",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/codabar"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code128-1lkm2": {
      "abstract": [
        {
          "text": "A constant that indicates Code 128 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code128"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code128-1lkm2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode128"
        }
      ],
      "role": "symbol",
      "title": "code128",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code128-1lkm2"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39-2ggrb": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code39"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39-2ggrb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode39"
        }
      ],
      "role": "symbol",
      "title": "code39",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39-2ggrb"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39Checksum-3jdl6": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 symbology with a checksum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code39Checksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39Checksum-3jdl6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode39Checksum"
        }
      ],
      "role": "symbol",
      "title": "code39Checksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39checksum-3jdl6"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCII-942jj": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 Full ASCII symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code39FullASCII"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCII-942jj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode39FullASCII"
        }
      ],
      "role": "symbol",
      "title": "code39FullASCII",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39fullascii-942jj"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCIIChecksum-6700": {
      "abstract": [
        {
          "text": "A constant that indicates Code 39 Full ASCII symbology with a checksum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code39FullASCIIChecksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCIIChecksum-6700",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode39FullASCIIChecksum"
        }
      ],
      "role": "symbol",
      "title": "code39FullASCIIChecksum",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code39fullasciichecksum-6700"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93-2geph": {
      "abstract": [
        {
          "text": "A constant that indicates Code 93 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code93"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93-2geph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode93"
        }
      ],
      "role": "symbol",
      "title": "code93",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code93-2geph"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93i-t5q5": {
      "abstract": [
        {
          "text": "A constant that indicates Code 93i symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code93i"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93i-t5q5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyCode93i"
        }
      ],
      "role": "symbol",
      "title": "code93i",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/code93i-t5q5"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/dataMatrix-6tg7m": {
      "abstract": [
        {
          "text": "A constant that indicates Data Matrix symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/dataMatrix-6tg7m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyDataMatrix"
        }
      ],
      "role": "symbol",
      "title": "dataMatrix",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/datamatrix-6tg7m"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean13-7gb2d": {
      "abstract": [
        {
          "text": "A constant that indicates EAN-13 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ean13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean13-7gb2d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyEAN13"
        }
      ],
      "role": "symbol",
      "title": "ean13",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/ean13-7gb2d"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean8-9qg0n": {
      "abstract": [
        {
          "text": "A constant that indicates EAN-8 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ean8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean8-9qg0n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyEAN8"
        }
      ],
      "role": "symbol",
      "title": "ean8",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/ean8-9qg0n"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBar": {
      "abstract": [
        {
          "text": "A constant that indicates GS1 DataBar symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gs1DataBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyGS1DataBar"
        }
      ],
      "role": "symbol",
      "title": "gs1DataBar",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/gs1databar"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarExpanded": {
      "abstract": [
        {
          "text": "A constant that indicates GS1 DataBar Expanded symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gs1DataBarExpanded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarExpanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyGS1DataBarExpanded"
        }
      ],
      "role": "symbol",
      "title": "gs1DataBarExpanded",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/gs1databarexpanded"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarLimited": {
      "abstract": [
        {
          "text": "A constant that indicates GS1 DataBar Limited symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gs1DataBarLimited"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarLimited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyGS1DataBarLimited"
        }
      ],
      "role": "symbol",
      "title": "gs1DataBarLimited",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/gs1databarlimited"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/itf14-9mbkq": {
      "abstract": [
        {
          "text": "A constant that indicates ITF-14 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itf14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/itf14-9mbkq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbologyITF14"
        }
      ],
      "role": "symbol",
      "title": "itf14",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology/itf14-9mbkq"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supported-Symbologies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/aztec-s3va",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/codabar",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39-2ggrb",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39Checksum-3jdl6",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCII-942jj",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCIIChecksum-6700",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93-2geph",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93i-t5q5",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code128-1lkm2",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/dataMatrix-6tg7m",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean8-9qg0n",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean13-7gb2d",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBar",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarExpanded",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarLimited"
      ],
      "title": "Supported Symbologies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNBarcodeSymbologyITF14"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyITF14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supported-Symbologies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/aztec-s3va",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/codabar",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39-2ggrb",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39Checksum-3jdl6",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCII-942jj",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code39FullASCIIChecksum-6700",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93-2geph",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code93i-t5q5",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/code128-1lkm2",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/dataMatrix-6tg7m",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean8-9qg0n",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/ean13-7gb2d",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBar",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarExpanded",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology/gs1DataBarLimited"
              ],
              "title": "Supported Symbologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VNBarcodeSymbology",
                    "text": "VNBarcodeSymbology"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNBarcodeSymbologyITF14"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1ean8-9qg0n/title",
          "value": "VNBarcodeSymbologyEAN8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1ean8-9qg0n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyEAN8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBarExpanded/title",
          "value": "VNBarcodeSymbologyGS1DataBarExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBarExpanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyGS1DataBarExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/title",
          "value": "VNBarcodeSymbology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39-2ggrb/title",
          "value": "VNBarcodeSymbologyCode39"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39-2ggrb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode39"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39Checksum-3jdl6/title",
          "value": "VNBarcodeSymbologyCode39Checksum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39Checksum-3jdl6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode39Checksum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1itf14-9mbkq/title",
          "value": "VNBarcodeSymbologyITF14"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1itf14-9mbkq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyITF14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39FullASCII-942jj/title",
          "value": "VNBarcodeSymbologyCode39FullASCII"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39FullASCII-942jj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode39FullASCII"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1aztec-s3va/title",
          "value": "VNBarcodeSymbologyAztec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1aztec-s3va/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyAztec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code128-1lkm2/title",
          "value": "VNBarcodeSymbologyCode128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code128-1lkm2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1codabar/title",
          "value": "VNBarcodeSymbologyCodabar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1codabar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCodabar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1dataMatrix-6tg7m/title",
          "value": "VNBarcodeSymbologyDataMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1dataMatrix-6tg7m/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyDataMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code93i-t5q5/title",
          "value": "VNBarcodeSymbologyCode93i"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code93i-t5q5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode93i"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBar/title",
          "value": "VNBarcodeSymbologyGS1DataBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyGS1DataBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code93-2geph/title",
          "value": "VNBarcodeSymbologyCode93"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code93-2geph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode93"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1ean13-7gb2d/title",
          "value": "VNBarcodeSymbologyEAN13"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1ean13-7gb2d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyEAN13"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39FullASCIIChecksum-6700/title",
          "value": "VNBarcodeSymbologyCode39FullASCIIChecksum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1code39FullASCIIChecksum-6700/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyCode39FullASCIIChecksum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBarLimited/title",
          "value": "VNBarcodeSymbologyGS1DataBarLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology~1gs1DataBarLimited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbologyGS1DataBarLimited"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnbarcodesymbology/itf14-9mbkq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnbarcodesymbology/itf14-9mbkq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
